### ISSUE TITLE
Upgrade the version of Node for central-services-database

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#100]
**Goal**:
As a developer I would like to upgrade the version of Node of central-services-database so that we can make use of new features and upgrade the dependencies for performance and stability

**Tasks**:
- [x] update dependencies
- [x] check unit tests work
- [x] add missing dependencies
- [x] ensure that api works when used as a dependency
- [x] update circleci config for new node version

**Acceptance Criteria**:
- [x] Upgraded node from 6.5.0 to 8.9.4 LTS
- [x] Ensure NPM dependencies are upgraded and compiles
- [x] Ensure all included tests pass

**Dependencies**:
- None currently
