### ISSUE TITLE
Create Configurable IaC to easily deploy Mojaloop on Kubernetes

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1004]
## **Goal**:
As an OSS Maintainer
I want to automate the deployment of a full Mojaloop environment
to enable performance testing and easy on-boarding and deployment of mojaloop

**Tasks**:
- [ ] Possibly merge the @lewisdaly 's [Moja-Box](https://github.com/vessels-tech/moja-box) tool with ModusBox's efforts in this space
- [ ] TBD
- [ ] Integrate into the CI/CD workflow (for helm maybe?) for automated performance and regression testing
- [ ] Write a follow up to the "My One Click Mojaloop" deployment guide (this has been rather popular, and should at least reference this work)

**Acceptance Criteria**:
- [ ] Automation is streamlined and available to rapidly deploy a Mojaloop environment for labs, sand-boxes, workbenches and other such environments
- [ ] This is available with configuration to enable/disable components such as WSO2, TLS and other features easily

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
This is covered elsewhere, and somewhat out of scope now. Closing
