### ISSUE TITLE
 Postman Golden Path collection - Parameterise transferAmount.amount

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1007]
## **Goal**:
As a `Hub Operator`, I want to `parameterise the transfer amount in the Postman collections` so that `they can be configured via env variables for all tests to pass on Golden Path`

**Tasks**:
- [x] Parameratise the transferAmount.amount on the Request Payloads
- [x] Parameratise the transferAmount.amount on Tests

**Acceptance Criteria**:
- [x] Golden-path Postman scripts allow for amounts to be configurable via env params
- [x] Golden-path tests all pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/postman/pull/47

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
Thanks @mdebarros
