### ISSUE TITLE
Refactor central-services-database to use config instead of connection string

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#1008]
## **Goal**:
As a developer I want to refactor central-services-shares library to take in a configuration object so that the database connection for APIs can be properly configured and the default config isnt always used

**Tasks**:
- [x] Refactor central-services-shared @rmothilal 
- [x] Update central-ledger @rmothilal 
- [x] Update central-settlement @rmothilal 
- [x] Update quoting service @rmothilal 
- [x] Update account-lookup-service @lewisdaly 
- [x] Update all relevant helm scripts @rmothilal - Will follow-up in #1015 

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-database/pull/70
- [x] https://github.com/mojaloop/central-services-database/pull/71 - makes the database config backwards compatible 
- [x] https://github.com/mojaloop/account-lookup-service/pull/105 - account-lookup-service changes
- [x] https://github.com/mojaloop/helm/pull/215- helm updates Will follow-up in #1015 

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rmothilal 
- QA/Review: @rmothilal @mdebarros @elnyry

**Comment by lewisdaly** [comment]
@rmothilal the backwards compatible changes are working with my local copy on `central-settlements` and `account-lookup-service`.

**Comment by lewisdaly** [comment]
So I'm thinking if we set the `config.js` up as follows, this means we can maintain the existing behaviour and not break _all_ of the integration tests with this change:

```js
DATABASE: RC.DATABASE_URI || {
    client: RC.DATABASE.DIALECT,
    connection: {
      host: RC.DATABASE.HOST.replace(/\/$/, ''),
      port: RC.DATABASE.PORT,
      user: RC.DATABASE.USER,
      password: RC.DATABASE.PASSWORD,
      database: RC.DATABASE.DATABASE
    },
. . .
}
```
This means that setting the `*_DATABASE_URI` will override any config, which will save us adding `default.json` file overrides for our integration tests that rely on the above services.
