### ISSUE TITLE
Health check for ALS and ml-api-adapter not showing 'broker' status

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1009]
**Summary**:
Health check for ALS and ml-api-adapter not showing 'broker' status.
They are seen as 
```
{
    "status": "OK",
    "uptime": 69468.467,
    "startTime": "2019-10-08T13:14:55.899Z",
    "versionNumber": "8.1.0",
    "services": []
}
```

**Tasks**
- [x] Validate that all services are returning correct health status and includes all relevant sub-services
  - ~ml-api-adapter~ (@oderayi - Already fixed in v8.2.0)
      - ~Add broker health check~
      - ~Remove 'datastore' health check~
  - [x] account-lookup-service
      - [x] Add 'datastore' health check 
  - ~quoting-service~ (@oderayi - Up to date)
  - ~bulk-api-adapter~ (@oderayi - Up to date)
  - ~central-ledger~ (@oderayi - Up to date) 
  - ~central-settlement~ (@oderayi - Up to date)

**Severity**:
(Medium)

**Priority**:
(Medium)

**Expected Behavior**
```
{
    "status": "OK",
    "uptime": 69453.257,
    "startTime": "2019-10-08T13:14:52.407Z",
    "versionNumber": "8.2.3",
    "services": [
        {
            "name": "broker",
            "status": "OK"
        }
    ]
}
```

**Steps to Reproduce**
  1. Hit the endpoint -  http://dev1-ml-api-adapter.mojaloop.live/health
```
{
    "status": "OK",
    "uptime": 69560.963,
    "startTime": "2019-10-08T13:15:40.107Z",
    "versionNumber": "8.2.0",
    "services": []
}
```
  2.Hit the endpoint -  http://dev1-account-lookup.mojaloop.live/health
```
  {
    "status": "OK",
    "uptime": 69468.467,
    "startTime": "2019-10-08T13:14:55.899Z",
    "versionNumber": "8.1.0",
    "services": []
}
```

**Specifications**
  - Component (if known):
  - Version: v8.1.0 helm
  - Platform: Mac
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:@amarmodus

**Notes**:

- Severity when opened:
- Priority when opened:

## Pull Requests ##
- [x] https://github.com/mojaloop/account-lookup-service/pull/106

**Comment by mdebarros** [comment]
@amarmodus there is no "datastore" for the ml-api. It only has a dependency on the "broker". I believe the issue would be valid if you updated it to reflect this.

**Comment by amarmodus** [comment]
Updated expected behaviour. 

> @amarmodus there is no "datastore" for the ml-api. It only has a dependency on the "broker". I believe the issue would be valid if you updated it to reflect this.

**Comment by oderayi** [comment]
Health check from current master branch of `ml-api-adapter` (v8.2.0):

```
{ 
   "status":"OK",
   "uptime":33.721,
   "startTime":"2019-10-09T10:51:26.674Z",
   "versionNumber":"8.2.0",
   "services":[ 
      { 
         "name":"broker",
         "status":"OK"
      },
      { 
         "name":"participantEndpointService",
         "status":"OK"
      }
   ]
}
``

**Comment by lewisdaly** [comment]
@mdebarros Doesn't the ALS also depend on the central-ledger? I remember adding a health check for that, but it must've gone missing somewhere.

**Comment by elnyry** [comment]
It does, for FSP lookup, and other Participant details

**Comment by vijayg10** [comment]
Only datastore check was included. Broker check was not included. Can you please check on this?

**Comment by vijayg10** [comment]
Steven confirmed that ALS has no direct dependency on kafka. So datastore health check is enough and this issue is resolved.
