### ISSUE TITLE
QA - Validate/test bugfix #737, #956 

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1011]
## **Goal**:
As a maintainer of the OSS codebase, QA 
I want to make sure that new releases are checked for regressions
so that releases are validated before being accepted or released to the public

This specific story is for writing regression postman tests for bugs  #737 and  #956 
so that it confirms the bugs are fixed

**Tasks**:
- [ ] ~~Tests for https://github.com/mojaloop/project/issues/737 [ @? ]~~
  - [ ] ~~Validate~~
- [x] Tests for https://github.com/mojaloop/project/issues/956  
  - [x] Manually validated and confirmed error format(screenshot attached). further regression tests needs to added&verified as part of #1265 

**Acceptance Criteria**:
- [x] Regression tests in postman are available for bugs:
  - [ ] ~~#737~~
  - [ ] ~~#956~~ - will be dealt as part of #1265 

## **Pull Requests**:
- [ ] 

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: 
- QA/Review:

**Comment by amarmodus** [comment]
1009 covered in 1014

**Comment by amarmodus** [comment]
Error format check for settlement
<img width="2427" alt="Screenshot 2020-05-11 11 04 42" src="https://user-images.githubusercontent.com/53434415/81550051-a2cda980-9377-11ea-9277-5337045cc856.png">

**Comment by amarmodus** [comment]
https://github.com/mojaloop/project/issues/1392 - created as follow up story
