### ISSUE TITLE
QA: Validate and write Postman tests for Event Framework

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1012]
## **Goal**:
As a maintainer of the ML OSS codebase
I want to validate the event framework
so that all events (errors, general, etc) can be audited and traced as expected

**Tasks**:
- [ ] Postman tests for Transfer Prepare[ @? ]
- [ ] Postman tests for Transfer Fulfil[ @? ]
- [ ] Postman tests for Transfer Prepare & Fulfil Successful Commit[ @? ]
- [ ] Postman tests for Transfer Prepare & Fulfil Abortted Commit[ @? ]
- [ ] Postman tests for Transfer Prepare Error - Invalid FSP[ @? ]
- [ ] Postman tests for Transfer Prepare Error - Position Limit Breach[ @? ]
- [ ] Postman tests for Transfer Prepare Error - Timeout abort[ @? ]

**Acceptance Criteria**:
- [ ] Log Events
- [ ] Audit Events
- [ ] Trace Events

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @amarmodus 
- QA/Review: TBC

**Comment by amarmodus** [comment]
https://github.com/mojaloop/project/issues/1024 - raised for Part 2
