### ISSUE TITLE
Upgrade event-streaming-processor to create transactions from parent spans 

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1013]
## **Goal**:
As Hub TechOps
I want to _be able to visualize end-to-end times of transactions (not transfers, essentially)_
so that _it gives an overview of the system performance in general_ for specific messages

This specific story is to upgrade the event-streaming-processor so that APM agent creates transactions out of root spans and close them whenever the trace ends. The association between transaction id and transferId should be persisted in memory or some storage.

**Tasks**:
- [x] Investigate can we create master span from event-stream-processor
- [x] Implement storage to persist transaction and agent data
- [x] Persist the whole trace to the storage and send it to APM after last span is finished, since span is not sent until it's finished and the parent
- [x] Implement two ways of storing the trace
    - [x] Create master span, that covers the whole trace timeline. All consecutive spans and the master span are single transactions, as well. _The whole trace and master span duration can be used to get details for TPM and other metrics. Trace and Span IDs are same between EventSDK and APM. Errors are shown on the exact transaction, where they were captured._
    - [x] Create master transaction, that covers the whole trace timeline. All consecutive spans are spans followed by that transaction. _The TPM is calculated by APM by default. Trace ID and the master transaction and consecutive span ids are different but the order and timestamps are correct. Error is displayed on the level of master transaction._
- [x] Release 2 snapshot versions with both approaches
  - [x] single transactions for each span: https://github.com/mojaloop/event-stream-processor/releases/tag/v8.3.2-snapshot
  - [x] only master span is transaction. everything else is spans: https://github.com/mojaloop/event-stream-processor/releases/tag/v8.3.0-snapshot
- [ ] ~Implement each snapshot version into dev1 and dev2 environments so we can gather enough traces so we can examine the impact of the both cases~
- [x] Decide on the above approaches. **scenario 2 has been picked**
- [ ] ~Implement label for end of trace so we can close the transaction together with the trace~
- [ ] ~Create POC with instrumenting ml-api-adapter and cl prepare handler~
- [x] Implement closing of span on based on service name and tags
- [x] Implement changes requested by @mdebarros 
  - [x] config for catbox cache
  - [x] master-span service name to be `transaction-<transactionType>`
  - [x] make rules for closing master span to be configurable
- ~[ ] Find a way to test that spans are correctly linked via Postman tests~ *moved to the follow-up story*
- ~[ ] Update event framework diagrams~ *moved to the follow-up story*

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] APM Dashboard visualize transactions as one trace
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] End-to-end times for transactions can be made available for visualization

## **Pull Requests**:
- [ ] https://github.com/mojaloop/event-stream-processor/pull/6

## **Follow-up**:
- #1039 

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
