### ISSUE TITLE
Validate bug fixes from 8.2

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1014]
## **Goal**:
As a ML OSS Codebase maintainer
I want to validate bug fixes made in Sprint8.2
to ensure these are fixed in latest releases and that tests are in place to validate them in future

**Tasks**:
- [x] Validate BugFix for https://github.com/mojaloop/project/issues/883 [@oderayi  ]
  - [x] Ensure tests are present for future; Add new tests if needed
- [x] Validate BugFix for https://github.com/mojaloop/project/issues/980  [@oderayi  ]
  - [x] Ensure tests are present for future; Add new tests if needed
- [x] Validate BugFix for https://github.com/mojaloop/project/issues/998 [@vijayg10 ]
  - [x] Ensure tests are present for future; Add new tests if needed 
- [x] Validate BugFix for https://github.com/mojaloop/project/issues/1009 [@vijayg10 ]
  - [x] Ensure tests are present for future; Add new tests if needed 

**Acceptance Criteria**:
- [x] Bugs below are validated in latest releases
  - [x] #883 
  - [x] #980 
  - [x] #998  
  - [x] #1009 
- [x] Postman collections are validated to make sure tests for fixes are included for
  - [x] #883 
  - [x] #980 
  - [x] #998  
  - [x] #1009 

## **Pull Requests**:
- [ ] https://github.com/mojaloop/postman/pull/50
- [ ] https://github.com/mojaloop/postman/pull/51

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @amarmodus 
- QA/Review: @elnyry, ML Core team

**Comment by oderayi** [comment]
Blocking story until https://github.com/mojaloop/project/issues/1030 is fixed.

**Comment by elnyry** [comment]
PRs completed, ready to be merged when 'dev1' deployment is updated with helm release v8.3.0..
