### ISSUE TITLE
Helm Release v8.4.0: Support QA, Fixes, Releases, etc

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1015]
## **Goal**:
As a ML OSS Code base maintainer
I want to _validate and make a release in PI8 (Sprint~8.3~ 8.4) that is successfully validated by the available Golden path tests_
so that _down stream entities can take and use a version of Mojaloop Switch services bundle thats tested and contains latest features and enhancements (added in and PI8(Sprints 8.2, 8.3, 8.4) so far)_ 

This specific story is for making necessary changes for supporting Deployment, QA, Debugging, Fixes, Integration and performing end-to-end testing for all the changes made since v8.1.0 of Helm and including transaction-requests-service

**Tasks**:
- [x] Helm Deployment of changes corresponding to use of updated DB config on Dev2, from PR https://github.com/mojaloop/helm/pull/215 [@elnyry @rmothilal @mdebarros ] <-- Sprint8.3
  - [x] Deploy, validate, fix issues, redeploy <-- Sprint8.3
  - [x] With stable deployment test Golden path <-- Sprint8.3
- [x] Helm changes for quoting-service events, add oracle path finder [@rmothilal ]
  - [x] Deploy, validate, fix issues, redeploy
  - [x] With stable deployment test Golden path
- [x] Validation using Golden path regression tests etc on Dev2 [  ]
- [x] Identify issues with QA Scripts if any - fix them and retest [  ]
- [ ] Identify Bugs, log them
- [ ] Fix bugs logged [ ] [Add details here]
- [x] Deployment of released Helm v8.4.0 on **Dev2** [ ]
- [x] Validation using Golden path regression tests etc on Dev2 [  ]
- [ ] Deployment of released Helm v8.4.0 on **Dev1** [ ]
- [ ] Validation using Golden path regression tests etc on Dev1 [  ]

**Acceptance Criteria**:
- [x] Helm v8.4.0 is deployed on AWS Dev2 without issues
- [x] QA (Golden path) on deployments done on AWS dev2 environment is done
- [ ] Bugs are logged based on observations, failures
- [ ] Bugs logged are fixed to make subsequent releases in individual services (or Helm)
- [ ] All the changes needed for supporting v8.4.0 of Helm (List out major changes in release notes once release is ready)
- [ ] Transactions requests service is included in the Helm release v8.4.0

**Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/215
- [ ] https://github.com/mojaloop/postman/pull/56

**Follow-up**:
- N/A

**Dependencies**:
- [ ] TBD

**Accountability**:
- Owner: 
- QA/Review: DA, Core team

**Comment by ggrg** [comment]
Please change port 50051 to 50055 everywhere, where event-sdk is referred. #827 (PR https://github.com/mojaloop/quoting-service/pull/70)
