### ISSUE TITLE
Fix bugs 10-13 from Issue#9 of Quoting-Service

### ISSUE THREAD

**Issue by gibaros** [mojaloop/project#1016]
## **Goal**:
As a Hub Operator of a Mojaloop Switch
I want to respond with an HTTP error code for requests that do not follow the (Swagger) API Definition Data Model and or data validation agains DB so that only valid requests are accepted and processed in the Switch

This specific story is to fix bugs 10-13 from the known issue list in mojaloop/quoting-service/issues/9

**Tasks**:
- [x] Implement Scheme and DB validations based on missing items as per list here bugs 10-13
- [x] Bug 10 - sending quote with non-existent payeePartyIdentifier does not result in expected Party Not found Error code 3204, validate header and body payee information match, check that payee partyIdentifier exists for the payeefsp header destination
- [x] Bug 11 - Test with PUT request to try to reproduce reported bug
 - [x] Bug 12 - Test with duplicate quoteid, two requests within and after expiry time, review API Spec documentation to build request and reproduce reported bug
 - [x] Bug 13 - Test with GET request to try to reproduce reported bug
- [x] Add tests to the postman collection to validate all these bug fixes
- [ ] Increase unit test code coverage

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] Bugs 10-13 in the known issue list mojaloop/quoting-service/issues/9 are fixed

## **Pull Requests**:
- [x] https://github.com/mojaloop/quoting-service/pull/66
- [ ] ~https://github.com/mojaloop/postman/pull/48~ - Follow-up in #1035 
- [x] https://github.com/mojaloop/quoting-service/pull/69

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @gibaros 
- QA/Review: @mdebarros @rmothilal

**Comment by gibaros** [comment]
Per discussion with @rmothilal and @elnyry bug # 10 is not an issue as the payee partyIdentifier is validated by ALS and therefore no need to be validated at the quoting-service.

**Comment by gibaros** [comment]
10. POST/Quotes - sending quote with non-existent payeePartyIdentifier - Party Not found Error code 3204
    - The quote response should:
      - Validate the information and return response code 404 in case the payeePartyIdentifier doesn't exists.
      - Error Code 3204
      - Error description displayed: "Party Not found"
      - No quote should be created
11. PUT/Quote - sending callback without condition field
    - Sending a PUT/quotes with no condition field should give an error message notifying about the missing information
12. Send Quote Request -13 - Validate the expire time with duplicate quote ID
  12.a Sending Duplicate Quote ID after expiry time - Not showing error
  12.b Sending Duplicate Quote ID within expiry time - Not showing error
    - Sending a POST/quote with correct body and headers.
      - There should successful quote.
      - Send a new quote using the same QuoteID as in step 1
      - An error due quote ID duplication should appear.
13. Get Quotes: Validate Header
  13.a GET/Quotes - Missing Accept header - Not showing Response code 400
  13.b GET/Quotes - Missing FSPIOP-Source header - Not showing Response code 400
  13.c GET/Quotes - Missing Date header - Not showing Response code 400
    - Get /quotes request with errors in the header 
    - The request should be rejected giving 400 response code and error code and error msg in the response body.

**Comment by gibaros** [comment]
**Status update:**

10. not a bug, validation happens at ALS, no validation needed at quoting-service

11. PUT /quote request without condition hangs and results in a timeout 

12. POST /quote
a. after expiration:
-duplicate quoteId detected per quoting-service and simulator logs, but Postman receives a 202
{ errorInformation:
   { errorCode: '3106',
     errorDescription:
      'Modified request - Quote c3d273ac-a52b-4bf0-960e-c584a437f5b5 is a duplicate but hashes dont match' } }

b. within expiration:
-duplicate quoteId detected per quoting-service and simulator logs, but Postman receives a 202
{ errorInformation:
   { errorCode: '3106',
     errorDescription:
      'Modified request - Quote c3d273ac-a52b-4bf0-960e-c584a437f5b5 is a duplicate but hashes dont match' } }

13. GET /quotes
a. missing accept header shows http status code 400, works as expected

b. no http status code 400 at Postman, but logs show 404 error not found

c. no http status code 400 at Postman, but simulator log show:

ValidationError: child "date" fails because ["date" is required]

and quoting-service log show:

[quotesmodel]: forwarding quote get request 07e92ea7-d655-4f88-925c-4aeefcee80f6 from payerfsp to payeefsp got response 404 Not Found

**Comment by gibaros** [comment]
Status update:

11. PUT /quote request without condition - after building a valid PUT /quote request works as expected

`{
    "errorInformation": {
        "errorCode": "3102",
        "errorDescription": "Missing mandatory element - condition"
    }
}`

12. Not a bug, due to async nature of service.

13. GET /quotes - PR https://github.com/mojaloop/quoting-service/pull/66 addresses issue

**Comment by gibaros** [comment]
@elnyry  Issue is ready for final review and close as there are no task pending.

**Comment by gibaros** [comment]
Closing issue, Georgi working on adding additional code coverage at https://github.com/mojaloop/project/issues/1041
