### ISSUE TITLE
Update Bulk Transfer services documentation

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#1017]
## **Goal**:
As a Hub Operator providing Bulk transfers feature
I would like to _have access to up-to-date documentation_
so that _latest changes to Bulk Transfers implementation can be fully and accurately understood_

As a ML OSS contributor
I want to update documentation
so that latest changes to Bulk Transfers implementation are fully captured

**Tasks**:
- [x] Update bulk related sequence diagrams [@ggrg]
- [x] Update DB schema diagrams [@ggrg]
- [x] Update "Bulk Transfer Operations" documentation section

**Acceptance Criteria**:
- [x] Bulk transfer designs are up-to date
  - [x] Sequence diagrams
  - [x] DB Schema diagrams
  - [x] Updated Bulk Transfer Operations section

## **Pull Requests**:
- [x] https://github.com/mojaloop/documentation/pull/117
- [x] https://github.com/mojaloop/documentation/pull/118

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

**Reference**:
- [x] #967

## **Accountability**:
- Owner: @ggrg 
- QA/Review: @elnyry
