### ISSUE TITLE
POST/Quotes with quoteid or transactionid missing mandatory field, error not displayed correctly due to hapi regex not properly handling empty value

### ISSUE THREAD

**Issue by gibaros** [mojaloop/project#1018]
## **Goal**:
As a Hub Operator of a Mojaloop Switch
I want to respond with an HTTP error code for requests that do not follow the (Swagger) API Definition Data Model and or data validation agains DB so that only valid requests are accepted and processed in the Switch

**Tasks**:
- [x] POST /quotes Sending quote with quoteid missing mandatory field error not displayed correctly due to hapi regex not properly handling empty quoteid value. Potential fix at hapi regex.
- [x] POST /quotes Sending quote with transactionid missing mandatory field error not displayed correctly due to hapi regex not properly handling empty quoteid value. Potential fix at hapi regex.

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- [ ] #1021  ~ Note this is a blocker for this story.

## **Accountability**:
- Owner: @rmothilal 
- QA/Review: @rmothilal @mdebarros

**Comment by yosheeck** [comment]
Enjoi 6.0.1 was just released with fix for this.

**Comment by elnyry-sam-k** [comment]
Thanks @rmothilal for confirming that this is now fixedd
