### ISSUE TITLE
Release finance-portal-lib under OSS

### ISSUE THREAD

**Issue by ndonnan** [mojaloop/project#1019]
## **Goal**:
As a Contributor
I want to publish the finance portal library (on Mojaloop)
so that it can be imported as dependencies into the finance portal backends

**Tasks**:
- [x] Check in the code currently in casa-lib into the mojaloop/finance-portal-lib repo
- [x] Remove any Mowali specific code / references
- [x] Set up circleci
- [x] Make the repo public
- [x] Release to npm

**Acceptance Criteria**:
- [x] Exisitng Unit Tests pass
- [x] Initial version is published to npm

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
