### ISSUE TITLE
Release finance-portal-backend-services under OSS

### ISSUE THREAD

**Issue by ndonnan** [mojaloop/project#1020]
## **Goal**:
As a Contributor
I want to release the finance-portal-backend-service module (to the public)
so that implementers can build front end portals using these as template/reference

**Tasks**:
- [x] Remove any Mowali specific code / references
- [x] Import the finance-portal-lib library instead of casa-lib 
- [x] Make the repo public
- [x] Create a snapshot release

**Acceptance Criteria**:
- [x] Exisitng Unit Tests pass
- [x] Initial snapshot release published

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
