### ISSUE TITLE
Fix for enjoi and hapi-openapi dependencies

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#1021]
**Summary**:
There was a massive rewrite of the Joi library recently which effects the library we use to validate our swagger.json, hapi-openapi which has a dependency on enjoi which is a validator for datatypes. 
 
**Severity**:
Low

**Priority**:
Low

**Expected Behavior**
The hapi-openapi library validates our swagger and all incoming requests

**Steps to Reproduce**
  1. Update service that requires hapiopenapi eg: ALS hapi and joi dependencies to the latest versions v19 hapi v17 joi
  2. Notice that the server will not start

**Specifications**
  - Component (if known): hapi-openapi
  - Version: 1.2.3
  - Platform: Node
  - Subsystem: 
  - Type of testing: local
  - Bug found/raised by: @rmothilal 

  - Component (if known): enjoi
  - Version: 4.0.0
  - Platform: Node
  - Subsystem:
  - Type of testing: local
  - Bug found/raised by: @rmothilal 

**Notes**:
Dependent story:
 - #1018 

- Severity when opened: Low
- Priority when opened: Low

**Dependency work**:
- [x] https://github.com/tlivings/enjoi/issues/73 - the bug in enjoi
  - [x] https://github.com/tlivings/enjoi/pull/82 - merged fix to enjoi
  - [x] Enjoi 6.0.1 released (https://github.com/tlivings/enjoi/blob/master/CHANGELOG.md)

**Tasks**:
- [ ] Update dependencies on enjoi
- [ ] Update dependencies on hapiopenapi
- [ ] Updated code to use latest Hapi and Joi functionality on enjoi
- [ ] Updated code to use latest Hapi and Joi functionality on hapiopenapi
- [ ] Update unit tests on enjoi
- [ ] Update unit tests on hapiopenapi
- [ ] Pull request enjoi
- [ ] Pull request hapiopenapi
  - [ ] enjoi dependency approved

**Acceptance Criteria**:
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBA

## **Follow-up**:
- N/A

## **Accountability**:
- Owner: @rmothilal 
- QA/Review: @mdebarros , @yosheeck , @vgenev

**Comment by rmothilal** [comment]
Still busy with code changes and tests

**Comment by elnyry** [comment]
Blocked on changes needed in a few dependent OSS libraries

**Comment by elnyry** [comment]
Good as of Sprint 10.2
