### ISSUE TITLE
QA: Validate and develop Postman tests for Event Framework - Part 2

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1024]
## **Goal**:
As a maintainer of the ML OSS codebase
I want to validate the event framework
so that all events (errors, general, etc) can be audited and traced as expected

**Tasks**:
- [x] Postman tests for Transfer Prepare & Fulfil Abortted Commit[ @? ]
  - [x] Manual test
  - [x] Identify events from kibana
- [x] Postman tests for Transfer Prepare Error - Invalid FSP[ @? ]
  - [x] Manual test
  - [x] Identify events from kibana
- [x] Postman tests for Transfer Prepare Error - Position Limit Breach[ @? ]
  - [x] Manual test
  - [x] Identify events from kibana
- [x] Postman tests for Transfer Prepare Error - Timeout abort[ @? ]
  - [x] Manual test
  - [x] Identify events from kibana

**Acceptance Criteria**:
- [x] Log Events
- [x] Audit Events
- [x] Trace Events

## **Pull Requests**:
- [x] https://github.com/mojaloop/postman/pull/58 

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @amarmodus 
- QA/Review: TBC

**Comment by amarmodus** [comment]
<img width="1192" alt="Screenshot 2019-10-25 14 07 45" src="https://user-images.githubusercontent.com/53434415/67590192-45af3500-f752-11e9-8cfc-c1b83cc30a67.png">
![Screenshot 2019-10-25 14 07 59](https://user-images.githubusercontent.com/53434415/67590196-48118f00-f752-11e9-8f0b-53098dcaef07.png)
