### ISSUE TITLE
Invalidate cache for endpoints when an endpoint is updated

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1025]
## **Goal**:
As a Hub Operator
I want to _use the latest endpoints updated by an FSP when making callbacks / calls to that FSP_ so that _communication is directed towards the correct endpoints and not outdated ones_

**Tasks**:
- [x] Reset / Invalidate Cache (central-ledger) when end-points are updated (preferably selectively, but if features not available, then all of the cache)
- [x] Create and expose reset endpoint cache resource for Admin at als
- [x] Create and expose reset endpoint cache resource for Admin at ml-api-adapter
- [x] Create and expose reset endpoint cache resource for Admin at bulk-api-adapter
- [x] Unit tests
- [x] Verify account-lookup-service, ml-api-adapter, bulk-api-adapter and other services using this mechanism
- [x] Fix ALS swagger semantic error at definitions.Status.properties.services
Schemas with 'type: array', require a sibling 'items: ' field
Jump to line 2382`

**Acceptance Criteria**:
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] When messages are sent to FSPs, they are directed at latest endpoints set by FSPs

## **Pull Requests**:
- [x] https://github.com/mojaloop/account-lookup-service/pull/120
- [x] https://github.com/mojaloop/ml-api-adapter/pull/239
- [x] https://github.com/mojaloop/bulk-api-adapter/pull/12
- [x] https://github.com/mojaloop/central-services-shared/pull/122

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Notes**:
- Follow-up changes from https://github.com/mojaloop/quoting-service/pull/67 to remove commented code after standardized changes are made

**Comment by gibaros** [comment]
All tasks were completed per PRs listed, closing issue.
