### ISSUE TITLE
Address quoting-service setImmediate calls in unit testing

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1027]
## **Goal**:
As a ML OSS code-base maintainer
I want to address issues in quoting-service that impede adding robust unit tests
 so that the code-quality needed for quoting-service can be achieved and maintaned

**Tasks**:
- [x] Address quoting-service setImmediate calls in unit testing [@ggrg]
  - [x] Discuss within team the right approach: native **jest.runAllImmediates()** does the job [@ggrg]
  - [x] Rewrite test/unit/model/quotes.test.js to ~fully~ test underlying model/quotes.js (100% coverage)
    - [x] validateQuoteRequest [@ggrg] (100%)
    - [x] validateQuoteUpdate [@ggrg] (100%)
    - [x] handleQuoteRequest [@ggrg] (100%)
    - [x] forwardQuoteRequest [@ggrg] (100%)
    - [x] handleQuoteRequestResend [@ggrg] (100%)
    - [ ] ~handleQuoteUpdate~ [@ggrg] (only provided sample QuotesIDPutResponse)
    - [ ] ~forwardQuoteUpdate~
    - [ ] ~handleQuoteUpdateResend~
    - [ ] ~handleQuoteError~
    - [ ] ~handleQuoteGet~
    - [ ] ~forwardQuoteGet~
    - [ ] ~handleException~
    - [ ] ~sendErrorCallback~
    - [ ] ~checkDuplicateQuoteRequest~
    - [ ] ~checkDuplicateQuoteResponse~
    - [ ] ~removeEmptyKeys~
    - [ ] ~calculateRequestHash~
    - [ ] ~generateRequestHeaders~
    - [ ] ~writeLog~

**Acceptance Criteria**:
- [x] Use jest testing framework
  - [x] Use native jest stubs (not Sinon)
  - [x] Use jest.runAllImmediates() to cover code whitin setImmediate() calls
  - [x] Use jest Matchers to ensure unit tests quality
  - [ ] ~Achieve 100% coverage for model/quotes.js to put the foundation of jest testing for quotes~
- [x] Unit Tests pass
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] Issues with setImmediate calls in quoting-service are addressed to help better develop unit tests

## **Pull Requests**:
- [x] https://github.com/mojaloop/quoting-service/pull/78

## **Follow-up**:
- [ ] #1041

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by ggrg** [comment]
According to the latest story acceptance criteria edit, the story estimate needs to change (or reverted back) - to be discussed during the daily. Current progress is 33% and it consists of ~670 lines of code. The estimate for this single file is ~2000 lines of code for 100% tests coverage.

**Comment by elnyry** [comment]
@ggrg I think this issue should be about directly addressing the issue and not coverage. We should update that criteria and move forward with this story.
