### ISSUE TITLE
Implement GET /quotes on the simulator to support event framework testing / demos on quoting-service

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1028]
## **Goal**:
As a Community member
I want to have the GET on /quotes supported by the Simulator, specific to events
so that Event framework capabilities can be tested/demonstrated end-to-end

**Tasks**:
- [x] Refactor simulator to support GET on /quotes for events (event framework) [@ggrg]

**Acceptance Criteria**:
- [ ] ~Designs are up-to date~
- [ ] ~Unit Tests pass~
- [ ] ~Integration Tests pass~
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] The simulator service supports GET /quotes calls so that event-framework support can be provided end-to-end on quotes

## **Pull Requests**:
- [x] https://github.com/mojaloop/simulator/pull/89

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
