### ISSUE TITLE
ValidationError caused by empty `extension` array in `extensionList`

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1030]
**Summary**:
In `ml-api-adapter`, some requests with empty `extension` array in `extensionList` are being sent causing `ValidationError` e.g. on the side of the Simulator. 

For example, the following request from `ml-api-adapter`:

```JSON
{ 
   "url":"http://172.17.0.1:8444/payeefsp/transfers/05b76c17-7b2f-4ed9-a411-0ef4ecea3295/error",
   "method":"PUT",
   "headers":{ 
      "Accept":"application/vnd.interoperability.transfers+json;version=1.0",
      "FSPIOP-Destination":"noresponsepayeefsp",
      "Content-Type":"application/vnd.interoperability.transfers+json;version=1.0",
      "Date":"Wed, 23 Oct 2019 10:19:45 GMT",
      "FSPIOP-Source":"payerfsp"
   },
   "data":"{\"errorInformation\":{\"errorCode\":\"3300\",\"errorDescription\":\"Generic expired error\",\"extensionList\":{\"extension\":[]}}}",
   "responseType":"json"
}
```

results in the following error on the simulator side:

>  ValidationError: child "errorInformation" fails because [child "extensionList" fails because [child "extension" fails because ["extension" must contain at least 1 items]]]

The API spec specifies that if `extensionList` is present in the `errorInformation` in the request, then `extension` array (a property of `extensionList`)  must have at least 1 item and not more than 16 items.

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
No `extensionList` should be sent if `extension` array is empty, and the number of objects in `extension` array should be between 1 and 16 (inclusive) as specified in the API spec and swagger.

**Steps to Reproduce**
  1. Launch the `central-ledger` stack, easier with `docker-compose up`
  2. Ensure you have ran the Postman collection `OSS-New-Deployment-FSP-Setup` to setup the stack, if you haven't done so already.
  3. Send the Postman request in `Golden_Path -> transfer_negative_scenarios -> transfer_timeout -> Send Prepare`, wait for the error timeout (about 30 seconds), then read the log for Simulator for the error and the log for `ml-api-adapter` for the request sent.

**Specifications**
  - Component (if known): `ml-api-adapter`, may apply to other central services too
  - Version: 8.3.2 and lower
  - Platform: *
  - Subsystem: *
  - Bug found/raised by: @oderayi 

**Tasks**:
- [x] fix configs for `ml-api-adapter` repo, so I can run it locally
- [x] reproduce and debug the issue
- [x] fix the code in https://github.com/mojaloop/central-services-error-handling
  - [x] fix/modify/add unit tests
  - [x] deploy `mojaloop/central-services-error-handling` npm package
- [x] update `ml-api-adapter`
  - [x] bump `central-services-error-handling` and other dependencies
  - [x] fix unit tests
- [x] verify issue is fixed on clean "master" builds

**Identified Cause**:
The bug is exposed by specific setup of configs for `ERROR_HANDLING` in `central-ledger` and `ml-api-adapter`:
- the source of that message is `central-ledger` where the `ERROR_HANDLING.includeCauseExtension` should be set to **TRUE**. 
- then that message is processed by `ml-api-adapter` where `ERROR_HANDLING.includeCauseExtension` is set to **FALSE**, so message with `extensionList` already in place, gets reprocessed and `extension` array items are being removed. However that code doesn't remove `extension` (nor `extensionList`) itself, causing "empty array".
- that processing is handled in `mojaloop/central-services-error-handling`

**PRs**:
- [x] https://github.com/mojaloop/ml-api-adapter/pull/259 - fix for configs
- [x] https://github.com/mojaloop/ml-api-adapter/pull/263 - one more configs change
- [x] https://github.com/mojaloop/central-services-error-handling/pull/89 - fix in library
- [x] https://github.com/mojaloop/ml-api-adapter/pull/265 - fixed issue
- [x] https://github.com/mojaloop/ml-api-adapter/pull/268 - minor PR (version bump and linting)

**Comment by elnyry** [comment]
@oderayi Thanks for this. Its pretty important that we're able to recognize this at least now. Lets address this soon..

@amarmodus @sri-miriyala FYI
