### ISSUE TITLE
Replace xmldom dependency in mock-pathfinder

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1031]
## **Goal**:
As an OSS Maintainer
I want to remove the `xmldom` dependency in `mock-pathfinder`
so that I can keep the licenses free of GPL licenses

~`xmldom` has an inappropriate license for the Mojaloop OSS project, and needs to be removed. It is a nested dependency of `soap`, so we need to either fork the `soap` project and replace its dependencies, or find an alternative library to soap which doesn't rely on `xmldom`~

This issue only applies to the `mock-pathfinder` service, which is about to be deprecated. Instead of removing the dependency, we are going to deprecate the repo and remove it from the upcoming release.

**Tasks**:
~- [ ] Replace the xmldom dependency in mock-pathfinder~
- [x] Deprecate the mock-pathfinder library and remove references from helm
- [ ] Change the license-scanner rules to disallow xmldom

**Acceptance Criteria**:
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/mock-pathfinder/pull/13 - Deprecation notice
- [x] https://github.com/mojaloop/license-scanner/pull/9 - Remove xmldom from license-scan whitelist
- [x] https://github.com/mojaloop/helm/pull/244

## **Follow-up**:
- [ ] double check the license scan files for mock-pathfinder, and verify they are free from the xmldom dependency

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: TBC

**Comment by lewisdaly** [comment]
It looks like `mock-pathfinder` is on the cusp of being deprecated and removed from helm, so it won't be an issue soon.

**Comment by lewisdaly** [comment]
Waiting for new helm release without mock-pathfinder

**Comment by lewisdaly** [comment]
In order to remove mock-pathfinder from helm, we must also remove:

- central-directory
- central-end-user-registry

I don't see either of these charts referenced in the `mojaloop/values.yml` file, so I think it should be safe to remove them. @mdebarros or @elnyry can you please confirm?

**Comment by elnyry** [comment]
@lewisdaly yes central-directory and central-end-user-registry are now not used

**Comment by lewisdaly** [comment]
this is now done, and will be reflected in the next helm release
