### ISSUE TITLE
Enhance the simulator to support bulkTransfers

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1033]
## **Goal**:
As a maintainer of the ML OSS Switch software
I want _the Simulators used for QA, testing purposes to support bulkTransfers requests by validating, responding bulkTransfer messages according to the ML v1.0 Spec_
so that _end-to-end testing, QA can be performed on a deployable ML Switch_

As a community member
I want to be able to deploy the ML OSS Switch with bulk transfers components
so that I can perform end-to-end QA, Testing and analysis

**Tasks**:
_**(As these endpoints are already implemented, the following tasks need to be validated)**_
- [x] ~~Refactor/Update~~ _Validate_ Simulator implementation to support
  - POST /bulkTransfers
  - PUT /bulkTransfers/{ID}
  - PUT /bulkTransfers/{ID}/error
- [x] ~~Refactor/Update~~ _Validate_ Simulator implementation to support GET calls on requests, callbacks, correlationId for QA purposes which respond with corresponding messages and headers.
- ~~Sanity testing~~
- ~~Helm changes needed~~

**Acceptance Criteria**:
- [x] The OSS Simulator is ~~updated~~ **verified** to support BulkTransfers
- [x] The OSS Simulator is ~~updated~~ **verified** to GET calls on BulkTransfers for QA to provide message details

## **Pull Requests**:
- TBD

**Dependencies**:
- N/A

## **Accountability**:
- Owner: 
- QA/Review: TBC

**Comment by vijayg10** [comment]
These endpoints are already implemented in PR https://github.com/mojaloop/simulator/pull/34.
I validated the functionality and confirming that it is matched with the ML API Specification 1.0.
So I am closing this issue.
