### ISSUE TITLE
Missing trace tags in cl timeout handler trace messages

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1034]
**Summary**:
In the event trace messages from the central-ledger timeout handlerTags no tags have been added. Thus master span rules for ending the span cannot be applied. The rules rely on *transactionType* and *transactionAction* tags, as well as the *service* name. 
Also the consecutive spans (position, notification) are from different trace. 

**Severity**:
Medium

**Priority**:
Low

**Expected Behavior**
Every trace-span event message should have following tags: 
```
"tags": {
  "transactionType": "transfer",
  "transactionAction": "prepare",
  "transactionId": "69a205bc-6b12-466a-9be4-575cb14fa30e",
  "source": "payerfsp",
  "destination": "payeefsp",
  "payerFsp": "payerfsp", 
  "payeeFsp": "payeefsp"
}
```
as payerFsp and payeeFsp, if applicable. 

**Steps to Reproduce**
  1. Create a transfer
  2. Wait for transfer to expire
  3. Check the event message

**Tasks**
- [x] Update central-services-shared to add getTransferSpanTags helper method to be able to use it in both central-ledger and ml-api-adapter
- [x] Update central-ledger timeout handler to add tags using the shared function and pass span context to the message so prepare handler and ml-notification-handler to fall into the same trace
- [x] Update ml-api-adapter to use the shared function
- [x] Update event-streaming-processor default.json to cover start and end criteria for the span from timeout handler
- [x] Update default.json in helm chart for event-streaming-processor

**Pull Requests**
- [x] https://github.com/mojaloop/central-services-shared/pull/127
- [x] https://github.com/mojaloop/central-ledger/pull/474
- [x] https://github.com/mojaloop/ml-api-adapter/pull/262
- [x] https://github.com/mojaloop/event-stream-processor/pull/10
- [x] https://github.com/mojaloop/helm/pull/226

**Dependencies**
 - [ ] https://github.com/mojaloop/project/issues/1061

**Specifications**
  - Component (if known): Central Ledger timeout handler
  - Version: latest
  - Bug found/raised by: @vgenev 

**Notes**:
At the moment in the event-streaming-processor the cl timeout handler span is closed as a single trace. This needs to be fixed as soon as the bug is fixed.
