### ISSUE TITLE
QA - Validate/test bugfix for 8.4.0 release

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1035]
## **Goal**:
As a maintainer of the OSS codebase, QA 
I want to make sure that new releases are checked for regressions
so that releases are validated before being accepted or released to the public

This specific story is for writing regression postman tests for bugs  #981  
so that it confirms the bugs are fixed. 

**Tasks**:
- [x] Fix cron job failures - https://s3-us-west-2.amazonaws.com/mojaloop-oss-qa-results/report-1573599601.html
- [x] Tests for https://github.com/mojaloop/project/issues/981
  - [x] Validate
  - [x] Develop / ensure postman tests
- [x] Follow-up PR from #1016 
  - [x] Review PR - https://github.com/mojaloop/postman/pull/48
  - [x] Verify PR, update tests as needed
  - [x] https://github.com/mojaloop/postman/pull/67 - part 1 - replacing PR-48
  - [x] https://github.com/mojaloop/postman/pull/68 - part 2

**Acceptance Criteria**:
- [x] Regression tests in postman are available for bugs:
  - [x] #981 
  - [x] #1016 
  

## **Pull Requests**:
- [x] https://github.com/mojaloop/postman/pull/65
- [x] https://github.com/mojaloop/postman/pull/67
- [x] https://github.com/mojaloop/postman/pull/68

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @amarmodus 
- QA/Review:

**Comment by amarmodus** [comment]
Missing QuoteID check and Missing TransactionID check - fix to be implemented in  https://github.com/mojaloop/project/issues/1018. Hence test not yet added as part of https://github.com/mojaloop/postman/pull/61
