### ISSUE TITLE
Postman collection for FSP setup & transfers Golden path on perf environment

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1036]
## **Goal**:
As a Community member
I want to have a collection readily available that focuses on transfers related setup
so that _I can use it for performance testing transfers on a basic Mojaloop deployment_

**Tasks**:
- [x] Take existing postman collection with mojaloop sim and confirm
   - [x] https://github.com/mojaloop/postman/pull/69 - tested in a Mojaloop Lab
- [x] Verify the collection a second time on a Mojaloop Lab - with updated env file with new bearer tokens
- [ ] Create postman collection (subset of current FSP setup) for testing a perf environment
  - [x] Setup additional FSPs (2 more)
  - [ ] Update environment file to use with ML OSS perf environment
  - [ ] Run FSP setup on perf environment, fix issues
  - [ ] Run Happy path on perf environment, fix issues
  - [ ] Run Settlements on perf environment, fix issues (might be a new issue)
  - [ ] Run entire Golden path on perf environment, fix issues (might be a new issue)
- [ ] Test on existing environments
- [ ] Review and publish

**Acceptance Criteria**:
- [ ] An FSP setup collection that can be used to setup a environment for transfers (to use for perf testing) is made available and published on postman repo

## **Pull Requests**:
- [x] https://github.com/mojaloop/pi8-perf-testing/pull/1

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
With the decision to use "mojaloop-simulator" for perf, the scope of this changes, and so moving this back to backlog to be discussed after a setup with mojaloop-simulator is designed and ready to be deployed or is deployed.

**Comment by amarmodus** [comment]
<img width="1279" alt="Screenshot 2019-12-11 09 12 47" src="https://user-images.githubusercontent.com/53434415/70607715-dc4a8f00-1bf6-11ea-93bc-fbeb3b60e526.png">
Mojaloop SIM - environment

**Comment by elnyry-sam-k** [comment]
This is now covered in other stories and concluded
