### ISSUE TITLE
SDK scheme adapter testing and documentation

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1040]
## **Goal**:
As a DFSP, I need a document to refer for the installation and testing procedure using the SDK scheme adapter with different scenarios to have a quick start.

**Tasks**:
- **Testing**:
  - [x]  "Scheme Adapter + Mock DFSP Backend" -> "Scheme Adapter + Mojaloop Simulator" [@vijayg10]
  - [x]  "Scheme Adapter + Mock DFSP Backend" -> "Local K8S cluster" [@vijayg10]
  - [x]  "Scheme Adapter + Mojaloop Simulator" -> "Public hosted WSO2 enabled Mojaloop testing API" [@vijayg10]

- **Documentation**:
  - [x]  "Scheme Adapter + Mock DFSP Backend" -> "Scheme Adapter + Mojaloop Simulator" [@vijayg10]
  - [x]  "Scheme Adapter + Mock DFSP Backend" -> "Local K8S cluster" [@vijayg10]
  - [x]  "Scheme Adapter + Mojaloop Simulator" -> "Public hosted WSO2 enabled Mojaloop testing API" [@vijayg10]

- **Review**:
  - [x] Validate published documentation --> https://mojaloop.io/documentation/sdk-scheme-adapter [@yosheeck]
    - [x] Fix postman collection against HOST_SIMULATOR vs HOST_SIMULATOR_K8S_CLUSTER confusion
    - [x] Fix modified postman environment against HOST_SIMULATOR vs HOST_SIMULATOR_K8S_CLUSTER
    - [x] Adjust documentation and example configs to cover environments which are stricter in terms of domain-name resolution: running on linux, running with different microk8s versions etc.

## **Pull Requests**:
- [x] Documentation
- [x] https://github.com/mojaloop/mojaloop-simulator/pull/23 - config updates
- [x] https://github.com/mojaloop/sdk-mock-dfsp-backend/pull/3 - config updates
- [x] https://github.com/mojaloop/postman/pull/74 - postman collection adjusted
- [x] https://github.com/mojaloop/documentation/pull/154 - documentation and postman collection adjusted

**Dependencies**:
 - [x] Need some information about setting up the callback endpoints in WSO2 from @NicoDuvenage 
 - [x] Need information from @NicoDuvenage about the provisioning the SSL certificates in WSO2, signing process and MCM

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @elnyry

**Comment by vijayg10** [comment]
Partially completed documentation can be found at
https://github.com/vijayg10/testing-sdk-scheme-adapter

**Comment by vijayg10** [comment]
The documentation is completed and available at the previous link. I will wait for the review for a couple of days and close this issue.
