### ISSUE TITLE
Improve unit tests coverage for quoting-service (part 1)

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#1041]
## **Goal**:
As a ML OSS code-base maintainer
I want to provide full unit test coverage for Quote Model script
so that the code-quality needed for quoting-service can be achieved and maintained

**Tasks**:
- [x] Provide full unit tests coverage for model/quotes.js [@ggrg]
    - [x] handleQuoteUpdate [@ggrg]
    - [x] forwardQuoteUpdate [@ggrg]
    - [x] handleQuoteUpdateResend [@ggrg] [d481c56](https://github.com/ggrg/quoting-service/commit/d481c56)
    - [ ] ~handleQuoteError~
    - [ ] ~handleQuoteGet~
    - [ ] ~forwardQuoteGet~
    - [ ] ~handleException~
    - [ ] ~sendErrorCallback~
    - [ ] ~checkDuplicateQuoteRequest~
    - [ ] ~checkDuplicateQuoteResponse~
    - [ ] ~removeEmptyKeys~
    - [ ] ~calculateRequestHash~
    - [ ] ~generateRequestHeaders~
    - [ ] ~writeLog~

**Acceptance Criteria**:
- [ ] ~Full unit tests coverage for Quote Model~
- [x] Unit Tests pass
- [ ] ~Integration Tests pass~
- [ ] ~Code Style & Coverage meets standards~
- [ ] ~Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.~

## **Pull Requests**:
- [x] https://github.com/mojaloop/quoting-service/pull/80

## **Follow-up**:
- #1047

**Dependencies**:
- [x] #1027

## **Accountability**:
- Owner: @ggrg
- QA/Review: @rmothilal, @mdebarros

**Comment by ggrg** [comment]
## Start:
![image](https://user-images.githubusercontent.com/20338055/68058999-9222e380-fd03-11e9-8d9e-b8c95fffa7b1.png)
## Current:
![image](https://user-images.githubusercontent.com/20338055/68058958-66076280-fd03-11e9-9d09-158df2d11231.png)
