### ISSUE TITLE
Provision Temporary Performance Environment

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1043]
## **Goal**:
As Ops
I want to _ensure performance testing can be done on a mojaloop Switch (core)_
so that _missing pieces can be identified and addressed_ for end-to-end perf testing to be done.

**Tasks**:
- Provision K8S Cluster
    - [x] Configure Cluster with Master, IO and GC nodes
    - [x] Taint Master, IO and GC nodes appropriately
    - [x] Lables for Master, IO and GC nodes appropriately
    - [x] Helm
    - [x] Dashboard
    - [x] Ingress
    - [x] DNS
- Create the deployment configurations for:
    - [x] EFK
    - [x] Promfana
    - [x] Event-Stream-Processor
    - [x] Mojaloop
- Deployments:
    - [x] EFK
    - [x] Promfana
    - [x] Event-Stream-Processor
    - [x] Mojaloop
- Test environment
    - [x] EFK
    - [x] Promfana
    - [x] Event-Stream-Processor
    - [x] Mojaloop
- JMeter
    - [x] Provision K8s Cluster
    - [x] Deploy JMeter
    - [x] Load sample remote JMeter script
    - [x] Test sample remote Jmeter script
    - [x] Setup dashboards for monitoring

**Acceptance Criteria**:
- [x] Provision documented
- [x] Perf PI8 Presentation up-to date
- [x] Temporary Performance Environment is provisioned
- [x] The following deployments are operational
    - [x] EFK
    - [x] Promfana
    - [x] Event-Stream-Processor
    - [x] Mojaloop
-  JMeter
    - [x] JMeter cluster running externally to the Perf environment
    - [x] JMeter cluster able to execute Jmeter scripts remotely in a clustered mode
-  Successfully execute QA scripts for the following
    - [x] QA Golden Path Tests
    - [ ] ~Event Stream Events into EFK Tests~
- [ ] ~Follow-up stories for gaps identified are created to be addressed separately~

## **Pull Requests**:
- [ ] https://github.com/mojaloop/helm/pull/220

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
