### ISSUE TITLE
Create postman collection for WSO2 hackathon API gateway

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1044]
## **Goal**:
I want to create a postman collection and environment like Goldpath Collection to test the WSO2 hackathon API.

**Tasks**:
- [x] Create postman environment file
- [x] Modify goldpath collection for WSO2
 
**Acceptance Criteria**:
- [ ] The new postman goldpath collection should be passed with 100% success rate.

## **Pull Requests**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: N/A
- QA/Review: N/A

**Comment by elnyry** [comment]
Closing this now to focus on making it more generic
