### ISSUE TITLE
Refactor simulator for scalability

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1045]
## **Goal**:
As a QA
I want to be able to use a simulator that is generic
so that it is scalable and can be used with a variety of FSPs

**Tasks**:
- [x] Review currently implemented code for different hardcoded fsps and determine its purpose to confirm current story estimate [@ggrg]
- [ ] Refactor simulator to remove hardcoded FSP names (for payerfsp, payeefsp, testfsps1-4, noresponsepayee, etc)
- [x] Review caching [@ggrg]
- [x] Instrumentation / Support for Prometheus (should already be there for transfers) [@ggrg]
- [ ] Configurability for FSPs (provides support for 'noresponsepayeefsp' scenario)
  - [ ] Send callback?
  - [ ] Send faulty / error callback?
  - [ ] If not config found, default config available

**Notes for tasks**:
- [ ] get rid of all other FSPs, remove payer/payee from end-points
- [ ]  combine payer and payee FSPs
- [ ] functionality moved to relevant path for quotes, ALS, transfers, etc
- [x] concern: callback endpoints hard-coded? should be derived from headers (Source, Dest) [@ggrg]
- [x] Review stored cache for each FSP and add tasks to move to Global caching - Server Cache? [@ggrg]

**Acceptance Criteria**:
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] [Simulator](https://github.com/mojaloop/simulator) is refactored to be generic, scalable

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by ggrg** [comment]
After performing initial analysis and file comparison I may confirm the current estimate as accurate. Have some minor questions to clarify with the story owner, but story with the provided description seems to be good to go.

**Comment by elnyry** [comment]
A decision has been made to use the 'mojaloop-simulator' for performance testing and so this effort will be halted to focus on getting mojaloop-simulator deployed on a perf environment and get things running with SDK / mojaloop-simulator

**Comment by elnyry** [comment]
Reducing the estimate and closing this
