### ISSUE TITLE
Improve unit tests coverage for quoting-service (part 2)

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#1047]
## **Goal**:
As a ML OSS code-base maintainer
I want to provide full unit test coverage for Quote Model script
so that the code-quality needed for quoting-service can be achieved and maintained

**Tasks**:
- [x] Provide full unit tests coverage for model/quotes.js
    - [x] handleQuoteError
    - [x] handleQuoteGet
    - [x] forwardQuoteGet
    - [x] handleException
    - [x] sendErrorCallback
    - [x] checkDuplicateQuoteRequest
    - [x] checkDuplicateQuoteResponse
    - [x] removeEmptyKeys
    - [x] calculateRequestHash
    - [x] generateRequestHeaders
    - [x] writeLog

**Acceptance Criteria**:
- [ ] Full unit tests coverage for Quote Model
- [ ] Unit Tests pass

## **Pull Requests**:
- [ ] https://github.com/mojaloop/quoting-service/pull/108

## **Follow-up**:
- N/A

**Dependencies**:
- [x] #1027
- [x] #1041

## **Accountability**:
- Owner: 
- QA/Review: @rmothilal, @mdebarros

**Comment by lewisdaly** [comment]
@ggrg @oderayi I'd like to take this one up if noone else is atm

**Comment by ggrg** [comment]
Sure @lewisdaly, go ahead. Please, make sure you use jest mocking capabilities. Thanks.
