### ISSUE TITLE
Add an onboarding checklist to the mojaloop documentation 

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1048]
## **Goal**:
As an OSS Maintainer
I want to add an onboarding checklist to the mojaloop documentation
to make the process of onboarding new community members easier

**Tasks**:
- [x] Add a new onboarding checklist (modeled on the OSS core team checklists) to the mojaloop documentation repo

**Acceptance Criteria**:
- [x] Documentation changes follow guidelines

## **Pull Requests**:
- [x] https://github.com/mojaloop/documentation/pull/168

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: @kjw000
