### ISSUE TITLE
Refactor FspEndpointTemplates in central-services-shared and other affected services

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1052]
## **Goal**:
As an OSS Maintainer 
I want to refactor template variables in `FspEndpointTemplates` 
to ensure consistency and intuitiveness in the naming of the variables in central-services-shared library and across all affected repositories.

**Tasks**:
- [x] In central-services-shared `src/enums/endpoints.js` standardize all placeholders to use camelCase  e.g `{{ID}}` should be `{{id}}`
- [ ] Make a release for central-services-shared
- [ ] refactor each service that uses those endpoints enumeration to use the new 
- [ ] Update following services to use the newly released central-services-shared and ensure all tests pass:
  - [ ] ALS
  - [ ] ML-API-Adapter
  - [ ] Quoting Service
  - [ ] Transaction Requests Service

**Acceptance Criteria**:
- [ ] Swagger definitions are updated, where applicable.
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @oderayi @ggrg 
- QA/Review: @rmothilal @mdebarros

**Comment by elnyry-sam-k** [comment]
not prioritized for v13.1.0 (or for core v1.0)
