### ISSUE TITLE
Provision Performance Environment - Alternate (IaC / repeatable)

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1055]
## **Goal**:
As Ops
I want to _setup an environment for performance testing on a mojaloop Switch (core) using IaC components_
so that _missing pieces can be identified and addressed_ for end-to-end perf testing to be done and for the process to be repeatable.

**Tasks**:
- [ ] IAC environmen
    - [ ] document steps (on-going)
    - [ ] a. test environment:
        - [x] a. configure for full deployment (gateway, add-ons, mojaloop, jmeter)
        - [x] b. provision k8s cluster and deployments
            - mojaloop
            - mcm
            - wso2
            - jmeter
        - [x] c. provision simulators ~ @mdebarros 
            - 4x simulators (DFSPs)
        - [ ] b. finish configurations
            - Certificates
            - Gateway
            - DFSP tokens    
            - simulators
            - switch
        - [ ] c. configure simulator & switch for tests
            - account lookup
            - quoting
            - transfers
        - [ ] d. execute tests via the simulators
    - [ ]  b. initial perf environment (no security):
        - [ ] a. configure for initial perf deployment 
            - exclude gateway, add-ons (mcm)
            - include mojaloop, jmeter
        - [ ] b. provision k8s cluster and deployments
            - mojaloop
            - jmeter
        - [ ] c. provision simulators
            - 4x simulators (DFSPs)
        - [ ] d. finish configurations
            - simulators
            - switch
        - [ ] e. configure simulator & switch for tests
            - account lookup
            - quoting
            - transfers
        - [ ] f. execute tests via the simulators
    - [ ] c. Secured perf environment (full security):
        - Future story to be created
- [ ] Simulators ~ @mdebarros
    - [ ] Helm scripts for deployment
    - [ ] Helm Values config for deployment
    - [ ] Update IAC for Simulator cluster?

**Acceptance Criteria**:
- [ ] Provision documented
- [ ] Perf PI8 Presentation up-to date
- [ ] IAC Scripts & Configure to enable a repeatable deployment of the provisioning of a Performance Environment
- [ ] Steps/instructions on how to configure IAC Performance Environment for test/perf use-cases
- [ ] The following deployments are operational
    - [ ] EFK
    - [ ] Promfana
    - [ ] Event-Stream-Processor
    - [ ] Mojaloop
-  JMeter
    - [ ] JMeter cluster running externally to the Perf environment
    - [ ] JMeter cluster able to execute Jmeter scripts remotely in a clustered mode
- Simulator
    - [ ] Simulator is deployable
    - [ ] Simulator has been tested with IAC setup/installation
-  Successfully execute QA scripts for the following
    - [ ] QA Golden Path Tests

## **Pull Requests**:
- TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by kjw000** [comment]
@mdebarros - is this blocked because you are waiting on IaC scripts?

**Comment by elnyry** [comment]
@kjw000 we currently have an existing performance environment; We have #1056 in progress that includes setting up mojaloop-simulator based simulators on that envt. Once that is done, #1055 will happen in parallel with the performance testing effort.

**Comment by mdebarros** [comment]
Moved this to blocked as we are able to continue with the existing Perf1 environment. We will re-look at this at a later stage once we need to test the full IAC Lab environment.
