### ISSUE TITLE
Deploy Mojaloop Simulator for Perf Testing

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1056]
## **Goal**:
As Ops
I want to _setup an environment for performance testing on a mojaloop Switch (core) using IaC components_
so that _missing pieces can be identified and addressed_ for end-to-end perf testing to be done and for the process to be repeatable.

**Tasks**:
- [x] Add an architecture diagram to show the components involved (JMeter, core ML, ml-sims)
- [x] 1. Temp environment for 2x DSPs:
    - [x] document steps (on-going)
    - [x] a. test environment:
        - [x] a. setup simulator for dfsp1
            - create machine
            - deploy using docker-compose
        - [x] b. setup simulator for dfsp2
            - create machine
            - deploy using docker-compose
        - [x] c. configure simulator & switch for tests
            - account lookup
            - quoting
            - transfers
        - [x] d. execute tests via the simulators
- [x] 2. Temp environment for additoinal 2x DSPs:
    - [x] a. setup simulator for dfsp3
        - create machine
        - deploy using docker-compose
    - [x] b. setup simulator for dfsp4
        - create machine
        - deploy using docker-compose
    - [x] c. configure simulator & switch for tests
        i. account lookup
        ii. quoting
        iii. transfers
    - [x] d. execute tests via the simulators
- [x] Create postman collection as an example
- [x] Update existing JMeter scripts to use the SDK-Scheme-Adapter Outbound API

**Acceptance Criteria**:
- [x] Provision documented
- [x] Perf PI8 Presentation up-to date
- [x] Steps/instructions on how to deploy/configure Simulators on Temp Performance Environment for test/perf use-cases
- [x] The following deployments are operational
    - [x] EFK
    - [x] Promfana
    - [x] Event-Stream-Processor
    - [x] Mojaloop
    - [x] sdk-scheme-adapter
    - [x] mojaloop-simulator
-  JMeter
    - [x] JMeter cluster running externally to the Perf environment
    - [x] JMeter cluster able to execute Jmeter scripts remotely in a clustered mode
- Simulator
    - [x] Simulator is deployable
    - [x] Simulator has been tested with Docker-compose
    - [x] 2x DFSPs have been setup and tested
    - [x] 4x DFSPs have been setup and tested
-  Successfully execute QA scripts for the following
    - [x] end-to-end transfer with ALS and Quoting included.
    - [x] end-to-end transfer tested against 2x DFSPs
    - [x] end-to-end transfer tested against 4x DFSPs
- [x] Postman collection containing example requests
- [x] Updated JMeter scripts that uses the SDK-Scheme-Adapter Outbound API

## **Pull Requests**:
- [x] https://github.com/mojaloop/pi8-perf-testing/pull/2

## **Follow-up**:
- #1071 

**Dependencies**:
- [ ] #1036 

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
