### ISSUE TITLE
Expand Test coverage and move to Jest for Transaction Request Service

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1057]
## **Goal**:
As an OSS Maintainer, 
I want to expand the test coverage of the tx request service and migrate to jest
to improve the quality of the codebase

**Tasks**:
- [ ] move existing unit tests over to jest
- [ ] make test coverage meet OSS Standards 

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/transaction-requests-service/pull/9

## **Follow-up**:
- fix the branch rules on `transaction-request-service` to require the unit tests and coverage before allowing PR merges

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
