### ISSUE TITLE
Instrumentation of ALS

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1058]
## **Goal**:
As an OSS Maintainer
I would like to refactor ALS to add metrics to all processes within ALS to allow for Prometheus dashboards.

**Tasks**:
- [ ] ~Refactor current sendRequest to follow a Model framework~
- [x] Create metrics standards and naming conventions for ALS
- [x] Add metrics to all ALS processes to support Prometheus
- [x] Update tests
- [x] Ensure test coverage meets required threshold

**Acceptance Criteria**:
- [x] ALS is refactored to support Prometheus and monitoring metrics

## **Pull Requests**:
- [x] https://github.com/mojaloop/account-lookup-service/pull/286

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rmothilal 
- QA/Review: @mdebarros @rmothilal @elnyry
