### ISSUE TITLE
Update sdk-scheme-adapter to support ML core deployment (without an API Gateway)

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1059]
## **Goal**:
As a ML OSS Community member
I want to _update [sdk-scheme-adapter](https://github.com/mojaloop/sdk-scheme-adapter)_
so that _it can be used in various scenarios that involve a Core ML Switch without an API Gateway_

**Tasks**:
- [x] Update peer endpoint to support 3 separate URLs for ALS, quoting-service, transfers
   - [x] Update sdk-scheme-adapter
   - [x] Update sdk-standard-components
- [x] PR Reviews
   - [x] sdk-scheme-adapter
   - [x] sdk-standard-components
- [x] Releases
   - [x] sdk-scheme-adapter
   - [x] sdk-standard-components

**Acceptance Criteria**:
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] A Release for sdk-scheme-adapter and sdk-standard-components is made (along with supporting services) that supports using separate URLs for quotes, transfers and ALS making it viable to use it with a Core ML Switch deployment with a Gateway.

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/75
- [x] https://github.com/mojaloop/sdk-standard-components/pull/23

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

## Releases
 - https://github.com/mojaloop/sdk-scheme-adapter/releases/tag/v8.5.1
 - https://github.com/mojaloop/sdk-standard-components/releases/tag/v8.4.0

**Comment by vijayg10** [comment]
These changes are available in the following release of the scheme adapter
https://github.com/mojaloop/sdk-scheme-adapter/releases/tag/v8.5.1
Please observe the local.env file
