### ISSUE TITLE
Core Service dependency and repo tidy up

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1060]
## **Goal**:
As an `OSS Maintainer`
I want to `tidy up the config files for core services` 
to ensure the `project is free from unused dependencies, unnecessary config etc.`

**Tasks**:
Go though all core services config files (namely `package.json`, `default.json`, `.nycrc.yml`), and `tsconfig.js` and `jest.config.js` if relevant.

Ensure:
- remove unused dependencies and devdependencies
- ensure consistency between `npm run` commands and remove unused commands
- ensure formatting and order is consistent
- remove redundant or unsed configurations

Apply the above for:
- [ ] account-lookup-service
- [ ] bulk-api-adapter
- [ ] central-ledger
- [ ] central-settlement
- [ ] ml-api-adapter

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- This ticket just covers core-services, but we should follow up by going over all repos at a later date

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: @elnyry

**Comment by elnyry-sam-k** [comment]
some clean up done as part of node upgrade in PI-19; closing this..
