### ISSUE TITLE
Update Event Framework tests in dedicated postman collection to match master-span changes

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1061]
## **Goal**:
As a QA tester I want to update the event framework postman collection tests for transfers so that they cover the changes, introduced by stories https://github.com/mojaloop/project/issues/1013 https://github.com/mojaloop/project/issues/1039 and fixes introduced by https://github.com/mojaloop/project/issues/1034.

**Tasks**:
- [ ] update event framework post man tests and confirm following conditions
  - [ ] Check transfer Prepare & Fulfil Abortted Commit
    - [x] Manual Check
    - [ ] Identify events in Kibana
    - [ ] Update Postman script and test
  - [ ] Check Transfer Prepare Error - Invalid FSP
  - [ ] Check Transfer Prepare Error - Position Limit Breach
  - [ ] Check Transfer Prepare Error - Timeout abort
  - [ ] Check Transfer Fulfil
  - [ ] Check Transfer Prepare & Fulfil Successful Commit
- [ ] Implement the POC built from story https://github.com/mojaloop/project/issues/1063

**Acceptance Criteria**:
- [ ] All postman test pass for event framework tests

## **Pull Requests**:
- [ ] 

## **Follow-up**:

**Dependencies**:
- [ ] https://github.com/mojaloop/project/issues/1063

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
