### ISSUE TITLE
Instrumentation of sdk-scheme-adapter

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1062]
**Goal**:
As a Hub Tech Operator or Hub DevOps
I would like the _add instrumentation to the mojaloop-simulator_
to enable operational monitoring and identify status/metrics and issues if any.

**Tasks**:
- [x] Add metrics to sdk-scheme-adapter to enable instrumentation
    - [x] Add event-instrumentation (Outbound API)
    - [x] Add prometheus instrumentation (Inbound + Outbound APIs)
- [x] Add support for Trace headers
     - [x] Update Inbound  (Mojaloop Spec) API to handle Trace Headers
- [ ] ~Validate~ --> followup validation in #1073 
- [x] QA - Tests if needed

**Acceptance Criteria**:
- [x] Instrumentation for metrics is added to the sdk-scheme-adapter

**PRs**:
- TBD

**Dependencies**:
- [ ] 

**Accountability**:
- Owner 
- QA/Review @rmothilal @mdebarros
