### ISSUE TITLE
Expand Event Framework tests to verify correct span tree

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1063]
## **Goal**:
As a Hub Operator I want to extend the event framework postman test collection so that we can verify are the spans linked as expected

**Tasks**:
- [ ] Create a list of service names ordered by parent-span relation
- [ ] Create expectations for all scenarios currently in the collection

**Acceptance Criteria**:
- [ ] Tests verifying the correct span tree is created are passing

## **Pull Requests**:
- [ ]

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
