### ISSUE TITLE
Service for schema validation based on a given Open API Spec (Mojaloop)

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1067]
## **Goal**:
As an FSP
I want to _run a service that can take as input a Mojaloop Spec version and provide Schema validation feature_
 so that _I can use it for self-testing_ to ensure my services follow the Rules / Schema definitions provided in a particular Mojaloop FSPIOP Spec.

**Tasks**:
- [x] Compare packages / libraries that provide mock service feature
- [x] Develop service to perform Schema validation based on a given API Specification
- [x] Use Mojaloop FSPIOP API quotes service as a starting point to provide Schema validation
- [x] Extend Schema validation for account-lookup and transfers calls
- [x] Version negotiation as specified in section 3.3.4 of the API Definition v1.0
- [x] Accept header validation
- [x] Review
- [x] Demo
- [x] Write unit tests 
- [x] Change the default error format from the library to match our API
- [x] Add test cases in postman collection for the remaining endpoints
- [x] Fix logger and log the requests, responses, and errors with verbosity
- [x] Write integration tests
- [x] Make the tool work in Windows OS as well. (Fixed an issue with windows line endings)
- [x] Write some documentation for running and testing this tool

**Acceptance Criteria**:
- [x] A service that can be run locally which provides Schema validation based on specific versions of Mojaloop FSPIOP API is made available.
- [x] A service that can be run locally and provides for version negotiation as described in the API Definition v1.0 document is made available.

## **Pull Requests**:
- [ ] https://github.com/mojaloop/ml-self-testing-toolkit

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 , @elnyry 
- QA/Review: @MichaelJBRichards , @elnyry
