### ISSUE TITLE
Customize sdk-scheme-adapter to work without quotes for perf testing

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1068]
## **Goal**:
As an Ops team member
I want to _customize sdk-scheme-adapter to allow transfers without quotes_
so that _it can be used for (perf) testing purposes_

**Tasks**:
- [x] Use config to allow transfers happen without a corresponding quote
- [x] Refactor the code to be able to merge it in master branch
- [x] Change the mojaloop-simulator to remove the dependency on quote in transfer request
- [x] Raised and merged the changes to pi8-perf branch and tested in perf environment for both mojaloop-simulator and sdk-scheme-adapter
- [x] Raise the PR to mojaloop-simulator:master
- [x] Raise the PR to sdk-scheme-adapter:master
- [x] Add unit tests to cover the change in mojaloop-simulator
- [x] Add unit tests to cover the change in sdk-scheme-adapter

**Acceptance Criteria**:
- [x] sdk-schemd-adapter is updated to allow transfers without a corresponding quote call to allow using it in PI8 performance testing

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/84
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/86
- [x] https://github.com/mojaloop/mojaloop-simulator/pull/17
- [x] https://github.com/mojaloop/mojaloop-simulator/pull/19
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/90
## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Notes**:
- Currently, a transfers call made without a corresponding quotes call is declined by mojaloop-simulator / scheme adapters
- However, for PI8 performance testing, the goal was to test transfers first to compare performance of the current system with the one demonstrated at Phase-3 kickoff. 
- For this to happen, we need to skp lookup and quotes requests for the time-being so that the TPS and other metrics are not affected.
