### ISSUE TITLE
Self-testing toolkit characteristics 0.5

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1069]
## **Goal**:
As an FSP / Hub
I want to _understand the characteristics of a self-testing toolkit provided by ML OSS_
so that _I can make an informed decision on how to use it_

**Tasks**:
- [x] Draft current understanding of tool-kit
- [ ] Review document with PDP dev sqaud
- [ ] Publish characteristics document that explains the self-testing toolkit (v0.5)

**Acceptance Criteria**:
- [ ] A draft document that describes the characteristics of the ML OSS Self-testing toolkit is made available to the community (that can be used by FSPs and Hub implementers)

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

## Characteristics currently identified:
1. Version negotiation (using Accept, Content-Type headers) provided as per the API Definition v1.0 Section **3.3.4**
2. Schema Validation provided based on the specific version of the API (v1.0, v1.1, v2.0 etc - only v1.0 active for now)
3. Validation of incoming requests based on **Rules**, after the Schema validation
4. Generate dynamic callbacks based on incoming requests using Rules (with capability to generate values at field/object level and not hard-coded)
5. Validate association of a transfer request with an existing quote (configurable to disable)
6. JWS validation and generation and support TLS
