### ISSUE TITLE
Upgrade mojaloop helm charts to use helm version 3.0.0

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1070]
## **Goal**:
As a maintainer of ML OSS
I want to _upgrade helm charts to version 3.0.0_
so that _the latest features in helm 3.0.0 can be used_ and _to ensure that the charts are up-to-date_

**Tasks**:
- [x] Upgrade mojaloop helm charts to helm 3.0.0
  - [x] Get background information regarding migration requirement, steps and potential issues [@oderayi]
  - [x] Update charts to Helm v3 [@oderayi] 
  - [x] Local simulation/test of the process [@oderayi]
  - [x] Investigate backward compatibility with Helm v3 with existing charts (i.e. without changes, with default values) [@oderayi] 
       >_Helm 3 client was used to successfully deploy current master branch of helm charts with no noticeable issues (with default values)._
  - [x] Try out v3 helm charts PR in dev environment [@oderayi]
     > Deployment was successful.
  - [ ] Fix https://github.com/mojaloop/helm/issues/219 (for NetworkPolicy, PodSecurityPolicy, DaemonSet, Deployment, StatefulSet, and ReplicaSet - Ingress for now until OSS dev environment is upgraded/and 1.20.x has wider adoption) 
  - [x] PR reviews/updates
  - [x] Fix issues/test
  - [x] Deploy to Dev2
  - [x] Validate with GP tests & Fix issues observed in Dev2 if any
  - [x] Validate downgrading locally to helm v2 and manage helm2 deployments
    > Helm 2 client was used successfully alongside Helm 3 client to deploy and manage Helm 2 deployments

**Acceptance Criteria**:
- [x] Mojaloop helm charts are available for helm version 3.0.0

## **Pull Requests**:
- [ ] https://github.com/mojaloop/helm/pull/285

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@elnyry is there any need here to support both Helm v2 and v3 at the same time? Or is it not worth worrying about?

**Comment by elnyry** [comment]
@lewisdaly Its worth worrying about sure ;-), but I think we need to keep things manageable for the core team. Taking that into consideration, I'm thinking the core team will focus on v3, whereas any volunteers from the Community can look into supporting v2, if there is a real need for it.

**Comment by mdebarros** [comment]
> @lewisdaly Its worth worrying about sure ;-), but I think we need to keep things manageable for the core team. Taking that into consideration, I'm thinking the core team will focus on v3, whereas any volunteers from the Community can look into supporting v2, if there is a real need for it.

I think we may need to think how best to do this. Perhaps we need a new helm repo for v3, allowing for v2 to remain in the current repo...assuming that we cannot support both v2 and v3 from the same code-base/repo.

**Comment by mdebarros** [comment]
Outcome of this investigation:
- Identified that Helm v3 is backward compatible with Helm v2 charts. 
- Helm v2 and v3 are independent and will still need to be used to respectively manage their deployments.
- Migration of existing deployments from Helm v2 to Helm v3 can be done using the following plugin: https://github.com/helm/helm-2to3 (this has not been tested)

**Comment by kjw000** [comment]
Are we going to update this story?

**Comment by elnyry** [comment]
Documentation to be followed-up in #1283

**Comment by lewisdaly** [comment]
@elnyry what's the plan here regarding support for both helm 2 and helm 3 support. The linked PR says [DO NOT MERGE]?

**Comment by lewisdaly** [comment]
From what I've been able to see, we can still deploy helm2 charts with helm3. So the only thing we need to do in the master branch is update the install instructions with helm3.

In terms of having a separate helm repo for v3, as @mdebarros suggests, I think it's a good idea, as long as both _helm_ repos can be updated easily from the same _github_ repo.

**Comment by elnyry** [comment]
@lewisdaly - wanted to get a consensus regarding support for helm2/3 before merging, hence the notice, not to merge before that. However, I think we're leaning towards going ahead with the merge now..

**Comment by lewisdaly** [comment]
Cool. Thanks for the update.
