### ISSUE TITLE
Perf1 Env: Testing & Validation - Sprint8.6

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1073]
## **Goal**:
As Ops
I want to _setup an environment for performance testing on a mojaloop Switch (core)_
so that _missing pieces can be identified and addressed_ for end-to-end perf testing to be done.

**Tasks**:
- Simulators:
    - [x] Configure & Test SDK-Scheme-Adapters + Mojaloop Simulator to only send Transfers (no Party or Quote requests) ~ [ @mdebarros, @vijayg10 ]
        - [x] simfsp01
        - [x] simfsp02
        - [x] simfsp03
        - [x] simfsp04
    - [x] Configure & Test SDK-Scheme-Adapters + Mojaloop Simulator to only send Transfers (no Party or Quote requests) ~ [ @mdebarros, @rmothilal ]
- Monitoring --> now tracked in #1111
- SDK-Schema-Adapter:
    - [x] Temporary remove trace injection into POST Transfers for inbound API request [ @mdebarros ]
    - [x] Fix Redis Connection Leak bug - https://github.com/mojaloop/project/issues/1088 [ @yosheeck , @bushjames ]

**Acceptance Criteria**:
- [ ] ~Documentations are up-to date~
- [ ] ~Perf1 Environment is ready to be used for Performance Test~
- [x] Test runs done on perf1 envt, issues uncovered are logged and fixed
- [x] Follow-up issue created to continue effort to achieve a working perf envt. (#1111)

## **Pull Requests**:
- N/A

## **Follow-up**:
- N/A

**Dependencies**:
- [x] https://github.com/mojaloop/project/issues/1068
- [ ] https://github.com/mojaloop/project/issues/1076
- [x] https://github.com/mojaloop/sdk-scheme-adapter/issues/97 [@ramirogm ]

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
