### ISSUE TITLE
Self-testing toolkit: Design callbacks to respond dynamically (Swagger, Rules)

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1074]
## **Goal**:
As an FSP
I want to _understand how the self-testing toolkit works, architecturally_
so that _I can use it appropriately for validating my implementation_

**Tasks**:
- [x] Identify components needed to dynamically generate callbacks
- [x] Design architecture using a Rules component for dynamic generation of callbacks
- [x] Flow diagram
- [x] Architecture diagram
- [x] Review the diagrams
- [x] Design the JSON format of callback generation file
- [x] Design the JSON format of additional validation file
- [x] Explore the code of scheme adapter and mojaloop simulator
- [x] Publish architecture & flow diagrams

**Acceptance Criteria**:
- [x] A design depicting the use of various components needed for the self-testing toolkit is published. This story is focussed particularly on the generation of callback messages dynamically using Rules

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
