### ISSUE TITLE
Helm Release v8.7.0: Updates to helm, Supporting QA, Fixes, Releases

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1075]
## **Goal**:
As a ML OSS Code base maintainer
I want to _validate and make a Helm release in PI8 (Sprint 8.7) that is successfully validated by the Golden path tests_
so that _down stream entities can take and use a version of Mojaloop Switch services bundle that is tested and contains latest features and enhancements (added in and PI8(Sprints 8.4, 8.5, 8.6, 8.7) so far)_ 

This specific story is for making necessary changes for supporting Deployment, QA, Fixes, Integration and performing end-to-end testing for all the changes made since Helm v8.4.0

**Tasks**:
- [x] Initial PR with changes for v8.7.0 [@elnyry , @mdebarros ]
- [x] Helm Deployment of changes corresponding to changes done to config (default.json) since helm v8.4.0
  - [x] Deploy, validate, fix issues, redeploy
  - [x] With stable deployment test Golden path
- [x] Validation using Golden path regression tests etc on Dev2
- [x] Identify issues with QA Scripts if any - fix them and retest
- [x] Identify Bugs, log them (event-sdk issue - comment below, #1116 , #1117 , #1118 )
- [x] Fix bugs logged (event-sdk release made, #1116 , #1117 , #1118 )
- [x] Helm v8.7.0 released (https://github.com/mojaloop/helm/releases/tag/v8.7.0 )
- [x] Deployment of released Helm v8.7.0 on **Dev2**
- [x] Validation using Golden path regression tests etc on Dev2
- [x] Deployment of released Helm v8.7.0 on **Dev1**
- [x] Validation using Golden path regression tests etc on Dev1

**Acceptance Criteria**:
- [x] Helm v8.7.0 is released after testing on dev2
- [x] Helm v8.7.0 is deployed on AWS Dev2 without issues
- [x] QA (Golden path) on deployments done on AWS dev2 environment is done
- [x] Bugs are logged based on observations, failures
- [x] Bugs logged are fixed to make subsequent releases in individual services (or Helm)
- [x] All the changes needed for supporting v8.7.0 of Helm (List out major changes in release notes once release is ready)

**Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/232

**Follow-up**:
- N/A

**Dependencies**:
- [ ] TBD

**Accountability**:
- Owner: 
- QA/Review: Core team

**Comment by elnyry** [comment]
blocked until we can release a new version of the event-sdk. Currently blocked with the below error during a deployment with the un-published version
```
2019-12-09T12:30:20.994Z - error: uncaughtException: ENOENT: no such file or directory, open '/opt/central-ledger/node_modules/@mojaloop/event-sdk/protos/message_type.proto'
12/9/2019 6:00:20 PM Error: ENOENT: no such file or directory, open '/opt/central-ledger/node_modules/@mojaloop/event-sdk/protos/message_type.proto'
12/9/2019 6:00:20 PM at Object.openSync (fs.js:438:3)
12/9/2019 6:00:20 PM at Object.readFileSync (fs.js:343:35)
12/9/2019 6:00:20 PM at fetch (/opt/central-ledger/node_modules/protobufjs/src/root.js:160:34)
12/9/2019 6:00:20 PM at Root.load (/opt/central-ledger/node_modules/protobufjs/src/root.js:194:13)
12/9/2019 6:00:20 PM at Root.loadSync (/opt/central-ledger/node_modules/protobufjs/src/root.js:235:17)
12/9/2019 6:00:20 PM at Object.loadSync (/opt/central-ledger/node_modules/@mojaloop/event-sdk/node_modules/@grpc/proto-loader/build/src/index.js:221:27)
12/9/2019 6:00:20 PM at Object.loadEventLoggerService (/opt/central-ledger/node_modules/@mojaloop/event-sdk/dist/transport/EventLoggerServiceLoader.js:32:41)
12/9/2019 6:00:20 PM at new EventLoggingServiceClient (/opt/central-ledger/node_modules/@mojaloop/event-sdk/dist/transport/EventLoggingServiceClient.js:47:61)
12/9/2019 6:00:20 PM at Object.<anonymous> (/opt/central-ledger/node_modules/@mojaloop/event-sdk/dist/Span.js:23:45)
12/9/2019 6:00:20 PM at Module._compile (internal/modules/cjs/loader.js:701:30)
12/9/2019 6:00:20 PM at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
12/9/2019 6:00:20 PM at Module.load (internal/modules/cjs/loader.js:600:32)
12/9/2019 6:00:20 PM at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
12/9/2019 6:00:20 PM at Function.Module._load (internal/modules/cjs/loader.js:531:3)
12/9/2019 6:00:20 PM at Module.require (internal/modules/cjs/loader.js:637:17)
12/9/2019 6:00:20 PM at require (internal/modules/cjs/helpers.js:22:18)
12/9/2019 6:00:20 PM at Object.<anonymous> (/opt/central-ledger/node_modules/@mojaloop/event-sdk/dist/Tracer.js:7:16)
12/9/2019 6:00:20 PM at Module._compile (internal/modules/cjs/loader.js:701:30)
12/9/2019 6:00:20 PM at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
12/9/2019 6:00:20 PM at Module.load (internal/modules/cjs/loader.js:600:32)
12/9/2019 6:00:20 PM at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
12/9/2019 6:00:20 PM at Function.Module._load (internal/modules/cjs/loader.js:531:3)
12/9/2019 6:00:20 PM at Module.require (internal/modules/cjs/loader.js:637:17)
12/9/2019 6:00:20 PM at require (internal/modules/cjs/helpers.js:22:18)
12/9/2019 6:00:20 PM at Object.<anonymous> (/opt/central-ledger/node_modules/@mojaloop/event-sdk/dist/index.js:28:18)
12/9/2019 6:00:20 PM at Module._compile (internal/modules/cjs/loader.js:701:30)
12/9/2019 6:00:20 PM at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
12/9/2019 6:00:20 PM at Module.load (internal/modules/cjs/loader.js:600:32)
```
