### ISSUE TITLE
Validate Kibana dashboard

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1076]
## **Goal**:
As Hub Tech Ops
I want to be able to *vallidate, extend and troubleshoot if necessary* the Kibana dashboard created by story #1000 

**Tasks**:
- [ ] Validate if all stored in central-ledger database transactions for period of time are visualized in the Kibana dashboard and APM
    - [ ] Number of successful requests within a time period
    - [ ] Number of failed/incomplete requests within a time period

**Acceptance Criteria**:
- [ ] Designs are up-to date

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- #1000 

## Accountability:
- Owner: @vgenev 
- QA/Review: TBC
## Notes
- sample query for check the number of transactions for a period of time and status
```
select count(distinct transferId)
FROM central_ledger.transferStateChange
where timestamp(createdDate) between timestamp('2019-11-21 10:00:00') and timestamp('2019-11-21 19:40:00') and transferStateId = 'COMMITED'
ORDER BY (createdDate) DESC limit 1;
```

**Comment by elnyry-sam-k** [comment]
outdated issue
