### ISSUE TITLE
Provide / Troubleshoot 'helm upgrade' option

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1077]
## **Goal**:
As Tech/Dev Ops
I want to _ensure the `helm upgrade` for mojaloop helm versions works
so that _FSP implementers, Hubs, interested parties can make use of the upgrade option with Helm_

**Tasks**:
- [ ] Try `helm upgrade` option to upgrade to latest version of helm from previous version
- [ ] Document issues that arise out of this, troubleshoot
- [ ] Log bugs to be resolved and make `helm upgrade` option to work

**Acceptance Criteria**:
- [ ] `helm upgrade` option is available to upgrade for a specified Mojaloop version from the previous helm release version
- [ ] Documentation is updated to use `helm upgrade` option with Mojaloop helm charts

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @mdebarros 

**Notes**:
- After resolving the issue, document the steps and the version of Helm from which `helm upgrade` is available for Mojaloop Helm
- Maintain an environment to test upgrade option moving forward once this issue is resolved.

**Comment by elnyry-sam-k** [comment]
This is now supported (upgrade is supported and tested with every official Helm release)
