### ISSUE TITLE
Auto-upload the license-summary file to the helm release

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1081]
## **Goal**:
As an OSS Maintainer, 
I want the license-scaner summary .xlsx to automatically be added to a release
for auditing and reporting purposes.

**Reference**
- Look at the github api for how to do this: https://developer.github.com/v3/repos/releases/#upload-a-release-asset

**Tasks**:
- [ ] Add the necessary config to CircleCI in the helm repo to automatically add the license summary file

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/230

## **Follow-up**:
- After the 8.5.0 release, check again to make sure this asset was uploaded as expected.

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
We should assess this again after the next helm release to ensure it was uploaded correctly.

**Comment by elnyry** [comment]
@lewisdaly validated on 8.7 and it looks good.. https://github.com/mojaloop/helm/releases/tag/v8.7.0

**Comment by lewisdaly** [comment]
Great! Thanks
