### ISSUE TITLE
Review Dockerfile Configuration and make recommendations in line with best practice(CIS)

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1082]
## **Goal**:
As an OSS Maintainer
I want to ensure we are following Dockerfile best practices
to improve the the quality and reliability of our docker images

**Description**:
The Center for Internet Security has a number of guidelines for writing dockerfiles in their [docker benchmark](https://mojaloop.slack.com/files/UFZAE2LT1/FQJKESQ20/cis_docker_community_edition_benchmark_v1.1.0.pdf), many of which are quite simple to implement.

Some recommendations relevant for our project are:
- create a non-root user
- update the base image to the latest node lts
- convert all images to multi-stage to reduce bloat
- enable --no-cache in docker build step to ensure we are always pulling in the latest images and security patches
- enable docker-content-trust (during build step?)
  - export DOCKER_CONTENT_TRUST=1
  - ref: https://docs.docker.com/engine/security/trust/content_trust/

**Tasks**:

- [ ] Apply the above for:
  - [ ] bulk-api-adapter
  - [ ] central-event-processor
  - [ ] central-ledger
  - [ ] central-settlement
  - [ ] email-notifier
  - [ ] ml-api-adapter
  - [ ] mock-pathfinder?
  - [ ] quoting-service
  - [ ] simulator?
  - [ ] mojaloop-simulator
  - [ ] central-directory?
  - [ ] central-end-user-registry?

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: TBC

**Comment by rasputtintin** [comment]
Hi Lewis, who can help me run the Docker-Bench script in OSS docker server?

**Comment by rasputtintin** [comment]
Sam to assist execute script across Dev environments.

**Comment by elnyry** [comment]
> Sam to assist execute script across Dev environments.

Done :-)

**Comment by godfreykutumela** [comment]
Hello @rasputtintin how are we doing this week on this one?

**Comment by lewisdaly** [comment]
@rasputtintin let me know when you need some help implementing and verifying some of these changes.

**Comment by rasputtintin** [comment]
Completed review of DockerBench script output. Key recommendations are around:
- Configuration Changes
- Enabling Audit
- User Review and Docker container permissions

See attached file. @lewisdaly @godfreykutumela we can have a chat on some of these recommendations as they will lead to additional stories involving infra teams.
[DockerBench Script Output.xlsx](https://github.com/mojaloop/project/files/4364908/DockerBench.Script.Output.xlsx)


Additional Manual Checks are also recommended.

**Comment by godfreykutumela** [comment]
Thanks @rasputtintin for completing and i have marked the story in progress for @lewisdaly and @elnyry to make final review before we can close.

When addressing the recommendation, i suggest we also explore how this process can be automated going forward.

**Comment by elnyry** [comment]
@godfreykutumela @rasputtintin - Thanks. I think we can now close this one, as we have the recommendations documented and published. We can now use other items to track the changes adopted and the refactoring needed.

**Comment by lewisdaly** [comment]
Thanks @rasputtintin. I've reviewed the doc, and already see some recommendations we can be applying. 

Perhaps we can sync up next week to talk through them and make some follow up stories to prioritize and implement these.
