### ISSUE TITLE
Event Framework: Integrate into Account-lookup-Service - Part2

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1086]
## **Goal**:
As a `Hub Operator` I want to `integrate Event Framework into Mojaloop components` so that `so that all events (errors, general, admin etc) can be audited and traced appropriately`

This is part-2 of the story

**Tasks**:
- [x] Review PR (#139)
- [ ] Integrate SDK for logging  [ ? ]
  - [x] account-lookup-service
    - [x] Integrate into health end-points for Event Sidecar (if sidecar is enabled)
    - [x] Recording
    - [x] Logs (replace existing logs)
- [x] Add event and action needed for Event Framework integration into ALS

**Acceptance Criteria**:
- [x] Designs are up-to-date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment configs.
- [x] Event Framework integrated into Account-Lookup-Service
	- [x] Ensure that components cannot operate without Sidecar functioning correctly when enabled
	- [x] Ensure that components will not startup without Sidecar when enabled
	- [x] Sidecar can be disabled for local development and/or debugging purposes only

## **Pull Requests**:
- [x] https://github.com/mojaloop/account-lookup-service/pull/139
- [x] https://github.com/mojaloop/central-services-shared/pull/138

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by gibaros** [comment]
Closing this issue now that ALS and central-services-shared PRs have been approved, merged and closed.
