### ISSUE TITLE
SDK Redis connection management improvements

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1088]
## **Goal**:
As a `Hub Operator`, I want to `improve the SDK Redis connection manager` so that `the SDK-Schema-Adapter can be utilised for Performance Testing`

**Tasks**:
- [x] setup local reproduction environment and reproduce the issue reliably
  Details in "reproduction setup" section
- [x] propose a fix,
  - [x] test it locally 
  - [x] and on perf environment
- [x] make sure all tests and other AC-s are fulfilled
- [x] update src/scheme-adapter.env in mojaloop-simulator with latest changes from sdk-scheme-adapter

**Acceptance Criteria**:
- [x] Unit Tests pass
- [x] Code Style & Coverage meets standards
- [x] Perf tests fixed (confirmed by @mdebarros)
- [x] SDK-Schema-Adapter is able to sustain a series of 25k transfers (1 thread) without suffering from connection leaks and can be used for performance testing
- [x] This resolves the following issue: https://github.com/mojaloop/sdk-scheme-adapter/issues/97

## **Reproduction Setup**:
- Reproduction setup overview:
![20191203_bug_1088_reproduction_flow](https://user-images.githubusercontent.com/3471171/70053843-37b0c780-15ce-11ea-8aa5-dc1af4cd5c77.png)
- There are updates needed in src/scheme-adapter.env - it's best to compare original, updated config in sdk-scheme against this file
- changes in port mapping in docker-compose.yml file are needed, as current settings don't reflect `scheme-adapter` ports setup
- it helps to set config of  `maxclients 100` on redis, to be able to quickly reproduce the issue
- this is node script I've used to trigger the issue [1088_spam.txt](https://github.com/mojaloop/project/files/3916818/1088_spam.txt) (the file extension is changed to .txt as github doesn't allow js files)

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/102 - the fix
- [x] https://github.com/mojaloop/mojaloop-simulator/pull/21 - cancelled config update
- [x] https://github.com/mojaloop/mojaloop-simulator/pull/23 - config update

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
Removing the blocker since the change is now done and merged
