### ISSUE TITLE
Propose Enhancement for TimeoutHandler to Allow Scaling and Avoid DB Deadlocks

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#1089]
## **Goal**:
As a *maintainer of the ML OSS codebase*
I want to *propose an enhanced processing of TimeoutHandler*,
so that *database deadlocks during performance testing are avoided and TimeoutHandler could be scaled*

**Tasks**:
- [x] Describe how current TimeoutHandler functions [@ggrg]
- [x] Describe the disadvantages that might be causing the deadlocks [@ggrg]
- [x] Plan how the TimeoutHandler might be enhanced [@ggrg]
- [x] Prepare DB schema enhancement [@ggrg]
- [x] Prepare sequence diagram(s) [@ggrg]
- [x] Discuss and validate with the team [@ggrg]
- [x] Resolve requests for changes and TODO items on the PRs

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Migrations and seeds are provided

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/515
- [x] https://github.com/mojaloop/documentation/pull/153

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
