### ISSUE TITLE
Generate and release documentation pdf automatically

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1090]
## **Goal**:
As an OSS developer
I want to automatically generate and attach the documentation as a pdf
so that others can easily access the documentation offline

**Tasks**:
For the `mojaloop/documentation` repo:
- [ ] go over existing .md -> .pdf scripts and automate inside of CircleCI 
- [ ] automatically attach the `.pdf` file to a given release
- [ ] ensure the correct licenses are included in the pdf

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: @kjw000

**Comment by lewisdaly** [comment]
It looks like the old tool, `dactyl` that we used in the past relies on a commercial tool, prince to convert to pdf. So perhaps this will be a little trickier than updating the old script.
