### ISSUE TITLE
Ensure there is a valid license.md file in every repo

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1091]
## **Goal**:
As an OSS Developer
I want a license file in every repo and a means to update them all en-masse
so that any license changes (as in with the Mojaloop Foundation) are easily propagated and maintained.

**Tasks**:
- [x] check the licenses in each repo, and ensure they are valid and match the requirements
- [x] write a script to update all licenses across all Mojaloop repos and open PRs easily

**Acceptance Criteria**:
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] All the repos on mojaloop GitHub org have the license file (same approved one)

## **Pull Requests**:
Most PRs are merged, but the following are failing for a variety of reasons:
- [ ] https://github.com/mojaloop/central-settlement/pull/247
- [ ] https://github.com/mojaloop/ml-api-adapter/pull/357
- [ ] https://github.com/mojaloop/forensic-logging-sidecar/pull/23

## **Follow-up**:
Follow up correct licences for the following repos
- sdk-mock-dfsp-backend
- sdk-scheme-adapter

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: @kjw000
