### ISSUE TITLE
Optimizing logs size in transfers critical path to improve performance, understand characteristics

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1092]
## **Goal**:
As an *FSP or Hub*
I want to *understand the size characteristics of transfers critical path*,
so that *it can help with performance testing and optimization*

**Tasks**:
- [x] Understand, assess log size in transfers critical path
- ~Optimize logs size where relevant and possible~ 
     - Current log content is optimal. 
     - Story to add async logging is already in progress.
- ~Recommendations~ 
- ~Verify logging to console for tracing (span) is configurable~
- [x] Discuss and validate with the team

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Logs size is recorded for transfers critical path [transfer prepare + fulfil path]

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @oderayi 
- QA/Review: @mdebarros

**Comment by oderayi** [comment]
Transfers: 
==========================================================================
- Prepare
  - Sizes:
    - ml-api-adapter:               `24.8kb`
      - Handler.create
          - span.audit
          - TransferService.prepare 
            - Kafka.Producer.produceMessage
            - snedRequest - Request and Response (headers, data, status)
      - Notification consumeMessage
          - span.audit
          - processMessage
    - central-ledger:               `30.4kb` 
    - simulator:                      `7.8kb`
     -----
                                    63kb
     ------               
---------------------------------------------------------------------------
- Fullfil
  - Sizes:
    - ml-api-adapter:               `21.4kb`
      - Handler.fullfilTransfer
          - span.audit
          - TransferService.fulfil 
            - Kafka.Producer.produceMessage
      - Notification.consumeMessage
          - span.audit
          - processMessage
          - trace
          - sendRequest - Request and Response (headers, data, status)
    - central-ledger:               `21.7kb` 
    - simulator:                     `2.8kb`
   ------
                               45.9kb
    -----
