### ISSUE TITLE
Alter DB schema to support for Request settlement by currency

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#1093]
## **Goal**:
As a core OSS team member
I want to change the existing database
so that the new DB model caters for Request settlement by currency

The scope of this story is to include all DB changes proposed by the **OSS Settlement BRD**, section 6.1 Request settlement by currency

**Tasks**:
- [x] Provide knex migration scripts [@ggrg]
  - [x] settlementWindowContent
  - [x] settlementWindowContentStateChange
  - [x] settlementContentAggregation
  - [x] settlementContentAggregationStateChange
    - [x] to be derived from settlementTransferParticipant
  - [x] Changes to support the settlement model [@ggrg]
    - [x] settlementDelay
    - [x] settlementInterchange
    - [x] settlementGranularity
    - [x] settlementModel
  - [x] Changes to existing tables [@ggrg]
    - [x] settlement
- [x] Provide seed values for all lookup and configuration tables [@ggrg]
- [x] Export ER diagram and have peer review and BRD validation [@ggrg]
- [x] Export DDL and ERD files [@ggrg]
- [x] Peer review and updates [@ggrg]
- [x] Present to DA [@ggrg] [link](https://github.com/mojaloop/design-authority/issues/40)

**Acceptance Criteria**:
- [x] Existing ERD is updated
- [x] Knex migration scripts are provided
- [x] Seeds are populated
- [x] The model is validated against the BRD
- [x] DB model is presented to the DA
- [x] Any changes, suggested by the DA are addressed
- [x] DB model is approved by the DA
- [x] Documentation is updated

## **Pull Requests**:
- [x] https://github.com/mojaloop/documentation/pull/144
- [x] https://github.com/mojaloop/central-ledger/pull/501

## **Follow-up**:
- #1094 

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
