### ISSUE TITLE
Provide SDs for all changes to the existing API (part 1)

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#1094]
## **Goal**:
As a core OSS team member
I want to update the stack of settlement related sequence diagrams (SDs)
so that Request settlement by currency is supported by Settlements API v2.

The scope of this story is to provide all SDs to accommodate for all changes referred in **OSS Settlement BRD**, section 6.1 Request settlement by currency.

**Tasks**:
- [x] Provide [sequence diagrams](https://github.com/mojaloop/documentation/blob/master/mojaloop-technical-overview/central-settlements/settlement-process/assets/diagrams/sequence) for Request settlement by currency
  - [x] 6.1.2. Close Settlement Window (closeSettlementWindow) [@ggrg]
    - [x] Validate and update following peer review [@ggrg]
  - [x] 6.2.1. Trigger Settlement Event (createSettlement) [@ggrg]
    - [x] Validate and update following peer review [@ggrg]
  - [x] 6.2.5. Acknowledgement of Settlement Transfer (updateSettlementById) [@ggrg]
- [x] Peer review and validation [@ggrg]
- [x] Present to DA [@ggrg]
- [x] Apply requested DA changes [@ggrg]

**Outside epic scope**:

List of sequence diagrams which are _not included_ in Request Settlement by Currency epic
- #1105 diagrams
- (new) Define a Settlement Model
- (new) Get Settlement Model By Id

**Acceptance Criteria**:
- [x] Existing SD stack is updated
- [x] SDs are approved by the DA
- [x] Documentation is updated

## **Pull Requests**:
- [x] https://github.com/mojaloop/documentation/pull/148

## **Follow-up**:
- [x] #1105

**Dependencies**:
- [x] #1093

## **Accountability**:
- Owner: @ggrg, @MichaelJBRichards
- QA/Review: DA

**Comment by ggrg** [comment]
@elnyry, @MichaelJBRichards - story is moved to Blocked until the peer review is made
