### ISSUE TITLE
Implement changes related to closeSettlementWindow

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#1095]
## **Goal**:
As a core OSS team member
I want to adapt existing codebase
so that closeSettlementWindow functionality works with the updated DB schema

The scope of this story is to implement **OSS Settlement BRD**, section 6.1.2.1 Change to code supporting closeSettlementWindow resource

**Tasks**:
- [x] Add PROCESSING and FAILED window states [@ggrg]
- [x] Reorganise/refactor scripts tree structure [@ggrg]
- [x] Dependencies upgrade [@ggrg]
- [x] Refactor server setup and init [@ggrg]
- [x] Add configs for producer and consumer to topic-settlementwindow-close [@ggrg]
- [x] Create SettlementWindowHandler [@ggrg]
- [x] Register SettlementWindowHandler [@ggrg]
- [x] SettlementWindowHandler CLI [@ggrg]
- [x] Implement closeSettlementWindow changes [@ggrg]
  - [x] Window state to PROCESSING [@ggrg]
  - [x] Produce message for async close [@ggrg]
  - [x] SettlementWindowHandler Processing [@ggrg]
    - [x] Generate records in settlementWindowContent [@ggrg]
    - [x] Generate records in settlementWindowContentStateChange [@ggrg]
    - [x] Generate records in settlementContentAggregation [@ggrg]
    - [x] Finalise closeSettlementWindow functionality [@ggrg]
    - [x] Retries and failure
- [x] Fix existing unit tests [@ggrg]
- [x] Fix existing integration tests [@ggrg]
- [ ] ~Unit testing to improve coverage~

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style meets standards
- [ ] ~Coverage meets standards~

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-shared/pull/162
- [x] https://github.com/mojaloop/central-ledger/pull/539
- [x] https://github.com/mojaloop/central-settlement/pull/220

## **Follow-up**:
- #1165

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @ggrg
- QA/Review: TBC
