### ISSUE TITLE
Change createSettlement API definition and validations

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#1096]
## **Goal**:
As a core OSS team member
I want to adapt existing codebase
so that createSettlement API resource is updated to cater for creating a settlement by currency and model. All checks for validating the payload are to be included here

The story refers to **OSS Settlement BRD**, section 6.1.2.2 createSettlement

**Tasks**:
- [x] Change swagger definition [@ggrg]
- [x] Modify handler [@ggrg]
- [x] Add validations [@ggrg]
- [x] Fix unit tests [@ggrg]

**Acceptance Criteria**:
- [x] All known pre-requisite validations for creating a settlement are implemented
- [x] Designs are up-to date
- [x] Unit Tests pass
- [ ] ~Integration Tests pass~
- [x] Code Style meets standards
- [ ] ~Coverage meets standards~

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-settlement/pull/224
- [x] https://github.com/mojaloop/central-ledger/pull/551

## **Follow-up**:
- #1097

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
