### ISSUE TITLE
Implement Update the progress of a settlement

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#1099]
## **Goal**:
As a core OSS team member
I want to adapt existing codebase
so that updateSettlementById resource is refactored to work with currency specific settlements

The story refers to **OSS Settlement BRD**, section 6.1.2.3 Updating the progress of a settlement

**Tasks**:
- [x] Refactor for settlementContentAggregation and settlementWindowContent [@ggrg]
- [ ] ~Change swagger definition to cater for changed response~ (already applied by #1096)
- [x] Verify implementation result [@ggrg]
- [x] Add QA notes to #1164 for functional testing
- [ ] ~Create follow-up story for unit tests coverage~ (updated #1171)

**Acceptance Criteria**:
- [x] Created settlements can be successfully moved to settled state
- [x] Designs are up-to date
- [x] Unit Tests pass
- [ ] ~Integration Tests pass~
- [x] Code Style meets standards
- [ ] ~Coverage meets standards~

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-settlement/pull/229

## **Follow-up**:
- #1100 
- #1164 
- #1171

**Dependencies**:
- #1097

## **Accountability**:
- Owner: @ggrg
- QA/Review: TBC
