### ISSUE TITLE
Request Settlement by Currency Wrap-up and QA

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#1100]
## **Goal**:
As a core OSS team member
I want to verify the completeness of the settlement process
so that all existing endpoints are functioning properly and quality meets standards

**Tasks**:
- [x] Unit tests coverage meets standards
  - [x] src/domain/settlement/index.js [@ggrg]
  - [x] src/models/lib/enums.js [@ggrg]
  - [x] src/models/settlement/facade.js [@ggrg]
  - [x] src/models/settlement/settlementModel.js [@ggrg]
  - [x] src/models/settlementWindowContent/facade.js [@ggrg]
  - [x] src/models/settlementWindowContent/settlementWindowContentStateChange.js [@ggrg]
  - [x] whatever is left after merging #1165
- [x] Integration Tests are adapted to the changed functionality [@ggrg]
  - [x] Release central-ledger settlement-v2 snapshot [@ggrg]
  - [x] Update integration configs [@ggrg]
  - [x] Ensure proper run on circleci [@ggrg]
- [x] Provide a demo for the delivered functionality [@ggrg]
- [ ] ~Provide updated Postman collection to be used by the QA for regression testing~ (#1164)
- [x] Summarise changes made to config to facilitate update of helm charts and other deployment config (see #1164, section QA Notes)
- [x] Update documentation [@ggrg]

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [ ] ~Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config~

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/564
- [x] https://github.com/mojaloop/central-settlement/pull/231
- [x] https://github.com/mojaloop/documentation/pull/159

## **Follow-up**:
- Changes made to config need to be added to helm charts after settlement-v2 is merged to master

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
