### ISSUE TITLE
Add flags and functionality for better support of tracestate headers 

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1102]
## **Goal**:
As a contributor I want to add functionality to Event SDK so that tracestate is used and supported according configuration.

**Tasks**:
- [x] Add flag for tracestate and traceparent support
- [x] Add tracestate and traceparent strings to the tags if the flag is operational and keep them updated with each child
- [x] Use the tags to inject context into HTTP header when injecting w3c standard headers
- [x] Persist tags when extracting context from HTTP header
- [x] Make sure that in all cases of outside or missing vendor information traces are correctly prepared @mdebarros @vgenev 
- ~[ ] Update Event Framework documentation~ --> #1102 

**Acceptance Criteria**:
- [x] Unit Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/event-sdk/pull/21

## **Follow-up**:
- #1102

**Dependencies**:
- N/A
## **Accountability**:
- Owner: @vgenev 
- QA/Review: @mdebarros
