### ISSUE TITLE
Explore sdk-scheme-adapter & mojaloop-simulator for rules, configurability to generate callbacks dynamically

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1103]
## **Goal**:
As an FSP
I want to _understand the capabilities of `sdk-scheme-adapter`_
so that _I can use it for testing to generate callbacks dynamically based on rules, configuraiton_

**Tasks**:
- [x] Explore sdk-scheme-adapter & mojallop-simulator to understand configurability, rules for callbacks and document observations
- [x] Plan next steps

**Acceptance Criteria**:
- [x] Observations regarding `sdk-scheme-adapter` & `mojaloop-simulator` regarding usage or rules, configurability are recorded so that it can help decide its usage with the self testing tool-kit for FSPs

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- As per the discussions with the team, we are not including the scheme adapter or simulator for the PoC because of the following reasons.
  - Version negotiation is not included
  - We need extended functionalities with Rules Engine which are not there in simulator as of now
  - We need two levels of Rules Engine. One for additional validation and second one for callback generation
  - We are not including the authentication and signing for the PoC
  - We need generation of mock requests and responses based on the openAPI
We definitely want to consider to include scheme adapter after PoC because of its JWS and signing capabilities which we want in self-testing toolkit.

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @elnyry @MichaelJBRichards

**Comment by vijayg10** [comment]
Explored the mojaloop-simulator for generating callbacks based on rules. My observations are as below.
* Support for multiple versions fo FSPIOP API:
  * ml-simulator doesn't support versioning and the callbacks are hardcoded. ml-self-testing-toolkit should support multiple versions and generate callbacks and responses dynamically.
* Callback generation based on the open API file:
  * There is no callback generation functionality from a given open API file
* Rules Engine (JRE):
  * The rules engine developed in ml-simulator is very basic. It just compares the request body and can respond with an entire callback body specified in the rules engine file. But we don't want to supply an entire callback body to the rules engine. We will supply only specific fields and formats, the toolkit should take those values and generate a mock callback body automatically from fspiop api specification file.
  * We need more sophisticated implementation of the rules engine. For example, two levels of rules engine. One for instant responses and one for callbacks. And also ml-self-testing-tookit want to implement various types of events raised by the rules engine. Based on the event type, toolkit generates callback accordingly.
  * It's not hard to implement the existing functionality of JRE in ml-self-testing-toolkit.
* Additional Overhead as a separate container:
  * It's not worth to run ml-simulator as a separate container with self testing tool as we are trying to make the toolkit very lite and should run in any machine.
  * Instead we can develop a common library that both ml-simulator and ml-self-testing-tookit can use
* Integration with mocking libraries:
  * We want to develop the toolkit with the help of opeapi mocking libraries already exist. It's hard to integrate these libraries if we include the ml-simulator into the tookit application.

So considering all the above observations, my opinion is to better implement a common library which includes callback generation and advanced rules engine which can be used in both ml-simulator and ml-self-tesitng-tookit.
