### ISSUE TITLE
Improve EventSDK CI/CD

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1104]
## **Goal**:
As an OSS Developer
I want to improve the Event SDK CI/CD process
so that we can maintain a high quality of code etc.

**Tasks**:
- Add the following missing CircleCI config:
  - [x] make coverage check fail on unsatisfactory coverage (currently it runs `npm run coverage`, instead of `npm run coverage-check`)
  - [x] add npm audit step
  - [x] add license scanner step

**Acceptance Criteria**:
- [x] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/event-sdk/pull/22

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: TBC
