### ISSUE TITLE
Provide SDs for all changes to the existing API (part 2)

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#1105]
## **Goal**:
As a core OSS team member
I want to update the stack of settlement related sequence diagrams (SDs)
so that functionality, that might be affected by the changes for Request settlement by currency epic, is up-to-date and working

The scope of this story is to provide update of remaining SDs, which are outside the defined scope by **OSS Settlement BRD**, section 6.1 Request settlement by currency, but are supported by the current v1 of Settlements

**Tasks**:
- [x] Provide [sequence diagrams](https://github.com/mojaloop/documentation/blob/master/mojaloop-technical-overview/central-settlements/settlement-process/assets/diagrams/sequence) for Request settlement by currency
  - [x] 6.1.1. Request Settlement Window By Id (getSettlementWindowById) [@ggrg]
    - [x] Report settlementWindowContent info, incl. settlementId (confirmed) [@ggrg]
  - [x] 6.1.3. Get Settlement Windows By Parameters (getSettlementWindowsByParams) [@ggrg]
  - [x] 6.2.4. Get Settlement By Id (getSettlementById) [@ggrg]
  - [x] 6.2.2. Query Settlements by Parameters (getSettlementsByParams) [@ggrg]
  - [x] 6.2.6. Settlement Abort (abortSettlementById) [@ggrg]
  - [x] 6.2.3. Get Settlement By Settlement, Participant and Account (getSettlementBySPA) [@ggrg]
- [x] Peer review and validation [@ggrg]
- [x] Present to DA [@ggrg]
- [x] Apply requested DA changes [@ggrg]

**Acceptance Criteria**:
- [x] Existing SD stack is updated
- [x] SDs are approved by the DA
- [x] Documentation is updated

## **Pull Requests**:
- [x] https://github.com/mojaloop/documentation/pull/150

## **Follow-up**:
**Add stories for**:
- Request Settlement Window By Id (getSettlementWindowById)
- Query Settlements by Parameters (getSettlementsByParams)
- Settlement Abort (abortSettlementById)
- Get Settlement By Settlement, Participant and Account (getSettlementBySPA)
- Create Settlement Model (createSettlementModel) [**new**]
- Get Settlement Model By Id (getSettlementModelById) [**new**]

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @ggrg, @MichaelJBRichards 
- QA/Review: DA

**Comment by ggrg** [comment]
@elnyry, @MichaelJBRichards - moving story to Blocked and awaiting peer review
