### ISSUE TITLE
Provide SDs for all changes to the existing API (part 3)

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#1106]
## **Goal**:
As a core OSS team member
I want to update the stack of settlement related sequence diagrams (SDs)
so that Request settlement by currency is fully supported

The scope of this story is to provide all SDs to accommodate for all changes referred in **OSS Settlement BRD**, section 6.2 Support continuous gross settlement. The estimate is to be updated once the list of diagrams is confirmed and finilised

**Tasks**:
- [ ] Provide [sequence diagrams](https://github.com/mojaloop/documentation/blob/master/mojaloop-technical-overview/central-settlements/settlement-process/assets/diagrams/sequence) for Support continuous gross settlement
  - [ ] (new) Define a Settlement Model
  - [ ] (new) Get Settlement Model By Id
  - [ ] TBD
- [ ] Peer review and validation
- [ ] Present to DA

**Acceptance Criteria**:
- [ ] Existing SD stack is updated
- [ ] SDs are approved by the DA
- [ ] Documentation is updated

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @ggrg, @MichaelJBRichards 
- QA/Review: DA
