### ISSUE TITLE
Address 'deploy' step in the CI/CD process on CircleCI (core repos)

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1107]
## **Goal**:
As an OSS codebase maintainer
I want to _ensure all steps in the CI/CD process (using CircleCI) process of the core repos are relevant and up-to-date_
so that _it ensures quality of the repositories, services and only includes steps that are applicable_

**Tasks**:
~- [ ] Identify which of the options - either to make deploy step work or removing it, makes sense in this context~ Decided to fix the step
- [x] Address the 'deploy' phase in the circleCI CI/CD process to ~either disable it and~ get it working with the core-team's dev environment (dev1 or dev2)
- [ ] Apply fixes to the mojaloop docker targets:
    - [x] quoting-service
    - [x] account-lookup-service - _PR_
    ~- [ ] als-oracle-pathfinder~ Out of scope for now
    - [x] bulk-api-adapter - _PR_
    - [x] central-event-processor - _PR_
    - [x] central-ledger - _PR_
    - [x] central-settlement - _PR_
    - [x] email-notifier - _PR_
    - [x] event-sidecar - _PR_
    - [x] event-stream-processor - _PR_
    - [x] finance-portal-backend-service - _PR_
    - [x] finance-portal-ui - _PR_
    - [x] ml-api-adapter - _PR_
    - [x] operator-settlement - _PR_
    - [x] settlement-management - _PR_
    - [x] simulator - _PR_
    - [x] transaction-requests-service - _PR_

**Acceptance Criteria**:
- [ ] 'Deploy' phase that is part of the release cycle in the CI/CD process (on CircleCI) is either removed or is made to work (on to core-team's dev environment)

## **Pull Requests**:
- [x] https://github.com/mojaloop/quoting-service/pull/154
- [x] https://github.com/mojaloop/account-lookup-service/pull/245
- [x] https://github.com/mojaloop/bulk-api-adapter/pull/23
- [x] https://github.com/mojaloop/central-event-processor/pull/152
- [x] https://github.com/mojaloop/central-ledger/pull/616
- [x] https://github.com/mojaloop/central-settlement/pull/261
- [x] https://github.com/mojaloop/email-notifier/pull/125
- [x] https://github.com/mojaloop/event-sidecar/pull/21
- [x] https://github.com/mojaloop/event-stream-processor/pull/24
- [x] https://github.com/mojaloop/finance-portal-backend-service/pull/40
- [x] https://github.com/mojaloop/finance-portal-ui/pull/31
- [x] https://github.com/mojaloop/ml-api-adapter/pull/362
- [x] https://github.com/mojaloop/operator-settlement/pull/11
- [x] https://github.com/mojaloop/settlement-management/pull/9
- [x] https://github.com/mojaloop/simulator/pull/151
- [x] https://github.com/mojaloop/transaction-requests-service/pull/21

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @mdebarros

**Comment by lewisdaly** [comment]
I was also looking into using CircleCI orbs (it's a feature they added about 1 year ago) to make some pieces of config that can be easily shared between our projects.

https://circleci.com/docs/2.0/creating-orbs/

This means that any major configuration changes in the future could be updated across all CI/CD pipelines without updating each and every repo.

**Comment by lewisdaly** [comment]
I managed to get an 'inline' CircleCI orb set up for this on the email notifier.

Just about everything looks like it will work, the only issue being I need the latest `K8_CLUSTER_SERVER` url, which is currently in CircleCI, but I'm pretty sure is outdated.

**Comment by lewisdaly** [comment]
@rmothilal @mdebarros in the past it looks like we deployed to a 'snapshot' cluster for snapshot releases, and a different cluster for normal releases.

Do we still want that functionality? Or we we happy to just deploy to `dev1` to start off with

**Comment by lewisdaly** [comment]
I managed to get everything working assuming a dev1 deployment locally.

My next challenge where I'm a little stuck is with the setting up kubectl auth. I was using my own credentials as a test, which obviously isn't a long term solution. 

I've been working on setting up a proper service account for circle-ci, and creating a secret, etc. but am now rather stuck. If anyone has any input on this, that would be very helpful!

**Comment by lewisdaly** [comment]
Moving to blocked for now.

**Comment by lewisdaly** [comment]
@mdebarros has provided an access token for the ci/cd, so we are all good to go.

**Comment by lewisdaly** [comment]
- event-stream-processor isn't in the root values.yml file, so can't be overriden as part of the deployment.

**Comment by lewisdaly** [comment]
Ok, we're done with all the PRs!
