### ISSUE TITLE
Validate incoming requests based on rules

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1109]
## **Goal**:
As an FSP
I want to _validate incoming requests based on rules_
so that _I can configure rules and use them to decide the valid status on incoming requests_

**Tasks**:
- [x] Explore rules framework to be used for validation rules component
- [x] PoC
- [x] Review with team
- [x] Incorporate feedback
- [x] Document the rules file structure, conditions, event types, and configurable parameters

**Acceptance Criteria**:
- [x] A rules framework is proposed to use for validation rules on the self testing tool-kit
- [x] A PoC is made with the aforementioned framework, reviewed and then published after the feedback (team's) is incorporated

## **Pull Requests**:
Documentation about the rules engine can be found here
https://github.com/mojaloop/ml-self-testing-toolkit/blob/master/RULES_ENGINE.md

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @elnyry @MichaelJBRichards
