### ISSUE TITLE
Automate the CI pipeline for central-services-auth

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#111]
**Goal**:
As a developer I would like to automate the CI pipeline for central-services-auth so that I can shorten the development cycle

**Tasks**:
- [ ] 

**Acceptance Criteria**:
- [x] Automated build artifacts are published to the respective repository for master (release) and develop (snapshot) pushed tags 
- [x] Automated unit tests for PR validations with results made available
- [x] Automated integration tests for PR validations with results made available
- [x] Automated functional tests for PR validations with results made available
- [x] Automated code coverage tests for PR validations with results made available to sonar-qube

**Dependencies**:
- None currently

**Comment by mdebarros** [comment]
Documentation for CI/CD created via this PR:
https://github.com/mojaloop/docs/pull/9

PR: 
https://github.com/mojaloop/central-services-auth/pull/12

SonarQube:
https://s3-us-west-2.amazonaws.com/elasticbeanstalk-us-west-2-886403637725/sonar/central-services-auth/lcov.info

See Published NPM deployments from CircleCI: 
$ npm view @mojaloop/central-services-auth

Output:
{ name: '@mojaloop/central-services-auth',
  description: 'Authentication module for central services',
  'dist-tags': { latest: '0.2.0', snapshot: '**1.1.0-snapshot.1**' },
  versions: [ '0.1.1', '0.1.2', '0.1.3', '0.2.0', '**1.1.0-snapshot.1**' ],
  time:
   { modified: '2018-02-20T08:07:22.863Z',
     created: '2017-11-27T13:42:38.482Z',
     '0.1.1': '2017-11-27T13:42:38.482Z',
     '0.1.2': '2017-11-29T10:39:14.241Z',
     '0.1.3': '2017-11-29T10:49:03.461Z',
     '0.2.0': '2018-02-07T12:48:17.224Z',
     '**1.1.0-snapshot.1': '2018-02-20T08:07:22.703Z**' },
