### ISSUE TITLE
Create Postman Collection with requests for the transaction-requests-service

### ISSUE THREAD

**Issue by gibaros** [mojaloop/project#1110]
## **Goal**:
As a `Hub Operator`,
I want to `create Postman Collection with requests for the transaction-requests-service`
so that `we can test transaction-request-service API functionality`

**Tasks**:
- [x] Create Postman Collection with requests for the transaction-request-service API for the following resources:
    - [x] GET /transactionRequestById
    - [x] PUT /transactionRequestById
    - [x] PUT /transactionRequestErrorById
    - [x] POST /transactionRequests  
    - [x] GET /health
- [x] Validate locally
- [x] Validate on AWS dev envt(s)

**Acceptance Criteria**:
- [x] `transaction-request-service` can be validated using a postman collection on a mojaloop deployment (or when deployed by itself)

## **Pull Requests**:
- [ ] https://github.com/mojaloop/postman/pull/72
- [x] https://github.com/mojaloop/transaction-requests-service/pull/13

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @gibaros 
- QA/Review: @elnyry, @amarmodus

**Comment by amarmodus** [comment]
After removing Content-length header, and changing response to 202 for POST /transactionRequests, all test passed in local environment

<img width="1230" alt="Screenshot 2019-12-16 16 47 12" src="https://user-images.githubusercontent.com/53434415/70926199-9a6d7e80-2024-11ea-8c00-5970283e3bf5.png">

**Comment by elnyry** [comment]
cool, thanks @amarmodus

**Comment by amarmodus** [comment]
Dev 1:
<img width="1281" alt="Screenshot 2019-12-18 01 29 23" src="https://user-images.githubusercontent.com/53434415/71048142-34711c00-2136-11ea-94fa-f382113470b7.png">

Dev 2:
<img width="1279" alt="Screenshot 2019-12-18 01 30 14" src="https://user-images.githubusercontent.com/53434415/71048147-36d37600-2136-11ea-9991-b606d7662ac6.png">
