### ISSUE TITLE
Perf1 Env: Testing & Validation - Sprint8.7

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1111]
## **Goal**:
As Ops
I want to _setup an environment for performance testing on a mojaloop Switch (core)_
so that _missing pieces can be identified and addressed_ for end-to-end perf testing to be done.

**Tasks**:
- Monitoring
    - [x] Configure & Test SDK-Scheme-Adapters for Event instrumentation ~ [ @mdebarros, @rmothilal ]
    - [x] Configure & Test SDK-Scheme-Adapters for Prometheus instrumentation ~ [ @mdebarros, @rmothilal ]
    - [x] Validate Events Dashboard against Transfer DB SDK-Scheme-Adapters for Event instrumentation ~ [ @mdebarros, @vgenev ] --> https://github.com/mojaloop/project/issues/1076
- [x] Validate instrumentation changes on sdk-scheme-adapter (from #1062 ) [@rmothilal ]
- SDK-Schema-Adapter:
    - [x] Deploy and validate "Redis connection leak fix" on the perf envt [@rmothilal ]
    - [x] Fix for Master Span transferState - https://github.com/mojaloop/project/issues/1080 [ @vgenev ]
    - [x] Fix for Tracestate header in the Event-SDK https://github.com/mojaloop/project/issues/1102 [@vgenev]
- [x] Test Runs on perf envt
  - [x] 2 threads 50k messages - identify, fix issues
  - [x] 3 threads 75k messages - identify, fix issues
  - [x] 4 threads 100k messages - identify, fix issues
  - [x] 8 threads 200k messages
- [x] Validate perf numbers on JMeter dashboards and Graphana

**Acceptance Criteria**:
- [x] Documentations are up-to date (Issue #1122 tracked separately)
- [x] Perf1 Environment is ready to be used for Performance Test

## **Pull Requests**:
- [x] https://github.com/mojaloop/event-sdk/pull/21
- [x] https://github.com/mojaloop/central-services-shared/pull/143
- [x] https://github.com/mojaloop/event-stream-processor/pull/12
- [x] https://github.com/mojaloop/ml-api-adapter/pull/292
- [x] https://github.com/mojaloop/central-ledger/pull/505
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/106
- [x] https://github.com/mojaloop/event-sidecar/pull/11

## **Follow-up**:
- N/A

**Dependencies**:
- TBD

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
