### ISSUE TITLE
ALS: Integrate event-sidecar into helm chart

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1112]
## **Goal**:
As a `Hub Operator`
I want to `integrate Event Framework into Mojaloop components`
so that `so that all events (errors, general, admin etc) can be audited and traced appropriately`

This specific story is to integrate the event-sidecar into ALS helm chart and other helm updates needed.

**Tasks**:

- [x] Helm updates
  - [x] Integrate event-sidecar into helm chart [@oderayi]
  - [x] Updated configuration for default.json in helm chart [@oderayi]
  - [x] Configure events for regular API endpoints[@oderayi] 
  - [x] Configure events for Admin API endpoints [@oderayi]
- [x] Validate in Dev environment [@oderayi]

**Acceptance Criteria**:
- [x] Helm Charts
	- [x] Deployment includes sidecar as part of deployment
	- [x] Deployment includes sidecar configuration

## **Pull Requests**:
- [x] https://github.com/mojaloop/account-lookup-service/pull/283
- [x] https://github.com/mojaloop/helm/pull/294

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
