### ISSUE TITLE
QA - Validate/test bugfixes done as part of Sprint 8.6

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1113]
## **Goal**:
As a maintainer of the OSS codebase, QA
I want to make sure that new releases are checked for regressions
so that releases are validated before being accepted or released to the public

**Tasks**:
- [x] Validate https://github.com/mojaloop/project/issues/1066
- [x] Validate https://github.com/mojaloop/project/issues/1065
- [x] Validate https://github.com/mojaloop/project/issues/1085

**Acceptance Criteria**:
- [X] Postman collection are available as part of https://github.com/mojaloop/postman/pull/69

## **Pull Requests**:
- [X] https://github.com/mojaloop/postman/pull/69

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @amarmodus 
- QA/Review: TBC

**Comment by elnyry** [comment]
@amarmodus initial review shows that all 3 are fine..

For #1085 , below are the logs from simulator:
```
2019-12-12T16:15:30.079Z - : L1p-Trace-Id=undefined - Response: null Status: 200 
2019-12-12T16:16:51.427Z - : L1p-Trace-Id=130ec926a5c588612aaff31b60193387 - Method: put Path: /payerfsp/quotes/4ad553ca-5154-4b6e-a3ff-e369e0b8b588/error Query: {} 
2019-12-12T16:16:51.427Z - : L1p-Trace-Id=130ec926a5c588612aaff31b60193387 - Headers: {"host":"dev2-simulator.mojaloop.live","connection":"close","x-request-id":"d0ef875c26ed995120dedb19b45719ec","x-real-ip":"10.1.2.146","x-forwarded-for":"10.1.2.146","x-forwarded-host":"dev2-simulator.mojaloop.live","x-forwarded-port":"80","x-forwarded-proto":"http","x-original-uri":"/payerfsp/quotes/4ad553ca-5154-4b6e-a3ff-e369e0b8b588/error","x-scheme":"http","content-length":"122","content-type":"application/vnd.interoperability.quotes+json;version=1.0","date":"Thu, 12 Dec 2019 16:16:51 GMT","fspiop-source":"switch","fspiop-destination":"payerfsp","fspiop-http-method":"PUT","fspiop-uri":"/quotes/4ad553ca-5154-4b6e-a3ff-e369e0b8b588/error","traceparent":"00-130ec926a5c588612aaff31b60193387-5bf27f12800e768b-00","tracestate":"mojaloop=5bf27f12800e768b","user-agent":"axios/0.19.0"} 
2019-12-12T16:16:51.428Z IN PAYERFSP:: PUT /payerfsp/quotes/4ad553ca-5154-4b6e-a3ff-e369e0b8b588/error { errorInformation: 
   { errorCode: '3202', 
     errorDescription: 
      'Payer FSP ID not found - Unsupported participant \'payerfsp\'' } } 
```

**Comment by amarmodus** [comment]
for 1085

![Screenshot 2019-12-12 16 37 02](https://user-images.githubusercontent.com/53434415/70731183-308c6680-1cfe-11ea-9479-fb628cb489d2.png)

**Comment by amarmodus** [comment]
for 1065

![Screenshot 2019-12-13 11 40 46](https://user-images.githubusercontent.com/53434415/70798034-caefb700-1d9d-11ea-9652-ada6f0b7dbc0.png)

![Screenshot 2019-12-13 11 39 55](https://user-images.githubusercontent.com/53434415/70798038-ce833e00-1d9d-11ea-8ba3-e618dc771367.png)

**Comment by amarmodus** [comment]
for 1066:

![Screenshot 2019-12-13 18 19 33](https://user-images.githubusercontent.com/53434415/70822886-8b918c80-1dd6-11ea-993f-f77e5fe6aac9.png)

![Screenshot 2019-12-13 18 13 31](https://user-images.githubusercontent.com/53434415/70822904-93e9c780-1dd6-11ea-9520-8cc651690c2a.png)
