### ISSUE TITLE
Kafka "Error: Local: Queue full"

### ISSUE THREAD

**Issue by yosheeck** [mojaloop/project#1114]
## **Summary**:
When running perf tests the following error is reported: "Error: Local: Queue full" by kafka client.

**Severity**:
High

**Priority**:
Critical

**Expected Behavior**
No error reported, no queue overflow should happen.

**Steps to Reproduce**
Detailed steps unknown, but looks like producing a lot of kafka messages recreates the issue.

**Specifications**
  - Component (if known): not sure, suggested central-services-stream
  - Version: 8.4.0
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Notes**:
- Severity when opened: High
- Priority when opened: Critical

## **Tasks**:
- [x] reproduce the issue in minimal environment
- [x] propose the fix, merge
- [x] bump/release all dependent packages
- [x] test fix in perf environment

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-stream/pull/57
- bumps/release by @mdebarros:
  - [x] https://github.com/mojaloop/ml-api-adapter/pull/299  - v8.7.2
  - [x] https://github.com/mojaloop/central-ledger/pull/511   - v8.7.1
  - [x] https://github.com/mojaloop/central-event-processor/pull/109    -v8.7.0
  - [x] https://github.com/mojaloop/bulk-api-adapter/pull/18   -v8.7.0-snapshot
  - [x] https://github.com/mojaloop/event-sidecar/pull/12    -v8.7.1
  - [x] https://github.com/mojaloop/email-notifier/pull/89   -v8.70
  - [x] https://github.com/mojaloop/event-stream-processor/pull/13
