### ISSUE TITLE
Self-testing toolkit: Generate callbacks dynamically 

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1115]
## **Goal**:
As an FSP
I want to _receive callbacks from a kit simulating a Mojaloop Hub / FSP based on the parameters in the incoming request and on rules that are configurable_
so that _I can configure rules and use them to generate callbacks dynamically for testing and validation_

**Tasks**:
- [x] Explore rules framework to be used for validation rules component
- [x] Implement the callback generation using rules engine
- [x] Generate proper headers for callback
- [x] Send http callback request to some endpoint configured in a configuration file
- [x] Setup an ml-simulator + scheme-adapter and try to send callbacks to the scheme-adapter.
- [x] Define some sample rules both for validation and callback considering a real-world use-case
- [x] Streamline the mock value patterns from a set of real names and numbers
- [x] Visualize the json rules in front-end for demo
- [x] PoC Demo
- [x] Review with team
- [x] Document configurability and options
- [x] Response validation and log the error

**Based on the feedback, the changes are as below**
- [x] Mock Callbacks - need to over ride the headers like date, destination with appropriate values
- [x] Generate condition & fulfilment dynamically
- [x] Override the pattern of extensionList to show fewer values
- [x] Incorporate feedback and release

**Acceptance Criteria**:
- [x] A rules framework is proposed to use for rules that decide how dynamic callbacks are generated by the self-testing tool-kit
- [x] A PoC is made with the aforementioned framework, reviewed and then published after the feedback (team's) is incorporated

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @elnyry @MichaelJBRichards
