### ISSUE TITLE
Remove unused/unnecessary configuration from all scripts and config files - helm

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1121]
## **Goal**:
As a developer
I want to remove all unused/unnecessary configuration from helm scrips so that we do have cleaned up repositories with only config that is applicable to the API

**Tasks**:
- [ ] Remove unused config from helm scripts for central-ledger
- [ ] Remove unused kafka cronjob config from from helm scripts for central-ledger
- [ ] Remove unused config from helm scripts for central-settlement
- [ ] Remove unused config from helm scripts for central-event-processor

**Acceptance Criteria**:
- [ ] Regression testing (manual/automated) passes without issues
- [ ] All deployments still occur as per usual

## **Pull Requests**:
- [ ] TBA

## **Follow-up**:
- N/A

**Dependencies**:
- #609 
- #636

## **Accountability**:
- Owner: @mdebarros 
- QA/Review: @rmothilal
