### ISSUE TITLE
Update event framework documentation to reflect changes done in PI8 until Sprint 8.6

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1122]
## **Goal**:
As `Tech Ops`
I want to  use `Event Framework Documentation/Guidelines regarding end-to-end trace` so that `I can understand them and use them for application in troubleshooting and Production Support`

**Tasks**:
- [x] Ensure event framework designs and documentation is up-to-date and reflects the implementation

**Acceptance Criteria**:
- [x] Documentation is published regarding end-to-end traces and other changes done to event framework to support traceability in PI8 (upto Sprint 8.6)

## **Pull Requests**:
- [ ] https://github.com/mojaloop/documentation/pull/152

## **Follow-up**:
- N/A

**Dependencies**:
- [x] #1102

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
