### ISSUE TITLE
QA : Postman Collection - Low priority test cases

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1123]
## **Goal**:
As a Community member
I want to have the postman test collections other than the golden path
so that they can be used to test various low priority coverage

For the initial version following tasks are added.

**Tasks**:
- [ ] /swagger.json for all services
- [ ] /documentation for all services

**Acceptance Criteria**:
- [ ] postman collection available and ran in latest helm release

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
