### ISSUE TITLE
Update core team 'dev' environments to use mojaloop-simulator instances

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1125]
## **Goal**:
As an FSP / Switch
I want to _use postman collections and Helm release versions that have been tested by the core team on a similar environment_
so that _I can upgrade to those releases and use the postman scripts with confidence_ as they've been validated by the core team

**Tasks**:
- [x] Update dev2 environment to use mojaloop-simulator instances as FSPs
  - [x] Update URL variables to support different services(ALS, Quoting, Transfers, Central Settlements)
- [x] Test Golden path mojaloop-simulators collection on dev2
- [x] Identify and fix issues

**Acceptance Criteria**:
- [x] AWS envt dev2 used by the core team is updated to use mojaloop-simulator instances as FSPs

## **Pull Requests**:
- [x] https://github.com/mojaloop/deploy-config/pull/11
- [x] https://github.com/mojaloop/helm/pull/299
- [x] https://github.com/mojaloop/helm/pull/307
- [ ] ~https://github.com/mojaloop/postman/pull/101~

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
Follow-up item #1370
