### ISSUE TITLE
Sprint8.7: Mojaloop Core Performance baselining

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1135]
## **Goal**:
As an FSP
I would like to _understand the performance metrics and baselines of a mojaloop system_
so that _I can understand the capabilities, limitations regarding performance of a Mojaloop based system._

**Tasks**:
- [x] Baseline runs over an hour on the current perf1 envt
  - [x] 1 thread, no scaling
  - [x] 4 threads, no scaling
  - [x] 8 threads, no scaling
  - [x] 8 threads, scaling [position handlers scaled to 4, other handlers scaled to 2]
    - [x] Issue: Consumers on only 3 partitions are working and 4th one is not
      - [x] Issue fixed and retested
    - [x] Issue: central-ledger message key set wrong in some instances
      - [x] Issue fixed and retested
  - [x] 8 threads, scaling [position handlers scaled to 8, notification handler scaled to 4, other handlers scaled to 2]
  - [ ] ~16 threads, scaling [position handlers scaled to 8, notification handler scaled to 4, other handlers scaled to 2]~
    - [ ] ~Issue: ?~
- [x] Issues identified and fixes

**Acceptance Criteria**:
- [x] Baseline numbers, metrics along with the corresponding config are documented
- [x] Issues identified as part of this performance testing are logged, separately and are addressed.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- TBD

## **Accountability**:
- Owner: @mdebarros @rmothilal 
- QA/Review: Core team, DA
