### ISSUE TITLE
Instrumentation of Metrics into central-services libraries

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1136]
**Goal**:
As a Hub Tech Operator or Hub DevOps
I would like the _add instrumentation to the Switch central-services libraries_
to enable _operational monitoring and identify status/metrics and issues if any_

**Tasks**:
- [x] import mojaloop/metrics lib
- [x] Add metrics to central-services-stream
    - [ ] Validate
- [ ] Add metrics to central-services-logger
    - [ ] Validate
- [x] Add metrics to event-sdk
    - [ ] Validate
- [x] Add metrics to central-services-database
    - [ ] Validate

**Acceptance Criteria**:
- [ ] Instrumentation is provided on central-services-stream
- [ ] Instrumentation is provided on central-services-logger
- [ ] Instrumentation is provided on event-sdk
- [ ] Instrumentation is provided on central-services-database 

**PRs**:
- [ ] https://github.com/mojaloop/central-services-stream/pull/62
- [ ] https://github.com/mojaloop/central-services-database/pull/86
- [ ] https://github.com/mojaloop/event-sdk/pull/23

**Dependencies**:
- [ ] 

**Accountability**:
- Owner 
- QA/Review @rmothilal @mdebarros
