### ISSUE TITLE
Self-testing toolkit: Rules builder UI

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1139]
## **Goal**:
As an FSP
I want to _have access to a User Interface that can build and configure rules_
so that _its intuitive and easy to configure rules which determine how the self-testing toolkit can be run_ for testing / QA.

**Tasks**:
- [x] Build a UI for Rules
    - [x] Condition builder
    - [x] Event builder
    - [x] Can save multiple rule sets among which only one rule set can be active (User can switch the active ruleset)
    - [x] The validation rules should also be changed to the new rules builder
    - [x] End to End testing should be done using the new rules builder
- [x] Review, feedback
- [x] Incorporate feedback

**Acceptance Criteria**:
- [x] A Rules builder UI is available to set rules and help with configuring the self-testing toolkit

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @elnyry @MichaelJBRichards
