### ISSUE TITLE
Host Logging Enhancement Optimizations

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1140]
## **Goal**:
As a `Hub Operator`, I want to `logs to be optimized` so that `disk pressure is not an issue`

**Tasks**:
- **Event-SDK** enhancements: <-- ref work in progress branch - [feature/hostLoggingEnhancement @ Mojallop remote](https://github.com/mojaloop/event-sdk/blob/feature/hostLoggingEnhancement/README.md#configuration)
    - [x] Deprecate existing env config: ~~EVENT_SDK_SIDECAR_WITH_LOGGER~~
    - [x] Add new env config: EVENT_SDK_LOG_FILTER
    - [x] Add new env config: EVENT_SDK_LOG_METADATA_ONLY
    - [x] Add new env config: EVENT_SDK_TRACEID_PER_VENDOR in Event SDK to switch between creating new traceId and keeping up the original one, when the vendor is external

- Implement logging changes
    - [x] ~Update all Logger output to debug~ on **ML-API-Adapter** with new Event-SDK functionality with EVENT_SDK_LOG_FILTER='audit:*, log:error, log:warning', EVENT_SDK_LOG_METADATA_ONLY='false'
    - [x] ~Update all Logger output to debug on~ **Central-Ledger** with new Event-SDK functionality with EVENT_SDK_LOG_FILTER='audit:*, log:error, log:warning', EVENT_SDK_LOG_METADATA_ONLY='false'
    - [x] ~Update all Logger output to debug on~ **Event-Sidecar** with new Event-SDK functionality with EVENT_SDK_LOG_FILTER='*:*', EVENT_SDK_LOG_METADATA_ONLY='true'
    - [x] ~Update all Logger output to debug on~ **Event-Stream-Processor** with new Event-SDK functionality with EVENT_SDK_LOG_FILTER='*:*', EVENT_SDK_LOG_METADATA_ONLY='true'

**Comment**
- We striked out *Update all Logger output to debug* because we can change the log filter and switch it off

- Update Helm charts with the above config changes
    - [x] ML-API-Adapter & Event-Sidecar
    - [x] Central-Ledger & Event-Sidecar

- Create new stories for:
    - [ ] Quoting Service
    - [ ] Account-Lookup-Service

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Golden Path Services (e.g. ML-API-Adapter, Central-Ledger) and supporting components log the minimum required for normal day-to-day operational monitoring.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
