### ISSUE TITLE
Performance PI8 Baseline with Legacy Simulator

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1141]
## **Goal**:
As a `Hub Operator`, I want to `run performance tests against the legacy simulator` so that `we can determine a baseline in PI8 which can be directly compared to PI4/5 performance results`

**Tasks**:
- Enhance [Legacy Simulator](https://github.com/mojaloop/simulator)
    - [x] Update to support TraceState headers
    - [x] Test end-to-end locally with ML-API-Adapter, Central-Ledger, Event-Sidecar, Event-Stream-Processor and Legacy Simulator (i.e. the same approach used when testing sdk-schema-adapter)
    - [x] add tags in the simulator spans
- [x] Change Event Stream Processor cache key to include vendor, to be able to send out simulator spans directly
- JMeter Tests
    - [x] Add tests for direct Mojaloop API Transfer to existing JMX tests in a new thread
- Performance Tests (High number of threads not needed as this mode is async). [Use additional threads if required, after decreasing delay]
    - [x] 1 Thread <-- In Progress (with 3ms delay)
- Enhancements:
    - [x] Async Logging - Done by @lewisdaly. To be tested.
    - [x] Reduced Logging Verbosity (event-sdk printing Audits, errors, warnings only) - Done by @vgenev. To be tested.
    - [x] Migrate to FAST NVME storage on GC Nodes on Perf1 environment - Done by the GCIO nodes. - Done by @mdebarros 
        - [x] Add new nodes to AWS CloudWatch - @rmothilal 
    - [x] Instrument the Notification Handler to determine where time is being spent - Add Span's for Callbacks to FSPs and Central-Ledger @vgenev 
    - [x] Increase Cache on Notification Handler to retrieve end-points from Central-Ledger - Update endpoint_cache_expiresInMs in Helm values to be 4000000
    - [x] Cache improvements on Central-Ledger - @yosheeck covered in a separate story #602 so closing here
    - [x] Deploy Mojaloop with light Health Checks - Configure health end-points for ML-API and Central-Ledger to support a `/health?simple` health check that does not call backends for status. @rmothilal.
    - [x] PRISM investigation based on PI-8 code-base and implementation @oderayi  - covered in a separate story #578 

Scenarios:
- [x] 0
    - Async Logging 
    - LOG_LEVEL=error
    - Migrate to FAST NVME storage on GC Nodes on Perf1 environment
    - Increase Cache on Notification Handler to retrieve end-points from Central-Ledger 
- [x] 1
    - Async Logging 
    - Reduced Logging Verbosity
    - Migrate to FAST NVME storage on GC Nodes on Perf1 environment
    - Increase Cache on Notification Handler to retrieve end-points from Central-Ledger 
- [x] 2
    - Includes use-case 1
    - Use simple health checks
- [x] 3
    - Includes use-case 2
    - UV Thread Pool increase to accomodate number of consumer threads + 4 (default UV Thread pool)
- [x] 4
    - Includes use-case 3
    - Disable Sidecar and ALL event logging
    - Undeploy FluentD DaemonSet from all Nodes to ensure that no logging is ingested into ElasticSearch <-- Can just undeploy EFK
- [x] 5
    - Includes use-case 3 (or 4 if use-case 4 proved to increase performance drastically)
    -  Cache improvements on Central-Ledger
- [x] 6 (Discussed on Friday's call, Jan 17th)
    - Switch-off Events, EFK, Event Logging
    - Scale position(8), notification handlers(8)
    - Try lag to 2ms and try for 10mins

Issues:
  - [x] Event-Stream-Processor throttling as ElasticSearch is not able to keep up with the ingestion of events @vgenev 
  - [x] Improving ElasticSearch ingestions performance: e.g re-deploy ElasticSearch based on the following article recommendations: https://sematext.com/blog/kubernetes-elasticsearch/ <-- Create story
  - [x] Central-Ledger Service Localised Perf slowdown issue on all end-points traced under https://github.com/mojaloop/project/issues/1152 - under investigation @yosheeck @oderayi 

**Acceptance Criteria**:
- [x] Legacy Simulator supports TraceState headers from the wc3 Trace header standards
- [x] Performance Baseline tests are executed against the test-cases
- [x] Test results are documented including links to dashboards for post-analysis/discussion

## **Pull Requests**:
- [x] https://github.com/mojaloop/event-stream-processor/pull/19
- [x] https://github.com/mojaloop/simulator/pull/118

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
