### ISSUE TITLE
Performance: Understand mojaloop-simulator / sdk-scheme-adapter perf characteristics by running 2 different scenarios

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1142]
## **Goal**:
As a _Mojaloop Hub_ / _FSP_
I want to _understand the performance characteristics of the mojaloop-simulator and the sdk-scheme-adapter
so that _I can estimate the Mojaloop system capabilities and plan accordingly for load and SLAs_

This specific story attempts to achieve the goal by running two scenarios: 1 - Run performance testing using an sdk-scheme-adapter <--> sdk-scheme-adapter , ie., two mojaloop-simulator instances and 2 - Run performance testing by injecting load directly (via JMeter) on to a Mojaloop Switch without sending it through an sdk-scheme-adapter (The FSP acting as payee would still be a mojaloop-simulator instance)

**Tasks**:
- [ ] Setup two mojaloop-simulator instances
- [ ] Run performance directing an sdk-scheme-adapter <--> sdk-scheme-adapter
- [ ] Record results and understand characteristics
- [ ] Setup scripts and deployment needed to direct JMeter scripts directly at a mojaloop Switch and a mojaloop-simulator instance as a Payee FSP
- [ ] Run performance directing JMeter scripts on to the Switch
- [ ] Record results and understand characteristics

**Acceptance Criteria**:
- [ ] Results of perf testing on a sdk-scheme-adapter <--> sdk-scheme-adapter scenario are available for analysis
- [ ] Results of perf testing by directing JMeter scripts on to a ML Switch and a mojaloop-simulator as Payee FSP are available for analysis

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
