### ISSUE TITLE
Self-testing toolkit: Dashboards page UI

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1143]
## **Goal**:
As an FSP
I want to _have the logs in the User Interface grouped_
so that _it helps with easier navigation with larger number of requests_ for testing / QA.

**Tasks**:
- [x] The logs UI should be changed. Include grouping of the logs, highlight method & resource clearly and a brief title should be added
- [x] Features added to the dashboard page to show the recent transfer cycle (A pictorial representation of the flow and where the transaction failed)

**Acceptance Criteria**:
- [x] The Logs UI is enhanced to provide for easier navigation with larger number of tests
- [x] Use case / resource based navigation provided in the Logs UI of the testing kit

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @elnyry @MichaelJBRichards
