### ISSUE TITLE
Self-testing toolkit: Test case initiation from the testing tool

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1144]
## **Goal**:
As an FSP
I want to _use the self-testing toolkit to initiate tests based on use cases_
so that _I can use it as initiator of messages and test the responder functionality on the FSP_

**Tasks**:
- [x] Create a front-end page for manual initiation of the individual requests using the existing components from rules builder
- [x] Add the required backend functionality to Initiate the requests from the testing toolkit
- [x] A page should be added through which we can initiate an automated transfer from testing tool (Includes three requests parties, quotes and transfer to be sent sequentially)
  - [x] Implement the page with a standard template though which we can edit the values and send transfer
  - [x] Add buttons to include configurable parameters
  - [x] Implement importing the template files, save files and create new template features
- [x] Required backend for the automated transfer cycle
- [x] Test the end-to-end transfer which is initiated form toolkit to the scheme adapter and simulator

**Acceptance Criteria**:
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @elnyry @MichaelJBRichards
