### ISSUE TITLE
Enable redis cache in Event Streaming Processor

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1145]
## **Goal**:
As a Hub Operator I want to utilize the catbox-redis adapter in the cache of the Event Stream Processor so that the cache uses redis instead of RAM and can scale.

**Tasks**:
- [ ] Enable the catbox-redis adapter

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
