### ISSUE TITLE
Document EventSDK

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1146]
## **Goal**:
As an OSS Developer I want to expand the README.md of [Event-SDK](https://github.com/mojaloop/event-sdk/) so that it is clearer how to use it.

**Tasks**:
- [ ] Add more details to the README

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
