### ISSUE TITLE
Sprint 8.8 - Update dependencies for central-ledger, ml-api-adapter, quoting-service, ALS

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1147]
## **Goal**:
As a Community member of Mojaloop
I'd like to _ensure that the Mojaloop codebase uses updated dependencies_
so that _any vulnerabilities are addressed and latest feature changes used while making sure these are compatible with usage in Mojaloop_

**Tasks**:
- [x] Update dependencies in central-ledger
  - [x] Ensure automated tests pass
  - [x] Ensure that there's no issue with running the service as earlier
- [x] Update dependencies in ml-api-adapter
  - [x] Ensure automated tests pass
  - [x] Ensure that there's no issue with running the service as earlier
- [x] Update dependencies in quoting-service
  - [x] Ensure automated tests pass
  - [x] Ensure that there's no issue with running the service as earlier
- [x] Update dependencies in account-lookup-service
  - [x] Ensure automated tests pass
  - [x] Ensure that there's no issue with running the service as earlier

**Acceptance Criteria**:
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] central-ledger, ml-api-adapter, quoting-service, ALS use latest versions of dependencies and are verified for regressions (Log issues separately if any issues are found).

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/532
- [x] https://github.com/mojaloop/ml-api-adapter/pull/313
- [x] https://github.com/mojaloop/quoting-service/pull/118
- [x] https://github.com/mojaloop/account-lookup-service/pull/193

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by oderayi** [comment]
### Updates / Oberservations ###
- @hapi/joi now requires Node.js v12. CI still uses Node.js v10 so I did not upgrade Joi.
- Other Hapi-related libraries like @hapi/inert require the latest version of Joi, so they were not upgraded as well until we are able to upgrade the services for the latest Joi.
