### ISSUE TITLE
Update Hapi.EventPlugin to include traceparent & tracestate headers into response

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1148]
## **Goal**:
As a Hub Operator I want to include traceparent and tracestate headers to the responses coming from Central services REST API

**Tasks**:
- [x] Update [shared lib](https://github.com/mojaloop/central-services-shared) to add tracestate and traceparent header to the response

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [ ] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] https://github.com/mojaloop/central-services-shared/pull/152

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
This is now done..
