### ISSUE TITLE
Accept header not receiving on payeefsp side even though the payerfsp is sending it

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#1149]
**Summary**:
When sending GET /parties call, ACCEPT header with value "application/vnd.interoperability.parties+json;version=1" is sent from Postman as payerfsp. **When I further look into the logs, the payeefsp is not receiving this header in the request itself.**

**Tasks**
- [x] Reproduce issue locally
- [x] Ensure `accept` header is received/visible at the payee side for GET /payeefsp/parties/{type}/{id} request in the simulator
- [x] Release simulator
- [ ] Validate

**Severity**:
Low

**Priority**:
Low

**Expected Behavior**
1. payeefsp should be receiving the ACCEPT header sent from payerfsp
2. the final response to payerfsp should have this ACCEPT header.

**Steps to Reproduce**
  1. Run the first three requests from here:
<img width="499" alt="Screen Shot 2020-01-06 at 10 00 28 AM" src="https://user-images.githubusercontent.com/38143240/71826769-b8029680-306c-11ea-9df9-e097f0177d0f.png">

  2. Check the response coming back which has no accept header. 3. Below screenshot shows the console output at payeefsp that says ACCEPT header not received at payeefsp.
Request:
curl -X GET
http://dev1-account-lookup.mojaloop.live/parties/MSISDN/17039811907
-H 'Accept: application/vnd.interoperability.parties+json;version=1'
-H 'Accept-Encoding: gzip, deflate'
-H 'Cache-Control: no-cache'
-H 'Connection: keep-alive'
-H 'Content-Type: application/vnd.interoperability.parties+json;version=1.0'
-H 'Date: Mon, 18 Nov 2019 17:12:39 GMT'
-H 'FSPIOP-Source: payerfsp'
-H 'Host: dev1-account-lookup.mojaloop.live'
-H 'Postman-Token: f2a14d26-63bd-43cc-88c7-8e2becfaa75e,96d30bff-222e-4c8a-9cd0-c28d7924f5a8'
-H 'User-Agent: PostmanRuntime/7.20.1'
-H 'cache-control: no-cache'

  3. Response (request at payeefsp):
<img width="651" alt="Screen Shot 2020-01-06 at 9 59 19 AM" src="https://user-images.githubusercontent.com/38143240/71826840-ef714300-306c-11ea-8dcd-a934ba1152da.png">

**Specifications**
  - Component (if known): Mojaloop
  - Version: 8.7.0
  - Platform: Mac OS
  - Subsystem: Interop switch
  - Type of testing: Functional
  - Bug found/raised by: Sri

**Notes**:

- Severity when opened: High
- Priority when opened: Medium

## Pull Requests ##
- [x] https://github.com/mojaloop/simulator/pull/122

**Comment by oderayi** [comment]
`/payeefsp/parties/{type}/{id}` handler in legacy simulator was missing the header validation entry for `accept` header. Though the `payerfsp` was correctly forwarding the said header, the absence of the entry on the side of the payee meant that the handler does not get to see the header because `hapi` had excluded unrecognized headers. Bug was resolved by adding the entry.

**Comment by elnyry** [comment]
If its not a bug on the Mojaloop core but as you said Steven @oderayi and is on the legacy simulator, then its a low priority bug.

**Comment by amarmodus** [comment]
<img width="1564" alt="Screenshot 2020-01-09 14 32 08" src="https://user-images.githubusercontent.com/53434415/72078925-e8a73200-32f1-11ea-88fa-a911dcd61614.png">
tested in Dev 2 - ok now.

**Comment by elnyry** [comment]
Thanks @amarmodus @oderayi 

@sri-miriyala - this has now been fixed and validated no dev2
