### ISSUE TITLE
Self-testing tookit: Improving rules builder UI

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1150]
## **Goal**:
As an FSP
I want the following improvements in rules builder interface
so that _its intuitive and easy to configure rules which determine how the self-testing toolkit can be run_ for testing / QA.

**Tasks**:
- [ ] Feature requests in UI for Rules
    - [ ] A rule can be duplicated / copied to a new rule
    - [ ] A group name or catalogue name to be added for each rule to group the rules from a ruleset for better visibility and organization
    - [ ] Separate / Multiple condition and event files can be created like templates
    - [ ] Can select and club conditions and events to create a rule
    - [ ] Read rules from files provided (or a directory) to support bulk
    - [x] A graphical representation of the rule should be there in rule editor and rule list page
- [ ] Review, feedback
- [ ] Incorporate feedback

**Acceptance Criteria**:
- [ ] A Rules builder UI with the above changes is available
- [ ] Rules can be read from files provided and displayed in UI

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @elnyry @MichaelJBRichards

**Comment by elnyry-sam-k** [comment]
@vijayg10  - is this still relevant?
