### ISSUE TITLE
QA: Postman tests for header validation in the legacy simulator

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1151]
## **Goal**:
As an OSS maintainer,
I want to write postman regression tests for header-related bug fixed in the legacy simulator
so that future changes are guaranteed to preserve functionality.

**Tasks**:
- [x] Write postman test for [#1149](https://github.com/mojaloop/project/issues/1149 )
  - [x] Validate in DEV env
  - [x] Ensure test is ported/present in mojasims collection.

**Acceptance Criteria**:
- [x] Regression tests are available for #1149

## **Pull Requests**:
- [x] https://github.com/mojaloop/postman/pull/79

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by amarmodus** [comment]
Validated as part of PR review https://github.com/mojaloop/postman/pull/79 and confirmed mojasims collection for the check.
