### ISSUE TITLE
Change license-scanner implementation from blacklist to a whitelist model

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1154]
## **Goal**:
Use whitelist instead of the current blacklist to ease management of open source licenses by only adding what is allowed whenever the list changes and what is not allowed(blacklist) will be rejeccted by default.

**Tasks**:
- [x] create a whitelist and activate it
- [ ] update the contributor's guide with a link to the whitelist

**Acceptance Criteria**:
- [ ] Code Style & Coverage meets standards
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/license-scanner/pull/11

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: Lewis
- QA/Review: Miguel

**Comment by lewisdaly** [comment]
Most of the implementation is done on my branch: `feature/1154-change-to-whitelist`.

I'm going to go ahead and test this on a few different repos (mainly helm) with a temporary release just to ensure that we haven't broken anything.

**Comment by godfreykutumela** [comment]
Much needed progress thanks @lewisdaly. Will await the test results on helm and take it from there.

**Comment by lewisdaly** [comment]
Pull request is ready to go. I've tested manually across a number of repos, but once the PR is in, we should spend some time validating the changes are working.

**Comment by godfreykutumela** [comment]
Perfect thanks @lewisdaly for this much needed milestone.

**Comment by godfreykutumela** [comment]
Thanks @lewisdaly for completing this - much needed milestone.
