### ISSUE TITLE
Develop Anchore CLI Reports of Images with / without vulnerabilities

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1157]
## **Goal**:
Prepare reports for a demo at the PI meeting in Johannesburg

**Tasks**:
- [x] figure out how to get the most current anchore reports in one place. The best method is likely:
    ~- [ ] Get CircleCI to automatically add these to releases (similar to the license-scanner summary on the `mojaloop/helm` repo~
     - [x] ~Write a tool to get all latest reports from a list of given repos in one place~
     - [x] upload these reports to the s3 bucket, similar to how we handle the sonarqube output
- [x] Apply CI/CD Updates for the following repos:
  - [x] bulk-api-adapter [PR]
  - [x] central-event-processor [PR]
  - [x] central-ledger [PR]
  - [x] central-settlement [PR]
  - [x] email-notifier [PR]
  - [x] ml-api-adapter [PR]
  - [x] quoting-service [PR]
  - [x] mojaloop-simulator [PR]
- [x] compile these reports for the upcoming convening
- [x] summarize into one or two slides

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/quoting-service/pull/132
- [x] https://github.com/mojaloop/mojaloop-simulator/pull/26
- [x] https://github.com/mojaloop/ml-api-adapter/pull/340
- [x] https://github.com/mojaloop/email-notifier/pull/110
- [x] https://github.com/mojaloop/central-settlement/pull/230
- [x] https://github.com/mojaloop/central-ledger/pull/563
- [x] https://github.com/mojaloop/central-event-processor/pull/134
- [x] https://github.com/mojaloop/bulk-api-adapter/pull/19
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Thanks @godfreykutumela.

This is already working on an automated basis. I'll look into how we might easily compile the reports in one place for future reference (and for this upcoming PI meeting).

**Comment by godfreykutumela** [comment]
Noted thanks @lewisdaly

**Comment by lewisdaly** [comment]
As per our recent discussion, we will upload the reports to s3, similar to the sonarqube reports

**Comment by lewisdaly** [comment]
Created new bucket to upload the reports to: `s3://mojaloop-ci-reports`

Here is my proposed directory structure:

```
/anchore-cli
    /central-ledger
        central-ledger-v8.8.0.json
        ...
    /ml-api-adapter
        ...
...
    /latest
         (contains all latest reports across all repos)
```

**Comment by godfreykutumela** [comment]
Noted, thanks @lewisdaly for actioning that

**Comment by lewisdaly** [comment]
I've shared an example excel file generated from the anchore-cli reports in slack (I'm not including here for security purposes). Waiting for some feedback from the team before continuing.

**Comment by godfreykutumela** [comment]
Noted Thanks @lewisdaly
