### ISSUE TITLE
Define AppArmor Profile and Test on a limited of number of containers

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1159]
## **Goal**:
AppArmor will improve security by restricting the capabilities of processes running on the host operating system by setting a polic profile to each host.

**Tasks**:
- [x] Go through the AppArmor nginx example, and understand how it works
- [ ] figure out how to apply an apparmor profile on helm and provide some code snippets
- [ ] evaluate some ready-made profiles that might be useful for the mojaloop containers

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
I finished running through the nginx demo provided here: https://docs.docker.com/engine/security/apparmor/ and have a reasonable high level understanding of how it works etc.

One of the challenges with testing AppArmour is that it's a linux extension, and therefore not available on Docker for Mac (not even when I tried logging into the Hyperkit container).

**Comment by lewisdaly** [comment]
It seems that since the AppArmor is applied on the nodes that run the pods/containers, we need to install the potential AppArmor profiles on the cluster itself, not as some sort of extension that runs from helm. 

This makes applying a given AppArmor profile rather difficult, and not something we can easily add to Helm, instead it will need to be applied for a given kubernetes deployment. For our current dev environment, that means looking at how Rancher can apply AppArmor profiles.

**Comment by lewisdaly** [comment]
Here's more information on getting AppArmor running on an existing cluster with just kubectl:
https://kubernetes.io/docs/tutorials/clusters/apparmor/#authoring-profiles

**Comment by godfreykutumela** [comment]
Thanks @lewisdaly for the update on this

**Comment by godfreykutumela** [comment]
Thanks @lewisdaly. After PI let's explore how best we can address the challenge of adding and managing profiles.

**Comment by godfreykutumela** [comment]
Very good descrption of AppArmor and frank explaination on how it addresses security issues and it has simplified the required integration for me - thanks @lewisdaly
