### ISSUE TITLE
Allow for simple health checks of API's

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#1163]
## **Goal**:
As Hub TechOps
I want to _to have simple health checks_
so that _we do not send excessive requests to dependent APIs and/or services_ (that can be configured for performance and other requirements)

**Tasks**:
- [x] Update health endpoint to cater the simple query parameter (e.g. /health?simple or health?simple=true)
- [x] Use supplied query parameter from above in a condition that allows/locks services to be sent to the central-services-health library 
- [x] Update central-ledger-service and handlers with above changes
- [x] Update ml-api-service and notification handler with above changes
- [x] Update tests to cater for the above scenarios

**Notes**:
- **Branch from the feature/#1140HostLoggingEnhancementOptimizations branches in each of the repos**

**Acceptance Criteria**:
- [x] Unit Tests pass
- [ ] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Health checking for simple health (200 OK) is made available (instead of comprehensive checks that include datastore, brokers, etc)

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/543
- [x] https://github.com/mojaloop/central-ledger/pull/550
- [x] https://github.com/mojaloop/ml-api-adapter/pull/328

## **Follow-up**:
- **Create a follow up story to make the changes to all remaining APIs that have health checks**

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @oderayi  
- QA/Review: @rmothilal @mdebarros

**Comment by lewisdaly** [comment]
@rmothilal I remember we considered this when first designing the current health checks, but if I remember correctly, we implemented it so that the current health checks don't make new database or kafka connections, but recycle the existing ones.
