### ISSUE TITLE
QA: Functional tests for "Settlement by Currency" feature: OTC-170

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1164]
## **Goal**:
As a Hub adopting of Mojaloop Settlement feature
I want to _have it functionally tested_
 so that _I can adopt it with confidence_ and use the test scripts / collections to validate functionality as needed

**Tasks**:
- [ ] Review existing postman tests for Settlement functionality (v1.0/ v1.1)
- [ ] Scenarios to cover
  - [x] Close settlement window
  - [x] Create Settlement (specifying the Settlement model)
  - [x] Update the progress of a Settlement
- [ ] Test for Settling a window, after settling all the content in different Settlements
- [ ] TBD [ @? ]

**Acceptance Criteria**:
- [ ] Functional tests for the "Settlement by Currency" feature are made available which can be used to test the releases with this feature for regressions.
- [ ] Functional tests for the "Settlement by Currency" feature are made available which can be used to test the releases for functionality.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @ggrg @MichaelJBRichards 

**Note**: Abort Settlement is not covered, but will be - in future. Scripts will be needed after thats done

## QA Notes:
- **closeSettlementWindow** (POST /settlementWindows/{id}):
  - The API resource remains unchanged
  - Before the enhancement if settlementWindowStateChange table content is examined, the sequence of states which would be discovered would be OPEN -> CLOSED -> OPEN (new window). Now the transition is OPEN -> PROCESSING -> OPEN (new window) -> CLOSED (requested window, closed by the newly implemented SettlementWindowHandler). Not sure if this could be functionally tested.
  - When window is processed by the SettlementWindowHandler, data is also inserted in settlementWindowContent, settlementWindowContentStateChange and settlementContentAggregation. Not sure if this could be functionally tested.
- **createSettlement** (POST /settlements):
  - Either API for creating a settlement model or default seeds insert **is required** 
  - Swagger definition changes:
    - settlementModel is now a required payload property
    - response payload has been extended to provide settlementWindowContent information at the following path: payload.settlementWindows[i].content[k]
  - New validation is in place, so that the requested settlementModel is DEFERRED & NET & MULTILATERAL
  - Existing validation of applicable windows is changed and instead of checking if all requested windows are existing and in CLOSED/ABORTED state, it is checked if all requested windows have settlementWindowContent that is applicable (CLOSE/ABORTED). This means the window itself upon request might be CLOSED/ABORTED/PENDING_SETTLEMENT
  - transferParticipant table is now deprecated
  - settlementParticipantCurrency aggregation now uses data from settlementContentAggregation
  - when settlement is created settlementContentAggregation.settlementId and settlementWindowContent.settlementId are updated to refer to it. The latter could be functionally tested once GET /settlementWindowById is upgraded to v2
  - the process of creating a settlement is expected to take longer (milliseconds), when compared to the previous version, as additional DML statements have been added
- **updateSettlementById** (PUT /settlements/{id}):
  - Nothing has changed to the request payload
  - Internal processing has changed and in regards to determining windows and contents state is no longer possible or made in-memory, but instead database is queried, which might result in longer execution.
  - Response now contains window content information, which was introduced by the Swagger definition changes above
  - What is different from before is that there is a scenario where all settlement accounts might be SETTLED, thus the entire settlement to be SETTLED, but still some window(s) might show as PENDING_SETTLEMENT, even though all window content applicable to the settlement is SETTLED. This would happen, when the settlement window contains settlement window content that is to be settled with another settlement. Only when all settlement window content is SETTLED, the window state would change to SETTLED. This can be tested if multiple currency transfers are recorded in a settlement window and then a settlement is created only for transfers in a single currency.
