### ISSUE TITLE
Unit tests for central-settlement, part 1

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#1165]
## **Goal**:
As a Mojaloop contributor
I want to add unit tests to central-settlement, branch settlement-v2
so that full coverage is achieved for newly introduced functionality

**Tasks**:
- [x] Unit tests to cover the following modules:
  - [x] src/api/index.js @bothadeon 
  - [x] src/domain/settlementWindow/index.js @bothadeon 
  - [x] src/handlers/index.js @bothadeon 
  - [x] src/handlers/register.js @bothadeon 
  - [x] src/lib/healthCheck/subServiceHealth.js @bothadeon 
  - [x] src/handlers/settlementWindow/handler.js @lazolalucas 
  - [x] src/models/settlementWindow/facade.js @bothadeon
  - [x] src/shared/setup.js @bothadeon

**Acceptance Criteria**:
- [x] Unit Tests pass
- [ ] ~Coverage meets standards~

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-settlement/pull/234

## **Follow-up**:
- #1100 

**Dependencies**:
- #1095

## **Accountability**:
- Owner: @ggrg
- QA/Review: @ggrg

**Comment by ggrg** [comment]
#### Current state:
```
=============================== Coverage summary ===============================
Statements   : 88.73% ( 1134/1278 )
Branches     : 87.77% ( 366/417 )
Functions    : 89.22% ( 149/167 )
Lines        : 88.5% ( 1101/1244 )
================================================================================
```

**Comment by bothadeon** [comment]
Current code coverage as at the end of Tuesday 14 Jan 2020:

========================= Coverage summary ===============================
Statements  : 90.76% ( 1159/1277 )
Branches       : 89.45% ( 373/417 )
Functions       : 90.42% ( 151/167 )
Lines               : 90.51% ( 1125/1243 )
=======================================================================
