### ISSUE TITLE
Event Framework: Integrate into Central-Settlement

### ISSUE THREAD

**Issue by gibaros** [mojaloop/project#1166]
## **Goal**:
As a `Hub Operator` I want to `integrate Event Framework into Mojaloop components` so that `so that all events (errors, general, admin etc) can be audited and traced appropriately`

**Tasks**:
- [ ] Event Framework
- [ ] Integrate SDK for logging  [ ? ]
  - [ ] central-settlement
    - [ ] Integrate into health end-points for Event Sidecar (if sidecar is enabled)
    - [ ] Recording
    - [ ] Logs (replace existing logs)
- [ ] Add event and action needed for Event Framework integration into Central-Settlement

**Acceptance Criteria**:
- [ ] Designs are up-to-date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment configs.
- [ ] Event Framework integrated into Central-Settlement
	- [ ] Ensure that components cannot operate without Sidecar functioning correctly when enabled
	- [ ] Ensure that components will not startup without Sidecar when enabled
	- [ ] Sidecar can be disabled for local development and/or debugging purposes only

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-shared/pull/165
- [ ] https://github.com/mojaloop/central-settlement/pull/233

## **Follow-up**:
- [ ] Story needed for "Instrumenting events for Settlement window handler"

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
