### ISSUE TITLE
GET /quotes for malformed ID error response is 1001 instead of 3xxx

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1169]
**Summary**:
GET /quotes for malformed ID error response is 1001 rather than 3002 or 3xxx.

![Screenshot 2020-01-13 17 53 30](https://user-images.githubusercontent.com/53434415/72279594-60e16080-362e-11ea-8c8f-2fc4710d9a73.png)

**Tasks**:
- [x] Validate the changes
- [x] Make sure test added to postman test collection

**Severity**:
Low

**Priority**:
Low

**Expected Behavior**
either 400 http code with proper error code (3002 ) or 202 with callback error code of 3002

**Steps to Reproduce**
```
curl --location --request GET 'http://dev1-quoting-service.mojaloop.live/quotes/000000' \
--header 'Accept: application/vnd.interoperability.quotes+json;version=1' \
--header 'Content-Type: application/vnd.interoperability.quotes+json;version=1.0' \
--header 'Date: Mon, 13 Jan 2020 15:13:48 GMT' \
--header 'FSPIOP-Source: payerfsp' \
--header 'FSPIOP-Destination: payeefsp'
```
with another ID
```
curl --location --request GET 'http://dev1-quoting-service.mojaloop.live/quotes/482f5eb4-67b6-####-9737-c77b0@$4706c' \
--header 'Accept: application/vnd.interoperability.quotes+json;version=1' \
--header 'Content-Type: application/vnd.interoperability.quotes+json;version=1.0' \
--header 'Date: Mon, 13 Jan 2020 15:13:48 GMT' \
--header 'FSPIOP-Source: payerfsp' \
--header 'FSPIOP-Destination: payeefsp'
```

**Specifications**
  - Component (if known): central-services
  - Version:v8.7.0
  - Platform: AWS
  - Subsystem:quoting service
  - Type of testing: functional
  - Bug found/raised by:@amarmodus

**Notes**:

- Severity when opened:
- Priority when opened:

## Pull Requests ##
- [x] https://github.com/mojaloop/quoting-service/pull/125
- [x] https://github.com/mojaloop/postman/pull/80 - postman collection

**Comment by amarmodus** [comment]
<img width="1275" alt="Screenshot 2020-01-20 11 20 48" src="https://user-images.githubusercontent.com/53434415/72723044-aeeaec80-3b77-11ea-9a82-66f1b464747b.png">

<img width="1275" alt="Screenshot 2020-01-20 11 20 25" src="https://user-images.githubusercontent.com/53434415/72723153-ece81080-3b77-11ea-951d-69c57c4ad60d.png">
