### ISSUE TITLE
QA : Validate known quoting-service issues from #9

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1170]
## **Goal**:
As a maintainer of the ML OSS codebase
I want to validate the quoting-service issues mentioned in https://github.com/mojaloop/quoting-service/issues/9
so that quoting-service function as expected and known issues are validated

**Tasks**:
- [x] https://github.com/mojaloop/quoting-service/issues/9
  - [x] Sending quote with amount zero: not showing any error
    - [x] Analysed and as expected as per https://github.com/mojaloop/quoting-service/issues/9 comment 
  - [x] Send Quote Request: Validate Currency Field
    - [x] verified, postman test as part OSS API collection
  - [x] Send Quote Request: Validate Quote Id Field
    - [x] verified, postman test as part OSS API collection and raised in https://github.com/mojaloop/project/issues/1169
  - [x] Sending a quote with negative Amount
    - [x] verified, postman test as part OSS API collection
  - [x] Send Quote Request: Validate Syntax Information
    - [x] verified, postman test as part OSS API collection
  - [x] Send Quote Request - 06- Validate Information Type Syntax
    - [x] verified, postman test as part of #990 
  - [x] POST/Quotes Sending quote with any missing mandatory fields
    - [x] verified, postman test as part of #990 
  - [x] POST/Quotes - sending duplicate quoteid request
    - [x] verified, postman test as part of #990 
  - [x] POST/Quotes Not showing Error 3201 Destination FSP cannot be found
    - [x] verified, postman test as part of #990 
  - [x] POST/Quotes - sending quote with non-existent payeePartyIdentifier
    - [x] missing payeePartyIdentifier verified, postman test as part of #990 
  - [x] PUT/Quote - sending callback without condition field
    - [x] verified, postman test as part of #990 
  - [x] Send Quote Request -13 - Validate the expire time with duplicate quote ID
    - [x] verified, postman test as part of #1016  
  - [x] Get Quotes: Validate Header
    - [x] verified, postman test as part of #1035 
  - [x] POST/quotes - Sending quote with incorrect version
    - [x] verified, postman test as part of #1035 

**Acceptance Criteria**:
- [x] All issues are fixed or justified
- [x] Postman test available 
- [x] Validation of issues

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
