### ISSUE TITLE
Unit tests for central-settlement, part 2

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#1171]
## **Goal**:
As a Mojaloop contributor
I want to add unit tests to central-settlement, branch settlement-v2
so that full coverage is achieved for newly introduced functionality

**Tasks**:
- [ ] ~Unit tests to cover the following modules:~
  - [ ] ~src/domain/settlement/index.js~ (moved to #1100)
  - [ ] ~src/models/lib/enums.js~ (moved to #1100)
  - [ ] ~src/models/settlement/facade.js~ (moved to #1100)
  - [ ] ~src/models/settlement/settlementModel.js~ (moved to #1100)
  - [ ] ~src/models/settlementWindowContent/facade.js~ (moved to #1100)
  - [ ] ~src/models/settlementWindowContent/settlementWindowContentStateChange.js~  (#1100)
- [ ] Optional, if coverage is not full after merging #1165:
  - [ ] src/api/index.js
  - [ ] src/domain/settlementWindow/index.js
  - [ ] src/handlers/index.js
  - [ ] src/handlers/register.js
  - [ ] src/lib/healthCheck/subServiceHealth.js
  - [ ] src/handlers/settlementWindow/handler.js
  - [ ] src/models/settlementWindow/facade.js
  - [ ] src/shared/setup.js

**Acceptance Criteria**:
- [ ] Unit Tests pass
- [ ] Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- #1097
- #1099

## **Accountability**:
- Owner: @ggrg
- QA/Review: @ggrg

**Comment by ggrg** [comment]
Coverage when excluding scripts, listed in https://github.com/mojaloop/project/issues/1165, by **.nycrc.yml** temporary update:
```
exclude: [
  'src/api/index.js',
  'src/domain/settlementWindow/index.js',
  'src/handlers/index.js',
  'src/handlers/register.js',
  'src/lib/healthCheck/subServiceHealth.js',
  'src/handlers/settlementWindow/handler.js',
  'src/models/settlementWindow/facade.js',
  'src/shared/setup.js'
]
```
```
=============================== Coverage summary ===============================
Statements   : 87.61% ( 926/1057 )
Branches     : 90.86% ( 318/350 )
Functions    : 82.39% ( 117/142 )
Lines        : 88.02% ( 904/1027 )
================================================================================
```

**Comment by ggrg** [comment]
## Overall coverage:
```
=============================== Coverage summary ===============================
Statements   : 81.82% ( 1121/1370 )
Branches     : 84.3% ( 365/433 )
Functions    : 77.47% ( 141/182 )
Lines        : 81.91% ( 1091/1332 )
================================================================================
```

**Comment by ggrg** [comment]
Estimate has been changed back to 3, since most of the scripts have been moved to story #1100
