### ISSUE TITLE
Quoting Service POST /quotes allows empty quoteId and transactionId

### ISSUE THREAD

**Issue by ndonnan** [mojaloop/project#1172]
**Summary**:
The quoting-service POST /quotes endpoint allows empty quoteId and transactionId values.

These are marked as mandatory in the swagger definition and have patterns, however a "minLength" of 1 is required in order to validate empty values being sent in these fields.

**Tasks**:
- [x] Validate the changes
- [x] Make sure test added to postman test collection

**NOTE:** This is due to an underlying bug in enjoi, PR raised here: https://github.com/tlivings/enjoi/issues/73

Once the above PR is merged the "minLength" should be removed from the quoting-service swagger.json!

**Severity**:
Low

**Priority**:
Low

**Expected Behavior**
An error message is returned if an empty value is passed for these fields:
*quoteId:*
```
{
    "errorInformation": {
        "errorCode": "3102",
        "errorDescription": "Missing mandatory element - \"QuoteId\" is not allowed to be empty"
    }
}

```
*transactionId:*
```
{
    "errorInformation": {
        "errorCode": "3102",
        "errorDescription": "Missing mandatory element - \"TransactionId\" is not allowed to be empty"
    }
}
```

**Steps to Reproduce**
  1. POST a /quotes request with an empty quoteId or transactionId value.
  2. A 202 accepted will be returned instead of a 400 with the appropriate error message above.

**Specifications**
  - Component (if known): quoting-service
  - Version: 8.8.0-snapshot
  - Platform: all
  - Subsystem:
  - Type of testing: manual
  - Bug found/raised by: TIPS

**Pull Requests:**
- [x] https://github.com/mojaloop/quoting-service/pull/128
- [ ] https://github.com/mojaloop/postman/pull/80

**Notes**:

- Severity when opened: low
- Priority when opened: low

**Comment by amarmodus** [comment]
Check in PR(https://github.com/mojaloop/postman/pull/80) for the test screenshot
