### ISSUE TITLE
GET /quotes for unknown quote ID error response is 1001 instead of 3205

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1173]
**Summary**:
GET /quotes for unknown quote ID error response is 1001 instead of 3205

<img width="1370" alt="Screenshot 2020-01-21 10 36 10" src="https://user-images.githubusercontent.com/53434415/72797904-e0c48780-3c39-11ea-8e29-439412d2c074.png">

**Tasks**:
- [x] Bug Repro
- [x] Fix simulator to send 3205 error callback async instead of 404 sync
- [x] Fix quoting service to return generic 3000 error instead of 1001
- [x] Validate the changes
- [x] Fix tracing issues
- [x] Release cs-shared 9.1.1
- [x] Update QS with cs-shared 9.1.1
- [x] Make sure test added to OSS API postman test collection (@amarmodus) - part of 971

**Severity**:
Low

**Priority**:
Low

**Expected Behavior**
202 response with error callback of 3205.

**Steps to Reproduce**
curl --location --request GET 'http://dev1-quoting-service.mojaloop.live/quotes/482f5ea4-67b6-431a-9737-c77b0123706c' \
--header 'Accept: application/vnd.interoperability.quotes+json;version=1' \
--header 'Content-Type: application/vnd.interoperability.quotes+json;version=1.0' \
--header 'Date: Fri, 17 Jan 2020 10:37:29 GMT' \
--header 'FSPIOP-Source: payerfsp' \
--header 'FSPIOP-Destination: payeefsp'

make sure the quote id is valid UUID but unused quote ID.

**Specifications**
  - Component (if known): central-services
  - Version:v8.7.0
  - Platform: AWS
  - Subsystem:quoting service
  - Type of testing: functional
  - Bug found/raised by:@amarmodus

**Notes**:

- Severity when opened:
- Priority when opened:

## Pull Requests ##
- [x] https://github.com/mojaloop/quoting-service/pull/139
- [x] https://github.com/mojaloop/documentation/pull/166
- [x] https://github.com/mojaloop/simulator/pull/138
- [x] https://github.com/mojaloop/central-services-shared/pull/177

**Comment by elnyry** [comment]
@amarmodus I agree that it shouldn't be 1001 in this case. I would actually say its 3000 - Generic client error if the Switch gets a 404 synchronously from the FSP on the other side (in our case, a simulator).

How would the Switch know that the other FSP rejected it because it wasn’t found? if the simulator sends an error callback with 3205, we can just relay / forward it, otherwise, the Switch - in pass through mode has no visibility of it

So, two things, I think we should update the current simulator to give a 3205 in case an ID is not found and not a 404 and on secondly, if we get a 404 from the FSP on the other side, we can only send something generic like 3000 to the initiating FSP

What do you think..

@oderayi - please let us know if you have any further thoughts..

**Comment by amarmodus** [comment]
> @amarmodus I agree that it shouldn't be 1001 in this case. I would actually say its 3000 - Generic client error if the Switch gets a 404 synchronously from the FSP on the other side (in our case, a simulator).
> 
> How would the Switch know that the other FSP rejected it because it wasn’t found? If the simulator sends an error callback with 3205, we can just relay / forward it, otherwise, the Switch - in pass through mode has no visibility of it
> 
> So, two things, I think we should update the current simulator to give a 3205 in case an ID is not found and not a 404 and on secondly, if we get a 404 from the FSP on the other side, we can only send something generic like 3000 to the initiating FSP
> 
> What do you think..
> 
> @oderayi - please let us know if you have any further thoughts..

@elnyry - Yes agreed, switch doesn't know the error number, if it is not provided by the simulator. Looks like switch is passing 1001 error code.

**Comment by amarmodus** [comment]
<img width="1662" alt="Screenshot 2020-02-10 22 31 51" src="https://user-images.githubusercontent.com/53434415/74196496-44e4d500-4c55-11ea-9818-33ec00ed946f.png">
