### ISSUE TITLE
Add mechanicsm to use Event SDK to only create and apply trace headers and context

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1174]
## **Goal**:
As a `Hub Operator`, I want to `update Event SDK to be able to switch off all logging` so that `the SDK can be used as a tracing tool without creating the objects silently`

**Tasks**:
- [ ] Refactor Event SDK, so when `LOG_FILTER = ""` (no logging) and `SIDECAR_DISABLED = true` no event message object are created and the SDK only takes care of trace context and its passing through the services via message or headers

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vgenev 
- QA/Review: @mdebarros
