### ISSUE TITLE
Update projects to use node 12.16.0 LTS

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1175]
## **Goal**:
As a community member
I want to update all packages to use node 12.16.0 LTS
so that we are on the latest recommended version of node

**Tasks**:
- See example PR here: https://github.com/mojaloop/ml-api-adapter/pull/339
- Update "library" projects covered in #1228 
- [x] Apply to all projects with docker targets (this means updating the docker version in the `Dockerfile(s)` `.circleci/config.yml` and `.nvmrc`)
  - [x] bulk-api-adapter [@oderayi]
  - [x] central-event-processor [@oderayi] 
  - [x] central-ledger [@oderayi]
  - [x] email-notifier [@oderayi]
  - [x] ml-api-adapter [@oderayi]
  - [x] quoting-service [@oderayi]
  - [x] event-sidecar [@rmothilal]
  - [x] simulator [@oderayi]
  - [x] transaction-requests-service [@oderayi]
    - ~Fix joi validation~ (#1021) 
  - [x] account-lookup-service [@oderayi] 
     - ~Fix hapi-joi validation~ (#1021)
  - [x] central-settlement [@oderayi]
    - [x] Upgrade central-ledger
    - [x] Publish central-ledger to npm
  - [x] mojaloop-simulator [@oderayi]
     - [x] Fix unit tests/code

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] The projects used in mojaloop core services are upgraded to node 12.16.0 LTS

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-api-adapter/pull/352
- [x] https://github.com/mojaloop/bulk-api-adapter/pull/20
- [x] https://github.com/mojaloop/central-event-processor/pull/141
- [x] https://github.com/mojaloop/event-sidecar/pull/18
- [x] https://github.com/mojaloop/central-ledger/pull/596
- [x] https://github.com/mojaloop/email-notifier/pull/117
- [x] https://github.com/mojaloop/quoting-service/pull/150
- [x] https://github.com/mojaloop/simulator/pull/146
- [x] https://github.com/mojaloop/transaction-requests-service/pull/18
- [x] https://github.com/mojaloop/central-settlement/pull/244
- [x] https://github.com/mojaloop/account-lookup-service/pull/239
- [x] https://github.com/mojaloop/quoting-service/pull/153
- [x] https://github.com/mojaloop/mojaloop-simulator/pull/29

## **Follow-up**:
- N/A

**Dependencies**:
- [x] #1228 

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
