### ISSUE TITLE
Helm Release v8.8.0: Updates to helm, Supporting QA, Fixes, Releases

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1176]
## **Goal**:
As an ML OSS Code base maintainer
I want to _validate and make a Helm release in PI8 (Sprint 8.8) that is successfully validated by the Golden path tests_
so that _Community members can take and use a version of Mojaloop Switch services bundle that is tested and contains latest features and enhancements (added in and PI8(Sprints 8.7, 8.8) so far)_ 

This specific story is for making necessary changes for supporting Deployment, QA, Fixes, Integration and performing end-to-end testing for all the changes made since Helm v8.7.0

**Tasks**:
- [x] Make releases on all core services to have latest images / versions [@oderayi ]
- [x] Identify changes needed for helm (config / default.json)  [@oderayi ]
- [x] Initial PR with changes for v8.8.0 [ @mdebarros ]
  - [x] Deploy, validate, fix issues, redeploy [ @mdebarros @elnyry ]
  - [x] With stable deployment test Golden path [@amarmodus ]
- [x] Identify issues with QA Scripts if any - fix them and retest  [@amarmodus ]
- [x] Identify Bugs, log them  [@amarmodus , @elnyry ]
- [x] Validate finance portal (included for the first time in an ML Helm release) [@amarmodus ]
- [x] Fix bugs logged if critical [@vijayg10 @oderayi ]
- [x] Deploy, validate on AWS dev2 [@elnyry ]
- [x] Helm v8.8.0 released [@elnyry ]
- [x] Deployment of released Helm v8.8.0 on **Dev2** [@elnyry ]
- [x] Validation using Golden path regression tests etc on Dev2 [@amarmodus  ]
- [x] Deployment of released Helm v8.8.0 on **Dev1**
- [x] Validation using Golden path regression tests etc on Dev1

**Acceptance Criteria**:
- [x] Helm v8.8.0 is released after testing RC version on dev2
- [x] Helm v8.8.0 is deployed on AWS Dev2 without issues
- [x] QA (Golden path) on deployments done on AWS dev2 environment is done
- [x] Bugs are logged based on observations, failures
- [x] Bugs logged are fixed to make subsequent releases in individual services (or Helm)
- [x] All the changes needed for supporting v8.8.0 of Helm (List out major changes in release notes once release is ready)
- [x] Helm v8.8.0 is deployed on AWS Dev1 without issues
- [x] QA (Golden path) on deployments done on AWS dev1 environment is done

**Pull Requests**:
- [ ] 

**Follow-up**:
- N/A

**Dependencies**:
- [x] Need help with validating finance portal which is added for the first time to a mojaloop Helm release

**Accountability**:
- Owner: @mdebarros @elnyry 
- QA/Review: Core team
