### ISSUE TITLE
Standardize changes done as part of perf testing

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1177]
## **Goal**:
As an ML Community member
I want to _have the improvements done for performance available on master branch_
so that _I can make use of the improvements in my deployments_

**Tasks**:
- [ ] Pick changes from perf changes to be merged with master and raise PR for
  - [ ] sdk-scheme-adapter: Raise PR into master from perf branch, do clean-up, refining as necessary (pull latest changes from master as well).
  - [ ] central-ledger
  - [ ] ml-api-adapter
  - [ ] event-sdk
  - [ ] event-stream-processor
  - [ ] Helm
  - [ ] Simulator
- [ ] Above PRs are addressed and merged

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] Changes made to perf changes that can be standardized are raised as a Pull Request into the corresponding master branch
- [ ] Above changes are merged and releases made.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
