### ISSUE TITLE
Implement createSettlementModel admin API

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#1179]
## **Goal**:
As a Hub Operator
I want to have the functionality on the admin API (POST /settlementModel) to set a settlement model
so that I can use it to set the settlement model my scheme uses

**Notes**: 
- The only settlement models in this context are MULTILATERAL NET DEFERRED and MULTILATERAL GROSS IMMEDIATE
- Proposed API or resource is POST /settlementModel

**Tasks**:
- [x] Add POST route with Joi validations
- [x] Add ENUMS to shared lib
- [x] Create handler script
- [x] Implement DAO script
- [x] Provide unit tests to cover newly added functionality
- [x] Address PR comments

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [ ] ~Integration Tests pass~
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] https://github.com/mojaloop/central-services-shared/pull/175
- [ ] https://github.com/mojaloop/central-ledger/pull/578

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @ggrg
- QA/Review: @ggrg
