### ISSUE TITLE
Design a POC for realtime reflection of Financial Positions for each DFSP and resilient message processing

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#118]
**Goal**:
Design a POC for realtime reflection of Financial Positions for each DFSP and resilient message processing capability

**Tasks**:
- [ ] 

**Acceptance Criteria**:
- [x] Ability to view a DFSP's current position in near realtime on a dashboard
- [x] Document a design for the calculation of the position for each DFSP
- [x] Ability to ensure transactionality for each DFSP
- [x] Ability to ensure transactional resilience

**Dependencies**:
- [ ]

**Comment by mdebarros** [comment]
Design Presentation for PoC: https://drive.google.com/file/d/1876XFk8eJOgZLQ8cUJb_Z-ctxi_b9ib6/view?usp=sharing

Sequence Diagram:
![image.png](https://images.zenhubusercontent.com/5a0d3bc58a75884b9087a3dd/e636e6de-939c-47f0-8800-a6265a6d1047)

**Comment by elnyry** [comment]
Looks good, thanks for the discussions
