### ISSUE TITLE
Enhance getSettlementWindowById endpoint to report window content

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#1180]
## **Goal**:
As a Hub Operator
I want to view the window content when I query GET /settlementWindow/{id} endpoint
so that response also reports window contents

**Tasks**:
- [x] Modify DAO script (@bothadeon)
- [x] Modify handler to group db query result and response (@bothadeon)
- [x] Update Integration tests  (@bothadeon @lazolalucas )
- [x] Add unit tests to cover delivered functionality (@bothadeon)
- [x] PR Review [@ggrg ]

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Swagger definition is up to date
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-settlement/pull/238

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @ggrg
- QA/Review: @ggrg

**Comment by bothadeon** [comment]
Pull request : https://github.com/mojaloop/central-settlement/pull/237

# tests 609
# pass  609
============================ Coverage summary ===============================
Statements   : 100% ( 1321/1321 )
Branches     : 99.47% ( 375/377 )
Functions    : 100% ( 185/185 )
Lines        : 100% ( 1282/1282 )
===========================================================================
