### ISSUE TITLE
Presentation for Mojaloop Phase-4 kickoff

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1183]
## **Goal**:
As a member of the presenting team at the Mojaloop Phase-4 kickoff event
I want to _draft presentations and other material necessary for the event_
so that _it can be used for discussions, demonstrations at the event and later for circulation and publishing_

**Tasks**:
- [x] Decide on the template, share the Initial draft v0.1 with just topics [@mdebarros @elnyry ]
- [x] Discussion with team about topics involved, demonstrations to be done [@elnyry ]
- [x] Identify topics and owners for each section based on attendance, etc 
- [x] Draft with all topics and placeholders for every discussion are added
- [x] Individual owners to submit initial draft of slides
  - [x] Intro, Summary [@elnyry ]
  - [x] Consolidation [@mdebarros @elnyry ]
  - [x] Performance [@mdebarros ]
  - [x] Event Framework [@mdebarros ]
  - [x] Settlement [@ggrg ]
  - [x] Features
  - [x] Functional / self testing-toolkit [@vijayg10 , @elnyry]
  - [x] Community [@elnyry]
  - [x] RoadMap [@elnyry ]
- [x] Review a complete slide deck 
- [x] Second iteration of presentation deck with updated slides from each owner
- [x] Complete review of the slide deck and make changes.
- [x] A v0.9 of the slide deck is ready

**Acceptance Criteria**:
- [x] A slide-deck that is to be used for the Mojaloop Phase-4 kickoff event is drafted and feedback incorporated
- [ ] Individual owners for each topic/section are identified responsible for that topic regarding both slides and discussions at the event.
- [x] Updated Designs are used

**Pull Requests**:
- [ ] 
 
**Follow-up**:
- N/A

**Dependencies**:
- N/A

**Accountability**:
- Owner: @elnyry 
- QA/Review: ML Core team
