### ISSUE TITLE
Refactor stale trace functionality in the event-streaming-processor

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1184]
## **Goal**:
As a `Hub Operator`, I want to `finish stale traces` in the event-stream-processor cache correctly if there are loose spans, as this is done in the recreateTraceObservable

**Tasks**:
- [ ] Take care for loose spans (spans which have parents, but doesn't have children and are not last spans) in the `finishStaleTrace` functionality 

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vgenev 
- QA/Review: @mdebarros
