### ISSUE TITLE
Performance Characterisation - Transfer Prepare Handler

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1185]
## **Goal**:
As a <stakeholder> I want to <action> so that <reason>

**Tasks**:
- [ ] Instrumentation (aggregate & specific to each pod)
    - [ ] Logging (rate - lines per second, how much time per append, tag log level)
    - [ ] Database ()
    - [ ] Event Framework ()
- [ ] As-Is
    - [ ] Characterise Transfer Prepare Handler with standard deployment
- [ ] Stubbed Database 
    - [ ] Mock/stub DB specific operations
    - [ ] Characterise Transfer Prepare Handler with stubbed Database
- [ ] Hosted
    - [ ] Characterise Transfer Prepare Handler with hosted Kafka on AWS
    - [ ] Characterise Transfer Prepare Handler with hosted Kafka on AWS + stubbed Database (if required)

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
Characterization items done for Phase-3; will re-assess after PoC being done in PI-10
