### ISSUE TITLE
Performance Characterisation - Central Services Stream library

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1187]
## **Goal**:
As Hub TechOps
I want to understand the performance characteristics of the stream library
so that I can make informed decisions of configuration needed and capabilities of the library used

**Tasks**:
- ~[ ] Benchmark Central Services Stream library~
- [ ] Instrumentation
    - [x] Central Service Stream (rate - read/write/s, data per/s, time spend read/write, data size, etc, include commit operations) - @vgenev 
    - [ ] ~Enhance log-processing script to push metrics into Prometheous~
        - [ ] ~stats for end-to-end flow (including prepare & position)~
        - [ ] ~stats to show time between send (producer) and receive (consumer)~
- [ ] ~Dashboards~
    - [ ] ~Real-time metrics scapred from /metrics end-point~
    - [ ] ~Log-processed metric output~
- [x] Docker image:
    - [x] HapiJs HTTP Server @vgenev / @mdebarros 
         - [x] /metrics end-point
         - [x] /health end-point (just return `{ status: ok }`)
    - [x] Helm/K8s script for deployment & config
    - [x] CLI for Producer
        - [x] Log start/end entries
        - [x] Size of message
        - [x] Batch size
        - [x] number of messages
        - [x] Kafka Client Configuration
        - [x] Topic Configuration (includes topic name)
        - [x] Node IO Threads
    - [x] CLI for Consumer
        - [x] Log start/end entries
        - [x] Batch size
        - [x] Kafka Client Configuration
        - [x] Topic Configuration (includes topic name)
        - [x] Node IO Threads
-
- [ ] ~Test Cases~
    - [ ] ~Characterise Producer (stand-alone) - benchmark config/options (specifically for timeouts, etc)~
    - [ ] ~Characterise Consumer (stand-alone) - benchmark config/options (specifically for timeouts, etc)~
    - [ ] ~Characterise Producer + Consumer (process log files)~

**Acceptance Criteria**:
- [x] Test project is created
- [x] Data is gathered from CSS
- [x] Data is gathered from node-rdkafka lib
- [x] Docker image of the test project is created
- [x] Test project can be deployed to Kubernetes cluster

## **Active branches**:
- [ ] https://github.com/mojaloop/central-services-stream/tree/release/9.1.0-performance

## **Follow-up**:
- #1237 

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @mdebarros 
- QA/Review: TBC

## ** Refernce**: 
- https://mdebarros.github.io/kafkapoc-results/
