### ISSUE TITLE
Performance Optimisation - Timeout Handler

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1188]
## **Goal**:
As a <stakeholder> I want to <action> so that <reason>

**Tasks**:
- [ ] Identify solution to resolve current row scan/lock issue:
    - [ ] Option 1: Use same code/algorithm but consider setting a non-locking isolation level during row scan to identify what has timed-out, then lock specific rows for time-out process
    - [ ] Option 2: Insert a record as part of prepare into Transfer Timeout Table (as per PI4 presentation slide 31)

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
