### ISSUE TITLE
Benchmark Our Open Source Vulnerability Management Tool against Commercial tools

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1189]
## **Goal**:
As an `OSS developer`
I want to `benchmark the existing and new container and code security tools against 1 or 2 commercial offerings`
so that `we gain a better understanding of our OSS Security approach`

## **Summary**:
>Measure against one or two of the advanced commercial offering (Whitesource or Blackduck depending with the commercial feasibility) to check if they are any major gap or blind spots – All

**Tasks**:
- [ ] Summarize existing reports from `anchore-cli` github security, npm audit etc. Apply for
  - [ ] central-ledger
  - [ ] ml-api-adapter
  - [ ] _[todo: other  projects?]_

- [ ] Negotiate trial license for checkmarkx and some other commercial tool and run across the following repos:
  - [ ] central-ledger
  - [ ] ml-api-adapter
  - [ ] _[todo: other  projects?]_

- [ ] Perform an analysis on the commercial tools vs our approach, and feed back to the community in a summary document

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@rasputtintin @godfreykutumela @pedrosousabarreto 

This one isn't in the list, but I think we should include it in the PI since it was specifically asked for in the PI.

It also ties somewhat into the tool summary list.

**Comment by lewisdaly** [comment]
The challenge will be getting access to those commercial tools

**Comment by rasputtintin** [comment]
Currently comparing output of:
- AnchoreCLI
- Snyk
- Tenable Nessus IO

**Comment by godfreykutumela** [comment]
Thanks Victor and we can please report on the progress on weekly - Kim has asked for this visibility on our work

**Comment by godfreykutumela** [comment]
Hello @rasputtintin can we report progress per sprint based on the current archivements? I am happy to keep it throughout the sprints to allow us more time to test more tools. Let me know if this is ok with everyone @lewisdaly @pedrosousabarreto @elnyry

**Comment by godfreykutumela** [comment]
Hello @rasputtintin can you please update this issue with the latest status

**Comment by rasputtintin** [comment]
I encountered challenges with Tenable Nessus IO licences. I have installed Rapid7 Container scanner and proceeding to analyse outputs compared to AnchoreCLI and Snyk.

**Comment by godfreykutumela** [comment]
Noted thanks @rasputtintin

**Comment by godfreykutumela** [comment]
@rasputtintin you're updating the wrong story, this is supposed to be in the Container security story this is restrictly for comparin NPM license audit and Blackduck

**Comment by rasputtintin** [comment]
Hi @godfreykutumela I have managed to run Anchore-CLI (community) vs Nexpose by Rapid7. The results are under analysis.

**Comment by godfreykutumela** [comment]
Noted @rasputtintin and let's try completing by thursday so that can have the analysis results included in our dry run presentation on friday.

**Comment by lewisdaly** [comment]
Thanks @rasputtintin , let me know where I can be of help with the comparison.

**Comment by elnyry** [comment]
@godfreykutumela - is this still blocked? Please review and move to an appropriate pipeline
