### ISSUE TITLE
Performance Issue - DB Scaling Optimistic Lock Handling

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1190]
**Summary**:
Currently when multiple instances of the database exists with multiple instances of our central APIs we get 'ER_LOCK_DEADLOCK' errors on all the central-services that connect to the central-ledger database and in turn the transfer fails. This occurs as a service is locking a row on one instance of the database whilst another is attempting to access that information this is causing the 'ER_LOCK_DEADLOCK' error. We need to introduce retry logic into our queries to ensure that they query has another chance at retrying for the relevant information.

**Severity**:
Medium

**Priority**:
Critical

**Expected Behavior**
When the database throws an 'ER_LOCK_DEADLOCK' error, our code should have retry functionality to have another attempt at commiting or reding information from the database

**Steps to Reproduce**
  1. Spin up an environment with multiple central-ledger databases and central-service handlers 
  2. Use jMeter to push in load into the system
  3. Monitor logs of the central-service handlers as well as the database

**Tasks**
  - [ ] Review logs to determine all areas that are currently having issues
  - [ ] Apply retry logic to areas found in 1
  - [ ] Retest
  - [ ] Investigate different monitoring tools that can give us an accurate description of the issues happening on the database
  - [ ] Apply fixes to performance stream so that they can test with multiple database instances

**Specifications**
  - Component (if known): central-ledger
  - Version: 9.3.0
  - Platform: nodejs
  - Subsystem: database queries
  - Type of testing: end-to-end
  - Bug found/raised by: @rmothilal 

**Notes**:

- Severity when opened: High
- Priority when opened: Critical
