### ISSUE TITLE
Performance Issue - EFK is unable to ingest events during load tests

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1193]
## **Goal**:
As a <stakeholder> I want to <action> so that <reason>

**Tasks**:
- [ ] Test throttling capability on the latest version of Event-Stream-Processor 
- [ ] Consider re-installing EFK/APM based on the following article (or similar) to handle high loads on ingestion of events/logs: https://sematext.com/blog/kubernetes-elasticsearch/

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
With rolling feature, this should now be taken care of
