### ISSUE TITLE
POST /transactionRequests does not work 

### ISSUE THREAD

**Issue by agalaguz** [mojaloop/project#1194]
**Summary**:
We are trying to emulate **5.1.6.8 Merchant-Initiated Merchant Payment** flow as **Payee FSP** [screen](http://prntscr.com/qy2bpx) by sending `POST transactionRequests` routes to **Mojaloop** server that we setup using [Official Deployment Quide](https://mojaloop.io/documentation/deployment-guide/). Unfortumately, we are getting an error inside K8S logs. 

**Severity**:
High (at least for our team)

**Priority**:
Critical (at least for our team as we need to emulate Merchant-Initiated Merchant Payment asap)

**Expected Behavior**
Once we send `POST /transactionRequests` to **Moja**, we should receive a `PUT transactionRequests/{id}` back from it.

**Specifications**
All the server details are here: https://docs.google.com/document/d/1aolOKDi3Yf60-Spfd23_v6zTaAmf8MILo8wnps8ekRQ/edit?usp=sharing

**Steps to Reproduce**
  1. Setup **Mojaloop** and [FSP simulator](https://github.com/mojaloop/simulator) using [Official deployment guide](https://mojaloop.io/documentation/deployment-guide/) (steps 1-5) w/o errors.
  2. Import to your Postman 4 collections and Env. config as per [Steps 1-2 of Postman collections for Mojaloop](https://github.com/mojaloop/postman)
  3. Execute [OSS-New-Deployment-FSP-Setup.postman_collection](https://github.com/mojaloop/postman) w/o errors.
  4. In `Golden_Path Postman collection` find -> `transaction-request-service` -> `transactionRequests` route. 
  5. Execute `transactionRequests`.
  6. Go to `transaction-request-service` in Pods of your K8S.
  7. Open logs of it.
  8. Find an **error** there

**Error**
```
2020-02-05T09:30:27.809Z - info: participantEndpointCache::getEndpoint::endpointType - FSPIOP_CALLBACK_URL_TRANSACTION
2020-02-05T09:30:27.809Z - info: [fsp=fspiop-source] ~ participantEndpointCache::fetchEndpoints := Refreshing the cache for FSP: fspiop-source
2020-02-05T09:30:27.809Z - info: sendRequest::request {"url":"http://localhost:3001/participants/fspiop-source/endpoints","method":"GET","headers":{"Accept":"application/vnd.interoperability.participants+json;version=1.0","FSPIOP-Destination":"switch","Content-Type":"application/vnd.interoperability.participants+json;version=1.0","Date":"Wed, 05 Feb 2020 09:30:27 GMT","FSPIOP-Source":"switch"},"responseType":"json"}
(node:23) UnhandledPromiseRejectionWarning: FSPIOPError: Invalid template! Template should be a "string" but "undefined" was given as the first argument for mustache#render(template, view, partials)
    at createFSPIOPError (/opt/transaction-requests-service/node_modules/@mojaloop/central-services-error-handling/src/factory.js:185:12)
    at Object.reformatFSPIOPError (/opt/transaction-requests-service/node_modules/@mojaloop/central-services-error-handling/src/factory.js:272:12)
    at Object.exports.getEndpoint (/opt/transaction-requests-service/node_modules/@mojaloop/central-services-shared/src/util/endpoints.js:123:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Invalid template! Template should be a "string" but "undefined" was given as the first argument for mustache#render(template, view, partials)
    at Object.render (/opt/transaction-requests-service/node_modules/mustache/mustache.js:689:13)
    at Object.exports.getEndpoint (/opt/transaction-requests-service/node_modules/@mojaloop/central-services-shared/src/util/endpoints.js:120:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 91)
2020-02-05T09:30:27.812Z - error: Request failed with status code 400
2020-02-05T09:30:27.812Z - error: participantEndpointCache::fetchEndpoints:: ERROR:'{"message":"Failed to send HTTP request to host","replyTo":"switch","apiErrorCode":{"code":"1001","message":"Destination communication error","name":"DESTINATION_COMMUNICATION_ERROR","type":{"regex":"^10[0-9]{2}$","description":"Generic Communication Error","httpStatusCode":503,"name":"GENERIC_COMMUNICATION_ERROR"},"httpStatusCode":503},"extensions":[{"key":"cause","value":"[{\"key\":\"url\",\"value\":\"http://localhost:3001/participants/fspiop-source/endpoints\"},{\"key\":\"sourceFsp\",\"value\":\"switch\"},{\"key\":\"destinationFsp\",\"value\":\"switch\"},{\"key\":\"method\",\"value\":\"GET\"},{\"key\":\"request\",\"value\":\"{\\\"url\\\":\\\"http://localhost:3001/participants/fspiop-source/endpoints\\\",\\\"method\\\":\\\"GET\\\",\\\"headers\\\":{\\\"Accept\\\":\\\"application/vnd.interoperability.participants+json;version=1.0\\\",\\\"FSPIOP-Destination\\\":\\\"switch\\\",\\\"Content-Type\\\":\\\"application/vnd.interoperability.participants+json;version=1.0\\\",\\\"Date\\\":\\\"Wed, 05 Feb 2020 09:30:27 GMT\\\",\\\"FSPIOP-Source\\\":\\\"switch\\\"},\\\"responseType\\\":\\\"json\\\"}\"},{\"key\":\"errorMessage\",\"value\":\"Request failed with status code 400\"},{\"key\":\"status\",\"value\":400},{\"key\":\"response\",\"value\":{\"errorInformation\":{\"errorCode\":\"3101\",\"errorDescription\":\"Malformed syntax - \\\"name\\\" must only contain alpha-numeric characters\"}}}]"}],"cause":"Error: Request failed with status code 400\n    at createError (/opt/transaction-requests-service/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/opt/transaction-requests-service/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/opt/transaction-requests-service/node_modules/axios/lib/adapters/http.js:237:11)\n    at IncomingMessage.emit (events.js:194:15)\n    at endReadableNT (_stream_readable.js:1125:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}'
2020-02-05T09:30:27.813Z - error: participantEndpointCache::getEndpoint:: ERROR:'TypeError: Invalid template! Template should be a "string" but "undefined" was given as the first argument for mustache#render(template, view, partials)'
2020-02-05T09:30:27.813Z - info: Error forwarding transaction request to endpoint undefined: FSPIOPError: Invalid template! Template should be a "string" but "undefined" was given as the first argument for mustache#render(template, view, partials)
    at createFSPIOPError (/opt/transaction-requests-service/node_modules/@mojaloop/central-services-error-handling/src/factory.js:185:12)
    at Object.reformatFSPIOPError (/opt/transaction-requests-service/node_modules/@mojaloop/central-services-error-handling/src/factory.js:272:12)
    at Object.exports.getEndpoint (/opt/transaction-requests-service/node_modules/@mojaloop/central-services-shared/src/util/endpoints.js:123:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Invalid template! Template should be a "string" but "undefined" was given as the first argument for mustache#render(template, view, partials)
    at Object.render (/opt/transaction-requests-service/node_modules/mustache/mustache.js:689:13)
    at Object.exports.getEndpoint (/opt/transaction-requests-service/node_modules/@mojaloop/central-services-shared/src/util/endpoints.js:120:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:23) UnhandledPromiseRejectionWarning: FSPIOPError: Invalid template! Template should be a "string" but "undefined" was given as the first argument for mustache#render(template, view, partials)
    at createFSPIOPError (/opt/transaction-requests-service/node_modules/@mojaloop/central-services-error-handling/src/factory.js:185:12)
    at Object.reformatFSPIOPError (/opt/transaction-requests-service/node_modules/@mojaloop/central-services-error-handling/src/factory.js:272:12)
    at Object.exports.getEndpoint (/opt/transaction-requests-service/node_modules/@mojaloop/central-services-shared/src/util/endpoints.js:123:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Invalid template! Template should be a "string" but "undefined" was given as the first argument for mustache#render(template, view, partials)
    at Object.render (/opt/transaction-requests-service/node_modules/mustache/mustache.js:689:13)
    at Object.exports.getEndpoint (/opt/transaction-requests-service/node_modules/@mojaloop/central-services-shared/src/util/endpoints.js:120:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 94) 
```

**Notes:**
on this line could be a bug `sendRequest::request {"url":"http://localhost:3001/participants/fspiop-source/endpoints","method":"GET","headers":{"Accept":"application/vnd.interoperability.participants+json;version=1.0","FSPIOP-Destination":"switch","Content-Type":"application/vnd.interoperability.participants+json;version=1.0","Date":"Wed, 05 Feb 2020 13:44:39 GMT","FSPIOP-Source":"switch"},"responseType":"json"}`

cause cause when I'm trying to make manually this request, on `centralledger-service/participants/fspiop-source/endpoints` getting error `"Malformed syntax - \"name\" must only contain alpha-numeric characters"`

Please let me know if I need to add more details.

Best regards,
Anton

**Tasks**: [@vijayg10 ]
- [x] Bug repro 
- [x] Root cause analysis
- [x] Fix transaction-requests-service
- [x] Fix Simulator
- [x] Fix postman setup scripts
- [x] Update Helm
- [x] Make releases for transaction-requests-service, simulator

PRs:
- [x] https://github.com/mojaloop/transaction-requests-service/pull/17
- [x] https://github.com/mojaloop/simulator/pull/140
- [x] https://github.com/mojaloop/postman/pull/85 
- [x] https://github.com/mojaloop/helm/pull/257

**Comment by brunosmm** [comment]
Hi @vijayg10, I saw you are working on this issue. Is there any update about it? I am curious to learn more. :)

**Comment by vijayg10** [comment]
> Hi @vijayg10, I saw you are working on this issue. Is there any update about it? I am curious to learn more. :)

Hi @brunosmm, I found some compatibility issues on helm 8.7.0. I am trying to run helm 8.8.0 to check whether this issue is fixed in the newer services or not. I am currently on it.

**Comment by vijayg10** [comment]
This bug is fixed now in helm v8.8.0.

**Comment by agalaguz** [comment]
@vijayg10 Thank you, we will check it!

**Comment by agalaguz** [comment]
Hi @vijayg10,
We setup helm v8.8.0 successfully which is cool.
Just step-by-step description of steps we did and what we faced:

1) We run 2 Postman collections:
- OSS-New-Deployment-FSP-Setup
- Golden_Path 
in order to add test data to the platform

2) Then we run `POST transactionRequests` from Golden_Path collection manually to [Transaction Request Service](http://prntscr.com/r1pxxa) in order to check if we receive `PUT transactionRequests/{id}` from [Mojaloop simulator](https://github.com/mojaloop/simulator) that also [exists in K8S](http://prntscr.com/r1pyjo).

3) We expected that 
- Transaction Request Service will send the `POST transactionRequests` to Mojaloop simulator 
- then, Mojaloop simulator send `PUT transactionRequests/{id}` to Transaction Request Service
- After that Transaction Request Service send `PUT transactionRequests/{id}` to us (at least try to do it)

However, in K8S logs we found that `POST transactionRequests` wasn't delivered to Mojaloop simulator, maybe because of the error in Transaction Request Service's logs.

The error is the next:
```
 (node:24) UnhandledPromiseRejectionWarning: FSPIOPError: Invalid template! Template should be a "string" but "undefined" was given as the first argument for mustache#render(template, view, partials)
    at createFSPIOPError (/opt/transaction-requests-service/node_modules/@mojaloop/central-services-shared/node_modules/@mojaloop/central-services-error-handling/src/factory.js:198:12)
    at Object.reformatFSPIOPError (/opt/transaction-requests-service/node_modules/@mojaloop/central-services-shared/node_modules/@mojaloop/central-services-error-handling/src/factory.js:285:12)
    at Object.exports.getEndpoint (/opt/transaction-requests-service/node_modules/@mojaloop/central-services-shared/src/util/endpoints.js:123:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Invalid template! Template should be a "string" but "undefined" was given as the first argument for mustache#render(template, view, partials)
    at Object.render (/opt/transaction-requests-service/node_modules/@mojaloop/central-services-shared/node_modules/mustache/mustache.js:721:13)
    at Object.exports.getEndpoint (/opt/transaction-requests-service/node_modules/@mojaloop/central-services-shared/src/util/endpoints.js:120:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:24) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 22) 
```

Could you please suggest a solution? Happy to jump on a call to share the screen and show all steps we are doing. 

Thanks.

**Comment by elnyry** [comment]
hi @agalaguz 

I would suggest first, to get the latest versions of the collections and then re-import them. Please check to see if there is any configuration issue as well, after that it can be debugged further.

On one of the AWS environments we use, it currently works as you mentioned in your step#3. Below are the logs from the simulator where you can see that it received the `POST /transactionRequests` and sends a `PUT transactionRequests/{id}`

```
2020-02-13T11:40:53.866Z - info: L1p-Trace-Id=undefined - Method: post Path: /transactionRequests Query: {}
2020-02-13T11:40:53.866Z - info: L1p-Trace-Id=undefined - Headers: {"host":"dev2-transaction-requests-service.mojaloop.live","connection":"close","x-request-id":"2c5389ab90bc8fe31a6a0248906114b6","x-real-ip":"10.1.2.119","x-forwarded-for":"10.1.2.119","x-forwarded-host":"dev2-transaction-requests-service.mojaloop.live","x-forwarded-port":"80","x-forwarded-proto":"http","x-original-uri":"/transactionRequests","x-scheme":"http","x-original-forwarded-for":"10.1.2.119","content-length":"1193","content-type":"application/vnd.interoperability.transactionRequests+json;version=1.0","date":"Thu, 13 Feb 2020 11:40:53 GMT","fspiop-source":"payerfsp","fspiop-destination":"payeefsp","fspiop-signature":"{\"signature\":\"iU4GBXSfY8twZMj1zXX1CTe3LDO8Zvgui53icrriBxCUF_wltQmnjgWLWI4ZUEueVeOeTbDPBZazpBWYvBYpl5WJSUoXi14nVlangcsmu2vYkQUPmHtjOW-yb2ng6_aPfwd7oHLWrWzcsjTF-S4dW7GZRPHEbY_qCOhEwmmMOnE1FWF1OLvP0dM0r4y7FlnrZNhmuVIFhk_pMbEC44rtQmMFv4pm4EVGqmIm3eyXz0GkX8q_O1kGBoyIeV_P6RRcZ0nL6YUVMhPFSLJo6CIhL2zPm54Qdl2nVzDFWn_shVyV0Cl5vpcMJxJ--O_Zcbmpv6lxqDdygTC782Ob3CNMvg\\\",\\\"protectedHeader\\\":\\\"eyJhbGciOiJSUzI1NiIsIkZTUElPUC1VUkkiOiIvdHJhbnNmZXJzIiwiRlNQSU9QLUhUVFAtTWV0aG9kIjoiUE9TVCIsIkZTUElPUC1Tb3VyY2UiOiJPTUwiLCJGU1BJT1AtRGVzdGluYXRpb24iOiJNVE5Nb2JpbGVNb25leSIsIkRhdGUiOiIifQ\"}","fspiop-http-method":"POST","user-agent":"PostmanRuntime/7.22.0","postman-token":"72ed440f-63a7-40a7-a24b-4cac0b69b58d","accept-encoding":"gzip, deflate, br","accept":"application/vnd.interoperability.transactionRequests+json;version=1"}
2020-02-13T11:40:53.868Z - info: Executing PUT: [http://d2-880-01-transaction-requests-service/transactionRequests/689c97fa-37a2-47bb-a6a4-4385145917e1], HEADERS: [{"Content-Type":"application/vnd.interoperability.transfers+json;version=1.0","FSPIOP-Source":"payeefsp","FSPIOP-Destination":"payerfsp","Date":"Thu, 13 Feb 2020 11:40:53 GMT","FSPIOP-HTTP-Method":"PUT","FSPIOP-URI":"/transactionRequests/689c97fa-37a2-47bb-a6a4-4385145917e1"}], BODY: [undefined]
2020-02-13T11:40:53.870Z - info: L1p-Trace-Id=undefined - Response: null Status: 202
2020-02-13T11:40:53.882Z - info: 2020-02-13T11:40:53.882Z
2020-02-13T11:40:53.884Z - info: response: 200
2020-02-13T11:40:53.898Z - info: L1p-Trace-Id=5efea9ca01316c70973188686917b00a - Method: put Path: /transactionRequests/689c97fa-37a2-47bb-a6a4-4385145917e1 Query: {}
2020-02-13T11:40:53.898Z - info: L1p-Trace-Id=5efea9ca01316c70973188686917b00a - Headers: {"host":"dev2-simulator.mojaloop.live","connection":"close","x-request-id":"7a3131b3fdae385df6b40324f9cebafa","x-real-ip":"10.42.7.157","x-forwarded-for":"10.42.7.157","x-forwarded-host":"dev2-simulator.mojaloop.live","x-forwarded-port":"80","x-forwarded-proto":"http","x-original-uri":"/transactionRequests/689c97fa-37a2-47bb-a6a4-4385145917e1","x-scheme":"http","content-length":"283","content-type":"application/vnd.interoperability.transfers+json;version=1.0","fspiop-source":"payeefsp","fspiop-destination":"payerfsp","date":"Thu, 13 Feb 2020 11:40:53 GMT","fspiop-http-method":"PUT","fspiop-uri":"/transactionRequests/689c97fa-37a2-47bb-a6a4-4385145917e1","traceparent":"00-5efea9ca01316c70973188686917b00a-129a59b45d6e834d-00","user-agent":"axios/0.19.2"}
2020-02-13T11:40:53.899Z - info: L1p-Trace-Id=5efea9ca01316c70973188686917b00a - Response: null Status: 200
```

**Comment by vijayg10** [comment]
Yes the problem might be because of old post man setup collection. Please delete the collection from postman. Git pull the postman repo and import the New setup collection again and run.

**Comment by elnyry** [comment]
Validated on AWS `dev2` envt and works now

**Comment by brunosmm** [comment]
Hey @elnyry, those AWS envs are public? Where we find information in the documentation to send request to it?

**Comment by elnyry** [comment]
@brunosmm these are not public but dev, qa envts for the core-oss team to validate releases, fixes and other updates. Unfortunately, there is no intention to make these public at this time.
