### ISSUE TITLE
Research Versioning best practices

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1197]
## **Goal**:
As a `switch implementer` 
I want to `research the best practices for managing and implementing versioning`
so that `we have a clear understanding of well tried approaches`.

**Tasks**:
- [ ] Research best practices related to implementing API versioning, both in defining, implementing etc.
  - Looking for Kubernetes/Microservices specific approaches may be helpful
- [ ] produce a short summary document of research, in markdown format in the [Discussion Documents](https://github.com/mojaloop/documentation/tree/master/discussions) directory in `mojaloop/documentation`

**Acceptance Criteria**:
- [ ] Updated summary discussion doc with findings

## **Pull Requests**:
- [ ] https://github.com/mojaloop/documentation/pull/172

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: @elnyry

**Comment by lewisdaly** [comment]
I have started this doc, and have a reasonable understanding of what questions we need to ask.

My final topic to read about is versioning messages within Kafka, and best practices around this.
