### ISSUE TITLE
Define/Find best practices for semantic versioning in Mojaloop

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1198]
## **Goal**:
As an `switch implementer`
I want to `have a standard for semantic versioning in future mojaloop implementations`
so that `future implementations can be well aligned.`

**Tasks**:
- [ ] research best practices around semantic versioning
- [ ] add to versioning discussion document
- [ ] _optional?:_ Add to the mojaloop standards in `mojaloop/documentation`

**Acceptance Criteria**:
- [ ] Updated .md document in [discussion-documents](https://github.com/mojaloop/documentation/tree/master/discussions)

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: TBC

**Comment by lewisdaly** [comment]
I feel pretty happy that we've covered this in the existing working doc.
