### ISSUE TITLE
Determine Scope for Versioning Proposal

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1199]
## **Goal**:
As a `Mojaloop OSS maintainer`
I want to `have a scope for the first iteration of the versioning proposal`
so that `the community and adopters know what is and isn't covered`

Instead of versioning 'all the things' define a set scope of what is reasonable to propose as a good starting point for versioning in Mojaloop.

Previous research will inform this ticket very heavily, in terms of what we can get done and approved by the community in this PI.

**Tasks**:
- [x] Update discussion doc with a proposed scope.

**Acceptance Criteria**:
- [x] An initial proposal with a scope for versioning in Mojaloop is made

## **Pull Requests**:
- [x] https://github.com/mojaloop/documentation/pull/177

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @elnyry 
- QA/Review: @lewisdaly , @matdehaast (and then DA)
