### ISSUE TITLE
Setup AWS Infrastructure for General computing for performance

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#120]
**Goal**:
Setup AWS Infrastructure for General computing for performance

**Tasks**:
- [x] Setup m4.xlarge instances on AWS
- [x] Add required storage to each node
- [x] Add required tags to each node
- ~~Update kubespray script to add the additional m4.xlarge nodes~~ (Not applicable)
- ~~Execute kubespray script to add the additional m4.xlarge nodes~~ (Not applicable)

**Acceptance Criteria**:
- [x] Nodes of m4.xlarge created on AWS
- [x] K8s installed and configured on the m4.xlarge Nodes
- [x] m4.xlarge Nodes added to the existing K8s k8s-venice cluster on AWS

**Dependencies**:
- [x] AWS Account limit increase [**BLOCKER**]

**Comment by elnyry** [comment]
Looks good.
