### ISSUE TITLE
Propose LTS Schedule for Mojaloop OSS

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1201]
## **Goal**:
As a `Hub`
I want `a predictable LTS schedule for the Mojaloop OSS`
so that I can `effectively deploy and manage my switch implementation`

**Tasks**:
- [x] Propose LTS schedule - initial draft
- [x] Present proposal during Mid-PI Review
- [x] Propose at PI-11 Community event

**Acceptance Criteria**:
- [x] A proposal for LTS for Mojaloop is made to the Community after reviews

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: TBC

**Comment by lewisdaly** [comment]
As we talked about in the standup yesterday:

We need to go into detail here about what is in scope for support at the same time, and how we manage that support.

For example, we could have multiple versions of the `central-ledger` that need to be supported at any given time, say `v10.0`, `v10.1` and `v11.0`.

For each of these versions, we need to think about:
- **source control**: How do we streamline the effort required to maintain older versions?
- **security scans + fixes**: How do we (automatically if possible) scan images for vulnerabilities, and update them accordingly (e.g. produce images `v10.0.1`, `v10.1.1` when the development team is already working on `v11.0`?
- **release management**: How do we make sure such updates are passed on to helm? and deployed effectively?
