### ISSUE TITLE
Associating quotes with transfers

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1205]
## **Goal**:
As an FSP
I want to _be able to configure the testing tool-kit_
so that _it can validate incoming transfer requests and ensure they're in accordance with an existing quote_

**Tasks**:
- [x] Associate transfers with an existing quote
- [x] An error callback is sent if there is no association
- [x] This is made configurable
- [x] Testing

**Acceptance Criteria**:
- [x] The testing tool-kit can be configured to validate that requests on POST /transfers have an associated existing quote.
- [x] The testing tool-kit sends an error callback if validation on quote-transfer association fails

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
