### ISSUE TITLE
Performance Characterisation - Fulfil Response Flow

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1206]
## **Goal**:
As Hub TechOps
I want to _understand the performance characteristics subject to particular level of scaling_
so that _I can use the ratio and characteristics to find an optimal number of handlers needed for my Switch deployment_

**Tasks**:
- [x] Pre-load Fulfil Topic with message for X time [Note: _Seeing ~294 TPS on the fulfil leg with 4 handlers_]
- [x] Scale fulfil topic for 4, 8 handlers [Not much difference]
- [x] End-to-end test with sufficient scaling (with infrastructure scaling as well)

**Acceptance Criteria**:
- [x] Fulfil handler performance characteristics (subject to particular scale) are recorded
- [x] End-to-end transfers performance characteristics (subject to particular scale) are recorded

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
