### ISSUE TITLE
Implement settlementModels management - GET and PUT operations

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#1207]
## **Goal**:
As a Hub Operator
I want to have the functionality on the admin API (GET /settlementModels, GET /settlementModels/{name}, PUT /settlementModels/{name}) to request information about all available settlementModels, to request information about settlementModels by name, and disable/enable an existing settlementModel by changing its isActive state
so that I can further mange the existing settlement models

**Notes**: 
- ~As part of this story, please also change POST /settlementModel to POST /settlementModels (plural)~ moved to #1211 

**Tasks**:
- [x] Add PUT/GET routes with Joi validations, where applicable
  - [x] Include #1211 autoPositionReset property to GET requests
- [x] Add ENUMS to shared lib, if applicable
- [x] Create handler scripts
- [x] Implement DAO scripts
- [x] Provide unit tests to cover newly added functionality
- [x] Address PR comments

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [ ] ~Integration Tests pass~
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/588
- [x] https://github.com/mojaloop/central-services-shared/pull/181

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @ggrg
- QA/Review: @ggrg
