### ISSUE TITLE
Improve createSettlement to fail attempts for continuous/gross models

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#1209]
## **Goal**:
As a Hub Operator
I want to _make sure no settlement can be initiated for IMMEDIATE/GROSS models_
so that _only DEFERRED/NET models may result in a successful settlement create operation_

**Tasks**:
- [x] Set up various combination for settlement models (e.g. IMMEDIATE/GROSS, DEFERRED/GROSS) [@ggrg]
- [x] Merge Node v2 upgrade from master into settlement-v2 for central-ledger and central-settlement. Also utilise upgraded ml-api-adapter and mojaloop/simulator for central-settlement integration tests run [@ggrg]
- [x] Add unique constraint on settlementModels to prevent similar models (delay-granularity-interchange-ledgerAccountType-currency) [@ggrg]
- [x] Improve createSettlement validation and make sure all of the above specified models fail with appropriate message [@ggrg]
- [x] Fix unit tests

**Acceptance Criteria**:
- [x] Inappropriate requests are rejected
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] A Settlement cannot be explicitly be initiated when he settlement model chosen is a IMMEDIATE/GROSS model

## **Pull Requests**:
- [ ] https://github.com/mojaloop/central-ledger/pull/606
- [ ] https://github.com/mojaloop/central-settlement/pull/249

## **Follow-up**:
- N/A

**Dependencies**:
- #1175 

## **Accountability**:
- Owner: @ggrg
- QA/Review: @ggrg
