### ISSUE TITLE
Setup AWS Infrastructure for High I/O computing 

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#121]
**Goal**:
Setup AWS Infrastructure for High I/O computing 

**Tasks**:
-  ~~Setup i3.xlarge instances on AWS~~ (not required as AWS provides dynamic provisioning of EBS volumes for fast storage)
- ~~Add required storage to each node~~ (not required as AWS provides dynamic provisioning of EBS volumes for fast storage)
- ~~Add required tags to each node~~ (not required as AWS provides dynamic provisioning of EBS volumes for fast storage)
-  ~~Update kubespray script to add the additional i3.xlarge nodes~~ (not required as AWS provides dynamic provisioning of EBS volumes for fast storage)
-  ~~Execute kubespray script to add the additional i3.xlarge nodes~~ (not required as AWS provides dynamic provisioning of EBS volumes for fast storage)
- [x] Define k8s config for AWS StorageClass created for gp2 volumes
- [x] Define k8s config for AWS StorageClass created for io1 volumes
- [x] Define k8s config for AWS StorageClass created for st1 volumes
- [x] Define k8s config for AWS StorageClass created for sc1 volumes

**Acceptance Criteria**:
- ~~Nodes of i3.xlarge created on AWS~~ (not required as AWS provides dynamic provisioning of EBS volumes for fast storage)
- ~~K8s installed and configured on the i3.xlarge Nodes~~ (not required as AWS provides dynamic provisioning of EBS volumes for fast storage)
- ~~i3.xlarge Nodes added to the existing K8s k8s-venice cluster on AWS~~ (not required as AWS provides dynamic provisioning of EBS volumes for fast storage)
- [x] AWS StorageClass created for gp2 volumes
- [x] AWS StorageClass created for io1 volumes
- [x] AWS StorageClass created for st1 volumes
- [x] AWS StorageClass created for sc1 volumes

**Dependencies**:
- [x] AWS Account limit increase [**BLOCKER**]

**Comment by elnyry** [comment]
Looks good, optimized.

**Comment by mdebarros** [comment]
**AWS EC2 Docs:**
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html

**K8s Storage Classes created to represent the EBS Volume Types that allow for dynamic provisioning to pods:**
http://35.178.91.55:8080/r/projects/1a496/kubernetes-dashboard:9090/#!/storageclass?namespace=default
