### ISSUE TITLE
Enhance createSettlementModels admin api endpoint to allow only pre-defined settlement models

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#1210]
## **Goal**:
As a Hub Operator
I want to be able to only define settlement models which could be mapped to real-world models
so that model definitions which don't make sense, fail upon creation attempt (e.g. DEFERRED/GROSS)

**Notes**:
- This story is good to have, but is not a priority for the current PI

**Tasks**:
- [x] Create valid configuration matrix for settlement model properties: settlementGranularity, settlementInterchange, settlementDelay [@ggrg]
- [x] Validate proposed configuration [@ggrg, @MichaelJBRichards]
- [x] Implement validation and fail invalid combinations [@ggrg]
  - [x] Update shared library [@ggrg]
  - [x] Release shared library and implement in central-ledger admin api [@ggrg]
- [x] central-ledger node upgrade (driven by @mojaloop libs upgrades)

**Acceptance Criteria**:
- [x] Only valid settlement models can be added
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-shared/pull/180
- [x] https://github.com/mojaloop/central-services-shared/pull/183
- [x] https://github.com/mojaloop/central-ledger/pull/594

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @ggrg
- QA/Review: @ggrg

**Comment by ggrg** [comment]
The following has been confirmed with @MichaelJBRichards:
![image](https://user-images.githubusercontent.com/20338055/74328159-1b7f9280-4d96-11ea-856c-649b591bc840.png)
