### ISSUE TITLE
Implement autoPositionReset config to settlementModel

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#1211]
## **Goal**:
As a Hub Operator
I want to be able to _define if position should be automatically reset on settlement model level_
so that _upon settling a settlement, positions are updated according to the settlement model configuration_

**Tasks**:
- [x] Add settlementModel.autoPositionReset db column [@ggrg]
- [x] Fix POST /settlementModel to plural /settlementModels [@ggrg]
- [x] Update POST /settlementModels admin api to require and populate the newly added column [@ggrg]
- [x] Fix unit tests for central-ledger [@ggrg]
- [ ] ~Update GET /settlementModels and GET /settlementModels/{name} to report autoPositionReset config~ (moved to #1207)
- [x] Enhance updateSettlementById handler to use the newly added config, so that when autoPositionReset is set to false, settlement transfer is not created [@ggrg]

**Acceptance Criteria**:
- [ ] ~Designs are up-to date~
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [ ] ~Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.~
- [x] Whether positions are to be automatically reset /adjusted upon Settling or not, can be set using config at deployment time by Hub Operators.

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/586
- [x] https://github.com/mojaloop/central-settlement/pull/240

## **Follow-up**:
- Create stories to allow position reset for ledgers other than POSITION

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @ggrg
- QA/Review: @ggrg
