### ISSUE TITLE
Add DELETE/REFRESH cache functionality to the API to allow management of cache

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1214]
## **Goal**:
As a Switch implementer
I want to provide functionality to delete / refresh cache ( catbox-memory) on central-ledger
so that the caching mechanism works as expected (and is refreshed when updates are made to cached information)

**Tasks**:
- [ ] Add DELETE/REFRESH cache functionality to the API to allow management of cache i.e. look at ALS for example
- [ ] Update tests
- [ ] Refactor implementation where a particular 'cache' needs to be deleted / cleared / invalidated, for example when a participant gets updated, etc.

**Acceptance Criteria**:
- [ ] Cache must be able to be reset
- [ ] All tests pass

**Pull Requests**:
- TBD

**Follow-up**:
- N/A

**Dependencies**:
- #602

**Accountability**:
- Owner:  @yosheeck 
- QA/Review: @mdebarros
