### ISSUE TITLE
Caching enhancements in central-ledger [Enhancements to #602]

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1215]
## **Goal**:
As a Switch implementer
I want to enhance caching mechanism used by central-ledger (building on changes done in Sprint8.8)
so that performance improvements can be achieved and unnecessary DB / API reads are avoided.

**Tasks**:
- [x] Add and implement configs: CACHE_ENABLED and EXPIRES_IN_MS
- [ ] ~The current enums caching should be refactored to register as a cache.js independent client, instead of being hard-embedded into cache.js structure (this is the remains of PoC)~ Moved to new story: https://github.com/mojaloop/project/issues/1366
- [x] Cache must be initialised when the server starts up and populated with the following data:
  - [x] Participant limits src/models/participant/participantLimit.js
  - [x] Store results from src/models/participant/facade.js/getByNameAndCurrency() as its used in a few places or create it from the calls in participantCached and participantCurrencyCached
  - [ ] ~Participant endpoints - participantEndpoint table~ Moved to new story: https://github.com/mojaloop/project/issues/1367
- [x] Update tests
- [x] Refactor implementation where a particular 'cache' needs to be deleted / cleared / invalidated, for example when a participant gets updated, etc.

**Acceptance Criteria**:
- [x] Caching enhancements are done by caching items such as limits, endpoint tables, etc
- [x] Cache must be able to be reset
- [x] All tests pass

**Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/587 - CACHE_ENABLED and EXPIRES_IN_MS
- [x] https://github.com/mojaloop/central-ledger/pull/700 - Caching Enhancements To Participant Limit

**Follow-up**:
- N/A

**Dependencies**:
- #602

**Accountability**:
- Owner: @yosheeck 
- QA/Review: @mdebarros
