### ISSUE TITLE
Test Settlements API with the testing tool-kit for initial observations

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1216]
## **Goal**:
As a user _of the OSS Testing tool-kit_
I want to _use the Settlements v1.2 / v2.0 API and record initial observations_
so that _I can then address any issues before using it to test the Settlements features_

**Tasks**:
- [x] Make version negotiation configurable from config file
- [x] Add the response rules to generate mock synchronous responses in the backend service
- [x] Implement front-end for creating response rules
- [x] Make changes to support multiple types of openapi files simultaneously
- [x] Use the testing toolkit with the Settlement API
- [x] Validate Schema validation
- [x] Write a sample test based on Settlements happy path tests
- [x] Write sample setup files / scripts
- [x] Record observations / gaps identified and feed into the OSS testing tool-kit backlog

**Acceptance Criteria**:
- [x] An initial attempt at using he Settlements API (v1.2 or v2.0) with the Testing tool-kit is done and observations are recorded
- [x] Sample setup and happy path test files are created to test Settlements features
- [x] Observations are recorded, bugs logged as necessary
- [x] Feature requests based on observations are made

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @elnyry @MichaelJBRichards
