### ISSUE TITLE
Implement Settlement Model Handler to central-ledger

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#1217]
## **Goal**:
As a Hub Operator
I want to _settlement state to be recorded on the lowest level such as transfer ledger_
so that _it is possible to report settlement state for each transfer participant entry_

**Tasks**:
- [x] Add transferParticipantSettlementState table to use settlement window states enum
- [x] Add current state pointer such as transferParticipant.currentStateChangeId
- [x] Add SettlementModelHandler to asynchronously assign window to committed transfers and perform settlement model related actions to transferParticipantSettlementState

**Acceptance Criteria**:
- [x] DB Migrations are up-to date
- [x] Settlement window is assigned to all committed transfers asynchronously
- [ ] Transfer ledgers, which are settled gross are marked as SETTLED
- [x] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- [ ] TBD

**Dependencies**:
- #1218

## **Accountability**:
- Owner: @ggrg
- QA/Review: @ggrg
