### ISSUE TITLE
Enhance documentation to specify processing of Settlement Model Handler

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#1218]
## **Goal**:
As an _OSS codebase contributor_
I want to _update documentation in relation to the proposed Settlement Model Handler_
so that _it could be reviewed by the DA and later used as reference during implementation_

**Tasks**:
- [x] Update DB schema diagram [@ggrg]
- [x] Collaborate on the update of the OSS Settlements FSD PR [@ggrg]
- [x] Add new sequence digram to describe processing for SettlementModelHandler [@ggrg]
- [x] Update existing diagrams
  - [x] Overall transfer fulfil [@ggrg]
  - [x] Fulfil Handler [@ggrg]
  - [x] Settlement Model Handler [@ggrg]
  - [x] closeSettlementWindow [@ggrg]
  - [x] createSettlement [@ggrg]
  - [x] updateSettlementById [@ggrg]
- [ ] ~Propose changes to the DA~
- [ ] ~Update designs with DA requested changes, if any~

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] All CI/CD checks pass
- [ ] ~Designs are presented and approved by the DA~
- [x] Designs are presented to the team

## **Pull Requests**:
- [ ] ~https://github.com/mojaloop/central-ledger/pull/607~ <-- pushed as mojaloop [feature branch](https://github.com/mojaloop/central-ledger/tree/feature/1218SettlementModelHandler)
- [x] https://github.com/mojaloop/documentation/pull/176

## **Follow-up**:
- #1217

**Dependencies**:
- [x] [PR #173](https://github.com/mojaloop/documentation/pull/173) by @mjbrichards 

## **Accountability**:
- Owner: @ggrg
- QA/Review: @ggrg, @MichaelJBRichards
