### ISSUE TITLE
Enable GROSS settlement models handling during settlement window close

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#1219]
## **Goal**:
As a Hub Operator
I want _GROSS settlement models to be handled during settlement window close_
so that _generated window contents and aggregations are only populated for NET settlement models

**Tasks**:
- [x] Only generate settlementWindowContent entries for NET settlement models
- [x] Only generate settlementContentAggregation entries for NET settlement models 
- [x] Change transferParticipantSettlementState entries to CLOSED for non-GROSS models

**Acceptance Criteria**:
- [x] Gross entries are not aggregated upon window closure
- [ ] Designs are up-to date
- [x] Unit Tests pass
- [ ] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- #1217

## **Accountability**:
- Owner: @ggrg
- QA/Review: @ggrg

**Comment by elnyry-sam-k** [comment]
@ndonnan - can we close this out?
