### ISSUE TITLE
Install & Configure Kafka

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#122]
**Goal**:
Install & Configure Kafka

**Tasks**:
- [x] Setup Helm charts for Scalable Zookeeper Cluster on Kubernetes and configure persistent storage
- [x] Setup Helm charts for Dynamic Scalable Kafka Cluster on Kubernetes and configure persistent storage
- [x] Test Kafka cluster

**Acceptance Criteria**:
- [x] Dynamic Scalable Zookeeper Cluster on Kubernetes with persistent storage
- [x] Dynamic Scalable Kafka Cluster on Kubernetes with persistent storage

**Dependencies**:
- [ ]

**Comment by mdebarros** [comment]
Deployment made to kubernetes: http://35.178.91.55:8080/r/projects/1a496/kubernetes-dashboard:9090/#!/overview?namespace=mojaloop-kafka-poc

**Comment by elnyry** [comment]
Looks good, was in discussion with Miguel when this was closed.
