### ISSUE TITLE
Update transferParticipantSettlementState for NET models during settlement processing

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#1220]
## **Goal**:
As a Hub Operator
I want _NET settlement models to be enhanced during settlement processing_
so that _individual transfer ledgers are updated accordingly_

**Tasks**:
- [ ] Change transferParticipantSettlementState entries to PENDING_SETTLEMENT when settlement is created
- [ ] Change transferParticipantSettlementState entries to SETTLED when respective content aggregation is SETTLED

**Acceptance Criteria**:
- [ ] Transfer participant settlement state is updated for NET settlement models based on the corresponding Settlement state
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- #1217

## **Accountability**:
- Owner: @ggrg
- QA/Review: @ggrg

**Comment by elnyry-sam-k** [comment]
addressed in other CGS stories in #1098
