### ISSUE TITLE
Address remaining Gross Settlement related follow-ups 

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#1221]
## **Goal**:
As a Hub Operator
I want _all settlement v1 endpoints to be updated_
so that _settlement v2 is fully functional_

**Tasks**:
- [ ] Add tasks for remaining follow-ups from story #1105

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @ggrg
- QA/Review: @ggrg

**Comment by elnyry-sam-k** [comment]
addressed in other CGS stories in #1098
