### ISSUE TITLE
Application security summary

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1222]
## **Goal**:
As a "Hub operator", I want to "see a summary of the security tools (open source and other) evaluated and used in Mojaloop" so I can "understand the suite of tools used within Mojaloop, and where they fit into the picture of Mojaloop code security"

**Tasks**:
- [x] Publish a security tool list summary
- [x] List of application security goals, and which tools map to which goals

**Acceptance Criteria**:
- [ ] Application security summary published in a central place? @elnyry do you have any suggestions? Maybe business documentation repo? Maybe in discussion docs?
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@godfreykutumela I'm going to un-assign myself from this, since I have plenty of other stuff for this PI, and this isn't exactly my strength.

I'm happy to provide input about the tools I'm familiar with for my component.

**Comment by godfreykutumela** [comment]
I will take ownership of this one @lewisdaly

**Comment by godfreykutumela** [comment]
Draft Document and finalize by tomorrow - @lewisdaly @rasputtintin 
[Mojaloop Application Security Summary - 25 January 2020 .pptx](https://github.com/mojaloop/project/files/4250512/Mojaloop.Application.Security.Summary.-.25.January.2020.pptx)

**Comment by godfreykutumela** [comment]
Final Draft from my side for your review @lewisdaly @elnyry @rasputtintin 
@lewisdaly please udpdate the open source license policy, SCA tools in used and Open Source vulnerabillity scanning tools in used.
@rasputtintin maybe spend time to expand on what each tool does - little bit swamped this week under the weather as well but I would like to meet all the targets for the sprint
[Mojaloop Application Security Summary - 27 January 2020 .pptx](https://github.com/mojaloop/project/files/4260536/Mojaloop.Application.Security.Summary.-.27.January.2020.pptx)

**Comment by godfreykutumela** [comment]
[Mojaloop Application Security Summary - 04 March 2020 .pptx](https://github.com/mojaloop/project/files/4286865/Mojaloop.Application.Security.Summary.-.04.March.2020.pptx)
Final Version for approval this afternoon

**Comment by godfreykutumela** [comment]
For final approval by all
