### ISSUE TITLE
Define a vulnerability reporting procedure

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1224]
## **Goal**:
As a "Switch Operator/Evaluating DFSP", I want to "know the vulnerability reporting procedure", so I can "be assured potential security issues are addressed safely and privatly"

**Tasks**:
- [x] Investigate the industry standard for vulnerability disclosure - I am here this week and have uploaded an ISO standard for reporting vulnerabilities and busy reviewing it together with the Apache info
- [x] Decide on the email domain\addresses to use for reporting - Please advise Sam and Lewis
- [ ] Design and deploy security measures to protect the intergrity and confidentiality of the email comms
- [x] Document and distribute a draft procedure for comments from the Core Team and Community contributors _@elnyry please advise about where this should live_
- [ ] Finalize and publish the new procedure

@elnyry @lewisdaly Please let me know if there is any other task missing to complete this story

**Acceptance Criteria**:
- [ ] Code Style & Coverage meets standards
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
Adding information that Ed Cable provided:

_"Here is the policy and process for Apache projects_:
_Process: https://www.apache.org/security/committers.html_
_General Info: https://www.apache.org/security/"_

**Comment by lewisdaly** [comment]
Ideally we could have a `security@mojaloop.io` email address which forwards to a list of people and/or the private security channel on slack.

Not sure what we should do in the meantime however.

**Comment by godfreykutumela** [comment]
Draft Procedure for everyone's review - I may add or two more sections to this still researching a bit of what can be relevant to make this comprehensive.
[Draft Mojaloop Vulnerability Reporting Procedure - 26 Feb 2020.docx](https://github.com/mojaloop/project/files/4255365/Draft.Mojaloop.Vulnerability.Reporting.Procedure.-.26.Feb.2020.docx)

**Comment by godfreykutumela** [comment]
[Draft.Mojaloop.Vulnerability.Reporting.Procedure.-.04.Mar.2020.docx](https://github.com/mojaloop/project/files/4286876/Draft.Mojaloop.Vulnerability.Reporting.Procedure.-.04.Mar.2020.docx)

For final approval by all
