### ISSUE TITLE
Define Mojaloop GDPR scope 

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1225]
## **Goal**:
As a "Hub Operator", I want to "understand how the OSS community can help me fulfill my GDPR requirements", so I can "plan accordingly in my organization"

**Tasks**:
- [ ] Investigate how we can handle GDPR Requirements as a part of Mojaloop OSS
- [ ] Produce a list GDPR controls and an implementation plan

**Acceptance Criteria**:
- [ ] Code Style & Coverage meets standards
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by rasputtintin** [comment]
I have prepared a self assessment framework we can review and apply.

**Comment by godfreykutumela** [comment]
I think we need to complete this story first and open 2 more stories for establishing the framework and also doing the actual assessment

**Comment by rasputtintin** [comment]
Working document: 

[https://docs.google.com/spreadsheets/d/1yAqpW6v8By0rRGP80QgO8r1OwRYlSOSPmo4NqYBk27k/edit#gid=0](url)

**Comment by godfreykutumela** [comment]
@rasputtintin  we don't have access to this doc on google docs so please email it to me then I will upload it on githut

**Comment by godfreykutumela** [comment]
@rasputtintin Can we have a 30min chat today or wednesday morning to finalize this

[GDPR Scope - OSS 09 March 2020.xlsx](https://github.com/mojaloop/project/files/4305900/GDPR.Scope.-.OSS.09.March.2020.xlsx)

**Comment by godfreykutumela** [comment]
Hello @rasputtintin I have sent you a meeting invite for today at 10h30am your time so please let me know if you're free for quick alignment on this one.

**Comment by godfreykutumela** [comment]
Victor and I had deeper look on how best Mojaloop can contribute to the GDPR compliance initiatives of implementors and their DSFP and the scope we identified is pretty much limited to the data security requirement for encryping data at rest and in motion (within the hub only and does not include external connections to the DFSPs. Based on these findings, we will engage with the core architect team to explore how best we can implement encryption within the hub to fullfil this requirement. 

Much of other GDPR requirements must be fullfilled by the hub operator as the data processor and the DFSP's as the controller - depending with each implementation use case the processor/controller roles may vary.

@elnyry, @rasputtintin and @kjw000 here we may need to source advise of a GDPR compliance expect just to ensure we got this right.

**Comment by godfreykutumela** [comment]
[GDPR.Scope.-.OSS.12.March.2020.xlsx](https://github.com/mojaloop/project/files/4328352/GDPR.Scope.-.OSS.12.March.2020.xlsx)

**Comment by godfreykutumela** [comment]
Hi All,

Please find attached GDPR Scope Defintion Document for your review and comment.
[Mojaloop GDPR Scope Definition Document - 19 March 2019.docx](https://github.com/mojaloop/project/files/4358454/Mojaloop.GDPR.Scope.Definition.Document.-.19.March.2019.docx)

**Comment by rasputtintin** [comment]
@godfreykutumela am ok with the scope document. Can we break it into taskable chunks?

**Comment by godfreykutumela** [comment]
Agreed @rasputtintin and thanks for the input. I have have closed this if ok with you all @lewisdaly and @elnyry

**Comment by lewisdaly** [comment]
Thanks @rasputtintin and @godfreykutumela . I guess our next steps are to figure out follow up items related to this, and then see what else we can (or want) to achieve in this PI

**Comment by godfreykutumela** [comment]
I agree @lewisdaly and for PI, I suggest we do a gap analysis of what is covered in the current implementation and what is still outstanding(the gaps). Addressing the gaps will be for the next PI. @rasputtintin and @elnyry @pedrosousabarreto

**Comment by kjw000** [comment]
@godfreykutumela I know this is closed but can we turn this doc into a md file and post here: https://github.com/mojaloop/documentation/edit/master/discussions/readme.md

**Comment by elnyry** [comment]
@kjw000 - Hi Kim, let me take that one.

**Comment by godfreykutumela** [comment]
@elnyry please find updated scope document
[Mojaloop.GDPR.Scope.Definition.Document.-.0404.2019 v1.0.docx](https://github.com/mojaloop/project/files/4496909/Mojaloop.GDPR.Scope.Definition.Document.-.0404.2019.v1.0.docx)

**Comment by elnyry** [comment]
Thanks @godfreykutumela

**Comment by elnyry** [comment]
@Godfrey Kutumela, here is a link you can use for the ‘Vulnerability reporting procedure’ and ‘Mojaloop Application Security Summary’ docs: https://mojaloop.io/documentation/code_quality_security/readme.html

The actual docs (as PDFs) are here: https://github.com/mojaloop/documentation-artifacts/tree/master/presentations/discussion-docs
