### ISSUE TITLE
Solicit devsecops input from implementors

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1226]
## **Goal**:
As an "OSS Community" we want to know the real security and compliance challenges "hub operators/Switch Operators" are experiencing on daily basis and see how best we can help address them at Mojaloop level. The main purpose of this is to learn from real time experience of implementation and operating the mojaloop switch.

**Tasks**:
1. [ ] Find a list of active mojaloop implementors - I only know of TIPPS and Mowali(have contacted the CISO already and he is onboard to input into this)
2. [ ] Establish contact with each requesting their participation
3. [ ] Solicit their expectations\requirements of security & compliance
3. [ ] Document and communicate feedback to the team
5. [ ] Finally decide on what we can take on in the next PI and provide feedback to the requesting entity

@lewisdaly please find above task breakdown

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
