### ISSUE TITLE
Update "library" projects to use node 12.16.0 LTS

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1228]
## **Goal**:
As an adopter of Mojaloop
I want to _have all the library projects used in mojaloop to be updated to use node 12.16.0_
so that _we are on the latest recommended (stable) version of node_

**Tasks**:
- See example PR here: https://github.com/mojaloop/ml-api-adapter/pull/339
- [x] Apply to all 'library' projects (this means updating the docker version in `.circleci/config.yml` and `.nvmrc`)
  - [x] sdk-standard-components [@oderayi]
  - [x] event-stream-processor [@oderayi ]
  - [x] central-services-auth  [@oderayi]
    ~[ ] Update to new error handling framework [@oderayi]~
  - [x] central-services-error-handling [@rmothilal] 
  - [x] central-services-shared [@oderayi]
  - [x] central-services-database [@oderayi ]
  - [x] central-services-health [@oderayi]
  - [x] central-services-stream [@rmothilal] 
    - [x] https://github.com/mojaloop/central-services-error-handling/pull/112
    - [x] https://github.com/mojaloop/central-services-logger/pull/12
  - [x] central-services-metrics [@rmothilal]
  - [x] central-object-store [@rmothilal]
    - [x] https://github.com/mojaloop/central-services-logger/pull/12
  - [x] central-services-logger [@rmothilal]
  - [x] event-sdk [@oderayi]

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] All the library projects used in mojaloop core services are upgraded to node 12.16.0 LTS

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-object-store/pull/7
- [x] https://github.com/mojaloop/central-services-metrics/pull/81
- [x] https://github.com/mojaloop/central-services-logger/pull/12
- [x] https://github.com/mojaloop/central-services-error-handling/pull/112
- [x] https://github.com/mojaloop/sdk-standard-components/pull/45
- [x] https://github.com/mojaloop/central-services-database/pull/100
- [x] https://github.com/mojaloop/central-services-shared/pull/179
- [x] https://github.com/mojaloop/central-services-stream/pull/75
- [x] https://github.com/mojaloop/central-services-health/pull/137
- [x] https://github.com/mojaloop/event-stream-processor/pull/21
- [x] https://github.com/mojaloop/central-services-auth/pull/83
- [x] https://github.com/mojaloop/event-sdk/pull/27

## **Follow-up**:
- #1175 

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
