### ISSUE TITLE
Provide a base-line for existing Prepare Process

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#123]
**Goal**:
Provide a base-line for existing Prepare Process

**Tasks**:
- [x] Create required accounts in central ledger
- [x] Point the stubs to central ledger in K8s perf env and make sure that payment executes end-end
- [x] Run jmeter tests against the stubs and capture tps.

**Acceptance Criteria**:
- [x] Provide a performance baseline for the existing pre-POC Payment Process (Performance TPS baseline)

**Dependencies**:
- None currently

**Comment by elnyry** [comment]
As per Murthy's inputs the performance (for prepare part) is averaging around 50TPS.
