### ISSUE TITLE
Unit tests for testing toolkit and refactoring needed

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1230]
## **Goal**:
As a maintainer _of the OSS Testing tool-kit_
I want to _ensure there are unit tests for the code base and the code refactored to support it_
so that _future updates are validated against them and test coverage is provided_

**Tasks**:
- [x] Add an initial set of unit tests to cover testing toolkit functionality
- [x] Perform refactoring of code as necessary
- [x] Document observations and next steps
- [x] Attempt setting up CI so that the unit tests can be run on PRs, releases, etc.

**Acceptance Criteria**:
- [x] An initial set of unit tests are created for the testing toolkit and code refactored accordingly
- [x] Next steps for unit testing are identified and documented
- [x] CircleCI is setup to run unit tests on PRs, releases

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @elnyry @MichaelJBRichards

**Comment by vijayg10** [comment]
- Achieved 23% unit test coverage as the first step.
- Need to implement unit tests for the main functions like openapi-backend functiions, hapi api functions, rule & mock generation functions and for outbound initiation functions...etc
- The test coverage for the above remaining functions will be added as a task to the story #1235 

Below is the code coverage output from Jest.

![Screenshot 2020-02-24 at 4 53 01 PM](https://user-images.githubusercontent.com/33152110/75150326-23421e00-572a-11ea-968c-9d8c1d0e43e5.png)
