### ISSUE TITLE
Tests for transaction-requests-service in the Golden path

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1231]
## **Goal**:
As an adopter of Mojaloop
I want to _have a postman test collection that includes for the transactions-requests-service_
so that _I can use it to validate my various deployments that need this service_

**Tasks**:
- [x] Support on the legacy simulator for QA ( `/transactionRequests` ) [@oderayi]
- [x] Postman tests on the Golden Path collection - https://github.com/mojaloop/project/issues/1238 - bug fixed
- [x] Sample runs, report issues with Simulator or the service
- [x] Error framework tests for transaction request - POST
- [x] Write postman test for authorizations service - Basic 202, 200 check
- [x] PR and reviews

**Acceptance Criteria**:
- [x] Tests for transaction-requests-service are added in the Golden path test collection on postman repo that provide coverage.

## **Pull Requests**:
- [x] https://github.com/mojaloop/simulator/pull/149
- [x] https://github.com/mojaloop/postman/pull/94
- [x] https://github.com/mojaloop/postman/pull/95

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @amarmodus, @oderayi 
- QA/Review: @rmothilal , @elnyry

**Comment by amarmodus** [comment]
<img width="1278" alt="Screenshot 2020-03-12 12 34 52" src="https://user-images.githubusercontent.com/53434415/76617826-02960880-651f-11ea-9e8c-0552a1db2368.png">
<img width="1278" alt="Screenshot 2020-03-12 12 41 09" src="https://user-images.githubusercontent.com/53434415/76617844-0c1f7080-651f-11ea-980e-046836c4afbd.png">
