### ISSUE TITLE
Extend toolkit to handle multiple API files

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1232]
## **Goal**:
As a user _of the OSS Testing tool-kit_
I want to _use multiple API files simultaneously with the toolkit_
so that _I can simulate either a Switch entirely or more than one major functionality at the same time (such as clearing, settlement, etc)_

**Tasks**:
- [x] Add capability to load multiple APIs and choose to support them simulataneously
- [x] Test changes
- [x] Automated tests (unit)
- [x] Validate with ML FSPIOP and Settlement APIs

**Acceptance Criteria**:
- [x] More than one API (can be up to 3 at the moment) can be supported by the testing toolkit so that clearing and settling functions can be validated

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @elnyry @MichaelJBRichards
