### ISSUE TITLE
'Hostname' and related details made configurable on the testing toollkit

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1233]
## **Goal**:
As a User of the _testing toolkit_
I want to _be able to provide 'hostname', 'port', 'basepath' details for callbacks or outbound mode_
so that _I can point the callbacks to where the listening services are running_

**Tasks**:
- [x] Refactor the logic around config (system config and user config) to make the config editable in runtime
- [x] Implement backend api for editing user config file
- [x] Provide UI options to give hostname, port, basepath details in a separate config section
- [x] Decide if usage of environment variables (integrated with UI) is needed here
- [x] Validation and testing
- [x] Record a demo video regarding settlements, multiple api support and CICD implementation in self-testing toolkit

**Acceptance Criteria**:
- [x] Callback endpoints and endpoints for outbound mode can be set / configured using UI

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
