### ISSUE TITLE
Configurable options for versions of APIs

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1234]
## **Goal**:
As a User of the _testing toolkit_ (an FSP)
I want to _be able to select a particular version of an API_
so that _I can choose the version to use while initiating a request_

**Tasks**:
- [x] Provide UI options to choose the version of an API
- [x] Do research on providing persistence and document the observations

**Acceptance Criteria**:
- [x] Version of a particular API can be chosen to initiate requests
- [x] Documented the observations regarding persistence and object store

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-self-testing-toolkit-ui/pull/5
- [x] https://github.com/mojaloop/ml-self-testing-toolkit/pull/23

## **Follow-up**:
- A new story is created for the persistence functionality with observations. https://github.com/mojaloop/project/issues/1248

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
A new story is created for the persistence functionality with observations. 
 https://github.com/mojaloop/project/issues/1248
