### ISSUE TITLE
Add more unit tests and setup CI/CD for the testing toolkit and UI

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1235]
## **Goal**:
As a Community Contributor of the _testing toolkit_ 
I want to _have a set of tests run on Pull Requests submitted_
so that _I know the changes are good and do not break existing functionality_

As a _maintainer of the ML OSS codebase)
I want to _have a set of tests run on Pull Requests submitted and releases_
so that _I know the changes are good and do not break existing functionality_

**Tasks**:
- [x] Cover unit tests for more than 50% of the functions for the backend service
- [x] Cover unit tests for UI (implemented 5 unit tests for reference)
- [x] Add functionality to store requests and callbacks for postman assertion tests
- [x] Design how to use / improve CI for the testing toolkit and analysis including backend and frontend
- [x] Enable stages that are relevant at this stage
- [x] Document stages needed to get into a Release stage (from experimental to snapshot and then release)
- [x] Enable CI/CD for backend and frontend in CircleCI
- [x] Validate and ensure runs on CircleCI work as configured

**Acceptance Criteria**:
- [x] CI/CD for the testing toolkit is enabled on CircleCI and applicable steps run on Pull Requests and when releases are made
- [x] Steps needed to get testing toolkit to release 'state' are documented

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/6
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/25

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
For **snapshot** we need to have 50% tests, deployment instructions and documentation about features and functionality.
For **release** stage we need >90% test coverage, integration test along with docs
