### ISSUE TITLE
Performance: Combine prepare and position handlers

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1236]
## **Goal**:
As a Hub Operator
I want to _use versions of Mojaloop Switch services with improved performance by combining prepare and position handlers_
so that _I can support higher performance needs of a Scheme_

**Tasks**:
- [ ] Refactor central-ledger to combine prepare and position handlers
- [ ] PR and reviews
- [ ] Design discussions , issues if needed
- [ ] Changes to documentation (including sequence diagrams)
- [ ] Helm charts changes
- [ ] Releases
- [ ] QA and validation

**Acceptance Criteria**:
- [ ] Designs are updated to reflect the changes and refactoring done
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] QA and validation done to ensure that there are no regressions

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by millerabel** [comment]
Hi Sam,

I’d like to discuss this work before we proceed to refactor the Kafka handlers. We will augment the performance work team and take a methodical approach that combines Kafka and Node expertise together with the core OSS team.

— Miller 

On Feb 15, 2020, at 9:20 PM, Sam <notifications@github.com> wrote:

Goal:

As a Hub Operator
I want to use versions of Mojaloop Switch services with improved performance by combining prepare and position handlers
so that I can support higher performance needs of a Scheme

Tasks:

 Refactor central-ledger to combine prepare and position handlers
 PR and reviews
 Design discussions , issues if needed
 Changes to documentation (including sequence diagrams)
 Helm charts changes
 Releases
 QA and validation
Acceptance Criteria:

 Designs are updated to reflect the changes and refactoring done
 Unit Tests pass
 Integration Tests pass
 Code Style & Coverage meets standards
 Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
 QA and validation done to ensure that there are no regressions
Pull Requests:

 TBD
Follow-up:

N/A
Dependencies:

N/A
Accountability:

Owner: TBC
QA/Review: TBC
