### ISSUE TITLE
Performance Characterisation - Central Services Stream library - II part

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1237]
## **Goal**:
As Hub TechOps
I want to understand the performance characteristics of the stream library
so that I can make informed decisions of configuration needed and capabilities of the library used

**Tasks**:
- [x] Benchmark Central Services Stream library

- [x] Instrumentation
    - [x] Enhance log-processing script to push metrics into Prometheous
        - [x] stats for end-to-end flow (including prepare & position)
        - [x] stats to show time between send (producer) and receive (consumer)
    - [ ] ~Observe the Perf4js metrics into Prometheous~ results showed it not 

- [x] Dashboards
    - [ ] ~Log-processed metric output~
    - [x] Add visualizations for:
        - [x] moja_css -> processing time like ML; diagram how many messages are flowing through; size of messages going through; rate
        - [ ] ~rdkafka -> count; rate; lag of both producer and consumer; queue buffer;~ 

--
- [x] Test Cases
    - [x] Characterise Producer (stand-alone) - benchmark config/options (specifically for timeouts, etc)
    - [x] Characterise Consumer (stand-alone) - benchmark config/options (specifically for timeouts, etc)
    - [ ] ~Characterise Producer + Consumer (process log files)~

**Acceptance Criteria**:
- [x] Results are convincing the problem is pinpointed or the streaming library is not the bottleneck

## **Pull Requests / branches **:
- [ ] https://github.com/mojaloop/central-services-stream/tree/release/9.1.0-performance

## **Notes**:
- Striked out tasks weren't completed because the results were enough to exclude the streaming library from the performance bottleneck

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @mdebarros 

## ** Refernce**: 
- https://mdebarros.github.io/kafkapoc-results/
