### ISSUE TITLE
Helm Release v9.2.0: Updates to helm, Supporting QA, Fixes, Releases

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1239]
## **Goal**:
As an ML OSS Code base maintainer
I want to _validate and make a Helm release in PI9 (Sprint 9.2) that is successfully validated by the Golden path tests_
so that _Community members can take and use a version of Mojaloop Switch services bundle that is tested and contains latest features and enhancements (added in and PI9(Sprints 8.8, 9.1, 9.2) so far)_ 

This specific story is for making necessary changes for supporting Deployment, QA, Fixes, Integration and performing end-to-end testing for all the changes made since Helm v9.2.0

**Tasks**:
- [x] Make releases on all core services to have latest images / versions [@oderayi]
- [x] Identify changes needed for helm (config / default.json) [@oderayi]
- [x] Initial PR with changes for v9.2.0 [@oderayi]
  - [x] Initial PR review
  - [x] Deploy, validate, fix issues, redeploy [@oderayi , @elnyry , @rmothilal ]
  - [x] With stable deployment test Golden path [@amarmodus ]
- [x] Identify issues with QA Scripts if any - fix them and retest [@amarmodus @oderayi ]
- [x] Identify Bugs, log them [@amarmodus @rmothilal ]
- [x] Validate finance portal [@amarmodus ]
- [x] Fix bugs logged if critical [@rmothilal @vijayg10 @oderayi ]
- [x] Deploy, validate on AWS dev2 [@rmothilal @amarmodus ]
- [x] Helm v9.2.0 released [@rmothilal @elnyry ]
- [x] Deployment of released Helm v9.2.0 on **Dev2** [@elnyry ]
- [x] Validation using Golden path regression tests etc on Dev2
- [x] Deployment of released Helm v9.2.0 on **Dev1**
- [x] Validation using Golden path regression tests etc on Dev1

**Acceptance Criteria**:
- [x] Helm v9.2.0 is released after testing RC version on dev2
- [x] Helm v9.2.0 is deployed on AWS Dev2 without issues
- [ ] QA (Golden path) on deployments done on AWS dev2 environment is done
- [x] Bugs are logged based on observations, failures
- [x] Bugs logged are fixed to make subsequent releases in individual services (or Helm)
- [x] All the changes needed for supporting v9.2.0 of Helm (List out major changes in release notes once release is ready)
- [x] Helm v9.2.0 is deployed on AWS Dev1 without issues
- [x] QA (Golden path) on deployments done on AWS dev1 environment is done

**Pull Requests**:
- [x] https://github.com/mojaloop/bulk-api-adapter/pull/22
- [x] https://github.com/mojaloop/central-event-processor/pull/151
- [x] https://github.com/mojaloop/central-ledger/pull/612
- [x] https://github.com/mojaloop/email-notifier/pull/124
- [x] https://github.com/mojaloop/event-stream-processor/pull/23
- [x] https://github.com/mojaloop/operator-settlement/pull/10
- [x] https://github.com/mojaloop/settlement-management/pull/8
- [x] https://github.com/mojaloop/helm/pull/274

**Follow-up**:
- N/A

**Dependencies**:
- [x] #1175 

**Accountability**:
- Owner: @oderayi 
- QA/Review: @mdebarros @elnyry

**Comment by elnyry** [comment]
Currently blocked. Needs a new event framework related release. Blocking this until the release is available next week.

```
2020-02-28T15:51:23.842Z - error: uncaughtException: config_1.default.EVENT_LOGGER_LOG_FILTER.forEach is not a function
TypeError: config_1.default.EVENT_LOGGER_LOG_FILTER.forEach is not a function
    at /opt/central-ledger/node_modules/@mojaloop/central-services-shared/node_modules/@mojaloop/event-sdk/dist/model/EventMessage.js:339:46
    at Object.<anonymous> (/opt/central-ledger/node_modules/@mojaloop/central-services-shared/node_modules/@mojaloop/event-sdk/dist/model/EventMessage.js:359:3)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/opt/central-ledger/node_modules/@mojaloop/central-services-shared/node_modules/@mojaloop/event-sdk/dist/Tracer.js:6:24)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/opt/central-ledger/node_modules/@mojaloop/central-services-shared/node_modules/@mojaloop/event-sdk/dist/index.js:28:18)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/opt/central-ledger/node_modules/@mojaloop/central-services-shared/src/util/kafka/index.js:40:18)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:9
```

**Comment by elnyry** [comment]
Above issue and a few others are now fixed as well. Helm v9.2.0 is released : https://github.com/mojaloop/helm/releases/v9.2.0 !
