### ISSUE TITLE
Assessing the scope to add features in Settlements API with the testing tool-kit

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1240]
## **Goal**:
As a user _of the OSS Testing tool-kit_
I want to use the testing toolkit to test all the scenarios involving Settlements in my Hub / FSP implementation.

**Tasks**:
- [ ] Understand the Settlements API end to end
- [ ] Observe the tests in golden path collection regarding settlements
- [ ] Make a list of things to implement to make testing toolkit to be able to test the settlements api implementations
- [ ] Check the feasibility to implement the required features
- [ ] Record observations / gaps identified and feed into the OSS testing tool-kit backlog

**Acceptance Criteria**:
- [ ] List of things to implement are noted
- [ ] Decision made on which functionality to implement based on the time factor
- [ ] Observations / decisions are recorded

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @elnyry @MichaelJBRichards

**Comment by elnyry-sam-k** [comment]
Scripting capabilities and other features available now should take care of this
