### ISSUE TITLE
Get settlements by params to include currency

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1241]
## **Goal**:
As a Hub Operator
I want to _be able to use currency as param for querying Settlements_
so that _I can get currency-specific Settlements_

**Tasks**:
- [x] Fix current 'query Settlements by params' to work as intended
- [x] Get settlements by params to include currency
- [x] Add window content to the response
- [x] Modify Swagger def
- [x] Modify DAO script 
- [x] Modify handler script
- [x] Add unit tests to cover delivered functionality
- [ ] Address PR comments

**Acceptance Criteria**:
- [x] Designs are up-to-date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment configs.
- [x] Get settlements by params functionality includes currency as one of the params

## **Pull Requests**:
- [ ] https://github.com/mojaloop/central-settlement/pull/268

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @ndonnan @ggrg @MichaelJBRichards
