### ISSUE TITLE
Error Framework: Adopt & Integrate Mojaloop SDK Error Handling to transaction-requests-service

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1242]
## **Goal**:
As a `Hub Operator`,
I want to `implement a standard Error Handling framework and apply it to the transaction-requests-service`
so that `errors are consistent throughout the Mojaloop stack for both the Switch and the FSPs`.

**Tasks**:
- [x] Integrate the [Error Handler](https://github.com/modusbox/mojaloop-sdk-standard-components/blob/master/src/lib/errors/index.js) from the standard components lib into **transaction-requests-service**
- [x] Refactor tests (unit and integration) that use previous Error object in favor of FSPIOPError
  - [x] Validate that hard coded Errors are being created and replaced with FSPIOErrors
  - [x] Validate that errors are correct per API Specification, eg:
https://github.com/mojaloop/central-ledger/blob/8a34ae14129b8a455703af56fa793cd23fcd1ea5/test/integration/handlers/handlers.test.js#L169
- [x] Update Unit Tests
- [x] Tested with Postman tests [@oderayi]

**Acceptance Criteria**:
- [x] Unit Tests pass
- [x] Code Style meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] Mojaloop SDK Standard Components for Error handling have been integrated into the transaction-requests-service
- [x] transaction-requests-service component produces ML API compliant Specification errors

## **Pull Requests**:
- [x] https://github.com/mojaloop/transaction-requests-service/pull/22
- [x] https://github.com/mojaloop/simulator/pull/154
- [x] https://github.com/mojaloop/transaction-requests-service/pull/23
- [x] https://github.com/mojaloop/postman/pull/88
- [x] https://github.com/mojaloop/postman/pull/91
- [x] https://github.com/mojaloop/simulator/pull/156

## **Follow-up**:
- [ ]

**Dependencies**:

## **Accountability**:
- Owner: @oderayi  
- QA/Review: @rmothilal @mdebarros @vgenev
