### ISSUE TITLE
Add data persistency feature by implementing an object store

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1248]
## **Goal**:
As a User of the _testing toolkit_ (an FSP)
I want to _be able to choose whether a particular request needs to be stored temporarily_
so that _I can use these capabilities to query for or use this information in a later request_

**Tasks**:
- [ ] Design the Object Store functionality like key value pattern, JSON Rules format, condition format ...etc (As generic as possible to be used for all use cases like quotes and transfer association and maintaining positions of FSPs...etc)
- [ ] Provide an option with requests to temporarily store them in a cache/ object-store
- [ ] Provide configurable parameter in events to choose the values in object-store
- [ ] Add an option in conditions to compare the values against the values stored in object-store. (WIth different type of operators like object equal, exists in an array, numerical and string operators ...etc)
- [ ] Provide an API and front-end to view the object-store
- [ ] Validation and testing

**Acceptance Criteria**:
- [ ] If needed, configuration is available to have a particular message stored temporarily (in a cache/ object-store)

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
The following is the format change for callback rules file.
These are just the initial observations based on the research happened in the story #1234  
```
"subRules": [
        {
          "ruleId": 1,
          "priority": 1,
          "description": "Save the transactionId",
          "conditions": {
            "all": []
          },
          "event": {
            "type": "STORE_SAVE",
            "name": "quotes",
            "key": "{$request.body.transactionId}",
            "value": "{$request.body}",
            "policy": "REPLACE",
            "expiration": "60"
          }
        }
      ]
```

```
      "subRules": [
        {
          "ruleId": 1,
          "priority": 1,
          "description": "Increment the position of payee fsp",
          "conditions": {
            "all": [
              {
                "fact": "callback.body.transferState",
                "operator": "equal",
                "value": "COMPLETED"
              }
            ]
          },
          "event": {
            "type": "STORE_SAVE",
            "name": "positions",
            "key": "{$request.body.payeeFsp}",
            "value": {
              "{$request.body.amount.currency}": "{$request.body.amount.amount}"
            },
            "policy": "MERGEADD",
            "expiration": "60"
          }
        }
      ]
```

**Comment by georgi-logodazhki** [comment]
Duplicate of #1377 
Duplicate of #1453
