### ISSUE TITLE
Merge Settlement v2 features into master

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1257]
## **Goal**:
As a Hub / Scheme Operator
I want to _make use of the Settlement v2 features - Settlement by Currency_
so that _I can provide that feature to the FSPs in my Scheme_

This story is about merging the changes done on v2 branch into master

**Tasks**:
- [x] Merge Settlement v2 branches into master (@bothadeon)
- [ ] Review, validate

**Acceptance Criteria**:
- [x] Designs are up-to date (@bothadeon)
- [x] Unit Tests pass (@bothadeon)
- [x] Integration Tests pass (@bothadeon)
- [x] Code Style & Coverage meets standards (@bothadeon)
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.(@bothadeon)
- [x] Settlement v2 branches on repos such as central-ledger, central-settlement and others are merged into master (@bothadeon)

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-settlement/pull/271

## **Follow-up**:
- N/A

**Dependencies**:
                                Manual Review                                 
            Some vulnerabilities require your attention to resolve            
Moderate      - Regular Expression Denial of Service                     
Package        - acorn                                                        
Patched in     >=7.1.1
Dependency of rewire [dev]
Path               - rewire > eslint > espree > acorn                      
More info      - https://npmjs.com/advisories/1488                           
found 1 moderate severity vulnerability in 10542 scanned packages

## **Accountability**:
- Owner: TBC
- QA/Review: @ndonnan @lazolalucas

**Comment by bothadeon** [comment]
Merge code changes from stories :

#1208 -- https://app.zenhub.com/workspaces/project-59edee71d1407922110cf083/issues/mojaloop/project/1208
#1241 -- https://app.zenhub.com/workspaces/project-59edee71d1407922110cf083/issues/mojaloop/project/1241

**Comment by bothadeon** [comment]
Dependancy on acorn : Patched in >=7.1.1 is not yet available in npm.
Dependancy ignored for 1 week currently : refer to audit-resolve.json
