### ISSUE TITLE
Testing toolkit and testing toolkit UI should meet ML OSS licensing standards

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1258]
## **Goal**:

As a User of the _testing toolkit_ 
I want the _testing toolkit ui to user libraries that conform to the ML OSS licensing standards_
so that _the toolkit UI service itself can conform to the Apache 2.0 license_

As a User of the _testing toolkit_ 
I want the monitoring page to be persistent across the page navigations
so that _I can have a consistent user experience_

**Tasks**:
- [x] Refactor the code to use 'Collapsable' from ant package instead of the library 'kendo-react-grid'
- [x] Work on licenses from 'Argon' template - Remove the template if necessary
- [x] Refactor reporting functionality be removing jsreport (which uses LGPL license ) with another library that is compatible with the Mojaloop compatible license
- [x] Re-enable audit license step in TTK's circle CI process
- [x] Add unit tests to achieve code coverage
- [x] Re-enable license check for TTK docker image on Helm CircleCI process by removing`| grep -v "mojaloop/ml-testing-toolkit"` from https://github.com/mojaloop/helm/blob/master/.circleci/format-docker-images.sh

**Acceptance Criteria**:
- [x] Redesigned and improved monitoring page with persistence
- [x] Passed audit license step in circle CI
- [x] License file from 'Argon' should not be included in the compiled code

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/66
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/111
- [x] https://github.com/mojaloop/helm/pull/399

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @elnyry-sam-k @mdebarros
