### ISSUE TITLE
ML Phase-3 Performance wrap-up and mid-PI (9) review prep

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1260]
## **Goal**:
As a Hub implementer / Switch
I want to _have an understanding of the Performance capabilities of the Mojaloop transfers_
so that _I can plan deployment models accordingly_ and _set the expectations, SLAs for the Scheme_

**Tasks**:
- [x] Wrap up any pending items for report-out on Phase-3 Performance effort
- [x] Demo-prep, presentation material

**Acceptance Criteria**:
- [x] Concluding presentation, report out for Phase-3 Performance wrap-up report is done

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @mdebarros 
- QA/Review: TBC
