### ISSUE TITLE
Update regex in ML interfaces (API and outward facing services) to support accents (select Unicode characters) in names

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1261]
## **Goal**:
As an FSP
I want to _update the regular expression used in ML FSPIOP API v1.0 API Swagger for Names_
so that _I can support parties / end-users with accents in their names_

As a Party (end-user) in a Mojaloop system with accent characters in my name
I want _my FSP to support registering names with accents_
so that _I can accurately register and use my name that has accents_

**Tasks**:
- [ ] Update the regex for Name definitions in the ML FSPIOP API Swagger used in the outward facing services for Schema validation
  - [ ] quoting-service
  - [ ] account-lookup-service
  - [ ] transaction-requests-service
  - [ ] ml-api-adapter
  - [ ] Review if any other services need to be updated
- [ ] (Before merging into master) Tests to be added around names with accents (Eg:  í, ű, á, ó, ü, ö, ú, ő, ű, é, Côte d'Ivoire ) and other negative scenarios that include characters that shouldn't be allowed
- [ ] Tests run on the interim version (before released)
- [ ] Once validated, approved and released

**Acceptance Criteria**:
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] Accents in names (unicode characters) are allowed based on the regular expression 

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @elnyry

**Comment by rmothilal** [comment]
This regex seems to work for javascript as the above works with other languages
`^(?!\s*$)[a-zA-ZÀ-ÖØ-öø-ɏ .,'-]{1,128}$`

**Comment by millerabel** [comment]
@rmothilal, thanks for testing that RE. However, for the code, we should use numeric range values for accented and non-latin characters. Within the CCB, @MichaelJBRichards is hosting a thread for how to specify what characters are permitted in names by the API specification. The _specification_ might take the form of an RE, but it is not intended that the spec be actual "code" that we can place in our system. We'll still have to choose the right form for an RE (or other implementation) that adheres to the requirements of the spec.

In RE's, we should be using named character classes rather than explicit characters (as used in your example). These named character classes are referenced using a standardized syntax and can extend to the subset of the Unicode 5 (or later) glyph space required in the API specification. Code may require certain parameters to be adjusted to activate these character classes.

The example you give here is limited to only a few accented latin characters rather than the broader Unicode space.

**Comment by millerabel** [comment]
The RE supplied in the story by Sam works fine in JavaScript and Node JS as of 10.0.0. The one you are suggesting here is not appropriate for our code as it depends on knowledge of the code points and ranges in Unicode. It also excludes the future use of non-Latin character symbols used in e.g. Myanmar.

I think this is a work in process.

For now, we should use the RE proposal in the story, and also strip leading and trailing blanks before storing, comparing, or matching Name Format values. There are other problems with this specification for Name Format that we’ll have to address with the CCB.

— Miller

**Comment by elnyry** [comment]
Thanks Miller.

We'd like to use the RE here, updated for the leading & trailing spaces (along with using a word character as the starting character - which you indicated elsewhere), and **_iterate_** over it with implementation & QA to reach a satisfactory conclusion..

**Comment by millerabel** [comment]
Thanks Sam(@elnyry). As Henrik notes in the thread on the CCB, requiring the first letter to be a word character might not be as intended. I concede that Name Format values like "123 Café" are quite reasonable. I'd start with the RE you propose, which aligns to the CCB change request, and as you say, iterate with code support until it gets the expected results.

Here is Node v12:

```
> RE = /^(?!\s*$)[\p{L}\p{Nd} .,'-]{1,128}$/u
/^(?!\s*$)[\p{L}\p{Nd} .,'-]{1,128}$/u
> RE.unicode
true
> aName = 'Pacific - A café';
'Pacific - A café'
> RE.test(aName)
true
> aName += '*'
'Pacific - A café*'
> RE.test(aName)
false
```

```
% node --version
v12.16.1
```

**Comment by millerabel** [comment]
Here is an example of compressing repeating strings of punctuation to a single space. And trimming leading and trailing spaces and punctuation:

``` JavaScript
> RE=/[ -.,']+/g
/[ -.,']+/g
> aName = "--123 O'Leary - a Café  "
"--123 O'Leary - a Café  "
> aName.replace(RE, ' ').trim();
'123 O Leary a Café'
```

We should discuss the proper canonical form for comparisons. I think this is a starting point.

**Comment by rmothilal** [comment]
Our current solution for this issue uses the OpenAPI-Backend library (https://github.com/anttiviljami/openapi-backend) the reason this was chosen was that it allowed us to edit the swagger used for validation AJV (https://ajv.js.org), we needed to updated the regex for use in Javascript with the appropriate flags as we are unable to do this with Swagger or Openapi > 3.0.
We have experience some issues with regards to the documentation endpoints that were used to access the swagger on the server. The plugin hapi-swagger stopped working and therefore we are unable to get that anymore. I was in the process of investigating other libraries namely XRegExp (http://xregexp.com) but I am unfortunately leaving the Mojaloop project and cannot continue with my investigation. I believe that the limitations of Javascript built in Regex library will not allow us to use the appropriate regex for the languages thus XRegExp is suggested. Using https://www.regular-expressions.info/unicode.html could give you a guide to address the language script regex issues under the Unicode Scripts section.

**Comment by mdebarros** [comment]
@elnyry-sam-k is this issue not closed?

**Comment by elnyry-sam-k** [comment]
I think we maybe able to close it now Miguel @mdebarros ; just need to make sure that any other services or resources using names are updated to use the latest regex expression. (for example, bulk Quotes, legacy Simulator, SDK scheme adapter)

**Comment by mdebarros** [comment]
> I think we maybe able to close it now Miguel @mdebarros ; just need to make sure that any other services or resources using names are updated to use the latest regex expression. (for example, bulk Quotes, legacy Simulator, SDK scheme adapter)

https://github.com/mojaloop/api-snippets/pull/105#pullrequestreview-733773360 <-- once this PR is released, we can update the SDK Scheme Adapter with the latest version of the api-snippets to regenerate the swagger. That will include the updated regex.
