### ISSUE TITLE
Migrate Perf changes into Master Code Branches

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1263]
## **Goal**:
As a Mojaloop Hub / Switch
I want to _have the performance enhancements done as part of PI8, PI9 to be made available to the community by including in master branches, releases_
so that _I can adopt them and take advantage of the new Performance upgrades (and monitoring features)_

**Tasks**:
- Metrics
    - [x] ~Central-Ledger [@vgenev]~ covered by #1289 
    - [ ] ~ML-API-Adapter~ covered by #1289 
    - [x] Central-Services-Stream
- Caching
    - [ ] Central-Ledger caching (traced in https://github.com/mojaloop/project/issues/1215 by @yosheeck)
- Enhancements
    - [ ] ~Duplicate-check Insert-only algorithm?~ [ Needs separate story]
    - [ ] ~Combined Prepare-Position Handler?~ [ Needs separate story]
    - [ ] Trace-state to support key-value pairs @vgenev
      - [x] ~event-sdk https://github.com/mojaloop/event-sdk/pull/34~ covered by #1289  
      - [x] ~central-services-shared https://github.com/mojaloop/central-services-shared/pull/203~ covered by #1289 
      - [x] ~ml-api-adapter https://github.com/mojaloop/ml-api-adapter/pull/380~ covered by #1289  
      - [x] ~central-ledger https://github.com/mojaloop/central-ledger/pull/647~ covered by #1289 
      - [x] ~simulator https://github.com/mojaloop/simulator/pull/166~ covered by #1289
      - [x] account-lookup-service https://github.com/mojaloop/account-lookup-service/pull/273
      - [x] transaction-requests-service https://github.com/mojaloop/transaction-requests-service/pull/27
      - [ ] quoting-service 
      - [x] ~event-sidecar~ covered by #1289
      - [ ] event-stream-processor ? 
 

    - [ ] central-services-metrics [new metric types: gauge, summary, etc.]
- ~Logging~ covered by #1289
   - [ ] ~Verbose~
   - [ ] ~Template processing~
   - [ ] ~Isolate logging statements (i.e. debug will only process if log-level is set to debug)?~
- Documentation
   - [ ] Architecture changes
   - [ ] Performance improvements
- Helm changes
    - [ ] ~Config changes~ --> Part of #1289 

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
