### ISSUE TITLE
QA: Postman OSS-API-Tests collection - Part2

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1265]
## **Goal**:
As a Hub / Switch
I want to _refine and have a postman test collection for API tests_
so that _I can use it to test various features for higher coverage apart from Golden Path tests_

**Tasks**:
- [ ] From the OSS-API-Tests postman collection(https://github.com/mojaloop/postman) refine the tests for below APIs and scenarios
  - [ ] Mojaloop-API
    - [ ] parties
    - [ ] quotes
      - [ ] PUT
    - [ ] transfers
- [ ] Create separate story to follow-up the below resources (a part-3 of this feature)
  - [ ] Admin-API
  - [ ] Settlements-API
  - [ ] Metrics-API
  - [ ] FundsIn-API
  - [ ] FundsOut-API
  - [ ] ALS Admin API (Oracles, etc.)
- [ ] Create a new collection with tests that are defined and validated (aptly named)
- [ ] Add it to the regression testing process to run with Helm releases, along with Golden path collection

**Acceptance Criteria**:
- [ ] A sub-set of the OSS API tests collection is identified based on active tests and created as a separate collection to be run regularly with Helm releases along with the Golden path collection for the below resources / APIs and scenarios
  - [ ] Mojaloop-API
    - [ ] parties
    - [ ] quotes
      - [ ] PUT
    - [ ] transfers

## **Pull Requests**:
- TBD

## **Related**:
- #971 

## **Follow-up**:
- N/A
