### ISSUE TITLE
Testing toolkit: JWS implementation and support

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1266]
## **Goal**:
As a User of the _testing toolkit_
I want to _be able to support JWS_
so that _I can validate and perform JWS validation_

**Tasks**:
- [x] Investigate sdk-standard-components for JWS features
- [x] Design for using JWS in testing toolkit
- [x] Investigate the use of connection manager and check the feasibility / necessity to integrate that in testing toolkit
- [x] Decision on design and usage for the testing toolkit
- [x] Implementation proposal for JWS in testing toolkit
- [x] Implementation of connection manager connector module
- [x] JWS module implementation for sign and validate functions
- [x] Add required options in the front-end
- [x] Streamline the login process for connection manager which uses Oauth2 for authentication 

**Acceptance Criteria**:
- [x] Understanding on usage of JWS features from sdk-standard-components in the testing toolkit is recorded
- [x] Designs for JWS in testing toolkit proposed and documented
- [x] Proposal for implementation
- [x] JWS functionality should work with scheme adapter both inbound and outbound with connection manager

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/29
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/9

## **Follow-up**:
- #1279 

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @elnyry
