### ISSUE TITLE
Performance: Combine fulfil and position handlers into a single handler

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1268]
## **Goal**:
As a Hub Operator
I want to _use versions of Mojaloop Switch services with improved performance by combining fulfil and position handlers_
so that _I can support higher performance needs of a Scheme_

**Tasks**:
- [x] Refactor central-ledger to combine fulfil and position handlers
- [ ] PR and reviews
- [ ] Design discussions , issues if needed
- [ ] Changes to documentation (including sequence diagrams)
- [ ] Helm charts changes
- [ ] Releases
- [ ] QA and validation

**Acceptance Criteria**:
- [ ] Designs are updated to reflect the changes and refactoring done
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] QA and validation done to ensure that there are no regressions
- [ ] A combined handler for the fulfil step in transfer process is available (a new fulfill handler that includes functionality of the current fulfil and position (fulfil step) handlers )

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vgenev** [comment]
POC was created for golden path scenario. If this needs to go into the master stream, it will be a follow up story.
