### ISSUE TITLE
Benchmark our container security tools against commercial tools

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1271]
## **Goal**:

This is specific to Anchore against tenable and snyk.

**Tasks**:
- [ ] TBD [ @? ]

- Things to compare:
- [ ] basic docker image scanning, 
  - [ ] What is the scope of each scanning tool? What are the defaults? How can each be configured?
  - [ ] test across 3 main mojaloop containers, perhaps `quoting-service`, `ml-api-adapter` and `central-ledger`
- [ ] CI/CD integrations (we have anchore just about working, but it would be interesting to see what the others do
- [ ] notification/management/etc. For anchore-cli, we don't get this at all.

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
