### ISSUE TITLE
Instrumentation of Transaction Requests Service

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1272]
**Goal**:
As a Hub Tech Operator or Hub DevOps
I would like the _add instrumentation to the Transaction Requests Service_
to enable operational monitoring and identify status/metrics and issues if any.

**Tasks**:
- [x] Import mojaloop/metrics lib
- [x] Transaction Requests Service metrics
  - [x] Include metrics initialization in API startup
  - [x] Add metrics to all relevant endpoints
  - [x] Update/fix tests
- [x] Validate locally

**Acceptance Criteria**:
- [x] Instrumentation is provided for the Transaction Requests Service
- [x] Designs are up-to-date
- [x] Unit Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment configs.

**PRs**:
- [x] https://github.com/mojaloop/transaction-requests-service/pull/26

**Dependencies**:
- [ ] 

**Accountability**:
- Owner @oderayi 
- QA/Review @rmothilal @mdebarros
