### ISSUE TITLE
As a contributor need to see the latest release notes

### ISSUE THREAD

**Issue by kjw000** [mojaloop/project#1273]
## **Goal**:
As a  contributor I want to see the latest release notes, what changes and relevant dependencies on Helm

**Tasks**:
- [x] kick off release
- [x] Update release notes - https://mojaloop.io/documentation/deployment-guide/releases.html

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] understand issues with helm 2.0 and 3.0

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
