### ISSUE TITLE
Trigger Daily QA Regression tests from CircleCI

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1274]
## **Goal**:
As a `project maintainer`, I want to `run the daily QA tests from CircleCI` so that `I can get more visibility into the test failures, and remove a dependency on 'hidden' cron jobs on EC2 instances`.

With CircleCI's scheduled jobs feature, we schedule daily QA test runs without needing to depend on the existing cron jobs triggered from an EC2. This would move some hidden configuration out into the open, and make it easier to modify and improve the tests.

This will also form the basis for other regular tests we may want to run in the future, and make it easier to configure them.

**Tasks**:
- [ ] Create a new repo? or use existing ci-config repo to configure a scheduled daily job to run the existing QA tests: https://circleci.com/docs/2.0/workflows/#scheduling-a-workflow
- [ ] Remove existing cron jobs after we are confident this new approach will work

**Acceptance Criteria**:
- [ ] New QA test is configured to run from CircleCI, and meets our existing QA Test standards
- [ ] Code Style & Coverage meets standards
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: @NicoDuvenage

**Comment by elnyry-sam-k** [comment]
@lewisdaly - is this still needed? we have the capability from the TTK to run tests on schedule (daily and configurable) and also post default install..

**Comment by lewisdaly** [comment]
Yeah this is outdated. On a related note - do we have the TTK test scheduling capability well documented?
