### ISSUE TITLE
Testing tool-kit: Adding assertions on the testing toolkit for FSP GP path

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1275]
## **Goal**:
As an FSP in a Scheme
I want to _have a tool that provides rules and assertions to an FSP's behavior based on the FSPIOP API_
so that _I can evaluate my readiness based on the results of the assertions_

This is one of the stories attempting to provide for the above goal.

**Tasks**:
- [x] Add assertions for FSP behavior - 1 [@HenkKodde ]
- [x] Add assertions for FSP behavior - 2 [@amarmodus ]
- [x] Bugfixes and immediate required features for adding assertions [@vijayg10 ]
- [x] Review added assertions
- [x] Identify gaps in adding assertions to check desired behavior [@HenkKodde ]

**Acceptance Criteria**:
- [ ] Assertions related to FSP behavior are added on the testing toolkit for the various resources present in the FSPIOP API
- [ ] The tests based on setup will pass on an FSP that conforms to the API Definition v1.0

## **Pull Requests**:
- [x] Initial assertions on current available operations - https://github.com/mojaloop/ml-testing-toolkit/pull/28

## **Follow-up**:
- https://github.com/mojaloop/project/issues/1293 - This task will be continued further

**Dependencies**:
- https://github.com/mojaloop/project/issues/1278 - All issues are verified
- https://github.com/mojaloop/project/issues/1291 - All issues are verified

## **Accountability**:
- Owner: @HenkKodde @amarmodus 
- QA/Review: @vijayg10 @elnyry

**Comment by vijayg10** [comment]
The initial plan for test cases hierarchy is as below

* P2P transfer happy path
   * Get parties
      * Response validation
      * Callback validation
   * Post quotes
      * Response validation
      * Callback validation
   * Post transfers
      * Response validation
      * Callback validation
* Get Parties Wrong header fields (Schema validation)
   * Missing required header 1
   * Missing required header 2
   * Wrong header 1
   * Wrong header 2
   * Wrong optional header 3
   * ...etc
* Get parties Wrong Body (Schema validation)
   * Missing required body param 1
   * Missing required body param 2
   * Wrong body param 1
   * Wrong body param 2
   * Wrong optional body param 3
* Get parties other negative scenarios
   * Get party information for an unprovisioned MSISDN
   * Get party info for an unprovisioned Type
   * ...etc
* Post quotes wrong headers
* Post quotes wrong body params
* Post quotes other negative scenarios
* Post transfer wrong headers
* Post transfer wrong body params
* Post transfer other negative scenarios

**Comment by amarmodus** [comment]
Following list can be used as reference for assertion - Thanks @vijayg10 

* P2P transfer happy path
   * Get parties
      * Response validation
      * Callback validation
   * Post quotes
      * Response validation
      * Callback validation
   * Post transfers
      * Response validation
      * Callback validation
* Get Parties Wrong header fields (Schema validation)
   * Missing required header 1
   * Missing required header 2
   * Wrong header 1
   * Wrong header 2
   * Wrong optional header 3
   * ...etc
* Get parties Wrong Body (Schema validation)
   * Missing required body param 1
   * Missing required body param 2
   * Wrong body param 1
   * Wrong body param 2
   * Wrong optional body param 3
* Get parties other negative scenarios
   * Get party information for an unprovisioned MSISDN
   * Get party info for an unprovisioned Type
   * ...etc
* Post quotes wrong headers
* Post quotes wrong body params
* Post quotes other negative scenarios
* Post transfer wrong headers
* Post transfer wrong body params
* Post transfer other negative scenarios

**Comment by amarmodus** [comment]
task will be continued further in https://github.com/mojaloop/project/issues/1293.
