### ISSUE TITLE
Perf testing - combined handlers for prepare, fulfil steps

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1277]
## **Goal**:
As a Hub Operator
I want to _understand the changes in performance characteristics of the Switch with combined prepare+position and fulfil+position handlers_
so that _I can make informed decisions of scaling levels, ratio needed_ and identify bottle-necks

**Tasks**:
- [x] Setup needed to understand perf characteristics of each individual handler (prepare, position, fulfil, notification)
- [x] Record numbers subject to variables (scaling, infrastructure) involved
- [x] Record observations
- Test Scenarios:
    - [x] Notification Handler -> <by-pass simulator> -> produce to fulfil topic [ @vgenev ]
      - [x] Create service to consume from configurable topic via CLI command
      - [x] Handle the message as the Notification topic will after receiving notification from FSP (based on simulator)
      - [x] Create docker image & helm chart
**Acceptance Criteria**:
- [x] Each handler is run with sufficient load of messages to understand its perf characteristics when run in conjunction with the other handlers (necessary for transfers)
- [x] Metrics / Perf numbers are recorded for reference
- [x] Observations recorded and recommendations made

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: 
- QA/Review: @mdebarros @elnyry

**Comment by elnyry** [comment]
The refactoring needed for supporting this PoC is done and observations documented in the Performance report
