### ISSUE TITLE
Testing tool-kit: Adding features for effective usage of the tool

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1278]
## **Goal**:
As an FSP in a Scheme
I want to have a tool that provides rules and assertions to an FSP's behavior based on the FSPIOP API
so that I can evaluate my readiness based on the results of the assertions

Following feature additions were uncovered during the https://github.com/mojaloop/project/issues/1275 testing

**Tasks**:
- [x] Add test case button
- [x] Delete and rename for test cases
- [x] Auto save on client side
- [x] Add response body along with status and statusText in “Add expectation”
- [x] Rename assertion function is missing
- [x] Response layout issue - If we reduce the width, input values box should be consistent
- [x] Duplicate feature for request
- [x] Duplicate a test-case
- [x] Request addition is breaking
- [x] Add configurable parameter button in Request editor and functionality 
- [x] Renaming button to be added in Request/Testcase editor
- [x] Change the layout of Testcase editor with vertical design when multiple request added / Add horizontal scrollbar for the vertical design
- [x] The add request button is not working where there are no requests in the testcase
- [x] Show actual request sent after execution
- [x] Show total passed and failed assertions

**Acceptance Criteria**:
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/10
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/11

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @amarmodus, @HenkKodde

**Comment by amarmodus** [comment]
Verified by @amarmodus 
- [x] Add test case button - verified
- [x] Delete and rename for test cases - verified
- [x] Auto save on client side - verified
- [ ] Add response body along with status and statusText in “Add expectation”
- [x] Rename assertion function is missing - verified
- [x] Duplicate feature for request - verified
- [x] Duplicate a test-case - verified
- [x] Request addition is breaking - verified

**Comment by amarmodus** [comment]
Duplicate request broken after sending all request.
<img width="1291" alt="Screenshot 2020-04-01 14 35 49" src="https://user-images.githubusercontent.com/53434415/78143639-72185d00-7426-11ea-8758-b1e2e0bcebf9.png">
<img width="710" alt="Screenshot 2020-04-01 14 36 20" src="https://user-images.githubusercontent.com/53434415/78143754-95430c80-7426-11ea-98a3-ef4fcd01e445.png">
