### ISSUE TITLE
Testing Toolkit - JWS review and test coverage

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1279]
## **Goal**:
As a User of the _testing toolkit_
I want to _be able to support JWS_
so that _I can validate and perform JWS validation_

**Tasks**:
- [x] Document and review the flow
- [x] Do required changes
- [x] Add unit tests for the new functionality

**Acceptance Criteria**:
- [x] JWS functionality is reviewed and the required changes are implemented
- [x] Added test coverage for the new JWS related functions

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/31

## **Follow-up**:
- Implementation

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @elnyry
