### ISSUE TITLE
Review Node.JS Kafka Libraries and provide recommendation for Implementation

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#128]
**Goal**:
As a developer I would like to research available Nodejs Kafka libraries and make recommendations for implementation in the Mojaloop project.

**Tasks**:
- [x] Review kafka nodejs libraries that are available for Node.js
- [x] Provide list of libraries and recommendation which lib to implement 
- [x] PoC with selected library against local Kafka instance (running in docker)

**Acceptance Criteria**:
- [x] Document nodejs library reviews results and outcomes
- [x] PoC with selected library against local Kafka instance (running in docker)

**Dependencies**:
- None currently

**Comment by lazolalucas** [comment]
Document with results and recommendations: 
https://drive.google.com/open?id=1rRTOkbdMPa9rRv6ZwKgh7nbNz1XWSrM2A7jVEoKNPXA

POC: https://github.com/lazolalucas/poc_kafka-node
