### ISSUE TITLE
Disable github issues or add issue template to Mojaloop Repos

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1280]
## **Goal**:
As an `OSS Maintainer` I want to `find a way that new contributors open issues in the right place`, so that `we can better keep track of issues opened by new contributors.`

I've had a bit of feedback that it's not easy to know where to file new github issues for new contributors. We have 2 options:
1. Disable github issues for most of the Mojaloop Repos
2. Add an issue template that tells users not to file an issue there, but in the `mojaloop/project`

We probably don't need this for all of the repos, but just the most popular ones at the moment. 

My preference is #2, but I'm happy to be swayed.
 

**Tasks**:
- [ ] Decide on above options
- [ ] Decide on list of repos to be changed
- [ ] apply the change either in code, or GitHub settings

**Acceptance Criteria**:
- [ ] Issues are disabled for repos, or issue template is updated.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: TBC

**Comment by elnyry** [comment]
@lewisdaly - its good to standardize this, but wanted to add the current convention here.

We encourage everyone to raise issues here: https://github.com/mojaloop/project/issues/new/choose , (under mojaloop/project) unless they are issues with the Mojaloop FSPIOP API Specification, in which case, they can be raised here: https://github.com/mojaloop/mojaloop-specification/issues/new/choose. In both these places, we have templates to choose from, based on the nature of the issues..
Another important point I wanted to add is that - so far, for specific issues in a repo or service we're still using the issues on that specific repo, so that for anyone using it or intending to use it, they're aware of the known and active issues. For example here are two repos: https://github.com/mojaloop/helm/issues, https://github.com/mojaloop/central-ledger/issues

So, may be we need more visibility to this concept and documentation, but I'm not opposed to your ideas as well.
