### ISSUE TITLE
Make mojaloop npm modules less strict on dependencies

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1281]
## **Goal**:
As an `OSS Maintainer` I want to `allow npm modules to install bugfix versions` to `reduce the burden of dependency management

Proposal: For mojaloop npm modules (such as `central-services-shared`), relax some of the npm module settings in the `package.json` files to allow bugfixes to be applied automatically without manually updating the packages.

**Tasks**:
- go through a list of all mojaloop projects with npm targets, and change the syntax to allow bugfixes to be applied automatically.

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
