### ISSUE TITLE
Documentation on usage of helm v3 charts for Mojaloop

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1283]
## **Goal**:
As a Community member
I want to _understand the usage of helm v3 and its compatibility issues_
so that _I can make an informed decision on how to use them and the consequences_

**Tasks**:
- [x] Based on validation of helm3 charts over various scenarios ( in #1070 )
- [x] Document helm v3 notes, observations and usage instructions
- [x] Document helm migation from v2 to v3
- [x] Test updated documentation for helm v3
- [x] Test migration of an existing helm v2 mojaloop deployment to helm v3

**Acceptance Criteria**:
- [x] Helm v3 usage and compatibility notes are documented

## **Pull Requests**:
- [x] https://github.com/mojaloop/documentation/pull/236

## **Follow-up**:
- N/A

**Dependencies**:
- [x] #1070 

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
