### ISSUE TITLE
QA: Tests for authorizations in the Golden path

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1284]
## **Goal**:
As an adopter of Mojaloop
I want to have a postman test collection that includes /authorizations
so that I can use it to validate my various deployments that need this service

**Tasks**:
- [x] Write postman test for authorizations
- [x] Error framework tests for authorizations - GET, PUT
- [x] Sample runs, report issues - https://github.com/mojaloop/project/issues/1285 , https://github.com/mojaloop/project/issues/1314 - Raised
- [x] PR and reviews

**Acceptance Criteria**:
- [x] Tests for transaction-requests-service are added in the Golden path test collection on postman repo that provide coverage.

## **Pull Requests**:
- [x] https://github.com/mojaloop/postman/pull/106
- [x] https://github.com/mojaloop/postman/pull/114

## **Follow-up**:
- https://github.com/mojaloop/project/issues/1314

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @amarmodus 
- QA/Review: TBC

**Comment by elnyry** [comment]
@amarmodus as discussed, once you have the PR, we can mark it appropriately (to be merged after we have the relevant version (or greater) of transactions-requests-service part of the Mojaloop deployment) and then close it

**Comment by amarmodus** [comment]
mojaloop/postman#114 - see screenshot attached.
