### ISSUE TITLE
Event Framework: Implement event tracing/audit for all appropriate endpoints in ALS

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1286]
## **Goal**:
As Hub TechOps
I want to be able to audited and trace account-lookup-service related endpoints
so that a complete view of all requests is captured

**Tasks**:
- [ ] Update all appropriate endpoints with tracing and audit

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
