### ISSUE TITLE
Migrated Performance Changes for v9.5 Release

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1289]
## **Goal**:
As a Mojaloop Hub / Switch
I want to _have the performance enhancements done as part of PI8, PI9 to be made available to the community by including in master branches, releases_
so that _I can adopt them and take advantage of the new Performance upgrades (and monitoring features)_

**Tasks**:
1. Metrics
    - [x] release non-snapshot version of the metrics library [@mdebarros]
    - [x] Central-ledger
    - [x] Ml-api-adapter - @vgenev 
    - [x] Central-services-shared <— I don’t think there is anything here
    - [x] Legacy-Simulators <— I don’t think there is anything here
    - [ ] Mojaloop-Simulator <— Need to add Event SDK/Sidecar Support. If there is time.
    - [ ] ~~Central-services-stream~~  (out of scope)
    - [ ] ~~Central-services-logger~~  (out of scope)
2. Tracestate - @mdebarros 
    - [x] EventSDK update tracestate handling @vgenev 
    - [x] Event-Sidecar
    - [x] Central-ledger
    - [x] Ml-api-adapter
    - [x] Central-services-shared
    - [x] Legacy-Simulators
    - [x] Event-Stream-Processor
    - [ ] Mojaloop-Simulator <— Need to add W3C Trace Header support. If there is time.
 
3. Log optimisation  - @yosheeck 
    - [x] Determine if we can get the Log_level from Winston
      - [x] Released @mojaloop/central-services-logger v9.5.1
    - [x] central-services-stream
      - [x] Released @mojaloop/central-services-stream v9.5.0
    - [x] central-services-shared
      - [x] Released @mojaloop/central-services-shared v9.5.3
    - [x] ML-API-Adapter  
    - [x] Central-Ledger
    - [x] Event-sidecar
    - [x] Legacy-Simulators <— I don’t think there is anything here
4. [ ] ~Optimised SQL~ <— Nice to have….and only if there is time
    - ~~5. Caching~~
        - ~~[ ] Limits~~
6. [ ] ~Helm~ Moved to #1323 

**Acceptance Criteria**:
- [x] Metrics enhancements done as part of Perf testing are merged to master
- [x] Tracestate related  enhancements done as part of Perf testing are merged to master
- [x] Log Optimisation related  enhancements done as part of Perf testing are merged to master
- [ ] ~Helm changes needed to support metrics, events, log optimization done are made~

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vgenev @yosheeck @mdebarros 
- QA/Review: TBC
