### ISSUE TITLE
Assess the notification functionality required by a user of the system 

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#129]
**Goal**:
As a user of the system, I would like to assess the notification functionality required.

**Tasks**:
- [ ] Analysis and design of notifications

**Acceptance Criteria**:
- [ ] Define/Gather requirements
- [ ] A spec detailing notification design

**Dependencies**:
- [ ] Product owner (or equivalent person) input
