### ISSUE TITLE
Benchmark (Performance) report for PI-9

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1290]
## **Goal**:
As a Mojaloop Hub / Switch
I want to _have a Benchmark Report of the performance enhancements done as part of PI8, PI9 made available to the community by including in master branches, releases_
so that _I can review the report, adopt the changes and take advantage of the new Performance upgrades (and monitoring features)_

**Tasks**:
1. Baseline with RDS + Percona @ 200 MB/s
    - Test Scenarios
        - [x] With simulated Notification Delivery with RDS
        - [ ] With real-notification delivery with RDS <— If there is time
        - [ ] With simulated Notification Delivery with Percona <— If there is time
        - [ ] With real-notification delivery with with Percona <— If there is time
    - General Setup for Testing
        - Caching disabled <— Reason: Too Risky as caching enabled has not been tested in Dev1/Dev2 as of yet.
        - Event-sidecar disabled
        - Time-out Handler disabled <— Known Issue: Dead-lock to be resolved in future
        - Logging (with Events locally Logged)
            - Async <— going with async logging for now. 
            - ~~Sync~~ <— In future to compare against sync.
2. Benchmark Report
    - [ ] Markdown Document as part of Mojaloop Documentation
    - Include
        - ~~100MB/s @ 300 TPS~~ Out of scope until we can re-test this
        - [ ] 200MB/s @ 500 TPS
        - [ ] 300MB/s @ 900 TPS
    - Master Baseline
        - [x] RDS @ 200 MB/s
        - [ ] Percona @ 200 MB/s <— If there is time

**Acceptance Criteria**:
- [x] A performance report with testing and observations done in PI9 timeframe is documented and published to GitHub
- [x] The Benchmark report test includes metrics for test scenarios for RDS, Percona for comparison
- [ ] The Benchmark report test includes metrics for test scenarios for 200MB/s @ 500 TPS and 300MB/s @ 900 TPS for comparison
- [x] The Benchmark report test includes metrics for other test scenarios as specified

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @mdebarros @yosheeck @vgenev 
- QA/Review: TBC

**Comment by elnyry** [comment]
This is done and findings presented during the PI-10 Community Event.
