### ISSUE TITLE
Testing tool-kit: Adding features for effective usage of the tool - part 2

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1291]
## **Goal**:
As an FSP in a Scheme
I want to have a tool that provides rules and assertions to an FSP's behavior based on the FSPIOP API
so that I can evaluate my readiness based on the results of the assertions

Following feature additions were uncovered during the #1275 testing further to #1278

**Tasks**:
- [x] Requests execution should continue when a previous request fails
- [x] While saving the file, check for the .json extension
- [x] Show current template name 
- [x] Show 'click to copy' in config params addition in request screen
- [x] % completion can be rounded off
- [x] While changing the value in param ID, type select box is losing its value

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/12
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/33

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @amarmodus

**Comment by amarmodus** [comment]
Requests execution should continue when a previous request fails - verified 
 While saving the file, check for the .json extension - verified 
 Show current template name - verified 
 Show 'click to copy' in config params addition in request screen - verified 
 % completion can be rounded off - verified
