### ISSUE TITLE
PI 10 Meeting - Mojaloop Security & Compliance Presentation

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1294]
## **Goal**:

Develop final feedback presentation to the community.

**Tasks**:
- [ ] Develop a presentation template [@godfreykutumela ]
- [ ] Distribute to the team for input [ @godfreykutumela ]
- [ ] Review input and finalize the presentation [ @godfreykutumela ]
- [ ] Setup and conduct a dry run session with all team members [ @godfreykutumela ]

**Acceptance Criteria**:
- [ ] Completed presentation
- [ ] Completed dry run session

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
