### ISSUE TITLE
Validate POC success criteria

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#130]
**Goal**:
As a developer of the mojaloop system, I would like to validate the POCs against the success criteria so that observations and recommendations can be used to make changes to existing services/system.

**Tasks**:
- [x] Validate data integrity is maintained (by validating data from all (3) DB instances separately against tests run via JMeter and cross reference them with data from JMeter runs)
- [x] Verify Replication (resilience) (via K8s, deleting a node and verifying replication on all the DB instances - especially the new pod/DB that got spun up).
- [ ]

**Acceptance Criteria**:
- [x] Understand performance characteristics (impact of replicas, etc – how does it compare to the existing implementation) (Priority: High) 
- [x] Prove scalability (micro-services – pods within K8) (Priority: Medium)
- [x] Understand limitations (Priority: Medium)
- [x] Prove resilience (High Availability – losing a node on K8) (Priority: Low) (Optional)

**Dependencies**:
- [x] #76 
- [x] #75 
- [x] #117

**Comment by HenkKodde** [comment]
Dependency on #76 still in progress.
