### ISSUE TITLE
Add more unit tests for testing toolkit

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1304]
## **Goal**:
As a maintainer _of the OSS Testing tool-kit_
I want to _ensure there are unit tests for the code base_ for at least 90% of the code.

**Tasks**:
- [x] Cover unit tests for more than 80% of the functions for the backend service
        (More than 90% coverage if we exclude some server initialization functions, We can address these in the PI10)

**Acceptance Criteria**:
- [x] 90% test coverage for backend service

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/45

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @elnyry
