### ISSUE TITLE
OSS On-Boarding Enablement [PI-12]

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1306]
## **Goal**:

To improve the overall OSS On-boarding process, starting with the end to end review, exploring solution options and adopting a solution framework on which improvement initiatives will be based on.

To be detailed further after consultation with key stakeholders.

**Tasks**:
- [ ] End to end review of the OSS on-boarding process [ @godfreykutumela ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Continued in #2162
