### ISSUE TITLE
OSS PDP: Testing tool-kit [PI-10]

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1313]
**Testing Toolkit - Objective for PI10**: Stand-alone version that can be used with features to export, import rules and settings is made available, with capability for hosting the toolkit.

- [x] 0. Verifying condition and fulfilment (based on the ilpPacket) - Payee FSP perspective #1364 
- [x] 1. Test Reports and exporting options #1321 
- [x] 2. Support for all the API resources #1312 
- [x] 3. Assertions for all the new resources added #1312 
- [x] 4. CLI Option #1322 
- [x] 5. Prioritize Rules #1425
- [x] 6. Import / Export Settings as file #1424 
- [x] 7. Import / Export Rules as file #1424 
- [x] 8. QA: >98% test coverage #1445 
- [x] 9. Trace ID - based grouping #1489 
- [x] 10. Test cases separately for Hub, FSP options 10.2 #1369 
- [x] 11. Capabilities to host the toolkit #1454
   - [x] Secure admin API with oAuth #1465
   - [x] Endpoint provisioning using MCM #1466 
   - [ ] ~Persistent logs and reports~ #1467 
- [x] 12. Curl (code) option for outbound messages (Also included in #1321)
- [x] 13. Rules for ML FSPIOP API v1.1 #1480 
- [x] 14. Caching functionality in rules #1453 

New Objectives

- [x] 15. Helm chart for testing toolkit #1410 
- [x] 16. Work on Mojaloop Community wide adoption (and work gaps if any)
