### ISSUE TITLE
Testing Toolkit: CLI client for test case execution

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1322]
## **Goal**:
As a DFSP in a Scheme
I want to have a command line client tool that can execute the testcases and generate a consolidated report.
so that I can integrate that tool in my CICD automation systems

**Tasks**:
- [x] Define the characteristics / scope of the command line client [ @vijayg10 @georgi-logodazhki ]
- [x] Define the command line options to provide [ @vijayg10 @georgi-logodazhki ]
- [x] Define the exit codes incase of success and failures to make it usable for CICD [ @vijayg10 @georgi-logodazhki ]
- [x] Finalize the format of the consolidated test report (PDF and JSON) [ @vijayg10 @georgi-logodazhki ]
- [x] Implementation
- [x] Add unit tests
- [x] Document the usage and features

**Acceptance Criteria**:
- [x] CLI tool has an initial set of command line options required
- [x] CLI tool can generate output in PDF and JSON formats based on the options given
- [x] The report generated is acceptable
- [x] The exit codes are appropriate
- [x] Unit tests added for the new functionality
- [x] Documentation available to use this tool

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/49
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/50

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: N/A
- QA/Review: @vijay @elnyry
