### ISSUE TITLE
Helm Release v10.1.0: Updates to helm, Supporting QA, Fixes, Releases - 1

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1323]
## **Goal**:
As an ML OSS Code base maintainer
I want to _validate and make a Helm release in PI-10 (Sprint 10.1) that is successfully validated by the Golden path tests_
so that _Community members can take and use a version of Mojaloop Switch services bundle that is tested and contains latest features and enhancements (added in and PI9(Sprints 9.4, 9.5, 9.6, 10.1) so far)_ 

This specific story is for making necessary changes for supporting Deployment, QA, Fixes, Integration and performing end-to-end testing for all the changes made since Helm v10.1.0

**Tasks**:
- [x] Make releases on all core services to have latest images / versions [@mdebarros, @vgenev ]
- [x] Identify changes needed for helm (config / default.json) [@mdebarros]
- [x] Integrate/Merge Mojaloop-Simulators into main Mojaloop Helm chart for general release  [@mdebarros]
- [x] Initial PR with changes for v10.1.0  [@mdebarros]
  - [x] Initial PR review
  - [x] Deploy, validate, fix issues, redeploy [@mdebarros]
  - [x] With stable deployment test Golden path [@mdebarros]
- [x] Identify issues with QA Scripts if any - fix them and retest [@mdebarros]
     - [x] https://github.com/mojaloop/postman/pull/109
- [x] Identify Bugs, log them [@mdebarros]
- [x] Validate finance portal [@amarmodus ]
- [x] Fix bugs logged if critical [ @mdebarros  ]
     - [x] https://github.com/mojaloop/project/issues/1338
     - [x] https://github.com/mojaloop/project/issues/1339
- [x] Deploy, validate on AWS dev2 [ @mdebarros ]
- [ ] ~Helm v10.1.0 released~ --> folllowed-up in #1371 
- [ ] ~Deployment of released Helm v10.1.0 on **Dev2**~ --> folllowed-up in #1371 
- [ ] ~Validation using Golden path regression tests etc on Dev2~ --> folllowed-up in #1371 
- [ ] ~Deployment of released Helm v10.1.0 on **Dev1**~ --> folllowed-up in #1371 
- [ ] ~Validation using Golden path regression tests etc on Dev1~ --> folllowed-up in #1371 

**Acceptance Criteria**:
- [x] Helm RC v10.1.0 is validated on dev2 and iterated until 100% pass result with postman Golden path collection is achieved
- [x] QA (Golden path) on deployments done on AWS dev2 environment is done
- [x] Bugs are logged based on observations, failures
- [x] Bugs logged are fixed to make subsequent releases in individual services (or Helm)
- [x] All the changes needed for supporting v10.1.0 of Helm (List out major changes in release notes once release is ready) are done

**Pull Requests**:
- [ ] https://github.com/mojaloop/helm/pull/309

**Follow-up**:
- #1371 

**Dependencies**:
- N/A

**Accountability**:
- Owner: @mdebarros 
- QA/Review: @elnyry

**Comment by mdebarros** [comment]
Golden path passing -> https://www.dropbox.com/s/qt5eqhlq1bsddqo/Screenshot%202020-05-11%2016.16.46.png?dl=0
@amarmodus please validate Finance-portal and Mojaloop-Simulators
