### ISSUE TITLE
Bulk transfers support in sdk-scheme-adapter (mojaloop-simulator)

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1325]
## **Goal**:
As an FSP / Mojaloop Switch
I want the sdk-scheme-adapter component to support Bulk Transfers end-points and related functionality
so that I can use it for QA and Validation of Bulk transfers (including mojaloop-simulator)

**Tasks**:
- [x] Analyze sdk-scheme-adapter codebase to verify bulk transfers support [@oderayi]
   -  _Bulk transfers is currently not supported in scheme-adapter_
- [x] Validate if Design is needed and include if needed [@oderayi]
   - _Design added as comment below_
- [x] Implement support for bulk quotes and bulk transfers [@oderayi]
  - [x] POST /bulkTransfers (test-api) [@oderayi]
  - ~PUT /bulkTransfers/{ID} (test-api)~
  - [x] POST /bulkQuotes (FSP backend) [@oderayi]
  - [x] POST /bulkTransfers (FSP backend) [@oderayi]
  - [x] POST /bulkQuotes (Inbound scheme-adapter) [@oderayi]
  - [x] PUT /bulkQuotes/{ID} (Inbound scheme-adapter) [@oderayi]
  - [x] PUT /bulkQuotes/{ID}/error (Inbound scheme-adapter) [@oderayi]
  - [x] PUT /bulkTransfers/{ID} (Inbound scheme-adapter) [@oderayi]
  - [x] PUT /bulkTransfers/{ID}/error (Inbound scheme-adapter) [@oderayi]
  - [x] GET /bulkTransfers/{ID} (Inbound scheme-adapter) [@oderayi] 
  - [x] POST /bulkTransfers (Inbound scheme-adapter) [@oderayi]
  - [x] POST /bulkQuotes (test-api) [@oderayi]
  - ~PUT /bulkTransfers/{ID} (Outbound scheme-adapter)~
  - [x] POST /bulkQuotes (Outbound scheme-adapter) [@oderayi]
  - [x] POST /bulkTransfers (Outbound scheme-adapter)[@oderayi]
  - [x] GET /bulkTransfers/{ID} (Outbound scheme-adapter)
- [x] Unit tests/test coverage fixes [@oderayi]
  - [x] Simulator tests (FSP backend)
     - [x] models/bulkQuotes.js [@oderayi]
     - [x] models/bulkTransfers.js 
     - [x] handlers.js 
  - [x] Test-API tests
    - [x] Bulk quotes scenario test
    - [x] Bulk transfers scenario test
   - [x] Scheme-adapter tests
      - [x] Inbound API [@oderayi]
      - [x] Outbound API [@oderayi]
- ~Local testing/validation~
- ~QA - postman tests~
- ~Update helm scripts to support changes and for deployment~
- ~Deploy on dev2 and validate~

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] sdk-scheme-adapter supports /bulkTransfers end-points and related functionality

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-standard-components/pull/62
- [ ] https://github.com/mojaloop/mojaloop-simulator/pull/49
- [ ] https://github.com/mojaloop/sdk-scheme-adapter/pull/159

## **Follow-up**:
- #1386

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by oderayi** [comment]
Initial Design for Bulk Transfers Support in SDK Scheme Adapter and Mojaloop Simulator
=======================================================================================
Inbound API (sdk-scheme-adapter)
---------------------------------
The inbound API of the scheme adapter accepts and processes requests from the Switch to facilitate transfers and other operations between the Switch and the DFSP backend.
The following endpoints will be implemented to support bulk transfers:
- GET /bulkTransfers/{ID}
    Accepts and processes requests to retrieve previously created bulk transfer or requested bulk transfer information. 
- POST /bulkTransfers
    Accepts and processes requests for creating new bulk transfers.
- PUT /bulkTransfers/{ID}
    Accepts and processess callbacks from ealier requested bulk transfers creation or information request.
- PUT /bulkTransfers/{ID}/error
    Accepts and processes error callbacks from ealier requested bulk transfers creation or information.

Outbound API (sdk-scheme-adapter)
---------------------------------
The outbound API of the scheme adapter accepts and processes requests from the DFSP backend system to the Switch to facilitate transfers and other operations.
The following endpoints will be implemented to support bulk transfers:
- POST /bulkTransfers
    Initiates a bulk transfer to payees' DFSP through the Switch. This will comprise of all the three stages involved in a transfer (namely parties lookup, quoting, and actual transfer).
    This endpoint will support both synchronous and asynchronous modes to allow pausing and resuming of transfers at each stages determined by the value of respective environment variables (i.e AUTO_ACCEPT_PARTIES, AUTO_ACCEPT_QUOTES), and to allow DFSPs freedom to implement against the sdk-scheme-adapter in either mode.    
- PUT /bulkTransfers/{ID}
    Continues a bulk transfer previously paused at the party lookup or quoting stage.
- GET /bulkTransfers/{ID}
    Retireves information for a specific bulk transfer.

DFSP backend (Mojaloop Simulator)
---------------------------------
These are inbound requests from the sdk-scheme-adapter to the DFSP backend that needs to be implemented at the DFSP backend to support bulk transfers.
The following endpoints will be implemented:
- POST /bulkTransfers
    Accepts and processes incoming request to transfer funds between an external account and internal accounts.

General Considerations/Note
----------------------------------------
- Inbound requests are cached if the scheme adapter is running in test mode, determined by an environment variable.
- Outbound request handlers set up subscriber on a pubsub queue topic per request (where applicable) to handle callback from peer.
- Subscriptions are carefully unsubscribed to prevent memory leaks.
- Switch-bound requests are implemented in the sdk-standard-components. New requests for the switch should be implemented there for easy maintainance.
