### ISSUE TITLE
Release validation of package.json versioning

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1326]
## **Goal**:
As a `OSS DevOp` I want to `ensure that a versioned release is validated against the package.json` so that `versions are in sync`

**Tasks**:
- [ ] Setup new CI pipeline to validate release tag against the version in package.json
- Roll out change to all repositories
     - [ ] ml-api-adapter
     - [ ] central-ledger
     - [ ] central-services-shared
     - [ ] central-services-database
     - [ ] central-services-logger
     - [ ] central-services-stream
     - [ ] central-services-health
     - [ ] central-services-metrics
     - [ ] account-lookup-service
     - [ ] quoting-service
     - [ ] event-stream-processor
     - [ ] central-event-processor
     - [ ] financial-portial-ui
     - [ ] financial-portial-lib
     - [ ] financial-portial-backend
     - [ ] settlement-management
     - [ ] settlement-operator
     - [ ] central-settlement
     - [ ] transaction-request-service
     - [ ] sdk-schema-adapter
     - [ ] sdk-stadard-components
     - [ ] mojaloop-simulator
     - [ ] simulator (legacy)
     - [ ] event-sdk
     - [ ] event-sidecar
     - [ ] als-oracle-pathfinder
     - [ ] oracle-sdk
     - [ ] ml-number
     - [ ] <add more here>

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] Mojaloop tagged releases will validate that the version matches the package.json to ensure they are in sync

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
