### ISSUE TITLE
Define User flow/experience for Hub Operator when executing a zero-downtime-deployment

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1329]
## **Goal**:
As a `hub operator` I want a `series of simple steps` to run a `zero downtime deployment of a mojaloop upgrade` so I can `easily understand and execute these steps`

This is really the desired end-user experience for the ZDD proof of concept.

The output of this task will likely be a playbook in `.md` format, with a bunch of helm commands that will do the upgrade. The tricky part is considering the potential need to drain mojaloop transfers or other operations on the hub operator side. 

This playbook should also contain details around DFSP api versions, and manual todos in place of some assumptions (such as "tell DFSPs to upgrade to the latest api version", "switch over the load balancer for the API gateway")

**Tasks**:
- [ ] research helm 3 commands for the upgrade (this will influence our decisions around helm deployment approaches)
  - [ ] q: is helm3 ok? Or should this be compatible with helm2 as well (or just helm2)?
- [ ] Draft of the zero downtime deployment playbook somewhere (where? Maybe a new repo? Maybe an existing one?)

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
