### ISSUE TITLE
Unsupported http method for all resources - Fix http status code to 405

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1331]
**Summary**:
When calling unsupported http method across services, the http status code of 404 is used.

eg.  DELETE/POST /authorizations - this can give 405 status code as it is unsupported HTTP method

**Severity**:
Low

**Priority**:
Medium

**Expected Behavior**
http status of 405 - unsupported HTTP method for the request was used

**Steps to Reproduce**
```
 curl --location --request DELETE 'http://dev1-transaction-requests-service.mojaloop.live/authorizations/5851581a-5e75-4622-9e2e-38bd9b48c166?authenticationType=OTP&retriesLeft=2&amount=102&currency=USD' \
--header 'Accept: application/vnd.interoperability.transactionRequests+json;version=1' \
--header 'Content-Type: application/vnd.interoperability.transactionRequests+json;version=1.0' \
--header 'Date: Wed, 06 May 2020 09:09:14 GMT' \
--header 'fspiop-source: payerfsp' \
--header 'fspiop-destination: payeefsp' \
--header 'fspiop-signature: {"signature":"iU4GBXSfY8twZMj1zXX1CTe3LDO8Zvgui53icrriBxCUF_wltQmnjgWLWI4ZUEueVeOeTbDPBZazpBWYvBYpl5WJSUoXi14nVlangcsmu2vYkQUPmHtjOW-yb2ng6_aPfwd7oHLWrWzcsjTF-S4dW7GZRPHEbY_qCOhEwmmMOnE1FWF1OLvP0dM0r4y7FlnrZNhmuVIFhk_pMbEC44rtQmMFv4pm4EVGqmIm3eyXz0GkX8q_O1kGBoyIeV_P6RRcZ0nL6YUVMhPFSLJo6CIhL2zPm54Qdl2nVzDFWn_shVyV0Cl5vpcMJxJ--O_Zcbmpv6lxqDdygTC782Ob3CNMvg\",\"protectedHeader\":\"eyJhbGciOiJSUzI1NiIsIkZTUElPUC1VUkkiOiIvdHJhbnNmZXJzIiwiRlNQSU9QLUhUVFAtTWV0aG9kIjoiUE9TVCIsIkZTUElPUC1Tb3VyY2UiOiJPTUwiLCJGU1BJT1AtRGVzdGluYXRpb24iOiJNVE5Nb2JpbGVNb25leSIsIkRhdGUiOiIifQ"}' \
--header 'fspiop-uri: /transactionRequests' \
--header 'fspiop-http-method: DELETE'
```

**Specifications**
  - Component (if known):
  - Version: Helm 9.2.0
  - Platform: 
  - Subsystem: authorizations (across services)
  - Type of testing: Manual
  - Bug found/raised by:@amarmodus

**Tasks**:
- [x] Make changes to SDK project and create release (add new 405 error)
- [x] Make changes to error handler project and create release (implement error code)
- [x] Update dependencies for central-event-processor
- [x] Update dependencies for account-lookup-service
- [x] Update dependencies or central-ledger (was already upgraded)
- [x] Update dependencies for ml-api-adapter
- [x] Update dependencies or quoting-service
- [x] Update dependencies for simulator (found bug https://github.com/mojaloop/project/issues/1415)
- [x] Update dependencies for transaction-requests-service
- [x] Update dependencies for central-settlement
- [x] Update dependencies or bulk-api-adapter

**PRs**:
- [x] https://github.com/mojaloop/sdk-standard-components/pull/63 - SDK project
- [x] https://github.com/mojaloop/central-services-error-handling/pull/145 - error handler
- [x] https://github.com/mojaloop/central-event-processor/pull/203 - central-event-processor
- [x] https://github.com/mojaloop/account-lookup-service/pull/342 - account-lookup-service
- [x] https://github.com/mojaloop/central-ledger/pull/729 - central ledger (closed, not needed)
- [x] https://github.com/mojaloop/ml-api-adapter/pull/430 - ml-api-adapter
- [x] https://github.com/mojaloop/quoting-service/pull/218 - quoting-service
- [x] https://github.com/mojaloop/simulator/pull/190 - simulator
- [x] https://github.com/mojaloop/transaction-requests-service/pull/38 - transaction-requests-service
- [x] https://github.com/mojaloop/central-settlement/pull/302 - central-settlement
- [x] https://github.com/mojaloop/bulk-api-adapter/pull/26 - bulk-api-adapter

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry** [comment]
Thanks Amar. I'm marking this as a feature request / story and not as a bug, since this wasn't ever implemented / prioritized..

**Comment by aenns** [comment]
@elnyry @rmothilal @mdebarros
Talked to Rajiv about this, and we're thinking to make an extension to handle it, similar to what's done in this 404 handler: https://hapi.dev/tutorials/routing/?lang=en_US#-404-handling
Let's discuss this asap.
