### ISSUE TITLE
Enable configuration to support on-us transactions

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1332]
## **Goal**:
As a Scheme
I want to _have capability to configure a Mojaloop deployment_
so that _I can enable or disable on-us transfers_

**Tasks**:
- [x] Refactor implementation to support on-us transfers
- [x] Helm changes needed
- [x] QA - unit, integration tests
- [x] Change ML API adapter to not to send payee confirmation notification incase of from fsp and to fsp are same
- [x] Add put quotes and put quotes error endpoints to payee in legacy simulator implementation
- [x] QA - postman tests
- [x] Release repositories after changes approved and merged

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] Configuration options are made available using which "on-us" transactions can be enabled (or disabled)

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/738
- [x] https://github.com/mojaloop/helm/pull/332
- [x] https://github.com/mojaloop/ml-api-adapter/pull/442
- [x] https://github.com/mojaloop/simulator/pull/193
- [x] https://github.com/mojaloop/postman/pull/118
## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
To enable on-us transfers, add a property **_"enable_on_us_transfers: false"_** in the helm values file at centralledger-handler-transfer-prepare->config
