### ISSUE TITLE
Feature to support final notification to a Payee FSP, a PATCH call

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1334]
## **Goal**:
As a Payee FSP
I want to _receive a notification of finalization of a transfer_
so that _I can use it to make informed decisions on down stream release of funds / payments_

As a Hub
I want the _option to notify Payee of a finalized transfer_
so that _the Payee FSP has more information regarding the final status of a transfer at the Hub_

**Note**:
- Issue from mojaloop-specification here: https://github.com/mojaloop/mojaloop-specification/issues/29
- Issue to access version v1.1 of the API Definition and Swagger: https://github.com/mojaloop/mojaloop-specification/issues/52#issuecomment-618636582

**Tasks**:
- [x] Review API Spec and Swagger v1.1 for this change
- [x] Design and update sequence diagrams
- [ ] ~Present designs to the DA (though already reviewed, discussed and approved)~ created follow up story #1462 
- [x] Implementation to support the PATCH notification and use the new Swagger v1.1
  - [x] ml-api-adapter
    - [x] PUT transfer route to support request for 
    - [x] notif handler
  - [x] central-services-shared
  - [x] central-ledger
    - [x] fulfil handler
    - [x] position handler
  - [x] simulator to accept PATCH
  - [ ] ~sdk-standard-components~  created follow up story #1462 
  - [ ] ~sdk-scheme-adapter (update swagger)~  created follow up story #1462 
  - [ ] ~mojaloop-simulator~  created follow up story #1462 
- [ ] ~Update all end-points needed to use v1.1 in the versions (Accept, content-type)~
- [x] register header validation plugin into ml-api-adapter
- [x] Unit, integration tests
- [x] Add special fsp in legacy simulator to send RESERVE and accept a PATCH
- [x] Update postman collections, etc for QA

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [ ] ~Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.~
- [x] A notification to a Payee FSP, via a PATCH call on finalization of a transfer can be made if requested by the Payee FSP

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-shared/pull/232
- [x] https://github.com/mojaloop/central-ledger/pull/751
- [x] https://github.com/mojaloop/ml-api-adapter/pull/444
- [x] https://github.com/mojaloop/simulator/pull/197
- [x] https://github.com/mojaloop/postman/pull/136
- [x] https://github.com/mojaloop/documentation/pull/230

## **Follow-up**:
- #1462 

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @elnyry

**Comment by elnyry-sam-k** [comment]
@vgenev latest Swagger here: https://github.com/mojaloop/mojaloop-specification/tree/master/documents/v1.1-document-set

**Comment by elnyry-sam-k** [comment]
Thanks @vgenev
