### ISSUE TITLE
Handling 'ABORTED' on a PUT /transfers/{ID} (Fulfil step)

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1335]
## **Goal**:
As a Switch / Hub
I want to _only handle fulfil requests from Payee FSPs that either use error callbacks for errors or COMMITTED state in case of PUT /transfers/{ID} calls
so that _I can conform to the v1.1 Specification_

**Note**: Issue on mojaloop-specification for reference: https://github.com/mojaloop/mojaloop-specification/issues/47

**Tasks**:
- [x] Update sequence diagrams to reflect changes (create new set for v1.1 for changes)
- [x] Refactor Switch implementation to only support using error callbacks for rejections / errors on transfers and not 'ABORTED' state in Fulfil calls (PUT /transfers/{ID}\
- [x] automated tests
- [x] Update QA teams
- [x] Changes to postman collections correspondingly

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [ ] ~Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.~
- [x] Rejections by Payee FSPs can only be done via error callbacks on /error endpoints. Using 'ABORTED' state on PUT /transfer/{ID} calls will be Scheme errors to be addressed during testing / integration phases.

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/740
- [x] https://github.com/mojaloop/documentation/pull/228
- [ ] https://github.com/mojaloop/postman/pull/119

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @elnyry
