### ISSUE TITLE
PCI DSS - Responsibility Matrix, Gap Analysis & Standard Baselines - Requirement 5 : Vulnerability Management Program

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1349]
@godfreykutumela commented on [Fri May 08 2020](https://github.com/mojaloop/mojaloop/issues/287)

## **Goal**:
Create a responsibility matrix, perform a Gap Analysis ( As-Is and To be) for Requirement 5 : Vulnerability Management Program and provide a standard baseline report.

**Tasks**:
- [x] Create a template [ @godfreykutumela ]
- [x] Complete the responsibility matrix [ @godfreykutumela ]
- [x] Perform an assessment (As-Is) [ @godfreykutumela ]
- [x] Recommendations (To-Be) [ @godfreykutumela ]
- [x] Compile an overall report with a compliance baseline [ @godfreykutumela ]

**Acceptance Criteria**:

- [x] Responsibility Matrix
- [x] As-Is assessment report
- [x] To-be report with recommendations
- [ ] Completed compliance baseline report

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
Final draft for team review.
[Mojaloop PCI DSS Responsibility Matrix, Gap Analysis & Compliace Baseline Requirement 5 Report - July 2020 v1.0 Final.xlsx](https://github.com/mojaloop/project/files/4722267/Mojaloop.PCI.DSS.Responsibility.Matrix.Gap.Analysis.Compliace.Baseline.Requirement.5.Report.-.July.2020.v1.0.Final.xlsx)

**Comment by lewisdaly** [comment]
Thanks Godfrey, here's a few of my thoughts on the draft: 

1. The confidentiality notice is not appropriate here:
> Confidential – This document is intended only for the use of Mojaloop OSS Team and should not be distributed external third parties.

Everything we are doing here is open source and licensed under the Apache 2.0 license, so by definition is _not_ confidential. 

2. I'm not sure the term "Cloud provider" is appropriate since there are deployments of Mojaloop (and there is already one) that is self-hosted. Perhaps Infrastructure provider would be better.

3. I take it that we are firmly saying that anti-virus and anti-malware responsibilities lie between hub operators and insfrastructure providers. 

How about in cases case where Hub operators are deploying the Mojaloop open source docker images from the mojaloop helm deployment (let's call that vanilla mojaloop if you will)?

I'm mainly thinking around processes here (which we already have for dependency vulnerability scanning) to ensure the security of docker images? Does that fall under 5.4 in this spreadsheet? Or is that covered elsewhere?

**Comment by godfreykutumela** [comment]
Thanks @lewisdaly for the revview and feedback. My point by point response below:

1. Yes I will remove that confidential clause - it is just a security thing we are used to nothing meant to be restrict the distribution by virtue sharing it here it is already public.
2. I agree, Cloud Provider will be renamed to Infrastructure Provider which might be a private, hybrid or public cloud setup - I will add more explaination notes on this somewhere in the document.
3. Hub operator and Infrastructure provider might be spread across a number of partners or just one e.g. For Mowali - Hub Operator is Mowali and Infrastructure provider is Microsoft and for Tips they act as both Hub Operator and infrastructure provider. 

Where a vanila version of Mojaloop is deployed will be left for adoptor to decide.

In essence, adoptors can custom change this responbility matrix for the hub operator and infrastructure provider for themselves only but they can't change Mojaloop's responsibilities however can send us a feature request to build a specific capability which they think can be addressed at Mojaloop OSS level.

The scope of requirement 5 - Vulnerability management is only as related to infrastrucure and the dependancy scanning will be covered in requirement 6 which has a specfic focus on custom code development - See bellow insert:

(6.3.2 Review custom code prior to release to production or Hub Operators in order to identify any potential coding vulnerability (using either manual or automated processes) to include at least the following:
- Code changes are reviewed by individuals other than the originating code author, and by individuals knowledgeable about code-review techniques and secure coding practices.
- Code reviews ensure code is developed according to secure coding guidelines
- Appropriate corrections are implemented prior to release.
- Code-review results are reviewed and approved by management prior to release.

Note: This requirement for code reviews applies to all custom code (both internal and public-facing), as part of the system development life cycle. Code reviews can be conducted by knowledgeable internal personnel or third parties. Public-facing web applications are also subject to additional controls, to address ongoing threats and vulnerabilities after implementation, as defined at PCI DSS Requirement 6.6. )

**Comment by godfreykutumela** [comment]
Hi @lewisdaly - Regarding the last point on vulnerability management, it is actually divided into 2 requirements(infrastructure and application) and the inserted picture gives a qucik overview on the section and requirement arrangements. 

![PCI DSS Summary](https://user-images.githubusercontent.com/58056329/83734425-447ea880-a64f-11ea-8ae5-1a884e78a241.png)

**Comment by lewisdaly** [comment]
Thanks @godfreykutumela for clearing this up

**Comment by godfreykutumela** [comment]
Draft version for review and approval.
[Mojaloop PCI DSS Responsibility Matrix, Gap Analysis & Compliace Baseline Requirement 6 Report - July 2020 v1.0 Final.xlsx](https://github.com/mojaloop/project/files/4772134/Mojaloop.PCI.DSS.Responsibility.Matrix.Gap.Analysis.Compliace.Baseline.Requirement.6.Report.-.July.2020.v1.0.Final.xlsx)

**Comment by godfreykutumela** [comment]
Draft Version for review and approval.
[Mojaloop PCI DSS Responsibility Matrix, Gap Analysis & Compliace Baseline Requirement 5 Report - July 2020 v1.0 Final.xlsx](https://github.com/mojaloop/project/files/4772143/Mojaloop.PCI.DSS.Responsibility.Matrix.Gap.Analysis.Compliace.Baseline.Requirement.5.Report.-.July.2020.v1.0.Final.xlsx)

**Comment by lewisdaly** [comment]
Thanks @godfreykutumela , looking good!

**Comment by godfreykutumela** [comment]
Thanks once more for the input here @lewisdaly and I have changed it already in all the 12 sections of the standard.
