### ISSUE TITLE
Test POC for DB HA against requirements

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#135]
**Goal**:
Test POC for DB HA against requirements

**Tasks**:
- [x] Integrate external JMeter tests 
- [x] Re-Run tests with load and disable a random DB Node
- [x] Test Data Integrity and replication
- [x] Bring in a stopped node
- [x] Re-Test data integrity

**Acceptance Criteria**:
- [x] Determine baseline for mySQL Implementation
- [x] Document findings

**Dependencies**:
- [x] #75

**Comment by elnyry** [comment]
Done, performance tested as well and results shared
