### ISSUE TITLE
PCI DSS Responsibility Matrix, Gap Analysis & Standard Baseline for Requirement 3 : Protect Cardholder Data

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1351]
@godfreykutumela commented on [Thu May 07 2020](https://github.com/mojaloop/mojaloop/issues/285)

## **Goal**:
Create a responsibility matrix, perform a Gap Analysis ( As-Is and To be) for Requirement 3 : Protect Cardholder Data and provide a standard baseline.

**Tasks**:
- [ ] Create a template [ @godfreykutumela ]
- [ ] Complete the responsibility matrix [ @godfreykutumela ]
- [ ] Perform an assessment (As-Is) [ @godfreykutumela ]
- [ ] Recommendations (To-Be) [ @godfreykutumela ]
- [ ] Compile an overall report with a standard baseline [ @godfreykutumela ]

**Acceptance Criteria**:
- [ ] Responsibility Matrix
- [ ] As-Is assessment report
- [ ] To-be report with recommendations
- [ ] Completed standard baseline report

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
[Mojaloop PCI DSS Responsibility Matrix, Gap Analysis & Compliace Baseline Requirement 3 Report - July 2020 v1.0 Final.xlsx](https://github.com/mojaloop/project/files/4701837/Mojaloop.PCI.DSS.Responsibility.Matrix.Gap.Analysis.Compliace.Baseline.Requirement.3.Report.-.July.2020.v1.0.Final.xlsx)
