### ISSUE TITLE
PCI DSS - Responsibility Matrix, Gap Analysis & Standard Baseline - Requirement 2 : System passwords management

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1352]
@godfreykutumela commented on [Thu May 07 2020](https://github.com/mojaloop/mojaloop/issues/284)

## **Goal**:
Create a responsibility matrix, perform a Gap Analysis ( As-Is and To be) for Requirement 2 : Defaults for system passwords and provide a standard baseline.

**Tasks**:
- [x] Create a template [ @godfreykutumela ]
- [x] Complete the responsibility matrix [ @godfreykutumela ]
- [x] Perform an assessment (As-Is) [ @godfreykutumela ]
- [x] Recommendations (To-Be) [ @godfreykutumela ]
- [x] Compile an overall report with a standard baseline [ @godfreykutumela ]

**Acceptance Criteria**:
- [x] Responsibility Matrix
- [x] As-Is assessment report
- [x] To-be report with recommendations
- [x] Completed baseline report

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
Completed and will now move this story to QA.
[Mojaloop PCI DSS Responsibility Matrix, Gap Analysis & Compliace Requirement 2 Report - July 2020.xlsx](https://github.com/mojaloop/project/files/4668887/Mojaloop.PCI.DSS.Responsibility.Matrix.Gap.Analysis.Compliace.Requirement.2.Report.-.July.2020.xlsx)

**Comment by godfreykutumela** [comment]
Completed and move to QA for team review.
[Mojaloop PCI DSS Responsibility Matrix, Gap Analysis & Compliace Baseline Requirement 2 Report - July 2020 Final.xlsx](https://github.com/mojaloop/project/files/4668950/Mojaloop.PCI.DSS.Responsibility.Matrix.Gap.Analysis.Compliace.Baseline.Requirement.2.Report.-.July.2020.Final.xlsx)

**Comment by godfreykutumela** [comment]
Final Approved Version
[Mojaloop PCI DSS Responsibility Matrix, Gap Analysis & Compliace Baseline Requirement 2 Report - July 2020 Final.xlsx](https://github.com/mojaloop/project/files/4670365/Mojaloop.PCI.DSS.Responsibility.Matrix.Gap.Analysis.Compliace.Baseline.Requirement.2.Report.-.July.2020.Final.xlsx)
