### ISSUE TITLE
PCI DSS - Responsibility Matrix, Gap Analysis & Standard Baseline for Requirement 1 : Secure Network and Systems

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1353]
@godfreykutumela commented on [Thu May 07 2020](https://github.com/mojaloop/mojaloop/issues/283)

## **Goal**:
Create a responsibility matrix, perform a Gap Analysis ( As-Is and To be) for Requirement 1 : Secure Network and Systems and provide a standard baseline.

**Tasks**:
- [x] Create a template [ @godfreykutumela ]
- [x] Complete the responsibility matrix [ @godfreykutumela ]
- [x] Perform an assessment (As-Is) [ @godfreykutumela ]
- [x] Recommendations (To-Be) [ @godfreykutumela ]
- [x] Compile an overall report with a standard baseline [ @godfreykutumela ]

**Acceptance Criteria**:
- [x] Responsibility Matrix
- [ ] As-Is assessment report
- [x] To-be report with recommendations
- [x] Completed standard baseline report

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
[Mojaloop PCI DSS Responsibility Matrix, Gap Analysis & Compliace Baseline Requirement 1 Report - July 2020.xlsx](https://github.com/mojaloop/project/files/4657103/Mojaloop.PCI.DSS.Responsibility.Matrix.Gap.Analysis.Compliace.Baseline.Requirement.1.Report.-.July.2020.xlsx)

**Comment by godfreykutumela** [comment]
Completed and now in QA/Review phase.

**Comment by godfreykutumela** [comment]
Final version after review process
[Mojaloop PCI DSS Responsibility Matrix, Gap Analysis & Compliace Baseline Requirement 1 Report - July 2020.xlsx](https://github.com/mojaloop/project/files/4659833/Mojaloop.PCI.DSS.Responsibility.Matrix.Gap.Analysis.Compliace.Baseline.Requirement.1.Report.-.July.2020.xlsx)

**Comment by godfreykutumela** [comment]
Final Version
[Mojaloop PCI DSS Responsibility Matrix, Gap Analysis & Compliace Baseline Requirement 1 Report - July 2020.xlsx](https://github.com/mojaloop/project/files/4668120/Mojaloop.PCI.DSS.Responsibility.Matrix.Gap.Analysis.Compliace.Baseline.Requirement.1.Report.-.July.2020.xlsx)

**Comment by godfreykutumela** [comment]
Final Approved Version
[Mojaloop PCI DSS Responsibility Matrix, Gap Analysis & Compliace Baseline Requirement 1 Report - July 2020 Final.xlsx](https://github.com/mojaloop/project/files/4670357/Mojaloop.PCI.DSS.Responsibility.Matrix.Gap.Analysis.Compliace.Baseline.Requirement.1.Report.-.July.2020.Final.xlsx)
