### ISSUE TITLE
Cryptographic Processing Module(CPM) - High Level Design

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1355]
## **Goal**:
Align with HSM integration work stream to ensure that implementation is done in line with the adopted HSM integration architecture model. The PI 10 focus points for the HSM integration stream are: 1. Documentation and analysis of existing use cases 2. Provide high level design 3. Select HSM vendors that will support us in the integration efforts.

**Tasks**:
- [ ] Document use cases [ @Max Coil].
- [ ] Provide a High level Design [ @Max Coil].
- [ ] Evaluate HSM Vendor\s and a select one or two to start with [ @Max Coil].

**Acceptance Criteria**:
- [ ] Documented use cases [ @Max Coil].
- [ ] High level Design [ @Max Coil].
- [ ] Appointed HSM Vendor\s [ @Max Coil].

## **Accountability**:
- Owner: @Max
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
Hi All, Please find attached draft Crytographic Processing Module(CPM)
[Mojaloop Crytographic Processing Module - 7 July 2020 v1.0.docx](https://github.com/mojaloop/project/files/4884141/Mojaloop.Crytographic.Processing.Module.-.7.July.2020.v1.0.docx)
 High Level Design Document for review ahead of today's meeting to present it in detail. Chat to you all later today.

**Comment by godfreykutumela** [comment]
Key notes from the review session on 7 July 2020:

- IKMS support will be limited to KMIP and PKCS11

- Adaptors should be light weight and easy to implement

- Sequeence diagrams will be part of the low level design and also on a use case by use case flow basis

- Very important, the scope of this design does not include DFSP's just for the Mojaloop Core for now.

**Comment by godfreykutumela** [comment]
PI 11 backlog

**Comment by godfreykutumela** [comment]
A clarification meeting was held last friday to address all the points raised by members of the DA and below are our final agreement and conclusion:

Articulation of Risks - We have agreed that all risk associated with the introduction of a CPM be clearly articulated to the hub operator to make their own choices. The current documentation should be updated as per this agreement.

Costing - The envisaged design is flexible enough to enable a low cost solution to be adopted by hub operators and their participants.

Detailed Implementation Plans and Roadmap - This is not covered in the current scope of the HLD and will part of the LLD's (PI 12) and Implementation Phase - POC in PI 13.

Avoiding Breaking Changes - The Module will be delivered as a microservice and will be part of the core switch services for handling all in-switch cryptographic funcations however hub operators may elect not use it on their own accord thereby accepting all the risk associated with not using secured cryptographic environment provided for from OSS core architecture.

Next Step - To approve the HLD design as-is and proceed with the LLD's.
