### ISSUE TITLE
Identify and categorize PII data (At Rest and In-Transit)

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1356]
## **Goal**:
Perform an assessment to identify all PII data and data sources within Mojaloop for both data at rest and data in-transit as per NIST Guideline for protecting PII Data (https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-122.pdf)

**Tasks**:
- [x] Identity PII data  [ @rasputtintin  ]
- [x] Identity PII data sources  [ @rasputtintin  ]
- [x] Document the report [ @rasputtintin ]

**Acceptance Criteria**:
- [x] Documented list of all PII data and sources within Mojaloop

## **Accountability**:
- Owner: @rasputtintin 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
@rasputtintin Please update this with the reports so that we can move it to review today's still
