### ISSUE TITLE
Data Protection  - Secure Logging Standard and Guidelines

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1358]
## **Goal**:
The objective is to look at compliance to best practice standards with regards to audit logging within a Mojaloop implementation. We shall investigate the following:

1. Identify sources of audit logs
2. Document PII data according to GDPR and investigate PII data in Mojaloop logs
3. Document security logging standard
4. Make recommendations for audit logging configurations

**Tasks**:
- [x] Extract audit logs from Mojaloop services and analyze them for audit logging adequacy [ @rasputtintin  ]
- [x] Explore Data Protection Standard for Data at Rest [ @rasputtintin ]
- [ ] Explore Data Protection Standard for Data in Motion [ @rasputtintin ]
- [x] Identify and Document recommendations on audit logging in Mojaloop [ @rasputtintin ]
- [x] Document logging and forensic data controls [ @rasputtintin ]

**Acceptance Criteria**:
- [x] List of audit log sources
- [x] List and description of existing controls per area
- [x] Gaps identified and documented recommendations

**Dependencies**:
- Completion of Identification PII data 

## **Accountability**:
- Owner: @rasputtintin 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
PI 11 Backlog

**Comment by rasputtintin** [comment]
Task 1 - Identified the following components that are involved in communication between the hub and DFSPs based on the diagram contained here - [https://docs.mojaloop.io/documentation/mojaloop-technical-overview/overview/components-PI8.html] :
- WSO2 API Gateway that receives API requests for processing and performs callbacks
- HAProxy  that acts as the ingress gateway. Traffic is encrypted as it comes here.
- Kafka Service - Streaming service that receives transaction requests for processing
- Kubernetes Cluster that manages running containers with Mojaloop applications
- Service related databases - These are the various databases supporting critical applications in Mojaloop

**Comment by rasputtintin** [comment]
Task 2 - Review existing controls within Kafka and Kubernetes clusteres relating to data in motion and document gaps:
- Mojaloop uses PII data as part of its switch processing from the context of GDPR
- Identified that there exists basic controls that are deployed as part of standard Kubernetes and Kafka deployment. 
- There is no authentication for readers and writers into Kafka.
- There are basic control restrictions for Zookeeper which is the configuration manager for Kafka
- Kafka streams receive information in plain text
- There is no audit logging for Kafka and Kubernetes enabled. This requires a policy to be configured and activated.

**Comment by rasputtintin** [comment]
Recommendations and Reporting (report attached)

Enforce the following controls within the Kafka streams and between the API gateway and Kafka:
- TLS encryption for all data in and out
- Authorization using ACLs for producers and consumers
- Configure quotas to throttle traffic
- Review swagger definition and highlight GDPR centric data elements used for processing to help Mojaloop implementers remain compliant
- Incorporate data protection centric monitoring controls in Mojaloop for data in transit i.e. alerts if data integrity issues are identified.
- Restrict access to Zookeeper using network access controls
- Explore Service mesh design with Kubernetes and Kafka which will enforce security and monitiring controls.

[Data Protection - Data in Motion Report.docx](https://github.com/mojaloop/project/files/5183110/Data.Protection.-.Data.in.Motion.Report.docx)

**Comment by godfreykutumela** [comment]
Thanks @rasputtintin I moved the story to final review.

**Comment by rasputtintin** [comment]
Made minor updates to document to add details of importance of Audit logging to the Mojaloop switch implementation:

Importance of Audit Logs
Audit logging provides a historical account of all activities done by actors within a Mojaloop ecosystem. It will help Mojaloop implementations in the following ways:
1.	Threat Detection Analytics – Through audit logs it is possible for Mojaloop switch operators to detect possible anomalies and identify malicious actions and trigger appropriate responses. This will go a long way in mitigating against possible fraud at DFSP and switch level.
2.	Customer Forensics – In cases of queries from DFSPs, audit logs can assist give a forensic breakdown of transaction details as well as actions by authorized switch actors.
3.	Compliance – Compliance standards such as GDPR have requirements to extract “all” customer data and also “delete” all customer data. For this to be possible, the audit data may also need to be extracted and preserved/deleted as appropriate. Audit logs are a critical requirement in most global best practice standards and regulatory frameworks such as PCI-DSS and GDPR.

[OSS.Audit.logging.Standard v1.1.docx](https://github.com/mojaloop/project/files/5281999/OSS.Audit.logging.Standard.v1.1.docx)
