### ISSUE TITLE
Data Protection - Kafka/Zookeeper Security Standard and Guideline

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1359]
The objective is to address GDPR data protection requirements as per defined scope by first assessing what has been done, what can be improved and identifying gaps to address specific to data in rest (Stored data).

**Tasks**:
- [x] Identify all areas of data at rest within the Mojaloop Switch (Intra) and between Mojaloop switch and participant  [ @rasputtintin  ]
- [x] Review all existing controls per area of data at rest [ @rasputtintin ]
- [x] Identify and Document gaps [ @rasputtintin ]

**Acceptance Criteria**:
- [x] List of area for data at rest
- [x] List and description of existing controls per area
- [x] Gaps identified and documented
- [x] Consolidate PII data Classification findings

**Dependencies**:
- Completion of Identification PII data 

## **Accountability**:
- Owner: @rasputtintin 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
PI 11 Backlog

**Comment by godfreykutumela** [comment]
[Kafka and Zookeeper Security - 24 August 2020 v1.docx](https://github.com/mojaloop/project/files/5149400/Kafka.and.Zookeeper.Security.-.24.August.2020.v1.docx)

Kafka and Zookeeper Security Standard - Risk assessment and recommendations

**Comment by godfreykutumela** [comment]
@rasputtintin Please review so that @pedrosousabarreto can do a final review on this.

**Comment by rasputtintin** [comment]
Completed consolidating PII Data Classification findings as attached.
[Mojaloop Data Classification.docx](https://github.com/mojaloop/project/files/5170359/Mojaloop.Data.Classification.docx)

**Comment by rasputtintin** [comment]
> @rasputtintin Please review so that @pedrosousabarreto can do a final review on this.

@godfreykutumela document reviewed and no changes proposed.

**Comment by godfreykutumela** [comment]
@rasputtintin this is a wrong story for the content

**Comment by rasputtintin** [comment]
> @rasputtintin this is a wrong story for the content

Noted. I have published to correct story.

**Comment by rasputtintin** [comment]
Hi @godfreykutumela I did the review and the report is in order. I have added as part of next steps the need to investigate a "service mesh" design for Kubernetes that describes how to configure Kafka Streams and associated Kubernetes clusters with security and operational efficiencies therein.

> [Kafka and Zookeeper Security - 24 August 2020 v1.docx](https://github.com/mojaloop/project/files/5149400/Kafka.and.Zookeeper.Security.-.24.August.2020.v1.docx)
> 
> Kafka and Zookeeper Security Standard - Risk assessment and recommendations

[Kafka.and.Zookeeper.Security.-.24.August.2020.v1.1.docx](https://github.com/mojaloop/project/files/5181513/Kafka.and.Zookeeper.Security.-.24.August.2020.v1.1.docx)

**Comment by godfreykutumela** [comment]
Perfect, thanks @rasputtintin. We will now await @pedrosousabarreto for a final review within this sprint thereafter move the story to closed.
