### ISSUE TITLE
Draft presentation to help with demo and discussion of topics

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#136]
**Goal**:
As a stake-holder and team member, I would like to draft a presentation slide deck to help with demos during the on-site meetings as well as help with talking points for discussions and planning for PI-2

**Tasks**:
- [ ] Draft presentation with place holders for demos, talking points for major topics to help with discussion and planning for PI-2
- [ ] Align with agenda, get it reviewed by various stake-holders

**Acceptance Criteria**:
- [ ] Presentation prepared and initial reviews done (aligns with Agenda)

**Dependencies**:
- [ ] Agenda needs to be finalized
- [ ] Reviewed by various stake-holders
