### ISSUE TITLE
Establish Data Protection Standards for Data at Rest 

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1360]
## **Goal**:
To understand architectural controls around PII data at rest as per identified areas of data at rest (e.g Kafka Cluster, MongoDB, MySQL etc...) and provide a data protection improvement plan for all data rest areas within the Mojaloop.

**Tasks**:
- [ ] Identify and document architectural controls per area of data at rest( e.g Kafka Cluster, MongoDB, MySQL etc...[ @rasputtintin ]
- [ ] Document Improvement Plan per area. [ @rasputtintin ]

**Acceptance Criteria**:
- [ ] Documented Architectural Controls per area of data at rest( e.g Kafka Cluster, MongoDB, MySQL etc.).
- [ ] Document an improvement plan for data protection per areas of data at rest.

**Dependencies**:
- Identification of PII data.
- Review of all existing PII data protection controls.

## **Accountability**:
- Owner: @rasputtintin 
- QA/Review: @rasputtintin

**Comment by godfreykutumela** [comment]
Duplicate story
