### ISSUE TITLE
Log & Forensic Data Controls : Review and Improvement

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1362]
## **Goal**:
Review protection controls for log and forensic data, identify gaps and make improvement recommendations.

**Tasks**:
- [x] Identify all areas of log and forensic data [ @rasputtintin  ]
- [x] Review existing controls per area [ @rasputtintin ]
- [x] Identify Gaps [ @rasputtintin ]
- [x] Document recommendations and improvement plan

**Acceptance Criteria**:
- [x] List and description of all areas that touches log and forensic data
- [x] List and description of existing controls
- [x] List and description of gaps identified
- [x] List and description of Improvement recommendations

## **Accountability**:
- Owner: @rasputtintin 
- QA/Review: @rasputtintin

**Comment by rasputtintin** [comment]
Areas of Log and forensic data in Mojaloop:

1. All running services log to EFK which is part of Mojaloop deployment
2. Default log level is INFO

**Comment by godfreykutumela** [comment]
@rasputtintin Please update this with the reports so that we can move it to review today's still
