### ISSUE TITLE
Testing Toolkit - Verifying condition and fulfilment

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1364]
## **Goal**:
As a _DFSP / Switch_
I want _the testing toolkit to verify the condition and fulfilment based on the ilpPacket_
so that _I can confirm the validity of these items_

Note: This option should be configurable to allow individual transfer requests to be made for QA/testing purposes

**Tasks**:
- [x] Implementation on backend to verify the condition and fulfilment
- [x] Implementation on backend to validate the transfer request content against the decoded IlpPacket
- [x] Configurable options in the front-end (ILP Packet verfication, condition verification and ILP secret)
- [x] Move the ILP decoding and transfer validation functions to sdk-standard-components library for reusability
- [x] Change the logic around quotes and transfer association
- [x] Unit tests
- [x] Add test coverage checking in circle CI

**Acceptance Criteria**:
- [x] The conditions and fulfilment in quotes / transfer calls can be verified
- [x] Option to toggle this feature is provided in the front-end

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/23
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/51

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
https://github.com/mojaloop/project/issues/1258
