### ISSUE TITLE
Enums caching should be refactored to register as a cache.js independent client [Enhancements to #602]

### ISSUE THREAD

**Issue by yosheeck** [mojaloop/project#1366]
## **Goal**:
The current enums caching should be refactored to register as a cache.js independent client, instead of being hard-embedded into cache.js structure (this is the remains of PoC for #602)

**Tasks**:
- [x] Refactor implementation
- [x] Update tests

**Acceptance Criteria**:
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/713

## **Accountability**:
- Owner: @yosheeck 
- QA/Review: @mdebarros
