### ISSUE TITLE
Cache participant endpoints in central-ledger [Enhancements to #602]

### ISSUE THREAD

**Issue by yosheeck** [mojaloop/project#1367]
## **Goal**:
Cache participant endpoints should be cached with the same mechanism (cache.js) as participants, participantCurrency and participantLimit.

**Tasks**:
- [ ] Implement caching for participant endpoints lists (e.g. callers of ParticipantFacade.getEndpoint() and ParticipantFacade.getAllEndpoints())
- [ ] Update tests

**Acceptance Criteria**:
- [ ] Implemented cache is part of cache.js client list, so it can be invalidated "centrally"
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Accountability**:
- Owner: @yosheeck 
- QA/Review: @mdebarros

**Comment by mdebarros** [comment]
Does not apply anymore.
