### ISSUE TITLE
API Schema Validation PoC Part 2

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#1368]
## **Goal**:
As a developer i want to create a standardised way to validate our APIs against the Swagger document

**Note**:
Issue continues from https://github.com/mojaloop/project/issues/1295

**Tasks**:
- [x] Implement openapi-backend library
  - [x] ~Investigate the way openapi-backend works~
  - [x] ~Investigate AJV schema validator~
  - [x] ~Build custom OpenAPIBackendValidator~
  - [x] ~Add support for events~
  - [x] Add support for error library
  - [ ] ~Add support for Hapi-Swagger~ moved to new story https://github.com/mojaloop/project/issues/1380
  - [x] Added custom validator to existing library
  - [x] transaction-requests-service - remove dependency on Hapi-Open-API and add routes
  - [x] Create PoC of Transactions-requests-service using updated library

**To be moved to new story**: Moved to #1396 
  - quoting-service - remove dependency on Hapi-Open-API and add routes
  - account-lookup-service - remove dependency on Hapi-Open-API and add routes
  - ml-api-adapter - Update to use ml-schema-validator library
  - legacy simulator - Update to use ml-schema-validator library
  - Review if any other services need to be updated

**Acceptance Criteria**:
- [x] Unit Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-shared/pull/221
- [x] https://github.com/mojaloop/central-services-error-handling/pull/140
- [ ] https://github.com/mojaloop/transaction-requests-service/pull/37

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rmothilal
- QA/Review: @rmothilal
