### ISSUE TITLE
Testing Toolkit - Test case collections for Hub and DFSP

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1369]
## **Goal**:
As a Hub operator
I want a separate test case collection for Hubs
so that I can use it to test my Hub implementation with testing toolkit.

As an FSP
I want a separate test case collection for FSPs
so that I can use it to test my implementation with testing toolkit.

**Tasks**:
- [x] Streamline the existing DFSP collection and maintain proper naming (Add tests regarding JWS and ILP packet if needed)
- [x] Create a test case collection for Hub implementation like postman golden path collection
- [x] Review with QA team
- [x] Address if there are any gaps
- [x] Create a follow up story if any other requirements to improve the whole functionality

**Gaps**:
- [x] Multiple endpoints support @vijayg10
- [x] Custom headers in test case editor @vijayg10
- [x] Raw JSON editor for headers in test case editor @vijayg10
- [x] Import CURL command in test case editor @vijayg10
- [x] Include atob function for assertions @vijayg10
- [x] Add an option to send a single test case @vijayg10
- [x] scripting capability - https://github.com/mojaloop/project/issues/1377 @vijayg10 @georgi-logodazhki  
- [x] include put requests for sync apis @vijayg10 
- [x] Add duplicate assertion button

**Acceptance Criteria**:
- [x] DFSP implementation can be tested with testing toolkit including security features
- [x] Hub implementation can be tested with testing toolkit in all aspects
- [x] Confirmation from QA team to use testing toolkit for testing Switch implementation
- [x] Observations are recorded and a follow up story is created

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/53

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @georgi-logodazhki 
- QA/Review: @vijayg10 @amarmodus
