### ISSUE TITLE
Create CSV comparison script

### ISSUE THREAD

**Issue by georgi-sgbg** [mojaloop/project#137]
**Goal**:
As a developer, I would like to easily compare 2 different CSV (comma separated values) files using a Node script
**Tasks**:
- [ ] Create a function to load a single line into an array of values using delimiter, text qualifier and escape characters
- [ ] Create a config object within the script with description of all available options
- [ ] Create a function to load source and destination files into memory
- [ ] Perform the preconfigured comparison tasks
- [ ] Create a function to output the desired file(s) as per config
- [ ] Make the script accessible by the command line and print appropriate messages during operation

**Acceptance Criteria**:
- [ ] Output file with matches into destination as per config
- [ ] Output file with unmatched records from source
- [ ] Output file with unmatched records from destination
