### ISSUE TITLE
Update core team 'dev' environments to use mojaloop-simulator instances 

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1370]
## **Goal**:
As an FSP / Switch
I want to _use postman collections and Helm release versions that have been tested by the core team on a similar environment_
so that _I can upgrade to those releases and use the postman scripts with confidence_ as they've been validated by the core team

**Tasks**:
- [x] Update dev2 environment to use mojaloop-simulator instances as FSPs
  - [x] Update the scripts to skip JWS signature validation tests with if loop ( with env variable set for whether WSO2 deployed or not, print the message ) 
- [x] Test Golden path mojaloop-simulators collection on dev2
- [x] Identify and raise issues as needed to complete the collection
   - [x] Raised https://github.com/mojaloop/project/issues/1404 - accept header issue
   - [x] Raised https://github.com/mojaloop/project/issues/1408 - missing uri header 
- [x] Test Golden path mojaloop-simulators collection on dev2
~~- [ ] Update daily test cron job to use mojaloop-simulators collection as well~~

**Acceptance Criteria**:
- [x] AWS envt dev2 used by the core team is updated to use mojaloop-simulator instances as FSPs
- [x] Golden path mojaloop-simulators collection (postman repo) is validated on dev2 environment and runs 100%
~~- [ ] AWS envt dev1 used by the core team is updated to use mojaloop-simulator instances as FSPs~~
~~- [ ] Golden path mojaloop-simulators collection (postman repo) is validated on dev1 environment and runs 100%~~
~~- [ ] Cron job that runs on dev1 envt is updated to use Golden path mojaloop-simulators collection and runs at 100% (ensure it runs once with and without notification to meet this criteria)~~

## **Pull Requests**:
- [x] https://github.com/mojaloop/postman/pull/113
- [x] https://github.com/mojaloop/postman/pull/115

## **Follow-up**:
- https://github.com/mojaloop/project/issues/1409

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by amarmodus** [comment]
1st after merge and changes : 

<img width="1270" alt="Screenshot 2020-05-27 11 52 55" src="https://user-images.githubusercontent.com/53434415/83011391-b3398180-a011-11ea-8789-a9b5bcbb0875.png">

settlement management - test stops because of these tests.
<img width="1330" alt="Screenshot 2020-05-26 22 08 53" src="https://user-images.githubusercontent.com/53434415/83011514-e8de6a80-a011-11ea-92fe-75bcde541ab0.png">

**Comment by amarmodus** [comment]
After PR 115 update 

* Commented out all current failure test cases for further analysis - 'CHECK' added
* removed settlement folder which did not run. - will be added in another task.

<img width="1279" alt="Screenshot 2020-05-28 14 50 26" src="https://user-images.githubusercontent.com/53434415/83150202-ea339400-a0f2-11ea-9b2b-30d0412fb561.png">
