### ISSUE TITLE
Helm v10.1.0: Updates to helm, Supporting QA, Fixes, Releases - 2

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1371]
## **Goal**:
As an ML OSS Code base maintainer
I want to _validate and make a Helm release in PI-10 (Sprint 10.1) that is successfully validated by the Golden path tests_
so that _Community members can take and use a version of Mojaloop Switch services bundle that is tested and contains latest features and enhancements (added in and PI9(Sprints 9.4, 9.5, 9.6, 10.1) so far)_ 

This is part-2 of the whole feature. Part-1 is #1323 

This specific story is for making necessary changes for supporting Deployment, QA, Fixes, Integration and performing end-to-end testing for all the changes made since Helm v10.1.0

**Tasks**:
- [x] Helm v10.1.0 released [@mdebarros]
- [x] Deployment of released Helm v10.1.0 on **Dev2** [@mdebarros]
- [x] Validation using Golden path regression tests etc on Dev2 [@amarmodus]
- [x] Deployment of released Helm v10.1.0 on **Dev1** [@mdebarros]
- [x] Validation using Golden path regression tests etc on Dev1 [@amarmodus]

**Acceptance Criteria**:
- [x] Helm v10.1.0 is released after testing RC version on dev2
- [x] Helm v10.1.0 is deployed on AWS Dev2 without issues
- [x] QA (Golden path) on deployments done on AWS dev2 environment is done
- [x] Helm v10.1.0 is deployed on AWS Dev1 without issues
- [x] QA (Golden path) on deployments done on AWS dev1 environment is done

**Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/309

**Follow-up**:
- N/A

**Dependencies**:
- N/A

**Accountability**:
- Owner: @mdebarros 
- QA/Review: @elnyry
