### ISSUE TITLE
Implement error end-points for bulk transfers and related functionality in bulk-api-adapter

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1374]
## **Goal**:
As a Switch
I want to handle incoming requests on /bulkTransfers/{ID}/error
so that I can correctly handle 'rejections' of a bulk transfer and other errors

**Tasks**:
- [x] Ensure designs are in place (Either create or validate existing ones)[@oderayi]
- [x] Implementation to provide functionality (may contain sub items)[@oderayi]
- [x] Unit tests [@oderayi]
- [ ] ~Tests in postman~ --> will be a separate story

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] Switch bulk-api-adapter can handle incoming requests on /bulkTransfers/{ID}/error according to the ML FSPIOP Spec v1.0 / v1.1

## **Pull Requests**:
- [x] https://github.com/mojaloop/bulk-api-adapter/pull/28

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @elnyry
