### ISSUE TITLE
Implement GET /bulkTransfers

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1375]
## **Goal**:
As a Switch
I want to handle incoming requests on GET /bulkTransfers as per the ML FSPIOP spec
so that _FSPs can use it to query the status of a given bulk Transfer_

**Tasks**:
- [x] Ensure designs are in place (Either create or validate existing ones)
- [x] Implementation to provide functionality (may contain sub items) [@oderayi] 
  - [x] Bulk API Adapter implementation
  - [x] Central Ledger implementation
- [x] Unit tests [@oderayi] 
- [x] Tests in postman --> can be a separate story [@oderayi] 

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] Switch can handle incoming GET requests on /bulkTransfers as per the ML FSPIOP spec v1.0 / v1.1

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-shared/pull/239
- [x] https://github.com/mojaloop/bulk-api-adapter/pull/37
- [x] https://github.com/mojaloop/central-services-shared/pull/240
- [x] https://github.com/mojaloop/central-ledger/pull/760
- [x] https://github.com/mojaloop/bulk-api-adapter/pull/39
- [x] https://github.com/mojaloop/simulator/pull/206

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @elnyry
