### ISSUE TITLE
Review documentation for the testing toolkit repos

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1376]
## **Goal**:
As an FSP
I want to _be able to easily find, access and usage the Usage Guide and other docs on the testing toolkit_
so that _I can use those docs for self testing / evaluation_

**Tasks**:
- [x] Review docs on ml-testing-toolkit repo [ @georgi-logodazhki ]
  - [x] split User Guide
  - [x] add onboarding for HUB
  - [x] add onboarding for DFSP
- [x] Review the modifications and all the documentation once [ @vijayg10 ]
- [x] Simplify README file with quick start commands [ @vijayg10 ]

**Acceptance Criteria**:
- [x] Docs on mojaloop-testing-toolkit repo are reviewed and updated for completeness.
- [x] Step-by-step instructions are provided for deployment, setup and general usage

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/58

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @elnyry
