### ISSUE TITLE
Testing Toolkit - Scripting capability in test case execution

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1377]
## **Goal**:
As a User of the testing toolkit
I want to have a provision to write scripts in test case requests
so that I can make advanced validations and comparisons (using scripts).

**Tasks**:
- [x] Test the postman sandbox library and check the feasibility for integrating it to the testing toolkit and play with it [ @vijayg10 ]
- [x] Integrate Postman sandbox library to testing toolkit for pre-requests [ @georgi-logodazhki ]
- [x] Provide the pre requests script in testing toolkit UI based on a configurable option [ @vijayg10 ]
- [x] Test the performance and reliability of script execution by adding good number of pre request scripts to the collection [ @georgi-logodazhki ]
- [x] Continue adding post request script on backend [ @georgi-logodazhki ]
- [x] Add post request script on front-end [ @vijayg10 ]
- [x] Fix the issue with sync execution with waiting for the callbacks [ @georgi-logodazhki ]
- [x] Implement some timeout functionality for waiting for the callbacks [ @georgi-logodazhki ]
- [x] Unit tests
- [x] Access environment variables setted in postman sandbox from everywhere [ @georgi-logodazhki @vijayg10 ]
- [x] Add consoleLog and environment state for the scripts [ @vijayg10 @georgi-logodazhki ]
- [x] Add environment variables to configurable params and assertion editor[ @vijayg10 ]

**Acceptance Criteria**:
- [x] Pre request and post request scripts can be specified for a request
- [x] Copying the postman scripts from the GP collection should work with minor changes
- [x] Sync APIs are working and async APIs are getting timeout for the failed callbacks
- [x] Unit tests are added

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/52

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 @GelatoDan 
- QA/Review: @elnyry
