### ISSUE TITLE
Add support for Hapi-Swagger to Openapi Backend APIs

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#1380]
## **Goal**:
As a implementer I want to be able to view and test requests against the valid API swaggers to ensure that I have the correct request and response objects catered for in my implementation

**Tasks**:
- [ ] Investigate approach currently used by hapi-swagger/swagger-ui
- [ ] Cater for scenario where the we pass in an existing swagger.json/yaml

**Acceptance Criteria**:
- [ ] Swagger documentation is shown on /documentation endpoints
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rmothilal 
- QA/Review: @rmothilal @mdebarros
