### ISSUE TITLE
Regular Security Patches + Updates

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1382]
## **Goal**:
As an `OSS Developer` I want to `address github and npm security updates` so `Mojaloop stays secure, and developers can put their trust in a well managed codebase`.

This is a reoccurring ticket, to track regular manual security updates

**Repos Reviewed**
- [central-services-auth](https://github.com/mojaloop/central-services-auth/)
- [central-services-database](https://github.com/mojaloop/central-services-database/)
- [central-services-error-handling](https://github.com/mojaloop/central-services-error-handling/)
- [forensic-logging-client](https://github.com/mojaloop/forensic-logging-client/)
- [simulator](https://github.com/mojaloop/simulator/)
- [central-services-metrics](https://github.com/mojaloop/central-services-metrics/)
- [account-lookup-service](https://github.com/mojaloop/account-lookup-service/)
- [central-services-stream](https://github.com/mojaloop/central-services-stream/)
- [als-oracle-pathfinder](https://github.com/mojaloop/als-oracle-pathfinder/)

**Tasks**:
- [x] resolve all open github security alerts (many could be ignored as they were for `devDependencies`
- [x] updated the `npm run audit:check` to ignore devDependencies (for the vulnerable repos only, this will be done eventually for other repos)

**Acceptance Criteria**:
- [ ] Github Security Alerts Addressed
- [ ] PRs opened and merged with security patches
- [ ] `npm audit` resolved/ignored where applicable

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-auth/pull/115
- [x] https://github.com/mojaloop/central-services-database/pull/128
- [x] https://github.com/mojaloop/central-services-error-handling/pull/146
- [x] https://github.com/mojaloop/forensic-logging-client/pull/78
- [x] https://github.com/mojaloop/simulator/pull/186
- [x] https://github.com/mojaloop/central-services-metrics/pull/124
- [x] https://github.com/mojaloop/account-lookup-service/pull/335
- [ ] https://github.com/mojaloop/central-services-stream/pull/100
- [x] https://github.com/mojaloop/als-oracle-pathfinder/pull/22

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
Thanks @lewisdaly for this and I will contribute. Currently what is the source of all Github security alerts?

**Comment by lewisdaly** [comment]
Yeah I just added you for visibility. 

All alerts are minor, just for issues with a package called `minimist`, 50% of which are ignoreable since they are devDependencies, and don't end up in our docker images

**Comment by godfreykutumela** [comment]
Ok thanks noted @lewisdaly
