### ISSUE TITLE
Update event framework documentation to cover tracestate changes

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1383]
## **Goal**:
As a OSS contributor I want to update documentation of Event-SDK and event framework so that tracestate changes has been documented.

**Tasks**:
- [x] update docs for event-sdk
- [x] update docs for event framework

**Acceptance Criteria**:
- [x] Unit Tests pass

## **Pull Requests**:
- [x] documentation https://github.com/mojaloop/documentation/pull/219
- [x] event-sdk https://github.com/mojaloop/event-sdk/pull/38

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vgenev 
- QA/Review: @elnyry
