### ISSUE TITLE
Bulk transfers support in sdk-scheme-adapter (mojaloop-simulator) - Part 2

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1386]
## **Goal**:
As an FSP / Mojaloop Switch
I want to ensure that the sdk-scheme-adapter component support for Bulk Transfers/Bulk Quotes  end-points and related functionality are thoroughly tested
so that I can use it for QA and Validation of Bulk transfers (including mojaloop-simulator)

**Note**:This particular story focuses on validating the implementation and QA

**Tasks**:
- [x] Implementation for the missing GET `/bulkQuotes/{ID}` (sdk-scheme-adapter inbound/outbound API) [@oderayi]
- [x] Unit tests [@oderayi]
- [x] PR review fixes [@oderayi] 
- [x] QA - postman tests [@oderayi] 
- [x] Update helm scripts to support changes and for deployment [@oderayi]
- [x] Deploy on dev2 and validate [@oderayi]

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-standard-components/pull/64
- [x] https://github.com/mojaloop/sdk-standard-components/pull/65
- [x] https://github.com/mojaloop/mojaloop-simulator/pull/49
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/159
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/176
- [x] https://github.com/mojaloop/postman/pull/141
- [x] https://github.com/mojaloop/simulator/pull/203
- ~https://github.com/mojaloop/mojaloop-simulator/pull/57~
- [x] https://github.com/mojaloop/mojaloop-simulator/pull/62
- [x] https://github.com/mojaloop/sdk-standard-components/pull/73
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/186
- [x] https://github.com/mojaloop/helm/pull/330

## **Follow-up**:
- N/A

**Dependencies**:
- #1325 

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by kjw000** [comment]
@elnyry-sam-k why is this blocked?

**Comment by elnyry-sam-k** [comment]
hi @kjw000 , its waiting on this PR: https://github.com/mojaloop/mojaloop-simulator/pull/61, which has significant implications to the work items in this story.. Steven is working with the contributors on that PR to get this unblocked.
