### ISSUE TITLE
Implement proper mono-repo structure

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#1388]
**Goal**:
Implement proper mono-repo structure

**Tasks**:
- [x] Re-structure repo [ @mdebarros  ]
- [x] Ensure that npm install/build are all working [ @mdebarros  ]

**Acceptance Criteria**:
- [ ] Code is split into modules that are imported dynamically
- [ ] `npm install` works
- [ ] `npm run build` works

## **Pull Requests**:
- [ ] https://github.com/mojaloop/poc-architecture/pull/3

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by millerabel** [comment]
Hi Pedro, use of “yarn” to replace NPM is not approved. If you want to think about replacing our tooling, that will need to be discussed with the DA and the TGB. We have significant tooling around NPM which is the standard for nodejs-based projects. Yarn is a bit anachronistic and as far as I can see offers no advantages.

— Miller

On May 25, 2020, at 10:27 AM, Pedro Barreto <notifications@github.com> wrote:


Replace npm with yarn and implement proper mono-repo structure

**Comment by pedrosousabarreto** [comment]
We stick to NPM, changing the name and scope of this ticket to the correct structure for the repositories' multiple sub modules

**Comment by mdebarros** [comment]
PR that was rejected for https://github.com/mojaloop/poc-architecture/pull/1

**Comment by pedrosousabarreto** [comment]
Looks good to me
