### ISSUE TITLE
Implement service with event and command handler for the participants aggregate

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#1390]
Implement the service for the participants (deployable), that includes for now:
- Command handler - to process commands for the participants aggregate;
- Event handler - to listen to events from the transfers aggregate and when necessary react by creating commands for the participants aggregate.

## **Goal**:
Implement the service for the participants (deployable), that includes for now:
- Command handler - to process commands for the participants aggregate;
- Event handler - to listen to events from the transfers aggregate and when necessary react by creating commands for the participants aggregate.

**Tasks**:
- [x] Create a simple service structure, no DI for now [ @mdebarros ]
- [x] Re-factor participantEntity to match Mojaloop requirements [ @mdebarros ]
- [x] Re-factor participantCmd's to match updated participantEntity [ @mdebarros ]
- [x] Re-factor participantEvt's to match updated participantEntity [ @mdebarros ]
- [x] Create participantCmdHandler [ @mdebarros ]
- [x] Implement createParticipant implementation [ @mdebarros ]
- [x] Implement reserveFunds implementation [ @mdebarros ]
- [x] Implement commitFunds implementation [ @mdebarros ]
- [x] Create participantEvtHandler [ @mdebarros ]
- [x] Handle transferPrepareAcceptedEvt in participantEvtHandler [ @mdebarros ]
- [x] Handle transferFulfilAcceptedEvt in participantEvtHandler [ @mdebarros ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
