### ISSUE TITLE
Create tests on the shared domain and infrastructure code

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#1394]
## **Goal**:
As a developer I want to tests on the shared domain and infrastructure code so that we increase its quality

**Tasks**:
- [X] Initial structure for tests with mock publisher and logger, here:https://github.com/mojaloop/poc-architecture/tree/feature/libdomaintests [ @pedrosousabarreto  ]
- [ ] Complete the remaining libDomain tests [@DonChangfoot ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by pedrosousabarreto** [comment]
Initial work done here: https://github.com/mojaloop/poc-architecture/tree/feature/libdomaintests
@DonChangfoot to carry on with this story

**Comment by mdebarros** [comment]
Initial tests were completed, but new tests will need to be made based on the recent changes made, and also during the "productionization" phase.
