### ISSUE TITLE
Testing Toolkit - Test case collections for Hub extended

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1395]
## **Goal**:
As a Hub operator
I want a _test case collection for Hubs that provides good coverage_
so that _I can use it to test my Hub implementation with testing toolkit)

**Tasks**:
- [x] Add more scenarios to testing toolkit hub collection (from GP) [ @georgi-logodazhki ]
- [x] Update Command line tool implementation [ @georgi-logodazhki ]
- [x] Update Command line tool documentation [ @georgi-logodazhki ]
- [x] Test the hub collection against aws dev environments [ @vijayg10 ]
- [x] Implement importing multiple template files and separate the environment from collection [ @vijayg10 ]
- [x] Review with QA team [ @vijayg10 @georgi-logodazhki ]
- [x] Make sure user guide for onboarding to test hub implementations is available [ @georgi-logodazhki ]

**Acceptance Criteria**:
- [x] The testing toolkit can be used to test all if not most of the scenarios in golden path collection
- [x] The testing toolkit can be used to test against dev environments
- [x] User guide is available from hub implementers perspective
- [x] User guide for Command line tool is up-to-date

## **Gaps**
- [x] The execution should be able to terminate [ @vijayg10 ]
- [x] Query params in test case request editor [ @vijayg10 ]
- [x] Proper console log in case of postman sendRequest failures
- [x] Add support for objects in environment variables [ @vijayg10 ]

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/54
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/55
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/56
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/57
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/59
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/26
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/27
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/61
## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 @georgi-logodazhki 
- QA/Review: @elnyry @amarmodus
