### ISSUE TITLE
Update APIs to use OpenAPI-Backend instead of Hapi-Openapi

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#1396]
## **Goal**:
As a developer
I want to update existing APIs that are using Hapi-Openapi to now use OpenAPI Backend
so that we are less dependent on the developers of Hapi-Openapi and Enjoi which prevents us from using the latest versions of Hapi and Joi.

**Note**: The above change will also allow us to use unicode Regex for accented characters

**Tasks**:
 - [x] quoting-service - remove dependency on Hapi-Open-API and add routes
 - [x] account-lookup-service - remove dependency on Hapi-Open-API and add routes
 - [ ] ~ml-api-adapter - Update to use ml-schema-validator library~ --> move to a new story after testing is done
 - [x] legacy simulator - Update to use ml-schema-validator library
 - [x] Review if any other services need to be updated
- [ ] ~Postman tests~
  - [ ] ~ALS Collections and ENV variables~
  - [ ] ~Transaction-requests-service Collection and ENV~
  - [ ] ~Quoting-service Collection and ENV~
  - [ ] ~Bulk-Transfers Collection and ENV~
- [ ] ~helm changes~

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config
- [x] legacy simulator, ml-api-adapter are updated to use  the ml-schema-validator library
- [x] ALS and quoting-service are updated to remove dependency on Hapi-Open-API
- [x] ALS and quoting-service are updated to add routes

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rmothilal 
- QA/Review: @rmothilal @elnyry
