### ISSUE TITLE
Test the performance enhancements of the streaming library

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1397]
## **Goal**:
As a OSS Developer I want to continue the tests in the perf environment the changes in the streaming library introduced into version: https://github.com/mojaloop/central-services-stream/releases/tag/v10.2.8-snapshot.

**Tasks**:
- [ ] Investigate unstable behaviour of the perf cluster
- [ ] get the perf cluster into stable state
- [ ] test flow mode
- [ ] test recursive mode

**Related stories**:
 - https://github.com/mojaloop/project/issues/1357

**Acceptance Criteria**:
- [ ] End-to-end tests are ran and results are captured

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
