### ISSUE TITLE
DevSecOps - Create a simple Security Alerts Dashboard

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1398]
## **Goal**:
As a `OSS Maintainer` I want to `see all of the github security alerts in one place` so that `I can get a feeling for the overall status of code security across the entire github organization`

At the moment, github sends weekly security alerts, but to view individual alerts, one must click into every repo individually. If we had a way to view them in one simple place, it would make the security alert process easier to manage. 

Additionally, such a dashboard could be a useful place to put other statuses/information about the project, such as license scan results, QA test results...

**Tasks**:
- [x] Investigate the github api, is there a tool for pulling in security alerts?
- [ ] look into (grafana github datasource)[https://github.com/grafana/grafana-github-datasource], and estimate the difficulty for adding the v4 GraphQL API calls
- [ ] make an example dashboard (local)
- [ ] recommend hosting options for the dashboard (I'm leaning towards a standalone helm chart that can run on the dev1 cluster)

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- [ ] helm chart for dashboard
- [ ] docs for using and managing the dashboard
- [ ] deployed dashboard 

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
I started an initial look into getting the security alerts over the API. They are currently only available at a per-repo level on the new GraphQL Github API.

That means that getting the security alerts to display will take an 1+ requests to 100 + repositories.

**Comment by millerabel** [comment]
Would be worthwhile to reach out to GitHub directly and see if there is an “organization” level API either in the works or an alternative to polling each repo. Could the dependabot output (and other tools output) be redirected into a common log that we ingest into ELK (e.g.)?

— Miller

On Jun 25, 2020, at 6:14 AM, Lewis Daly <notifications@github.com> wrote:


I started an initial look into getting the security alerts over the API. They are currently only available at a per-repo level on the new GraphQL Github API.

That means that getting the security alerts to display will take an 1+ requests to 100 + repositories.

**Comment by lewisdaly** [comment]
Yeah I'll get in touch with github and see what they have to say. I know these features are rapidly expanding, so they might have something in the works or in preview mode.

**Comment by godfreykutumela** [comment]
PI 11 Backlog

**Comment by lewisdaly** [comment]
I did a little looking around on this today, and I think we could and should use grafana for this purpose. Here's a simple example: https://neuvector.com/cloud-security/prometheus-grafana/

We would still need to figure out where this could be hosted, and if/how we might make this publicly available.

**Comment by godfreykutumela** [comment]
Thanks @lewisdaly. Don't we have grafana runnning somewhere within the Mojaloop landscape that we can re-use for this?

**Comment by lewisdaly** [comment]
We have grafana deployed inside of Mojaloop for monitoring purposes, but I think this should be hosted separately, perhaps in a `community-tools` namespace on the dev cluster.

This project: https://github.com/grafana/grafana-github-datasource might be a good place to start and see how these tools might all work together.

**Comment by lewisdaly** [comment]
It also looks like github's v4 graphql api contains the security alert information:
(on the [graphql explorer](https://developer.github.com/v4/explorer/))
```
query { 
  organization(login: "mojaloop") {
    id,
    login,
    name,
    repositories(first: 20, after: "Y3Vyc29yOnYyOpHOBnfYwA==", isLocked: false) {
      pageInfo {
        endCursor
      }
      edges:
          nodes {
            id,
            name
            description,
            vulnerabilityAlerts(last: 100) {
              edges:
              	nodes {
                  id
                  vulnerableManifestFilename
                  securityAdvisory {
                    id
                    severity
                  }
                }
            }
          }
        }
   }
}
```


Contains some data like so:
```json
{
            "id": "MDEwOlJlcG9zaXRvcnkxMDg5MTE1MzA=",
            "name": "central-services-auth",
            "description": "Share authentication and authorization code for central services",
            "vulnerabilityAlerts": {
              "edges": [
                {
                  "id": "MDI4OlJlcG9zaXRvcnlWdWxuZXJhYmlsaXR5QWxlcnQyNTkxMTk4MzQ=",
                  "vulnerableManifestFilename": "package-lock.json",
                  "securityAdvisory": {
                    "id": "MDE2OlNlY3VyaXR5QWR2aXNvcnlHSFNBLXZoOTUtcm1nci02dzRt",
                    "severity": "MODERATE"
                  }
                },
                {
                  "id": "MDI4OlJlcG9zaXRvcnlWdWxuZXJhYmlsaXR5QWxlcnQzMjM0MDcyMzc=",
                  "vulnerableManifestFilename": "package-lock.json",
                  "securityAdvisory": {
                    "id": "MDE2OlNlY3VyaXR5QWR2aXNvcnlHSFNBLWptcW0tZjJneC00Zmp2",
                    "severity": "LOW"
                  }
                },
                {
                  "id": "MDI4OlJlcG9zaXRvcnlWdWxuZXJhYmlsaXR5QWxlcnQzMjgzNTMxMTE=",
                  "vulnerableManifestFilename": "package-lock.json",
                  "securityAdvisory": {
                    "id": "MDE2OlNlY3VyaXR5QWR2aXNvcnlHSFNBLXA2bWMtbTQ2OC04M2d3",
                    "severity": "LOW"
                  }
                }
              ]
            }
          },
```

**Comment by lewisdaly** [comment]
It may be better to leverage Prometheus for the data source, instead of directly querying the github api. That way, we can better capture historical information (provided we are 

[This project](https://github.com/vegasbrianc/github-monitoring) uses the community supported prometheus github plugin (written in go). It doesn't contain the stats we need, so we would need to contribute some code to extend the prometheus plugin and be able to extract the organization-based stats on security vulnerabilities

**Comment by godfreykutumela** [comment]
Thanks @lewisdaly I have asked for Victor Chinyavada to jump and assist on this - Look at both Grafana and Prometheus for the security dashboard as envisaged.

**Comment by lewisdaly** [comment]
Great! I've got a working branch going on here: https://github.com/vessels-tech/moja-stats/tree/feature/security-dash

**Comment by godfreykutumela** [comment]
@chinyavadav

**Comment by godfreykutumela** [comment]
Deferred to PI 12

**Comment by lewisdaly** [comment]
Closing this as out of scope for now. GitHub is getting better at their dependabot/security alerts dashboard. Feel free to reopen or reassign in the future.
