### ISSUE TITLE
Zero-downtime deployment example approach for a breaking change

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1400]
## **Goal**:
As a hub operator/integrator, I want to see an example approach of a Mojaloop upgrade with zero downtime, so I can learn and implement my own approach for zero downtime upgrades.

> Note: This story contains a lot of work, and we might end up dividing it into further stories

**Tasks**:
- [ ] add `RollingUpgrade` definitions to the relevant `Deployment` templates and `values.yml` files in helm. For an example, see this comparison from @lewisdaly's fork: https://github.com/mojaloop/helm/compare/master...vessels-tech:versioning/zdd-test?expand=1
- [ ] from a fork or branch of `mojaloop/helm` publish a number of helm versions for incrementally applying the breaking change (see #1329 for more information)
- [ ] TBD [ @? ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
