### ISSUE TITLE
Minimal CI/CD is configured to ensure PR QA

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1405]
## **Goal**:
Minimal CI/CD is configured to ensure PR QA

**Tasks**:
- [x] Configure standard CI/CD configs for PoC
- [x] Add additional QA checks in place (e.g. lint)

**Acceptance Criteria**:
- [x] Standard CI/CD scripts are available to the PoC repository for future enhancement as required
- [x] Selected (lint) CI/CD checks are run as part of PR process

## **Pull Requests**:
- [ ] https://github.com/mojaloop/poc-architecture/pull/6

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
