### ISSUE TITLE
Update mojasims collection to fix identified issues

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1409]
## **Goal**:
This is follow up story of https://github.com/mojaloop/project/issues/1370

As an FSP / Switch
I want to _use postman collections and Helm release versions that have been tested by the core team on a similar environment_
so that _I can upgrade to those releases and use the postman scripts with confidence_ as they've been validated by the core team

**Tasks**:
- [x] Rename mojaloop sim collection - both mojasims and legacy collection named accordingly
- [x] Add settlement related test/folder to mojasims collection
- [ ] ~~Identify all the request which had failures mojasim collection and labelled as 'CHECK'~~
- [x] Identify and fix issues
   - [x] Raised https://github.com/mojaloop/project/issues/1404 - accept header issue - validated as part of GP Collection
   - [x] Raised https://github.com/mojaloop/project/issues/1408 - missing uri header - validated in https://github.com/mojaloop/project/issues/1443
- [x] Test Golden path mojaloop-simulators collection on dev2
- [ ] ~~Update daily test cron job to use mojaloop-simulators collection as well~~

**Acceptance Criteria**:
- [ ] ~~AWS envt dev1 used by the core team is updated to use mojaloop-simulator instances as FSPs~~
- [x] Golden path mojaloop-simulators collection (postman repo) is validated on dev1 environment and runs 100%
- [ ] ~~Cron job that runs on dev1 envt is updated to use Golden path mojaloop-simulators collection and runs at 100% (ensure it runs once with and without notification to meet this criteria)~~

## **Pull Requests**:
- [ ]
 
## **Follow-up**:
- https://github.com/mojaloop/project/issues/1464

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by amarmodus** [comment]
https://github.com/mojaloop/project/issues/1464 - follow up item raised.
