### ISSUE TITLE
Testing Toolkit - Helm chart deployment

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1410]
## **Goal**:
As a user of the testing toolkit I want to have a helm chart to make the testing toolkit deployment easy in a k8s environment.

**Tasks**:
- [ ] Prepare an initial version of the helm chart for api service and UI service
- [ ] Volume mounts to be added in the helm to make the changes to the rules persistent across the pod restarts.

**Acceptance Criteria**:
- [ ] Helm chart for testing toolkit is available in helm repository
- [ ] Helm chart is working in dev environments and in local cluster deployments.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @elnyry  @mdebarros
