### ISSUE TITLE
HSM Integration - Document Key and Certificate Management Use Case Requirements

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1411]
## **Goal**:
Provide Key and Certificate Management Use Case input to the HSM design team.

**Tasks**:
- [ ] Identify existing pain points from implementation [ @rasputtintin ]
- [ ] Analyze key and certificate management requirements [ @rasputtintin ]
- [ ] Prepare and present results to the HSM team

**Acceptance Criteria**:
- [ ] Key and Cert Management documented use case requirements

## **Accountability**:
- Owner: @rasputtintin @godfreykutumela 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
Key and Certificate Management Requirements:
--
- Must conform to relevant International Standards on Certificate management
- Solution must allow storage and management of keys and secrets as well as monitoring usage including policy violations.
- The solution must support End User   Digital Certificate
- The Digital Certificate must   support variable certificate validity periods..
- The digital certificates delivered   must support the following actions: authentication, digital signing, data   integrity and non-repudiation.
- The solution must support the   administration of digital certificate request(Approve/Reject)
- The solution should have   configurable workflows to determine process flows
- The solution must support the   provision to revoke compromised certificate
- The solution must support   self-service facility for end-user to enroll, pick up, revoke and renew   approved digital certificate over the internet.
- The system must be accessible   through standard Web browsers (Firefox, and MS web browsers) without   additional add-ins
- The solution must support SHA2   (SHA-256) Signature and RSA Encryption with 2048 bit key length and higher
- The solutions must have APIs to support CSR generation, validation as part of automated DFSP onboarding process
- The solution must support integration with CM to automate certificate managent as part of DFSP onboarding
- Solution must allow advanced   authentication capabilities for management os keys and secrets
- Support centralised dashboards,   reports and alerts on certificate / secrets activities.
