### ISSUE TITLE
Improve the "Transfers" app

### ISSUE THREAD

**Issue by yosheeck** [mojaloop/project#1413]
## **Goal**:
Further iteration of Transfers app improvements.

**Tasks**:
- [x] Rename/refactor names of events and commands according to latest designs
- [x] Adapt Transfers app to latest changes in command interfaces
- [x] Implement logic for receiving "payer funds reserved" event and "payee funds reserved"
- [x] Refactor transfer entity, so it's not using general "changeStateTo()", but has a number of dedicated methods to mutate states
- [x] Add support for external payload being passed from ml-api to ml-api-notify

## **Pull Requests**:
- [x] https://github.com/mojaloop/poc-architecture/pull/12
- [x] https://github.com/mojaloop/poc-architecture/pull/17
- [x] https://github.com/mojaloop/poc-architecture/pull/19
