### ISSUE TITLE
Gather rdkafka metrics for performance analysis

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1414]
## **Goal**:
As a ML Community member I want to gather rdkafka metrics using this library: https://github.com/Collaborne/node-rdkafka-prometheus and expose it to prometheus

**Tasks**:
- [x] Enable event statistics callback
- [x] Register metrics into central-services-stream host service - https://github.com/mojaloop/central-services-stream/releases/tag/v10.3.0-snapshot
- [x] change helm charts to enable statistics callback
- [x] deploy to perf environment and test services /metrics endpoint
- [x] add metrics for async.queue depth and highBatchWaterMark
- [ ] ~Visualize desired metrics in Perf Grafana dashboards~

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- #1414 

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vgenev 
- QA/Review: @yosheeck @mdebarros
