### ISSUE TITLE
Initial instrumentation implementation

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#1417]
## **Goal**:
As a developer I want to see tracing, metrics and logging info on requests that span multiple services so that I can better troubleshoot the system behaviour

**Tasks**:
- [x] initial tracing setup [ @pedrosousabarreto   ] - done in https://github.com/mojaloop/poc-architecture/pull/26
- [x] initial metrics setup on the application along with a simple metrics endpoint [ @mdebarros  ]
- [ ] initial logging setup [ @mdebarros   ]
- [x] initial health check endpoint on the application [ @mdebarros   ]

Tools and Libs:
- prom-client for metrics;
- Fastify for the minimal web server (metrics and health endpoint)
- no tools/libs required for the tracing atm

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
@pedrosousabarreto what is the task for `initial logging setup [ @mdebarros ]`?
