### ISSUE TITLE
HSM Integration - Calculate TPS sizing estimates

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1418]
## **Goal**:
Provide TPS sizing estimates on the switch side only - no DFSP level throughput to be consider for this exercise. This will be based on  a full transfer process across all traffic of participating DSFP's - aggregated not per transfer or per DFSP.

**Tasks**:
- [x] Determine a method and approach for this [ @pedrosousabarreto @godfreykutumela @rasputtintin  ]
- [ ] Calculate crypto messages per single transfer [ @rasputtintin @godfreykutumela ]
- [ ] Determine all required crypto operations and key size in a single transfer [ @godfreykutumela 
- [ ] Calculate required TPS for 1000 transfers per second and use that as basis to calculate the overall TPS for the switch side.

**Acceptance Criteria**:
- [ ] Defined estimation method
- [ ] Estimated TPS figure

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela @rasputtintin

**Comment by elnyry-sam-k** [comment]
hey @godfreykutumela did you plan on posting some numbers here as a ball park estimate, etc?

**Comment by godfreykutumela** [comment]
[HSM Transaction Rate Estimation.docx](https://github.com/mojaloop/project/files/4772803/HSM.Transaction.Rate.Estimation.docx)
 
Hi @elnyry-sam-k Attached is the hsm tps calculation analysis report and calculator.

**Comment by godfreykutumela** [comment]
![image](https://user-images.githubusercontent.com/58056329/84539347-82d13300-acf3-11ea-806d-57264201cffe.png)

**Comment by godfreykutumela** [comment]
[HSM Transaction Rate Estimation.xlsx](https://github.com/mojaloop/project/files/4772812/HSM.Transaction.Rate.Estimation.xlsx)

HSM TPS calculator

**Comment by elnyry-sam-k** [comment]
Thanks a lot, @godfreykutumela
