### ISSUE TITLE
Adapt ML-API-Adapter for the PoC (topics)

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#1419]
## **Goal**:
As a developer I want the ML-API-Adapter to send messages to a different topic in Kafka so the new PoC can pick them up
As a developer I wan the ML-API-Adapter to read the PoC response messages from the PoC specific topic to enable notifications to be sent

**Tasks**:
- [x] move a copy of ml-api-adapter into the mono-repo for ease of development (since we can share poc libraries) [ @mdebarros  ]
- [x] change ingress topic for events published by ML-API-Adapter [ @mdebarros  ]
- [x] change ingress message to event topic to align to PoC
- [x] change egress topic for events that ML-API-Adapter listens to [ @mdebarros  ]
- [x] change egress message to event topic to align to PoC

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
