### ISSUE TITLE
How to get participant endpoint from ML-API-Adapter

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#1420]
## **Goal**:
As a developer I want to find a way for the ML-API-Adapter to have/find the information about the participant endpoint to call at the end of the prepare and fulful legs

**Tasks**:
- [ ] investigate how to pass the participant endpoint to the ML-API-Adapter [ @? ]
- [ ] implement for now the fastest way (whatever comes from the task above) [ @? ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
