### ISSUE TITLE
Initial scalability and performance early tests

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#1421]
## **Goal**:
As a developer I want to be able to measure the new PoC's scalability and performance so that assess we are in the right track and adjust architecture decisions

**Tasks**:
- [x] put in initial scripts/tooling to measure scalability and performance (nothing fancy initially) [ @pedrosousabarreto  ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/poc-architecture/pull/16

## **Follow-up**:
- nothing, next step is to have the PoC running on the performance environment with proper metrics

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

## Description
See /modules/devtools/ for the scripts to be used.
- use "npm run perfMeasure" to start the simple perf monitor
- use "npm run pubPrepareMultipleTransferEvt" to Inject multiple "TransferPrepareRequestedEvt" messages 

Initial results, single server (dual xeon, 64 GB ram, raid0 nvme):
- common: single kafka broker and single redis both running in docker
- using the PoC simulator that listens to prepared events and injects fulfil requests (not the real simulator + ml-api-adapter)
- injection of 200 TransferPrepareRequests per second
-- with 4 pairs of transfer evt + cmd handlers and participant evt + cmd handlers - 200 req/s at avg 400ms per msg
-- with 3 pairs of transfer evt + cmd handlers and participant evt + cmd handlers - 200 req/s at avg 600ms per msg
-- with 2 pair of transfer evt + cmd handlers and participant evt + cmd handlers - 200 req/s at avg 800ms per msg
