### ISSUE TITLE
Visualize rdkafka metrics

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1422]
## **Goal**:
As a ML Community member I want to visualize on Perf dashboard all metrics, which are significant from the ones made available in story #1414  
**Tasks**:
- [ ] Visualize desired metrics in Perf Grafana dashboards

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- #1414 

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
