### ISSUE TITLE
Capability to host the testing toolkit

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1426]
## **Goal**:
As a User of the testing toolkit
I want to have the capability to host the testing toolkit
so that I can use it for easily validating Mojaloop FSP or Hub deployments without having to deploy it locally

**Tasks**:
- [ ] Design the solution needed to support hosting the toolkit
- [ ] Design changes needed for dealing with sessions, persistence and file system usage
- [ ] Review Security of toolkit usage when hosted
- [ ] Refactoring for changes needed
- [ ] Unit tests
- [ ] End to end testing

**Acceptance Criteria**:
- [ ] Design for hosting the testing toolkit is done
- [ ] The testing toolkit is refactored to have the hosting capability
- [ ] Unit Tests pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @georgi-logodazhki 
- QA/Review: @vijayg10 @elnyry-sam-k
