### ISSUE TITLE
Create Hub Operator documentation/guides

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1427]
## **Goal**:
As a `Hub Operator`
I want to `Event Framework Documentation/Guidelines for each stakeholder involved in the end-to-end trace`
so that `each stakeholder understands their responsibilities and implementation requirements`

**Tasks**:
- [ ] Create Hub Operator documentation/guides on how to:
    - [ ] Monitoring events/transactions
    - [ ] Troubleshoot issues
    - [ ] Trace requests/transactions
    - [ ] Information on types of Events

**Acceptance Criteria**:
- [ ] Published documentation for Hub Operators on how to use the Event Framework/Visualisation dashboards provided by EFK/APM for Operational Monitoring, Management & Troubleshooting

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
handled as part of epic https://github.com/mojaloop/project/issues/2303
