### ISSUE TITLE
Helm Release v10.4.0: Updates to helm, Supporting QA, Fixes, Releases

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1430]
## **Goal**:
As an ML OSS Code base maintainer
I want to _validate and make a Helm release in PI-10 (Sprint 10.4) that is successfully validated by the Golden path tests_
so that _Community members can take and use a version of Mojaloop Switch services bundle that is tested and contains latest features and enhancements (added in and PI-10(Sprints 10.2, 10.3, 10.4) so far)_ 

This specific story is for making necessary changes for supporting Deployment, QA, Fixes, Integration and performing end-to-end testing for all the changes made since Helm v10.4.0

**Tasks**:
- [x] Fix the issues in the current helm master branch #1428 
- [x] Make releases on all core services to have latest images / versions
- [x] Identify changes needed for helm (config / default.json)
- [x] Integrate/Merge Mojaloop-Simulators into main Mojaloop Helm chart for general release
- [x] Initial PR with changes for v10.4.0
  - [x] Initial PR review
  - [x] Deploy, validate, fix issues, redeploy
  - [x] With stable deployment test Golden path
- [x] Identify issues with QA Scripts if any - fix them and retest
- [x] Identify Bugs, log them
- [x] Validate finance portal
- [x] Fix bugs logged if critical
- [x] Deploy, validate on AWS dev2
- [x] Validate upgrade scenario (from v10.1.0)
- [x] Validate with Legacy Simulator collection
- [x] Validate with Mojaloop Simulator collection
- [x] Release notes for helm v10.4.0 is drafted
- [x] Helm v10.4.0 released
- [x] Deployment of released Helm v10.4.0 on **Dev2**
  - [x] Helm v10.4.0 is deployed on **Dev2** successfully
  - [x] Validation using Golden path regression tests etc on Dev2
    - [x] Legacy Simulator collection
    - [x] Mojaloop Simulator collection
  - [x] Validate finance portal
- [x] Deployment of released Helm v10.4.0 on **Dev1**
  - [x] Helm v10.4.0 is deployed on **Dev1** successfully
  - [x] Validation using Golden path regression tests etc on Dev1
    - [x] Legacy Simulator collection
    - [x] Mojaloop Simulator collection

**Acceptance Criteria**:
- [x] Helm RC v10.4.0 is validated on dev2 and iterated until 100% pass result with postman Golden path collection is achieved
- [x] QA (Golden path) on deployments done on AWS dev2 environment is done
- [x] Bugs are logged based on observations, failures
- [x] Bugs logged are fixed if critical to make subsequent releases in individual services (or Helm)
- [x] All the changes needed for supporting v10.4.0 of Helm (List out major changes in release notes once release is ready) are done
- [x] Helm v10.4.0 release notes is drafted and published

**Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/335
- [x] https://github.com/mojaloop/helm/pull/336
- [x] https://github.com/mojaloop/helm/pull/339
- [x] https://github.com/mojaloop/postman/pull/138
- [x] PR on a private repo for config (not adding here)

**Follow-up**:
- N/A

**Dependencies**:
- N/A

**Accountability**:
- Owner: @vijayg10  
- QA/Review: @elnyry @mdebarros @rmothilal

**Comment by elnyry-sam-k** [comment]
100% on Legacy Sim collection
![image](https://user-images.githubusercontent.com/10507686/86490563-70439a00-bd85-11ea-8e45-4236e02abc11.png)

**Comment by elnyry-sam-k** [comment]
100% with MojaSims collection
![image](https://user-images.githubusercontent.com/10507686/86490594-8e10ff00-bd85-11ea-910e-030e9341e872.png)

**Comment by vijayg10** [comment]
100% with MojaSims collection on Dev1

![Screenshot 2020-07-08 at 5 09 40 PM](https://user-images.githubusercontent.com/33152110/86920052-bebab500-c146-11ea-83cc-b11cafc4aca7.png)

**Comment by elnyry-sam-k** [comment]
@vijayg10 thanks!
