### ISSUE TITLE
Setup and run the PoC on the performance env

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#1431]
## **Goal**:
As a sponsor I want to compare the performance of the Arch PoC in the same performance environment so that a comparable performance test result is available

**Tasks**:
- [ ] Setup the PoC on the performance env [ @? ]
- [ ] execute the performance tests on the performance env [ @? ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
