### ISSUE TITLE
Simplify KafkaMessagePublisher implementation

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#1432]
## **Goal**:
As a developer I want to have a consolidated KafkaMessagePublisher so that no I remove unecessary complexity

**Tasks**:
- [ ] Merge KafkaMessagePublisher and KafkaGenericProducer into KafkaMessagePublisher [ @ ]
- [ ] Remove the handlerCallback parameter from abstract MessageProducer.init() [ @ ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
