### ISSUE TITLE
Create and test KafkaJs' implementation

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#1433]
## **Goal**:
As a developer I want to experiment with KafkaJs lib to see if we can use it in the project, 
Context: It is simpler and if the performance is adequate we can consider changing to it.

**Tasks**:
- [x] Create the consumer an publisher using KafkaJs [ @mdebarros  ]
- [x] Test the performance of the new implementation [ @pedrosousabarreto    ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
