### ISSUE TITLE
Add Validation to Commands

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#1435]
## **Goal**:
As a developer I want to be able to have a validation methods on commands so that when creating them on the event handlers I can ensure only properly formed commands are published

**Tasks**:
- [ ] Create validation mechanism in the abstraction/base classes  @pedrosousabarreto  ]
- [ ] Create validation methods for transfer commands  @ ]
- [ ] Create validation methods for participant commands  @  ] 

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
