### ISSUE TITLE
QA : Validate unsupported http method for all resources - Fix http status code to 405 - #1331

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1436]
## **Goal**:
As a QA I want to validate #1331 and add postman test in GP test 
so that it can be validated and tested in regression

**Tasks**:
- [x] validate #1331 - unsupported http method's status code
- [x] Add postman test in legacy test.
- [x] verify in dev environment

**Acceptance Criteria**:
- [x] Postman test added to GP legacy test

## **Pull Requests**:
- [x] https://github.com/mojaloop/postman/pull/124

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
