### ISSUE TITLE
Use offsets to control participant dupplicate commands on rebalances

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#1437]
## **Goal**:
As a developer I want to have the ability to guarantee that no duplicate commands are processed by the participant command adapters.

Context: because on the participants we have no state machine like we have with the transfers we need an alternate mechanism. Using offsets for now is simpler than versioning.

Strategy:
- on the base/abstract aggregate check for consistency after loading the aggregate and before processing any commands;
- on each aggregate implementation implement the adequate 

**Tasks**:
- [ ] create the mechanism above for the abstract aggregate to check for consistency after (maybe automatic loading) of the root entity  [@pedrosousabarreto ]
- [ ] create a "LastOffset" structure in libInfrastructure to store topicName, partitionId and offset [ @? ]
- [ ] for participants, change the agg to use the offset consistency check mechanis [ @? ]
- [ ] for transfers we use the state field to control [ @? ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by pedrosousabarreto** [comment]
Not that easy, we'll have to come back to this later - for now there is not much value if we assume that we can run this with auto-commit = false and the new kafkajs consumer
