### ISSUE TITLE
Regular Security Patches + Updates - June

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1439]
## **Goal**:
As an `OSS Developer` I want to `address github and npm security updates` so `Mojaloop stays secure, and developers can put their trust in a well managed codebase`.

This is a reoccurring ticket, to track regular manual security updates

**Repos Reviewed**
- [oracle-shared-library](https://github.com/mojaloop/oracle-shared-library)
- [central-object-store](https://github.com/mojaloop/central-object-store)
- [central-services-health](https://github.com/mojaloop/central-services-health)
- [central-services-error-handling](https://github.com/mojaloop/central-services-error-handling)
- [event-stream-processor](https://github.com/mojaloop/event-stream-processor)
- [forensic-logging-client](https://github.com/mojaloop/forensic-logging-client)

**Tasks**:
- [x] resolve all open github security alerts (many could be ignored as they were for `devDependencies`)
- [x] updated the `npm run audit:check` to ignore devDependencies (for the vulnerable repos only, this will be done eventually for other repos)

**Acceptance Criteria**:
- [x] Github Security Alerts Addressed
- [x] PRs opened and merged with security patches
- [x] `npm audit` resolved/ignored where applicable

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-health/pull/221
- [x] https://github.com/mojaloop/central-services-error-handling/pull/150
- [x] https://github.com/mojaloop/central-object-store/pull/10
- [x] https://github.com/mojaloop/oracle-shared-library/pull/7
- [x] https://github.com/mojaloop/event-stream-processor/pull/27

- [ ] TBD

## **Follow-up**:
- [ ] https://github.com/mojaloop/project/issues/1460 (hapi updates broke unit tests, this requires more work on the tests not covered here)

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: @godfreykutumela
