### ISSUE TITLE
DevSecOps - Remove npm-run-all dependency from across all repos

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1440]
## **Goal**:
As a `project maintainer` I want to `remove the npm-run-all` dependency so that I can `be free from ambiguous licenses in modules`

The `npm-run-all` dependency requires a bunch of packages, including `spdx-exceptions@2.2.0`, which has a `CC-BY-3.0` license, which in turn requires attribution. This is a little ambiguous for us to deal with, and an easier option would be to remove the `npm-run-all` package altogether, especially since we don't seem to be using it much.

**Tasks**:
- [ ] find alternative to `npm-run-all`, one option could be that we don't really need it at all...
- [ ] replace `npm-run-all` with alternative 
- [ ] Apply to the following packages:
    - [ ] account-lookup-service
    - [ ] central-end-user-registry
    - [ ] central-ledger
    - [ ] central-settlement (note this is in the dependency tree because it for some reason depends on `central-ledger`...)
    - [ ] event-stream-processor
- [ ] update the common license-scanner config (https://github.com/mojaloop/license-scanner), to no longer whitelist `spdx-exceptions`, and add `npm-run-all` to the blacklist.

**Acceptance Criteria**:
- [ ] License scans reveal no more `spdx-exceptions` package
- [ ] packages updated as above
- [ ] license scanner whitelist/blacklist updated
- [ ] Unit Tests pass
- [ ] Integration Tests pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @lewisdaly

**Comment by lewisdaly** [comment]
@godfreykutumela is someone working on this?

**Comment by godfreykutumela** [comment]
No one @lewisdaly and please have a look at it and advise you can close it before friday otherwise we should move it to next PI.

**Comment by lewisdaly** [comment]
Yeah I'm happy to leave it to next PI. This was one of a few tickets I identified as being good for newcomers and not all that urgent, so I'd like to leave for now.

**Comment by godfreykutumela** [comment]
Cool let's move it to next PI. In the next PI, I have planned to have a specific set of tasks reserved for open source developers so this will be the first. Thanks @lewisdaly

**Comment by godfreykutumela** [comment]
Deferred to PI 12

**Comment by godfreykutumela** [comment]
@lewisdaly Did we address this one? It has a long history from the last PI so let's aim to close this PI

**Comment by lewisdaly** [comment]
Nope. We can close as out of scope for now... it will be addressed in v2 arch

**Comment by godfreykutumela** [comment]
Noted thanks @lewisdaly
