### ISSUE TITLE
Automated Script to help manage OSS Rancher Perf Environment

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1441]
## **Goal**:
As a <stakeholder> I want to <action> so that <reason>

**Tasks**:
- [x] NodeJS script/app to handle the configuration of a Rancher performance Environment
   - [x] Run initial nvme config on identified i3.xxx machines, and remove/modify label indicating that they have been configured
- [x] Adding Removing Nodes (no need to remove pools, we can simply scale them to 0)
- Scripts
    - [x] Bash Config scripts for NVME [ @mdebarros ]
    - [x] Bash setup for CloudWatch agent [ @lewisdaly ]
- Setup
    - [x] Configure Scripts for Perf1 Env Node Pools
    - [x] Configure Scripts for weekend shutdown

**Assumptions**:
- Master nodes will remain, only worker nodes will be dynamically configured, started and destroyed

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/345

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Initial work going on in this repo: https://github.com/mojaloop/rancher-scaler

Basic scaling is working and has been validated on a test cluster. I'm working now on providing the tools to be able to run a script on after the nodes are up and running.

**Comment by lewisdaly** [comment]
Touched base with Miguel about this today.
- bootstrap script is working now, and has been validated on i3 nodes
- improved format and slack messages etc.

It sounds like we will just apply this on the `perf` environment, and:
- scale up on demand (no need to schedule the scale up at this stage)
- scale down on saturday morning, with 30 minute warning in advance

Next steps:
- [ ] start work on a helm chart
- [ ] add affinities and tolerations to make sure crons get scheduled based on the `controlplane` label
- [ ] break out cloudwatch install into separate script
- [ ] investigate dashboards in more detail: 
    - can we improve the Grafana dashboards with the missing metrics that we were using cloudwatch for?
    - can we automatically create and destroy the aws dashboards as needed?

**Comment by lewisdaly** [comment]
I ended up just using a node selector + affinity to get the pods scheduled in the right place, but now it seems they might not have public internet access to call the slack api from the masters.

**Comment by lewisdaly** [comment]
Ok. We are fixing the above by simply deploying on the master rancher cluster.

Regarding the dashboards it appears that prometheus is grabbing in node information using the [node_exporter](https://github.com/prometheus/node_exporter). The challenge here is that we only get the ip addresses of the nodes, and not the other important information (like which node pool, instance type) that will help when building out the dashboards.

This issue may help with attaching some of that information, but I don't know all that much about prometheus:
https://github.com/prometheus/node_exporter/issues/1528

**Comment by lewisdaly** [comment]
This doc will help understand the metrics that prometheus is gathering: https://docs.signalfx.com/en/latest/integrations/agent/monitors/prometheus-node.html

**Comment by lewisdaly** [comment]
Helm release is working, I'm just now debugging some newer issues with the hourly crons that will prove everything to be working.

**Comment by lewisdaly** [comment]
@mdebarros - I think this one can be considered done now. What do you think?
