### ISSUE TITLE
QA : Validate fspiop-uri header missing in PUT /transfers callback - #1408

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1443]
## **Goal**:
As a QA I want to validate #1408 and add postman test in GP test collection
so that it can be validated and tested in regression

**Tasks**:
- [x] Validate fspiop-uri header missing in PUT /transfers callback - #1408 - this test is present in the MojaSims collection
- [x] Add postman test in legacy test.
- [x] verify in dev2 environment

**Acceptance Criteria**:
- [x] Postman test added to GP legacy test

## **Pull Requests**:
- [x] https://github.com/mojaloop/postman/pull/140

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by amarmodus** [comment]
<img width="943" alt="Screenshot 2020-07-09 09 13 25" src="https://user-images.githubusercontent.com/53434415/87014793-88bc1600-c1c4-11ea-9aea-b417affe7456.png">
