### ISSUE TITLE
Testing Toolkit - 95% Test coverage

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1445]
## **Goal**:
As a maintainer _of the OSS Testing tool-kit_
I want to _ensure there are unit tests for the code base_ for at least 95% of the code.

**Tasks**:
- [x] 85% code coverage
- [x] 90% code coverage
- [x] 95% code coverage
- [x] Discuss with team and fix the threshold values for functional, branch and line coverage
- [x] Update the thresholds in CICD

**Acceptance Criteria**:
- [x] 95% test coverage for backend service
- [x] CICD updated with the new thresholds for both PRs and releases

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/73

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @georgi-logodazhki 
- QA/Review: @vijayg10

**Comment by georgi-logodazhki** [comment]
![ml-testing-toolkit-test-coverage](https://user-images.githubusercontent.com/63578894/86469631-72383980-bd42-11ea-861a-4163daa4551b.png)
