### ISSUE TITLE
QA : Validate and confirm postman tests for bugs #1378 and #1332

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1446]
## **Goal**:
As an adopter of Mojaloop
I want to know that fixes for #1378 and #1332 are validated
so that they can be validated and also postman tests available for regression testing

**Tasks**:
- [x] Validate #1378 - ExtensionList missing when unsupported version requested
- [x] Validate #1332 - Enable configuration to support on-us transactions
- [x] verify postman test for 1378
- [x] verify postman test for 1332

**Acceptance Criteria**:
- [x] Postman test available in legacy collection (release/10.4.0)
- [x] Postman test passes in dev environment

## **Pull Requests**:
- [x] mojaloop/postman#118

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by amarmodus** [comment]
<img width="1282" alt="Screenshot 2020-06-29 at 22 26 43" src="https://user-images.githubusercontent.com/53434415/86057768-b207d400-ba57-11ea-9393-42d3fe47611e.png">
