### ISSUE TITLE
QA : Validate and confirm postman tests for bugs #1381 and #1335

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1447]
## **Goal**:
As a implementer of Mojaloop
I want to see fixes for #1381 and #1335 validated (bug/features)
so that they can be validated and that postman tests available for regression testing

**Tasks**:
- ~~[ ] Validate #1381 - PAYEE flag disables notification to PAYER~~
- [x] Validate #1335 - Handling 'ABORTED' on a PUT /transfers/{ID} (Fulfil step)
- ~~[ ] verify postman test for 1381~~
- [x] verify postman test for 1335

**Acceptance Criteria**:
- [x] Postman test available in legacy collection
- [x] Postman test passes in dev environment

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by amarmodus** [comment]
1381 changes are not applicable any more with PATCH changes in v1.1.
