### ISSUE TITLE
Automated testing (unit) for bulk transfers-related code in central ledger

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1450]
## **Goal**:
As QA
I would like to have (automated) unit tests for bulk transfers-related code in central ledger
to ensure quality and avoid regressions.

**Tasks**:
- [ ] Unit tests for all bulk transfers-related code are written and tested
  - [ ] src/domain/bulkTransfer/index.js
  - [ ] src/handlers/bulk/index.js
  - [ ] src/handlers/bulk/fulfil/handler.js 
  - [ ] src/handlers/bulk/prepare/handler.js 
  - [ ] src/handlers/bulk/processing/handler.js
  - [ ] src/handlers/bulk/shared/validator.js 
  - [ ] src/models/bulkTransfer/bulkTransfer.js 
  - [ ] src/models/bulkTransfer/facade.js 
  - [ ] src/models/bulkTransfer/bulkTransferAssociation.js 
  - [ ] src/models/bulkTransfer/bulkTransferDuplicateCheck.js 
  - [ ] src/models/bulkTransfer/bulkTransferExtension.js 
  - [ ] src/models/bulkTransfer/bulkTransferFulfilmentDuplicateCheck.js 
  - [ ] src/models/bulkTransfer/bulkTransferStateChange.js 
  - [ ] src/models/bulkTransfer/individualTransfer.js 
  - [ ] src/schema/bulkTransfer.js 

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
