### ISSUE TITLE
Postman tests for bulk transfers negative scenarios

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1451]
## **Goal**:
As QA
I would like to have Postman tests for bulk transfers negative scenarios
to ensure quality and avoid regressions.

**Tasks**:
- [x] Postman tests for bulk transfers negative scenarios are written and tested including error callbacks [@oderayi] 

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/bulk-api-adapter/pull/33
- [x] https://github.com/mojaloop/postman/pull/129
- [x] https://github.com/mojaloop/simulator/pull/198

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
