### ISSUE TITLE
Tests to cater for updated regex for Accented & other unicode Characters

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#1452]
## **Goal**:
As an adopter of Mojaloop

I want to have TTK tests (new or existed ones updated) for APIs that are using OpenAPI Backend

so that we can have thorough regression tests and ensure that Accent characters and multiple language scripts are supported.

**Tasks**:
- [x] Enhance TTK to support new regex for names in spec files
- [x] Update regex in TTK v1.1 and v1.0 to use the updated interpretation
`pattern: '^(?!\s*$)[\p{L}\p{gc=Mark}\p{digit}\p{gc=Connector_Punctuation}\p{Join_Control} .,''-]{1,128}$'`
- [x] TTK tests
  - [x] ALS, Quotes tests and ENV variables for
    - [x] Unicode characters - accented
    - [x] Unicode characters - Burmese

**Acceptance Criteria**:
- [x] TTK supports new regular expression for names that supports unicode characters (and scripts)
- [x] Regression Tests for accented and Burmese character. pass
- [x] Code Style & Coverage meets standards
- [x] Tests covering Regular expressions and unicode characters are available for 
    - [x] Unicode characters - accented
    - [x] Unicode characters - Burmese

## **Pull Requests**:
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/48
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/186

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: v1 core team
- QA/Review: @elnyry-sam-k , @vijayg10 , @mdebarros

**Comment by elnyry-sam-k** [comment]
Released with https://github.com/mojaloop/testing-toolkit-test-cases/releases/tag/v13.0.2
