### ISSUE TITLE
Testing Toolkit - Caching functionality and scripting capability for inbound requests

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1453]
## **Goal**:
As a user of the testing toolkit I want to have an option to store the inbound requests for future processing.

**Note**:
It would be great if there is some **_scripting functionality_** so that I can do some calculations before storing them.

**Tasks**:
- [x] Design the functionality [ @vijayg10 ]
- [x] Required changes in the backend
- [x] Required changes in the frontend
- [x] Update the documentation with an example use case
- [x] Unit tests

**Acceptance Criteria**:
- [x] The caching functionality is working for the inbound requests
- [x] Documentation is updated with an example use case

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/74
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/34

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @georgi-logodazhki 
- QA/Review: @vijayg10

**Comment by vijayg10** [comment]
This is the initial idea for implementing caching on inbound requests and scripting capability like in outbound transfers.

![TTK-caching-functionality](https://user-images.githubusercontent.com/33152110/85847296-c1232380-b7c4-11ea-8b70-3dea364f84bc.jpg)

**Comment by georgi-logodazhki** [comment]
![ml-testing-toolkit-test-coverage](https://user-images.githubusercontent.com/63578894/86374003-bc5ee380-bc8c-11ea-8143-71517a28b3a8.png)
