### ISSUE TITLE
Testing Toolkit - Capabilities to host the toolkit (design and identify gaps)

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1454]
## **Goal**:
As a Hub operator I want to have a hosted solution for the testing toolkit so that I can direct my DFSPs to that portal for testing their implementation easily.

**Tasks**:
- [x] List the initial requirements for hosting the testing toolkit (Security, scalability, distributed cache, database...etc)
- [x] Propose the changes required
- [x] Discuss and prioritise the features and finalise the possible changes for this PI
- [x] Document the observations and gaps to be addressed
- [x] Create stories for the agreed changes

**Acceptance Criteria**:
- [x] Designs and observations are documented
- [x] Scope is finalised
- [x] Features are prioritised for this PI
- [x] Stories are created for this PI

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @elnyry-sam-k

**Comment by vijayg10** [comment]
### Security
 * Admin API - Authentication (JWS, Oauth ..etc)
 * Sync API - Some kind of security to avoid requests from unauthorized fsps and to avoid flooding attacks (....TBD)

  ### DFSP wise environment (Rules and settings)
 * Rules and settings should be stored per DFSP
 * Base URL should be unique for each DFSP (Eg: http://somehub.com/ttk/dfsp1/quotes)
 * Callbacks and events should be handled properly in case of outbound test case execution
 * Cache should be stored DFSP wise
 * Authentication for DFSPs to send spec APIs

### Scalability
 * Distributed Cache
 * Quotes and transfer association - Quote storage in shared space
 * Connection manager - Certificates sharing among pods
 * Inbound caching - Should be stored in shared space
	**Proposed Technologies:** Redis
 * Event emissions and listeners
 * Outbound Test Case Execution - Listen for callbacks (If the callback came to different pod, then the executor pod should be notified)
	**Proposed Technologies:** Kafka, socket.io (not sure)
 * Websocket messaging to client
 * Websocket server should support cluster pattern
         **Proposed Technologies:** Socket Cluster IO

### Logs & Reports persistent storage
 * Server side storage of logs and reports
    **Proposed Technologies:** NoSQL(mongodb) or MySQL (Need to select one based on the usage)

**Comment by vijayg10** [comment]
### DFSP wise environment - Changes required
* Change **_mb-connection-manager_** to use object store to store and get data (certs and keys)
* Implement endpoints provisioning functionality using **_mb-connection-manager_**
* Standardise / Refactor the methods in object store and make it like an interface to easily switch between the storage mechanisms
* Store object store in redis or mongodb (discuss with the team and make decision)
* Change callback map file and refactor the code to specify the path in an inbound request from where fspid for the callback to be taken (like FSP-source from header for fspiop requests)
* Create a model class for config and refactor the config to store per DFSP
* Refactor the rules file per DFSP
* Change import and export functionality according to the new system
* Separate event emitter DFSP wise
* Separate notificationEmitter DFSP wise
* Refactor the logging functionality
* Refactor **_rulesEngineModel_**
* Some refactoring in targeted notifications
