### ISSUE TITLE
ExtensionList missing when unsupported accept version requested for services

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1456]
**Summary**:

When wrong accept header is supplied in the request header, following error information is sent and extension list is missing.

```
{
    "errorInformation": {
        "errorCode": "3001",
        "errorDescription": "Unacceptable version requested - Client requested to use a protocol version which is not supported by the server"
    }
}
```

**Expected Behavior**
```
{ 
     "errorInformation": { 
               "errorCode": "3001", 
                "errorDescription": "The Client requested an unsupported version, see extension list for supported version(s).", 
                  "extensionList": [ 
                           { "key": "1", "value": "0" }, 
                           { "key": "2", "value": "1" }, 
                           { "key": "4", "value": "2" } 
                    ]
         } 
} 
```

**Steps to Reproduce**
  ```
curl --location --request POST 'http://dev2-quoting-service.mojaloop.live/quotes' \
--header 'Accept: application/vnd.interoperability.quotes+json;version=3' \
--header 'Content-Type: application/vnd.interoperability.quotes+json;version=1.0' \
--header 'Date: Mon, 29 Jun 2020 10:32:27 GMT' \
--header 'FSPIOP-Source: payerfsp' \
--header 'FSPIOP-Destination: payeefsp' \
--header 'FSPIOP-Signature: {"signature":"iU4GBXSfY8twZMj1zXX1CTe3LDO8Zvgui53icrriBxCUF_wltQmnjgWLWI4ZUEueVeOeTbDPBZazpBWYvBYpl5WJSUoXi14nVlangcsmu2vYkQUPmHtjOW-yb2ng6_aPfwd7oHLWrWzcsjTF-S4dW7GZRPHEbY_qCOhEwmmMOnE1FWF1OLvP0dM0r4y7FlnrZNhmuVIFhk_pMbEC44rtQmMFv4pm4EVGqmIm3eyXz0GkX8q_O1kGBoyIeV_P6RRcZ0nL6YUVMhPFSLJo6CIhL2zPm54Qdl2nVzDFWn_shVyV0Cl5vpcMJxJ--O_Zcbmpv6lxqDdygTC782Ob3CNMvg\",\"protectedHeader\":\"eyJhbGciOiJSUzI1NiIsIkZTUElPUC1VUkkiOiIvdHJhbnNmZXJzIiwiRlNQSU9QLUhUVFAtTWV0aG9kIjoiUE9TVCIsIkZTUElPUC1Tb3VyY2UiOiJPTUwiLCJGU1BJT1AtRGVzdGluYXRpb24iOiJNVE5Nb2JpbGVNb25leSIsIkRhdGUiOiIifQ"}' \
--header 'Authorization: Bearer {{TESTFSP1_BEARER_TOKEN}}' \
--data-raw '{
  "quoteId": "b5031edb-eca0-4120-989b-606a174b0ab5",
  "transactionId": "845b458f-0c6d-4244-8d91-07327b232389",
  "payer": {
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "{{payerMSISDN}}",
      "fspId": "payerfsp"
    },
    "personalInfo": {
      "complexName": {
        "firstName": "Mats",
        "lastName": "Hagman"
      },
      "dateOfBirth": "1983-10-25"
    }
  },
  "payee": {
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "22556999125",
      "fspId": "payeefsp"
    }
  },
  "amountType": "SEND",
  "amount": {
    "amount": "60.11",
    "currency": "USD"
  },
  "transactionType": {
    "scenario": "TRANSFER",
    "initiator": "PAYER",
    "initiatorType": "CONSUMER"
  },
  "note": "hej"
}'
```

**Severity**:
Medium

**Priority**:
Low

**Specifications**
  - Component (if known): Error framework
  - Version:v10.1.0 
  - Platform: 
  - Subsystem:
  - Type of testing: Manual postman test 
  - Bug found/raised by: @amarmodus 

**Notes**:

- Severity when opened:
- Priority when opened:

https://github.com/mojaloop/project/issues/1378 - this is opened for similar issue but for content header version.

**Tasks**:
- [x] Fix bug in Central Services Shared library
- [x] Update CS-Shared in ML-API Adapter
- [x] Update CS-Shared in Central Settlement
- [x] Update CS-Shared in Central Ledger
- [x] Update CS-Shared in Central Event Processor
- [x] Update CS-Shared in ALS
- [x] Update CS-Shared in Simulator
- [x] Update CS-Shared in Bulk API Adapter
- [x] Update CS-Shared in Quoting Services
- [x] E2E validation across all services updated

**PRs**:
- [x] https://github.com/mojaloop/central-services-shared/pull/235
- [x] https://github.com/mojaloop/ml-api-adapter/pull/447
- [x] https://github.com/mojaloop/central-settlement/pull/313
- [x] https://github.com/mojaloop/central-ledger/pull/752 [Superseded by subsequent PRs]
- [x] https://github.com/mojaloop/central-event-processor/pull/206 [Superseded by subsequent PRs]
- [x] https://github.com/mojaloop/simulator/pull/201 [Superseded by subsequent PRs]
- [x] https://github.com/mojaloop/bulk-api-adapter/pull/35 [Superseded by subsequent PRs]
- [x] https://github.com/mojaloop/account-lookup-service/pull/360 [Superseded by subsequent PRs]
- [x] https://github.com/mojaloop/quoting-service/pull/229 [Closed to be completed in #247] 
- [x] https://github.com/mojaloop/quoting-service/pull/247

**Comment by claudio-viola** [comment]
PR: https://github.com/mojaloop/central-services-shared/pull/235/files

**Comment by elnyry-sam-k** [comment]
@claudio-viola - are you done with this? Thanks for the effort..

**Comment by oderayi** [comment]
Closing to continue implementation and validation of FSPIOP headers in some of the services that could not be validated in this story. https://github.com/mojaloop/project/issues/1854
