### ISSUE TITLE
Investigate alternate libraries to cater for characters from different language scripts

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#1457]
## **Goal**:
As an implementer of Mojaloop
I want to cater for multiple language scripts in the API messages
so that when the switch is implemented in a region with alternate language scripts, the requests to the switch do not fail

**Tasks**:
- [ ] Validate that the existing regex for scripts is valid for all scripts '^(?!\s*$)[\p{L}\p{Nd} .,'-]{1,128}$'
- [ ] Look for alternate libraries the cater for the regex we currently use

**Acceptance Criteria**:
- [ ] Test solution to ensure that scenarios such as "Burmese characters" are catered for

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rmothilal 
- QA/Review: @rmothilal @elnyry-sam-k

**Comment by elnyry-sam-k** [comment]
new regular expression used now (which is an exact interpretation of the regex from the FSPIOP spec), with increased support for unicode chars in ajv, openapi-backend libraries in recent versions. See #2358 for more details
