### ISSUE TITLE
DevSecOps - Reduce noisy pull request notifications

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1458]
## **Goal**:
As an `OSS Maintainer`
I want to `reduce the number of 'noisy' pull request notifications`
so that `I can have more clarity on urgent dependency vulnerabilities`

The main goal here is to cut back on dependabot notifications, but this could be useful for other PR notifications.

**Tasks**:
- [ ] investigate https://github.com/apps/weekly-digest
- [ ] can we turn off PR notifications for _only_ dependabot/based on a label?

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
So we can get all PRs that dependabot has created pretty easily:

https://github.com/pulls?q=is%3Apr+author%3Aapp%2Fdependabot-preview+org%3Amojaloop+is%3Aopen

The trouble will be an individual's PR notification settings. As far as I can find, there is no way to make a PR that will _not_ trigger a notification, but I'm still investigating.

**Comment by lewisdaly** [comment]
The weekly-digest tool looks interesting, but it is per-repo. I'm looking into if we can modify it for all repos (or better yet, an organization level)

**Comment by lewisdaly** [comment]
So there isn't too much to the weekly-digest tool, it's likely we could customize it pretty extensively to suit our needs, and potentially share our changes upstream with others.

We could post a weekly dependabot digest across all repos, which would live as an issue in the `mojaloop/mojaloop` repository. 

This would require individual contributors to:
- disable all PR notifications, _or_ apply some email filtering rules to hide the dependabot PRs (we can provide some nice instructions perhaps)
- watch the `mojaloop/mojaloop` repository to get the weekly digest emailed to them - the weekly digest _lives_ as an issue, instead of a standalone email.

**Comment by godfreykutumela** [comment]
PI 11 Backlog

**Comment by godfreykutumela** [comment]
Deferred to PI 12

**Comment by lewisdaly** [comment]
I think this is out of scope. It has been covered by a combination of:
- reducing the frequency of dependabot checks to once a week
- changing the owners + admins groups in the Mojaloop org so that notifications go to the relevant people (at least in principle... Github can still be a spambot at times)

**Comment by godfreykutumela** [comment]
Cool Thanks @lewisdaly
