### ISSUE TITLE
Bulk Transfers: Sequence diagram update for POST /bulkTransfers duplicate check

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1459]
## **Goal**:
As an OSS Maintainer
I want to update design for bulk transfers duplicate check for the `POST /bulkTransfers` end-point
so that we can have up-to-date documentation capturing changes done in the Performance stream.

**Tasks**:
- [ ] Update documentation (sequence diagrams) to match current implementation for duplicate checks on `POST /bulkTransfers`

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
should be addressed during refactoring for reference architecture implementation
