### ISSUE TITLE
Update Hapi dependency in oracle-shared-library

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1460]
## **Goal**:
As a `OSS Developer`
I want to `keep dependencies up to date`
so I can `ensure the security of Mojaloop and improve maintainability`

**Tasks**:
- [ ] update `oracle-shared-library` to the latest version of `@hapi/hapi`
- [ ] fix broken unit tests (tests currently fail with wrong response codes after the upgrade)
- [ ] improve unit tests to check the response body as well as response codes

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
