### ISSUE TITLE
Precompile the Kafka bindings  on host (OSx, Linux, Windows) and in docker containers to avoid long recompilation process during npm install

### ISSUE THREAD

**Issue by claudio-viola** [mojaloop/project#1461]
## **Goal**:
As a developer I want to 
- save precious and costly time while installing node-rkafka  
  both locally and inside docker containers 
   by avoiding re-compilation of the kafka bindings across services for the different OSes during npm install
- so that I can work happily ever after

node-rkakfa gets reinstalled and recompiled each time we build a new container (without cache) or when we update package.json leading to a huge waste of time from developers. Find a way to prepackage it into the container reducing container installation before npm install is run inside the container

Some info on the reasoning here https://rclayton.silvrback.com/thoughts-on-node-rdkafka-development and a similar issue here https://github.com/Blizzard/node-rdkafka/issues/664
tried several approaches but still haven’t managed to make it work. This is a massive waste of time on engineer resource when having to build containers and the cache gets busted

What I attempted without success

1. global install npm install -g node-rkafka 

2. building librdkafka from source https://github.com/Blizzard/node-rdkafka/issues/664 - Connect to preview 

3. Installing with NODE_ENV='/usr/local/lib/node_modules' doesn’t pick it up and rebuilds the package already installed 

4. Using npm link on the global package unfortunately npm link is broken too . It may be also because we are installing it within a scoped package  https://github.com/npm/npm/issues/17287 - Connect to preview  https://docs.npmjs.com/using-npm/scope 

**Tasks**:
- [1] Provide or update  on boarding documentation for Mac OSx , Linux and Windows on how to preinstall / precompile / install globally the kafka library so that  when doing npm install on all the services the compilation step does not happen and the service works the same
- [2] Provide an example of a docker container  which install and precompile kafka before the npm install so that this step remain cached even when package.json gets updated for other libraries / scripts
- [3] Update all docker files to use a precompiled node kafka library before the npm install step with the solution found at 2

**Acceptance Criteria**:
- node-rkafka is installed globally on OSx and it does not get recompiled / reinstalled when doing npm install on multiple mojaloop services   (central settlement, central-ledger, etc)
- node-rkafka  is installed globally on Linux and it does not get recompiled / reinstalled when doing npm install on multiple services  
- node-rkafka  is installed globally on Windows and it does not get recompiled / reinstalled when doing npm install on multiple services  
- node-rkafka  is precompiled inside docker containers before the npm install step

- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
