### ISSUE TITLE
Feature to support final notification to a Payee FSP, a PATCH call - continue

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1462]
## **Goal**:
As a Payee FSP
I want to _receive a notification of finalization of a transfer_
so that _I can use it to make informed decisions on down stream release of funds / payments_

As a Hub
I want the _option to notify Payee of a finalized transfer_
so that _the Payee FSP has more information regarding the final status of a transfer at the Hub_

**Note**:
- Issue from mojaloop-specification here: https://github.com/mojaloop/mojaloop-specification/issues/29
- Issue to access version v1.1 of the API Definition and Swagger: https://github.com/mojaloop/mojaloop-specification/issues/52#issuecomment-618636582

**Tasks**:
- [x] Present designs to the DA (though already reviewed, discussed and approved)~ created follow up story (already done)
- [x] Implementation to support the PATCH notification and use the new Swagger v1.1
  - [x] ~sdk-standard-components~ no need to change that component for this functionality
  - [x] sdk-scheme-adapter
    - added env var for request for notification functionality.
  - [x] ~mojaloop-simulator~ if requested, scenarios can be added on later stage

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] A notification to a Payee FSP, via a PATCH call on finalization of a transfer can be made if requested by the Payee FSP

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/181
## **Follow-up**:
- N/A

**Dependencies**:
- #1334 

## **Accountability**:
- Owner: @vgenev
- QA/Review: @elnyry
