### ISSUE TITLE
Update Helm charts to support Kubernetes deployments 1.15 and later versions

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1463]
## **Goal**:
As a `OSS Contributor` I want to `implement support for API Version checks on Helm charts` so that `Mojaloop helm charts can be deployed on both legacy and v.1.15+ versions of Kubernetes`

**Tasks**:
- [ ] Add version template helper function
- [ ] Update templates to set `apiVersion` by using template helper function

**Acceptance Criteria**:
- [ ] Mojaloop Helm Charts support being deploying on K8s v1.15
- [ ] Mojaloop Helm Charts support being deploying on K8s v1.16

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
