### ISSUE TITLE
Testing Toolkit - Persistent logs and reports

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1467]
## **Goal**:
As a Scheme
I want to enable persistent logging and reporting for the Scheme's DFSPs
so that they can view them at any point of time.

**Acceptance Criteria**:
- [x] Reports of transactions are stored in a persistent storage
- [x] Logs of transactions are stored in a persistent storage
- [x] Report history is available in the UI
- [x] Log history is available in the UI

**Tasks**:
- [x] Logs should be stored in the database based on the system config param (HOSTING_MODE) DFSP wise
- [x] Change and improve the user interface to show the live logs along with those stored in the database
- [x] Reports should be stored in the database if HOSTING_MODE is enabled
- [x] Add a page to view the report history
- [x] Unit tests

## **Pull Requests**:
- [ ] https://github.com/mojaloop/ml-testing-toolkit/pull/96
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/50
- [ ] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/52

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @georgi-logodazhki 
- QA/Review: @vijayg10
