### ISSUE TITLE
PI-11 Community event presentations, demos - core team

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1473]
## **Goal**:
As a contributor team for the ML OSS
I want to prepare presentation and content for the PI-11 Community event
so that it can be used to demonstrate Mojaloop capabilities to the Community and for discussions

**Tasks**:
- [x] Create and share slide-deck template
- [x] Identify various sections, sub-topics and their owners
- [x] Prep for Demos
  - [x] Testing toolkit demos [@vijayg10 , @georgi-logodazhki ]
  - [x] Accented characters [@rmothilal ]
  - [x] Bulk transfers [@rmothilal , @oderayi ]
  - [x] On-us transfers [@vijayg10 ]
  - [x] v1.1 changes (ABORTED change, ExtensionList, PATCH notification) [@vgenev  ]
- [x] Update presentation slide deck
  - [x] Overview and introduction section [@elnyry-sam-k ]
  - [x] Bulk Transfers
  - [x] ML FSPIOP v1.1 changes [@vgenev , @elnyry-sam-k ]
  - [x] Other updates
    - [x] Helm Releases
    - [x] Accented characters
    - [x] Bug Fixes
    - [x] On-us transfers
  - [x] CCB updates [@elnyry-sam-k ]
  - [x] Testing toolkit slides [@vijayg10 . @elnyry-sam-k ]
  - [x] QA section [@amarmodus , @elnyry-sam-k ]
  - [x] Roadmap for PI-11 [@elnyry-sam-k ]
- [x] Review presentation and items to discuss

**Acceptance Criteria**:
- [x] A slide-deck is prepared for use during the PI-11 Community Event to inform / share progress regarding objectives and provide details as necessary. 
- [x] The slide deck covers all significant items worked on so far in PI-10 and also bring forth any significant design decisions.
- [x] Demo items are finalized and prepared

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @elnyry @mdebarros 
- QA/Review: OSS Core team
