### ISSUE TITLE
Simplify / Improve Mojaloop "project" Backlog

### ISSUE THREAD

**Issue by ramakrishnan-sankar** [mojaloop/project#1478]
`As a` Community Member 
`I want to` simplify / improve the backlog structure and dynamically generate reports where feasible within the constraints of ZenHub
`so that `
we (teams / community) can continuously improve

(Note: Community Member is used as placeholder persona - persona may be refined later)

**Acceptance Criteria:**
- [x] Refined / Simplified backlog structure aligned with Product Owner (Sam) [and team]
- [x] Improved transparency to promote continuous improvement
---
### Tasks
**Backlog Structure** 
- [x] Refine
- [x] Review with Team
- [x] Implement

**Pipeline**
- [x] Refine
- [x] Review with Team
- [x] Implement

**Labels**
- [x] Define
- [x] Implement

**Reports**
- [x] Define
- [x] Implement

**Release Plan**
- [ ] ~Define~
- [ ] ~Implement~

**Roadmap**
- [x] Define
- [x] Implement
