### ISSUE TITLE
Document the topics and events that are currently used in the ML Core services

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1479]
## **Goal**:
As a Technical Community Contributor to Mojaloop
I want to _find details of the various Kafka topics and events used in the Mojaloop Core services_
so that _I can get a better understanding of the core services and use it for technical contributions_

As a Tech Ops team member
I want to _find details of the various Kafka topics and events used in the Mojaloop Core services_
so that _I can get a better understanding of the core services and use it for debugging, triaging and identifying issues_

**Tasks**:
- [ ] Document Kafka Topics used in Mojaloop Core services, include partitions details where used
- [ ] Document events used in Mojaloop Core services
- [ ] Follow-up by revisiting sequence diagrams (can be a follow-up story based on scope)

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Documentation is available on docs.mojaloop.io for Kafka Topics and Events used in Mojaloop Core services

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
