### ISSUE TITLE
Design, Implement "common streaming library"

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#148]
**Goal**:
As a developer of the system, I would like to Design, Implement "common streaming library" so that it can be tested later on and used/re-used.

**Tasks**:
- [x] Design "common streaming library", with APIs for consumers and producers
- [x] Implement "common streaming library"

**Acceptance Criteria**:
- [x] A common streaming library is available for with an API for Kafka producers (pending testing)
- [x] A common streaming library is available for with an API for Kafka consumers (pending testing)

**Risk**:
- [ ] Nodejs Kafka client patch for performance (https://github.com/Blizzard/node-rdkafka/issues/332)
- [ ] #155

**Comment by mdebarros** [comment]
See PR#: https://github.com/mojaloop/central-services-shared/pull/12

See docs: https://github.com/mojaloop/central-services-shared/blob/feature/%23148DesignImplementCommonStreamingLibrary/src/kafka/readme.md

See Unit Test Results: https://297-108914050-gh.circle-artifacts.com/0/home/circleci/project/test/results/tape.xml

See Coverage Check Results: https://298-108914050-gh.circle-artifacts.com/0/home/circleci/project/coverage/lcov-report/index.html

**Comment by mdebarros** [comment]
bump
