### ISSUE TITLE
Testing toolkit: Support for Mojaloop FSPIOP API version 1.1

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1480]
## **Goal**:
As a _Scheme_
I want to _have Templates and Rules in the testing toolkit that support the Mojaloop FSPIOP API Version v1.1_
 so that _I can use it to validate my Hub's and FSP's implementation that follow the v1.1_

**Tasks**:
- [x] Identify changes needed in the Swagger (Swagger version 3.0)
- [x] Provide Swagger 3.0 of he FSPIOP v1.1 [@elnyry-sam-k  ]
- [x] Update the toolkit to use v1.1 in addition to v1.0
- [x] Add templates (if needed)
- [x] Add Rules for the three new changes
  - [x] Usage of "ABORTED" in Fulfil calls (only) `PUT /transfers/{ID}` (v1.1 this usage is prohibited)
  - [x] New PATCH notification and usage of "RESERVED" in Fulfil calls `PUT /transfers/{ID}`
  - [x] Presence of an optional ExtensionList element in `PartyIdInfo` Object and POST /participants/{TYPE}/{ID} call and its alternative
- [x] Add assertions to cover the new changes
- [x] Validate against a dev environment (dev1 or dev2)

**Acceptance Criteria**:
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Version v1.1 of the Mojaloop FSPIOP API is supported by the testing toolkit
- [x] Additional, Rules, templates. assertions are added to support changes introduced in v1.1 of the FSPIOP API

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @elnyry-sam-k

**Comment by elnyry-sam-k** [comment]
Demonstrated at the ML PI-11 Community event
