### ISSUE TITLE
Support for /bulkQuotes - passthrough mode follow-up

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#1485]
## **Goal**:
`As a` Scheme
`I want to` have `/bulkQuotes` support in the Mojaloop OSS implementation documented
`so that` I can use it in bulk Payments scenarios

**Acceptance Criteria**:
- [x] `When` bulk quotes request is sent to SDK Scheme adapter `then`it got passed to the switch, validated and forwarded from there to the other participant
- [x] `When` valid bulk transfer for the bulk quotes is sent to the SDK Sheme adapter `then` it got passed to the switch, and the transfers are committed 

**Tasks**:
- [x] Document high-level on `/bulkQuotes` works in pass-through mode
- [x] Mojaloop Simulator refactored to support `/bulkQuotes`
- [x] SDK-Scheme-Adapter to support /bulkTransfer
- [x] Update Helm scripts with latest created APIs
- [x] Update TTK tests ( Update BulkQuotes Postman test collection to be a separate story )

**Done**:
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Bulk Quotes endpoint `/bulkQuotes` is supported by the Mojaloop simulator
- [x] Bulk Quotes endpoint `/bulkTransfers` is supported by the Mojaloop simulator

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/206

## **Follow-up**:
- Will have follow up discussion and design sessions, maybe, if the functionality is not working as expected

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rmothilal 
- QA/Review: @rmothilal @oderayi @elnyry-sam-k
