### ISSUE TITLE
Change the transfers to the eventSourcing implementation

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#1486]
## **Goal**:
As a developer I want to have the EventSourcing implementation on the transfers aggregate, the same way we have it on the participants

**Tasks**:
- [x] Create StateEvents in the transfers/messages [ @? ]
- [x] Create the transfers aggregate inheriting from BaseEventSourcingAggregate [ @? ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by pedrosousabarreto** [comment]
Done, still on the eveneventsourcing branch waiting for review

**Comment by mdebarros** [comment]
Event-sourcing was removed from transfers due to the high bootstrap latencies. Instead, we are using a standard in-memory cache backed by Redis.
