### ISSUE TITLE
Create the read side event handler that creates the persisted projections for participants & transfers

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#1487]
## **Goal**:
Create the readonly projection event handler - using same repository pattern as with the rest

**Tasks**:
- [x] Create a event handler (participantReadSideEvtHandler) that listens to ParticipantStateEvents topic and creates/updates the read state in mongo [ @? ]
- [x] Create a event handler (transferReadSideEvtHandler) that listens to TransferStateEvents topic and creates/updates the read state in mongo [ @? ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
