### ISSUE TITLE
Re-align DB Model to Mojaloop API

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#149]
**Goal**:
As a developer I would like to realign the DB Model to Mojaloop (Base) API so that I can conform to the Specification

**Tasks**:
- [x] Re-align DB Model to Base API, in this case, the Mojaloop API
- ~Ensure tests are updated and pass~

**Acceptance Criteria**:
- [x] A new ERD is available (that is compatible with the Mojaloop API)
- [x] Apply the ERD to the DB (Migration scripts, etc)

**Dependencies**:
- [x] #153

**Comment by mdebarros** [comment]
@elnyry @NicoDuvenage @vgenev @georgi-sgbg re-opened this story since it was never completed.  Code was never merged into Mojaloop repo, and is sitting in the following fork: https://github.com/georgi-sgbg/central-ledger/tree/feature/%23149reAlignDbModelMigrations

**Comment by mdebarros** [comment]
PR: https://github.com/mojaloop/central-ledger/pull/60

**Comment by ZARDeonBotha** [comment]
![Currentcentral-ledger-schema-5.png](https://images.zenhubusercontent.com/5aafa73a4b5806bc2bcb67ed/26a0ac50-616a-4a1d-879a-e8283ec8966c)
