### ISSUE TITLE
Testing Toolkit - Refactor bulk payments test case to get callbacks without waiting

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1490]
## **Goal**:
As a DFSP I want to have a test case for bulk payments which can run fast so that I can test that without waiting to get callbacks from the simulators.

**Tasks**:
- [x] Investigate the issue occurred with testing toolkit while creating the test case for bulk payments
- [x] Refactor bulk payments test case to get the async callbacks without using setTimeout
- [x] add headers to error callbacks

**Acceptance Criteria**:
- [x] Test case for bulk payments is provided in the load samples section

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/85
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/87

## **Follow-up**:
- N/A

**Dependencies**:
- [ ] https://github.com/mojaloop/project/issues/1523

## **Accountability**:
- Owner: @vijayg10 @georgi-logodazhki 
- QA/Review: @oderayi
