### ISSUE TITLE
Data Protection - Database Security Standard and Guideline

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1494]
## **Goal**:
Review Mojaloop database protection framework (guided by data protection standards) and recommend improvements based on database access, user management, audit logging settings in place in Mojaloop standard deployment environment.

**Tasks**:
- [ ] Document best practice standards for security databases and datastores as guided by PCI-DSS and GDPR @rasputtintin 
- [ ] Identify all Mojaloop databases and datastores @rasputtintin 
- [ ] Document gaps and recommendations @rasputtintin 

**Acceptance Criteria**:
- [ ] Documented best practice standard
- [ ] inventory of Mojaloop databases / datastores and high level context of content (i.e. PII data)

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- Data classification findings
- Mojaloop Architecture

## **Accountability**:
- Owner: @rasputtintin 
- QA/Review: @godfreykutumela

**Comment by rasputtintin** [comment]
@godfreykutumela I will update the story by 17th September

**Comment by godfreykutumela** [comment]
Provide architecture principles for assessing data: @rasputtintin 

1. Always avoid access to the database and limit it to accessing via a services

**Comment by godfreykutumela** [comment]
Deferred to PI 12
