### ISSUE TITLE
Data Protection - PII and PCI DSS Data Identification : Key Findings

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1495]
## **Goal**:
Identify PII and PCI DSS related data within Mojaloop

**Tasks**:
- [x] Analyse Mojaloop logs [ @rasputtintin ]
- [x] Analyse Mojaloop PII Data (Data Classification) [ @rasputtintin ]
- [x] Identification of data sources and sinks [ @rasputtintin ]
- [x] Compile report with findings [ @rasputtintin ]

**Acceptance Criteria**:
- [x] Document PII and PCI DSS Data findings

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @rasputtintin

**Comment by godfreykutumela** [comment]
Draft report
[Data Protection - PII and PCI DSS Data Identification - Key Findings.docx](https://github.com/mojaloop/project/files/5059931/Data.Protection.-.PII.and.PCI.DSS.Data.Identification.-.Key.Findings.docx)

**Comment by godfreykutumela** [comment]
@rasputtintin Please make a final review of this so that we can close it by the end of the current sprint

**Comment by godfreykutumela** [comment]
@rasputtintin Please amend this with the PII detailed data sets and mapping from Mowali's example so that we can move this Review/QA

**Comment by godfreykutumela** [comment]
@rasputtintin Just a reminder to upload the detailed data mapping so that we can close this story before end of the sprint

**Comment by rasputtintin** [comment]
Completed consolidating PII Data Classification findings as attached. High level findings and recommendations

1. Mojaloop applications and database process and store PII data
2. Some sensitive data is stored in application log files
3. There is need to explore security controls centered on data protection focusing on PII data within Mojaloop
4. Recommended protection controls (to be investigated in subsequent PIs) include:
       a. Encryption of data at rest and service mesh security for data in motion within applications
       b. Role based access controls on who can access PII data
       c. Audit logging and monitoring with appropriate alerts
       d. Resilience and recovery in the event of data loss / corruption
       e. Automated PII data recovery controls within Mojaloop where applicable

[Mojaloop Data Classification.docx](https://github.com/mojaloop/project/files/5170500/Mojaloop.Data.Classification.docx)

**Comment by rasputtintin** [comment]
@godfreykutumela please review the report for story closure.
