### ISSUE TITLE
Investigate and resolve issue with GET /bulkTransfers in Mojadev2

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1496]
**Summary**:
While testing out bulk transfers in Mojadev2 with TTK, it was observed that no callbacks were received for GET calls on bulk transfers.

**Tasks:**
- Investigate issues
- Report discovery
- Resolve issue 

**Severity**: Medium
**Priority**: Low

**Expected Behavior**
On `GET /bulkTransfers/{ID}` calls, a PUT callback response should be received from the switch.

**Steps to Reproduce**
  1. Send a `POST /bulkTransfers` (positive scenario e2e)
  2. Send a `GET /bulkTransfers/{ID}`
  3. Monitor the console for the sdk-scheme-adapter for the requesting DFSP, no `PUT` callback is received.

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Notes**:

- Severity when opened:
- Priority when opened:

## Pull Requests: ##
- [x] https://github.com/mojaloop/central-ledger/pull/765
- [x] https://github.com/mojaloop/central-ledger/pull/766
- [x] https://github.com/mojaloop/postman/pull/152
- [ ] https://github.com/mojaloop/helm/pull/352
