### ISSUE TITLE
Get swagger/openapi yaml from api-docs endpoint for openapi-backend

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#1497]
## **Goal**:
As a implementer I want to be able to view API swaggers on the /api-docs endpoint to get the complete swagger/openapi yaml in all openapi-backend APIs

**Tasks**:
- [ ] Create api-docs endpoint in yaml
- [ ] Create reusable service to cater for /api-docs request
- [ ] Updated applicable services
  - [ ] Account-Lookup-Service
  - [ ] Quoting-Service
  - [ ] Transaction-Requests-Service

**Acceptance Criteria**:
- [ ] Swagger/Openapi document returned when the /api-docs endpoint is called
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rmothilal 
- QA/Review: @rmothilal
