### ISSUE TITLE
Test, document and address config for "common streaming library"

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#150]
**Goal**:
As a developer of the system, I would like to Test, document and configure "common streaming library" so that it can be used/re-used later.

**Tasks**:
- [x] Test "common streaming library" - unit tests for producers, consumers
- [x] Document "common streaming library"
- [x] Configure "common streaming library" - default & templates

**Acceptance Criteria**:
- [x] The common streaming library is tested (unit testing), configured
- [x]  Documentation of API is available for configuration and templates, etc.

**Dependencies**:
- [x] #148

**Comment by mdebarros** [comment]
PR: https://github.com/mojaloop/central-services-shared/pull/14
CI/CD: https://circleci.com/workflow-run/ec8502a7-2691-43ca-adb8-1d4bd34be657
Unit Test Results: https://316-108914050-gh.circle-artifacts.com/0/home/circleci/project/test/results/tape.xml
Coverage Test Results: https://317-108914050-gh.circle-artifacts.com/0/home/circleci/project/coverage/lcov-report/index.html

**Comment by mdebarros** [comment]
bump
