### ISSUE TITLE
Testing Toolkit 2.1.2 - Investigate the feasibility and dependencies for implementing Hub-only functionality

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1500]
## **Goal**:
`As a` DFSP 
`I want` to investigate the feasibility, dependencies, and effort in implementing the hub only role in the Testing Toolkit
`so that` I can proceed with the implementation

**Tasks**:
- [x] Outline the functionality needed in detail
- [x] Investigate the dependencies like JWS & TLS handling, endpoint configuration...etc
- [x] Document the observations
- [x] Refactor the relevant stories and re-estimate

**Acceptance Criteria**:
- [x] The dependencies are documented and reviewed by Sam

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
- Should the TTK validate the **JWS signature** or just forward the headers as it received
- There are two approaches identified for configuring the **forward functionality**
  1. Modify callback rules to integrate a new event called "Forward Request" instead of generating callbacks
  2. Implement a new rules engine like 'Forward Rules' to add conditions and forward events (Preferred way)
- For maintaining the **DFSP wise endpoints** we can add a property in user settings like "ENDPOINTS_DFSP_WISE"
- For **Account lookup** what should happen on the testing toolkit side
  - By adding a forward rule for parties with a condition on ID, we can forward the requests to the specified DFSP
- Need refactoring for **mTLS** functionality to maintain DFSP wise certificates like as in hosted mode (Fetch the list of DFSPs from ENDPOINTS_DFSP_WISE in user settings)


![Hub-only-mode](https://user-images.githubusercontent.com/33152110/88914515-5c099480-d280-11ea-95f9-a66c7e691a71.png)

**Comment by elnyry-sam-k** [comment]
Thanks for putting this together @vijayg10
