### ISSUE TITLE
Testing Toolkit - Make sure the oAuth authentication is working with a real oAuth server

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1506]
## **Goal**:
`As a` Scheme
`I want to` make sure that oAuth authentication in the testing toolkit is working with a real oAuth server
`so that` I can use any oAuth server with the testing toolkit

**Tasks**:
- [x] Install and configure a free oAuth server
- [x] Configure and test the oAuth from testing toolkit
- [x] Configure and test the oAuth from connection manager
- [x] Address any gaps in the oAuth implementation
- [x] Document the installation and configuration process of the oAuth server to make it work with testing toolkit in hosted mode

**Acceptance Criteria**:
- [x] The oAuth implementation of the testing toolkit is working with a real oAuth server
- [x] Documentation is available to install and configure a free oAuth server to use with testing toolkit

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/86

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @georgi-logodazhki @elnyry-sam-k
