### ISSUE TITLE
Create Postman test collection to align with sequence diagrams

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#1509]
## **Goal**:
As a developer 
I want to create a mojaloop sequence diagram test collection in postman
so that we can easily show test cases assigned to sequence diagrams and what processes are required

**Tasks**:
- [x] Create Postman collection
- [x] Create mappings according to service then functionality then sequence diagram name
- [x] Create reference Item mapping 
- [x] Implement reference Item tests

**Acceptance Criteria**:
- [ ] Sequence Diagrams are up-to date
- [ ] Postman Tests pass

## **Pull Requests**:
- [ ] https://github.com/mojaloop/postman/pull/153

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rmothilal 
- QA/Review: @elnyry-sam-k @rmothilal

**Comment by rmothilal** [comment]
Moved to blocked as we are going forward with TTK tests, will address this after completion of the TTK tests
