### ISSUE TITLE
Update Node - DB interfaces

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#151]
**Goal**:
As a developer I would like to _Update Node - DB interfaces_ so that they align with the PI-2 DB CDM.

**Tasks**:
- [ ] Update interfacing between the Node code and DB

**Acceptance Criteria**:
- [ ] The interfacing between and node and DB are updated as per PI-2 CDM.
- [ ] Tests tests pass, same as before

**Dependencies**:
- #153, #207
