### ISSUE TITLE
Align Account-Lookup-Service Sequence Diagrams with Testing Toolkit Collection [1.04]

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#1511]
## **Goal**:
`As a` switch operational user 

`I want to` have a relational reference between the sequence diagrams for the Account-lookup-service and the Testing toolkit test collection
  
`so that` I could use it for debugging purposes so that I can quickly find the root cause of an issue

**Acceptance Criteria**:
- [ ] As-is 4 sequence diagrams(and steps) in [Account-lookup-service](https://docs.mojaloop.io/documentation/mojaloop-technical-overview/account-lookup-service/) have corresponding [testing toolkit tests](https://github.com/mojaloop/testing-tookit-test-cases/tree/master/collections/hub/sequence)

**Complexity**: Low -  May change if there are missing Sequence diagrams

**Uncertainty**: Medium - There is a level of uncertainty with regards to missing postman tests and sequence diagrams

---

**Tasks**:
- [x] Identify and document gaps in the test collections
  - [x] Missing negative test scenarios for GET /parties/{ID} *seq-acct-lookup-get-parties-7.2.0*
  - [x] Missing tests for all scenarios for GET /participants/{Type}/{ID} *seq-acct-lookup-get-participants-7.1.0*
  - [x] Missing tests for all scenarios for POST /participants *seq-acct-lookup-post-participants-batch-7.1.1*
  - [x] Missing test for all scenarios for DELETE /participants/{Type}/{ID} *seq-acct-lookup-del-participants-7.1.2*
- [x] Identify and document gaps in the sequence diagrams
  - Missing diagram for POST /participants/{Type}/{ID} https://github.com/mojaloop/project/issues/1565
  - Missing diagram for DELETE /participants/{Type}/{ID} https://github.com/mojaloop/project/issues/1565
  - Missing admin diagrams for DELETE /endpointcache https://github.com/mojaloop/project/issues/1566
  - Missing Admin diagrams GET /oracles https://github.com/mojaloop/project/issues/1566
  - Missing Admin diagrams POST /oracles https://github.com/mojaloop/project/issues/1566
  - Missing Admin diagrams PUT /oracles/{ID} https://github.com/mojaloop/project/issues/1566
  - Missing Admin diagrams DELETE /oracles/{ID} https://github.com/mojaloop/project/issues/1566
- [x] Refactor outdated sequence diagrams
- [x] Update test collections to correlate with Sequence diagrams
- [x] Refactor existing testing toolkit Golden Path tests to add new tests for missing functionality
- [ ] Peer review
- [x] Create follow-up stories for missing sequence diagrams and tests
  - Missing [Sequence Diagram for POST Participants](https://docs.mojaloop.io/documentation/mojaloop-technical-overview/account-lookup-service/als-post-participants.html)
- [x] Update Central-services-shared to cater for delete http requests without a body
- [x] Update Legacy simulator to return correct error message 
- [x] Fix TTK not linking callbacks to requests:
  - [x] POST /participants
  - [x] DELETE /participants/{Type}/{ID}

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Testing Toolkit Tests pass

## **Pull Requests**:
- [ ] https://github.com/mojaloop/testing-tookit-test-cases/pull/4

## **Follow-up**:
- N/A

**Dependencies**:
- #1637

## **Accountability**:
- Owner: TBC
- QA/Review: @amarmodus @elnyry-sam-k
