### ISSUE TITLE
Align Central-Settlements Sequence Diagrams with Postman Collection [1.08]

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1512]
## **Goal**:
`As a` switch operational user 

`I want to` have a relational reference between the sequence diagrams for Central Settlements and the Postman test collection
  
`so that` I could use it for debugging purposes so that I can quickly find the root cause of an issue.

**Acceptance Criteria**:
- [ ] As-is sequence diagrams (and steps) in [Central Settlements](https://docs.mojaloop.io/documentation/mojaloop-technical-overview/central-settlements/) have corresponding [postman tests](https://github.com/mojaloop/postman/blob/master/ML_OSS_MojaSim_Sequence.postman_collection.json)

**Note**: The scope here is limited to the codebase on 'master' branch only.

**Complexity**: Low -  We won't be creating new Sequence diagrams in this story.

**Uncertainty**: Medium - There is a level of uncertainty with regards to missing postman tests and sequence diagrams.

---

**Tasks**:
- [ ] Identify and document gaps in the test collections
- [ ] Identify and document gaps in the c.15 sequence diagrams
- [ ] Refactor outdated sequence diagrams
- [ ] Update test collections to correlate with Sequence diagrams
- [ ] Refactor existing postman Golden Path tests to add new tests for missing functionality
- [ ] Peer review
- [ ] Create follow-up stories for missing sequence diagrams and tests

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Postman Tests pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @amarmodus @elnyry-sam-k
