### ISSUE TITLE
1.05. Align Quoting-Services Sequence Diagram with TTK Collection

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1513]
## **Goal**:
`As an` Ops team member supporting a Switch
`I want to` have a relational reference between the sequence diagrams for the Quoting-service and the TTK test collection
`so that` I could use it for debugging purposes so that I can quickly find the root cause of an issue

**Acceptance Criteria**:
- [ ] As-is sequence diagrams (and steps) in [quoting-service](https://docs.mojaloop.io/documentation/mojaloop-technical-overview/quoting-service/) have corresponding TTK tests

**Complexity**: Low -  We won't be creating new Sequence diagrams in this story

**Uncertainty**: Medium - There is a level of uncertainty with regards to missing TTK tests and sequence diagrams

---
**Tasks**:
- [x] Naming & Referencing conventions for TTK tests & sequence diagram
- [x] Identify and document gaps in the test collections [@oderayi]
   - Missing Tests:
      - POST /quotes
      - PUT /quotes/{id} (-ve scenarios)
      - PUT /quotes/{id}/error
      - POST /bulkQuotes
      - PUT /bulkQuotes/{id}
      - PUT /bulkQuotes/{id}/error
      - GET /bulkquotes/{id} (-ve scenarios)
      - PUT /bulkQuotes/{id} (-ve scenarios)
- [x] Identify and document gaps in the sequence diagrams [@oderayi] 
    - Missing Diagrams [Follow-up stories #1602 #1643]
      - GET /quotes/{id}
      - POST /quotes
      - PUT /quotes/{id}
      - PUT /post/{id}/error
      - POST /bulkQuotes
      - PUT /bulkQuotes/{id}
      - PUT /bulkQuotes/{id}/error
      - GET /bulkQuotes/{id}
- ***Other gaps identified [[Follow-up story #1603](https://github.com/mojaloop/project/issues/1603)] :***
   - POST /quotes handler needs to aligned with sequence diagram e.g. 202 response is not returned immediately as seen in diagram
- [x] Refactor outdated sequence diagrams [@oderayi] 
- [x] Update test collections to correlate with Sequence diagrams [@oderayi] 
   - [x] POST /quotes [@oderayi] 
   - [x] POST /quotes (-ve scenarios) [@oderayi]
   - [x] PUT /quotes/{id} (-ve scenarios) [@oderayi] 
   - [x] PUT /quotes/{id}/error [@oderayi] 
- [x] Refactor existing TTK Golden Path tests to add new tests for missing functionality [@oderayi] 
- [x] Peer review [@Team]
- [x] Create follow-up stories for missing sequence diagrams and tests [@oderayi] 

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] TTK Tests pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/documentation/pull/251
- [x] https://github.com/mojaloop/simulator/pull/207
- [x] https://github.com/mojaloop/helm/pull/369
- [x] https://github.com/mojaloop/postman/pull/164

## **Follow-up**:
- #1602
- #1603
- #1643
- #1646

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @amarmodus @elnyry-sam-k
