### ISSUE TITLE
Align Transaction Requests Service Sequence Diagrams with TTK tests [1.09]

### ISSUE THREAD

**Issue by yosheeck** [mojaloop/project#1514]
## **Goal**:
`As a` switch operational user 

`I want to` have a relational reference between the sequence diagrams for the Transaction Requests Service and the TTK test collections
  
`so that` I could use it for debugging purposes and quickly find the root cause of an issue

**Acceptance Criteria**:
- [ ] Sequence diagrams (and steps) in Transaction Requests Service have corresponding TTK tests

**Complexity**: Low -  

**Uncertainty**: Low -  The list of sequence diagrams to align is clear.

---

**Tasks**:
- [ ] Update the transcactionRequests test template to use Mojaloop Simulator (from Legacy Sim)
- [ ] Add / Refactor TTK Golden Path test collections to correlate with Sequence diagrams
    - [ ] GET & PUT on `/transcactionRequests/{ID}`
    - [ ] POST `/transcactionRequests` & PUT `/transcactionRequests/{ID}`
    - [ ] Authorizations GET and PUT `/transcactionRequests/{ID}`
- [ ] Peer review

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] TTK Tests pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- #1520 

## **Accountability**:
- Owner: TBC
- QA/Review: @amarmodus @elnyry-sam-k

**Comment by elnyry-sam-k** [comment]
since designs will change based on reference architecture work-stream's outcomes, this is not applicable anymore
