### ISSUE TITLE
Align Central-Ledger Prepare Sequence Diagrams with TTK [1.06.1]

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1515]
## **Goal**:
`As a` switch operational user 

`I want to` to make sure that all functionalities in Central-Ledger [Prepare] leg have correct PlantUML sequence diagrams corresponding tests in TTK and if missing tests or diagrams are identified to create corresponding stories for that.
  
`so that`  I could use it for debugging purposes so that I can quickly find the root cause of an issue

**Acceptance Criteria**:
- [ ] Existing ~8~ 5 PlantUML sequence diagrams(and steps) in Central-Ledger [Prepare incl. relevant position] have corresponding TTK tests

**Sequence diagram links**:
- [Prepare Transfer Request](https://docs.mojaloop.io/documentation/mojaloop-technical-overview/central-ledger/transfers/1.1.0-prepare-transfer-request.html)
- [Position Handler Consume](https://docs.mojaloop.io/documentation/mojaloop-technical-overview/central-ledger/transfers/1.3.0-position-handler-consume.html)
- [Position Handler Consume v1.1](https://docs.mojaloop.io/documentation/mojaloop-technical-overview/central-ledger/transfers/1.3.0-position-handler-consume-v1.1.html)

**Validated diagrams**
- [x] mojaloop-technical-overview/central-ledger/assets/diagrams/sequence/seq-prepare-1.1.0.plantuml
- [x] mojaloop-technical-overview/central-ledger/assets/diagrams/sequence/seq-prepare-1.1.1.a.plantuml
- [x] mojaloop-technical-overview/central-ledger/assets/diagrams/sequence/seq-position-1.3.0.plantuml
- [x] mojaloop-technical-overview/central-ledger/assets/diagrams/sequence/seq-position-1.3.0-v1.1.plantuml
- [x] mojaloop-technical-overview/central-ledger/assets/diagrams/sequence/seq-position-1.3.1-prepare.plantuml

**Not Implemented**
- [x] remove not implemented diagrams from SUMMARY.md and add note at the beginning of each diagram and remove them from overview diagram references
  - [x] mojaloop-technical-overview/central-ledger/assets/diagrams/sequence/seq-prepare-1.1.1.b.plantuml
  - [x] mojaloop-technical-overview/central-ledger/assets/diagrams/sequence/seq-prepare-1.1.2.b.plantuml
  - [x] mojaloop-technical-overview/central-ledger/assets/diagrams/sequence/seq-prepare-1.1.4.b.plantuml

**Diagrams that needs rework**
Note: should prepare a story
- [ ] mojaloop-technical-overview/central-event-processor/assets/diagrams/sequence/seq-event-9.1.0.plantuml

**Notes**:
 * Tests for refactoring: Tracing tests are currently tied to elasticsearch and are not complete. Would suggest and like to discuss at some point tight integration between TTK and EventFramework to be able to visualize and test programmatically the events
 * Golden path transfer prepare lacks tests for position change, but is available in negative scenarios
 * The scope of this iteration is not to cover all the error scenarios exhaustively but representatively and ensure all the steps in sequence diagrams are covered (unit tests will ensure coverage for all error codes implemented)

**Complexity**: Medium -  May change if there are missing Sequence diagrams

**Uncertainty**: Low - There is a level of uncertainty with regards to missing postman tests and sequence diagrams

---

**Tasks**:
- [x] Identify Gaps & agree on change needed as a team
- [x] Refactor outdated sequence diagram (or) Create a story to refactor code
- [ ] Create follow-up stories for missing
  - [x] sequence diagrams
  - [ ] tests
- [ ] Update test collections to correlate with Sequence diagrams
- [ ] Refactor existing TTK Golden Path tests to add new tests for missing functionality
- [ ] Create follow-up stories for missing sequence diagrams and tests
- [ ] Peer review

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Code checked-in
- [ ] TTK Tests pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @amarmodus @elnyry-sam-k

**Comment by vgenev** [comment]
combined back to #1515
