### ISSUE TITLE
Investigate the best approach to improve Postman test latency, reliability and consistency

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1517]
## **Goal**:
`As a` Quality Assurer

`I want to` identify the best approach on how to improve postman scripts to pro-actively query test-results
  
`so that` the test processing time/latencies are reduced with improvements on the test reliability and consistency

**Acceptance Criteria**:
- [ ] Agreement on the best approach for Postman tests to query test-results pro-actively (instead of waiting for a set timeout as per the As-Is) to improve Postman scripts latencies, reliability, and consistency - with pros/cons on choices & decisions documented as comments to this story.

**Complexity**: Medium-Low - Some due to the multiple choices to be investigated

**Uncertainty**: Low - Minimal since this story is purely investigatory

---
**Notes**:
- [Postman Sandbox API Reference](https://learning.postman.com/docs/writing-scripts/script-references/postman-sandbox-api-reference/)
- [PR for sdk-scheme-adapter support utilising WebSocket integration to mojaloop-simulator for push-notifications](https://github.com/mojaloop/sdk-scheme-adapter/pull/185)

**Tasks**:
- [ ] Investigate the best approach for Postman tests to query the simulator pro-actively (instead of waiting for a set timeout as per the As-Is) based on one of the following choices:
    1. Web-sockets
    2. Polling
    3. SDK-Scheme-Adapter
- [ ] Present pros & cons/limitations for each of the above approaches with a recommendation
- [ ] Present any additional choices that may arise from the investigation   
- [ ] Create a follow-up story for the implementation based on the agreed approach

**Done**
- [ ] Acceptance Criteria pass
- [ ] Pros & Cons on choices & decisions documented as comments to this story.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by msk-** [comment]
@mdebarros Postman does not support websockets. I'm unsure whether it's possible to `eval` a websocket client library into Postman. I personally wouldn't spend time trying. Have you seen this: https://github.com/msk-/postman-migration/blob/master/Proposal.md?

**Comment by elnyry-sam-k** [comment]
I think this is outdated at this stage.. We have the GP tests on TTK now using websockets and the TTK workstream will continue with test improvements there
