### ISSUE TITLE
2.022 Create 'Delta' folder in the MojaSim collection

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1519]
## **Goal**:
As an Adopter of Mojaloop
I want to have the MojaSim Golden path test collection contain tests for new features(& bug fixes) added after 8.8
so that I can use the MojaSim collections for regression testing and validating the new features.

This story has tasks to move the tests over and address the 'delta' provided in #1518 .

**Tasks**:
- [ ] Bug Fixes Folder (#998 , 1009, 981, 990, 1331, 1378, 849, 949, 742, 733, 956, 883, 1032)
- [ ] transaction request service ( health, received state, reject state, error framework, authorizations, authorizations -error framework)
- [ ] quoting service folder 
- [ ] p2p on us transfer ( 4 request)
- [ ] version 1.1 tests

**Acceptance Criteria**:
- [ ] Tests are now ported to the MojaSim collection for
  - [ ] bug fixes 
  - [ ] transaction request service
  - [ ] quoting service folder 
  - [ ] p2p on us transfer ( 4 request)
  - [ ] version 1.1 tests 

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @amarmodus , @elnyry-sam-k
