### ISSUE TITLE
Implement the DB PoC

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#152]
**Goal**:
As a developer I would like to Implement the DB PoC so that the work done as PoC is now integrated into base code.

**Tasks**:
- [x] Implement the DB PoC

**Acceptance Criteria**:
- [ ] The implementation from the DB PoC becomes the new base
- [x] Documentation for changes made

**Dependencies**:
- None currently

**Comment by kjw000** [comment]
@elnyry - is there documentation for this one to review as well?  thanks.

**Comment by elnyry** [comment]
Covered a little bit here - https://github.com/mojaloop/docs/blob/develop/PerformanceAndLatencyMetricsAndScenarios.md,but this was about implementing what was discussed, and demonstrated at the PI2 convening..
