### ISSUE TITLE
Create Sequence Diagrams for transaction-requests-service [1.10]

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1520]
## **Goal**:
`As a` Switch or an FSP

`I want to` have sequence diagrams for the Transaction Requests Service
  
`so that` I can have proper documentation of the flows of functionalities in Transaction Request Service.

**Acceptance Criteria**:
- [ ] Sequence diagrams are created covering all flows in Transaction Requests Service

**Complexity**: Low 

**Uncertainty**: Low

---

**Tasks**:
- [ ] Create 7 sequence diagrams
  - [x] PUT /transactionRequests/{ID}/error
  - [ ] GET /transactionRequests/{ID}
  - [x] PUT /transactionRequests/{ID}
  - [x] POST /transactionRequests
  - [x] GET /authorizations/{ID}
  - [x] PUT /authorizations/{ID}
  - [x] PUT /authorizations/{ID}/error
- [x] Create documentation pages to show the diagrams
- [x] Ensure link to pages are shown in the documentation sidebar
- [ ] Peer review

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date

## **Pull Requests**:
- [ ] https://github.com/mojaloop/documentation/pull/263

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @amarmodus @elnyry-sam-k
