### ISSUE TITLE
Obtain list of TTK enhancements required for its adoption [2.1.1-01]

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1521]
## **Goal**:
`As a` Product Owner of the TTK
`I want to` understand the blockers / missing features on the toolkit which make it impossible for potential adopters to adopt the TTK
`so that` I can make the TTK the standard testing tool across Mojaloop implementations

**Acceptance Criteria**:
- [ ] An agreed list of requirements needed for an MVP from the below groups is documented which when implemented to allow for the TTK's adoption
  - [ ] Mowali
  - [ ] ~OSS core team~ #1604 
  - [ ] ~TIPS~ #1605

**Complexity**: Medium -  Meetings / discussions should help

**Uncertainty**: Medium - There's the usual element of the "Unknown"

---
**Tasks**:
- [x] Demo TTK to Mowali team to elicit requirements for MVP
- [ ] Document needs / Requirerments from Mowali to use the TTK

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @amarmodus @elnyry-sam-k

**Comment by elnyry-sam-k** [comment]
Requirements for Mowali adoption (minimum):

1. Ability to test admin/operator functionality
2. Getting buy-in from dev teams (javascript tests)
3. Concurrent execution 
4. Cost savings
5. Support for PR Reviews and collaboration (simple files and not a single huge json file)
