### ISSUE TITLE
Template to 'agree adoption timetable with two TTK adopters' [2.1.2]

### ISSUE THREAD

**Issue by mjbrichards** [mojaloop/project#1522]
## **Goal**:
As a Product manager for TTK 
I want to _come with a template to be used to agree on an adoption timetable for making TTK their standard testing tool with two projects_
so that _I can make TTK the standard testing tool across the Mojaloop community_

**Acceptance Criteria**:
- [ ] Adoption plan created and documented
- [ ] Adoption plan created and documented
- [ ] Template stories that can be used in adopters' projects are documented
- [ ] Support process drafted and agreed upon by the team
- [ ] Validated with OSS Core team as reference.

**Tasks**:
- [ ] Identify adoption tasks and document
- [ ] Estimate task complexity
- [ ] Draft template adoption stories in the target projects
- [ ] Agree an oversight process to support projects in their adoption of TTK
- [ ] Quick review with OSS team as reference

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @elnyry-sam-k @MichaelJBRichards
