### ISSUE TITLE
Benchmark PoC with In-Memory store-only

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1524]
## **Goal**:
Benchmark PoC with In-Memory store-only

**Tasks**:
- [x] Add configuration to select specific stores participants, transfers and duplicates
- [x] Create In-memory store for Duplicate-Store
- [x] Create In-memory store for Transfer-Store
- [x] Create In-memory store for Participant-Store
- [x] Split Handlers into separate deployments for Evt and Cmd
- [ ] build/publish docker image
- [ ] Deploy standard-store for end-to-end Performance Tests as a baseline
- [ ] Deploy In-Memory store-only for end-to-end Performance Tests
- Tests
    - [ ] Test In-Memory store-only for end-to-end Performance Tests
    - [ ] Test with/without GZIP compression
    - [ ] Test EventSourcing

**Acceptance Criteria**:
- Documented Baseline results for standard-store
- Documented Performance results for In-Memory store

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
