### ISSUE TITLE
Create Testing Tool kit(TTK) collection to align with sequence diagrams - Reference item

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1525]
## **Goal**:
`As a` developer 
`I want to` create a mojaloop sequence diagram test collection for the POST Quotes for the Quoting Service in TTK
`so that` we can easily show test cases assigned to sequence diagrams and what processes are required

**Tasks**:
- [x] Create TTK collection for POST Quotes
- [x] Create mappings according to service then functionality then sequence diagram name
- [x] Create reference Item mapping 
- [x] Create pre-requests scripts to Mojaloop Simulator to allow us to use the correct response values
- [x] Implement reference Item tests
- [x] Testing Toolkit review session with Vijay
- [x] Nested folder to be implemented in TTK
- [x] Documenting standards / naming conventions / folder structure that can be used in other stories ( in this objective )

**Acceptance Criteria**:
- [x] Sequence Diagrams are up-to date for POST Quotes in the Quoting Service
- [x] TTK Tests pass for the POST Quotes in the Quoting Service

## **Pull Requests**:
- [x] https://github.com/mojaloop/testing-tookit-test-cases/pull/1
- [x] https://github.com/mojaloop/deploy-config/pull/25

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner:  
- QA/Review: @elnyry-sam-k

**Comment by vijayg10** [comment]
Screen shot for the test results on testing toolkit
![Screenshot 2020-08-04 at 2 11 31 PM](https://user-images.githubusercontent.com/33152110/89272892-6e0e7d00-d65c-11ea-9161-5c28c1eccc57.png)
