### ISSUE TITLE
Design for Bulk Parties Lookup

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#1526]
## **Goal**:
As a FSP
I want to be able to lookup multiple Party IDs in a single bulk request
so that I can can create a Bulk Quote without doing individual lookups

**Tasks**:
- [ ] Define Bulk Parties request object
- [ ] Define Bulk Parties callback object
- [ ] Define Lookup Oracle request object
- [ ] Define Lookup Oracle response object
- [ ] Create Sequence Diagrams

**Acceptance Criteria**:
- [ ] Designs are up-to date

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @rmothilal @elnyry-sam-k
