### ISSUE TITLE
Design configurable option to fulfil bulk only if all transfers pass [3.3.1]

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1528]
## **Goal**:
`As an` OSS Maintainer
`I want to` design a configurable option in bulk transfers for all-or-nothing scenarios
`so that` Switch operators can use the option to control how partial fulfillment of bulk transfers are handled by the Switch.

**Acceptance Criteria**:
- [ ] A design of the configurable option is created, reviewed and accepted by the team

**Complexity**: Medium

**Uncertainty**: Low

---
**Tasks**:
- [ ] Create a detailed description of the design
- [ ] Create a sequence diagram showing the design functionalities
- [ ] Refactor relevant existing sequence diagrams
- [ ] Update related documentation pages
- [ ] Peer review

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Postman Tests pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @mdebarros @rmothilal @elnyry-sam-k
