### ISSUE TITLE
Complete CQRS read side event-handlers (transfers and participants)

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#1531]
Using the event-sourcing state events, create the read side event handlers that create and keep up to date the read side readonly views.
Initial implementation using MongoDb

(split if necessary)

**Tasks**:
- [x] Participants read side event handler [ @pedrosousabarreto  ]
- [x] Transfers read side event handler [ @ ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by pedrosousabarreto** [comment]
initial implementation for the participants here:
