### ISSUE TITLE
Develop the ES snapshotting mechanism

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#1532]
Create the event-sourcing snapshotting mechanism for the participants.
Implement it as a command that is sent to the usual participants command topic so the command handler can create a snapshot of itself.

Figure out later, and split if necessary, which mechanism sends the snapshotCommand, ideas:
- Kubernetes triggers a script based on an interval/cron;
- Participants event handler has a counter of processed events and sends the snapshotCmd after X (not enough on its own due to log retention and inactivity)
- We can even have both to achieve for example: every day or 100 changes, whatever comes first

Note: Because transfers are short lived on the write side snapshotting might not be necessary at all. State loads can be performed from cache + events only.

**Tasks**:
- [x] SnapshotCommand implementation on the aggregate and cmd handler [ @pedrosousabarreto  ]
- [ ] Triggering mechanism for SnapshotCommand [  ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
