### ISSUE TITLE
Validate new Mojaloop Helm deployments with the TTK via post-install hook [2.042]

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1536]
## **Goal**:

`As a` Hub Operator

`I want to` validate new Mojaloop Helm deployments with the TTK via post-install hook 
  
`so that` we can gain confidence on the new deployments

**Acceptance Criteria**:
`When` post-install hook is invoked
`Then`
- [x] Mojaloop setup collection (currently in Postman) should be run and results are available in the container's standard out
- [x] Mojaloop Test suite (i.e. all available Mojaloop tests) in TTK should run and results are available in the container's standard out

**Complexity**: <Medium> Post install hooks may be difficult to debug.

**Uncertainty**: <Low>  Quite clear

---

**Tasks**:
- [x] Write the post-install hook
- [x] Convert Mojaloop setup collection in Postman to TTK ( new story required )
- [x] Deploy a Mojaloop instance
- [x] Test

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Code Style standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/395
- [x] https://github.com/mojaloop/deploy-config/pull/32

## **Follow-up**:
- N/A

**Dependencies**:
- #1725 
- #1730

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
<img width="1220" alt="Screenshot 2020-10-12 at 10 36 23 PM" src="https://user-images.githubusercontent.com/33152110/95773056-66fa8f80-0cdb-11eb-98fa-ca50e25d8451.png">
