### ISSUE TITLE
Investigate feasibility of running regression tests on every commit to master branch (core repos only) [2.052]

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1538]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` investigate the feasibility of running regression tests on every commit to master branch of core repositories
  
`so that` a decision can be made on implementation.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Discuss with implementers
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
