### ISSUE TITLE
Enhance Docker Container for TTK CLI to support AWS S3 CLI and Slack Webhooks for notifications [2.031]

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#1539]
## **Goal**:
`As an` Implementer

`I want to` enhance the Docker container for the TTK CLI
  
`so that` we can share tests can be run and results published on slack 

**Acceptance Criteria**:
- [x] The Self-Testing Toolkit CLI is enhanced to support
  - [x] uploading of test-results to an AWS S3 Bucket
  - [x] send a notification to a Slack channel on the Mojaloop Slack Org via a Webhook (which contains the public link to the test-results uploaded to the AWS S3 Bucket.)
- [x] Existing TTK Docker-image is modified to support the execution of the Enhanced Self-Testing Toolkit CLI
- [x] The TTK CLI documentation is updated to reflect new capabilities
  - [x] For S3, reportTarget value of s3://<bucket_name>/<path>, with envs AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY. (Take care of region) (Add the CLI documentation regarding this)
  - [x] For Slack, slackWebhookURL value of http://.....

**Complexity**: Low > Should be straight forward to work on getting a docker container to work locally

**Uncertainty**: Low > We have the knowledge in the team to create the helm scripts

---

**Tasks**:
Note:  the TTK backend GitHub repo, 
Note:  existing Docker image / CLI
- [x] Develop JS script to execute a set of test collection on a remote TTK
- Gather the reports
    - [x] Display results in the standard out console
    - [x] Upload those reports to AWS s3 bucket if there is a configuration flag to do so
- [x] Slack notification to notify availability of reports with a link, if there is a configuration flag to do so
- [x] Test docker image
- [x] Documentation for CLI options

**Done**
- [x] Acceptance Criteria pass
- [x] Testing Toolkit Tests pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/99

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @mdebarros @elnyry-sam-k @vijayg10 @georgi-logodazhki

**Comment by mdebarros** [comment]
CLI tool will consume the inputFiles from the docker file, later stories when we Helmify the TTK CLI, we will pull the input files from Github using a "tag" which is set via the values.yaml.
