### ISSUE TITLE
2.4.25.01 Implement PrepareHandler - [13, 13]

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#154]
**Goal**:
As a developer I would like to 
_Implement PrepareHandler in upgraded code_
so that the Stream processing works using the 'common stream library' for prepares.

**Tasks**:
- [x] Implement prepare in upgraded code
- [x] Unit tests for PrepareHandler @bothadeon @rmothilal
- [ ] Integration tests for PrepareHandler **Time-boxed** @bothadeon @rmothilal
- [ ] Review of the PR
- [x] Resolve local dev issue with Kafka
- [ ] Merge the PR

**Acceptance Criteria**:
- [x] Implement re-usable handler framework for easy addition & implementation of handlers in future
- [x] The new base code has prepares implemented with the latest design using the 'common library'
- [x] Notifications are placed on the topics for a specific DFSP
- [x] Implement functionality based on sequence diagrams for PrepareHandler (no batch processing, no event logging)
- [x] Unit tests are available for PrepareHandler
- [ ] Integration tests are available for PrepareHandler
- [ ] Automated tests pass

**Dependencies**:
- [x] #148
- [x] #151 
- [x] #211
- [ ] #262 (for Integration tests)

**Accountability**
- Owner @rmothilal 
- Review

**Comment by mdebarros** [comment]
@ksatya77 @NicoDuvenage @THEADEV this is blocked for story #151
