### ISSUE TITLE
Submit Bulk Design to the CCB for Bulk Parties Lookup

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1543]
## **Goal**:
`As a` OSS Implenter

`I want to` submit Bulk Designs to the CCB
  
`so that` the Mojaloop API Specification can be updated to support the Bulk Design changes

**Acceptance Criteria**:
- [ ] Mojaloop API Specifications have been updated to cater for Bulk Designs changes for Bulk Parties
- [ ] Stories have been created to implement any change deltas made by the CCB to the Bulk Designs

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] CCB provide feedback to Bulk Designs for Bulk Party Lookup

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
