### ISSUE TITLE
Design for Bulk Quote Make [3.2.1] 

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#1544]
## **Goal**:
As an _FSP_
I want to be able to _create a bulk quote with multiple payee FSPs_
so that _I can can create a single Bulk request instead of individual requests_

**Tasks**:
- [ ] Design Bulk Quote request object
- [ ] Design Bulk Quote callback object
- [ ] Create Sequence Diagrams for POST /bulkQuotes request object
- [ ] Create Sequence Diagrams for PUT /bulkQuotes request object
- [ ] Create Sequence Diagrams for PUT /bulkQuotes error request object

**Acceptance Criteria**:
- [ ] Designs are up-to date

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @rmothilal @elnyry-sam-k
