### ISSUE TITLE
Testing Toolkit - Loading samples based on folder hierarchy

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1545]
## **Goal**:
`As a` user of the testing toolkit

`I want to` see the test case examples with subfolders
  
`so that` it will be easy to browse through the test cases

**Acceptance Criteria**:
- [x] Test cases will be populated based on the subfolders hierarchy

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Find out a react library for browsing files through folders
- [x] Changes in the backend if required to fetch the list of files in compatible format
- [x] Changes in the UI to browse through the collections easily with folder hierarchy

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/42
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/88

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @elnyry-sam-k
