### ISSUE TITLE
Testing Toolkit - Update the TTK test cases to cover all the cases in latest postman collections

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1548]
## **Goal**:
`As a` Hub / DFSP

`I want to` have a complete collection of test cases in the testing toolkit
  
`so that` I can test every scenario of my implementation

**Acceptance Criteria**:
- [ ] Test cases from the Postman legacy GP collection are available in TTK
- [ ] Test cases from the Postman mojasim GP collection are available in TTK

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] Compare the TTK test cases with Postman Legacy GP and list out the test cases to be added
- [ ] Compare the TTK test cases with Postman Mojasim GP and list out the test cases to be added
- [ ] Discuss the list
- [ ] Add the test cases from the reviewed list

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Should be taken care of by #1516
