### ISSUE TITLE
Investigate missing use cases from the FSPIOP API spec document and create those in TTK

### ISSUE THREAD

**Issue by georgi-logodazhki** [mojaloop/project#1549]
## **Goal**:
`As a` Hub / DFSP
`I want to` have a test cases for all use cases from FSPIOP API spec document 
`so that` I can test every use case in TTK

**Complexity**: Medium
**Uncertainty**: Medium

**Acceptance Criteria**:
- [x] Test cases for each use case from the FSPIOP API spec document are available in TTK

**Tasks**:
- [x] Investigate missing use cases from the FSPIOP API spec document
- [x] add test cases for each use case from the FSPIOP API spec document to TTK

**Done**:
- [ ] All use cases from the FSPIOP API spec document are available in TTK
- [ ] e2e testing of the whole functionality
- [ ] Acceptance Criteria passed

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @georgi-logodazhki @vijayg10  

- QA/Review: @elnyry-sam-k
