### ISSUE TITLE
Testing Toolkit - Break the JSON test cases into smaller files and maintain sub folders

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1550]
## **Goal**:
`As a` user of the testing toolkit

`I want to` have smaller JSON files of test cases
  
`so that` it will be easy to browse through the test cases

**Acceptance Criteria**:
- [ ] Test cases are broken down to small JSON files and folders are refactored appropriately

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] Break down the test cases into smaller files

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @elnyry-sam-k

**Comment by vijayg10** [comment]
[Initial_Research_and_Observations.pdf](https://github.com/mojaloop/project/files/5084783/47bcf52b-2342-4b10-808a-b918cc254c11.pdf)

**Comment by vijayg10** [comment]
The implementation stories are created
https://github.com/mojaloop/project/issues/1611
https://github.com/mojaloop/project/issues/1612
https://github.com/mojaloop/project/issues/1613
