### ISSUE TITLE
Hosted TTK - Review the hosting capability design with Core Team

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1551]
## **Goal**:
`As a` Scheme

`I want to` have hosting capability for the testing toolkit
  
`so that` I can host the TTK and let my DFSP's use that

**Acceptance Criteria**:
- [x] The proposed changes in the hosting capability of the TTK are reviewed by the core team.

**Complexity**: Low

**Uncertainty**: High. DB design option may not accepted by Core team or lot of changes may be suggested by Core team in the design

---

**Tasks**:
- [x] Review the changes regarding hosting capability with core team
- [x] Document the feedback / suggested design changes

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- N/A

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @georgi-logodazhki 
- QA/Review: @vijayg10

**Comment by georgi-logodazhki** [comment]
The new MongoDB license is not going to affect us so we are going to use Mongoose+MongoDB instead PouchDB+CouchDB. 
[db-observations-and-hosting-draft-design-reviewed.pdf](https://github.com/mojaloop/project/files/5097505/db-observations-and-hosting-draft-design-reviewed.pdf)
