### ISSUE TITLE
Create Draft Design to maintain DFSP specific properties

### ISSUE THREAD

**Issue by georgi-logodazhki** [mojaloop/project#1552]
## **Goal**:
`As a` Scheme

`I want to` have hosting capability for the testing toolkit
  
`so that` I can host the TTK and let my DFSP's use that

**Acceptance Criteria**:
- [x] draft design created with proposed changes in the hosting capability of the TTK

**Complexity**: Low. 

**Uncertainty**: Medium.

---

**Tasks**:
- [x] create draft design regarding hosting capability to maintain DFSP specific properties 
  - [x] rules
  - [x] settings
  - [x] logs
  - [x] reports 
- [x] investigate the most suitable NoSQL DB for this design and restrictions.
   - [x] Apache CouchDB
   - [x] Apache PouchDB
   - [x] Apache Couchbase
   - [x] Apache Cassandra
- [x] Decision on whether to include a DB for TTK or continue to use existing File storage based on the observations

**Done**
- [x] Acceptance Criteria pass

## **Pull Requests**:
- N/A

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @georgi-logodazhki 
- QA/Review: @vijayg10

**Comment by georgi-logodazhki** [comment]
[e6596939-923d-469e-b454-bfc4610b33fc.pdf](https://github.com/mojaloop/project/files/5090890/e6596939-923d-469e-b454-bfc4610b33fc.pdf)
