### ISSUE TITLE
Implementation Support - Consult with Mowali on their Challenges around GDPR Tooling and Security Operations 

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1554]
## **Goal**:
Provide support to Mowali data privacy and security operations in order to make them fully production ready.

**Acceptance Criteria**:
-

**Complexity**: <Medium > GDPR 

**Uncertainty**: < Low > 

---

**Tasks**:
- [ ] Review session to understand the nature of the challenges
- [ ] Explore and evaluate solutions
- [ ] Adopt a fit for purpose solution 
- [ ] Develop an implementation plan

**Done**

- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @kjw000

**Comment by godfreykutumela** [comment]
Deferred to PI 12
