### ISSUE TITLE
Perf PoC - Benchmarking in-memory Kafka Processing

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1555]
## **Goal**:

- Performance Test Perf PoC with in-memory processing only to benchmark Kafka capability and also what is the best theoretical performance we can expect

**Acceptance Criteria**:
- [x] Create In-memory store for Duplicate-Store
- [x] Create In-memory store for Transfer-Store
- [x] Create In-memory store for Participant-Store
- [x] Split Handlers into separate deployments for Evt and Cmd
- [ ] Test with/without GZIP compression
- [ ] Test EventSourcing

**Complexity**: High

**Uncertainty**: High

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Duplicate of https://github.com/mojaloop/project/issues/1524
