### ISSUE TITLE
Mojaloop-Operator v1.0

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1557]
## **Goal**:
`As a` Hub Operator

`I want to` be informed of new security patches for my running mojaloop containers
  
`so that` I can keep my mojaloop installation secure

> Note: we may choose to break down this story smaller implementation stories, but I want to just get the conversation started, and keep a track of it.

**Acceptance Criteria**:
- [ ] mojaloop-operator v1.0 (see below for feature list)
- [ ] installation instructions for mojaloop-operator using helm
- [ ] running mojaloop-operator on our dev1 or dev2 clusters
- [ ] basic unit tests and some coverage
- [ ] CI/CD pipelines set up to auto release mojaloop-operator

**Complexity**: Medium - @matdehaast has got a basic POC working, so it's a case of making it more _real_

**Uncertainty**: High - We need to define the feature list better and perhaps break this story up

---

**Tasks**:
- [ ] Implement core features:
  - [ ] watch mojaloop codebases for new docker image releases based on some regex rules
  - [ ] scheduled (daily? weekly?) slack notifications sent to hub operators (for now a simple webhook to 
- [ ] installation instructions for mojaloop-operator using helm
- [ ] running mojaloop-operator on our dev1 or dev2 clusters
- [ ] basic unit tests and some coverage
- [ ] CI/CD pipelines set up to auto release mojaloop-operator

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly , @matdehaast 
- QA/Review: @elnyry-sam-k

**Comment by lewisdaly** [comment]
Closing as this was broken down into a number of smaller tickets
