### ISSUE TITLE
Migrate all codebases to Semantic Versioning

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1558]
## **Goal**:
`As a` OSS maintainer

`I want to` switch mojaloop codebases to semantic versioning
  
`so that` we can keep better track of bugs, fixes and better communicate versioning changes with other developers and hub operators

**Acceptance Criteria**:
- [x] All mojaloop codebases use semantic versioning

**Complexity**: Low  - This is more a ticket to track the communication around the community using versioning.

**Uncertainty**: Medium - We may decide that updating codebases to semantic versioning might take more work.

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Code Style & Coverage meets standards
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly, @elnyry-sam-k 
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Thanks @lewisdaly - I think we need to keep an eye on the PRs and releases being made, until most of the contributors are onboard. Right now, we already have our core contributors making releases starting with v11.0.0 and then following SemVer, so its looking good!

**Comment by lewisdaly** [comment]
Cool, yeah let's just be the SemVer police for a month or so.
