### ISSUE TITLE
Port Central-Ledger Admin AS-IS Sequence Diagrams / tests to TTK [1.06.3]

### ISSUE THREAD

**Issue by yosheeck** [mojaloop/project#1559]
## **Goal**:
`As a` switch operational user 

`I want to` have a relational reference between the PlantUML sequence diagrams for the Central-Ledger [Admin ops] and the TTK test collection
  
`so that` I could use it for debugging purposes so that I can quickly find the root cause of an issue

**Acceptance Criteria**:
- [ ] Existing 10 [PlantUML sequence diagrams](https://docs.mojaloop.io/documentation/mojaloop-technical-overview/central-ledger/admin-operations/) (and steps) in Central-Ledger [Admin ops] have corresponding TTK tests

**Complexity**: Low -  There may not be much to change as Admin api is stable

**Uncertainty**: Low -   Not anticipating much changes to existing Admin api diagrams / tests

---

**Note**: Refer to stories #1650 and #1651 for gap analysis findings.
Create Missing Diagrams [ #1650 ]**:
Create missing tests [ #1651 ] : 

**Tasks**:
- [ ] Refactor existing Postman tests to TTK
- [ ] Refactor outdated sequence diagram (or) Add new tasks / Create a story to refactor code 
- [ ] Update test collections to correlate with Sequence diagrams
- [ ] Peer review

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Code checked-in
- [ ] TTK Tests pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- TBD

**Dependencies**:
- #1632 
- #1650 
- #1651 

## **Accountability**:
- Owner: TBC
- QA/Review: @amarmodus @elnyry-sam-k
