### ISSUE TITLE
Implement a translation layer that converts from Mojaloop API to Central Services Internal Messaging format for transfers

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#156]
**Goal**:
As a developer I would like to Implement a translation layer that converts from Mojaloop API to Central Services Internal Messaging format for transfers

**Tasks**:
- [ ] Create ml-api-adapter repo in github that houses Transfer API and Notification Handler
- [ ] Leverage Producer from streaming library to write Prepare Messages to Kafka topics

**Acceptance Criteria**:
- [ ] Able to receive Transfer messages from REST endpoint and write them to kafka cluster

**Dependencies**:
- None currently

**Comment by mdebarros** [comment]
@ksatya77
