### ISSUE TITLE
Align Central-Ledger Reject/Abort Sequence Diagrams with TTK [1.06.5]

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1560]
## **Goal**:
`As a` switch operational user 

`I want to` have a relational reference between the PlantUML sequence diagrams for the Central-Ledger [Reject/Abort] and the TTK test collection
  
`so that` I could use it for debugging purposes so that I can quickly find the root cause of an issue

**Acceptance Criteria**:

- [ ] Existing 4 PlantUML sequence diagrams(and steps) in Central-Ledger [Reject/Abort incl. relevant position] have corresponding TTK tests

- https://docs.mojaloop.io/documentation/mojaloop-technical-overview/central-ledger/transfers/2.2.0.a-fulfil-abort-transfer-v1.1.html
- https://docs.mojaloop.io/documentation/mojaloop-technical-overview/central-ledger/transfers/2.2.1-fulfil-reject-handler-v1.1.html
- https://docs.mojaloop.io/documentation/mojaloop-technical-overview/central-ledger/transfers/1.3.3-abort-position-handler-consume.html
- https://docs.mojaloop.io/documentation/mojaloop-technical-overview/central-ledger/transfers/1.1.4.a-send-notification-to-participant-v1.1.html

- [ ] One TTK test file per sequence diagram and the alternative cases within the sequence diagram.

**Complexity**: Medium -  the Sequence diagrams are detailed and have many branches

**Uncertainty**: Low - There is a level of uncertainty with regards to missing postman tests and sequence diagrams

---

**Tasks**:
- ~Refactor outdated sequence diagram (or) create a story to refactor code~
  -  _**Note**_: Sequence diagrams are complete
- [ ] Add / Refactor existing TTK Golden Path collection to add new tests for missing functionality based on the 4 sequence diagrams
    - [ ]  https://docs.mojaloop.io/documentation/mojaloop-technical-overview/central-ledger/transfers/2.2.0.a-fulfil-abort-transfer-v1.1.html
    - [ ] https://docs.mojaloop.io/documentation/mojaloop-technical-overview/central-ledger/transfers/2.2.1-fulfil-reject-handler-v1.1.html
    - [ ]  https://docs.mojaloop.io/documentation/mojaloop-technical-overview/central-ledger/transfers/1.3.3-abort-position-handler-consume.html
    - [ ] https://docs.mojaloop.io/documentation/mojaloop-technical-overview/central-ledger/transfers/1.1.4.a-send-notification-to-participant-v1.1.html
- [ ] Peer review

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Code checked-in
- [ ] TTK Tests pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- #1634

## **Accountability**:
- Owner: TBC
- QA/Review: @amarmodus @elnyry-sam-k

**Comment by elnyry-sam-k** [comment]
Designs will change with Reference Architecture implementation so this is not applicable anymore
