### ISSUE TITLE
Align Central-Ledger Fulfil sequence diagrams to the TTK [1.06.2]

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#1561]
## **Goal**:
`As a` switch operational user 

`I want to` have a relational reference between the PlantUML sequence diagrams for the Central-Ledger [Fulfil] and the TTK test collection
  
`so that` I could use it for debugging purposes so that I can quickly find the root cause of an issue

**Acceptance Criteria**:
- [ ] Existing 6 PlantUML sequence diagrams(and steps) in Central-Ledger [Fulfil incl. relevant position] have corresponding TTK tests 

**Complexity**: Medium -  May change if there are missing Sequence diagrams

**Uncertainty**: Medium - There may be some requirements from the TTK (e.g. around abort/patch)

---

**Tasks**:
- [x] Identify Gaps & agree on change needed as a team -- #1631 
  - [x] Missing diagram for fulfil negative scenarios ABORT and REJECT #1658
- [x] Create follow-up stories for missing sequence diagrams and tests --  #1631   ( 1631 to be closed as it is superseeded by this story ) 
- [ ] Update test collections to correlate with Sequence diagrams (Ensure test collections from MojaSim have a corresponding TTK test)
  - [ ] Missing tests for fulfil negative scenarios ABORT and REJECT
  - [ ] Convert all of the postman tests (Happy Path, Abort/Patch and Reject - c.30 tests) to TTK tests using MojaSim
- [ ] Peer review

**Note**: All new tests should use MojaSim and not LegacySim

TTK <- uses LegaSim :  change target to MojaSim ( also change pre-request script )
Legacy Sim. : Tag collections with 'legacy'

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Code checked-in
- [ ] TTK Tests pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @amarmodus @elnyry-sam-k
