### ISSUE TITLE
Align Central-Ledger Timeout operations Sequence Diagrams with TTK [1.06.4]

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1562]
## **Goal**:
`As a` switch operational user 

`I want to` have a relational reference between the PlantUML sequence diagrams for the Central-Ledger [Timeout ops] and the TTK test collection
  
`so that` I could use it for debugging purposes so that I can quickly find the root cause of an issue

**Acceptance Criteria**:
- [ ] Existing (4) PlantUML sequence diagrams](https://docs.mojaloop.io/documentation/mojaloop-technical-overview/central-ledger/admin-operations/) (and steps) in Central-Ledger [Timeout ops] have corresponding TTK tests

**Complexity**: Medium -  May change if there are missing Sequence diagrams

**Uncertainty**: Low - There is a level of uncertainty with regards to missing postman tests and sequence diagrams

**Note**:   We will not be able to test the scenario where transfer state id is recieved-prepare

---

**Tasks**:
- [ ] Identify Gaps & agree on change needed as a team
- [ ] Refactor outdated sequence diagram (or) Create a story to refactor code
- [ ] Update test collections to correlate with Sequence diagrams
- [ ] Refactor existing TTK Golden Path tests to add new tests for missing functionality
- [ ] Peer review
- [ ] Create follow-up stories for missing sequence diagrams and tests

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Code checked-in
- [ ] TTK Tests pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @amarmodus @elnyry-sam-k

**Comment by elnyry-sam-k** [comment]
Designs will change with Reference Architecture implementation so this is not applicable anymore
