### ISSUE TITLE
TTK Hosted Mode: Test the deployment of TTK in hosted mode in AWS with keycloak integration

### ISSUE THREAD

**Issue by ramakrishnan-sankar** [mojaloop/project#1563]
## **Goal**:
`As a` scheme

`I want to` be able to deploy the TTK in hosted mode
  
`so that` I can provide the link to my DFSPs

**Acceptance Criteria**:
**Scenario**: TTK with Keycloak
`Given`  TTK, connection manager and Keycloak Server are deployed with the necessary configuration AND the two DFSP's are configured in AWS
`When` DFSP's login to the TTK and connection manager with the credentials created in Keycloak Server AND either DFSP sends a transfer request
`Then`
- [ ] DFSP's can be able to maintain the rules separately.  
- [ ] The DFSPs can receive the corresponding mock callback based on the rules
- [ ] Rules settings, logs, and reports data should be persisted in TTK database

**Complexity**: High.  Keycloak familiarity

**Uncertainty**: Low.  

---

**Tasks**:
 - [ ] Keycloak server deployed based on documentation
       https://github.com/mojaloop/ml-testing-toolkit/blob/master/documents/User-Guide-OAuth-Server-Deployment.md
- [ ] Deploy TTK backend, front-end and DB in hosted mode
- [ ] Deploy connection manager-api and connection-manager-ui
- [ ] Do required configuration to attach all the services
- [ ] Deploy two DFSP's on separate servers
- [ ] Provide the SSL certificates through connection manager as DFSPs
- [ ] Test the login into TTK and connection manager using the credentials created through KeyCloak admin page
- [ ] Test the rules and settings
- [ ] Test logs and reports
- [ ] Test the events and push message
- [ ] Test an end-to-end transfer from DFSP's

**Done**
- [ ] Acceptance Criteria pass

- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by ramakrishnan-sankar** [comment]
Covered under #1744
