### ISSUE TITLE
Create missing sequence diagrams and tests for Account-lookup-service api 

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#1565]
## **Goal**:
`As a` implementor

`I want to` have all all sequence diagrams and tests for the Account-lookup-service api
  
`so that` i can understand and test all process flows that occur within the API

**Acceptance Criteria**:
- [x] All sequence diagrams for the Account-Lookup-Service API are complete
- [x] All tests pass on the testing toolkit

**Complexity**: Low > We have the processes working, it would be to just translate them into diagrams

**Uncertainty**: Low > We have the processes working, it would be to just translate them into diagrams

---

**Tasks**:
- [x] Create sequence diagrams for missing flows
  - [x] POST /participants/{Type}/{ID}
  - [x] DELETE /participants/{Type}/{ID}
- [x] Create testing toolkit test collections
  - [x] POST /participants/{Type}/{ID}
  - [x] DELETE /participants/{Type}/{ID}

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Testing Toolkit Tests pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/testing-tookit-test-cases/pull/5

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @rmothilal @elnyry-sam-k @amarmodus
