### ISSUE TITLE
Create missing sequence diagrams for Account-lookup-service Admin API 

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#1566]
## **Goal**:
`As a` implementor

`I want to` have all all sequence diagrams for the Account-lookup-service Admin API
  
`so that` i can understand and test all process flows that occur within the Admin API

**Acceptance Criteria**:
- [x] All sequence diagrams for the Account-Lookup-Service Admin API are complete

**Complexity**: Low > We have the processes working, it would be to just translate them into diagrams

**Uncertainty**: Low > We have the processes working, it would be to just translate them into diagrams

---

**Tasks**:
- [x] Create sequence diagrams for missing flows
  - [x] DELETE /endpointcache
  - [x] GET /oracles
  - [x] POST /oracles
  - [x] PUT /oracles/{ID}
  - [x] DELETE /oracles/{ID}
- [x] Create Architecture diagram for the ALS Admin service

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date

## **Pull Requests**:
- [x] https://github.com/mojaloop/documentation/pull/267/files

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @rmothilal @elnyry-sam-k @amarmodus
