### ISSUE TITLE
TTK Hosted Solution - Refactor the helm chart

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1569]
## **Goal**:
`As a` Scheme

`I want to` have a helm chart for the testing toolkit with configurable options for hosting capability
  
`so that` I can deploy the testing toolkit in our cluster

**Acceptance Criteria**:
- [x] The hosted solution of the TTK can be deployed using Helm chart with the updated user and system configuration
- [x] The deployed TTK hosted service should work with oAuth, JWS and mTLS

**Complexity**: Medium (Connection manager to be included)

**Uncertainty**: Medium (Depend on the design decision on hosting capability)

---

**Tasks**:
- [x] get more familiar with helm and k8s - @georgi-logodazhki 
- [x] Refactor the TTK helm chart with hosted mode configuration
- [x] Include connection manager api, ui and db
- [x] Include mongodb in TTK helm chart
- [x] Include keycloak
- [x] Test:
   - [x] rules, settings, logs, reports are separate and appropriate db collections are created
   - [x] authentication with a mock server
   - [x] authentication with keycloak server
   - [x] JWS and TLS with connection manager

**Done**
- [x] Acceptance Criteria pass
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/387/files

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @georgi-logodazhki 
- QA/Review: @vijayg10
