### ISSUE TITLE
TTK Hosted mode - Documentation for the Helm chart usage with hosting capability enabled

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1571]
## **Goal**:
`As a` Scheme

`I want to` have a documentation for the helm chart deployment in hosted mode
  
`so that` I can deploy the testing toolkit in our cluster

**Acceptance Criteria**:
- [x] Helm chart deployment documentation available in the testing toolkit repository

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Prepare the documentation with step-by-step instructions how to deploy the TTK helm chart with hosted mode enabled
- [x] Validate the documentation by deploying the solution in hosted mode in local k8s cluster

**Done**
- [x] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by akapur99** [comment]
@ramakrishnan-sankar I think you assigned me on this by accident
