### ISSUE TITLE
PATCH notification in sdk-scheme-adapter and Mojaloop simulator 

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1572]
## **Goal**:
`As a` Payee DFSP

`I want to` to be notified upon the finalization of a transfer
  
`so that` I could use the information for releasing funds / notifying the end user.

**Acceptance Criteria**:
- [x] Once a transfer is finalized and notification received in sdk-scheme-adapter, a successful transfer notification is sent to the Payee FSP.

**Complexity**: Medium

**Uncertainty**: Medium.  Uncertainty in the what / how needed to change. 

---

**Tasks**:
- [x] Merge PR
- [x] Test the initial changes
- [x] Demo the initial changes
- [x] PR is approved and merged
- [x] Demo is presented
- [x] Make changes requested by Mowali team in sdk-scheme-adapter and mojasim as per that comment: https://github.com/mojaloop/sdk-scheme-adapter/pull/181#issuecomment-673459689
  - [x] Change api documentation to provide new PUT /transfers/{ID} endpoint where the notification should be received by the payee fsp
  - [x] Change mojaloop-sim api to provide new PUT /transfers/{ID} endpoint where the notification should be received by the payee fsp
  - [x] Create separate handler for the PATCH callback to deliver the notification to the payee fsp
  - [x] Create backend function for the PATCH callback
  - [x] Create PUT API handler for transfers on the Mojasim hanlder to receive the notification
  - [ ] ~Handle Error scenarios~ after discussion with @bushjames there was a decision that retry logic that was implemented in that particular request is better to be implemented in all of the sdk-scheme-adapter requests. the following story was created to capture that intention: https://github.com/mojaloop/project/issues/1609 Also James suggested 

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] https://github.com/mojaloop/sdk-scheme-adapter/pull/194
- [ ] https://github.com/mojaloop/mojaloop-simulator/pull/75

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
