### ISSUE TITLE
[thirdparty-api-adapter]: Factor out getEndpoint and Mustache.render

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1573]
## **Goal**:
`As a` OSS Maintainer

`I want to` factor out getEndpoint and Mustache.render()
  
`so that` the code can be better tested and maintained

As @eoln [noted](https://github.com/mojaloop/thirdparty-api-adapter/pull/16#discussion_r467773826) in the thirdparty api adapter, `getEndpoint` and `Mustache.render` are often used together. Perhaps we should factor them out to simplify the handler code.

**Acceptance Criteria**:
- [x] factored out code as above
- [x] passing unit tests
- [x] code coverage meets repository standards

**Complexity**: Low - Nothing all that difficult about this, it's more whether or not we _want to_

**Uncertainty**: Low - We know what needs to be done.

---

**Tasks**:
- [x] factor out common code into separate `shared` function - in central-services-shared
  > new function: `getEndpointAndRender()`, which takes a render function along these lines:
```ts
    const endpoint = await Util.Endpoints.getEndpointAndRender(
      Config.ENDPOINT_SERVICE_URL,
      destinationDfspId,
      endpointType,
      path,
      () => { ID: transactionRequestId }) 
)
```
- [x] write unit tests, and fix any broken tests
- [x] look through usage, and remove legacy `getEndpoint()`
- [x] add typings to `index.d.ts` so we don't have to specify in ambient.d.ts

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/thirdparty-api-adapter/pull/36

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly, @eoln 
- QA/Review: TBC
