### ISSUE TITLE
Align Central-Ledger GP TTK Tests with verified and updated diagrams [1.06.1]

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1577]
## **Goal**:
`As a` switch operational user 

`I want to` make sure that all diagrams from #1515 have tests in TTK and if missing tests are identified to create them
  
`so that` I could use it for debugging purposes so that I can quickly find the root cause of an issue

**Acceptance Criteria**:
- [ ] Existing 8 PlantUML sequence diagrams(and steps) in Central-Ledger [Prepare incl. relevant position] have corresponding TTK tests

**Complexity**: Medium -  May change if there are missing Sequence diagrams

**Uncertainty**: Low - There is a level of uncertainty with regards to missing postman tests and sequence diagrams

---

**Tasks**:
- [ ] Update test collections to correlate with Sequence diagrams
- [ ] Refactor existing TTK Golden Path tests to add new tests for missing functionality
- [ ] Peer review
- [ ] Create follow-up stories for missing sequence diagrams and tests

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Code checked-in
- [ ] TTK Tests pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @amarmodus @elnyry-sam-k

**Comment by vgenev** [comment]
combined back to #1515
