### ISSUE TITLE
Port the difference from LegacySim to MojaSim Postman collection [2.022] - Part 2

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1578]
## **Goal**:
As an Adopter of Mojaloop
I want to have the MojaSim Golden path test collection contain tests for new features(& bug fixes) added after 8.8
so that I can use the MojaSim collections for regression testing and validating the new features.

This story has tasks to move the tests over and address the 'delta' provided in #1518 .

**Acceptance Criteria**:
- [x] Tests (corresponding to c.100 requests) are now ported to the MojaSim collection for the below and all tests pass 
  - [x] transaction request service
  - [x] quoting service folder 
  - [x] p2p on us transfer ( 4 request)

---

**Tasks**:
- [x] Copy existing legacy sim test
- [x] Change URL and test
- [x] Validate JWS
Add (or move over) tests for below from LegacySim to MojaSim Postman collection
- [x] transaction request service (health, received state, reject state, error framework, authorizations, authorizations -error framework) -  https://github.com/mojaloop/project/issues/1647 raised for callback error response
- [x] quoting service folder  - https://github.com/mojaloop/project/issues/1640 (created to support GET/quotes)
- [x] p2p on us transfer ( 4 request)
- [ ] ~~Tests on MojaSim collection to validate PATCH notification(https://github.com/mojaloop/project/issues/1334)~~
- [ ] ~~Accent character testcases - **blocked** (https://github.com/mojaloop/project/issues/1653 - raised)~~

## **Pull Requests**:
- [x] https://github.com/mojaloop/postman/pull/167

## **Follow-up**:
- N/A

**Dependencies**:
- https://github.com/mojaloop/project/issues/1653 - accent character sdk support, https://github.com/mojaloop/project/issues/1615 - PATCH notification

## **Accountability**:
- Owner: TBC
- QA/Review: @amarmodus , @elnyry-sam-k

**Comment by amarmodus** [comment]
<img width="1281" alt="Screenshot 2020-09-02 at 22 42 55" src="https://user-images.githubusercontent.com/53434415/92119597-f1ec8e00-edef-11ea-9354-d0e5bf3d133a.png">

**Comment by amarmodus** [comment]
https://github.com/mojaloop/project/issues/1675 - raised for accent character test validation

**Comment by amarmodus** [comment]
https://github.com/mojaloop/project/issues/1676 - raised for patch notification test
