### ISSUE TITLE
Update existing CI/CD for each repo to be compatible with K8s London

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#158]
**Goal**:
As a developer I would like to _Update CI/CD for each repo to be compatible with K8s London_ so that I can automate installations and upgrades

**Tasks**:
- [x] Update Central-Ledger - @mdebarros                        
- [x] Update Forensic-Logging sidecar - @mdebarros                        
- [x] Update Central-Hub - @mdebarros   
- [x] Update Central-Directory - @lazolalucas     
- [x] Update Central-End-User-Registry - @lazolalucas                        

**Acceptance Criteria**:
- [x] Updated CI/CD 2.0 config that can install and upgrade to K8s London

**Dependencies**:
- [x] #64 
- [x] #159

**Comment by mdebarros** [comment]
1. Central-ledger: https://circleci.com/workflow-run/71a404c1-8eb7-4faf-9d64-278394edd606 *(Unit, Integration, Functional & Code-Coverage currently broken due to the MySQL changes. To be fixed in future)*
2. Forensic-logging-sidecar: https://circleci.com/workflow-run/f18a9825-b438-480e-8652-56b0df293de0
