### ISSUE TITLE
TTK - Re-design the scripting functionality to address the needs

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1580]
## **Goal**:
`As a` Mojaloop implementer

`I want to` have a tool that can convert the existing postman collections into testing toolkit format
  
`so that` I can adopt the testing toolkit easily

**Acceptance Criteria**:
- [ ] The new design is ready and documented
- [ ] The new design is reviewed by the core team and implementers if any
- [ ] The new design can serve the requirement from the community
- [ ] The new design can make the creation of the conversion tool easy

**Complexity**: Low

**Uncertainty**: Medium (Design decisions may vary based on the feedback from reviewers)

---

**Tasks**:
- [ ] Investigate the possibilities for the new design to make the scripting functionality consistent and configurable
- [ ] Review with core team
- [ ] Review with implementers if feasible
- [ ] Document the finalised version

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
As per Matt's update the following code converts JS test to TTK test.
https://github.com/msk-/ml-testing-toolkit/blob/feature/support-javascript-tests/src/lib/parseJsTest.js

`const syncClient = require('sync-client')
describe('Server', () => {
  it('starts', () => {
    const fspiopRequest = {
      operationPath: 'whatever',
      method: 'get',
      headers: {},
      params: {},
      apiVersion: {
        minorVersion: 1,
        majorVersion: 0,
        type: 'fspiop',
        asynchronous: false,
      },
      url: 'whatever',
    }
    const resp1 = syncClient(fspiopRequest)
    console.log('this log statement is post-request script 1')
    expect(resp1).whatever()
    const fspiopRequest2 = {
      operationPath: 'whatever',
      method: 'get',
      headers: {},
      params: {},
      apiVersion: {
        minorVersion: 1,
        majorVersion: 1,
        type: 'fspiop',
        asynchronous: false,
      },
      url: 'whatever',
    }
    const resp2 = syncClient(fspiopRequest2)
    console.log('this log statement is post-request script 2')
    expect(resp2).whatever()
    expect(resp2).whatever()
  })
})`
 **to** 
`{
  "test_cases": [
    [
      {
        "operationPath": "whatever",
        "method": "get",
        "headers": {},
        "params": {},
        "apiVersion": {
          "minorVersion": 1,
          "majorVersion": 0,
          "type": "fspiop",
          "asynchronous": false
        },
        "url": "whatever",
        "tests": {
          "assertions": [
            {
              "id": 0,
              "exec": [
                "expect(resp1).whatever()"
              ],
              "description": ""
            }
          ]
        },
        "scripts": {
          "preRequest": {
            "exec": [
              "const fspiopRequest = {",
              "  operationPath: 'whatever',",
              "  method: 'get',",
              "  headers: {},",
              "  params: {},",
              "  apiVersion: {",
              "    minorVersion: 1,",
              "    majorVersion: 0,",
              "    type: 'fspiop',",
              "    asynchronous: false,",
              "  },",
              "  url: 'whatever',",
              "}"
            ]
          },
          "postRequest": {
            "exec": [
              "console.log('this log statement is post-request script 1')"
            ]
          }
        }
      },
      {
        "operationPath": "whatever",
        "method": "get",
        "headers": {},
        "params": {},
        "apiVersion": {
          "minorVersion": 1,
          "majorVersion": 1,
          "type": "fspiop",
          "asynchronous": false
        },
        "url": "whatever",
        "tests": {
          "assertions": [
            {
              "id": 0,
              "exec": [
                "expect(resp2).whatever()"
              ],
              "description": ""
            },
            {
              "id": 1,
              "exec": [
                "expect(resp2).whatever()"
              ],
              "description": ""
            }
          ]
        },
        "scripts": {
          "preRequest": {
            "exec": [
              "const fspiopRequest2 = {",
              "  operationPath: 'whatever',",
              "  method: 'get',",
              "  headers: {},",
              "  params: {},",
              "  apiVersion: {",
              "    minorVersion: 1,",
              "    majorVersion: 1,",
              "    type: 'fspiop',",
              "    asynchronous: false,",
              "  },",
              "  url: 'whatever',",
              "}"
            ]
          },
          "postRequest": {
            "exec": [
              "console.log('this log statement is post-request script 2')"
            ]
          }
        }
      }
    ]
  ]
}`
