### ISSUE TITLE
Identify requirements and feasibility for test collection conversion tool

### ISSUE THREAD

**Issue by georgi-logodazhki** [mojaloop/project#1581]
## **Goal**:
`As a` Mojaloop implementer

`I want to` have a tool that can convert the existing postman collections into testing toolkit format
  
`so that` I can adopt the testing toolkit easily

**Acceptance Criteria**:
- [ ] The Decision is taken whether the tool is needed
- [ ] Investigated the possibilities about the feasibility of creating the tool 
- [ ] Document the requirements if any

**Complexity**: Low

**Uncertainty**: Medium - Dependency on the Core Team

---

**Tasks**:
- [ ] Go through postman collections to identify gaps
- [ ] Discuss with the team about the need and feasibility
- [ ] Gather the requirements from the team if it's feasible
- [ ] Document the observation

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @georgi-logodazhki @vijayg10 
- QA/Review: @elnyry-sam-k

**Comment by elnyry-sam-k** [comment]
not relevant anymore
