### ISSUE TITLE
Standard Baseline - PCI DSS Section 1 : Build a Secure Network - Guidelines and Recommendations

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1582]
## **Goal**:

As a hub operator, I want advice, guidenance and recommendations on how best to address baseline requirements of PCI DSS so that I can ensure my deployment is in line with best practice standards and recommendations from Mojaloop OSS Code Quality and Security Team. 

**Acceptance Criteria**:

- [ ] Set of recommendations and implementation guideliness 

**Complexity**: < Medium > Create a balance between a large variety of adoptors makes the complexity of completing this tasks medium.

**Uncertainty**: < Low > We have the skills, knowledge and capacity to fulfil on time.

---

**Tasks**:

- [ ] Detailed analysis of the PCI DSS standard baseline findings
- [ ] Review existing controls in line with section requirements
- [ ] Provides recommendations on additional controls, processess and tools

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @pedrosousabarreto

**Comment by godfreykutumela** [comment]
To help improve the network perimeter posture of the Mojaloop Hub, the following additional measures are recommended for consideration:

1. Web Gateway - This will enable the addition of a fine-grained web access policy at the perimeter without impacting on the transaction flow and paths
2. API Gateway/Firewall - Allow security policy to be added on the fly to all API calls traversing the API gateway. Developers can focus on writting functionality and the gateway will handle security heavy lifting inclusive of integration to ICAP enabled system like ATP, DCS etc...
3. Privilaged Identity and Access Management - At OSS level ease or default passwords will be used to enable adoptors to implementation the components easily and quickly however there is need to manage all privillaged access on all system components used in Mojaloop.

**Comment by godfreykutumela** [comment]
@pedrosousabarreto Let me when we can do a final review on the proposed recommendation by tomorrow or friday latest so that we can close this story by the end of the sprint.

**Comment by godfreykutumela** [comment]
Attaching detailed baseliness analysis findings for the section 1 which consist of requirement 1 & 2.

[Mojaloop PCI DSS Responsibility Matrix, Gap Analysis & Compliace Baseline Requirement 1 Report - July 2020 v1.0 Final.xlsx](https://github.com/mojaloop/project/files/5098105/Mojaloop.PCI.DSS.Responsibility.Matrix.Gap.Analysis.Compliace.Baseline.Requirement.1.Report.-.July.2020.v1.0.Final.xlsx)
[Mojaloop PCI DSS Responsibility Matrix, Gap Analysis & Compliace Baseline Requirement 2 Report - July 2020 v1.0 Final.xlsx](https://github.com/mojaloop/project/files/5098106/Mojaloop.PCI.DSS.Responsibility.Matrix.Gap.Analysis.Compliace.Baseline.Requirement.2.Report.-.July.2020.v1.0.Final.xlsx)

**Comment by godfreykutumela** [comment]
Updated set of recommendations:

To help improve the network perimeter posture of the Mojaloop Hub, the following additional measures are recommended for consideration:

1.	Web Gateway - This will enable the addition of a fine-grained web access policy at the perimeter without impacting on the transaction flow and paths. This is targeting the envisaged Portal architecture and will act a gatekeeper to protect the switch OWASP Top 10 related vulnerabilties that might slip through our static code analysis checks.

2.	API Gateway/Firewall - Allow security policy to be added on the fly to all API calls traversing the API gateway. Developers can focus on writing functionality and the gateway will handle security heavy lifting inclusive of integration to ICAP enabled system like ATP and DCS. Generally having an API Gateway will simply additions non-functional services – security included.

3.	Privileged Identity and Access Management - At OSS level ease or default passwords will be used to enable adopters to implementation the components easily and quickly however there is need to manage all privileged access on all system components used in Mojaloop. Given many system components involved in the Mojaloop Hub environment, one exposed credential can give an attacker inside access to everything including the CPM where secrets will be safe guided in the near future.
