### ISSUE TITLE
Standard Baseline - PCI DSS Section 2: Protect Data - Guidelines and Recommendations

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1583]
## **Goal**:

As a hub operator, I want advice, guidenance and recommendations on how best to address baseline requirements of PCI DSS so that I can ensure my deployment is in line with best practice standards and recommendations from Mojaloop OSS Code Quality and Security Team. 

**Acceptance Criteria**:

- [ ] Set of recommendations and implementation guideliness 

**Complexity**: < Medium > 

**Uncertainty**: < Low >

---

**Tasks**:

- [x] Detailed analysis of the PCI DSS standard baseline findings
- [x] Review existing controls in line with section requirements
- [x] Provides recommendations on additional controls, processess and tools

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @pedrosousabarreto

**Comment by godfreykutumela** [comment]
[Mojaloop PCI DSS Compliace Baseline Requirement Overall Report - 14 July 2020 v1.0.xlsx](https://github.com/mojaloop/project/files/5156555/Mojaloop.PCI.DSS.Compliace.Baseline.Requirement.Overall.Report.-.14.July.2020.v1.0.xlsx)

Reference material

**Comment by godfreykutumela** [comment]
Our recommendation to hub operators is to comply with all PCI DSS Section 2 ( requirement 3 and 4) as much as possible and additonally Mojaloop is currently developing to more solutions to supplement existing controls in this area in the form of:

1 . Cryptographic Processing Module - This is a separate module to handle all the security processing minimal changes will be required on the current Mojaloop system

This module will be able to interact with a key management system as necessary for the necessary encryption keys, as well as various HSMs to perform secure cryptographic operations. Should an external key management system or physical HSMs not be available the module will provide a key storage system as well as limited cryptographic operations performed in software.

2. RFC 7517 Aligned Key Distribution Solution - The primary problem that's being faced when doing a fresh installation of mojaloop is that every participant will need to have jws of other participant to validate msg and send request to them. Our envaged RFC 7517 aligned key distribution method of  using a JWS Keyset RFC actually solves this.



The RFC basically suggest that the central switch will host JWS Keyset endpoint which every participant can query to get Public key of other participant. In this model the central switch will host JWS Keyset endpoint which every participant can query and this will eliminate the need to use as separate add-on mechanism like MCM and Hub operated key exchange mechanism
