### ISSUE TITLE
Core Functionality Support - Fraud Management Module Security Guidelines and Recommendations

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1587]
## **Goal**:
Review design of proposed Fraud Management System for Hub Operators, identify possible security gaps and propose controls to be discussed by design team.

**Tasks**:
- [ ] Review proposed design [ @rasputtintin  ]
- [ ] Document threat modelling framework for portals design review using STRIDE + OWASP top 20 frameworks [ @rasputtintin ]
- [ ] Identify Gaps [ @rasputtintin ]
- [ ] Document recommendations and improvement plan

**Acceptance Criteria**:
- [ ] List and description of security touch points 
- [ ] List and description of STRIDE threat model to be used
- [ ] List and description of gaps identified
- [ ] List and description of Improvement recommendations

## **Accountability**:
- Owner: @rasputtintin 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
Deferred to PI 12
