### ISSUE TITLE
Core Functionality Support - ISO20022 Adaptation Initiative

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1588]
## **Goal**:
Review design of the proposed ISO20022 adaptation initiative, identify possible security gaps and propose controls to be discussed by design team.

**Tasks**:
- [ ] Review proposed design [ @rasputtintin  ]
- [ ] Document threat modelling framework for portals design review using STRIDE + DREAD [ @rasputtintin ]
- [ ] Identify Gaps [ @rasputtintin ]
- [ ] Document recommendations and improvement plan

**Acceptance Criteria**:
- [ ] List and description of security touch points
- [ ] List and description of STRIDE/DREAD threat model to be used
- [ ] List and description of gaps identified
- [ ] List and description of Improvement recommendations

## **Accountability**:
- Owner: @rasputtintin 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
Deferred to PI 12
