### ISSUE TITLE
Core Functionality Support - PISP Initiation and Transfer Flows Security Review

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1589]
## **Goal**:
Review design of the proposed PISP initiative, identify possible security gaps and propose controls to be discussed by design team.

**Tasks**:
- [x] Review proposed design [ @rasputtintin  ]
- [x] Document threat modelling framework for portals design review using STRIDE + DREAD [ @rasputtintin ]
- [x] Review Linking process using STRIDE methodology [ @rasputtintin ]
- [x] Identify Gaps in Linking Process [ @rasputtintin ]
- [x] Identify Gaps in Transaction process [ @rasputtintin ]
- [x] Document recommendations and improvement plan for Linking process [ @rasputtintin ]
- [x] Document recommendations and improvement plan for Transaction process [ @rasputtintin ]

**Acceptance Criteria**:
- [x] List and description of security touch points 
- [x] List and description of STRIDE/DREAD threat model to be used
- [ ] List and description of gaps identified
- [ ] List and description of Improvement recommendations

## **Accountability**:
- Owner: @rasputtintin 
- QA/Review: @godfreykutumela

**Comment by rasputtintin** [comment]
I am currently reviewing Linking process using STRIDE methodology and will seek to establish:
- Existing proposed controls and their adequacy
- Gaps in linking process from data protection and best practice view if any
- Document recommendations

**Comment by godfreykutumela** [comment]
@rasputtintin Put a due date per task

**Comment by rasputtintin** [comment]
> @rasputtintin Put a due date per task

@godfreykutumela I have added due dates.

**Comment by rasputtintin** [comment]
Completed Linking Security Analysis and will upload report here. Proceeding with Discovery and Consent STRIDE analysis.

**Comment by rasputtintin** [comment]
Linking process review report below:

**Key recommendations (with some areas needing clarification from PISP team):**
1 - The mobile / web application to be used by end users should adhere to best practice standards for mobile and web applications i.e. OWASP top 20
2 - PISP users must have awareness not to use the same credentials for PISP service as well as their main DFSP engagement depending on the relationship.
3 - Authentication related information between the end user and DFSP for the linking process must be encrypted to ensure the PISP cannot intercept / tamper with the data.
4 - Request consent process (web) needs to be airtight to prevent the PISP from generating rogue authentication URLs to be presented to the customer and harvest credentials via Man in the Middle Attacks. There needs to be a way for the end user app to verify that the URL presented by PISP is the actual URL generated by DFSP. If possible sending of this URL should bypass PISP. (Ref section 1.3.1 in PISP Linking Process)
5 - Authentication, OTP process must ensure OTPs cannot be reused or spoofed.
6 - There needs to be a separate special access token or OTP issued by DFSP to the user after the user authenticated successfully per transaction. This token must (Ref section 1.4 in PISP Linking Process):
      (a) Not be reusable
      (b) Be unique for every transaction
      (c) Ensure that DFSP can trace which access token belongs to which user and for what purpose
      (d) Must have an expiry defined and this must be configurable
      (e) Must be for a one time transaction only. This recommendation is for the separate transactional token and not the consent token)
7 - Web Authentication URL will be publicly available hence needs to be protected by reverse proxy / WAF (Web Application Firewall) to protect it from web attacks.
8 - After grant consent, the user should receive an SMS (or any other appropriate alert) to notify them of a successful consent process with specified PISP.
9 - The Special access token must be part of the credential generated by the switch for the PISP. This will link the credential to the user to the DFSP. (Ref section 1.6 in PISP Linking Process)
10 - Requesting a challenge needs a leg where the DFSP authorises the process. (Ref section 1.6.1 and 1.6.2 in PISP Linking Process). This will require the PISP to provide the DFSP with the grant consent secret it received from earlier on when the user granted consent to the PISP.

**Assumptions**
1 - The following are some assumptions we used within our assessment:
2 - Customers will use separate authentication credentials for the PISP application as well as the DFSP service they are subscribed to.
3 - The Mobile Application used by PISP will adhere to best practice security recommendations to ensure user security
PISP onboarding process will follow same process as DFSP onboarding process
4 - The Web Application is publicly facing and accessible to the internet from the DFSP side.

Report - [PISPThreatModel-LinkingAnalysis.pdf](https://github.com/mojaloop/project/files/5292436/PISPThreatModel-LinkingAnalysis.pdf)

**Comment by rasputtintin** [comment]
The following are upcoming tasks:
1 - Seek clarification on Credential generation for PISP process and get team feedback/alignment on recommendations
2 - Review PISP Transaction process design flow
3 - Prepare final PISP report (Linking + Transaction + Feedback)

@godfreykutumela please note the above.

**Comment by rasputtintin** [comment]
Conducted review of existing controls within PISP linking process with Lewis. The following are final recommendations:

1. The mobile / web application to be used by end users should adhere to best practice standards for mobile and web applications i.e. OWASP top 20 a validation needs to be conducted (pentest) before the service is availed to the public. This is to be actioned by PISP / DFSP developers.
2. PISP users must have awareness not to use the same credentials for PISP service as well as their main DFSP engagement depending on the relationship. This is to be actioned by PISP / DFSP developers.
3. Request consent process (web) needs to be airtight to prevent the PISP from generating rogue authentication URLs to be presented to the customer and harvest credentials via Man in the Middle Attacks. There needs to be a way for the end user app to verify that the URL presented by PISP is the actual URL generated by DFSP. If possible sending of this URL should bypass PISP. (Ref section 1.3.1 in PISP Linking Process). This is an existential risk to the process. This is to be actioned by Hub / PISP / DFSP developers.
4. As for authentication using the OTP process, ensure the OTPs are not transferable or reusable. This is to be actioned by DFSP developers.
5. Web Authentication URL will be publicly available hence needs to be protected by reverse proxy / WAF (Web Application Firewall) to protect it from web attacks. This is to be actioned by DFSP developers.
6. After grant consent, the user should receive an SMS (or any other appropriate alert) to notify them of a successful consent process with specified PISP. This will be handled in CRED-17 stage in the Credential registration process (Ref section 1.6 in Credential Registration).
7. During credential generation - the Special access token must be part of the credential generated by the switch for the PISP. This will link the credential to the user to the DFSP. There is a risk the PISP can generate a fake FIDO credential and challenge. (Ref section 1.6 in PISP Linking Process).

**Further Research**
Point 7 (Credential Generation) requires additional research into how FIDO credential generation plus challenge transmission by PISP will be tamper proof. Our discussion led us to believe a rogue PISP may generate a fraudulent public key + FIDO challenge response hence there is need for validation of these artifacts outside PISP.

See attached updated report:
[PISP Threat Model - Linking Analysis 1.1.docx](https://github.com/mojaloop/project/files/5339860/PISP.Threat.Model.-.Linking.Analysis.1.1.docx)

**Comment by rasputtintin** [comment]
@godfreykutumela  Tasks this week for PISP:
1 - Research on FIDO security in PISP linking process to mitigate risk of MITM by rogue PISP on credential generation process.
2 - Complete PISP Transaction flow analysis

**Comment by godfreykutumela** [comment]
Thanks @rasputtintin for the feedback on this investigation and I will move the issue to Review/QA.

**Comment by rasputtintin** [comment]
Completed Transaction review with @lewisdaly and the following are key points:
- Review assumes PISP will enforce authentication with its users
- Proposed transaction level controls using FIDO Challenge appear adequate as user will sign transaction with the private key embedded within their device.

Recommendations
- Review security of private key within mobile device. We recommend storing the private key within the mobile device secure keystore to prevent the app (developed by PISP) from reading the private key.
- PISPs and DFSPs need to take measures to authenticate and fingerprint mobile device to ensure non repudiation with the customers. They need assurance that the customer on the other end of the device is indeed their customer.

@godfreykutumela I will upload final report consolidating linking + transaction STRIDE review details.
