### ISSUE TITLE
Investigate the key management provider options 

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1590]
## **Goal**:
As a OSS developer, I want to make an informed and consultantive decision on one or two major key management providers to support as part of the OSS standard implementation of the CPM KMIS adaptors.

**Acceptance Criteria**:
- [ ] Shortlist of 2 or 3 key management providers to choose from
---

**Tasks**:
- [ ] Vendor analysis
- [ ] Identifiication of top key management providers
- [ ] Vendor presentations 
- [ ] Internal discussions
- [ ] Select one or two providers to support on the envisaged implementation of the CPM KMIP Adaptor

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
The key qualifying criteria for developing an Key Management Adaptor for a specific vendor for testing purposes are:

1. The vendor should support both KMIP and PKCS11 with documented integration API's
2. The vendors  should be part of the top 3 most used Key management system in the west and eastern african block
3. The vendor should be able to provide with integration support even prior to making any product committment
