### ISSUE TITLE
Cryptographic Processing Module (CPM) - Identify, document, and prioritize CPM related use cases for PI 11 and PI 12

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1591]
## **Goal**:

As a hub operator, I want to ensure my cryptographic processing requirements to be prioritized so that I can assure the trust, confidentiality and integrity of my hub services to my eco system participants.

**Acceptance Criteria**:
- [ ] List of identified and prioritized use cases

## **Tasks**:
- [ ] Identify common use cases across existing implementations
- [ ] Detailed need analysis and prioritization
- [ ] Document use case 
- [ ] Develop implementation roadmap

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela
