### ISSUE TITLE
Cryptographic Processing Module (CPM) - Low-level designs (LLD’s) development

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1592]
## **Goal**:
As a OSS developer, I want to start with the development of CPM Low level design based on the approved HLD so that I can have a clear implementation plan for the CPM.

**Tasks**:
- [ ] Breakdown CPM HLD into subcomponents - CPM Core, HSM Adaptors and Key Management Adaptors
- [ ] Develop a detailed design for each component

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by godfreykutumela** [comment]
The CPM Low -level designs have been completed and plans for implementation to resume in PI 12.
