### ISSUE TITLE
Data Protection - PII Data Threat Modelling and Risk Assessment 

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1593]
## **Goal**:
As a hub operator, I want to know what threats and risk are there against my privacy and payment sensitive data so that I can take measures to protect comsumerate with the risk level.

**Acceptance Criteria**:
- [ ] TBD

**Tasks**:
- [ ] Identify datasets
- [ ] Data Architecture Breakdown and Analysis
- [ ] Data flow and analysis with trace
- [ ] Perform Stride/Dread
- [ ] Document threat and risks

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rasputtintin 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
Duplicate story
