### ISSUE TITLE
[auth-service] - Decide and implement import ordering rules

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1595]
## **Goal**:
As an`OSS developer`
I want to `order my imports consistently`
so that `code is readable and maintainable`

**Acceptance Criteria**:
- [ ] decision on import ordering rules
- [ ] import rules implemented in eslint
- [ ] updated all files to conform to import ordering rules

**Complexity**: Low
**Uncertainty**: Low

---

**Tasks**:
- [ ] decide on the format for import rules
- [ ] apply the appropriate settings in `eslint`
- [ ] update the code to conform to these settings

**Done**
- [ ] Acceptance Criteria pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly @eoln
- QA/Review: TBC

**Comment by eoln** [comment]
https://eslint.org/docs/rules/sort-imports
