### ISSUE TITLE
[central-services-shared] - Move Enums over to typescript

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1597]
## **Goal**:
`As an` OSS Developer 

`I want to` have unified enum types imported from `central-services-shared`
  
`so that` I don't have to maintain types across different PISP codebases

**Acceptance Criteria**:
- [ ] Decision: write an `index.d.ts` for `central-services-shared`? Or rewrite some sections of the library with typescript, and add a compilation step to generate and update this automatically?
- [ ] Updated `central-services-shared` with nice typings (either generated or manually specified)

**Complexity**: Medium

**Uncertainty**: High - depending on first decision

---

**Tasks**:
- [ ] Investigate and decide between:
    - Option 1: Write an `index.d.ts` for `central-services-shared`?
    - Option 2: Rewrite some sections of the library with typescript, and add a compilation step to generate and update this automatically?
- [ ] Port over the existing typings from `ambient.d.ts` in `thirdparty-api-adapter` (either directly into the code if option 2, or into a base `index.d.ts` if option 1)
- [ ] Add a typescript -> javascript compilation step
- [ ] Deploy an updated and backwards compatible `central-services-shared` with nice typings (either generated or manually specified)

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly
- QA/Review: TBC

**Comment by yuit** [comment]
This has been completed. The Central Service Shared exposed index.d.ts. As of the time of this comment, the index.d.ts is hand written
