### ISSUE TITLE
[auth-service]: JWS and MutualTLS happy path integration tests

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1598]
## **Goal**:
`As a` Hub operator

`I want to` be assured that the JWS and MutualTLS configuration works on the auth service
  
`so that` I can deploy to production with security guarantees

**Acceptance Criteria**:
- [ ] working integration tests that test JWS and MutualTLS scenarios for auth-service

**Complexity**: Medium -  I'm not sure if we have similar tests out there in mojaloop we can borrow from
**Uncertainty**: Medium - The integration runner for the `auth-service` is somewhat unknown

---

**Tasks**:
- [ ] write a list of possible happy path test cases (just in describe/it blocks is fine) for the various permutations of JWS and mutualTLS configurations available 
- [ ] implement those test cases

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
