### ISSUE TITLE
[sdk-standard-components] - Add error callback requests related to auth-service

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1599]
## **Goal**:
`As an` OSS developer

`I want to` be able to format and send thirdparty error callbacks from the sdk-standard-components library
  
`so that` integration for error scenarios is easy and fun

**Acceptance Criteria**:
- [ ] a list of error callbacks that the `auth-service` may need to send
- [ ] new release of `sdk-standard-components` with error callbacks related to the `auth-service`

**Complexity**: Low - We've done this before! Plenty of times.

**Uncertainty**: Low - we have the list of endpoints in our docs already

---

**Tasks**:
- [ ] compile a list of error callbacks that the `auth-service` may need to send
- [ ] Add new error callback related calls to the `sdk-standard-components` `thirdpartyApi.js` library
- [ ] unit tests as appropriate

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Outdated, please reopen if needed.
