### ISSUE TITLE
[docs] - Update auth-service related error codes  

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1600]
## **Goal**:
`As a` CCB

`I want to` have a unified and concise list of error codes for PISP work
  
`so that` we can communicate the list of error codes easily and effectively with integrators

Now that we're done adding error handling to the `auth-service` with placeholder error codes, we need to go and harmonize the list of error codes for design approval

**Acceptance Criteria**:
- [ ] Updated list of [Error Codes](https://github.com/mojaloop/pisp/blob/master/docs/error_codes.md) for auth-service specific errors

**Complexity**: Low
**Uncertainty**: Medium

---

**Tasks**:
- [ ] Produce a list of error codes and update in [this doc](https://github.com/mojaloop/pisp/blob/master/docs/error_codes.md)

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- [ ] After a design review, there may be a need to go back to the code and update the error codes + tests

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Outdated, please reopen if needed.
