### ISSUE TITLE
DevSecOps - Evaluate Mojaloop default container security settings and make recommendations

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1601]
## **Goal**:
As OSS developer I want improve the security of deployed Mojaloop Kubernetes containers by evaluating their default security settings and making recommendations on improvements for security assurance, compliance and data protection.

**Acceptance Criteria**:
- [ ] List of recommended container security settings with Kubernetes [ @rasputtintin ]
- [ ] List of identified issues with Mojaloop Kubernetes container deployment settings [ @rasputtintin ]
- [ ] List of recommendations as a standard for Mojaloop deployments [ @rasputtintin ]

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:

- [ ] Automate checks on security patches and updates  [ @lewisdaly ]
- [ ] Evaluate Mojaloop default container security settings  [ @rasputtintin ]
- [ ] Generate Mojaloop Open Source Inventory and dependencies to aid security threat investigation [enhancing the current state] and Identify most vulnerable components in use now [ @rasputtintin ]
- [ ] Create and document policies for enabling audit logging in Kubernetes [ @rasputtintin ]
- [ ] Evaluate Mojaloop default container security settings [ @rasputtintin ]

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly @rasputtintin 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
@lewisdaly @rasputtintin This is an umbrella story for CI/CD security process improvement as discussed yesterday so lets detail the tasks and start executing. Thanks

**Comment by godfreykutumela** [comment]
Deferred to PI 12
