### ISSUE TITLE
Create sequence diagrams for Quoting Service to cover scenarios not covered in existing sequence diagrams

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1602]
## **Goal**:
`As an`  implementer

`I want to` have sequence diagrams for Quoting Service covering all aspects and scenarios of the service currently not covered by current sequence diagrams for the service
  
`so that` I can understand and test all process flows that occur within the API

**Acceptance Criteria**:
- [x]  Missing sequence diagrams for the Quoting Service API are created
    - [x] GET /quotes/{id} with a PUT /quotes/{id} or a PUT /quotes/{Id}/error callback
    - [x] POST /quotes with a PUT /quotes/{id} or PUT /post/{id}/error callback

**Complexity**: Low. We have both the functionality and spec to refer to

**Uncertainty**: Low.  We have both the functionality and spec to refer to

---

**Tasks**:

**Note**: _Existing diagram for quoting is merely an overview. Detailed diagrams for all endpoints are required covering low level operations like duplicate-check, quote resend logic, database operations etc._
- [x] Create PlantUML sequence diagrams for missing scenarios (+ve & -ve flows for each):
    - [x] GET /quotes/{id}
    - [x] POST /quotes
    - [x] PUT /quotes/{id}
    - [x] PUT /quotes/{id}/error

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Team review
- [x] Code Style standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/documentation/pull/260

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
