### ISSUE TITLE
Obtain list of TTK enhancements required for its adoption (core team) [2.1.1-02]

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1604]
## **Goal**:
`As a` Product Owner of the TTK
`I want to` understand the blockers / missing features on the toolkit which make it impossible for potential adopters to adopt the TTK
`so that` I can make the TTK the standard testing tool across Mojaloop implementations

**Acceptance Criteria**:
- [x] An agreed list of requirements needed for an MVP from the OSS Core team is documented which when implemented to allow for the TTK's adoption

**Complexity**: Medium -  Meetings / discussions should help

**Uncertainty**: Medium - There's the usual element of the "Unknown"

---
**Tasks**:
- [x] Document needs / Requirements from Core team to use the TTK

**Done**
- [x] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- Related to #1521 

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @amarmodus @elnyry-sam-k

**Comment by elnyry-sam-k** [comment]
Primary requirements for the core team
- [ ] 1. End-to-end test coverage at least as much as the current GP MojaSim postman collection
- [ ] 2. Ability to run as a cron job on a daily schedule [This is already present now]
- [ ] 3. Share results of daily regression test runs on #announcements channel
- [ ] 4. Capability to. easily update tests for new functionality added during the PIs by dev team (or QA members)
- [ ] 5. Ability to run test suites after deployment automatically (post install) and on-demand

**Comment by elnyry-sam-k** [comment]
Only #1 pending, items #2 - #5 are now supported by the TTK
