### ISSUE TITLE
Obtain list of TTK enhancements required for its adoption (for TIPS) [2.1.1-03]

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1605]
## **Goal**:
`As a` Product Owner of the TTK
`I want to` understand the blockers / missing features on the toolkit which make it impossible for potential adopters to adopt the TTK
`so that` I can make the TTK the standard testing tool across Mojaloop implementations

**Acceptance Criteria**:
- [ ] An agreed list of requirements needed for an MVP from the TIPS team is documented which when implemented to allow for the TTK's adoption

**Complexity**: Medium -  Meetings / discussions should help

**Uncertainty**: Medium - There's the usual element of the "Unknown"

---
**Tasks**:
- [ ]  Demo TTK to the team to elicit requirements for MVP
- [ ] Document needs / Requirements from TIPS team to use the TTK

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- Related to #1521 , #1604 

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @amarmodus @elnyry-sam-k
