### ISSUE TITLE
[PISP] - Add thirdparty-api definitions to the `docker-contract` ml-testing-toolkit setup

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1608]
## **Goal**:
`As a` PISP integrator

`I want to` have the thirdparty-api definitions in the `pisp/docker-contract`ml-testing-toolkit
  
`so that` I can easily test my PISP implementation

**Acceptance Criteria**:
- [x] Added thirdparty-api definitions generated from api-snippets
> This will be similar to the swagger templating approaches in `thirdparty-scheme-adapter` and `thirdparty-api-adapter`
- [x] Updated ml-testing-toolkit config for thirdparty-api
- [x] Well documented steps for updating the thirdparty-api definitions from api-snippets (how to run `npm run build:openapi`)

**Complexity**: Medium

**Uncertainty**: Low - we've done this a number of times before now team

---

**Tasks**:
- [x] Add a new `thirdparty-api` in the `pisp/docker-contract`ml-testing-toolkit setup
- [x] Make sure api is generated from api-snippets
- [x] Add any new snippets to api-snippets as required
- [x] Document approach and ensure it is easy to make changes to the api template 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
I've made a start on this - but it is a little blocked by the api snippets updates.

It also seems we need to do additional config for the testing toolkit to get the nice mocked callbacks working.

**Comment by lewisdaly** [comment]
@kleyow I have a working branch here: https://github.com/mojaloop/pisp/tree/feature/1608-api-defs

Hopefully what I've done makes sense - I got about 50% through the updated swagger spec for the thirdparty api, and then I started playing around with the testing toolkit config
