### ISSUE TITLE
TTK Hosted Mode - Maintain DFSP specific rules and settings (Include DB) 

### ISSUE THREAD

**Issue by georgi-logodazhki** [mojaloop/project#1610]
## **Goal**:
`As a` Scheme

`I want to` have hosting capability for the testing toolkit
  
`so that` I can host the TTK and let my DFSP's use that

**Acceptance Criteria**:
- [x] TTK Hosted mode is working as expected
  - [x] when updating rules and settings, those changes doesn't reflect other DFSPs
  - [x] The settings and rules are saved to a central database
- [x] TTK standalone mode is working as expected
  - [x] updating rules and settings is working fine
  - [x] The settings and rules are saved to local JSON files

**Complexity**: Low

**Uncertainty**: Medium - integrating the DB

---

**Tasks**:
- [x] Define system configuration for the MongoDB
- [x] pass dfspId in each function
  - [x] outbound requests
  - [x] inbound requests
- [x] add proper Adapters to support
   - [x] Storage adapter
   - [x] File adapter
   - [x] DB adapter
- [x] Refactor functions related rules and settings to use the new storage adapter
- [x] Include MongoDB in docker-compose and make it configurable
- [x] Test the hosted solution with docker-compose
- [x] add/modify unit tests

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] e2e Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/94

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @georgi-logodazhki 
- QA/Review: @vijayg10
