### ISSUE TITLE
TTK - Import test cases from a folder on local machine

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1611]
## **Goal**:
`As a` Individual implementor

`I want to` identify / customize areas of change in the TTK in a targeted manner
  
`so that` i can easily identify where changes need to be made and make them without needing to worry about their effect on other tests.

**Acceptance Criteria**:
- [ ] Implemented the functionality to import a folder and maintain the folder hierarchy on client side (Refactoring needed at browser local storage). And also make sure all the files are executed.

**Complexity**: Medium (Have to deal with multiple files in the browser storage)

**Uncertainty**: Medium (Need to check the browser's compatibility for importing folder and reading the files inside it and also deal with the local storage limit for a browser session)

---

**Tasks**:
- [ ] Implement the folder import functionality in the browser (Add drag and drop feature also if possible)
- [ ] Refactor the browser storage to store the files and folders (Check if there is any issue if we store large number of files into local storage)
- [ ] Show the folder structure as tree to browse through the individual files
- [ ] Options to send all the test cases in a file, all the test cases from all the files in a folder...etc
- [ ] Test the test case execution

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
