### ISSUE TITLE
TTK - Define the order for the individual test-case files in a folder

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1612]
## **Goal**:
`As a` Individual implementor

`I want to` identify / customize areas of change in the TTK in a targeted manner
  
`so that` i can easily identify where changes need to be made and make them without needing to worry about their effect on other tests.

**Acceptance Criteria**:
- [x] An option to change the order of the test-case files is available in the front-end
- [x] If order is specified, a master.json file should be created in that folder which contains the file sequencing
- [x] If order is not specified, test-cases should be executed in alphabetical order
- [x] If some files in the master file are missed from the import, an error is thrown
- [x] Re-usability of functions such as party lookups / quotes / position checks or retrieval etc., is provided

**Complexity**: Medium (Need to handle the validations and master file creation)

**Uncertainty**: Medium (Take care of the relative paths and multiple inclusions of a file)

---

**Tasks**:
- [x] Define a format for master file
- [x] The import function should read the master.json file if exists in a folder and populate the files in that sequence
- [x] Option to change the file order in front-end by creating / modifying the master.json file
- [x] Validate all the master files and references whether they are part of the import or not
- [x] Test the test-case execution by change the order of the files
- [x] Cater for re-usability of functions such as party lookups / quotes / position checks or retrieval etc

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/51

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
master.json file format will be like below
```
{
    "name": "Hub Collection",
    "order": [
        {
            "type": "file",
            "name": "hub_07_quoting_service.json"
        },
        {
            "type": "folder",
            "name": "hub_01_p2p_happy_path"
        },
        {
            "type": "fileRef",
            "name": "../hub_fsp_setup.json"
        },
        {
            "type": "folder",
            "name": "hub_02_block_transfer",
            "disabled": true
        }
    ]
}
```
