### ISSUE TITLE
TTK - Exporting the test cases folder as a zip file

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1613]
## **Goal**:
`As a` Individual implementor

`I want to` identify / customize areas of change in the TTK in a targeted manner
  
`so that` i can easily identify where changes need to be made and make them without needing to worry about their effect on other tests.

**Acceptance Criteria**:
- [ ] Implement export functionality for the folder structure. Start with exporting the zip file. Create followup stories regarding the other possibilities like Github / S3 integrations, Local file access through native app wrapper...etc

**Complexity**: Medium (Need to consider the performance and memory usage impact of the browser when creating a zip file)

**Uncertainty**: Medium (Its not clear about the zip creation and compression on client side)

---

**Tasks**:
- [ ] Try to create the zip file from browser
- [ ] If the above one is not possible, create the zip file on server side
  - [ ] Create the api endpoint to accept the request body containing the files data and respond with a zip file
  - [ ] Use the API URL in front-end, upload the required files and download the zip file
- [ ] Take care of the compression and performance
- [ ] Make sure the limits for local storage and browser memory are in safe zone for a considerable number of test case files
- [ ] Create followup stories regarding the other possibilities like Github / S3 integrations, Local file access through native app wrapper...etc

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
