### ISSUE TITLE
Identify missing setup items in MojaSim setup collections

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1614]
## **Goal**:
`As a` Hub Operator

`I want to` use the MojaSim setup collections below to setup a Hub completely
 - [MojaloopHub_Setup](https://github.com/mojaloop/postman/blob/master/MojaloopHub_Setup.postman_collection.json)
- [MojaloopSims_Onboarding](https://github.com/mojaloop/postman/blob/master/MojaloopSims_Onboarding.postman_collection.json)
`so that` I can use it for validation and further processing using GP collections

**Acceptance Criteria**:
- [ ] MojaSim setup collections listed above contain all setup steps needed to run MojaSim GoldenPath collection

**Complexity**: <Low> Identify missing setup items and apply fix

**Uncertainty**: <Low> No unknown tasks (as we can use Legacy Sim setup collection for reference)

---

**Tasks**:
- [ ] Missing setup steps in the Golden path setup collections are identified
- [ ] Add new setup steps to address above

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @vijayg10 , @elnyry-sam-k , @amarmodus

**Comment by vijayg10** [comment]
Added a missing variable `"HOST_SIMULATOR"` to postman environment files 'Mojaloop-DEV1-MojaSims.postman_environment' and 'Mojaloop-DEV2-MojaSims.postman_environment'. There is nothing wrong with the mojasim setup collections.

**Comment by elnyry-sam-k** [comment]
Great news, thanks @vijayg10 ... Also, do we need to have a story to create local setup collections for these..
