### ISSUE TITLE
Update content-type header to use v1.1

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1615]
## **Goal**:
`As an` FSP

`I want to` use headers to indicate and understand the version supported by a Switch
  
`so that` I can then understand compatibility and proceed further with messages

**Acceptance Criteria**:
- [x] Switch headers use version 1.1 for Content-Type, Accept as relevant for _outgoing_ messages
- [x] Switch headers support both 1.1 and 1.0 for Content-Type, Accept as relevant for _incoming_ messages
- [ ] ~Postman tests verify support for v1.1, v1.0 messages and v1.1 version on Switch messages~

**Complexity**: <Low> The header changes need to be made (from v1.0 to v1.1) and corresponding changes in tests

**Uncertainty**: <Low> 

**Notes**:
- v1.1 and v1.0 messages should be accepted by the Switch
- Pass-through messages are not updated
- Only messages originating in the Switch will always use v1.1
- Currently identified: `GET /parties` which triggers `GET /participants` and then `GET /parties`; Error callbacks and PATCH notification 
- timeout handler has header version hardcoded to 1.0
- PATCH returns whatever version has been sent by dfsp, the sdk-standard-components method has 1.0 hardcoded. when fixed to 1.1 it returns back 1.1. 
- what to do with simulators?

---

**Tasks**:
- [x] Update content-type, Accept headers to v1.1 as needed in core services for outgoing messages
  - [x] sdk-standard-component
  - [x] sdk-scheme-adapter
  - [x] Decide on the way to pass the api version into central-services-shared methods (switchDefaultHeaders and sendRequest)
  - [x] central-services-shared
  - [x] ALS
  - [x] quoting-service
  - [x] central-ledger
  - [x] transaction-requests (including authorizations)
- [x] Support content-type, Accept headers for both v1.1, v1.0 as needed in core services for incoming messages
  - [x] ALS
  - [x] quoting-service
  - [x] central-ledger
  - [x] transaction-requests (including authorizations)
- [ ] Update MojaSim postman tests for the headers
  - [x] create example tests
  - [ ] ~on support for v1.1, v1.0~
  - [ ] ~and checks on messages coming out of the Switch (to have v1.1)~

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-standard-components/pull/94
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/199 
- [x] https://github.com/mojaloop/central-services-shared/pull/251
- [x] https://github.com/mojaloop/quoting-service/pull/240
- [x] https://github.com/mojaloop/central-ledger/pull/782
- [x] https://github.com/mojaloop/account-lookup-service/pull/370
- [x] https://github.com/mojaloop/transaction-requests-service/pull/53
- [x] https://github.com/mojaloop/ml-api-adapter/pull/459
- [x] https://github.com/mojaloop/postman/pull/171

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @elnyry-sam-k
