### ISSUE TITLE
Key Management  - Design a new key distribution method that aligns to RFC 7517

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1616]
## **Goal**:

`As a OSS developer, I want simply the process of key distribution method and align it to RFC 7517 - The RFC suggest that the central switch will host JWS Keyset endpoint which every participant can query and this will eliminate the need to use as separate add on mechanism like MCM.

**Acceptance Criteria**:
- [ ] TBD

**

**Tasks**:
- [ ] High Level Design - Microservices and PKI Datastore
- [ ] Define an interface to CPM (future need)
- [ ] Presentation to various committess for approval
- [ ] Low Level Designs and Implementation plans

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
Deferred to PI 12
