### ISSUE TITLE
Helm Release v11.0.0: Updates to helm, Supporting QA, Fixes, Releases

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1617]
## **Goal**:
`As a` ML OSS Code base maintainer

`I want to` validate and make a Helm release in PI-11 (Sprint 11.3) that is successfully validated by the Golden path tests
  
`so that` Community members can take and use a version of Mojaloop Switch services bundle that is tested and contains latest features and enhancements (added in and PI-11(Sprints 11.1, 11.2, 11.3) so far)

This specific story is for making necessary changes for supporting Deployment, QA, Fixes, Integration and performing end-to-end testing for all the changes made since Helm v11.0.0

**Acceptance Criteria**:
- [x] Helm RC v11.0.0 is validated on dev2 and iterated until 100% result with postman GoldenPath collection is achieved
- [x] QA (Golden path) on deployments done on AWS dev2 environment is done
- [x] Bugs are logged based on observations, failures
- [x] Bugs logged are fixed if critical to make subsequent releases in individual services (or Helm)
- [x] All the changes needed for supporting v11.0.0 of Helm are done
- [x] Helm v11.0.0 release notes is drafted and published

**Complexity**: <Medium> Involves all core and supporting services

**Uncertainty**: <Low> No major feature changes, only minor fixes and maintenance changes since previous release

---

**Tasks**:
- [x] Make releases on all core services to have latest images / versions [@oderayi, @rmothilal ]
   _**Note**: Done for all services except for Central Settlement and services that will be affected by story #1615_ 
- [x] Identify changes needed for helm (config / default.json) [@oderayi] 
- [x] Initial PR with changes for v11.0.0 [@oderayi, @elnyry-sam-k ] 
  - [x] Update MojaSim as default option (LegacySim as non-default) [@vijayg10 ] 
  - [x] Initial PR review
  - [x] Deploy, validate, fix issues, redeploy [@elnyry-sam-k ]
  - [x] With stable deployment test Golden path [@elnyry-sam-k ]
- [x] Identify issues with QA Scripts if any - fix them and retest [@elnyry-sam-k ]
  - [ ] Add local env files corresponding to MojaSim GP collections --> covered in #1760 
- [x] Identify Bugs, log them [@elnyry-sam-k ]
- [x] Validate finance portal [@amarmodus ]
- [x] Fix bugs logged if critical
  - [x] email-notifier pod issue [@mdebarros fixed, parameterized config as well]
  - [x] bulk api adapter start-up 'axios' issue [@rmothilal - fixed ]
  - [x] Bug #1734  [@rmothilal - fixed ]
  - [x] Bug #1724  [@mdebarros  - fixed ]
- [x] Deploy, validate on AWS dev2 [@elnyry-sam-k ]
- [ ] Validate upgrade scenario (from v10.4.0 --> v11.0.0) [@mdebarros] --> Followed-up in #1759 
- [x] Validate with Legacy Simulator collection [@elnyry-sam-k ] (fixed Legacy Sim GP collection)
- [x] Validate with Mojaloop Simulator collection [@elnyry-sam-k ]
- [x] Release notes for helm v11.0.0 is drafted [@elnyry-sam-k ]
- [x] Helm v11.0.0 released [@elnyry-sam-k ]
- [x] Deployment of released Helm v11.0.0 on **Dev2** [@elnyry-sam-k ]
  - [x] Helm v11.0.0 is deployed on **Dev2** successfully [@elnyry-sam-k ]
  - [x] Validation using Golden path regression tests etc on Dev2 [@elnyry-sam-k ]
    - [x] Legacy Simulator collection [@elnyry-sam-k ]
    - [x] Mojaloop Simulator collection [@elnyry-sam-k ]
  - [x] Validate finance portal [@amarmodus ]
- [x] Deployment of released Helm v11.0.0 on **Dev1** [@elnyry-sam-k ]
  - [x] Helm v11.0.0 is deployed on **Dev1** successfully [@elnyry-sam-k ]
  - [x] Validation using Golden path regression tests etc on Dev1 [@elnyry-sam-k ]
    - [x] Legacy Simulator collection (seeing 2 test failures, fixed) [@elnyry-sam-k ]
    - [x] Mojaloop Simulator collection [@elnyry-sam-k ]
    - [x] TTK [@vijayg10 ]
- [ ] Deployment of released Helm v11.0.0 on **Local Deployment** [ @vijayg10  ]
  - [x] Helm v11.0.0 is deployed on **Local Deployment** successfully [ @vijayg10 ]
  - [ ] Validation using Golden path regression tests etc on Local Deployment [ @vijayg10 ]
    - [ ] Legacy Simulator collection [ @vijayg10 ]
    - [ ] Mojaloop Simulator collection [ @vijayg10 ]
    - [ ] TTK [@vijayg10 ]

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Postman Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-settlement/pull/322
- [x] https://github.com/mojaloop/helm/pull/375
- [x] https://github.com/mojaloop/helm/pull/379
- [x] https://github.com/mojaloop/helm/pull/393
- [x] https://github.com/mojaloop/helm/pull/394

## **Follow-up**:
- N/A

**Dependencies**:
- #1657
- #1615
- #1485 

## **Accountability**:
- Owner: TBC
- QA/Review: @mdebarros @elnyry-sam-k

**Comment by elnyry-sam-k** [comment]
Couple of follow-up issues #1759 and #1760 to address couple of pending items
