### ISSUE TITLE
[thirdparty-api-adapter] - Implement workflow to ensure github pr titles follow conventional commits.

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#1618]
## **Goal**:
`As a` developer

`I want to` have pull request titles follow conventional commits
  
`so that` when pull requests are squashed that the squashed commit message follows conventional commits standard.

**Acceptance Criteria**:
- [ ] Automated workflow added that checks pull request title and passes or fails the pull request

**Complexity**: Low

**Uncertainty**: Low

Integrating the feature can use Github actions if preferable to CircleCi.
https://github.com/marketplace?type=actions&query=pull+request+conventional+commits
---

**Tasks**:
- [ ] Add an automated workflow that passes/fails pull requests depending on if the title follows conventional commit format

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
This is being followed up in the DA, and will be available as a circleci orb shortly.

**Comment by lewisdaly** [comment]
This is a simple update to the circleci `config.yaml` file. See this example: https://github.com/mojaloop/central-ledger/blob/master/.circleci/config.yml#L400
