### ISSUE TITLE
Forensic Logging Sidecar (FLS): Determine type of events

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#162]
**Goal**:
As a developer I would like to _determine type of events logged by FLS_ so that I can implement the missing events (that are desired)

**Tasks**:
- [x] Determine & document type of events logged by FLS

**Acceptance Criteria**:
- [ ] A document is available and lists the events logged by the FLS in its current state
- [x] A document showing additional events that need to be implemented

**Dependencies**:
- [x] Logging requirements doc [here](https://www.dropbox.com/s/sh6qhfte46atlpl/Logging%20Requirements.docx?dl=0)

**Comment by elnyry** [comment]
The consensus is that right now the FLS logging is not focussed and very extensive beyond any reasonable needs, this needs to be overhauled. There needs to be focussed logging and only for required events. A lot of logging is at service & hub level (account logins, service starting/stopping etc), so this needs to be revisited when those aspects are production ready (right now they aren't).

**Comment by kjw000** [comment]
One item that came out as a result of the Fraud discussion is we should potentially just log everything.  Storage is cheap and we should just try to log every user interaction with the system.

**Comment by elnyry** [comment]
Thats interesting. Its just just about storage but bandwidth, processing as well, but point noted.

**Comment by elnyry** [comment]
• logRequest - from request: method, timestamp, url, body, auth
	• src/admin/charge
		○ exports.create, exports.update
	• Src/admin/participants
		○ Create, update
	• src/admin/party
		○ Create, remove, update, updateRole
	• src/admin/role
		○ createRole, updateRole, deleteRole
	• src/admin/token
		○ Create
	• src/admin/webhooks 
		○ rejectExpired, settle, rejectExpiredTokens
	• src/api/messages
		○ sendMessage
	• src/api/participants
		○ create, updatePartyCredentials, updateParticipantSettlement, getByName
	• src/api/token
		○ Create
	• src/api/transfers
prepareTransfer, fulfillTransfer, rejectTransfer
