### ISSUE TITLE
[ml-operator] - Docker Hub scaper/cache service

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1620]
## **Goal**:
`As a` hub operator

`I want to` be able to easily get the next docker image tag based on a current image and upgrade strategy
  
`so that` I can easily implement other tooling to automate docker image tags

**Acceptance Criteria**:
- [x] API Design for cache service
- [x] Basic api implementation, with redis as a simple cache
- [ ] Helm example and running service for Mojaloop services deployed on dev1 cluster

**Complexity**: Medium
**Uncertainty**: Low - We know what this service needs to do, and have a POC example

---

**Tasks**:
- [x] define API for image-watcher
- [x] implement basic image-watcher
- [x] unit tests on `./src/domain` with > 75% coverage
- [x] setup ci/cd
~- [ ] helm configuration~
~- [ ] deploy to dev1 cluster~
Helm steps covered in #1623 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-operator/pull/1
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: @matdehaast, @elnyry-sam-k
