### ISSUE TITLE
[ml-operator] - watch resources based on labels

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1621]
## **Goal**:
`As a` hub operator

`I want` a service to watch my running images
  
`so that` I can get alerts in the future

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Medium

**Uncertainty**: Low - we have a POC already, just need to expand on it

---

**Tasks**:
- [ ] client that checks with image-watcher web service for available patches
  - [x] pass in "my image, version, and desired upgrade (e.g. security patch)"
  - [x] configurable times (daily, weekly, etc)
  - [x] configurable images, based on kubernetes labels
- [ ] unit tests

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/ml-operator/pull/3

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: TBC
