### ISSUE TITLE
[ml-operator] - repo and ci/cd setup

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1622]
## **Goal**:
`As a` OSS developer

`I want to` automate the ml-operator repo
  
`so that` I can easily maintain the project

**Acceptance Criteria**:
- for both ml-operator and image-watcher repos:
- [x] working automated deployments with changelogs
- [ ] ci/cd setup working with tests passing

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- for both ml-operator and image-watcher repos:
  - [x] ci/cd setup
  - [x] automated versioning and release

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
none - work was commited directly to master

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
