### ISSUE TITLE
[ml-operator] - helm config and test deployment

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1623]
## **Goal**:
`As a` hub operator

`I want to` be able to deploy the ml-operator easily with k8s and helm
  
`so that` it's easy to run the ml-operator on my deployment

**Acceptance Criteria**:
- [x] working helm config in `ml-operator` repo
- [x] live deployment for testing in `pisp` cluster
- [x] detailed instructions for how to deploy from scratch

**Complexity**: Medium

**Uncertainty**: Medium - Where will this live? How will it be installed?

---

**Tasks**:
- [x] detailed instructions on how to deploy, and what you need to do to get the operator inspecting _your_ pods
- [x] helm configuration in `ml-operator` repo to deploy the operator
- [x] live test (and working) deployment on pisp cluster

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/ml-operator/pull/5

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
