### ISSUE TITLE
[ml-operator] - Slack notification

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1624]
## **Goal**:
`As a` hub operator

`I want to` get a slack notification from the ml-operator
  
`so that` I am informed and can update my cluster

**Acceptance Criteria**:
- [x] slack notification config
- [x] working periodic slack notification to `#announcements-ci/cd` channel

**Complexity**: Medium - building out the messages with the helm instructions may be difficult

**Uncertainty**: Low - We already have this working in the demo

---

**Tasks**:

- [x] for a given cluster state, produce a `helm upgrade ...` which will apply the security patches
  > If this is a one-liner, then great! Otherwise maybe we will need to output a proper `values.yml` file
- [x] slack notification to inform operator that security patches are available
~- [ ] deploy and run on the `dev1` cluster~ - handled elsewhere

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
