### ISSUE TITLE
[ml-operator] - Configure and validate first start behaviour

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1625]
## **Goal**:
`As a` hub operator

`I want to` get a notification from `ml-operator` after first installing mojaloop if my images have patches available
  
`so that` I can update my running deployment immediately after starting it

**Acceptance Criteria**:
- [ ] clarify how the ml-operator will work on first install
- [ ] slack notification tested on install with older images

**Complexity**: Medium
**Uncertainty**: Medium - testing/verifying may be difficult

---

**Tasks**:
- [ ] clarify installation instructions for ml-operator: before or after a deployment?
- [ ] configure the startup behaviour 
- [ ] test slack notification on first install

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
