### ISSUE TITLE
[ml-operator/image-watcher] - make images to watch configurable by api

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1626]
## **Goal**:
`As a` hub operator

`I want to` be able to add and remove images to watch from the image-watcher api
  
`so that` I don't need to start and stop the image watcher to watch new images

**Acceptance Criteria**:
- [ ] updated image watcher api specification
- [ ] images to watch can be added and removed through the api
- [ ] simple basic auth on the api call

**Complexity**:  Medium

**Uncertainty**: Medium

---

**Tasks**:
- [ ] update the image watcher api specification to allow admins to add or remove images to watch (`POST`, `DELETE`)
- [ ] images to watch can be added and removed through the api
- [ ] simple basic auth on the api call
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
