### ISSUE TITLE
Research branching strategies for applying security patches to images in LTS

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1627]
## **Goal**:
`As a` OSS Developer

`I want to` have a clear statement on the mojaloop branching strategies for LTS 
  
`so that` I can implement security patch automation

**Acceptance Criteria**:
- [ ] branching strategy for mojaloop recommendation
- [ ] approval by DA
- [ ] example strategy implemented on `ml-api-adapter` repo

**Complexity**:  Medium
**Uncertainty**: High

---

**Tasks**:
- [x] Research different strategies for branching in order to apply security patches to existing images
- [x] Look into dependabot and CI/CD - how might this be automated?
- [ ] Write a document along with examples and clear diagrams to communicate this
- [ ] Present to the DA

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Matt suggests looking into `laravel`'s versioning strategy

**Comment by lewisdaly** [comment]
I think we're making good progress on this.

This image demonstrates the approach we want to take:

![Screen Shot 2020-09-18 at 2.27.44 pm.png](https://images.zenhubusercontent.com/5cd963af3613073e20e46e60/96e73a19-f0e8-48c7-bc12-6f52c7b558d8)


Releaseflow: http://releaseflow.org/ looks pretty close to what we want to implement.

**Comment by lewisdaly** [comment]
- How do we determine what should be a supported version for a service?
-

**Comment by elnyry-sam-k** [comment]
> * How do we determine what should be a supported version for a service?
> * How does this pattern work if we "support" a version with a bugfix != 0?

@lewisdaly , as we covered in the PI-12 presentation, I think its a decision to be taken by the Mojaloop Foundation whether to support LTS versions or to allow it to be competitive space where commercial entities can play the role of supporting institutions..

So, can we close this for now then?

**Comment by lewisdaly** [comment]
Yeah, I'd say so.

Thanks Sam
________________________________
