### ISSUE TITLE
[auth-service] test api routes in `index.test.ts`

### ISSUE THREAD

**Issue by akapur99** [mojaloop/project#1629]
## **Goal**:
`As a` Auth Service

`I want to` to test all my routes
  
`so that` I can check against any errors

---

**Tasks**:
- [ ] Mock out handlers
- [ ] Create route tests to test that each endpoint is hitting the correct handler

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
