### ISSUE TITLE
TTK HOSTED MODE - Maintain DFSP specific reports and logs

### ISSUE THREAD

**Issue by georgi-logodazhki** [mojaloop/project#1630]
## **Goal**:
`As a` Scheme

`I want to` have hosting capability for the testing toolkit
  
`so that` I can host the TTK and let my DFSP's use that

**Acceptance Criteria**:
- [ ] The reports and logs are saved to a central database

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] Refactor functions related reports and logs to use the new storage adapter

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] e2e Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @georgi-logodazhki 
- QA/Review: @vijayg10

**Comment by elnyry-sam-k** [comment]
Duplicate of #1467
