### ISSUE TITLE
Determine Central-ledger Fulfil sequence diagram and test collection gaps 

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#1631]
## **Goal**:
`As a` switch operational user 

`I want to` determine the difference between the PlantUML sequence diagrams for the Central-Ledger [Fulfil] and the TTK test collection
  
`so that` I could use it to determine the amount of outstanding working for the follow up story #1561

**Acceptance Criteria**:
- [x] Missing diagrams and tests are found and stories to cater for them are updated and created

**Complexity**: Low -  This is just and investigation story to determine the missing information

**Uncertainty**: Low - There is a level of uncertainty with regards to missing postman tests and sequence diagrams

---
**Note**:
Refer to information in the story #1491

**Tasks**:
- [x] Identify and document gaps in the test collections
- [x] Identify and document gaps in the sequence diagrams
  - [x] Missing diagram for fulfil negative scenarios ABORT and REJECT #1658
- [x] Peer review
- [x] Create follow-up stories for missing sequence diagrams and tests

**Done**
- [x] Acceptance Criteria pass
- [x] New stories created for missing diagrams
- [x] Base story #1561 is updated with findings from this story

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @amarmodus @elnyry-sam-k
