### ISSUE TITLE
Determine Central-ledger Admin sequence diagram and test collection gaps 

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1632]
## **Goal**:
`As a` switch operational user 

`I want to` determine the difference between the PlantUML sequence diagrams for the Central-Ledger [Admin] and the TTK test collection
  
`so that` I could use it to determine the amount of outstanding working for the follow up story #1559

**Acceptance Criteria**:
- [x] Missing diagrams and tests are found and stories to cater for them are updated and created

**Complexity**: Low -  This is just and investigation story to determine the missing information

**Uncertainty**: Low - There is a level of uncertainty with regards to missing postman tests and sequence diagrams

---
**Note**: Refer to information in the story #1491

**Tasks**:
- [x] Identify and document gaps in the test collections [@oderayi] 
  **Missing Tests [ #1651 ]**:
  **Note**: _No GP tests, but some existing tests were found in "OSS-API-Tests-old" Postman collection_.
   - GET /enums (no assertions)
   - GET /health (incomplete assertions)
   - GET /metrics (incomplete assertions)
   - GET /participants (no assertions)
   - POST /participants (no assertions)
   - GET /participants/limits (incomplete assertions)
   - GET /participants/{name} (incomplete assertions)
   - PUT /participants/{name}
   - GET /participants/{name}/endpoints (incomplete assertions)
   - POST /participants/{name}/endpoints
   - GET /participants/{name}/limits
   - PUT /participants/{name}/limits
   - GET /participants/{name}/positions (incomplete)
   - GET /participants/{name}/accounts (no assertions)
   - POST /participants/{name}/accounts 
   - POST /participants/{name}/initialPositionAndLimits
   - POST /participants/{name}/accounts/{id}
   - PUT /participants/{name}/accounts/{id}
   - PUT /participants/{name}/accounts/{id}/transfers/{id}
   - GET /settlementModels
   - POST /settlementModels
   - GET /settlementModels/{name}
   - PUT /settlementModels/{name}
   - GET /transactions/{id}
- [x] Identify and document gaps in the sequence diagrams [@oderayi] 
   **Missing Diagrams [ #1650 ]**:
   - GET /health
   - GET /enums
   - GET /metrics
   - GET /participants
   - POST /participants
   - GET /participants/{name}
   - PUT /participants/{name}
   - GET /participants/{name}/endpoints
   - PUT /participants/{name}/endpoints
   - GET /participants/{name}/accounts
   - POST /participants/{name}/accounts
   - POST /participants/{name}/accounts/{id}
   - PUT /participants/{name}/accounts/{id}
   - PUT /participants/{name}/accounts/{id}/transfers/{transferId}
   - GET /settlementModels
   - POST /settlementModels
   - GET /settlementModels/{name}
   - PUT /settlementModels/{name}
   - GET /transactions/{id}
- [x] Peer review
- [x] Create follow-up stories for missing sequence diagrams and tests

**Done**
- [x] Acceptance Criteria pass
- [x] New stories created for missing diagrams
- [x] Base story #1559 is updated with findings from this story

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- #1650
- #1651

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @amarmodus @elnyry-sam-k
