### ISSUE TITLE
Determine gaps in Central-Settlements sequence diagrams and test collections

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1633]
## **Goal**:
`As a` switch operational user 

`I want to` determine the difference between the sequence diagrams (PlantUML) for the Central-Settlements and the TTK test collection
  
`so that` I can use it to determine the follow-up actions needed (follow up story #1632 )

**Acceptance Criteria**:
- [ ] Missing diagrams and tests are found and stories to cater for them are updated and created

**Complexity**: Low -  This is just and investigation story to determine the missing information

**Uncertainty**: Low - There is a level of uncertainty with regards to missing postman tests and sequence diagrams

---
**Note**:
Refer to information in the story #1491

**Tasks**:
- [ ] Identify and document gaps in the test collections
- [ ] Identify and document gaps in the sequence diagrams
- [ ] Peer review
- [ ] Create follow-up stories for missing sequence diagrams and tests

**Done**
- [ ] Acceptance Criteria pass
- [ ] New stories created for missing diagrams
- [ ] Base story #1559 is updated with findings from this story

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- #1632 

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @amarmodus @elnyry-sam-k
