### ISSUE TITLE
Determine Central-Ledger [Reject/Abort] sequence diagram and test collection gaps

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1634]
## **Goal**:
`As a` switch operational user 

`I want to` determine the difference between the PlantUML sequence diagrams for the Central-Ledger [Reject/Abort] and the TTK test collection
  
`so that` I could use it to determine the amount of outstanding working for the follow up story #1560 

**Acceptance Criteria**:
- [x] Missing diagrams and tests are found and stories to cater for them are updated and created

**Complexity**: Low -  This is just and investigation story to determine the missing information

**Uncertainty**: Low - There is a level of uncertainty with regards to missing postman tests and sequence diagrams

---
**Note**:
Refer to information in the story #1491

**Tasks**:
- [x] Identify and document gaps in the test collections [@oderayi] 
  _**Notes**_:
   - Existing Postman Golden Path collections need to be migrated to TTK
   - Clarification should be sought for some `Reject` tests with requests to `/transfers/{ID}` rather than `/transfers/{ID}/error`
- [x] Identify and document gaps in the sequence diagrams [@oderayi] 
   _**Note**_:
   - Sequence diagrams are complete
   - Clarifications should be sought for some diagrams with `Reject` requests to `/transfers/{ID}` rather than `/transfers/{ID}/error`
      - https://docs.mojaloop.io/documentation/mojaloop-technical-overview/central-ledger/transfers/2.2.0-fulfil-reject-transfer.html
      - https://docs.mojaloop.io/documentation/mojaloop-technical-overview/central-ledger/transfers/2.2.0-fulfil-reject-transfer-v1.1.html
- [x] Peer review [@elnyry-sam-k @rmothilal @vgenev] 
- ~Create follow-up stories for missing sequence diagrams and tests~ [@oderayi] 

**Done**
- [x] Acceptance Criteria pass
- ~New stories created for missing diagrams~
- [x] Base story #1560  is updated with findings from this story

## **Pull Requests**:
- [x] https://github.com/mojaloop/documentation/pull/258

## **Follow-up**:
- https://github.com/mojaloop/project/issues/1560

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @amarmodus @elnyry-sam-k
