### ISSUE TITLE
 Determine Central-ledger timeout sequence diagram and test collection gaps

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1635]
## **Goal**:
`As a` switch operational user 

`I want to` determine the difference between the PlantUML sequence diagrams for the Central-Ledger [Timeout] and the TTK test collection
  
`so that` I could use it to determine the amount of outstanding working for the follow up story #1562

**Acceptance Criteria**:
- [ ] Missing diagrams and tests are found and stories to cater for them are updated and created

**Complexity**: Low -  This is just and investigation story to determine the missing information

**Uncertainty**: Low - There is a level of uncertainty with regards to missing postman tests and sequence diagrams

---
**Note**:
Refer to information in the story #1491

**Tasks**:
- [ ] Identify and document gaps in the test collections
- [ ] Identify and document gaps in the sequence diagrams
- [ ] Peer review
- [ ] Create follow-up stories for missing sequence diagrams and tests

**Done**
- [ ] Acceptance Criteria pass
- [ ] New stories created for missing diagrams
- [ ] Base story #1562 is updated with findings from this story

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @amarmodus @elnyry-sam-k
