### ISSUE TITLE
Cryptographic Processing Module (CPM) - Establish and approve a low level design framework

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1638]
## **Goal**:
As a OSS developer, I want to provide and communicate a framework for the development of CPM Low level design based on the approved HLD so that I can have a clear plan and breakdown activities for the process of developing LLD's. 

**Acceptance Criteria**:
- [ ] Complete framework covering current use cases and all key components of the HLD

**Tasks**:
- [x] Define a CPM LLD framework @godfreykutumela 
- [x] Provide a detailed breakdown on components and subcomponents in scope @godfreykutumela 
- [ ] Dicsuss and approve the framework with the CQS team and start development process @godfreykutumela 

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
CPM Low level design framework for review - @godfreykutumela 
[Mojaloop CPM LLD Framework - 1 Sept 2020.docx](https://github.com/mojaloop/project/files/5156307/Mojaloop.CPM.LLD.Framework.-.1.Sept.2020.docx)
