### ISSUE TITLE
Implementation Support - GDPR Data Protection Impact Assessment (DPIA) Guideline : Approach Note, Templates and Tools

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1639]
## **Goal**:
`As a hub operator, I need a guideline on how to approach GDPR requirement for performing a data protection impact assessment on my implementation to ensure alignment with best practice standards. 

**Tasks**:
- [x] Define an Impact assessment framework and approach
- [x] Design a base template for Impact assessment framework
- [x] Recommend assessment tools
- [x] Present the DPIA Framework and Approach Note to Mowali

**Done**
- [x] Acceptance Criteria pass
- 

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
GDPR DPIA approach note for Mowali - In Review/QA
[GDPR Data Protection Impact Analysis - 1 September 2020.docx](https://github.com/mojaloop/project/files/5155108/GDPR.Data.Protection.Impact.Analysis.-.1.September.2020.docx)

**Comment by godfreykutumela** [comment]
DPIA Template - 
[GDPR DPIA Template - 1 Sept 2020.pdf](https://github.com/mojaloop/project/files/5156422/GDPR.DPIA.Template.-.1.Sept.2020.pdf)

**Comment by godfreykutumela** [comment]
GDPR Toolset -

For Mowali GDPR tooling for unstrcutured data management component we recommend Varonis GDPR Data Protection Platform - https://www.varonis.com/solutions/gdpr-compliance/# This recommended tool can be used as basis for evaluting other tools - open source or commercial.

**Comment by godfreykutumela** [comment]
DPIA Assessment guideline session 1 has been setup for the 8th September with all Mowali GDPR stakeholders.
