### ISSUE TITLE
Implement callback capability with participant detail look-up

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#164]
**Goal**:
As a developer I want to _Implement callback capability with participant detail look-up_ so that notifications can be sent out.

**Tasks**:
- [ ] Refactor for HTTP REST Callbacks

**Acceptance Criteria**:
- [ ] Central Services to provide CRUD operations for notification details via the REST service.
- [ ] Notification Handler is able to look up the notification details from a API REST call to the central services.

**Dependencies**:
- None currently

**Comment by elnyry** [comment]
Duplicate of #351 , #352
