### ISSUE TITLE
Implement GET /quotes/{id} in sdk-scheme-adapter

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1640]
## **Goal**:
`As a` implementor

`I want to` have sdk's support for GET /quotes/{id}
  
`so that` it can be used in golden path test and other implementers.

Note:
currently it gives following response for GET /quotes/{id} callback
```JSON
"errorInformation":{
    "errorCode":"3000",
    "errorDescription":"Generic client error - Not found"
}
```
**Acceptance Criteria**:
- [x] `When` a request GET /quotes/{id} is sent to SDK Scheme Adapter, `then` it should respond with PUT /quotes/{id} callback from the stored quote as per the API spec for both
   - [x] happy path
   - [x] error path

**Complexity**: Low.  Straight forward implementation 

**Uncertainty**: Low.  API spec is clear 

---

**Tasks**:
- [x] Create handler for GET /quotes/{id} in sdk-scheme-adapter
- [ ] Create handler for GET /quoterequests/{quoteId} in mojaloop-simulator
- [ ] Create Postman Test for endpoint
- [x] Unit Test

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/228

## **Follow-up**:
- Create a new story to handle the `GET /quotes/{ID}` in a better way when the cache does not return any data

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
