### ISSUE TITLE
[Demo Server] Update Consent Model

### ISSUE THREAD

**Issue by akapur99** [mojaloop/project#1641]
## **Goal**:
`As a` PISP demo server

`I want to` have a well-defined Consent object model
  
`so that` I can use typescript effectively, and improve code clarity 

**Complexity**: Low 

**Uncertainty**: Medium : Might require more changes later on

---

**Tasks**:
- [x] Add necessary fields to `Consent` model

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/pisp-demo-server/pull/18

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
