### ISSUE TITLE
Create sequence diagrams for Bulk Quotes API

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1643]
## **Goal**:
`As an`  DFSP / Hub

`I want to` have designs for Bulk Quotes in the form of sequence diagrams
  
`so that` I can understand and test all process flows that occur within the API for `bulkQuotes`

**Acceptance Criteria**:
- [x]  Missing sequence diagrams for Bulk Quotes API are created

**Complexity**: Low

**Uncertainty**: Low

---
**Note**:  The diagrams should be same as Quoting Service passthrough

**Tasks**:

- [x] Create sequence diagrams:
  - [x] POST /bulkQuotes
    - [x] PUT /bulkQuotes/{id}
    - [x] PUT /bulkQuotes/{id}/error
  - [x] GET /bulkQuotes/{id}

**Done**:
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Code Style (seq. diagram)

## **Pull Requests**:
- [x] https://github.com/mojaloop/documentation/pull/266

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @elnyry-sam-k 
- QA/Review: TBC
