### ISSUE TITLE
[Demo Server] Fix Linking Diagram Errors

### ISSUE THREAD

**Issue by akapur99** [mojaloop/project#1645]
## **Goal**:
`As a` PISP Demo Server
`I want to` update linking diagrams and fix errors
  
`so that` there is clarity for anyone reading/implementing

**Complexity**: Low 

**Uncertainty**: Low 

---

**Tasks**:
- [ ]  Fix errors in Linking Diagram docs

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass

## **Pull Requests**:
- [ ] https://github.com/mojaloop/pisp-demo-server/pull/19

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
