### ISSUE TITLE
Align AS-IS Bulk Quotes Mojasim tests to Sequence diagrams

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1646]
## **Goal**:
`As an` Ops team member supporting a Switch
`I want to` have a relational reference between the sequence diagrams for the Bulk Quotes API and the TTK test collection
`so that` I could use it for debugging purposes so that I can quickly find the root cause of an issue

**Acceptance Criteria**:
- [ ] Sequence diagrams (and steps) (to be created in #1643) have corresponding TTK tests

**Complexity**: Low 

**Uncertainty**: Low

---
**Tasks**:
- [ ] Covert AS-IS Bulk Quotes MojaSim tests to TTK Collection
   - [ ] POST /bulkQuotes
   - [ ] POST /bulkQuotes (-ve scenarios)
   - [ ] PUT /bulkQuotes/{id}
   - [ ] PUT /bulkQuotes/{id} (-ve scenarios)
   - [ ] PUT /bulkQuotes/{id}/error
   - [ ] PUT /bulkQuotes/{id}/error (-ve scenarios)
   - [ ] GET /bulkQuotes/{id}
   - [ ] GET /bulkQuotes/{id} (-ve scenarios) 
- [ ] Peer review

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] TTK Tests pass

## **Pull Requests**:
- TBD

## **Follow-up**:
- TBD

**Dependencies**:
- #1643

## **Accountability**:
- Owner: TBC
- QA/Review: @amarmodus @elnyry-sam-k
