### ISSUE TITLE
Valid transactionRequests callback in SDK responding with error response

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1647]
**Summary**:
When Valid POST transactionRequests are sent, the callbacks or request are responded with "Unknown URI" with mojasim 

Note: Check PUT and GET callbacks for the same services

**Severity**:
(Medium)

**Priority**:
( Medium)

**Expected Behavior**

**Steps to Reproduce**
  1. 
```
curl --location --request POST 'http://dev1-transaction-requests-service.mojaloop.live/transactionRequests' \
--header 'Accept: application/vnd.interoperability.transactionRequests+json;version=1.0' \
--header 'Content-Type: application/vnd.interoperability.transactionRequests+json;version=1.0' \
--header 'Date: Thu, 27 Aug 2020 00:22:26 GMT' \
--header 'fspiop-source: payeefsp' \
--header 'fspiop-destination: payerfsp' \
--header 'fspiop-http-method: POST' \
--data-raw '{
    "transactionRequestId": "cf10c40e-b018-4a8f-a30e-8b81d4816c57",
    "payee": {
        "partyIdInfo": {
            "partyIdType": "PERSONAL_ID",

            "partyIdentifier": "16135551212",
            "partySubIdOrType": "DRIVING_LICENSE",
            "fspId": "1234"
        },
        "merchantClassificationCode": "4321",
        "name": "Justin Trudeau",
        "personalInfo": {
            "complexName": {
                "firstName": "Justin",
                "middleName": "Pierre",
                "lastName": "Trudeau"
            },
            "dateOfBirth": "1971-12-25"
        }
    },
    "payer": {
        "partyIdType": "PERSONAL_ID",
        "partyIdentifier": "16135551212",
        "partySubIdOrType": "DRIVING_LICENSE",
        "fspId": "1234"
    },
    "amount": {
        "currency": "USD",
        "amount": "123.45"
    },
    "transactionType": {
        "scenario": "DEPOSIT",
        "subScenario": "CUSTOM_SUBSCENARIO",
        "initiator": "PAYEE",
        "initiatorType": "CONSUMER",
        "refundInfo": {
            "originalTransactionId": "cf10c40e-b018-4a8f-a30e-8b81d4816c57",
            "refundReason": "free text indicating reason for the refund"
        },
        "balanceOfPayments": "123"
    },
    "note": "Free-text memo",
    "geoCode": {
        "latitude": "+45.4215",
        "longitude": "+75.6972"
    },
    "authenticationType": "OTP",
     "expiration": "2020-08-27T00:32:26.168Z"
}'
```
  2. callback or request with  "unknown URI" responded

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem: sdk-scheme-adapter / mojaloop-simulator
  - Type of testing:
  - Bug found/raised by:@amarmodus

**Notes**:

- Severity when opened:
- Priority when opened:

**Tasks**:
- [x] Debug the issue
- [x] Implement trasactionRequests endpoint configuration in SDK-Scheme-Adapter
- [x] Test it using tests that already exist in MojaSim collection
   - [x] Verify POST
   - [x] Verify PUT
   - [x] ~~Verify GET~~ (GET is not implemented in the sdk-scheme-adapter)
- [x] Update Helm Chart for SDK-Scheme-Adapter
- [x] Redeploy in Dev environment

**Done**:
- [x] MojaSim tests pass

**Pull Requests**:
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/205
- [x] https://github.com/mojaloop/helm/pull/377
- [ ] https://github.com/mojaloop/postman/pull/174

**Comment by vijayg10** [comment]
Investigated on this for some time and found that the transaction request service endpoint configuration is not implemented in sdk-scheme-adapter.

**Comment by elnyry-sam-k** [comment]
Thanks @amarmodus for confirming
