### ISSUE TITLE
Update Type Definitions in SDK-Standard-Components

### ISSUE THREAD

**Issue by akapur99** [mojaloop/project#1648]
## **Goal**:
Update Type Definitions in `index.t.s` in `sdk-standard-components` according to linking diagrams in https://github.com/mojaloop/pisp/tree/master/docs/linking. 

**Acceptance Criteria**:
- [x] Interfaces/Types match linking diagrams

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] TBD [ @? ]

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [ ] Code Style & Coverage meets standards
## **Pull Requests**:
- [ ] https://github.com/mojaloop/sdk-standard-components/pull/93

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
