### ISSUE TITLE
2.4.70.01 Implement Data Access Layer required for PositionHandler

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#165]
**Goal**:
As a developer
I want to _Implement Data Access Layer required for PositionHandler_
so that FSP positions are calculated/updated and transfers are persisted.

**Tasks**:
- [ ] Create a model object for transferPosition
- [ ] Create a model object for participantLimit
- [ ] Investigate if partyRoleId should be removed from participantLimit role, if so remove it
- [ ] Create a model object for (possibly) partyRole
- [ ] Create a model object for (possibly) role
- [ ] Unit tests for:
  - [ ] transferPosition
  - [ ] participantLimit
  - [ ] partyRole (possibly)
  - [ ] role (possibly)
- [ ] Integration tests for:
  - [ ] transferPosition
  - [ ] participantLimit
  - [ ] partyRole (possibly)
  - [ ] role (possibly)
- [ ] Update ERD for any changes needed

**Acceptance Criteria**:
- [x] Central services to provide the following tables: participant, currency
- [ ] Central services to provide the following tables: transferPosition
- [ ] Central services to provide the following tables: participantLimit, (possibly depending on task-2 point)- partyRole, role 
- [ ] Central services to provide data access objects to position handler.
- [ ] ERD is updated if any changes are made

**Dependencies**:
- [ ] #207

**Accountability**:
- Owner 
- QA/Review

**Comment by elnyry** [comment]
Duplicate, covered in 2.x items in 3.x sprints
