### ISSUE TITLE
Create missing sequence diagrams for Central Ledger Admin API

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1650]
## **Goal**:
`As a` switch operational user 

`I want to` create missing PlantUML sequence diagrams for the Central-Ledger [Admin]
  
`so that` I can understand and test all process flows that occur within the API

**Acceptance Criteria**:
- [ ] Missing sequence diagrams for Central Ledger Admin API are created

**Complexity**: Low -  This is mainly for creating the sequence diagrams only.

**Uncertainty**: Low - There are no uncertainties in this story.

---

**Tasks**:
- [ ] Create missing sequence diagrams:
   - [ ] GET /health
   - [ ] GET /enums
   - [ ] GET /metrics
   - [ ] GET /participants
   - [ ] POST /participants
   - [ ] GET /participants/{name}
   - [ ] PUT /participants/{name}
   - [ ] GET /participants/{name}/endpoints
   - [ ] PUT /participants/{name}/endpoints
   - [ ] GET /participants/{name}/accounts
   - [ ] POST /participants/{name}/accounts
   - [ ] POST /participants/{name}/accounts/{id}
   - [ ] PUT /participants/{name}/accounts/{id}
   - [ ] PUT /participants/{name}/accounts/{id}/transfers/{transferId}
   - [ ] GET /settlementModels
   - [ ] POST /settlementModels
   - [ ] GET /settlementModels/{name}
   - [ ] PUT /settlementModels/{name}
   - [ ] GET /transactions/{id}
- [ ] Peer review

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
