### ISSUE TITLE
Create missing TTK tests for Central Ledger Admin API

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1651]
## **Goal**:
`As a` switch operational user 

`I want to` create missing TTK tests for the Central-Ledger [Admin] based on new sequence diagrams
  
`so that` I can use it to validate new deployments.

**Acceptance Criteria**:
- [ ] TTK tests for all new sequence diagrams for Central Ledger Admin API are created

**Complexity**: Medium

**Uncertainty**: Low 

---

**Tasks**:
- [ ] Create missing tests: 
  **Note**: _Refer to "OSS-API-Tests-old" Postman collection_ for some existing tests.
   - [ ] GET /enums (no assertions)
   - [ ] GET /health (incomplete assertions)
   - [ ] GET /metrics (incomplete assertions)
   - [ ] GET /participants (no assertions)
   - [ ] POST /participants (no assertions)
   - [ ] GET /participants/limits (incomplete assertions)
   - [ ] GET /participants/{name} (incomplete assertions)
   - [ ] PUT /participants/{name}
   - [ ] GET /participants/{name}/endpoints (incomplete assertions)
   - [ ] POST /participants/{name}/endpoints
   - [ ] GET /participants/{name}/limits
   - [ ] PUT /participants/{name}/limits
   - [ ] GET /participants/{name}/positions (incomplete)
   - [ ] GET /participants/{name}/accounts (no assertions)
   - [ ] POST /participants/{name}/accounts 
   - [ ] POST /participants/{name}/initialPositionAndLimits
   - [ ] POST /participants/{name}/accounts/{id}
   - [ ] PUT /participants/{name}/accounts/{id}
   - [ ] PUT /participants/{name}/accounts/{id}/transfers/{id}
   - [ ] GET /settlementModels
   - [ ] POST /settlementModels
   - [ ] GET /settlementModels/{name}
   - [ ] PUT /settlementModels/{name}
   - [ ] GET /transactions/{id}
- [ ] Peer review

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
