### ISSUE TITLE
Implement accented character support in SDK-scheme-adapter

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1653]
## **Goal**:
`As a`  DFSP

`I want to` have accented characters support in SDK scheme adapter
  
`so that` i can test and verify those test cases involving multiple languages and accented characters

**Acceptance Criteria**:
- [x] `When` a request comes in with accented characters (latin) in the First, Middle and Last names, `then` it gets accepted and validated correctly by the SDK-scheme-adapter

**Complexity**: Medium.   Writing happy path is complex

**Uncertainty**: High.   Unsure if REGEX tests with Swagger will succeed

**Not in scope**:  Idiographic (or) Picture characters (e.g. Cyrillic, Devanagri)

Request body with accented character in name
```
{
    "quoteId": "e0bc4218-ae8f-4075-aaeb-6a2b5b57e898",
    "transactionId": "ecb75eed-a9e9-4080-ae16-8e0ec2120dfd",
    "payer": {
        "partyIdInfo": {
            "partyIdType": "MSISDN",
            "partyIdentifier": "918381008987",
            "fspId": "payerfsp"
        },
        "personalInfo": {
            "complexName": {
                "firstName": "Renée",
                "lastName": "Noël"
            },
            "dateOfBirth": "1983-10-25"
        }
    },
    "payee": {
        "partyIdInfo": {
            "partyIdType": "MSISDN",
            "partyIdentifier": "17039811907",
            "fspId": "payeefsp"
        }
    },
    "amountType": "RECEIVE",
    "amount": {
        "amount": "60",
        "currency": "USD"
    },
    "transactionType": {
        "scenario": "TRANSFER",
        "initiator": "PAYER",
        "initiatorType": "CONSUMER"
    },
    "note": "hej"
}

```
Current response for POST /quotes callback
```
{
    "headers": {
        "host": "dev2-sim-payerfsp.mojaloop.live",
        "connection": "close",
        "x-request-id": "6228362f2f62011adcb4cf438b317d2e",
        "x-real-ip": "10.1.2.224",
        "x-forwarded-for": "10.1.2.224",
        "x-forwarded-host": "dev2-sim-payerfsp.mojaloop.live",
        "x-forwarded-port": "80",
        "x-forwarded-proto": "http",
        "x-original-uri": "/sim/payerfsp/inbound/quotes/e0bc4218-ae8f-4075-aaeb-6a2b5b57e898/error",
        "x-scheme": "http",
        "content-length": 110,
        "content-type": "application/vnd.interoperability.quotes+json;version=1.0",
        "date": "Thu, 03 Sep 2020 12:43:22 GMT",
        "fspiop-source": "switch",
        "fspiop-destination": "payerfsp",
        "fspiop-http-method": "PUT",
        "fspiop-uri": "/quotes/e0bc4218-ae8f-4075-aaeb-6a2b5b57e898/error",
        "traceparent": "00-e2382afec549dfedd8a35b07391604e3-80c7cf2ce659f0c4-00",
        "tracestate": "mojaloop=eyJzcGFuSWQiOiI4MGM3Y2YyY2U2NTlmMGM0In0=",
        "fspiop-signature": "{\"signature\":\"YXQ68J1HoAnzTXIxIOBOjVX8ognfLDaTNsr7IqxtByHL9dPj9_XRrYxKb_QhGKtv80wQ4ECiLjmuyRkEMJ62qFOcu3AWGgD3bDiLfwWwNTX1LKL3hPStBhf0KwlbGBq_3Ba5W8FMamu-dtT0-RcgOKz0ZV2IWYkSKKd7rMcHaVIO0doY-fLLVaPt_zXi7N-alqCg0NxDf9GUDGfL0BN8tAXNgBEdt1pJk5AVFwcZcn7XcQp6I4xYyy2Q-MfRPYlTcsMxDj1s4Fwt7kA-NDGu7LFh5kIt8EhRuR0zLuORf5pZ8x8FeWsHM4H4IXyBtdlrw8Ht3xpmQDKVvGnYbdr4JQ\",\"protectedHeader\":\"eyJhbGciOiJSUzI1NiIsIkZTUElPUC1VUkkiOiIvcXVvdGVzL2UwYmM0MjE4LWFlOGYtNDA3NS1hYWViLTZhMmI1YjU3ZTg5OC9lcnJvciIsIkZTUElPUC1IVFRQLU1ldGhvZCI6IlBVVCIsIkZTUElPUC1Tb3VyY2UiOiJzd2l0Y2giLCJGU1BJT1AtRGVzdGluYXRpb24iOiJwYXllcmZzcCIsIkRhdGUiOiJUaHUsIDAzIFNlcCAyMDIwIDEyOjQzOjIyIEdNVCJ9\"}",
        "user-agent": "axios/0.19.2"
    },
    "data": {
        "errorInformation": {
            "errorCode": "1001",
            "errorDescription": "Destination communication error - Network error"
        }
    }
}

```
---

**Tasks**:
- [x] Use REGEX [@oderayi]  
- [x] Test if regular expressions can be used by Swagger Definition [@oderayi] 
   **_Note_**: Unicode-based regex did not work without introducing non-standard JSON-Schema keyword.
 Use of non-standard JSOn-Schema is not acceptable.
- ~If so~ 
   - ~use REGEX ( review how flags get added )~
- [x] If not 
  - ~Investigate Koa Middleware Architecture~
  - [x] ~create middleware for Koa to convert the REGEX with flags to regular JS~.
  - [x] Update existing code to dynamically add non-standard JSON-Schema keywords to the loaded API spec in-memory.
      **_Note_**: New code is packaged into a library and applied to relevant places.
- [x] Update Mojaloop Simulator to accept accent character
     **_Note_**: Mojaloop Simulator does not have validation needs for accented characters at the moment. All names are validated as `string` [@oderayi]
- [x] Fix broken tests [@oderayi] 
- [x] Add new unit tests [@oderayi] 
- [x] End-to-end tests with Postman/TTK
- [ ] Update Helm scripts for deployment of SDK-Scheme-Adapter
- [x] Validate deployment/test

**Done**
- [x] Acceptance Criteria pass
- [x] Unit Tests pass
- [x] E2E Postman/TTK Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/203

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
