### ISSUE TITLE
TTK - Implement add rename delete and duplicate functionality for the files and folders in outbound request page

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1655]
## **Goal**:
`As a` Individual implementor

`I want to` manage test case files via the TTK
  
`so that` I can customize the sequence of tests run in TTK

**Acceptance Criteria**:
- [x] `When` the user clicks on folder management button, `then` they should see the following file operations in the folder management section of the outbound request page. 
  - [x] Create a file ( an empty file should be created )
  - [x] Create a folder
  - [x] Rename file / folder
  - [x] Duplicate a file
  - [x] Duplicate a folder
  - [x] Delete a file / folder with confirmation dialog
  - [x] Move a file / folder to a different sub-folder
- [x] `When` the folders & files have been re-arranged, `then` the tests should execute as per the new sequence including the new files that are created and not including the deleted ones.

**Complexity**: Medium (Number of file operations)

**Uncertainty**: Low

---

**Tasks**:
- [x] Create a context menu
- [x] The following operations should be implemented
  - [x] Create a file
  - [x] Create a folder
  - [x] Rename file / folder
  - [x] Duplicate a file
  - [x] Duplicate a folder
  - [x] Move a file / folder to a different location
  - [x] Delete a file / folder with confirmation dialog

**Note**:  Content is going to changed in memory and in the browser local storage.  It will not be stored in the back-end

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] End to End Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/53
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/98
## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
