### ISSUE TITLE
[sdk-standard-components] Update/Fix Type Definitions

### ISSUE THREAD

**Issue by akapur99** [mojaloop/project#1656]
## **Goal**:
`As a` central library

`I want to` ensure my type definitions are upto date with linking diagrams
  
`so that` code is correct

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Update Type Definitions
- [x] Fix Type Errors

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-standard-components/pull/95

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
