### ISSUE TITLE
Create missing sequence diagrams and tests for Central-Ledger Fulfil API

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#1658]
## **Goal**:
`As a` implementor

`I want to` have all all sequence diagrams and tests for Central-Ledger Fulfil api
  
`so that` i can understand and test all process flows that occur within the API

**Acceptance Criteria**:
- [ ] All sequence diagrams for the Central-Ledger Fulfil API are complete
- [ ] All tests pass on the testing toolkit

**Complexity**: Low > We have the processes working, it would be to just translate them into diagrams

**Uncertainty**: Low > We have the processes working, it would be to just translate them into diagrams

---

**Tasks**:
- [ ] Create sequence diagrams for missing flows
  - [ ] PUT /transfers/{ID}
- [ ] Create testing toolkit test collections
  - [ ] PUT /transfers/{ID}

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Testing Toolkit Tests pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @rmothilal @elnyry-sam-k @amarmodus
