### ISSUE TITLE
Create a TTK setup collection

### ISSUE THREAD

**Issue by ramakrishnan-sankar** [mojaloop/project#1659]
## **Goal**:
`As a` Hub Operator

`I want to` have the setup collection in TTK
  
`so that` I need not to use the postman for setting up the new deployments

**Acceptance Criteria**:
- [x] Following setup collections are available in the samples section of TTK
  - [x] Mojaloop Hub Setup
  - [x] Mojaloop Sims onboarding
- [x] Dev1 & Dev2 environment files are updated to support the new setup collections

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Create the Hub setup collection
- [x] Create the Sims onboarding collection
- [x] Update the Dev1 environment file
- [x] Update the Dev2 environment file
- [x] Release new versions
- [x] Update helm chart

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
Duplicate of #1725
