### ISSUE TITLE
[docs] - Add `PUT /thirdpartyRequests/transaction/{id}` to the sequence diagrams

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1660]
## **Goal**:
`As a` OSS developer

`I want to` update the sequence diagrams to include a `PUT /thirdpartyRequests/transaction/{id}`
  
`so that` I can follow the updated design

**Acceptance Criteria**:
- [ ] updated sequence diagrams as above
- [ ] updated list of endpoints and callbacks (if needed)

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] Update the sequence diagrams to include a `PUT /thirdpartyRequests/transaction/{id}` callback from the DFSP to the PISP before creating quote request
> see https://github.com/mojaloop/pisp/issues/56 for the discussion around this
- [ ] update the [Roles and Endpoints](https://github.com/mojaloop/pisp/blob/master/docs/roles_and_endpoints.md) doc if needed, to include this new endpoint (outbound from DFSP, inbound to PISP)

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Lewis to double check

**Comment by lewisdaly** [comment]
Looks like this was already done.
