### ISSUE TITLE
Implementation Support - Data Protection Impact Assessment (DPIA) : Establish Purpose for Processing PII in a P2P transfer (Same currency)

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1662]
## **Goal**:
`As a` <hub operators>

`I want to` source guidance on how to establish purpose for processing PII one of my processes ( in a single P2P transfer same currency) 
  
`so that` I can able to perform this exercise on my own for the rest of the hub operations processes

**Acceptance Criteria**:

- [ ] Documented purposes for processing PII in a single P2P transfer

**Complexity**: Low

**Uncertainty**:  High

---

**Tasks**:

- [x] Identify PII in a P2P transfer process - @godfreykutumela 
- [x] Design a methodology for tracing the use of PII through the transfer process @godfreykutumela 
- [x] Establish the purpose/s for processing PII in a single end to end transfer @godfreykutumela 
- [ ] Design report template for the findings @godfreykutumela 
- [ ] Document the finding and discuss with the hub operator @godfreykutumela 

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
Below is a summary of the PII datasets , its sources and destinations and as well as the purposes for processing it throughtout in a single P2P transfer same currency:

1. PII dataset 1 : Payee MSISDN - Source is Payer DFSP and destinations are Swich, Pathfinder and Payee DFSP
2. PII dataset 2 : Payer MSISDN - Source is Payer DFSP and destinations are Switch and Payee DSFP
3. PII dataset 3: Payee Name - Source is Payee DFSP and destinations are Switch and Payer DFSP

Mowali compliance team is busy investigating the full implementations of classifying GSMA pathfinder as one of the PII data processing partners or not since they receive PII dataset which they're already have from other sources.

Further detailed from this exercise is available at request from Mowali team.
