### ISSUE TITLE
Implementation Support - Data Protection Impact Assessment (DPIA) : PII Assessment Approach for structured and unstructured data

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1663]
## **Goal**:
`As a` hub operator

`I want to` identity and document the use of PII per process
  
`so that` I can be able to define the scope and set boundaries in our effort to manage PII in line with best practice standards such as GDPR, CCBA, POPIA etc.... 

**Acceptance Criteria**:
- [ ] Document PII data and all processes it touches throughout the its lifespan

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] identify all PII dataset - Unstructured and Structured across the hub environment @godfreykutumela 
- [x] Map all the process which requires the processing of PII @godfreykutumela 
- [ ] Document the findings - PII dataset and business processess that requires it @godfreykutumela 
**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela
