### ISSUE TITLE
Implementation Support - Data Protection Impact Assessment (DPIA) : Establish a PII Access Management Framework

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1664]
## **Goal**:
`As a` hub operator

`I want to` establish methods and techniques for managing and moniroting all access to PII in my hub operations 
  
`so that` I can know at time where my PII data is 

**Acceptance Criteria**:
- [x] PII Access Management Framework

**Complexity**: Low

**Uncertainty**: High

---

**Tasks**:
- [x] Perform a full data flow and analysis with complete trace for both data at rest and data in transit irrespective the form the data is in (Structured and Unstructured) @godfreykutumela 
- [x] Desigm methods for auditing user access to all PII datasets @godfreykutumela 
- [x] Design methods for Identifing third parties with access PII datasets @godfreykutumela 
- [x] Establish a PII access management framework that includes - methods, tools and processes @godfreykutumela 

**Done**
- [x] Acceptance Criteria pass

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
We have provided Mowali with guidance through several workshops on addressing all areas of GDPR DPIA, and much of the reports from the exercise are kept internal and confidential as requested.
