### ISSUE TITLE
Create missing TTK tests for Bulk Quotes API

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1665]
## **Goal**:
`As a` switch operational user 

`I want to` create missing TTK tests for the Bulk Quotes API
  
`so that` I can use it to validate new deployments.

**Acceptance Criteria**:
- [ ] Missing TTK tests for Bulk Quotes API are created

**Complexity**: Medium

**Uncertainty**: Low 

---

**Tasks**:
- [ ] Create missing TTK (MojaSim) tests: 
   - [ ] POST /bulkQuotes
   - [ ] PUT /bulkQuotes/{id}
   - [ ] PUT /bulkQuotes/{id}/error
   - [ ] GET /bulkquotes/{id} (-ve scenarios)
   - [ ] PUT /bulkQuotes/{id} (-ve scenarios)
- [ ] Peer review

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by ramakrishnan-sankar** [comment]
superseeded by #1646
