### ISSUE TITLE
Implementation Support - Data Protection Impact Assessment (DPIA) : Establish a PII Data Protection Framework 

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1666]
## **Goal**:
`As a` hub operator

`I want to` establish a framework for protecting PII datasets across my hub operations
  
`so that` I can set a minimum required protection baseline to ensure that my hub security operations are in line with compliance standards

**Acceptance Criteria**:
- [ ] PII Data Protection Framework

**Complexity**: Medium

**Uncertainty**: High
---

**Tasks**:
- [ ] Review all existing controls framework for PII dataset
- [ ] Identify critical gaps 
- [ ] Open discussion additional recommended control
- [ ] Agree on a new PII Data Protection Framework with a well defined minimum controls baseline 

**Done**
- [ ] Acceptance Criteria pass

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela
