### ISSUE TITLE
[design] - Clarify source and destination headers as well as participantId for the auth service

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1668]
## **Goal**:
`As a` PISP integrator

`I want to` know how to address the auth-service for a given DFSP using the `FSPIOP-Destination` header
  
`so that` I can integrate the PISP features

**Acceptance Criteria**:
- [ ] clarified design decision on how the PISP should address the DFSP's auth service
- [ ] peer approval as required (perhaps DA approval as well...)

**Complexity**: Medium
**Uncertainty**: Medium

---

**Tasks**:
Following up from mojaloop/project#1606, and https://github.com/mojaloop/pisp/issues/52, we need to clarify how:
- [ ] DFSPs register endpoints for the switch to address requests to them and their nominated auth service
- [ ] PISPs and DFSPs will address the auth service _explicitly_ for a given DFSP. One proposal was to register a new participant for each DFSP's auth service, with the id: `auth.<dfspId>`.
 

**Done**
- [ ] Designs are up-to date and approved by the team

## **Pull Requests**:
- [ ] https://github.com/mojaloop/pisp/pull/84

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
