### ISSUE TITLE
[pisp] - end to end transaction with docker-local and thirdparty-scheme-adapter

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1671]
## **Goal**:
`As a` OSS developer

`I want to` demonstrate a live PISP Transfer against a locally running version Mojaloop
  
`so that` we can demonstrate end to end transfers work

**Acceptance Criteria**:
- [x] working end to end transaction initiated from pisp

**Complexity**: Medium - We have the test cases, but the docker-local config can sometimes be fiddly to get right

**Uncertainty**: High - I'm not sure what this involves on the DFSP side

---

Following on from mojaloop/project#1670, we should be able to copy across the tests, but this time target our `docker-local` PISP environment instead of the testing toolkit

**Tasks**:
- [x] update docker-local to use the latest `thirdparty-scheme-adapter` for the PISP and Payer DFSP
~- [ ] implement `signedChallenge` endpoint in TTK~ - this has been superceded by the newer 3p-scheme-adapter designs
~- [ ] For DFSP side, add any configuration, mocking, etc as required~
> DFSP side is already covered by existing `mojaloop-simulator`
~-[x] fix ts typings in sdk-standard-components
~- [x] fix backend-requests in thridparty-scheme-adapter
- [x] fix`/singchallenge` path and make it configurable
- [x] extend ts typings for braking change in sdk-standard-components v12
- [x] adjust thirdparty-scheme-adapter to be compatible with braking change in sdk-standard-components v12
- [x] extend thridparty-scheme-adapter to have sdk-standard-components config for missing endpoints: transactionRequestsEndpoint, thirdpartyRequestsEndpoint, bulkTransfersEndpoint and update docker-compose config files
- [x] copy across tests from mojaloop/project#1670 as needed
- [x] kick the POST /authorization in sdk-scheme-adapter in transferModel after receiving the quote detecting first the presence of PISPModel in Redis for given transactionRequestId - POC - is it simple enough?
- [x] extend mojaloop simulator to have /verify-authorization endpoint
- [x] propose `thirdparty` and `sdk`scheme adapter cooperation run for Payer DFSP
- [x] use thirdparty-scheme-adapter (PISP & DFSP side interfaces when ready)

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-standard-components/pull/110
- [x] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/36/files
- [x] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/37
- [x] https://github.com/mojaloop/pisp/pull/76
- [x] https://github.com/mojaloop/sdk-standard-components/pull/112
- [x] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/40
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/219
- [x] https://github.com/mojaloop/pisp/pull/80/files
- [x] https://github.com/mojaloop/mojaloop-simulator/pull/82
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/220
- [x] https://github.com/mojaloop/pisp/pull/87
## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by eoln** [comment]
https://github.com/mojaloop/pisp/blob/master/test/e2e/PIPSAuthorizations.test.ts
![components_layout.png](https://images.zenhubusercontent.com/5e9efb1f861fca3041741b8a/7cf23045-d54a-43e2-bc24-065f86860396)

**Comment by lewisdaly** [comment]
@eoln I've updated this ticket to reflect some of our changes to the 3p-scheme-adapter. Can you please sanity-check it ahead of our call tonight?

**Comment by elnyry-sam-k** [comment]
Thank you Pawel @eoln !
