### ISSUE TITLE
[pisp] - full thirdparty-dfsp-api swagger doc

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1673]
## **Goal**:
`As a` person presenting to the CCB

`I want to` have a full `thirdparty-dfsp-api` swagger document
  
`so that` I can describe the full thirdparty dfsp specification

**Acceptance Criteria**:
- [x] a full `thirdparty-dfsp-api` swagger document in the `mojaloop/pisp` repo

**Complexity**:  Low - This is just a case of compiling a bunch of api snippets we have elsewhere

**Uncertainty**:  Low - This is just a case of compiling a bunch of api snippets we have elsewhere

---

**Tasks**:
in https://github.com/mojaloop/pisp:
- [x] ensure we have 2 separate swagger template files - one for thirdparty-dfsp, and another for thirdparty-dfsp
- [x] add a `build:openapi:dfsp` step to `package.json`
- [x] add the DFSP -> switch api calls
- [x] add the Switch -> dfsp api calls
- [x] updates to `api-snippets` as required

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date

## **Pull Requests**:
- [x] https://github.com/mojaloop/pisp/pull/63
- [x] https://github.com/mojaloop/pisp/pull/65
- [x] https://github.com/mojaloop/pisp/pull/67
- [x] https://github.com/mojaloop/pisp/pull/70
- [x] https://github.com/mojaloop/pisp/pull/72

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
