### ISSUE TITLE
[thirdparty-api-adapter] - kafka consumer config and mock Fulfil event

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1674]
## **Goal**:
`As a` OSS developer

`I want to` mock out the PISP fulfil event
  
`so that` we can test end to end transfers

**Acceptance Criteria**:
- [x] working kafka consumer config on thirdparty-api-adapter
- [x] some way to pretend that `transferId=123` is actually `transactionId=987`, so that we can configure the mock 

**Complexity**: Medium
**Uncertainty**: High - using kafka in pisp for the first time, typescript/`ambient.d.ts` rabbit holes

---

**Tasks**:
- [x] add kafka consumer config to `thirdparty-api-adapter` to listen for a `Transfer Fulfil Notification` (emitted from the central-ledger)
  - [x] Add typings for `central-services-stream` in `ambient.d.ts` as needed
- [x] simple mock config to 'pretend' this notification is actually a `ThirdpartyTransactionRequest Fulfil` notification (which will be emitted from the central-event-processor
> Incoming event Event will look like: https://github.com/mojaloop/pisp/tree/master/docs/transaction_callback#a4-transfer-fulfil-notification
> And we should have a way to map it to the 'pretend' event, which will look like: https://github.com/mojaloop/pisp/tree/master/docs/transaction_callback#a5-thirdpartytransactionrequest-fulfil
> That way, we can listen for a specific `transferId` in the thirdparty-api-adapter, and easily configure the mock end to end transfers

- [x] simple demo integration test setup with central-ledger and kafka to verify consumer is working as expected

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
~- [ ] https://github.com/mojaloop/thirdparty-api-adapter/pull/21~
- [x] https://github.com/mojaloop/thirdparty-api-adapter/pull/22
- [x] https://github.com/mojaloop/thirdparty-api-adapter/pull/23
- [ ] https://github.com/mojaloop/thirdparty-api-adapter/pull/25/files

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
