### ISSUE TITLE
Validate and Test accent character support in Mojasim environment

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1675]
## **Goal**:
`As a` Implementor 

`I want to` validate the support of accent character in mojasim environment 
  
`so that` mojasim can be used for testing those scenarios and added in Golden path collection

**Acceptance Criteria**:
- [x] `When` a request comes in with accented characters (latin) in the First, Middle and Last names, `then` it gets accepted and validated correctly by the Mojasim Simulator

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Postman tests added in Mojasim collection - test run and passes
- [x] Validate the accent character support in Legacy sim - manual check 

**Done**
- [x] Acceptance Criteria pass

## **Pull Requests**:
- [ ] https://github.com/mojaloop/postman/pull/176

## **Follow-up**:
- N/A

**Dependencies**:
- https://github.com/mojaloop/project/issues/1653

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
![image](https://user-images.githubusercontent.com/10507686/93869389-5dd45f00-fce9-11ea-8045-e8224b83fba4.png)

tested on dev1 after testing with v11.3.0 (temp) release of sdk-scheme-adapter (updated payer and payee fsp simulators)
