### ISSUE TITLE
Cryptographic Processing Module (CPM) - Define supported use cases

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1677]
## **Goal**:
`As a` hub operator

`I want to` know use cases planned for the envisaged CPM 
  
`so that` I can align my migration plans to the CPM accordingly

**Acceptance Criteria**:
- [ ] Defined use cases

**Complexity**: <Medium

**Uncertainty**: <High

---

**Tasks**:
- [x] Identify intial use case to start with
- [x] Document and communicate to the community

**Done**
- [ ] Acceptance Criteria pass
- [ ] 

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
Final list of use cases for review
[Mojaloop Crytographic Processing Module LLD Use Cases.docx](https://github.com/mojaloop/project/files/5174669/Mojaloop.Crytographic.Processing.Module.LLD.Use.Cases.docx)
