### ISSUE TITLE
DevSecOps - Threat Intelligence scans on public repos for Mojaloop code usage

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1678]
## **Goal**:
`As a` OSS developer

`I want to` get a feel of who access and uses code base somewhere else within their internal projects or other open source initiatives 
  
`so that` I can reach and extend our support and also get feedback on issues related to code quality, security and performance.

**Acceptance Criteria**:
- [ ] Report on intel scans across the public code repositories 

**Complexity**: Medium

**Uncertainty**: High

---

**Tasks**:
- [ ] Setup a scanning service with key words related to our code base
- [ ] Monitor alerts and review weekly reports

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
Current tool is giving too many false positives so will close this for now
