### ISSUE TITLE
TTK - Wrapper program for TTK web UI to handle local file operations

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1679]
## **Goal**:
`As a` Individual implementor

`I want to` work on the template files directly from the local machine file system
  
`so that` i can make changes to the test cases and raise PR's easily

**Acceptance Criteria**:
- [x] A wrapper program for the testing toolkit web UI is available to work on the local file system directly instead of importing and exporting the test case files to the web UI

**Complexity**: High (Learn the electronJS API)

**Uncertainty**: High (Don't know the electorJS can support all the features we want to develop and also need to check on the OS platforms it supports)

---

**Tasks**:
- [x] Investigate the use of electron and try to create a sample wrapper around TTK to check it runs on all major OS's
- [x] Make sure all the functions required are available in API regarding file operations and javascript calls and event listeners
- [x] Refactor the existing logic around test case file operations to support electronJS APIs
- [x] Override the file management through electronJS
- [x] Make sure everything is working as expected by saving the folder structure and observing the git changes on the local machine file system

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/72

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
