### ISSUE TITLE
Developer Portal - 1

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#168]
**Goal**:
As SMEs we need to spend about a day per week (or so) on developer portal that can be used for on-boarding (for both commercial & public parties)

**Tasks**:
- [ ] Participate and contribute towards creating/updating a developer portal that can be used for developer on-boarding etc.

**Acceptance Criteria**:
- [ ] Information is contributed towards and creation and updating of a Developer portal (time-boxed)

**Dependencies**:
- [ ] Sprint scheduling and availability, deadlines
- [ ] #177
