### ISSUE TITLE
DevSecOps - Review current Kubernetes audit logging setup and report on findings

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1681]
## **Goal**:
`As a` hub operator

`I want to` check if there are no possible data leakage avenues due to my insecure Kubernetes logging setup and practices
  
`so that` I can find a solution to the problem

**Acceptance Criteria**:
- [ ] Document Kubernetes audit logging standard for Mojaloop
- [ ] Kubernetes audit logging investigation report with findings and key issues

**Complexity**: Low

**Uncertainty**: High

---

**Tasks**:
- [ ] @rasputtintin to define

**Done**
- [ ] Acceptance Criteria pass
-

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela @rasputtintin 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
Deferred to PI 12
