### ISSUE TITLE
DevSecOps - Investigate Kubernetes security improvements (Alignment to security best practice) 

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1682]
## **Goal**:
`As a` Hub operator

`I want to` initiative a process reviewing and improvement the security practices on my kubernetes environment 
  
`so that` I can improve the security posture of my application landscape

**Acceptance Criteria**:
- [ ] kubernetes security standard

**Complexity**: Medium

**Uncertainty**: High

---

**Tasks**:
- [ ] @rasputtintin to define

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela @rasputtintin 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
Deferred to PI 12
