### ISSUE TITLE
Create TTK tests for the Account Lookup Service Admin Sequence Diagrams

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#1683]
## **Goal**:
`As a` implementor

`I want to` have all TTK tests for the Account-lookup-service Admin API
  
`so that` i can understand and test all process flows that occur within the Admin API

**Acceptance Criteria**:
- [x] All tests pass on the testing toolkit

**Complexity**: Low > We have the processes working, it would be to just translate them into diagrams

**Uncertainty**: Low > We have the processes working, it would be to just translate them into diagrams

---

**Tasks**:
- [x] Create Testing toolkit tests for all sequences
  - ~DELETE /endpointcache~ _**Not part of ALS Admin API**_ [@oderayi] 
  - [x] GET /oracles [@oderayi] 
  - [x] POST /oracles [@oderayi] 
  - [x] PUT /oracles/{ID} [@oderayi] 
  - [x] DELETE /oracles/{ID} [@oderayi] 

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Testing Toolkit Tests pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/8

## **Follow-up**:
- N/A

**Dependencies**:
- https://github.com/mojaloop/project/issues/1566

## **Accountability**:
- Owner: TBC
- QA/Review: @rmothilal @elnyry-sam-k @amarmodus
