### ISSUE TITLE
Revive APM on dev1 or dev2 to demonstrate end-to-end traceability

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1684]
## **Goal**:
`As a` Switch

`I want to` setup APM on dev1 or dev2 to demonstrate end-to-end traceability
  
`so that` I can use it to demo trace header functionality to CCB and have these headers included in the ML FSPIOP Spec (as optional)

**Acceptance Criteria**:
- [x] End-to-end traceability of transfers is validated on dev1/dev2 and can be demonstrated (@mdebarros)
- [ ] ~Change request is raised with the ML FSPIOP API CCB~ --> will be demo-ed to the CCB on 27th Oct during the CCB biweekly call and then a change request will be raised.

**Complexity**: Medium > This was working for some time; need to revive the functionality

**Uncertainty**: Low

---

**Tasks**:
- [x] Setup APM on dev1 or dev2
- [x] Validate end-to-end traceability of transfers
- [ ] ~Raise Change request for ML FSPIOP API CCB~

**Done**
- [x] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
