### ISSUE TITLE
Clean setup of local development environment based on existing documentation

### ISSUE THREAD

**Issue by ramakrishnan-sankar** [mojaloop/project#1685]
## **Goal**:
`As a` community member

`I want to` setup a local development environment following the ML documentation
  
`so that` I can test the setup documentation and help improve it

**Acceptance Criteria**:
`Given' Local development environment setup including Mojaloop and TTK

`When` Mojaloop and its components and TTK are run, 

`Then` Golden Path tests pass

**Complexity**: <Medium> > A number of moving parts

**Uncertainty**: <Medium> > Current documentation assumes a certain familiarity with tech setup.

---

**References**:   

**Local Deployment**
[Deployment Handbook](https://docs.mojaloop.io/documentation/deployment-guide/)

[Onboarding](https://github.com/mojaloop/central-ledger/blob/master/Onboarding.md) 

**Run component Locally**
To run the code locally, refer to the readme of each component Example: [central ledger](https://github.com/mojaloop/central-ledger#running-locally) 

**Tasks**:
- [ ] Install
  - [ ] IDE
    - [x] [VS Code](https://code.visualstudio.com/)
  - [x] IDE Extensions
    - [x] ESLint
    - [x] StandardJs
    - [x] Bracket Pair Colourizer 2
    - [x] Code Runner
    - [x] Docker
    - [x] DotENV
    - [x] GitLens
    - [x] Prettify JSON
    - [x] Visual Studio IntelliCode
   
  - [ ] iTerm
  - [ ] GitHub Desktop
  - [ ] [Homebrew](https://brew.sh/) 

  - [ ] Language Runtime
    - [ ] Typescript
    - [x] [Node ( 12.18.3 )](https://nodejs.org/en/)
    - [x] [NPM (npm install npm@latest -g)](https://www.npmjs.com/get-npm)

  - [ ] Testing Tools
    - [ ] Postman for Chrome (deprecated)
    - [ ] Postman for Mac

  - [ ] Runtime
    - [x] Docker Desktop
    - [ ] Kubernetes
      - [ ] kubernetes-cli ( brew install kubernetes-cli )

- [ ] VPN
- [ ] Run tests against Dev Environment ( Dev 2 )
- [ ] Run tests in local env.

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
