### ISSUE TITLE
PI-11 Mid-PI Review prep - ML OSS core

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1686]
## **Goal**:
`As a` Community member

`I want to` understand the features implemented, enhancements made to the Mojaloop OSS core in PI-11 Sprints 11.1, 11.2, 11.3
   
`so that` I can stay updated the features, releases and adopt them accordingly.

**Acceptance Criteria**:
- [ ] Mid PI Review Demo Videos and presentation successfully prepared

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] Story Board 
- [ ] Slide Prep
- [ ] Demo Video Prep
- [ ] Live Demo Prep

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
