### ISSUE TITLE
TTK - Make Cached Requests & Callbacks accessible from the inbound/outbound scripts

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1687]
## **Goal**:
`As a` individual implementer

`I want to` have the capability to access the cached requests and callbacks from the inbound and outbound scripts
  
`so that` I can make assertions on the cached inbound requests or callbacks

**Acceptance Criteria**:
**Scenario**: Test the p2p use case

`When` we test p2p with both payer and payee are configured to TTK

`Then`
- [x] The inbound requests and generated callbacks are being cached in object store
- [x] The cached data is accessible from the ~~inbound and~~ outbound scripts

**Complexity**: Medium.  We need to access object store from the scripts based on the ids of the requests.

**Uncertainty**: Medium.    May have to refactor the storing mechanism 

---

**Tasks**:
- [x] Make sure inbound requests and generated callbacks are being cached in object store
- ~~Make them accessible from scripts in rules editor~~ (To avoid performance impact on inbound requests, not passing the history to scripts in rules. If we find any usecase for that, we can enable that anytime)
- [x] May have to refactor the storing mechanism 
- [x] Make them accessible from the pre-request and post-request scripts in outbound request page

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/101

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
