### ISSUE TITLE
[pisp-demo-server] Specialized Error Classes

### ISSUE THREAD

**Issue by akapur99** [mojaloop/project#1688]
## **Goal**:
`As a` server

`I want to` have specialized error classes
  
`so that` when I throw exceptions they are informative and easy to understand

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/pisp-demo-server/pull/27
