### ISSUE TITLE
[pisp-demo-server] Firebase Unit Tests

### ISSUE THREAD

**Issue by akapur99** [mojaloop/project#1689]
## **Goal**:
`As a` PISP Server

`I want to` write unit tests for firebase methods (mocked)
  
`so that` I can ensure current and future firebase methods work correctly 

**Complexity**: Low 
**Uncertainty**: Low

---

**Tasks**:
- [ ] Add Necessary Mocks
- [ ] Write unit tests for firebase methods

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
My $0.02 - we should start with solid unit tests on the business domain, and not go into all of the fuss of trying to find the right libraries to do the right things for us, that may not even end up testing 100% of what we want. 

For testing our model serialization and deserialization, firebase triggers etc. we can then look at proper integration tests with a locally running firebase emulator or something.

**Comment by akapur99** [comment]
I think you're absolutely right - spent a bunch of time yesterday and today exploring third party mocking libraries + firebase emulator/test solutions and they add unnecessary complexity or added refactoring. Had a discussion with @eoln  about this earlier today, and we decided to stick to a barebones jest mocking and just slightly expanding the mocking we already have in place thanks to steven. As you mentioned our focus for unit testing is just to make sure that that we're calling the correct firebase methods with the right parameters, the actual test of functionality should be done through integration testing.

**Comment by eoln** [comment]
@lewisdaly we have had a chat with @akapur99 today. I suggested it's not worth to use this simulator because we will have to implement integration tests later so it will be double work. Also using ts-mock-firebase module isn't the option because we both can't install it properly and this project looks parked because of lack of resources. With @akapur99 we agreed that the best option is to extend a little existing mocking https://github.com/mojaloop/pisp-demo-server/blob/master/src/lib/firebase/__mocks__/index.ts and identify patterns, implement one test for each of them, grab experience, make a retro and then discuss together where to go next.

**Comment by lewisdaly** [comment]
Cool. Thanks for the updates.

**Comment by akapur99** [comment]
Currently attempting this via https://github.com/dmurvihill/firebase-mock
Local in-memory firebase unit testin

**Comment by akapur99** [comment]
Moving to doing 'bare-minimum' testing using basic jest mocking 
Created an issue for better unit tests in the repo 
https://github.com/mojaloop/pisp-demo-server/issues/35

**Comment by lewisdaly** [comment]
@kkzeng please close after confirming that it's only the repository level code left.
