### ISSUE TITLE
CPM - Investigate design options and trust models for introducing CPM in the current P2P flow 

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1693]
## **Goal**:
`As a` hub operator 

`I want to` know how the envisaged CPM will be introduced in my current p2p flow
  
`so that` I can plan appropriterly for this change

**Acceptance Criteria**:
- [ ] Architectural alignment

**Complexity**: High

**Uncertainty**: Medium
---

**Tasks**:
- [ ] TBD @godfreykutumela 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
Deferred to PI 12
