### ISSUE TITLE
Regular Security Patches + Updates - August

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1695]
## **Goal**:
As an `OSS Developer` I want to `address github and npm security updates` so `Mojaloop stays secure, and developers can put their trust in a well managed codebase`.

This is a reoccurring ticket, to track regular manual security updates

**Tasks**:
- Reviewed alerts on github and dismissed the invalid or already fixed issues
- Reviewed and merged automatic PRs from dependabot

**Acceptance Criteria**:
- [x] Github Security Alerts Addressed
- [x] PRs opened and merged with security patches
- [x] `npm audit` resolved/ignored where applicable

## **Pull Requests**:
- [x] https://github.com/mojaloop/email-notifier/pull/167
- [x] https://github.com/mojaloop/central-services-auth/pull/124
- [x] https://github.com/mojaloop/event-sidecar/pull
- [x] https://github.com/mojaloop/central-event-processor/pull/211

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
Thanks @lewisdaly
