### ISSUE TITLE
[pisp-demo-server] Deciding + Implementing Ambient Declarations

### ISSUE THREAD

**Issue by akapur99** [mojaloop/project#1696]
## **Goal**:
`As a` PISP Server
`I want to` set up my ambient declaration file with the typings to allow access to my custom mojaloopClient library through ServerApplicationState

`so that` I can use my client library

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Medium - Lot of ways to approach this + random errors seem to pop up

**Uncertainty**: Medium 

---

**Tasks**:
- [ ] Change/Update the `ambient.d.ts` file 
- [ ] Refactor all files as needed
- [ ] Refactor all unit tests as needed

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] https://github.com/mojaloop/pisp-demo-server/pull/30

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
