### ISSUE TITLE
Implementation Support - Data Protection Impact Assessment : Establish purpose for processing in a P2P transfer with forex 

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1697]
## **Goal**:
`As a` <hub operators>

`I want to` source guidance on how to establish purpose for processing PII one of my processes ( in a single P2P transfer with forex) 
  
`so that` I can able to perform this exercise on my own for the rest of the hub operations processes

**Acceptance Criteria**:

- [x] Documented purposes for processing PII in a single P2P transfer

**Complexity**: Low

**Uncertainty**:  High

---

**Tasks**:

- [x] Identify PII in a P2P transfer process with forex - @godfreykutumela 
- [x] Design a methodology for tracing the use of PII through the transfer process @godfreykutumela 
- [x] Establish the purpose/s for processing PII in a single end to end transfer @godfreykutumela 
- [x] Design report template for the findings @godfreykutumela 
- [x] Document the finding and discuss with the hub operator @godfreykutumela 

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
This has been completed the report of this exercise is confidential to Mowali but available on request from Mowali directly.
