### ISSUE TITLE
Refactor the database for Error Codes

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#17]
**Goal**:
As a Scheme
I want to Refactor the Database to support for Error codes and Descriptions
so that custom errors can be supported (supported by the FSPIOP API as well) and defined / configured by business.

**Tasks**:
- [ ] Move error codes to database
- [ ] Automated testing

**Acceptance Criteria**:
- [ ] A Document with a normalized design / structure for ErrorCodes and related tables is produced
- [ ] The current implementation is refactored to cater for the normalized ErrorCodes in DB
- [ ] Unit tests are refactored
- [ ] Integration tests are refactored

**Dependencies**:
- [ ] Please refer to the existing mojaloop documentation - API Definition v1.0
