### ISSUE TITLE
2.4.80.01 NTPD Daemons

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#170]
**Goal**:
As a developer
I want to write NTPD Daemons
for time syncing

**Tasks**:
- [x] Run a docker container with appropriate permissions locally, install NTP
- [x] Write Helm script for NTPD Daemons (for time sync-ing)

**Acceptance Criteria**:
- [ ] System times of containers can be synced by NTPD Daemons

**Dependencies**:
- None currently

**Accountability**:
- Owner 
- QA/Review

**Comment by fbotha-stratuscloud** [comment]
Testing fbotha/ntpd

docker run --cap-add SYS_TIME --restart=always -d fbotha/ntpd -t ntpd

**Comment by fbotha-stratuscloud** [comment]
Published to mojaloop/ntpd:0.1 & mojaloop/ntpd:latest

docker run --cap-add SYS_TIME --restart=always -d mojaloop/ntpd

**Comment by fbotha-stratuscloud** [comment]
Initial Commit of ntpd Helm Chart - Awaiting Review

https://github.com/mojaloop/helm/tree/feature/%23170NTPDaemons

**Comment by fbotha-stratuscloud** [comment]
This has been merged into the develop branch of mojaloop/helm
