### ISSUE TITLE
[pisp-demo-server] Refactor firestore.ts file to use optional chaining and write tests for firestore.ts

### ISSUE THREAD

**Issue by akapur99** [mojaloop/project#1701]
## **Goal**:
`As a` PISP server
`I want to` test my firestore handler file and use optional changing
  
`so that` code is clear and I know it's working properly

https://github.com/mojaloop/pisp-demo-server/issues/31

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Low
**Uncertainty**: Low
---

**Tasks**:
- [ ] Write tests for firestore.ts
- [ ] Refactor to use optional chaining

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
