### ISSUE TITLE
[pisp-demo-server] BDD Testing

### ISSUE THREAD

**Issue by akapur99** [mojaloop/project#1702]
## **Goal**:
`As a` PISP Server

`I want to` to have full coverage for BDD tests
  
`so that` I know everything is working correctly

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Medium
**Uncertainty**: Low
---

**Tasks**:
- [ ] BDD Tests for entire repo

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
