### ISSUE TITLE
Write out documentation for Flutter FIDO client plugin

### ISSUE THREAD

**Issue by kkzeng** [mojaloop/project#1704]
**Goal**
As a developer, I want to be able to quickly setup the plugin and use it. I want to understand how to configure it.

**Tasks**

- [ ] Write a quick start guide
- [ ] Write out server-side recommendations
- [ ] Write detailed guide for configuration params
