### ISSUE TITLE
[thirdparty-scheme-adapter] - Migrate `POST /thirdpartyRequests/transactions` from sdk-scheme-adapter to thirdparty-scheme-adapter

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1705]
## **Goal**:
`As a` oss developer

`I want to` Migrate `POST /thirdpartyRequests/transactions` from sdk-scheme-adapter to thirdparty-scheme-adapter
  
`so that` PISPs can trigger a thirdparty transaction

**Acceptance Criteria**:
- [x] migrated code and tests

**Complexity**: Medium - state machine conversion is not a 1-1 conversion, also a need to set up a listener on redis

**Uncertainty**: Low

---

Design: https://github.com/mojaloop/pisp/blob/master/docs/thirdparty_scheme_adapter_models.md#outboundthirdpartytransactionmodel
Example Code: 

**Tasks**:
- [x] migrate code from sdk-scheme-adapter
- [x] JS -> TS 
- [x] migrate unit tests

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/38

## **Follow-up**:
- [x] refine model definitions (TODO: @lewisdaly make tickets for these!)
- [x] create ticket to handle inbound `POST /authorizations`

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by eoln** [comment]
example how to setup redis listener: 
https://github.com/mojaloop/thirdparty-scheme-adapter/blob/master/src/models/outbound/authorizations.model.ts

**Comment by sridharvoruganti** [comment]
POST /thirdpartyRequests/transactions changes covered as part of 1711 PR
