### ISSUE TITLE
auth-service: Remove 'ignore-istanbul' from handlers

### ISSUE THREAD

**Issue by kkzeng** [mojaloop/project#1706]
**Acceptance Criteria**:
- [ ] Remove ignore-instanbul so coverage is checked for handlers
- [ ] Fix any potential coverage issues

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
