### ISSUE TITLE
ACCEPT header returned in the PUT from switch for the timeout scenario 

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#1710]
**Summary**:
As per the API spec document, there should not be a ACCEPT header in the PUT callbacks. But when we test the timeout scenario where the switch sends the error msg to payerfsp, we found ACCEPT header is being sent to payerfsp in the callback.

**Severity**:
High

**Priority**:
Critical

**Expected Behavior**
1. The PUT callback from switch in the timeout scenario should not contain ACCEPT header

**Steps to Reproduce**
  Send POST /quotes request from happy path

Send POST /transfers request from happy path by modifying the transferExpiration from the pre-request script. Change that to 1.2 sec instead of 60 sec like below.
pm.environment.set("transferExpiration",new Date(new Date().getTime() + 1200))

Check the logs at payerfsp, payeefsp

Response:
{
"headers": {
"host": "dev1-sim-payerfsp.mojaloop.live",
"connection": "close",
"x-request-id": "a96198f184a6bebc442796f1c7b94afa",
"x-real-ip": "10.1.2.224",
"x-forwarded-for": "10.1.2.224",
"x-forwarded-host": "dev1-sim-payerfsp.mojaloop.live",
"x-forwarded-port": "80",
"x-forwarded-proto": "http",
"x-original-uri": "/sim/payerfsp/inbound/transfers/4f1c5723-c62b-4204-b4b4-93fc06916af7/error",
"x-scheme": "http",
"content-length": 84,
"content-type": "application/vnd.interoperability.transfers+json;version=1.0",
**"accept": "application/vnd.interoperability.transfers+json;version=1.0",**
"fspiop-destination": "payerfsp",
"date": "Tue, 15 Sep 2020 18:08:30 GMT",
"fspiop-source": "switch",
"fspiop-http-method": "PUT",
"fspiop-uri": "/transfers/4f1c5723-c62b-4204-b4b4-93fc06916af7/error",
"fspiop-signature": "{"signature":"LO4WH3XpelRSM5uE18PLW8tqMDKbzv4WqznTWsxNfMdmmDjWwhPGVdoLuvrhXBA1z34LK3b3N2McOm9tAUL9wFz-Y3qHOo1dBztFqJDqqc1wRAoJ-FQOHiQu2HiUeBEaH3i9tEZWANf_UUJl9PRM-8LU8sH6qjW5nbxEaXwGLsa_-AwNr0KO_OEQRkqyRhFAK1wCmlBST3f_0bey6JOAV1XE9vdI1Ej4NvZ8vfhMGxN4SJhGp-UB3MK7IuK90zXJcZPeHME2OUcle-wr2adcnGxX_1yVz1IneE_ltitcIGAnS648kIB9DTV_AqRBqqx-b_CEFh0VIZwSAapVOuVddA","protectedHeader":"eyJhbGciOiJSUzI1NiIsIkZTUElPUC1VUkkiOiIvdHJhbnNmZXJzLzRmMWM1NzIzLWM2MmItNDIwNC1iNGI0LTkzZmMwNjkxNmFmNy9lcnJvciIsIkZTUElPUC1IVFRQLU1ldGhvZCI6IlBVVCJ9"}",
"traceparent": "00-de64620a0f4d8bd80ed262e2b78d739a-1db745b8b7007ca0-00",
"tracestate": "mojaloop=eyJzcGFuSWQiOiIxZGI3NDViOGI3MDA3Y2EwIn0=",
"user-agent": "axios/0.19.2"
},
"data": {
"errorInformation": {
"errorCode": "3300",
"errorDescription": "Generic expired error"
}
}
}
**Screenshot:**

![image (2)](https://user-images.githubusercontent.com/38143240/93476239-90382380-f8c7-11ea-84da-949ca35bf8eb.png)

**Specifications**
  - Component (if known): ml-api-adapter, CL
  - Version: ml-api-adapter - 11.0.3, CL :10.6.1
  - Platform: Mac
  - Subsystem: Mojaloop
  - Type of testing: Functional
  - Bug found/raised by: Sri & Egor

**Notes**:

- Severity when opened:
- Priority when opened:

**Tasks**:
- [x] Remove accept header on the PUT call back for time out scenario
- [x] Unit Test
- [x] Update Mojasim collection, as needed. (potentially just add an assertion)
- [x] Regression test using Mojasim Postman collection

**Pull Requests**
- [x] https://github.com/mojaloop/central-services-shared/pull/257
- [x] https://github.com/mojaloop/central-ledger/pull/787
- [x] https://github.com/mojaloop/helm/pull/385
- [x] https://github.com/mojaloop/postman/pull/182

**Comment by amarmodus** [comment]
```
{
   "headers":{
      "host":"dev1-sim-payerfsp.mojaloop.live",
      "connection":"close",
      "x-request-id":"cd9602d40606648ede85e2183a050785",
      "x-real-ip":"10.1.2.224",
      "x-forwarded-for":"10.1.2.224",
      "x-forwarded-host":"dev1-sim-payerfsp.mojaloop.live",
      "x-forwarded-port":"80",
      "x-forwarded-proto":"http",
      "x-original-uri":"/sim/payerfsp/inbound/transfers/861e272a-4f81-4979-b03e-eae378cc83d2/error",
      "x-scheme":"http",
      "content-length":84,
      "content-type":"application/vnd.interoperability.transfers+json;version=1.0",
      "accept":"application/vnd.interoperability.transfers+json;version=1.0",
      "date":"Mon, 21 Sep 2020 21:35:15 GMT",
      "fspiop-http-method":"PUT",
      "fspiop-uri":"/transfers/861e272a-4f81-4979-b03e-eae378cc83d2/error",
      "fspiop-source":"switch",
      "fspiop-destination":"payerfsp",
      "fspiop-signature":"{\"signature\":\"kldWLw8cI7G9WVUOqUbAp9WgwZsnL1l2Vw6De9YyPmFD7oNQq-Gy7qOsFQLogONzU-KFBRC_2pWV-ktNpUswwPYhX0x9ObKL3YFKqwEKifMa3oefm3267AeMREFtXMNidsdyzrArz6hyY9xmUqT3hghEbUCKe5smSjl9gXxpWkpuXJXuJT35MXUFVFdKOKZzlzFwS0kvSbhxA2MsHRvx6WhbZUCKmK9bXtamdv0dNt_tJIL1eNdZZU69sIDy35RCngAchQfme31fR60hQQroev3b5RznAqe-o6C_KKXZdxM1HdstHyBljl6O3iuteJFESB4HCoAOjfWw0Zkq10MB8w\",\"protectedHeader\":\"eyJhbGciOiJSUzI1NiIsIkZTUElPUC1VUkkiOiIvdHJhbnNmZXJzLzg2MWUyNzJhLTRmODEtNDk3OS1iMDNlLWVhZTM3OGNjODNkMi9lcnJvciIsIkZTUElPUC1IVFRQLU1ldGhvZCI6IlBVVCIsIkZTUElPUC1Tb3VyY2UiOiJzd2l0Y2giLCJGU1BJT1AtRGVzdGluYXRpb24iOiJwYXllcmZzcCJ9\"}",
      "traceparent":"00-b7ad9dd13efbc1437ecd7916e4d505d1-6802f586a57929c6-00",
      "tracestate":"mojaloop=eyJzcGFuSWQiOiI2ODAyZjU4NmE1NzkyOWM2In0=",
      "user-agent":"axios/0.20.0"
   },
   "data":{
      "errorInformation":{
         "errorCode":"3300",
         "errorDescription":"Generic expired error"
      }
   }
}
```
