### ISSUE TITLE
[thirdparty-scheme-adapter] - set up PISP-side state machine 

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1711]
## **Goal**:
As a PISP
I want to be able to talk to the scheme adapter in a series of synchonous calls
so that I can easily integrate with mojaloop's 3p apis

**Tasks**:
- [x] TS typings for getParties in sdk-standard-components
- [x] setup of PISPTransactionRequestModel:
- [x] placeholder functions for state transitions
- [x] workflow `run` function
- [x] Inbound PUT /authorization should publish to two channels:  authorization-test & transaction-request-flow
- [x] Inbound POST /authorization handler works in two modes PISPTransactionModel/AuthorizationModel
- [x] PISPTransactionRequestModel unit tests:
- [x] outbound API definition & handlers & unit tests
  - [x]  `/thirdpartyTransaction/partyLookup`
  - [x]  `/thirdpartyTransaction/{ID}/initiate`
  - [x]  `/thirdpartyTransaction/{ID}/approve`
  - [x]   outbound handler unit tests
- [x] inbound API definition & handlers & unit tests
  - [x]  `/parties/{Type}/{ID}`
  - [x]  `/parties/{Type}/{ID}/error`
  - [x]  `/parties/{Type}/{ID}/{SubId}`
  - [x]  `/parties/{Type}/{ID}/{SubId}/error`
  - [x]   PATCH `/thirdpartyRequests/transactions/{ID}`
  - [x]  `/thirdpartyRequests/transactions/{ID}/error`
  - [x]   inbound handler unit tests
- [x] docker-compose with TTL setup
- [x] integration test of transaction phases
- [x] extend all PISPTransaction flow related handlers by adding proper guards to protect the flow and order of execution

**Acceptance Criteria**:
- [x] tasks completed
- [x] unit tests passed

**Complexity**: Medium
**Uncertainty**: Medium

---

**Done**
- [ ] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-standard-components/pull/107
- [x] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/38

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

## **transaction flow diagram**:
![PISP Transaction.png](https://images.zenhubusercontent.com/5cd963af3613073e20e46e60/8d66891c-b033-4e31-b009-701dfecf430c)
