### ISSUE TITLE
Add Test scenarios for various requests ( e.g. Quotes, Transfers) to support v1.1. ( Validate #1615 )

### ISSUE THREAD

**Issue by ramakrishnan-sankar** [mojaloop/project#1717]
## **Goal**:
`As a` Implementor 

`I want to` add test scenarios and validate the support of v1.1 accept and content header in OSS environment
  
`so that` it can be used for testing as part of regression

**Acceptance Criteria**:
- [ ] `When` a v1.0 or v1.1 content header and accept header is sent as pass through request, `then` switch should revert with v1.0 or v1.1 respectively

- [ ] `When` a v1.1 or v1.0 content header and accept header is raised by switch,  `then` it should send only v1.1 header

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Investigate approach to Parametrization for API version in the test collection.
- [x] Discuss & Agree on Parametrization approach 
[ Note: The agreed approach is to use a Global Version Variable in the postman Environment file and use it for all the services.  Not service specific version to be implemented in this story.  This may be a future story]
- [ ] Update Postman tests ( +ve and -ve ) added in Mojasim collection to use the parametrized API version variable 
    - [ ] Test Scenarios for Quotes
    - [ ] Test Scenarios for Transfers
    - [ ] Test Scenarios for Pass through mode
    - [ ] Test Scenarios for When a request originates from Switch
- [ ] Run test collection and validate it passes

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/postman/pull/183

## **Follow-up**:
- N/A

**Dependencies**:

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by ramakrishnan-sankar** [comment]
Dev 1 deployment with #1676 service updates are causing failures. Team investigating

**Comment by amarmodus** [comment]
<img width="1497" alt="Screenshot 2020-09-25 at 15 17 26" src="https://user-images.githubusercontent.com/53434415/94280173-02061200-ff45-11ea-80c2-9b60a8169bf6.png">

current failures in dev 1 - analysis on progress

**Comment by amarmodus** [comment]
Current Failures after parameterization & removal of redundant GP collection

<img width="1324" alt="Screenshot 2020-09-28 at 21 52 36" src="https://user-images.githubusercontent.com/53434415/94547192-dafe5780-0246-11eb-9a36-edefd8941177.png">

**Comment by amarmodus** [comment]
<img width="1281" alt="Screenshot 2020-10-01 at 23 12 10" src="https://user-images.githubusercontent.com/53434415/94906482-746f7880-0496-11eb-8894-040109533481.png">

**Comment by elnyry-sam-k** [comment]
This can now be closed.. postman tests were recently updated to deal with this and there's a separate issue for TTK
