### ISSUE TITLE
Create missing TTK tests for Quoting Service sequence diagrams

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1718]
## **Goal**:
`As a` switch operational user 

`I want to` create missing TTK tests for the Quoting Service for new sequence diagrams
  
`so that` I can use it to validate new deployments.

**Acceptance Criteria**:
- [ ] TTK tests for all new sequence diagrams for Quoting Service are created

**Complexity**: Medium

**Uncertainty**: Low 

---

**Tasks**:
- [ ] Create TTK tests for the following sequence diagrams: 
   - [ ] https://docs.mojaloop.io/documentation/mojaloop-technical-overview/quoting-service/qs-get-quotes.html [@oderayi] 
   - [ ] https://docs.mojaloop.io/documentation/mojaloop-technical-overview/quoting-service/qs-post-quotes.html [@oderayi] 
- [ ] Peer review

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
