### ISSUE TITLE
[pisp] - Initial Helm lab environment

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1719]
## **Goal**:
As a OSS dev
I want a PISP lab environment hosted on our kubernetes cluster
so that I can demonstrate a live PISP demo

**Acceptance Criteria**:
- [ ] deployed PISP lab environment
- [ ] nice docs that are easy to follow

**Complexity**: Medium - we have pretty good examples in docker-local
**Uncertainty**: Medium

---

**Tasks**:
- [x] convert the docker-local `docker-compose.yml` file to a helm chart that can easily be installed on our kubernetes cluster. The helm config should live in the pisp repo, under a `./docker-live` directory.
- [x] Instructions and scripts (if needed) for installing and running the helm charts in a `README.md`
- [ ] DNS entry pointing to lab environment
- [ ] diagram describing the environment
- [ ] list of endpoints for all services
- [ ] Live deployment on `dev1` cluster

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/pisp/pull/73
- [x] https://github.com/mojaloop/pisp/pull/77
- [x] https://github.com/mojaloop/pisp/pull/81
- [ ] https://github.com/mojaloop/pisp/pull/82

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
