### ISSUE TITLE
[pisp-demo-server] Firebase Emulation and Tests

### ISSUE THREAD

**Issue by akapur99** [mojaloop/project#1723]
## **Goal**:
`As a` Server using Firebase

`I want to` add firebase emulator to the project and use it to write tests
  
`so that` I can ensure current and future firebase methods work correctly 

**Complexity**: Medium - No experience with firebase emulation

**Uncertainty**: Low

---

**Tasks**:
- [ ] Add Firebase Emulators
- [ ] Write tests for firebase methods

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Out of scope for now.
