### ISSUE TITLE
Moja Setup and Onboarding collections to  TTK

### ISSUE THREAD

**Issue by ramakrishnan-sankar** [mojaloop/project#1725]
## **Goal**:
`As a` Scheme

`I want to` have the setup and onboarding collections in TTK
  
`so that` I can run those collections on a fresh deployment of mojaloop cluster

**Acceptance Criteria**:
- [x] Moja Setup collection in provisioning examples folder of the TTK passes
- [x] Moja Onboarding collection in provisioning examples folder of the TTK passes
- [x] After running these setup and onboarding collections, the GP postman collection should be succeeded.

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Convert the Moja Setup collection to TTK format
- [x] Convert the Moja Onboarding collection to TTK format
- [x] Moja Setup collection is available in provisioning examples folder of the TTK
- [x] Moja Onboarding collection is available in provisioning examples of the TTK
- [x] add ALS Admin api definition to ttk
- [x] Test the new collections by redeploying a mojaloop cluster without using postman for setup and onboarding
- [x] resolve https://github.com/mojaloop/ml-testing-toolkit/issues/104
- [x] update deploy config
- [x] Test the postman GP collection after running these TTK collections. Everything should pass.

**Done**:
- [x] Acceptance Criteria pass
- [x] TTK Tests pass
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/103
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/6
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/7
- [x] https://github.com/mojaloop/deploy-config/pull/30
- [x] https://github.com/mojaloop/deploy-config/pull/31
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/9
## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @georgi-logodazhki 
- QA/Review: @vijayg10 @elnyry-sam-k

**Comment by elnyry-sam-k** [comment]
Thanks for taking this up @georgi-logodazhki

**Comment by vijayg10** [comment]
@georgi-logodazhki Please check the callback endpoints are wrong. And also I added a new acceptance criteria, please check.
