### ISSUE TITLE
[thirdparty-scheme-adapter] - Update DFSP-side PISP transaction Design

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1728]
## **Goal**:
`As a` DFSP

`I want to` have an updated design for the thirdparty-scheme-adapter
  
`so that` I can integrate the PISP functionality 

**Acceptance Criteria**:
- [ ] implementation stories written
- [ ] sequence diagram containing API calls

**Complexity**: Medium
**Uncertainty**: Low

---

**Tasks**:
- [ ] Define the outbound API for the DFSP-side of the PISP transaction - as a sequence diagram
> Note: use the [pisp-side](https://github.com/mojaloop/thirdparty-scheme-adapter/blob/master/out/docs/sequence/PISPTransactionApi/PISP%20Transaction.png) as a reference
> note: let's use different resource names so we don't get confused between the thirdparty-api and the scheme-adapter's Outbound API
- [ ] sequence diagram with list of states
- [ ] create implementation tickets

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@eoln I think we can park this one for now if we're happy with the current end to end test strategy

**Comment by lewisdaly** [comment]
Covered elsewhere by @eoln
