### ISSUE TITLE
Design & Create Deposit API

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#173]
**Goal**:
Design & Create Deposit API

**Tasks**:
- [ ] Design Deposit API
- [ ] Create Deposit API

**Acceptance Criteria**:
- [ ] Deposit API is available for use

**Dependencies**:
- None currently
