### ISSUE TITLE
TTK CLI - Refactor the input file functionality to work with new complex folder structure

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1730]
## **Goal**:
`As an` individual implementer

`I want to` use the TTK CLI tool to execute a set of testcase templates from a folder
  
`so that` I can use the TTK CLI for automation

**Acceptance Criteria**:
`When`
  - [x] A folder is provided as input for the TTK CLI with the following constraints
    - [x] With ordering through master.json file in each folder
    - [x] File references through master.json
    - [x] Subfolders

`Then`
  - [x] The TTK CLI should form a consolidated template and execute the tests in the given order

**Complexity**: Medium (Need to look after multiple aspects like ordering, file references, sub folders...etc)

**Uncertainty**: Low

---

**Tasks**:
- [x] Refer the new folder structure parsing logic in the WebUI
- [x] Create a common shared library for the parsing functions and access this lib from UI and backend
- [x] Refactor the TTK CLI to read from the new folder structure
- [x] Refactor the TTK UI using the new shared library
- [x]  Include the collection name and environment name in test report and notification
- [x] Test the modified CLI tool using helm chart

**Done**
- [x] Acceptance Criteria pass
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/105
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/55
- [x] https://github.com/mojaloop/ml-testing-toolkit-shared-lib/releases/tag/v11.0.0
- [x] https://github.com/mojaloop/helm/pull/386

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
