### ISSUE TITLE
TTK helm - Include TTK in mojaloop helm chart

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1731]
## **Goal**:
`As a` Individual implementer

`I want to` have TTK deployed as part of the mojaloop helm chart
  
`so that` I can use TTK to test the mojaloop deployment easily

**Acceptance Criteria**:
- [x] `When` Mojaloop is deployed using its helm chart in a local machine, 
`then` TTK should also be deployed automatically in the same environment as per the Mojaloop helm chart with proper configuration for endpoints, ingress URLs.
`and` We can test the deployed mojaloop instance using the accompanying TTK without further configuration.

- [x] `When` Mojaloop is deployed using its helm chart and a custom value file in a remote cluster, 
`then` TTK should also be deployed automatically in the same environment as per the Mojaloop helm chart with proper configuration for endpoints, ingress URLs.
`and` We can test the deployed mojaloop instance using the accompanying TTK without further configuration.

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Include the TTK as dependency in the Mojaloop folder in mojaloop helm chart
- [x] Add the values for the TTK backend, frontend and CLI charts in multiple levels (mojaloop values, deploy-config dev1 and dev2 values files ....etc)
- [x] Take care of the endpoints and hostnames in the values files to make TTK work straight away after deployment both in dev environments and in local deployment
- [x] Test the cluster in dev environment and also in the local environment

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] Covered in https://github.com/mojaloop/helm/pull/395

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
