### ISSUE TITLE
Implementation Support - DPIA : Establish Purpose of Processing for PII in a Settlement Process

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1732]
## **Goal**:
`As a` hub operator

`I want to establish purpose of processing for PII in a settlement process
  
`so that` I can record the information in my GDPR DPIA exercise

**Acceptance Criteria**:
- [x] TBD

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
This has been completed the report of this exercise is confidential to Mowali but available on request from Mowali directly.
