### ISSUE TITLE
TTK UI - Show outbound requests in monitoring page

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1736]
## **Goal**:
`As an` individual implementer

`I want to` see the outbound requests in monitoring page
  
`so that` I can debug every outbound request from my test cases

**Acceptance Criteria**:
- [x] Monitoring page in TTK should include outbound requests also

**Complexity**: Low (It's just logging the outbound requests from backend and show them in UI)

**Uncertainty**: Low

---

**Tasks**:
- [x] Refactor the TTK backend service to fire events for every outbound request
- [x] Re-design the monitoring page to have two sections for inbound and oubound categories
- [x] Implement the new design in TTK UI

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
