### ISSUE TITLE
TTK UI - Accept Enter and Escape keys at input dialogues in TTK UI

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1737]
## **Goal**:
`As a` individual implementer

`I want the` TTK UI to take the keyboard inputs for input dialogues
  
`so that` I can use TTK UI more easily

**Acceptance Criteria**:
- [x] `When` I press `Enter` key at an input dialogue, `Then` it should be submitted
- [x] `When` I press `Esc` key at an input dialogue, `Then` it should be cancelled

**Complexity**: Low

**Uncertainty**: Medium (Should investigate the options of Ant component library)

---

**Tasks**:
- [x] Identify the places to handle keyboard inputs
    - Sync Response Rules -> New Rules File
    - Validation Rules -> New Rules File
    - Callback Rules -> New Rules File
    - Outbound Request -> New Template
    - Outbound Request -> Save (Template)
    - Outbound Requests -> Add Test Case
    - Outbound Requests -> Add Input Value
    - Outbound Requests -> Rename (Test case)
    - Outbound Requests -> Test Case Editor -> Add New Request
    - Outbound Requests -> Test Case Editor -> Tests -> Add New Assertion
    - Outbound Requests -> Test Case Editor -> Tests -> Rename
- [x] Investigate options in Ant component library to handle keyboard inputs
   - Enter - there is existing onPressEnter event
   - Escape - there is no existing event so we need to update the the popup visibility to false if the event key is "Escape"
- [x] Implement the changes

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/62

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @georgi-logodazhki 
- QA/Review: @vijayg10
