### ISSUE TITLE
TTK UI - Import and Export Curl command in Test case editor

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1738]
## **Goal**:
`As a` individual implementer

`I want to` import and export curl command in test case editor
  
`so that` I can migrate the http requests from other tools into TTK and vice versa

**Acceptance Criteria**:
- [ ] `When` I import the curl command into TTK request editor, `Then` all the fields should be populated (Headers, Body, Path parameters, Query parameters, Host URL)
- [ ] `When` I click on 'Copy to Clipboard' button in test case editor, I want the curl command of the executed request should be copied to clipboard

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] Fix the issues with import curl functionality
- [ ] Add a button 'Copy to Clipboard' in request tab of test case editor

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
