### ISSUE TITLE
Implement/Accommodate ELK Stack

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#174]
**Goal**:
As a Hub TechOps
I want to have _the EFK (e.k.a ELK) Stack implemented and dashboard capability added_
so that _it helps in tracing/tracking transactions, messages and in debugging issues._

**Tasks**:
- [x] Draft helm chart for EFK stack, test and add to parent helm repo [ @jeffplesko ]
- [x] Test Helm chart [@jeffplesko, @mdebarros]
- [x] Deploy and ensure relevant logs are available, accessible [@jeffplesko, @mdebarros , @elnyry ]
- [x] Implement logger patterns for Mojaloop components so that EFK can index Mojaloop logs
- [x] Test querying of EFK against index'd Mojaloop logs

**Acceptance Criteria**:
- [x] ELK stack is available to provide search and other capabilities for the Mojaloop log files

**Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/147

**Dependencies**:
- None currently

**Comment by mdebarros** [comment]
@jeffplesko @elnyry update story with more explicit tasks

**Comment by mdebarros** [comment]
Screenshot showing a Transfer being traced by its ID: https://www.dropbox.com/s/jm5g2pm2g31xxb2/Screenshot%202019-02-14%2012.18.08.png?dl=0

This EFK deployment was done via the offical helm chart using the following CMD:
`helm install --namespace=logging --name=efk mojaloop/efk -f ./values-efk-IGNORE.yaml`

__Note: Values file contained the correct Ingress DNS for dev0 environment.__
