### ISSUE TITLE
PI-12 Community event presentations, demos - core team

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1743]
## **Goal**:
As a contributor team for the ML OSS
I want to prepare presentation and content for the PI-12 Community event
so that it can be used to demonstrate Mojaloop capabilities to the Community and for discussions

**Tasks**:
- [x] Create and share slide-deck template
- [x] Identify various sections, sub-topics and their owners
- [x] Prep for Demos
  - [x] Testing toolkit demos [@vijayg10 , @georgi-logodazhki ]
  - [x] v1.1 changes [PATCH notification, headers usage including transfer states, etc]
  - [x] Streamlining code, designs and Test frameworks (TTK)
  - [x] Running tests post-install, on-schedule (TTK)
- [x] Update presentation slide deck
  - [x] Overview and introduction section [@elnyry-sam-k ]
  - [x] Agile practices / streamlining [@ramakrishnan-sankar ]
  - [x] Maintenance updates
    - [x] Helm changes    - [ ] Accented characters
    - [x] v1.1 changes
    - [x] Bug Fixes
  - [x] Testing toolkit slides [@vijayg10 . @elnyry-sam-k , @georgi-logodazhki ]
  - [x] QA section [@amarmodus , @elnyry-sam-k ]
  - [x] Roadmap for PI-12
- [x] Review presentation and items to discuss

**Acceptance Criteria**:
- [x] A slide-deck is prepared for use during the PI-12 Community Event to inform / share progress regarding objectives and provide details as necessary. 
- [x] The slide deck covers all significant items worked on so far in PI-11 and also bring forth any significant design decisions.
- [x] Demo items are finalized and prepared

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @elnyry @mdebarros 
- QA/Review: OSS Core team
