### ISSUE TITLE
TTK Hosted Mode - Validate the documentation on deploying helm chart

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1744]
## **Goal**:
`As a` Scheme

`I want to` have a tested step-by-step documentation
  
`so that` I can deploy the TTK in hosted mode using the helm chart

**Acceptance Criteria**:
- [x] The TTK helm chart was successfully deployed in hosted mode using the step-by-step documentation for the following scenarios
  - [x] End-to-End solution for the scheme
  - [x] Using scheme's oauth server
  - [x] Using scheme's connection manager
  - [x] Without using mTLS and JWS
- [x] The TTK helm chart was successfully deployed in standalone mode as before

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Test the existing standalone deployment with the new helm chart
- [x] Deploy the helm chart with hosted mode with all necessary modules enabled
- [x] Verify configurability
  - [x] Check the feasibility to use scheme's keycloack oauth server 
  - [x] Check the feasibility to use scheme's connection manager
  - [x] Check the feasibility to use without using mTLS and JWS
- [x] Document the gaps identified

**Done**
- [x] Acceptance Criteria pass
- [x] Documentation is up-to date

## **Pull Requests**:
- [x] Added some commits to the PR https://github.com/mojaloop/helm/pull/387
- [x] https://github.com/mojaloop/deploy-config/pull/33

## **Observations**:
- The issues identified are fixed in backend service, helm and deploy-config repos
- Should hide the unnecessary and non working user settings like TLS, connection manager URL…etc
- TLS will not be supported with ingress rules. We may need to use network load balancer. We should investigate the possibilities and mention in the documentation about this.
- Need to take care of the load samples section in hosted mode. We may need to change the provisioning collections, environment files…etc
- If I add a user in key cloak with a different name than the dfspId, the connection manager interface is not allowing me to login with that user

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
Created a followup story for the gaps identified in this story.
https://github.com/mojaloop/project/issues/1773
