### ISSUE TITLE
TTK - setup connection manager environment based on users in keycloak server

### ISSUE THREAD

**Issue by georgi-logodazhki** [mojaloop/project#1745]
## **Goal**:
`As a` Scheme

`I want to` have a dynamic setup of the connection manager environment based on users in kyecloak server
  
`so that` I could configure all the certificates and endpoints in the connection manager

**Acceptance Criteria**:
- [x] `When` we add a new user in Keycloak server, `then` we should be able to login with the same user to:
  - [x]  TTK 
  - [x]  connection manager

**Complexity**:  Low

**Uncertainty**: Medium ( Investigation required on keycloak API)

---

**Tasks**:
- [x] Research how to read users through keycloak API 
- [x] Configure Admin access in TTK
- [x] Read users from keycloak server and add them to the connection manager

**Done**
- [x] Acceptance Criteria pass
- [x] Unit Tests pass
- [x] Code Style & Coverage meets standardsconfig.
## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/106

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @georgi-logodazhki 
- QA/Review: @vijayg10
