### ISSUE TITLE
TTK community support - Investigate the feasibility of supporting FXP use case in TTK

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1746]
## **Goal**:
`As an` individual implementer

`I want to` know whether TTK can cater for our usecase
  
`so that` I can use the TTK to test our solution

**Acceptance Criteria**:
- [x] Observed the postman test collection and identified the features covered in TTK and documented the gaps

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Go through the postman test collection and observe the end-to-end flow
- [x] Investigate on possibility to use TTK as test platform instead of postman
- [x] Implement the necessary changes required
  - [x] Minor change required to pass the converted request to script execution
- [x] Prepare a P2P test case for FXP based on the postman collection provided
- [x] Document the gaps identified

**Done**
- [x] Acceptance Criteria pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/107

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @georgi-logodazhki 
- QA/Review: @vijayg10

**Comment by vijayg10** [comment]
The following is the requirement from implementer.

**Comment by georgi-logodazhki** [comment]
[fxp-p2p-postTransfer-scenario.zip](https://github.com/mojaloop/project/files/5370572/fxp-p2p-postTransfer-scenario.zip)
we could manage fxp scenarios by implementing a custom logic in the pre-request or post-request scripts like in postman.
observe pre-request script in "P2P Transfer FXP Happy Path" / "POST /transfers". There if the currency not matched we are  taking the correct currency and virtual DFSP based on the payee dfspId.
