### ISSUE TITLE
[pisp/mojapay/demo-server] - e2e demo for account linking

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1747]
## **Goal**:
`As a` Community Member

`I want to` see an awesome demo of the account linking flow between the pisp-demo-server and the Testing Toolkit
  
`so that` I am impressed with the excellent work of the PISP team

**Acceptance Criteria**:
- [ ] working demo running locally

**Complexity**: Medium - we have done this before for the transfers flow

**Uncertainty**: High - I'm not sure what work needs to be done in the PISP app and demo server to get this working

---

**Tasks**:
- [x] locally running demo server and testing toolkit
- [x] configure demo server to talk to toolkit
- [x] add missing account linking calls to the demo server
- [ ] fix any missing or buggy UI components

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
This is working! I've made a few demo branches that will take a little while to merge back into their respective 'master's however.
