### ISSUE TITLE
[design] - Allow PISP to query the status of a thirdpartyTransactionRequest

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1748]
## **Goal**:
`As a` PISP

`I want to` be able to query the status of a thirdpartyTransactionRequest
  
`so that` I can recover from failures, or deliver more robust features to my users

**Acceptance Criteria**:
- [ ] accepted design and sequence diagram for `GET /thirdpartyRequests/transactions`

---

**Tasks**:
- [x] Design `GET /thirdpartyRequests/transactions` API call from PISP -> Switch, and detail how it might work
- [x] detailed sequence diagram and documentation

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date

## **Pull Requests**:
- [ ] https://github.com/mojaloop/pisp/pull/85

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
