### ISSUE TITLE
[pisp/design] - specify negative test cases for transactions flow

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1749]
## **Goal**:
`As a` OSS developer

`I want to` specify a set of unhappy path tests for the transactions flow
  
`so that` we can write the tests

**Acceptance Criteria**:
- [x] a set of test definitions for unhappy path transaction flow where PISP can do anything about

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [x] find out existing error scenarios for Transfer - Transfer folder in Postman
- [x] analyze existing error codes 
- [x] new error codes for new PISP features (non existing yet)
- [x] Create a new file, `PISPTransferFailure.test.ts` in https://github.com/mojaloop/pisp/tree/master/test/e2e
- [x] specify a set of negative use cases using the `it.todo()` jest syntax
> e.g: `it.todo('recieves a error callback from the DFSP initiating a transcation with a nonexistent counsentId)`

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/pisp/pull/90

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

https://github.com/mojaloop/pisp/blob/master/docs/error_codes.md
