### ISSUE TITLE
[central-services-shared] Add a consent-request/thirdparty/consent eventType.

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#1750]
## **Goal**:
`As a` developer 

`I want to` have event types for new pisp specific api calls.
  
`so that` calls are appropriately named in span event logging.

**Acceptance Criteria**:
- [ ] Event type names are approved by design team.
- [ ] Event types are added to https://github.com/mojaloop/central-services-shared/blob/master/src/enums/events.js
- [ ] Typescript declarations are updated here https://github.com/mojaloop/central-services-shared/blob/master/src/index.d.ts

**Complexity**: Low
**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
