### ISSUE TITLE
TTK: Option to re-order the test-cases in the test case editor

### ISSUE THREAD

**Issue by ramakrishnan-sankar** [mojaloop/project#1754]
## **Goal**:
`As a` Implementor

`I want to` have an option to re-order the test-cases in the TTK test case editor
  
`so that` i can better organize test cases as well as validate the tests case and sequences

**Acceptance Criteria**:
- [x] `When` a test case is reordered / repositioned  `then` 
    - [x] the test case should move to the correct location in the test hierarchy `AND` 
    - [x] the test case should be executed in the correct order when the TTK tests are run `AND`
    - [x] the new test case position should be recalled when the test collection page is loaded the next time.
- [x] `When` a request is reordered / repositioned  `then` 
    - [x] the request should move to the correct location in the test hierarchy `AND` 
    - [x] the request should be executed in the correct order when the TTK tests are run `AND`
    - [x] the new request position should be recalled when the test collection page is loaded the next time.

**Complexity**: Low 

**Uncertainty**: Low 

---

**Tasks**:
- [x] Redesign the test case list component as foldable list
- [x] Implement 'reorder' button for test cases
- [x] Implement 'reorder' button for requests in a test case
- [x] Test
- [x] ~~Release~~

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] E2E Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/58

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @georgi-logodazhki 
- QA/Review: @vijayg10
