### ISSUE TITLE
TTK: Synchronize collection manager and load samples file import

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1755]
## **Goal**:
`As a` Hub Operator

`I want to` have UI capabilities to import single files and ensure collection manager structure and load samples feature are in sync 
  
`so that` I can easily load files

**Acceptance Criteria**:
- [x] Single files can be imported using the frontend
- [x] Collection manager folder structure and 'load samples' browser feature are in sync

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Ability to import a single file into existing folder structure 
- [x] Change Load Samples folder browser functionality to sync. with folder structure in collection manager
- [x] Improve loading environment file to be more intuitive
- ~~`To be discussed` Provide a shortcut in the dashboard to run the GP with default environment easily if the TTK is deployed as part of the mojaloop~~
- [x] Add simple documentation in the dashboard about the various menu options

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/license-scanner/pull/21
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/91
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/147

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
