### ISSUE TITLE
TTK UI - Option to add file references in the collection manager

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1756]
## **Goal**:
`As a` QA team member

`I want to` be able to use file operations such as copy, paste, paste-as-reference
  
`so that` in collection manager so that I can easily create tests, files using collection manager, TTK UI

**Acceptance Criteria**:
- [x] Option to add file references in the collection manager is available

**Complexity**: Medium (Have to go through the existing logic in react components)

**Uncertainty**: Low

---

**Tasks**:
- [x] Add an option "Copy" in the context menu
- [x] Add an option "Paste" to copy the file at the selected location
- [x] Add an option "Paste as reference" to create file reference

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/64

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
