### ISSUE TITLE
2.4.20.02 Update helm charts to reference the PI-2 architecture - [5]

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#176]
**Goal**:
As a developer
I would like to Update helm charts to reference Percona XtraDB  as a dependency and updated separation of components
so that I can manage installations and upgrades

**Tasks**:
- [x] Updated dependencies for Kafka on Central-Ledger ~ @mdebarros
- [x] Updated values for Kafka on Central-Ledger ~ @mdebarros
- [x] Updated dependencies for Ml-API-Adapter ~ @ksatya77 
- [x] Updated dependencies for Kafka on Ml-API-Adapter ~ @mdebarros
- [x] Updated values for Kafka on Ml-API-Adapter ~ @mdebarros
- [x] Deploy to k8s cluster to validate & test deployments ~ @ksatya77 @mdebarros
- [x] Deploy to k8s cluster to validate & test connectivity ~ @ksatya77 @mdebarros
- [x] Sanity testing to make sure end-points are working ~ @ksatya77 @mdebarros

**Acceptance Criteria**:
- [x] helm charts to reference Percona XtraDB as a dependency
- [x] helm charts to have separation of components
- [x] helm charts to have kafka dependencies
- [x] Test result successfully deploying Mojaloop chart with Percona XtraDB + Kafka

**Dependencies**:
- [x] #263 

**Accountability**:
- Owner 
- QA/Review

**Comment by elnyry** [comment]
Miguel: Done already but hasn't been tested

**Comment by mdebarros** [comment]
@ksatya77 updated tasks to reflect what needs to be done now since this story is no longer blocked by

**Comment by ksatya77** [comment]
Thanks @mdebarros
