### ISSUE TITLE
Local environment files for MojaSim collection

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1760]
## **Goal**:
`As a` Community contributor

`I want to` be able to access a postman environment file that works for a local mojaloop deployment
  
`so that` use it to validate my local Mojaloop deployment

**Acceptance Criteria**:
- [x] A postman environment file that can be used for local (without DNS) Mojaloop deployments is provided for MojaSim test collection

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Create a postman environment file that works with local deployment for a Mojaloop deployment using MojaSims

**Done**
- [x] Acceptance Criteria pass
- [x] Code Style & Coverage meets standards
- [x] End-to-end tests pass on local deployments

## **Pull Requests**:
- [x] https://github.com/mojaloop/postman/pull/186
- [x] https://github.com/mojaloop/helm/pull/396

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @elnyry-sam-k

**Comment by vijayg10** [comment]
![Screenshot 2020-10-13 at 4 37 25 PM](https://user-images.githubusercontent.com/33152110/95853483-23536480-0d73-11eb-96d3-ccf3faeac256.png)
