### ISSUE TITLE
[3p-scheme-adapter] DFSP side - state machine & handlers

### ISSUE THREAD

**Issue by eoln** [mojaloop/project#1761]
## **DFSP side state machine**:
`As a` DFSP

`I want to` thridparty-scheme-adapter endpoints related to PISP transfer
  
`so that` I can participate in a transfer initiated by PISP

**Acceptance Criteria**:
- [x] definition of state machine
- [x] flow diagram for transfer from DFSP perspective
- [x] verification of Authorization done by auth-service endpoint (mock it if auth-service is not ready yet)
- [x] create story to implement ThridpartyRequests with PATCH /thirdpartyRequests/transactions/{ID} [here](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/1770)
- ~[ ] fix inbound PATCH interface in thirdparty-scheme-adapter to be compatible with api-snippets~
- [x] inbound thridparty.transactions.model 
- [ ] inbound thridparty.transactions.model unit tests
- [x] inbound BackendRequests unit tests
- [x] inbound handler for thirdpartyRequests/transactions
- [ ] inbound handler for thirdpartyRequests/transactions unit tests
- [ ] requestToPayTransfer endpoint for simulator
- [x] refactor pispTransactionModel to use GET /parties from sdk-standard-components to avoid a clash on PUT /parties
- [ ] inbound handler for thirdpartyRequests/transactions integration tests
- [x] for demo purpose call  PATCH /thirdpartyRequests/transactions/{ID} directly on PISP scheme-adapter Inbound endpoint
- [ ] TBD

**Complexity**: <Medium> > There is a need to properly identify the states

**Uncertainty**: <Low> > We have done it for PISP side

---

**Tasks**:
- [x] identify state machine phases/states
- [x] prepare TS interfaces
- [x] uml diagram for Transfer flow from DFSP perspective
- [x] extend config to express auth-service endpoints /  are sdk-standard-components ThirdpartyRequests exporting all necessary endpoints (create a new story if needed)?
- [x] implement state machine
- [ ] unit tests
- [x] implement handlers
- [ ] integration tests using docker-compose - consider to use auth-service or mock it if needed

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/43/files

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by eoln** [comment]
branch for implementing tests: https://github.com/mojaloop/thirdparty-scheme-adapter/tree/feat/1761_3pr_transactions
