### ISSUE TITLE
[3p-scheme-adapter] DFSP & PISP side cross integration tests

### ISSUE THREAD

**Issue by eoln** [mojaloop/project#1762]
## **Goal**:
`As a` party using thridparty-scheme-adapter in PISP Transfer flow

`I want to` run integration tests between both sides (DFSP & PISP) in a cross-linked setup of two thirdparty-scheme-adapters
  
`so that` be sure both sides (DFSP & PISP) can work together

**Acceptance Criteria**:
- [ ] integration test should be run in CI/CD

**Complexity**: <High> > We already did integration tests of crosslinked adapter but the Transfer flow is much more complex

**Uncertainty**: <Medium> > There could be hidden surprises in complex Transfer flow

---

**Tasks**:
- [ ] docker-compose setup
- [ ] mock not ready services
- [ ] integration test
- [ ] setup deffered call to PATCH @ inbound PISP side, so the flow will continue

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@kleyow any idea if we've done this already?

**Comment by kleyow** [comment]
don't believe so. from a prelimanary check there are no integration tests covering a direct PISP/DFSP tp scheme adapter interaction in `thirdparty-scheme-adapter`

**Comment by lewisdaly** [comment]
Would you say this is in scope though? To me it looks out of scope, since we're covering this in the docker-local tests

**Comment by kleyow** [comment]
Yes. I think we have enough coverage atm that this is just a nice to have.

**Comment by lewisdaly** [comment]
thanks. 

Closing as out of scope for now.
