### ISSUE TITLE
[pisp] - add git commit hook to generate plantuml diagrams

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1763]
## **Goal**:
`As a` OSS maintainer

`I want to` have a git commit hook to auto-generate plantuml diagrams
  
`so that` rendered sequence diagrams don't get out of sync with the code

**Acceptance Criteria**:
- [x] git commit hook implemented on mojaloop/pisp repo

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Add a git commit hook to generate plantuml diagrams in the mojaloop/pisp repo
- [x] if possible, only run on changed `.puml` files

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date

## **Pull Requests**:
- [ ] https://github.com/mojaloop/pisp/pull/104

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
