### ISSUE TITLE
[thirdparty-api-adapter] - handle `GET /thirdpartyRequests/transactions/{id}`

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1764]
## **Goal**:
`As a` PISP

`I want to` be able to issue a [thirdparty-api-adapter] - handle `GET /thirdpartyRequests/transactions/{id}`
  
`so that` I can query the status of a thirdparty transaction request

**Acceptance Criteria**:
- [x] implemented `GET /thirdpartyRequests/transactions/{id}` handler at thirdparty-api-adapter
- [x] passing unit tests

**Complexity**:  Medium
**Uncertainty**: Low

---

**Tasks**:
- [x] update thirdparty-api-adapter swagger spec to allow `GET /thirdpartyRequests/transactions/{id}`
- [x] update api-snippets if required
- [x] handle inbound `GET /thirdpartyRequests/transactions/{id}` from PISP
- [x] respond with a `202 Accepted`
- [x] lookup endpoint for DFSP based on `FSPIOP-Destination` header
- [x] forward request to DFSP
- [x] implement unit tests

**Links**
- [Sequence Diagrams](https://github.com/mojaloop/pisp/blob/master/docs/transfer/README.md#request-transactionrequest-status) in pisp repo

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/thirdparty-api-adapter/pull/39

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
