### ISSUE TITLE
[thirdparty-api-adapter] - handle `PUT /thirdpartyRequests/transactions/{id}`

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1765]
## **Goal**:
`As a` DFSP

`I want to` be able to inform a PISP of a transaction's status
  
`so that` I they can update their user (my customer)

**Acceptance Criteria**:
- [ ] implemented `PUT /thirdpartyRequests/transactions/{id}` handler at thirdparty-api-adapter
- [ ] passing unit tests

**Complexity**:  Medium
**Uncertainty**: Low

---

![Screen Shot 2020-10-13 at 12.16.11 pm.png](https://images.zenhubusercontent.com/5cd963af3613073e20e46e60/d1280af7-2f58-40da-bbd5-f17611443a22)

see [here](https://raw.githubusercontent.com/mojaloop/pisp/master/docs/out/transfer/api_calls_detailed/PISPTransferDetailedAPI-page2.png) for the full sequence diagrams.

> Note: this is a design change to bring the thirdparty-api more in line with the FSPIOP-API

**Tasks**:
- [x] update thirdparty-api-adapter swagger spec to allow `PUT /thirdpartyRequests/transactions/{id}`
- [x] update api-snippets if required
- [x] handle inbound `PUT /thirdpartyRequests/transactions/{id}` from DFSP
- [x] respond with a `200 OK`
- [x] lookup endpoint for PISP based on `FSPIOP-Destination` header
- [x] forward request to PISP
- [x] implement unit tests

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/thirdparty-api-adapter/pull/42

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
