### ISSUE TITLE
ML OSS: Testing tool-kit [PI-12]

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1767]
**Testing Toolkit Objectives for PI12**:

- [x] 1. Reach parity with Postman end-to-end test coverage for validating Switch, FSP, PISP implementations (for TTK), so Schemes can be confident of adoption
  - [x] Dependencies
     - [x] Enable javascript support in test case scripts
     - [x] Provide support for Payee side assertions using websocket feature in SDK scheme adapter
     - [x] Fix any issues related to test case creation / execution
     - [x] Implement a wrapper native program around TTK web UI to build test cases easily
  - [x] Measuring criteria: Hub test suites provide test coverage as much as the PM MojaSim test collection
  - [x] Separate FSP test suites for validating FSP implementations
  - [x] Provide test coverage at least as much as the MojaSim PM collection for Switch validation
  - [x] Provide FSP suite of tests for validating FSP implementations
- [x] 2. Support Schemes’ adoption of TTK
  - [x] Measuring criteria: Support Mowali Scheme [or one scheme]
  - [x] As a hosted solution for on-boarding
  - [x] As a validation tool for Switch implementation
  - [x] As a Validation tool for FSP implementations as part of on-boarding (Supported by Objective#1)
- [x] 3. Providing enhancements for TechOps teams of Schemes [Stretch goal]
  - [x] Usage / UI enhancements based on community feedback #1737 #1843 
  - [x] Sequence diagrams for default tests (based on event framework)
  - [ ] ~Event Framework integration [Stretch]~ moved to #2006 
  - [ ] ~Non-functional support [Stretch]~ moved to #2006 
  - [ ] ~Dashboards / home-screen for live data [Stretch]~ moved to #2006 

Additional items
- [ ] 4. Automate steps for on-boarding any new API [Stretch]
  - [x] Add capability to upload any API specification file through UI
  - [ ] ~Add capability to map callbacks to requests for asynchronous API through UI~ moved to #2006 

Follow-up to:  #1475
