### ISSUE TITLE
Clean up Mojaloop repos documentation

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#177]
**Goal**:
As a developer I want to clean up Mojaloop repos documentation

**Tasks**:
- [x] Clarify stakeholder objectives
- [x] Review current repo structure for optimisation
- [ ] Define conceptual high-level repository structure
- [ ] ~Clean up Mojaloop repos documentation~

**Acceptance Criteria**:
- [ ] Document high-level repository structure for comment
- [ ] Identify focus areas to be covered in the overall repository
- [ ] Propose a process to restructure repo and populate missing areas
- [ ] ~Mojaloop repos documentation is reviewed and has relevant information.~

**Dependencies**:
- None currently
