### ISSUE TITLE
[sdk-scheme-adapter] GET /parties on outbound service 

### ISSUE THREAD

**Issue by eoln** [mojaloop/project#1771]
## **Goal**:
`As a` DFSP

`I want to` retrieve parties information from the switch
  
`so that` I can use these to prepare other requests

**Acceptance Criteria**:
- [x] GET /parties model implemented

**Complexity**: <Medium> > A short comment to remind the reason for the rating

**Uncertainty**: <Medium> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Parties.model
- [x] GET /parties at Outbound
- [x] PUT /parties at Inbound
- [x] PUT /parties/.../error

**Done**
- [x] Acceptance Criteria pass
- [x] Unit Tests pass
- [ ] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/221
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/222

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
