### ISSUE TITLE
[pisp/contract] - Implement initial negative use cases against the TTK

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1775]
## **Goal**:
`As a` OSS Dev

`I want to` have a set of tests to validate the initial negative use cases identified in mojaloop/project#1749 
  
`so that` I can make sure that we can verify transaction failures against in our end to end tests.

**Acceptance Criteria**:
- [ ] simulated negative use cases with the TTK
- [ ] passing tests against the TTK - to fulfil negative cases identified in mojaloop/project#1749

**Complexity**:  Medium
**Uncertainty**: Medium

---

Following on from mojaloop/project#1749, we want to implement tests on some of these initial negative use cases.

While we initially planned to implement these tests against the docker-local environment, I'm now thinking it will be faster to implement these test cases against the TTK, and migrate them to test against the docker-local environment later on.

**Tasks**:
- [x] move `it.todo` tests from mojaloop/project#1749 into the `./test/contract` directory
- [ ] configure the TTK to simulate these test scenarios using the rules config (@sridharvoruganti might know more about this... I know it's possible)
- [ ] implement the tests

**Done**
- [ ] Acceptance Criteria pass
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
