### ISSUE TITLE
Design: Consolidated updates for CCB

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1777]
## **Goal**:
As a `PISP team`
I want to `update the CCB with the consolidated design docs` 
so that `we can deliver the benefits of PISP, while remaining aligned to the structure and objectives of the Mojaloop API`

**Tasks**:
- [x] Create PISP API definition
- [x] create CCB issue
- [x] manage discussion at upcoming meeting
- [x] report on successful results

**Acceptance Criteria**:
- [x] everything we are doing is ~accepted by~ proposed to the CCB

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
change proposal issue here: https://github.com/mojaloop/mojaloop-specification/issues/70
