### ISSUE TITLE
MPQS Lab Setup

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1779]
## **Goal**:
`As a` OSS developer

`I want to` a dedicated code quality and security test Lab on AWS
  
`so that` I can be able to test certain recommended configurations and settings from the approved standards and guidelines

**Acceptance Criteria**:
- [x] Document requirements
- [x] Deploy environment assisted by OSS team.
- [x] Install security tools to perform security testing and analysis on Mojaloop

**Complexity**: Medium  - All components of Mojaloop has to be installed

**Uncertainty**: Low - We have all the help we need within the OSS team to complete this 

---

**Tasks**:
- [x] Setup QA K8S environment [ @mdebarros ]
    - [x] Deploy k8s Cluster [ @mdebarros ]
    - [x] Configure Mojaloop env DNS [ @mdebarros ]
    - [x] Configure Access accounts [ @mdebarros ]
    - [x] Configure VPN accounts [ @mdebarros ]
- [x] Document requirements [ @rasputtintin  ]
- [x] Deploy Mojaloop environment [ @rasputtintin ]
- [x] Install security tools based on scope. [ @rasputtintin ]
- [ ] Subscribe to additional AWS components to support CPM use cases

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- https://github.com/mojaloop/project/issues/1871

## **Accountability**:
- Owner: @rasputtintin 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
Hi @rasputtintin what is the status of the lab?

**Comment by godfreykutumela** [comment]
Hi @rasputtintin can you execute this task - Install security tools based on scope - so that we can close this story by the end of the sprint.

**Comment by godfreykutumela** [comment]
Today's update - Topic: CQS - MPQS Environment Info and Walk-throughs
Date: Feb 22, 2021 12:26 PM Johannesburg
Meeting Recording:
https://modusbox.zoom.us/rec/share/eF4lKEdi2Hz2kLU-3SOo7By4HUTyTRHU4vrwi8NjZfiwx3z9qM2Z8BuSn76i_Hk4.P7SQsHpfZhd7ruo6
Access Passcode: Sf!UHT?2
I talk a bit about how k8s works: i.e. pods, deployments, ingress, services, k8s cluster config and some best practices.
Also cover on how to test Mojaloop.

**Comment by rasputtintin** [comment]
MPQS Environment setup completed:

1. Rancher and KubeCTL Access confirmed
2. Mojaloop deployment completed
3. Helm Mojaloop testing completed
4. Initial security tools deployed successfully based on PI Scope to conduct CIS Baseline scans, Audit and Vulnerability assessment of the environment.
5. Initial CIS scans conducted on Master and Worker Nodes

Next Steps
1 - Create and test auditing policies for Kubernetes, OS and scoped assets.
2 - Further vulnerability scans based on scope.

**Comment by godfreykutumela** [comment]
@bukasaaime please send @lewisdaly additional AWS components required to fully implement all the CPM related use cases.

**Comment by godfreykutumela** [comment]
Additional AWS components to be added to the lab to complete the setup

1. An AIM Admin user
2. ECR repository
3. Gateway
4. Lambda
5. Volumes (ECB)
6. KMS
7. Cloudfront
8. Route 53
9. Load Balancer
10. Certificate Manager

**Comment by godfreykutumela** [comment]
@lewisdaly Please assist in adding the above components or give @bukasaaime or @rasputtintin Admin rights so that they can add these themselves.

**Comment by lewisdaly** [comment]
Thanks @godfreykutumela - perhaps we can discuss on today's call the best way to go about this. I'm keen to automate as much as possible to reduce costs from keeping services running.
