### ISSUE TITLE
Onboarding team members

### ISSUE THREAD

**Issue by georgi-sgbg** [mojaloop/project#178]
**Goal**:
As a team-member I would like to make sure new SG team members are fully set-up to the project

**Tasks**:
- [ ] Ensure access to Harvest (Nico)
- [x] ModusBox emails (Nico)
- [x] Ubuntu dual-boot
- [x] Collect names and email addresses - Nikolay Anastasov: nikolay.anastasov@softwaregroup.com,
Shashikant Hirugade: shashikant.hirugade@softwaregroup.com,
Valentin Genev: valentin.genev@softwaregroup.com
- [x] Collect GitHub IDs: vgenev, shashi165, nikolayanastasov
- [x] Send self-invitation link to Slack mojaloop workspace: https://mojaloop-slack.herokuapp.com/
- [x] Communicate internally to arrange Ubuntu dual boot according to SG security policies
- [x] Communicate internally to arrange 16 GB RAM availability for the target machines
- [x] Slack invite to mojaloop-core-team channel, self-join onboarding
- [x] Introduction to Harvest and JIRA time-tracking requirement
- [x] Introduction to GitHub workflow
- [x] Introduction to standard coding style
- [x] Brief overview of documentation (mojaloop/mojaloop, mojaloop/docs)
- [x] Onboarding videos: https://drive.google.com/open?id=1kpQw5WU5djfWTPqYI1F65msbs6WNWyik
- [x] Getting the Central-Ledger up and running on local machines: https://github.com/mojaloop/central-ledger/blob/develop/Onboarding.md, https://github.com/mojaloop/central-ledger/blob/develop/README.md
- [x] Share Local Kubernetes Development Guide: https://github.com/mojaloop/mojaloop/blob/develop/contribute/Local-K8s-Development-Guide.md
- [x] Share Helm Charts Guide: https://github.com/mojaloop/helm/blob/develop/README.md
- [x] Ensure ZenHub access: https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd, https://github.com/mojaloop/project#boards?repos=116650553 (Nico, Thea)
- [x] Zoom availability
- [x] Software list: https://github.com/mojaloop/central-ledger/blob/develop/Onboarding.md
- [x] Dropbox access (Sam)
