### ISSUE TITLE
[docker-contract] - DFSP Side contract tests for linking

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1789]
## **Goal**:
`As a` OSS developer

`I want to` have contract tests against the mocked linking services (TTK) for the DFSP Scenarios
  
`so that` we can demonstrate full test coverage on the API

**Acceptance Criteria**:
- [x] Implemented `PUT /consentRequests/{id}` contract test from DFSP Side
- [x] Implemented `PUT /consents/{id}` contract test from DFSP Side

**Complexity**: Medium

**Uncertainty**: Low - we have other examples

---

We have adequate tests for the PISP side account linking in docker-contract, but we are missing a couple scenarios where the DFSP or Auth-Service needs to interact with the switch.

**Tasks**:
- [x] Add the necessary TTK config in `docker-contract` to handle the following scenarios
    - [x] `PUT /consentRequests/{id}` from DFSP for `WEB` auth channel (see [sequence here](https://github.com/mojaloop/pisp/tree/master/docs/linking#131-web))
    - [x] `PUT /consentRequests/{id}` from DFSP for `OTP` auth channel (see [sequence here](https://github.com/mojaloop/pisp/tree/master/docs/linking#132-otp--sms))
    - [x] `POST /consents` (I think perhaps we do have this, let's just double check. [sequence](https://camo.githubusercontent.com/42b253dfcf3a8223cd6b056362872fdb9a5b9396/687474703a2f2f7777772e706c616e74756d6c2e636f6d2f706c616e74756d6c2f70726f78793f63616368653d6e6f267372633d68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d6f6a616c6f6f702f706973702f6d61737465722f646f63732f6c696e6b696e672f342d6772616e742d636f6e73656e742e70756d6c))
    - [x] `PUT /consents/{id}` from the Auth-service or DFSP ([sequence](https://github.com/mojaloop/pisp/tree/master/docs/linking#162-finalizing-the-credential))
- [x] write tests in [`test/contract`](https://github.com/mojaloop/pisp/tree/master/test/contract) against the above scenarios

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Contract Tests pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/pisp/pull/97

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
