### ISSUE TITLE
2.4.50.01 Implement Kafka based Fulfills

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#179]
**Goal**:
1. As a developer
I would like to _implement Kafka based Fulfills_
so that the complete payment process is implemented as per PI2 architecture.
2. As a Payee FSP
I would like to _notify the Hub of an acceptance or rejection of a transfer request_
so that the Hub can manage the Settlement;
so that if the Transfer is rejected, the Payer's position can be reverted back to a state before the reservation of funds.

**Tasks**:
- [ ] Fulfill Handler Consume (Success) {2.1.1.}
  - [ ] Unit tests
  - [ ] Integration tests
- [ ] Position Handler Consume (Success) {2.1.2.}
  - [ ] Unit tests
  - [ ] Extend the existing Integration tests
- [ ] Transfer Handler Consume (Success) {2.1.3.}
  - [ ] Unit tests
  - [ ] Extend the existing Integration tests
- [ ] Send notification to Participant (Payer, Payee) {2.1 - 1.1.4.}
  - [ ] Unit tests
  - [ ] Extend the existing Integration tests
- [ ] ML-API-Adapter Fulfill Put (Success) {2.1.1}
  - [ ] Unit tests
  - [ ] Extend the existing Integration tests

**Acceptance Criteria**:
- [ ] The new base code has fulfills implemented with the latest design using the 'common library'
- [ ] Notifications are placed on the specific topics
- [ ] Functionality based on sequence diagrams for FulfillHandler is implemented
- [ ] ml-api-adapter is updated to handle fulfill requests
- [ ] ~Rejections based on Kafka events are implemented~
- [ ] ~ML-API-adaptor to produce rejection events~
- [ ] ~ML-API-adaptor to cater for fulfill rejections via API calls~
- [ ] ~Fulfill handler consumes rejection and produces position event~
- [ ] ~Position event handler to consume rejection: decrement position and produce notification, produce transfer~

**Dependencies**:
- [ ] #247 

**Accountability**:
- Owner 
- QA/Review

**Comment by elnyry** [comment]
This has been divided into 5 separate stories - #272 , #273 , #274 , #275 , #276 . The current estimate is for reviewing sequence diagrams to break this up and for adding stories etc. Also, created another item to cater for scenarios not covered as part of the happy path (Fulfil success). This will be addressed post PI3 meetings.

**Comment by elnyry** [comment]
Follow-up story #284
