### ISSUE TITLE
TTK Hosted Solution: TLS support

### ISSUE THREAD

**Issue by georgi-logodazhki** [mojaloop/project#1790]
## **Goal**:
`As a` Scheme

`I want to` have tls support in hosted mode for the testing toolkit
  
`so that` I can host the TTK and let my DFSP's use that

**Acceptance Criteria**:
- [x] TTK could be deployed with tls

**Complexity**: Low

**Uncertainty**: Medium

---

**Tasks**:
- [x] ~~TLS will not be supported with ingress rules. We may need to use network load balancer. We should investigate the possibilities~~ This is not correct, the nginx ingress can be configured with SSL
- [x] Fix the issue with connection manger service when TTK is running in hosted mode
  - [x] Fix the issue with getting user list from keycloak
  - [x] Fix the issue with autogeneration of hub certs in connection manager
  - [x] Refactored the TLS config param (Moved from user config to system config)
- [x] Test the hosted mode with TLS using a simulator by configuring proper keys and certs
- [x] Fix unit tests
- [x] Change the values in the helm chart if any
- [x] Provide docker-compose file for hosted mode with TLS
- [x] Proper comments should be placed to switch between normal deployment, hosted mode (With TLS and without TLS)
- [x] ~~Add documentation. about the hosted mode~~ (This can be covered in the story #2409 )

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/192
- [x] https://github.com/mojaloop/helm/pull/458

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
