### ISSUE TITLE
TTK OBJ#1 Analyse the best way to make payee side assertions

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1793]
## **Goal**:
`As a` QA supporting a Hub implementation

`I want to` have the capability to make payee side assertions
  
`so that` I can use TTK to test my hub implementation end-to-end

**Acceptance Criteria**:
- [ ] Decision is taken whether to use TTK or MojaSim as payee while testing hub with TTK

**Complexity**: Low

**Uncertainty**: Medium

---

**Tasks**:
- [x] Observe pros and cons of using TTK as payee
- [x] Observe pros and cons of using Mojasim as payee
- [x] Determine the better way of making payee side assertions for TTK
- [x] Document findings and approach taken

**Done**
- [x] Acceptance Criteria pass
- [x] Observations are noted

## **Pull Requests**:
- [x] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @elnyry-sam-k

**Comment by vijayg10** [comment]
Drawbacks for both approaches are given below.

## Using TTK as payee
  - Should depend on TTK for payee simulation. There will be some additional work on defining rules for all the use-cases in the TTK to make it as complete simulator.
  - When somebody add features to mojaloop simulator, the necessary rules should be defined in the TTK also.

## Using Moja-SIM as payee
  - Simulators should be configured appropriately for running end to end golden path tests.
  - Hard to debug the errors in mojasim or scheme adapter
  - Implementing new feature to SDK or moja-sim is taking long time compared to adding the same functionality to TTK by just defining new rules.

## Conclusion
  - I think using "mojaloop-simulator" as payee simulator is a better way for now concerning the Moja-sims adoption by many mojaloop implementers and the confidence they have already on the simulator functionality of moja-sim compared to TTK.
  - If its feasible, it's a good practice to separate the logic for getting payee side data (requests/callbacks) from the actual test cases using a separate script file. All the tests can use the functions from the script file for getting payee side data. By using this approach we can easily switch payee side simulator just by editing that script instead of changing all the test cases.

**Comment by elnyry-sam-k** [comment]
Thanks for the analysis @vijayg10
