### ISSUE TITLE
TTK OBJ#1 Re-design the scripting functionality in outbound test cases

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1794]
## **Goal**:
`As a` individual implementer

`I want to` use javascript in TTK scripting
  
`so that` I can use third party functions in scripting to fulfil my requirements

**Acceptance Criteria**:
- [x] The new scripting design should support scripting in javascript and should be backwards compatible

**Complexity**: Medium (Should consider the existing test cases are using postman scripting)
**Uncertainty**: Medium (There is some bad reputation for javascript eval function)

---

**Tasks**:
- [x] Design the module structure and eval function usage to use javascript instead of postman
   _(Evaluated different sandbox libraries to replace postman-sandbox like vm, vm2, notevil, v8-sandbox. It seems VM is a better option to replace the exiting postman-sandbox based scripting module.
   It's better to maintain similar naming conventions for env variables and http request functions.)_
- [x] Find a way to achieve backward compatibility for the existing test-case collections
   _(We can acheive backward compatibility by introducing a parameter in test case template like **scriptingEngine** which can be set to new javascript. The default can be postman-sandbox for now)_
- [x] Should decide on the refactoring of three step pattern for scripts (pre-request, post-request and assertions)
  - [x] The fetched callback from a http or websocket request should be accessible from assertions instead of storing it in a temporary environment variable
  _(The three step pattern can be continued and we can share same context object in all the steps so that the scripts can use the variables set in previous steps)_
- [x] Understand the websocket usage of the scheme adapter and how to integrate the websocket functionality in TTK through scripting.
- [x] Optional: Design the re-usability of the scripting functions in test cases. They should be declared in a common js files and access them from different test cases in the folder _(I think this can be ignored now as some of the websocket functionality should be through some hardcoded functions in the service. Because it involves network connects and can not be achieved through user scripting entirely)_
- [x] Create a followup story for implementation

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date

**Follow-up**:
- #1859 
- #1860 

**Dependencies**:
- N/A

**Accountability**:
- Owner: @vijayg10 
- QA/Review: @elnyry-sam-k
