### ISSUE TITLE
TTK OBJ#1 - Validate the golden path collection

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1795]
## **Goal**:
`As a` individual implementer

`I want to` have a golden path test suite in TTK
  
`so that` validate my hub implementation with TTK

**Acceptance Criteria**:
- [x] TTK GP collection is available in testing-toolkit-test-cases which has almost the test coverage 

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Compare and validate the test-cases from postman GP mojasim collection with TTK collection
- ~~Change the webhook to run daily GP test suite and change the channel~~
- [x] Add some documentation about the test cases in the README file of the repo
- [x] Helm Changes
  - [x] Update the new input values in
    - [x] Default values in mojaloop helm chart
    - [x] TTK CLI cron values in deploy config
    - [x] TTK mobile sim values file in deploy config
  - [x] Add annotation to TTK helm chart for nginx ingress post body limit

**Done**
- [x] Acceptance Criteria pass
- [x] TTK test cases are available in the repo

## **Pull Requests**:
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/26
- [x] https://github.com/mojaloop/deploy-config/pull/35
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/27

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
