### ISSUE TITLE
TTK OBJ#1 - Standardise the DFSP collection

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1796]
## **Goal**:
`As a` individual implementer

`I want to` have a test case collection for DFSP
  
`so that` I can verify the DFSP implementation end-to-end

**Acceptance Criteria**:
- [x] DFSP test case collection should be available in testing-toolkit-testcases repo

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Refine the existing DFSP collection in examples
- [x] Add negative and other missing tests
- [x] Resopnses, http codes, headers and GET calls
- [x] Add JWS signing and validation based on the new javascript functions

**Note**
  - Admin, Settlement API resources are not needed
  - The tests should be generic to the FSP implementation. (Eg: We shouldn't use websocket functionality in the sdk-scheme-adapter. We may use test API, /scenarios, provisioning party ...etc which are specific to mojaloop simulator in a separate file with correct naming)

**Done**
- [x] Acceptance Criteria pass
- [x] Tests are up-to date

## **Pull Requests**:
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/23

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
