### ISSUE TITLE
TTK - There are no outbound logs when making requests from inbound scripting

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1797]
## **Goal**:
`As a` implementer

`I want to` see all the outbound logs when I make calls through scripting
  
`so that` I can use debug better

**Acceptance Criteria**:
- [x] Outbound logs appears in monitoring page when we make http calls in scripts
  - [x] Postman script
  - [x] Java script
  - [x] Both inbound and outbound scripts
- [x] Monitoring page should be improved

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Check the already implemented functionality in postman script
- [x] Implement the same functionality in javascript for axios commands
- [x] Swap the timestamp and request styling in monitoring page

**Done**
- [x] Acceptance Criteria pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/168
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/98

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
