### ISSUE TITLE
TTK OBJ#1 - Train PISP team to be able to prepare their own test cases

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1798]
## **Goal**:
`As a` individual implementer 

`I want to` learn to create my own test cases using TTK
  
`so that` I can test my implementation with TTK

**Acceptance Criteria**:
- [ ] Team should be able to create their own test cases

**Complexity**: Low

**Uncertainty**: Medium (Based on the interest and availability of the team)

---

**Tasks**:
- [ ] Conduct training sessions to explain about the test-case creation to cater for various use-cases

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
Mission accomplished
