### ISSUE TITLE
TTK OBJ#2 - Identify one scheme who are ready to adopt / try TTK for their validations

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1799]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` <action>
  
`so that` <reason> 

**Acceptance Criteria**:
- [x] Identify one scheme who are ready to adopt / try TTK for their validations

**Complexity**: Low

**Uncertainty**: Medium

---

**Tasks**:
- [x] Identify one scheme who are ready to adopt / try TTK for their validations
- [x] Schedule a meeting with Business, QA & Dev team to introduce TTK and its features

**Done**
- [x] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
