### ISSUE TITLE
Design & refactor the Accounts table and associated Micro-Service - [21]

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#18]
**Goal**:
As a developer I would like to design & refactor the Accounts table and associated Micro-Service in order to expand the data and functionality catered for

**Tasks**:
- [x] Normalise entire database and add referential constraints to move the integrity checks to the database rather than having implement RI programatically.
- [ ] Make code changes to reflect the changes to the normalised database, in this case the Accounts table and test all new RI checks

**Acceptance Criteria**:
- [x] Document a normalised data structure for Accounts and related tables
- [ ] Refactor the current implementation to cater for the normalised Accounts data structure
- [ ] Refactor unit tests to cater for the normalised Accounts data structure
- [ ] Refactor functional tests to cater for the normalised Accounts data structure
- [ ] Refactor integration tests to cater for the normalised Accounts data structure

**Dependencies**:
- #151

**Comment by NicoDuvenage** [comment]
create table if not exists migrations
(
	id serial not null
		constraint migrations_pkey
			primary key,
	name varchar(255),
	batch integer,
	migration_time timestamp with time zone
)
;

create table if not exists migrations_lock
(
	is_locked integer
)
;

create table if not exists accounts
(
	"accountId" serial not null
		constraint accounts_pkey
			primary key,
	name varchar(256) not null
		constraint accounts_name_unique
			unique,
	"createdDate" timestamp with time zone default now() not null,
	"isDisabled" boolean default false not null
)
;

create index if not exists accounts_name_index
	on accounts (name)
;

create table if not exists charges
(
	"chargeId" serial not null
		constraint charges_pkey
			primary key,
	"chargeType" varchar(256) not null,
	name varchar(256) not null
		constraint charges_name_unique
			unique,
	payer varchar(16) not null,
	payee varchar(16) not null,
	rate numeric(10,2) default 0::numeric not null,
	"rateType" varchar(256) not null,
	minimum numeric(10,2),
	maximum numeric(10,2),
	code varchar(256),
	"isActive" boolean default false not null,
	"createdDate" timestamp with time zone default now() not null
)
;

create index if not exists charges_name_index
	on charges (name)
;

create table if not exists "executedTransfers"
(
	"transferId" uuid not null
		constraint "executedTransfers_pkey"
			primary key
)
;

create index if not exists executedtransfers_transferid_index
	on "executedTransfers" ("transferId")
;

create table if not exists fees
(
	"feeId" serial not null
		constraint fees_pkey
			primary key,
	"transferId" uuid not null,
	amount numeric(10,2) not null,
	"payerAccountId" integer not null,
	"payeeAccountId" integer not null,
	"chargeId" integer not null
		constraint fees_charges_chargeid_fk
			references charges,
	"createdDate" timestamp with time zone default now() not null
)
;

create index if not exists fees_payeraccountid_index
	on fees ("payerAccountId")
;

create index if not exists fees_payeeaccountid_index
	on fees ("payeeAccountId")
;

create index if not exists fees_chargeid_index
	on fees ("chargeId")
;

create table if not exists "ledgerDomainEvents"
(
	"eventId" uuid not null
		constraint "ledgerDomainEvents_pkey"
			primary key,
	name varchar(128) not null,
	payload jsonb not null,
	"aggregateId" uuid not null,
	"aggregateName" varchar(128) not null,
	"sequenceNumber" smallint not null,
	timestamp timestamp with time zone default now() not null,
	constraint ledgerdomainevents_aggregateid_sequencenumber_unique
		unique ("aggregateId", "sequenceNumber")
)
;

create table if not exists roles
(
	"roleId" uuid not null
		constraint roles_pkey
			primary key,
	name varchar(256) not null
		constraint roles_name_unique
			unique,
	description varchar(1000),
	permissions text not null,
	"createdDate" timestamp with time zone default now() not null
)
;

create index if not exists roles_name_index
	on roles (name)
;

create table if not exists "settledTransfers"
(
	"transferId" uuid not null
		constraint "settledTransfers_pkey"
			primary key,
	"settlementId" uuid not null
)
;

create table if not exists settlements
(
	"settlementId" uuid not null
		constraint settlements_pkey
			primary key,
	"settlementType" varchar(16) not null,
	"settledAt" timestamp with time zone default now() not null
)
;

alter table "settledTransfers"
	add constraint settledtransfers_settlements_settlementid_fk
		foreign key ("settlementId") references settlements
;

create table if not exists tokens
(
	"tokenId" serial not null
		constraint tokens_pkey
			primary key,
	"accountId" integer
		constraint tokens_accountid_foreign
			references accounts,
	token varchar(1000) not null
		constraint tokens_token_unique
			unique,
	expiration bigint,
	"createdDate" timestamp with time zone default now() not null
)
;

create index if not exists tokens_accountid_index
	on tokens ("accountId")
;

create table if not exists "userCredentials"
(
	"userCredentialId" serial not null
		constraint "userCredentials_pkey"
			primary key,
	"accountId" integer not null
		constraint usercredentials_accounts_accountid_fk
			references accounts,
	password varchar(512) not null,
	"createdDate" timestamp with time zone default now() not null
)
;

create index if not exists usercredentials_accountid_index
	on "userCredentials" ("accountId")
;

create table if not exists users
(
	"userId" uuid not null
		constraint users_pkey
			primary key,
	key varchar(256) not null
		constraint users_key_unique
			unique,
	"lastName" varchar(128) not null,
	"firstName" varchar(128) not null,
	email varchar(256),
	"isActive" boolean default true not null,
	"createdDate" timestamp with time zone default now() not null
)
;

create table if not exists "userRoles"
(
	"userId" uuid not null
		constraint userroles_userid_foreign
			references users,
	"roleId" uuid not null
		constraint userroles_roleid_foreign
			references roles,
	constraint "userRoles_pkey"
		primary key ("userId", "roleId")
)
;

create table if not exists transfers
(
	"transferUuid" uuid not null
		constraint transfers_pkey
			primary key,
	state varchar(10) not null,
	ledger varchar(1024) not null,
	"debitAccountId" integer
		constraint transfers_debitaccountid_foreign
			references accounts,
	"debitAmount" numeric(10,2) default 0::numeric not null,
	"debitMemo" varchar(4000),
	"creditAccountId" integer
		constraint transfers_creditaccountid_foreign
			references accounts,
	"creditAmount" numeric(10,2) default 0::numeric not null,
	"creditMemo" varchar(4000),
	"creditRejected" smallint default 0::smallint not null,
	"creditRejectionMessage" varchar(4000),
	"executionCondition" varchar(4000),
	"cancellationCondition" varchar(4000),
	fulfillment varchar(65535),
	"rejectionReason" varchar(512),
	"expiresAt" timestamp with time zone,
	"additionalInfo" varchar(4000),
	"preparedDate" timestamp with time zone,
	"executedDate" timestamp with time zone,
	"rejectedDate" timestamp with time zone
)
;

create index if not exists transfers_debitaccountid_index
	on transfers ("debitAccountId")
;

create index if not exists transfers_creditaccountid_index
	on transfers ("creditAccountId")
;

alter table "executedTransfers"
	add constraint executedtransfers_transfers_transferuuid_fk
		foreign key ("transferId") references transfers
;

alter table fees
	add constraint fees_transfers_transferuuid_fk
		foreign key ("transferId") references transfers
;

alter table "settledTransfers"
	add constraint settledtransfers_transfers_transferuuid_fk
		foreign key ("transferId") references transfers
;

create table if not exists "settledFees"
(
	"feeId" integer not null
		constraint "settledFees_pkey"
			primary key
		constraint settledfees_fees_feeid_fk
			references fees,
	"settlementId" uuid not null
		constraint settledfees_settlements_settlementid_fk
			references settlements
)
;

create table if not exists "accountsSettlement"
(
	"accountSettlementId" serial not null
		constraint "accountsSettlement_pkey"
			primary key,
	"accountId" integer not null
		constraint accountssettlement_accountid_unique
			unique
		constraint accountssettlement_accountid_foreign
			references accounts,
	"accountNumber" varchar(16) not null,
	"routingNumber" varchar(16) not null
)
;

create table if not exists contacttype
(
	"contactTypeId" serial not null
		constraint contacttype_pkey
			primary key,
	desription varchar(256) not null
		constraint contacttype_description_unique
			unique
)
;

create table if not exists "accountsContact"
(
	"accountContactId" serial not null
		constraint "accountContact_pkey"
			primary key,
	"accountId" integer not null
		constraint accountscontact_accountid_foreign
			references accounts,
	"contactTypeId" integer not null
		constraint accountscontact_contacttypeid_foreign
			references contacttype,
	desription varchar(256) not null
)
;

**Comment by kjw000** [comment]
should we move this to 1.2?

**Comment by NicoDuvenage** [comment]
This story has been completed by applying the changes as required but will be moved to the "blocked" pipeline. We will not implement these changes yet until a design session provides outcome on the inevitable data model changes required as a result of the fact that we are planning to re-align to a new API specification.

**Comment by elnyry** [comment]
Duplicate, covered in other stories
