### ISSUE TITLE
TTK OBJ#2 - Help a scheme to be able to run the GP collection

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1800]
## **Goal**:
`As a` scheme

`I want to` check the GP collection of TTK
  
`so that` I can validate my implementation with TTK

**Acceptance Criteria**:
- [x] Scheme should be able to run GP collection on their implementation

**Complexity**: Low
**Uncertainty**: Medium (Based on the availability of the scheme members)

---

**Tasks**:
- [x] Work with Scheme's QA / Infra team to run TTK GP against their switch implementation
- [x] Record if there are any gaps and suggestions by the team

**Done**
- [x] Acceptance Criteria pass

## **Pull Requests**:
- NA

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Addressed this with a support team (provided mTLS support as part of the exercise..)
