### ISSUE TITLE
TTK OBJ#2 - Help Scheme to configure scheduled regression tests

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1801]
## **Goal**:
`As a` Schme

`I want to` know how to configure TTK CLI helm chart
  
`so that` I can schedule regression tests against my implementation

**Acceptance Criteria**:
- [ ] Help Scheme to configure scheduled regression tests

**Complexity**: Low

**Uncertainty**: Medium (Schmes availability)

---

**Tasks**:
- [ ] Work with Scheme's infra team to train how to configure TTK CLI helm chart for scheduled regression tests

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
