### ISSUE TITLE
TTK OBJ#2 - Train Scheme to add their own test cases in addition to the provided collection

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1802]
## **Goal**:
`As a` Scheme

`I want to` know how to write my own test cases in TTK
  
`so that` I can test my implementation end-to-end

**Acceptance Criteria**:
- [x] Train Scheme to add their own test cases in addition to the provided collection

**Complexity**: Low

**Uncertainty**: Medium (Scheme's availability)

---

**Tasks**:
- [x] Conduct training session to explain how to write test cases in TTK for QA & Developers in Scheme

**Done**
- [x] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
now covered; helped an MES team with this
