### ISSUE TITLE
TTK OBJ#2 - Train Schemes to do DFSP validation locally

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1803]
## **Goal**:
`As a` Scheme

`I want to` be able to validate the implementation of our DFSPs using TTK
  
`so that` I can assist my DFSPs on using TTK for their self validation

**Acceptance Criteria**:
- [ ] Schemes' should be able to validate DFSP implementations locally

**Complexity**: Low

**Uncertainty**: Medium (Scheme's availability)

---

**Tasks**:
- [ ] Conduct a training session for the team on validating DFSP implementations locally

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
