### ISSUE TITLE
TTK OBJ#2 - Help Schemes to deploy TTK in hosted mode

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1804]
## **Goal**:
`As a` Scheme

`I want to` be able to deploy TTK in hosted mode using helm chart
  
`so that` I can provide access to our DFSPs to test their implementations

**Acceptance Criteria**:
- [ ] TTK should be deployed in Scheme's environment
- [ ] Identify if there are any gaps

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Work with Scheme's infra team to deploy TTK in hosted mode in their environment
- [ ] Record if there are any gaps identified

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Closing for now; if this use case materializes in the future, this can be revived..
