### ISSUE TITLE
TTK OBJ#2 - Followup with FXP team

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1805]
## **Goal**:
`As a` individual implementer

`I want to` be able to use TTK
  
`so that` I can test my implementation with TTK

**Acceptance Criteria**:
- [ ] Followup with FXP team and provide them the example test case

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Schedule a call with FXP team and provide them the example test case

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
