### ISSUE TITLE
TTK OBJ#4 - API spec file upload feature in UI

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1808]
## **Goal**:
`As a` individual implementer

`I want to` have a feature in UI to provision my API spec file in TTK
  
`so that` I can use TTK with my API requests for validation, exploration or demonstration purposes

**Acceptance Criteria**:
- [x] API Spec upload feature is available in TTK UI
- [x] Documentation is updated to reflect this feature

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Add new endpoint in backend to provision a new api
  - [x] The new entry should be created in system config
  - [x] New file should be uploaded to spec_files folder
- [x] Add uploading option in UI with following parameters
  - [x] API spec name
  - [x] Sync / Async
  - [x] Version
  - [x] File upload
- [x] Make sure the service should be reloaded after provisioning the new API (like openapibackend handlers, callback map...etc)
- [x] Validate the selected API file first before creating the entry and uploading it to backend
- [x] Add feature for deleting the added APIs
- [x] Add unit tests

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/67
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/112

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @elnyry-sam-k

**Comment by vijayg10** [comment]
![Uploading api-provisioning-add-new-api-confirmation.png…]()
