### ISSUE TITLE
TTK OBJ#4 - Adding custom mock values through UI

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1810]
## **Goal**:
`As a` individual implementer

`I want to` have an option to provision a new API in TTK
  
`so that` I can use TTK to test my API implementation

**Acceptance Criteria**:
- [ ] Custom mock values should be able to specify through UI

**Complexity**: Low
**Uncertainty**: Low

---

**Tasks**:
- [ ] Implement backend endpoint
- [ ] Add UI feature to add custom mock values for the selected API

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
