### ISSUE TITLE
Apply updated license acros Mojaloop Org

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1811]
## **Goal**:
`As an` OSS Maintainer

`I want to` have an updated license file
  
`so that` the terms of the Mojaloop license are clear

**Acceptance Criteria**:
- [ ] Updated license in all public, non archived mojaloop repos

**Complexity**: Low - we have done this before
**Uncertainty**:  Low

---

**Tasks**:
- [x] Using Lewis' (work in progress) community tools - run the [update-license](https://github.com/vessels-tech/moja-stats/blob/master/oss-stats/gulpfile.ts#L132) tool across all repos with the [updated license](https://github.com/mojaloop/mojaloop/blob/master/LICENSE.md)
- [ ] PR review and Merge!

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review:  @kjw000

**Comment by lewisdaly** [comment]
I'm currently updating some of the tooling we have [here](https://github.com/mojaloop/community-tools/tree/feat/repo-sync) with a tool for updating multiple file sets across all repos.

**Comment by lewisdaly** [comment]
about 71 PRs are currently being reviewed by @elnyry-sam-k
