### ISSUE TITLE
Widget testing for Mojapay

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1812]
@MahidharBandaru commented on [Wed Aug 05 2020](https://github.com/mojaloop/mojaloop/issues/405)

## **Goal**:
As a developer I want Mojapay to have good widget testing coverage.

**Tasks**:
- [x] Write widget tests for authentication screens
- [ ] Write widget tests for transaction flow screens
- [ ] Write widget tests for account dashboard screen

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Widget Tests Pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
