### ISSUE TITLE
[demo-app] - linking Request and sign challenge

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1813]
@kkzeng commented on [Tue Aug 04 2020](https://github.com/mojaloop/mojaloop/issues/399)

**Goals**

**Task**

- [ ] Request a challenge from the backend
- [ ] Ask user to verify identity using biometric auth process (fallback to PIN if not available)
- [ ] Sign the challenge
- [ ] Show that account linking process was successful using a nice UI.
