### ISSUE TITLE
Compile Typescript to Javascript for production deployment

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1814]
@eoln commented on [Mon Aug 17 2020](https://github.com/mojaloop/mojaloop/issues/415)

## **Goal**:
As a Hub Operator I want to run Typescript services as Javascript so that execution env doesn't have to play with Typescript dependencies
**Tasks**:
- [ ] find out proper TS->JS translation method (AOT), experiment with output code optimization 
- [ ] handle paths shortcuts defined in `tsconfig.json` and not properly resolved during TS->JS translation
- [ ] drop any Typescript dependencies from `production`
- [ ] build a container with JS only & adjust docker-compose if needed

**Acceptance Criteria**:
- [x] thirdparty-api-service 
- [x] thirdparty-sdk
- [ ] auth-service
- [x] Unit Tests pass run against Javascript compiled code
- [x] Integration Tests pass run against Javascript compiled code
- [x] Code Style & Coverage meets standards
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/thirdparty-api-svc/pull/64
- [x] https://github.com/mojaloop/thirdparty-sdk/pull/127
- [x] https://github.com/mojaloop/auth-service/pull/96

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
