### ISSUE TITLE
[auth-service] - Consistent Error Handling for `PUT callbacks`

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1815]
@ramanmangla commented on [Tue Jul 07 2020](https://github.com/mojaloop/mojaloop/issues/355)

## **Goal**:
As a `Developer`
I want `ensure consistent and complete error handling in auth models and endpoints`
so that `I can ensure there is no undefined behavior at run time.`

**Tasks**:
- [ ] ~Add Auth-Service/PISP specific errors to the Mojaloop error codes~ New error codes not needed, can use existing enum value (rejected)
- [x] Modify sdk-standard-components to be able to call `PUT consents/{ID}/error` to notify the client of an error in the auth-service
- [x] Modify auth-service source code to handle errors correctly
- [x] Add unit tests to test `PUT callback` errors
~- [ ] Add integration tests to test `PUT callback` error API flows~
- [ ] ~Document error conditions for later refining and mapping to approved error codes~ [New error codes not needed; can use "rejected" state in the [data model](https://github.com/mojaloop/documentation/blob/master/website/versioned_docs/v1.0.1/api/thirdparty/data-models.md#3221-authenticationresponse)]
- [x] 2/18: Review error codes used

**Acceptance Criteria**:
- [x] Unit tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-standard-components/pull/108
- [x] https://github.com/mojaloop/auth-service/pull/99

## **Follow-up**:
- [x] Harmonize error codes afterwards

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

---

@eoln commented on [Fri Sep 25 2020](https://github.com/mojaloop/mojaloop/issues/355#issuecomment-698756786)

The idea behind this story is that all handling of async errors reported to the client using PUT …/{id}/error should be handled in the same way/style over the code. Now in code, there are still places with TODO comments and there is a need to revise the whole code and make it consistent.

There is also a need to revise the list of error codes and create a new one if needed

**Comment by lewisdaly** [comment]
@kleyow can you please comment on the status on this ticket? I had a look around the auth service code, and didn't see any `PUT /error` calls... but I didn't look too hard.

**Comment by kleyow** [comment]
there are error callbacks for account linking https://github.com/mojaloop/auth-service/blob/master/src/model/registerConsent.model.ts#L167

right now I believe they need another pass/check/addition of error codes to `sdk-standard-components` is needed. right now errors are returning generic account linking `PUT` callbacks.

**Comment by lewisdaly** [comment]
I think this may have been covered in other tickets, but we need to double check and confirm.

**Comment by elnyry-sam-k** [comment]
@lewisdaly , @kleyow , @georgi-logodazhki - can you please take another look at this and list whats need to see it through?

**Comment by elnyry-sam-k** [comment]
Follow-up story: https://github.com/mojaloop/project/issues/2699 (This doesn't need new error codes in this instance but can use the 'rejected' enum value of the the enumeration [`AuthenticationResponse` ](https://github.com/mojaloop/documentation/blob/master/website/versioned_docs/v1.0.1/api/thirdparty/data-models.md#3221-authenticationresponse).
