### ISSUE TITLE
[docker-local] - Investigate a clean solution to DNS resolution for PISP's docker setup on Linux based OS's.

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1821]
@kleyow commented on [Mon May 11 2020](https://github.com/mojaloop/mojaloop/issues/296)

## **Goal**:
As a developer I want to run the PISP local mojaloop without having to battle DNS issues.

**Tasks**:
- [ ] Implement a solution that resolves the service DNS's without using the `extra_hosts` option.

**Acceptance Criteria**:
- [ ] Setup runs and tests pass under solution.
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

---

@lewisdaly commented on [Tue May 19 2020](https://github.com/mojaloop/mojaloop/issues/296#issuecomment-630757526)

Not a critical issue, nice to have. 

---

@lewisdaly commented on [Thu Oct 29 2020](https://github.com/mojaloop/mojaloop/issues/296#issuecomment-718353398)

We should look into this a little more if we want to spin out docker-local into it's own 'thing'.

**Comment by lewisdaly** [comment]
This was taken care of by fixing some of the docker-compose config.
