### ISSUE TITLE
[central-ledger] Add PISP TP_CB_URL_TRANSACTION_REQUEST_PATCH endpoint to database seeds.

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1822]
@kleyow commented on [Fri Sep 11 2020](https://github.com/mojaloop/mojaloop/issues/428)

## **Goal**:
As a `DFSP/PISP`
I want `to be able to register Thirdparty PATCH callback endpoint with the mojaloop switch`
so I `can support PISP functions`

**Tasks**:
- [x] Add the new TP_CB_URL_TRANSACTION_REQUEST_PATCH endpoint type to the database seed
- [x] bump and release on the `central-ledger:pisp` repo
- [x] update end to end onboarding (postman) collections to register the new TP_CB_URL_TRANSACTION_REQUEST_PATCH endpoint in `mojaloop/pisp/docker-local` for each DFSP/PISP
- [x] Update endpoint type in `central-services-shared`  https://github.com/mojaloop/central-services-shared/blob/master/src/enums/endpoints.js and build
- [x] Update endpoint type in `thirdparty-api-adapter` https://github.com/mojaloop/thirdparty-api-adapter/blob/master/ambient.d.ts

Links:
- [PISP endpoint type reference](https://github.com/mojaloop/pisp/blob/master/docs/participant_endpoint_enums.md)
- [`central-ledger` seed file](https://github.com/mojaloop/central-ledger/blob/master/seeds/endpointType.js)

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] E2E Tests pass

## **Pull Requests**:
- []

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
@lewisdaly , @kleyow - this seems to be done already, is there anything still left?

**Comment by kleyow** [comment]
Yes this story seems to been done.
