### ISSUE TITLE
productionize ml-operator v1.0

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1824]
## **Goal**:
`As a` OSS maintainer

`I want to` productionize the ml-operator
  
`so that` it can be deployed automatically from the mojaloop helm charts

**Acceptance Criteria**:
- [ ] deployable ml-operator as part of mojaloop helm charts

**Complexity**: Medium
**Uncertainty**: Medium

---

**Tasks**:
- [ ] compile ts to js 
- [ ] add ml-operator to `mojaloop/helm` repo along with instructions for how to configure it

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/417 - first pass that needs plenty of work

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: @elnyry-sam-k

**Comment by lewisdaly** [comment]
Done!
