### ISSUE TITLE
automate ml-operator upgrades

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1825]
## **Goal**:
`As a` hub operator

`I want to` have the ability to auto upgrade my running mojaloop deployment
  
`so that` the latest security patches and fixes are applied

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Medium

**Uncertainty**:  Medium

---

**Tasks**:
- [ ] add the ability for ml-operator to automatically upgrade the cluster during a specified upgrade window

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
