### ISSUE TITLE
ml-operator define admin API

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1826]
## **Goal**:
`As a` OSS developer

`I want to` define an admin API for the ml-operator
  
`so that` I can easily see and manage upgrade windows

**Acceptance Criteria**:
- [ ] basic admin api defined for ml operator with the ability to (1) see outdated and current images being watched, (2) view the upgrade window, (3) click "update now" to apply the fix

**Complexity**: Medium
**Uncertainty**: Medium

---

**Tasks**:
- [ ] define an admin api for the ml-operator with the ability to (1) see outdated and current images being watched, (2) view the upgrade window, (3) click "update now" to apply the fix

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
