### ISSUE TITLE
Perform an audit of our ci/cd pipelines

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1827]
## **Goal**:
`As a` OSS Contributor

`I want to` understand the different ci/cd configs we are using
  
`so that` we can plan a cohesive ci/cd strategy and abstract away common features

**Acceptance Criteria**:
- [ ] a list of all repos that are under ci/cd
- [ ] a categorization of repo type, age of ci/cd pipelines, purposes etc.

**Complexity**:  Low
**Uncertainty**: Low

---

Before we try and harmonize our ci/cd pipelines, we should first go through and understand what we have across the different repos. 

**Tasks**:
- [ ] look through each repos and produce a list of ci/cd uses, targets, artifacts, production-readyness etc.

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
