### ISSUE TITLE
Security Review November

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1828]
**Tasks**:
- [x] review dependabot alerts
- [x] merge in existing PRS
- [x] create new prs for fixes where applicable
- [ ] created any follow up tickets where applicable

- apply to the following repos (as identified by dependabot):
  - [x] ml-number
  - [x] mojaloop-simulator
  - [x] template-typescript-public
  - [x] central-services-health
  - [x] event-stream-processor
  - [x] account-lookup-service
  - [x] central-services-metrics
  - [x] central-event-processor
  - [ ] central-settlement

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-number/pull/8
- [x] https://github.com/mojaloop/event-stream-processor/pull/30
- [x] https://github.com/mojaloop/account-lookup-service/pull/374
- [x] https://github.com/mojaloop/mojaloop-simulator/pull/83
- [ ] https://github.com/mojaloop/central-settlement/pull/327

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Central-settlement has a bunch of other issues with integration tests. I think we should address that in a separate follow up.
