### ISSUE TITLE
Implement Exception handling framework

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#183]
**Goal**:
As a developer I would like to Implement Exception handling framework so that error/exceptions are gracefully handled.

**Note**:
- [ ] Break this down once design is done (dependency)

**Tasks**:
- [ ] Lookup/Translation for errors (caching?)
- [ ] Implement Exception handling framework

**Acceptance Criteria**:
- [ ] Capability to capture exceptions (and preferably persisted) and notify as needed via mechanism thats relevant (callbacks/notifications)

**Dependencies**:
- [ ] #243

**Comment by elnyry** [comment]
Using #765 now..
