### ISSUE TITLE
PISP Support - Research on FIDO Private key security - Android Keystore

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1835]
## **Goal**:
`As a` OSS security officer

`I want to` investigate FIDO private key security controls specific to mobile operating systems (Android Only)
  
`so that` I can make recommendations to the PISP team to enhance security of the PISP linking and transaction process.

**Acceptance Criteria**:
- [x] Identify details of Android FIDO private key storage
- [x] Identify details of ISO FIDO private key storage
- [ ] Identify possible risks affecting FIDO private key storage in Android devices and communicate to PISP team

**Complexity**: <Medium> This is because it requires an indepth understanding of Android and IOS secure keystore and possible vulnerabilities of each.

**Uncertainty**: <Medium> > Possible lack of detailed information on investigation items.

---

**Tasks**:
- [x] Investigate Android secure keystore [ @rasputtintin  ]
- [ ] Document standard on Android secure keystore use for storing PISP FIDO private key [ @rasputtintin  ]
- [ ] Discuss findings with PISP team [ @rasputtintin  ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
Hi @rasputtintin any update on this from last week?

**Comment by rasputtintin** [comment]
The focus this week is to look at the Android keystore in relation to FIDO Private key storage:
1 - Understand Android Key store
2 - Understand security features relative to PKI
3 - Link security features to proposed PISP FIDO Linking / Transaction signing and identify any gaps.

**Comment by rasputtintin** [comment]
Examine key generation processes using android code using java code
- Key generation using Android keystore on mobile device
- Key generation without using android keystore on mobile device
- Test whether code can output private keys to the logs

Focus this week is to complete the report and commence IOS investigation

Key areas of concern:
- It is possible for a developer to output generated keys to phone logs
- With appropriate permissions, the developer may read out the private keys and possibly use them. Further research on this aspect is necessary.
- Consider having device fingerprinting options as part of overall PISP Merchant security model for mobile.

**Comment by godfreykutumela** [comment]
@bukasaaime Please work on this one as well with @rasputtintin

**Comment by bukasaaime** [comment]
Good day @godfreykutumela and @rasputtintin,

1. FIDO keys are protected by authenticators (internal or external).
2. In addition, in the case of a mobile phone, biometrics or PIN are used.

**Comment by rasputtintin** [comment]
> Good day @godfreykutumela and @rasputtintin,
> 
> 1. FIDO keys are protected by authenticators (internal or external).
> 2. In addition, in the case of a mobile phone, biometrics or PIN are used.

Agreed @bukasaaime 

My question was to check whether its possible for a developer to programmatically read the keys via code from within the device using the same app that makes the call to generate the keys.

**Comment by bukasaaime** [comment]
Hi @rasputtintin,

As far as I know, once the public/private key pair is generated, only the public can be exported from the secure element. The private key can only be used to generate signatures (sign transactions) but cannot be exported.

**Comment by rasputtintin** [comment]
is there any way we can test this so we can conclusively validate the risk. 

> Hi @rasputtintin,
> 
> As far as I know, once the public/private key pair is generated, only the public can be exported from the secure element. The private key can only be used to generate signatures (sign transactions) but cannot be exported.

Thanks @bukasaaime . 

Im looking for any links that we can use to conclusively verify/demonstrate this so we can close the possible risk. 

Another area would be to digest what implications FIDO Certified Authenticator levels are required at minimum to support PISP as detailed here: [FDO Authenticator Certification](https://fidoalliance.org/certification/authenticator-certification-levels/) . It may have implications on supported Android devices which the business needs to be cognizant of.

**Comment by lewisdaly** [comment]
Hey @bukasaaime and @rasputtintin - just to follow up on this one:

Our latest sequence diagrams for the linking process are available [here](https://github.com/mojaloop/pisp/tree/master/docs/linking).

I wanted to draw your attention to [this section](https://github.com/mojaloop/pisp/tree/master/docs/linking#162-registering-the-credential)
We have decided to design for 2 types of credentials: (1) a generic public/private keypair, and (2) a FIDO credential.

This means that a DFSP or Hub can require a PISP to use the FIDO credential type, which will include the attestation object in the `payload` field - allowing the PISP to prove the authenticity of the credential.

**Comment by godfreykutumela** [comment]
Thanks @lewisdaly for this update. Please lets create a new GitHub issue for under our PI 13 CQS epic to trace this better.
