### ISSUE TITLE
TTK OBJ#1 - Reference P2P test case with new payee side assertions functionality

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1839]
## **Goal**:
`As a` QA team member

`I want to` have a reference for payee side assertions
  
`so that` I can create payee side assertions for all corresponding moja-sim tests in TTK

**Acceptance Criteria**:
- [x] A reference P2P happy path test case with the new payee side assertions functionality is created in TTK using web-socket feature in scheme-adapter

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Refactor the P2P test case in golden path using websocket functionality to make payee side assertions
- [x] Make this websocket based assertions configurable from "InputValues"
- [x] This test case passes 100% on Dev1 or Dev2 environments
- [x] Merge the changes to collection and environment files to respective repos.

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/404
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/17

**Dependencies**:
- #1794 

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @elnyry-sam-k
