### ISSUE TITLE
Implement Settlement Engine

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#184]
**Goal**:
As a developer I would like to Design & Implement Settlement Engine to facilitate Settlements

**Tasks**:
- [ ] Implement Settlement Engine

**Acceptance Criteria**:
- [ ] A Settlement Engine to kick-off settlements based on an API request 
- [ ] Settlement Engine can settle all transfers (pending settlement)
- [ ] Settlement Engine can kick-off a position event to reduce the positions of each associated FSP

**Dependencies**:
- [ ] #245

**Comment by elnyry** [comment]
Covered in stories starting with 3.xx numbers
