### ISSUE TITLE
TTK OBJ#1 - Implementation for payee side assertions from a separate script file

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1840]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` <action>
  
`so that` <reason> 

**Acceptance Criteria**:
- [ ] Capability of including a script file in test cases
- [ ] Payee side assertions can be made from the script using websockets (to SDK or Moja-Sim)

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- #1839 

**Dependencies**:
- #1794 

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
Two stories are created related to the implementation (#1859 & #1860). So this story is no longer required.
