### ISSUE TITLE
[DevSecOps] Streamline GitHub Repo access

### ISSUE THREAD

**Issue by kjw000** [mojaloop/project#1841]
## **Goal**:
As an administrator of Mojaloop GitHub Org, we need to clean up repo access

I want to:
1) Move anyone who as admin access to specific repos to maintain access
2) Create new org level group called "Mojaloop Maintain" - this needs maintain repo access to every repo (add Miller, maybe others)
3) Create new org level group called "Mojaloop Admin"  - this needs admin repo access to every repo (this is specifically for CI/CD access

 **Acceptance Criteria**:
- [x] No individual users should have admin access at repo level (should only be groups)
- [x] A group 'ml-maintainers' is created that consists of users who need maintain access on all repos
- [x] A group 'ml-administrators' is created that consists of users who need admin access on all repos

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Move anyone who as admin access to specific repos to maintain access
- [ ] Create new org level group called "Mojaloop Maintain" - this needs maintain repo access to every repo (add Miller, maybe others)
- [ ] Create new org level group called "Mojaloop Admin"  - this needs admin repo access to every repo (this is specifically for CI/CD access

**Done**
- [ ] Acceptance Criteria pass
- [ ] Changes made are documented and communicated
- [ ] New guidelines for access, groups are documented and communicated

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Starting with a repo review first, I think we need to reach out to a few people for:
- Mowali repos that may not be needed
- Anyone still using (somehow) the dfsp-* repos (there's a lot of them)

**Comment by lewisdaly** [comment]
Update:

- Most flagged old repos have been deleted, we are currently waiting until next week to archive and close the following repos:
```
interop-devops
interop-elk
interop-ilp-conditions
interop-switch
ilp-crypto
ilp-service
```

- Sam and Lewis are working to classify our existing repo list, e.g. `CORE`, `EXPERIMENTAL`,  `INCUBATION`, `SUPPORTING` and the like
  - once we have these classified, we will update the branch protection rules (especially those of the core repos) and `CODEOWNERS` list in github

**Comment by lewisdaly** [comment]
also need to add categories to
- [ ] repo description
- [ ] repo labels

**Comment by lewisdaly** [comment]
@elnyry-sam-k updated this in late December. The last thing we need to do is the codeowners and master protection rules for the `core` repos
