### ISSUE TITLE
central-settlement dependency upgrades

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1842]
## **Goal**:
`As a` OSS developer

`I want to` have the latest possible packages on central-settlement
  
`so that` we have security patches applied to repos

**Acceptance Criteria**:
- [ ] upgraded central-settlement packages

**Complexity**: Medium - unknown test failures with new packages

**Uncertainty**: High - integration test runners are a mess

---

**Tasks**:
- [ ] upgrade central-settlement to the latest packages
- [ ] fix integration tests
- [ ] improve integration test runner to make it easier to run

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
@lewisdaly is this still relevant?

**Comment by lewisdaly** [comment]
Closing for now - we can always open it again ;)
