### ISSUE TITLE
TTK OBJ#2 - Add functionality to run test cases for any number of iterations

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1843]
## **Goal**:
`As a` Scheme

`I want to` have a provision to specify a number of iterations
  
`so that` I can run a set of test cases repeatedly for the specified number

**Acceptance Criteria**:

- `Given`
  - [x] That there is a provision to specify number of iterations in the test case execution page
- `When`
  - [x] I specify number of iterations
- `Then`
  - [x] The test case should be executed that many times
  - [x] A report should be generated including the runtime for each iteration and average run time

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Refactor the existing outbound function to disable some push messages and some checks incase of multi iteration execution
- [x] Add a separate backend end point for test case execution in iterations
- [x] Refactor the front-end page for iterations
- [x] Add a new report template for multiple iterations
- [x] Investigate the options to run iterations in parallel
  - [x] Check by executing the iterations in async fashion by storing the promises in an array an wait for all the promises to be resolved at the end
  - [x] In addition to the above, check the performance by increasing UV_THREADPOOL_SIZE in nodejs
  - [x] Check by increasing v8-pool-size
  - [x] Test by increasing the number of SDK and mojaloop services
- [x] Unit tests for the new functionality

**Done**
- [x] Acceptance Criteria pass
- [x] Unit test pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/68
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/113

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @elnyry-sam-k

**Comment by vijayg10** [comment]
Increased the estimate due to additional work on investigation on parallel execution.

**Comment by vijayg10** [comment]
1. When executing test case iterations in parallel using promises, I noticed that the total time for all the iterations got reduced. But each transfer took more time. I think this is because of the single threaded model of nodjs. There may be possibility on bottleneck at callback event listener or any other common component. Observed some iterations are failing (Inconsistency)
2. To make the TTK to execute test cases with high speeds, we need to make it scalable so that we can spin up multiple replicas.
3. Tested the performance by increasing the SDK and mojasims, noticed considerable improvement in total run time.
4. Didn't notice any change when playing with the nodejs configuration like UV_THREADPOOL_SIZE...etc
