### ISSUE TITLE
Helm Release v11.0.0: Updates to helm, Supporting QA, Fixes, Releases

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1851]
## **Goal**:
`As a` ML OSS Code base maintainer

`I want to` validate and make a Helm release in PI-12 (Sprint 12.1) that is successfully validated by the Golden path tests
  
`so that` Community members can take and use a version of Mojaloop Switch services bundle that is tested and contains latest features and enhancements (added in and PI-11 and PI-12 (Sprints 12.1, 12.2) so far)

This specific story is for making necessary changes for supporting Deployment, QA, Fixes, Integration and performing end-to-end testing for all the changes made since Helm v11.0.0

**Acceptance Criteria**:
- [x] Helm RC v11.0.0 is validated on dev2 and iterated until 100% result with postman GoldenPath collection is achieved
- [x] QA (Golden path) on deployments done on AWS dev2 environment is done
- [x] Bugs are logged based on observations, failures
- [x] Bugs logged are fixed if critical to make subsequent releases in individual services (or Helm)
- [x] All the changes needed for supporting v11.0.0 of Helm are done
- [x] Helm v11.0.0 release notes is drafted and published

**Complexity**: Medium - Involves all core and supporting services

**Uncertainty**: Low - No major feature changes, only minor fixes and maintenance changes since previous release

---

**Tasks**:
- [x] _Make releases on all core services to have latest images / versions_ [@mdebarros ] (done during prior attempt, will go ahead with those for this iteration except where critical fixes and updates were made, such as central-ledger)
- [x] Identify changes needed for helm (config / default.json) [@mdebarros ]
- [x] Initial PR with changes for v11.0.0 [@mdebarros ]
  - [x] Initial PR review
  - [x] Deploy, validate, fix issues, redeploy
  - [x] With stable deployment test Golden path
- [x] Identify issues with QA Scripts if any - fix them and retest [@mdebarros ]
- [x] Identify Bugs, log them [@mdebarros ]
- [x] Validate finance portal [@amarmodus ]
- [x] Fix bugs logged if critical
- [x] Deploy, validate on AWS dev2 [@mdebarros ]
- [x] Validate/Document upgrade scenario details (from v10.4.0 --> v11.0.0) [@mdebarros] --> Followed-up in #1759 
- [x] Validate with Legacy Simulator collection
- [x] Validate with Mojaloop Simulator collection
- [x] Release notes for helm v11.0.0 is drafted
- [x] Helm v11.0.0 released
- [x] Deployment of released Helm v11.0.0 on **Dev2**
  - [x] Helm v11.0.0 is deployed on **Dev2** successfully
  - [x] Validation using Golden path regression tests etc on Dev2
    - [x] Legacy Simulator collection
    - [x] Mojaloop Simulator collection
    - [x] TTK Post-hook install
- [x] Deployment of released Helm v11.0.0 on **Dev1**
  - [x] Helm v11.0.0 is deployed on **Dev1** successfully
  - [ ] Validation using Golden path regression tests etc on Dev1
    - [ ] Legacy Simulator collection
    - [x] Mojaloop Simulator collection
    - [x] TTK [@vijayg10 ]

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Postman Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] Helm - https://github.com/mojaloop/helm/pull/401
- [x] Postman - https://github.com/mojaloop/postman/pull/188

## **Follow-up**:
- #1617 

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @mdebarros @elnyry-sam-k

**Comment by mdebarros** [comment]
Known issues have been updated on the release notes: https://github.com/mojaloop/helm/releases/tag/v11.0.0
