### ISSUE TITLE
Remove external dependencies that are tightly integrated into the Mojaloop Helm Chart

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1852]
## **Goal**:
`As a` Mojaloop Deployer

`I want to` remove all external Helm chart dependencies from the Mojaloop Helm chart
  
`so that` deployers are able to manage the external dependencies separately

**Acceptance Criteria**:
- [ ] Helm Charts no longer have external dependencies (Kafka, MySQL, MongoDB, Grafana, etc)
- [ ] Mojaloop Umbrella Helm Charts are deprecated (i.e. Promfana, EFK+APM)
- [ ] Deployment Guide is updated to include:
        - a list of external dependencies as pre-requisites
        - instructions or links provided on how they can be deployed using Helm (or alternatively additional guides on how to use managed servers in AWS, Azure, etc can also be considered)
        - instructions on how to configure Mojaloop charts to use these external deployed dependencies (i.e. Kafka URIs, etc)
- [ ] Update Helm Chart documentation to reflect this change.
- [ ] Updated Deployment Guide instructions are tested by QA

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
#### Refactor existing dependency charts into separate Helm Chart
- [x] MySQL
- [x] Kafka
- [x] MongoDB

##### ML-API-Adapter:
- [ ] MySQL
- [ ] Kafka

##### Central-Ledger:
- [ ] MySQL
- [ ] Kafka

##### Mojaloop-Bulk:
- [ ] MongoDB

##### Account Lookup Service:
- [ ] MySQL

##### Quoting Service:
- [ ] MySQL

##### Central-Event-Processor:
- [ ] MongoDB

##### ML-Testing-Toolkit:
- [ ] MongoDB

##### Time permitting:
- [ ] Upgrade charts to Helm v3
- [ ] Move TTK Post-hook installs to feature Tests

---

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- [x] Design Authority Proposal - https://github.com/mojaloop/design-authority/issues/69
- [x] https://github.com/mojaloop/project/issues/1973

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
After some initial analysis and work by Miguel, decided to take this up after the Helm release for CGS is done.. will take up in PI13
