### ISSUE TITLE
TTK OBJ#1 Add websocket functionality to make payee side assertions using MojaSim

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1860]
## **Goal**:
`As a` individual implementer

`I want to` use SDK/MojaSim's websocket feature from TTK
  
`so that` I can make assertions on payee side faster

**Acceptance Criteria**:
- [x] Websocket related functions should be available to use in TTK scripting to make payee side assertions
- [x] Documentation is provided to use the WS functionality to get the payee side data 

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [x] Add a new module using a websocket client and events to be used from test case scripting
- [x] Refactor the outbound request functionality to integrate the new websocket module
- [x] Add capability to provide the WS URL in the environment file
- [x] Alter a P2P test case to enable payee side assertions using websocket to MojaSim
- [x] Add the new WS related functions in the documentation
- [x] Unit tests

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/115

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
Planning to add functions similar to these

websocket.connect('ws://asdfsdf/as', 'payeeSim')
const request = websocket.get('requests/asdfasf', 'payeeSim', 1000)
websocket.disconnect()
