### ISSUE TITLE
Migrate ml-api-adapter to openapi-backend lib for api swagger validation

### ISSUE THREAD

**Issue by shashi165** [mojaloop/project#1863]
## **Goal**:
`As a` Developer

`I want to` Migrate `ml-api-adapter` to openapi-backend lib for api swagger validation
  
`so that` openapi-backend lib is reused for all swagger api validation 

**Acceptance Criteria**:
- [ ] API swagger validation should be done by `openapi-backend` lib
- [ ]  `GET /documentation` endpoint should work
- [ ]  `GET /swagger.json` endpoint should expose raw JSON

**Complexity**: Medium > This has already been implemented in `account-lookup-service`

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
oudated, but also migration done..
