### ISSUE TITLE
TTK Test cases - Align the setup collection with postman

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1866]
## **Goal**:
`As a` individual implementer

`I want to` have the setup collection in the TTK updated
  
`so that` I can use the postinstall setup hook to setup my newly deployed mojaloop cluster automatically

**Acceptance Criteria**:
- [x] `Given` the mojaloop helm is deployed with TTK postinstall hook
- [x] `When` I run the postman GP collection 
- [x] `Then` it should pass 100% without need to run the postman setup and onboarding collections

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Compare each request in the provisioning collection with postman setup and onboarding collections
- [x] Update if there are any differences
- [x] Test postinstall hook with new deployment on Dev environment and check GP run after that

**Done**
- [x] Acceptance Criteria pass
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/14
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/15

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @mdebarros @elnyry-sam-k

**Comment by vijayg10** [comment]
<img width="1664" alt="Screenshot 2020-11-25 at 4 17 58 PM" src="https://user-images.githubusercontent.com/33152110/100217935-0c8b5a80-2f3a-11eb-8f61-50403247768a.png">
