### ISSUE TITLE
Design for Scheme specified cascaded time-outs

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1867]
## **Goal**:
`As a` Payer FSP
`I want to` be able to establish a specific duration for a transfer after which a transfer can be safely timed-out
`so that` a Payer's funds are not held any longer than necessary and in addition, minimize the need for reconciliation

`As a` Payee FSP
`I want to` know the specific duration after which a transfer will be timed-out at the Switch
`so that` I can aim to process transfers below that time and minimize the need for reconciliation

`As a` Switch
`I want to` know the specific duration after which a transfer will be timed-out and notification sent to the Payer FSP
`so that` I can aim to process transfers below that time and minimize the need for reconciliation

This specific story relates to the design of the above goals

**Acceptance Criteria**:
- [ ] Given a Minimum Payer FSP time-out (duration), when a notification isn't received by a Payer FSP within a specified (valid) time (expressed as duration) then that transfer can be safely timed-out by the Payer FSP
- [ ] Given a Minimum Payer FSP time-out (duration) and a Maximum Payee FSP timeout, when a Fulfil request from the Payee FSP isn't received by the Switch within a specified (valid) time (expressed as duration) then that transfer can be safely timed-out by the Switch and notification(s) sent out
- [ ] A proposal is made to the DA with the designs

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
