### ISSUE TITLE
Replace wildcard endpoints with explicit endpoints in ALS

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1868]
## **Goal**:
`As an` OSS Maintainer

`I want to` replace wildcard endpoints in ALS with explicit endpoints
  
`so that` individual endpoints are explicitly defined and API documentations (swagger) can be more detailed and usable.

**Acceptance Criteria**:
- [x] Wildcard endpoints/routes are replaced with specific endpoints
- [x] API documentation (swagger) endpoints are detailed and usable 

**Complexity**: Medium - Requires familiarity with `OpenAPIBackend` library

**Uncertainty**: Medium - It is not clear if this proposed change is supported by `OpenAPIBackend` library

---

**Tasks**:
- [x] Replace all wildcard endpoints with explicit endpoints with relevant description
- [x] Ensure changes cascade down to `/documentation` and `/swagger.json` endpoints

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/account-lookup-service/pull/376

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
