### ISSUE TITLE
Design for reliable notifications on finalization of a transfer

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1869]
## **Goal**:
`As an` FSP

`I want to` reliably receive a notification upon finalization of a transfer (COMMITTED or ABORTED)
  
`so that` I can make an informed decision about a end-user's funds

Note: This is primarily for a Payer FSP to ensure that a "Payer FSP always receives. a notification"

**Acceptance Criteria**:
- [x] Designs for reliable notifications are done (SDs) and reviewed by team
- [x] Above designs submitted to DA for review
- [ ] DA decision requested on implementation (dependency on Reference Architecture Stream)

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [x] Document requirements
- [x] Design High-level Architecture overview
- [x] Design Sequence-diagrams
- [x] Define Message Examples
- [x] Initial review with Core-Team
- [x] Incorporate Core-Team comments
- [x] Initial review with DA
- [x] Incorporate DA comments
- [x] Define Data Schemas
- [x] Define API Specifications
- [ ] Final review with DA
- [ ] Incorporate Final DA comments

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs Documentations
- [ ] Approval from DA for Design

## **Pull Requests**:
- [ ] https://github.com/mojaloop/documentation/pull/288

## **Follow-up**:
- N/A

**Dependencies**:
- [ ] https://github.com/mojaloop/design-authority/issues/74

## **Accountability**:
- Owner: @mdebarros
- QA/Review: Design Authroity

**Comment by mdebarros** [comment]
Closing design.

Any changes at this stage are from the reference architecture stream.
