### ISSUE TITLE
PISP Support - FIDO Security in IOS Devices (Keystore)

### ISSUE THREAD

**Issue by rasputtintin** [mojaloop/project#1870]
## **Goal**:
`As a` OSS security officer

`I want to` investigate FIDO private key security controls specific to mobile operating systems (IOS Only)
  
`so that` I can make recommendations to the PISP team to enhance security of the PISP linking and transaction process.

**Acceptance Criteria**:
- [ ] Identify details of IOS FIDO private key storage
- [ ] Identify details of ISO FIDO private key storage
- [ ] Identify possible risks affecting FIDO private key storage in IOS devices and communicate to PISP team

**Complexity**: <Medium> This is because it requires an indepth understanding of Android and IOS secure keystore and possible vulnerabilities of each.

**Uncertainty**: <Medium> > Possible lack of detailed information on investigation items.

---

**Tasks**:
- [ ] Investigate Android secure keystore [ @rasputtintin  ]
- [ ] Document standard on Android secure keystore use for storing PISP FIDO private key [ @rasputtintin  ]
- [ ] Discuss findings with PISP team [ @rasputtintin  ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rasputtintin 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
@rasputtintin Please update this issue with your progress on weekly basis.
