### ISSUE TITLE
CQS Test Lab - Document Requirements for Lab Environment

### ISSUE THREAD

**Issue by rasputtintin** [mojaloop/project#1871]
## **Goal**:
As a OSS CQS Workstream Contributor

I want to document the requirements for a CQS security test lab

so that I can test security configurations within Mojaloop configurations to assure the OSS team of the environmental security and compliance status to best practices.

Acceptance Criteria:
**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <Medium> > A short comment to remind the reason for the rating

**Uncertainty**: <Medium> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Document and share requirements with Infra [ @rasputtintin  ]
- [ ] Review created environment to ensure all components are in place. 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by godfreykutumela** [comment]
@rasputtintin and @bukasaaime please advance this issue and let's aim to close by Friday so that we can start next week with the lab build.

**Comment by rasputtintin** [comment]
Shared requirements with Miguel for his feedback. Overall intention is to explore hands on some of the best practice recommendations documented thus far and see impact in a running environment e.g. Enabling audit logging, encryption at service level etc.

[OSS PI 12 - Environment.xlsx](https://github.com/mojaloop/project/files/5650459/OSS.PI.12.-.Environment.xlsx)
