### ISSUE TITLE
Notifications paticipant metadata projection

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#1872]
## **Goal**:
`As a` developer of the notifications

`I want to` update my local participant metadata read-only store from participant's aggregate state events (and keep it updated)
  
`so that` I'm able to use participant metadata information, namely endpoints, with sync calls

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Create an event handler to update the local store from participants state events [ @? ]
- [ ] Create a repository for the notification cmd side that reads from the local participant store   [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
