### ISSUE TITLE
Notfications base structure

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#1873]
## **Goal**:
`As a` developer

`I want to` create the notifications services with the same strcuture as the rest of the PoC's architecture
  
`so that` I can apply the same patterns and principles, have the same scalability benefits and be consistent

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Design the notification aggregate, entities and data structures [ @? ]
- [ ] Create command handler [ @? ]
- [ ] Create event handler [ @? ]
- [ ] Create tech notification adapter mechanism (for now http, future support for websockets) [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
