### ISSUE TITLE
Participant snapshot operator service

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#1874]
## **Goal**:
`As a` developer

`I want to` have a service that sends snapshot commands to the participant cmd handler
  
`so that` we always have up-to-date snapshots of participants' data on the persisted kafka topic for snapshots (at a max of X minutes or X state events processed)

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Create the new service that sends the snapshot cmds [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
@pedrosousabarreto , @mdebarros can we close this one out?

As the Ref Arch workstream is progressing, I'm thinking you'll prefer a fresh start rather than repurposing existing issues.. In any case, please take care of these open issues (this and others with the oss-perf label)
