### ISSUE TITLE
As a contributor/developer can we minimize the number of repos

### ISSUE THREAD

**Issue by kjw000** [mojaloop/project#1879]
## **Goal**:
As a contributor/developer can we minimize the number of repos so it is easier to understand the core components of the hub

`I want to` develop a plan to lessen the number of repos
  
`so that` the mojaloop project is easier to maintain and deploy.

**Acceptance Criteria**:
- [ ] the number of repos is consolidated for deployment/distribution

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by kjw000** [comment]
Added this issue for comments/thoughts.  thanks!

**Comment by lewisdaly** [comment]
Thanks @kjw000 - this came up in conversation the other day with @adrianhopebailie. One approach worth exploring is moving all "core" repos into one monorepo. 

That would allow us to be able to say "You want to develop mojaloop, clone this one repo and off you go"

**Comment by elnyry-sam-k** [comment]
Hmm, if we're moving towards automated releases and conventional commits and even for general contributions, not sure if its ideal to have all services in the same repo.. but definitely something to discuss..

**Comment by adrianhopebailie** [comment]
At a minimum it would be great to be able to map each block in this diagram to a repo:

![architecture](https://docs.mojaloop.io/documentation/mojaloop-technical-overview/assets/diagrams/architecture/Arch-Mojaloop-end-to-end-simple.svg "Mojaloop Architecture")

**Comment by elnyry-sam-k** [comment]
Good point @adrianhopebailie - lets follow it up

**Comment by lewisdaly** [comment]
Perhaps this is worth a further discussion with the DA. I think @pedrosousabarreto was going to do some looking into this as well.

Despite the management overhead, I'm thinking more and more we should have a `mojaloop-community` github org where we can put all of the half-baked repos or things that are being refined and aren't yet ready (or maybe never will be) a part of the `mojaloop` github org.

On an automation note, Kubernetes built a tool for managing github orgs using git ops: https://github.com/kubernetes/org which may be of interest.

**Comment by lewisdaly** [comment]
I think this conversation will also be heavily influenced by the ongoing reference architecture discussion. I'm going to mark this as blocked until we have produced a reference arch.

**Comment by elnyry-sam-k** [comment]
Or close it for the current iteration, marking the completion of this phase and then reopen when the new architecture, direction is finalized?

**Comment by godfreykutumela** [comment]
@elnyry-sam-k If we close it we risk forgetting it so let's leave open until the third sprint.

**Comment by pedrosousabarreto** [comment]
I'm working on a proposal for this and I will require your collaboration once it is in a decent enough state to share. It's not my main priority though, so it's taking longer than expected. Probably another week or two.

**Comment by pedrosousabarreto** [comment]
A draft version of the proposal document was shared with the security team for review.

**Comment by godfreykutumela** [comment]
Hi @pedrosousabarreto please upload the proposal here as well.

**Comment by pedrosousabarreto** [comment]
Here it is, needs https://docs.google.com/document/d/1AZbX0UjraytFty0IWOHpyR6z35bh0-MCFG1vGKId_5M/edit#

**Comment by godfreykutumela** [comment]
Additional guidelines
[10_GitHub_Security_Best_Practices_cheat_sheet.pdf](https://github.com/mojaloop/project/files/6323775/10_GitHub_Security_Best_Practices_cheat_sheet.pdf)
 from snyk
