### ISSUE TITLE
Meaningful Documentation End-point for Micro-services

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1885]
## **Goal**:
`As a` Developer

`I want` access to meaningful-documented API end-points that are generated from the swagger for each micro-service
  
`so that` the documentation information is populated directly from the swagger (and not code).

**Acceptance Criteria**:
- [x] `/documentation` end-point provides meaningful API documentation based on the micro-service interface swagger specification
- [x] `/swagger.json` is available, and is provided by the interface specification (not generated from code)
- Services
    - [x] Account-lookup
     - [x] Quoting-Service
     - [x] Central-Ledger (Admin API)
     - [x] Central-Settlements
     - ~ML-API-Adapter~

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Investigate alternatives to `hapi-swagger` (Shins, Widdershins, ReDoc, ReSlate) [@oderayi ]
- [x] Present results to team and select best alternative [@oderayi] 
- [x] Implement adopted libraries (Widdershins, Shins) as Hapi plugin in Central Services Shared [@oderayi] 
- [x] Implement plugin in the following services:
     - [x] Quoting-Service [@oderayi] 
     - [x] Central-Ledger (Admin API) [@oderayi]
     - [x] Central-Settlements [@oderayi] 
     - ~ML-API-Adapter~ [@oderayi] 
     - [x] Account-Lookup [@oderayi] 

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-shared/pull/263
- [x] https://github.com/mojaloop/central-services-shared/pull/264
- [x] https://github.com/mojaloop/quoting-service/pull/250
- [x] https://github.com/mojaloop/central-settlement/pull/330
- [x] https://github.com/mojaloop/central-ledger/pull/798
- [x] https://github.com/mojaloop/central-services-shared/pull/267
- [x] https://github.com/mojaloop/account-lookup-service/pull/379

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
