### ISSUE TITLE
TTK - Deployment in Dev environment should be separated

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1889]
## **Goal**:
`As a` individual implementer

`I want to` setup the testing toolkit properly in two dev environments
  
`so that` I can use TTK to test dev1 and dev2 individually

**Acceptance Criteria**:
- [x] TTK should be available in both DEV1 and DEV2 using separate URLs and endpoints
- [x] The default installation should deploy TTK automatically

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Redeploy Dev1 with the existing values file and check whether TTK is deployed automatically or not
- [x] Configure the dev1 and dev2 values files with proper ingress URLs
- [x] Remove common testing toolkit deployment
- [x] Update Dev1 cron file and re-deploy the cronjob according to new setup
- [x] Update the TTK versions in helm chart

**Done**
- [x] Acceptance Criteria pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/402

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @elnyry-sam-k @mdebarros
