### ISSUE TITLE
Standardize Admin API and enhance documentation

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1890]
## **Goal**:
`As` a Hub Operator

`I want to` have API definition for the Admin API
  
`so that` easily understand the Admin API and use it as reference for using the API

**Acceptance Criteria**:
- [x] An API Definition doc for Admin API is drafted and submitted for review by the Admin API SIG, CCB

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Finalize swagger to use as reference
- [x] Fix, identify any initial issues
- [x] Draft initial API definition and submit for review
- [x] Address review feedback and standardize the Admin API & and API Definition doc
- [ ] ~Create stories to refactor underlying services based on Admin API changes~

**Done**
- [x] Acceptance Criteria pass
- [x] Document Style & patterns meets standards
- [x] Admin API definition doc is published

## **Pull Requests**:
- [x] https://github.com/mojaloop/mojaloop-specification/pull/86

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vandaillyes-modusbox , @mdebarros , @elnyry-sam-k 
- QA/Review: CCB, Admin API SIG

**Comment by elnyry-sam-k** [comment]
Tracking story..

**Comment by elnyry-sam-k** [comment]
PR https://github.com/mojaloop/mojaloop-specification/pull/86 is finally merged!

Thank you @vandaillyes-modusbox , @mdebarros
