### ISSUE TITLE
implement GET and PUT /parties/{type}/{id}/{subId} in simulator

### ISSUE THREAD

**Issue by shashi165** [mojaloop/project#1892]
## **Goal**:
`As a` implementor

`I want to` implement GET and PUT /parties/{type}/{id}/{subId} in simulator
  
`so that` I can use add/modify/delete details of party based on the subID

**Acceptance Criteria**:
- [ ] `Given` that there is a provision to add / edit / delete subIDs through the endpoints('POST /repository/parties') in the test-api
- [ ] `When` I send a request 'GET /parties/{Type}/{ID}/{SubID}' to mojaloop-simulator
- [ ] `Then` I should get a proper response with the information about that SubID

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Add the endpoints in `test-api`
  - [x] /repository/parties/{idType}/{idValue}/{subIdValue} (GET)
  - [x] /repository/parties/{idType}/{idValue}/{subIdValue} (PUT)
  - [x] /repository/parties/{idType}/{idValue}/{subIdValue} (DELETE)
  - [x] /repository/parties (POST) - Include subIdValue
- [x] Add the endpoints in `simulator`
  - [x] /participants/{idType}/{idValue}/{subIdValue} (GET)
  - [x] /parties/{idType}/{idValue}/{subIdValue} (GET)

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/mojaloop-simulator/pull/85

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
