### ISSUE TITLE
TTK - Review the documentation for PI14

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1893]
## **Goal**:
`As a` an individual implementer

`I want to` have the documentation for the APIs provisioned in TTK with code samples
  
`so that` I can copy the code and use with my own tools to set requests to TTK

**Acceptance Criteria**:
- [ ] Documentation should be updated with the new features

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] Review the documentation
- [ ] Add if any functionality is missing
- [ ] Add documentation about the helm chart deployments in the TTK repo

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
To be covered in #2409
