### ISSUE TITLE
TTK OBJ#1 - TTK test suites for transfer positive scenarios

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1894]
## **Goal**:
`As a` hub operator
`I want to` have all the test suites from the GP collection in TTK
`so that` I can use them to validate my Switch deployment (or implementation)

`As a` hub operator
`I want to` have all the test suites from the GP collection in TTK
`so that` I can use TTK for my day-to-day test runs

**_This story covers all the positive transfer scenarios_**

**Acceptance Criteria**:
- [x] `Given` a mojaloop deployment
        `When` TTK test suites for transfer positive scenarios are run
        `Then` we get 100% pass-rate and observe no regression failures

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Create the TTK tests in testing-toolkit-test-cases for all the positive scenarios in GP postman collection
  - [x] feature-tests
    - [x] p2p
    - [x] post-transfer [@oderayi] 
        - [x]  Positive Scenarios [@oderayi] 
        - [x] Reserve Notifictaions [@oderayi]
    - [x] block-transfer [@oderayi] 
    - [x] get-transfers
- [x] Execute the tests against Dev1
- ~Execute the tests against Dev2~
- ~Execute the tests against Local Deployment~

**Done**
- [ ] Acceptance Criteria pass
- [ ] TTK Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] https://github.com/mojaloop/testing-toolkit-test-cases/pull/18

## **Follow-up**:
- Issues/bugs:
   - Mojaloop Simulator Setup scripts use same MSISDN for registering all parties cause JWS validation errors in TTK tests 

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
