### ISSUE TITLE
TTK OBJ#1 - TTK test suites for settlements

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1896]
## **Goal**:
`As a` hub operator
`I want to` have all the test suites from the GP collection in TTK
`so that` I can use them to validate my Switch deployment (or implementation)

`As a` hub operator
`I want to` have all the test suites from the GP collection in TTK
`so that` I can use TTK for my day-to-day test runs

**_This story covers all the settlements_**

**Acceptance Criteria**:
- [x] `Given` a mojaloop deployment
        `When` TTK test suites for settlements are run
        `Then` we get 100% passrate and observe no regression failures

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Create the TTK tests in testing-toolkit-test-cases for all the negative scenarios in GP postman collection
  - [x] feature-tests
    - [x] funds-in
    - [x] funds-out
    - [x] settlements-management
- [x] Execute the tests against Dev1
- [x] Execute the tests against Dev2
- [x] Execute the tests against Local Deployment

**Done**
- [x] Acceptance Criteria pass
- [x] TTK Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by modusemerson** [comment]
Im currently working on this item
