### ISSUE TITLE
TTK OBJ#1 - TTK test suites for quotes, ALS and transaction requests service

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1897]
## **Goal**:
`As a` hub operator
`I want to` have all the test suites from the GP collection in TTK
`so that` I can use them to validate my Switch deployment (or implementation)

`As a` hub operator
`I want to` have all the test suites from the GP collection in TTK
`so that` I can use TTK for my day-to-day test runs

**_This story covers all the quotes, ALS and transaction requests service_**

**Acceptance Criteria**:
- [x] `Given` a mojaloop deployment
        `When` TTK test suites for quotes, ALS and transaction requests service are run
        `Then` we get 100% passrate and observe no regression failures

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Create the TTK tests in testing-toolkit-test-cases for all the quotes, ALS and transaction requests service in GP postman collection
  - [x] api-tests
  - [x] Transaction requests service
  - [x] Quoting service
  - [x] Bug fixes
  - [x] On-US transfer
- [x] Execute the tests against Dev1

**Done**
- [x] Acceptance Criteria pass
- [x] TTK Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/22
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/24

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by modusemerson** [comment]
I think I have completed this one, but @vijayg10  
can you confirm if the latest file I shared with  you covers this ticket?
