### ISSUE TITLE
2.3.3.1 Design and refactor the Transfers table and associated DAO

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#19]
**Goal**:
As a developer I would like to
_design and refactor the Transfers table and associated Micro-Service_
in order to expand the data and ensure that the functionality is catered for.

**Tasks**:
- [ ] Assess the need to change current transfer functionality
- [ ] Retro-fit database technology of choice as required

**Acceptance Criteria**:
- [ ] The transfer process works as intended

**Dependencies**:
- [ ] #151 

**Accountability**
- Owner
- Review

**Comment by NicoDuvenage** [comment]
This story has been completed by applying the changes as required but will be moved to the "blocked" pipeline. We will not implement these changes yet until a design session provides outcome on the inevitable data model changes required as a result of the fact that we are planning to re-align to a new API specification.

**Comment by elnyry** [comment]
Decided to add this as a task in story #205 as this is not big enough to be a story by itself
