### ISSUE TITLE
Refactor Unit tests for DB & Kafka PoCs

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#190]
**Goal**:
As a developer I would like to _refactor Unit tests_ so that they can run with same pass rate as before (the changes were made based on DB & Kafka PoCs).

**Tasks**:
- [ ] Refactor Unit tests so that they pass

**Acceptance Criteria**:
- [ ] Unit tests pass after changes for DB & Kafka PoCs are made.

**Dependencies**:
- [ ] DB & Kafka PoCs are both integrated and builds available.

**Comment by elnyry** [comment]
This was the initial plan but later the team decided to go with a different strategy - to add unit, functional and integration tests as relevant during development phase of that particular feature, etc itself
