### ISSUE TITLE
Security Review December

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1901]
**Tasks**:
- [ ] review dependabot alerts
- [ ] merge in existing PRS
- [ ] create new prs for fixes where applicable
- [ ] created any follow up tickets where applicable

- apply to the following repos (as identified by dependabot):
   - [x] central-services-metrics
   - [x] als
   - [x] event-sdk
   - [x] central-services-health
   - [x] central-services-logger
   - [x] settlement-management
   - [x] operator settlement
   - [x] finance-portal-lib
   - [x] oracle-shared-library

Note:
- `finance-portal-lib` is still in snapshot status, so I removed the security alerts for this repo

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/settlement-management/pull/19
- [x] https://github.com/mojaloop/operator-settlement/pull/17
- [x] https://github.com/mojaloop/oracle-shared-library/pull/11

## **Follow-up**:
- [ ] operator-settlement uses a vulnerable version of `hapi`, and needs to be updated to`@hapi/hapi@20`. There aren't enough tests to verify such a large dependency change (mojaloop/project#1905)
- 

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
