### ISSUE TITLE
Explore what we can leverage from the Open Source Security Foundation (OpenSSF)

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1902]
## **Goal**:
`As a` OSS developer 

`I want to` investigate and explore how best Mojaloop could leverage from the OpenSSF work
  
`so that` I can align our Mojaloop with industry's best practices.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] Review https://github.com/ossf [ @godfreykutumela ]
- [ ] https://openssf.org/ [ @godfreykutumela ]

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela
