### ISSUE TITLE
Merging CGS feature to master branches

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1904]
## **Goal**:
`As a`Mojaloop Scheme
`I want to` support Continuous Gross Settlement (CGS) model / feature
`so that` Mojaloop Schemes that need to support CGS can start using it

**Acceptance Criteria**:
- [x] The CGS feature related branches on blow repos are merged into master branches without issues and releases made
  - [x] central-ledger
  - [x] central-settlement
  - [ ] ~documentation~

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [x] Merged CGS PR on central-ledger master in feature branch
- [x] Merged CGS PR on central-settlement master in feature branch
- [ ] Merged CGS PR on documentation repo
- [ ] Validate tests on the features before releases are made
  - [x] build docker images of central-ledger and central-settlement in own repo to be able to use docker-compose locally for tests
  - [ ] ~get postman scripts used by TIPS team and set environment for local use~ _partial success on that one. we went for deployment instead_
  - [x] deploy on dev environment
  - [x] run TIPS collections on the deployed environment and fix whatever errors come out
    - [x] decide on how the ledger account types would be set up - through admin API or configuration (API is more in sync with the current practices) add the ledger account types in helm or Switch onboarding collection
  - [x] Test DEFERREDNET settlement model with Golden path - _settlement API v2 is not working_
- [x] document and create stories for the issues found across the the services 
  - [x] central-ledger ADDED FOLLOW UP STORY: #1944 
    - [x] empty config for ADDITIONAL_PARTICIPANT_LEDGER_ACCOUNT_TYPES and SETTLEMENT_MODELS are breaking the service - __needs production ready fix__
    - [x] ~FundsIn is DECREASING the position of payer - needs verification with current version~ correct behavior
    - [x] Transfer is rejected with 'Not enough liquidity' in position because of transferState != RESERVED, instead its state is RECEIVED_PREPARE __this was due to bad onboarding postman collections__
    - [ ] ~add REST API to add INTERCHANGE_FEE_SETTLEMENT and INTERCHANGE_FEE account types for each participant~ 
  - [x] central-settlement ADDED FOLLOW UP STORY: #1945
    ~- [ ] add the _scripts_ folder to be accessible from rancher like the rules in sdk-scheme-adapter deployment AND/OR~
    - [ ] ~add __SCRIPTS_FOLDER__ to env configuration~
    - [ ] ~add an option to run API and only one handler from config now its either api or both handler~
    - [ ] ~find out why settlement in DEFERREDNET mode, with Settlement API v2 is not working for Golden Path~
    - [ ] ~helm charts~
      - [ ] ~add wait-for-kafka on helm chart for central-settlement~
      - [ ] ~add a check for settlement model to decide should the handler be deployed or not, probably it would be easier to be well documented in the service and the check whether the handler should be deployed or not~
  - [ ] ~Optimize Dockerfile's for both services to reduce the layers~
- [ ] ~Release on all related repos made with the feature~

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- 

**Dependencies**:
- https://github.com/mojaloop/project/issues/1944
- https://github.com/mojaloop/project/issues/1945

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Follow-up: https://github.com/mojaloop/project/issues/2027
