### ISSUE TITLE
[design] - update existing sequence diagrams to match v0.1 of the API Draft

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1922]
## **Goal**:
`As a` developer

`I want to` have up to date sequence diagrams
  
`so that` I can write correct code

**Acceptance Criteria**:
- [ ] linking and transfer sequence diagrams are up to date (see: https://github.com/mojaloop/mojaloop-specification/issues/70) and [here](https://github.com/mojaloop/mojaloop-specification/files/5538077/Draft.PISP.Specification.Changes.docx)

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] update linking sequence diagrams to line up with v0.1 of the Draft Thirdparty API Spec
- [ ] update transfer sequence diagrams to line up with v0.1 of the Draft Thirdparty API Spec
- [ ] update unlinking sequence diagrams in line with draft thirdparty api spec

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date

## **Pull Requests**:
- [ ] https://github.com/mojaloop/pisp/pull/114

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: @eoln @kleyow

**Comment by lewisdaly** [comment]
I had already started this task for the account linking, and I ran into the following problems:

- v0.1 of the Thirdparty API Draft is missing `POST /consents/{id}/generateChallenge` @MichaelJBRichards what was the proposed method for the PISP to obtain the challenge for account linking? Or is there something I'm missing here?

**Comment by lewisdaly** [comment]
I spoke with Michael before the holidays, and we have more guidance on this one. I'm currently in the process of updating the sequences to match, but there will be a little back and forth with the api draft.

**Comment by lewisdaly** [comment]
todo - unlinking sequence diagrams
