### ISSUE TITLE
make a common DTO defs a part of `api-snippets`

### ISSUE THREAD

**Issue by eoln** [mojaloop/project#1923]
## **Common TypeScript types/interfaces**:
`As a` OSSDev

`I want to` have OpenAPI `api-snippets` and TypeScript DTO ([Data Transfer Objects](https://en.wikipedia.org/wiki/Data_transfer_object)) in sync
  
`so that` there is one common place to use and maintain DTO Specification

**Acceptance Criteria**:
- [x] Some request/response DTO specified in `api-snippets` are having their TypeScript representations (we want to find a pattern to use in #1927)
- [x] DTO hierarchy should reflect `api-snippets` hierarchy so import/usage of TS definitions should be very similar to `api-snippets` based interface specification experience
- [x] prepare a few definitions and get experience which will be used in autogeneration story [1927](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/1927)
- [x] document structure and way of using new TS interfaces

**Complexity**: <Medium> > There is a big set with a lot of small definitions, keeping consistency and transparency is a clue, autogeneration from one source of truth could be a challenge

**Uncertainty**: <Low> > yaml -> ts mapping is quite simple, there shouldn't be surprises

---

**Tasks**:
- [x] make a common DTO defs or part of `api-snippets` - folder structure
- [x] identify common patterns and prepare few definitions to get experience for autogeneration
- [x] update documention

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] https://github.com/mojaloop/api-snippets/pull/41

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
