### ISSUE TITLE
autogeneration of TS types files from openAPI yaml snippets

### ISSUE THREAD

**Issue by eoln** [mojaloop/project#1927]
## **Common TypeScript types/interfaces**:
`As a` OSSDev

`I want to` have TypeScript DTO ([Data Transfer Objects](https://en.wikipedia.org/wiki/Data_transfer_object)) autogenerated from OpenAPI yaml in sync
  
`so that` there is one common place to use and maintain DTO Specification

**Acceptance Criteria**:
- [x] autogenerate cli deps & commands
- [ ] proper license in TS files are present
- [ ] documentation how-to generate TS files

**Complexity**: <Medium> > There is a big set with a lot of small definitions, keeping consistency and transparency is a clue, autogeneration from one source of truth could be a challenge

**Uncertainty**: <Low> > yaml -> ts mapping is quite simple, there shouldn't be surprises

---

**Tasks**:
- [x] autogeneration of TS type files from `api-snippets`, maybe use on of these or find another:  
  - https://github.com/drwpow/openapi-typescript
  - https://www.npmjs.com/package/dtsgenerator
  - https://github.com/quicktype/quicktype
- [ ] update documentation

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
