### ISSUE TITLE
testing of Typescript DTO types in api-snippets

### ISSUE THREAD

**Issue by eoln** [mojaloop/project#1928]
## **Common TypeScript types/interfaces**:
`As a` OSSDev

`I want to` have TypeScript DTO ([Data Transfer Objects](https://en.wikipedia.org/wiki/Data_transfer_object)) types well tested
  
`so that` there is one common place to use and maintain DTO Specification

**Acceptance Criteria**:
- [ ] syntax of TS files should be testable to ensure well working imports of DTOs
  - [x] v1_0
  - [x] v1_1
  - [ ] thirdparty 
- [ ] documentation of how to run tests

**Complexity**: <Medium> > There is a big set with a lot of small definitions, keeping consistency and transparency is a clue, autogeneration from one source of truth could be a challenge

**Uncertainty**: <Low> > yaml -> ts mapping is quite simple, there shouldn't be surprises

---

**Tasks**:
- [x] unit tests for types files, maybe use this or find another: https://github.com/ai/check-dts 
- [ ] docs

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
