### ISSUE TITLE
[design] - account linking failure scenario sequence diagrams

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1929]
## **Goal**:
`As an` OSS Dev

`I want to` have sequence diagrams for the account linking failure scenarios
  
`so that` I can implement the error handling

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Medium
**Uncertainty**: Low

---

**Tasks**:
- [ ] Go over the failure scenarios defined in the [Error Codes](https://github.com/mojaloop/pisp/blob/master/docs/error_codes.md) document
- [ ] in the [Linking](https://github.com/mojaloop/pisp/tree/master/docs/linking) document, add a new section called "failure scenarios"
- [ ] to the above section, describe the account linking failure scenarios, and include sequence diagrams which show what API calls will be expected between a PISP, Switch, and DFSP

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @lewisdaly @MichaelJBRichards @jgeewax

**Comment by lewisdaly** [comment]
Closing in favour of our more "vertical" approach to slicing stories
