### ISSUE TITLE
2.3.7 Deploy mule services for Mojaloop switch into K8s test cluster - [13]

### ISSUE THREAD

**Issue by ksatya77** [mojaloop/project#193]
**Goal**:
As a developer
_I would like to deploy the existing mule services into k8s aws test cluster_
so that the endpoints for participants, parties, quotes are serviced

**Tasks**:
- [x] Deploy interop-account-lookup (for 2.2), interop-switch, interop-routing as docker containers
- [x] User lookup, quotes work from dfsp1 -> dfsp2 and dfsp2 -> dfsp1
- [x] Update the test harness to test parties, participants and quotes end points separately @sri-miriyala 
- [x] Add helm charts
- [x] Deploy these services onto the k8s cluster

**Acceptance Criteria**:
- [x] participants calls work as expected
- [x] parties and quotes calls work as expected
- [x] quotes calls work as expected
- [x] Mule services that provide for participants are deployed onto k8s
- [x] Mule services that provide for parties are deployed onto k8s
- [x] Mule services that provide for quotes are deployed onto k8s
- [x] Participants end-point is tested separately using the test harness
- [x] Parties end-point is tested separately using the test harness
- [x] Quotes end-point is tested separately using the test harness

**Dependencies**:
- [x] #263

**Accountability**
- Owner @ksatya77 
- Review @ksatya77

**Comment by elnyry** [comment]
Bug logged here: https://github.com/mojaloop/project/issues/263

**Comment by elnyry** [comment]
As per Murthy's comments, this is mostly done but the testing of endpoints is blocked because of the bug logged above. Moving to blocked and this can be closed once that bug is resolved.
