### ISSUE TITLE
linting of TypeScript DTO in api-snippets

### ISSUE THREAD

**Issue by eoln** [mojaloop/project#1931]
## **Common TypeScript types/interfaces**:
`As a` OSSDev

`I want to` have TypeScript DTO ([Data Transfer Objects](https://en.wikipedia.org/wiki/Data_transfer_object)) types well linted
  
`so that` the code format is standarised

**Acceptance Criteria**:
- [ ] linting TS files should be enforced at pre-commit hook and there should be cli command to do it at wish

**Complexity**: <Medium> > There is a big set with a lot of small definitions, keeping consistency and transparency is a clue, autogeneration from one source of truth could be a challenge

**Uncertainty**: <Low> > yaml -> ts mapping is quite simple, there shouldn't be surprises

---

**Tasks**:
- [ ] linting 
- [ ] pre commit hook
- [ ] doc about TS linting

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
