### ISSUE TITLE
CI/CD publication pipeline for Typescript DTO in api-snippets

### ISSUE THREAD

**Issue by eoln** [mojaloop/project#1932]
## **Common TypeScript types/interfaces**:
`As a` OSSDev

`I want to` have OpenAPI `api-snippets` and TypeScript DTO ([Data Transfer Objects](https://en.wikipedia.org/wiki/Data_transfer_object)) in sync 
  
`so that` CI/CD is always publishing fresh and synced version

**Acceptance Criteria**:
- [ ] CI/CD pipeline for linting, testing and npm module publication

**Complexity**: <Medium> > There is a big set with a lot of small definitions, keeping consistency and transparency is a clue, autogeneration from one source of truth could be a challenge

**Uncertainty**: <Low> > yaml -> ts mapping is quite simple, there shouldn't be surprises

---

**Tasks**:
- [ ] update CI/CD pipeline
- [ ] document CI/CD howto

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
