### ISSUE TITLE
[consent-oracle] - investigate existing als-oracle-template

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1933]
## **Goal**:
`As an` OSS dev

`I want to` investigate the existing [als-oracle-template](https://github.com/mojaloop/als-oracle-template)
  
`so that` we can build a new Consent oracle

**Acceptance Criteria**:
- [x] updated template if required
- [x] follow up tickets ready for next steps with the Consent oracle

**Complexity**: Low - Oracles don't really do that much, we have other examples

**Uncertainty**: High

---

For account linking, we need to make a new oracle for the `CONSENT` type. We have an existing oracle template, which we can use to help build this.

**Tasks**:
- [x] investigate [als-oracle-template](https://github.com/mojaloop/als-oracle-template) will it suit our needs?
- [x] update the template and documentation if required
  > Sam: there is some docs somewhere... will require some digging

**Notes**:
- ALS oracle template: https://github.com/mojaloop/als-oracle-template
- https://docs.mojaloop.io/documentation/mojaloop-technical-overview/account-lookup-service/#12-als-oracle
- https://docs.mojaloop.io/documentation/mojaloop-technical-overview/account-lookup-service/#4-als-admin-design
- https://github.com/mojaloop/documentation/tree/master/mojaloop-technical-overview/account-lookup-service/assets/diagrams/sequence (7.3.1 - 7.3.4)

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
