### ISSUE TITLE
TTK - Ability to execute testsuites against switch over mTLS connection

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1935]
## **Goal**:
`As a` hub implementer

`I want to` deploy TTK outside my cluster with mTLS
  
`so that` I can test my implementation using TTK test suites

**Acceptance Criteria**:
- [ ] TTK can be deployed in a separate environment than mojaloop switch and can be configured mTLS settings to communicate with mojaloop switch behind an API gateway

**Complexity**: High

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
This issue is blocked because MCM client is not donated to opensource yet. We are planning to use MCM client for establishing secure mTLS connection to mojaloop switch behind an API gateway.

**Comment by vijayg10** [comment]
This is a duplicated story #2098
