### ISSUE TITLE
TTK - OBJ#1 Add functions related to JWS signing and validation in javascript engine

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1936]
## **Goal**:
`As a` individual implementer

`I want to` use JWS signing and validation functions in the test case scripting
  
`so that` I can make assertions on FSP-signature

**Acceptance Criteria**:
- [x] JWS sign and validate functions should be available in javascript engine of test cases

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Add `atob` function to javascript
- [x] Implement a wrapper function for JWS signing using a key from pre-request script using the existing signing functions from sdk-standard-library
- [x] Implement a wrapper function for JWS validation using public certificate from post-request script using the existing signing functions from sdk-standard-library
- [x] Add a function to validate only protected headers
- [x] Unit tests
- [x] Documentation

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/122

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @oderayi @elnyry-sam-k
