### ISSUE TITLE
Split Event-SDK on two libraries - tracing and logging

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1938]
## **Goal**:
`As a` Core developer

`I want to` split the Event-SDK to two libraries - one for creating and passing trace context and one for logging and recording different levels of logging and tracing messages to side car.
  
`so that` it is possible to use only the tracing capabilities into non-core services and apps and DFSPs implementations 

**Acceptance Criteria**:
- [ ] Published tracing library that supports: creation of new trace, adding child span, export and import of trace context into messages and HTTP requests, adding different tags
- [ ] Refactored Event-SDK that uses the new library
- [ ] Both are well documented and meets all community standards

**Complexity**: <Medium> Might be slightly different to just cut code out and paste it in new project

**Uncertainty**: <Low> I it is clear what has to be done to cover acceptance criteria

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
