### ISSUE TITLE
[docker-local] Build updated pisp images and integrate into docker-local setup

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#1940]
## **Goal**:
`As a` OSS dev
I want to make sure the PISP feature branches are updated, built, integrated and tested.
`so that` we are working on fresh code

**Acceptance Criteria**:
- [x] pisp images built
- [x] passing e2e tests on pisp repo

**Complexity**: Low 

**Uncertainty**: High - a lot of tests may break

---

**Tasks**:
- [x] build the pisp feature branches:
   - [x] sdk-scheme-adapter
   - [x] ml-api-adapter - or remove if not needed
   - [x] central-ledger - or remove if not needed
   - [x] transaction-requests-service
   - [x] account-lookup-service
   - [x] mojaloop-simulator
- [x] releases for the above, and update docker-compose in `pisp/docker-local`
- [x] update outdated config files for `pisp/docker-local`
- [x] fix e2e tests in docker-local

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
