### ISSUE TITLE
[docs] thirdparty & sdk scheme adapters cooperation

### ISSUE THREAD

**Issue by eoln** [mojaloop/project#1942]
## **Goal**:
`As a` Dev

`I want to` have a well-described scheme-adapters-tandem specification of cooperation
  
`so that` I can have enough understanding of the third-party feature separation to go on

**Acceptance Criteria**:
- [x] responsibilities and scopes of third-party & sdk adapters well described
- [x] server-client relationship between adapters
- [x] visual illustration of adapter positioning in PISP scenario
- [x] specify endpoints required by third-party client scheme adapter to be exposed by sdk-scheme-adapter
 
**Complexity**: <Low> > thirdparty interfaces separation is well understood

**Uncertainty**: <Low> > interfaces are already specified in pisp poc

---

**Tasks**:
- [x] update dependencies
- [x] index
- [x] responsibilities & scopes
- [x] server-client relationship
- [x] diagram/s
- [x] specify endpoints
**Done**
- [ ] Acceptance Criteria pass
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/46
- [ ] https://github.com/mojaloop/pisp/pull/112
## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
