### ISSUE TITLE
 Follow up on central-ledger service for  #1904 - Fixing config, provisioning support

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1944]
## **Goal**:
`As a`Mojaloop Scheme, based on previous tests and observations from story #1904
`I want to` fix issues in __central-ledger__ while introducing the Continuous Gross Settlement (CGS) model / feature
`so that` Mojaloop Schemes that need to support CGS can start using it

**Acceptance Criteria**:
- [x] central-ledger service runs in default settings in DEFERREDNET settlement mode without changes in default.json
- ~Participant accounts for INTERCHANGE_FEE_SETTLEMENT and INTERCHANGE_FEE account types can be added via REST API~ - Not Applicable as these are created using `POST /participants` API operations and only when the INTERCHANGEFEE settlement model is configured
- [ ] On-boarding postman collection for CGS and Interchangefee models are setting up participants correctly

- [x] central-ledger service on start up based on configuration in default.json must create the following settlement models in the database
   - [x] DEFERREDNET (default)
   - [x] CGS
   - [x] INTERCHANGEFEE 
- [x] On central-ledger service startup validate the following settlement model configuration combinations only
   - [x] DEFERREDNET
   - [x] CGS
   - [x] DEFERREDNET, INTERCHANGFEE
   - [x] CGS, INTERCHANGEFEE
- [x] Participant accounts must be created based on the ledgerAccountTypes defined by the configured settlement model(s) when a `POST /participant` API is called
- [x] When calling `POST /participants/{name}/initialPositionAndLimits` the initial position for each ledgerAccountTypes should be set based on the configured settlement model(s) 
- [x] disable the following route `POST /ledgerAccountTypes` (because `POST /settlementModels` has a reference to the hardcoded seed of ledgerAccountTypes and not the database entries)
- [x] When a new settlement model is created either by the config on start or by the API `POST /settlementModels`, the associated ledger accounts must be created retroactively for all the existing participants.
 
 **Additional Changes**:
- [x] Add new constraint to settlementModel table --> `t.unique([‘ledgerAccountTypeId’, ‘currencyId’], ’settlementmodel_uniqueAccountCurrency)` to migrations
- [x] Remove the `ConfigDataSeeder.initializeSeedData()` on server startup setup.js  <-- Note: Needs to be a new seed
- [x] Remove the SETTLEMENT_MODELS from the default.json
- [x] Remove the validateSettlementModelCombinations
- [x] Remove the validation in create settlementModel operation: https://github.com/mojaloop/central-ledger/blob/master/src/domain/settlement/index.js#L38
- [x] Re-enable the POST /ledgerAccountTypes API operations
- [x] Update the POST /settlementModels routes: change the ledgerAccounType from an enum to a string <-- validate (if this does not already exist) this in the domain.settlements.create operation instead
 
**Complexity**:  Low

**Uncertainty**: Low

---

**Tasks**:
- [x] fix the issue of empty config for ADDITIONAL_PARTICIPANT_LEDGER_ACCOUNT_TYPES and SETTLEMENT_MODELS - @shashi165 
- ~add REST API to add INTERCHANGE_FEE_SETTLEMENT and INTERCHANGE_FEE account types for each participant~
- [x] add postman requests for on-boarding participants
- [ ] reduce dockerfile commands to reduce number of layers and image size
- [x] central-ledger service on start up based on configuration in default.json must create the following settlement models in the database
   - [x] DEFERREDNET (default)
   - [x] CGS
   - [x] INTERCHANGEFEE 
- [x] On central-ledger service startup validate the following settlement model configuration combinations only
   - [x] DEFERREDNET
   - [x] CGS
   - [x] DEFERREDNET, INTERCHANGFEE
   - [x] CGS, INTERCHANGEFEE
- [x] Participant accounts must be created based on the ledgerAccountTypes defined by the configured settlement model(s) when a `POST /participant` API is called
- [x] When calling `POST /participants/{name}/initialPositionAndLimits` the initial position for each ledgerAccountTypes should be set based on the configured settlement model(s) 
- [x] disable the following route `POST /ledgerAccountTypes` (because `POST /settlementModels` has a reference to the hardcoded seed of ledgerAccountTypes and not the database entries)
- [x] When a new settlement model is created either by the config on start or by the API `POST /settlementModels`, the associated ledger accounts must be created retroactively for all the existing participants.
- [x] Fix unit tests
- [x] Fix integration/functional tests
- [ ] postman tests

 

**Done**
- [ ] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/808

## **Follow-up**:
- N/A

**Dependencies**:
- #1904 
- #1945

## **Accountability**:
- Owner: @vgenev , @shashi165 
- QA/Review: @elnyry-sam-k

**Comment by elnyry-sam-k** [comment]
Continued in https://github.com/mojaloop/project/issues/2027
