### ISSUE TITLE
 Follow up on central-settlement service for #1904 - Merging CGS feature to master branches 

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1945]
## **Goal**:
`As a`Mojaloop Scheme, based on previous tests and observations from story #1904
`I want to` fix issues in __central-settlement__ while introducing the Continuous Gross Settlement (CGS) model / feature
`so that` Mojaloop Schemes that need to support CGS can start using it

**Acceptance Criteria**:
- [x] central-settlement can run either API only, or mix of handlers and/or API modes based on CLI
- [x] scripts folder can be accessed from Rancher dashboard so scripts can be added without redeployment
- [x] a correct handlers and services are spawned based on helm configuration 
- [x] Golden Path for DEFERREDNET is passing with Settlement API v2

**Complexity**: Low

**Uncertainty**: High

---

**Tasks**:
- [x] find out why settlement in DEFERREDNET mode, with Settlement API v2 is not working for Golden Path - since the functionality is now separated into service and kafka handlers, and its not possible to run only settlementWindow handler 
- [x] ~add~ find an option to run API and only one handler from config now its either api or both handler
- [x] reduce dockerfile commands to reduce number of layers and image size
- [x] add __SCRIPTS_FOLDER__ to env/default.json configuration so it can be set on deployment
- [x] refactor the transfersettlement handler to run only if settlement model is CGS
- [x] helm charts changes
  - [x] create separate charts for transferSettlement and settlementWindow handlers and for the centralsettlement-service
  - [x] refactor each chart to match the central-ledger services pattern
    - add wait-for-kafka on helm chart for central-settlement
    - add sidecar config
      - [x] centralsettlement-handler-settlementwindow
      - [x] centralsettlement-handler-transfersettlement
      - [x] centralsettlement-service
    - [x] central-settlement   
  - [x] add the _scripts_ folder to be accessible from rancher like the rules in sdk-scheme-adapter deployment

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/central-settlement/pull/332

## **Follow-up**:
- N/A

**Dependencies**:
- #1904 
- #1944

## **Accountability**:
- Owner: @vgenev , @shashi165 
- QA/Review: @elnyry-sam-k

**Comment by elnyry-sam-k** [comment]
Follow-up: https://github.com/mojaloop/project/issues/2027
