### ISSUE TITLE
Helm Release v12.0.0 (it was v11.1.0): Updates to helm, QA, Fixes, Releases

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1947]
## **Goal**:
`As a` ML OSS Code base maintainer

`I want to` validate and make a Helm release in PI-12 (following v11.0.0) that is successfully validated by the Golden path tests
  
`so that` Community members can take and use a version of Mojaloop Switch services bundle that is tested and contains latest features and enhancements such as CGS, etc (added in and PI-12 (Sprints 12.2, 12.3, 12.4) so far)

**Acceptance Criteria**:
- [x] Helm RC vX.Y.0 is validated on dev2 and iterated until 100% result with postman GoldenPath collection is achieved
- [x] QA (Golden path) on deployments done on AWS dev2 environment is done
- [x] Bugs are logged based on observations, failures
- [x] Bugs logged are fixed if critical to make subsequent releases in individual services (or Helm)
- [x] All the changes needed for supporting vX.Y.0 of Helm are done
- [x] Helm vX.Y.0 release notes is drafted and published
- [x] TTK tests run successfully as Post-Hook jobs and Tests

**Complexity**: Medium - Involves all core and supporting services

**Uncertainty**: High - New feature for Settlement (Continuous Gross Settlement & Interchange fees to be included for the first time)

---

**Tasks**:
- [x] Make releases on all core services to have latest images / versions [@elnyry-sam-k , @mdebarros , @vgenev ]
- [x] Identify changes needed for helm (config / default.json)
- [x] Initial PR with changes for vX.Y.0
  - [x] Initial PR review
  - [x] Deploy, validate, fix issues, redeploy
  - [x] With stable deployment test Golden path
- [x] Identify issues with QA Scripts if any - fix them and retest
- [x] Identify Bugs, log them
- [x] Validate finance portal
- [x] Fix bugs logged if critical
- [x] Deploy, validate on AWS dev2
- [ ] ~Validate/Document upgrade scenario details~ -- not applicable (breaking changes for CGS)
- [x] Validate with Mojaloop Simulator collection
- [x] Release notes for helm v12.0.0 is drafted
- [x] Helm v12.0.0 released
- [x] Deployment of released Helm v12.0.0 on **Dev2**
  - [x] Helm v12.0.0 is deployed on **Dev2** successfully
  - [x] Validation using Golden path regression tests etc on Dev2
    - [x] Mojaloop Simulator postman collection
    - [x] TTK Post-hook install
  - [x] Validation using CGS Golden path regression tests etc on Dev2
    - [x] Mojaloop Simulator postman collection
- [x] Deployment of released Helm v12.0.0 on **Dev1**
  - [x] Helm v12.0.0 is deployed on **Dev1** successfully
  - [x] Validation using Golden path regression tests etc on Dev2
    - [x] Mojaloop Simulator postman collection
    - [x] TTK Post-hook install
  - [x] Validation using CGS Golden path regression tests etc on Dev2
    - [x] Mojaloop Simulator postman collection

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Postman Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/420
- [x] https://github.com/mojaloop/helm/pull/424
- [x] https://github.com/mojaloop/postman/pull/199

## **Issues**:
- [x] https://github.com/mojaloop/project/issues/2067
- ~https://github.com/mojaloop/project/issues/2054~ <-- Not applicable to release.

## **Follow-up**:

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @mdebarros @elnyry-sam-k

**Comment by mdebarros** [comment]
Found a bug with a recent version of Helm v3.x with regard to updating dependencies. An issue has been logged --> https://github.com/helm/helm/issues/9348

The impact being that we are not able to determine when there is an incorrect version dependency being defined on a parent chart.

We are able to use older version of Helm v3 and v2 to circumvent the issue.

**Comment by mdebarros** [comment]
## Testing Toolkit Report
Test Result: PASSED
Test Suite: GP Tests
Environment: Dev2
- Total assertions: 1557
- Passed assertions: 1557
- Failed assertions: 0
- Total requests: 297
- Total test cases: 61
- Passed percentage: **100.00%**
- Started time: Mon, 15 Feb 2021 21:19:32 GMT
- Completed time: Mon, 15 Feb 2021 21:21:05 GMT
- Runtime duration: 93071 ms
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2021-02-15T21%3A21%3A05.215Z.html)

**Comment by mdebarros** [comment]
┌─────────────────────────┬─────────────────────┬────────────────────┐
│                         │            executed │             failed │
├─────────────────────────┼─────────────────────┼────────────────────┤
│              iterations │                   1 │                  0 │
├─────────────────────────┼─────────────────────┼────────────────────┤
│                requests │                 501 │                  0 │
├─────────────────────────┼─────────────────────┼────────────────────┤
│            test-scripts │                 854 │                  0 │
├─────────────────────────┼─────────────────────┼────────────────────┤
│      prerequest-scripts │                 766 │                  0 │
├─────────────────────────┼─────────────────────┼────────────────────┤
│              assertions │                1851 │                  0 │
├─────────────────────────┴─────────────────────┴────────────────────┤
│ total run duration: 12m 5.4s                                       │
├────────────────────────────────────────────────────────────────────┤
│ total data received: 560.05KB (approx)                             │
├────────────────────────────────────────────────────────────────────┤
│ average response time: 264ms [min: 191ms, max: 897ms, s.d.: 112ms] │
└────────────────────────────────────────────────────────────────────┘

**Comment by mdebarros** [comment]
## Postman Golden Path CSG Report
```
┌─────────────────────────┬─────────────────────┬─────────────────────┐
│                         │            executed │              failed │
├─────────────────────────┼─────────────────────┼─────────────────────┤
│              iterations │                   1 │                   0 │
├─────────────────────────┼─────────────────────┼─────────────────────┤
│                requests │                  94 │                   0 │
├─────────────────────────┼─────────────────────┼─────────────────────┤
│            test-scripts │                 299 │                   0 │
├─────────────────────────┼─────────────────────┼─────────────────────┤
│      prerequest-scripts │                 250 │                   0 │
├─────────────────────────┼─────────────────────┼─────────────────────┤
│              assertions │                 175 │                   0 │
├─────────────────────────┴─────────────────────┴─────────────────────┤
│ total run duration: 1m 8.1s                                         │
├─────────────────────────────────────────────────────────────────────┤
│ total data received: 288.76KB (approx)                              │
├─────────────────────────────────────────────────────────────────────┤
│ average response time: 503ms [min: 206ms, max: 1751ms, s.d.: 327ms] │
└─────────────────────────────────────────────────────────────────────┘
```
[View report](https://github.com/mojaloop/project/files/5987246/dev2-postman-gp-csg-report.txt)

**Comment by mdebarros** [comment]
```
--------------------TEST CASES--------------------
Test Suite:GP Tests
Environment:Dev1
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 1557                          │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 1557                          │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 0                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 297                           │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 61                            │
├───────────────────┼───────────────────────────────┤
│ Passed percentage │ 100.00%                       │
├───────────────────┼───────────────────────────────┤
│ Started time      │ Wed, 17 Feb 2021 13:43:42 GMT │
├───────────────────┼───────────────────────────────┤
│ Completed time    │ Wed, 17 Feb 2021 13:45:14 GMT │
├───────────────────┼───────────────────────────────┤
│ Runtime duration  │ 92343 ms                      │
└───────────────────┴───────────────────────────────┘
```

**Comment by mdebarros** [comment]
## Dev1 -  Postman Golden Path Report
```

┌─────────────────────────┬─────────────────────┬────────────────────┐
│                         │            executed │             failed │
├─────────────────────────┼─────────────────────┼────────────────────┤
│              iterations │                   1 │                  0 │
├─────────────────────────┼─────────────────────┼────────────────────┤
│                requests │                 494 │                  0 │
├─────────────────────────┼─────────────────────┼────────────────────┤
│            test-scripts │                 854 │                  0 │
├─────────────────────────┼─────────────────────┼────────────────────┤
│      prerequest-scripts │                 766 │                  0 │
├─────────────────────────┼─────────────────────┼────────────────────┤
│              assertions │                1850 │                  0 │
├─────────────────────────┴─────────────────────┴────────────────────┤
│ total run duration: 12m 10.5s                                      │
├────────────────────────────────────────────────────────────────────┤
│ total data received: 553.02KB (approx)                             │
├────────────────────────────────────────────────────────────────────┤
│ average response time: 255ms [min: 185ms, max: 870ms, s.d.: 101ms] │
└────────────────────────────────────────────────────────────────────┘
```

[View report](https://github.com/mojaloop/project/files/5997259/dev1-postman-gp-report.txt)
)

**Comment by mdebarros** [comment]
## Dev1 -  Postman Golden Path CSG Report
```
┌─────────────────────────┬─────────────────────┬─────────────────────┐
│                         │            executed │              failed │
├─────────────────────────┼─────────────────────┼─────────────────────┤
│              iterations │                   1 │                   0 │
├─────────────────────────┼─────────────────────┼─────────────────────┤
│                requests │                  94 │                   0 │
├─────────────────────────┼─────────────────────┼─────────────────────┤
│            test-scripts │                 299 │                   0 │
├─────────────────────────┼─────────────────────┼─────────────────────┤
│      prerequest-scripts │                 250 │                   0 │
├─────────────────────────┼─────────────────────┼─────────────────────┤
│              assertions │                 175 │                   0 │
├─────────────────────────┴─────────────────────┴─────────────────────┤
│ total run duration: 1m 2.8s                                         │
├─────────────────────────────────────────────────────────────────────┤
│ total data received: 288.87KB (approx)                              │
├─────────────────────────────────────────────────────────────────────┤
│ average response time: 450ms [min: 192ms, max: 1047ms, s.d.: 262ms] │
└─────────────────────────────────────────────────────────────────────┘
```

[View report](https://github.com/mojaloop/project/files/6001075/dev1-postman-gp-csg-report.txt)

**Comment by mdebarros** [comment]
Finance portal test completed by @amarmodus --> https://www.dropbox.com/s/uz1q4g3hfecf4mc/Screenshot%202021-02-19%20at%2001.48.08.png?dl=0

**Comment by mdebarros** [comment]
New Postman release with minor bugs and fixes for OSS and IaC deployments: https://github.com/mojaloop/postman/releases/tag/v12.0.1

**Comment by elnyry-sam-k** [comment]
A test issue with TTK tests in using v1.1 version is in progress, but its not related to the helm release as such, so closing this
