### ISSUE TITLE
TTK bugs - sprint12.5 variables, formatting, exporting issues

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1948]
**Summary**:
Some newly identified bugs in TTK:
- [x] `requestVariables` are not replaced when the value is zero (0)
- [x] ~~Intermittently, Pre-request and Post-request scripts were lost, probably, during export~~ (Created a new bug #1970 
- [x] ~~"Stop" button does not appear to actually stop tests from running~~ (Created a new feature request #1971)
- [x] ~~No visible clues or error messages given when errors are encountered running some tests~~ (Can't reproduce it, created a new feature request #1972)
- [x] When you add a header to a request using the "Add Header" button, it leaves a comma "," before the header name
- [x] When you paste assertions into the raw editor for tests, the screen goes white 

**Severity**:
Medium

**Priority**:
Medium

**Steps to Reproduce**
  1.
  2.
  3.

**Pull Requests**
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/124
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/76

**Specifications**
  - Component (if known): TTK
  - Version:
  - Platform:
  - Subsystem: 
  - Type of testing:
  - Bug found/raised by: @oderayi 

**Notes**:

- Severity when opened: Low
- Priority when opened: Medium
