### ISSUE TITLE
TTK - Implement a page to show the server logs from Elastic Search

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1950]
## **Goal**:
`As a` individual implementer

`I want to` have an option to view server side logs
  
`so that` I can debug if there is an issue with the test case execution

**Acceptance Criteria**:
- [ ] An option to view server side logs is available in the test case execution page

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Add a configuration parameter 'EVENT_STREAM_LOGS_SUPPORT' in the system config [@oderayi] 
- [x] Add an API endpoint in TTK backend to get the logs from elastic search for a specific traceID, quoteID, transferID...etc [@oderayi] 
- [x] Add the feature in the front-end to show the logs based on the available search criteria [@oderayi] 
- [x] Add link to view logs in Elastic Search [@oderayi] 
- [x] Change the system_config in the helm chart to include new params [@oderayi] 
- [x] Enable Logs in Dev1 and Dev2

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/80
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/128
- [x] https://github.com/mojaloop/helm/pull/418
- [x] https://github.com/mojaloop/deploy-config/pull/37

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
