### ISSUE TITLE
TTK - Mobile simulator demo page

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1951]
## **Goal**:
`As a` individual implementer

`I want to` have a mobile simulator demo page
  
`so that` I can demonstrate the Mojaloop functionality

**Acceptance Criteria**:
- [x] A demo page is available with two mobile simulators where we can send a transfer from one to another against a real mojaloop switch. Live sequence diagram and request/response logs should be populated dynamically.

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Design a page in the TTK UI for mobile simulation
- [x] Integrate TTK backend to the demo page to make it work with a real mojaloop switch
   - [x] Design the react component architecture for integrating to TTK backend
   - [x] Refactor the components and request and response parsing
   - [x] Prepare the individual templates for all the requests
   - [x] Integrate the TTK backend and run P2P against real mojaloop switch

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/77

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
