### ISSUE TITLE
CQS Documentation Upload - Program Management 

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1952]
## **Goal**:
`As a OSS developer

`I want to` sort and update all the program management related information of the CQS workstream
  
`so that` I have them ready to be uploaded to the new document portal 

**Acceptance Criteria**:
- [ ] Document ready for uploading from a single store

**Complexity**: Low
**Uncertainty**: Low
---
**Tasks**:

- [ ] Identify all the document sets as per approved CQS Doc schema [ @godfreykutumela  ]
- [ ] Ensure that they are all updated [ @godfreykutumela ]
- [ ] Put them on a single repository marked appropriately and ready for uploading [ @godfreykutumela ]

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela
