### ISSUE TITLE
Investigate how an end to end FIDO Implementation can be introduced on the current Mojaloop Architecture

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1955]
## **Goal**:

Explore FIDO design options for an end to end to Mojaloop deployment. Areas to be investigated includes but not limited to:

1. Three user cases. The user needs to interact with the PISP in the following use cases:
     - register user
     - authenticate user
     - credit transaction
     - authorize transaction
2. Authenticators. Introduction of the different authenticators and where they apply.
3. Attestation. Integration Attestation Certificate provider for Authenticators. 
4. Private keys protection. Secure element in the smartphone (internal authenticators)
5. Relying Party Origin. The use of the Relying Party (PISP) domain to protect Private Keys.
6. FIDO Server. Introduction of Mojaloop FIDO server component. 
7. Define FIDO API. Define end points for PISP to access FIDO Server services.
8. Crypto functions. Define crypto functions to be used by the FIDO services.
9. User database. Associate users with their credentials (Public keys and challenges)
7. Public keys. Public keys generation.
8. Challenge. Challenge generation.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: High

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @bukasaaime ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @bukasaaime 
- QA/Review: @godfreykutumela
