### ISSUE TITLE
Central-Settlement v2 CGS support - Integrate Event Framework

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1956]
## **Goal**:
As a `Hub Operator`
I want to `integrate Event Framework into Mojaloop components`
so that `so that all events (errors, general, admin etc) can be audited and traced appropriately`

This specific story is to integrate the event-sidecar into Central-Settlement

**Tasks**:
- [ ] Event Framework
  - [ ] Integrate SDK for logging
    - [ ] Integrate event-sdк
      - [ ] Configuration in default.json (e.g. sidecar enabled, logging mode etc)
      - [ ] Import NPM dependency
    - [ ] Integrate into health end-points for Event Sidecar (if sidecar is enabled)
    - [ ] Recording
      - [ ] Add Audits for beginning of receiving request for participants, party, etc
      - [ ] Add Errors for both Internal vs External (e.g. errors - ?)
    - [ ] Implemented Endpoints for which Event Framework was integrated into:
      - [ ] /settlementWindows/{id}
        - [ ] GET
        - [ ] POST
      - [ ] /settlementWindows
        - [ ] GET
      - [ ] /settlements
        - [ ] GET
        - [ ] POST
      - [ ] /settlements/{id}
        - [ ] GET
        - [ ] PUT
      - [ ] /settlements/{id}
        - [ ] GET
        - [ ] PUT
      - [ ] /settlements/{sid}/participants/{pid}
        - [ ] GET
        - [ ] PUT
      - [ ] /settlements/{sid}/participants/{pid}/accounts/{aid}
        - [ ] GET
        - [ ] PUT
    - [ ] Implemented Handlers for which Event Framework was integrated into:
      - [ ] settlementWindow handler
      - [ ] transferSettelement handler
    - [ ] tools
      - [ ] scripts execution

**Acceptance Criteria**:
- [ ] Sidecar is recording and
  - [ ] Deployment includes sidecar as part of deployment
  - [ ] Deployment includes sidecar configuration

## **Pull Requests**:
- [ ] TBA

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
