### ISSUE TITLE
[consent-oracle] Setup mojaloop/als-consent-oracle repository.

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#1958]
## **Goal**:
`As a` developer

`I want to` setup a repository for the als-consent-oracle
  
`so that` I can manage the development of the oracle.

**Acceptance Criteria**:
- [ ] Repository is created, team members are added and permissions are setup properly.

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Superceded by #1960
