### ISSUE TITLE
[als-oracle-template] Upgrade template to latest libraries, upgrade schema to openapi3 v1.1 and remove swagger2 dependent code.

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#1959]
## **Goal**:
`As a` developer

`I want to`  build off of a stable als-oracle-template using the latest libraries and schema standards
  
`so that` we and others can build als oracles quickly

**Acceptance Criteria**:
Updated libraries and swagger interface, switched to `openapi-backend` for swagger magic.

**Complexity**: Medium: Template is old. Libraries might give trouble.
**Uncertainty**: Low

---

**Tasks**:
- [x] Upgraded libraries to latest stable and fix outstanding vulnerabilities.
- [x] Upgraded interface to openapi3 and remove and dependent swagger2 code.
- [x] switch from `hapi-openapi` -> `openapi-backend` for swagger 3 support (we have examples in thirdparty-scheme-adapter, auth-service, ALS, Transaction Requests Service)
    > Note: if you encounter Regex issues with extended unicode, in this library refer to the `Transaction-Requests-Service` codebase for examples 

- [x] ensure that the github repo is set up as a "template repository"

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/als-oracle-template/pull/14

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@kleyow what is the cost of delay on this one? Do we 100% need it for the current features in our scope? Or is it more of a nice to have?

**Comment by kleyow** [comment]
@lewisdaly More than I initially thought. Not the OA3 stuff, but yes on updating to latest libraries. Nice to have.

I explored this ticket a bit after writing it. It doesn't seem to be a swift change. 
hapi-openapi still doesn't support OA3 fully(?), seems to be going downhill in its maintaining. 
Brings to question how we move forward with our other hapi stack code...
