### ISSUE TITLE
[consent-oracle] Initialize als-consent-oracle with updated als-oracle-template.

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#1960]
## **Goal**:
`As a` developer

`I want to` commit the als-oracle-template to the als-consent-oracle repo
  
`so that` we can begin deviating development.

**Acceptance Criteria**:
- [x] als-consent-oracle created from template and customized as needed

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] set up the npm project config (package.json, tsconfig, eslint, precommit hooks)
- [x] set up the repo:
  - [x] default branch rules
  - [x] admin and access
  - [x] codeowners

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by kleyow** [comment]
Just copied the settings from thirdparty-api-adater.
