### ISSUE TITLE
[consent-oracle] Configure oracle with mysql database and handle various `/participants` requests from ALS.

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#1965]
## **Goal**:
`As a` developer

`I want to` add a database to store consent and fspId information and perform CRUD operations depending on each individual handler.
  
`so that` we have a working oracle that associates consents with a FSP.

**Acceptance Criteria**:
- [x] Consent table gets added to mysql database.
- [x] Libraries to manage database are added.
- [x] Code to CRUD database added to `/participants` handles which return appropriate responses to the ALS.

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
