### ISSUE TITLE
[consent-oracle] Configure circleci to run tests/scans and build docker image of consent oracle.

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#1966]
## **Goal**:
`As a` developer

`I want to` automate tests, scans and the building of the oracle
  
`so that` have deployable image to test in the PISP sandbox.

**Acceptance Criteria**:
- [x] CircleCI script is added
- [x] Tests/Image scans/Vulnerability scans pass.
- [x] Docker Image is automated and built

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
