### ISSUE TITLE
[design] - Design the API for the DFSP Mock Login Page/Simulator

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1967]
## **Goal**:
`As a` QA tester

`I want to` be able to simulate the out-of-bound user authentication
  
`so that` I can perform an end-to-end test of pisp account linking

**Acceptance Criteria**:
- [x] Agreed upon feature list of the DFSP Mock Login Page/Simulator
- [x] OpenAPI definition for this API

**Complexity**: Medium 

**Uncertainty**: Medium > We have a rough idea of the feature set we want, but need to get a better understanding of the requirements

---

In order to test our entire end to end account linking flow, we need a service that will simulate the out of bound user authentication (OTP or WEB) between a DFSP and their user. Such a service will need:
1. User facing endpoints: `/login` and `/getOtp`, which will allow a fake user to login and get an access token that can be used by the PISP
2. The ability to simulate different actions depending on the OTP/Auth Token entered (similar to how the rules engines work in the simulators/ttk today)
  - e.g. if the PISP supplies an OTP of `000000` that will simulate a certain error scenario, `000001` will simulate a different error scenario, and `123456` will be a successful user authentication

**Tasks**:
- [x] Scope out the required features that the Mock Login Page will need (both user facing and simulated api call based)
- [x] document /sendOTP in pisp repo
- [x] document Web flow
- [x] Define an API that will allow those features
  - [x] `POST /login`
  - [x] `POST /authorize`
  - [x] `POST /sendOTP`
  - [x] `POST /verifyOTPorSecret`
  - [x] `GET /getOTPorSecret`
  - [x] `GET /store/consentRequests/{ID}`
  - [x] `POST /store/consentRequests/{ID}`
- [x] Produce an OpenAPI definition for this API (you can probably just put it in the PISP repo for now)
- [x] Add sequence diagrams to docs

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date

## **Pull Requests**:
- [x] https://github.com/mojaloop/pisp/pull/109
- [x] https://github.com/mojaloop/pisp/pull/110
- [x] https://github.com/mojaloop/pisp/pull/111 (API yaml)

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by sridharvoruganti** [comment]
we need to finalise how to initiate DFSP `AUTH-5 step Verify OTP/Auth Token is correct` 
https://github.com/mojaloop/pisp/tree/master/docs/linking#142-otp
