### ISSUE TITLE
Identify and replace deprecated Mojaloop dependant Helm Charts

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1969]
## **Goal**:

`I want to` replace deprecated Helm chart dependencies from the Mojaloop Helm chart
  
`so that` deployers have "reference" Helm charts for backend dependencies.

**Acceptance Criteria**:
- [ ] Helm Charts have been identified and replaced for the following dependencies:
    - [ ] MySQL
    - [ ] Kafka
    - [ ] MongoDB
    - [ ] Prometheus
    - [ ] Grafana
    - [ ] EFK
    - [ ] APM
- [ ] Deployment Guide is updated to include:
    - a list of external dependencies as pre-requisites
    - instructions or links provided on how they can be deployed using Helm (or alternatively additional guides on how to use managed servers in AWS, Azure, etc can also be considered)
    - instructions on how to configure Mojaloop charts to use these external deployed dependencies (i.e. Kafka URIs, etc)
- [ ] Update Helm Chart documentation to reflect this change.
- [ ] Updated Deployment Guide instructions are tested by QA

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
#### Identify Helm Charts for Backend dependencies
- [ ] MySQL
- [ ] Kafka
- [ ] MongoDB
- [ ] Promfana
- [ ] EFK+APM

#### Remove Deprecated Charts:
- [ ] Promfana
- [ ] EFK+APM
- [ ] MySQL
- [ ] Kafka

---

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- Design Authority Proposal - https://github.com/mojaloop/design-authority/issues/69

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
completed
