### ISSUE TITLE
2.3.4 API Refactoring: Implement notification handler as part of ml-api-adapter - [13, 8]

### ISSUE THREAD

**Issue by THEADEV** [mojaloop/project#197]
**Goal**:
As a developer 
I would like to _implement notification handler as part ML API Adapter_
so that _notifications can be sent to DFSP from central services stack_

**Tasks**:
- [x] Make sure base code from central-ledger, develop-PI2 branch is being used as it has the right dependency versions in package.json - Done
- [x] Create the appropriate folder structure. - Done
- [x] In Transfer API, populate Headers - Done
- [x] Update schema validation to be compliant with Mojaloop API Spec - Done
- [x] Update unit and functional test cases to test the above 2 new features added - Done
- [x] In Notification Handler, upon receiving the message from Kafka, extract the payload from content.payload. Extract content.Headers and populate as HTTP Headers. - Done
- [x] Use the "to" attribute from Kafka message, determine the callback url based on it and send a PUT call at that callback endpoint. - Done
- [x]  unit test cases for notification handler - Done
- [x] Add Integration Tests - Done
- [x] Move the kafka configurations to config file -  Done

**Acceptance Criteria**:
- [x] Notification Handler is able to send REST callback to the DFSP 
- [x] Notification Handler needs to consume notification messages from the Kafka topic.
- [x] Integration Tests are available

**Dependencies**:
- [x] #164 

**Accountability**
- Owner @shashi165 
- Review @ksatya77
