### ISSUE TITLE
TTK - Improve stop functionality of the test case execution

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1971]
## **Goal**:
`As a` individual implementer

`I want to` have the capability to stop the execution of the test cases reliably
  
`so that` I can stop the execution incase of long waiting times

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Identify the scenarios where some requests are being executed very long time and put some timeout
- [ ] Improve the stop execution functionality more user friendly

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
