### ISSUE TITLE
Modify Kafka Configuration to include default Host information to support removal of external dependencies from Helm charts

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1973]
## **Goal**:
`As a` Mojaloop Deployer

`I want to` configure Kafka via a K8s Secret
  
`so that` Kafka client configurations are stored/accessed securely against k8s best practices

This is required for the following story: https://github.com/mojaloop/project/issues/1852

**Notes:**
- This story is a result of the Kafka host information being defined by a "." separated key (i.e. `metadata.broker.list`). As a result, we are unable to override this value using our config library (i.e. `RC`) through Environment Variables, as ENV vars can only contain the following character set: `[a-zA-Z_][a-zA-Z0-9_]*` (Ref: IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore)). As such we are able to define default Host configs that will automatically set the host information in the Kafka config. If required the existing `metadata.broker.list` can still be set if required in the default.json config file which will ignore the default values.

**Acceptance Criteria**:
- [ ] Mojaloop Helm charts will no longer deploy external dependant Helm Charts
- Mojaloop deployment documentation to be updated to include:
    - [ ] Support version of backend dependencies (MySQL, Kafka, MongoDB, etc)
    - [ ] Instructions on where/how they can be deployed
- [ ] Mojaloop "Dependencies" Helm Chart that can be used by deployers to setup development and lab environments - this will deploy the removed external dependant Helm Charts, and create the necessary external secrets to support the deployment of Mojaloop Helm Charts.

**Complexity**: High

**Uncertainty**: Medium

---

**Tasks**:
-  Central-services-shared
    - [ ] Updated to map default Host information to Kafka config if host information is not provided
    - [ ] Create new release
- Update dependant components with no release and config changes (if required):
    - [ ] Central-Ledger
    - [ ] ML-API-Adapter
    - [ ] Cetranl-Event-Processor
    - [ ] Event-Stream-Processor
    - [ ] Central-Ledger
    - [ ] Bulk-API-Adapter
- Create new releases for the updated components:
    - [ ] Central-Ledger
    - [ ] ML-API-Adapter
    - [ ] Cetranl-Event-Processor
    - [ ] Event-Stream-Processor
    - [ ] Central-Ledger
    - [ ] Bulk-API-Adapter
- Update Helm for the new releases:
    - [ ] Central-Ledger
    - [ ] ML-API-Adapter
    - [ ] Cetranl-Event-Processor
    - [ ] Event-Stream-Processor
    - [ ] Central-Ledger
    - [ ] Bulk-API-Adapter

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] Updates to Helm for new Component Versions

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
This is not required at this stage as we have an alternative solution by utilising YAML anchors to achieve the same result, as per the [mojaloop/values.yaml](https://github.com/mojaloop/helm/blob/master/mojaloop/values.yaml#L2) CONFIG section file header.
