### ISSUE TITLE
TTK - Mobile simulator UI standardisation

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1975]
## **Goal**:
`As a` individual implementer

`I want to` deploy the TTK with mobile simulator page
  
`so that` I can demonstrate the transaction flow easily with TTK

**Acceptance Criteria**:
- [x] The mobile simulator page can be configurable to use it in any type of TTK deployment

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] FSPs provisioning through a settings dialogue
- [x] A link to the mobile simulator should be available in the TTK somewhere (may be homepage)
- [x] Configurability to edit / import environment values
- [x] Isolate the socket messages session wise
- [x] Change the default callback rules based on the new FSP names
- [x] Try to show the oracle lookup sequence (Or create a new story for this)

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/126
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/78
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/127
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/79
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/81

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @elnyry-sam-k
