### ISSUE TITLE
resolve high vulnerabilities for thirdparty-scheme-adapter

### ISSUE THREAD

**Issue by eoln** [mojaloop/project#1976]
## **Goal**:
`As a` Mojaloop OSS maintainer

`I want to` resolve high vulnerabilities
  
`so that` we can releases of services are free of known safety issues

**Acceptance Criteria**:
- [x] dependences updated &  unit tests & integration tests for thridparty-scheme-adapter are working well
- [x] `npm run audit:check` doesn't show high vulnerabilites

**Complexity**: <Low> > only update deps and rerun the tests

**Uncertainty**: <Low> > nothing new

---

```
Server-Side Request Forgery
 vulnerable versions <0.21.1 found in:
 - dependencies: @mojaloop/central-services-health>@mojaloop/central-services-shared>axios
 - dependencies: @mojaloop/central-services-shared>axios
```

**Tasks**:
- [x] central-services-health
- [x] central-services-shared
- [x] update deps and retest thirdparty-scheme-adapter

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-shared/pull/273
- [x] https://github.com/mojaloop/central-services-health/pull/233

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
