### ISSUE TITLE
Mojaloop Secure Network & Application Access Standard 

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1979]
## **Goal**:
`As a` OSS Security Specialist

`I want to` define a secure network and application access standard
  
`so that` it can guide the network security design considerations for Mojaloop Hub Implementors.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] Define the framework for the standard 
- [ ] Link to the PCI DSS Standard Baseline work
- [ ] Compile a final version and set it for review 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @kjw000

**Comment by godfreykutumela** [comment]
Draft Standard for Team Review.
[Uploading Mojaloop Secure Network Access Standard and Recommendations v1.0 15012021 Final.docx…]()

**Comment by rasputtintin** [comment]
Hi @godfreykutumela the link attached is not opening.

**Comment by godfreykutumela** [comment]
Try now @rasputtintin

**Comment by mdebarros** [comment]
> Try now @rasputtintin

Thanks its working for me now.

**Comment by mdebarros** [comment]
It would be great if we could move this document to google docs where we can colab and add comments etc.

**Comment by godfreykutumela** [comment]
I will move the doc to gdocs

**Comment by godfreykutumela** [comment]
https://docs.google.com/document/d/1JM8pVNZoVkF058cJEa9pqGQabjb7t_-4Mwandie_kTQ/edit?usp=sharing
