### ISSUE TITLE
[Impl] - Implement the APIs for the DFSP Mock Login Page/Simulator

### ISSUE THREAD

**Issue by sridharvoruganti** [mojaloop/project#1982]
## **Goal**:
As a QA tester

I want to be able to simulate the out-of-bound user authentication

so that I can perform an end-to-end test of pisp account linking

**Acceptance Criteria**:
- [x] Implement the APIs defined for the DFSP Mock Login Page/Simulator in #1967

**Complexity**: Medium

**Uncertainty**: Medium > We have a rough idea of the feature set we want, but need to get a better understanding of the requirements

---

**Tasks**:
- [x] Implement following endpoints (on TTK)
  - [x] `POST /login`
  - [x] `POST /authorize`
  - [x] `POST /sendOTP`
  - [x] `POST /verifyOTPorSecret`
  - [x] `GET /getOTPorSecret`
  - [x] `GET /store/consentRequests/{ID}`
  - [x] `POST /store/consentRequests/{ID}`
- [x] use the user's name a scenario selector (e.g. failure, success, etc)

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] https://github.com/mojaloop/pisp/pull/115

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
