### ISSUE TITLE
TTK universal store

### ISSUE THREAD

**Issue by eoln** [mojaloop/project#1986]
## **Goal**:
`As a` DEV

`I want to` store arbitrary payloads in TTK
  
`so that` I can simulate any datastore

- 
**Acceptance Criteria**:
- [ ] POST/GET /store/<resource>/<id> generic handler
- [ ] yaml definition for `/store/consentRequests/<id>`
- [ ] in-memory storage implemented as dictionary indexed by composite keys in form `<resource>-<id>` and any payload as the value

**Complexity**: <LOW> > in memory storage 

**Uncertainty**: <Low> > simple api

---

**Tasks**:
- [ ] GET/POST /store/<resource>/<id> generic handler
- [ ] yaml definition for `/store/consentRequests/<id>`
- [ ] in-memory storage implemented as dictionary indexed by composite keys in form `<resource>-<id>` and any payload as the value
- [ ] unit tests
- [ ] documentation how to use the generic store, especially how to define input validation in yaml

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
This may not be required, or at least is not urgent since we covered this implementation in the mojaloop-simulator
