### ISSUE TITLE
Security Review February + March

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1988]
**Tasks**:
- [x] remove unneeded central-services-shared dependency from central-services-health:
    - [ ] https://github.com/mojaloop/central-services-health/pull/235

- [x] review dependabot alerts
- [x] merge in existing PRS
- [x] create new prs for fixes where applicable
- [x] created any follow up tickets where applicable

- apply to the following repos (as identified by dependabot):
   - [x] email-notifier
   - [x] central-event-processor
   - [x] event-sdk
   - [x] transaction-requests-service
   - [x] event-stream-processor
   - [x] central-ledger

- fix broken builds:
  - [x] ml-api-adapter
  - [ ] simulator
  - [ ] sdk-scheme-adapter
  - [ ] auth-service

- make the following releases
    - [ ] central-services-health
    - [ ] ml-schema-validator

Note:
- `finance-portal-lib` is still in snapshot status, so I removed the security alerts for this repo

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-api-adapter/pull/465
- [x] https://github.com/mojaloop/central-services-health/pull/235
- [x] https://github.com/mojaloop/ml-schema-validator/pull/8

## **Follow-up**:
- [ ] event-stream-processor - need to upgrade to the latest central-services-health to fix an issue where dependabot can't apply a fix.
- 

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: @godfreykutumela
