### ISSUE TITLE
Mowali Security Vulnerabilities Evaluation

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1989]
## **Goal**:
`As a` OSS security specialist

`I want to` review, investigate and respond to vulnerabilities detected from Mowali's lastest security scan.
  
`so that` I can determine if they originate from our OSS code version or not. And if so, I will proceed to investigate why our vulnerability scanning tools detected them.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Receive a list of vulnerabilities from Mowali [ @godfreykutumela  ]
- [ ] Distribute for team review [ @godfreykutumela ]
- [ ] Investigate and respond to Mowali [ @godfreykutumela ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
Resolutions to be pursued in the next PI 
1.	We should get to automated releases asap (for at least the core packages), so we can reduce the overhead of managing releases ourselves. All we would need to do it merge dependabot and a new release will be made for us
2.	We need to move ml-operator to production, so it will be able to pick up new image releases and alert the Mowali folks
3.     Additionally, it would be great to get feedback from Mowali once they can use the operator and see how it can be tailored to suit their needs.
