### ISSUE TITLE
2.4.70.02 Extend the PositionHandler to affect change on FSP positions based on events

### ISSUE THREAD

**Issue by THEADEV** [mojaloop/project#199]
**Goal**:
1. As a developer
I want to _Implement the PositionsHandler_
so that FSP positions are calculated/updated and transfers persisted.
2. As the Switch Operator
I want to ensure that no FSP exceeds the net debit cap (position)
so that I do not issue credit to the FSP
3. As a Payer FSP
I want to be sure that the Switch never allows my net debit cap (position limit) to be exceeded
so that I am never exposed to a greater financial risk than my agreed position limit allows

**Note**: 
- Event logging is handled by story #218

**Tasks**:
- [ ] Extend Position Handler to:
  - [ ] retrieve the latest position
  - [ ] retrieve the latest participantLimit for the payer
  - [ ] calculate the latest position
  - [ ] validate the position
  - [ ] persist latest calculated position when validation is successful
  - [ ] send notification to Payer when the validation has failed
  - [ ] persist state of transfer depending on validation success ('transferState'='RESERVED') or failure('transferState'='ABORTED')

**Acceptance Criteria**:
- [ ] Positions Handler to:
  - [ ] consume position events: Prepares
  - [ ] consume position events: Rejections
  - [ ] consume position events: Time-outs
  - [ ] consume position events: Settlements
  - [ ] validate each position against the participant limit
  - [ ] produce notification message on to the notification topic
  - [ ] calculate new position and persist
- [ ] Implement functionality based on sequence diagrams (https://github.com/mojaloop/docs/blob/develop/CentralServices/seq_diagrams/seq-prepare-1.1.2.a.svg) for Position Handler

**Dependencies**:
- [ ] #165
- [ ] #239 
- [ ] #273 

**Accountability**:
- Owner 
- QA/Review

**Comment by elnyry** [comment]
Duplicate, covered in 2.x items in 3.x sprints
