### ISSUE TITLE
sync POST /authorization/.... @ SDK-Outgoing

### ISSUE THREAD

**Issue by eoln** [mojaloop/project#1992]
## **Goal**:
`As a` thirdparty-scheme-adapter

`I want to` expose sync POST /authorization/.... @ SDK-Outgoing
  
`so that` this endpoint can be used in third-party workflows

**Acceptance Criteria**:
- [x] yaml definition
- [x] expiry property and proper timeout handling
- [x] implementation
- [x] unit testing
- [x] merged with master branch

**Complexity**: <Low> > in pisp/master branch there is a POC implementation for this endpoint, there is a need to extend timeout handling & resources cleanup

**Uncertainty**: <Low> > well known pattern asyn-PUB/SUB-sync

---
https://github.com/mojaloop/pisp/tree/master/docs/scheme-adapters

**Tasks**:
- [x]  Add POST `\authorizations` to MojaloopRequests in `sdk-standard-components`
- [x]  Update `api-snippets` authorization schemas
- [x] extract code from pisp/master to working branch forked from the latest master
- [x] implement expiry & timeout handling
- [x] finalise unit-tests
- [x] documentation
- [ ] add comment to sdk-standard-components about 'slightly not kosher' use of POST Authorizations in `mojaloopRequests.js`

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to the team and follow-up tasks added to update helm charts and another deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/256

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
