### ISSUE TITLE
sync POST /quotes @ SDK-Outgoing

### ISSUE THREAD

**Issue by eoln** [mojaloop/project#1993]
## **Goal**:
`As a` thirdparty-scheme-adapter

`I want to` expose sync POST /quotes/.... @ SDK-Outgoing
  
`so that` this endpoint can be used in third-party workflows

**Acceptance Criteria**:
- [x] yaml definition
- [x] expiry property and proper timeout handling
- [x] implementation
- [x] unit testing
- [x] merged with master branch

**Complexity**: <Low> > in pisp/master branch there is a POC implementation for this endpoint, there is a need to extend timeout handling & resources cleanup

**Uncertainty**: <Low> > well known pattern asyn-PUB/SUB-sync

---
https://github.com/mojaloop/pisp/tree/master/docs/scheme-adapters

**Tasks**:
- [x] API definitions for Outgoing & Ingoing
- [x] Model generation
- [x] Handlers
- [x] Unit Tests
- [x] Integration Tests
- [x] merge latest master
- [ ] documentation

**Done**
- [ ] Acceptance Criteria pass
- [x] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to the team and follow-up tasks added to update helm charts and another deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/251
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
