### ISSUE TITLE
Re-factor any functional logic from Central-Ledger API Handler layer into Service Domain Layer

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1995]
## **Goal**:
`As a` Mojaloop Developer

`I want to` ensure that all service logic is placed in the Domain layer
  
`so that` the Domain layer is the logic separation layer from the API layer, which will allow different API/Transports to be added in future

Example:

Here is an example of the `POST /participants` implementation of the Handler layer: https://github.com/mojaloop/central-ledger/blob/master/src/api/participants/handler.js#L73, which contains the functional logic.
Here is the actual Domain layer implementation, which only contains the call to the model layer: https://github.com/mojaloop/central-ledger/blob/master/src/domain/participant/index.js#L58

All functional logic should be moved to the Domain layer:
- Validation for existing Participants
- Validation of Hub accounts
- Creation of Participant
- Creation of Participant accounts for Position and Settlements

The Handler layer should only be calling the ParticipantService.create(...) Domain layer service operation.

**Acceptance Criteria**:
- [ ] Service Domain layer contains all logic required to process the request from a functional perspective
- [ ] API Layer only handled transport/API protocol transformations into the underlying service Domain layer

**Complexity**: <High|Medium|Low> > Medium

**Uncertainty**: <High|Medium|Low> > Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @mdebarros
- QA/Review: TBC
