### ISSUE TITLE
Auto-configure Mojaloop Template for index patterns with Elasticsearch when deploying the Event-Stream-Processor

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1997]
## **Goal**:
`As a` Mojaloop Deployer

`I want to` have the Mojaloop Template automatically defined on ElasticSearch when deploying Event-Stream-Processor
  
`so that` Mojaloop Event Logs (Audits, Errors) are properly indexed and searchable for operational monitoring and issues resolution

**Acceptance Criteria**:
- [ ] Event-Stream-Processor Helm Charts automatically register the Mojaloop Template to ElasticSearch as an Init-container:
    - [ ] Init-container must first check if the Mojaloop Template is not already registered before creating it: https://github.com/mojaloop/event-stream-processor#113-get-template
    - [ ] Init-container will create the Mojaloop Template if the existing check passes: https://github.com/mojaloop/event-stream-processor#111-create-template

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
not planned for the foreseeable future; need to reopen if required
