### ISSUE TITLE
[sdk-scheme-adapter] templating open-api interfaces

### ISSUE THREAD

**Issue by eoln** [mojaloop/project#1998]
`As a` Dev

`I want to` have Inbound/Outbound open-api interfaces templated with mojaloop@api-snippets
  
`so that` interface definitions are defined using common mojaloop types from one source of truth

**Acceptance Criteria**:
- [x] Inbound interface
- [ ] Outbound interface

**Complexity**: <Medium> > there are multiple endpoints

**Uncertainty**: <Medium> > whereas Inbound interfaces should be identical with mojaloop ones, then Outbound ones are extended

---

**Tasks**:
- [x] install api-snippets as devDependency and implement scripts to generate spec from templates
- [x] Inbound service
- [ ] Outbound service

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
