### ISSUE TITLE
Design & refactor the User table and associated Micro-Service

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#20]
**Goal**:
As a developer I would like to design & refactor the User table and associated Micro-Service in order to expand the data and functionality catered for

**Tasks**:
Performance activities:
- [x] Assess complete database, normalise User table.

**Acceptance Criteria**:
- [x] Document a normalised data structure for user table and related foreign key associated tables
- [x] Refactor the current implementation to cater for the normalised data structure
- [x] Refactor unit tests to cater for the normalised data structure
- [x] Refactor functional tests to cater for the normalised data structure
- [x] Refactor integration tests to cater for the normalised data structure

**Dependencies**:
- None currently
