### ISSUE TITLE
[design/linking] - auth channel not supported

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2000]
## **Goal**:
`As a` PISP's user

`I want to` be able to choose which method to log in to my DFSP, Web or OTP, and be informed if this method is not supported.

`so that` I can pick another method.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

The Thirdparty-PISP API supports 2 types of auth channels: `Web` and `OTP`. In the `POST /consentRequests` body, the PISP can specify either `Web`, `OTP`, or both `Web` and `OTP`, and the DFSP can decide which channel it would like to use. 

If, for example, a DFSP only supports `OTP` flows, and the PISP requests only `Web` flow for account linking, the DFSP needs an error code for `unsupported auth channel`, or something along those lines.

**Tasks**:
- [ ] define an error code for unsupported auth channel during account linking
- [ ] add a sequence diagram for a failure scenario with a `POST /consentRequests` call with an unsupported authChannel

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
This can be pretty low priority... it delivers pretty small value to the user, and we can for now stipulate that a PISP MUST send both `Web` and `OTP` in the `authChannels` array.

**Comment by lewisdaly** [comment]
Closing as out of scope
