### ISSUE TITLE
[linking] - Invalid scopes handling

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2001]
## **Goal**:
`As a` user

`I want to` be informed if the accounts I've selected for linking are not available, or the account actions are not allowed
  
`so that` I can restart the linking process from scratch

**Acceptance Criteria**:
- [ ] updated/new sequence diagram with error callback from DFSP for an invalid set of scopes: `PUT /consentRequests/{id}/error`
- [x] end to end test that produces a `PUT /consentRequests/{id}/error` for a bad `accountId` 

**Complexity**: High

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] update sequence diagrams and error codes
- [x] update the handling of `POST /consentRequests` in the thirdparty-api-adapter
- [x] implement a test scenario on the DFSP to call `PUT /consentRequests/{id}/error` when receiving a bad set of scopes
- [x] handle `PUT /consentRequests/{id}/error` in the thirdparty-api-adapter
- [x] implement `POST /consentRequests` in the thirdparty-scheme-adapter inbound
- [x] handle `PUT /consentRequests/{id}/error` in the thirdparty-scheme-adapter inbound
- [x] implement `POST /consentRequests` endpoint in the thirdparty-scheme-adapter outbound
- [x]  implement validateConsentRequests endpoint in `mojaloop-simulator`
- [x] end to end test for this error callback on the PISP's side
- [x]  add all possible error scenarios
**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/80
- [x] https://github.com/mojaloop/mojaloop-simulator/pull/94
- [x] https://github.com/mojaloop/pisp/pull/131
- [x] https://github.com/mojaloop/sdk-standard-components/pull/143
- [x] https://github.com/mojaloop/mojaloop-simulator/pull/95
- [x] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/86
## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
I think this one should wait for now - JJ, Michael and I were discussing an update to the `PUT /consentRequests/{id}` body that would include the `accountIdentifier` to make the scopes lookup on the DFSP side much easier.

**Comment by lewisdaly** [comment]
Sequences are updated, so please go ahead.
