### ISSUE TITLE
[linking] - valid otp account linking step

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2002]
## **Goal**:

`As a` DFSP

`I want to be` able to accept an account linking request if I receive a correct OTP from the PISP

`so that` I can proceed with the account linking

**Acceptance Criteria**:
- [x] an end to end test that demonstrates a valid OTP 

**Complexity**: Medium - first time writing this type of test with it's necessary components

**Uncertainty**: Medium

---

**Tasks**:
- [x] implement OTP linking success case end to end test
- [x] UML detailed sequence diagram
- [x] Implement Workflow:
Something along these lines:
1. PISP calls `PATCH (instead of PUT) /consentRequests/{id}` with a valid OTP (ref: https://github.com/mojaloop/pisp/blob/master/docs/linking/README.md#142-otp)
    - PISP Outbond interface ----- switch ----> Inbound DFSP
    - Listen on RegisteredConsent @ Redis and when receive the notification returns sync response 
2. DFSP recognizes that this is a valid OTP 
    - Inbound DFSP ----> backend (synchronous call to validate OTP)
    - invalid OTP ---> PUT /consentRequests/{id}/error to PISP (#1996)
3. DFSP issues a `POST /consents`
    - Inbound DFSP -> switch POST /consents (sdk ThirdpartyRequests)
4. PISP receives `POST /consents` and notes any updates to scopes object
   - PISP Inbound  ---- Consent to be stored @ auth-service 
   - PISP Inbound - publish RegisteredConset @ Redis
- [x] E2E tests in docker-local

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] E2E tests in PISP pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
