### ISSUE TITLE
Follow up on Merging CGS feature to master branches #1945 with non-urgent pending updates

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#2003]
## **Goal**:
`As a`Mojaloop Scheme, based on previous tests and observations from story #1945
`I want to` fix non-urgent issues in __central-settlement__ while introducing the Continuous Gross Settlement (CGS) model / feature
`so that` Central-Settlement is aligned with best OSS practices and standards

**Acceptance Criteria**:
- [x] All the sub stories are captured on board

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] covered by PR: https://github.com/mojaloop/central-settlement/pull/344/files
  - [x] create a check for settlement model is CGS, based on the settlement model properties
  - [x] Re-factor CGS handler to operate correctly when only deferred-net is configured
  - [x] CGS processing should only be based on the configured settlementModels (i.e. it should only process transfers of the configured CGS currencies on the system, and ignore other currencies configured for deferred-net)
- [ ] ~STORY to Split out CGS and InterchangeFee Capabilities~ #2056
- [ ] ~STORY Central-Settlement: Refactor TransferSettlement handler to align with the OSS standards and architecture~ #2057 
- [ ] ~STORY Move postman CGS tests to TTK~ #2061 
- [ ] ~STORY Create a demo video for CGS (using TTK)~ #2062
  - [ ] ~Messaging around usage of Postman, maintenance and TTK as standard validation tool~
----------------------------
- Technical Debt
  - [ ] ~STORY to realign settlement and admin apis~ #2063
  - [ ] ~STORY change the assertion framework in the narrow integration scripts to be jest~ #2095 
  - [ ] ~STORY for event-sdk implementation in the central-settlement~ #1956 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- [ ] #2056 
- [ ] #2057 
- [ ] #2061 
- [ ] #2062 
- [ ] #2063 
- [ ] #1956
- [ ] #2095 

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Thanks Valentin for creating the follow-up stories
