### ISSUE TITLE
add PR request title check to all core repos

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2004]
## **Goal**:
`As a` oss maintainer

`I want to` enforce conventional commit titles on github PRs
  
`so that` we can start to automate releases

**Acceptance Criteria**:
- [ ] PR title check applied to all repos
---

**Tasks**:
- [ ] add the [Pr title check](https://github.com/mojaloop/ci-config#mojalooppr-tools) orb from Mojaloop's set of circleci orbs
- [ ] update ci/cd files where required
- [ ] apply to the following repos:
    - [ ] account-lookup-service
    - [ ] bulk-api-adapter
    - [ ] central-event-processor
    - [ ] central-ledger
    - [ ] central-object-store
    - [ ] central-settlement
    - [ ] email-notifier
    - [ ] event-sidecar
    - [ ] event-stream-processor
    - [ ] finance-portal-backend-service
    - [ ] finance-portal-ui
    - [ ] ml-api-adapter
    - [ ] ml-operator
    - [ ] ml-testing-toolkit
    - [ ] ml-testing-toolkit-ui
    - [ ] mojaloop-simulator
    - [ ] operator-settlement
    - [ ] quoting-service
    - [ ] sdk-scheme-adapter
    - [ ] settlement-management
    - [ ] simulator
    - [ ] transaction-requests-service
    - [ ] apm-agent-nodejs
    - [ ] apm-agent-nodejs-opentracing
    - [ ] central-services-auth
    - [ ] central-services-database
    - [ ] central-services-error-handling
    - [ ] central-services-health
    - [ ] central-services-logger
    - [ ] central-services-metrics
    - [ ] central-services-shared
    - [ ] central-services-stream
    - [ ] event-sdk
    - [ ] finance-portal-lib
    - [ ] ml-number
    - [ ] ml-schema-validator
    - [ ] ml-testing-toolkit-shared-lib
    - [ ] postman
    - [ ] sdk-standard-components
    - [ ] api-snippets
    - [ ] documentation
    - [ ] helm
    - [ ] mojaloop-specification
    - [ ] hackathon
    - [ ] hackathon-docs
    - [ ] mojaloop-business-docs

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/event-stream-processor/pull/33
- [ ] https://github.com/mojaloop/finance-portal-ui/pull/54
- [ ] https://github.com/mojaloop/settlement-management/pull/20
- [ ] https://github.com/mojaloop/event-sdk/pull/47
- [ ] https://github.com/mojaloop/operator-settlement/pull/19
- [ ] https://github.com/mojaloop/central-services-metrics/pull/139
- [ ] https://github.com/mojaloop/documentation/pull/298
- [ ] https://github.com/mojaloop/event-sidecar/pull/30
- [ ] https://github.com/mojaloop/simulator/pull/214
- [ ] https://github.com/mojaloop/finance-portal-backend-service/pull/60
- [ ] https://github.com/mojaloop/central-settlement/pull/341
- [ ] https://github.com/mojaloop/quoting-service/pull/256
- [ ] https://github.com/mojaloop/transaction-requests-service/pull/64
- [ ] https://github.com/mojaloop/ml-api-adapter/pull/466
- [ ] https://github.com/mojaloop/helm/pull/415
- [ ] https://github.com/mojaloop/mojaloop-simulator/pull/88
- [ ] https://github.com/mojaloop/sdk-scheme-adapter/pull/247

## **Follow-up**:
- The following core- repos need to be updated to the circlei 2.1 template:
    - [ ] central-object-store
    - [ ] central-services-auth
    - [ ] central-services-database
    - [ ] central-services-error-handling
    - [ ] central-services-health
    - [ ] central-services-logger
    - [ ] central-services-shared
    - [ ] central-services-stream
    - [ ] finance-portal-lib
    - [ ] ml-number
    - [ ] ml-schema-validator
    - [ ] ml-testing-toolkit
    - [ ] ml-testing-toolkit-shared-lib
    - [ ] ml-testing-toolkit-ui
    - [ ] mock-pathfinder
    - [ ] mojaloop-specification
    - [ ] postman
    - [ ] sdk-standard-components
    - [ ] test-scripts

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
I've started opening the mass PRs, will open the rest once the first few get approved.
