### ISSUE TITLE
PI 13 - Mojaloop Platform Quality and Security Initiative

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#2005]
Continuously improve the Trust (reliability, transparency, privacy, quality, and security) of the Mojaloop System by supporting both functional and non-functional requirements of the project, working alongside other workstreams & various governance committees on a shared responsibility model.

PI 13 Objectives:

1. Enhance security in new functionality additions
2. Support major implementations
3. Improve data protection measures and controls
4. Baselining of Mojaloop against industry standards
5. Maintain and enhance secure DevOps/CI-CD practices
6. Improve communication and community engagement
7. Improve access control measures
8. Tackle infrastructure security starting with a cloud-based PAAS Model
9. End to end Hub Security Monitoring and Management
10. Test approved standards in a lab environment
11.  Support Product Roadmap

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- 

1. [ ] IAM Epic [ @bukasaaime ]
2. [ ] DevSecOps Epic [ @lewisdaly ]
3. [ ] Implementation Support [ @godfreykutumela ]
4. [ ] Community Engagement [ @godfreykutumela ]
5. [ ] CQS Lab Testing [ @rasputtintin @bukasaaime @pedrosousabarreto ]
6. [ ] Data Protection Epic [ @rasputtintin ]
7. [ ] Product Council and Functionality Support [@godfreykutumela ]
8. [ ] Standard Baseline [@godfreykutumela ]
9. [ ] Infrastructure Secuirty Epic [ @godfreykutumela ]
10. [ ] Security Monitoring Epic (App first then Hub Operations) [ @godfreykutumela ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @kjw000
