### ISSUE TITLE
ML OSS: Testing tool-kit [PI-13]

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2006]
**Testing Toolkit Objectives for PI13**:

- [x] 1. Distributing TTK as native desktop application for different platforms​ #2007 
- [ ] 2. Demonstration capabilities to demonstrate
  - [x] P2P
  - [x] PISP
  - [x] Settlement (DMLNS)
  - [ ] Settlement (CGS)
  - [ ] Merchant Request to Pay
  - [x] Capability to show accounts, balances, etc (to support Settlement demos)
- [x] 3. TTK as an FSP interacting with a Hub over mTLS​ (need Payment Manager to be OSS)
- [x] 4. Improve reliability of tests
  - [x] UI status sync-ing issues with backend state? More consistency needed
- [x] 5. Improve end-to-end test coverage (exhaustive tests for API conformance)
- [x] 6. General maintenance
  - [x] Bug fixes
  - [x] Releases
  - [x] Test case maintenance, management
- [ ] 7. Automatic API provisioning for async APIs​
- [ ] 8. Event Framework integration [Stretch]
- [ ] 9. Documentation on Test cases - metrics on coverage and grouping​ [Stretch]
- [ ] 10. UI testing (testcafe usage) [Stretch]

Follow-up to:  #1767
