### ISSUE TITLE
TTK - Distributing TTK as native desktop application for different platforms​

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2007]
## **Goal**:
`As a` user (QA/Dev/Produc/Business/Hub Operator) of mojaloop implementation

`I want to` be able to download TTK locally
  
`so that` I can test my implementation or explore use cases

**Acceptance Criteria**:
- [x] TTK binaries are available for the following platforms
  - [x] MacOS
  - [x] Windows
  - [x] Linux

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [x] Try to compile the TTK backend service as binary (Using pkg is one option, can refer genexec script in package.json)
- [x] Handle issues related to custom functions
- [x] Include pre-built TTK frontend files in the express server of TTK backend
- [x] Test with multiple platforms
- [x] Add CICD step to compile, package and attach binaries in a release

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] E2E Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/138

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
Thought the issue is with docker memory allocation and tried to change the resource_class in circleCI, I think due to our plan I can not use medium+ or large resource class for docker execution in circle CI.

**Comment by vijayg10** [comment]
The I tried to use the node option `NODE_OPTIONS=--max_old_space_size=4096`. But it didn't make any difference.

**Comment by vijayg10** [comment]
Then came across this page https://support.circleci.com/hc/en-us/articles/360038192673-NodeJS-Builds-or-Test-Suites-Fail-With-ENOMEM-or-a-Timeout

**Passing `--maxWorkers=2` to jest command did the trick.**

The problem is solved now. Jest is getting the CPU count of real physical machine instead of CPU count of docker VM. So the real CPU count is very high, it is starting those many workers to run the unit tests, hence the problem with "Out of memory".
