### ISSUE TITLE
TTK CLI - Proper progress updates during test execution

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2008]
## **Goal**:
`As a` individual implementer

`I want to` be able to see the progress in the test execution through CLI
  
`so that` I can debug incase of any issue

**Acceptance Criteria**:
- [x] CLI should output the progress of the test execution properly like web UI

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Make CLI client to show the progress of the updates [@oderayi]
  - [x] Add Configuration parameter to specify the verbosity level [@oderayi] 
  - [x] Based on the verbosity level, display the incoming socket messages (Progress updates) [@oderayi] 
    - [x] Test case wise
    - [x] Request wise
    - [x] Assertions wise
    - [x] Only failures ...etc
- [x] Show S3 URL on output if enabled

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/139

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @mdebarros
