### ISSUE TITLE
[ci/cd] - Automate releases for `core-` repos

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2010]
## **Goal**:
`As an` OSS developer

`I want to` automate the releases of the core- mojaloop repos
  
`so that` I can deliver patches and updates super fast, with minimal management overhead

**Acceptance Criteria**:
- [ ] automated releases enabled on all core repos

**Complexity**: High - this is fiddly work

**Uncertainty**: Low - we've done this before, plenty of times
---

**Tasks**:
- [ ] make a circleci orb that generalizes our existing automated release pattern (see thirdparty-api-adapter, thirdparty-scheme-adapter, api-snippets)
- [ ] apply to all `core-package` repos: https://github.com/search?q=topic%3Acore-package+org%3Amojaloop+fork%3Atrue
- [ ] apply to all `core-docker` repos: https://github.com/search?q=topic%3Acore-docker+org%3Amojaloop+fork%3Atrue
- [ ] apply to all `core-spec` repos: https://github.com/search?q=topic%3Acore-spec+org%3Amojaloop+fork%3Atrue
> Note: out of `core-spec` only documentation may apply...

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
As mentioned on our call recently, I think this not worth putting too much effort into until after we have a better picture of the updated reference architecture.
