### ISSUE TITLE
Review existing CI/CD code and repository Scanning policies with aim to update existing policies

### ISSUE THREAD

**Issue by rasputtintin** [mojaloop/project#2018]
## **Goal**:
`As a` hub security operator 

`I want to` ensure that CI/CD scanning scripts and tools used within Mojaloop development environment are up to date and relevant based on best practice standards.
  
`so that` Mojaloop can have assurance of the security of the code packages being deployed and released to the public repository.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rasputtintin 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
Duplicate
