### ISSUE TITLE
Document existing policies and controls on code generation and storage, identify gaps, applicable standards and make recommendations 

### ISSUE THREAD

**Issue by rasputtintin** [mojaloop/project#2019]
## **Goal**:
`As a` hub security operator 

`I want to` document existing policies and controls around code generation and storage.
Identify applicable standards and use them to establish gaps and
make recommendations for improvement.
  
`so that` Mojaloop can have assurance of the security of the code packages being deployed and released to the public repository.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rasputtintin 
- QA/Review: @godfreykutumela
