### ISSUE TITLE
2.4.40.01 CI/CD Pipeline for ML-API-Adapter

### ISSUE THREAD

**Issue by ksatya77** [mojaloop/project#202]
**Goal**:
As a developer
 of ML-API-Adapter service, I want to implement CI/CD pipeline for this service
so that running unit, functional, integration and spec tests can be automated, along with deployment.

**Tasks**:
- [x] Enable CircleCI2.0 (workflow based) for ml-api-adapter [ @elnyry ]
- [x] Ensure unit, functional and integration tests run [ @elnyry ]
  - [x] Run tests locally
  - [x] Enable scripts and check runs in CircleCI
- [x] ~Add CI/CD scripts (integration, functional runner)~ [Sam: Were already added by Shashi/Murthy]
- [x] Update CI/CD scripts  [@elnyry]
  - [x] integration runner
  - [x] functional runner
  - [x] Coverage tests failing (debugging)
  - [x] PR raised
- [x] Add Helm chart [@ksatya77]

**Acceptance Criteria**:
- [x] CircleCI config should be implemented
- [x] Workflow in CircleCI should run without issues (no issues in CI/CD, not tests as such, not including deployment)
- [x] Helm chart should be defined
- [x] Should be able to deploy to k8 aws cluster automatically

**Dependencies**:
- None currently

**Accountability**:
- Owner 
- QA/Review - @mdebarros

**Comment by elnyry** [comment]
Discussed with Murthy and Integration tests still need to be done. This is not a good time to get this done, so moving to Sprint 2.3 where things may be more completely.

**Comment by elnyry** [comment]
This can be resumed once Feature/197-notification-handler branch is merged to develop. Scripts for functional, integration and Spec tests are already present. Was able to run functional script without issues but will need to return to the others after the merging.

**Comment by elnyry** [comment]
Run from CircleCI - https://circleci.com/workflow-run/130e8a3b-9e15-4816-b8d0-0384c01b797e
