### ISSUE TITLE
TTK - Add DFSP positions to mobile simulator page

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2020]
## **Goal**:
`As a` mojaloop switch implementer

`I want to` have position / account balance update in the mobile simulator page
  
`so that` I can get timely details about the positions of DFSPs during transfers

**Acceptance Criteria**:
- [x] Mobile Simulator page should consists of the following details
  - [x] DFSP position accounts
  - [x] DFSP settlement accounts
  - [x] Net debit cap values

**Complexity**: Medium
**Uncertainty**: Medium

---

**Tasks**:
- [x] Add label for MSISDN in pinkbank fsp
- [x] Add a table contains the following details
  - [x] Position values
  - [x] Settlement values
  - [x] Net debit cap values
- [x] Make it configurable
- [x] Create a followup story for CGS related view

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/90
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/141

## **Follow-up**:
- https://github.com/mojaloop/project/issues/2104

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
