### ISSUE TITLE
TTK - Add timeout for the whole test run

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2023]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` <action>
  
`so that` <reason> 

**Acceptance Criteria**:
- [ ] Testcase execution should be terminated after certain time
- [ ] There should be default time and also the time can be supplied with the test template
- [ ] The time should be configurable from TTK UI
- [ ] The time should be configurable from TTK CLI

**Complexity**: Medium

**Uncertainty**: Medium
---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @mdebarros @elnyry-sam-k
