### ISSUE TITLE
[api-snippets] Investigate/document how to use symlinks to shorten path references when bundling snippets. 

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#2026]
## **Goal**:
`As a` developer

`I want to` have a good experience referencing api-snippets
  
`so that` integrate with it easier. 

**Acceptance Criteria**:
- [ ] Instructions add on how to use `api-snippets` with symlinks to shorten reference paths.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Investigate and document how to use symlinks to shorten path references when bundling snippets. 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
