### ISSUE TITLE
Validate CGS handlers and tests on v12.0.0 helm RC

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2027]
## **Goal**:
`As` Hub Operations team

`I want to` to be able to deploy Mojaloop using a preferred Settlement model
  
`so that` I can support a settlement model of choice (DMLNS, CGS) and deploy related handlers for this mechanism

**Note**: Though Interchange fees is not a Settlement model, this update supports it along with CGS

**Acceptance Criteria**:
- [x] Helm v12.0.0 supports setting up config for CGS, Interchange fees (config will take care of configuring, running handlers for this)
- [x] helm v12.0.0 is tested with CGS, Interchange fees tests (demo, tests provided by previous team)

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [x] Enable settlement handler and other services needed for CGS
- [x] Helm changes, raise PR
- [x] Potential issue - (with settlement handler for CGS attempting to settle all transfers) -- needs to be analyzed, fixed
- [x] Test with Postman collections
  - [x] demo collection
  - [x] TIPS collection for CGS, Interchange fees tests
  - [x] PR raised on postman repo

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/424
- [x] https://github.com/mojaloop/postman/pull/197

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
