### ISSUE TITLE
Add a signature verification function

### ISSUE THREAD

**Issue by bukasaaime** [mojaloop/project#2028]
## **Goal**:
Develop a Signature Verification function within Mojaloop.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: High. This is a complex cryptographic function.
**Uncertainty**: Medium. Integration and time constraint.
---

**Tasks**:
- [ ] design signature verification microservice to be exposed to other Mojaloop services. @bukasaaime 
- [ ] attached microservice to AWS KMS signature function. @bukasaaime 
- [ ] generate private / public key pair using javascript client. @bukasaaime 
- [ ] provision a database (AWS DynamoDB) to store certificates. @bukasaaime 
- [ ] demonstrate FIDO registration function (verify signature generated by a javascript client.@bukasaaime

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @bukasaaime 
- QA/Review: @godfreykutumela

**Comment by bukasaaime** [comment]
1. Architecture design for CPM

![image](https://user-images.githubusercontent.com/33176495/110318712-81c8fa00-8016-11eb-861b-d32516e29bae.png)


2. Definition of CPM namespace in k8s-tanuki-qa1
3. Development done on AWS to expose AWS KMS signature verification function endpoint.
4. AWS Dynamo DB to store certificates for signature verification.
5. Defining CPM pod with express.js. Expose signature verification service.
Demo setup
6. Developing Relaying Party application to generate FIDO ECC key pair. Public key to be stored in Dynamo DB.
7. Developing user FIDO handle function
8. Developing FIDO random number challenge function.
9. Defining FIDO user DB in AWS Dynamo DB.

**Comment by millerabel** [comment]
While it may seem convenient to use AWS DynamoDB, our design philosophy is to remain hosting agnostic. We support both on-premises and cloud hosting and we do not require a specific cloud platform.

Please consider another key-value pair NoSQL DB that can be hosted on premises and that has cloud hosting support from more than just Amazon.

This strategy suggests that our CRUD ops on this data store are abstract so an adopter can still use DynamoDB, if they choose to, but are not required to. Or they might choose Azure Cosmos DB or Mongo DB.

— Miller

On Mar 8, 2021, at 4:10 AM, bukasaaime <notifications@github.com> wrote:

﻿
Architecture design for CPM


Definition of CPM namespace in k8s-tanuki-qa1
Development done on AWS to expose AWS KMS signature verification function endpoint.
AWS Dynamo DB to store certificates for signature verification.
Defining CPM pod with express.js. Expose signature verification service.
Demo setup
Developing Relaying Party application to generate FIDO ECC key pair. Public key to be stored in Dynamo DB.
Developing user FIDO handle function
Developing FIDO random number challenge function.
Defining FIDO user DB in AWS Dynamo DB.

**Comment by bukasaaime** [comment]
You are correct Miller. I will introduce a persistence service (layer) that will talk to a DB container that is supported by Kubernetes. 

The first in mind is the MongoDB (and claim volumes that are hosted either on prem or cloud. AWS cloud in this case).   

Regards,

Aime

**Comment by bukasaaime** [comment]
1. Testing FIDO basic Server and CPM Signature verification function on Docker.
2. Preparing CPM low architecture.
3. Preparing FIDO Server low level architecture.

**Comment by godfreykutumela** [comment]
Move images from docker to cluster
