### ISSUE TITLE
Automated Contract Testing for Mojaloop API - /participants/{TYPE}/{ID} endpoint [13]

### ISSUE THREAD

**Issue by ksatya77** [mojaloop/project#203]
**Goal**:
As a _Test Engineer_
I would like to _automate testing /participants/{TYPE}/{ID} endpoint in the Mojaloop API_ 
so that _User Onboarding business feature is tested end-end_.

**Tasks**:
- [x] Define Gherkin Scenarios covering positive and negative scenarios for:
  - [x] POST /participants/{TYPE}/{ID}
  - [x] GET /participants/{TYPE}/{ID}
  - [x] DELETE /participants/{TYPE}/{ID}
- [ ] Define StepDefinitions implementing the above Gherkin scenarios for:
  - [x] POST /participants/{TYPE}/{ID}
  - [x] GET /participants/{TYPE}/{ID}
  - [x] DELETE /participants/{TYPE}/{ID}
- [x] Across all the above endpoints positive and negative test cases for field lengths, data-types, required/optional fields for requests and responses to be defined and implemented.

**Acceptance Criteria**:
- [x] Tested positive and negative scenarios for the below endpoints, and the results are available as part of Cucumber Report.
  - [x] POST /participants/{TYPE}/{ID}
  - [x] GET /participants/{TYPE}/{ID}
  - [x] DELETE /participants/{TYPE}/{ID}
- [x] Across all the above endpoints the following Headers are accepted and processed by the application: Content-Type
Date
X-Forwarded-For
FSPIOP-Source
FSPIOP-Destination
FSPIOP-Encryption
FSPIOP-Signature
FSPIOP-URI
FSPIOP-HTTP-Method
- [x] For Negative Test Cases, the application returns the appropriate error code as defined below in the API Specification:
  - [x] 400
  - [x] 401
  - [x] 403
  - [x] 404
  - [x] 405
  - [x] 406
  - [x] 501
  - [x] 503
- [x]  All the test cases defined and implemented in Cucumber should run automatically without any manual intervention

**Dependencies**:
- [x] #193 

**Accountability**
- Owner @sri-miriyala 
- Review **Design Authority**
