### ISSUE TITLE
2.4.01 Create Integration Tests for Common Streaming Library

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#204]
**Goal**:
As a developer using the Common Streaming Library
I want Integration tests to insure that the Integration aspect of the Streaming Library are properly tested
so that it can be included in the CI/CD pipeline

**Tasks**:
- [ ] Create Common Streaming Library Integration tests (based on the reviewed approach #238 )
- [ ] Updated CircleCI v2.0 config to include Integration Tests

**Acceptance Criteria**:
- [ ] Integration tests are available for the Common Streaming Library
- [ ] CI/CD executes Integration Tests as part of the pipeline

**Dependencies**:
- [ ] Strategy for testing Kafka (with monitoring)

**Accountability**:
- Owner 
- QA/Review
