### ISSUE TITLE
2.4.25.20 Implement TransferHandler for prepare process [13, 13]

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#205]
**Goal**:
As a developer I would like to
_implement TransferHandler in upgraded code_
so that the notifications are sent and acknowledgements from FSPs are handled for prepares.

**Tasks**:
- [x] Add changes to default.json  [@bothadeon]
- [x] Add code changes to handler.js [@bothadeon , @rmothilal, @mdebarros]
- [x] Add event DAO [@bothadeon, @rmothilal]
- [x] Resolve issue with 'Cannot find' Async Module after branching code[@bothadeon , @rmothilal]
- [x] Consume events from the transfers topic (using the 'common streaming library')[@bothadeon, @rmothilal]
- [x] Send notifications  [@bothadeon, @rmothilal]
- [x] Add Unit tests @rmothilal
- [x] Add Integration tests @bothadeon @rmothilal
- [x] Set up functional test env using the test producer. [@bothadeon, @rmothilal]
- [ ] Merge the PR

**Acceptance Criteria**:
- [x] The new base code has prepares implemented with the latest design using the 'common library'
- [x] Notifications for each FSP are placed on the notification topic
- [x] Implement functionality based on sequence diagrams for TransferHandler (except batch and event logging)
- [x] Unit tests are available to test the TransferHandler
- [x] Integration tests are available to test the TransferHandler

**Dependencies**:
- [x] #154 
- [x] #151 

**Accountability**
- Owner @bothadeon 
- Review

**Comment by bothadeon** [comment]
Postman : Register all handlers.
![Screen Shot 2018-05-17 at 12.22.12.png](https://images.zenhubusercontent.com/5a8acccb4b5806bc2bc777a7/bda7510b-f9af-4df8-99f3-ab7d863b46c1)
