### ISSUE TITLE
Review Mojaloop Security Course 104 and align it with the MPQS work

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#2050]
## **Goal**:

`As a` OSS developer

`I want to`  Mojaloop Security Course 104 and align it with the MPQS work 
  
`so that` we can ensure the consistency of our messages to the community

**Acceptance Criteria**:
- [ ] Well defined set of proposed amendments to the course content

**Complexity**: Low - It is just a training review exercise nothing complex at all

**Uncertainty**: Low - We will definitely archive the objectives without any huddles.

---

**Tasks**:
- [ ] Review the training in detail @godfreykutumela 
- [ ] Identify areas of the course which requires alignment @godfreykutumela 
- [ ] Propose amendments to the training owners @godfreykutumela 

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
Overall the training is fine and very informative, and below are few pointers to factor into the next version:

1. I would redo the first section on payment risks to focus only on technology-related ones and exclude payment system operational risks. Also, we demonstrate how we are addressing each of the technical payment threats in the rest of the training modules
2. We should separate OSS switch level controls from the hub implementation controls - To clear a line of separation
3. Get input from the MPQS regarding some of the newly added controls - Not all our controls are covered
4. coupler repetitions are trying to explain the confidentiality, integrity and non-repudiation - We can help on this in the next version
5.  Comments regarding  VPN/ TLS should be removed.
6.  The use of IP whitelisting in addition to MTLS is not necessary - An MTLS based connection is meant to avoid the use of network boundaries, so this should be removed as control over and above MTLS 
7. Almost all controls are highlighted as providing the confidentiality, integrity, and non-repudiation payments, and I suggest we should relook at this and only include relevant ones per each of the 3 areas.

Also we could include a lot info from the MPQS documentation so please consult with us in preparing the next version of this training Module 104
