### ISSUE TITLE
Continue to monitor and benchmark against the Open-Source Security Foundation (OpenSSF) work

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#2052]
## **Goal**:
`As a` OSS developer

`I want to` continuously monitor the Open-Source Security Foundation (OpenSSF) work output.
  
`so that I can benchmark Mojaloop against one of the most recent and most significant open-source security initiative globally (OpenSSF)

**Acceptance Criteria**:
- TBD

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] Review daily email updates [ @godfreykutumela 
- [ ] Attend some of the working groups meetings [ @godfreykutumela ]
- [ ] Identify areas of common synergies to baseline ML against [ @godfreykutumela ]
- [ ] Define next steps on areas of interest [ @godfreykutumela ]

**Done**
- [ ] Acceptance Criteria pass

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
Hi @rasputtintin Can we resusitate this issues and perform a benchmark analysis of Mojaloop against the OpenSSF

**Comment by godfreykutumela** [comment]
We didn't find this relevant to the Mojaloop project and we can re-open when needed!
