### ISSUE TITLE
Deploy Mojaloop into MPQS Lab

### ISSUE THREAD

**Issue by rasputtintin** [mojaloop/project#2055]
## **Goal**:
`As a` security officer

`I want to` deploy Mojaloop into the CQS test lab
  
`so that` I can understand and review security of configurations and components deployed in a Mojaloop instance and make recommendations based on best practice standards around confidentiality, integrity and availability including audit trails.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High> We are learning the deployment process and following the documented runbook

**Uncertainty**: <Medium> There may be support requirements from Mojaloop team.

---

**Tasks**:
- [x] Review Mojaloop deployment documentation [ @rasputtintin ]
- [x] Deploy Mojaloop instance [ @rasputtintin ]

**Done**
- [x] Acceptance Criteria pass
- [x] Successful deployment
- [ ] Document scope of security review areas.
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by rasputtintin** [comment]
Task completed.
1 - Deployed Mojaloop instance
2 - Executed Helm testing -> PASS
3 - Deleted and redeployed instance -> PASS

**Comment by rasputtintin** [comment]
Duplicate story. this is covered in more detail in #1779
