### ISSUE TITLE
Central-Settlement: Create settlement rules handler

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#2056]
## **Goal**:
`As a` Mojaloop Developer

`I want to` create Settlement rules handler into the Central Settlements service
  
`so that` user can apply own rules for fees triggered in Settlement schemes the same way the Interchange fee has been done in the CGS model

Problems: 
 - Tight coupling: Currently, if Rules processing fails, CGS fails, which is not desirable
 - Rules are applied only in CGS and if transfer is COMMITTED
 - No validation both on rule loading and rules results
 
**Acceptance Criteria**:
- [ ] Rules engine is separated from transferSettlement handler
- [ ] Rules engine starts up with no configured rules elegantly
- [ ] Rules engine validates rule-files before loading them and provides appropriate error on validation failure
- [ ] Rules engine includes validations to ensure that each output “ledger entries” can be inserted successfully, and if not must be handled appropriately
- [ ] Documentation/Designs for settlement rules are up to date
- [ ] Current CGS/Interchange fees tests are passing correctly with the same rule
- [ ] Golden path is passing with deferred net settlement model
- [ ] ~helm chats are updated for the new settlement rules handler~ 

**Complexity**: Medium 

**Uncertainty**: Medium > We will reassess after the design/workshop

---

**Tasks**:
- [x] Separate the rules handler from the CGS handler -[@shashi165]
- [x] unit tests -[@shashi165]
- [x] Update exiting designs/documentation for the CGS handler -[@shashi165]
- [x] Update exiting designs/documentation for the rules handler -[@vgenev @shashi165]
- [x] workshop on validation rules about the ledger entries
- [x] Document rules engine, and how to create/define rules with examples, etc [@vgenev @shashi165 ]
- [ ] ~Update the helm charts for the new rules handler~ [@vgenev] new story created #2117
- [ ]  ~move out configurations from source to config file: https://github.com/mojaloop/central-settlement/pull/338#discussion_r563691339~ moved to #2057

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/central-settlement/pull/346
- [ ] https://github.com/mojaloop/documentation/pull/304

## **Follow-up**:
- #2057 #2117 

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
