### ISSUE TITLE
Central-Settlement: Refactor handlers model and domain to align with the OSS standards and architecture

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#2057]
## **Goal**:
`As a` Mojaloop Developer

`I want to` Ensure that all the handlers have clearly separated business logic (domain) from data access (model), use enums from central-services-shared library and expose only service API endpoints
  
`so that` central-settlement service follows OSS standards for code structure and separation of concerns

**Acceptance Criteria**:
- [x] Service Domain layer contains all logic required to process the request from a functional perspective
- [x] Model layer cares only for database access
- [x] All constants are loaded from config or central-services-shared library
- [x] Handlers expose only /health and /metrics api
- [x] Rename the `transferSettlement` handler to `grossSettlement` handler
- [x] Rename the `settlementWindow` handler to `deferredSettlement` handler

**Complexity**: Low 

**Uncertainty**: Low

---

**Tasks**:
- [x] Move all business logic out of the model to domain layer
- [x] align both the client.id and group.id to match the name of the settlement handler
- [x] use ENUMS instead of 'GROS, 'SETTLED' and others if any
- [x] expose only /health and ~/metric~ operations on handlers APIs - _/metric_ is not available in the whole service atm
- [x] Rename the `transferSettlement` handler to `grossSettlement` handler
- [x] Rename the `settlementWindow` handler to `deferredSettlement` handler
- [x] move out configurations from source to config file: https://github.com/mojaloop/central-settlement/pull/338#discussion_r563691339

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/central-settlement/pull/347

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
