### ISSUE TITLE
[docker-live] Merge pisp changes for central-ledger, account-lookup-service and update

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2058]
## **Goal**:
`As a` user of mojaloop helm charts for local testing
`I want to` be able to deploy `docker-live` helm charts alongside an existing switch
`so that` I can demonstrate the PISP functions with mainstream Mojaloop

**Acceptance Criteria**:
- [ ] docker-live is deployable alongside `mojaloop/helm` charts for easy installation of PISP functionality

**Complexity**: High - Lots of moving parts here
**Uncertainty**: Medium

---

## Example Proposed Component diagram:

![PISP Mega Board - PISP middle architecture.jpg](https://images.zenhubusercontent.com/5cd963af3613073e20e46e60/be88d270-1b7d-48e6-bb66-85e4cd29849a)

**Tasks**:
- [x] merge `central-ledger` upstream with core Mojaloop
    - [x] ensure that we aren't breaking anything
    - [x] investigate feature switches if required to make the PISP stuff configurable from ENV vars
- [x] merge `account-lookup-service` upstream with core Mojaloop
    - [x] ensure that we aren't breaking anything
    - [x] investigate feature switches if required to make the PISP stuff configurable from ENV vars
      e.g.
      - `FEATURE_ENABLE_DETAILED_ACCOUNT_LOOKUP`
      - `FEATURE_ENABLE_EXTENDED_PARTY_ID_TYPE`
     
- [x] close the `pisp/master` branch and remove old ci/cd config for:
    - [ ] central-ledger
    - [x] account-lookup-service
- [x] update the docker-local `docker-compose.yml` config after these services have been redeployed, and make sure nothing breaks
- [x] update `docker-live` to be able to deploy "alongside" the mojaloop helm charts
- [ ] test the Mojaloop Golden Path, alongside the PISP Tests 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by kleyow** [comment]
Time boxing this ticket.
- Couldn't delete central-ledger pisp/master with my permissions. It's a protected branch. @lewisdaly 

- test the Mojaloop Golden Path, alongside the PISP Tests

While our PISP tests pass. Running the postman golden path against our sandbox is quite a nightmare with configuration. README instructions are old and it's very hard to tell whats going wrong when tests actually do start running. I think this is a ticket on its own.

**Comment by lewisdaly** [comment]
Thanks @kleyow, I can go ahead and delete `pisp/master` on central ledger - should I also do the same for account-lookup-service?

I agree with you re. PISP Golden path tests - perhaps a 'good enough' approach for this is to take the latest helm deployment, deploy it with the updated central-ledger and account-lookup-service images, and make sure the golden path tests pass.

I'm happy to close this one here - can you please make a ticket re. those tests and assign it to me?

**Comment by kleyow** [comment]
>  I can go ahead and delete pisp/master on central ledger - should I also do the same for account-lookup-service?

Just central-ledger. I was able to delete ALS myself.

> I'm happy to close this one here - can you please make a ticket re. those tests and assign it to me? 

Will do.

**Comment by lewisdaly** [comment]
Hmm, I can't see `pisp/master` on central-ledger

**Comment by kleyow** [comment]
@lewisdaly Wires crossed.

I was unable to delete ALS pisp/master. central-ledger was the one I was able to delete.

**Comment by lewisdaly** [comment]
Haha I should've checked the other one. Done now.
