### ISSUE TITLE
[docker-live] - Get demo up and running on the OSS-Sandbox

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2059]
## **Goal**:
`As a` potential adopter
`I want to` be able to see the PISP Demo App running against the OSS Sandbox
`so that` I can understand and see a real use case of PISP working

**Acceptance Criteria**:
- [x] Lesley-Ann is able to install the PISP Demo App (or simulate it on a computer)
- [x] Able to complete demo account linking flows with TTK
- [ ] Able to complete transfer flows against OSS Sandbox, sending to any Payee DFSP

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

## Proposed Architecture

![PISP Mega Board - PISP First Architecture.jpg](https://images.zenhubusercontent.com/5cd963af3613073e20e46e60/75c7122c-dacb-4753-95f0-c14609b360ba)

**Tasks**:
- [ ] customize docker-live to run alongside the vanilla mojaloop installation, and include the necessary components for the working demo
- [ ] deploy the PISP TTK config for simulating account linking flows
- [ ] deploy the firebase demo server and connect to the TTK + OSS-Lab
- [x] hook up the app to the firebase demo server and figure out how to make it easily runnable
- [ ] 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
I've got a basic P2P transfer working with the customized Mojaloop installation on local with microk8s. Next step is to get a PISP transfer working.

**Comment by lewisdaly** [comment]
PISP P2P lookup works, other bits (`POST /thirdpartyRequests/transactions` and `PUT /authorizations` are blocked by some of the sdk scheme adapter changes)

I'll move onto working on the UI side of the demo while I wait for those last few changes.

**Comment by lewisdaly** [comment]
This is blocked by some required changes for Helm, since our helm charts don't let us easily add arbitrary ENV vars into a container spec.

**Comment by lewisdaly** [comment]
I'm going to do a demo handoff tomorrow with Lesley-Ann, which will complete our above acceptance criteria.

**Comment by lewisdaly** [comment]
I talked this over with LA and Dave today - there's a few things to be tweaked before it's truly demoable - I'm capturing a list which we can share at a later date.
