### ISSUE TITLE
Determine and implement consistency for Position Update

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#206]
**Goal**:
As a developer I would like to _implement consistency for Position Update_ so that

**Tasks**:
- [ ] Determine the best approach for consistency

**Acceptance Criteria**:
- [ ] Determine the best approach for the consistency - Options: Transactionality/ Compensation/ Validation Patterns
- [ ] Update Sequence Diagrams with "consistency" change to PositionHandler with one of the three approaches: Transactionality/Compensation/Validation Patterns
- [ ] Implement the chosen approach to ensure consistency

**Dependencies**:
- [ ] #165

**Comment by elnyry** [comment]
Duplicate, covered in 2.x items (stories that start with such a number) in 3.x sprints
