### ISSUE TITLE
Move postman CGS tests to TTK

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#2061]
## **Goal**:
`As a` hub operator
`I want to` have all the test suites from the CGS donated test collection in TTK
`so that` I can use them to validate my Switch deployment in CGS settlement mode (or implementation)

**Acceptance Criteria**:
- [x] `Given` a mojaloop deployment and setup as CGS
        `When` TTK test suites for settlements are run
        `Then` we get 100% passrate and observe no regression failures
- [x] Ensure that correct TTK test cases are executed based on whether CGS is enabled or disabled(GP)

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
 - [x] Make sure postman scripts for CGS settlement are running ok [ @modusemerson @vgenev ]
 - [x] work on the script conversion [ @modusemerson ]
 - [x] make sure the assertions are passing for all tests [ @modusemerson ]
 - [x] make sure the whole CGS settlement is passing from TTK [ @vijayg10 ]
- [x] Update provisioning in TTK into 2 sub-folders:  [ @modusemerson ]
    - [x] Existing GP onboarding
    - [x]  CGS onboarding
- [x] Update GP in TTK into 2 sub-folders: [ @modusemerson ]
    - [x] Exiting GP tests
    - [x] New CGS tests
 - [x] Add TTK ENV for CGS collection [ @vijayg10 ]
   - [x] In helm mojaloop values file
   - [x] In testing-toolkit-testcases repo

**Done**
- [x] Acceptance Criteria pass
- [x] TTK Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/33
- [x] https://github.com/mojaloop/helm/commit/8bd230d999bef5abe1f7f7340c90fbf9fc8ace73
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/34
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/35

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
