### ISSUE TITLE
Create a demo video for Deferred, Continuous Settlement Models using TTK 

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#2062]
## **Goal**:
`As a` OSS Contributor

1. `I want to` Create video explaining deferred net settlement model (DMLNS) and accounts supported by Mojaloop. For the demonstration purpose we want to use TTK.
  
`so that` the Settlement process in deferred net settlement model is easy to be explained and demoed

2. `I want to` Create video explaining continuous (immediate) gross settlement (CGS) model and accounts supported by Mojaloop. For the demonstration purpose we want to use TTK.
  
`so that` the Settlement process in deferred net settlement model is easy to be explained and demoed

**Acceptance Criteria**:
- [ ] Presentation recording, explaining the deferred net settlement processes made with TTK, is recorded
- [ ] Presentation recording, explaining CGS processes made with TTK, is recorded

**Complexity**: <Medium>

**Uncertainty**: <Low>

---

**Tasks**:
- [x] Ensure we have working deployment with deferred net settlement model running
- [x] Introduction of the process with associated accounts and api calls
- [x] Record a video with TTK using Golden Path Settlements folder and demonstrating the account balances with Mobile Simulator page

**Done**
- [x] Acceptance Criteria pass

## **Pull Requests**:
- [ ] 

## **Follow-up**:
- [x] ~create separate story for CGS~ included here!

**Dependencies**:
- [x] https://github.com/mojaloop/project/issues/2020

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Great progress on this team - @vijayg10 , @vgenev , @mdebarros ..

Looks like we need a couple of slides to discuss (script) the demos and we should be done here.. I think we made twice the amount of progress we wanted to make here
