### ISSUE TITLE
Investigate solution options to prevent dependency confusion attack 

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#2064]
## **Goal**:
`As a` OSS developer

`I want to` explore options on how to securely manage packages 
  
`so that` I can reduce dependency confusion attack surface within Mojaloop

More on dependency confusion attack - https://www.bleepingcomputer.com/news/security/researcher-hacks-over-35-tech-firms-in-novel-supply-chain-attack/

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] dependency confusion attack detailed analysis
- [ ] Explore solution options
- [ ] Adopt a prevention and monitoring methods

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly @pedrosousabarreto 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
To narrow this down, we should start by looking deep at the attack vector nicely summarized by Miller Abel as "Uploading a package to NPM with the same name is not possible and that’s not the attack vector. The vector is placing a module with the same name as an NPM module somewhere else in the load path, with a higher priority than NPM or wherever the real module is. That vector has different characteristics in Deno since the resolution and loader work differently. But you can still load modules from the local file system along a path and from random remote servers. As with Node, one should obviously “not do that!”

**Comment by godfreykutumela** [comment]
Some relevant resource from Microsoft - https://azure.microsoft.com/mediahandler/files/resourcefiles/3-ways-to-mitigate-risk-using-private-package-feeds/3%20Ways%20to%20Mitigate%20Risk%20When%20Using%20Private%20Package%20Feeds%20-%20v1.0.pdf

**Comment by godfreykutumela** [comment]
@lewisdaly As discussed, let us state the potential impact and put together a mitigation plan for this attack.

**Comment by lewisdaly** [comment]
@godfreykutumela I don't think we're at risk of this.

From the first article:
> Birsan noticed some of the manifest file packages were not present on the public npm repository but were instead PayPal's privately created npm packages, used and stored internally by the company.

We have no private npm packages, everything we have is published publicly. That means that nobody can create new packages that will get loaded in with higher priority than our packages.


On a related note however, there were some more general recommendations for out build processes:

>Registries are linked to a package name scope, making npm safe for properly scoped packages. 

>Either use scopes for all private packages or override the default registry with your private registry and enable upstreams.

>Also include package-lock.json with your sources and use “npm ci” to install matching packages without performing any upgrades.

`npm ci` is one we've been adopting slowly, but it's not used everywhere just yet. They also recommend pinning to a specific version for each dependency, which we mostly do, but I have problems with because of the amount of extra work it tends to create.

**Comment by godfreykutumela** [comment]
Re-opened the issue to explore the Github solution approach to dependancy attack - https://github.blog/2021-02-12-avoiding-npm-substitution-attacks/ @lewisdaly @pedrosousabarreto please review and suggest what we should consider adopting from this.

**Comment by lewisdaly** [comment]
@godfreykutumela these are good recommendations for companies that use a mix of private and public packages.

We don't use private packages for any Mojaloop Open Source projects, so it's a nonissue.
