### ISSUE TITLE
TTK - Server logs are not displaying all the logs

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2065]
**Summary**:
TTK Serverlogs are not displaying all the logs

**Severity**:
Medium

**Priority**:
Medium

**Current Behavior**
Server logs are displaying only getparties requests and there are no logs related quotes and transfers

**Tasks**
- [x] Fix the issue
- [x] Add loading spinner to backend while getting the logs
- [x] Some cosmetic changes in showing the server logs

**Pull Requests**
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/140
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/88
