### ISSUE TITLE
TTK Tests is using hard-coded USD currency

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2066]
**Summary**:
TTK Tests is using hard-coded USD currency

**Severity**:
Low

**Priority**:
Medium

**Expected Behavior**
Hub Setup, Onboarding and Golden Path collections should utilise a configurable env variable for the currency.

**Steps to Reproduce**
  1. Run TTK collections

**Specifications**
  - Component (if known): https://github.com/mojaloop/testing-toolkit-test-cases
  - Version: v12.0.0
  - Platform: n/a
  - Subsystem: n/a
  - Type of testing: Manual
  - Bug found/raised by: @mdebarros 

**Notes**:

- Severity when opened:
- Priority when opened:

**Tasks**:
- [x] update golden path tests to take currency from the ENV variable
- [x] update onboarding collection to take currency from the ENV variable

**PRs**:
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/32
