### ISSUE TITLE
Auto-populate currency table with ISO 4217 Currency codes

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#207]
**Goal**:
As a developer I would like to __Auto-populate currency table with ISO 4217 Currency codes__ so that we associate the correct currency code to participants.

**Tasks**:
- [ ] ...

**Acceptance Criteria**:
- [x] Migration script auto populates the Currency table with ISO 4217 Currency codes
- [x] The "currencyId" column in the Currency table must be changed to a VAR Char so that it can now store to the ISO 4217 Currency codes
- [x] remove "code" column in the Currency table as this is stored in the "currencyId" field
- [ ] Update ERD diagram updates to reflect the Currency table changes

**Dependencies**:
- ...

**Comment by mdebarros** [comment]
PR: https://github.com/mojaloop/central-ledger/pull/62
