### ISSUE TITLE
Create and document a deployment of mojaloop using a secure kubernetes network policy 

### ISSUE THREAD

**Issue by tdaly61** [mojaloop/project#2074]
## **Goal**:
`As a` contributor interested in Kubernetes and ML security 

`I want to` create an example of a deployment of Mojaloop featuring a "Network policy" (as this  is the primary tool for securing a Kubernetes network) and thereby demonstrate how to limit East-West and North-South network traffic within pods of the K8S cluster and to-from K8S clusters. 
  
`so that` any attack surface of Mojaloop deployments is minimised and so that anyone who deploys Mojaloop commercially will have a good starting point for their network security model.  Also  `so that` network security might become a "feature" of the Mojaloop product that is attractive to potentially risk-adverse businesses. 

**Acceptance Criteria**:
- [ ] demonstrate fully functioning mojaloop deployment i.e. passing all golden path tests using both MiniLoop plus a cloud deployment (which cloud ?) 
- [ ] passing a formal security review which includes appropriate sections of the CIS benchmark for K8S network security.

**Complexity**: <High|Medium> > completing the tasks associated with this project are actually envisaged as being fairly straight-forward i.e. finding and restricting network paths on the existing flat network that are not required for full functioning of the mojaloop code.  Of medium complexity is PoC modification of the helm charts to demonstrate this path restriction, also there may be unforeseen path in use today that might show the desirability of  mojaloop code changes beyond helm chart re-crafting.  What is higher complexity is keeping the security model current over the long term. 

**Uncertainty**: <Medium> > As mentioned above the main uncertainty is around process for keeping the networking model current which might involve creating standards for adding network access paths as new functions and modules are added to mojaloop. 

---

**Tasks**:
- [ ] update MiniLoop to use latest versions of MojaLoop, linux, helm , postman , npm and test data [ @? ]
- [ ] initially using calico, implement policies in the MiniLoop deployment of Mojaloop that and restrict north south traffic to the ingress only i.e. ingress -> pods 
- [ ] initially using calico implement policies in the MiniLoop deployment of Mojaloop that prevent any-to-any pod communication and then develop the required pod access policies that allow full functioning of Mojaloop. 
- [ ] determine  appropriate RBAC and namespace requirements to support this North-South and East-West traffic restriction
- [ ] perhaps in parallel with the above tasks update the helm charts and MiniLoop automated deployment so as to make this environment easily accessible for security review
- [ ] Due to the possible differences in K8S CNI implementation , implement these same network restrictions on a yet to be determined cloud provider either using their K8S engine.  
- [ ] Document the network policy so that it can be generically applied to any cloud provider or any on premise deployment.

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @tdaly61 Tom Daly is volunteering to do the main work here on this POC
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
Hi @tdaly61 Just checking where did we end with this issue? Any documentation that was produced that we can preserve for future use?
