### ISSUE TITLE
PISP get a list of DFSPs that support PISP features

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2079]
## **Goal**:
`As a` PISP's user

`I want to` be able to view a list of DFSPs who support PISP feature
  
`so that` I can select my DFSP and start the linking process

**Acceptance Criteria**:
- [ ] ability for a PISP to lookup a list of DFSPs who support linking
- [ ] support from 3p-scheme-adapter to make this lookup synchronous

**Complexity**: Medium - Lots of pieces

**Uncertainty**: Low - using static config, doesn't sound too hard

---

**Tasks**:
- [ ] on the 3p-api-adapter, implement the `GET /services/THIRD_PARTY_DFSP` endpoint, which will return a list 
    - see: https://github.com/mojaloop/pisp/tree/master/docs/linking#11-pre-linking
- [ ] allow the list of DFSP ids to be populated using Convict config
- [ ] return an error callback (`PUT /services/<TYPE>/error`) when:
    - [ ] the TYPE != `THIRD_PARTY_DFSP`
- [ ] implement on the 3p-scheme-adapter and expose a synchronous endpoint for this call
- [ ] add an integration test in docker-live that demonstrates the failure and success scenarios

__Out Of Scope (for this ticket)__:
- Any sort of method for a hub operator to modify this list in real time
- Any need for state - static config is just fine for now

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- [ ] Add state, and API to update this list by a Hub operator - mojaloop/project#2080

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
This is pretty low-value - I'd rather get on with other linking tickets ahead of this one.

**Comment by lewisdaly** [comment]
This has been implemented on the TTK for now.
