### ISSUE TITLE
[linking] - PISP tries to register invalid credential

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2081]
## **Goal**:
`As a` PISP's user

`I want to` be informed if there as a problem registering my credential
  
`so that` I can rectify the issue, and try linking again.

**Acceptance Criteria**:
- [ ] automated integration test case from thirdparty-scheme-adapter that demonstrates an error callback sent to PISP after calling `PUT /consents/{id}` with an invalid credential

**Complexity**: High - Lots of moving pieces

**Uncertainty**: Medium

---
When it happens:
 - user needs to register a fingerprint for Consent with DFSP

Error scenario examples:
 - invalid credential is when the challenge string is invalid
 - device used to create credential was rooted and DFSP no longer trust it

**Tasks**:
- [ ] Add a new sequence diagram (at the bottom of the [linking page](https://github.com/mojaloop/pisp/tree/master/docs/linking#11-pre-linking) that demonstrates a failure case where the credential is invalid:
    1. DFSP receives the `PUT /consents/{id}`with invalid credential
    2. DFSP sends it to the auth-service
    3. Auth-service finds it to be invalid, and replies to the DFSP with `PUT /consents/{id}/error`
    4. DFSP does any additional processing and sends a `PUT /consents/{id}/error` to the PISP
- [ ] Update thirdparty-api-adapter to handle any API changes in `PUT /consents/{id}` since the last draft
- [ ] update the thirdparty-scheme-adapter to forward the `PUT /consents/{id}` to the auth-service (mocked out by TTK)
- [ ] DFSP looks up the PISP for this consentId, and forwards the `PUT /consents/{id}/error` to the PISP
- [ ] update API-snippets with the latest auth-service interfaces, and use these interfaces to simulate the negative scenario for the auth-service with the TTK

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@lewisdaly to make a follow up story for implementing validation logic on auth-service

**Comment by lewisdaly** [comment]
For integration tests, let's use the ttk to mock out the auth-service invalid credential call

**Comment by lewisdaly** [comment]
I think this has been covered aleady.
