### ISSUE TITLE
TTK - Bulk Transfers test suite is not working

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2082]
**Summary**:
The test suite about the "Bulk Transfers" in "Load Samples" section of the TTK is not working

**Severity**:
Medium

**Priority**:
Medium

**Tasks**:
- [x] Fix the errors in the test suite
- [x] Improve the test suite execution time by using websockets

**Tasks**:
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/30
