### ISSUE TITLE
Change noresponsepayeefsp from legacy simulator to mojaloop simulator

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2085]
## **Goal**:
`As a` individual implementer

`I want to` use mojaloop simulator for noresponsepayeefsp
  
`so that` I can use the websocket functionality of the mojaloop-simulator

**Acceptance Criteria**:
- [ ] A mojaloop simulator is added to the helm chart with noresponsepayeefsp which will not respond with callbacks

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
