### ISSUE TITLE
Refactor BulkAPI to use OpenAPI Backend

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#2087]
## **Goal**:
`As a` OSS Contributor

`I want to` update the bulk-api-adapter to use OpenAPI Backend
  
`so that` it is aligned with other mojaloop APIs, we are less dependent on outside projects and the fix for unicode Regex for accented characters is also implemented.

**Acceptance Criteria**:
- [ ] bulk-api-adapter is using OSS adopted API toolchain
- [ ] all tests are passing as before
- [ ] Unicode regex can be used in bulk transfers

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
