### ISSUE TITLE
TTK - show skipped assertions with proper status

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2088]
## **Goal**:
`As a` QA

`I want to` see the skipped tests with correct status instead of PASSED status
  
`so that` I can know about the quality of my test run

**Acceptance Criteria**:
- [x] The skipped tests should be reported as skipped instead of passed.

**Complexity**: Medium
**Uncertainty**: Medium

---

**Tasks**:
- [ ] ~Try to change or make a plan to change the assertion execution logic from eval to VM~
- [x] Identify the tests ran without a single expect statement -[@shashi165 ]
- [x] Mark them as skipped and change the JSON progress events and final report format
- [x] Handle the new status "SKIPPED" in the following
  - [x] Web UI
    - [x] In each request in test case editor - [@shashi165]
    - [ ] ~Total counts at top~
  - [x] HTML reports
  - [x] TTK CLI progress events and final console report

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/92
- [ ] https://github.com/mojaloop/ml-testing-toolkit/pull/152

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
