### ISSUE TITLE
complete thirdparty API definitions

### ISSUE THREAD

**Issue by eoln** [mojaloop/project#2089]
## **Goal**:
`As a` API Client

`I want to` use thirdparty typescript interfaces
  
`so that` I want to have a consistent thirdparty API interface across all services

**Acceptance Criteria**:
- [x] all thirdparty paths defined in api-snippets
- [x] `Consent` paths on auth-service in sync with documentation or updated documentation
- [x] thirdparty-api-adapter updated
- [x] sdk-standard-components typescript defs updated for `ThirdpartyRequests` class
- [x] thirdparty-scheme-adapter updated
- [x] auth-service updated
- [x] ~~pisp-demo-server updated~~
- [x]  for all services, remove local definitions (`.d.ts`) in favour of api-snippets
- [x] all DTO re-exported
- [x] integration tests and E2E (docker-local) tests pass

**Complexity**: Low > 

**Uncertainty**: Low > 

---

**Tasks**:
- [x] all thirdparty paths defined in api-snippets
- [x] `Consent` paths on auth-service in sync with documentation or updated documentation @lewisdaly todo
  > Investigate db scheme on auth-service, and adjust if easy... or make a follow up ticket if possible
- [x] thirdparty-api-adapter updated
- [x] sdk-standard-components typescript defs updated for `ThirdpartyRequests` class
- [x] thirdparty-scheme-adapter updated
- [x] auth-service updated
- [x] ~~pisp-demo-server updated~~
  - [x]  updated defs using local paths, but require code refactoring,  will be covered as part of story #1916
- [x]  for all services, remove local definitions (`.d.ts`) in favour of api-snippets
- [x] all DTO re-exported
- [x] integration tests and E2E (docker-local) tests pass

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/api-snippets/pull/64
- [x] https://github.com/mojaloop/thirdparty-api-adapter/pull/46
- [x] https://github.com/mojaloop/auth-service/pull/61
- [x] https://github.com/mojaloop/api-snippets/pull/66
- [x] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/68
- [ ] https://github.com/mojaloop/pisp-demo-server/pull/58

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Thanks @eoln - I added a task to update the sequence diagrams for linking and transfer. Linking is pretty much 100% lined up with the latest API draft, but I think there were some resource name changes in the latest version of the draft we need to account for.

**Comment by lewisdaly** [comment]
I've added my comments to the auth-service PR
