### ISSUE TITLE
[pisp][helm] Run Golden Path tests against latest helm deployment with updated account lookup service and central ledger

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#2091]
## **Goal**:
`As a` developer

`I want to` know that my deployments are realiable 
  
`so that` no production bugs may appear.

**Acceptance Criteria**:
- [ ] Golden Path tests pass against latest deployment

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
This has been taken care of already, and will rear it's ugly head again shortly with mojaloop/project#2533 if it's a problem.
