### ISSUE TITLE
Upgrade NodeJS Version for core services

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2092]
## **Goal**:
`As a` Hub Operator

`I want to` run Mojaloop on Nodejs to v16.x LTS: https://nodejs.org/en/about/releases/
  
`so that` Mojaloop is running on the latest secure/performant Nodejs runtime.

**Notes**:

Stories needed or high level items below:

1. Documentation (Standards + Contributors Guide) on upgrade recommendations:
1.1 Use LTS
1.2 Update repos nvmrc, etc
2. Update Nodejs/Typescript Template Repos according to LTS requirements (nvm, docker, CI-CD config, etc)
3. Pick a library
3.1 central-services-logger?
3.2 central-services-shared?
3.3 central-services-metrics?
3.4 central-services-stream?
3.5 event-sdk?
4. Pick a service
4.1 ml-api-adapter?
4.2 central-ledger
5. CI/CD: Ensure images use latest LTS version
6. Update docker builds to use latest LTS Ubuntu version
7. Create stories (one each) for upgrading all repos/services part of a Mojaloop deployment

Individual stories:
- [x] core libraries - 8
  - [x] central-services-stream
  - [x] central-services-logger
  - [x] central-services-metrics
  - [x] central-services-health
  - [x] central-services-shared
  - [x] central-services-error-handling
  - [x] sdk-standard-components
  - [x] event-sdk
- [x] central-ledger
- [x] ml-api-adapter
- [x] central-setttlement
- [x] account-lookup-service
- [x] ALS oracle pathfinder
- [x] ALS consent oracle (3PPI)
- [ ] Oracle shared library (not high priority - not required for v14 release)
- [ ] ALS oracle template (not high priority - not required for v14 release)
- [x] quoting-service
- [x] transactions-requests-service
- [x] auth-service
- [x] central-event-processor
- [x] event-stream-processor
- [x] event-sidecar
- [x] TTK
  - [x] ttk toolkit
  - [x] ttk toolkit ui
  - [x] ttk shared lib
  - [x] ttk client lib
- [x] mojaloop-simulator
- [x] simulator (legacy, ALS oracle)
- [x] email-notifier
- [x] bulk-api-adapter
- [x] sdk-scheme-adapter
- [x] Helm release story for v14

**Comment by elnyry-sam-k** [comment]
Maybe it will be an Epic :-) to upgrade to v16.x.x LTS

**Comment by mdebarros** [comment]
https://nodejs.org/en/about/releases/ <--  Node v12 will lose support in April 2022.

**Comment by millerabel** [comment]
It seems a reasonable roadmap would be to move to v14 without delay, then plan to move to v16 in late January, as part of first 2022 Mojaloop functional release.

Can someone identify the breaking changes between Node v12 and v14-v16 that we will likely encounter? This would help us prioritize and map out the work.

— Miller

On Aug 16, 2021, at 1:54 AM, Miguel de Barros ***@***.***> wrote:

﻿
https://nodejs.org/en/about/releases/ <-- Node v12 will lose support in April 2022.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by elnyry-sam-k** [comment]
related DA issue https://github.com/mojaloop/design-authority-project/issues/78

**Comment by elnyry-sam-k** [comment]
Closed with #2743
