### ISSUE TITLE
TTK - Assertions on the content-type version in the callbacks generated by switch should be based on the input values

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2093]
## **Goal**:
`As a` individual implementer

`I want to` assert on the content-type header in the callbacks generated by switch using an input value
  
`so that` I can test using TTK test suite for the versions configured in my deployment

**Acceptance Criteria**:
- [ ] `Given` separte set of values available in the input values of the TTK
- [ ] `When` the switch is configured with a perticular version for the callbacks
- [ ] `Then` TTK test cases should match the 'Content-Type' header exactly equal to the value from the input values

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] Add separate set of input values like below
  - [ ] switchPartiesVersion
  - [ ] switchQuotesVersion
  - [ ] switchTransfersVersion
  - [ ] switchTransactionRequestsVersion
  - [ ] switchParticipantsVersion
  - [ ] switchAuthorizationsVersion
- [ ] Modify TTK golden path tests based on the new variables (For example a test case in duplicate transfers)

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
@vijayg10 - with the parameterization of variables, version parameters, this is now addressed, isn't it?

**Comment by elnyry-sam-k** [comment]
Additional parameterization needed for validation of headers on callbacks generated by the Switch
