### ISSUE TITLE
refactor: central-settlement cgs handler unit tests assertion framework to jest

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#2095]
## **Goal**:
`As a` OSS code contributor

`I want to` refactor the central-settlement tests 
  
`so that` the narrow integration tests uses the jest native assertion framework

**Acceptance Criteria**:
- [ ] cgs handler tests are using jest as only test and assertion framework

**Complexity**: <Low>

**Uncertainty**: <Low>

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
