### ISSUE TITLE
Implement BREAKING CHANGES of api-snippets & sdk-standard-components in thirdparty-scheme-adapter

### ISSUE THREAD

**Issue by sridharvoruganti** [mojaloop/project#2096]
## **Goal**:
`As a`  PISP developer

`I want to` implement BREAKING CHANGES of api-snippets(v12.0.0) and sdk-standard-components(v15.0.0) in `thirdparty-scheme-adapter`.
  
`so that` we can use latest releases\features and unblocks other development work (#1999 )

**Acceptance Criteria**:
- [x] Updated Inbound  and Outbound API definitions
- [x] Updated typescript definitions

**Complexity**: Medium

**Uncertainty**: Medium
---

**Tasks**:
- [x] Modify Inbound , Outbound and docker-contract API definitions accordance with new releases 
- [x] Use api-snippets typescript definitions in place of local types defined in index.d.ts (sdk-standard-components)
**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/54

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
