### ISSUE TITLE
TTK - Test the p2p test case with a mojaloop instance behind the WSO2 gateway

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2097]
## **Goal**:
`As a` individual implementer

`I want to` make sure that TTK supports WSO2
  
`so that` I can run test suites from a TTK deployed outside of my mojaloop cluster

**Acceptance Criteria**:
- [ ] Investigated the TTK test suite execution combined with WSO2 gateway
- [ ] Observations are recorded

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [x] Get the following details from an implementer
  - [x] TTK access
  - [x] TTK collection and environment files if available
  - [ ] K8S access (optional)
  - [ ] Access to WSO2 gateway (optional)
- [x] Try to run a P2P transfer with a mojaloop behind the WSO2 gateway
- [x] Understand the SSL configuration in the WSO2 for this to run
- [x] Understand the Authroization token configuration in the WSO2
- [x] Understand how the postman p2p test case with WSO2 works
- [x] Record the observations and discuss with the team about the next steps

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] P2P Tests pass
- [x] Recorded the observations

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- https://github.com/mojaloop/project/issues/2098

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @elnyry-sam-k

**Comment by vijayg10** [comment]
This issue was already addressed in #2098
