### ISSUE TITLE
update Mini-loop deployment of ML to recent s/ware versions 

### ISSUE THREAD

**Issue by tdaly61** [mojaloop/project#2099]
## **Goal**:
`As a` contributor 

`I want to` update the virtualbox version of the miniloop deployment of mojaloop to the latest software versions and potentially use K3s Kubernetes engine in place of microk8s 
  
`so that` I can create an up-to-date test bed to develop the secure k8s network policy per #2074 
Versions: 

- Mojaloop ?
- Kubernetes v1.20
- Ubuntu 18.04 (bionic64) 
- Helm v3.5.2

**Acceptance Criteria**:
- [ ] using vagrant , mojaloop deployed and running in virtualbox (6.x) 
- [ ] golden path tests (or I think testing tookit) successfully running 
- [ ] _example_transfer.sh  script that is part of Mini-loop runs successfully 

**Complexity**: <Medium>  this is mostly just version updates to what is already today with Mini-loop

**Uncertainty**: <Low> > again , most of this already exists

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @tdaly61 
- QA/Review: @godfreykutumela , @lewisdaly @mdebarros

**Comment by tdaly61** [comment]
hi @godfreykutumela @lewisdaly , I have re-opened this because it is what I am working on right now. I also want to expand it a bit to add in the fact that I am loading data from the ml-oss-lab as well as the TTK and I am using nginx and of course this is all highly automated.  Can you please advise as to what project/sprint/deliverable this should be tied to. I would expect to have this done and ready within a few weeks now that I am finishing at Oracle.  TIA

**Comment by elnyry-sam-k** [comment]
Thanks @tdaly61 , Sam here.. I've added this to Sprint 15.3 based on what you said.

But, here's the milestone list and corresponding dates: https://github.com/mojaloop/project/milestones, feel free to update as needed

**Comment by tdaly61** [comment]
Hi @elnyry-sam-k , oh that helps , thanks much.
