### ISSUE TITLE
Design & refactor the Settlements table and associated Micro-Service - [13]

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#21]
**Goal**:
As a developer I would like to design & refactor the Settlements table and associated Micro-Service in order to expand the data and ensure the functionality is catered for.

**Tasks**:
- [ ] Assess the need to change current Settlements functionality
- [ ] Retro-fit database technology of choice as required

**Acceptance Criteria**:
- [ ] The Settlements process works as intended with functionality of extracting/sending settlement reports to the FSPs

**Dependencies**:
- [ ] Verify that this is not impacted by the 'Positions' data related stories
- #151

**Comment by NicoDuvenage** [comment]
This story has been completed by applying the changes as required but will be moved to the "blocked" pipeline. We will not implement these changes yet until a design session provides outcome on the inevitable data model changes required as a result of the fact that we are planning to re-align to a new API specification.

**Comment by elnyry** [comment]
Duplicate, covered in other stories
