### ISSUE TITLE
Re-factor "transferBatch" in CDM & DB to "transferSetttlementBatch"

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#210]
**Goal**:
As a developer I want to __re-factor "transferBatch" in CDM to "transferSetttlementBatch"__ so that the semantics for the table is better understood

**Tasks**:
- [ ] ...

**Acceptance Criteria**:
- [x] Rename table "transferBatch" to "transferSettlementBatchId"
- [x] Rename the "transferBatchId" to "transferSettlementBatchId"
- [x] Update the migration scripts to reflect this change
- [x] Update ERD to reflect this change

**Dependencies**:
- n/a

**Comment by HenkKodde** [comment]
![cdm- 210](https://user-images.githubusercontent.com/36304517/39431267-746e9336-4c90-11e8-88cc-20b2f75ad40d.png)

Attached .png of CDM.
