### ISSUE TITLE
Configure TLS & Authentication for Core Mojaloop Service connectivity to Backends

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2100]
## **Goal**:
`As a` Hub Operator

`I want to` configure TLS & Authentication for Mojaloop Backend services
  
`so that` communication is secure & authenticated between Mojaloop and Backend Services

**Acceptance Criteria**:
- [ ] Central-Ledger supports TLS & Authentication credentials for:
   - [ ] Kafka
   - [ ] MySQL
   - [ ] MongoDB
- [ ] ML-API-Adapter supports TLS & Authentication credentials for:
   - [ ] Kafka
- [ ] Bulk-API-Adapter supports TLS & Authentication credentials for:
   - [ ] Kafka
   - [ ] MongoDB
- [ ] Central-Settlements
   - [ ] Kafka
   - [ ] MySQL
- [ ] Account-Lookup-Service
   - [ ] MySQL
- [ ] Quoting-Service
   - [ ] MySQL
   - [ ] Redis
- [ ] Mojaloop-Simulators
   - [ ] Redis
- [ ] Event-sidecar
   - [ ] Kafka
- [ ] Event-Stream-Processor
   - [ ] Kafka
   - [ ] ElasticSearch
   - [ ] APM
- [ ] Schema-Adapter
   - [ ] Redis
- [ ] Email-Notifier
   - [ ] Kafka
- [ ] Finance-Portal
   - [ ] MySQL
- [ ] Settlement-Management
   - [ ] MySQL

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
MongoDB support for TLS doesn't look all that difficult:

https://github.com/Automattic/mongoose/blob/c25169702ccc2a8f8123853453ed755f17278ce7/docs/tutorials/ssl.md

We will probably want to expose some options around specifying a CA file, and turning off and on the `sslValidate` option.

**Comment by lewisdaly** [comment]
@mdebarros maybe we can convert this into an Epic? Seems pretty epic to me.

**Comment by elnyry-sam-k** [comment]
yep @lewisdaly , @mdebarros - this is epic :-)
