### ISSUE TITLE
TTK - Improve info related to settlements in mobile simulator page

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2104]
## **Goal**:
`As a` individual implementer

`I want to` have some information in the mobile simulator page about settlements
  
`so that` I can demonstrate the settlement models "**_DEFERRED and CGS_**" using TTK mobile simulator

**Acceptance Criteria**:
- [x] TTK mobile simulator hub console contains the following information
  - [x] Settlement account values of DFSPs
  - [x] Settlement windows information
  - [x] Other information related CGS

**Complexity**: Medium

**Uncertainty**: High

---

**Tasks**:
- [x] Add information related to settlement windows if we drill down in addition to the settlement list
- [x] Understand the CGS settlement model
- [x] Design the page and discuss with the team
- [x] Implement the designs
- [x] Make the various components in hub console configurable based on the settlement model

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- NA

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
demonstrated as part of PI-15 Mojaloop community event
