### ISSUE TITLE
realize p2p transaction using thirdparty-scheme-adapter - DFSP side

### ISSUE THREAD

**Issue by eoln** [mojaloop/project#2108]
## **Goal**:
`As a` Developer
`I want to` apply the same patterns to all parts of the code (with thirdparty-scheme-adapter)
`so that` we can effectively work and build the codebase

**Acceptance Criteria**:
- [x] DFSPTransactionModel implemented & tested
- [x] implement `PATCH /thirdpartyRequests/transfer/{id} at thirdparty-api-adapter`
- [x] specify error cases for transfer workflow

**Complexity**: Medium> there is approved UML sequence diagram
**Uncertainty**: Medium >  there is approved UML sequence diagram

---

**Tasks**:
- [x] ~~fix invalid def for outgoing POST /authorizations in sdk-scheme-adapter~~
- [x] DFSPBackendRequests
  - [x] validate ThirdpartyRequestsTransaction
- [x] SDKOutgoingRequest
  - [x] add Quotes call
  - [x] add Authorizations 
  - [x] add SimpleTransfer
- [x] DFSPTransactionModel implementation
  - [x] stat machine layout
  - [x] validate ThirdpartyReqeustsTransaction with DFSPBackend
  - [x] request Quote
  - [x] request Authorization
  - [x] validate AuthorizationInfo
  - [x] request simpleTransfer
  - [x] update PISP with transfer result
- [x] implement PATCH /thridpartyRequests/transactions/{id} at thirdparty-api-adapter
  - [x] while you're here, check for other endpoints that may need to be added to the thirdparty-api-adapter, central-ledger, and seeds
- [x] improve unit tests to reach coverage
- [x] integration test - in thirdparty-scheme-adapter, simulators, ttk
  - [x] implement verification endpoints on mojaloop-simulator
- [x] unexpected work
  - [x] drop duplicated POST /authorizations integration tests - already implemented in sdk-scheme-adapter
  - [x] refactor CI/CD & docker-compose config to use one file - simplification and local work with integration tests speedup
  - [x] fixed problems with TTK multiple spec and endpoint clashing - fix 404
  - [x] investigation of TTK script invocation problems with Vijay, what resulted in new TTK release

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and another deployment config.
- [x] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/270
- [x] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/79
- [x] https://github.com/mojaloop/sdk-standard-components/pull/144
- [x] https://github.com/mojaloop/mojaloop-simulator/pull/97
- [x] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/88

![](https://raw.githubusercontent.com/mojaloop/thirdparty-scheme-adapter/master/out/docs/sequence/PISPTransactionApi/PISP%20Transaction.svg)
