### ISSUE TITLE
realize p2p transaction using thirdparty-scheme-adapter - E2E (docker-local)

### ISSUE THREAD

**Issue by eoln** [mojaloop/project#2109]
## **Goal**:
`As a` Tester
`I want to` test E2E P2P transfer initiated by PISP
`so that` I am sure the whole docker-setup is well integrated

**Acceptance Criteria**:
- [x] E2E P2P transfer test in docker-local

**Complexity**: Medium > integration tests  should be  working
**Uncertainty**: Medium >  integration tests should be working

---

**Tasks**:
- [x] latest docker images
- [x] updated configuration of services
- [x] update test code to use latest API schemes

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBA
## **Follow-up**:

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
closing this following an end-to-end demo by Lewis. Thanks @lewisdaly , @kleyow , @eoln
