### ISSUE TITLE
Implement Data Access Layer required for PrepareHandler

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#211]
**Goal**:
As a developer I want to __Implement Data Access Layer required for PrepareHandler__ so that FSP prepares are received and processed as per the design

**Note**: 
- Event logging is handled by story #217

**Tasks**:
- [x] Implement DAO for PrepareHandler

**Acceptance Criteria**:
- [x] Central services to provide the following tables: transfer [Rajiv]
- [x] Central services to provide the following tables: transferStateChange, transferState [Miguel]
- [x] Central services to provide the following tables: ilp, extension [Valentin]
- [x] Central services to provide the following tables: currency, participant [Valentin]
- [x] Central services to provide data access objects to prepareHandler []
- [x] Update ERD if any changes are made []

**Dependencies**:
- [x] #207

**Comment by vgenev** [comment]
I am taking care of the participants and currencies right now.
