### ISSUE TITLE
Review Mojaloop MysQL Database Security Configurations on MPQS Environment

### ISSUE THREAD

**Issue by rasputtintin** [mojaloop/project#2110]
## **Goal**:
`As a` security officer

`I want to` review security configurations for deployed databases in MPQS environment using documented baseline standards
  
`so that` I can be able to validate compliance with best practice standards

**Acceptance Criteria**:
- [ ] Document requirements and database inventory
- [x] Run Audit scripts and tools on Mojaloop Databases
- [ ] Analyse findings and generate report

**Complexity**: Medium  - All components of Mojaloop has to be installed

**Uncertainty**: Low - We have all the help we need within the OSS team to complete this 

---

**Tasks**:
- [x] Document Database inventory [ @rasputtintin  ]
- [x] Run security scans [ @rasputtintin  ]
- [x] Analyse output and generate report [ @rasputtintin  ]
- [x] Analyse user configurations [ @rasputtintin  ]

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- https://github.com/mojaloop/project/issues/1871

## **Accountability**:
- Owner: @rasputtintin 
- QA/Review: @godfreykutumela

**Comment by rasputtintin** [comment]
Executed audit scripts and security scans on ML databases and am currently analysing the outputs. Scans are informed by CIS standards as well as PCI-DSS for best practice configurations and data protection.

**Comment by rasputtintin** [comment]
Reviewing initial findings as well as investigating audit logging in Mysql for this week. I note Open Source version of MySQL has limited audit logging capabilities hence we may need a plugin to support.

**Comment by godfreykutumela** [comment]
Thanks @rasputtintin

**Comment by rasputtintin** [comment]
Key Findings:

**1 - Access control** 
a) No granular access control defined for database users. Enforce CRUD restrictions for different Database users depending on roles (including service accounts)b) Access control - no users with password set to expire. 

**2 Monitoring and Audit**
a) Slow query log disabled
b) Audit not enabled
c) Performance statistics not configured 

**3 Data Protection Controls**
a) Tablespace encryption - no at-rest encryption detected
b) DB Backup execution - No backup configurations detected (to verify settings exist in AWS)
c) No data masking controls detected
d) Review binlog configurations for point in time recovery.

**4 Secure Configurations**
a) Any host access - Users can connect from everywhere (central_ledger / monitor / root)
b) Dedicated datadir - no dedicated datadir. Ensure 'datadir' is configured and has appropriate permissions
c) Password policy - Length + Complexity needs to be optimized
d) Local_infile enabled - this needs to be disabled if not used.
e) DB Password check - some users have easy passwords	(monitor@'%' monitor@'localhost' mysql@'localhost')
f) Master_info - store master_info data in a table and not a plaintext file.

I am compiling final report with additional details.

**Comment by godfreykutumela** [comment]
Thanks @rasputtintin
