### ISSUE TITLE
Explore creation of Mojaloop Security Dashboard capturing security events in a Mojaloop Deployment in MPQS environment

### ISSUE THREAD

**Issue by rasputtintin** [mojaloop/project#2111]
## **Goal**:
`As a` security officer

`I want to` test deployment of a security monitoring tool within Mojaloop environment 
  
`so that` I can be able to have visibility on security events in Mojaloop that may trigger incident response.

**Acceptance Criteria**:
- [ ] Identify open source tools available
- [ ] Install tools in MPQS environment
- [ ] Test Security dashboard

**Complexity**: Medium  - All components of Mojaloop has to be installed

**Uncertainty**: Low - We have all the help we need within the OSS team to complete this 

---

**Tasks**:
- [ ] Explore open source tools [ @rasputtintin  ]
- [ ] Install tools in MPQS environment [ @rasputtintin  ]
- [ ] Create simple security dashboard [ @rasputtintin  ]

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- https://github.com/mojaloop/project/issues/1779

## **Accountability**:
- Owner: @rasputtintin 
- QA/Review: @godfreykutumela
