### ISSUE TITLE
Review database audit logging configurations in MPQS environment using documented baseline

### ISSUE THREAD

**Issue by rasputtintin** [mojaloop/project#2112]
## **Goal**:
`As a` security officer

`I want to` review database audit logging settings 
  
`so that` I can be able to ensure configurations comply with documented database audit logging baseline

**Acceptance Criteria**:
- [ ] Extracted configurations and logs
- [ ] Documented report and recommendations

**Complexity**: Medium  - All components of Mojaloop has to be installed

**Uncertainty**: Low - We have all the help we need within the OSS team to complete this 

---

**Tasks**:
- [ ] Extract configurations and logs from a golden path test [ @rasputtintin  ]
- [ ] Analyse configurations and logs [ @rasputtintin  ]
- [ ] Create report with recommendations [ @rasputtintin  ]
- [ ] Test recommendations in MPQS environment [ @rasputtintin  ]

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- https://github.com/mojaloop/project/issues/1779

## **Accountability**:
- Owner: @rasputtintin 
- QA/Review: @godfreykutumela

**Comment by rasputtintin** [comment]
Investigating audit logging features of MySQL community vs enterprise version. Community version does not have audit logging hence we need to test if existing audit logs may be sufficient as MVP.
