### ISSUE TITLE
Edit error message on Prepare Handler when SettlementModel is not found

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#2114]
## **Goal**:
`As a` OSS Contributor

`I want to` Change error message in case of no SettlementModel has been associated with that currency. The behaviour is described in #2107 
  
`so that` When a transfer is received, if there is no SettlementModel for the given currency, the error thrown in the prepare handler is clearer 

**Acceptance Criteria**:
- [ ] When a transfer is received in the prepare handler, if there is no SettlementModel for the transfer currency, the error message is `No SettlementModel found for the transfer currency`

**Complexity**: <Low>

**Uncertainty**: <Low>

---

**Tasks**:
- [ ] Log clearer error in case no SettlementModel is set

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
