### ISSUE TITLE
Provide rule based extensionList for quotes response in mojaloop-simulator

### ISSUE THREAD

**Issue by shashi165** [mojaloop/project#2115]
## **Goal**:
`As a` Mojaloop Scheme

`I want to` provide rule based custom extensionList values for quotes response in mojaloop-simulator
  
`so that` a Payee FSP can send custom extensionList elements

**Acceptance Criteria**:
- [ ] `PUT /quotes/{ID}` by mojaloop-simulator (based on sdk scheme-adapter) should be able to support extensionList elements in the response body
- [ ] extensionList should be configured as a rule
- [ ] provide the option to 
  - [ ] merge the response(provided by the rule) extensionList with the request extensionList
  - [ ] replace the request extensionList with the response extensionList(provided by the rule)

**Complexity**: Medium 

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Thanks @shashi165 .. closing this in favor of: https://github.com/mojaloop/project/issues/2116
