### ISSUE TITLE
Customize extensionList elements in PUT /quotes when using ml-simulator

### ISSUE THREAD

**Issue by ludovickouassi** [mojaloop/project#2116]
## **Goal**:
`As a` Mojaloop FSP / Scheme

`I want to` provide rule based custom extensionList values for quotes response in mojaloop-simulator
  
`so that` a Payee FSP can send custom extensionList elements, which can can be collected by the Scheme/Switch according to the local requirements, regulations

**Acceptance Criteria**:
- [ ] Collect additional KYC details from Payee using data from `PUT /quotes` if provided in the extensionList elements provided by the Mojaloop API
- [ ] `PUT /quotes/{ID}` by mojaloop-simulator (based on sdk scheme-adapter) should be able to support extensionList elements in the response body
- [ ] extensionList elements should be configurable using rules
- [ ] provide the option to 
  - [ ] merge the response(provided by the rule) extensionList with the request extensionList
  - [ ] replace the request extensionList with the response extensionList(provided by the rule)

**Complexity**: <Medium> > A short comment to remind the reason for the rating

**Uncertainty**: <Medium> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Modify `sdk-scheme-adapter` to support extensionList for quotes
- [x] Modify `mojaloop-simulator` to support extensionList for quotes
- [x] Add support for a rule to merge the extensionList on quote response
- [x] Add support for a rule to replace the extensionList on quote response

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/mojaloop-simulator/pull/89
- [ ] https://github.com/mojaloop/sdk-scheme-adapter/pull/269

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
