### ISSUE TITLE
Incorporate new central-settlement config with separate rules handler into helm charts

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#2117]
## **Goal**:
`As a` OSS Contributor

`I want to` Incorporate changes from #2056 and #2057 into helm charts 
  
`so that`  Central-Settlement Rules handler is separated, so it can be used more generically and the Central-Settlement  code is refactored to align with OSS standards, while Central-Settlement CGS functionality is the same as in helm v12.0.0 and the same tests are passing.

**Acceptance Criteria**:
- [x] Tests for CGS are passing with CGS and INTERCHANGE FEE Settlement models
- [x] Golden path tests are passing with DEFERREDNET Settlement model
- [x] Rules are executed by separate handler
- [x] Rules can be triggered on different events

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [ ] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- #2056 #2057
## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
this is now complete
