### ISSUE TITLE
Proposal Change Request: Distributed Tracing Support for FSPIOP API

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2121]
## **Goal**:
`As a` Hub Operators

`I want to` support Distributed Tracing when using the FSPIOP API
  
`so that` FSPIOP API Transaction requests are traceable end-to-end for all FSPs and Hub interactions.

**Acceptance Criteria**:
- [x] General Distributed Tracing Specification Document reviewed and accepted by the FSPIOP CCB
- [ ] FSPIOP Specification includes Distributed Tracing Headers and references to General Document
- [ ] Proposed Distributed Tracing changed to FSPIOP Specification is reviewed and accepted by the FSPIOP CCB

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Draft Proposal for the FSPIOP Change Control Board (CCB)
- [x] Create Pull-Request (PR) for review by the FSPIOP Change Control Board (CCB)
- [x] Integrate review comments/changes from FSPIOP Change Control Board (CCB)
- [x] Re-review PR Submission with FSPIOP CCB
- [x] Merge PR and Publish amended version

**Done**
- [ ] Acceptance Criteria pass
- [x] Designs are up-to date

## **Pull Requests**:
- [x] https://github.com/mojaloop/mojaloop-specification/pull/85

## **Follow-up**:
- N/A

**Dependencies**:
- https://github.com/mojaloop/mojaloop-specification/issues/71

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
