### ISSUE TITLE
Central-Settlements supports a default SettlementModel

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2123]
## **Goal**:
`As a` Hub Operator

`I want to` support a default SettlementModel
  
`so that` transfers that are not associated with a specific SettlementModel are processed by the configured Default

**Acceptance Criteria**:
- [ ] ~Updated Settlement Designs to include default SettlementModel support~
- [ ] ~Updated Database ERD Settlement Designs to include Default SettlementModel changes~
- [ ] ~Central-Ledger migration scripts are updated~
- [x] Central-Settlements Postman Golden path tests work without changes with Default SettlementModel configurations
- [ ] ~Central-Settlements TTK Golden path tests are updated to include Default SettlementModel configurations for deferred net~
- [ ] ~Central-Settlements TTK CGS tests are updated to:~
  - [ ]  ~setup the hub with a new currency and CGS settlement model for it~
  - [ ] ~run TTK CGS tests successfully~
  - [ ] ~run default currency and deferred settlement model test successfully~
- [x] Central-Settlements is able to process transfers with only a Default SettlementModel
- [x] Central-Settlements is able to process transfer+currency combination correctly via either the Default SettlementModel and pre-configure currency-specific SettlementModels.
- [x] When there are configured two DEFERREDNET settlement models: one default (no currency) and one with defined currency(A) - when settlement for default settlement model is initiated it, should settle all transfers with currency which is not A

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] merge back config seeder functionality
- [x] allow settlement model creation without currency (default)
- [x] test transfer and settlement with default settlement model 
- [x] remove default settlement from config and leave it as an API only
- [x] fix tests
  - [x] unit
  - [x] docker command for mysql 5.7.34 on integration tests for central-ledger and central-settlement
- [x] throw meaningful errors when no default settlement model is set and transfer with missing currency for settlement is requested
- [x] fix API specification documentation 
- [x] test with both settlement models (deferred as default and cgs for another currency)

**Done**
- [x] Acceptance Criteria pass
- [ ] Designs are up-to date: will follow-up in #2234 
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-error-handling/pull/162
- [x] https://github.com/mojaloop/central-ledger/pull/839
- [x] https://github.com/mojaloop/central-settlement/pull/351

## **Follow-up**:
- https://github.com/mojaloop/project/issues/2231
- #2234 

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
1. Fix error scenarios for both Central-Ledger and Central-Settlements (i,e. what happens if there is no default found)
2. Check the GET /settlementModels on Admin API for default SettlementModel. Does it not return the currency on the default model? <-- do we need any changes here?
3. Update specification-doc and swagger to indicate that the currency is NOT required
4. Can you test the following scenario:
Setup:
Hub has two currencies (A & B) loaded
Create defferednet SettlementModel that is default
Create deferrednet SettlementModel with a specific currency B
Tests:
Close a settlement with the default SettlementModel <-- what transfers are settled?
Close a settlement with the SettlementModel that is specific currency B
5. Helm updates (pending) (
