### ISSUE TITLE
2.3.2.1. Design Sequence Diagram for Prepare Flow Use-Cases - [2]

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#213]
**Goal**:
As a developer I would like to __Design Sequence Diagram for Prepare Flow Use-Cases__ so that the Stream processing epic can be implemented

**Tasks**:
- [x] produce plantuml 
- [x] produce SVB export of plantuml diagram
- [x] Add alt flows for error scenarios, but use ref to external file for details of the error scenario [ @mdebarros ]
- [x] Update notifications to show the "to" participant for the retrieval of the participant information
- [x] Remove the 1st notification. This should be handled by the schema rules, and subsequantly the flow must be updated to call a rules engine to determine the action. The rules engine will then provide the instruction to send notifications to the respective dfsp.
- [x] Update event persist elements to show that the events are sent to a topic (use external ref flow)
- [x] Add new external flow for event handler to process and store in DB
- [x] Peer review changes [ @mdebarros @ggrg ]

**Acceptance Criteria**:
Update the Sequence Diagrams for the Prepare Flow as per the following:
- [x] colour co-ordinate the same boxes to the arch diagram
- [x] update sequence diagram to show batch processing
- [x] add persistence of the transfer to the position event handler
- [x] add update of transfer status to the transfer event handler
- [x] added example messages
- [x] added expected error codes
- [x] review and brake into smaller reusable parts in regards to #247 [ @ggrg ]
- [x] Reviewed by the Design Authority
- [x] Updates from Design Authority review

**Dependencies**:
- n/a

**Accountability**:
- Owner @mdebarros 
- Review **Design Authority**

**Comment by mdebarros** [comment]
PR: https://github.com/mojaloop/docs/pull/16
