### ISSUE TITLE
refactor auth-service to mitigate technical debt

### ISSUE THREAD

**Issue by eoln** [mojaloop/project#2132]
## **Goal**:
`As a` Dev

`I want to` see the proper separation of concerns
  
`so that` auth-service is easy to maintain

**Acceptance Criteria**:
- [x] Handers should only depend on Domain
- [x] Domain should only depend on Model
- [x] Model should only depend on Knex
- [x] Config merged and simplified
- [x] fix false-positive unit tests 
- [x] refactor existing code TODOs (keeping test coverage up)
- [x] improve unit tests to leverage separation of concerns

**Complexity**: <Medium> > three layers must be separated

**Uncertainty**: <Low> > no big changes in business logic, good test coverage already reached

TODOS in compare view:
https://github.com/mojaloop/auth-service/compare/feat/pi13-assessment
---

**Tasks**:
- [x] Handers should only depend on Domain
- [x] Domain should only depend on Model
- [x] Model should only depend on Knex
- [x] Config merged and simplified
- [x] fix false-positive unit tests 
- [x] refactor existing code TODOs (keeping test coverage up)
- [x] improve unit tests to leverage separation of concerns

**Done**
- [ ] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/auth-service/pull/64
- [x] https://github.com/mojaloop/auth-service/pull/67
- [x] https://github.com/mojaloop/auth-service/pull/69

## **Follow-up**:
- [ ] mojaloop/project#1943

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
