### ISSUE TITLE
Linking workflow in thirdparty-scheme-adapter

### ISSUE THREAD

**Issue by eoln** [mojaloop/project#2134]
## **Goal**:
`As a` Dev

`I want to` perform linking using thirdparty-scheme-adapter
  
`so that` I can run e2e automated tests

**Acceptance Criteria**:
- [ ] Design & Sequence diagrams of linking workflow from thirdparty-scheme-adapter perspective
- [ ] PISP & DFSP models state machine specified
- [ ] workflow e2e test in pips/docker-local

**Complexity**: <High> > We never do whole linking workflow

**Uncertainty**: <High> > We never do whole linking workflow

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
