### ISSUE TITLE
update mini-loop helm charts to install DB separately from ML helm-charts

### ISSUE THREAD

**Issue by tdaly61** [mojaloop/project#2136]
## **Goal**:
`As a` contributor 

`I want to` incorporate into the mini-loop deployment of ML changes to the helm charts that separate the database install from the rest of the mojaloop deployment.  This will take advantage of the work @lewisdaly is doing in the demo lab but will be specific to mini-loop deployment (at least initially) 
  
`so that` decisions on databases can be made independently when deploying ML, but also mainly to fix deployment issues with the current percona/mysql helm charts where busybox seems broken on the side-car container of percona.

**Acceptance Criteria**:
- [ ] mojaloop runs in mini-loop and passes the testing toolkit so as to enable development and completion of the secure kubernets network config i.e. #2074 

**Complexity**: <Medium> > taking some time to come up to speed with al the ML charts that use DB and the configuration of the DB

**Uncertainty**: <Low> > there is nothing really advanced or not-understood here , just a different way of deploying

---

**Tasks**:
- [ ] install a database e.g. mysql with configuration gleaned from existing ML helm charts
- [ ] configure ML (accounts loookup and central-ledger at least) to use already installed DB

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
