### ISSUE TITLE
incorporate calico into miniloop and restrict north-south/east-west traffic

### ISSUE THREAD

**Issue by tdaly61** [mojaloop/project#2137]
## **Goal**:
`As a` contributor 

`I want to` install and configure calico (automatically) into the miniloop deployment of mojaloop so as to determine and demonstrate how to restrict network traffic both north-south and east-west within mojaloop per #2074 
  
`so that` we can demonstrate and document a secure network deployment of mojaloop again in line with and as part of #2074

**Acceptance Criteria**:
- [ ] calico installed and configured automatically via helm such that network traffic is restricted to only necessary paths within the K8s cluster and in/out of it.

**Complexity**: <Medium> > the risks are all about my understanding of the existing traffic flows AND of what the minimum traffic paths are.  Certainly turning off all the paths and then enabling until the app and the testing toolkit tests run successfully will also show what paths are actually needed. 

**Uncertainty**: <Medium> > my ongoing but (hopefully) receding un-familiarity with the application is I think the largest risk

---

**Tasks**:
- [ ] calico installed automatically 
- [ ] develop / determine and set calico policies/configuration such that network traffic can still flow where it is required BUT *only* where it is required and not unrestricted as per the current vanilla helm deployment 
- [ ] ensure testing toolkit still works

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @tdaly61 
- QA/Review: @godfreykutumela
