### ISSUE TITLE
TTK - Improve inbound scripting

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2138]
## **Goal**:
`As a` individual implementer

`I want to` have inbound scripting more sophisticated
  
`so that` I can customise TTK responses for a request sent

**Acceptance Criteria**:
  The following things can be improved w.r.t inbound scripting
  - [x] Ability to write inbound scripts in javascript rather than postman scripting
  - [x] Ability to debug the scripts by adding console log some where (Next to scripts or in monitoring page)
  - [x] Proper logs in the monitoring page about the scripts execution along with the other inbound logs
  - [x] Add the API name and version picked up in the monitoring logs
  - [x] Document the inbound scripting (Available functions, variables, parameters ...etc)

**Complexity**: Low

**Uncertainty**: Medium

---

**Tasks**:
- [x] TBD [ @? ]

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/151
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/96
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/161

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
