### ISSUE TITLE
2.4.95.01 Design: I want to be able to record quote requests and ensure that transfers can be associated with a quote. - [13]

### ISSUE THREAD

**Issue by HenkKodde** [mojaloop/project#214]
**Goal**:
This is a design story for the below goals:

1. As a **_HUB Operator_**
I want to be able to _record quote requests_
so that I can report to the regulator and be able to enforce scheme rules.

2. As a **_Participant_**
I want to _ensure that transfers can be associated with a quote_
so that the billing model and scheme rules can be applied. 

**Tasks**:
- [x] Get the current CDM and analyze for changes needed [@Henk]
- [x] Create a new data module to support the Quote **_request_** data in the Central Services DB. [@Henk]
- [x] Create a new data module to support the Quote **_response_** data in the Central Services DB. [@Henk]
- [x] Verify DDL [@Henk, @Warren & @ggrg ]
- [New story 296] Verify the updated design is reviewed by the Design Authority
- [New story 296] Publish updated design

**Acceptance Criteria**:
- [x] Verify that the data model includes an auditable record of the quote request as per Mojaloop API POST /quote (insert only with appropriate foreign keys).
- [x] Verify that the data model includes an auditable record of the quote response as per Mojaloop API POST /quote (insert only with appropriate foreign keys).
- [x] Verify that the requesting party can be identified.
- [x] Verify that the responding party can be identified.
- [x] Verify that the data model can reconcile requests.
- [x] Verify that the data model can reconcile responses.
- [x] Verify that the data model supports linking a quote to a transfer.
- [x] The CDM/Data Model is updated/aligned to reflect the Quote requirements
- [x] Verify the data model supports the concept of **Transaction**
- [New story 296] Verify that the CDM supports the requirements for Quotes

**Dependencies**:
- None currently

**Accountability**
- Owner @HenkKodde 
- Review **Design Authority** To be actioned as part of new story #296.

**Comment by HenkKodde** [comment]
Design was presented at the PI-2 demo. The initial requirements for the story has been achieved.
Some questions was posed to include the quote process as the major design changed that would be required to realise this design.

**Comment by HenkKodde** [comment]
![image](https://user-images.githubusercontent.com/36304517/41336620-0cb60d80-6eed-11e8-9c5e-3b637a157d7d.png)
