### ISSUE TITLE
TTK - Capability to disable some requests or test suits based on an environment variable

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2141]
## **Goal**:
`As a` individual implementer

`I want to` disable some tests
  
`so that` I can use the same GP collection for my custom mojaloop deployment

**Acceptance Criteria**:
- [ ] Requests / Test suites can be disabled with an environment variable

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
