### ISSUE TITLE
Run CIS Benchmark on Mojaloop Ubuntu 18.04 Operating System in MPQS Environment

### ISSUE THREAD

**Issue by rasputtintin** [mojaloop/project#2142]
## **Goal**:

`As a security officer

`I want to review security configurations for Ubuntu 18.04 in MPQS environment using CIS Benchmark baseline standards

`so that I can be able to validate compliance with best practice standards

**Acceptance Criteria**:
- [x] Install Audit Script
- [x] - [x] Run Audit scripts and tools on Mojaloop Ubuntu 18.04
- [ ] Analyse findings
- [ ] Generate report with recommendations

**Complexity**: Medium  - All components of Mojaloop has to be installed

**Uncertainty**: Low - We have all the help we need within the OSS team to complete this 

---

**Tasks**:
- [ ] Install CIS Benchmark Tool [ @rasputtintin  ]
- [ ] Run security scans [ @rasputtintin  ]
- [ ] Analyse output and generate report [ @rasputtintin  ]

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- https://github.com/mojaloop/project/issues/1871

## **Accountability**:
- Owner: @rasputtintin 
- QA/Review: @godfreykutumela

**Comment by rasputtintin** [comment]
@godfreykutumela tasks done last week
1 - Install CIS Script on two servers running Ubuntu 18.04
2 - Run Audit Scans

This week I am analyzing output for reporting and recommendations

**Comment by godfreykutumela** [comment]
Hi @rasputtintin Can you share the scan results here?

**Comment by rasputtintin** [comment]
@godfreykutumela 

Please see attached output from CIS Script.
[CIS-Master-Node-MPQS.txt](https://github.com/mojaloop/project/files/6335365/CIS-Master-Node-MPQS.txt)

Tests Done - 237 
Pass: 96 
Fail:109 
Chek: 32
