### ISSUE TITLE
Create demo: Bulk transfers in Mojaloop

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2143]
## **Goal**:
`As a` Mojaloop Community member

`I want to` understand whether bulk transfers functionality is supported by Mojaloop (Switch) OSS codebase and if so how
  
`so that` I can have a clearer understanding of how Mojaloop can support bulk feature.

**Acceptance Criteria**:
- [ ] Demonstration (as a video) of bulk transfers is done and shared with MLF/Virtual
- [ ] Demo video shared with MLF/Virtual after reviews, feedback

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] Create initial version of bulk transfers demo
- [ ] Reviews and incorporate feedback

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
We have demos now published and also done at PI-20 event with bulk support provided on the sdk-scheme-adapter
