### ISSUE TITLE
Create demo: Operational monitoring (Distributed tracing, Grafana dashboards)

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2144]
## **Goal**:
`As a` Mojaloop Community member

`I want to` understand the Operational monitoring capabilities supported by Mojaloop (Switch) OSS codebase
  
`so that` I can have a clearer understanding of how Mojaloop can operational monitoring for TechOps and other support teams

**Acceptance Criteria**:
- [ ] Demonstration (as a video) of Operational monitoring capabilities is done and shared with MLF/Virtual
  - [ ] Covers distributed tracing
  - [ ] Covers Grafana dashboards usage
- [ ] Demo video shared with MLF/Virtual after reviews, feedback

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Create initial version of Operational monitoring capabilities demo that
  - [x] Covers distributed tracing
  - [x] Covers Grafana dashboards usage
- [ ] Reviews and incorporate feedback

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Links to demos:
Distributed Tracing -> https://drive.google.com/file/d/18HlH_chVXf_vnaVpTAG_kHAAY0g_3x1y/view?usp=sharing
Realtime Instrumentation -> https://drive.google.com/file/d/1_k5dsKZxxru3MGIWrHFBMyQ3VCevA4m-/view?usp=sharing
