### ISSUE TITLE
Create demo: A Mojaloop transfer - (content from MTP) demo using TTK

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2145]
## **Goal**:
`As a` Mojaloop Community member

`I want to` have a demonstration video available that covers the anatomy of a Mojaloop transfer leveraging the content from MTP
  
`so that` I can understand all the steps/stages a mojaloop transfers goes through

**Acceptance Criteria**:
- [ ] Demonstration (as a video) of "the anatomy of a Mojaloop transfer" is done and shared with MLF/Virtual
- [ ] Demo video shared with MLF/Virtual after reviews, feedback

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] Create initial version of "the anatomy of a Mojaloop transfer"demo
- [ ] Reviews and incorporate feedback

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
