### ISSUE TITLE
Create demo: Using TTK for switch validation

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2146]
## **Goal**:
`As a` Mojaloop Community member

`I want to` have a demonstration video that shows how a ML TTK can be used to validate a Switch deployment
  
`so that` I can understand it and replicate it on my deployment

**Acceptance Criteria**:
- [ ] Demonstration (as a video) of "Using TTK for switch validation" is done and shared with MLF/Virtual
- [ ] Demo video shared with MLF/Virtual after reviews, feedback

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] Create initial version of "Using TTK for switch validation"demo
- [ ] Reviews and incorporate feedback

**Notes**:
- [x] Introduction about the use-case
- [x] Deployment methods
- [x] Loading a collection
- [x] Loading an environment
- [x] Running Test Suites and Downloading reports
- [x] Creating and editing test suites
- [x] Advanced topics
  - [x] Pre-request and Post-request scripts
  - [x] JWS signing and validation
  - [x] Websocket client based assertions
- [x] Iterations
- [x] Running Test Suites with TTK CLI
- [ ] Configuring cron jobs using helm
- [x] S3 integration, Slack notifications ...etc

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
