### ISSUE TITLE
Create demo: Using TTK for demonstration purposes

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2147]
## **Goal**:
`As a` Mojaloop Community member

`I want to` have a video that shows how ML TTK can be used for demonstrating features
  
`so that` I can use it for demonstration purposes

**Acceptance Criteria**:
- [x] Demonstration (as a video) of "Using TTK for demonstration purposes" is done and shared with MLF/Virtual
- [ ] Demo video shared with MLF/Virtual after reviews, feedback

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Create initial version of "Using TTK for demonstration purposes"demo
- [ ] Reviews and incorporate feedback

**Notes**
- [x] Introduction about the use-case
- ~~Deployment methods~~
- [x] Mobile simulator page walkthrough
- [x] Advanced features like settlements and positions
- [x] Monitoring page and the sequence diagram in the Test runner for demonstration
- [x] Example: ISO 20022 hackathon demo

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
