### ISSUE TITLE
Create demo: Using TTK to accelerate development

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2148]
## **Goal**:
`As a` Mojaloop Community member

`I want to` have a demonstration video that shows how a ML TTK can be used to accelerate development
  
`so that` I can benefit from it (as part of work-stream / feature development)

**Acceptance Criteria**:
- [ ] Demonstration (as a video) of "Using TTK to accelerate development" is done and shared with MLF/Virtual
- [ ] Demo video shared with MLF/Virtual after reviews, feedback

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Create initial version of "Using TTK to accelerate development"demo
- [ ] Reviews and incorporate feedback

**Notes**
- [x] Introduction about the use-case
- [x] Deployment methods (Including local deployment using native program)
- [x] TTK as simulator
- [x] Configuring Rules
- [x] Advanced: Provisioning new API into TTK

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
