### ISSUE TITLE
2.4.95.02  Ensure transfers can be associated with a quote

### ISSUE THREAD

**Issue by HenkKodde** [mojaloop/project#215]
**Goal**:

1. As a Participant
I want to _ensure that transfers can be associated with a quote_
so that I can enable the enforcement of the billing model and scheme rules. (Recording a quote and associating the quote with a transfer process/event).
2. As a Switch
I want to _ensure that transfers can be associated with a quote_
so that I can enable the enforcement of the billing model and scheme rules.

**Tasks**:
- [ ] Ensure the data module keeps record of quotes and transfer events with the ability to link an "accepted" quote to a transfer process/event.

**Acceptance Criteria**:
- [ ] Verify that the DAO _**(Data Access Object)**_ used to record the request supports the Mojaloop API - POST /quote.
- [ ] Verify that the DAO used to record the response supports the Mojaloop API - PUT/quote.
- [ ] Verify that the DAO supports additional elements needed to accurately record the event.
- [ ] Verify that the DAO is inserted into the quote workflows.
- [ ] Verify that requests (POST /quote by FSP1) are recorded into the Database.
- [ ] Verify that response (PUT /quote by FSP2) are recorded into the Database.
- [ ] Verify that there is a configuration parameter to enforce quotes and transfer referential integrity.

**Dependencies**:
- [ ] #214

**Accountability**
- Owner @HenkKodde 
- Review

**Comment by elnyry** [comment]
This will be catered if Headers proposed by the new Event & Error Framework is used. There is also a change coming soon to the Mojaloop FSPIOP Spec that will link quotes with transfers.. 

Closing this issue for that reason..
