### ISSUE TITLE
TTK - Understand the testing environment at Mowali

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2150]
## **Goal**:
`As a` individual implementer

`I want to` share my testing environment / scenario to the developer
  
`so that` we can find out if there are any gaps

**Acceptance Criteria**:
- [ ] Understood the testing environment at Mowali
  - [ ] Infrastructure of mojaloop switch and simulators currently using with postman
    - [ ] Gateways
    - [ ] TLS
    - [ ] Authentication
    - [ ] Endpoint configuration
  - [ ] Team memebers test setup
    - [ ] VPN access
    - [ ] Authentication
    - [ ] Onboarding a team member
  - [ ] Test Reports
    - [ ] Report format
    - [ ] Sharing the reports
  - [ ] Automation
    - [ ] Scheduled jobs
    - [ ] Tests in CICD
- [ ] Documented the observations and gaps identified

**Complexity**: Low

**Uncertainty**: Medium (Based on their availability)

---

**Tasks**:
- [ ] Followup with Mowali's team
- [ ] Schedule the meetings
- [ ] Discuss with core team
- [ ] Record the observations and gaps

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
