### ISSUE TITLE
Helm Release v13.0.0 (formerly v12.1.0)

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2151]
## **Goal**:
`As a` ML OSS Code base maintainer

`I want to` validate and make a Helm release in PI-14 that is successfully validated by the Golden path tests
  
`so that` Community members can take and use a version of Mojaloop Switch services bundle that is tested and contains the latest features and enhancements such as CGS, etc and bug fixes added in PI-13/PI-14.

**Acceptance Criteria**:
- [x] Helm RC v13.0.0 is validated on dev2 to achieve 100% result with TTK GoldenPath collection
- [x] QA (Golden path) on deployments done on AWS dev2 environment is done
- [x] Bugs are logged based on observations, failures
- [x] Bugs logged are fixed if critical to make subsequent releases in individual services (or Helm)
- [x] All the changes needed for supporting v13.0.0 of Helm are done
- [x] Helm v13.0.0 is released and release notes published
- [x] Test cases v13.0.0 is published (TTK)
- [x] TTK tests run successfully as Post-Hook jobs and Tests

**Complexity**: Medium - Involves all core and supporting services

**Uncertainty**: Medium

---

**Tasks**:
- [x] Make releases on all core services to have latest images / versions [@elnyry-sam-k , @mdebarros , @vgenev ]
- [x] Identify changes needed for helm (config / default.json)
- [x] Initial PR with changes for vX.Y.0
  - [x] Initial PR review
  - [x] Deploy, validate, fix issues, redeploy
  - [x] With stable deployment test Golden path
- [x] Identify issues with QA Scripts if any - fix them and retest
- [x] Identify Bugs, log them
- [ ] ~Validate finance portal~
- [x] Fix bugs logged if critical
- [x] Deploy, validate on AWS dev2
- [x] Validate/Document upgrade scenario details --> changed version to v13.0.0 because of #2302 
- [x] Validate with TTK Mojaloop Simulator collection
- [x] Release notes for helm v13.0.0 drafted
- [x] Helm v13.0.0 released
- [x] Review deployment guide documentation to ensure its up-to-date
- [x] Deployment of released Helm v13.0.0 on **Dev2**
  - [x] Helm v13.0.0 is deployed on **Dev2** successfully
  - [x] Validation using Golden path regression tests etc on Dev2
    - [x] Mojaloop Simulator postman collection
    - [x] TTK Post-hook install job and Tests
  - [x] Validation using CGS Golden path regression tests etc on Dev2
    - [x] Mojaloop Simulator TTK collection
- [x] Deployment of released Helm v13.0.0 on **Dev1**
  - [x] Helm v13.0.0 is deployed on **Dev1** successfully
  - [x] Validation using Golden path regression tests etc on Dev2
    - [x] Mojaloop Simulator TTK collection
    - [x] TTK Post-hook install and Tests
  - [x] Validation using CGS Golden path regression tests etc on Dev2
    - [x] Mojaloop Simulator TTK collection
    - [x] TTK Post-hook install and Tests
- Update to latest dependencies
    - [x] Central-services-logger
    - [x] Central-services-database
    - [x] Central-services-metrics
    - [x] Central-services-shared
    - [x] Central-services-stream
    - [x] Central-services-health
    - [x] Central-object-store
    - [x] ml-number
    - [x] Event-SDK
    - [x] Event-stream-processor
    - [x] Bulk-api-adapter
    - [x] Account-lookup-service
    - [x] Central-Ledger
    - [x] Central-Settlements
    - [x] Central-event-processor
    - [x] Quoting-service
    - [x] Transaction-Request-service
    - [x] legacy Mojaloop Simulator
    - [x] Testing-toolkit [@vijayg10]
    - [x] ~Finance-portal [@sam to confirm if Finance-portal team will do this]~ to use latest release
    - [x] ~Settlement-management~ to use latest release
    - [x] ~operator-management~ to use latest release
    - [x] Simulators
    - [x] ML-API-Adapter
- [x] TTK test cases v13.0.0 version released

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Postman (where applicable) Tests pass
- [x] TTK Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/436
- [x] https://github.com/mojaloop/helm/pull/437
- [x] https://github.com/mojaloop/helm/pull/440
- [x] https://github.com/mojaloop/quoting-service/pull/267
- [x] https://github.com/mojaloop/quoting-service/pull/269
- [x] https://github.com/mojaloop/quoting-service/pull/270
- [x] https://github.com/mojaloop/event-sdk/pull/55
- [x] https://github.com/mojaloop/event-sdk/pull/56
- [x] https://github.com/mojaloop/central-services-database/pull/144
- [x] https://github.com/mojaloop/central-services-metrics/pull/148
- [x] https://github.com/mojaloop/central-services-shared/pull/297
- [x] https://github.com/mojaloop/central-services-shared/pull/298
- [x] https://github.com/mojaloop/central-services-logger/pull/30
- [x] https://github.com/mojaloop/event-stream-processor/pull/39
- [x] https://github.com/mojaloop/central-services-stream/pull/116
- [x] https://github.com/mojaloop/central-services-health/pull/240
- [x] https://github.com/mojaloop/ml-number/pull/16
- [x] https://github.com/mojaloop/central-object-store/pull/26
- [x] https://github.com/mojaloop/central-ledger/pull/842
- [x] https://github.com/mojaloop/central-ledger/pull/843
- [x] https://github.com/mojaloop/central-ledger/pull/844
- [x] https://github.com/mojaloop/central-ledger/pull/845
- [x] https://github.com/mojaloop/central-ledger/pull/853
- [x] https://github.com/mojaloop/account-lookup-service/pull/408
- [x] https://github.com/mojaloop/account-lookup-service/pull/411
- [x] https://github.com/mojaloop/central-settlement/pull/351
- [x] https://github.com/mojaloop/central-settlement/pull/353
- [x] https://github.com/mojaloop/bulk-api-adapter/pull/56
- [x] https://github.com/mojaloop/bulk-api-adapter/pull/58
- [x] https://github.com/mojaloop/simulator/pull/222
- [x] https://github.com/mojaloop/simulator/pull/223
- [x] https://github.com/mojaloop/ml-testing-toolkit-shared-lib/pull/8
- [x] https://github.com/mojaloop/transaction-requests-service/pull/72
- [x] https://github.com/mojaloop/central-event-processor/pull/223
- [x] https://github.com/mojaloop/ml-api-adapter/pull/474
- [x] https://github.com/mojaloop/mojaloop-simulator/pull/106
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/275
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/277
- [x] https://github.com/mojaloop/quoting-service/pull/272
- [x] https://github.com/mojaloop/account-lookup-service/pull/415
- [x] https://github.com/mojaloop/email-notifier/pull/185
- [x] https://github.com/mojaloop/email-notifier/pull/186
- [x] https://github.com/mojaloop/event-sidecar/pull/41
- [x] https://github.com/mojaloop/central-settlement/pull/356
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/40
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/41
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/42

## **Issues**:
- [x] https://github.com/mojaloop/project/issues/2182
- [x] https://github.com/mojaloop/project/issues/2171
- [x] https://github.com/mojaloop/project/issues/2017
- [x] https://github.com/mojaloop/project/issues/2243
- [x] https://github.com/mojaloop/project/issues/2083
- [ ] https://github.com/mojaloop/project/issues/2149
- [x] https://github.com/mojaloop/project/issues/1891
- [x] https://github.com/mojaloop/project/issues/2246
- [x] https://github.com/mojaloop/project/issues/2302
- [x] https://github.com/mojaloop/project/issues/2304
- [x] https://github.com/mojaloop/project/issues/2304
- [x] https://github.com/mojaloop/project/issues/2308
- [ ] https://github.com/mojaloop/project/issues/2313

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @mdebarros 
- QA/Review: @mdebarros @elnyry-sam-k @vijayg10 @vgenev

**Comment by mdebarros** [comment]
- [] Transaction-Request-service
- [] Testing-toolkit (@vijayg10)
- [] Finance-portal
- [] Event-SDK
- [] Event-stream-processor
- []
