### ISSUE TITLE
[design] - Determine outcomes and goals for a PISP Hackathon

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2155]
Answer the following questions:

1. What is a solid Hackathon Experience?
2. Understand participants and motivations of attendees of a PISP hackathon - and who we want to attract
3. Who are the personas? e.g. A fintech acting as a PISP? A merchant interacting with a PISP?
4. What are the sorts of demos that can inspire hackathon attendees?
5. What does good documentation look like? Find some inspiration and start some templates:
    - integration guide for a PISP
    - API guide
    -  

Acceptance Criteria:
- [ ] a set of 4 well defined personas/use cases for what we will want to demo to support a hackathon
- [ ] a set of docs templates we can follow when writing docs for each use case
- [ ] a plan for what a good hackathon experience looks like

**Comment by lewisdaly** [comment]
Removing, will re add if we determine it is in scope for PI 15
