### ISSUE TITLE
As a Hub Operator/Participant, I need to be able to generate operational and audit reports.

### ISSUE THREAD

**Issue by HenkKodde** [mojaloop/project#216]
**Goal**:
Implement a Retrieval API for reporting.

**Task**:
- [ ] Design and implement an reporting API with the objective to make relevant meta data available to Hub's/Participants. This will enable them to use a reporting tool of there preference, to generate a variation of operational and audit reports to complement there business and regulatory processes and requirements.

**Acceptance Criteria**:
- [ ] Role base access needs to be applied. 
- [ ] Hub will be able to see all the data applicable to the Hub. 
- [ ] Participant will only receive data pertaining to the requesting Participant. 
- [ ] Verify that the data model includes an auditable record of the quote request as per Mojaloop API POST /quote.
- [ ] Verify that the data model includes an auditable record of the quote response as per Mojaloop API POST /quote.
- [ ] Verify that the requesting party can be identified.
- [ ] Verify that the responding party can be identified.
- [ ] Verify that the data model can reconcile requests and responses.
- [ ] Verify that the data model supports linking a quote to a transfer.

**Dependencies**:
- [ ] #214

**Comment by elnyry-sam-k** [comment]
should be covered as part of bus ops workstream
