### ISSUE TITLE
TTK - Add functionality for grouping the test case files

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2161]
## **Goal**:
`As a` individual implementer

`I want to` have an ability to select a group of test suites to be run from the central repository
  
`so that` I need not maintain a my own set of files and folders

**Acceptance Criteria**:
- [x] A theme / template can be selected to run a group of tests spread across multiple folders and sub-folders in a collection
- [x] Ability to create a theme / template

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Design the file format to serve the following use-cases (Either master.json file or a separate file for this)
  - [x] Name and description for the template / theme
  - [x] A group of testsuites can be included
  - [x] A group of testsuites can be omitted
- [x] Implement the UI to switch between the templates
- [x] Add the CLI options to list and select templates along with the collection

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/193
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/122
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/124
- [x] https://github.com/mojaloop/ml-testing-toolkit-shared-lib/pull/9

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @georgi-logodazhki 
- QA/Review: @vijayg10
