### ISSUE TITLE
[OS&T FG] Demonstration of "how to set up Mojaloop"

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2163]
## **Goal**:
`As a` Community contributor

`I want to` understand how to set up Mojaloop
  
`so that` I can set it up (easily) and contribute

**Notes**:
1. Create a recording of how to set up Mojaloop, but break it up into multiple smaller videos.  This way, when there are changes it will be possible to tag the smaller video with updated comments.  This way there will not be a need to redo the video with every change [Question: Is this for local development or is the goal to setup a Mojaloop Switch (core)? ]
2. Incorporate feedback from Sybrin team who documented some of the procedures
3. Pre-requisites: setup k8s, everything before running the helm command (we need to provide helpful links for pre-reqs).
4. how to install k8s on various OS (Linux, MacOS) - only Mac possible for now - documentation links
5. How to deploy Mojaloop
  - [x] video#1 on pre-reqs
  - [x] using helm install  (video#2)
  - [x] using helm test to validate(video#2)
  - [x] using TTK to validate (video#3)

**Acceptance Criteria**:
- [x] Separate videos describing "how to set up Mojaloop" are published

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [x] Acceptance Criteria pass
- [x] Docs are up-to date

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by StefanPrinsloo** [comment]
Hi
The feedback was regarding an Ubuntu local development setup.  Please find attached updated setup manual
[Installing the Mojaloop Stack on Ubutu ver 2.docx](https://github.com/mojaloop/project/files/6589751/Installing.the.Mojaloop.Stack.on.Ubutu.ver.2.docx)

**Comment by mdebarros** [comment]
@StefanPrinsloo, thanks for the document. Short and concise!

Would you be able to clarify this statement `Due to issues with the newer versions of helm with Mojaloop @Aarón Reynoza has recommended that we use Helm 2.16. So to install helm run:` <-- The OSS team has been using Helm v3 without any issues since v11.x. I would be interested in finding out more information here. Perhaps there is an issue that needs to be addressed within the Helm charts.

**Comment by mdebarros** [comment]
Videos:

1. https://drive.google.com/file/d/1iAj8oHKhEm2hmdTLGgofJAY6wwaJVZ0f/view?usp=sharing
2. https://drive.google.com/file/d/12xhWUwpuf0BK5Gi-Rwp5HbjU2gjCnMdu/view?usp=sharing
3. https://drive.google.com/file/d/1H8JX5uKrV7QrFkir37xIgsYYn6wf7C4N/view?usp=sharing
