### ISSUE TITLE
2.3.8.2.1 Implement eventLogging in PrepareHandler

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#217]
**Goal**:
As a developer
I want to _Implement eventLogging in PrepareHandler_
so that all events through the prepareHandler can be audited.

**Tasks**:
- [ ] Implement event Logging PrepareHandler

**Acceptance Criteria**:
- [ ] Kafka topic
- [ ] Central services to provide the following tables: transferEventIndex, eventName, 
- [ ] PrepareHandler to log events as per the sequence diagram design
- [ ] Ensure that events are persisted based on a log-level (info, warning, debug, etc)

**Dependencies**:
- [ ] #154 
- [ ] #239

**Accountability**
- Owner
- Review

**Comment by elnyry** [comment]
Covered as part of #824
