### ISSUE TITLE
[demo] - Connect PineapplePay demo to TTK Web Demo Flow

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2176]
## **Goal**:
`As a` user trying out the PineapplePay application

`I want to` be able to log in to my DFSP with an example web login
  
`so that` I can see the full end to end login flow

**Acceptance Criteria**:
- [ ] Running demo with the PineapplePay app + WEB Demo flow on the TTK

**Complexity**: Medium

**Uncertainty**: Medium
---

**Tasks**:
- [x] run the ttk demo alongside pineapple pay locally
- [x] update the fido client to use a consistent interface for Web and Android
- [x] update the demo app to pass through the entire attestation object for linking
- [x] add linking challenge derivation steps for the demo app
- [x] update the demo app to pass through the full signed challenge response for transfers
- [x] build out interface for web login (was already done)
- [x] run local web login demo locally
- [x] set up web login redirects

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- [ ] update demo server to handle updated APIs from api-snippets

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
