### ISSUE TITLE
Add integration tests for Continuous Gross Settlement model

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#2177]
## **Goal**:
`As a` OSS Contributor

`I want to` add integration tests for CGS model
  
`so that` the CGS functionality is verified by integration tests.

**Acceptance Criteria**:
- [ ] There are passing integration tests for CGS

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
