### ISSUE TITLE
Homepage documentation cleanup

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2179]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` <action>
  
`so that` <reason> 

**Acceptance Criteria**:
- [ ] All broken links and 404s are fixed
- [ ] Links to Training Materials are added from home page

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: Medium:  Some figuring out to be done to know where the code for the home page is.
---

**Tasks**:
- [ ] Fix broken links and 404s [ @meekg33k  ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
