### ISSUE TITLE
2.3.8.2.2 Implement eventLogging in PositionHandler

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#218]
**Goal**:
As a developer
I want to _Implement eventLogging in PositionHandler_
so that all events through the prepareHandler can be audited

**Tasks**:
- [ ] Implement event Logging in PositionHandler

**Acceptance Criteria**:
- [ ] Central services to provide the following tables: transferEventIndex, eventName
- [ ] PositionHandler to log events as per the sequence diagram design
- [ ] Ensure that events are persisted based on a log-level (info, warning, debug, etc)

**Dependencies**:
- [ ] #199
- [ ] #239 

**Accountability**
- Owner
- Review

**Comment by elnyry** [comment]
Covered as part of #824
