### ISSUE TITLE
Review Helm Chart v12.0.0 Packages for vulnerabilities using Snyk

### ISSUE THREAD

**Issue by rasputtintin** [mojaloop/project#2183]
## **Goal**:
As a Security Officer

I want to scan Mojaloop Helm chart v12.0.0 package vulnerabilities are resolved from CICD pipeline

so that I can report on any MEDIUM and HIGH risk vulnerabilities identified

**Acceptance Criteria**:
- [ ] Scan all referenced services with Snyk
- [ ] Prepare report highlighting MEDIUM and HIGH risk issues
- [ ] Share report with Dev Team and review together the recommendations for action

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @rasputtintin  ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rasputtintin 
- QA/Review: @godfreykutumela
