### ISSUE TITLE
Make recommendations on CICD Vulnerability triage process affecting skipping scans during build process

### ISSUE THREAD

**Issue by rasputtintin** [mojaloop/project#2184]
## **Goal**:
`As a` Security Officer

`I want to` make recommendations on security bug triage process within CICD build process
  
`so that` the process can be enhanced to minimise skipping of vulnerability scans within build process.

**Acceptance Criteria**:
- [ ] TBD @rasputtintin 

**Complexity**: <Medium> A short comment to remind the reason for the rating

**Uncertainty**: <Medium> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @rasputtintin  ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
