### ISSUE TITLE
TTK - Ability to select github release of test cases in UI

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2186]
## **Goal**:
`As a` individual implementer

`I want to` have option to select release / tag / branch for git testcases repository
  
`so that` I can select various test cases accordingly

**Acceptance Criteria**:
- [x] An option is available at github test-cases component to select tags, ~~branches~~ or a particular release
- [x] A default option for the above can be configurable via user config of TTK

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Explore git http API to get release / tag ~~and branch~~ information
- [x] List the tags ~~and branches~~ in the UI
- [x] List the files & folders based on the selected tag ~~/ branch~~
- [x] Download function should be refactored based on the selected tag ~~/ branch~~
- [x] Add the config param in userconfig for default tag

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/97

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: @mdebarros
