### ISSUE TITLE
Design of Authentication and Authorization Framework​: RBAC implementation with IAM, JamStack, Microservice

### ISSUE THREAD

**Issue by Dorota-MB** [mojaloop/project#2189]
## **Goal**:
`As a`  Technical support engineer working for a Hub Operator

`I want to`  configure the UI microservices and the backend API access to enable a customised business operational portal deployment to a CDN network to be used by the hub operator staff
  
`so that` best practice RBAC and IAM is applied to the deployment and API access, optional customisations that are build by independent work efforts are built into the deployment, and a User and role based audit log exists for any usage of the portal.

**Acceptance Criteria**:
- [ ] The Proposed Design should Meet Jamstack Design Principles
  - Static Mark-up
  - Atomic Deployment
  - Client side JavaScript 
  - BackEnd APIs
- [ ] Mojaloop Design Authority Acceptance
- [ ] Document considerations for Mojaloop Reference Architecture Future Proofing 
- [ ] Document considerations for IAC4 Architecture Future Proofing 
- [ ] Create series of Artefacts that cover the Community Design and Processes
- [ ] Build POC to support the design principles

**What is not included in this Epic but expected to provided later on**
- Documented UI design principles 
- Guidelines for community collaboration (reviewed by Community council) to accelerate community contributions are published

**Squad Allocation Suggestions**:
- RBAC - Fry & Russel
- UI Design - Ivan & Vijay 
- POC - Yehvin, Kevin and Vijay

**Complexity**: <High > Multiple concepts combined

**Uncertainty**: <Med>  Failure with the tools, however have not put them together this way before. May need to use a new state lib.

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

**Comment by PaulGregoryBaker** [comment]
Definition of done will include
- [ ] PoCs done to finalize technology stack, architecture and deployment models
- [ ] Best practice design presented to the DA and feedback incorporated
- [ ] Finalize & demonstrate IAM framework example (PoC of UI framework presented to the DA for feedback)
