### ISSUE TITLE
2.3.8.2.3 Implement eventLogging in TransferHandler

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#219]
**Goal**:
As a developer
I want to _Implement eventLogging in TransferHandler_
so that all events through the TransferHandler can be audited

**Tasks**:
- [ ] Implement event Logging TransferHandler

**Acceptance Criteria**:
- [ ] Central services to provide the following tables: transferEventIndex, eventName, 
- [ ] TransferHandler to log events as per the sequence diagram design
- [ ] Ensure that events are persisted based on a log-level (info, warning, debug, etc)

**Dependencies**:
- [ ] #205 
- [ ] #239 

**Accountability**
- Owner
- Review

**Comment by elnyry** [comment]
Covered as part of #765
