### ISSUE TITLE
Implement Batch Process on PositionHandler

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#221]
**Goal**:
As a developer I would like to __Implement Batch Process on PositionHandler__ so that PositionHandler processing is performant

**Tasks**:
- [ ] ...

**Acceptance Criteria**:
- [ ] Update Sequence Diagram to reflect Batch Processing Design
- [ ] Updated existing PositionHandler to cater for batch processing (batch insert)
- [ ] Updated existing PositionHandler to cache the current transferSettlementBatchId
- [ ] Updated existing PositionHandler to cache the current position
- [ ] Update existing tests (unit, integration, functional) that are impacted by this change

**Dependencies**:
- ...
