### ISSUE TITLE
Implement Batch Process on TransferHandler

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#222]
**Goal**:
As a developer I would like to __Implement Batch Process on TransferHandler__ so that TransferHandler processing is performant

**Tasks**:
- [ ] ...

**Acceptance Criteria**:
- [ ] Update Sequence Diagram to reflect Batch Processing Design
- [ ] Updated existing TransferHandler to cater for batch processing (batch update)
- [ ] Update existing tests (unit, integration, functional) that are impacted by this change

**Dependencies**:
- ...

**Comment by elnyry** [comment]
TransfersHandler has been removed a while ago and now this is no longer applicable
