### ISSUE TITLE
Community Documentation Setup

### ISSUE THREAD

**Issue by meekg33k** [mojaloop/project#2226]
## **Goal**:
`As a documentation user, I want to be able to able to navigate to the parent page for community documentation from where I can easily find other sections of the community documentation.

**Acceptance Criteria**:
- [x] `<baseUrl>/community` does not return a 404.
- [x] Parent page for community documentation is available on `<baseUrl>/community`.

**Complexity**: Medium. This involves creating a new route at https://docs.mojaloop.io/community

**Uncertainty**: High. Need to figure out what the existing route configuration is.

---

**Tasks**:
- Setup route configuration for the community documentation at https://docs.mojaloop.io/community- @meekg33k 
- Create a basic community documentation page - @meekg33k
---

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
