### ISSUE TITLE
Create Getting Started button on documentation home

### ISSUE THREAD

**Issue by meekg33k** [mojaloop/project#2227]
## **Goal**:
As a documentation user, I want to see a `Getting Started` button on the documentation home to help me easily get started with Mojaloop.

**Acceptance Criteria**:
- [ ] User can see `Getting Started` button when they navigate to the documentation home page.
- [ ] Clicking on the `Getting Started` button should take the user to a `Getting Started` documentation page at this url: `<baseUrl>/getting-started`.

**Complexity**: Low - Vuepress has in-built support for this.

**Uncertainty**: Low.

---

**Tasks**:
- [ ] Add `Getting Started` button to documentation's index `README` - @meekg33k 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @meekg33k 
- QA/Review: TBD
