### ISSUE TITLE
ML TTK: Mindmap, initial outline of content for the MTP course

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2230]
## **Goal**:
`As a` MTP team member

`I want to` review a mind-map / course outline of the course for MTP TTK course
  
`so that` I can review and ensure it follows the requirements and contains everything needed to get the course started

**Acceptance Criteria**:
- [x] A mind-map depicting course outline for MTP TTK course is generated and documented
- [x] This mind-map is reviewed and accepted by the MTP team

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Create an initial mind-map depicting the course outline for an MTP TTK course
- [x] Review internally and address feedback
- [x] Review the MTP team and make necessary changes

**Done**
- [x] Acceptance Criteria pass
- [x] Mind-map, course outline are accepted by the MTP team and the course related effort moves to the next step

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 @elnyry-sam-k 
- QA/Review: MTP team
