### ISSUE TITLE
Add default settlement support into TTK tests

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#2231]
## **Goal**:
`As a` OSS contributor

`I want to` add support for deferred net Default settlement model into TTK test cases
  
`so that` Default settlement can be tested and demoed

**Acceptance Criteria**:
- [x] Central-Settlements TTK Golden path tests are updated to include Default SettlementModel configurations for deferred net
- [x] Golden Path includes both - currency specific and default - deferrednet settlement models and they are passing correctly 
- ~[ ] Central-Settlements TTK CGS tests are updated to:~
  - ~[ ]  setup the hub with a new currency and CGS settlement model for it~
  - ~[ ] run TTK CGS tests successfully~
  - ~[ ] run default currency and deferred settlement model test successfully~

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Add default settlement model in provisioning
- [x] Add secondary currency accounts
- [x] Create test cases for currency specific and default and settlement models

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] Release: https://github.com/mojaloop/testing-toolkit-test-cases/releases/tag/v13.0.0

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
