### ISSUE TITLE
ML TTK: Draft presentation for MTP TTK-101 for an initial review (first 3 topics)

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2232]
## **Goal**:
`As a` MTP team member

`I want to` review a draft presentation for the MTP TTK-101 focussing on the first 3 chapters (Intro, Overview and a single use case of usage)
  
`so that` we can consider it for the MTP-101 and proceed to next stages of developing the course and discuss standards for the. rest of the section

**Acceptance Criteria**:
- [x] A draft presentation with template slides for sections from mind-map (course outline) is submitted to the MTP team for the very first review
- [x] The sections for the first three chapters are covered in more detail to help gather feedback and understand standards to be applied for the rest of the course

**Complexity**: High

**Uncertainty**: Medium

---

**Tasks**:
- [x] Prepare an initial deck with various sections and sub-sections as templates
- [x] Add speaker notes for the first 3 chapters
- [x] Add narration text for each slide
- [x] Internal review with TTK team
- [x] Submit for an initial review with MTP team

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Presentation is reviewed and feedback provided to continue drafting rest of the sections

## **Pull Requests**:
- N/A

## **Follow-up**:
- #2341

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 @elnyry-sam-k 
- QA/Review: MTP team
