### ISSUE TITLE
Updated Settlement Designs with default settlement

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#2234]
## **Goal**:
`As a` Hub Operator

`I want to` understand Settlement Designs that include default SettlementModel support 

`so that` Default settlements flows can be understood and adopted

**Acceptance Criteria**:
- [ ] Settlement Designs include the default SettlementModel support

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Add default settlement model in provisioning
- [ ] ~Create test cases for default and mixed settlement setups~ issue #2314 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: Core team
