### ISSUE TITLE
ML TTK: Export test case details in readable format (from test cases)

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2237]
## **Goal**:
`As a` Release Manager

`I want to` be able to export test case details such as names, descriptions and other useful information from test cases
  
`so that` I can generate a (readable) report with test case details that can help understand coverage and scenarios covered, etc.

**Acceptance Criteria**:
- [x] During exporting of test cases, test case details are exported as well as a readable file.

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [x] Understand requirements and information needed, use sample data [@vijayg10]
- [x] Explore how fields can be exported
- [x] Implement Edit info functionality in UI
- [x] Implementation tasks TBD

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/174
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/108
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/45

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

**Followup Stories**
- https://github.com/mojaloop/project/issues/2348

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
Documentation can be found at this link

https://github.com/mojaloop/ml-testing-toolkit/blob/master/documents/User-Guide-Mojaloop-Testing-Toolkit.md#59-download-testcase-definition
