### ISSUE TITLE
use latest API definitions for auth-service

### ISSUE THREAD

**Issue by eoln** [mojaloop/project#2238]
## **Goal**:
`As a` Dev

`I want to` use the latest API design
  
`so that` auth-service will be compatible with the rest of the PISP services

**Acceptance Criteria**:
- [x] use latest API design specified in diagrams from `pisp` repo
- [x] use generated from API spec DTO

**Complexity**: <High> > Multi endpoints to touch and multiple unit/integration tests to fix

**Uncertainty**: <Low> > daily bread

---

**Tasks**:
- [x] use latest api-snippets with newest way of generating API interfaces
- [x] identify changes and prepare related tasks here:
  - [x] API interfaces changes in API snippets for credential registration
  - [x] refactor API interface for POST /consents in AUTH scenario
  - [x] POST /consents  
  - [x] PUT /consents/{ID}
- [x] validate credential using crypto

**Done**
- [x] Acceptance Criteria pass
- [ ] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/api-snippets/pull/92
- [x] https://github.com/mojaloop/api-snippets/pull/93
- [x] https://github.com/mojaloop/api-snippets/pull/94

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
