### ISSUE TITLE
[OS&T FG] Describe, demonstrate (typical) scenarios using APIs

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2244]
## **Goal**:
`As a` contributor to Mojaloop

`I want to` understand correlation between the APIs, APIs and various scenarios
  
`so that` I can easily understand the correlation between APIs and typical scenarios such as making a payment, creating an FSP, etc..

**Note**: This story is limited to catering for the limited set of scenarios identified in the story. This can be used as template for other scenarios not covered here.

**Acceptance Criteria**:
- [ ] A demonstration or documentation artifact is produced showing correlation between API calls (APIs) and an (end-to-end) scenario for FSP creation
- [ ] A demonstration or documentation artifact is produced showing correlation between API calls (APIs) and an (end-to-end) scenario for making a payment

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] Analyze scenarios for this iteration (FSP creation, make a payment)
- [ ] Create a demonstration, analysis using API calls (APIs) to achieve an end-to-end scenario for FSP creation
- [ ] Create a demonstration, analysis using API calls (APIs) to achieve an end-to-end scenario for making a payment (P2P)
- [ ] Review with OS&T team
- [ ] Finalize approach by addressing, incorporating feedback.

**Done**
- [ ] Acceptance Criteria pass
- [ ] Documentation, demonstration related artifacts are uploaded to appropriate locations (GitHub, Dropbox, mojaloop.io, etc)

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: OS&T CoCo team
