### ISSUE TITLE
[OS&T FG] Streamline GitHub search, navigation for onboarding

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2245]
## **Goal**:
`As a` contributor to Mojaloop

`I want to` be able to understand the repository structure of Mojaloop and search, navigate easily
  
`so that` I can find the docs, information I need and the repositories relevant to the topic I'm looking for

**Notes**:
Challenges: Finding relevant information
1. Many repos in GitHub and sources, difficult to understand where what is, the centralised documentation (Mojaloop website) is outdated.
2. The search engine returns lot of unnecessary details, not like in "stack overflow" which provide more focussed results
Suggestion to improve;  We think this will naturally get better as more content is added.  Possibly consider a google type search covering all sources 

**Acceptance Criteria**:
- [ ] Every repository in Mojaloop GitHub has description, naming, tags and readme files that help easily identify what the repo does and what it is for
- [ ] Repositories are categorized into well organized groups (libraries, services, tools, supporting services) and the names reflect that.
- [ ] Its easy for search for required information on mojaloop (search functionality - refine the requirement further)

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: OS&T CoCo team
