### ISSUE TITLE
Create a new repository for Mojaloop Docs 2.0

### ISSUE THREAD

**Issue by meekg33k** [mojaloop/project#2247]
## **Goal**:
`As a documentation user or contributor, I want to see the new Mojaloop documentation so that I can view it locally or contribute to it.`

**Acceptance Criteria**:
- [ ] New repository for Mojaloop Docs 2.0 is available on GitHub.

**Complexity**: Low - creating a new repository on GitHub isn't difficult. 

**Uncertainty**: Medium - decision to create new or use existing repository.

---

**Tasks**:
- [ ] Check-in with @lewisdaly if we need to create a new repository or use the existing [Hackathon docs](https://github.com/mojaloop/hackathon-docs) repository [ @meekg33k  ]

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: [@meekg33k]
- QA/Review: TBC

**Comment by lewisdaly** [comment]
What's the value in creating a new repo here? Isn't it easier to just make a new branch (for example something like `v2.0`)?

**Comment by meekg33k** [comment]
@lewisdaly, a branch off the existing hackathon-docs [https://github.com/mojaloop/hackathon-docs] repository?

**Comment by lewisdaly** [comment]
I would say off of the `mojaloop/documentation` repo

**Comment by meekg33k** [comment]
@lewisdaly, this is for the [new documentation](https://github.com/mojaloop/project/issues/2248) using vuepress.

**Comment by lewisdaly** [comment]
Sure. I'd still say that it should live in the `mojaloop/documentation` repo - the `hackathon-docs` repo does contain a first attempt at doing some demos with vuepress, but there's no reason to migrate all the new docs there. That repo was originally just a dumping ground for our random docs associated with running hackathons.

In the past, we've set up long-lived branches for different projects and purposes, so we can set up a workflow that publishes/compiles a vuepress site from a branch of `mojaloop/documentation` for people to view and get a feel for it.
