### ISSUE TITLE
Setup Mojaloop Documentation 2.0 with Vuepress

### ISSUE THREAD

**Issue by meekg33k** [mojaloop/project#2248]
## **Goal**:
`As a user who is part of the Mojaloop community, I want to see that the new Mojaloop documentation is setup to use VuePress so that I can contribute more easily to the documentation.`

**Acceptance Criteria**:
- [ ] User can see the new Mojaloop documentation 

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] Setup a new project for Mojaloop Documentation 2.0 [ @meekg33k ]
- [ ] Install [vuepress](https://github.com/vuejs/vuepress) and all the related dependencies in the [ @meekg33k  ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: [ @meekg33k ]
- QA/Review: TBD

**Comment by meekg33k** [comment]
Setup completed and can be found [here](https://github.com/mojaloop/documentation/tree/mojaloop-docs-2.0/vuepress)
