### ISSUE TITLE
Integration Testing for ML-API-Adapter

### ISSUE THREAD

**Issue by ksatya77** [mojaloop/project#225]
**Goal**:
As a developer I would like to implement Integration Testing for ML-API-Adapter

**Tasks**:
- [x]  Determine an approach to spin up kafka locally or in CircleCI during Integration tests.

**Acceptance Criteria**:
- [ ] Test Coverage includes Integration Testing

**Dependencies**:
- [ ] Use #223 as baseline

**Comment by elnyry** [comment]
Duplicate, covered as part of #197
