### ISSUE TITLE
Setup navigation bar on Mojaloop Documentation 2.0

### ISSUE THREAD

**Issue by meekg33k** [mojaloop/project#2250]
## **Goal**:
`As a documentation user, I want to see a navigation bar with links to different parts of the documentation and other relevant content so I can navigate easily through the documentation.`

## **Description**:
The following links should be accessible in the navigation bar:
- Getting started
- Community
- Technical (APIs): TBD
- Mojaloop Training Program

**Acceptance Criteria**:
- [ ] User can see navigation bar.
- [ ] User can see a `Getting Started` link in the navigation bar.
- [ ] User can see a `Community` link in the navigation bar.
- [ ] User can see a `Technical` link in the navigation bar.
- [ ] User can see a link to the `Training program` link in the navigation bar.
- [ ] The navigation bar is accessible from all documentation pages.

**Complexity**: Low - Vuepress already has in-built support for this.

**Uncertainty**: Low

---

**Tasks**:
- [ ] Setup the config required to enable the links [ @meekg33k ]
- [ ] Connect the links to the right documentation [ @meekg33k ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: [ @meekg33k ]
- QA/Review: TBC
