### ISSUE TITLE
Create community documentation index page

### ISSUE THREAD

**Issue by meekg33k** [mojaloop/project#2252]
## **Goal**:
As a documentation user, I want to see the parent page for community documentation at  `<baseUrl>/community`  from where I can easily find other parts of the community documentation.

**Acceptance Criteria**:
- [ ] `<baseUrl>/community` does not return a 404.
- [ ] Community documentation parent page is accessible from the navigation bar.

**Complexity**: Low

**Uncertainty**: Low.

---

**Tasks**:
- Create the community documentation `README` - @meekg33k
- Connect the `Community` link in the navigation bar to this page - @meekg33k 
---

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: [ @meekg33k ]
- QA/Review: TBC
