### ISSUE TITLE
Create Getting Started documentation index page

### ISSUE THREAD

**Issue by meekg33k** [mojaloop/project#2254]
## **Goal**:
As a documentation user, I want to see the parent page for community documentation at  `<baseUrl>/getting-started`  from where I can easily find other parts of the community documentation.

## **Description**:
The index page should contain the following (with appropriate links) as possible actions a user can take:

1. **View the quickstarts**: `<baseUrl>/getting-started/quickstart.html`
2. **Watch a demo**: `TBD`
3. **Read the documentation**: `https://docs.mojaloop.io/`
4. **Test out Mojaloop APIs**: `TBD`
5. **Take a training program**: `https://mojaloop.io/mojaloop-training-program/`
6. **Contribute to Mojaloop**: `<baseUrl>/community/contributors-guide.html`

**Acceptance Criteria**:
- [ ] `<baseUrl>/getting-started` does not return a 404.
- [ ] `Getting Started` documentation index page is accessible from the navigation bar.
- [ ] User can see a list of possible first actions from this page.

**Complexity**: Low

**Uncertainty**: Low.

---

**Tasks**:
- Create the `Getting Started` documentation `README` - @meekg33k
- The `Getting Started` documentation `README` should contain a list of possible first actions a user can take - @meekg33k
- Connect the `Getting Started ` link in the navigation bar to this page - @meekg33k
---

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: [ @meekg33k ]
- QA/Review: TBC
