### ISSUE TITLE
Create Getting Started documentation sub-pages

### ISSUE THREAD

**Issue by meekg33k** [mojaloop/project#2255]
## **Goal**:
As a documentation user, I want to see the other pages in the `Getting Started` documentation that point me to relevant documentation for getting started with interacting with Mojaloop.

## **Description**:
The sub-pages should be in the `<baseUrl>/getting-started/<subPage>` path and they should be categorized under the following groups, which should be visible on the sidebar.
1. **Quickstarts**: containing pages with useful information about quick starts.
2. **Demos**: containing all demo sub-pages.
3. **FAQs**: containing all FAQ-related sub-pages.

**Acceptance Criteria**:
- [ ] All sub-pages should be under the `<baseUrl>/getting-started` path.
- [ ] A user should be able to easily navigate between the sub-pages by clicking on the `->` and `<-` buttons

**Complexity**: Medium

**Uncertainty**: Medium - Has a dependency on [#2256]

---

**Tasks**:
- Create placeholder README files for the sub-pages inside the `getting-started` directory - @meekg33k
- Update sidebar configuration for `/getting-started` to group the sub-pages as described above - @meekg33k
- Validate that clicking on `<-` and `->` buttons navigates the user through the documentation sub-pages - @meekg33k
---

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: [ @meekg33k ]
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
completed in v1 but revamped in v2 as well
