### ISSUE TITLE
Setup sidebar for the Getting Started documentation

### ISSUE THREAD

**Issue by meekg33k** [mojaloop/project#2256]
## **Goal**:
As a documentation user who visits the `Getting Started` documentation: `<baseUrl>/getting-started`, I want to see well-structured links to other parts of the `Getting Started` documentation on the sidebar so that I can easily navigate to other parts by clicking on any of the links. 

## **Description**:
The sidebar should be have the following groups, with each group containing links to the relevant documentation:
1. **Quickstarts**
2. **Demos**
3. **FAQs**

**Acceptance Criteria**:
- [ ] The groups should be visible on the sidebar.
- [ ] The sub-pages within each group should be visible on the sidebar.

**Complexity**: Low - Vuepress has an in-built configuration to support this.

**Uncertainty**: Low

---

**Tasks**:
- [ ] Add sidebar config for the `/getting-started/` path - @meekg33k 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
looks like this is implemented: https://docs.mojaloop.io/getting-started/
