### ISSUE TITLE
Migrate FAQs from existing documentation to Mojaloop Documentation 2.0

### ISSUE THREAD

**Issue by meekg33k** [mojaloop/project#2259]
## **Goal**:
As a documentation user, I want to see that the FAQs at the current [documentation](https://docs.mojaloop.io/documentation/contributors-guide/frequently-asked-questions.html) have been moved to the new documentation, so I can view it there.

## **Description**:
The new location for the FAQs would be under the `Getting Started` documentation as mentioned in #2256.

**Acceptance Criteria**:
- [x] Users can see the FAQs in the `Getting Started` section of the documentation.

**Complexity**: Low

**Uncertainty**: High - migration may require some cleanup and assets may need to be replaced.

---

**Tasks**:
- [x] Create new FAQ readme file in the `/getting-started/` directory in the new project - @meekg33k 
- [x] Copy existing [FAQ readme](https://github.com/mojaloop/documentation/blob/master/contributors-guide/frequently-asked-questions.md) to Mojaloop Documentation 2.0 project - @meekg33k 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @meekg33k 
- QA/Review: TBC
