### ISSUE TITLE
Automated Test case for P2P Money Transfer

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#226]
**Goal**:

As a Quality Analyst, I would like to define and implement _a BDD style test case for a successful P2P Money Transfer_ so that this can be used as a base test case for Regression Testing needs and also for Demo purposes.
 
**Tasks**:
- [X] Define Gherkin Scenarios and their corresponding implementation in Cucumber for User Onboarding using POST /participants/{TYPE}/{ID} endpoint - Done
- [X] Define Gherkin Scenarios and their corresponding implementation in Cucumber for User Look-up using GET /parties/{TYPE}/{ID} endpoint - Done
- [x] Define Gherkin Scenarios and their corresponding implementation in Cucumber for Quotes using POST /quotes endpoint
- [x] Define Gherkin Scenarios and their corresponding implementation in Cucumber for P2P transfer using  Post /transfers endpoint

**Acceptance Criteria**:
- [ ] As this is a positive scenario for a P2P Money Transfer, getting a final successful transfer response is considered a success criterion for this story.

**Dependencies**:
- #193

**Comment by ksatya77** [comment]
Code looks good. For the next sprint, this code needs to point to the Mojaloop codebase deployed on K8 cluster and make sure that golden path is working as expected.
