### ISSUE TITLE
Migrate community docs from existing documentation to Mojaloop Documentation 2.0

### ISSUE THREAD

**Issue by meekg33k** [mojaloop/project#2260]
## **Goal**:
As a documentation user, I want to see that all community-related documentation have been moved to the new documentation, so I can view it there.

## **Description**:
The pages to be migrated can be found at the link [here](https://docs.mojaloop.io/documentation/contributors-guide/).

**Acceptance Criteria**:
- [ ] Users can now see all the pages under the `Community` section of the documentation under the different groups described in #2257.

**Complexity**: Medium

**Uncertainty**: High - migration may require some cleanup and assets may need to be replaced.

---

**Tasks**:
- [ ] Create new README files for each of the docs to be migrated in the `/community/` directory in the new project - @meekg33k 
- [ ] Copy the content to the newly created files in the Mojaloop Documentation 2.0 - @meekg33k 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @meekg33k 
- QA/Review: TBC
