### ISSUE TITLE
Cleanup & restructure migrated community docs

### ISSUE THREAD

**Issue by meekg33k** [mojaloop/project#2261]
## **Goal**:
As a documentation user, I want to see that the migrated community documentation is cleaned up and restructured inline with the [Mojaloop Documentation 2.0 Architecture](https://docs.google.com/presentation/d/1E8zh-B7FehlDShpLbyz88MhobYSodEILnsgfb2OdRqM/edit?usp=sharing)

## **Description**:
The details of the restructuring are outlined in the table below:

|  Documentation Group |  Current Location   | New Location |
| ---------------------- | -------------------- | --------------------- |
| Contributor's Guide |  [Current URL](https://docs.mojaloop.io/documentation/contributors-guide/) | `<baseUrl>/community/contributors-guide.html` |
| Standards |  [Current URL ](https://docs.mojaloop.io/documentation/contributors-guide/standards/) | `<baseUrl>/community/standards.html` |
| Tools and Technologies |  [Current URL](https://docs.mojaloop.io/documentation/contributors-guide/tools-and-technologies/) | `<baseUrl>/community/tools-and-technologies.html` |
| Documentation|  [Current URL](https://docs.mojaloop.io/documentation/contributors-guide/documentation/) | `<baseUrl>/community/documentation.html` |

**Acceptance Criteria**:
- [ ] Users can see the restructured community documentation pages.

**Complexity**: Medium

**Uncertainty**: High - difficult to estimate how long cleanup may take.

---

**Tasks**:
- [ ] Update the sidebar config for `/community` to reflect reference architecture - @meekg33k 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @meekg33k 
- QA/Review: TBC
