### ISSUE TITLE
[pisp-demo-server] - Update types to use API Snippets

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2263]
## **Goal**:
`As a` user testing out the PISP features and codebase

`I want to` see consistent use of types in the pisp demo server
  
`so that` I can easily reason about and use the PISP examples

**Acceptance Criteria**:
- [x] switched from sdk-standard-components defined types in Demo server to latest api-snippets

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [x] replace existing local API defs with api-snippets
- [x] replace sdk-standard-components types with api-snippets
- [x] fix compile time issues
- [x] fix tests
- [x] merge in changes from local #2176 branch
- [x] run docker-local and load a new pisp for the local pisp-demo-server
- [x] end to end manual test account linking from pineapplepay app
- [x] end to end manual test account transfers from pineapplepay app - blocked by mojaloop/project#2316
- [x] fix outstanding references to old API in demo server

**Done**
- [x] Acceptance Criteria pass
- [x] Unit Tests pass
- [ ] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/contrib-pisp-demo-svc/pull/63
- [x] https://github.com/mojaloop/pisp/pull/139
- [x] https://github.com/mojaloop/contrib-pisp-demo-ui/pull/57
- [x] https://github.com/mojaloop/contrib-pisp-demo-svc/pull/64
- [x] https://github.com/mojaloop/pisp/pull/140
- [x] https://github.com/mojaloop/contrib-pisp-demo-svc/pull/65
- [x] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/106
- [x] https://github.com/mojaloop/contrib-pisp-demo-ui/pull/58
- [x] https://github.com/mojaloop/contrib-pisp-demo-svc/pull/66
- [x] https://github.com/mojaloop/pisp-project/pull/142

## **Follow-up**:
- [ ] demo server - update to use `/services` call - Blocked by https://github.com/mojaloop/project/issues/2310
- contrib-pisp-demo-ui:
    - remove custom currency definition, this should always come from the messages with mojaloop    
    - allow the user to select the live or simulated switch in the demo app
    - send through signed challenge in p2p transfer

- contrib-pisp-demo-svc:
    - use the newer `/services` endpoint
    - allow the user to select the live or simulated switch in the demo app
    - replace `/authorizations` with `/thirdpartyRequests/transactions/{id}/authorizations`
    - send through signed challenge in p2p transfer

- pisp-project/docker-local:       
    - clean up readme 
    - remove ttk instances
    - fix ttk for /services stuff

- ml-bootstrap:
    - remove unused endpoints and sort properly

- thirdparty-scheme-adapter:
    - add a THIRD_PARTY_LINK lookup step to resolve the correct identifier    

- sdk-scheme-adapter:
    - fix the quote not found bug

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
- E2E account linking demo working from pineapplepay with docker-local!

**Comment by lewisdaly** [comment]
This is now blocked by: mojaloop/project#2311
