### ISSUE TITLE
SDK-Scheme-Adapter validates Inbound FSPIOP request content-type headers

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2264]
## **Goal**:
`As a` SDK-Scheme-Adapter User

`I want to` ensure that the SDK-Scheme-Adapter validates Inbound FSPIOP request content-type headers
  
`so that` the header validation conforms to the FSPIOP Specification

**Acceptance Criteria**:
- [ ] FSP Inbound request headers are validated against the FSPIOP content-type specification throwing an FSPIOP Error: `3001 - Unacceptable version requested` (ref: https://docs.mojaloop.io/mojaloop-specification/fspiop-api/documents/API%20Definition%20v1.1.html#table-112)

- [ ] FSP Inbound request content-type header is correctly matched to the operation (i.e. transfers, parties or participants) throwing an FSPIOP Error: `3001 - Unacceptable version requested` (ref: https://docs.mojaloop.io/mojaloop-specification/fspiop-api/documents/API%20Definition%20v1.1.html#table-112)

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/sdk-scheme-adapter/pull/278

## **Follow-up**:
- https://github.com/mojaloop/project/issues/1891

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Initial thinking on how to resolve this --> https://github.com/mojaloop/sdk-scheme-adapter/pull/276

However, much re-factoring required on unit/integration tests.
