### ISSUE TITLE
Update repos to use new mojaloop naming conventions

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2266]
## **Goal**:
`As a` newcomer to the community

`I want to` have clearly established repo naming conventions
  
`so that` I can easily reason about which repos are for what purpose

**Acceptance Criteria**:
- [ ] Mojaloop GitHub repositories' names are informative indicating whether they're services, libraries, etc. and convey related information

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] TODO: link to best practices [owned by Pedro's] doc, and examples: [here](https://docs.google.com/document/d/1AZbX0UjraytFty0IWOHpyR6z35bh0-MCFG1vGKId_5M/edit?usp=sharing)
- [x] Planning, discuss repercussions, follow-up tasks
- [ ] Rename repositories that are not part of Mojaloop helm charts
- [ ] Rename repositories part of Mojaloop helm charts in one-go (with release targeted for ML v14)

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to dat3
- [ ] Mojaloop GitHub repositories are renamed to follow adopted standards

## **Pull Requests**:
- [ ] https://github.com/mojaloop/central-object-store/pull/31
- [ ] https://github.com/mojaloop/auth-lib/pull/142

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
As @elnyry-sam-k noted:

- How do repo names affect the names of the docker images?
- Tag repos with automated releases so it's easy to know when to do automated releases or not

Will follow up on a call on Thursday
