### ISSUE TITLE
Automated Contract Testing for Mojaloop API - /participants/{TYPE}/{ID}/{SubID} endpoint

### ISSUE THREAD

**Issue by ksatya77** [mojaloop/project#227]
**Goal**:
As a Quality Analyst, I would like to define and implement _Positive and Negative Automated Contract Test Cases for /participants/{TYPE}/{ID}/{SubID} endpoint in the Mojaloop API_ so that User Onboarding business feature is tested end-end.

**Tasks**:
- [ ] Define Gherkin Scenarios and their corresponding implementation in Cucumber for GET, PUT, POST, DELETE of /participants/{TYPE}/{ID}/{SubID} endpoint
- [ ] Define Gherkin Scenarios and their corresponding implementation in Cucumber for PUT /participants/{Type}/{ID}/{SubID}/error endpoint
 - [ ] Across all the above endpoints positive and negative test cases for field lengths, data-types, required/optional fields for requests and responses to be defined and implemented.

**Acceptance Criteria**:
- [ ] For /participants/{TYPE}/{ID}/{SubID} endpoint, positive and negative tests for different combinations of {TYPE}, {ID} and {SubID} are executed and the results are available as part of Cucumber Report.
- [ ] Across all the above endpoint the following Headers are accepted and processed by the application: Content-Type
Date
X-Forwarded-For
FSPIOP-Source
FSPIOP-Destination
FSPIOP-Encryption
FSPIOP-Signature
FSPIOP-URI
FSPIOP-HTTP-Method
- [ ] For Negative Test Cases, the application returns the appropriate error code as defined below in the API Specification: 400, 401, 403, 404, 405, 406, 501, 503
- [ ]  All the test cases defined and implemented in Cucumber should run automatically without any manual intervention

**Dependencies**:
- [ ] #193

**Comment by elnyry** [comment]
Closing this as this Epic/Topic isn't part of the plan for Mojaloop PI-3. Please re-open if necessary.
