### ISSUE TITLE
Setup versioning for Mojaloop Docs 2.0

### ISSUE THREAD

**Issue by meekg33k** [mojaloop/project#2272]
## **Goal**:
As a documentation user, I want to be able to view different versions of the Mojaloop documentation.

**Description**:
This feature allows a documentation user to be able select different versions of the documentation. By default, the user should see the current version but should 

**Acceptance Criteria**:
- [ ] User sees the default version of the documentation by default.
- [ ] User can see a dropdown to select a different version of the documentation.
- [ ] Selecting a different version displays that version of the documentation.

**Complexity**: Medium

**Uncertainty**:  Medium: Possibly requires restructuring of the project directory.

---

**Tasks**:
- [ ] Setup folder structure to support documentation versioning - @meekg33k 
- [ ] Enable versioning using plugin - @meekg33k 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
