### ISSUE TITLE
Use Mojaloop brand theme 

### ISSUE THREAD

**Issue by meekg33k** [mojaloop/project#2273]
## **Goal**:
`As a documentation user, I see that the text of the documentation is in line with Mojaloop brand.

**Acceptance Criteria**:
- [ ] Documentation uses the right Mojaloop fonts and colors.

**Complexity**: Low - requires making changes to the theme configuration

**Uncertainty**: High - need to figure out how to use external fonts with the vuepress theme.

---

**Tasks**:
- [ ] Update documentation text to use Mojaloop font - @meekg33k 
- [ ] Update documentation text to use Mojaloop colors - @meekg33k 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
