### ISSUE TITLE
Mojaloop FIDO components implementation in Kubernetes cluster - AWS VPC public subnet setup

### ISSUE THREAD

**Issue by bukasaaime** [mojaloop/project#2278]
## **Goal**:
`As a` Security Consultant

`I want to` setup AWS VPC public subnet
  
`so that` to implement Mojaloop FIDO modules in Kubernetes cluster. The modules include:

    1. FIDO relying party client
    2. FIDO relying party server
    3. FIDO server
    4. FIDO DB (Mongo DB)
    5. CPM server 

**Acceptance Criteria**:
- [ ] AWS VPC - public subnet provisioned and configured.

**Complexity**: Low > AWS VPC defaults provided

**Uncertainty**: Low > AWS VPC defaults provided
---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by bukasaaime** [comment]
Default Mojaloop Test AWS VPC public subnet used.
