### ISSUE TITLE
Deploy the v2.0 docs preview in CI/CD

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2282]
## **Goal**:
`As a` community member

`I want to` see the new docs changes in the pipeline
  
`so that` I can review and contribute to them

**Acceptance Criteria**:
- [ ]  `mojaloop-docs-2.0` branch deployed somewhere (maybe s3) as a part of CI/CD

**Complexity**:  Medium - we have templates already, but need to do some config for hosting

**Uncertainty**:  We can't use github pages for this repo, since we are already using it

---

**Tasks**:
- [ ] add CI/CD steps for docs v2.0
- [ ] set up static hosting for docs v2.0
- [ ] write a script to deploy docs to static site
- [ ] DNS setup and documentation

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
