### ISSUE TITLE
Mojaloop FIDO components implementation in Kubernetes cluster - CPM Server Digital Verification service setup

### ISSUE THREAD

**Issue by bukasaaime** [mojaloop/project#2283]
## **Goal**:
`As a` Security Consultant

`I want to` develop, configure and install CPM server into the Mojaloop Kubernetes cluster for Cryptographic Digital Verification service.
  
`so that` I can implement Mojaloop FIDO modules in Kubernetes cluster. The modules include:

    1. FIDO relying party client
    2. FIDO relying party server
    3. FIDO server
    4. FIDO DB (Mongo DB)
    5. CPM server 

**Acceptance Criteria**:
- [ ] CPM server Digital Verification service developed, configured, installed, running in the cluster and available to other modules.

**Complexity**: High > JavaScript module development, Docker image, Docker hub repository and Kubernetes cluster knowledge.

**Uncertainty**: Medium > AWS KMS and AWS Kubernetes cluster available.

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by bukasaaime** [comment]
CPM Server - Development completed
