### ISSUE TITLE
Mojaloop FIDO components implementation in Kubernetes cluster - MongoDB configuration and installation

### ISSUE THREAD

**Issue by bukasaaime** [mojaloop/project#2284]
## **Goal**:
`As a` Security Consultant

`I want to` I can configure and install MongoDB database for FIDO data object persistence as FIDO data objects are currently kept in http sessions.
  
`so that` I can implement Mojaloop FIDO modules in Kubernetes cluster. The modules include:

    1. FIDO relying party client
    2. FIDO relying party server
    3. FIDO server
    4. FIDO DB (Mongo DB)
    5. CPM server 

**Acceptance Criteria**:
- [ ] FIDO relying party client developed, configured, installed, running and exposed to the public.

**Complexity**: High > JavaScript module development, Docker image, Docker hub repository and Kubernetes cluster knowledge.

**Uncertainty**: Medium > AWS Kubernetes cluster, VPC, external load balancer, Cloudfront CDN, https certificate available.

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by bukasaaime** [comment]
Mongo DB installed
