### ISSUE TITLE
Mojaloop FIDO components implementation in Kubernetes cluster - MongoDB ClusterIp service configuration and installation 

### ISSUE THREAD

**Issue by bukasaaime** [mojaloop/project#2285]
## **Goal**:
`As a` Security Consultant

`I want to` configure and install MongoDB ClusterIp service into the Mojaloop Kubernetes cluster.
  
`so that` I can avail MongoDB services to rest of the Kubernetes cluster. The modules include:

    1. FIDO relying party client
    2. FIDO relying party server
    3. FIDO server
    4. FIDO DB (Mongo DB)
    5. MongoDB Express
    6. CPM server 

**Acceptance Criteria**:
- [ ] FIDO MongoDB services configured, installed, running and exposed to the cluster.

**Complexity**: Medium > Kubernetes knowledge.

**Uncertainty**: Medium > AWS Kubernetes cluster available.

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by bukasaaime** [comment]
Mongo DB service configured
