### ISSUE TITLE
Mojaloop FIDO components implementation in Kubernetes cluster - MongoDB Express Load Balancer service configuration and installation

### ISSUE THREAD

**Issue by bukasaaime** [mojaloop/project#2286]
## **Goal**:
`As a` Security Consultant

`I want to` configure and install MongoDB Express Load Balancer service into the Mojaloop Kubernetes cluster.
  
`so that` External component such as a browser can view database data and observe the changes that will occur
with FIDO registration, authentication and transaction authorizations.

    1. FIDO relying party client
    2. FIDO relying party server
    3. FIDO server
    4. FIDO DB (Mongo DB)
    5. MongoDB Express
    6. CPM server 

**Acceptance Criteria**:
- [ ] FIDO MongoDB Express Load Balancer services configured, installed, running and exposed to a browser.

**Complexity**: Medium > Mongo DB, Mongo DB ClusterIp, Mongo DB Express configuration and installation.

**Uncertainty**: Medium > AWS Kubernetes cluster, Mongo DB, Mongo DB express available.

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by bukasaaime** [comment]
Mongo DB Express load balancer implemented.
