### ISSUE TITLE
Mojaloop FIDO components implementation in Kubernetes cluster - MongoDB Secrets configuration 

### ISSUE THREAD

**Issue by bukasaaime** [mojaloop/project#2287]
## **Goal**:
`As a` Security Consultant

`I want to` setup Mongo DB user id and password in a secure Secret configuration.
  
`so that` MongoDB root user and password are kept secure in a Kubernetes Cluster Secret.  This will in turn enforce security
for the following components :

    1. FIDO relying party client
    2. FIDO relying party server
    3. FIDO server
    4. FIDO DB (Mongo DB)
    5. Mongo DB Express
    6. CPM server 

**Acceptance Criteria**:
- [ ] Kubernetes cluster Secret component created and working with MongoDB.

**Complexity**: High > use of base 64 hashing
**Uncertainty**: Medium > configuring Mongo DB to work with Secrets.
---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by bukasaaime** [comment]
MongoDB Secrets configuration implemented
