### ISSUE TITLE
Mojaloop FIDO components implementation in Kubernetes cluster - ConfigMap configuration

### ISSUE THREAD

**Issue by bukasaaime** [mojaloop/project#2288]
## **Goal**:
`As a` Security Consultant

`I want to` setup Mongo DB url in a configMap configuration.
  
`so that` MongoDB url can remain accessible even if MongoDB pod has been restarted and that ip address has changed.  This will in turn ensure the correct functioning of all following components :

    1. FIDO relying party client
    2. FIDO relying party server
    3. FIDO server
    4. FIDO DB (Mongo DB)
    5. Mongo DB Express
    6. CPM server 

**Acceptance Criteria**:
- [ ] Kubernetes cluster configMap component created and working with MongoDB.

**Complexity**: Medium > ip mapping to url
**Uncertainty**: Medium > configuring Mongo DB to work with ConfigMap accordingly.

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by bukasaaime** [comment]
Mongo DB ConfigMap configuration implemented.
