### ISSUE TITLE
Mojaloop FIDO components implementation in Kubernetes cluster - configure MongoDB volumes

### ISSUE THREAD

**Issue by bukasaaime** [mojaloop/project#2289]
## **Goal**:
`As a` Security Consultant 

`I want to` setup Mongo DB volumes in AWS.
  
`so that` MongoDB data can be persisted even if MongoDB pod is restarted. This to ensure correct functioning 
for the following components :

    1. FIDO relying party client
    2. FIDO relying party server
    3. FIDO server
    4. FIDO DB (Mongo DB)
    5. Mongo DB Express
    6. CPM server 

**Acceptance Criteria**:
- [ ] MongoDB volumes persisting data even when pod is restarted.

**Complexity**: High > Mongo DB volume configured and working. 
**Uncertainty**: Medium > configuring Mongo DB to work with volumes.

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by bukasaaime** [comment]
MongoDB volumes configured completed.
