### ISSUE TITLE
Mojaloop FIDO components implementation in Kubernetes cluster - FIDO Server MongoDB CRUD operations - CREATE

### ISSUE THREAD

**Issue by bukasaaime** [mojaloop/project#2290]
## **Goal**:
`As a` Security Consultant 

`I want to` develop and expose a service linked to Mongo DB CREATE operation.
  
`so that` Fido user (enrolment) data object can be persisted in MongoDB.  The FIDO data object (JSON) include the following :

    1. object id
    2. certificate generated by authenticator
    3. user name
    4. flag indicating whether user has been registered or not.
    5. array list of authenticators.

Note: data currently persisted in http request session object and response object.

This to ensure correct functioning for the following components :

    1. FIDO relying party client
    2. FIDO relying party server
    3. FIDO server
    4. FIDO DB (Mongo DB)
    5. Mongo DB Express
    6. CPM server 

**Acceptance Criteria**:
- [ ] FIDO user record created (enrolment).

**Complexity**: High > Development with JS Express libraries to call MongoDB libraries. 
**Uncertainty**: Medium > JS Express integration to JS MongoDB libraries.
---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
