### ISSUE TITLE
Mojaloop FIDO components implementation in Kubernetes cluster - Configure AWS target groups (Relying Party Client)

### ISSUE THREAD

**Issue by bukasaaime** [mojaloop/project#2293]
## **Goal**:
`As a` Security Consultant 

`I want to` create AWS Target groups
  
`so that` they can be associated to AWS EC2 ports where FIDO components are running. This will also be used in the 
Security group definitions.  

This to ensure correct functioning for the following components :

    1. FIDO relying party client
    2. FIDO relying party server
    3. FIDO server
    4. FIDO DB (Mongo DB)
    5. Mongo DB Express
    6. CPM server 

**Acceptance Criteria**:
- [ ] Target groups created, ports and listeners in healthy state.

**Complexity**: Medium > ports configuration and use of defaults. 
**Uncertainty**: Low > Kubernetes creates and configure Target group during Load Balancer creation.

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by bukasaaime** [comment]
AWS target groups created.
