### ISSUE TITLE
Mojaloop FIDO components implementation in Kubernetes cluster - Configure AWS Application Load Balancer (Mongo Express) 

### ISSUE THREAD

**Issue by bukasaaime** [mojaloop/project#2299]
## **Goal**:
`As a` Security Consultant 

`I want to` create AWS Application Load Balancer
  
`so that` the Mongo Express can be exposed to the public.  

This will enable testing of the following components :

    1. FIDO relying party client
    2. FIDO relying party server
    3. FIDO server
    4. FIDO DB (Mongo DB)
    5. Mongo DB Express
    6. CPM server 

**Acceptance Criteria**:
- [ ] Relying Party exposed and function.

**Complexity**: Medium > All component working as per design. 
**Uncertainty**: Low >All component working as per design.

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by bukasaaime** [comment]
Application load balancer configured.
