### ISSUE TITLE
Assess and add adequate logging in central-settlement service

### ISSUE THREAD

**Issue by shashi165** [mojaloop/project#2301]
## **Goal**:
`As a` hub operator

`I want to`  make sure that every failure in central-settlement is logged in default log level
  
`so that` I can check the logs to debug the failures

**Acceptance Criteria**:

**Complexity**:  Low > Easy to assess and add

**Uncertainty**: Low

---

**Tasks**:
- [x] Incorporate `event-sdk` into requests

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-settlement/pull/358

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
