### ISSUE TITLE
[ML BOF PI-15] Template documentation outlining BizOps hub operator requirements

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2303]
**Goal**: Template documentation that outlines the BizOps hub operator requirements submitted to the Product Council.

- [x] Technical Operations (L1, L2, L3, Support)
  - [x] Incident management
  - [x] Problem management
  - [x] Change management
  - [x] Release management
  - [x] Defect triage
- [x] Business processes (prioritized)
  - [x] Settlement Management Guide
    - [x] Intro to basic concepts of settlement management.
    - [x] Step-by-step guidance to Finance Portal functionality that supports settlement management.
  - [x] Onboarding Guide for the Hub Operator
    - [x] Onboarding checklist for DFSPs
    - [x] Connecting to Mojaloop overview
- [x] High level roles vs  business processes generating candidate APIs (for PI-15)
  - [x] Initial RBAC design that covers Participant onboarding and liquidity management and Settlement.

**Comment by elnyry-sam-k** [comment]
completed with https://github.com/mojaloop/mojaloop-business-docs/pull/11 !
