### ISSUE TITLE
Forensic Logging - use CPM services to build an immutable database for forensic data  

### ISSUE THREAD

**Issue by bukasaaime** [mojaloop/project#2306]
## **Goal**:
`As a` Security Architect

`I want to use CPM services : 

1. Digital Signature generation
2. Digital Signature verification
3. Hashing
4. Encryption
5. Decryption
  
`so that` an immutable database can be created for forensic logging. 

**Acceptance Criteria**:
- [ ] Immutable database

**Complexity**: High > CPM to hide complexity of crypto process.

**Uncertainty**: Medium > time constraint

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @bukasaaime 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
![Slide1](https://user-images.githubusercontent.com/58056329/122747439-59929d80-d28b-11eb-88fc-b61d627f4c8b.JPG)
