### ISSUE TITLE
TTK - Handle socket hangup issue during testcase execution

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2312]
**Summary**:
Handle socket hangup issue during testcase execution

**Severity**:
High

**Priority**:
Critical

**Expected Behavior**
TTK tests should be continue after logging the error

**Tasks**
- [x] Try to produce the error with a sample program
- [x] Fix the test run by catching the error socket hangup

**Pull Requests**
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/171
