### ISSUE TITLE
Add CGS default settlement test cases in testing toolkit test collection

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#2314]
## **Goal**:
`As a` OSS contributor

`I want to` add support for CGS Default settlement model into TTK test cases
  
`so that` Default settlement can be tested and demoed

**Acceptance Criteria**:
- [x] Central-Settlements TTK CGS tests are updated to:
  - [x]  setup the hub with a new currency and CGS settlement model for it
  - [x] run TTK CGS tests successfully
  - [x] run default currency and deferred settlement model test successfully

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Test locally default CGS model
- [x] Onboarding for CGS takes a long time ~6m20s -- investigate
- [x] Add default CGS settlement model in provisioning
- [x] Add secondary currency accounts
- [x] Create test cases for currency specific and default and settlement models in CGS
- [x] Move tests done in scripts (post requests) into separate requests and assertions (instead of doing it in scripts)
- [x] Refactor folder structure to merge DMLNS (default) and CGS collections
- [x] Add envt variables to the helm charts
- [x] Validate on moja2 / moja1 envts

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/54
- [x] https://github.com/mojaloop/helm/pull/458
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/57

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
