### ISSUE TITLE
Remove or disable kafka config from 3p-api-adapter

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2315]
## **Goal**:
`As a` developer

`I want to` remove or disable kafka from the 3p-api-adapter 
  
`so that` technical debt is reduced

**Acceptance Criteria**:
- [ ] 3p-api-adapter no longer requires or connects to kafka

**Complexity**: Low

**Uncertainty**: Low

---

We no longer need the 3p-api-adapter to listen to any kafka events, so we can go ahead and remove all references to kafka from our codebase.

**Tasks**:
- [ ] Remove redundant Kafka config from the 3p-api-adapter

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Covered in #2386
