### ISSUE TITLE
Event-Stream-Process to support recent version of ElasticSearch and APM that support Authentication and TLS

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2319]
## **Goal**:
`As a` Hub Operator

`I want to` update the Event-Stream-Process (ESP) to support the latest security features made available on the [ECK](https://www.elastic.co/guide/en/cloud-on-k8s/current/index.html) Stack
  
`so that` ESP is able to send Event stream messages to the ECK Stack.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] ESP supports basic authentication for APM on the ECK stack
- [ ] ESP supports basic authentication for ElasticSearch on the ECK stack

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
