### ISSUE TITLE
Mojaloop Metric scrapping support from Prometheus deployed via an Operator

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2321]
## **Goal**:
`As a` Hub Operator

`I want to` have Helm deployments support the Promfana Operator Deployments
  
`so that` Mojaloop metrics can be ingested into the modern Promfana Stack

**Acceptance Criteria**:
- [ ] Mojaloop services metric end-points are scraped by Prometheus that is deployed using the Prometheus Operator (Which does not scrap based on Annotations, but rather labels)
- [ ] Add support to each Mojaloop helm chart to support arbitrary labels that can be added to each helm chart's deployment

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
