### ISSUE TITLE
Expand Event SDK integration in central-settlement to capture complex db operations

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#2326]
## **Goal**:
`As a` OSS developer

`I want to` add child spans in central-settlements for the db (facade) operations
  
`so that` complex db operations are traced and profiled

**Acceptance Criteria**:
- [ ] child spans for all complex db operations are created and reported

**Complexity**: <Low> 

**Uncertainty**: <Low>

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
