### ISSUE TITLE
Add script validation for central-settlement rules handler

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#2327]
## **Goal**:
`As a` OSS contributor

`I want to` create rules script validators that could capture and log any issues in the rules scripts failures.
  
`so that` faulty scripts don't stop the settlement process.

See issue #2149 for more details.

**Acceptance Criteria**:
- [ ] If script is faulty, the error is captured and logged and settlement process is not interrupted.

**Complexity**: <Medium>

**Uncertainty**: <Low>

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- #2149 

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
