### ISSUE TITLE
TTK - Runtime information for each request

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2334]
## **Goal**:
`As a` individual implementer

`I want to` see the runtime information for each request
  
`so that` I can know if there are any problems with a specific request / component

**Acceptance Criteria**:
- [ ] Runtime information for each request can be seen in
  - [ ] Request editor
  - [ ] Under every request in reports

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] Calculate and insert the runtime details in each request by backend modification
- [ ] Show the information in the UI
- [ ] Show the information in Reports
- [ ] Show the information in CLI

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: NA
- QA/Review: @mdebarros
