### ISSUE TITLE
TTK - Checkbox to disable some requests in test case editor easily

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2335]
## **Goal**:
`As a` individual implementer

`I want to` disable some requests in the test case editor easily
  
`so that` I can execute the request I want from test case editor

**Acceptance Criteria**:
- [x] There should be following options to disable the requests in test case editor
  - [x] A checkbox on top of each request (Not inside the tabs)
  - [x] An option to Select All, Unselect All

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [x] Find a way to combine existing functionality to disable the requests using scripting
- [x] Add a new parameter in the JSON format and implement backend logic
- [x] Add the UI options

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/204
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/127

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @georgi-logodazhki 
- QA/Review: @vijayg10

**Comment by elnyry-sam-k** [comment]
Thanks @vijayg10
