### ISSUE TITLE
TTK - Provision new APIs

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2336]
## **Goal**:
`As a` individual implementer

`I want to` have newer APIs provisioned in the TTK
  
`so that` I can use them straight after deployment

**Acceptance Criteria**:
- [x] The following APIs are available in TTK by default
  - [x] New settlements API (v2.0)
  - [x] SDK scheme adapter outbound API v1.0
  - [x] Central Admin API v1.0

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Provision new settlements API
- [x] Provision sdk scheme adapter outbound API
- [x] Check the remaining APIs are updated

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/107
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/173

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
