### ISSUE TITLE
TTK - The callback timeout events should be logged to console

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2337]
## **Goal**:
`As a` individual implementer

`I want to` see the logs related to callback timeouts in the console
  
`so that` I can debug my setup incase of test failures

**Acceptance Criteria**:
- [ ] Callback timeout events should be logged to console

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] Add the console logs incase of callback timeouts and other test failures

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
