### ISSUE TITLE
TTK - Improve test case viewer

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2339]
## **Goal**:
`As a` individual implementer

`I want to` have better visibility  of my test cases
  
`so that` I can organise and run my test cases more efficiently

**Acceptance Criteria**:
- [x] Test Cases should display the "file" that they belong to - probably a metadata field
- [x] Test case name should be displayed in test case editor
- [x] Renaming of test cases should be easy (An edit icon next to test case name)
- [x] Test case viewer should contain labels

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Improve the UI to fulfil acceptance criteria

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit-shared-lib/pull/9
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/124

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
