### ISSUE TITLE
ML TTK: Draft presentation for MTP TTK-101 for an initial review -2

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2341]
## **Goal**:
`As a` MTP team member

`I want to` review a draft presentation for the MTP TTK-101 focussing on the final 4 chapters (TTK usage scenarios: in onboarding FSPs, accelerating development, advanced usage)
  
`so that` we can consider it for the MTP-101 and proceed to next stages of developing the course and discuss standards for the. rest of the section

**Acceptance Criteria**:
- [ ] Slides added for the last four chapters for an initial review
- [ ] Feedback for the first three sections is incorporated to get it ready for MTP team

**Complexity**: High

**Uncertainty**: Medium

---

**Tasks**:
- [ ] Prepare an initial deck for the last 4 sections of the MTP TTK-101
- [ ] Add speaker notes for the last 4 chapters
- [ ] Add narration text for each slide
- [ ] Internal review with TTK team
- [ ] Submit all 7 parts for an initial review with MTP team
- [ ] Feedback for the first 3 chapters (by MTP team) in incorporated

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Presentation is reviewed and feedback provided to continue drafting rest of the sections

## **Pull Requests**:
- N/A

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 @elnyry-sam-k 
- QA/Review: MTP team

**Comment by elnyry-sam-k** [comment]
iterating over this with the MTP team..
