### ISSUE TITLE
Helm v13.0.1 release

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2343]
## **Goal**:
`As a` ML OSS Code base maintainer

`I want to` validate and make a patch release to v13.0.0 that is successfully validated by the Golden path tests
  
`so that` Community members can take and use a version of Mojaloop Switch services bundle that is tested and contains the latest features and enhancements such as CGS, etc and bug fixes added in PI-14/PI-15.

**Acceptance Criteria**:
- [x] Helm RC v13.0.1 is validated on Moja2 to achieve 100% result with TTK GoldenPath collection
- [x] QA (Golden path) on deployments done on AWS Moja2 environment is done
- [x] Bugs are logged based on observations, failures
- [x] Bugs logged are fixed if critical to make subsequent releases in individual services (or Helm)
- [x] All the changes needed for supporting v13.0.1 of Helm are done
- [x] Helm v13.0.1 is released and release notes published
- [x] Test cases v13.0.1 is published (TTK)
- [x] TTK tests run successfully as Post-Hook jobs and Tests

**Complexity**: Medium - Involves all core and supporting services

**Uncertainty**: Medium

---

**Tasks**:
- [x] Make releases on all core services to have latest images / versions [@elnyry-sam-k , @mdebarros , @vgenev ]
  - [x] Need latest ALS release after vulnerabilities (dependabot alerts are addressed)
- [x] Identify changes needed for helm (config / default.json)
- [x] Initial PR with changes for v13.0.1
  - [x] Initial PR review
  - [x] Deploy, validate, fix issues, redeploy
  - [x] With stable deployment test Golden path
  - [x] Central-Settlements updates:
    -  [x] Add sdk-sidecar 
    -  [x] Add event/tracing config
- [x] Identify issues with QA Scripts if any - fix them and retest
- [x] Identify Bugs, log them #2368 
- [x] Fix bugs logged if critical
- [x] Deploy, validate on AWS Moja2
- [x] Validate with TTK Mojaloop Simulator collection
- [x] Validate upgrade scenario (to v13.0.1) from v13.0.0
- [x] Release notes for helm v13.0.1 drafted
- [x] Helm v13.0.1 released
- [x] Review deployment guide documentation to ensure its up-to-date
- [x] Deployment of released Helm v13.0.1 on **Moja2**
  - [x] Helm v13.0.1 is deployed on **Moja2** successfully
  - [x] Validation using Golden path regression tests etc on Moja2
    - [x] Mojaloop Simulator postman collection
    - [x] TTK Post-hook install job and Tests
  - [x] Validation using CGS Golden path regression tests etc on Moja2
    - [x] Mojaloop Simulator TTK collection
- [x] Deployment of released Helm v13.0.1 on **Moja1**
  - [x] Helm v13.0.1 is deployed on **Moja1** successfully
  - [x] Validation using Golden path regression tests etc on Moja2
    - [x] Mojaloop Simulator TTK collection
    - [x] TTK Post-hook install and Tests
  - [x] Validation using CGS Golden path regression tests etc on Moja2
    - [x] Mojaloop Simulator TTK collection
    - [x] TTK Post-hook install and Tests
- [x] TTK test cases v13.0.1 version released including additional Settlement Test-cases

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Postman (where applicable) Tests pass
- [x] TTK Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/443
- [x] https://github.com/mojaloop/central-settlement/pull/363
- [x] https://github.com/mojaloop/central-settlement/pull/364

## **Issues**:
- [x] https://github.com/mojaloop/project/issues/2325
- [x] https://github.com/mojaloop/project/issues/2342
- [x] https://github.com/mojaloop/project/issues/2310
- [x] https://github.com/mojaloop/project/issues/2329
- [x] https://github.com/mojaloop/project/issues/2330
- [x] https://github.com/mojaloop/project/issues/2331
- [x] https://github.com/mojaloop/central-settlement/pull/363
- [x] https://github.com/mojaloop/project/issues/2368

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @mdebarros 
- QA/Review: @mdebarros @elnyry-sam-k @vijayg10 @vgenev

**Comment by elnyry-sam-k** [comment]
will pickup after community event prep

**Comment by elnyry-sam-k** [comment]
Great work @mdebarros! Thanks for your support @vijayg10 👏
