### ISSUE TITLE
Testing Toolkit Test-cases are references the wrong interface spec versions

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2345]
**Summary**:
Testing Toolkit Test-cases are reference the wrong interface spec versions.

Central-settlements API v2 is not being referenced.

Central-Ledger Admin API v1 is not being referenced.

**Severity**:
Low

**Priority**:
Medium

**Expected Behavior**

The following interface specs are added to the TTK, and the associated Testing Toolkit Test Cases are updated to reflect this change for Mojaloop Helm release v13.0.1:
- Central-settlements API v2
- Central-Ledger Admin API v1

Old versions should be kept to maintain compatibility with older versions, and include any additional "description" information to reflect this.

**Steps to Reproduce**
  1. Deploy Mojaloop v13.0.0

**Specifications**
  - Component (if known): Testing Toolkit Backend + Test-cases
  - Version: v12.x
  - Platform: Helm
  - Subsystem: n/a
  - Type of testing: Manual
  - Bug found/raised by: @vijayg10 

**Tasks**
- [x] Update all the versions in test cases
- [x] Test the new release with updated helm chart
  - [x] Deferred settlement Collections
  - [x] CGS Collections

**Pull Requests**:

- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/44

**Comment by vijayg10** [comment]
Tested Diferred and CGS collections
