### ISSUE TITLE
Migrate QA Report announcements to the #announcements channel

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2346]
## **Goal**:
`As a` Mojaloop Community Contributor

`I want to` see daily QA reports moved from #qa-testing-webhooks to the #announcements channel
  
`so that` the wider community have access to QA reports

**Acceptance Criteria**:
- [ ] moja1.test.mojaloop QA reports are published daily to the #announcements channel
- [x] moja2.test.mojaloop QA reports are published daily to the #announcements channel

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Updated deploy-configs for both moja1 and moja2 to publish announcements to #announcements channel on slack.

This will be fully tested with the v13.0.2 release.

**Comment by mdebarros** [comment]
Moja2 --> https://mojaloop.slack.com/archives/CG3MAJZ5J/p1629225440053400

**Comment by mdebarros** [comment]
Moja1 --> https://mojaloop.slack.com/archives/CG3MAJZ5J/p1629449183054800
