### ISSUE TITLE
PI-15 Community event presentations, demos - core + ttk team

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2347]
## **Goal**:
As a contributor team for the ML OSS
I want to prepare presentation and content for the PI-15 Community event
so that it can be used to demonstrate Mojaloop capabilities to the Community and for discussions

**Tasks**:
- [x] Create and share slide-deck template
- [x] Identify various sections, sub-topics and their owners
- [x] Prep for Demos, updates
  - [x] Settlement DMLNS with Testing toolkit demos [@vijayg10 , @vgenev ] -- **issue** #2062 
  - [x] Settlements CGS with Testing toolkit demos [@vijayg10 , @vgenev ]
  - [x] Default settlement changes - can be update/demo [@vgenev ]
  - [x] Demo/Update: Helm v13.0.0 overview, running helm test / tests post-install, on-schedule (TTK)
- [x] Update presentation slide deck
  - [x] Overview and introduction section [@elnyry-sam-k ]
  - [x] Maintenance updates
    - [x] Helm changes
    - [x] Bug Fixes
  - [x] Any separate Testing toolkit updates [@vijayg10 . @elnyry-sam-k]
  - [x] Roadmap candidate items for PI-15
- [x] Review presentation and items to discuss
- [x] Changes required in TTK mobile simulator page for settlements demo [@vijayg10 ]
  - [x] Add Settlements Model selection in Hub Console
  - [x] Add Currency selection in payer quotes screen
  - [x] Change the expiration for quote to something realistic like a day or two
  - [x] Calculate the transfer expiration based on current time and configurable offset
  - [x] Change fee and commission realistically and fix receive amount in rule
  - [x] Add fee and commission to transfer amount and make sure that the payee app gets proper amount
  - ~~Add Delay at payee app for transfer response callback (Need to change callback rule)~~
  - **_PRs:_**
    - [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/110
    - [x] https://github.com/mojaloop/ml-testing-toolkit/pull/175
    - [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/111
    - [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/46
    - [x] https://github.com/mojaloop/ml-testing-toolkit/pull/176
    - [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/112
    - [x] https://github.com/mojaloop/ml-testing-toolkit/pull/179

**Acceptance Criteria**:
- [x] A slide-deck is prepared for use during the PI-15 Community Event to inform / share progress regarding objectives and provide details as necessary. 
- [x] The slide deck covers all significant items worked on so far in PI-14 and also bring forth any significant design decisions.
- [x] Demo items are finalized and prepared

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @mdebarros @vijayg10 @vgenev @elnyry-sam-k 
- QA/Review: OSS Core team
