### ISSUE TITLE
ML TTK: Test cases definition report with grouping

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2348]
## **Goal**:
`As a` Release Manager

`I want to` be able to export test case details such as names, descriptions and other useful information from test cases with grouping
  
`so that` I can generate a (readable) report with test case details that can help understand coverage and scenarios covered, etc.

**Acceptance Criteria**:
- [x] Test case definitions are exported as readable format with grouping.

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [x] Group test case definitions

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/196

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
