### ISSUE TITLE
Refactor ML-API-Adapter to use Contract First Driven Approach

### ISSUE THREAD

**Issue by ksatya77** [mojaloop/project#235]
**Goal**:
As a developer I would like to refactor ML-API-Adapter code base to be Contract First Driven

**Tasks**:
- [ ]  Use hapi-openapi module. https://github.com/krakenjs/hapi-openapi/blob/master/README.md

**Acceptance Criteria**:
- [ ] Routes are automatically generated from OpenAPI specification
- [ ] Json schema validation is performed against the Json schema and not hardcoded in the nodejs application code.

**Dependencies**:
- [ ] #164
