### ISSUE TITLE
Contributors Documentation to include instructions on how to manage Package-lock changes and conflicts

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2351]
## **Goal**:
`As a` Deveoper

`I want to` documentation on how to manage the package-lock.json
  
`so that` I know how to handle changes and merge conflicts when contributing

**Acceptance Criteria**:
- [ ] Contributors guide includes developer-focused instructions on how to manage the package-lock.json file
    - [ ] How to handle merge conflicts
    - [ ] How to regenerate package-lock.json (i.e. ensure that audit resolve is cleared)

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @mdebarros 
- QA/Review: Design Authority
