### ISSUE TITLE
Mojaloop Helm support for Kubernetes networking.k8s.io/v1 (Ingress) Pts 5

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2352]
## **Goal**:
`As a` Mojaloop Deployer

`I want to` update API versions in Helm charts
  
`so that` I can deploy a Mojaloop Release to Kubernetes v1.22 onwards

**Acceptance Criteria**:
- [ ] Kubernetes API ingress definitions are migrated from `networking.k8s.io/v1beta1` to `networking.k8s.io/v1`, ref: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [x] update all values files to reflect the above changes
- [x] test and document deployment steps 

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/508

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by tdaly61** [comment]
hey @elnyry-sam-k , @mdebarros @lewisdaly : I assigned this issue to myself because as part of the mini-loop update I want to be able to use k3s and possibly other kubernetes engines and v1.20 is starting to be very problematic indeed and enabling other k8s engines means solving this issue.  Now I know it is part of the v14 activities BUT I think I can solve this one programmatically with a "reasonably straight-forward python program to make the mods necessary for the ingress and ingress class (plus the minor changes in the ingress synytax).  So I plan to assess this/test this a bit to see just how hard it might be to make 3.x work across releases. I will report back.

**Comment by tdaly61** [comment]
Hey @elnyry-sam-k , @mdebarros  I said I was going to open a new issue but then I discovered we already have this open issue so I am updating it to reflect the decision from the DA on separating out the services from the rest of the charts as this  is the solution to the this issue.   I am now working on this admittedly a couple of weeks behind what I hoped , but it should not take too long for me to get you something to test.

**Comment by mdebarros** [comment]
Separated this story into: https://github.com/mojaloop/project/issues/2887

**Comment by tdaly61** [comment]
@mdebarros , @elnyry-sam-k  the API changes are done and charts are deploying and tests passing with k8s 1.21.  I will check V1.24 shortly but I anticipate issues with the DB due to that percona chart but obviously I can work around that.  I have some cosmetic fixes to do in the values files which I would prefer NOT to do by hand.  Anyhow nearly there with this issues 
![Screen Shot 2022-09-29 at 11 17 52 am](https://user-images.githubusercontent.com/31208690/192920818-c6421eeb-1830-411d-9f4d-ebde00f83208.png)

**Comment by mdebarros** [comment]
PR (https://github.com/mojaloop/helm/pull/508) has been merged, and we now have a development release \:D/

```
❯ helm search repo mojaloop/mojaloop --devel
NAME                       	CHART VERSION       	APP VERSION                                       	DESCRIPTION
mojaloop/mojaloop          	14.1.0-14362.471407b	ml-api-adapter: v14.0.0; central-ledger: v15.1....	Mojaloop Helm chart for Kubernetes
```

**Comment by mdebarros** [comment]
```
--------------------FINAL REPORT--------------------

Test Suite:GP Tests
Environment:Development
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 2634                          │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 2634                          │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 0                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 598                           │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 130                           │
├───────────────────┼───────────────────────────────┤
│ Passed percentage │ 100.00%                       │
├───────────────────┼───────────────────────────────┤
│ Started time      │ Thu, 20 Oct 2022 08:25:03 GMT │
├───────────────────┼───────────────────────────────┤
│ Completed time    │ Thu, 20 Oct 2022 08:28:24 GMT │
├───────────────────┼───────────────────────────────┤
│ Runtime duration  │ 200089 ms                     │
└───────────────────┴───────────────────────────────┘
TTK-Assertion-Report-multi-2022-10-20T08:28:24.054Z.html was generated
```

```
--------------------FINAL REPORT--------------------

Test Suite:Bulk Tests
Environment:Development
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 183                           │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 183                           │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 0                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 17                            │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 4                             │
├───────────────────┼───────────────────────────────┤
│ Passed percentage │ 100.00%                       │
├───────────────────┼───────────────────────────────┤
│ Started time      │ Thu, 20 Oct 2022 08:33:27 GMT │
├───────────────────┼───────────────────────────────┤
│ Completed time    │ Thu, 20 Oct 2022 08:33:51 GMT │
├───────────────────┼───────────────────────────────┤
│ Runtime duration  │ 24341 ms                      │
└───────────────────┴───────────────────────────────┘
TTK-Assertion-Report-multi-2022-10-20T08:33:51.710Z.html was generated
```

```
--------------------FINAL REPORT--------------------

Test Suite:Thirdparty Tests
Environment:Development
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 21                            │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 21                            │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 0                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 20                            │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 8                             │
├───────────────────┼───────────────────────────────┤
│ Passed percentage │ 100.00%                       │
├───────────────────┼───────────────────────────────┤
│ Started time      │ Thu, 20 Oct 2022 08:30:14 GMT │
├───────────────────┼───────────────────────────────┤
│ Completed time    │ Thu, 20 Oct 2022 08:30:23 GMT │
├───────────────────┼───────────────────────────────┤
│ Runtime duration  │ 8901 ms                       │
└───────────────────┴───────────────────────────────┘
TTK-Assertion-Report-multi-2022-10-20T08:30:23.243Z.html was generated
```
