### ISSUE TITLE
TTK: Login is not working in the hosted mode

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2359]
**Summary**:
When TTK is deployed in HOSTED mode, the following functionalities are not working
  - [x] We can't be able to login in TTK UI even after creating a user in keycloak with proper attributes.
  - [x] We can't be able to login in Connection Manager UI

**Severity**:
High

**Priority**:
Medium

**Expected Behavior**
We should be able to login to TTK UI and connection manager UI

**Steps to Reproduce**
  1. Deploy TTK helm using hosted mode
  2. Create a user in keycloak with proper attributes (Follow documentation in TTK repo)
  3. Try to login in TTK UI

**Tasks**
  - [x] Fix login in TTK UI
  - [x] Fix the error `body.dfspId.replace is not a function` when TTK backend service is trying to create a DFSP
  - [x] Test everything is working
  - [x] Update the helm values file with proper descriptions (With commented lines for hosted mode)

**Pull Requests**
 - [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/114
 - [x] https://github.com/mojaloop/ml-testing-toolkit/pull/180
 - [x] https://github.com/mojaloop/helm/pull/444

**Specifications**
  - Component (if known): TTK UI
  - Version: v13.2.1
  - Bug found/raised by: @vijayg10
