### ISSUE TITLE
Setup sidebar for the API documentation

### ISSUE THREAD

**Issue by meekg33k** [mojaloop/project#2360]
## **Goal**:
As a documentation user who visits the `API Specification` documentation: `<baseUrl>/apis`, I want to see well-structured links to other parts of the `API Specification` documentation on the sidebar so that I can easily navigate to other parts by clicking on any of the links. 

## **Description**:
The sidebar should be have the following groups, with each group containing links to the relevant documentation:
1. **API Overview**
   - Mojaloop API
   -- Participants
2. **API Specification**

**Acceptance Criteria**:
- [ ] The groups should be visible on the sidebar.
- [ ] The sub-pages within each group should be visible on the sidebar.

**Complexity**: Low - Vuepress has an in-built configuration to support this.

**Uncertainty**: Low

---

**Tasks**:
- [ ] Add sidebar config for the `/apis/` path - @meekg33k 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
