### ISSUE TITLE
Dev Portal - Publish sync pisp API with TTK

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2365]
## **Goal**:
`As an` APIX user

`I want to` be able to test out the sync pisp APIs using the developer portal (http://sandbox.mojaloop.io/apis/sync-3ppi.html)
  
`so that` I can build out my solution

**Acceptance Criteria**:
- [x] Deployed 3ppi api on developer portal with sensible happy-path examples
- [ ] Updated outbound interface in 3p-scheme-adapter repo 
---

**Tasks**:
- [x] finish getting examples working with ttk in docker-contract
- [x] contract tests in `mojaloop/pisp` to prove that the TTK config works
- [x] add POST example values into file to make the "try it out" examples better
- [x] fix dev portal POST/PATCH requests sending OPTIONS
- [x] Update the original API defs as defined in 3p-scheme-adapter outbound interface
- [x] Re-render the sync api, and copy into developer portal site

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/109
- [ ] https://github.com/mojaloop/pisp-project/pull/148
- [ ] https://github.com/mojaloop/thirdparty-scheme-adapter/pull/110
- [x] https://github.com/mojaloop/contrib-dev-portal/pull/8

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
