### ISSUE TITLE
Dev Portal - Document G2P Example Use Case

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2366]
## **Goal**:
`As an` APIX user looking at our developer portal

`I want to` be able to understand the G2P use case for PISP
  
`so that` I can get ideas for my CDBC use case

**Acceptance Criteria**:
- [ ] Deployed G2P use case guide with 1-2 pretty diagrams/pictures showing the components working together

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
