### ISSUE TITLE
Implement Central Services API for Health-check service through a Swagger Design First Approach

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#237]
**Goal**:
As a developer
I would like to _Implement Central Services API for Health-check service through a Swagger Design First Approach_
so that API, Validations are generated from the Swagger

**Tasks**:
- [ ] Implement Central Services API for Health-check service through a Swagger Design First Approach to include checks for back-end connectivity (DB, Kafka, etc)

**Acceptance Criteria**:
- [ ] Swagger defining interface for Central Services
- [ ] Generate routes/handlers for API Rest end-points using https://github.com/krakenjs/hapi-openapi
- [ ] Create new stories for implenting each of the routes/handlers generated by hapi-openapi
- [ ] Health end-points to properly report status on Service based on its operationability and connectivity to back-end components

**Dependencies**:
- [ ] #264

**Accountability**:
- Owner
- Review **Design Authority**

**Comment by ksatya77** [comment]
Should it be 2 separate calls get:/notifiactions and get:/participants or one generic endpoint for /participants resource that can be used for fsp on-boarding including registration of callbacks ( the way @NicoDuvenage designed with ContactType ENUM). So a get:/participant?contactType=Enum.CALLBACK to get the notification details?

**Comment by elnyry** [comment]
Repurposed this for the first item Miguel listed - Implement Central Services API for Health-check service through a Swagger Design First Approach. Created separate story for Design and the other 3 items listed.

**Comment by elnyry** [comment]
Covered as part of #796
