### ISSUE TITLE
ML TTK: PI-15 enhancements to TTK and TTK-101

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2370]
PI-15 TTK features, enhancements and Mojaloop Training Program [MTP] Course for Testing Toolkit [TTK]

- [x] TTK MTP-101
  - [x] First 3 sections review with MTP team and iterations over feedback
  - [x] All seven sections approved with MTP team
- [x] Initial version of MTP TTK-101 ready
- [x] TTK features
  - [x] Improve test case definition report
  - [x] Hosted mode enhancements
  - [x] Bug fixes

Follow-up to #2154

**Comment by elnyry-sam-k** [comment]
succeeded by #2583
