### ISSUE TITLE
TTK - Make TLS optional for hosted mode and implement token authorisation

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2376]
## **Goal**:
`As a` scheme

`I want to` use TTK in hosted mode without TLS and token authorisation
  
`so that` I can provide access to our DFSPs to play around with the APIs provided by the scheme (such as FSPIOP API)

**Acceptance Criteria**:
- [ ] TLS can be disabled in TTK hosted mode
- [ ] DFSPs can be authorised by providing Bearer token in headers

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Provide an option to disable TLS in hosted mode
- [x] TLS related services services should not be run if its disabled
  - [x] Connection manager api and UI services
  - [x] MCM client adapter thread for automation in TTK
- [x] Prepare docker-compose file to run TTK in hosted mode
- [x] DFSP should be identified by using token in headers (Not FSPIOP-Source as previously)
- [x] Corresponding callback endpoint should be picked up based on the DFSP authenticated
- [x] Test using scheme-adapter as DFSP
  - [x] Authentication with static token
  - [x] Automatic token fetching using openID configuration to keycloak
- [x] Push messages should be sent to corresponding DFSP
- [x] Share existing spec_files folder with different version of sys_config and user_config somehow
- [x] Add unit tests
- [x] Add documentation about the hosted mode with docker-compose

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/184
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/116

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
