### ISSUE TITLE
TTK hosted mode should work with payement manager deployments

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2377]
## **Goal**:
`As a` DFSP implementer

`I want to` deploy TTK in hosted mode which works with payment manager
  
`so that` I can test my implementation with TTK

**Acceptance Criteria**:
- [ ] TTK hosted mode works with payment manager deployments

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [ ] Deploy TTK in hosted mode with latest connection manager
- [ ] Deploy payment manager
- [ ] Establish connection between TTK and PM
- [ ] Document the steps

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
https://drive.google.com/file/d/1ES-uNdi47UhXFLEgC8JzHTnUtsyHXPzA/view?usp=sharing

**Comment by vijayg10** [comment]
Moving this to blocked for the next version of payment manager. Please let us know about it @kirgene .

**Comment by elnyry-sam-k** [comment]
Updated version of PM released, so this can be continued
