### ISSUE TITLE
Determine an approach to spin-up Kafka to be used in integration tests

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#238]
**Goal**:
As a developer I would like to determine an approach to spin-up Kafka so that it can be used in integration tests

**Tasks**:
- [x] Design approach to spin-up Kafka for integration tests [ @mdebarros ]
- [x] Test the approach: https://github.com/mojaloop/project/issues/197 [ @shashi165 ]

**Acceptance Criteria**:
- [x] A strategy is documented/available which helps in spinning-up Kafka to be used for integration tests as necessary

**Dependencies**:
- None currently

**Accountability**:
- Owner: @rmothilal 
- Review:

**Comment by mdebarros** [comment]
Approach:
As part of the existing integration test script (integration.sh): This will be modified to start up a Kakfa+Zookeeper (combined) Docker container which will be used for the Integration tests.

The test/example for this being the following story: https://github.com/mojaloop/project/issues/197

This approach has been implemented in the ml-api-adapter.

**Comment by mdebarros** [comment]
Note this has also been resolved as per the following PR: https://github.com/rmothilal/central-ledger/pull/17
