### ISSUE TITLE
Create TechOps Hub Operating guidelines for Change Management

### ISSUE THREAD

**Issue by chris-me-law** [mojaloop/project#2380]
## **Goal**:
As a Hub Operator

I want to have a detailed technical operations guidelines for Change Management

so that I can implement strategies for effecting change, controlling change and helping people to adapt to change

**Acceptance Criteria**:
- [x] Create a detailed process document without step-by-step guidance to the actual tools that support these processes:

**Complexity**: Medium
**Uncertainty**: Low 

---

**Tasks**:
- [x] Collate material from implementation experience and ensure that it is generic
- [x] Convert current content from asciidoc to markdown (command line conversion + manual clean-up)
- [x] Organise content into folder structure that VuePress expects
- [x] Add helper files that VuePress expects

**Done**
- [x] Acceptance Criteria pass
- [x] Documents are available in https://github.com/mojaloop/mojaloop-business-docs 

## **Accountability**:
- Owner: Vanda Illyes
- QA/Review: Sub-team of the Product Council

**Comment by elnyry-sam-k** [comment]
completed via https://github.com/mojaloop/mojaloop-business-docs/pull/11
