### ISSUE TITLE
Create TechOps Hub Operating guidelines for Release Management

### ISSUE THREAD

**Issue by chris-me-law** [mojaloop/project#2381]
## **Goal**:
`As a` Hub Operator

`I want to` have a detailed technical operations guidelines for Release Management
  
`so that` I can ensure that the integrity of all the environments are protected and that the correct components are released.

**Acceptance Criteria**:
- [x] Create a detailed process document without step-by-step guidance to the actual tools that support these processes: Release Management

**Complexity**: Medium
**Uncertainty**: Low 

---

**Tasks**:
- [x] Collate material from implementation experience and ensure that it is generic
- [x] Convert current content from asciidoc to markdown (command line conversion + manual clean-up)
- [x] Organise content into folder structure that VuePress expects
- [x] Add helper files that VuePress expects

**Done**
- [x] Acceptance Criteria pass
- [x] Documents are available in https://github.com/mojaloop/mojaloop-business-docs 

## **Accountability**:
- Owner: Vanda Illyes
- QA/Review: sub-team of the product council

**Comment by elnyry-sam-k** [comment]
completed with https://github.com/mojaloop/mojaloop-business-docs/pull/11
