### ISSUE TITLE
Helm release v13.0.2

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2382]
## **Goal**:
`As a` ML OSS Code base maintainer

`I want to` validate and make a patch release to v13 that is successfully validated by the Golden path tests
  
`so that` Community members can take and use a version of Mojaloop Switch services bundle that is tested and contains the latest features and enhancements such as CGS, etc and bug fixes added in PI-14/PI-15.

**Acceptance Criteria**:
- [x] Helm RC v13.0.2 is validated on Moja2 to achieve 100% result with TTK GoldenPath collection
- [x] QA (Golden path) on deployments done on AWS Moja2 environment is done
- [x] Bugs are logged based on observations, failures
- [x] Bugs logged are fixed if critical to make subsequent releases in individual services (or Helm)
- [x] All the changes needed for supporting v13.0.2 of Helm are done
- [x] Helm v13.0.2 is released and release notes published
- [x] Test cases v13.0.2 is published (TTK)
- [x] TTK tests run successfully as Post-Hook jobs and Tests

**Complexity**: Medium - Involves all core and supporting services

**Uncertainty**: Medium

---

**Tasks**:
- [x] Make releases on all core services to have latest images / versions [@elnyry-sam-k , @mdebarros]
  - [x] Need latest ALS release after vulnerabilities (dependabot alerts are addressed)
- [x] Identify changes needed for helm (config / default.json)
- [x] Initial PR with changes for v13.0.2
  - [x] Initial PR review
  - [x] Deploy, validate, fix issues, redeploy
  - [x] With stable deployment test Golden path
- [x] Identify issues with QA Scripts if any - fix them and retest
  - [x] Update tests for accented characters and other unicode characters (Myanmar script and others)
- [x] Identify Bugs, log them
- [x] Fix bugs logged if critical
- [x] Deploy, validate on AWS Moja2
- [x] Validate with TTK GP collection
- [x] TTK test-cases repo v13.0.2 is published
- [x] Validate upgrade scenario (to v13.0.2) from v13.0.1
- [x] Release notes for helm v13.0.2 drafted
- [x] Helm v13.0.2 released
- [x] Review deployment guide documentation to ensure its up-to-date
- [x] Deployment of released Helm v13.0.2 on **Moja2**
  - [x] Helm v13.0.2 is deployed on **Moja2** successfully
  - [x] Validation using Golden path regression tests etc on Moja2
    - [x] Mojaloop Simulator postman collection
    - [x] TTK Post-hook install job and Tests
  - [x] Validation using CGS Golden path regression tests etc on Moja2
    - [x] Mojaloop Simulator TTK collection
- [x] Deployment of released Helm v13.0.2 on **Moja1**
  - [x] Helm v13.0.2 is deployed on **Moja1** successfully
  - [x] Validation using Golden path regression tests etc on Moja2
    - [x] Mojaloop Simulator TTK collection
    - [x] TTK Post-hook install and Tests
  - [x] Validation using CGS Golden path regression tests etc on Moja2
    - [x] Mojaloop Simulator TTK collection
    - [x] TTK Post-hook install and Tests

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] TTK Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- See release notes for the full list: https://github.com/mojaloop/helm/releases/tag/v13.0.2

## **Issues**:
- See release notes for the full list: https://github.com/mojaloop/helm/releases/tag/v13.0.2

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @mdebarros 
- QA/Review: @mdebarros @elnyry-sam-k @vijayg10

**Comment by mdebarros** [comment]
Leaving this issue open for approximately 2 weeks to pick up issues/bugs that can be included before creating the release.

If anybody requires the fixes for Account-lookup-service/Quoting-service for the extended Unicode character fixes (https://github.com/mojaloop/project/issues/2358), then please use the development build for the time being: <pending>

**Comment by mdebarros** [comment]
PR for [Helm v13.0.2](https://github.com/mojaloop/helm/pull/448).

```text
Test Suite:GP Tests
Environment:moja2.test.mojaloop.live
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 2064                          │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 2064                          │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 0                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 446                           │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 99                            │
├───────────────────┼───────────────────────────────┤
│ Passed percentage │ 100.00%                       │
├───────────────────┼───────────────────────────────┤
│ Started time      │ Tue, 17 Aug 2021 08:46:09 GMT │
├───────────────────┼───────────────────────────────┤
│ Completed time    │ Tue, 17 Aug 2021 08:48:32 GMT │
├───────────────────┼───────────────────────────────┤
│ Runtime duration  │ 142526 ms                     │
└───────────────────┴───────────────────────────────┘
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2021-08-17T08%3A48%3A32.170Z.html)

**Comment by mdebarros** [comment]
GP Tests on moja2 which includes minor change ([account-lookup-service/pull#425](https://github.com/mojaloop/account-lookup-service/pull/425)) for the following issue:

1. **#2374:** ALS is sending out multiple requests to participants for both Oracle records that match non-subId and subId result set ([account-lookup-service/pull#424](https://github.com/mojaloop/account-lookup-service/pull/424), [account-lookup-service/pull#425](https://github.com/mojaloop/account-lookup-service/pull/425) closes [mojaloop/#2374](https://github.com/mojaloop/project/issues/2374))

```text
--------------------FINAL REPORT--------------------

Test Suite:GP Tests
Environment:moja2.test.mojaloop.live
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 2064                          │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 2064                          │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 0                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 446                           │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 99                            │
├───────────────────┼───────────────────────────────┤
│ Passed percentage │ 100.00%                       │
├───────────────────┼───────────────────────────────┤
│ Started time      │ Tue, 17 Aug 2021 18:34:57 GMT │
├───────────────────┼───────────────────────────────┤
│ Completed time    │ Tue, 17 Aug 2021 18:37:16 GMT │
├───────────────────┼───────────────────────────────┤
│ Runtime duration  │ 139027 ms                     │
└───────────────────┴───────────────────────────────┘
Successfully uploaded the file to S3. URL is s3://mojaloop-oss-qa-results/ttk-tests/reports/TTK-Assertion-Report-multi-2021-08-17T18:37:16.272Z.html
Slack notification sent.
```

**Comment by elnyry-sam-k** [comment]
removing 15.2 for now to address pre-requisites for this in 15.2 - once these are done (regex related changes and other bug fixes), this will be prioritized

**Comment by mdebarros** [comment]
```
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2021-09-17T15%3A19%3A17.032Z.html)
