### ISSUE TITLE
Create TechOps Hub Operating guidelines for Defect Triage

### ISSUE THREAD

**Issue by chris-me-law** [mojaloop/project#2388]
## **Goal**:
`As a` Hub Operator
`I want to` have a detailed technical operations guidelines for Defect Triage
  
`so that` I can review and prioritise open defects and provide stakeholders with the opportunity to track progress, review and take action based on the information available.

**Acceptance Criteria**:
- [x] Create a detailed process document without step-by-step guidance to the actual tools that support these processes:

**Complexity**: Medium
**Uncertainty**: Low 

---

**Tasks**:
- [x] Collate material from implementation experience and ensure that it is generic
- [x] Convert current content from asciidoc to markdown (command line conversion + manual clean-up)
- [x] Organize content into folder structure that VuePress expects
- [] Add helper files that VuePress expects

**Done**
- [x] Acceptance Criteria pass
- [x] Documents are available in https://github.com/mojaloop/mojaloop-business-docs 

## **Accountability**:
- Owner: Vanda Illyes
- QA/Review: Sub-team of product council

**Comment by elnyry-sam-k** [comment]
completed with https://github.com/mojaloop/mojaloop-business-docs/pull/11
