### ISSUE TITLE
2.3.8.1 Design event logging Framework- [8]

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#239]
**Goal**:
As a developer
I want to __design an event logging Framework__
so that this can be used to implement LoggingHandlers

**Tasks**:
- [ ] Design event logging DB object(s) [ @ggrg ]
- [ ] Design event logging Framework
- [ ] Review the design

**Acceptance Criteria**:
- [ ] Update sequence diagram to show the event logging framework
- [ ] Design reviewed by the Design Authority
- [ ] Design published

**Dependencies**:
- None currently

**Blockers**:
- [x] https://github.com/mojaloop/project/issues/247 (due to resource constraints)

**Accountability**
- Owner @mdebarros 
- Review **Design Authority**

**Comment by elnyry** [comment]
Using #765 now..
