### ISSUE TITLE
ml-bootstrap - add seeds for `/thirdpartyRequests/verifications` endpoints

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2391]
## **Goal**:
`As a` DFSP and Hub Operator (auth-service)

`I want to` be able to easily register 
  
`so that` <reason> 

**Acceptance Criteria**:
- [ ] Updated endpoints in https://github.com/vessels-tech/ml-bootstrap that enable a DFSP and Auth Service to easily register their endpoints

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
