### ISSUE TITLE
[auth-service] Update DB schema and add fido2 verification functionality

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#2393]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` be able to verify signatures using `auth-service`
  
`so that` I can verify a user is initiating a transfer

**Acceptance Criteria**:
- [x] Updated DB schema to handle FIDO credential field storage
- [ ] Updated verification functions to use new `fido2-lib` for verification

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@kleyow what's the status on this one?

**Comment by kleyow** [comment]
Uh...I think you could call this done since the library has the function, the state machine still needs to be updated to pull the consent and verify in a transistion. @lewisdaly

**Comment by lewisdaly** [comment]
Ok cool, yeah that's right, I remember where we left it last time now. 

I'll close this and make a new ticket for looking up the consent and verification etc.
