### ISSUE TITLE
Create a lightweight POC to demonstrate and confirm microservice design using Jamstack with atomic deploys to a CDN

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2394]
## **Goal**:
`As a`  Mojaloop Community Design Authority 
`I want to` adopt a UI framework
`so that` I can incorporate my customised UI that is sourced from a different repo into the standardised offering using configuration that atomically deploy to a CDN and uses the hub operators IAM

**Acceptance Criteria**:
- [x] Verify that the POC supports an Atomic deploy to a CDN
- [x] Verify that the POC is a Micro-frontend compilation from multiple repos
- [x] Verify that the state container store used is compatible with the CDN

**Complexity**: <High > Multiple concepts combined

**Uncertainty**: <Med>  Failure with the tools, however have not put them together this way before. May need to use a new state lib.

- [x] Build Working POC Demo Story
- [x] Initial design artefact presented to the DA for discussion

---

**Tasks**:
- [x] Design artefact presented to the DA that outlines how the Micro-frontend and JAMStack are to be deployed.
- [x] Framework UI POC that implements Micro-frontends and atomic JAMStack deploys.

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by kleyow** [comment]
Write up by Ivan about the rational behind the boilerplates
https://github.com/modusintegration/microfrontend-shell-boilerplate/wiki/Motivation

**Comment by PaulGregoryBaker** [comment]
Added above motivation to the Mojaloop hosted design documents.
