### ISSUE TITLE
Create an exemplar POC that demonstrates how the RBAC design can be built

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2395]
## **Goal**:
`As a` Mojaloop Community Design Authority
`I want to` enforce RBAC controls for hub operations by adopting this framework
 `so that`  the users and their associated roles can be easily maintained that enforce access control based on a configurable set of associated permissions in a security approved hub deployment

**Acceptance Criteria**:
- [x] An exemplar POC demonstrates how this can be built onto the current Mojaloop version showing RBAC 
- [x] Build a complete helm chart that includes all the pieces of the POC using a fake service (WSO2 Identity Server)
- [ ] Verify that the RBAC user information is accessible through the Audit logs 
- Specific Information: Existing Logging Information
- Opaque Token in the header
- Current logging performed by WSO2
- Deploy WSO2 minus Auth turned off for this demo
- [x] Verify that the permissions associated with the role are independently configured from the IAM
- Manually inject for the POC and call out 2 additional stories for that management
- Additional Story: Assignment of Roles to Users
- Additional Story: Details of the roles permissions are configured
- Keto
- [x] Verify that users without the correct roles do not have access to the backend API's
- [x] Verify that users with role but without the correct associated permissions do not have access to the backend API's
- [x] Verify that users that are not logged do not have access to the backend API's
- [x] Verify that a simplified set of tests has been implemented that highlights the RBAC goals

**Complexity**: <High > New tools with a mix of technologies

**Uncertainty**: <High > 
New tools with a mix of technologies
ISK - Risk for deployment of WSO2 Identity Server

---

**Tasks**:
- [x] Create initial helm chart composing Ory Keto and Ory Oathkeeper
- [x] Create deployment connecting composed helm chart to IdP and protecting fake service
- [x] Create tests covering acceptance criteria
- [x] Update helm charts to have smart defaults and avoid duplicating internal configuration

**Done**
- [x] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: Russel
- QA/Review: TBC
