### ISSUE TITLE
Build a POC

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2396]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` <action>
  
`so that` <reason> 

**Acceptance Criteria**:
- [ ] Verify that micro-front ends are packaged in the build
- [ ] Verify that only static markup assets are used
- [ ] Verify that markup is not rendered during runtime.
- [ ] Verify that data is provided through APIs
- [ ] Verify that deployment is through atomic deploys
- [ ] Verify that cache invalidation is automatic
- [ ] Verify that deployment is on a CDN or equivalent hosting (e.g. git pages).
- [ ] Verify that the IAM and RBAC is implemented and restricted at an API level.
- [ ] Verify that Permissions are linked to the defined roles and separately configured and restrict access at an API level.
- [ ] Verify that Session caching is operational on the CDN deploy
- [ ] Verify that the audit logging contains a user reference

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
