### ISSUE TITLE
[dev-portal] - Allow user to register a phone number as 'government account holder' with a simulator

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2398]
## **Goal**:
`As a` hackathon user

`I want to` be able to register a real phone number as a 'government account holder'
  
`so that` I can receive real SMS messages to make the 3PPI demo real

**Acceptance Criteria**:
- [x] User can go to sandbox.mojaloop.io, and be directed to register their phone number at some sort of BankOne simulator.

**Complexity**: High

**Uncertainty**: High

---

**Tasks**:
- [x] attach some persistent state to the simulator
- [x] implement some account setup APIs on the simulator
- [x] ~integrate with Twilio to send an SMS and verify that the phone number is real~ - using firebase auth
- [x] implement a small front-end app to perform the registration (maybe ok to use Retool for at least a first pass?)
- [x] deploy updated simulator
- [x] add links to the simulator

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/contrib-dev-portal/pull/12

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
