### ISSUE TITLE
Automated `helm tests` validations during CI/CD release

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2399]
## **Goal**:
`As a` OSS Contributor

`I want to` validate releases using `helm test` on a lightweight k8s as part of the CI/CD process
  
`so that` Mojaloop releases are automatically verified no longer requiring manual checks

**Acceptance Criteria**:
- [ ] Helm releases included a `helm test` verification step against a deployed lightweight k8s as part of the CI/CD process
- [ ] Helm reports are published to AWS S3 Buckets
- [ ] Helm tests results are announced in Slack

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
