### ISSUE TITLE
Create Business Process Guide for Settlement Management

### ISSUE THREAD

**Issue by chris-me-law** [mojaloop/project#2401]
## **Goal**:
`As a` Hub Operator

`I want to` have a business process guide for Settlement Management
  
`so that` I can use it for financial management on the Switch (for managing settlements)

**Acceptance Criteria**:
- [x] Create a business process guide for Settlement Management

**Complexity**: Medium
**Uncertainty**: Low 

---

**Tasks**:
- [x] Collate material from implementation experience and ensure that it is generic
- [x] Organise content into folder structure that VuePress expects
- [x] Add helper files that VuePress expects
- [x] Final internal reviews

**Done**
- [x] Acceptance Criteria pass
- [x] Documents are available in https://github.com/mojaloop/mojaloop-business-docs 

## **Accountability**:
- Owner: Vanda Illyes
- QA/Review: sub-team of the product council

**Comment by elnyry-sam-k** [comment]
completed with https://github.com/mojaloop/mojaloop-business-docs/pull/11
