### ISSUE TITLE
Define RBAC requirements for Schemes & Roadmap for Business Operations framework

### ISSUE THREAD

**Issue by chris-me-law** [mojaloop/project#2403]
## **Goal**:
`As a` product owner/manager of a Mojaloop implementation / deployment team

`I want to` have an Guide on access control based on roles (RBAC)
  
`so that` I can review it and use as a template for my Hub, Scheme

**Acceptance Criteria**:
- [x] RBAC guide, considerations and design for a Mojaloop Hub is made available on mojaloop-business-docs repo as markdown document

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Create an initial draft
- [x] Convert to markdown 
- [x] Compatibility with vuepress
- [x] Final reviews (internal) and published on Mojaloop GitHub to be reviewed by Product Council

**Done**
- [x] Acceptance Criteria pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/mojaloop-business-docs/pull/11

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vandaillyes-modusbox , @PaulGregoryBaker , @elnyry-sam-k 
- QA/Review: Product Council sub-team

**Comment by elnyry-sam-k** [comment]
completed with https://github.com/mojaloop/mojaloop-business-docs/pull/11
