### ISSUE TITLE
[dev-portal] - list of participants who support 3PPI Features

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2406]
## **Goal**:
* As a CDBC innovator, I want to be able to get a list of all DFSPs who support account linking features, and select mine from the list.

**Acceptance Criteria**:
- [ ] sync API call exposed that fetches a list of the available DFSPs for linking
- [ ] dev portal documentation that shows how to use that for _my_ PISP's 3rd Party API Adapter

**Complexity**: Medium
**Uncertainty**:  Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
