### ISSUE TITLE
Central Services Admin API "id" should return Datastore Identifier

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2407]
## **Goal**:
`As a` Mojaloop Operator

`I want to` have the Central Services Admin API to return a datastore identifier instead of an FQDN (as per specification)
  
`so that` the datastore identifier can be returned providing some alignment to the central-settlements service

**Acceptance Criteria**:
- [ ] API Speciifcation is updated to reflect that the ID is the datastore identifier
- [ ] Central-Service Admin Service will be updated to reflect this change:
    - [ ] GET /participants end-point will have an optional query filter param for `id`
    - [ ] Operations that return Participant entities will return the datastore `id` instead of the FQDN

**Complexity**: Low

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @mdebarros 
- QA/Review: Mojaloop Change Control Board, Core OSS Team
