### ISSUE TITLE
Central Settlements API to provide the Participant "name" when returning the Participant entity 

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2408]
## **Goal**:
`As a` Hub Operator

`I want to` updated the Central-Services API to return the Participant `name` whenever the Participant entity is provided as a response to any operations
  
`so that` Hub Operators/Integrators can use the Participant `name` to query the Central Services Admin API

**Acceptance Criteria**:
- [ ] Central-Settlements API operations include the Participant `name` when the Participant entity is returned in any response (along with the existing Participant `id`).

**Complexity**: Low

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @mdebarros 
- QA/Review: Mojaloop Change Control Board, Core OSS Team

**Comment by mdebarros** [comment]
@MichaelJBRichards FYI.
