### ISSUE TITLE
TTK Docs - Add documentation missing from MTP slide deck

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2409]
## **Goal**:
`As a` user of TTK

`I want to` have the documentation uptodate
  
`so that` I can refer it for my usercase

**Acceptance Criteria**:
- [ ] TTK docs are up to date

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] Convert the missing documentation into markup format from MTP

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
