### ISSUE TITLE
QA improvements for Unit Tests and Code Coverage - event-stream-processr

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2412]
QA improvements for Unit Tests and Code Coverage - email-notifier

## **Goal**:
`As a` Hub Operators

`I want to` improve unit test & code coverage on the mojaloop/event-stream-processr
  
`so that` quality of code meets the Mojaloop Standards

**Acceptance Criteria**:
- [ ] Ensure that unit tests & code-coverage passes against the following rules:

```yaml
per-file: true
lines: 90
statements: 90
functions: 90
branches: 90
```

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
