### ISSUE TITLE
Complete and Present Finalised Design Document/s for Mojaloop DA Approval

### ISSUE THREAD

**Issue by chris-me-law** [mojaloop/project#2414]
## **Goal**:
`As a` Mojaloop Community Design Authority

`I want to` see a completed version of the BizOps Framework design
  
`so that` I can understand the problems that it solves for me; how to use the framework; and understand the work effort required to make the adoption of the framework.

The document should be high level and somewhat technical.
The detailed technical will be in the source-code and boiler place source code; this document should compliment that.
Need to highlight the good design principles being implemented. I.e. needs to sell the framework so that other community work efforts adopt it.

**Acceptance Criteria**:
- [ ] ...
- [x] Verify that the Document contains considerations for Mojaloop Reference Architecture Future Proofing
- [x] Verify that the Document contains considerations for IAC4 Architecture Future Proofing
- [x] Verify that the Document is in markdown and meets community standards
- [x] Verify that the Document is source controlled in community OSS repositories
- [x] Verify that the Document has been authorised by Executive Sponsor and Principle Architects

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Document restructured into Security BC, Micro-front ends & JAMStack, and Reporting and Auditing BC and Deployments
- [x] Finalise Markdown for document
- [x] Commit to Mojaloop Repos

Security BC
- [x] Sequence diagrams for logging in
- [x] Sequence diagrams for operational API call
- [x] Sequence diagrams for User Role Assignment
- [x] Sequence diagram for Role permission assignment
- [x] Overview architecture diagram for current Mojaloop and IaC3.xx
- [x] Overview architecture diagram for IaC 4.xx
- [x] Alignment to Reference architecture diagram
- [x] Keto detailed usage description with Query, Store and Remove Tuples
- [x] Keto verify permission example

MicroService JAMStack
- [x] JamStack overview diagram (microservice, CDN and Git Actions) [@ivannovazzi ]
- [x] Boiler plate for Microservice [@ivannovazzi ]
- [x] Documentation supporting Boiler plate for microservice [@ivannovazzi ]
    - [ ] React Menu item component documentation[@ivannovazzi ]
- [x] Deployment heading description
- [x] Technology Stack

Reporting and Auditing BC
- [x] Design overview diagram
- [x] Alignment to reference architecture
- [x] Reporting DB
- [x] Reporting Event Store
- [x] Multiple data syncs 
- [x] Graph QL implementation
- [x] Future extensions
- [x] Technical debt

Deployments
- [x] IaC 4.xx diagram
- [ ] 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
