### ISSUE TITLE
Design the Reporting & auditing BC to provide an end-to-end transaction view including settlement for a transaction

### ISSUE THREAD

**Issue by chris-me-law** [mojaloop/project#2417]
## **Goal**:
`As a` Design Authority
`I want to` review the design for the Reporting & Auditing BC operational API 
`so that` I can validate that the full audit and tracing capability for a given Txn can be performed practically conforming to best practice and security requirement.

**Acceptance Criteria**:
- [ ] Verify that the Reporting & auditing BC is for the current version of Mojaloop (v13)
- [ ] Verify that an individual transaction can be viewed
- [ ] Verify that hub generated errors associated with a transaction failure are visible in this view.
- [ ] Verify that Payee DFSP generated errors associated with a transaction failure are visible in this view.
- [ ] Verify that Payer DFSP generated errors associated with a transaction failure are visible in this view.
- [ ] Verify that the settlement information linked to the viewed transfer is available in this view.
- [ ] Verify that Reporting API CCB Group 
- [ ] Verify that the design is performant 

**Complexity**:  Medium 
- Simple Reporting DB and Elastic Search

**Uncertainty**: Medium
- Performance
- Community Acceptance
- Community thinking on the use of GraphQL
- Database Selection is a key decision (Relational or not)

---

**Tasks**:
- [x] Discuss with team and understand the modules involved and data flow [ @vijayg10 @Lenbkr @kirgene @elnyry-sam-k @PaulGregoryBaker ]
  - Search Criteria: Date range, any IDs, DFSP, Error codes, general text search, amount, currency ...etc
  - Return Data: Transaction status, associated settlement and status, the messages and timestamps
  - Module architecture diagram in the comments
- [ ] Prepare a very minimal POC module for graphQL [ @kirgene ]
- [ ] Action items from the discussion
  - [x] Define use cases [ @PaulGregoryBaker ]
    - [x] TransferID search (Part of delivery)
    - [x] All the possible use-cases to be documented (Because it is a deciding factor for tools & technologies)
  - [x] Documentation about different approaches - [ @vijayg10 ]
  - [x] Kafka aggregation (tables & queries) capabilities - discuss with Miguel - [ @vijayg10 ]
  - [ ] Event sourcing / stateful data store - [ @kirgene ]
  - [ ] Database selection (Depends on the above task)
     - Relational Database
     - NoSQL
     - Event sourcing friendly DBs
- [ ] Create Use Case, Sequence Diagrams and Data requirements to implement the traceability of a transfer [ @Lenbkr @vijayg10  ]
- [x] Business Flow for the Transfer Tracing Use Case (Hub Operator and User) [ @Lenbkr ]
- [x] Inspect the existing kafka messages from audit and trace events [ @vijayg10 ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: Vijay Kumar, Yevhen Kyriukha, Len Bekker
- QA/Review: Vijay Kumar

**Comment by vijayg10** [comment]
The following is the initial thought derived from the discussion with @PaulGregoryBaker @kirgene @Lenbkr 

![BOF-reporting-module-architecture-interation1](https://user-images.githubusercontent.com/33152110/130656057-2884e318-defb-4772-8001-20fc424c5186.png)

**Comment by vijayg10** [comment]
After a detailed discussion with @elnyry-sam-k and @mdebarros about the above design, we thought there is a deviation in the data flow. The following is the suggested and original design.

**Comment by vijayg10** [comment]
Discussed with the team and everyone was agreed with this design.
There are some ideas about design patterns.
Please refer to this document https://docs.google.com/document/d/1JypFxHuLXzRtbpZ5bsGxEEzO1t9mKoOJrD_00YyCzhw/edit?usp=sharing

The action items derived from the discussion are updated in the tasks

**Comment by PaulGregoryBaker** [comment]
This story is being closed even though it is incomplete.
This is because the new stories have been written to include the outstanding items.
#2442 replaces the graphQL POC as a generic data resource solution
The story was change to just be a design story.
The design has taken a different path that is more aligned to the reference architecture to create a reporting data store from the kafka topic messages.
This is encapsulated in these stories.
#2441,#2442,#2438,#2443
