### ISSUE TITLE
Demonstration of tracing a transfer as a Hub Operator

### ISSUE THREAD

**Issue by chris-me-law** [mojaloop/project#2418]
## **Goal**:
`As a` Mojaloop Hub's Business Operations User
`I want to` understand how the BizOps framework can be used 
`so that` I can trace a Mojaloop transaction from the hub end-to-end

`As a` Mojaloop Community Contributor
`I want to` understand how the BizOps framework can be used 
`so that` I understand the effort required and benefit provided by adopting the framework

**Acceptance Criteria**:
- [x] Demonstration of the tracing of a transaction end-to-end

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Record and share version1[ @sri-miriyala ]
- [x] Record and share version2[ @sri-miriyala ]

**Done**
- [x] Acceptance Criteria pass

## **Accountability**:
- Owner: @sri-miriyala 
- QA/Review: TBC
