### ISSUE TITLE
Provide a micro-front end view that provides an end-to-end transaction view

### ISSUE THREAD

**Issue by chris-me-law** [mojaloop/project#2422]
## **Goal**:
`As a` Mojaloop Community Software Engineer

`I want to` configure the BizOps Framework to incorporate an exemplar end-to-end transaction view 
  
`so that` I can trace a transaction end-to-end

**Acceptance Criteria**:
- [ ] Exemplar micro-front end for end-to-end transaction tracing available to the BizOps framework through configuration.
- [ ] Exemplar experience layer API that uses RBAC IAM that calls the Reporting and Auditing BC Operational APIs.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
![TracingATransferUX](https://user-images.githubusercontent.com/40144680/135974754-16200485-19b1-4121-9406-caaf7a7f07af.png)

**Comment by chris-me-law** [comment]
https://docs.google.com/document/d/1ibTtjxUbdYFPJOUMVKF_KSk5F727NkALaLDzGvBvXDY/edit
