### ISSUE TITLE
[auth-service] - ability to skip validation of certain consent.credentialIds

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2423]
## **Goal**:
`As a` hackathon user 

`I want to` be able to copy and paste pre-generated credentials to add to a Consent object
  
`so that` I can complete account linking without implementing the front-end fido flow

**Acceptance Criteria**:
- [ ] A deployer can specify a list of credentialIds for testing purposes that will be approved by the auth-service
- [ ] A PISP can send `PUT /consents` with a credential

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
