### ISSUE TITLE
Create Initial Business Operations Framework UI Design Document for approval by Mojaloop DA

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2424]
## **Goal**:
`As a`  Mojaloop Community Design Authority 
`I want to` review the UI framework design
`so that` I am confident that it meets the requirements of the framework

**Acceptance Criteria**:
- [ ] Verify that the UI design confirms to the JAMStack design principles
> - [ ]  Static Markup only
> - [ ]  Backend APIs
> - [ ]  Javascript
> - [ ]  Deploy to CDN
> - [ ]  Atomic Deploys
> - [ ]  Auto cache invalidation
- [ ] Verify that design include Micro-frontends committed to independent repos
- [ ] Verify that a suitable IAM integration Standard(s) for the framework has been selected
- [ ] Present design to the Mojaloop design authority

**Complexity**: <Med > Multiple concepts combined
**Uncertainty**: <Med>  Familiar with the tools, however have not put them together this way before. May need to use a new state lib.

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by ivannovazzi** [comment]
[# Motivation.md](https://github.com/mojaloop/project/files/7091237/Motivation.md)

**Comment by elnyry-sam-k** [comment]
Thanks for the update @ivannovazzi ; adding it to the story #2394 as well
