### ISSUE TITLE
Design for Exception handling framework

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#243]
**Goal**:
As a developer I would like to Design for Exception handling framework so that error/exceptions are gracefully handled.

**Hint**:
Leverage event handling to do this (as a special kind of event) and specific handler for those events.

**Tasks**:
- [ ] Design session for an exception handling framework (decide on a framework - hapi?)
- [ ] Exception handling framework for backend and for business needs
- [ ] Roll-up internal error code and provide to adapter which may then do the lookup/translation

**Acceptance Criteria**:
- [ ] Deliver a comprehensive design for Exception handling framework across the system
- [ ] Error events logging for adapters

**Dependencies**:
- None currently

**Comment by elnyry** [comment]
Using #765 now..
