### ISSUE TITLE
Option for breaking a test case on error

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2431]
## **Goal**:
`As a` QA member

`I want to` have an option to break the test execution incase of failure
  
`so that` I don't need to wait for remaining tests and prevent unnecessary requests

**Acceptance Criteria**:
- [ ] The following options are available in each test case incase of error
  - [ ] Break the current test case execution
  - [ ] Break entire test run
- [ ] The skipped tests in a test case in this case should be marked appropriately

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
