### ISSUE TITLE
ML TTK: MTP TTK course content - iterating with MTP, Hubble teams

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2434]
## **Goal**:
`As a` MTP team member

`I want to` address feedback and inputs provided by reviewers, Hubble team for the MTP TTK course content
  
`so that` it can be considered for publication along with other course 

**Acceptance Criteria**:
- [x] Feedback and inputs provided by Hubble team other reviewers is addressed
- [x] MTP course content is considered for publication

**Complexity**: High

**Uncertainty**: Medium

---

**Tasks**:
- [x] Address feedback from reviewers
- [ ] ~Finalize last section (using Payment Manager) to be included with rest of the course content~
- [x] Address feedback from Hubble team
- [x] Any other changes needed to consider the MTP course content for publication

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Presentation is reviewed and iterated over to incorporate feedback provided

## **Pull Requests**:
- N/A

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 @elnyry-sam-k 
- QA/Review: MTP team

**Comment by elnyry-sam-k** [comment]
MTP TTK 101 is published learn.mojaloop.io !
