### ISSUE TITLE
Finalise the BOF Reporting & Auditing API BC design

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2437]
## **Goal**:
`As a` Design Authority
`I want to` view a proposed design that implement the Reporting and auditing operational BC API
`so that` it meets all the use case requirements, within time and budget, and conforms to the reference architecture within reason, and functions on the latest Mojaloop version.

**Acceptance Criteria**:
 Finalise Design Proposal
- [x]  Verify that a single Architectural Design is proposed
- [x]  Verify that Generic Data Resource Design specification is proposed that queries all data stores (satisfy use cases by querying simple types: transactions, parties, dfsps)
- [x]  Verify that the generic resource implements GraphQL 
- [x]  Verify that the Proposed Design for the 'Reporting and Auditing' BC API Resources meets the use case requirements
- [x]  Verify that design has clear guidance on supported nested graph QL queries (e.g. use nesting queries for MongoDB resources only etc..., are filters on nested object permitted.)
- [x] Verify that the Reporting & auditing BC is for the current version of Mojaloop (v13) ?
- [x] Ensure the Reporting & Auditing API is able to provide an end-to-end transaction view including settlement for a transaction on current version of Mojaloop ?

**Complexity**:  Medium 
- Simple Reporting DB and Elastic Search

**Uncertainty**: Medium

---

**Tasks**:
- [x] Sign off on proposed design TBD ask Sam?
- [x] Get Access to Mojaloop Prod environment @elnyry-sam-k @Lenbkr @kirgene 
    - [x] Deploy Mojaloop to Prod environment @vijayg10 @Lenbkr
    - [x] Deploy Kowl to Prod environment @vijayg10 @Lenbkr 
- [x] Research whether Kafka Connector is viable as sink [Kafka->MongoDB] @Lenbkr 
- [x] Design of Reporting Database [Mongodb Eventstore]
    - [x] Determine criteria from kafka topic for audit events. @Lenbkr 
    - [x] Create basic schema for mongodb preserving original event message @Lenbkr 
- [x] Define Proposed 'Reporting and Auditing' BC API Resources 
    - [x] Generic lookup like DFSPs, Users, Transactions filtered by date, etc in plain english @kirgene , @Lenbkr 
- Present to the Reporting API CCB Group TBD - no longer a requirement
- ~~Implement Automated Testing~~
    - ~~Validation of Kafka Topics by running transactions and validating the data~~
    - ~~Validation of MongoDB schema~~
    - ~~GraphQL integration tests for API resources~~ @kirgene

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- Environment to deploy to

## **Accountability**:
- Owner: @kirgene @Lenbkr 
- QA/Review: @vijayg10
