### ISSUE TITLE
Build the Reporting Event store event processor - for tracing a transfer that converts event stream into a queryable data store

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2438]
## **Goal**:
`As a` Hub Operator Technical Specialist
`I want to` build a reporting and auditable data store
`so that` I have access to various levels of the transactional that can be used for auditing, reporting and tracing transfers.

**Acceptance Criteria**:
- [ ] Verify that the datastore conform to design for Reporting & Auditing BC API
- [ ] Verify that data mapped from the Kafka topics in #2441 is included / stored
- [ ] Verify that the datastore is queryable in an efficient way to meet the use cases defined in #2417 
- [ ] Verify that Unit Testing is in Place
- [ ] Verify that a Docker File has been completed
---

**Tasks**:
- [x] Create event processing engine
    - [x] Subscribe to Kafka Topic
    - [x] Events Filter (quote, transfers, settlement)
    - [x] Transform Events
    - [x] Persist resulting events to MongoDB
    - [x] Refactoring Code
- [ ] Design and Create Unit Tests 
   - [ ] Testing documentation
   - [x] Mojaloop Code Standards
   - [x] Create unit tests environment
   - [x] Create test cases
   - [x] Create integration test cases  
- [x] Commit code to Mojaloop repository
- [ ] Create Docker file(s)
- [ ] Deploy to testing environment
   - [ ] Create Helm Chart
   - [ ] Deploy to bof1 environment
- [ ] Create Basic Query Scaffold to verify data ? (Acceptance criteria)

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
