### ISSUE TITLE
Update central services database to support batch inserts and transactions

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#244]
**Goal**:
As a developer I would like to **Update central services database to support batch inserts and transactions** so that batch processing can be implemented

**Tasks**:
- [x] Expose knex database object to dependencies
- [x] Update Unit Tests

**Acceptance Criteria**:
- [x] Update central services database to support batch inserts
- [x] Update central services database to support transactions

**Dependencies**:
- N/A
