### ISSUE TITLE
Deploy and Migrate to Docs 2.0

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2440]
## **Goal**:
`As a` community member
`I want to` see the new docs pages when I go to `docs.mojaloop.io`
`so that` I can see the latest iteration of the docs and learn about mojaloop

**Acceptance Criteria**:
- [ ] new docs are deployed (as a preview mode) at docs.mojaloop.io

**Complexity**: Medium
**Uncertainty**: High

---

**Tasks**:
- [ ] Figure out how to link users to older pages if they aren't updated yet  
  - I think vuepress has a redirect plugin we can configure, but first we will need a list of all current pages
- [x] Merge docs 2.0 into the master branch of `mojaloop/documentation`
- [ ] switch over docs.mojaloop.io to point to the documentation homepage (it looks like it's currently redirecting to 

## Docs v2 Deployment Checklist
- [x] merge existing PRs @meekg33k 
- [x] fix broken build @meekg33k 
- [x] fix broken CI/CD @lewisdaly 
    > CI/CD doesn't look broken to me, but the actual yarn build is broken - [TODO: address tonight]
- [x] deploy new docs s3 bucket and site and retrieve cloudfront URL @lewisdaly (d2swsyveawc320.cloudfront.net)
- [x] run the versioning tool for `v1.0.0` - or figure out how to make `next` the default version (for now, until we get better releases) @lewisdaly  @meekg33k 
- [x] Merge in docs-2.0 branch to master (and restructure directories) @lewisdaly , @meekg33k , @mdebarros 
    > Blocked by above PRs - @lewisdaly 
- [x] compile list of links that will break and deploy redirect logic @lewisdaly 
    > Issue! The list exceeds 10kb which is the maximum Cloudfront function size - workaround is to reduce this list for now
- [x] figure out what to do with mojaloop business docs @lewisdaly @meekg33k 
  > Looks like CloudFront gives us options for path base routing. @lewisdaly to investigate tomorrow
- [x] deploy to docs s3 bucket
- [x] create a new DNS entry: docs-preview.mojaloop.io --> CloudFront URL @simeonoriko /Virtual
- [x] figure out how to sort out `mojaloop-business-docs` and `business-operations-framework-docs`- I didn't realise they were using the same domain (@lewisdaly to investigate if we can have path based routing similar to existing functionality)
  - we can replicate the existing method in cloudfront by adding a `mojaloop.github.io` origin, and configuring behaviours that will route to the correct github pages sites. In order for this to work, we must remove the CNAME entry from the `mojaloop.github.io` repo, otherwise cloudfront gets stuck in an infinite loop
- [x] Test HTTPS certs are generated properly, test docs.preview.mojaloop.io @all
- [x] Switch over docs.mojaloop.io DNS entry to --> CloudFront URL @simeonoriko /Virtual
- [x] remove the CNAME entry from the `mojaloop.github.io` repo @lewisdaly 
- [x] configure behaviours for mojaloop-business-docs and business ops docs pages
- [ ] Workshop to review documentation after migration done to review, document issues (if any)
- [x] test reference-architecture-doc, mojaloop-business-docs and business-operations-framework-docs

## Cleanup
- [ ] destroy the docs-preview resources after a successful switchover

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@meekg33k @simeonoriko I've written a deployment checklist based on our conversation on Monday.
