### ISSUE TITLE
Build a generic data resource/objects for the BC

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2442]
## **Goal**:
`As a` Technical Hub Operations specialist
`I want to` configure new Reporting data store that is queryable as a data resources in the Reporting and Auditing BC
`so that` I can build a new micro-front end in the BizOps framework that uses the resource to support changing hub process requirements 

**Acceptance Criteria**:
- [x] Verify that the data resource provides data from the central ledger database
- [x] Verify that the data resource provides data from the event reporting store
- [x] Verify that generic data resources are queryable through the graph ql interface
- [x] Verify that the Keto Permissions has been discussed
- [x] Verify that example data is available for UI testing (Either mocked or in the reporting DB and the reporting event store)

---

**Tasks**:
- [x] Create Transaction resource
- [x] Create DFSP resource
- [x] Create Party resource
- TBD

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
