### ISSUE TITLE
Use a UI List component that queries the GraphQL API

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2443]
## **Goal**:
`As a` Mojaloop Community Contributor build a micro-service UI to support hub operations
`I want to` view the information provided by the graphQL Reporting and Auditing BC API in my microservice
`so that` with minimal effort, I can sort, filter and paginate the data viewed.

**Acceptance Criteria**:
- [ ] Verify that the component can be configure to query the graph QL api
- [ ] Verify that UI filtering corresponds to the equivalent filtered graph QL query
- [ ] Verify that sorting on a column corresponds to the equivalent filtered graph QL query change
- [ ] Verify that pagination and current page selection corresponds to the equivalent graph QL query change

---

**Tasks**:
- [ ] Build a Feature Rich List

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Might not need this story worked on. Will re-evaluate later on in the project delivery.

**Comment by PaulGregoryBaker** [comment]
Don't need this, so closing.
