### ISSUE TITLE
Build specific resource implementations to meet the four use case requirements

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2444]
## **Goal**:
`As a` Hub Operator
`I want to` be able to trace a transfer
`so that` I can understand everything about the tranced transfer as defined by the use cases in #2417

Adjust the framework as necessary to implement the use cases.

**Acceptance Criteria**:
- [x] verify that the dashboard summary meets the defined requirements 
- [x] verify that the transfer list resource meets the defined requirements 
- [x] verify that the transfer detailed resource meets the defined requirements 
- [x] verify that the transfer message resource meets the defined requirements (MongoDB)
- [x] Verify that a transfer resource is queryable through the framework
- [x] Verify that a participant resource is queryable through the framework
- [x] Verify that a party resource is queryable through the framework

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Implement transfer summary query
  - [x] Implement SQL query to query transfers
  - [x] Add filter based on start and end date time 
  - [x] Add filter based on payer and payee fsp
  - [x] Add group by based on payer
  - [x] Add group by based on payee
  - [x] Add group by based on currency
  - [x] Add group by based on errorCode
  - [x] Add resource for quotes
- [x] `Expose Transaction Type`, `Transfer State`, `Settlement Batch Id` in Transaction resource

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
