### ISSUE TITLE
Complete new UI components

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2449]
## **Goal**:
`As a` Mojaloop community contributor
`I want to` use a table react component to provide functionality in the user interface
`so that` the user can filter/sort and paginate the results.

**Acceptance Criteria**:
- [x] Verify that the component performs client side filtering
- [x] Verify that the component performs client side sorting
- [x] Verify that the component performs client side pagination

**Complexity**: <Low> 
**Uncertainty**: <Low>

---

**Tasks**:
- [x] Add pagination to the table component [ @ivannovazzi  ]

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
