### ISSUE TITLE
Design Settlement Engine

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#245]
**Goal**:
As a developer I would like to Design Settlement Engine to facilitate Settlements

**Tasks**:
- [ ] Design Settlement Engine

**Acceptance Criteria**:
- [ ] A Settlement Engine to kick-off settlements based on an API request 
- [ ] Settlement Engine can settle all transfers (pending settlement)
- [ ] Settlement Engine can kick-off a position event to reduce the positions of each associated FSP
- [ ] The above design is documented

**Dependencies**:
- None currently

**Comment by elnyry** [comment]
Covered in stories starting with 3.xx numbers
