### ISSUE TITLE
Build User-Role API that assign roles to users (and participant to users)

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2451]
## **Goal**:
`As a` Hub Operator
`I want to` change the RBAC assignment of roles to RBAC user accounts accounts
`so that` I can manage service (user/app/DFSP) RBAC access control of users of the system as these change day-to-day.

`As a` Hub Operator
`I want to` change the RBAC participant assignment to RBAC user accounts that are necessary to enable participant API access control
`so that` I can manage service participant (DFSP) RBAC access control of users of the system as these change day-to-day.

**Acceptance Criteria**:
- [x] Verify that a user accounts can have a role/s assigned
- [x] Verify that a user accounts can have a role removed
- [x] Verify that a new user account is visible and can have a role assigned
- [x] Verify that user account role assignment changes result in keto
- [x] Verify that a user accounts can have a participant/s assigned
- [x] Verify that a user accounts can have a participant removed
- [x] Verify that a new user account is visible and can have a participant assigned
- [x] Verify that user account participant assignment changes result in keto

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Sandbox environment for development/testing (central-ledger/keto/user-role service)
- [x] Add wso2is to sandbox environment for development/testing (Rabbit hole, gets it's own task)
- [x] Design api schema 
- [x] Implement endpoints that achieve the functionality of attached diagram
- [x] bdd/integration/unit tests
- [x] CI config for building image

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/role-assignment-service/pull/1

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
![userroles](https://user-images.githubusercontent.com/40144680/131988338-dfebf7a9-0f11-42ea-b491-fb19d83aef2f.png)

**Comment by PaulGregoryBaker** [comment]
Specification link on how to load participants from AdminAPI
[Mojaloop Get \Participants Specification](https://github.com/mojaloop/mojaloop-specification/blob/master/admin-api/admin-api-specification-v1.0.md#get-participants)

**Comment by fugu13** [comment]
The user list (which includes both people and service accounts) will be retrieved from WSO2 Identity Server, and the participant list from the existing API for that purpose. In both cases, a durable permanent identifier should be what is then used as part of the Keto calls.

The list of roles will be hardcoded, and every role should be given a unique identifier that is not a name (a UUID is good, they can be manually generated at this stage) as well as a name.

There will be two Keto namespaces used for calls, `role` and `participant`. The Keto tuples used will be `role:ROLEID#member@USERID` and `participant:PARTICIPANTID#member@USERID` (using the notation used for Keto/Zanzibar, see https://www.ory.sh/keto/docs/concepts/relation-tuples ).

The reuse of the relation "member" is not an issue, each relation is namespace-specific. If there's a preferred terminology for the participant-user relationship other than member, that word can be used instead, and should be documented here.

To retrieve the role or participant list for a particular user, the Query Relation Tuples API will be used ( https://www.ory.sh/keto/docs/reference/rest-api#query-relation-tuples ), and the namespace, relation, and subject provided as parameters. This will provide a list of tuples in the response, with a next page token if there are additional results, and the identifiers for the participants or roles can be read from the resulting tuples.

When a role or participant is added or removed for a user, the create ( https://www.ory.sh/keto/docs/reference/rest-api#create-a-relation-tuple ) and delete ( https://www.ory.sh/keto/docs/reference/rest-api#delete-a-relation-tuple ) relation tuple calls can be used, since only a single tuple is involved at a time. If the call fails, but the failure isn't 4xx, it should be retried a couple times.

**Comment by kleyow** [comment]
Helms charts still need to be made, but I believe other than niche refinements and improvements the acceptence criteria has been addressed. Moving to done.
