### ISSUE TITLE
Operator to assign permissions to roles

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2452]
## **Goal**:
`As a` Technical specialist working for a hub operator
`I want to` change the access permissions associated to a role  
`so that` I can alter the security access that is associated with scheme or hub operator related roles to accommodate changing operations

**Acceptance Criteria**:
- [ ] Verify that permissions can be added and removed from roles
- [ ] Verify that permission changes have corresponding access changes

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Duplicate #2456
