### ISSUE TITLE
Refine contributors guide

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2453]
## **Goal**:
`As a` new contributor to Mojaloop

`I want to` have a contributors guide with guidelines and instructions
  
`so that` I can easily get onboarded and contribute to Mojaloop

**Acceptance Criteria**:
- [x] Contributors guide is refined and shared with new contributors for usage, review and feedback

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] Recommendation of MTP and course details
- [ ] Active work-stream details (links to mojaloop.io)
- [ ] Link to governance structure (DA, CCB, Product Council, Community council, etc)
- [ ] Remove deprecated details
- [ ] Review Sprint schedules

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@elnyry-sam-k you may want to target the docs-2.0 branch for this one, I think it's already been changed over to the new vuepress format: https://docs-preview.moja-lab.live/community/new-contributor-checklist.html

@meekg33k can you point @elnyry-sam-k to the right place in the new docs branch?

**Comment by elnyry-sam-k** [comment]
Sure @lewisdaly ; thank you

**Comment by elnyry-sam-k** [comment]
Updated contributors guide.. However, we need to do this periodically to ensure the guides are up-to-date
