### ISSUE TITLE
Convert Financial V2 Transfer UI into micro-frontend.

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2454]
## **Goal**:
`As a` Hub Operator
`I want to` Trace a transfer end to end 
 `so that` see the status details of the transfer confirm to diagnose unexpected occurrences

**Acceptance Criteria**:
- [x] Verify that the UI code use to trace a transfer in the financial V2 portal is running in a micro-frontend
- [x] Verify that the microfrontend can be configured into the BizOps Framework.

**Complexity**: <Low > 
**Uncertainty**: <Low > 

---

**Tasks**:
- [x] Create `modusintegration/reporting-hub-bop-trx-ui-internal` as interim repo to house microfrontend
- [x] Port UI from financial portal
- [x] Update components to `@modusbox/react-components`
- [x] Verify microfrontend works with shell

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/modusintegration/reporting-hub-bop-trx-ui-internal/pull/1

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
@kleyow can you use this repo: https://github.com/mojaloop/reporting-hub-bop-trx-ui, please let me know if you have any issues (its empty as of now)..

**Comment by kleyow** [comment]
Code merged into https://github.com/modusintegration/reporting-hub-bop-trx-ui-internal per previous talks about holding the code in modusintegration since the org has a vercel plan.

Moving to done.
