### ISSUE TITLE
Migration Guide for Mojaloop Helm Releases

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2455]
## **Goal**:
`As a` deployer of Mojaloop

`I want to` have a guide with migration strategies for Mojaloop Helm Releases
  
`so that` I can have guidance when upgrading existing Mojaloop deployments

**Acceptance Criteria**:
- [x] Migration guide
- [x] Reviewed by community

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Draft Update Strategy Guide
- [x] Review by community
- [x] Incorporate community feedback

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date

## **Pull Requests**:
- [x] https://github.com/mojaloop/documentation/pull/332

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
@elnyry-sam-k I think we should move the task for the release notes to the v13.0.3 release story instead.

Let me know what you think?
