### ISSUE TITLE
Build Kubernetes Role Permission Operator

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2456]
## **Goal**:
`As a` Hub Operator
`I want to` have a method of assigning permissions to roles in a Kubernetes deployment  
`so that` I can adjust to changing role permission requirements, and so that there is a single source of truth for these permissions, and that they affect appropriately

**Acceptance Criteria**:
- [x] Verify that mapped role resources changes notify the role permission operator
- [x] Verify that mapped role resources changes are appropriately passed on to Keto
- [x] Verify that permission can be added to a role
- [x] Verify that permission can be removed from a role

**Complexity**: <Low> 
**Uncertainty**: <Low>

---

**Tasks**:
- [x] Understand the K8S operator concept
- [x] Investigate different ways of building K8S operator using various frameworks
- [x] Develop a PoC for K8S operator that monitors a custom resource like 'mojaloopRole' and maintains the permissions role wise
- [x] Integrate Keto to sync the permissions
- [x] Improve the code structure
- [x] Improve error handling
- [x] Unit tests
- [x] Integration tests
- [x] Enable CICD
- [x] Add documentation about deployment and usage

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/security-role-perm-operator-svc/pull/1
- [x] https://github.com/mojaloop/security-role-perm-operator-svc/pull/3
- [x] https://github.com/mojaloop/security-role-perm-operator-svc/pull/4

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
![rolepermissions](https://user-images.githubusercontent.com/40144680/131974274-29f7f846-ad54-4f8b-bd49-4a8d1ebb64fd.png)

**Comment by PaulGregoryBaker** [comment]
Example resource YML file “roleresource.yaml”

apiVersion: "mojaloop.io/v1"
kind: MojaloopRole
metadata:
  name: arbitrary-name-here
spec:
  # must match what it is used in Keto, whatever that is
  role: RoleIdentifier
  permissions:
  - permission_01
  - permission_02
  - permission_03
  - permission_04

**Comment by fugu13** [comment]
This will be a Kubernetes Operator for a Custom Resource Definition (CRD). The operator could be implemented in most any language; existing Modusbox Operator expertise is mostly based around `kopf`, a python framework, but there are options in Go and Node as well (and others).

CRDs are described at https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/_print/

The operator should maintain a memory of all resources it manages, grouped by role. Kopf's indexing functionality is ideal for this: https://kopf.readthedocs.io/en/latest/indexing/

When a role resource is changed, the list of permissions for that role across all role resources should be compiled, and a change sent through the Keto Patch Multiple Relation Tuples API ( https://www.ory.sh/keto/docs/reference/rest-api#patch-multiple-relation-tuples ) using the patch actions `insert` and `delete`. It is necessary to take all role resources into account, because there may be multiple resources for one role, and more than one may include the same permission, so deleting a role resource that maps Role X to Permission P does not necessarily mean that the Keto tuple for that role-permission connection needs to be deleted, since there may still be another role resource mapping Role X to Permission P.

The Keto tuples will be of the form: `permission:PERMISSIONID#granted@role:ROLEID#member`

The specific operations on resource change are as follows:

1. Retrieve current permissions granted for role using the Query Relation Tuples API https://www.ory.sh/keto/docs/reference/rest-api/#query-relation-tuples
2. Based on stored index of roles to permissions, compute a diff from the retrieved list.
3. Execute patch from diff.
4. If there are problems, throw an exception so the problem will log and a re-sync will be attempted later.
