### ISSUE TITLE
Microfront-end design for RBAC role assignment to users

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2457]
## **Goal**:
`As a` Hub Operator
`I want to` assign/remove role assignments from users, and add/remove participant assignment from users
`so that` maintain the correct authorisation access as the organisation adapts daily, and that each user is correctly assigned to a participant.

**Acceptance Criteria**:
- [ ] Verify that new roles can be added to a user in the design
- [ ] Verify that existing roles can be deleted from a user in the design
- [ ] Verify that new participants can be added to a user in the design
- [ ] Verify that existing participants can be deleted from a user in the design

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Build UX design skeleton [cooper] 
- [x] Build frontend UI following mock ups

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
![userroles](https://user-images.githubusercontent.com/40144680/131987487-1f32f686-47ea-45e0-9b6f-1af43c78bffd.png)

**Comment by PaulGregoryBaker** [comment]
Created new story to complete functionality.
This story has been changed to UI design and POC.

**Comment by PaulGregoryBaker** [comment]
New story #2473
