### ISSUE TITLE
 Helm release v15

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2458]
## **Goal**:
`As a` ML OSS Code base maintainer

`I want to` validate and make a patch release to v15 that is successfully validated by the Golden path tests
  
`so that` Community members can take and use a version of Mojaloop Switch services bundle that is tested and contains the latest features and enhancements such as CGS, etc and bug fixes added in PI-18 through PI-19.

**Acceptance Criteria**:
- [ ] Helm RC v15.0.0 is validated on Moja2 to achieve 100% result with TTK GoldenPath collection
- [ ] QA (Golden path) on deployments done on AWS Moja2 environment is done
- [ ] Bugs are logged based on observations, failures
- [ ] Bugs logged are fixed if critical to make subsequent releases in individual services (or Helm)
- [ ] All the changes needed for supporting v14.0.0 of Helm are done
- [ ] Helm v15.0.0 is released and release notes published
- [ ] Test cases v15.0.0 is published (TTK)
- [ ] TTK tests run successfully as Post-Hook jobs and Tests

**Complexity**: Medium - Involves all core and supporting services

**Uncertainty**: Medium

---

**Tasks**:
- [ ] Make releases on all core services to have latest images / versions [@elnyry-sam-k , @mdebarros]
  - [ ] Need latest ALS release after vulnerabilities (dependabot alerts are addressed)
- [ ] Identify changes needed for helm (config / default.json)
- [ ] Initial PR with changes for v15.0.0
  - [ ] Initial PR review
  - [ ] Deploy, validate, fix issues, redeploy
  - [ ] With stable deployment test Golden path
- [ ] Identify issues with QA Scripts if any - fix them and retest
  - [ ] Update tests for accented characters and other unicode characters (Myanmar script and others)
- [ ] Identify Bugs, log them
- [ ] Fix bugs logged if critical
- [ ] Deploy, validate on AWS Moja2
- [ ] Validate with TTK Mojaloop Simulator collection
- [ ] Validate upgrade scenario if applicable (from previous version)
- [ ] Release notes for helm v15.0.0 drafted
- [ ] Helm v15.0.0 released
- [ ] Review deployment guide documentation to ensure its up-to-date
- [ ] Deployment of released Helm v15.0.0 on **Moja2**
  - [ ] Helm v15.0.0 is deployed on **Moja2** successfully
  - [ ] Validation using Golden path regression tests etc on Moja2
    - [ ] Mojaloop Simulator postman collection
    - [ ] TTK Post-hook install job and Tests
  - [ ] Validation using CGS Golden path regression tests etc on Moja2
    - [ ] Mojaloop Simulator TTK collection
- [ ] Deployment of released Helm v15.0.0 on **Moja1**
  - [ ] Helm v15.0.0 is deployed on **Moja1** successfully
  - [ ] Validation using Golden path regression tests etc on Moja2
    - [ ] Mojaloop Simulator TTK collection
    - [ ] TTK Post-hook install and Tests
  - [ ] Validation using CGS Golden path regression tests etc on Moja2
    - [ ] Mojaloop Simulator TTK collection
    - [ ] TTK Post-hook install and Tests

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Postman (where applicable) Tests pass
- [ ] TTK Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] ...

## **Issues**:
- [ ] ...

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @mdebarros 
- QA/Review: @mdebarros @elnyry-sam-k @vijayg10

**Comment by tdaly61** [comment]
hi @mdebarros , should we add in the versions of kubernetes that this release should function with ?

**Comment by tdaly61** [comment]
Just as an update I am now actively working this , status updates to follow in a few days

**Comment by elnyry-sam-k** [comment]
Thanks @tdaly61 , @mdebarros - rethinking this - we need an Epic for this.. I'll start a conversation with you and @dfry to continue the thinking around this and break it down into manageable, trackable issues..
