### ISSUE TITLE
Helm v14.0.0 PoC

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2459]
## **Goal**:
`As a` ML OSS Code base maintainer

`I want to` define a Helm pattern/example utilizing Helm v3.x best practices/capabilities
  
`so that` the pattern/example can be leveraged for Helm v14.0.0 release

**Acceptance Criteria**:
- [x] A PoC that uses helm v3.x best practices, is available for deployers of Mojaloop (IAC team,  etc) for comments and suggestions

**Complexity**: High

**Uncertainty**: Medium

---

**Tasks**:
- [x] Create repo
- [x] Create common library with re-usable functions/templates across Mojaloop's Helm Charts
- [x] Re-factor existing ML-API-Adapter charts to utilize common library
- [x] Re-factor existing Central-Ledger Prepare Handler chart to utilize common library
- [x] Issues to be addressed:
- [x] [Remove external dependencies that are tightly integrated into the Mojaloop Helm Chart #1852
](https://github.com/mojaloop/project/issues/1852)
    - [x] [Identify and replace deprecated Mojaloop dependant Helm Charts #1969
](https://github.com/mojaloop/project/issues/1969) - _Note: PoC scope is for MySQL and Kafka only_
    - [x] [Mojaloop Helm support for Kubernetes 1.22](https://github.com/mojaloop/project/issues/2352)
    - [x] [Nginx Ingress Controller v1.0.0 is incompatible with Mojaloop Helm v13.0.x releases #2448
](https://github.com/mojaloop/project/issues/2448)
    - [x] [Mojaloop Helm deployments are not compatible when deployed to ARM-arch based hosts #2317
](https://github.com/mojaloop/project/issues/2317)
    - [x] [Helm ingress rules at centralledger/chart-service hardcode ingress values #870
](https://github.com/mojaloop/project/issues/870)
    - [x] [Helm install failing with with "medium to large" release names #2322
](https://github.com/mojaloop/project/issues/2322)
- [x] Gather community feedback
- [x] Incorporate feedback

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Repo being used for this PoC: https://github.com/mojaloop/charts

**Comment by elnyry-sam-k** [comment]
Thanks Miguel..
