### ISSUE TITLE
Design audit logging from Ory Oathkeeper

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2462]
## **Goal**:
`As a` Hub Operator
`I want to` have an audit trail of all operational API calls
`so that` I can identify all historic actions taken when investigating an incident.

**Acceptance Criteria**:
- [x] Verify that API calls that pass through Ory Oathkeeper are logged.
- [ ] Verify that the user can be identified from the logged activity

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Identify how to turn up logging on Oathkeeper
- [x] Ensure logging is sufficient for audit

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
The oathkeeper logs all the requests to stdout and in IaC we are already storing all the logs to elastic search. We can access the logs from oathkeeper through Kibana dashboard and I verfied that. Hence closing the issue.

**Comment by PaulGregoryBaker** [comment]
In the review, the user identifier wasn't in the logs.
A configuration change is necessary. 
Re-opening
