### ISSUE TITLE
[auth-service] - get consent from db, and check credential

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2465]
## **Goal**:
`As a` DFSP

`I want to` be able to use the auth-service to verify a transaction
  
`so that` I can more easily support PISPs

**Acceptance Criteria**:
- [ ] auth service loads a saved consent credential from the database

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] implement getConsent from database
- [x] implement verify transaction with fido2 lib
- [x] unit tests
- [ ] integration tests

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [x] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/auth-service/pull/88
- [x] https://github.com/mojaloop/auth-service/pull/89
- [ ]  https://github.com/mojaloop/auth-service/pull/90

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
