### ISSUE TITLE
Choose control mechanism for modifying Role Resource in the deployment

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2466]
## **Goal**:
`As a` Mojaloop Technical Operations Expert
`I want to` Deploy standard ResourceRole resources files into K8
`so that`  there are the necessary control point in place to manage ongoing changes to these role-permission files

**Acceptance Criteria**:
- [ ] Verify that mechanism chosen can restrict changes to these resources
- [ ] Verify that changes to the resources are logged and can be audited

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
