### ISSUE TITLE
Choose deployment of Micro-service front end mechanism 

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2467]
## **Goal**:
`As a` Mojaloop Technical Operations expert
`I want to` deploy the hub operations UI with a Mojaloop IaC deployment
`so that` access the hub operations UI

**Acceptance Criteria**:
- [ ] Verify that an appropriate JAMstack deployment method is chosen
- [ ] Verify that the deployment tool, method, and approach uses open source tools
- [ ] Verify that the deployment tool, method, and approach is compatible with IaC

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Choose an deployment approach/tool

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
