### ISSUE TITLE
Review MMD project deliverable and identify what can be re-used

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2468]
## **Goal**:
`As a` DFSP participant of a Mojaloop scheme
`I want to` access my settlement and reconciliation reports with RBAC controls  
`so that` only I have access to appropriate information, and that all access is logged

**Acceptance Criteria**:
- [ ] Verify which parts of the current MMD deliverable can be reused.
- [ ] Verify that all the gaps between the MMD deliverable and the BizOps project requirements are identified

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Story details to complete the use the MMD work for completion of this Epic

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
