### ISSUE TITLE
2.4.01.01 Design Fulfill [5]

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#247]
**Goal**:
As a Payee DFSP
_I want to be able to confirm fulfillment of a transfer_
so that the Payer and the switch are informed that I have accepted or rejected the transfer.

**Tasks**:
- [x] Setting up tools (Atom, api-extension, plantuml), communicating details with the
story owner [ @ggrg ]
- [x] Research API Definition document, CentralServices diagrams, sds for Prepare, quick
uml sd review (sd = sequence diagram), PlantUML Language Reference Guide [ @ggrg ]
- [x] Review #213 and refactor to base on it [ @ggrg ]
- [x] Produce a sequence diagram to describe the Fulfill process (success) [ @ggrg ]
- [x] Produce a sequence diagram to describe the Fulfill process (reject) [ @ggrg ]
- [x] Produce a sequence diagram to describe the Timeout process [ @ggrg ]
- [x] Peer review changes [ @mdebarros @ksatya77 @ggrg ]
- [x] Review the aforementioned sequence diagram with Design team
- [x] Publish the design

**Acceptance Criteria**:
- [x] Verify we have a sequence diagram for fulfill process
- [x] Verify we have the architecture diagram is aligned with this process
- [x] Reviewed by the Design Authority
- [x] Updates from Design Authority review

**Dependencies**:
- [x] Review (approvement/rejection) changes of #213 

**Accountability**:
- Owner @mdebarros 
- QA/Review **Design Authority**

**Comment by wdcmb** [comment]
As a Payee DFSP 
I want to be able to confirm fulfillment of a transfer 
so that the Payer and the switch is informed that I have accepted or rejected the transfer
