### ISSUE TITLE
Characterising the performance for this POC

### ISSUE THREAD

**Issue by chris-me-law** [mojaloop/project#2472]
## **Goal**:
`As a` Hub Operator adopting the BizOps RBAC design
`I want to` understand the performance impact of the RBAC
`so that` I can better understand and plan for the cost and functional impact.

**Acceptance Criteria**:
- [x] Verify that there is a measured impact of the change in performance when applying the RBAC security validations.
- [x] Verify that this impact is available in the Business Operations design documents.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Test the performance of RBAC by comparing the reponse times to oathkeeper proxy and directly to API services
- [x] Test the performance of RBAC by enabling RBAC checks in the API services like keto checks in reporting API

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
I have setup the tool locust (https://docs.locust.io/) for tested the role API and transfers API with and without oathkeeper proxy (RBAC checks).
I observed there is 10-15ms difference in response time for RBAC check. I attached the html report for referenc
[Test Report for Business operations framework.pdf](https://github.com/mojaloop/project/files/7463037/Test.Report.for.Business.operations.framework.pdf)
e.

**Comment by elnyry-sam-k** [comment]
Thanks @vijayg10 this looks good; can you also please add where these were observed, locally or on a hosted VM / cluster (and the config in that case)

**Comment by vijayg10** [comment]
Thanks @elnyry-sam-k , I updated my comment with some information about my testing setup

**Comment by fugu13** [comment]
If we're already getting these numbers, it's probably possible to drive it even lower with various caching and affinity options, but we can already see that RBAC time is swamped by variance in these sorts of API calls so I wouldn't put tuning at a high priority

**Comment by vijayg10** [comment]
Reopening this story since the previous results posted were with the keto checks disabled from reporting service. So we want to enabled them and re-test.

**Comment by vijayg10** [comment]
I tested the performance with RBAC checks enabled in the transfers service and observed there is an increase in response time about 40ms when compared to RBAC checks disabled on both service level and in proxy. I think the difference is not with the checks itself, there is an increase in response payload when RBAC check is enabled.
I attached the report here
![perf-report-with-keto-check-in-transfers](https://user-images.githubusercontent.com/33152110/141839565-75d1313f-75b2-432c-b474-bf10bb6ea23f.png)
