### ISSUE TITLE
Complete Role & Permissions assignment to User Microfrontend

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2473]
## **Goal**:
`As a` Hub Operator
`I want to` assign/remove role assignments from users, and add/remove participant assignment from users
`so that` maintain the correct authorisation access as the organisation adapts daily, and that each user is correctly assigned to a participant.

**Acceptance Criteria**:
- [ ] Verify that new roles can be added to a user
- [ ] Verify that existing roles can be deleted from a user
- [ ] Verify that new participants can be added to a user
- [ ] Verify that existing participants can be deleted from a user
- [ ] Verify that access control is removed when an appropriate role is removed from a user
- [ ] Verify that access control is provided when an appropriate role is added to a user

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Integrate frontend with Roles API
- [ ] Integrate front end to Admin API

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
