### ISSUE TITLE
Micro-frontend utility - defining common type between shell and micro frontend

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2475]
## **Goal**:
`As a` Mojaloop Contributor
`I want to` Build a micro-frontend and use or import the shared micro-frontend definitions defined in the library 
`so that`  it more easy to develop without breaking because of the improved type checking.

**Acceptance Criteria**:
- [ ] Verify that the lib is published and available in a public repository like npm.
- [ ] Verify that the micro-frontend boilerplate uses the lib
- [ ] Verity that the shell application uses the lib

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by ivannovazzi** [comment]
Initial versions library are published: https://www.npmjs.com/package/@modusbox/microfrontend-utils
Repo: https://github.com/modusintegration/microfrontend-utils
Github Actions flows for linting, testing, building and publishing are setup.
