### ISSUE TITLE
TTK Provisioning Collection - Parameterise the FspIds

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2477]
**Summary**:
Parameterise the FspIds in provisioning collection and  in GP collection

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Tasks**
- [x] Parameterise the fspIds in provisioning collection
- [x] Parameterise the fspIds in GP collection
- [x] Test with default sim names
- [x] Test with custom sim names

**Pull Requests**
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/50
