### ISSUE TITLE
Mojaloop Helm - Parameterise the fspIds of simulators in TTK environment values of mojaloop helm chart

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2479]
## **Goal**:
`As a` Hub operator

`I want to` change the simulator names in TTK environment configuration through the helm values file
  
`so that` I can deploy the simulators with customized names and run TTK setup and GP collections

**Acceptance Criteria**:
- [x] The simulator names can be changed easily in mojaloop helm values file

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Modify TTK chart to replace the parameters in extra-environment object
- [x] Modify TTK CLI chart to handle the same functionality
- [x] Deploy mojaloop with default sim names and test GP through UI
- [x] Deploy mojaloop with custom sim names and test GP through UI
- [x] Test Setup and GP with helm test command

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/450

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
