### ISSUE TITLE
2.4.80.02 Add tests that test the DAO for the PrepareHandler [13]

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#248]
**Goal**:
As a developer I want to
__add unit and integration tests for all functionalities related to the PrepareHandler__
so that we can be sure everything is working as expected.

**Tasks**:
- [x] Add **Unit** tests for the following tables:
  - [x] transfer read model __[ @vgenev, @bothadeon ]__
  - [x] transferStateChange __[ @vgenev ]__
  - [x] transferState __[ @nikolayanastasov ]__  
  - [x] ilp  __[ @nikolayanastasov ]__
  - [x] extension __[ @vgenev ]__
  - ~currency~ (Not applicable)
  - [x] participant model __[ @vgenev, @bothadeon]__
  - [x] participant service __[ @vgenev ]__
- [x] Add **Integration** tests for the following tables:
  - [x] transfer read model __[ @vgenev ]__
  - [x] transferStateChange __[ @vgenev ]__
  - [x] ilp  __[ @nikolayanastasov ]__
  - [x] transferState __[ @mdebarros ]__
  - [x] extension __[ @vgenev ]__
  - ~currency~ (Not applicable)
  - [x] participant model __[ @vgenev ]__
  - [x] participant service  __[ @vgenev ]__
- [x] Fix any issues that the tests uncover
- [x] Fix all unit tests if integration tests causes model or service (where applicable) change
- [x] Create **Helper Module** backbone for inserting a test data into the actual database, and use it into the **Integration** tests __[@nikolayanastasov]__
- [x] Code Review __[ @vgenev ]__
- [x] **Test coverage** of tests to make sure 100% or >90% coverage
  - [x] transfer read model __[@bothadeon]__
  - [x] transferStateChange  __[ @vgenev ]__
  - [x] transferState __[ @nikolayanastasov ]__                       
  - [x] ilp  __[ @nikolayanastasov, @vgenev ]__
  - [x] extension __[ @vgenev ]__
  - ~currency~ (Not applicable)
  - [x] participant model __[ @vgenev, @bothadeon]__
  - [x] participant service __[ @vgenev ]__
- [x] Refactor ILP data access model, its unit and integration tests and get 100% coverage __[ @vgenev ]__

**Acceptance Criteria**:
- [x] Unit tests are available for the following tables:
  - [x] transfer
  - [x] transferStateChange
  - [x] transferState
  - [x] ilp
  - [x] extension
  - ~currency~ (Not applicable)
  - [x] participant
- [x] Integration tests are available for the following tables:
  - [x] transfer
  - [x] transferStateChange
  - [x] transferState
  - [x] ilp
  - [x] extension
  - ~currency~ (Not applicable)
  - [x] participant
- [x] Create **Helper Module** for inserting a test data into the actual database, and use it into the **Integration** tests __[@nikolayanastasov]__
- [x] **Test coverage** of tests to make sure 100% or >90% coverage
  - [x] transfer read model __[@bothadeon]__
  - [x] transferStateChange 
  - [x] transferState __[ @nikolayanastasov ]__
  - [x] ilp  __[ @nikolayanastasov ]__
  - [x] extension __[ @vgenev ]__
  - ~currency~ (Not applicable)
  - [x] participant model __[ @vgenev, @bothadeon]__
  - [x] participant service __[ @vgenev , @bothadeon]__

**Dependencies**:
- [x] #211 
- [ ] #262 (for Integration tests)

**Accountability**
- Owner @vgenev 
- Review

**Comment by mdebarros** [comment]
Proof for Integration Test for TransferState:
```
/usr/local/opt/node@8/bin/node --inspect-brk=49937 /Users/mdebarros/Documents/ModusDocs/Projects/MojaLoop/git/fork/central-ledger/test/integration/domain/transfer/models/transferState.js
Debugger listening on ws://127.0.0.1:49937/5d82ca49-2c2a-4a87-a5d3-9569ecfc6b0e
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
TAP version 13
# transferState Model Test
# setup
not ok 1 (unnamed assert)
  ---
    operator: fail
    at: Test.transferStateTest.test (/Users/mdebarros/Documents/ModusDocs/Projects/MojaLoop/git/fork/central-ledger/test/integration/domain/transfer/models/transferState.js:85:14)
  ...
# saveTransferState List
(node:11285) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'insert' of undefined
(node:11285) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11285) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'insert' of undefined
(node:11285) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'insert' of undefined
(node:11285) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): TypeError: Cannot read property 'insert' of undefined
(node:11285) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): TypeError: Cannot read property 'insert' of undefined
not ok 2 test exited without ending
  ---
    operator: fail
  ...

1..2
# tests 2
# pass  0
# fail  2

Waiting for the debugger to disconnect...

Process finished with exit code 1
```

**Comment by vgenev** [comment]
unit and integration tests for participants are ok and passing
