### ISSUE TITLE
Central-ledger migration scripts should configure the Quote Party table to utf8 character set

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2480]
## **Goal**:
`As a` Mojaloop Installation Upgrader

`I want to` have the existing Central-Ledger Migration scripts update the Quoting Party table to utf8 character set encoding
  
`so that` upgrades from Mojaloop Helm releases v13.0.1 to v13.0.2 are seamless

_Note: this is a follow up to [#2471: Quoting service (in persistence mode) having storage issues for Unicode characters](https://github.com/mojaloop/project/issues/2471#issuecomment-917089800)._

**Acceptance Criteria**:
- [x] Central-ledger migration scripts must upgrade the `Party` table with the following characteristics:
    -  character-set: utf8mb4
    -  collation: utf8mb4_unicode_ci

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Add new migration script to alter `Party` table to convert character-set to UTF8

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/862

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
