### ISSUE TITLE
FSPIOP Interop API BC - Ref Arch Documentation

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#2483]
## **Goal**:
`As a` stakeholder

`I want to` be able to consult the Reference Architecture documentation regarding the Bounded Context "FSPIOP Interop API"
  
`so that` I can better understand the BC use cases and it's relation with the rest of the Reference Architecture

**Acceptance Criteria**:
- [ ] TBD

---

**Tasks**:
- [x] Write documentation [ @JohannWNel ]
- [ ] Review documentation [ @elnyry-sam-k ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/reference-architecture-doc/pull/29

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
