### ISSUE TITLE
Participant Lifecycle BC - Ref Arch Documentation

### ISSUE THREAD

**Issue by JohannWNel** [mojaloop/project#2485]
## **Goal**:
`As a` stakeholder

`I want to` be able to consult the Reference Architecture documentation regarding the Bounded Context "Participant Lifecycle"
  
`so that` I can better understand the BC use cases and it's relation with the rest of the Reference Architecture

**Acceptance Criteria**:
- [ ] TBD

---

**Tasks**:
- [x] Write documentation [ @JohannWNel ]
- [x] Review documentation [@elnyry-sam-k ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/reference-architecture-doc/pull/17

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @JohannWNel 
- QA/Review: TBC
