### ISSUE TITLE
FSPIOP Interop API TEST - Ref Arch Documentation

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#2486]
## **Goal**:
`As a` stakeholder

`I want to` be able to consult the Reference Architecture documentation regarding the Bounded Context "FSPIOP Interop API"
  
`so that` I can better understand the BC use cases and its relation with the rest of the Reference Architecture

**Acceptance Criteria**:
- [ ] TBD

---

**Tasks**:
- [ ] Write documentation [ @JohannWNel ]
- [ ] Review documentation [ @elnyry-sam ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by JohannWNel** [comment]
Closed due to being duplicates that were created.
