### ISSUE TITLE
Logging BC - Ref Arch Documentation

### ISSUE THREAD

**Issue by JohannWNel** [mojaloop/project#2487]
## **Goal**:
`As a` stakeholder

`I want to` be able to consult the Reference Architecture documentation regarding the Bounded Context "Logging"
  
`so that` I can better understand the BC use cases and it's relation with the rest of the Reference Architecture

**Acceptance Criteria**:
- [ ] TBD

---

**Tasks**:
- [x] Write documentation [ @JohannWNel ]
- [x] Review documentation [ @mdebarros  ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/reference-architecture-doc/pull/30

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- BC Owner: TBC
- Document Writer: @JohannWNel 
- QA/Review: @mdebarros
