### ISSUE TITLE
Notifications BC - Ref Arch Documentation

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2489]
## **Goal**:
`As a` stakeholder

`I want to` be able to consult the Reference Architecture documentation regarding the Bounded Context "Notifications"
  
`so that` I can better understand the BC use cases and it's relation with the rest of the Reference Architecture

**Acceptance Criteria**:
- [ ] TBD

---

**Tasks**:
- [x] Write documentation [ @mdebarros ]
- [x] Review documentation [ @pedrosousabarreto ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by pedrosousabarreto** [comment]
Looks good,
Only one suggestion regarding the Alert Notification use cases at the bottom, maybe we should use a have different external component than a DFSP, like an operator for example.

I've added an example on Miro; https://miro.com/app/board/o9J_lJyA1TA=/?openComment=3074457364537612756
