### ISSUE TITLE
Transfers & Transactions - Ref Arch Documentation

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2490]
## **Goal**:
`As a` stakeholder

`I want to` be able to consult the Reference Architecture documentation regarding the Bounded Context "Transfers & Transactions"
  
`so that` I can better understand the BC use cases and it's relation with the rest of the Reference Architecture

**Acceptance Criteria**:
- [ ] TBD

---

**Tasks**:
- [x] Write documentation [ @mwmentor  ]
- [x] Review documentation [ @mdebarros  ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
@pedrosousabarreto I am happy to close this after merging some minor typo changes in this PR: https://github.com/mojaloop/reference-architecture-doc/pull/36
