### ISSUE TITLE
Agreements/Quoting BC - Ref Arch Documentation

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2491]
## **Goal**:
`As a` stakeholder

`I want to` be able to consult the Reference Architecture documentation regarding the Bounded Context "Agreements/Quoting"
  
`so that` I can better understand the BC use cases and it's relation with the rest of the Reference Architecture

**Acceptance Criteria**:
- [ ] TBD

---

**Tasks**:
- [x] Write documentation [ @mwmentor  ]
- [x] Review documentation [ @elnyry-sam-k, @mdebarros  ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
@pedrosousabarreto added some changes to my review PR --> https://github.com/mojaloop/reference-architecture-doc/pull/36
