### ISSUE TITLE
3rd Party Initiated Payments BC - Ref Arch Documentation

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2493]
## **Goal**:
`As a` stakeholder

`I want to` be able to consult the Reference Architecture documentation regarding the Bounded Context "3rd-Party Initiated Payments BC"
  
`so that` I can better understand the BC use cases and it's relation with the rest of the Reference Architecture

**Acceptance Criteria**:
- [ ] TBD

---

**Tasks**:
- [ ] Write documentation [ @mwmentor  ]
- [ ] Review documentation [ @lewisdaly ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@mwmentor is this one completed now?

**Comment by mwmentor** [comment]
@lewisdaly - yes, this is how I worded it:
`Description
The workflow provided by this UC enables the Switch to handle instances in which a DFSP Account Holder responds to a Consent Request received from an authorised and authenticated PISP User. The DFSP Account Holder issues a request to the PISP via the Switch for the PISP User to create an identifying Credential on their device. Upon receipt of the identifying Credential, verified by the issuing DFSP Account Holder, both the Switch and the DFSP Account Holder Account records are updated with the PISP User Credential and linked Accounts, and the PISP User is notified that their DFSP Account Holder Account/s has/have been successfully linked to their PISP profile.

Note: The Consent Issue is in response to a Consent Request made by an authorised PISP User to link one or more of their DFSP Account Holder Accounts to their PISP profile and follows the workflow noted in the PISP Consent Request UC above`

Please let me know if you're happy with that.  Thanks.

**Comment by lewisdaly** [comment]
Yeah looks good to me.

**Comment by mwmentor** [comment]
Thanks @lewisdaly - have a good night :-)
