### ISSUE TITLE
Accounts & Balances BC - Ref Arch Documentation

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#2496]
## **Goal**:
`As a` stakeholder

`I want to` be able to consult the Reference Architecture documentation regarding the Bounded Context "Accounts & Balances"
  
`so that` I can better understand the BC use cases and its relation with the rest of the Reference Architecture

**Acceptance Criteria**:
- [ ] TBD

---

**Tasks**:
- [x] Write documentation in VuePress Format[ @mwmentor  ]
- [ ] Review documentation [ Jasons? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
