### ISSUE TITLE
Account Lookup & Discovery BC - Ref Arch Documentation

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#2498]
## **Goal**:
`As a` stakeholder

`I want to` be able to consult the Reference Architecture documentation regarding the Bounded Context "Account Lookup and Discovery" so that I can better understand the BC use cases and its relation with the rest of the Reference Architecture

**Acceptance Criteria**:
- [ ] TBD

---

**Tasks**:
- [x] Write documentation in VuePress Format[ @ ]
- [ ] Review documentation [ @MichaelJBRichards  ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mwmentor** [comment]
I am kicking off this BC whilst I wait for some queries to be answered regarding the other BCs that I am currently working on.
