### ISSUE TITLE
Reporting BC - Ref Arch Documentation

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#2500]
## **Goal**:
`As a` stakeholder

`I want to` be able to consult the Reference Architecture documentation regarding the Bounded Context "Reporting"
  
`so that` I can better understand the BC use cases and its relation with the rest of the Reference Architecture

**Acceptance Criteria**:
- [ ] TBD

---

**Tasks**:
- [ ] Write documentation in VuePress Format[ @ ]
- [ ] Review documentation [ @ ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/reference-architecture-doc/pull/35

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by pedrosousabarreto** [comment]
Initial version done, see PR: https://github.com/mojaloop/reference-architecture-doc/pull/35
