### ISSUE TITLE
ALS subid error callback endpoint not implemented (PUT /parties/{TYPE}/{ID}/{SubId}/error)

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2505]
## **Goal**:
`As a` scheme using sub identifiers as part of lookup (Account lookup service (ALS) )

`I want to` support error callbacks on subid endpoints
  
`so that` support ALS for subids (and error callbacks on those)

**Acceptance Criteria**:
- [x] ALS supports SubId error callbacks for `PUT parties/{Type}/{ID}/{SubId}/error`

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Implementation to support errors on SubId endpoints in ALS

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/account-lookup-service/pull/429
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/52

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Notes**:
Review: https://github.com/mojaloop/account-lookup-service/blob/master/src/handlers/parties/%7BType%7D/%7BID%7D/%7BSubId%7D/error.js

**Comment by mdebarros** [comment]
[TTK-Assertion-Report-multi-2021-09-28T15_16_57.947Z.html.zip](https://github.com/mojaloop/project/files/7245507/TTK-Assertion-Report-multi-2021-09-28T15_16_57.947Z.html.zip)

Total GP results for PR merged in master: https://github.com/mojaloop/testing-toolkit-test-cases/pull/52

![Screenshot 2021-09-28 at 17 29 43](https://user-images.githubusercontent.com/11392873/135118217-d4c4e645-840d-46d6-813d-9f2a0e39c1e4.png)

New  test-case results added from the above PR: `p2p_money_transfer - p2p_unhappy_path with invalid subID at PayeeFSP` 
![Screenshot 2021-09-28 at 17 29 32](https://user-images.githubusercontent.com/11392873/135118239-b3f4ca3a-12d5-4c69-8d41-0540edbb4ea2.png)

**Comment by mdebarros** [comment]
@elnyry-sam-k I think we can close this issues, see previous post.

**Comment by elnyry-sam-k** [comment]
Great, thanks Miguel @mdebarros
