### ISSUE TITLE
Add Combined RBAC POC to IaC

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2508]
## **Goal**:
`As a` Tech Operational Support Engineer working for the Hub
`I want to` Deploy Mojaloop with the combined RBAC solution
`so that` access to the hub operations have RBAC authentication, authorisation and can be audited.

**Acceptance Criteria**:
- [x] Verify that the IaC Mojaloop is deployed and golden path tests pass
- [x] Verify that that the RBAC Implementation is in place ... need to elaborate on this more
- [x] Verify that the backend services are protected by the RBAC
- [x] Verify that the frontend services are working properly
- [x] Verify that the default Role and permissions can be configured in IaC in a pipeline
- [x] Verify that the Oathkeeper Inbound logs are stored and available in AWS (for an audit) with User information.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Add dependency services to the IaC
- [x] Add Bof Services to the IaC
- [x] ~~Configure current IaC WS02 with Bof~~ (Using current WSO2 seems not possible for now)
- [x] Create new WSO2 ISKM for BOF
- [x] Test the BOF login flow with new WSO2 configured manually
- [x] Automate WSO2 service provider configuration for BOF
- [x] Implement start-up script to assign admin role to default WS02 Admin user
- [x] Create standardised custom resource from role-permissions
- [x] Add above custom resource to IaC with Git Lab deploy - in it's own pipeline
- [x] Configure Logstash to store Oathkeeper logs
- [x] Build Values file for terraform (David F)
- [x] Generate secrets 
   - not sure on the details of this, but all options are well understood
- [x] Build list of Ingress endpoints. 
- [x] Add Ingress endpoints to current IaC deployment (through wireguard VPN) (David F)
- [x] Few automations
  - [x] Create a service provider
  - [x] Create Oauth/OpenID Connect Configuration in Inbound Authentication Configuration
  - [x] Propagate the client key and client secret and provided that in kratos config map
  - [x] Add claim configuration (fullname and email address as mandatory claims in "Request claims" and userid as subject claim)
  - [x] Automate changing the Identity Provider Entity ID value to 'https://iskmssl.dev.infra.mojatest.live:7443/oauth2/token' in OAuth2 config
  - [x] Automate user creation for bizops iskm based on workbench-config
  - [x] Automate creation of portaladmin user for bizops iskm
  - [x] Automatic assignment of admin role to the portaladmin user through Keto API
  - [x] Separate pipeline for role permission resources update
  - [x] Storing Oathkeeper logs somewhere (Like AWS cloudwatch or something)
- [x] Raise a question about using self signed certificates in Kraos / Github ODC implementation
- [x] Try to change oathkeeper logging to json and the UUID should be exposed

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
I have raised a question regarding self signed certficates in Ory forum and got a reasonable reply.

> Hello everyone, I am trying to configure kratos with selfservice method OIDC with generic provider configuration.
I made everything work with an identity server hosted with SSL certificate from trusted authority (I used Let'sencrypt).
The problem is the whole solution is not working if I host the identity server with a self signed certificate. I couldn't find a way to provision the list of trusted authorities (CAs) in kratos config.
The error I am getting from kratos is like 'Self signed certificate found while discovery"
Can anybody suggest on this?

> I assume you’re running Kratos from the official docker image. I think the best solution would be to add your self-signed certificate like suggested on StackOverflow. This would mean that you create your own kratos image with a self-signed certificate added to trusted certificates.
The other option would be to modify kratos to accept TLS verification which would bypass the certificate but this is bad from a security perspective, plus you would still have to create a docker image based on the modified code. Option #1 sounds better :slightly_smiling_face:

**Comment by vijayg10** [comment]
Oathkeeper logs are tested and we can set the log level to 'warning' and all the allowed and denied requests can be seen in the Kibana dashboard. Below is a screenshot of some logs

![Screenshot 2021-11-16 at 11 34 59 PM](https://user-images.githubusercontent.com/33152110/142041222-9b3ae6b8-19e0-44e5-9853-aa09b7dfbbe9.png)
