### ISSUE TITLE
Event-stream-process on startup should configure the mojaloop_template if and only if it doesn't already exist

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2509]
## **Goal**:
`As a` Hub Deployer

`I want to` have the Event-Stream-Processor automatically configure the [mojaloop_template](https://github.com/mojaloop/event-stream-processor/blob/master/config/template-mojaloop.json) on startup
  
`so that` ElasticSearch will index events properly, and remove any uncertainty on template management going forward

**Acceptance Criteria**:
- [ ] ESP on startup checks to see if the [mojaloop_template](https://github.com/mojaloop/event-stream-processor/blob/master/config/template-mojaloop.json) has been loaded
- [ ] ESP creates the [mojaloop_template](https://github.com/mojaloop/event-stream-processor/blob/master/config/template-mojaloop.json) if the template is not found

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Closing this as its a duplicate of https://github.com/mojaloop/project/issues/1997
