### ISSUE TITLE
TTK - Implement threading model for Testcase execution

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2510]
## **Goal**:
`As a` individual implementer

`I want to` have the Stop option in the test runner to be more responsive
  
`so that` I can stop the test case execution immediately whenever I want

**Acceptance Criteria**:
- [ ] The Stop button in test runner should be more responsive. The testrun should be stopped immediately irrespective of the state of the execution.

**Complexity**: High

**Uncertainty**: Medium

---

**Tasks**:
- [ ] Investigate different approaches to have stop option more responsive
  - We can create a worker thread for each execution and kill it whenever we want irrespective of the state of the execution
  - [ ] Tried the worker thread approach and made some progress (WIP PR included)
- [ ] Investigate if there are better threading mechanisms also suitable for parallel testcase execution (Ex: with iteration runner)

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/ml-testing-toolkit/pull/191

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
