### ISSUE TITLE
Create helm chart for Reporting BC

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2512]
## **Goal**:
`As a` Hub Operator
`I want to` deploy the reporting bounded context onto my Mojaloop hub
`so that` I can access the reporting BC functionality to support my hub business processes.

**Acceptance Criteria**:
- [ ] Verify that the helm chart deploys the Graph QL backend API
- [ ] Verify that the helm chart deploys the event reporting DB
- [ ] Verify that the hem chart deploys the replica reporting DB that clones the Mojaloop central-ledger DB
- [ ] Verify that the helm chart deploys the Event processor.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Identify how the central-ledger DB is currently replicated in MMD
- [ ] 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
