### ISSUE TITLE
Completing the Micro-Frontend to trace a transfer

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2513]
## **Goal**:
`As a` Hub Operator 
`I want to` a trace a transfer end to end including settlement
 `so that` I can trace unexpected behaviours that affected an individual transfer

The Micro frontend that was refactored from the Financial Portal V2 need to be completed and make to query the Graph QL API
Need a UI design.

**Acceptance Criteria**:
- [ ] Verify that all the four use cases are implemented 
- [ ] Verify that the Reporting BC graphQL API is used to supply the data for this ui.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
This is a duplicate. 
Refer to original story #2422.
Closing
