### ISSUE TITLE
Provide helm chart for Microfrontends JAMStack UI

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2514]
## **Goal**:
`As a` Hub operator
`I want to` deploy the BizOps framework UI
 `so that` I can use the UI to support my business processes

**Acceptance Criteria**:
- [ ] Verify that the helm chart deploys the Micro frontend shell application 
- [ ] Verify that the helm chart deploys the User Role micro-frontend
- [ ] Verify that the helm chart deploys the micro frontend that enables the tracing of a transfer.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Image scan and licence scan errors - disabled currently
