### ISSUE TITLE
Add Mojaloop styling to the microfront end shell application

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2515]
## **Goal**:
`As a` hub operator
`I want to` the Biz Ops framework to look like it belongs the Mojaloop
`so that` it support the Mojaloop brand.

**Acceptance Criteria**:
- [x] Verify that the Mojaloop styling that has been adopted in the Financial portal Version 2 is displayed in the BizOps framework shell applicaiton

**Complexity**: <High|Medium|Low> > Low

**Uncertainty**: <High|Medium|Low> > Low
---

**Tasks**:
- [x] Duplicate shell boilerplate to Bizop's specific shell
- [x] Copy finance portal UI over to microfrontend-shell-boilerplate

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/reporting-hub-bop-shell/pull/1

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
