### ISSUE TITLE
Add type definitions for Central Services Logger to be used in typescript services

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2516]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` <action>
  
`so that` <reason> 

**Acceptance Criteria**:
- [x] Type definitions are available for Central Services Logger
- [x] Typescript services can use central services logger without any workarounds

**Complexity**: Low
**Uncertainty**: Low

---

**Tasks**:
- [x] Add type definitions for Central Services Logger to be used in typescript services

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-logger/pull/35

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
