### ISSUE TITLE
2.4.90.50.01 Implement EventLogging in Kafka Framework

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#252]
**Goal**:
As a technical operator
_I want to be able to record events to an events topic_
so that they can be used in the future for diagnostics

**Tasks**:
- [ ] Enhance current "common streaming library" to implement event logging
- [ ] Update the version of central-services-shared in central services so that it contains the event logging functionality
- [ ] Add Unit tests
- [ ] Add Integration tests

**Acceptance Criteria**:
- [ ] Kafka consumers would log events based on log level (INFO, DEBUG, ERROR, PERF) to an event logging topic
- [ ] Unit tests are available
- [ ] Integration tests are available

**Dependencies**:
- None currently

**Accountability**:
- Owner 
- QA/Review

**Comment by elnyry** [comment]
Two new stories (#238, #262 ) were added to this Sprint as they were needed for the stories currently in the Sprint to be completed (these were not planned-for earlier). So, moving this out to 2.4

**Comment by elnyry** [comment]
Covered as part of #765
