### ISSUE TITLE
Scan ML Helm 13.0.2 Code Packages (Manually)

### ISSUE THREAD

**Issue by rasputtintin** [mojaloop/project#2520]
## **Goal**:
`As a` CQS Security Officer

`I want to` scan the ML Helm 13.0.2 Code Packages
  
`so that` I can document identified vulnerabilities for resolution by the development team.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Scan the code packages in Helm 13.0.2 [ @rasputtintin ]
- [ ] Document vulnerabilities [ @rasputtintin ]

**Done**
- [ ] Acceptance Criteria pass

- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
