### ISSUE TITLE
[sdk-scheme-adapter] - API resource names and docs for `/requestToPay` and `requestToPayTransfer` are unclear

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2521]
## **Goal**:
`As a` DFSP

`I want to` use the Mojaloop SDK
  
`so that` integration to Mojaloop's Async API is made easier

**Acceptance Criteria**:
- [ ] improved swagger documentation for https://github.com/mojaloop/sdk-scheme-adapter/blob/master/src/OutboundServer/api.yaml and perhaps better resource names

**Complexity**: Low

**Uncertainty**: Low

---

I'm currently building out a Merchant Request to Pay guide on the Mojaloop Sandbox.
I ran into problems where the API is very unclear for what resources the Payee and Payer should use
to kick off the `/transactionRequests` flow

**Tasks**:
- [ ] Change (in a backwards compatible nature)  the  `/requestToPay` and `requestToPayTransfer`  to something easier to read
- [ ] update the swagger documentation to remove unclear copy pasted references

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/2521?planning-poker) with Zenhub @PaulGregoryBaker @vijayg10
