### ISSUE TITLE
Reporting event processor - Standardisation to align with other mojaloop services

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2523]
## **Goal**:
`As a` Hub operator

`I want to` have the service reporting event processor aligned with other mojaloop services
  
`so that` I can use this with mojaloop standards

**Acceptance Criteria**:
- [ ] Verify proper logging with different verbosity levels by mojaloop/central-services-logger
- [ ] Verify the service can be configured using JSON file or environment variables as offered by 'rc' library
- [ ] Verify the docker image can be built and run properly
- [ ] Verify the CICD process is working for PRs and releases (Test, build & publish)

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Implement Logger by using https://github.com/mojaloop/central-services-logger
- [ ] Configuration by npm library 'rc' (Ref https://github.com/mojaloop/security-role-perm-operator-svc/blob/master/src/shared/config.ts)
- [ ] Prepare docker file
- [ ] Implement CICD

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
