### ISSUE TITLE
Helm release v13.1.0

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2528]
## **Goal**:
`As a` ML OSS Code base maintainer

`I want to` validate and make the release v13.1.0 that is successfully validated by the Golden path tests
  
`so that` Community members can take and use a version of Mojaloop Switch services bundle that is tested and contains the latest features enhancements and bug fixes added in PI-15/PI-16.

**Acceptance Criteria**:
- [x] Helm RC v13.1.0 is validated on Moja2 to achieve 100% result with TTK GoldenPath collection
- [x] Helm RC v13.1.0 is validated with PISP provisioning and test collections (TTK) with 100%
- [x] QA (Golden path) on deployments done on AWS Moja2 environment is done
- [x] Bugs are logged based on observations, failures
- [x] Bugs logged are fixed if critical to make subsequent releases in individual services (or Helm)
- [x] All the changes needed for supporting v13.1.0 of Helm are done
- [x] Helm v13.1.0 is released and release notes published
- [x] Test cases v13.1.0 is published (TTK)
- [x] TTK tests run successfully as Post-Hook jobs and Tests

**Complexity**: Medium - Involves all core and supporting services

**Uncertainty**: Low (no new features, enhancements, only two fixes)

---

**Tasks**:
- [x] Initial PR with changes for v13.1.0
  - [x] Initial PR review
  - [x] Deploy, validate, fix issues, redeploy
  - [x] With stable deployment test Golden path
- [x] Validate PISP test provisioning and test collections (TTK) 
- [x] Identify issues with QA Scripts if any - fix them and retest
  - [x] Update tests for v1.1 patch notification scenarios
- [x] Identify Bugs, log them
- [x] Fix bugs logged if critical
- [x] Deploy, validate on AWS Moja2
- [x] Validate with TTK GP collection
- [x] TTK test-cases repo v13.1.0 is published
- [x] Validate upgrade scenario (to v13.1.0) from v13.0.2
- [x] Release notes for helm v13.1.0 drafted
- [x] Update release notes with Upgrade Strategy Guide link
- [x] Helm v13.1.0 released
- [x] Review deployment guide documentation to ensure its up-to-date
- [x] Deployment of released Helm v13.1.0 on **Moja2**
  - [x] Helm v13.1.0 is deployed on **Moja2** successfully
  - [x] Validation using Golden path regression tests etc on Moja2
    - [x] TTK GP collection
    - [x] TTK Bulk collection
    - [x] TTK TP collection
    - [x] TTK Cron-job
  - [x] Validation using CGS Golden path regression tests etc on Moja2
- [x] Deployment of released Helm v13.1.0 on **Moja1**
  - [x] Helm v13.1.0 is deployed on **Moja1** successfully
  - [x] Validation using Golden path regression tests etc on Moja1
    - [x] TTK GP collection
    - [x] TTK Bulk collection
    - [x] TTK TP collection
  - [x] Validation using CGS Golden path regression tests etc on Moja1

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] TTK Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/455

**See release notes for the full list**: https://github.com/mojaloop/helm/blob/v13.1.0/.changelog/release-v13.1.0.md

## **Issues**:
**See release notes for the full list**: https://github.com/mojaloop/helm/blob/v13.1.0/.changelog/release-v13.1.0.md

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @mdebarros 
- QA/Review: @mdebarros @elnyry-sam-k @vijayg10

**Comment by tdaly61** [comment]
so @elnyry-sam-k  @mdebarros : Do I understand this correctly, what you want me to do pretty much comes down to testing 13.0.2 in mini-loop and make sure all the GP tests work with the TTK ?

**Comment by lewisdaly** [comment]
@mdebarros @elnyry-sam-k how do I go about helping with the Third Party stuff? #2533 is now in review, with a PR to update the deployment guide

**Comment by elnyry-sam-k** [comment]
Thanks @lewisdaly ; once we get started on this story, will need your support to ensure 3ppi services are deployed correctly and we can correctly use the 3p provisioning and test collections to get 100% pass-rate :-).. 

We want to include #2530 , #2556 in 13.1.0, so you can say this is blocked on those. those are prioritized as next items.. if you have bandwidth, can you help us with #2556 ? :-)

**Comment by lewisdaly** [comment]
I may be able to - where is most of the work? In the ml-api-adapter and central-ledger I guess?

**Comment by elnyry-sam-k** [comment]
Yes thats correct @lewisdaly ; we can have a quick chat about that if you're ready..

**Comment by lewisdaly** [comment]
Sure. I'll try and be on the sprint status check in today and we can discuss at the end of that maybe.

**Comment by elnyry-sam-k** [comment]
Blocked on #2660

**Comment by mdebarros** [comment]
Moja2 test results:

Golden-path: https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-03-14T15%3A41%3A16.818Z.html
Bulk: https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-03-14T15%3A41%3A53.292Z.html
Thirdparty: https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-03-14T15%3A42%3A32.808Z.html

Default tests passed:
- default install (gp, bulk, tp) of v13.1.0-13299.d9e9fe1
- default upgrade from v13.0.1 to v13.1.0-13299.d9e9fe1 (gp, bulk, tp)

**Comment by mdebarros** [comment]
**Moja1 Test Results**

Environment: moja1.test.mojaloop.live

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP Tests
Environment: moja1.test.mojaloop.live
Total assertions: 2535
Passed assertions: 2535
Failed assertions: 0
Total requests: 577
Total test cases: 128
Passed percentage: 100.00%
Started time: Mon, 14 Mar 2022 16:58:41 GMT
Completed time: Mon, 14 Mar 2022 17:01:46 GMT
Runtime duration: 184989 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-03-14T17%3A01%3A46.792Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Bulk Tests
Environment: moja1.test.mojaloop.live
Total assertions: 183
Passed assertions: 183
Failed assertions: 0
Total requests: 17
Total test cases: 4
Passed percentage: 100.00%
Started time: Mon, 14 Mar 2022 17:01:59 GMT
Completed time: Mon, 14 Mar 2022 17:02:23 GMT
Runtime duration: 24035 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-03-14T17%3A02%3A23.816Z.html)

```
esting Toolkit Report
Test Result: PASSED
Test Suite: Thirdparty Tests
Environment: moja1.test.mojaloop.live
Total assertions: 21
Passed assertions: 21
Failed assertions: 0
Total requests: 20
Total test cases: 8
Passed percentage: 100.00%
Started time: Mon, 14 Mar 2022 17:03:08 GMT
Completed time: Mon, 14 Mar 2022 17:03:13 GMT
Runtime duration: 4627 ms
```
View Report - link missing due to misconfiguration. [Slack Announcement](https://mojaloop.slack.com/archives/CG3MAJZ5J/p1647277393196329)


```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP CronJob
Environment: moja1.test.mojaloop.live
Total assertions: 2535
Passed assertions: 2535
Failed assertions: 0
Total requests: 577
Total test cases: 128
Passed percentage: 100.00%
Started time: Tue, 15 Mar 2022 08:00:12 GMT
Completed time: Tue, 15 Mar 2022 08:03:17 GMT
Runtime duration: 185249 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-03-15T08%3A03%3A17.989Z.html)

**Comment by mdebarros** [comment]
Moja 2 Test Results

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP Tests
Environment: moja2.test.mojaloop.live
Total assertions: 2535
Passed assertions: 2535
Failed assertions: 0
Total requests: 577
Total test cases: 128
Passed percentage: 100.00%
Started time: Mon, 14 Mar 2022 16:06:49 GMT
Completed time: Mon, 14 Mar 2022 16:10:02 GMT
Runtime duration: 192703 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-03-14T16%3A10%3A02.264Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Bulk Tests
Environment: moja2.test.mojaloop.live
Total assertions: 183
Passed assertions: 183
Failed assertions: 0
Total requests: 17
Total test cases: 4
Passed percentage: 100.00%
Started time: Mon, 14 Mar 2022 16:10:17 GMT
Completed time: Mon, 14 Mar 2022 16:10:41 GMT
Runtime duration: 23972 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-03-14T16%3A10%3A41.891Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Thirdparty Tests
Environment: moja2.test.mojaloop.live
Total assertions: 21
Passed assertions: 21
Failed assertions: 0
Total requests: 20
Total test cases: 8
Passed percentage: 100.00%
Started time: Mon, 14 Mar 2022 16:11:41 GMT
Completed time: Mon, 14 Mar 2022 16:11:46 GMT
Runtime duration: 4593 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-03-14T16%3A11%3A46.217Z.html)

**Comment by mdebarros** [comment]
Other manual tests carried out:
1. Default install of v13.1.0, with 100% pass for GP, Bulk and TP verification tests
2. Default install of v13.0.2 upgraded to v13.1.0, with 100% pass for GP, Bulk and TP verification tests

**Comment by mdebarros** [comment]
@elnyry-sam-k I think we can close this.

**Comment by elnyry-sam-k** [comment]
This is awesome! Thanks @mdebarros
