### ISSUE TITLE
Provision FX API into TTK

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2529]
## **Goal**:
`As a` CCB team member

`I want to` explore the FX API using the Mojaloop Testing Toolkit
  
`so that` I can test various scenarios and finalize the design for FX

**Acceptance Criteria**:
- [ ] A new version of TTK with the FX API provisioned is made available

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] Develop the OpenAPI file based on the FX definition word doc [@elnyry-sam-k ]
- [ ] Review API for accuracy [@elnyry-sam-k ]
- [ ] Provision FX API into the TTK and verify correctness 
- [ ] Release a version of TTK with FX API support
- [ ] Iterate over changes needed based on feedback from Michael

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @elnyry-sam-k @vijayg10 
- QA/Review: @MichaelJBRichards @elnyry-sam-k
