### ISSUE TITLE
2.4.10.01 Test the Golden Path for Parties, Quotes, Transfer on a deployment with PI2 architecture

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#253]
**Goal**:    
1. As a contributor
I want to _test the golden path for parties, quotes and transfers on a k8s setup with PI2 architecture_
so that testing for these end-points can be automated.
2. As an FSP
I want to be able to _confirm the expected Golden Path behavior_
so that I can validate my integrations in the knowledge that the Mojaloop switch works as expected.
3. As a Hub Operator
I want to be able to _verify the Mojaloop release behaves as expected_
so that I can incorporate the the Mojaloop release into my product.

**Tasks**:
- [x] Configure the test harness to point to a setup with PI2 arch
- [ ] Test below end points separately
  - [ ] /participants
  - [ ] /parties
  - [ ] /quotes
  - [ ] /transfer
- [ ] The Golden path for a P2P transfer is tested on the deployed k8s environment
  - [ ] AWS
  - [ ] Azure
- [ ] Documentation to be reviewed so that it is ready to be consumed by contributors who want to use the test framework for testing

**Acceptance Criteria**:
- [x] The test harness (Cucumber framework) is configured to point to a k8s setup with the PI2 architecture code
- [ ] The below end-points are tested separately
  - [ ] /participants
  - [ ] /parties
  - [ ] /quotes
  - [ ] /transfer
- [ ] The Golden path for a P2P transfer is tested on the deployed k8s environment
  - [ ] AWS
  - [ ] Azure
- [ ] Test reports are available for test runs
- [ ] Tests can be run external to an environment

**Dependencies**:
- [ ] Dependent on existence of a setup with a PI2 architecture setup on AWS #269 
- [ ] Dependent on existence of a setup with a PI2 architecture setup on Azure #269 

**Accountability**:
- Owner @sri-miriyala 
- QA/Review
**NOTE: There are errors and will work on it in the next sprint.**
