### ISSUE TITLE
Get payment manager deployed locally

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2531]
## **Goal**:
`As a` participant in a Mojaloop Hackathon

`I want to` deploy Payment Manager instance locally
  
`so that` I can use it to run various Mojaloop use-cases on a Sandbox and explore various resources

**Acceptance Criteria**:
- [ ] Steps to get Payment Manager for OSS working locally are documented and made available on Mojaloop GitHub
- [ ] Document steps so that it can be used for HiPiPo Hackathon

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [ ] Get Payment Manager for OSS working locally
- [ ] Test it with OSS Sandbox for hackathons
- [ ] Document steps so that it can be used for HiPiPo Hackathon

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @gibaros @vijayg10 @mdebarros 
- QA/Review: @elnyry-sam-k @lewisdaly
