### ISSUE TITLE
QA - add 3PPI tests to TTK collections

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2533]
## **Goal**:
`As a` hub operator

`I want to` have 3PPI linking and transfer tests in the TTK collections
  
`so that` I can verify a deployment supports the Mojaloop Third Party API

**Acceptance Criteria**:
-  [x] update deployment guide with instructions for with 3PPI support, provisioning the environment, and running the tests
 - [x] tests defined in pisp/docker-local translated to TTK test environment

**Complexity**: Medium

**Uncertainty**: High

---

**Tasks**:
- [ ] add thirdparty tests to ttk collection

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] e2e tests pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/55
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/195
- [x] https://github.com/mojaloop/documentation/pull/335

## **Follow-up**:
- Deploy the 3rd party services, simulators on moja3 deployment: #2528

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
