### ISSUE TITLE
Add Dashboard view to complete the UX design for tracing a transfer end-to-end

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2541]
## **Goal**:
`As a` Mojaloop Community Software Engineer
`I want to` configure the BizOps Framework to incorporate an exemplar end-to-end transaction dashboard view 
`so that` I can identify trends before tracing a transaction end-to-end

**Notes:**
- This story continues from #2422  to complete the UX design as specified in that story I.e. This story includes the 'Dashboard View' (interactive donut pie charts).

**Acceptance Criteria**:
- [x] Verify that the dashboards summary views are interactive as specified in the desing document
- [x] Verify that the dashboard views update correctly when the data range filters are changed.

**Issues**:
- [ ] Issues in Event Processor to be reviewed 

**Tasks still to complete**:
- [ ] Testing Suite: Implement Integration Tests
- [ ] Sprint Review - A number of Errors and Fixes (Kevin to document)
- [ ] Templating and Documentation
- [ ] Recorded Demo for Mojaloop Foundation

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
