### ISSUE TITLE
Configure Ory Oathkeeper to perform RBAC for BOF POC

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2542]
## **Goal**:
`As a` Design authority
`I want to` Verify that the BOF proposed RBAC solution meets requirements
`so that` Only authenticated authorised users have access to the correct end points and functions, and so that a log is available to audit this activity.

**Acceptance Criteria**:
- [x] Verify that Ory oathkeeper is deployed 
- [x] Verify that Ory Oathkeeper access rules restrict access to the Reporting API
- [x] Verify that Ory Oathkeeper is using Ory Keto as it's authoriser
- [x] Verify that Ory Oathkeeper is correctly introspecting the authorisation token with WSO2
- [x] Verify that Ory Oathkeeper is using Kratos to obtain the cookie tokens
- [x] Configure Oathkeeper to use Kratos as it's cookie Authenticator (@vijayg10 )

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

Notes:
- Ory Oathkeeper is to restrict access to backend endpoints as a reverse proxy. Ory Oathkeeper will use WSO2 to perform token introspection, Ory Kratos to perform cookie authentication and use Ory Keto as authoriser.
- Ory Kratos will manage the user flows required to log in and out of the system and store the tokens as cookies.
- Ory Keto will manage all authorisation requests.
---

**Tasks**:
- [x] Create environment to test configurations
   - Micro-frontends
   - Ory Oathkeeper
   - Ory Keto
   - Ory Kratos
   - Reporting BC API

- [x] Configure Ory Oathkeeper
   - [x] Create helm chart for deploying Ory Oathkeeper ~~with MySQL db~~ as a reverse proxy (@vijayg10 )
   - [x] Define Access rules for BOF POC  (@vijayg10 )
   - [x] Configure Oathkeeper to use WSO2 ISKM for token introspection (@vijayg10 )
   - [x] Configure Oathkeeper to use Keto as its authoriser  (@vijayg10 )
   - [x] Enable new mutation and pass token to backend APIs

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/charts/pull/9

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by fugu13** [comment]
Took a bit longer than anticipated, partly because I wanted to make sure I had some of the Kratos bits right before I finished this, but I've created the following guide for doing this, @vijayg10 

# Configuring Oathkeeper for BizOps

The Oathkeeper helm chart is described at [ORY Oathkeeper Helm Chart | k8s](https://k8s.ory.sh/helm/oathkeeper.html) and defined in [k8s/helm/charts/oathkeeper at master · ory/k8s · GitHub](https://github.com/ory/k8s/tree/master/helm/charts/oathkeeper) The Ory helm repository is documented at [ORY Helm Charts | k8s](https://k8s.ory.sh/helm/). The Oathkeeper configuration reference is at [Configuration | ORY Oathkeeper](https://www.ory.sh/oathkeeper/docs/reference/configuration) but note that the Helm chart values has different ways of doing certain things. Also, every configuration value can be overridden with environment variables. 

The Oathkeeper helm chart deploys two key components into Kubernetes: Oathkeeper itself, and the Oathkeeper Maester. Oathkeeper is stateless and config-driven, and seamlessly reloads itself with zero downtime anytime that config changes. Oathkeeper Maester is a controller for the Rule CRD, and composes the Rule objects in Kubernetes into a single complete rules file that is loaded by Oathkeeper.  By default, that’s a ConfigMap that Oathkeeper mounts, but it can also be set to run as a sidecar and use a shared mount.

Oathkeeper exposes two ports as two services. One service is the API service, and the other is the Proxy service. Long-term, we’ll be using the API service, which will be queried by the next generation API Gateway using the Access Control Decision API  (see [REST API | ORY Oathkeeper](https://www.ory.sh/oathkeeper/docs/reference/api/#access-control-decision-api) ) that Oathkeeper provides, but for now we will be using the Proxy service, and exposing that via Ingress. External URLs to services protected by Oathkeeper will be pointed at  the Oathkeeper Proxy ingress, which will then proxy access to the internal services at those URLs and apply access control rules.

Oathkeeper will be configured to generate and sign a JWT containing claims that internal services can check and verify by pointing at the JWKS that Oathkeeper will publish (which is part of the configuration) at the well-known URL for JWKS on the API service (see [REST API | ORY Oathkeeper](https://www.ory.sh/oathkeeper/docs/reference/api/#lists-cryptographic-keys) ). If a service does this, then it is operating under a basic zero trust regime, as it will not be possible to call that service except with a token that has been generated by Oathkeeper, and Oathkeeper will only generate a token if the access rules for the given URL allow access.


## Debugging
The responses and logs from Oathkeeper tend to be pretty informative, definitely start there. Make sure you’re looking at the logs for the request that matters. Oathkeeper will also be logging health checks and similar. 

Some possible debugging actions that I’ve found useful in different circumstances:

* make a match much, much more permissive (replacing the entire beginning with `<.*>` and then having the minimum currently unique suffix is good)
* double check that each internal URL is the proper internal URL by checking it is accessible inside the cluster with curl
* look at the IdP logs
* make sure the domains and ports for the introspection and the external token endpoint are identical. Keycloak at least doesn’t like it if they are not
* point the Oathkeeper rule at https://httpbin.org/ , usually the `/anything` path prefix which will reflect back everything it gets, making it easy to see what the service will see

## In Addition to Helm Chart
The following piece will be needed in addition to the helm chart.

### JWKS Secret

A secret should be created with key `mutator.id_token.jwks.json` and value of a JWKS suitable for use with Oathkeeper. An initial one can be generated as described at [Configure and Deploy | ORY Oathkeeper](https://www.ory.sh/oathkeeper/docs/configure-deploy#cryptographic-keys). It will contain both public and private keys.

#### Operating with the JWKS Secret

To rotate the secret, apply the following procedure:

0. Note the time.
1. Add a public and private key pair to the beginning of the array in the JWKS (make sure all public JWKs have a specified unique `kid`) in the secret. All keys other than the new keys and the previous first public and private keys can be removed. This is because Oathkeeper always signs with the first key.
2. Wait until all requests that Oathkeeper might have received and authorized would have had their JWT handled by the backend service. The main delay here is the time for the secret update to propagate, comprising the delay of the secret manager to the updated secret and the delay of the secret to the updated volume, which is probably at most a minute or two, so wait that long after the time in step 0.
3. If the old secret is being removed (this is only necessary if a breach is suspected, otherwise step 1 is sufficient for periodic key rotation), remove it now.


## Annotated Helm Values

Several places will need to be changed to the rest-of-deployment-specific URLs or other values. Those places are described in the comments, as well as other commentary.

I’m not sure if we can use the built-in Proxy ingress or if we’ll need to define our own ingress pointing at the Proxy service, so I’ve left that area of the config unspecified, which leaves the ingress out by default. You can change `ingress.proxy.enabled` to `true` to enable the proxy ingress. See the linked pages at the beginning for options  available for the built-in ingress configuration.

If TLS needs to be terminated at Oathkeeper, see the `tls` sections in the config documentation, and combine that with secrets and the `deployment.extraVolumes` and `deployment.extraVolumeMounts` values.

Prometheus is at `:9000/metrics` by default, if that is in use.


```yaml

oathkeeper:
  config:
    log:
    # the maximum log level, we'll stick here or maybe debug if this is overwhelming until the config is verified
    # then, we'll determine what log level to set based on needs
    level: trace
    access_rules:
      matching_strategy: regexp
    authenticators:
      cookie_session:
        enabled: true
        config:
          # this should be the internal URL of the public Kratos service's whoami endpoint, which might look like the below
          check_session_url: http://kratos-public/sessions/whoami
          preserve_path: true
          # this means we automatically sweep up all the metadata kratos provides for use
          # in, for example, the JWT, if we ever have more
          extra_from: "@this"
          # kratos will be configured to put the subject from the IdP here
          subject_from: "identity.id"
          only:
          - ory_kratos_session
      oauth2_introspection:
        enabled: true
        config:
          introspection_url: https://whatever/the/wso2/url/is/oauth2/introspect
          introspection_request_headers:
          # see https://is.docs.wso2.com/en/latest/learn/invoke-the-oauth-introspection-endpoint/ for what credentials
          # will need to be configured here
          # also, this does not seem to be settable via environment variable, which means it is 
          authorization: "Basic SOME WORKING AUTH HERE"
          cache:
            # disabled to make debugging easier. enable for caching.
            enabled: false
            ttl: "60s"
    authorizers:
      remote_json:
        enabled: true
        config:
          # the check URL for Keto. This will be POST'd to. See https://www.ory.sh/keto/docs/reference/rest-api#operation/postCheck
          remote: http://internal-keto-url-here/check
    mutators:
      id_token:
        enabled: true
        config:
          # this should be the internal base URL for the API service, which will look something like the below
          issuer_url: http://whatever-oathkeeper-internal-is-api:4456/
    errors:
      fallback:
        - json
      handlers:
        json:
        # this gives API clients pretty error JSON
        enabled: true
        config:
          verbose: true
          redirect:
        enabled: true
        config:
          # set this to whatever the main URL is, it'll ensure that browser errors redirect there
          to: https://whatever-external-main-url-is/
          when:
          - error:
            - unauthorized
            - forbidden
            request: 
            header:
              accept:
              - text/html
secret:
  # without this we would need to put the JWKS in the config, which would mean we couldn't rotate it just by changing the secret
  manage: false
  # change to whatever is used for secret name
  name: oathkeeper-jwks
deployment:
  extraEnv:
    # for whatever reason this environment variable only gets set if the JWKS is in the config even though the rest of the secret mounting
    # and such still happens
    - name: MUTATORS_ID_TOKEN_CONFIG_JWKS_URL
    value: file:///etc/secrets/mutator.id_token.jwks.json


```



## Rules

Rule resources will need to be created in k8s along the lines of the following, for each backend “match” (URL regex plus HTTP method(s)) protected with a permission.

As the flexibility to define 3rd party services and bounded contexts increases, they can define their own rules (perhaps behind a helm values flag), which express which permissions should be required for which URLs. 

The biggest potential issue here is that each match MUST be unique. If a request matches multiple, Oathkeeper will complain. Once a general pattern is picked that results in unique regexes, this will not happen except with user error.

```yaml

apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: a-unique-name
spec:
  version: v0.36.0-beta.4
  upstream:
    # set to whatever URL this request should be forwarded to
    url: http://internal-url-of-backend-service/
  match:
    # this might need to be http even if external is https, it depends on how ingress does things
    # my recommendation is to have a given prefix, then the "everything else in the domain name" matcher
    # so it doesn't need to be changed when the config is moved between various main domains
    # then whatever is needed for the specific path (this is set to match all subpaths)
    # regexes go in between angle brackets
    url: https://example.<[^/]*>/<.*>
    methods:
    # whatever method(s) this rule applies to
    - GET
  authenticators:
    - handler: oauth2_introspection
    # comment out this second one to not allow browser-cookie access
    - handler: cookie_session
  authorizer:
    handler: remote_json
    # these will generally be identical for all rules,
    # except "object" will be changed to the permission ID that is relevant for
    # this URL
    payload: |
    {
      "namespace": "permission",
      "object": "PERMISSION IDENTIFIER HERE",
      "relation": "granted",
      "subject_id": "{{ print .Subject }}"
    }
  mutators:
    # change this to an empty array if the id_token isn't needed, if you want
    - handler: id_token

```

**Comment by fugu13** [comment]
I realized I forgot to nest "payload" inside "config" in the Rule at the bottom, I've updated the text now

**Comment by vijayg10** [comment]
I think we can use the mutator '**_header_**' instead of '**_id_token_**' for now in our deployments. I tested this and I can confirm that the backend APIs are getting the header X-User with wso2-uuid.

**'id_token'** mutator takes the authentication information (e.g. subject) and transforms it to a signed JSON Web Token, and more specifically to an OpenID Connect ID Token. The API backends can verify the token by fetching the (public) key from the /.well-known/jwks.json endpoint provided by the ORY Oathkeeper API.

**'header'** mutator will transform the request, allowing you to pass the credentials to the upstream application via the headers. For example the API backends will get the following header in the http requests.
X-User: **_wso2-uuid_**

**Comment by fugu13** [comment]
There are three main consequences of not using an id_token mutator (and checking it in internal services):

1. Without it, there is no zero trust architecture, while with it calls will only be possible to internal services that oathkeeper has handled, removing a large category of attack
2. Lots of languages have existing libraries that support introspecting a JWT and automatically hooking the claims into their auth setup, eg https://github.com/eclipse/microprofile-jwt-auth
3. Additional claims means additional headers, each custom-handled (which might be done a number of ways for structured claims), while a JWT is a standardized way to transport a bundle of claims, including structured claims

Really, the main one is number one, since a zero trust architecture is a long term goal.
