### ISSUE TITLE
Configure Ory Kratos to perform RBAC for BOF POC

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2543]
## **Goal**:
`As a` Design authority
`I want to` Verify that the BOF proposed RBAC solution meets requirements
`so that` Only authenticated authorised users have access to the correct end points and functions, and so that a log is available to audit this activity.

**Acceptance Criteria**:
- [x] Verify that Ory Kratos is deployed 
- [x] Verify that Ory Kratos correctly follows the token login flows and redirects when a Micro-frontend user is not logged in
- [x] Verify that Ory Oathkeeper is using Kratos to obtain the cookie tokens

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

Notes:
- Ory Oathkeeper is to restrict access to backend endpoints as a reverse proxy. Ory Oathkeeper will use WSO2 to perform token introspection, Ory Kratos to perform cookie authentication and use Ory Keto as authoriser.
- Ory Kratos will manage the user flows required to log in and out of the system and store the tokens as cookies.
- Ory Keto will manage all authorisation requests.
---

**Tasks**:
- [x] Create environment to test configurations
   - Micro-frontends
   - Ory Oathkeeper
   - Ory Keto
   - Ory Kratos
   - Reporting BC API

- [x] Configure Ory Kratos (@kleyow )
   - [x] Create helm chart for deploy Ory Kratos (@vijayg10 )
   - [x] Provide code and docker for Shim (Russell)
   - [x] Deploy shim alongside Kratos as part of helm chart (@vijayg10 )
   - [x] Configuring Login Sessions (@kleyow )
   - [x] Configuring Session cookies (@kleyow )
   - [x] Configuring Kratos for CORS (@kleyow )
   - [x] Ory Kratos - WSO2 OIDC integration (@kleyow )
   - [x] Configuring micro-frontend shell application to call Ory Kratos (@kleyow )
   - [x] Configure Oathkeeper to use Kratos as it's cookie Authenticator (@vijayg10 )
   - [x] Configuring Ory Kratos - Ory Oathkeeper integration (@kleyow )
   - [x] Fix logout flow
   - [x] Proper default values in the helm charts
   - [x] Enable MySQL 
   - [x] ~~Kratos UI for OIDC move repo from ModusBox to Mojaloop~~ (Didn't get the approval from the original author, so currently left it in the original repo which is public anyway)
   - [x] ~~Add to Config Map Jsonnet~~ (I think we can skip this for now as the functionality is working with base64 encoded jsonnet without any problem)

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/charts/pull/7
- [x] https://github.com/mojaloop/charts/pull/9

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
