### ISSUE TITLE
[helm/ttk] - migrate docker-local e2e tests to use TTK 

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2546]
## **Goal**:
`As a` deployer

`I want to` be able to test the 3P API in my mojaloop deployment
  
`so that` I can be confident that the 3P API is working

**Acceptance Criteria**:
- [ ] ability to run e2e tests against a live mojaloop deployment in a postinstall hook
- [ ] 

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
