### ISSUE TITLE
Merge BizOps into the Finanical Portal V2 UI

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2547]
## **Goal**:
`As a` Hub operator 
`I want to` use Biz Operation workstream function within the current Financial Portal V2 
`so that` the hub operations functionality is extended to include the enhanced tracing of a transfer and assigning users to roles and assign DFSP report access to users.

**Acceptance Criteria**:
- [ ] Verify that the Financial Portal V2 UI Application can load and integrate the BizOps micro-frontends into the UI by extending the current menu with the loaded functionality.
- [ ] Verify that the Kratos cookie token authentication OIDC flows work for the loaded micro-frontends.
- [ ] Verify that the existing Financial Portal functionality User token and RBAC functionality still work. 

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---
Add Micro-frontend loading to the Financial Portal V2 UI Application
**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
