### ISSUE TITLE
FSPIOP API version negotiation for pass-throughs not handled - Transfers-service

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2548]
## **Goal**:
`As a` Hub Operator

`I want to` have the Notification Service handle sync API version negotiation failures
  
`so that` the central services can compensate

**Acceptance Criteria**:
- [ ] Notification Handler (ML-API-Adapter) publishes a message to Central-Services (Prepare/Fulfil handlers) to handle compensating actions for delivery failures such as API version negotiation failures
- [ ] Central-Services (Prepare/Fulfil handlers) to handle compensating actions for API version negotiation failures

**Complexity**: High

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
