### ISSUE TITLE
[pisp-e2e]: Add un happy path transfer tests

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2551]
## **Goal**:
`As a` hub operator

`I want to` have more complete pisp transfer tests (test cases listed in task list)
  
`so that` I can be assured that the thirdparty transfers works

**Acceptance Criteria**:
- [x] added unhappy path tests for third party transaction requests as described in https://github.com/mojaloop/pisp-project/blob/master/docs/transfer/README.md#3-error-conditions

**Complexity**: Medium> A short comment to remind the reason for the rating

**Uncertainty**: Medium > way to generate test credentials for the consents 

---

**Tasks**:
- [x] 3.1 bad payee lookup https://github.com/mojaloop/pisp-project/blob/master/docs/transfer/README.md#31-bad-payee-lookup
- [x] 3.2 Bad thirdpartyRequest/transactions Request - https://github.com/mojaloop/pisp-project/blob/master/docs/transfer/README.md#32-bad-thirdpartyrequesttransactions-request
- [x] 3.3 Downstream FSPIOP  Failure - https://github.com/mojaloop/pisp-project/blob/master/docs/transfer/README.md#33-downstream-fspiop-api-failure
- [x]  3.4 Invalid Signed Challenge - https://github.com/mojaloop/pisp-project/blob/master/docs/transfer/README.md#33-downstream-fspiop-api-failure
- [x] 3.5 Thirdparty Transaction Request Timeout - https://github.com/mojaloop/pisp-project/blob/master/docs/transfer/README.md#35-thirdparty-transaction-request-timeout
- [ ] Creating test credentials(https://github.com/mojaloop/contrib-fido-test-ui) for each test case in order to run them in bulk

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @georgi-logodazhki 
- QA/Review: @lewisdaly

**Comment by elnyry-sam-k** [comment]
@georgi-logodazhki - whats left for us to close this here?

**Comment by georgi-logodazhki** [comment]
@lewisdaly - could you help us to create several test credentials
