### ISSUE TITLE
Complete the merging of the Financial Portal V2 and the BizOps Framework

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2553]
## **Goal**:
`As a` a hub operator
`I want to` keep the current financial portal functionality and have the BizOps framework functionality
`so that` I can benefit from the BizOps workstream work without compromising my current operations

**Acceptance Criteria**:
- [x] Verify that the Kratos Login is use for all parts of the financial portal
- [x] Verify that the Trackability of a transfer is fit for purpose.
- [x] Verify that there exist tests against the existing financial portal functionality 

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Port over Settlements functionality from financial portal into microfrontend
- [x] Port over Positions functionality from financial portal into microfrontend
- [x] Update shell to handle new microfrontends
- [x] Testing Suite: Role frontend integration tests.
- [x] Testing Suite: Transfer frontend integration tests.

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
