### ISSUE TITLE
Use TTK golden path to test event processor

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2554]
## **Goal**:
`As a` Hub Operator
`I want to` ensure that the event sourcing process is capturing data appropriately for all normal and exceptional situations  
`so that` I can use the results of the event sourcing processor to diagnose unexpected events.

**Acceptance Criteria**:
- [ ] Verify that the TTK golden path test set is run against Mojaloop, and that the resultant stored event processor events reflect what happened.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
