### ISSUE TITLE
Build appropriate UI testing and test coverage

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2555]
## **Goal**:
`As a` quality engineer,

`I want to` make sure the BOF portal is up and working as expected.
  
`so that` more stable releases are possible with regression tests.

**Acceptance Criteria**:
- [x] The BOF portal is manually tested for the feature Users and roles
- [x] The BOF portal is manually tested for the feature Find Transfer
- [x] Any bugs are logged for tracking

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x]  Have access to the current env and get the access details
- [x] Review the stories related to the functionality
- [x] start writing tests
- [x] Testcases related to the Find trasnfer feature
- [x] Testcases related to the Users and roles
- [x] Validate the Users and roles
- [x] Validate the Find Transfer feature 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD
- [ ] 
## **Issues**:
- [ ] Events not showing up for the quotes, transfers,settlements @vijayg10 
- [ ] Date time drop down is always showing the current date as opposed to the Date on the field. This is for both From and To dates. 
- [x] 403 error while accessing roles @vijayg10 
- [ ] Sort on the Amount filed is not working as expected. [Seems, it is sorting based on text than numeric value.] 
- [ ] Date times are inconsistent across portal. (not showing the same time zone)
## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
