### ISSUE TITLE
2.3.0 Decide on approach for unit, integration testing with legacy code

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#256]
**Goal**:
As a contributor on the team
I want to _decide on an approach for running unit, integration tests with legacy code_
so that new additions for changes, features get completed.

**Tasks**:
- [x] Setup discussion to come up with an approach __[ @mdebarros ]__
- [x] Based on the decision necessary action items to affect the changes are added either as a separate story or as tasks in existing stories

**Acceptance Criteria**:
- [x] A decision is made on how to run unit, integration tests on legacy code 
-  ~~A new story or new tasks in existing stories are added to affect the changes based on the decision~~

**Dependencies**:
- None currently

**Accountability**:
- Owner @mdebarros                        
- QA/Review __Dev Team__

**Comment by mdebarros** [comment]
Decision:

For Unit, Integration tests we will create a new temp folder in the project called "testPI2", as per the following branch: @channel note the branch for the testPI2 discussion: https://github.com/mojaloop/central-ledger/tree/feature/PI2Tests

The Unit, and Integration tests have been updated to use this folder for the time being.

Note that this does not resolve the issue for Code Coverage. This will have to be ignored until all the code is re-factored.
