### ISSUE TITLE
Implement Reporting Operator for loading reporting templates

### ISSUE THREAD

**Issue by kirgene** [mojaloop/project#2560]
## **Goal**:
`As a` DFSP operator to accommodate requirements from Mowali

`I want to` import reporting templates using Operator pattern
  
`so that` I can use private reporting templates

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Update helm chart to include Operator
- [x] Use dotenv for env variable retrieval
- [x] Update docs on how to create ConfigMap for reporting templates
- [x] Fix npm audit vulnerability issues
- [x] Kubernetes Operator (Manual) Testing
- [x] Update Helm Charts
- [x] Convert  Reconciliation Amount Report
- [x] Convert  Settlement Window Report
- [x] Convert  Transaction Reconciliation Report
- [ ] Add the validation into the operator and update the K8S status of the custom resources

**Demo Reporting**:
- recorded for submission with invoicing
- Manual Uploading of Reports for demonstration
- [x] Automated Test Cases

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
