### ISSUE TITLE
[sandbox] - HTTPS support

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2564]
## **Goal**:
`As a` sandbox user

`I want to` have https support for sandbox.mojaloop.io
  
`so that` I can be assured of the security of the sandbox site

**Acceptance Criteria**:
- [ ] add domain verification (blocked - waiting for virtual to update the dns...)
- [ ] generate certs on AWS for the ELB
- [ ] add http -> https rerouting for user facing sites on the sandbox 

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
