### ISSUE TITLE
Extensions to RBAC - Enforcing mutually exclusive permissions

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2565]
## **Goal**:
`As a` Hub Operator
`I want to` enforce the separation of duties in an RBAC policy
`so that` a person within the organisation with access to a function, cannot at the same time have access to another function. Permissions to these functions must be mutually exclusive.

**Acceptance Criteria**:
- [ ] Verify that mutually exclusive permissions sets can be loaded as a kubertetes resources 
- [ ] Verify that a user cannot be assigned roles that have mutually exclusive permissions.
- [ ] Verify that an update to the existing role - permission assignment can be validated against current user role assignments before these updates are applied through an API.
- [ ] Verify that an update to the existing role - permission assignment that violates the mutually exclusive permissions because of currently assigned user roles is not applied.

**Current Functionality**
- Users are assigned one or more roles. A user may 'take on' multiple roles, subject to defined rules.
- Roles are assigned Permissions
- The Identity and Access Proxy (Ory Oathkeeper) enforces access to endpoints based on permission.
- Backend API can optionally check permissions through Keto API.

**Enforcing mutually exclusive permissions**
The enforcement of mutually exclusive permissions to support the separation of duty and corresponding security of information and management of security policy controls. The implementation of separation of duty creates tighter security but can lead to complexity for the security administrator and the end users who use the system. Enforcing mutually exclusive permissions can reduce and manage this complexity. 

An example of mutually exclusive permissions might be a user able to access the Finance Portal and to carry out sensitive functions such as add/withdraw funds should not also have access to audit functions. 

**Modelling the exclusion**
It is recommended that this exclusion is modelled as a set of permission - permission exclusions that are enforced globally.

Modelling mutually exclusive permissions can be done a number of ways namely:

1. User Role - User Role exclusions
2. User Role - Permission exclusions
3. Permission - Permission exclusions

Because this functionality has been added to support the segregation/separation of duties, the cleanest way of enforcing this is to have a permission pair exclusion that is globally enforced. With all the other options, there is the possibility that the exclusion can be bypassed with the addition of a new inclusive role. These permissions come in sets, so defining an exclusion set is much simpler and easier to maintain.

**Synthetic Roles Vs Multiple User Roles**
These are two methods that can be used to model RBAC permissions with mutually exclusive permissions.

1. Dynamically building up a synthetic role for each user based on rules associated with the current assigned roles and their permissions and exclusions. 
2. Defining roles that are associated with user functions. Each user therefore will need to be assigned more than one role. Roles permissions are less likely to change.

The preference is to implement multiple functional roles. This is because it is much simpler to understand, maintain and support this method. Identifying the cause of a loss of permission in a synthetic role because of multiple role assignments subsequent rule applications requires a detailed understanding of the process of how the synthetic roles are calculated and implemented. This is complexity that is avoided with the second option.

**Multiple user role assignments required dynamic checking of exclusions**
Allowing the system administrator to assign more than one role to a user is convenient, flexible and limits the number of roles required within the organisation. This also means that it is possible to violate a mutually exclusive permission by assigning users to roles. Checking and enforcing these exclusions therefore need to be dynamic.

There are a number of places that this dynamic check needs to take place.

1. On the assignment of a role to a user
2. On the application of a new role-permission resource definition, or the application of a new security policy that may include a wholesale change of permission and role structures.

>**Note 1:** If it is possible that a violation can exist in the system, then each time a permission is checked, exclusion violations should also be checked. Currently this is not designed for as it is assumed that 1 & 2 are sufficiently implemented that a violation cannot exist.

> **Note 2:** The change control release and testing on lower environments may not catch these violations. Testing for these violations cannot be done on lower environments without first making sure that the user access control is identical in the lower environments which is normally not the case.

### **Proposed Changes**
**New Keto relation**
Introduction of a new relation that relates two permissions that cannot be held together. 
```
“permission:X excludes permission:Y#allowed”
```
**New Permission Exclusion Custom Resource Definition**
New permission exclusion custom resources are consumed by the Role Permission Controller, which  will upload the new exclusions into Keto using this new relation. Each will contain two sets of permissions, and holding any permission in one set will mean no permission in the other set can be held. This allows for many flexible scenarios, and the simplest scenario of “any person who can do this one thing cannot do this other thing, and vice versa” remains simple to express.

**Role Permission Operator API Validation Check**
The Role Permission Resource Controller will provide an API that can be used to check a security permission update’s allowability before it is applied. That API will take a proposed change to a particular Role Permission resource and calculate whether or not any existing users would have mutually exclusive permissions after that change, returning the result. This API will be usable by the administrative UI and CI systems to “preflight” changes for likely problems.

**Role Permission Operator Change Enforcement**
When a role-permission resource is changed, the role-permission operator will first lock the ability to change user role assignments, then perform the same check as the validation API does, and if the resource does not pass the check it will not accept the changes from that resource, instead maintaining the current role permission assignments, and surfacing the issue as an error in the kubernetes API for instrumentation and alerting.

**Conflict Check on User Role Assignment**
When a user is assigned a role, the user role assignment API will validate that the change does not result in the user having two mutually excluded permissions. If it does, the change will be rejected and an error returned.

### **Enforcing Maker-Checker**
There are two approaches that can be taken to enforce a maker-checker validation flow.

1.  Enforce using roles and mutually exclusive permissions via security policies. I.e. Makers cannot also be checkers
2.  Enforce in application layer security rules.  I.e. Makers cannot also be checkers within the same validation process. This is often implemented in the application layer when assigning makers and/or checkers as defined in a process flow, and by enforcing that a checker cannot be the same person as the maker in a validation flow.  I.e. the code that enforces this will exist within each bounded context.

To support this functionality the RBAC system must provide: 

1.  the User Identifier to that bounded context.
2.  A means for checking authorisation if necessary.

**Comment by PaulGregoryBaker** [comment]
Duplicate
