### ISSUE TITLE
Extending the Role Permission Operator to load mutually exclusive kubernetes resources

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2567]
## **Goal**:
`As a` Hub operator
`I want to` add a mutually exclusive permission set
 `so that` I can enforce a separation of duties against sensitive functions.

**Acceptance Criteria**:
- [x] Verify that a new Kubernetes Resource definition for these mutually exclusive permission sets is defined.
- [x] Verify that when applying a mutually exclusive permission sets, that the corresponding Keto tuples are added.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Define CRD for the new permission exclusions
- [x] Test the CRD with sample resources in K8s
- [x] Modify the operator service to handle the new custom resources
  - [x] Separate configs for the two type of custom resources
  - [x] Refactor the existing operator file structure to accommodate the new operator
  - [x] Implement in-memory store for the inbound permission exclusions via custom resources
  - [x] Construct delta by comparing the existing tuples in keto
  - [x] Update keto relation tuples with the delta
  - [x] Add unit tests for the new functions
  - [x] Add integration tests
- [x] Test the functionality in K8S by deploying the new chart and making some keto checks
- ~~Modify the helm chart with new config and image version (Don't forget to bump the chart major version as this is breaking change)~~ ( Adding this task to the followup story #2568 )

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/security-role-perm-operator-svc/pull/6 (WIP)

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Here is an example of what the new kubernetes resource file could look like.

```yml
apiVersion: "mojaloop.io/v1"
kind: MojaloopPermissionExclusions
metadata:
  name: arbitrary-name-here
spec:
  # must match what is used in Keto, whatever that is
  permissionsA:
  - permission_01
  - permission_02
  - permission_03
  - permission_04'
  permissionsB:
  - permission_05
  - permission_06
  - permission_07
  - permission_08'
 ```

**Comment by PaulGregoryBaker** [comment]
https://docs.mojaloop.io/business-operations-framework-docs/guide/SecurityBC.html#enforcing-seperation-of-duties
