### ISSUE TITLE
Pre update operator validation

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2568]
## **Goal**:
`As a` Hub operator
`I want to` ensure that the changes that I am about to apply to the role-permissions resources don't cause a mutually exclusive permission set violation
`so that` the RBAC policy is never violated.

**Acceptance Criteria**:
- [x] Verify that an API is provided that the user-role service can use to assign users to roles.
- [x] Verify that the User role assignment API will not allow an assignment that violates the mutually exclusive permissions
- [ ] Verify that the users cannot be assigned while the permissions roles and exclusive permission are being updated.
- [x] Verify that resources that will cause violations are recognised as such
- [x] Verify that this functionality is accessible through an API
- [x] Verify that new resources being loaded are not applied if they create a violation
- [ ] Verify that when new resources are being loaded, that the user role assignment change functionality is locked
- [ ] Verify that suitable Recovery Options to be implemented to support Pipeline Cancelation, TimeOut and Failures

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Implement a function which contains logic to validate the permission exclusions while udpating role permissions
- [x] Implement a function to validate the permission exclusions while user role assignment
- [x] Expose these two functionalities through API
- [x] Implement API resources to validate and assign roles to a user
- [x] Add the validation into the operator and update the K8S status of the custom resources accordingly (Like In-Progress, Success, Failed ...etc) and notify about the error through some K8S mechanism (Like Emit K8S events, set error message to the custom resources ...etc)
- [x] Decision to be made on the locking mechanism
- [ ] ~~Implement locking mechanism~~ (Should be moved to a new story based on the discussion)
- [x] Modify the helm chart with new config and image version (Don't forget to bump the chart major version as this is breaking change)
- [x] Address the suggestions and comments in the PR reviews
- [x] Update the versions and new config in IaC
- [ ] Add validation API call to the IaC pipeline (Both install platform and mojaloop roles pipelines)
  - Use shell script to get the roles and permissions from workbench config file
  - Pass that as body to API call

**Done**
- [ ] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/security-role-perm-operator-svc/pull/7
- [x] https://github.com/mojaloop/charts/pull/34 [WIP]

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
