### ISSUE TITLE
Update User Role API to check permission exclusions

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2569]
## **Goal**:
`As a` Hub operator
`I want to` be able to assign roles to users 
`so that` mutually exclusive permissions are not violated 

**Acceptance Criteria**:
- [ ] Verify that user roles changes have not been locked
- [x] Verify that a user role assignment does not violate mutually exclusive permissions before applying the user role assignment
- [x] Verify that the user-role assignment call is made through the permission role operator.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Change the user role API service to call operator service to assign roles to users
- [x] Add required new config variables
- [x] Test the user role assignment process with role permissions and permission exclusions in place
- [x] Incase of permission exclusion clash, verify that the error is displayed properly
- [x] Modify UI if required to display errors properly (A detailed list of errors should be displayed to know exactly why the role assignment is failed)
- [ ] Fix integrations tests
- [ ] Modify helm chart with new configuration

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] https://github.com/mojaloop/role-assignment-service/pull/10
- [x] https://github.com/mojaloop/reporting-hub-bop-role-ui/pull/19

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
