### ISSUE TITLE
2.4.99.01 Enable self-service registration for DFSP developers to use the API sandbox portal - [8]

### ISSUE THREAD

**Issue by markusvanaardt** [mojaloop/project#257]
**Objective**: Allow third-party (DFSP) developers to create API accounts on the WSO2 gateway to access services published on the Mojaloop's sandbox.

**Goal**:
1. As a developer of an FSP
I would like to _have a public landing/registration page_
so that I can register an account to use the API sandbox gateway for published services
2. As a contributor
I would like to _assign a vanilla user role to the new account_
so that the newly registered user has access to all the services as they are published
3. As a contributor
I would like to _provide a registered user with feedback once the account has been registered and activated_
so that they can be informed.

**Tasks**:
- [x] Configure 2x AWS virtual machines to host the different components;
- [x] Install and configure WSO2 API Manager (APIM) with public access;
- [x] Confirm SSL requirements (install if required);
- [x] Install and configure WSO2 Identity and Access Manager (IAM);

**Acceptance criteria**:
- [x] As a new user I must be able to create a new API gateway account;
- [x] The user account will be assigned the required access roles; and

**Dependencies**:
None

**Accountability**:
Owner: @markusvanaardt                        

![WSO2 API Manager and IAM design.png](https://images.zenhubusercontent.com/5ac635574b5806bc2bcdc9c4/29d4bed9-0f55-44b1-85a7-0899f3fa6860)

**Comment by markusvanaardt** [comment]
Incomplete tasks were redefined under tasks #277 and #278.
