### ISSUE TITLE
Add integration tests to quoting-service

### ISSUE THREAD

**Issue by shashi165** [mojaloop/project#2570]
## **Goal**:
`As a` developer

`I want to`  add integration tests to quoting-service
  
`so that`  all the features are integration tested

**Acceptance Criteria**:
- [ ] integration tests should cover major features of quoting-service 

**Complexity**:  Medium - Since we do not have any integration tests

**Uncertainty**: Medium 
---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
