### ISSUE TITLE
Docs preview automation

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2572]
## **Goal**:
`As a` codebase maintainer

`I want to` have the new docs deployed every time a release is made
  
`so that` I don't need to do it manually

**Acceptance Criteria**:
- [ ] terraform? configuration to create and update cloudfront
- [ ] compile and deploy site
- [ ] automatically update cloudfront functions to handle fallbacks to legacy docs

**Complexity**: Medium
**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
