### ISSUE TITLE
v14 charts - automate CI/CD testing across multiple k8s versions

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2573]
## **Goal**:
`As a` developer

`I want to` know that the mojaloop/charts install correctly across multiple k8s versions
  
`so that` I can be confident in the quality and coverage of the charts

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/charts/pull/15

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
