### ISSUE TITLE
Build helm test to test RBAC deployment

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2579]
## **Goal**:
`As a` Deployment expert working for a Hub Operator
`I want to` be able to run a helm test 
`so that` to check that the Ory RBAC solution is correctly deployed

**Acceptance Criteria**:
- [x] Verify that the tests run wit the standard test users
- [x] Verify that the Ory Oathkeeper and Ory Keto Integration configuration is operational
- [x] Verity that Ory Oathkeeper protects end points when access is not given
- [x] Verity that Ory Oathkeeper provides access to end points when access is removed
- [x] Verify that API (Access and Restriction) are documented
- [x] Verify that this is run as part of IAC and Manually
- [x] Verify that this test can be run in a production environment
- [x] [Optional] Verify that Ory Kratos is retrieving the cookie token
- [x] [Optional] Verify that the Ory Krato and Ory Oathkeeper integration configuration is operational

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Automate login flow and get cookie with supplied username and password [@partiallyordered ]
- [x] Assign Roles to user by calling role assignment service directly [@partiallyordered ]
- [x] Create test harness by changing the roles to user and check the API call [@partiallyordered ]
- [x] Refactor the code by separating repeated functions into separate files and folder structure [@vijayg10 ]
- [x] Add tests for central settlement endpoints [@vijayg10 ]
- [x] Add tests for central admin [@vijayg10 ]
- [x] Add tests for role api [@vijayg10 ]
- [x] Add tests for transfers api [@vijayg10 ]
- [x] Add tests for reports api [@vijayg10 ]
- [x] Fix the issue with login for fresh users [@vijayg10]
- [x] Helm test should work, add the configuration to the bof chart [@vijayg10 ]
- [x] Make it work in IaC pipeline [@vijayg10 ]

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/security-rbac-tests/releases/tag/v1.0.0

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
https://github.com/mojaloop/charts/tree/feat/rbac-helm-test/test/rbac#run-tests-locally

**Comment by PaulGregoryBaker** [comment]
The API access is documented in the oathkeeper rule and the

[Oathkeeper rule](https://github.com/mojaloop/iac-aws-platform/tree/master/bof-custom-resources/oathkeeper-rules/templates)
[Standard Role Permissions](https://github.com/mojaloop/iac-aws-platform/tree/master/gitlab_templates/switch-iac)
