### ISSUE TITLE
Publish Mojaloop party API to registered DFSP developers via the sandbox API gateway

### ISSUE THREAD

**Issue by markusvanaardt** [mojaloop/project#258]
**Objective**: Publish the Mojaloop *party API* on the sandbox API gateway for DFSP developers to consume.

**Goal**:
As a *DFSP developer*
I want to be able call the *Mojaloop party API* and receive the response
so that I can *test the Central Directory behaviour*

**Tasks**:
- [x] Publish the *party API* on the API gateway; and
- [x] Assign the correct access role of the API using the WSO2 IDM.

**Acceptance criteria**:
- [x] As a DFSP developer I want to obtain my session ID from the API gateway;
- [x] As a DFSP developer I want to access the published sandbox party API and get a valid response from the back-end Mojaloop API.

**Dependencies**:
- #257

**Accountability**:
- Owner: @markusvanaardt 

![WSO2 API Manager and IAM design 2.png](https://images.zenhubusercontent.com/5ac635574b5806bc2bcdc9c4/a0e6634a-8b2b-4757-b6e7-8c20dc24ce03)
