### ISSUE TITLE
BizOps: Important Settlement events not appearing in Event trace against the transfer

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2582]
**Summary**:
When tracing a transfer, the important settlement events relating the the settlement process are not visible in the UI.
These settlement events don't have a transfer id and therefor don't appear in the mongoDB query.
 
**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Tasks to fix**:

- [x] Extend event processor to store settlementID into the meta/reporting [@vijayg10 ]
  - [x] Settle a differed settlement and observe various events in kafka
  - [x] Change event processor to transform and populate the settlement IDs in metadata
- [x] Amend GraphQL query to use settlementID in the Settlement event MongoDB query. [@kirgene ]

**Pull Requests**
- [ ] https://github.com/mojaloop/reporting-events-processor-svc/pull/3
