### ISSUE TITLE
ML TTK: PI-16 enhancements to TTK and TTK-101

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2583]
PI-16 TTK features, enhancements and Mojaloop Training Program [MTP] Course for Testing Toolkit [TTK]

- [x] TTK MTP-101
  - [x] MTP TTK course initial draft reviewed
  - [x] Published and ready for community
- [x] TTK
  - [x] Support adoption of the TTK by at least one implementer
  - [ ] Capability to add/onboard OpenAPI definitions easily using the UI
  - [x] Bug fixes
  - [x] Support FXP implementation

Preceded by #2370

**Comment by elnyry-sam-k** [comment]
Followed up in #2733 - moving to maintenance after standardizing the TTK and publishing of MTP course TTK-101
