### ISSUE TITLE
Implement Standard Roles that align with the documentation as part of deployment

### ISSUE THREAD

**Issue by chris-me-law** [mojaloop/project#2587]
As a Technical Deployment expert working for the Hub operator
I would like to deployment the latest Mojaloop using IaC and have the standard roles and permissions included in the deployment
so that I can take advantage of the newly provided RBAC controls with an initial RBAC design from which to build.

**Acceptance Criteria**
Verify that Oathkeeper rules enforce the appropriate API protection based on role assignment

1. Verify that the standard Mojaloop API's are protected by the RBAC solution
2. Verify that the User Role service API is protected by the RBAC solution
3. Verify that the DFSP Legacy report API is protected by the RBAC solution 
4. [Optional] Automated Testing POC is in place for [2579]

**Remaining:**
Final Testing taking place ready for deployment @PaulGregoryBaker 

**Tasks**
- [x] Defined standard roles and permissions [@PaulGregoryBaker]
- [x] Prepare oathkeeper rules based on the permissions [@PaulGregoryBaker]
- [x] Update role permissions in workbench config file [@partiallyordered ]
- [x] Add oathkeeper rules files to Iac [@vijayg10 ]
- [x] Fix if there are any issues in the IaC with new roles and permissions [@vijayg10 ]
- [x] Fix the role-permission-operator bug (Creating duplicate tuples) [@vijayg10 ]
- [x] Test the deployment with the fixes in OSS test env [@vijayg10 @PaulGregoryBaker ]
- [x] Merge the files from test env to master IaC and release a version [@dfry ]
- [x] Deploy a new instance with the new IaC release [@dfry ]
- [x] Test the new deployment [@vijayg10 @PaulGregoryBaker ]

**Comment by PaulGregoryBaker** [comment]
This is the product summary table mapping roles to permissions 
![image](https://user-images.githubusercontent.com/40144680/145400630-8c0f56f1-2089-441f-8968-9438a54db486.png)

**Comment by chris-me-law** [comment]
https://docs.google.com/spreadsheets/d/17Ch5NLKGudXTJWFIdkuKD_OmAUZTIxGbm55j-9BiaWs
