### ISSUE TITLE
convert account lookup service charts to new v14.x.x charts format 

### ISSUE THREAD

**Issue by tdaly61** [mojaloop/project#2588]
## **Goal**:
`As a` contributor to v14.x.x

`I want to`update the account lookup service charts to the new v14.x.x format as implemented by existing charts in the "charts" repo
  
`so that` we can progress with the v14.x.x release 

**Acceptance Criteria**:
- [x] account lookup service charts are added to the charts repo
- [x] the circle ci initial tests run w/o error on these new format charts
- [ ] some part of the TTK should be runnable and pass on the account-lookup-charts to verify their correctness

**Complexity**: <medium> > charts format is already tested, seems little risk or uncertainty in moving the exiting helm v2 charts to v3 but the ML helm charts and their configurations (values files) are fairly large and interconnected.  

**Uncertainty**: <Low> > despite the medium complexity of the job , there are not too many unknowns and one goal of the task is to make the charts more maintainable in the future.  

---

**Tasks**:
- [x] convert the account lookup service charts and subcharts and required dependent charts to helm v3  
- [x] ensure new charts pass circle ci testing (for k8s v20,21,22) 
- [x] figure out what part of the TTK can be used on the account-lookup-service charts (plus other required, e.g. database, kafka etc)
- [ ] update circle CI to incorporate the TTK testing of the updated account-look-service charts

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [x] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @tdaly61 
- QA/Review: TBC

**Comment by tdaly61** [comment]
hey @elnyry-sam-k , this is done BUT as written can't be completed until we have updated the TTK to charts v14, so wondering if we should just close it out for now and have a separate task for TTK testing of v14 charts added to circle-ci ?

**Comment by elnyry-sam-k** [comment]
Thanks @tdaly61 ; What you said makes sense, I'm moving this to review - will discuss with @vijayg10 and @mdebarros on one of the meetings on how best to address the tests (if they should be part of the TTK GP end-to-end tests or if there are ways we can do it on CI)

**Comment by tdaly61** [comment]
I am closing this and marking it as done because the updates were done and merged into the charts repo master branch.  I have delayed marking this as done until now as I was expecting that we would have part of the TTK converted by now to run against the updated account-lookup-service charts,  but this is likely to still be some time off and leaving this open when it is essentially done is not helpful.

**Comment by tdaly61** [comment]
I am closing this and marking it as done because the updates were done and merged into the charts repo master branch.  I have delayed marking this as done until now as I was expecting that we would have part of the TTK converted by now to run against the updated account-lookup-service charts,  but this is likely to still be some time off and leaving this open when it is essentially done is not helpful.
