### ISSUE TITLE
Include bulk-api-adapter TTK Test-Cases in Helm Tests when bulk-api-adapter is enabled

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2590]
## **Goal**:
`As a` Hub Deployer

`I want to` include bulk-api-adapter test collections in the Helm tests
  
`so that` I can validate a fullswitch deployment

**Acceptance Criteria**:
- [ ] Helm deployment tests will include bulk-api-adapter test collections when bulk-api-adapter is enabled on helm deployments
- [ ] Helm deployment tests will NOT be included bulk-api-adapter test collections when bulk-api-adapter is disabled on helm deployments (by default)

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Included in https://github.com/mojaloop/helm/pull/457

```
--------------------FINAL REPORT--------------------

Test Suite:Bulk Tests
Environment:Development
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 134                           │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 134                           │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 0                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 14                            │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 3                             │
├───────────────────┼───────────────────────────────┤
│ Passed percentage │ 100.00%                       │
├───────────────────┼───────────────────────────────┤
│ Started time      │ Thu, 25 Nov 2021 15:13:43 GMT │
├───────────────────┼───────────────────────────────┤
│ Completed time    │ Thu, 25 Nov 2021 15:13:46 GMT │
├───────────────────┼───────────────────────────────┤
│ Runtime duration  │ 3437 ms                       │
└───────────────────┴───────────────────────────────┘
TTK-Assertion-Report-multi-2021-11-25T15:13:46.874Z.html was generated
Terminate with exit code 0
Done
```
