### ISSUE TITLE
Extend the PositionHandler to support position index

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#260]
**Goal**:
As an FSP and Hub Operator
I want to be able to tell the sequence of the transfer processing against an FSP's position
so that I can create the "statement" i.e, sequence of financial actions against an FSP's account.

**Note**: 
- Event logging is handled by story #218

**Tasks**:
- [ ] 

**Acceptance Criteria**:
- [ ] Ability to persist (metadata) event information - transferEventIndex?
- [ ] Ability to replay a transfer through all the stages
- [ ] Ability to extract a sequence of events against an FSP's position 

**Dependencies**:
- [ ] #239 

**Accountability**:
- Owner 
- QA/Review

**Comment by elnyry** [comment]
Duplicate, covered in 2.x items (stories that start with such a number) in 3.x sprints
