### ISSUE TITLE
[docs 2.0] - automate the versioning of docs

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2607]
## **Goal**:
`As a` community member

`I want to` be able to browse past versions of the docs
  
`so that` I can find the docs that are for a specific version of mojaloop

**Acceptance Criteria**:
- [ ] automatic versioning of documentation and deployment of the new versions
- [ ] set of criteria defined for how we go about determining when a new version of the docs should be made

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

We now have some features in the vuepress based docs to be able to display multiple versions of the docs at once.

The challenge is figuring out when to version these docs and what to version them with... should they be tied to helm releases? 

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
We have some basic docs versioning automation set up, so that every push to master will deploy the latest working changes. 

I think for archiving 'old versions' we can either create a manual release each time a new helm version is released, so our docs follow along with the helm versioning scheme.
