### ISSUE TITLE
Central services shared library is taking the resource versions config from RC library

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2608]
## **Goal**:
`As a` mojaloop implementer

`I want to` pass the resource version config to the function calls to the central shared lib
  
`so that` the configuration is consistent across all the core services

**Acceptance Criteria**:
- [ ] Resource version config can be passed as argument to function calls to the central share lib

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
