### ISSUE TITLE
Port new settlement code into micro-frontend.

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2609]
## **Goal**:
`As a` hub operator
`I want to` use the financial portal version 3 with the latest settlement automation functionality
`so that` I can upgrade to V3 and have the same functionality as V2.

**Acceptance Criteria**:
- [ ] Verify that the settlement initialisation report is configured and running when a settlement is initialised.
- [ ] Verify that the finalisation of settlement automation through the loading of a settlement report from the settlement bank is functional.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/reporting-hub-bop-settlements-ui/pull/5
- [x] https://github.com/mojaloop/reporting-hub-bop-settlements-ui/pull/6

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
