### ISSUE TITLE
2.4.10.02 Automated Contract Testing for Mojaloop API - /parties endpoint

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#261]
**Goal**:
As a _Test Engineer_
I would like to _automate testing /parties/{TYPE}/{ID} endpoint in the Mojaloop API_ 
so that the /parties end-point can be tested automatically.

**Tasks**:
- [x] Define Gherkin Scenarios covering positive and negative scenarios for:
  - [x] GET /parties /{TYPE}/{ID}
  - [x] PUT /parties /{TYPE}/{ID}
- [x] Define StepDefinitions implementing the above Gherkin scenarios for:
  - [x] GET /parties /{TYPE}/{ID}
  - [x] PUT /parties /{TYPE}/{ID}
- [x] Across all the above endpoints positive and negative test cases for field lengths, data-types, required/optional fields for requests and responses to be defined and implemented.

**Acceptance Criteria**:
- [x] Tested positive and negative scenarios for the below endpoints, and the results are available as part of Cucumber Report.
  - [ ] GET /parties /{TYPE}/{ID}
  - [ ] PUT /parties /{TYPE}/{ID}
- [ ] Across all the above endpoints the following Headers are accepted and processed by the application: Content-Type  (Code is not ready, need to test when the code is available)
Date    (Code is not ready, need to test when the code is available)
X-Forwarded-For   (Code is not ready, need to test when the code is available)
FSPIOP-Source
FSPIOP-Destination
FSPIOP-Encryption  (Code is not ready, need to test when the code is available)
FSPIOP-Signature   (Code is not ready, need to test when the code is available)
FSPIOP-URI   (Code is not ready, need to test when the code is available)
FSPIOP-HTTP-Method
- [ ] For Negative Test Cases, the application returns the appropriate response code and error code as defined below in the API Specification
  - [x] 400
  - [ ] 401  (Code is not ready, need to test when the code is available)
  - [ ] 403  (Code is not ready, need to test when the code is available)
  - [ ] 404  (Code is not ready, need to test when the code is available)
  - [x] 405
  - [x] 406
  - [ ] 501  (Code is not ready, need to test when the code is available)
  - [ ] 503  (Code is not ready, need to test when the code is available)
  - [x] 3000
  - [x] 3001
  - [x] 3200
  - [x] 3201
  - [x] 3204
  - [ ] 3200  (Code is not ready, need to test when the code is available)
  - [ ] 3100  (Code is not ready, need to test when the code is available)
  - [x] 3101
  - [x] 3102
  - [ ] 3105  (Code is not ready, need to test when the code is available)
  - [ ] 3300  (Code is not ready, need to test when the code is available)
- [ ]  All the test cases defined and implemented in Cucumber should run automatically without any manual intervention

**Dependencies**:
- [ ] #193 

**Accountability**
- Owner @sri-miriyala 
- Review **Design Authority**

**Comment by kjw000** [comment]
Thanks for the story, here are some additional concerns to check:
The GET scenarios should also cover boundary conditions: 
Examples: I GET when there are zero, one, or many IDs

Are there performance criteria for any of these calls?
Are there security/permissions considerations (Ex: I attempt delete when I’m not an admin)?

**Comment by elnyry** [comment]
Thanks Kim.
As you mentioned in the examples part, some of these will be covered in the negative scenarios (as specified in the tasks, acceptance criteria) of the stories.

Performance testing is not part of this story, there are a couple of other stories related to analytics that capture this. Security in general is not part of this but the one scenario similar to the one you mentioned should be part of this task (an FSP trying delete a party that it hasn't provisioned).

**Comment by sri-miriyala** [comment]
Thanks, Kim for the questions. 

The GET scenarios should also cover boundary conditions:
The API specification says that the callback PUT for /parties has a cardinality of 1. 

The callback PUT /parties/<Type>/<ID> (or PUT /parties/<Type>/<ID>/<SubId>) is used to inform the client of a successful result of the Party information lookup. See Table 12 for data model. 
Name    Cardinality         Type               Description 
party          1                   Party         Information regarding the requested Party. 

I will check with the Dev team on how multiple records are handled in the response.

Performance is not being considered in this story. I will work on those stories next. 
Good note about security. I will add it in. But for now Authorization/Authentication is not available in the code yet. For now in my test cases I am having placeholders for security related test cases.
