### ISSUE TITLE
Convert MMD settlement initialisation report into new report format.

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2610]
## **Goal**:
`As a` hub operator 
`I want to` run my settlement initialisation report
`so that` the settlement bank is forwarded the correct settlement information.

**Acceptance Criteria**:
- [ ] Verify that the settlement initialisation report run with the new operator pattern format.
- [ ] Verify that only anonymised data is included in the report
- [ ] Verify that the report is added to a new public reporting repository (naming convention tbc)
---

**Tasks**:
- [x] Convert MMD settlement initialization report into new report format
- [x] Create helm charts for reports
- [x] Create a separate GitHub repo for storing public reports
- [x] Create CI/CD scripts for automated helm repo creation.

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
