### ISSUE TITLE
Multi-currency settlement

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2611]
## **Goal**:
`As a` hub operator that supports multi-currency transfers
`I want to` us the financial portal v3 
`so that` initiate and finalise settlement

**Acceptance Criteria**:
- [ ] Verify that settlement can be viewed, initialised and finalised separately for each currency within a settlement window
- [ ] Verify that the settlement UI displays the currency correctly where appropriate.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Here is a UI design for this.
https://modusbox.atlassian.net/wiki/spaces/mboxPortals/pages/1742962989/Extend+Settlement+screens+for+multicurrency
