### ISSUE TITLE
[docs] - puml diagrams aren't rendering

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2612]
**Summary**:
I don't know how we overlooked this, but the puml hasn't been converted properly for docs 2.0.

See: https://docs.mojaloop.io/next/api/fspiop/v1.1/api-definition.html#http-post-call-flow

My proposed approach for this was to use a git commit hook to render any changed diagrams as they were modified, and then and CircleCI job to make sure that all of the diagrams were up to date.

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**

**Steps to Reproduce**
  1.
  2.
  3.

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

## Tasks:

- [x] get static puml rendering to .svg for one example page
- [ ] port over puml from legacy docs:
  - [x] api definitions
- [ ] add git commit hooks to automatically re-render changed puml sources
- [ ] add a ci check to make sure all puml and svg are in sync

**Notes**:

- Severity when opened:
- Priority when opened:
