### ISSUE TITLE
Automated releases for documentation 

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2613]
## **Goal**:
`As a`maintainer
`I want to` automatically publish a new version of the docs every time there is a change
`so that` I can view the latest docs without running a manual release

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:

The current automation creates a new version with the vuepress versioning tool every time a new tag is pushed to the repository. That means that until we push a new tag, the 'latest' version of the docs is hidden behind the 'next' selection in the navigation bar. 

As discussed yesterday with @elnyry-sam-k, the best approach would be to have the latest docs as default, published every time a commit to `master` is made, and a 'historical' version archived each time a new release is made to `mojaloop/helm`. Such an approach gives us a balance between always seeing the latest docs, while keeping older versions published for posterity.

- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/documentation/pull/349

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Automated releases are now in place for docs
