### ISSUE TITLE
Perform an open source security scan on the Payment Manager Source Code

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#2617]
## **Goal**:
`As a` security specialist

`I want to` perform an open-source security scan on the payment manager source code 
  
`so that` I can ensure that there are no high-risk security vulnerabilities and also confirm conformance with the Mojaloop open source license policy 

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Low 

**Uncertainty**: Low  

---

**Tasks**:
- Prepare scanning instructions
- Execute the scan
- Generate the report
- Analysis of the findings
- Present the findings to the code owner
- Agree on remediation activities with the code owners - new or old

**Done**
- [x] Acceptance Criteria pass
- [ ] Designs are up-to date
- [x] Unit Tests pass
- [ ] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @lewisdaly

**Comment by godfreykutumela** [comment]
OSS scan completed - results to be presented to the FRMS team on the 12th Jan 2022 @JBornman @JustusOrtlepp

**Comment by elnyry-sam-k** [comment]
@godfreykutumela - can you please share with @PaulGregoryBaker , Bryan S (who are the owners of Payment Manager) and the DA as well please?

**Comment by godfreykutumela** [comment]
Hi @elnyry-sam-k this was meant for the FRMS OSS scan issue, my apologies posted this in the wrong issue.

I have forwarded the payment manager OSS scan results to lewis to share with relevant people who needs to know what about it.

**Comment by elnyry-sam-k** [comment]
Thanks @godfreykutumela, got it..
