### ISSUE TITLE
Support IaC workstream to use TTK for regression tests

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2618]
## **Goal**:
`As a` individual implementer

`I want to` have a pipeline job in IaC for TTK GP tests
  
`so that` I can run TTK test suite instead of postman test suite in IaC deployments

**Acceptance Criteria**:
- [x] TTK setup and GP can be run through a manual job in CICD pipeline
- [x] HTML report can be stored in Job artifacts in gitlab

**Complexity**: Medium
**Uncertainty**: Low

---

**Tasks**:
- [x] Make helm test command work within a pipeline
- [x] Investigate the possibilites to get html report out of a completed pod in pipeline
- [x] Create a pipeline to execute TTK tests using TTK CLI to have more control instead of running helm test
- [x] Store HTML report in Job artifacts
- [x] Parameterise the variables in the job

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
