### ISSUE TITLE
Central Service Integration-test runner script

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#262]
**Goal**:
As a developer I would like to 
_Implement integration test runner_
so that the all integration tests will be executed against any backend dependency/systems.

**Tasks**:
- [x] re-align script to latest integration test methodologies [ @mdebarros ]
- [x] update script to include kafka
- [x] update script to change postgresql to mysql
- [x] test script

**Acceptance Criteria**:
- [x] Integration runner will startup backend dependency - mysql server
- [x] Integration runner will startup backend dependency - kafka server
- [x] Integration runner will execute all integration scripts

**Dependencies**:
- n/a

**Accountability**
- Owner @mdebarros                        
- Review

**Comment by mdebarros** [comment]
PR for this story for merging into @rmothilal base code: https://github.com/rmothilal/central-ledger/pull/17

**Comment by mdebarros** [comment]
Merged into https://github.com/mojaloop/project/issues/154 codebase
