### ISSUE TITLE
Build the Segregation of Duties workflow checks into IaC

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2621]
## **Goal**:
`As a` Hub Operator
`I want to` be able to load a new/or update an existing RBAC security policy without the possibility of violating a segregation of duties restriction
`so that` I can maintain the RBAC security without ever violating segregation of duties

**Acceptance Criteria**:
- [ ] Verify that a pre merge PR hook in the IaC calls the user role operation validation API with the security PR changes.
- [ ] Verify that the PR fails if a violation is found
- [ ] Verify that the user role assignments cannot be changed during the merging of the PR and before the new security CRs are published.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
