### ISSUE TITLE
add demos to docs getting started page

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2622]
## **Goal**:
`As a` community member

`I want to` have easy access to Mojaloop demo videos
  
`so that` I can see how mojaloop can be used and easily share these demos

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] In the demos page, we should embed all the videos listed in [this](https://docs.google.com/spreadsheets/d/1txuDp8hlCJtUX34-1-aXzawGQNodDKm8/edit#gid=949371532) doc (under the “Mojaloop demos” tab)

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/documentation/pull/357

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@simeonoriko I think we need to change some settings on youtube - I'm getting the following error when I try to embed the videos:

![video_disabled.png](https://images.zenhubusercontent.com/5cd963af3613073e20e46e60/4c57d16f-64b5-46cb-adc1-dfcc08e6b5a0)

**Comment by simeonoriko** [comment]
I'll check with the Virtual team and get back @lewisdaly

**Comment by lewisdaly** [comment]
@simeonoriko it looks like it's working now: https://docs.mojaloop.io/next/getting-started/demos/inside-the-loop.html
