### ISSUE TITLE
[ttk] - want to be able to specify a nested value in callback rules (Firefox Issue)

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2624]
## **Goal**:
`As a` QA engineer

`I want to` have flexibility in the callback rules
  
`so that` I can test a wide variety of test cases

**Acceptance Criteria**:
- [ ] Verify that the user has the ability to specify a nested value in callback rules
- [ ] Verify that this works in FireFox (working in Chrome)
- [ ] Manual Testing Approved

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

I'm trying to modify the callback rules in the TTK so that when a `POST /transfers` is received by the TTK with a certain `amount.amount`, I can specify custom behaviour, such as sending a `PUT /transfers/{ID}` callback with a `transferState: reserved`.

At the moment, the rules UI only lets me select top level elements, such as `body.transferId` or `body.amount`, but not nested values, such as `body.amount.amount`. This makes it hard to configure custom behaviour, and instead I need to rely on fields such as the `transferId` to evaluate rules and apply custom callback behaviour. 

This doesn't work long term since Mojaloop will reject transfers with the same Id. 

Here's a screenshot for more context. I tried to just use the top level `body.amount` with a JSON string, but this didn't seem to work. 

![ttk_amount.png](https://images.zenhubusercontent.com/5cd963af3613073e20e46e60/5db0cf8c-f38b-452b-a044-07bd824b536b)

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Thanks @vijayg10  - what version did that get added with? When I install Mojaloop `13.0.2` I get `mojaloop/ml-testing-toolkit-ui:v13.5.2`, which doesn't have that UI

**Comment by vijayg10** [comment]
@lewisdaly I am using the same version mojaloop/ml-testing-toolkit-ui:v13.5.2.

I can see your issue now. I think you are using "SYNC RESPONSE RULES" instead of "CALLBACK RULES"
Please use "CALLBACK RULES" to customise asynchronous callbacks.

But you are right, there is an issue with the rulesUI for "SYNC RESPONSE RULES". It should be fixed. I will keep this story open and to fix the Sync response rules UI.
For your use-case you can go ahead with "Callback Rules".

**Comment by lewisdaly** [comment]
We discussed this at the end of last year. It turns out to be an issue with the TTK UI on firefox. When using chrome, the UI elements appeared as expected.

**Comment by elnyry-sam-k** [comment]
This is a browser specific issue with firefox
