### ISSUE TITLE
[pisp-e2e] - Establish a performance baseline for PISP happy path flows

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2625]
## **Goal**:
As a hub operator, I want to understand the performance characteristics of the 3PPI APIs, so that I can plan a real deployment with a real SLA accordingly

**Acceptance Criteria**:
- [ ] Performance tests that demonstrate happy path linking and transfer processes
- [ ] A short document in the pisp documentation that describes the high level performance of the PISP use cases
- [ ] A backlog of performance improvement tasks/stories that can be implemented at a later date to improve the performance of the tested use cases

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] on one of the moja dev environments, write or find existing performance test automation to establish a performance baseline for E2E tests
- [ ] write performance tests for PISP account linking happy path scenario
- [ ] write performance tests for PISP transfer happy path scenario
- [ ] on the same hardware, compare the PISP happy path transfer scenario and 'vanilla' mojaloop P2P transfer 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- [ ]  Can we include some of the performance tests in our CI/CD automation to better keep track of the performance baselining?

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
