### ISSUE TITLE
Research, Plan and Implement Custom Code Security Scanning(Aka Static Code Analysis(SCA)) Processes and Tools

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#2633]
## **Goal**:
`As a` Security Advisor

`I want to introduce code security scanning processes and tools
  
`so that` all contributed code can be security vetted, focusing on malicious backdoors, and approved to be safe to use by our adopters.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**:  Medium - It is slightly complex to do this using open source tools

**Uncertainty**:  High - We may not have enough security and DevOps resourcing to execute on this.

---

**Tasks**:
- [ ] Research the open-source code security options
- [ ] Define the code security scanning process, policy and integrate it into our CI/CD pipeline
- [ ] Run a POC using at least two tools
- [ ] Adopt a solution and present it to the security workstream for approval.
- [ ] Implement the solution and start using it from Pi 17, if feasible
- [ ] Generate ad-hoc, bi-weekly, and monthly code security scanning reports

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela @lewisdaly @MichaelJBRichards @pedrosousabarreto @mdebarros 
- QA/Review: @godfreykutumela @MichaelJBRichards

**Comment by godfreykutumela** [comment]
Hi @lewisdaly and @MichaelJBRichards do want to add any action or recommendation to this issue before I roll it over to the next PI?

**Comment by godfreykutumela** [comment]
I will set up a meeting with Github Executive for DevSecOps to update us on the latest Github security eco system including SCA.

**Comment by godfreykutumela** [comment]
We have decided on Github's CodeQL as our SAST tool and implementation is planned now in PI 19!
