### ISSUE TITLE
Finance-portal-backend-service must handle settlementEndpoint configs consistently

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2639]
## **Goal**:
`As a` Finance-portal deployer

`I want to` configure the settlementEndpoint in a consistent fashion
  
`so that` only a single config param is used to manage the settlement API endpoint

**Acceptance Criteria**:
- [ ] Finance-portal-backend-service utilises a single config param for the Settlement Endpoint
- [ ] Implement any backwards-compatibility measures if possible (to be confirmed)

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
