### ISSUE TITLE
2.4.90.30.01 Design for implementing Central Services API through a Swagger Design First Approach

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#264]
**Goal**:
As a contributor
I would like to _design for implementing Central Services through a Swagger Design First Approach_
so that API, Validations are generated from the Swagger

**Tasks**:
- [ ] Review and validate Hapi-openAPI (https://github.com/krakenjs/hapi-openapi) plugin for Swagger Design First Approach
- [ ] Design for implementing the Central Services through a Swagger Design First Approach
- [ ] Review the design with DA

**Acceptance Criteria**:
- [ ] Swagger defining interface for Central Services
- [ ] The design is reviewed by DA

**Dependencies**:
- n/a

**Accountability**:
- Owner
- Review **Design Authority**
