### ISSUE TITLE
DFSP names missing in Settlement Details window

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#2645]
**Tasks**: 
- [x] Port over latest commits from Settlement feature in Financial Portal v2
- [x] Investigate root cause of bug 
- [x] Implement fix for bug
- [x] UI test to assert that name appears

**Summary**:
With the new version of BizOps framework, I noticed the DFSP names missing in the settlement details view page.
<img width="901" alt="Screen Shot 2022-01-18 at 11 45 21 AM" src="https://user-images.githubusercontent.com/38143240/149981069-8f701db1-a5fa-44fb-bcd0-ed4b0fa52298.png">

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**
DFSP names to be visible on the settlement details view.

**Steps to Reproduce**
  1. Send transfers
  2.Close the window
  3. Go to settlement page
  4. Click on the settlement ID
  5. Check the settlement ID is missing

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: Sri

**Notes**:

- Severity when opened:
- Priority when opened:
