### ISSUE TITLE
Quaterly OSS scan on the Mojaloop core

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#2648]
## **Goal**:
`As a security specialist

I want to perform an open-source security scan on the Mojaloop core source code

so that I can ensure that there are no high-risk security vulnerabilities and assess conformance with the Mojaloop open source license policy

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] Prepare scan instructions @godfreykutumela 
- [ ] Execute the scan @lewisdaly 
- [ ] Analysis and reporting @lewisdaly @godfreykutumela 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @lewisdaly
