### ISSUE TITLE
Implement Central Services API for get://Notifications service through a Swagger Design First Approach

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#265]
**Goal**:
As a developer
I would like to _Implement Central Services API for get://Notifications service through a Swagger Design First Approach_
so that API, Validations are generated from the Swagger

**Tasks**:
- [ ] Implement Central Services API for get://Notifications service through a Swagger Design First Approach

**Acceptance Criteria**:
- [ ] Swagger defining interface for Central Services
- [ ] Generate routes/handlers for API Rest end-points using https://github.com/krakenjs/hapi-openapi
- [ ] Create new stories for implenting each of the routes/handlers generated by hapi-openapi

**Dependencies**:
- [ ] #264

**Accountability**:
- Owner
- Review **Design Authority**
