### ISSUE TITLE
Run 3PPI TTK tests with 3PPI services enabled

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2650]
## **Goal**:
`As an` adopter of Mojaloop (and 3PPI services)

`I want to` be able to take the 3PPI TTK end-to-end tests available and run them successfully
  
`so that` I can be assured of the quality of the releases (and that the tests pass with expected results)

**Note**: This is a follow-up to the Epic: https://github.com/mojaloop/project/issues/2385

**Acceptance Criteria**:
- [x] On a standard (using a Mojaloop helm release) Mojaloop deployment, setup for 3PPI services is done
- [x] The 3PPI TTK end-to-end tests are run
- [ ] Bugs are logged for any failures, if the pass-rate is not 100%
- [ ] Update documentation as relevant

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Get a Mojaloop deployment (using a helm release) with 3PPI services enabled
- [x] Get 3PPI TTK end-to-end test suites running
- [ ] If the pass rate is not 100%, log bugs for failures

**Done**
- [ ] Acceptance Criteria pass
- [ ] Bugs are logged for failures with priority, severity assigned

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@mdebarros  added the thirdparty-sdk for the simulators in `helm/mojaloop-simulator`

https://github.com/mojaloop/helm/blob/master/mojaloop-simulator/values.yaml#L29-L38

So to turn 'on' the 3p api features in our simulated DFSPS, you just need to change that field in the `values.yaml`

**Comment by mdebarros** [comment]
> https://github.com/mojaloop/helm/blob/master/mojaloop-simulator/values.yaml#L29-L38

Thanks @lewisdaly, does that mean we need to have **new** simulators configured for testing 3P API Features? Or can we just bolt it on one of our existing simulators?

**Comment by mdebarros** [comment]
Thirdparty helm test setup collection: ml-ttk-test-setup-tp
```
--------------------FINAL REPORT--------------------
Test Suite:Thirdparty Provisioning Collection
Environment:Development
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 137                           │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 137                           │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 0                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 135                           │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 15                            │
├───────────────────┼───────────────────────────────┤
│ Passed percentage │ 100.00%                       │
├───────────────────┼───────────────────────────────┤
│ Started time      │ Thu, 10 Mar 2022 15:53:10 GMT │
├───────────────────┼───────────────────────────────┤
│ Completed time    │ Thu, 10 Mar 2022 15:53:25 GMT │
├───────────────────┼───────────────────────────────┤
│ Runtime duration  │ 15710 ms                      │
└───────────────────┴───────────────────────────────┘
```

Thirdparty verification tests: ml-ttk-test-val-tp
```
--------------------FINAL REPORT--------------------
Test Suite:Thirdparty Tests
Environment:Development
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 21                            │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 21                            │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 0                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 20                            │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 8                             │
├───────────────────┼───────────────────────────────┤
│ Passed percentage │ 100.00%                       │
├───────────────────┼───────────────────────────────┤
│ Started time      │ Thu, 10 Mar 2022 15:53:31 GMT │
├───────────────────┼───────────────────────────────┤
│ Completed time    │ Thu, 10 Mar 2022 15:53:35 GMT │
├───────────────────┼───────────────────────────────┤
│ Runtime duration  │ 4375 ms                       │
└───────────────────┴───────────────────────────────┘
TTK-Assertion-Report-multi-2022-03-10T15:53:35.561Z.html was generated
Terminate with exit code 0
Done
```

**Comment by lewisdaly** [comment]
That's awesome @mdebarros @kleyow !

**Comment by mdebarros** [comment]
Issue tested with [v13.1.0 release](https://github.com/mojaloop/project/issues/2528).
