### ISSUE TITLE
Document FSPIOP version v1.1 and v1.0 support in mojaloop deployments

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2658]
## **Goal**:
`As a` Scheme

`I want to` understand the usage of FSPIOP API v1.1 and v1.0
  
`so that` I can understand how backwards compatibility works and how to support multiple versions if required and plan deployment scenarios based on that

**Acceptance Criteria**:
- [ ] A document is published that explains usage of Mojaloop releases that support versions v1.1 and v1.0 (and links to the features supported) and discusses deployment scenarios to support both.

**Complexity**: High

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
