### ISSUE TITLE
Explore usage of v1.1 and v1.0 with same mojaloop release

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2660]
## **Goal**:
`As an` adopter of Mojaloop

`I want to` understand if a Mojaloop release (v13.1.0 RC) can support FSPIOP API v1.1 and v1.0 (in headers)
  
`so that` I can plan adoption and deployment accordingly

**Acceptance Criteria**:
- [x] An understanding of what steps, features, measures, changes are needed to have backwards compatibility for FSPIOP API v1.0 with the v13.1.0 Mojaloop release (which is v1.1) is documented

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [x] Document the delta (changes needed) to support FSPIOP API v1.1 and v1.0 (backwards compatibility without deploying multiple instances of services, etc)
  - [x] code changes needed
  - [x] configuration changes needed
  - [x] Helm changes needed
  - [x] Create follow-up stories needed based on the findings
- [x] Identify tests and testing scenarios needed
  - [x] create a separate story for TTK test-cases

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
# Delta changes neeed:

## Code changes

Currently, the Content-type is [validated](https://github.com/mojaloop/central-services-shared/blob/master/src/util/hapi/plugins/headerValidation.js#L89) against a single value injected by a config (e.g. [ml-api-adapter](https://github.com/mojaloop/ml-api-adapter/blob/master/config/default.json#L10)) that matches as follows:

```JSON
"PROTOCOL_VERSIONS": {
    "CONTENT": "1.1", <-- used to validate the content-type header, and value used for content-type headers when requests are generated by the "switch"
    "ACCEPT": {
      "DEFAULT": "1",  <--  value used for accept headers when requests are generated by the "switch"
      "VALIDATELIST": [ <-- used to validate the accept headers
        "1",
        "1.1"
      ]
    }
  }
```

To improve the backward compatibility the following changes can be made:


1. Config Changes

Split the content section to match the accept structure as follows:

```JSON
"PROTOCOL_VERSIONS": {
    "CONTENT": {
      "DEFAULT": "1.1", <--  value used for content-type headers when requests are generated by the "switch"
      "VALIDATELIST": [ <-- used to validate the content-type headers
        "1.0",
        "1.1"
      ]
    }
    "ACCEPT": {
      "DEFAULT": "1", <--  value used for accept headers when requests are generated by the "switch"
      "VALIDATELIST": [ <-- used to validate the accept headers
        "1",
        "1.0",
        "1.1"
      ]
    }
  }
```


1. Central-Services-Shared
Currently, the Content-type is [validated](https://github.com/mojaloop/central-services-shared/blob/master/src/util/hapi/plugins/headerValidation.js#L89) against a single value injected by a config (e.g. [ml-api-adapter](https://github.com/mojaloop/ml-api-adapter/blob/master/config/default.json#L10)) that matches as follows:

```
"PROTOCOL_VERSIONS": {
    "CONTENT": "1.1", <-- used to validate the content-type header, and value used to generate content-type headers from the "switch"
    "ACCEPT": {
      "DEFAULT": "1", <--  value used to generate accept headers from the "switch"
      "VALIDATELIST": [ <-- used to validate the accept headers
        "1",
        "1.1"
      ]
    }
  }
```





https://github.com/mojaloop/ml-api-adapter/blob/master/config/default.json#L11

##Configuration changes

**Comment by mdebarros** [comment]
Further thinking about this, and taking into consideration that the swagger already validates the incoming CONTENT-TYPE to make sure it matches a `#.#` pattern, i.e. it will fail validation up-front if someone sends the following: `application/vnd.interoperability.transfers+json;version=1`

This will result in the following sync error:

```
{
  "status": 400,
  "statusText": "Bad Request",
  "body": {
    "errorInformation": {
      "errorCode": "3101",
      "errorDescription": "Malformed syntax - Invalid content-type header"
    }
  },
  "headers": {
    "content-type": "application/json; charset=utf-8",
    "cache-control": "no-cache",
    "content-length": "109",
    "date": "Thu, 10 Feb 2022 08:54:36 GMT",
    "connection": "keep-alive"
  }
}
```

Taking this into consideration, we could further simplify the config to the following:

```
"PROTOCOL_VERSIONS": {
  "CONTENT": {
    "DEFAULT": "1.1", <-- same as initial proposal
  }
  "ACCEPT": {
    "DEFAULT": "1",  <-- same as initial proposal
  },
  "VALIDATELIST": [ <-- used to validate incoming ACCEPT & CONTENT-TYPE headers
    "1", <-- this would be filtered out by the swagger validation for CONTENT-TYPE, but it does make the assumption that the swagger will always filter out this kind of request which is a concern.
    "1.0",
    "1.1"
  ]
}
```

However, I am still leaning toward my initial proposal based on my in-line comment above.

Just including this here as part of the thought process.

**Comment by mdebarros** [comment]
- [ ] Core-services support for non-breaking backward API compatibility for PROTOCOL_VERSION configs -  https://github.com/mojaloop/project/issues/2704

**Comment by mdebarros** [comment]
> The following stories/issues have been created as a result of this investigation:
> 
> * [ ]  Core-services support for non-breaking backward API compatibility for PROTOCOL_VERSION configs -  [Core-services support for non-breaking backward API compatibility for PROTOCOL_VERSION configs #2704](https://github.com/mojaloop/project/issues/2704)
> * [ ]  API-Snippets to support generating backwards compatible OpenAPI Definitions [API-Snippets to support generating backwards compatible OpenAPI Definitions #2706](https://github.com/mojaloop/project/issues/2706)
> * [API-Snippets to support generating backwards compatible OpenAPI Definitions #2706](https://github.com/mojaloop/project/issues/2706)
> * [ ]  API Validations against multiple OpenAPI definitions to support backward compatibility [API Validations against multiple OpenAPI definitions to support backward compatibility #2707](https://github.com/mojaloop/project/issues/2707)
> * [API Validations against multiple OpenAPI definitions to support backward compatibility #2707](https://github.com/mojaloop/project/issues/2707)
> * [ ]  Integrate API-Snippets into Core components - [Integrate API-Snippets into Core components #2708](https://github.com/mojaloop/project/issues/2708)
> * [ ]  GP tests to validate backward compatibility use-cases - [GP tests to validate backward compatibility use-cases #2709](https://github.com/mojaloop/project/issues/2709)

@elnyry-sam-k am I missing anything from this list?
