### ISSUE TITLE
Ref Arch Documentation Review: Introduction Page

### ISSUE THREAD

**Issue by mwmentor** [mojaloop/project#2662]
## **Errors and Omissions**
The following errors and omissions have been noted and need attention:

**Copy**
- [x] Page intro - What is... - improve paragraphing for easier reading.  Viz.: the Reference Architecture statement could be on its own line with line-space above and below for better and more impactful reading
- [x] Section titles are not consistent.  Viz.: Rewrite the "Objectives" heading as "What are the objectives of... "
- [x] Solution space copy requires improved paragraphing and the language usage in the BC and UL sub-sections require checking

**Images**
- [x] Add Alt. Text to images

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mwmentor** [comment]
I have completed the improvements noted and have created [PR #65](https://github.com/mojaloop/reference-architecture-doc/pull/65).  I have invited @pedrosousabarreto to review.
