### ISSUE TITLE
Ref Arch Documentation Review: Reference Architecture Section

### ISSUE THREAD

**Issue by mwmentor** [mojaloop/project#2663]
## **Errors and Omissions**
The following errors and omissions have been noted and need attention:

**Copy**
 - [x] Copy issues - there are a number of issues to resolve including image spaces that have been retained but not used.
 - [x] Incomplete notes - see the BC and CCC sections of the page and update accordingly
 - [x] List formatting needs to be improved - make key terms bold and the description normal text
 
**Images**
 - [x] Check image scaling and make them consistent with the rest of the document
 - [x] Update images to remove gaps in layouts and exclude stickies unless they are relevant to the audience
 - [x] Add Alt. Text to images
 - [ ] Where images include embedded URLs, create a list below the image to include the links
 - [x] Solution Space image resolution very poor

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mwmentor** [comment]
Solution Space image:

- Remove details
- Increase font size
- Maintain arrows
- Republish

**Comment by mwmentor** [comment]
Busy with this presently... forgot to pull it into WIP...

**Comment by mwmentor** [comment]
Tasks completed (I am still not entirely satisfied with the images.  Will review at a later date if there is time.  They will do for now).  [PR #64](https://github.com/mojaloop/reference-architecture-doc/pull/64) created.  Referred to @pedrosousabarreto for review.

**Comment by mwmentor** [comment]
Responded to review by @pedrosousabarreto - removed references to "Mojaloop 2.0", and replaced them with "Mojaloop" only.  [PR#64](https://github.com/mojaloop/reference-architecture-doc/pull/64) has been updated accordingly and is ready for a second review.  Thanks.
