### ISSUE TITLE
Ref Arch Documentation Review: Common Terms

### ISSUE THREAD

**Issue by mwmentor** [mojaloop/project#2665]
## **Errors and Omissions**
The following errors and omissions have been noted and need attention:

**Copy**
- [x] All external references to be added to page footnotes
- [x] All external references require a URL

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mwmentor** [comment]
I have completed the updates noted in this ticket.  They are included in [PR#66}(https://github.com/mojaloop/reference-architecture-doc/pull/66).  I have requested @pedrosousabarreto to review and revert should he find any issues.
(I noted an issue that may or may not be an issue in the live document - for some reason, anchors using the # reference don't seem to work too well.  For example, I find that `../../furtherReading/README.md#reference-articles-and-documents` will navigate to the page (Further Reading), but not the anchor point which I did not expect.  Perhaps someone could ping me regarding this as it is possible that I have done something wrong.  Thanks.)
