### ISSUE TITLE
Ref Arch Documentation Review: Account Lookup & Discovery

### ISSUE THREAD

**Issue by mwmentor** [mojaloop/project#2666]
## **Errors and Omissions**
The following errors and omissions have been noted and need attention:

**Copy**
- [x] Terms table - term name needs to be made **bold** 

**Images**
- [x] Functional Overview image needs to be scaled in accordance with the scaling in use for the other images on the page.
- [x] Add Alt. Text to images
- [ ] Where images include embedded URLs, create a list below the image to include the links

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mwmentor** [comment]
I have noted an error with the URLs included with the Party/Participant Associate, Disassociate, and Get Party POST link URLs - they all 404.  I have done some sniffing and have found that the URL has been updated: it was `https://docs.mojaloop.io/mojaloop-specification/fspiop-api/documents/API%20Definition%20v1.1.html` but should probably now be: `https://docs.mojaloop.io/api/fspiop/v1.1/api-definition.html` with no anchors... I have asked @pedrosousabarreto and @MichaelJBRichards (BC Owner) for assistance.

**Comment by mwmentor** [comment]
I am placing this ticket in Blocked for now.

**Comment by mwmentor** [comment]
The updates for this Ticket have been merged with the main document and the branch (PR#67) deleted.  @MichaelJBRichards has been notified.  This ticket will now be closed as the associated PR has been approved notwithstanding the 404 URLs in some of the images.  Thanks.
