### ISSUE TITLE
Ref Arch Documentation Review: Accounts & Balances

### ISSUE THREAD

**Issue by mwmentor** [mojaloop/project#2667]
## **Errors and Omissions**
The following errors and omissions have been noted and need attention:

**Copy**
- [ ] Intro - please review and add a point regarding how the Accounts and Balances BC prevents duplicate journals from being created to the explainer "Note"
- [ ] Intro - check the points in the explainer "Note" - the first point is alpha (a) and the second point, numeric (2)
- [ ] Terms - highlight term names using bold
- [ ] General - please covert points into sentences to align with the overall approach to the documentation

**Images**
- [ ] Functional Overview - please scale per the look and feel of the images in other BC sections
- [ ] Add Alt. Text to images
- [ ] Where images include embedded URLs, create a list below the image to include the links

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mwmentor** [comment]
@koekiebox:  Hi Jason... In the next few days I intend to begin tweaking the Ref Arch document where indicated.  I wanted to ask you if you could let me how the Accounts & Balances BC takes care of preventing duplicate journal entries from occurring?  Thanks so much and have a great day :-)

**Comment by tselit** [comment]
Hi @mwmentor 
When you have a moment, are you able to please also take a look at the content of the "Note" sub-section? I think the third numbered item is supposed to be (c) but has been resolved to the copyright symbol.

**Comment by mwmentor** [comment]
Hi @tselit - thanks for the feedback.  I'll take a look... :-)

**Comment by mwmentor** [comment]
> 

Hi @tselit - I have resolved the issue... it seems that the best way to avoid is just to create a gap on either side of the letter, so I have done so on each of the letters, viz. ( a ), ( b ), ( c ).  Good catch, and it does not show up in VSC, so interesting... :-)

**Comment by mwmentor** [comment]
> 

@tselit Hi Tšeli:  I checked it out and escaping both parentheses works so, like this \(c\) and that sorts the problem out... what fun... :-)

**Comment by mwmentor** [comment]
These tweaks have been completed and merged.
