### ISSUE TITLE
Review CR#107 to 3PPI API and document observations

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2668]
## **Goal**:
`As a` 3PPI adopter

`I want to` understand the changes to implementation that the API change request: https://github.com/mojaloop/mojaloop-specification/issues/107 implies
  
`so that` I can have an estimate of implementation changes needed and publish a newer version with changes needed

**Acceptance Criteria**:
- [ ] Document observations on the CR (if it can be approved or if there are concerns)
- [ ] Document changes needed in implementation to achieve this and make releases on 3PPI services 
- [ ] Verify that outline and estimations for tests cases are included

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [x] Document observations on the CR (if it can be approved or if there are concerns)
- [x] Document changes needed in implementation to achieve this and make releases on 3PPI services 
- [x] Verify that outline and estimations for tests cases are included

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
