### ISSUE TITLE
ALS v14 charts

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2674]
## **Goal**:
`As an` adopter of Mojaloop v14 charts

`I want to` have a version of v14 ALS charts that are well tested and validated
  
`so that` I can ensure compatibility with the standards adopted with Mojaloop v14 and then can be used as template for the rest of the Mojaloop components

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
