### ISSUE TITLE
TTK - 5000 port is being used by airplay receiver (control centre) in MacOS

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2675]
## **Goal**:
`As a` individual implementer

`I want to` deploy TTK in my mac machine
  
`so that` I can use it for my development.

**Acceptance Criteria**:
- [x] TTK should listen on some non-standard ports (not used by other known services)

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Discuss with the team and agree on the ports to be used for TTK (Currently it is using 5000, 5050, 6060)
- [x] Change the ports in nodejs and docker
- [x] Change the ports in helm chart and corresponding variables in mojaloop chart
- [x] Change the documentation with new ports
- [ ] ~Change MTP course with new ports~
- [ ] ~Upgrade TTK in PM4ML on-premise-deploy repo and corresponding config~
- [ ] ~Inform the IaC work stream about the change in ports~

**Done**
- [x] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
https://developer.apple.com/forums/thread/682332

**Comment by millerabel** [comment]
I think we should move to a new port. AirPlay is used to project presentations which is a natural part of the developer experience. Disabling AirPlay is not a practical solution.

TTK should not use a well-known port.

On Feb 8, 2022, at 4:04 AM, vijayg10 ***@***.***> wrote:

﻿
Goal:

As a individual implementer

I want to deploy TTK in my mac machine

so that I can use it for my development.

Acceptance Criteria:

 Instructions should be added in the documentation to disable airplay which listens on port 5000
Complexity: Low

Uncertainty: Low

Tasks:

 TBD [ @? ]
Done

 Acceptance Criteria pass
 Designs are up-to date
 Unit Tests pass
 Integration Tests pass
 Code Style & Coverage meets standards
 Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
 TBD
Pull Requests:

 TBD
Follow-up:

N/A
Dependencies:

N/A
Accountability:

Owner: TBC
QA/Review: TBC
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by elnyry-sam-k** [comment]
Thanks for the inputs, Miller. Yes, changing to a non-standard port (not used by other known services) is the way to go.

**Comment by vijayg10** [comment]
Thanks @millerabel and @elnyry-sam-k, I will change the story according to that.
