### ISSUE TITLE
Ref Arch Documentation Review: Auditing BC

### ISSUE THREAD

**Issue by mwmentor** [mojaloop/project#2679]
## **Issues to Fix**
The following issues have been noted and require tweaks:

**Copy**
- [x] Copy layout needs to be reviewed - layout order needs to follow: Title, Intro, Terms, Functional Overview Image, UCs...

**Images**
- [x] Functional Overview image - scale is too large
- [x] UC Images - scale is too small
- [x] UC- Calculate Quote - Invalid Quote Request - copy typeface size varies
- [x] UC- Calculate Quote - Invalid Scheme Rules detected in response - copy typeface size varies; image has background noise on top right and top margin (image boundary)
- [x] Add Alt. Text to images
- [ ] Where images include embedded URLs, create a list below the image to include the links

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mwmentor** [comment]
I have completed the tasks noted in this ticket.  I have pushed [PR #69](https://github.com/mojaloop/reference-architecture-doc/pull/69) and have requested @godfreykutumela and/or @pedrosousabarreto to review and revert should they hit any snags.  I am moving this ticket to review.

**Comment by mwmentor** [comment]
@godfreykutumela Has responded per [Slack](https://mojaloop.slack.com/archives/C01P7PFD9RN/p1649679627120019) noting that he has approved [PR #69](https://github.com/mojaloop/reference-architecture-doc/pull/69) for merging.  Thank you Godfrey! :-)
