### ISSUE TITLE
2.4.20.03 Deploy updated codebase based on PI2 architecture for Prepares (k8s) on AWS

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#268]
**Goal**:
As a contributor
I would like to _deploy the updated codebase based on PI2 architecture for Prepares_
so that initial testing, analytics can be done.

**Tasks**:
- [x] Deploy updated codebase based on PI2 architecture for Prepares (k8s) on AWS (once it is ready)
- [x] Verify compatibility with ml-api-adapter

**Acceptance Criteria**:
- [x] An updated version of the codebase based on PI2 architecture, with Prepares completed is deployed.
- [ ] Some sanity testing is done to ensure ml-api-adapter compatibility

**Dependencies**:
- [x] Updated codebase availability
- [x] #176 

**Accountability**:
- Owner
- Review

**Comment by elnyry** [comment]
Blocked on #176

**Comment by elnyry** [comment]
Covered deployment tasks here and moving on to the deployment of the demo code
