### ISSUE TITLE
Ref Arch Documentation Review: FSPIOP BC

### ISSUE THREAD

**Issue by mwmentor** [mojaloop/project#2680]
## **Issues to Fix**
The following issues have been identified and require fixing:
 
**Copy**
- [ ] Page layout - order of items;
- [ ] Copy - general comment is that the language used in this BC is notably different than other BCs.  It has been updated to reflect workflow journeys and is quite technical in nature.  In some discussions, it was noted that granularity in the Descriptions is not a good idea in order to avoid requiring extensive updates to accommodate flow changes in the accompanying diagram.

**Images**
- [ ] Functional Overview image scale?
- [ ] Add Alt-Text to all images?
- [ ] Some images include a URL-ref. In instances where this is the case, create a list for URLs to be added beneath the image
- [ ] Image scaling is not consistent throughout the page.
- [ ] Image resolution quality variable and in some instances the source image has clearly been modified without noting the overall image scale (e.g.: Calc Quote - Invalid Scheme Rules.)
- [ ] Resolution issues: Perform Transfer (uni mode); Perform Transfer with Payee Confirm; Duplicate POST (Resend); PayeeFSP Rejects Transfer; Timeout (prepare) (also source image color scheme (Red/Black); Timeout (pre-committed) (per previous); Duplicate POST (none matching)

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mwmentor** [comment]
With reference to the 2nd task listed in the Copy section of the task list, this will be referred to the BC Owner once confirmed.  I believe that it is @MichaelJBRichards - Michael, if that is the case, please could you add yourself as an assignee to this ticket and review and comment.  Thanks.  (I have pinged you via Slack as well :-) )

**Comment by pedrosousabarreto** [comment]
This documentation, should avoid details of how FSPIOP works and link that to the official FSPIOP documentation pages in here: https://docs.mojaloop.io/v1.0.1/api/fspiop/

This ref arch doc page, should stop at the "Functional Overview" block.
