### ISSUE TITLE
Ref Arch Documentation Review: Notifications and Alerts BC

### ISSUE THREAD

**Issue by mwmentor** [mojaloop/project#2682]
## **Issues to Fix**:
The following issues have been identified and require fixing:

**Code**
- [ ] Some UCs do not include any form of Description

**Images**
- [ ] Image scale is inconsistent across all images
- [ ] Add Alt. Text to images
- [ ] Where images include embedded URLs, create a list below the image to include the links

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mwmentor** [comment]
I have completed the updates for this BC and created a new [PR #71](https://github.com/mojaloop/reference-architecture-doc/pull/71).  I have requested that either @mdebarros or @pedrosousabarreto review and revert with any issues.  I am moving this ticket to review.

**Comment by mwmentor** [comment]
This Issue is currently blocked.  It is waiting for a response from @mdebarros in order to continue.  Per @pedrosousabarreto, the Alert Notification workflow is incorrect and should not be forwarding alerts to the DFSP.  Please see PR#68 and [Miro](https://miro.com/app/board/o9J_lJyA1TA=/?openComment=3458764523001973211).  Thanks.

**Comment by mwmentor** [comment]
Comments added from [PR#68](https://github.com/mojaloop/reference-architecture-doc/pull/68):

2022/04/12 - [Miguel de Barros](@mdebarros):
> Mostly looks good!

> The only thing I picked up was that we are missing a callBackReport on the Get Quotes use case -> docs/boundedContexts/quotingAgreement/assets/ML2RA_UC_getQuoteHappy_Mar22-a-1700.png

> Let me know your thoughts on this.

> Also based on this comment from the story mojaloop/project#2678 (comment), you mentioned there is an issue with the reference link. I don't see an update on this PR?

2022/04/28 - [Michael Wagener](@mwmentor):
> Responding to @mdebarros: Hi Miguel: I have been looking in on this periodically, and have decided that as the conversation appears to be mainly between you and me, for the time being, I would respond. My comment regarding the Gets Quote UC callBackReport is that I suspect was missed during the initial architecture planning session, and has subsequently been overlooked as a result of attention focusing elsewhere, or whatever. So I am guessing that incorporating it will entail a conversation between the BC Owners (I think you and Sam, per the Mojaloop 2.0 Reference Architecture Work Sessions document), Pedro, and any other relevant participants.

> With reference to the comment regarding the broken URLs, we just need to decide if they are going to be updated and included in the Ref Arch overview document that I am working to finish, or if they should be replaced. As they appear to be fairly relevant to the UC model/workflow structure approach, I would advocate that they require updating as the reference target has been moved. If not, we can remove them. The reason that I ask is that as we are including images only, a summary of the target URL should be included in a table within the UC Description that includes the target URL reference.

> Thanks, and I will include this conversation in Ticket #2682.

> (On another note, and pursuant to your comment regarding the inclusion of the URL Reference issue in this PR, this is where a problem arrives, in that we are using two platforms for managing the same issue. So perhaps we need to decide the roles of each, as it requires a bit of admin work to maintain both. This may be dependent on the role/function/interest of the viewer/reader, in which case, perhaps we should be thinking about how to short-circuit double-entry, for example automatically including PR comments in the ticket... Thanks.)

**Comment by pedrosousabarreto** [comment]
I'll change the diagrams and the wording as soon as I have time. Right now blocked with vNext dev.
