### ISSUE TITLE
Ref Arch Documentation Review: Participant Lifecycle BC

### ISSUE THREAD

**Issue by mwmentor** [mojaloop/project#2683]
## **Errors and Omissions**
The following errors and omissions have been noted and need attention:

**Copy**
- [x] Copy is a phrase-like in places.  Perhaps review and re-write as sentences where needed

**Images**
- [x] Image scale is inconsistent across all images
- [x] Add Alt. Text to images
- [ ] Where images include embedded URLs, create a list below the image to include the links

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mwmentor** [comment]
Picking this up for work later today 04/25/2022.

**Comment by mwmentor** [comment]
I have completed the tasks in this Ticket and have pushed [PR #76](https://github.com/mojaloop/reference-architecture-doc/pull/76) for review and approval by @pedrosousabarreto and/or @JohannWNel.  Once approved, I shall merge it and delete the branch that I created.   Ticket moved to Review.

**Comment by pedrosousabarreto** [comment]
Looks like this one can be closed.
