### ISSUE TITLE
Ref Arch Documentation Review: Reporting BC

### ISSUE THREAD

**Issue by mwmentor** [mojaloop/project#2684]
## **Errors and Omissions**
The following errors and omissions have been noted and need attention:

**Copy**
- [x] Bullet indenting missing
- [x] UC descriptions use the word "Strategy" to describe the workflow.  Change?
- [ ] Should the "To Do:" list be included?

**Images**
- [x] Image scale inconsistent across all images
- [x] General - UC flow diagram title case inconsistent throughout all images: some upper-case first letter, others not, etc.
- [x] Add Alt. Text to images
- [ ] Where images include embedded URLs, create a list below the image to include the links

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mwmentor** [comment]
I have completed the tasks for this BC.  There is one query that will be logged with the PR regarding the To-Do list.

**Comment by mwmentor** [comment]
I have pushed the updates for this BC to [PR#72](https://github.com/mojaloop/reference-architecture-doc/pull/72), and have asked @pedrosousabarreto to review.

**Comment by mwmentor** [comment]
Completed, reviewed, merged, and branch deleted.  Ticket completed.
