### ISSUE TITLE
Ref Arch Documentation Review: Security BC

### ISSUE THREAD

**Issue by mwmentor** [mojaloop/project#2686]
## **Errors and Omissions**
The following errors and omissions have been noted and need attention:

***Copy***
- [ ] The introduction needs to include a brief overview of the BC function, not a list of contents;
- [ ] The "Terms" require additional formatting: term names should be bold
- [ ] The "Notes" section should be hidden as it is presently empty

**Images**
- [x] Image scale is inconsistent across all images.
- [x] Add Alt. Text to images
- [ ] Where images include embedded URLs, create a list below the image to include the links

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mwmentor** [comment]
@godfreykutumela Hi Godfrey: Could you take a look at the comments that I made regarding the copy for this BCs doc's and let me know your thoughts.  Thanks. :-)

**Comment by mwmentor** [comment]
I have updated the images to provide consistent scale and font-height across the page.  I am waiting for comment from Godfrey.

**Comment by godfreykutumela** [comment]
@mwmentor The new images looks good to me and however we can close it once Pedro approves!

**Comment by pedrosousabarreto** [comment]
Looks like this can be closed.
