### ISSUE TITLE
Ref Arch Documentation Review: Settlements BC

### ISSUE THREAD

**Issue by mwmentor** [mojaloop/project#2687]
## **Errors and Omissions**
The following errors and omissions have been noted and need attention:

**Copy**
- [ ] The introduction could include references to Wiki or similar articles providing greater insight into the two settlement methods employed by the BC.  Alternatively, the descriptions for the DNS and IGS/RTGS Terms could be expanded to contain a broader explanation of the term.  A good example to follow can be found in the Transfers BC Terms section.
- [ ] UC descriptions sentence construction needs to improve, for example, "The Deferred Net Settlement method is used to provide DFSPs with the ability to settle multiple batches in accordance with a predetermined schedule. ... " 

**Images**
- [ ] Image scaling should be reviewed,  specifically, the Function Overview, Create/Update Settlement model, Bootstrap Settlement Model, Create Settlement-related accounts
- [ ] Add Alt. Text to images
- [ ] Where images include embedded URLs, create a list below the image to include the links

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mwmentor** [comment]
I have completed the listed tasks for this Ticket and have pushed [PR #75](https://github.com/mojaloop/reference-architecture-doc/pull/75).  Have requested @pedrosousabarreto and @mdebarros to review.

**Comment by pedrosousabarreto** [comment]
Waiting for review from Michael Richards
