### ISSUE TITLE
Ref Arch Documentation Review: Third Party API BC

### ISSUE THREAD

**Issue by mwmentor** [mojaloop/project#2688]
## **Errors and Omissions**
The following errors and omissions have been noted and need attention:

**Copy**
- [ ] No issues noted (Round 1)

**Images**
- [ ] Check image scaling in the "Linking Scenarios" section of the page and make it consistent with the scaling used in the "Transfers Scenarios" section, specifically, these images require rescaling - DFSP Issue Consent, Unlink Accounts - Hub Hosted Auth, Credential Registration Error, DFSP Rejects OTP/Auth Token from PISP, Unlink Accounts - Downstream failure
- [ ] General - UC flow diagram title case inconsistent throughout all images: some upper-case first letter, others not, etc.
- [ ] Add Alt. Text to images
- [ ] Where images include embedded URLs, create a list below the image to include the links 

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mwmentor** [comment]
Per my note appended to PR#58, please note the following:
I have completed the following items: Link Scenarios - images renewed, font sizes reviewed and updated, image scale reviewed and updated, image title case reviewed and updated, Alt. Text added to all images, no external link list required.  I will complete the Transfer scenario next and bump it up as an update to this PR.  Please advise if you have questions, and I will add this comment to #2688 as well.  Thanks. -M :-)

**Comment by tselit** [comment]
Hi @mwmentor 
May you please take a look at some DFSP typos:
- in the title: DSPF Rejects OTP/Auth Token from PISP
- content in one of the sections: "...but the Payee DSFP fails to locate a valid..."

**Comment by mwmentor** [comment]
Hi Tšeli: Thanks for taking a look - I will sort that. 👍

**Comment by mwmentor** [comment]
I have completed the following: Updated images, fonts, scale, title case.  Any issues please let me know.  This is the last update for the 3rd Party API BC barring any bugs.

**Comment by mwmentor** [comment]
@pedrosousabarreto Hi Pedro: I have completed my review of work completed and made a few minor updates: spelling, grammar, and type case.  Please could you review [PR #59](https://github.com/mojaloop/reference-architecture-doc/pull/59) and approve.  Thanks. -M.

**Comment by pedrosousabarreto** [comment]
PR #59 has been merged already, this can be closed
