### ISSUE TITLE
Ref Arch Documentation Review: Transfers BC

### ISSUE THREAD

**Issue by mwmentor** [mojaloop/project#2689]
## **Errors and Omissions**
The following errors and omissions have been noted and need attention:

**Copy**
- [ ] UC Descriptions should be expanded into sentences, for example: "The method provided by this UC workflow enables the switch to... "
- [ ] The Flow Diagram section needs to be hidden in sections where there are no images available.

**Images**
- [x] Image scaling is not consistent across all images included in the BC
- [ ] Some UCs do not have flow diagrams - Unhappy Path - Query (GET) Transfer - Validation Failure (Invalid Payer Participant) / (Invalid Payee Participant) / (Transfer Identifier Not Found)
- [ ] General - UC flow diagram title case inconsistent throughout all images: some upper-case first letter, others not, etc.
- [ ] Add Alt. Text to images
- [ ] Where images include embedded URLs, create a list below the image to include the links

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mwmentor** [comment]
@mdebarros Hi Miguel:  When you have a moment, please could you talk to me about the UC descriptions for this BC.  I would like to restructure them into a more sentence-like format.  Thanks so much. -M.

**Comment by mwmentor** [comment]
I have completed the updates per the above list and have created a new PR  - [61](https://github.com/mojaloop/reference-architecture-doc/pull/61) - which is awaiting approval by @pedrosousabarreto.

**Comment by mwmentor** [comment]
This update has been completed and the PR ([#61](https://github.com/mojaloop/reference-architecture-doc/pull/61)) has been merged, deleted, and closed.
