### ISSUE TITLE
2.4.30.01 Deploy updated codebase based on PI2 architecture for PI3 event demo on AWS

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#269]
**Goal**:
As a contributor
I would like to _deploy the updated codebase based on PI2 architecture for the PI3 demo that includes transfers_
so that the features implemented can be demonstrated at the onsite meetings.

**Tasks**:
- [ ] Deploy updated codebase based on PI2 architecture for **transfers** (k8s) on:
  - [x] AWS
- [ ] Sanity testing to ensure endpoints necessary for P2P are tested.
  - [x] participants ?
  - [x] parties
  - [x] quotes
  - [x] transfers
- [x] Basic testing to ensure for P2P positive scenario works and other basic features.

**Acceptance Criteria**:
- [x] An updated version of the codebase based on PI2 architecture, with transfers completed is deployed.
- [x] Sanity testing is done to ensure ml-api-adapter compatibility
- [x] Sanity testing is done on the end-points necessary for P2P use case
- [x] P2P positive scenario works as expected

**Dependencies**:
- [x] Updated codebase availability

**Accountability**:
- Owner
- Review
