### ISSUE TITLE
Ref Arch Documentation Review: Common Interface List

### ISSUE THREAD

**Issue by mwmentor** [mojaloop/project#2690]
## **Errors and Omissions**
The following errors and omissions have been noted and need attention:

**Copy**
- [ ] This section requires a title and one line intro.
- [ ] Ensure that all interfaces have been included in the list - review the source [Google Sheet](https://docs.google.com/spreadsheets/d/1ITmAesHjRZICC0EUNV8vUVV8VDnKLjbSKu_dzhEa5Fw/edit#gid=1810993431)

**Images:
No images here

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mwmentor** [comment]
I have completed the list of tasks associated with this issue.  There are three questions:

- There are a number of areas in the usage table where "?"s are being used instead of an "x".  Does this mean that the use of the interface in those contexts has been proposed but not confirmed?  Or does it mean that it has not yet been implemented?
- There are a number of placeholder blocks for the Accounts Lookup BC towards the bottom of the table.  Is that because the interfaces are still WIP, or can the placeholders be removed from the published document for now?
- Does the content noted in the questions above need to be included in the published release of the document?

Thanks.

**Comment by mwmentor** [comment]
Response:

- Not sure about the question marks - maybe that the interfaces are new and yet to be confirmed as suggested.
-

**Comment by mwmentor** [comment]
Assigned to PR#54, reviewed, merged, and deleted.  Ticket closed.

**Comment by tselit** [comment]
Hi @mwmentor 
Just a note for you to please take a look at the following items:
1. The URL to access the Common Interfaces seems to be invalid: 
- **the current URL**: https://docs.mojaloop.io/reference-architecture-doc/boundedContexts/
- **perhaps this should be**: https://docs.mojaloop.io/reference-architecture-doc/boundedContexts/commonInterfaces/
2. **/log-write**: The last record in the table seems to be populated in a way that's off by 1 column
