### ISSUE TITLE
TTK does not send callbacks after processing a Callback-Rule with a `FIXED_CALLBACK`

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2695]
**Summary**:

TTK does not send callbacks after processing a Callback-Rule with a `FIXED_CALLBACK`.

Here is the screenshot showing the TTK monitoring tool with no callback after the Callback-Rule match:
![Screenshot 2022-02-11 at 14.43.59.png](https://images.zenhubusercontent.com/5a0d3bc58a75884b9087a3dd/8740ed87-09b0-4f11-82bf-e1b69b044360)

Here is the TTK log file:

```
2022-02-11T11:34:00.304Z - info: Reloading validation Rules from file default.json
2022-02-11T11:34:00.305Z - info: Validating Ilp packet against the transfer request
2022-02-11T11:34:00.305Z - info: Validating condition with the stored fulfilment
{
  type: 'FIXED_CALLBACK',
  params: {
    body: {
      fulfilment: 'WLctttbu2HvTsa1XWvUoGRcQozHsqeu9Ahl2JW9Bsu8',
      completedTimestamp: '2021-02-11T10:15:26.000Z',
      transferState: 'RESERVED',
      extensionList: null
    },
    scripts: { scriptingEngine: 'postman' }
  }
}
2022-02-11T11:34:00.309Z - info: Using existing http/https agent for generic
(node:26) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'traceparen![Screenshot 2022-02-11 at 14.42.44.png](https://images.zenhubusercontent.com/5a0d3bc58a75884b9087a3dd/fbc27d00-cd46-471b-95be-ac0113d5712c)t' of undefined
    at Object.handleCallback (/opt/mojaloop-testing-toolkit/src/lib/callbackHandler.js:118:40)
```

**Severity**:
Medium

**Priority**:
High

**Expected Behavior**

TTK should send the callback as per the following screenshot using the `MOCK_CALLBACK` event type:

![Screenshot 2022-02-11 at 14 49 49](https://user-images.githubusercontent.com/11392873/153594333-b8cf3ead-a16a-4f4c-88ff-f21d4ffaab7c.png)

**Steps to Reproduce**
  1. Setup a Callback-rule with a `FIXED_CALLBACK` event-type
  2. Invoke the TTK so that the Callback-rule is fired

**Specifications**
  - Component (if known): testing-toolkit-backend
  - Version: v14.0.2
  - Platform: AWS / TTK
  - Subsystem: Callback-Rules
  - Type of testing: Adding tests for new features
  - Bug found/raised by: @mdebarros 

**Notes**:

- Severity when opened: Medium?
- Priority when opened: Medium?

**Tasks**:
- [x] 1. Show the error response data in the "Monitoring" page 
- [x] 2. Fix "Add Header" button in the "Event" builder
- [x] 3. Add "Add Custom Header" button in the "Event" builder

**PR(s)**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/203 (task 1)
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/126 (tasks 2,3)
