### ISSUE TITLE
TTK - Add array comparison operator

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2698]
## **Goal**:
`As a` individual implementer

`I want to` have more comparison operators in the rule conditions
  
`so that` I can create more granular rules

**Acceptance Criteria**:
- [ ] Add array comparison operator

**Complexity**: Medium
**Uncertainty**: Medium

---

**Tasks**:
- [ ] Investigate some sample UIs for array comparison
- [ ] Implement in the rules editor
- [ ] Create a version and update helm chart

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Hi @tselit, did you close this issue by mistake?

I have re-opened it with that assumption.
