### ISSUE TITLE
Fix processing of validation failures on /thirdpartyRequests/verifications/{ID}

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2699]
## **Goal**:
`As a` DFSP

`I want to` receive a callback (`PUT /thirdpartyRequests/verifications/{ID}`) with `authenticationResponse: 'REJECTED'` when a validation failure of the third-party transaction request (validation of challenge) happens on the switch
  
`so that` I'm informed of the failure and can respond accordingly

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Update api-snippets to use 'rejected' enum value for the enumeration AuthenticationResponse 
- [x] Update sequence diagrams for validation failures of transaction requests / challenges (instead of using error callback)
- [x] Update auth service implementation
- [x] Unit tests
- [x] Integration tests
- [x] Update end-to-end tests

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/auth-service/pull/99

## **Follow-up**:
- This is a follow-up of story: https://github.com/mojaloop/project/issues/1815

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
