### ISSUE TITLE
2.4.05.02 Resolve the aws api authentication issue experienced by the K8s cluster

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#270]
**Goal**:
As a developer 
I would like to _resolve the aws api authentication issue experienced by the K8s cluster_
so that LoadBalancer's can be provisioned for the Ingress to allow for external service invocation

**Tasks**:
- [x] Investigate cause of aws API authentication issue [ @fbotha-statuscloud @mdebarros ]
- [x] Setup new AWS DNS [ @fbotha-statuscloud ]
- [x] Setup new Rancher Server [ @fbotha-statuscloud @mdebarros ]
- [x] Setup new k8s-phoenix environment [ @fbotha-statuscloud @mdebarros ]
- [x] Test Helm deployments [@fbotha-statuscloud @mdebarros ]
- [x] Test Helm Ingress [ @fbotha-statuscloud @mdebarros ]
- [x] Resolve AWS API authentication issue

**Acceptance Criteria**:
- [x] K8s cluster is able to provision LoadBalancer for the Ingress Services

**Dependencies**:
- n/a

**Accountability**
- Owner @mdebarros 
- Review @mdebarros

**Comment by fbotha-stratuscloud** [comment]
@mdebarros - This issue should now be resolved as a new Rancher 2.0 based k8s cluster has been deployed.

**Comment by mdebarros** [comment]
Phoenix Kubernetes Rancher URL: https://k8s-phoenix-rancher.mojaloop.live/login
Phoenix Kubernetes Dashboard URL: https://k8s-phoenix-rancher.mojaloop.live/k8s/clusters/c-k8fts/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/#!/overview

**Comment by fbotha-stratuscloud** [comment]
Pegasys Kubernetes Rancher URL: https://k8s-pegasys-rancher.mojaloop.live/login
Pegasys Kubernetes Dashboard URL: https://k8s-pegasys-rancher.mojaloop.live/k8s/clusters/c-25pgz/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/#!/overview
