### ISSUE TITLE
ML-API-Adapter Notification Handler is missing metrics for egress

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2700]
## **Goal**:
`As a` Hub-Operator

`I want to` monitor egress metrics around the egress notification
  
`so that` I can analyse the performance/health of outgoing notifications to DFSPs

**Acceptance Criteria**:
- [ ] All egress's will be wrapped with a metric tracker for prometheus

**Complexity**: Low

**Uncertainty**:  Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @mdebarros
