### ISSUE TITLE
[api-snippets] Update OpenApi snippets to latest version of 3PPI API

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#2701]
## **Goal**:
`As an` adopter of api-snippets

`I want to` I want to make sure I have the latest version of the 3PPI API (resources, data model) to integrate into, as I use api-snippets
  
`so that` I can be assure that I'm using the latest version of the published API and use the latest features and fixes

**Acceptance Criteria**:
- [x] api-snippets are updated to reflect the latest version of Mojaloop 3p API
- [x] CI/CD issues publishing api-snippets are resolved
- [x] api-snippets can be used by third-party services to use v1.0 of the 3p API

**Complexity**: High

**Uncertainty**: Medium

---

**Tasks**:
- [x] Review newest API draft 
- [x] Resolve Enumerators that imply that authentication responses shouldn't be a `thirdpartyRequests/verifications/error` callback but a successful `thirdpartyRequests/verifications`one with a REJECTED  enum one like authenticationResponse during verification. Leading into a bigger question of how do we handle things like authentication in linking or the verification that a credential is signed correctly.
- [x] Resolve `providers` or `serviceProviders` in `PUT /service/{ServiceType}` callback.
- [x] Resolve 🤔 rabbit hole thought "If verification/authentication rejection are now handled with enums in response body, there was no need for `auth-service` specific error codes and since it is apart of the switch, it can adopt already established error codes and use `extensionList` to convery any extra data. This applies to errors codes for OTP rejection and credential registration errors as well"
- [x] Resolve some callbacks/requests have `extensionList` added but some don't. What is the criteria as to which get `extensionList` added
- [x] Conform any differences to the draft
- [x] Publish image

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by kleyow** [comment]
Re: Invalid signed challenge.

https://github.com/mojaloop/documentation/blob/master/website/versioned_docs/v1.0.1/api/thirdparty/transaction-patterns-transfer.md#-54-invalid-signed-challenge

![image.png](https://images.zenhubusercontent.com/5e8dbb4f85ab382447a8a1b7/89fb0da5-45cb-4e43-9867-ea2dbd848ca1)

Outlines that an invalid signed challenge will be a `PUT /error` callback. 

A successful callback would be return with the body
```
authenticationResponse: 'VERIFIED'
```
![image.png](https://images.zenhubusercontent.com/5e8dbb4f85ab382447a8a1b7/347459a6-69e4-4e9f-835a-3b2ad5b0c7bc)

However. The data models imply that an invalid signed signature should return a successful callback with 
```
authenticationResponse: 'REJECTED'
```
![image.png](https://images.zenhubusercontent.com/5e8dbb4f85ab382447a8a1b7/06c54e17-f4b8-436d-90eb-5be4a35f46a6)

**Comment by kleyow** [comment]
Re: `PUT service/{ServiceType}`
`providers` or `serviceProviders`. Currently it is
```
properties:
  providers:
    type: array
    minLength: 0
    maxLength: 256
    items:
      $ref: ./FspId.yaml
``` in the OA3 spec.

![image.png](https://images.zenhubusercontent.com/5e8dbb4f85ab382447a8a1b7/e300e371-a0d1-41eb-8133-875e2ae015a0)
![image.png](https://images.zenhubusercontent.com/5e8dbb4f85ab382447a8a1b7/efb52211-7876-4212-b5e0-2e5ead0a54a1)

**Comment by kleyow** [comment]
Add extension lists to all requests/responses.
Lewis managed to upgrade most of the snippets to the latest draft.

**Comment by elnyry-sam-k** [comment]
Follow up stories 

- Review sequence diagrams
- One story for each 3p service (sdk-standard-components, 3p-sdk, 3p-api-adapter, auth-service)
- Update integration tests in pisp-local repo
- Final step: 3p end-to-end tests

**Comment by elnyry-sam-k** [comment]
Covered in #2711 , #2712 , #2713 , #2714 , #2715 , #2716
