### ISSUE TITLE
Generate top level helm chart values.yaml from subcharts

### ISSUE THREAD

**Issue by tdaly61** [mojaloop/project#2705]
## **Goal**:
`As a` contributor to the v14 helm chart update
`I want to` create a small script to automatically generate the top level helm chart values.yaml from selected or indicated subcharts
  
`so that` the consistency of the charts is improved in the future and maintenance burden reduced.  
 

**Acceptance Criteria**:
- [x] TBD

**Complexity**: [Medium] It is not too complicated to textually substitute the yaml from one file to another

**Uncertainty**: [High] I am not 100% certain that the top-level charts values.yaml is just a superset of each of the subchart values.yaml.  This is part of the exercise i.e. to try and find out if this is possible for all top level charts

---

**Tasks**:
- [x] create the script and test it against the already updated account-lookup-service helm charts to generate the top level yaml (Using Perl / Python)
- [x] depending on the outcome of the account-lookup-service , update script and use it to generate other converted v14 topl level values.yaml files 
- [x] determine if it can be used for all of the v14 top-level charts [ @? ]

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [x] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @tdaly61 
- QA/Review: TBC

**Comment by tdaly61** [comment]
@elnyry-sam-k : this was included in PR #68 in the charts repo.  I don't plan to put it in the pipeline and it may take some tweaking over time but should be marked as done for now.  Oh and for full disclosure it is written in Python Miguel has asked me to consider re-writing in js but this will only be worth it if the tool can be made to work very generically across all the charts and that is TBD.

**Comment by elnyry-sam-k** [comment]
for some reason, the link to the PR above was showing wrong, instead of this one: https://github.com/mojaloop/charts/pull/68

**Comment by elnyry-sam-k** [comment]
Thanks for the update, @tdaly61 .. hopefully we can adopt this across the rest of the charts for v14
