### ISSUE TITLE
API-Snippets to support generating backwards compatible OpenAPI Definitions

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2706]
## **Goal**:
`As a` Developer

`I want to` use API-Snippets to generate OpenAPI definitions for all supported versions of the Mojaloop FSPIOP specification
  
`so that` Mojaloop components can utilise the generated OpenAPI definitions for backward compatibility

**Acceptance Criteria**:
- [ ] Documentation is made available on how to use api snippets of various published versions of the Mojaloop APIs (FSPIOP, 3PPI APIs, etc)
- [ ] API Snippets for Mojaloop APIs' published versions are made available for consumption by Mojaloop services

**Complexity**: High

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by kleyow** [comment]
@mdebarros Might not fully understand the story since it's fresh but snippets already supports 1.0 and 1.1 of the fspiop api.

https://github.com/mojaloop/sdk-scheme-adapter/blob/master/src/InboundServer/api_template.yaml

You simple change the `.../v1_1` to the version of your choice and then run a command to output a bundled version
"build:openapi:inbound": "openapi bundle --output ./InboundServer/api.yaml --ext yaml ./InboundServer/api_template.yaml"

```
openapi: 3.0.0
info:
  version: '1.1'
  title: Open API for FSP Interoperability (FSPIOP)
  description: >-
    Based on API Definition.docx updated on 2020-05-19 Version 1.1.
    API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP
    header.
  license:
    name: Open API for FSP Interoperability (FSPIOP)
paths:
  '/participants/{ID}/error':
    $ref: '../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/paths/participants_ID_error.yaml'
  '/participants/{ID}':
    $ref: '../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/paths/participants_ID.yaml'
  '/participants/{Type}/{ID}/error':
    $ref: '../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/paths/participants_Type_ID_error.yaml'
```
