### ISSUE TITLE
GP tests to assert backward compatibility use-cases

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2709]
## **Goal**:
`As a` tester

`I want to` ensure that the Mojaloop Golden Paths (GP) execute all Backward Compatibility Test Scenarios
  
`so that` Mojaloop releases ensure backward compatibility

**Acceptance Criteria**:
- [ ] Updated Helm to support Backward Compatibility Test Scenarios (i.e. add additional Test FSPs configured with the appropriate FSPIOP version )
- [ ] Update Onboarding collections to support the additional Test FSPs
- [ ] Add Backward Compatibility Test Scenarios to the GP Test Scenarios

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
