### ISSUE TITLE
ingress hosts updated globally through the helm charts and subsequent child charts through a dynamic template

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#271]
**Goal**:
As a developer 
I would like to have _ingress hosts updated globally through the helm charts and subsequent child charts through a dynamic template_
so that the configuration the helm charts are maintainable

**Tasks**:
- [ ] Update helm chart values to use the templating functionality for value files
- [ ] Test helm chart generation
- [ ] Test helm chart deployment

**Acceptance Criteria**:
- [ ] Any templatised values in the value files should be generated when running helm commands
- [ ] Helm charts should generate templates based on the provided value files,

**Dependencies**:
n/a

**Accountability**
- Owner @mdebarros 
- Review @mdebarros
