### ISSUE TITLE
Update sdk-standard-components to use api-snippets v13.0.8

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2711]
## **Goal**:
`As a` adopter of Mojaloop standard components (sdk-standard-components)

`I want to` have Mojaloop standard components using the v13.0.8 of api-snippets
  
`so that` I can use it in my services (downstream) and use the updated resources, data models of the API

**Acceptance Criteria**:
- [x] A release of Mojaloop sdk-standard-components is made available that uses api-snippets v13.0.8 (that reflects Mojaloop 3PPI API v1.0 as published)

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Update package
- [x] Fix tests
- [x] Build and publish npm package

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
