### ISSUE TITLE
Update thirdparty-api-svc to use api-snippets v13.0.8

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#2712]
## **Goal**:
As a adopter of Mojaloop thirdparty funtionality 

I want to have Mojaloop thirdparty api service using the v13.0.8 of api-snippets

so that I can use it in my services and use the updated resources, data models of the API

**Acceptance Criteria**:
- [ ] A release of Mojaloop thirdparty-api-svc is made available that uses api-snippets v13.0.8 (that reflects Mojaloop 3PPI API v1.0 as published)

**Complexity**: Low

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
