### ISSUE TITLE
Update auth-svc to use api-snippets v13.0.8

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2713]
## **Goal**:
As a adopter of Mojaloop thirdparty funtionality 

I want to have Mojaloop auth-service using the v13.0.8 of api-snippets

so that I can use it in my deployments and use the updated resources, data models of the API

**Acceptance Criteria**:
- [ ] A release of Mojaloop auth-service is made available that uses api-snippets v13.0.8 (that reflects Mojaloop 3PPI API v1.0 as published)

**Complexity**: Low

**Uncertainty**: Medium

---

**Tasks**:
- [x] Update packages
- [x] Update functional code 
- [x] Update contrib-fido-test-ui to derive challanges with new scope api schema
- [x] Merge contrib-fido-test-ui changes
- [x] Update Unit Tests
- [x] Update BDD Tests
- [x] Update Integration Tests
- [ ] Build and publish npm package

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
