### ISSUE TITLE
Update 3ppi integration tests to reflected updated services with api snippets v13.0.8

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2715]
## **Goal**:
As a adopter of Mojaloop thirdparty funtionality 

I want to have the 3p functionality validated using integration tests updated for api snippets v13.0.8

so that I can use it for testing and validation purposes

**Acceptance Criteria**:
- [ ] Integration tests in pisp-project repo are updated to use 3p services updated with api snippets v13.0.8

**Complexity**: Low

**Uncertainty**: Medium

---

**Tasks**:
- [x] Update services in docker integration harness
- [x] Update event-sdk to produce type declartion file
- [x] Update thirdparty-api-svc to capture missed interace update
- [x] Update tests

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
