### ISSUE TITLE
Update thirdparty-sdk to use api-snippets v13.0.8

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#2718]
## **Goal**:
`As an` adopter of the Mojaloop third-party features

I want to have Mojaloop thirdparty sdk using the v13.0.8 of api-snippets

so that I can use it in my services and use the updated resources, data models of the API

**Acceptance Criteria**:
- [x] A release of Mojaloop thirdparty-sdk is made available that uses api-snippets v13.0.8 (that reflects Mojaloop 3PPI API v1.0 as published)

**Complexity**: Medium

**Uncertainty**: High

---

**Tasks**:
- [x] Update package
- [x] Update functional code 
- [x] Resolve npm git:// package install error with node-oauth2-server
- [x] Update sdk-scheme-adapter types
- [x] Update sdk-standard-components types
- [x] Update Unit Tests
- [x] Update BDD Tests
- [x] Update Integration Tests
- [x] Build and publish npm package

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
