### ISSUE TITLE
2.4.50.03 Implement Fulfil Handler Consume (Success) {2.1.1.}

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#272]
**Goal**:
As a developer
I would like to _implement consuming Fulfils in the Fulfil Handler_
so that the complete payment process is implemented as per PI2 architecture.

**Note**:
This story doesn't include implementing Position related checks/events

**Tasks**:
- [x] Run through the sequence diagrams with Georgi/Miguel to ensure clarity [ @ggrg ]
- [x] Familiarise with the relevant code, libraries, config, etc. [ @ggrg ]
- [x] Setup environment - code base, postman, kafka, mysql [ @ggrg ]
- [x] Fulfill Handler Consume (Success) {2.1.1.} [ @ggrg ]
  - [x] Update design to match implementation - **seq-fulfil-2.1.1.svg** [ @ggrg ]
  - [x] Unit tests [ @ggrg, @vgenev ]
  - [x] Integration tests [ @ggrg, @vgenev ]

**Acceptance Criteria**:
- [x] The new base code has fulfils implemented with the latest design using the 'common library'
- [x] Notifications are placed on the specific topics (**topic-dfsp2-position-prepare**)
- [x] Functionality based on sequence diagrams for FulfilHandler is implemented

**Dependencies**:
- [x] #247 
- [x] New story **TODO: FiveBellsCondition.fulfillmentToCondition** always passes

**Accountability**:
- Owner @rmothilal 
- Review
