### ISSUE TITLE
remove default passwords for databases for V14 of ML Helm charts 

### ISSUE THREAD

**Issue by tdaly61** [mojaloop/project#2720]
## **Goal**:
`As a` mojaloop contributor 
`I want to` remove all default (database) passwords from the ML helm charts and importantly the docker images where they could much more easily remain in "production systems"
  
For example: in the central-ledger/docker/sql-init directory there is hard-coding for the docker container that statically adds the central_ledger and sets a default password  for running the data migration , this password does get updated but is still a default password and therefore opens questions of exploit windows.

`so that` we  improve security and adopt well accepted security standards thus helping to ensure confidence in the project.

**Acceptance Criteria**:
- [ ] there are no default passwords at a minimum in the docker images  that enable the deployed code to function or pass the TTK
- [ ] there are no default passwords in the yaml files of the helm charts.  
- [ ] a small utility or configuration mechanism is provided that makes it very simple for the user/deployer/tester to generate passwords at deploy time thus avoiding making it harder to try-out ML

**Complexity**: <Low> > removing default passwords is anticipated to be fairly straight-forward, as is providing a configuration utility to generate and insert at deploy time. 

**Uncertainty**: <Medium> > maintaining simplicity for end-users and enabling this same functionality in the circle-ci pipleline should be straight-forward. 

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
@tdaly61 - closing this as it has been a couple of months now. Please re-open if needed.. Thank you!
