### ISSUE TITLE
Develop DevSecOps Guideline for implementors

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#2721]
## **Goal**:
`
`Document DevSecOps guidelines for implementors based on our current implementation at Mojaloop!
  
**Acceptance Criteria**:
- [ ] Document our current DevSecOps framework
- [ ] Repurpose it as a guideline for implementors to reference and adopt

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela
