### ISSUE TITLE
Design a very basic demoable QR code Scheme for Merchants

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2729]
## **Goal**:
`As a` community member

`I want to` have a basic document describing a prototypical QR code scheme for merchants
  
`so that` I can see a real demo of a P2B QR code payment

**Acceptance Criteria**:
- [ ] A document living in the contrib-mojawallet-demo repo that describes a QR code scheme for merchants
- [ ] 3-5 examples of QR codes that adhere to this scheme for demo purposes

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
