### ISSUE TITLE
2.4.50.02 Implement Position Handler Consume (Fulfill Success) {2.1.2.}

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#273]
**Goal**:
1. As a developer
I would like to _Implement Position Handler Consume (Fulfill Success) {2.1.2.}_
so that the complete payment process is implemented as per PI2 architecture.

**Note**:
Change Transfer status from _reserved_ to _committed_

**Tasks**:
- [x] Run through the sequence diagrams with Georgi/Miguel to ensure clarity
- [x] Fulfill Handler Consume (Fulfill Success) {2.1.1.} (Testing limited to the happy path) - partial functionality to change status
  - [x] Unit tests
  - [x] Integration tests

**Acceptance Criteria**:
- [x] For this PI, a partial functionality that at a minimum updates the status from _reserved_ to _committed_ is present

**Dependencies**:
- [x] #247 

**Accountability**:
- Owner 
- QA/Review

**Comment by rmothilal** [comment]
@NicoDuvenage @elnyry Please not that the acceptance criteria for the story is not valid as it was discussed that this would only be a state change from reserved to committed.

**Comment by elnyry** [comment]
Agree, lets sync up to update it so that it is relevant
