### ISSUE TITLE
[3ppi] Update linting libraries and configurations to conform with standards found in typescript-svc-template

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#2731]
## **Goal**:
`As a` developer

`I want to` contribute to a code base without having to worry about code structure and formating
  
`so that` I can contribute code in a timely fashion

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] api-snippets https://github.com/mojaloop/api-snippets/pull/129
- [x] auth-service https://github.com/mojaloop/auth-service/pull/116
- [x] consent-oracle https://github.com/mojaloop/als-consent-oracle/pull/13
- [x] thirdparty-sdk https://github.com/mojaloop/thirdparty-sdk/pull/143
- [x] thirdparty-api-adapter https://github.com/mojaloop/thirdparty-api-svc/pull/83

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
