### ISSUE TITLE
Migrate the Deployment Guide

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2736]
## **Goal**:
`As a` newcomer to the community

`I want to` be able to deploy mojaloop easily following the deployment guide
  
`so that` I can get up and running as fast as possible

**Acceptance Criteria**:
- [ ] move the old deployment guide https://docs.mojaloop.io/legacy/deployment-guide/ to a new place on the updated docs.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
completed
