### ISSUE TITLE
[sdk-scheme-adapter] Reconcile mojaloop-connector with sdk-scheme adapter

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#2739]
## **Goal**:
`As an` adopter of Mojaloop

`I want to` have the best features of both mojaloop-connector and sdk-scheme-adapter in one repo
  
`so that` maintaining and contributing is easier.

**Acceptance Criteria**:
- [ ] Integration tests in 3p setup run without failures using the new mojaloop-connector in place of sdk-scheme-adapter [to be covered in #2762]
- [ ] ~Integration tests in pm4ml ui setup run without failures using the new mojaloop-connector in place of sdk-scheme-adapter~ [to be covered in #2756 ]
- [ ] Mojaloop end-to-end tests using mojaloop-connector (replacing sdk-scheme-adapter) run without failures [to be covered in #2757]

**Complexity**: High

**Uncertainty**: High

---

**Tasks**:
- [x] Pull in Yehven's oauth fixes and bump node version to 16 (https://github.com/mojaloop/sdk-scheme-adapter/pull/300)
- [x] Port updated config format
- [x] Port in metric promtheus logic
- [x] Pull in live reconfiguration (e.g. from MCM client)
- [x] Merge mojaloop-connector changes into sdk-scheme-adapter
- [x] Reconcile split tests
~~- [ ] Rename sdk-scheme-adapter to mojaloop-sdk. Deprecate mojaloop-connector and sdk-scheme-adapter~~

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
