### ISSUE TITLE
2.4.50.04 Implement Transfer Handler Consume (Fulfill Success) {2.1.3.}

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#274]
**Goal**:
1. As a developer
I would like to _Implement Transfer Handler Consume (Success) {2.1.3.}_
so that the complete payment process is implemented as per PI2 architecture.

**Tasks**:
- [x] Run through the sequence diagrams with Georgi to ensure clarity [@bothadeon , @rmothilal]
- [x] Implement Transfer Handler Consume (Success) {2.1.3.}[@bothadeon , @rmothilal]
  - [x] Unit tests[@bothadeon]
  - [x] Extend the existing Integration tests [@bothadeon]

**Acceptance Criteria**:
- [x] The new base code has fulfills implemented with the latest design using the 'common library'
- [x] Notifications are placed on the specific topics
- [x] Functionality based on sequence diagrams for TransferHandler is implemented

**Dependencies**:
- [x] #247 

**Accountability**:
- Owner @rmothilal 
- QA/Review
