### ISSUE TITLE
Onboard GSP API into TTK

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2741]
## **Goal**:
`As a` third party implementer

`I want to` onboard a sample 3P implementation API such as GSP API 
  
`so that` I can create and run 3p scenarios end-to-end

**Acceptance Criteria**:
- [ ] GSP API is onboarded into the TTK
- [ ] Initial test collections made available that trigger linking and 3p transfer flows
- [ ] Initial test collections available that cover linking with basic errors
- [ ] Initial test collections available that cover 3p transfers with basic errors

**Complexity**: Low

**Uncertainty**: Medium

**Notes**:
Link to GSP API:
---

**Tasks**:
- [ ] Onboard GSP API into Mojaloop TTK
- [ ] Trigger scenarios for
  - [ ] Linking
  - [ ] third-party transfer
- [ ] Create initial test collections to
  - [ ] link accounts with basic errors
  - [ ] Rules configured
  - [ ] Transfers including errors

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
