### ISSUE TITLE
Documentation Standards + Contributors Guide on node upgrade recommendations

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2743]
## **Goal**:
`As a` Mojaloop community contributor

`I want to` the contributors guide provide node upgrade recommendations and best practices (include guidelines on LTS (NodeJS, CI, etc))
  
`so that` I can use them for guidance while upgrading to nodejs LTS versions when needed. 

**Acceptance Criteria**:
- [ ] Contributors guide is updated to document standards and best practices regarding node upgrades
- [ ] Standards proposed Include LTS life-cycle  for NodeJS, Kubernetes, Ubuntu (CI), etc
- [ ] Standards proposed Include "how LTS is enforced in Mojaloop's repositories, and how one can go about updating repos to a newer LTS version
- [ ] Standards Documentation proposed to the DA

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] Update contributors guide to document and capture
  - [ ] Guidance on choosing a version of LTS
  - [ ] Basics of updates to be done and where (Update repos nvmrc files, etc)

**Done**
- [ ] Acceptance Criteria pass
- [ ] Contributors guide is updated with documentation on standards and best practices regarding node upgrades for Mojaloop

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
