### ISSUE TITLE
Update Nodejs/typescript Template Repos according to LTS requirements (nvm, docker, CI-CD config, etc)

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2744]
## **Goal**:
`As a` community contributor of Mojaloop

`I want to` be able to use nodejs/typescript template repos updated to latest LTS requirements
  
`so that` I can use them as templates for creating new services and other contributions

**Acceptance Criteria**:
- [ ] Nodejs/typescript template repos are updated according to latest LTS requirements 
- [ ] New versions of repos released after CI/CD flows are validated

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
