### ISSUE TITLE
Upgrade "central-services-logger" to node v16 (LTS)

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2745]
## **Goal**:
`As an` adopter of Mojaloop core services

`I want to` be able to use services that are upgraded to latest node LTS (v16 LTS)
  
`so that` I can ensure support for the version used

**Acceptance Criteria**:
- [x] A new version of "central-services-logger" that uses  node v16 (LTS) is published

**Complexity**: Low

**Uncertainty**: Medium

---

**Tasks**:
- [x] Update CI/CD template to follow new standards
- [x] New release of central-services-logger ([v11.0.0](https://github.com/mojaloop/central-services-logger/releases/tag/v11.0.0))

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
