### ISSUE TITLE
Upgrade (core) central services libraries to node v16 (LTS)

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2746]
## **Goal**:
`As an` adopter of Mojaloop core services

`I want to` be able to use core libraries that are upgraded to latest node LTS (v16 LTS)
  
`so that` I can ensure support for the version used

**Acceptance Criteria**:
- [x] New versions of core services upgraded to node LTS v16 are published
  - [x] central-services-shared
  - [x] central-services-metrics
  - [x] central-services-stream
  - [x] central-services-health
  - [x] central-services-logger
  - [x] central-services-error-handling
  - [x] event-sdk
  - [x] sdk-standard-components

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [x] Upgrade libraries used by Mojaloop core services to node LTS v16
  - [x] central-services-shared
  - [x] central-services-metrics
  - [x] central-services-stream
  - [x] central-services-health
  - [x] central-services-logger
  - [x] central-services-error-handling
  - [x] event-sdk
  - [x] sdk-standard-components
- [x] Upgrade CI/CD config for below repos
  - [x] central-services-shared
  - [x] central-services-metrics
  - [x] central-services-stream
  - [x] central-services-health
  - [x] central-services-logger
  - [x] central-services-error-handling
  - [x] event-sdk
  - [x] sdk-standard-components

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-stream/pull/125
- [x] https://github.com/mojaloop/central-services-shared/pull/330
- [x] https://github.com/mojaloop/event-sdk/pull/67
- [x] https://github.com/mojaloop/central-services-logger/issues/37
- [x] https://github.com/mojaloop/central-services-logger/issues/38
- [x] https://github.com/mojaloop/central-services-error-handling/issues/174
- [x] https://github.com/mojaloop/central-services-error-handling/issues/177
- [x] https://github.com/mojaloop/sdk-standard-components/issues/168
- [x] https://github.com/mojaloop/central-services-metrics/issues/154
- [x] https://github.com/mojaloop/central-services-health/pull/250
- [x] https://github.com/mojaloop/central-services-shared/pull/330

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
