### ISSUE TITLE
Upgrade ml-api-adapter to use node LTS v16

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2747]
## **Goal**:
`As an` adopter of Mojaloop core services

`I want to` be able to use ml-api-adapter service that is upgraded to latest node LTS (v16 LTS)
  
`so that` I can ensure support for the version used

**Acceptance Criteria**:
- [ ] Mojaloop core service ml-api-adapter is upgraded to use the latest node LTS v16 and its image is published
- [ ] Standardize CI/CD flow for docker image publishing
- [ ] Docker images use latest Ubuntu LTS images as part of CI/CD flows

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
