### ISSUE TITLE
Upgrade central-ledger to use node LTS v16

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2748]
## **Goal**:
`As an` adopter of Mojaloop core services

`I want to` be able to use central-ledger service that is upgraded to latest node LTS (v16 LTS)
  
`so that` I can ensure support for the version used

**Acceptance Criteria**:
- [x] Mojaloop core service central-ledger is upgraded to use the latest node LTS v16 and its image is published

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [x] Needs object store library upgraded
- [x] central-ledger

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] Mojaloop end-to-end GP tests pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/object-store-lib/pull/39
- [x] https://github.com/mojaloop/central-ledger/pull/902

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
