### ISSUE TITLE
2.4.50.05 Implement sending notifications to Participant (Payer, Payee) {2.1 - 1.1.4.} from ml-api-adapter

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#275]
**Goal**:
1. As a developer
I would like to _Implement sending notifications to Participant (Payer, Payee) {2.1 - 1.1.4.} from  #ml-api-adapter_
so that the complete payment process is implemented as per PI2 architecture.

**Tasks**:
- [x] Go through the ml-api-adapter for understanding [@lazolalucas]
- [x] Run through the sequence diagrams with Georgi/Miguel to ensure clarity [@lazolalucas]
- [x] Implement sending notifications to Participant (Payer, Payee) {2.1 - 1.1.4.} from ml-api-adapter [@lazolalucas]
  - [x] Unit tests [@lazolalucas]
  - [x] Extend the existing Integration tests

**Acceptance Criteria**:
- [ ] The new base code has fulfills implemented with the latest design using the 'common library'
- [ ] Notifications are placed on the specific topics
- [ ] Functionality based on sequence diagrams for FulfillHandler is implemented

**Dependencies**:
- [x] #247 

**Accountability**:
- Owner 
- QA/Review
