### ISSUE TITLE
display license on new documentation

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2755]
## **Goal**:

Reported from @millerabel 

The links on the Overview page of the Specification doc, the links to the other documents do not seem to work (on Safari on Mac).

I don’t see the license or copyright notice. We should probably have a license doc following Overview that has this information, or else incorporate it into the Overview doc. It must be human readable from the documentation pages, and not require access to GitHub sources (though it should also be there in the LICENSE.txt file). The developers of the API specification (including the Gates Foundation) crafted a license text for this spec. It used to be on the cover of the specification. Matt might be able to assist with finding it if it’s lost.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/documentation/pull/374

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
The PR: https://github.com/mojaloop/documentation/pull/374 linked here was approved and merged so closing this
