### ISSUE TITLE
Integration tests in pm4ml ui to use the new (ml-connector merged) sdk-scheme-adapter version

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2756]
## **Goal**:
`As an` adopter of Mojaloop

`I want to` have the capability to run integration tests using pm4ml ui with sdk-scheme-adapter
  
`so that` I can ensure there are no regressions by running these tests with adjacent services

**Acceptance Criteria**:
- [x]  Integration tests in pm4ml ui setup run without failures using the new mojaloop-connector in place of sdk-scheme-adapter

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Identify broken onboarding/tests and code updates
~~- [ ] Update management-api service to conform to new sdk-scheme-adapter redis interface~~
- [x] Update pm4ml ui integration test harness with new ~~management api and~~ sdk-scheme-adapter
- [x] Update tests

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
