### ISSUE TITLE
 Mojaloop end-to-end tests using sdk-scheme-adapter (version with changes from ml-connector)

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2757]
## **Goal**:
`As an` adopter of Mojaloop

`I want to` validate the new version of sdk-scheme-adapter with changes from mojaloop-connector
  
`so that` I can ensure that there are no regressions

**Acceptance Criteria**:
- [x]  Mojaloop end-to-end tests using mojaloop-connector (replacing sdk-scheme-adapter) run without failures

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [x] Update ML dev envt with sdk-scheme-adapter version v16.0.0
- [x] Ensure GP TTK tests pass
- [x] Ensure 3p TTK tests pass
- [x] Ensure bulk TTK test pass

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] https://github.com/mojaloop/helm/pull/476
- [ ] https://github.com/mojaloop/testing-toolkit-test-cases/pull/76

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
```
--------------------FINAL REPORT--------------------
Test Suite:GP Tests
Environment:moja2.test.mojaloop.live
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 2573                          │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 2505                          │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 68                            │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 587                           │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 129                           │
├───────────────────┼───────────────────────────────┤
│ Passed percentage │ 97.36%                        │
├───────────────────┼───────────────────────────────┤
│ Started time      │ Tue, 21 Jun 2022 10:58:49 GMT │
├───────────────────┼───────────────────────────────┤
│ Completed time    │ Tue, 21 Jun 2022 11:01:51 GMT │
├───────────────────┼───────────────────────────────┤
│ Runtime duration  │ 182231 ms                     │
└───────────────────┴───────────────────────────────┘
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-06-21T11%3A01%3A51.340Z.html)

**Comment by mdebarros** [comment]
```
Test Result: FAILED
Test Suite: Thirdparty Tests
Environment: moja2.test.mojaloop.live
Total assertions: 21
Passed assertions: 2
Failed assertions: 19
Total requests: 20
Total test cases: 8
Passed percentage: 9.52%
Started time: Tue, 21 Jun 2022 11:03:30 GMT
Completed time: Tue, 21 Jun 2022 11:03:38 GMT
Runtime duration: 8152 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-06-21T11%3A03%3A38.457Z.html)

**Comment by mdebarros** [comment]
> ```
> Test Result: FAILED
> Test Suite: Thirdparty Tests
> Environment: moja2.test.mojaloop.live
> Total assertions: 21
> Passed assertions: 2
> Failed assertions: 19
> Total requests: 20
> Total test cases: 8
> Passed percentage: 9.52%
> Started time: Tue, 21 Jun 2022 11:03:30 GMT
> Completed time: Tue, 21 Jun 2022 11:03:38 GMT
> Runtime duration: 8152 ms
> ```
> 
> [View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-06-21T11%3A03%3A38.457Z.html)

@kleyow any idea why this is failing? 

I upgraded SDK-Scheme-Adapter and Mojaloop-Simulators, do I need to also upgrade the Thirdparty Adapters?

**Comment by mdebarros** [comment]
These PR have all GP tests passing:
- https://github.com/mojaloop/helm/pull/476 @ https://github.com/mojaloop/helm/pull/476/commits/810936b6d49d5638f1d05f0e02cacd7d2f389f06
- https://github.com/mojaloop/testing-toolkit-test-cases/pull/76 @ https://github.com/mojaloop/testing-toolkit-test-cases/pull/76/commits/f50f440a3747f648642fbbcb0540312b91ac9c49
```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP Tests
Environment: moja2.test.mojaloop.live
Total assertions: 2573
Passed assertions: 2573
Failed assertions: 0
Total requests: 587
Total test cases: 129
Passed percentage: 100.00%
Started time: Fri, 01 Jul 2022 14:08:55 GMT
Completed time: Fri, 01 Jul 2022 14:12:07 GMT
Runtime duration: 192015 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-07-01T14%3A12%3A07.626Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Bulk Tests
Environment: moja2.test.mojaloop.live
Total assertions: 183
Passed assertions: 183
Failed assertions: 0
Total requests: 17
Total test cases: 4
Passed percentage: 100.00%
Started time: Fri, 01 Jul 2022 14:12:32 GMT
Completed time: Fri, 01 Jul 2022 14:12:56 GMT
Runtime duration: 23908 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-07-01T14%3A12%3A56.300Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Thirdparty Tests
Environment: moja2.test.mojaloop.live
Total assertions: 21
Passed assertions: 21
Failed assertions: 0
Total requests: 20
Total test cases: 8
Passed percentage: 100.00%
Started time: Fri, 01 Jul 2022 14:13:54 GMT
Completed time: Fri, 01 Jul 2022 14:13:59 GMT
Runtime duration: 5184 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-07-01T14%3A13%3A59.577Z.html)

**Comment by mdebarros** [comment]
```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP Tests
Environment: moja2.test.mojaloop.live
Total assertions: 2573
Passed assertions: 2573
Failed assertions: 0
Total requests: 587
Total test cases: 129
Passed percentage: 100.00%
Started time: Mon, 04 Jul 2022 10:20:55 GMT
Completed time: Mon, 04 Jul 2022 10:24:06 GMT
Runtime duration: 190397 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-07-04T10%3A24%3A06.181Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Bulk Tests
Environment: moja2.test.mojaloop.live
Total assertions: 183
Passed assertions: 183
Failed assertions: 0
Total requests: 17
Total test cases: 4
Passed percentage: 100.00%
Started time: Mon, 04 Jul 2022 10:24:15 GMT
Completed time: Mon, 04 Jul 2022 10:24:39 GMT
Runtime duration: 23937 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-07-04T10%3A24%3A39.306Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Thirdparty Tests
Environment: moja2.test.mojaloop.live
Total assertions: 21
Passed assertions: 21
Failed assertions: 0
Total requests: 20
Total test cases: 8
Passed percentage: 100.00%
Started time: Mon, 04 Jul 2022 10:25:10 GMT
Completed time: Mon, 04 Jul 2022 10:25:14 GMT
Runtime duration: 4414 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-07-04T10%3A25%3A14.633Z.html)
