### ISSUE TITLE
Certificate management functionality in thirdparty sdk (from mojaloop connector)

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2758]
## **Goal**:
`As an` adopter of Mojaloop 3p functionality

`I want to` have certificate management functionality part of 3p sdk
  
`so that` I can use 3p services security with certificate management

**Acceptance Criteria**:
- [ ] Certificate management functionality is added to thirdparty sdk (re-used from mojaloop connector)

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
