### ISSUE TITLE
3p services node upgrade

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2759]
## **Goal**:
`As an` adopter of Mojaloop 3p services

`I want to` be able to use 3p services that are upgraded to latest node LTS (v16 LTS)
  
`so that` I can ensure support for the version used

**Acceptance Criteria**:
- [ ] All 3ppi services/libraries are upgrading to Node 16.15.0 alongside their Dockerfiles and CI build automation

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] api-snippets https://github.com/mojaloop/api-snippets/pull/129
- [x] auth-service 
  - https://github.com/mojaloop/auth-service/pull/115
  - https://github.com/mojaloop/auth-service/pull/116
- [x] consent-oracle https://github.com/mojaloop/als-consent-oracle/pull/13
- [x] thirdparty-sdk 
  - https://github.com/mojaloop/thirdparty-sdk/pull/142
  - https://github.com/mojaloop/thirdparty-sdk/pull/144
  - https://github.com/mojaloop/thirdparty-sdk/pull/145
- [x] thirdparty-api-adapter 
  - https://github.com/mojaloop/thirdparty-api-svc/pull/82
  - https://github.com/mojaloop/thirdparty-api-svc/pull/84

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
