### ISSUE TITLE
2.4.50.06 Implement ML-API-Adapter consuming Fulfil PUT (Fulfil Success) {2.1.1}

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#276]
**Goal**:
1. As a developer
I would like to _Implement ML-API-Adapter consuming Fulfill Put (Success) {2.1.1}_
so that the complete payment process is implemented as per PI2 architecture.

**Tasks**: 
- [x] Considering only success scenarios, error scenarios will be handled in a separate story
- [x] Run through the sequence diagrams with Georgi/Miguel to ensure clarity - Done
- [x] Implement ML-API-Adapter consuming Fulfill Put (Success) {2.1.1} -Done
  - [x] Unit tests - Done
  - [x] Extend the existing Integration tests --Done
- [x] Update the documentation -- Done

**Acceptance Criteria**:
- [x] The new base code has fulfills implemented with the latest design using the 'common library'
- [x] ml-api-adapter is updated to handle fulfill requests

**Dependencies**:
- [x] #247 

**Accountability**:
- Owner 
- QA/Review
