### ISSUE TITLE
Third-party (3p) core connector for 3PPIs

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2761]
## **Goal**:
`As a` Third-party (3P) implementer (/ PISP)

`I want to` be able to use a "core-connector" that provides 3p functionality
  
`so that` I can support and provide 3p functionality (3p initiated transfers and 3p linking) to end users in the Scheme

**Acceptance Criteria**:
- [ ] A 3p core-connector for 3PPIs (/ PISPs) is published after end-to-end testing is done

**Complexity**: High

**Uncertainty**: High

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
