### ISSUE TITLE
Integration tests in 3ppi to use the new (ml-connector merged) sdk-scheme-adapter version

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#2762]
## **Goal**:
`As an` adopter of Mojaloop

`I want to` have the capability to run integration tests using `pisp-project` with sdk-scheme-adapter
  
`so that` I can ensure there are no regressions by running these tests with adjacent services

**Acceptance Criteria**:
- [x]  Integration tests in  `pisp-project` setup run without failures using the new mojaloop-connector in place of sdk-scheme-adapter

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Update sdk-scheme-adapter outbound TS interface
- [x] Update missed party model reformat message function
- [x] Update thirdparty-sdk code and integration tests
- [x] Update pisp-project integration test harness

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
