### ISSUE TITLE
Publish TTK CLI to NPM Repository

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2763]
## **Goal**:
`As a` Mojaloop Tester

`I want to` be able to use the TTK CLI from my local machine
  
`so that` I can run/execute TTK Test-Cases natively

**Acceptance Criteria**:
- [ ] TTK CLI package is published to the Mojaloop NPM Org repository
- [ ] TTK CLI package can be installed using `npm install`
- [ ] TTK CLI can be executed locally if installed using `npm install`
- [ ] TTK CLI can be installed/executed locally by using `npx`

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
