### ISSUE TITLE
Upgrade quoting-service to use node LTS v16

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2767]
## **Goal**:
`As an` adopter of Mojaloop core services

`I want to` be able to use quoting service that is upgraded to latest node LTS (v16 LTS)
  
`so that` I can ensure support for the version used

**Acceptance Criteria**:
- [ ] Mojaloop core quoting service is upgraded to use the latest node LTS v16 and its image is published

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [x] quoting service is upgraded
- [x] Verify Unit, integration tests pass
- [ ] Verify Mojaloop GP end-to-end tests pass

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] Mojaloop end-to-end GP tests pass

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

Notes:
- central ledger upgrade story #2748
