### ISSUE TITLE
Configure WSO2 Identity Server as key manager for API Manager (APIM)

### ISSUE THREAD

**Issue by markusvanaardt** [mojaloop/project#277]
**Objective**: Separate user/group/token management into a stand-alone capability within WSO2 Identity Server (IS).

**Goal**:
1. As a contributor I want to integrate IS with APIM for _user and role management_; and
2. As a contributor I want to configure IS to _issue session tokens to registered users_ upon request through the token API.

**Tasks**:
- [ ] Configure MySQL database to store user, role and session information;
- [ ] Configure APIM and IS to access MySQL database for user, role and session information;
- [ ] Configure IS as key manager for APIM; and
- [ ] Configure IS to issue session tokens through APIM.

**Acceptance criteria**:
- [ ] As a new user I must be able to create an APIM account, which will reside in IS;
- [ ] As a registered user I must be able to obtain a session token from APIM as issued by IS;
- [ ] As a registered user I must be able to use the session token to access APIs published on APIM;

**Dependencies**:
None

**Accountability**:
Owner: @markusvanaardt
