### ISSUE TITLE
Upgrade account-lookup-service to use node LTS v16

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2772]
## **Goal**:
`As an` adopter of Mojaloop core services

`I want to` be able to use account-lookup-service that is upgraded to latest node LTS (v16 LTS)
  
`so that` I can ensure support for the version used

**Acceptance Criteria**:
- [ ] Mojaloop account-lookup-service is upgraded to use the latest node LTS v16 and its image is published

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [ ] account-lookup-service is upgraded to use node v16 LTS
- [ ] Verify Unit, integration tests pass

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] Mojaloop end-to-end GP tests pass (with ALS)

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

Notes:
- central ledger upgrade story #2748

**Comment by mdebarros** [comment]
PR https://github.com/mojaloop/account-lookup-service/pull/445

**Comment by mdebarros** [comment]
> PR [mojaloop/account-lookup-service#445](https://github.com/mojaloop/account-lookup-service/pull/445)

```
--------------------FINAL REPORT--------------------
Test Suite:GP Tests
Environment:moja2.test.mojaloop.live
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 2535                          │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 2535                          │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 0                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 577                           │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 128                           │
├───────────────────┼───────────────────────────────┤
│ Passed percentage │ 100.00%                       │
├───────────────────┼───────────────────────────────┤
│ Started time      │ Mon, 20 Jun 2022 13:50:26 GMT │
├───────────────────┼───────────────────────────────┤
│ Completed time    │ Mon, 20 Jun 2022 13:53:33 GMT │
├───────────────────┼───────────────────────────────┤
│ Runtime duration  │ 187260 ms                     │
└───────────────────┴───────────────────────────────┘
```

[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-06-20T13%3A53%3A33.914Z.html)
