### ISSUE TITLE
Review/choose example for 3P FSP core-connector

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2776]
## **Goal**:
`As an` FSP

`I want to` be able to research and choose an example or template "core-connector"
  
`so that` I can use it to provide an example for 3p functionality core-connector (to support 3p initiated transfers and 3p linking)

**Acceptance Criteria**:
- [ ] An example core-connector for FSPs is chosen to be used as example to develop a 3p FSP core-connector

**Complexity**: medium

**Uncertainty**: High

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

Note: Can use @vijayg10  work as an example (can't link it here)
