### ISSUE TITLE
Upgrade event-sidecar to use node LTS v16

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#2778]
## **Goal**:
`As an` adopter of Mojaloop core services

`I want to` be able to use event-sidecar that is upgraded to latest node LTS (v16 LTS)
  
`so that` I can ensure support for the version used

**Acceptance Criteria**:
- [ ] Mojaloop event-sidecar service is upgraded to use the latest node LTS v16 and its image/package is published

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [ ] event-sidecar is upgraded to use node v16 LTS
- [ ] event-sidecar uses new CI/CD config (central-ledger as reference)
- [ ] Verify Unit, integration tests pass

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] Mojaloop end-to-end GP tests pass

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

Notes:
- central ledger upgrade story #2748
