### ISSUE TITLE
Implement on-boarding process for new users

### ISSUE THREAD

**Issue by markusvanaardt** [mojaloop/project#278]
**Objective**: Initiate a series of on-boarding processes when new users are registered through the API Manager (APIM) onto the Identity Server (IS).

**Goal**:
1. As a DFSP developer I want my portal account to be pre-configured with a generic account profile allowing me access to a basic group of Mojaloop APIs; and
2. As a DFSP developer I would like to _receive an email confirming my account being registered_ on the developer portal and my profile has been configured.

**Tasks**:
- [ ] Configure a generic service email account under which portal notifications will be sent out;
- [ ] Define vanilla user roles on IAM;
- [ ] Implement post-registration process to assign vanilla roles to new portal user accounts; and
- [ ] Implement post-registration process to send an email to new portal users.

**Acceptance critiria**:
- [ ] As a new user my account has to be configured using the vanilla user role to access basic Mojaloop services; and
- [ ] As a new user I want to receive a confirmation email after my account has been successfully created and configured.

**Dependencies**: #277

**Accountability**:
Owner: @markusvanaardt

**Comment by elnyry** [comment]
Closing this as this Epic/Topic isn't part of the plan for Mojaloop PI-3. Please re-open if necessary.
