### ISSUE TITLE
Upgrade mojaloop TTK to use node LTS v16

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2784]
## **Goal**:
`As an` adopter of Mojaloop core services

`I want to` be able to use TTK (backend) that is upgraded to latest node LTS (v16 LTS)
  
`so that` I can ensure support for the version used

**Acceptance Criteria**:
- [x] Mojaloop TTK is upgraded to use the latest node LTS v16

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [x] TTK is upgraded to use node v16 LTS
- [x] Standardise CICD
- [x] Standardise package.json
- [x] Add pre-commit hooks
- [x] Change audit tool to `audit-ci`
- [x] Add dependency checker
- [x] Verify Unit, integration tests pass

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] Mojaloop end-to-end GP tests pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/215
- [x] https://github.com/mojaloop/ml-testing-toolkit-client-lib/pull/1
- [x] https://github.com/mojaloop/helm/pull/482 (WIP)

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

Notes:
- central ledger upgrade story #2748

**Comment by vijayg10** [comment]
Upgraded nodejs version in docker files and in circleCI config. Got couple of failures in unit tests. Need to look at the failures.

https://github.com/mojaloop/ml-testing-toolkit/pull/210
