### ISSUE TITLE
Introduce basic branding for the developer portal on the API Manager (APIM)

### ISSUE THREAD

**Issue by markusvanaardt** [mojaloop/project#279]
**Objective**: Introduce basic Mojaloop branding on the API Manager.

**Goal**:
1. As a contributor I want to include a Mojaloop logo and other basic branding elements into the API Manager landing page to identify the gateway as part of the Mojaloop project.

**Tasks**:
- [ ] Replace the WSO2 logo with a Mojaloop logo; and
- [ ] Update the page header text to reflect Mojaloop.

**Acceptance criteria**:
- [ ] The API portal will reflect the Mojaloop brand.

**Dependencies**: None.

**Accountability**:
Owner: @markusvanaardt

**Comment by elnyry** [comment]
Closing this as this Epic/Topic isn't part of the plan for Mojaloop PI-3. Please re-open if necessary.
