### ISSUE TITLE
Upgrade bulk-api-adapter to use node LTS v16

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2790]
## **Goal**:
`As an` adopter of Mojaloop core services

`I want to` be able to use bulk-api-adapter that is upgraded to latest node LTS (v16 LTS)
  
`so that` I can ensure support for the version used

**Acceptance Criteria**:
- [x] bulk-api-adapter is upgraded to use the latest node LTS v16
- [x] bulk TTK collection passes without issues

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] bulk-api-adapter is upgraded to use node v16 LTS
- [x] Verify Unit, integration tests pass

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] Mojaloop end-to-end GP tests pass (along with bulk collection)

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

Notes:
- central ledger upgrade story #2748
