### ISSUE TITLE
Documentation needs a prominent link to instructions on deploying Mojaloop

### ISSUE THREAD

**Issue by tdaly61** [mojaloop/project#2791]
## **Goal**:
`As a` stakeholder 

`I want to` see a high level link in the Mojaloop documentation on how to deploy/install mojaloop
  
`so that` anyone who wants to try Mojaloop can easily find instructions on how to do so. 
I think one or menu items in the LHS of the https://docs.mojaloop.io/getting-started/ page would work nicely and these menu items should access the information that is currently found at https://docs.mojaloop.io/legacy under the "Deployment Guide" heading in the LHS menu.

**Acceptance Criteria**:
- [x] the getting started page contains a link to the deployment guide as indicated above
- [ ] 
**Complexity**: <|Low> > this is a very minor but important change

**Uncertainty**: <|Low> > this is a very simple change for anyone familiar with the Mojaloop documentation

---

**Tasks**:
- [x] TBD [ make the doc change ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @tdaly61

**Comment by tdaly61** [comment]
This is all done , per previous comment
