### ISSUE TITLE
TTK - Option to define hostname and path prefix to match provisioned APIs 

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2792]
## **Goal**:
`As a` individual implementer

`I want to` set hostname of path prefix to some provisioned APIs
  
`so that` I can avoid clash when two APIs with same resource names are provisioned in TTK

**Acceptance Criteria**:
- [ ] Option to define hostnames in the API definition list
- [ ] Option to define path prefix in the API definition list
- [ ] New parameters are visible in the "API definitions" page in TTK UI
- [ ] Edit the parameter values through TTK UI

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] Implement hostname option in TTK backend
- [ ] Implement path prefix option in TTK backend
- [ ] Fix unit tests and release
- [ ] Show the new params in TTK UI
- [ ] Ability to change the values through TTK UI
- [ ] Update the documentation

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
