### ISSUE TITLE
[SDK Scheme adaptor] Add bulk Discovery calls  (Steps 6-27) [point 2]

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2799]
**As a** DFSP connected to Mojaloop 
**I would like to** use the bulk transfers use case
**So that I** can integrate bulk load disbursement calls with my core banking system

**Note:** 
The automation tests used to test this functionality in CICD and deployment, should use TTK as core connector/CBS simulator.
Revised to 8 Story Points

**Limitations**
- This story covers flows steps in 6 - 27 in the sequence diagram; these are the bulk discovery calls. 
I.e. from the first Post to Mojaloop Connector, to the first returned bulkPartyAccept results through the PUT Callback when:
- AutoAcceptParty is false and 
- synchronous is false.
- This story covers the

 **Detailed Design**
The details of the design implementation are specified [here](https://github.com/mojaloop/sdk-scheme-adapter/tree/mvp/bulk-sdk/docs/design-bulk-transfers) 
   - [Outbound Event design](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/outbound-sequence.md)
   - [Outbound Redis Store](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/outbound_redis_message_format.md)
   - [Inbound Event design](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/inbound-bulk-transfers-sequence.md)
   - [Inbound Redis Store](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/inbound_redis_message_format.md)
 
**Acceptance Criteria**

- [x] Verify that Kafka messages are use to ensure persistence, reliability with minimal duplication on failures.
- [x] Verify that the typescript message definitions are provided
- [x] Verify that persistent model is defined
- [x] Verify that Event handler rules are added to complete the flow as designed above.
- [x] Verify the the Command handler is has commands added that complete the flow as designed above.
- [x] Verify that the Event handler has narrow integration tests
- [x] Verify that the Command handler has narrow integration tests
- [x] Verify that API Snippets are updated\added

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---
**Tasks**:
- [x] Create API snippets and update the swagger for outbound api
- [x] implement POST /bulktransfers
- [x] respond back with PUT /bulktransfers callback with results of party lookup
- [x] define entity types
   - [x] build the bulk transfer object - generate transactionId
   - [x] build the party model
- [x] Define the error types
- [x] Define infrastructure interfaces
- [x] Define the aggregates and entities based on super classes (@vijayg10 )
- [x] Define message types (@vijayg10 )
- [x] Implement infrastructure interfaces for Redis repo with unit tests (@vijayg10 )
- [x] Create the event handler service; with switch statements based on Design above (@vijayg10 )
- [x] Create basic command handler service to enable testing 
I.e. process event SDKOutboundBulkRequestReceived -> ProcessSDKOutboundBulkRequest -> Store in Redis
- [x] handle validation errors
- [x] write tests unit tests
- [x] write narrow integration tests
- [x] raise PR and get reviewed
   - [x] @mdebarros 
   - [x] @kirgene 
- [ ] Change batch status more appropriately in the design diagrams (Comment by @PaulGregoryBaker: The batch status of TRANSFER_SUCCESS is a bit misleading. Maybe we should change this to TRANSFER_COMPLETED.)

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/api-snippets/pull/131
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/335

## **Follow-up**:
- N/A

## **Linked stories**
- #2808 
- #2809 

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
https://github.com/mojaloop/api-snippets/pull/131
