### ISSUE TITLE
Publish Mojaloop APIs by means of the API Manager for consumption by registered developer portal users

### ISSUE THREAD

**Issue by markusvanaardt** [mojaloop/project#280]
**Objective**: Publish a core number of Mojaloop APIs through the API Manager (APIM) to introduce DFSP developers to basic functionality contained within Mojaloop (ML).

**Goal**:
1. Publish a core number of ML APIs onto the APIM;
2. Invite DFSP developers to register on the portal;
3. Introduce the DFSP developers to the process and functionality of the public ML environment;

**Tasks**:
- [x] Identify a number of core APIs that can be published on the gateway;
- [x] Activate the back-end APIs in a sandbox environment;
- [x] Publish the back-end APIs in the APIM sandbox; and
- [x] Publish the back-end APIs' documentation onto the APIM store for use by the DFSP developers.

**Acceptance criteria**:
- [x] As a DFSP developer I must be able to access the APIM store and review the published services;
- [x] As a DFSP developer I must be able to review the API documentation published on the APIM; and
- [x] As a DFSP developer I must be able to consume the APIs published on the APIM.

**Dependencies**:
- [x] #277

**Accountability**:
- Owner: @markusvanaardt 
- Back-end API activation: TBC
- Content: TBC

**Comment by markusvanaardt** [comment]
Deployed FSPIOP as a prototype to API manager.
