### ISSUE TITLE
[SDK Scheme adapter] Add bulk Quotes calls (Steps 32-57)

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2802]
**As a** DFSP connected to Mojaloop 
**I would like to** use the bulk transfers use case
**So that I** can integrate bulk load disbursement calls with my core banking system

**Note:** 
The automation tests used to test this functionality in CICD and deployment, should use TTK as core connector/CBS simulator.
This story has been split, so that it only covers the outbound changes. The inbound changes have been added to story #2905 

**Limitations**
This story covers flows steps in 32 - 57 in the sequence diagram. 
I.e. from the first PATCH with bulk accept party to the to Mojaloop Connector, to the PUT callback response with the bulk quote acceptance results when:
- AutoAcceptParty is false, 
- AutoAcceptQuote is false,
- synchronous is false, and
- the Payee SDK-Scheme-Adpater config ~~HasSupportForBulkQuotes = false~~ **HasSupportForBulkQuotes = true**

**Sequence Diagram**
The sequence diagram of this design can be accessed [here](https://raw.githubusercontent.com/mojaloop/documentation/PB.SDKBulkSupport/docs/technical/sdk-scheme-adapter/assets/sequence/BulkTransactionsSequenceDiagramOverview.svg).

 **Detailed Design**
The details of the design implementation are specified [here](https://github.com/mojaloop/sdk-scheme-adapter/tree/mvp/bulk-sdk/docs/design-bulk-transfers) 
   - [Outbound Event design](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/outbound-sequence.md)
   - [Outbound Redis Store](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/outbound_redis_message_format.md)
   - [Inbound Event design](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/inbound-bulk-transfers-sequence.md)
   - [Inbound Redis Store](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/inbound_redis_message_format.md)
 
**Acceptance Criteria**
- [ ] Verify that the Outgoing API’s are implemented in line with Epic design
   - PATCH /bulkTransactions/<bulkAcceptParty>
   - PUT /bulkTransactions/<bulkAcceptQuoteResponse>
- [ ] ~~Verify that the Incoming API’s are implemented in line with above Epic design~~
   - ~~Post /bulkquotes~~
   - ~~PUT /bulkquotes callback@@~~
- [ ] ~~Verify that the POST /bulkquote call is split into n synchronous POST /quoterequests calls~~
- [ ] Verify that the results for both happy and unhappy quote requests are consolidate and returned in the PUT /bulkquotes callback
- [ ] Verify that the bulk transfers API error cases are implemented in the SDK Scheme Adapter
- [ ] Verify that if a transfer is delayed by more than the bulk Expiration time are aborted
- [ ] Verify that failed quotes abort the transfer with error
- [ ] Verify that transfers for different Payee DFSP’s in the same bulk transfer message are supported
- [ ] Verify that transfers that are marked as invalid are skipped and returned in the aborted transfers response list
- [ ] Verify that the bulkExpiration is taken into account when setting quote expirations
- [ ] Verify that automated CICD test are added to cover this functionality
- [ ] Verify that the TTK is use to simulate the core connector
- [ ] Verify that Kafka messages are use to ensure persistence, reliability with minimal duplication on failures.
- [ ] Verify that the typescript message definitions are provided
- [ ] Verify that persistent model is defined
- [ ] Verify that Event handler rules are added to complete the flow as designed links above.
- [ ] Verify the the Command handler is has commands added that as designed links above.
- [ ] Verify that the Command handler has narrow integration tests
- [ ] Verify that API Snippets are updated\added

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---
**Tasks**:
- [x] Add steps from the overview sequence diagram into the detail Event Sourcing design e.g. Steps [32-39](https://raw.githubusercontent.com/mojaloop/documentation/80b060427292150d31c5b5124bdac0751b9a9011/docs/technical/sdk-scheme-adapter/assets/sequence/BulkDisbursementSequenceDiagramOverview-bulk.svg).
  - Command events
    - [x] ProcessSDKOutboundBulkAcceptPartyInfo
      - [x] Implementation
      - [x] Integration Test Cases 
    - [x] ProcessSDKOutboundBulkQuotesRequest
      - [x] Implementation
      - [x] Integration Test Cases - In Progress @kleyow
    - [x] ProcessBulkQuotesCallback
      - [x] Implementation
      - [x] Integration Test Cases - In Progress @kleyow
        - [x]  [Bug 2922](https://github.com/mojaloop/project/issues/2922) - [@vijayg10 ]
    - [x] ~~ProcessSDKOutboundBulkQuotesRequestComplete~~ (This event is deleted in the sequence diagram. Ref PR)
  - Domain events
    - [x] SDKOutboundBulkAcceptPartyInfoReceived
    - [x] SDKOutboundBulkAutoAcceptPartyInfoRequested
    - [x] SDKOutboundBulkAcceptPartyInfoProcessed
    - [x] BulkQuotesRequested (This should be handled in api service, message format is specified as part of this story)
    - [x] BulkQuotesCallbackReceived
    - [x] BulkQuotesProcessed
    - [x] SDKOutboundBulkAcceptQuoteRequested
  - ~~Inbound command events~~ (This work is moved to a new story [mojaloop/2905](https://github.com/mojaloop/project/issues/2905))
    - ~~ProcessInboundBulkQuotesRequest~~
    - ~~ProcessInboundBulkQuotesRequestComplete~~
    - ~~ProcessInboundBulkQuotesReponseSent~~
  - ~~Inbound domain events~~
    - ~~InboundBulkQuotesRequestReceived~~
    - ~~SDKBulkQuotesRequested~~
    - ~~SDKBulkQuotesCallbackReceived~~
    - ~~InboundBulkQuotesRequestProcessed~~
    - ~~InboundBulkQuotesReponseSent~~
- [x] Fix the following issues in API snippets library
  - [x] The amount field in bulkQuotesRequest -> individualQuotes should be required field.
  - [x] The expiration field is declared as required field in individualQuoteResults but there is no field in the definition at all.
  - [x] There is no currentState in the bulkQuotesResult specification, but its there in the response.
  - [x] The quoteId should be required field in the individualQuoteResponse. But it is optional now.
  - [x] Current dfspInboundAPI is outdated and its better to add the core connector API to the API snippets library as single source of truth. Create a story for this.
  - [x] POST /bulkTransaction has an optional bulkTransactionId in the body, yet the  PUT /bulkTransaction/{bulkTransferId} . Thus the CBS would not have prior knowledge of the bulkTransferId ….thus the bulkTransferId (bulkTransactionId) should be required instead of optional on the POST?
  - [x] Issue: Schema for Outbound API for homeTransactionId on Individual Transfers is not a generic string, but rather enforces UUID Regex pattern
- [x] define entity types
   -  [x] build the bulk batch transfer object
   - [x] build the quotes model
- [x] Define message types
- [x] Define the aggregates and entities based on super classes 
- [x] Extend interfaces for Redis repo with unit tests
- [x] Extend the event handler service; with switch statements based on Design above 
- [x] Extend the command handler service
   - [x] Add narrow integration tests for bulk quote handling in Command Handler Service (Sri) - In Progress
- [x] Outbound: Refactor backend API to consume Kafka topics for bulk @kirgene 
   - [x] implement PUT /bulkTransations/{bulkTransactionId} outbound for accept party
   - [x] respond back with PUT /bulkTransactions/{bulkTransactionId} callback for accept quote
- [x] Inbound: Refactor backend API to consume Kafka topics for bulk @kirgene 
transfers
- [x] Outbound: Refactor FSPIOP API to publish / consume Kafka topics for bulk @kirgene 
   - [x] create the POST /bulkquotes request object 
   - [x] handle the response from the PUT /bulkquotes/{id}  request 
- [x] Inbound: (Payer DFSP) Refactor FSPIOP API to publish / consume  Kafka topics for bulk @kirgene 
   - [x] handle the POST /bulkquotes request object 
   - [x] create the PUT /bulkquotes/{id} request with the results 
- [x] Combine event handler, command handler, backend API and FSPIOP API @kirgene 
- [x] Address duplication message event being sent due to redis increment @kleyow 
- [x] handle the error cases
- [x] handle validation errors
- [x] write narrow integration tests

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/sdk-scheme-adapter/pull/356
- [ ] https://github.com/mojaloop/api-snippets/pull/138

## **Follow-up**:
- #2905 

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
