### ISSUE TITLE
[SDK Scheme adapter] Add bulk Transfers calls (Steps 62-85) (Repoint 8pts)

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2803]
**As a** DFSP connected to Mojaloop 
**I would like to** use the bulk transfers use case
**So that I** can integrate bulk load disbursement calls with my core banking system

**Note:** 
This story has been split into two, and therefor only covers the Payer DFSP or outbound side of the required changes. (The inbound/payee dfsp changes are covered in story #2907
The automation tests used to test this functionality in CICD and deployment, should use TTK as core connector/CBS simulator.

**Limitations**
This story covers flows steps in 62 - 85 in the epic's sequence diagram. 
I.e. from the first PATCH with bulk accept party to the to sdk-scheme-adapter, to the PUT callback response with the bulk quote acceptance results when:
- AutoAcceptParty is false, 
- AutoAcceptQuote is false,
- synchronous is false, and
- the Payee SDK-Scheme-Adpater config ~~HasSupportForBulkQuotes = false~~ **HasSupportForBulkQuotes = true**

**Sequence Diagram**
The sequence diagram of this design can be accessed [here](https://raw.githubusercontent.com/mojaloop/documentation/PB.SDKBulkSupport/docs/technical/sdk-scheme-adapter/assets/sequence/BulkTransactionsSequenceDiagramOverview.svg).

 **Detailed Design**
The details of the design implementation are specified [here](https://github.com/mojaloop/sdk-scheme-adapter/tree/mvp/bulk-sdk/docs/design-bulk-transfers) 
   - [Outbound Event design](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/outbound-sequence.md)
   - [Outbound Redis Store](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/outbound_redis_message_format.md)
   - [Inbound Event design](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/inbound-bulk-transfers-sequence.md)
   - [Inbound Redis Store](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/inbound_redis_message_format.md)
 
**Acceptance Criteria**
- [ ] Verify that the Payer DFSP Backend API’s are implemented in line with  design
   - PUT /bulkTransactions/<bulkAcceptQuote>
   - PUT /bulkTransactions/{id}
- [ ] ~~Verify that the Payee DFSP API’s are implemented in line with  design where the individual transfers are sent to the CC, and consolidated response returned.~~
   - ~~POST /bulktransfers~~
   - ~~PUT /bulktransfers/{id} callback~~
   - [ ] ~~Verify that the POST /bulktransfers call is split into n synchronous POST /transfers calls~~
   - [ ] ~~Verify that the results for both happy and unhappy quote requests are consolidate and returned in the PUT /bulktransfers/ callback~~
- [x] Verify that the bulk transfers API error cases are implemented in the sdk-scheme-adapter
- [ ] Verify that if a transfer is delayed by more than the bulk Expiration time are aborted
- [x] Verify that failed get parties calls abort the transfer with error
- [x] Verify that failed quotes abort the transfer with error
 bug: https://github.com/mojaloop/project/issues/2946
- [x] Verify that transfers for different Payee DFSP’s in the same bulk transfer message are supported
- [ ] Verify that transfers that are marked as invalid are skipped and returned in the aborted transfers response list
      Q: what is meant by invalid? Does it mean accept party or accept quote is false? In this case, the return response for the transfer do not contain this info. For ex, if there are 10 requests and in which accpet party is false for 5, only 5 responses are to be returned.
- [ ] Verify that bulk transfer returns soon (within seconds) after the bulk Expiration time if that time is reached.
- [ ] Verify that the outgoing post Transfers expiration time considers both the response from the quotes and the bulk Expiration when being calculated.
- [x] Verify that the TTK is use to simulate the core connector
- [ ] Verify that Event handler rules are added to complete the flow as designed links above.
- [x] Verify the the Command handler is has commands added that as designed links above.
- [x] Verify that the Command handler has narrow integration tests, for happy path.
- [ ] Verify that API Snippets are updated\added @kirgene pls confirm this.
- [x] Verify that functional test are added to support transfers
- [ ] Verify that automated CICD test are added to cover this functionality using the testing harness https://github.com/mojaloop/ml-core-test-harness (This task is covered in a different story)

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---
**Tasks**:
- [x] Add steps from the [High-level Overview Sequence Diagram (62-85)](https://raw.githubusercontent.com/mojaloop/documentation/80b060427292150d31c5b5124bdac0751b9a9011/docs/technical/sdk-scheme-adapter/assets/sequence/BulkDisbursementSequenceDiagramOverview-bulk.svg) as per the [Detailed Design](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/outbound-sequence.md)
    - [x] Outbound PUT/bulkTransfers/{bulkTransferId} from Core-Connector to SDK-Scheme-Adapter API [64] [Added 2022-09-15] [ @kirgene ]
      - [x] Implementation
          - [x] define entity types
          - [x] build the transfer model
          - [x] Define message types
          - [x] Add route handling
          - [x] Add Unit Tests
    - [x] SDKOutboundBulkAcceptQuoteReceivedDmEvt [Added 2022-09-15] [ @mdebarros ]
      - [x] Implementation
          - [x] define entity types
          - [x] build the transfer model
          - [x] Define message types
          - [x] Add route handling
    - [x] ProcessSDKOutboundBulkAcceptQuoteCmdEvt [Added 2022-09-15] [ @mdebarros ]
      - [x] Implementation
          - [x] define entity types
          - [x] build the transfer model
          - [x] Define message types
          - [x] Add route handling
          - ~Add Unit Tests?~
      - [x] Integration Test Cases
    - [x] SDKOutboundBulkAcceptQuoteProcessedDmEvt [Added 2022-09-15] [ @mdebarros ]
      - [x] Implementation
          - [x] define entity types
          - [x] build the transfer model
          - [x] Define message types
          - [x] Add route handling
    - [x] ProcessSDKOutboundBulkTransfersRequestCmdEvt [ @mdebarros ]
      - [x] Implementation
          - [x] define entity types
          - [x] build the transfer model
          - [x] Define message types
          - [x] Define the aggregates handler
          - [x] Add logic to aggregates handler
          - ~Add Unit Tests?~
      - [x] Integration Test Cases 
    - [x] BulkTransfersRequestedDmEvt [@kleyow][ @mdebarros ]
      - [x] Implementation
          - [x] define entity types
          - [x] build the transfer model
          - [x] Define message types
          - [x] Add route handling
    - [x] BulkTransfersCallbackReceivedDmEvt [@kleyow]
      - [x] Implementation
          - [x] define entity types
          - [x] build the transfer model
          - [x] Define message types
          - [x] Add route handling
    - [x] ProcessBulkTransfersCallbackCmdEvt [@kleyow]
      - [x] Implementation
          - [x] define entity types
          - [x] build the transfer model
          - [x] Define message types
          - [x] Define the aggregates handler
          - [x] Add logic to aggregates handler
          - ~Add Unit Tests?~
      - [x] Integration Test Cases
    - [x] BulkTransfersCallbackProcessedDmEvt [@kleyow]
      - [x] Implementation
          - [x] define entity types
          - [x] build the transfer model
          - [x] Define message types
          - [x] Add route handling
    - [x] SDKOutboundBulkTransfersRequestProcessedDmEvt [@kleyow]
      - [x] Implementation
          - [x] define entity types
          - [x] build the transfer model
          - [x] Define message types
          - ~Add Unit Tests?~
    - [x] PrepareSDKOutboundBulkResponseCmdEvt [@kleyow]
      - [x] Implementation
          - [x] define entity types
          - [x] build the transfer model
          - [x] Define message types
          - [x] Define the aggregates handler
          - [x] Add logic to aggregates handler
          - ~Add Unit Tests?~
      - [x] Integration Test Cases
    - [x] SDKOutboundBulkResponsePreparedDmEvt [@kirgene]
      - [x] Implementation
          - [x] define entity types
          - [x] build the transfer model
          - [x] Define message types
          - [x] Add route handling
    - [x] SDKOutboundBulkResponseSentDmEvt [@kirgene]
      - [x] Implementation
          - [x] define entity types
          - [x] build the transfer model
          - [x] Define message types
          - [x] Add route handling
    - [x] ProcessSDKOutboundBulkResponseSentCmdEvt [@kleyow]
      - [x] Implementation
          - [x] define entity types
          - [x] build the transfer model
          - [x] Define message types
          - [x] Add route handling
          - ~Add Unit Tests?~
       - [x] Integration Test Cases
      
- [x] Outbound: Refactor backend API to consume Kafka topics for bulk
   - [x] implement PUT /bulkTransactions/{bulkTransactionId} outbound for accept quotes
   - [x] respond back with PUT /bulkTransactions/{bulkTransactionId} callback for bulk transfer response
- [x] Outbound: Refactor FSPIOP API to publish / consume Kafka topics for bulk
   - [x] create the POST /bulktransfer request object
   - [x] handle the response from the PUT /bulktransfers/{id} request
- [x] Combine event handler, command handler, backend API and FSPIOP API
- [ ] Switch Mode from Synchronous to Asynchoronous @vijayg10 
- [x] Write Functional Error Test Cases @sri-miriyala  [Inprogress]
  - [ ] [Bug 2946](https://github.com/mojaloop/project/issues/2946)
  - [x] [Bug 2950](https://github.com/mojaloop/project/issues/2950)
  - [ ] [Bug 2951](https://github.com/mojaloop/project/issues/2951)
  - [ ] [Bug 2952](https://github.com/mojaloop/project/issues/2952)
  - [x] [Bug 2953](https://github.com/mojaloop/project/issues/2953)
  - [ ] [Bug 2957](https://github.com/mojaloop/project/issues/2957)
  - [ ] [Bug 2958](https://github.com/mojaloop/project/issues/2958)
  - [ ] [Bug 2960](https://github.com/mojaloop/project/issues/2960)
  - [ ] [Bug 2961](https://github.com/mojaloop/project/issues/2961)
  - [ ] [Bug 2970](https://github.com/mojaloop/project/issues/2970)
  - [ ] [Bug 2972](https://github.com/mojaloop/project/issues/2972)
  - [ ] [Bug 2974](https://github.com/mojaloop/project/issues/2974)
- [x] Write Functional Quotes Test Cases @sri-miriyala 
- [x] Write '50' Bulk Txn Test Case @sri-miriyala 
- [x] write narrow integration tests for Happy Path
- [x] write functional tests
- [x] raise PR and get reviewed @kleyow 

---
**Functional Error Test Cases written**
- [x] [pass] Error cases for PUT outbound/bulkTransactions/{bulkTransferId} 
   - [x] [PASS] [TC-BHP3] fails schema validation - fails to start
   - [x] [FAIL] [TC-BHP2] bulk expiration already exceeded - fails to start - No Implementation yet
- [ ] Error cases for POST /bulkTransfers
   - [x] [FAIL] [TC-BT1] Whole API fails and responds with PUT /bulkTransfers/{ID}/error e.g. 2000 Generic server error
     - [ ] [Bug 2972](https://github.com/mojaloop/project/issues/2972)
   - [x] Individual transfer fails (All, one & none) and responds with PUT /bulkTransfers/{ID} e.g. 5101 Payee rejected quote
     - [x] [FAIL] [TC-BT4] One Transfer fails -  [Bug 2974](https://github.com/mojaloop/project/issues/2974) 
   - [x] [FAIL] [TC-BHP2] Bulk Expiration occurs after start - No Implementation yet
   - [x] [FAIL] [TC-BQ4]  Individual transfer quote failed (All, one & none) - validate that it is excluded in the bulkTransfers call
   - [x] [FAIL] [TC-BQ5] Individual transfer quote not accepted (All, one & none) - validate that it is excluded in the bulkTransfers call
     - [x]  [FAIL] [TC-BQ5] One quote not accepted - [2961](https://github.com/mojaloop/project/issues/2961)
- [x] [FAIL] [TC-BHP2]Bulk Expiration calculations
   - [x] Test when bulk transfer expiration is calculated based on config. I.e. now + config time < bulk expiration time
   - [x] Test when bulk transfer expiration is calculated based on bulk expiration. I.e. now + config time > bulk expiration time
- [ ] Test Consolidated response when 
   - [x] Discovery: Individual transfer failed validation I.e. POST /bulkTransaction has individual transfer with error code
   - [x] [PASS] [TC-BP1] Discovery: Individual transfer failed \getParties I.e. returns /parties/{Type}/{ID}/error
   - [x] [FAIL] [TC-BQ6]Discovery: Individual transfer accept party = false
   - [x] [FAIL] [TC-BQ1] [bug: 2946] Quotes: failed batch POST /bulkQuotes I.e. returns /bulkQuotes/{ID}/error
   - [x] [FAIL] [TC-BQ4] Quotes: Individual transfer failed POST /bulkQuotes I.e. returns /bulkQuotes/{ID}
   - [x] [FAIL] [TC-BT6]Quotes: individual accept quote  = false
   - [x] [FAIL] [TC-BT1]Transfers: failed batch POST /bulkTransfers I.e. returns /bulkTransfers/{ID}/error 
   - [x] [FAIL] [TC-BT4]Transfers: Individual transfer failed POST /bulkTransfers I.e. returns /bulkTransfer/{ID} e.g. 5103 - Payee rejected quote
   - [x] [FAIL] [TC-BT6]Transfers: individual accept quote  = false
   
---

---
**Quotes Test Cases (2809)**
- [x] Error cases for PUT outbound/bulkTransactions/{bulkTransferId} 
   - [x] [PASS] [TC-BHP3] fails schema validation - fails to start
   - [x] [FAIL] [TC-BHP2] bulk expiration already exceeded - fails to start - No Implementation yet
- [x] Error cases for POST /bulkQuotes
   - [x] [FAIL] [TC-BQ1] Whole API fails and responds with PUT /bulkQuotes/{ID}/error e.g. 2000 Generic server error
     [Bug 2946](https://github.com/mojaloop/project/issues/2946) 
   - [x] [FAIL] [TC-BQ4] Individual transfer fails (All, one & none) and responds with PUT /bulkQuotes/{ID} e.g. 5101 Payee rejected quote
     - [x]  One transfer fails - TC-BQ4 - payeefsp failing with missing transfer - [Bug 2974](https://github.com/mojaloop/project/issues/2974) 
   - [x] Bulk Expiration occurs after start
- [x] [FAIL] [TC-BHP2]Bulk Expiration calculations
   - [ ] Test when bulk quote expiration is calculated based on config. I.e. now + config time < bulk expiration time
   - [ ] Test when bulk quote expiration is calculated based on bulk expiration. I.e. now + config time > bulk expiration time

---

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/2803?planning-poker) with ZenHub @elnyry-sam-k @kirgene @mdebarros @sri-miriyala @vijayg10

**Comment by PaulGregoryBaker** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/2803?planning-poker) with ZenHub @kleyow

**Comment by sri-miriyala** [comment]
Bugs reported while testing this feature are followed up in separate bug tickets.
