### ISSUE TITLE
Revert API bulk transfers to preserve existing bulk Mojaloop calls through the SDK

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2804]
**As a** Prodcut Development squad
**I would like to** make sure that the sdk scheme adapter API support the older-API bulk calls
**So that I** can test the mojaloop bulk functionality through the SDK.

**Acceptance Criteria**
- [ ] verify that the existing bulk calls are supported
- [ ] Verify that the API snippets are included in the SDK

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Reference**
API Snippets repo: https://github.com/mojaloop/api-snippets

---
**Tasks**:
- [x] Revert API definition to for bulktransfers. (See note above).
- [x] Change bulk transfers end point in the API snippets  repo
- [x] Replace outbound API to import from the API Snippets.
- [x] Refactor the new /bulktransfers into a /bulktransactions call in the API Snippets repo
- [ ] ~~Merge newly added TTK tests (by Emerson) into TTK main branch after validation~~ Covered by story #2814 to be built later.

---
**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
