### ISSUE TITLE
Improve test coverage of Bulk MVP

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2805]
## **Goal**:
`As a` Hub operation implementing the mojaloop bulk use-case
`I want to` ensure that all happy and unhappy path API calls are regression tested
 `so that` I can deploy the mojaloop bulk functionality with confidence

`As a` Hub operation deploying the SDK Scheme Adapter to support a DFSP connection to Mojaloop
`I want to` ensure that all Bulk function are deployed and working
 `so that` I can deploy the mojaloop bulk functionality with confidence

`As a` Mojaloop Developer
`I want to` ensure that the unit and CICD integration testing covers the functionality that has been added by the bulk MVP
 `so that` future changes can be regression tested and applied with confidence.

**Acceptance Criteria**:
- [x] Verify that the bulk MVP unit tests meet the Mojaloop minimum coverage
- [x] Verify that the bulk Existing Mojaloop functionality has appropriate functional testing
- [x] Verify that the TTK bulk collection is extended to include test for the bulk MVP functionality
- [x] Verify that the bulk MVP functionality is tested externally I.e. through an API gateway with full security applied.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
