### ISSUE TITLE
[SDK Scheme Adapter] Refactor backend API and FSPIOP API to consume / produce Kafka topics for bulk discovery

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2808]
**As a** DFSP connected to Mojaloop 
**I would like to** use the bulk transfers use case
**So that I** can integrate bulk load disbursement calls with my core banking system

**Note:** 
The automation tests used to test this functionality in CICD and deployment, should use TTK as core connector/CBS simulator.

**Limitations**
- This story covers flows steps in 6 - 27 in the sequence diagram; these are the bulk discovery calls. 
I.e. from the first Post to SDK SCheme Adapter, to the first returned bulkPartyAccept results through the PUT Callback when:
- AutoAcceptParty is false and 
- synchronous is false.
- This story relates to configuring the

 **Detailed Design**
The details of the design implementation are specified [here](https://github.com/mojaloop/sdk-scheme-adapter/tree/mvp/bulk-sdk/docs/design-bulk-transfers) 
   - [Outbound Event design](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/outbound-sequence.md)
   - [Outbound Redis Store](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/outbound_redis_message_format.md)
   - [Inbound Event design](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/inbound-bulk-transfers-sequence.md)
   - [Inbound Redis Store](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/inbound_redis_message_format.md)
 
**Notes:**
Current bulk API development replaced the \bulktransfers. This was a mistake that must be undone, with the new functionality being added as a POST \bulkTransactions
This needs to be configurable. I.e. It must work without Kafka installed. 

**Acceptance Criteria**

- [x] Verify that Open API definition is changed so that the new functionallity extends the SDK instead of replacing the **POST** /bulktransfers
I.e. use **POST** /bulktransactions end point instead
- [x] Verify that the Outgoing backend API’s are implemented in line with Epic design
   - **POST** /bulktransactions
   - **PUT** /bulktransactions callback with a bulk Party Accept response
- [x] Verify that the Outgoing FSPIOP API’s are implemented in line with Epic design
   - **GET** /parties/*
   - **PUT** /parties/{type}/{id} callback 
- [ ] Verify that the tests are built using TTK as the core connector simulator @sri-miriyala 
- [x] Verify that the trace headers are added as specified in the design
- [x] Verify that SDK can be deployed without Kafka

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---
**Tasks**:
** on a new branch**
- [x] Create separate backend handlers for inbound requests: REST API and Kafka.
- [x] Refactor inbound model to use DI request handler instead of BackendRequests.
- [x] Implement Kafka handlers module (similar to REST API)
- [x] Fix Redis timeout issue while running integration tests
- [x] Fix running integration tests in CI/CD pipeline
- [x] Fix API definition to include both bulktransactions and bulktransfers. (See note above).
- [x] Integrate event sdk into the scheme-adapter to generate trace headers
- [x] Refactor backend API to consume / produce Kafka topics for bulk
- [x] Refactor FSPIOP API to consume / produce Kafka topics for bulk
- [x] write tests unit tests
- [x] write narrow integration tests
- [ ] write end-end tests in TTK and test them locally @sri-miriyala 
  - [ ] Setup CoreConnector(TTK Sim) SDK Scheme Adapter on Payer side, Switch(TTK) and SDK Scheme Adapter, Core Connector(TTK Sim) on the Payee Side locally to test end-end functional tests
- [x] raise PR and get reviewed
- [ ]
