### ISSUE TITLE
[SDK Scheme Adapter] Combine event handler, command handler, backend API and FSPIOP API for bulk discovery & Quotes

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2809]
**As a** DFSP connected to Mojaloop 
**I would like to** use the bulk transfers use case
**So that I** can integrate bulk load disbursement calls with my core banking system

**Dependency**
#2808 

**Note:** 
The automation tests used to test this functionality in CICD and deployment, should use TTK as core connector/CBS simulator.

**Limitations**
- This story covers flows steps in 6 - 27 in the sequence diagram; these are the bulk discovery calls. 
I.e. from the first Post to SDK Scheme Adapter, to the first returned bulkPartyAccept results through the PUT Callback when:
- AutoAcceptParty is false and 
- AutoAcceptQuotes is false and
- synchronous is false.

 **Detailed Design**
The details of the design implementation are specified [here](https://github.com/mojaloop/sdk-scheme-adapter/tree/mvp/bulk-sdk/docs/design-bulk-transfers) 
   - [Outbound Event design](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/outbound-sequence.md)
   - [Outbound Redis Store](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/outbound_redis_message_format.md)
   - [Inbound Event design](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/inbound-bulk-transfers-sequence.md)
   - [Inbound Redis Store](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/inbound_redis_message_format.md)
 
**Acceptance Criteria**

- [ ] Verify that the tests are built using TTK as the core connector simulator
- [ ] Verify that automated CICD test are added to cover this functionality using a TTK to simulate the Payee DFSP for quotes and get parties; and another TTK to simulate the core connector calls.
- [ ] Verify that the happy path tests are added

**Note:** problems found in commissioning need to be created as other stories/bugs.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---
**Tasks**:
- [x] Setup functional test framework [@vijayg10 ]
  - [x] Prepare docker-compose for running the following services with proper config
    - [x] Payer API service
    - [x] Payer Command Handler
    - [x] Payer Domain Handler
    - [x] Payee API service
    - [x] TTK
    - [x] Redis, Kafka ...etc
  - [x] Configure TTK to simulate Core Connector using rules
  - [x] Test a p2p transfer from payer to payee using TTK
- [x] Merge fix for bulkQuotes and bulkTransfers from master [@vijayg10 ]
  - [x] PR [#369](https://github.com/mojaloop/sdk-scheme-adapter/pull/369)
  - [x] PR [#371](https://github.com/mojaloop/sdk-scheme-adapter/pull/371)
  - [x] Test /bulkQuotes and /bulkTransfers using functional test harness
- [x] Issue: once the api-svc publishes domain event, its not getting picked up by Domain Event handler [@vijayg10 ]
  - ```
    unc-payer-sdk-api-svc-1                         | 2022-09-10T21:12:02.115Z (SDK-Scheme-Adapter backend-api-handler v0.0.1) (null) [] info: Sent domain event SDKOutboundBulkRequestReceivedDmEvt
    ```
  - Fixed in the PR branch. Commit [Link](https://github.com/mojaloop/sdk-scheme-adapter/commit/f5e622cc954ef1db473c02cab6dccb6b137d4375)
- [x] API-SVC Bugs: Identified the following issues with api-svc  [@vijayg10 ]
  - Bugs:
    - [x]  kafka handlers in api-svc. The backend and fspiop handlers are not starting up. Need to add start and stop calls to the application entry point.
    - [x] The handler functions are incorrectly named `handlePartyInfoRequestedDmEvt` & `handleBulkQuotesRequestedDmEvt`
    - [x] Issue with using different logger implementations
    - [x] Issue with handling PUT /parties callback
    - [x] It should be `options.producer` instead of `options.domainProducer`
  - PRs:
    - [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/372
    - [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/373
- [x] Issue: individualTransferResults is empty in domain event `SDKOutboundBulkAcceptPartyInfoRequestedDmEvt` [@vijayg10 ]
  - [x] PR https://github.com/mojaloop/sdk-scheme-adapter/pull/374
- [x] Test discovery end-end locally using TTK(as CC) payer SDK and payee SDK for happy path- @sri-miriyala (done)
  - [x] [Bug 2932](https://github.com/mojaloop/project/issues/2932) [fixed,tested and closed]
  - [ ] [Bug 2933](https://github.com/mojaloop/project/issues/2933) [not in scope for MVP]
- [x] Test bulk quotes end-end locally using TTK(as CC) payer SDK and payee SDK for happy path- @sri-miriyala   [Inprogress]
- [x] Test negative scenario - failed party lookup [ @vijayg10 ]
  - [x] Fix TTK response rule properly to make payee respond with error for a particular MSISDN in the [PR commit](https://github.com/mojaloop/sdk-scheme-adapter/pull/376/commits/f77223538e087858eeac63bf9f8a769bfba197e4)
  - [x] Issue: The api-svc is not generating domain event `PartyInfoCallbackReceivedDmEvt` properly with error information if the response from core connector is error
    - [x] PR [sdk-scheme-adapter/pull/391](https://github.com/mojaloop/sdk-scheme-adapter/pull/381) WIP
- [ ] Add negative test cases for end-end discovery tests @sri-miriyala (In-Progress)
  - [x] [Bug 2939](https://github.com/mojaloop/project/issues/2939)
  - [ ] [Bug 2940](https://github.com/mojaloop/project/issues/2940)
  - [x] [Bug 2941](https://github.com/mojaloop/project/issues/2941) 
- [ ] Add negative test cases for end-end Quote tests @sri-miriyala 
- [ ] Load all components and test discovery message.  - fix if any problems arise 
- [x] write functional test by building docker-compose TTK based testing framework [Inprogress]
- [ ] raise PR and get reviewed
- [ ] merge PR ?? (Still need to be discussed and decided that this is a good idea.)


---
**Test Cases**
- [ ] Error cases for PUT outbound/bulkTransactions/{bulkTransferId} 
   - [ ] fails schema validation - fails to start
   - [ ] bulk expiration already exceeded - fails to start
- [ ] Error cases for POST /bulkQuotes
   - [ ] Whole API fails and responds with PUT /bulkQuotes/{ID}/error e.g. 2000 Generic server error
   - [ ] Individual transfer fails (All, one & none) and responds with PUT /bulkQuotes/{ID} e.g. 5101 Payee rejected quote
   - [ ] Bulk Expiration occurs after start
- [ ] Bulk Expiration calculations
   - [ ] Test when bulk transfer expiration is calculated based on config. I.e. now + config time < bulk expiration time
   - [ ] Test when bulk transfer expiration is calculated based on bulk expiration. I.e. now + config time > bulk expiration time


---

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/2809?planning-poker) with ZenHub @elnyry-sam-k @kirgene @mdebarros @sri-miriyala @vijayg10
