### ISSUE TITLE
Implement Aborting a transfer Scenario when Payee sends an Error message

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#281]
**Goal**:
As a Payee 
I want to _be able to send a <http:put> error message on /transfers/{ID}/error, as per the API specification_ (9.3.6 API Resource /transfers)
so that _I can affect aborting a transfer_

**Tasks**:
- [x] Update sequence diagrams to fix corrections (consistency of newly proposed states, naming changes, etc) following-up from #637 [@elnyry]
- [x] Validate current implementation to check what is done if 'fulfilment' is not present for an 'aborted' request [@ggrg]
- [x] Update seeds in transferState.js to include four new internal states as proposed in #637 
- [x] Update existing Rejection implementation to change "REJECTED" internal state to "RECEIVED_REJECT" [@ggrg]
- [x] Update existing Rejection implementation to change "ABORTED" internal state to "ABORTED_REJECTED" [@ggrg]
- [x] Verify GET /transfers returns "ABORTED" enumeration, not the internal state "ABORTED_REJECTED" [@ggrg]
- [x] Provide implementation to support /error end-point on transfers using designs provided in #637 [@ggrg]
- [x] Verify GET /transfers returns "ABORTED" enumeration, not the internal state "ABORTED_ERROR" [@ggrg]
- [x] Unit tests are updated [@ggrg]
- [x] Code coverage is verified [@ggrg]
- [x] ~Integration tests are updated~ (now covered in #665)
- [x] Transfer abort without fulfilment [@ggrg]
  - [x] Change DB schema (migrations) to allow insert in transferFulfilment with nullable ilpFulfilment [@ggrg]
  - [x] Alter the action flow to RECEIVED_REJECT [@ggrg]
  - [x] Make sure transferExtensions are captured and recorded [@ggrg]
- [x] Transfer Error endpoint to be altered [@ggrg]
  - [x] Add migration script with new reference column: transferExtension.transferErrorId [@ggrg]
  - [x] Add enclosing errorInformation [@ggrg]
  - [x] Add extensionList within errorInformation [@ggrg]

**Acceptance Criteria**:
- [x] Updated Implementation provides for the changes in new internal states and updates existing rejection flows to include new internal states (RECEIVED_REJECT->ABORTED_REJECTED)
- [x] Implementation now supports /error end-points on transfer and affects the aborting of a transfer
- [x] Validate GET /transfers returns ABORTED enumeration, not internal state
- [x] Error information is persisted in the DB which includes the extensions list
- [x] When transfer error is received the flow is RECEIVED_ERROR -> ABORTED_ERROR
- [x] Designs need to be updated
  - [x] seq-reject-2.2.0.svg [@elnyry]
  - [x] seq-reject-2.2.0.a.svg [@elnyry]
  - [x] seq-reject-2.2.1.svg [@elnyry]
  - [ ] ~seq-position-1.3.3-abort.svg~

**PRs**:
- [x] https://github.com/mojaloop/docs/pull/140
- [x] https://github.com/mojaloop/docs/pull/139
- [x] https://github.com/mojaloop/docs/pull/138
- [x] https://github.com/mojaloop/docs/pull/141
- [x] https://github.com/mojaloop/ml-api-adapter/pull/95
- [x] https://github.com/mojaloop/central-ledger/pull/255

**Dependencies**:
- [x] #637 

**Follow-up**:
- #665

**Accountability**
- Owner
- Review @elnyry  

**Notes**:
- API Specification indicates that a normal PUT with status='aborted' or an Error message can be sent to the switch to reject the fulfilment. #247 catered for the design of the PUT with status='aborted' scenario. This story is to cater for the alternative Error message scenario.

**Comment by ggrg** [comment]
Estimate updated due to adding new tasks and modification of acceptance criteria.
