### ISSUE TITLE
Mojaloop Helm release v14.0.0

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2812]
## **Goal**:
`As a` ML OSS adopter

`I want to` have a Mojaloop release v14.0.0 that is successfully validated by the Golden path tests
  
`so that` I can adopt and use a version of Mojaloop Switch services bundle that is tested and contains the latest features enhancements and bug fixes added in PI-17/PI-18 and services that use Node v16 (that has LTS).

**Acceptance Criteria**:
- [x] Helm RC v14.0.0 is validated on Moja2 to achieve 100% result with TTK GoldenPath collections
- [x] Helm RC v14.0.0 is validated with PISP provisioning and test collection (TTK) with 100%
- [x] Helm RC v14.0.0 is validated with Bulk test collection (TTK) with 100%
- [x] QA (Golden path) on deployments done on AWS Moja2 environment is done
- [x] Bugs are logged based on observations, failures
- [x] Bugs logged are fixed if critical to make subsequent releases in individual services (or Helm)
- [x] All the changes needed for supporting v14.0.0 of Helm are done
- [x] Helm v14.0.0 is released and release notes published
- [x] Test cases v14.0.0 is published (TTK)
- [x] TTK tests run successfully as Post-Hook jobs and Tests

**Complexity**: Medium - Involves all core and supporting services

**Uncertainty**: Medium

---

**Tasks**:
- [x] Initial PR with changes for v14.0.0
  - [x] Initial PR review
  - [x] Deploy, validate, fix issues, redeploy
  - [x] With stable deployment test Golden path
- [x] Validate PISP test provisioning and test collections (TTK) 
- [x] Identify issues with QA Scripts if any - fix them and retest
- [x] QA for bugs, regressions, log them
- [x] Fix bugs logged if critical
- [x] Deploy, validate on AWS Moja2
- [x] Validate with TTK GP collection
- [x] TTK test-cases repo v14.0.0 is published
- [x] Release notes for helm v14.0.0 drafted
  - [x] Guidance for migration from v13.1.0 (since this is a breaking change)
- [x] Update release notes with Upgrade Strategy Guide link
- [x] Helm v14.0.0 released
- [x] Review deployment guide documentation to ensure its up-to-date
- [x] Deployment of released Helm v14.0.0 on **Moja2**
  - [x] Helm v14.0.0 is deployed on **Moja2** successfully
  - [x] Validation using Golden path regression tests etc on Moja2
    - [x] TTK GP collection
    - [x] TTK Bulk collection
    - [x] TTK TP collection
    - [x] TTK Cron-job
  - [x] Validation using CGS Golden path regression tests etc on Moja2
- [x] Deployment of released Helm v14.0.0 on **Moja1**
  - [x] Helm v14.0.0 is deployed on **Moja1** successfully
  - [x] Validation using Golden path regression tests etc on Moja1
    - [x] TTK GP collection
    - [x] TTK Bulk collection
    - [x] TTK TP collection
  - [x] Validation using CGS Golden path regression tests etc on Moja1

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] TTK Tests pass
- [x] Code Style & Coverage meets standards
- [x] Release notes are verified

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/487
- [x] https://github.com/mojaloop/helm/pull/486
- [x] https://github.com/mojaloop/helm/pull/485
- [x] https://github.com/mojaloop/helm/pull/484
- [x] https://github.com/mojaloop/helm/pull/483
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/76

## **Issues**:
- N/A

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: 
- QA/Review: @mdebarros @elnyry-sam-k @vijayg10

**Comment by mdebarros** [comment]
Helm Test results for [v14.0.0-13708.b731bd4](https://github.com/mojaloop/helm/commit/b731bd4f03a93de2dd8014c3e3c00a5675197e48):

```
helm -n moja1 upgrade moja1 mojaloop/mojaloop --install -f values-moja1-test-mojaloop-harness.yaml --devel --version 14.0.0-13708.b731bd4
```

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP Tests
Environment: moja1.test.mojaloop.live
Total assertions: 2573
Passed assertions: 2573
Failed assertions: 0
Total requests: 587
Total test cases: 129
Passed percentage: 100.00%
Started time: Fri, 29 Jul 2022 09:37:39 GMT
Completed time: Fri, 29 Jul 2022 09:40:50 GMT
Runtime duration: 191247 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-07-29T09%3A40%3A50.561Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Bulk Tests
Environment: moja1.test.mojaloop.live
Total assertions: 183
Passed assertions: 183
Failed assertions: 0
Total requests: 17
Total test cases: 4
Passed percentage: 100.00%
Started time: Fri, 29 Jul 2022 09:41:58 GMT
Completed time: Fri, 29 Jul 2022 09:42:23 GMT
Runtime duration: 24969 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-07-29T09%3A42%3A23.663Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Thirdparty Tests
Environment: moja1.test.mojaloop.live
Total assertions: 21
Passed assertions: 21
Failed assertions: 0
Total requests: 20
Total test cases: 8
Passed percentage: 100.00%
Started time: Fri, 29 Jul 2022 09:45:12 GMT
Completed time: Fri, 29 Jul 2022 09:45:19 GMT
Runtime duration: 7560 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-07-29T09%3A45%3A19.587Z.html)

**Comment by mdebarros** [comment]
Default Helm install test results: 

```
--------------------FINAL REPORT--------------------

Test Suite:GP Tests
Environment:Development
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 2573                          │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 2573                          │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 0                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 587                           │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 129                           │
├───────────────────┼───────────────────────────────┤
│ Passed percentage │ 100.00%                       │
├───────────────────┼───────────────────────────────┤
│ Started time      │ Fri, 29 Jul 2022 10:04:09 GMT │
├───────────────────┼───────────────────────────────┤
│ Completed time    │ Fri, 29 Jul 2022 10:07:17 GMT │
├───────────────────┼───────────────────────────────┤
│ Runtime duration  │ 188284 ms                     │
└───────────────────┴───────────────────────────────┘
TTK-Assertion-Report-multi-2022-07-29T10:07:17.799Z.html was generated
```

**Comment by mdebarros** [comment]
Helm Test results for [14.0.0-13758.a0fe373](https://github.com/mojaloop/helm/commit/a0fe373d50fce8333e35b811f26cb4e2d3773bcf)

TBD
---

```
❯ helm -n moja2 upgrade moja2 mojaloop/mojaloop --install -f /Users/mdebarros/Documents/work/projects/mojaloop/git/deploy-config/mojaloop/test.mojaloop.live/values-moja1-test-mojaloop-harness.yaml --devel --version 14.0.0-13758.a0fe373
```

```
❯ helm list
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION                                                                                                                                                                                                                                                                                                                                                                                                                                                               
moja2   moja2           1               2022-07-29 14:35:01.44457 +0200 SAST    deployed        mojaloop-14.0.0-13758.a0fe373   ml-api-adapter: v14.0.0; central-ledger: v15.1.0; account-lookup-service: v13.0.0; quoting-service: v15.0.2; central-settlement: v14.0.0; central-event-processor: v12.0.0; bulk-api-adapter: v13.0.1; email-notifier: v12.0.0; als-oracle-pathfinder: v12.0.0; transaction-requests-service: v14.0.1; simulator: v12.0.0; mojaloop-simulator: v13.0.0; sdk-scheme-adapter: v18.0.2; thirdparty-sdk: v15.1.0; ml-testing-toolkit: v15.0.0; ml-testing-toolkit-ui: v15.0.0;
```

**Comment by mdebarros** [comment]
Helm Test Results for [helm/releases/tag/v14.0.0](https://github.com/mojaloop/helm/releases/tag/v14.0.0)
---

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP Tests
Environment: moja1.test.mojaloop.live@v14.0.0
Total assertions: 2573
Passed assertions: 2573
Failed assertions: 0
Total requests: 587
Total test cases: 129
Passed percentage: 100.00%
Started time: Fri, 29 Jul 2022 14:12:08 GMT
Completed time: Fri, 29 Jul 2022 14:15:16 GMT
Runtime duration: 187791 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-07-29T14%3A15%3A16.152Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Bulk Tests
Environment: moja1.test.mojaloop.live@v14.0.0
Total assertions: 183
Passed assertions: 183
Failed assertions: 0
Total requests: 17
Total test cases: 4
Passed percentage: 100.00%
Started time: Fri, 29 Jul 2022 14:15:36 GMT
Completed time: Fri, 29 Jul 2022 14:16:00 GMT
Runtime duration: 24810 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-07-29T14%3A16%3A00.956Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Thirdparty Tests
Environment: moja1.test.mojaloop.live@v14.0.0
Total assertions: 21
Passed assertions: 21
Failed assertions: 0
Total requests: 20
Total test cases: 8
Passed percentage: 100.00%
Started time: Fri, 29 Jul 2022 14:17:19 GMT
Completed time: Fri, 29 Jul 2022 14:17:26 GMT
Runtime duration: 7387 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-07-29T14%3A17%3A26.626Z.html)

---

```bash
```

```bash
❯ helm list
NAME 	NAMESPACE	REVISION	UPDATED                              	STATUS  	CHART                      	APP VERSION
moja1	moja1    	1       	2022-07-29 15:48:39.158425 +0200 SAST	deployed	mojaloop-14.0.0            	ml-api-adapter: v14.0.0; central-ledger: v15.1.0; account-lookup-service: v13.0.0; quoting-service: v15.0.2; central-settlement: v14.0.0; central-event-processor: v12.0.0; bulk-api-adapter: v13.0.1; email-notifier: v12.0.0; als-oracle-pathfinder: v12.0.0; transaction-requests-service: v14.0.1; simulator: v12.0.0; mojaloop-simulator: v13.0.0; sdk-scheme-adapter: v18.0.2; thirdparty-sdk: v15.1.0; ml-testing-toolkit: v15.0.0; ml-testing-toolkit-ui: v15.0.0;
```

**Comment by mdebarros** [comment]
---

---

```bash
❯ helm install moja2 mojaloop/mojaloop --version 14.0.0
```

```bash
❯ helm -n moja2 list
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION                                                                                                                                                                                                                                                                                                                                                                                                                                                               
moja2   moja2           1               2022-07-29 16:23:25.39373 +0200 SAST    deployed        mojaloop-14.0.0 ml-api-adapter: v14.0.0; central-ledger: v15.1.0; account-lookup-service: v13.0.0; quoting-service: v15.0.2; central-settlement: v14.0.0; central-event-processor: v12.0.0; bulk-api-adapter: v13.0.1; email-notifier: v12.0.0; als-oracle-pathfinder: v12.0.0; transaction-requests-service: v14.0.1; simulator: v12.0.0; mojaloop-simulator: v13.0.0; sdk-scheme-adapter: v18.0.2; thirdparty-sdk: v15.1.0; ml-testing-toolkit: v15.0.0; ml-testing-toolkit-ui: v15.0.0;
```

**Comment by mdebarros** [comment]
```
❯ helm search repo mojaloop/mojaloop --max-col-width 600
NAME                       	CHART VERSION	APP VERSION                                                                                                                                                                                                                                                                                                                                                                                                                                                               	DESCRIPTION
mojaloop/mojaloop          	14.0.0       	ml-api-adapter: v14.0.0; central-ledger: v15.1.0; account-lookup-service: v13.0.0; quoting-service: v15.0.2; central-settlement: v14.0.0; central-event-processor: v12.0.0; bulk-api-adapter: v13.0.1; email-notifier: v12.0.0; als-oracle-pathfinder: v12.0.0; transaction-requests-service: v14.0.1; simulator: v12.0.0; mojaloop-simulator: v13.0.0; sdk-scheme-adapter: v18.0.2; thirdparty-sdk: v15.1.0; ml-testing-toolkit: v15.0.0; ml-testing-toolkit-ui: v15.0.0;	Mojaloop Helm chart for Kubernetes
```
