### ISSUE TITLE
[SDK Scheme adaptor] Add Command Handler for bulk Discovery calls

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2813]
**As a** DFSP connected to Mojaloop 
**I would like to** use the bulk transfers use case
**So that I** can integrate bulk load disbursement calls with my core banking system

**Limitations**
- This story covers flows steps in 6 - 27 in the sequence diagram; these are the bulk discovery calls. 
I.e. from the first Post to Mojaloop Connector, to the first returned bulkPartyAccept results through the PUT Callback when:
- AutoAcceptParty is false and 
- synchronous is false.

 **Detailed Design**
The details of the design implementation are specified [here](https://github.com/mojaloop/sdk-scheme-adapter/tree/mvp/bulk-sdk/docs/design-bulk-transfers) 
   - [Outbound Event design](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/outbound-sequence.md)
   - [Outbound Redis Store](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/outbound_redis_message_format.md)
   - [Inbound Event design](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/inbound-bulk-transfers-sequence.md)
   - [Inbound Redis Store](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/inbound_redis_message_format.md)
 
**Acceptance Criteria**
- [ ] Verify that the Command handler manages all the commands necessary for Discovery
- [ ] Verify that narrow integration test are in-place to test the commands added (I.e. Kafka in --> Kafka out)
- [ ] Verify that these tests are called by the CICD

**Tasks**
- [ ]  Implement the Discovery commands
   - [x] Getting familiar with sdk-scheme-adapter new architecture design
   - [x] Build yarn workspaces in dependency order
   - [x] ProcessSDKOutboundBulkRequest
   - [x] ProcessSDKOutboundBulkPartyInfoRequest
   - [x] ProcessPartyInfoCallback
   - [x] ProcessSDKOutboundBulkPartyInfoRequestComplete
   - [x] Bug https://github.com/mojaloop/project/issues/2865 - Status OPEN
   - [x] Bug https://github.com/mojaloop/project/issues/2869 - Status CLOSED
   - [x] Bug https://github.com/mojaloop/project/issues/2870 - Status CLOSED
   - [x] Bug https://github.com/mojaloop/project/issues/2871 - Status CLOSED
   - [x] Bug https://github.com/mojaloop/project/issues/2872 - Status OPEN
   - [x] Bug https://github.com/mojaloop/project/issues/2875 - Status CLOSED
   - [x] Bug https://github.com/mojaloop/project/issues/2877 - Status OPEN
   - [ ] Bug https://github.com/mojaloop/project/issues/2878 - Status [This is part of quotes story #2802]
   - [x] Bug https://github.com/mojaloop/project/issues/2879 - Status CLOSED
   - [x] https://github.com/mojaloop/project/issues/2893 - Status OPEN
   - [x] Merge changes from master branch
  -  [x] Refactor event message names:
    * remove `Message` ending
    * add `DmEvent` ending for domain events, i.e. `SDKOutboundBulkAcceptPartyInfoRequestedDmEvent`
    * add `CmdEvent` ending for command events, i.e. `ProcessSDKOutboundBulkRequestCmdEvent`

- [ ] Create narrow integration testing framework
   - [x] Merge test code into working branch (Sri) - In Progress
   - [x] Write generic test functions (Not needed anymore)
   - [ ] ProcessSDKOutboundBulkRequest - BLOCKED because of bug 2879
   - [ ] ProcessSDKOutboundBulkPartyInfoRequest (Sri) - BLOCKED because of bug 2879
   - [ ] ProcessPartyInfoCallback (Sri) - BLOCKED because of bug 2879
   - [ ] ProcessSDKOutboundBulkPartyInfoRequestComplete (Sri) - BLOCKED because of bug 2879

- [ ] Create narrow integration tests for each of the above commands.

**Comment by sri-miriyala** [comment]
Integration Testing Update:

08/10:
- ProcessSDKOutboundBulkRequest - Kafka domain events are not being published for ProcessSDKOutboundBulkPartyInfoRequest
- ProcessSDKOutboundBulkPartyInfoRequest - Not able to run restructure-ddd-concepts branch locally. Shared the error details with Yevhen. Without running the code locally, not able to run any tests.

**Comment by sri-miriyala** [comment]
Opened the bug https://github.com/mojaloop/project/issues/2865 while testing Party callback
