### ISSUE TITLE
Enable External bulk TTK happy path test

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2814]
## **Goal**:
`As a`  hub operator 
`I want to` like to know that my Mojaloop hub deployment is configured to support bulk transfers
`so that` I can be confident in the service that I provide to participants.

**Note:**
- As this test needs to be through the API gateway with security enabled.  This is more easily achieved by modifying an existing PM4ML deployment with TTK configured to call the SDK-Scheme-Adapter's backend API's
- Test will be limited to happy path, and will only test the response as there will be no way of asserting against the Payee.
- The full golden path bulk test that check all scenarios is run internally and compliments this testing story

**Acceptance Criteria**:
- [ ]  Verify that a bulk quote can be called by and external participant in a Mojaloop hub with security enabled
- [ ]  Verify that a bulk transfer can be called by and external participant in a Mojaloop hub with security enabled

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
Found a bug in TTK helm chart while trying to deploy it in PM4ML. Logged the bug here https://github.com/mojaloop/project/issues/2860

**Comment by vijayg10** [comment]
Use the following TTK testcase and rules file for testing bulk.
[bulk-test-ttk.zip](https://github.com/mojaloop/project/files/9414478/bulk-test-ttk.zip)
