### ISSUE TITLE
Design Fulfil Rejection Scenario when Payee sends an Error message for rejection

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#282]
**Goal**:
As a Payee 
I wish to <http:put> __error message as per the API specifications for a fulfil rejection__
so that switch can execute the normal rejection process

**Tasks**:
- [ ] Update design documentation to include alt-flow for error put message
- [ ] Resolve aws API authentication issue

**Notes**:
- API Specification indicates that a normal PUT with status='aborted' or an Error message can be sent to the switch to reject the fulfilment. #247 catered for the design of the PUT with status='aborted' scenario. This story is to enhance that to cater for the alternative Error message scenario.

**Acceptance Criteria**:
- [ ] design documentation to include alt-flow for error put message showing the correct error code being sent to the switch
- [ ] Create implementation story to implement the Error-Rejection flow

**Dependencies**:
- n/a

**Accountability**
- Owner @mdebarros 
- Review @mdebarros

**Comment by elnyry** [comment]
This is now covered in #637
