### ISSUE TITLE
[Mojaloop] Extend the PUT \Transfers\{id} callback from Mojaloop to include the Extension List provided by the Payee DFSP in the PUT \Transfers\{id} callback

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2820]
## **Goal**:
`As a` Payee (of Payer) DFSP Participant involved in a transaction
`I want to` have the extension list associated with the transaction included in resultant PUT \Transfers\{id} (step 23) callback that is triggered by the GET \Transfers\{id} (step 22) api call
 `so that` I can use the extension list in the core banking system integration.

**Note:**
The FSPIOP already includes the extension list in the PUT \transfers\{id} callback from Mojaloop, however is has not been implemented yet and nothing is returned.
This story is about providing that information to complete the FSPIOP implementation.
The extension list that must be returned in the extension list that is returned by the Payee DFSP to Mojaloop in the PUT \transfers\{id} . This is the same call that returns the fulfilment.

**Acceptance Criteria**:
- [ ] Verify that the Extension list provided by the Payee DFSPs PUT \transfers\{id} (step 17) is included in the Mojaloop PUT \transfers\{id} (step 23) that is triggered after the mojaloop GET \transfers\{id} API (step 22) is called.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
