### ISSUE TITLE
[SDK Scheme Adapter] Extend the GET /transfers/{id} backend API response to include the homeTransactionId and the Extension List

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2821]
## **Goal**:
`As a` System Integrator building a Payee integration into Mojaloop
`I want to` query additional information associated with a transfer that has been provided in the extension lists
`so that` make use of this information in my backend API integration

**Acceptance Criteria**:
- [ ] Verify that backend API of the sdk-scheme-adapter open API definition is extended to include a HomeTransferId and an Extension List.
- [ ] Verify that the extension list provided in the backend API POST \transfers response (step15) is included in the GET \transfers\{id} response (step 25)
- [ ] Verify that the homeTransactionId is included in the GET \transfers\{id} response (step 25)

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
