### ISSUE TITLE
[IaC] AWS Platform - generate next IaC release for AWS

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2822]
## **Goal**:
`As a` Tech Ops deploying and maintaining a Mojaloop with tools deployment
`I want to` have an easy consolidated release that include the SDK certificate automation
`so that` easily release the latest functionality to existing and new environments

**Notes:**
Consolidate changes/overrides from Prod Dev to produce a new IaC release

**Acceptance Criteria**:
- [x] Verify that a new release to https://github.com/mojaloop/iac-aws-platform is made based on v13.0.2 of mojaloop
- [ ] Verify that release notes are updated
- [x] Verify that the new release is deployable and all passes GP tests.
- [x] Verify that releases are on the master/main branches

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---
Reference to github repos
Switch:  https://github.com/mojaloop/iac-aws-platform

**Tasks**:
- [x] Create a release for MCM dependencies
- [x] Create a Mojaloop IaC release
- [ ] 
- [ ] 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
