### ISSUE TITLE
Testing Spike - that include create test cases for next sprint stories

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2823]
## **Goal**:
`As a` delivery squad
`I want to` ensure that the testing strategy for the bulk development is sound, has a high code coverage and easy to extend an run
`so that` we can ensure reliable completion and deployment of the bulk functionality

`As a` delivery squad
`I want to` have test cases for the command handler that are designed to have high coverage
`so that` this can support the development

`As a` delivery squad
`I want to` have functional end-to-end test cases that can be used to confirm deployment
`so that` this can support the development and deployment of the bulk functionaliy

**Acceptance Criteria**:
- [x] Verify that the testing strategy is communicated to the team
- [x] Verify that the command handler test are added to the command handler repo 
- [x] Verify that end-to-end tests are created that use the TTK to test this functionality

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] 1. Review sequence diagram for Bulk
- [x] 2. define a testing strategy on integration tests and end to end tests
- [x] 3. Implement test frame work on the command handler for parties
- [x] 4. Implement test frame work on the command handler for quotes

**Done**
- [x] Acceptance Criteria pass
- [ ] Designs are up-to date [not applicable]
- [ ] Unit Tests pass [not applicable]
- [ ] Integration Tests pass [not applicable]
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config. [not applicable]
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
