### ISSUE TITLE
TechDebt: SDK-Standard-Components Dependency Upgrades

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2829]
## **Goal**:

`As a` Mojaloop Maintainer

`I want to` to address the dependency Technical Debt
  
`so that` all dependencies are fully upgraded thus improving maintainability and security concerns

**Acceptance Criteria**:
- [ ] dependencies are upgraded to latest version (`ilp-packet`): [sdk-standard-components/blob/master/.ncurc.yml](https://github.com/mojaloop/sdk-standard-components/blob/master/.ncurc.yml)
- [ ] Unit tests pass
- [ ] [sdk-standard-components/blob/master/.ncurc.yml](https://github.com/mojaloop/sdk-standard-components/blob/master/.ncurc.yml) file contains no entries in `reject` list

**Complexity**: Medium

**Uncertainty**: Low

Notes:

- This story is here to ensure that `ilp-packet` cannot be upgraded. Most likely it can't since later versions of the ILP-Packet are NOT compatible with the Mojaloop FSPIOP v1.x Specification.

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
