### ISSUE TITLE
API Validation for Currency codes is hardcoded using Joi

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#283]
**Goal**:
As a developer 
I would like to _load the currency codes from the DB currency table_
so that the currency code values are dynamically loaded from the DB instead of being hardcoded

**Tasks**:
- [ ] TBC

**Acceptance Criteria**:
- [ ] Agreed on approach for handling currency code validation (DB load vs Swagger/RAML open API generation)
- [ ] Documentation of approach/findings
- [ ] Create any stories that are required based on approach/findings as required

**Dependencies**:
- n/a

**Accountability**
- Owner @mdebarros 
- Review @mdebarros

**Comment by wdcmb** [comment]
It's the validation regex strings that need to be loaded/customised from the swagger(?)
I think the currencies are already populated.
