### ISSUE TITLE
TechDebt: Transaction-Request-Service Dependency Upgrades

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2836]
## **Goal**:

`As a` Mojaloop Maintainer

`I want to` to address the dependency Technical Debt
  
`so that` all dependencies are fully upgraded thus improving maintainability and security concerns

**Acceptance Criteria**:
- [ ] dependencies are upgraded to latest version (`get-port`): [transaction-requests-service/blob/master/.ncurc.yaml](https://github.com/mojaloop/transaction-requests-service/blob/master/.ncurc.yaml)
- [ ] Unit tests pass
- [ ] [transaction-requests-service/blob/master/.ncurc.yaml](https://github.com/mojaloop/transaction-requests-service/blob/master/.ncurc.yaml) file contains no entries in `reject` list

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
