### ISSUE TITLE
TechDebt: Mojaloop-Simulator Dependency Upgrades

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2840]
## **Goal**:

`As a` Mojaloop Maintainer

`I want to` to address the dependency Technical Debt
  
`so that` all dependencies are fully upgraded thus improving maintainability and security concerns

**Acceptance Criteria**:
- [ ] dependencies are upgraded to latest version (`eslint`, `node-fetch`, `ava`): [mojaloop-simulator/blob/master/.ncurc.json](https://github.com/mojaloop/mojaloop-simulator/blob/master/.ncurc.json)
- [ ] Unit tests pass
- [ ] [mojaloop-simulator/blob/master/.ncurc.json](https://github.com/mojaloop/mojaloop-simulator/blob/master/.ncurc.json) file contains no entries in `reject` list

**Complexity**: Medium

**Uncertainty**: Low

NOTE:

- `eslint` should be removed and replaced with `standard`, the Mojaloop standard linting tool unless there is a good reason not too?

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
