### ISSUE TITLE
TechDebt: ML-Testing-Toolkit-UI Dependency Upgrades

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2843]
## **Goal**:

`As a` Mojaloop Maintainer

`I want to` to address the dependency Technical Debt
  
`so that` all dependencies are fully upgraded thus improving maintainability and security concerns

**Acceptance Criteria**:
- [ ] dependencies are upgraded to latest version (`react`, `react-ace`, `react-dom`, `react-router-dom`, `react-scripts`, `web-vitals`, `@types/react`, `@testing-library/jest-dom`, `@testing-library/react`, `@testing-library/user-event`, `bootstrap`): [ml-testing-toolkit-ui/blob/master/.ncurc.yaml](https://github.com/mojaloop/ml-testing-toolkit-ui/blob/master/.ncurc.yaml)
- [ ] Unit tests pass
- [ ] [ml-testing-toolkit-ui/blob/master/.ncurc.yaml](https://github.com/mojaloop/ml-testing-toolkit-ui/blob/master/.ncurc.yaml) file contains no entries in `reject` list

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
