### ISSUE TITLE
QA: Replace Legacy-Simulator as a NORESPONSE_SIMPAYEE in Testing-Toolkit Goden Path Test-Suite

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2845]
## **Goal**:
`As a` Mojaloop Deployer

`I want to` replace `Legacy-Simulator` Interactions as a `NORESPONSE_SIMPAYEE` FSP with either TTK or Mojaloop-Simulator in the Testing-Toolkit Goden Path Test-Suite
  
`so that` Websocket notifications are used to improve the consistency of TTK Test-cases

> NOTES
>
> Without this change TTK GP Test Collections will fail occasionally due to timing issues introduced by the arbitrary delay.
>
> This feature will thus improve TTK GP Test Collection's consistency as it will remove the need to wait for an arbitrary delay, and instead we will be using the Web-socket to monitor for notification of requests/callbacks being received for this test scenario.
>

**Acceptance Criteria**:
- [x] Replace Legacy Simulator as a `NORESPONSE_SIMPAYEE` FSP  in GP Test-Cases with either TTK or Mojaloop-Simulator
- [x] Remove unnecessary `Use delay` where changes have been made to Test-Cases

**Complexity**: Medium

**Uncertainty**: Medium

NOTES:

-   Example of where this improvement needs to be made: https://github.com/mojaloop/testing-toolkit-test-cases/blob/master/collections/hub/golden_path/feature_tests/transfer_negative_scenarios/fulfil-reserved-v1.0.json#L278

---

**Tasks**:
- [x] Identify locations where Legacy-Simulator (i.e. `NORESPONSE_SIMPAYEE_NAME`) is still used.
- [x] Add new no response TTK 
- [x] Update test collection to point to new TTK
- [x] Remove delays in test collection

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/119
- [x] https://github.com/mojaloop/helm/pull/565

PI 21.0 - Use values-moja4-test-mojaloop-harness-v15.0.0.feat2845.yaml for testing in deploy-config

## **Follow-up**:
- N/A

**Dependencies**:
- #3176  

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
