### ISSUE TITLE
QA: Mojaloop TTK GP Test Collections to reset available liquidity after each run

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2846]
## **Goal**:
`As a` Mojaloop QA Tester

`I want to` Mojaloop TTK GP Test Collections to reset available liquidity after each run
  
`so that` tests do not fail with `insufficient liquidity after repeated runs

**Acceptance Criteria**:

- [ ] Repeated TTK GP Tests should not fail with `Insufficient Liquidity` as the Test-Cases should pre/post load `Funds-In` as required to ensure that Liquidity is always available when executing TTK GP Tests.
- [ ] OSS Moja1 environment does not fail due to `Insufficient Liquidity` after repeated runs from the daily testing cronjob.

Note: As the settlements process reset the positions of the DFSPs in the settlement window that allows to transnfer successfully, Settlements are run before and after the tests. 

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Observe the current tests [ @sri-miriyala ]
- [x] come up with a solution on NDC or settlement
- [x] Test settlement on bulk transfer window
- [x] Add settlement model manually
- [x] Add scripts as needed
- [x] Call settlements before Bulk tests [updating master.json]
- [x] Call settlements after bulk tests [updating master.json]
- [x] Call settlements before TTK tests start 
- [x] Call settlements after TTK tests end 
- [x] work on the failures
- [x] Modify pre set up collection to remove transfers in settlements
- [x] Include all windows in settlements that are closed
- [x] add fundsIn
- ~~[ ] add validate positions [Inprogress]~~ [This is blocked, pls read comments]
- [x] Run the tests

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Note**:
- Add to Deferred settlements test (similar to CGS)

**Comment by mdebarros** [comment]
Example of issue: 

```
Testing Toolkit Report
Test Result: FAILED
Test Suite: GP CronJob
Environment: moja1.test.mojaloop.live@v14.0.0
Total assertions: 2573
Passed assertions: 2491
Failed assertions: 82
Total requests: 587
Total test cases: 129
Passed percentage: 96.81%
Started time: Thu, 04 Aug 2022 08:00:05 GMT
Completed time: Thu, 04 Aug 2022 08:03:41 GMT
Runtime duration: 216040 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-08-04T08%3A03%3A41.485Z.html)

**Comment by elnyry-sam-k** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/2846?planning-poker) with Zenhub @mdebarros @vijayg10

**Comment by chris-me-law** [comment]
The scope increased after the sprint started

**Comment by sri-miriyala** [comment]
As per this story, settlements are being run to make sure that the positions get reset. But in discussing with the team, we felt it is beneficial to check the positions after running the settlements to make sure that the positions are indeed reverted back. 

Adding the position check functionality had a blocker. The way the test cases are spread out across multiple collections for easy readability, there is no option to share position values that were before and after running the bulk transfers across multiple TTK collections. To achieve this functionality, the collections need to be refactored so that they can share the state of the position data before and after running the bulk transfers. 

As the original goal of this story is met, the refactoring needed for the position check can be addressed as part of another story.

**Comment by sri-miriyala** [comment]
Reset positions story on the BULK GP :
https://github.com/mojaloop/project/issues/3068
