### ISSUE TITLE
DOCS: LTS Maintenance guidelines in Mojaloop's Standards Documentation

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2847]
## **Goal**:
`As a` Mojaloop Contributor

`I want to` have Standards documentation updated to include guidelines on LTS (NodeJS, CI, etc)
  
`so that` I am able to assist with maintaining Mojaloop's code-base when making contributions

**Acceptance Criteria**:
- [ ] Add guidelines for LTS to Mojaloop's Standards Documentation
    - [ ] Describe LTS life-cycle (and include links to products) for NodeJS, Kubernetes, Ubuntu (CI), etc
    - [ ] Describe how LTS is enforced in Mojaloop's repositories, and how one can go about updating repos to a newer LTS version.

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Duplicate of #2743
