### ISSUE TITLE
4.6.1 Design Duplicate Analysis in Server on Receiving a HTTP POST Request

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#285]
**Goal**:
As a Switch
I want to _design for duplicate analysis in Server on Receiving a HTTP POST Request (Prepare)_
so that duplicates are dealt with correctly (as per the specification API Documentation in section section 2.2.5.1).

**Tasks**:
- [x] Validate current design for duplicate analysis in Server on Receiving a HTTP POST Request (Prepare)
- [x] Changes to the Prepare Handler Sequence diagram
- [x] Add changes if required based on the acceptance criteria
- [ ] Review with the DA

**Acceptance Criteria**:
When a server receives a request from a client, the server should check to determine if there is an already-existing service object with the same ID; for example, if a client has previously sent the request POST /transfers with the identical transferId. If the object already exists, the server must check to determine if the parameters of the already-created object match the parameters from the new request.
- [x] If the previously-created object matches the parameter from the new request, the request should be assumed to be a resend from the client.
  - [x] If the server has not finished processing the old request and therefore has not yet sent the callback to the client, this new request can be ignored, because a callback is about to be sent to the client.
  - [x] If the server has finished processing the old request and a callback has already been sent, a new callback should be sent to the client, similar to if a HTTP GET request had been sent.
- [x] If the previously-created object does not match the parameters from the new request, an error callback should be sent to the client explaining that an object with the provided ID already exists with conflicting parameters.
- [ ] To simplify duplicate analysis, create and store a hash value of all incoming POST requests on the server, so that it is easy to compare the hash value against later incoming POST requests.

**Dependencies**:
- [ ] DA

**Accountability**:
- Owner @mdebarros                        
- QA/Review DA

**Comment by elnyry** [comment]
PR - https://github.com/mojaloop/docs/pull/42  is reviewed and approved
