### ISSUE TITLE
Upgrade Platform IaC to use Mojaloop 14.0.0

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2850]
## **Goal**:
`As a` Hub operator
`I want to` deploy the version v14.0.0 of Mojaloop
`so that` I can take advantage of the new features and bug fixes in the latest release

**Acceptance Criteria**:
- [ ] IaC deploys the latest Mojaloop version 14.0.0
- [ ] Golden path and bulk tests are passing on the deployment
- [ ] Tests for changes in Mojaloop 14.1.0 have been run and pass

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Identify tests needed to be run for the new deployment [@elnyry-sam-k ]
- [ ] Use IaC to deploy Mojaloop v14.0.0 
  - [ ] Run TTK GP tests and document results
  - [ ] Run Finance portal tests (BOF portal) and document results
  - [ ] Run PM4ML UI tests and document results
- [ ] If there are issues debug and create tasks or bugs/stories as needed [team]
- [ ] Validate k8s 1.24 compatibility in parallel to prepare for release [@dfry ]
- [ ] Separate out the Mojaloop Version from the Test-Collection Version for the `4. Run TTK Tests` Job to run the correct Test-Collection version for the appropriate release (ref: [gitlab-tests-ci.yml#L157](https://github.com/mojaloop/iac-aws-platform/blob/341f2c5b91b291809e34764b4337ce54bbbb9cd2/gitlab_templates/gitlab_ci_templates/.gitlab-tests-ci.yml#L157)).

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/2850?planning-poker) with Zenhub @mdebarros @vijayg10 @dfry

**Comment by vijayg10** [comment]
@elnyry-sam-k I think we should list out all the possible tests we want to execute to help operations team to follow.
Like switch GP, internal pm4ml gp, RBAC, UI e2e tests...etc. I think @sri-miriyala can help to populate that list.

**Comment by elnyry-sam-k** [comment]
v14.1.0 RC deployed on moja envts, looking good (tests passing) so far..

**Comment by elnyry-sam-k** [comment]
We have IaC support for Mojaloop (helm) releases v14.1.0, v14.1.1 and currently support for v15.0.0 is in progress.

Closing this for now but can be re-opened if there's a specific (implementer /adopter) request to provide IaC support for v14.0.0
