### ISSUE TITLE
[ML Bulk] Investigate time-out implementation for bulk transfers

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2853]
## **Goal**:
`As an` Switch offering Bulk feature of Mojaloop

`I want to` understand the bulk time-out implementation and document gaps if any
  
`so that` I can adopt the feature and address any gaps identified

Note: This came up as a follow-up to the story #2801 

**Acceptance Criteria**:
- [x] Bulk time-out functionality in Mojaloop is investigated and documented
- [x] Any gaps identified are documented as issues 
- [x] Sequence diagrams are updated if required, to conform to the specification and implementation

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [x] Investigate bulk functionality in Mojaloop by running (write tests if none existing) bulk time-out tests
- [x] Document gaps as issues for follow-up

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Below Log shows the `ML-API-Adapter Notification Handler` receiving the notification message from the `Bulk-Transfer-Prepare Handler`.

The message sent by the `Bulk-Transfer-Prepare Handler` for `duplicate request`, contains an incorrect action-type `PREPARE_DUPLICATE`. This action type is correct for standard `duplicate requests` for Transfers but not for BulkTransfer-requests. A new action type will be required for the  `ML-API-Adapter Notification Handler` to correctly handle this event.

```log
2022-08-04T15:01:21.465Z - info: Notification:consumeMessage message: - [{"value":{"from":"switch","to":"testingtoolkitdfsp","id":"b463e02c-9258-402a-be03-feb57274d230","content":{"headers":{"content-type":"application/vnd.interoperability.bulkTransfers+json;version=1.1","accept":"application/vnd.interoperability.bulkTransfers+json;version=1.1","date":"2022-08-04T14:59:01.000Z","fspiop-source":"testingtoolkitdfsp","fspiop-destination":"testingtoolkitdfsp","traceparent":"00-aabb44abb3367f14172312744d8f6704-0123456789abcdef0-00","user-agent":"axios/0.27.2","content-length":2720,"host":"moja2-bulk-api-adapter-service","connection":"keep-alive"},"payload":{"bulkTransferState":"COMPLETED","completedTimestamp":"2022-08-04T14:59:06.000Z","individualTransferResults":[{"transferId":"2c12f314-b8e7-499e-ae2e-90f743f0b5bc","fulfilment":"tChMwYE5Zw9ZDiU6cUQyeLmReAE55dG74MJKHPWNjvs"},{"transferId":"a14dffbe-6259-4581-bd7b-9f7931240726","fulfilment":"tChMwYE5Zw9ZDiU6cUQyeLmReAE55dG74MJKHPWNjvs"}]},"uriParams":{"id":"cd4331c2-5288-4c55-9e5f-8761ebc312a6"}},"type":"application/json","metadata":{"event":{"id":"0a144027-fea5-4870-a99c-e107c7336a50","type":"notification","action":"prepare-duplicate","createdAt":"2022-08-04T14:59:06.296Z","state":{"status":"success","code":0,"description":"action successful"},"responseTo":"2b418464-bebd-45a0-b0f9-885a03c99e3a"},"protocol.createdAt":1659625281457}},"size":1317,"key":null,"topic":"topic-notification-event","offset":610,"partition":0,"timestamp":1659625281458}]
2022-08-04T15:01:21.466Z - info: Notification::consumeMessage::processMessage
2022-08-04T15:01:21.467Z - info: Notification::processMessage
2022-08-04T15:01:21.467Z - info: Notification::processMessage action: prepare-duplicate
2022-08-04T15:01:21.467Z - info: Notification::processMessage status: success
2022-08-04T15:01:21.467Z - info: Notification::getJWSSigner: get JWS signer
2022-08-04T15:01:21.468Z - info: participantEndpointCache::getEndpoint::endpointType - FSPIOP_CALLBACK_URL_TRANSFER_PUT
2022-08-04T15:01:21.468Z - info: [fsp=testingtoolkitdfsp] ~ participantEndpointCache::fetchEndpoints := Refreshing the cache for FSP: testingtoolkitdfsp
2022-08-04T15:01:21.468Z - info: sendRequest::request {"url":"http://moja2-centralledger-service:80/participants/testingtoolkitdfsp/endpoints","method":"GET","headers":{"accept":"application/vnd.interoperability.participants+json;version=1","FSPIOP-Destination":"switch","Content-Type":"application/vnd.interoperability.participants+json;version=1.0","date":"Thu, 04 Aug 2022 15:01:21 GMT","FSPIOP-Source":"switch"},"responseType":"json"}
2022-08-04T15:01:21.474Z - info: Success: sendRequest::response {"status":200,"statusText":"OK","headers":{},"config":{"headers":{}},"request":{},"data":[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]}
2022-08-04T15:01:21.477Z - audit: {
  "type": "application/json",
  "content": {
    "url": "http://moja2-ml-testing-toolkit-backend:4040/transfers/cd4331c2-5288-4c55-9e5f-8761ebc312a6",
    "method": "PUT",
    "headers": {
      "content-type": "application/vnd.interoperability.bulkTransfers+json;version=1.1",
      "date": "Thu, 04 Aug 2022 14:59:01 GMT",
      "traceparent": "00-09d8e508374518abeb8677293af7539e-857d3c68c2896e5d-00",
      "user-agent": "axios/0.27.2",
      "connection": "keep-alive",
      "fspiop-http-method": "PUT",
      "fspiop-uri": "/transfers/cd4331c2-5288-4c55-9e5f-8761ebc312a6",
      "fspiop-source": "switch",
      "fspiop-destination": "testingtoolkitdfsp",
      "fspiop-signature": "{\"signature\":\"67auuLFuaHVmFBTmWl5xcbm_y99VnBk58M8xJpgjlgUMU-iwr9fLZ1xh3phGTdk3JLgi6aca45Ft_9VfUAfnVlk0RvDREgaIyEZio5vPFS3CJUZp7pMVEoTc_kI6br3009fkanaxYj4Kvf2o5KLuHYT7EYYuPqfz5-6BcejXYUAbVQ-WqGc2cHBI15L0ltuyoATkRaAlZ_dnfpowlg5D0FMRbAxg5fn9OLoSOpPvGJ3A7x-zrZD3sPsIXTlt3RbJtnRfg6RBof4iGl-am0Nhx_-pBkZItv6sGB5SdCf7A9vlHBkMTr9ko_BjRPGm45kVdiQDf6nynUe_-pqLBARN7Q\",\"protectedHeader\":\"eyJhbGciOiJSUzI1NiIsIkZTUElPUC1VUkkiOiIvdHJhbnNmZXJzL2NkNDMzMWMyLTUyODgtNGM1NS05ZTVmLTg3NjFlYmMzMTJhNiIsIkZTUElPUC1IVFRQLU1ldGhvZCI6IlBVVCIsIkZTUElPUC1Tb3VyY2UiOiJzd2l0Y2giLCJGU1BJT1AtRGVzdGluYXRpb24iOiJ0ZXN0aW5ndG9vbGtpdGRmc3AiLCJEYXRlIjoiVGh1LCAwNCBBdWcgMjAyMiAxNDo1OTowMSBHTVQifQ\"}",
      "tracestate": "mojaloop=eyJzcGFuSWQiOiI4NTdkM2M2OGMyODk2ZTVkIn0="
    },
    "data": "{\"bulkTransferState\":\"COMPLETED\",\"completedTimestamp\":\"2022-08-04T14:59:06.000Z\",\"individualTransferResults\":[{\"transferId\":\"2c12f314-b8e7-499e-ae2e-90f743f0b5bc\",\"fulfilment\":\"tChMwYE5Zw9ZDiU6cUQyeLmReAE55dG74MJKHPWNjvs\"},{\"transferId\":\"a14dffbe-6259-4581-bd7b-9f7931240726\",\"fulfilment\":\"tChMwYE5Zw9ZDiU6cUQyeLmReAE55dG74MJKHPWNjvs\"}]}",
    "responseType": "json"
  },
  "id": "05f6e5a8-5ac0-40dc-9c9f-0f643661c49f",
  "metadata": {
    "event": {
      "id": "7427f2dd-c0dd-47df-8370-5c3ca007369c",
      "type": "audit",
      "action": "egress",
      "createdAt": "2022-08-04T15:01:21.477Z",
      "state": {
        "status": "success"
      }
    },
    "trace": {
      "service": "ml_notification_event",
      "traceId": "09d8e508374518abeb8677293af7539e",
      "spanId": "857d3c68c2896e5d",
      "startTimestamp": "2022-08-04T15:01:21.466Z",
      "tags": {
        "tracestate": "mojaloop=eyJzcGFuSWQiOiI4NTdkM2M2OGMyODk2ZTVkIn0="
      },
      "tracestates": {
        "mojaloop": {
          "spanId": "857d3c68c2896e5d"
        }
      }
    }
  }
}

2022-08-04T15:01:21.477Z - info: sendRequest::request {"url":"http://moja2-ml-testing-toolkit-backend:4040/transfers/cd4331c2-5288-4c55-9e5f-8761ebc312a6","method":"PUT","headers":{"content-type":"application/vnd.interoperability.bulkTransfers+json;version=1.1","date":"Thu, 04 Aug 2022 14:59:01 GMT","traceparent":"00-09d8e508374518abeb8677293af7539e-857d3c68c2896e5d-00","user-agent":"axios/0.27.2","connection":"keep-alive","fspiop-http-method":"PUT","fspiop-uri":"/transfers/cd4331c2-5288-4c55-9e5f-8761ebc312a6","fspiop-source":"switch","fspiop-destination":"testingtoolkitdfsp","fspiop-signature":"{\"signature\":\"67auuLFuaHVmFBTmWl5xcbm_y99VnBk58M8xJpgjlgUMU-iwr9fLZ1xh3phGTdk3JLgi6aca45Ft_9VfUAfnVlk0RvDREgaIyEZio5vPFS3CJUZp7pMVEoTc_kI6br3009fkanaxYj4Kvf2o5KLuHYT7EYYuPqfz5-6BcejXYUAbVQ-WqGc2cHBI15L0ltuyoATkRaAlZ_dnfpowlg5D0FMRbAxg5fn9OLoSOpPvGJ3A7x-zrZD3sPsIXTlt3RbJtnRfg6RBof4iGl-am0Nhx_-pBkZItv6sGB5SdCf7A9vlHBkMTr9ko_BjRPGm45kVdiQDf6nynUe_-pqLBARN7Q\",\"protectedHeader\":\"eyJhbGciOiJSUzI1NiIsIkZTUElPUC1VUkkiOiIvdHJhbnNmZXJzL2NkNDMzMWMyLTUyODgtNGM1NS05ZTVmLTg3NjFlYmMzMTJhNiIsIkZTUElPUC1IVFRQLU1ldGhvZCI6IlBVVCIsIkZTUElPUC1Tb3VyY2UiOiJzd2l0Y2giLCJGU1BJT1AtRGVzdGluYXRpb24iOiJ0ZXN0aW5ndG9vbGtpdGRmc3AiLCJEYXRlIjoiVGh1LCAwNCBBdWcgMjAyMiAxNDo1OTowMSBHTVQifQ\"}","tracestate":"mojaloop=eyJzcGFuSWQiOiI4NTdkM2M2OGMyODk2ZTVkIn0="},"data":"{\"bulkTransferState\":\"COMPLETED\",\"completedTimestamp\":\"2022-08-04T14:59:06.000Z\",\"individualTransferResults\":[{\"transferId\":\"2c12f314-b8e7-499e-ae2e-90f743f0b5bc\",\"fulfilment\":\"tChMwYE5Zw9ZDiU6cUQyeLmReAE55dG74MJKHPWNjvs\"},{\"transferId\":\"a14dffbe-6259-4581-bd7b-9f7931240726\",\"fulfilment\":\"tChMwYE5Zw9ZDiU6cUQyeLmReAE55dG74MJKHPWNjvs\"}]}","responseType":"json"}
2022-08-04T15:01:21.485Z - error: Request failed with status code 400

2022-08-04T15:01:21.486Z - error: {
  "type": "application/json",
  "content": {
    "error": {
      "name": "FSPIOPError",
      "cause": {
        "message": "Request failed with status code 400",
        "name": "AxiosError",
        "config": {
          "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
          },
          "transformRequest": [
            null
          ],
          "transformResponse": [
            null
          ],
          "timeout": 0,
          "xsrfCookieName": "XSRF-TOKEN",
          "xsrfHeaderName": "X-XSRF-TOKEN",
          "maxContentLength": -1,
          "maxBodyLength": -1,
          "env": {},
          "headers": {
            "Content-Type": "application/vnd.interoperability.bulkTransfers+json;version=1.1",
            "date": "Thu, 04 Aug 2022 14:59:01 GMT",
            "traceparent": "00-09d8e508374518abeb8677293af7539e-857d3c68c2896e5d-00",
            "user-agent": "axios/0.27.2",
            "connection": "keep-alive",
            "fspiop-http-method": "PUT",
            "fspiop-uri": "/transfers/cd4331c2-5288-4c55-9e5f-8761ebc312a6",
            "fspiop-source": "switch",
            "fspiop-destination": "testingtoolkitdfsp",
            "fspiop-signature": "{\"signature\":\"67auuLFuaHVmFBTmWl5xcbm_y99VnBk58M8xJpgjlgUMU-iwr9fLZ1xh3phGTdk3JLgi6aca45Ft_9VfUAfnVlk0RvDREgaIyEZio5vPFS3CJUZp7pMVEoTc_kI6br3009fkanaxYj4Kvf2o5KLuHYT7EYYuPqfz5-6BcejXYUAbVQ-WqGc2cHBI15L0ltuyoATkRaAlZ_dnfpowlg5D0FMRbAxg5fn9OLoSOpPvGJ3A7x-zrZD3sPsIXTlt3RbJtnRfg6RBof4iGl-am0Nhx_-pBkZItv6sGB5SdCf7A9vlHBkMTr9ko_BjRPGm45kVdiQDf6nynUe_-pqLBARN7Q\",\"protectedHeader\":\"eyJhbGciOiJSUzI1NiIsIkZTUElPUC1VUkkiOiIvdHJhbnNmZXJzL2NkNDMzMWMyLTUyODgtNGM1NS05ZTVmLTg3NjFlYmMzMTJhNiIsIkZTUElPUC1IVFRQLU1ldGhvZCI6IlBVVCIsIkZTUElPUC1Tb3VyY2UiOiJzd2l0Y2giLCJGU1BJT1AtRGVzdGluYXRpb24iOiJ0ZXN0aW5ndG9vbGtpdGRmc3AiLCJEYXRlIjoiVGh1LCAwNCBBdWcgMjAyMiAxNDo1OTowMSBHTVQifQ\"}",
            "tracestate": "mojaloop=eyJzcGFuSWQiOiI4NTdkM2M2OGMyODk2ZTVkIn0=",
            "Content-Length": 337
          },
          "url": "http://moja2-ml-testing-toolkit-backend:4040/transfers/cd4331c2-5288-4c55-9e5f-8761ebc312a6",
          "method": "put",
          "data": "{\"bulkTransferState\":\"COMPLETED\",\"completedTimestamp\":\"2022-08-04T14:59:06.000Z\",\"individualTransferResults\":[{\"transferId\":\"2c12f314-b8e7-499e-ae2e-90f743f0b5bc\",\"fulfilment\":\"tChMwYE5Zw9ZDiU6cUQyeLmReAE55dG74MJKHPWNjvs\"},{\"transferId\":\"a14dffbe-6259-4581-bd7b-9f7931240726\",\"fulfilment\":\"tChMwYE5Zw9ZDiU6cUQyeLmReAE55dG74MJKHPWNjvs\"}]}",
          "responseType": "json"
        },
        "code": "ERR_BAD_REQUEST",
        "status": 400
      },
      "replyTo": "switch",
      "apiErrorCode": {
        "code": "1001",
        "message": "Destination communication error",
        "name": "DESTINATION_COMMUNICATION_ERROR",
        "type": {
          "regex": "^10[0-9]{2}$",
          "description": "Generic Communication Error",
          "httpStatusCode": 503,
          "name": "GENERIC_COMMUNICATION_ERROR"
        },
        "httpStatusCode": 503
      },
      "httpStatusCode": 503,
      "extensions": [
        {
          "key": "status",
          "value": 400
        },
        {
          "key": "cause",
          "value": "[{\"key\":\"url\",\"value\":\"http://moja2-ml-testing-toolkit-backend:4040/transfers/cd4331c2-5288-4c55-9e5f-8761ebc312a6\"},{\"key\":\"sourceFsp\",\"value\":\"switch\"},{\"key\":\"destinationFsp\",\"value\":\"testingtoolkitdfsp\"},{\"key\":\"method\",\"value\":\"PUT\"},{\"key\":\"request\",\"value\":\"{\\\"url\\\":\\\"http://moja2-ml-testing-toolkit-backend:4040/transfers/cd4331c2-5288-4c55-9e5f-8761ebc312a6\\\",\\\"method\\\":\\\"PUT\\\",\\\"headers\\\":{\\\"content-type\\\":\\\"application/vnd.interoperability.bulkTransfers+json;version=1.1\\\",\\\"date\\\":\\\"Thu, 04 Aug 2022 14:59:01 GMT\\\",\\\"traceparent\\\":\\\"00-09d8e508374518abeb8677293af7539e-857d3c68c2896e5d-00\\\",\\\"user-agent\\\":\\\"axios/0.27.2\\\",\\\"connection\\\":\\\"keep-alive\\\",\\\"fspiop-http-method\\\":\\\"PUT\\\",\\\"fspiop-uri\\\":\\\"/transfers/cd4331c2-5288-4c55-9e5f-8761ebc312a6\\\",\\\"fspiop-source\\\":\\\"switch\\\",\\\"fspiop-destination\\\":\\\"testingtoolkitdfsp\\\",\\\"fspiop-signature\\\":\\\"{\\\\\\\"signature\\\\\\\":\\\\\\\"67auuLFuaHVmFBTmWl5xcbm_y99VnBk58M8xJpgjlgUMU-iwr9fLZ1xh3phGTdk3JLgi6aca45Ft_9VfUAfnVlk0RvDREgaIyEZio5vPFS3CJUZp7pMVEoTc_kI6br3009fkanaxYj4Kvf2o5KLuHYT7EYYuPqfz5-6BcejXYUAbVQ-WqGc2cHBI15L0ltuyoATkRaAlZ_dnfpowlg5D0FMRbAxg5fn9OLoSOpPvGJ3A7x-zrZD3sPsIXTlt3RbJtnRfg6RBof4iGl-am0Nhx_-pBkZItv6sGB5SdCf7A9vlHBkMTr9ko_BjRPGm45kVdiQDf6nynUe_-pqLBARN7Q\\\\\\\",\\\\\\\"protectedHeader\\\\\\\":\\\\\\\"eyJhbGciOiJSUzI1NiIsIkZTUElPUC1VUkkiOiIvdHJhbnNmZXJzL2NkNDMzMWMyLTUyODgtNGM1NS05ZTVmLTg3NjFlYmMzMTJhNiIsIkZTUElPUC1IVFRQLU1ldGhvZCI6IlBVVCIsIkZTUElPUC1Tb3VyY2UiOiJzd2l0Y2giLCJGU1BJT1AtRGVzdGluYXRpb24iOiJ0ZXN0aW5ndG9vbGtpdGRmc3AiLCJEYXRlIjoiVGh1LCAwNCBBdWcgMjAyMiAxNDo1OTowMSBHTVQifQ\\\\\\\"}\\\",\\\"tracestate\\\":\\\"mojaloop=eyJzcGFuSWQiOiI4NTdkM2M2OGMyODk2ZTVkIn0=\\\"},\\\"data\\\":\\\"{\\\\\\\"bulkTransferState\\\\\\\":\\\\\\\"COMPLETED\\\\\\\",\\\\\\\"completedTimestamp\\\\\\\":\\\\\\\"2022-08-04T14:59:06.000Z\\\\\\\",\\\\\\\"individualTransferResults\\\\\\\":[{\\\\\\\"transferId\\\\\\\":\\\\\\\"2c12f314-b8e7-499e-ae2e-90f743f0b5bc\\\\\\\",\\\\\\\"fulfilment\\\\\\\":\\\\\\\"tChMwYE5Zw9ZDiU6cUQyeLmReAE55dG74MJKHPWNjvs\\\\\\\"},{\\\\\\\"transferId\\\\\\\":\\\\\\\"a14dffbe-6259-4581-bd7b-9f7931240726\\\\\\\",\\\\\\\"fulfilment\\\\\\\":\\\\\\\"tChMwYE5Zw9ZDiU6cUQyeLmReAE55dG74MJKHPWNjvs\\\\\\\"}]}\\\",\\\"responseType\\\":\\\"json\\\"}\"},{\"key\":\"errorMessage\",\"value\":\"Request failed with status code 400\"},{\"key\":\"status\",\"value\":400},{\"key\":\"response\",\"value\":{\"errorInformation\":{\"errorCode\":\"3100\",\"errorDescription\":\"must have required property 'transferState'\",\"extensionList\":[{\"key\":\"keyword\",\"value\":\"required\"},{\"key\":\"instancePath\",\"value\":\"/requestBody\"},{\"key\":\"missingProperty\",\"value\":\"transferState\"}]}}}]"
        }
      ],
      "useMessageAsDescription": false,
      "message": "Failed to send HTTP request to host",
      "stack": "FSPIOPError: Failed to send HTTP request to host\n    at Object.createFSPIOPError (/opt/app/node_modules/@mojaloop/central-services-error-handling/src/factory.js:198:12)\n    at Object.sendRequest (/opt/app/node_modules/@mojaloop/central-services-shared/src/util/request.js:127:46)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async processMessage (/opt/app/src/handlers/notification/index.js:304:5)\n    at async consumeMessage (/opt/app/src/handlers/notification/index.js:152:21)"
    }
  },
  "id": "56790ef3-0695-460d-bf80-9bd67a950722",
  "metadata": {
    "event": {
      "id": "2737e836-a21b-4fee-af9e-0a87554f5fa4",
      "type": "log",
      "action": "error",
      "createdAt": "2022-08-04T15:01:21.486Z",
      "state": {
        "status": "failed",
        "code": "1001",
        "description": "Destination communication error"
      }
    },
    "trace": {
      "service": "ml_notification_event_sendRequest",
      "traceId": "09d8e508374518abeb8677293af7539e",
      "spanId": "972c5a4895e2e060",
      "parentSpanId": "857d3c68c2896e5d",
      "startTimestamp": "2022-08-04T15:01:21.475Z",
      "tags": {
        "tracestate": "mojaloop=eyJzcGFuSWQiOiI5NzJjNWE0ODk1ZTJlMDYwIn0=",
        "source": "switch",
        "destination": "testingtoolkitdfsp",
        "method": "PUT",
        "url": "http://moja2-ml-testing-toolkit-backend:4040/transfers/cd4331c2-5288-4c55-9e5f-8761ebc312a6"
      },
      "tracestates": {
        "mojaloop": {
          "spanId": "972c5a4895e2e060"
        }
      }
    }
  }
}
```

**Comment by kleyow** [comment]
Prepare request with short expiration window timeout.

Test written.
```
{
  "request": {
    "uniqueId": "1660689435124frquwm",
    "headers": {
      "content-type": "application/vnd.interoperability.transfers+json;version=1.1",
      "fspiop-destination": "testingtoolkitdfsp",
      "date": "Tue, 16 Aug 2022 22:37:15 GMT",
      "fspiop-source": "switch",
      "fspiop-http-method": "PUT",
      "fspiop-uri": "/testingtoolkitdfsp/bulkTransfers/046084b4-dc12-48d2-8edc-8a3566e6fe93",
      "user-agent": "axios/0.27.2",
      "content-length": "327",
      "host": "moja3-ml-testing-toolkit-backend:4040",
      "connection": "close"
    },
    "queryParams": {},
    "body": {
      "bulkTransferState": "COMPLETED",
      "individualTransferResults": [
        {
          "errorInformation": {
            "errorCode": "3303",
            "errorDescription": "Transfer expired"
          },
          "transferId": "dd168a98-d842-4b52-bc6f-ed4a9027e2ac"
        },
        {
          "errorInformation": {
            "errorCode": "3303",
            "errorDescription": "Transfer expired"
          },
          "transferId": "7185201a-68f2-4d57-892e-ecb8ab398f9d"
        }
      ]
    }
  }
}
```

Documentation seems inline. @elnyry-sam-k lets go through it together when we're both online.

What are the other timeout scenarios are there Sam, if any?

**Comment by kleyow** [comment]
Documentation improvements

1. Updating payload to 3303 error used in implementation
![image](https://user-images.githubusercontent.com/5932442/185199371-84505cfc-51b7-448c-9ae0-ccd70ebb299f.png)

**Comment by kleyow** [comment]
Tests needed.

1) POST /bulkTransfers prepare request which has timed out. Assert both Payer and Payee receive PUT /bulkTransfers/{ID} callbacks detailing a COMPLETED bulkTransfer with individualTransfer errors for all transfers.

2) POST /bulkTransfers prepare request which has timed out and the Payee sends a PUT /bulkTransfers/{ID} fulfilment request. Assert both Payer and Payee receive PUT /bulkTransfers/{ID} callbacks detailing a COMPLETED bulkTransfer with individualTransfer errors for all transfers. Payee recieves some error on late fulfilment.


3) POST /bulkTransfers prepare request which has timed out **in the middle of a large set of individual transfers**  Assert both Payer and Payee receive PUT /bulkTransfers/{ID} callbacks detailing a COMPLETED bulkTransfer with individualTransfer errors for a partial amount of transfers and sucessful fulfilments for the rest.
