### ISSUE TITLE
Participants BC - Add integration tests

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#2858]
Goal:
- Add unit tests with coverage above 90%

# Tasks
- [ ] Integration tests
- [x] CircleCI build
- [x] Restructure to be called `packages` and not `modules`
- [x] Restructure integration tests to be outside of packages
- [x] Update the `README.md`
- [x] add `.husky` from logging-bc

# References

Circle-CI: https://github.com/mojaloop/logging-bc/tree/main/.circleci

<img width="496" alt="image" src="https://user-images.githubusercontent.com/1992108/188472309-6c5ceddb-41df-44c5-b0c2-250d00cf90d7.png">

**Comment by koekiebox** [comment]
- [ ] CircleCI build
- [ ] Restructure to be called `packages` and not `modules`
- [ ] Restructure integration tests to be outside of packages
- [ ] Update the `README.md`

# References

Circle-CI: https://github.com/mojaloop/logging-bc/tree/main/.circleci

<img width="496" alt="image" src="https://user-images.githubusercontent.com/1992108/188472309-6c5ceddb-41df-44c5-b0c2-250d00cf90d7.png">

**Comment by elnyry-sam-k** [comment]
In the most recent run here for participants-bc, there's no integration test step in the CI: https://app.circleci.com/pipelines/github/mojaloop/participants-bc/317/workflows/eb9cc878-9d88-4dfc-991d-ee0654fc0973

**Comment by JulieG19** [comment]
There is a change of strategy with vNext. I am closing this ticket accordingly to that change.
