### ISSUE TITLE
Ensure FiveBellsCondition.fulfillmentToCondition always passes

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#286]
**Goal**:
As a **developer**
I want to be able to _xxxxxx_
so that I can 

**Note**:
This story needs clarity. This was added as follow-up to the story #272 

FiveBellsCondition.fulfillmentToCondition always returns `ni:///sha-256;47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU?fpt=preimage-sha-256&cost=0` no matter the input parameter. Tested with 'oAKAAA', 'oAKAAA---AAA', 'oAKAAA---BBB'.
It is currently used as fulfilment check in script file 'src/handlers/transfers/handler.js' which always returns **true**. Please, look up the code for `TODO: FiveBellsCondition.fulfillmentToCondition always passes`. The input fulfilment for testing purposes is controlled by 'testPI2/integration/helpers/testProducer.js:36' (look up `fulfilment:`)

**Tasks**:
- [ ] Investigate failure in the FiveBellsCondition.fulfillmentToCondition
- [ ] Fix

**Acceptance Criteria**:
- [ ] Analysis performed on why FiveBellsCondition.fulfillmentToCondition is failing
- [ ] Ensure FiveBellsCondition.fulfillmentToCondition passes always

**Dependencies**:
- [ ] #272 

**Accountability**
- Owner
- Review

**Comment by elnyry** [comment]
Replaced, can be closed out
