### ISSUE TITLE
TTK Helm - Configurable rules through helm values

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2861]
## **Goal**:
`As a` individual implementer

`I want to` configure various rules in TTK through the helm chart
  
`so that` I can deploy TTK with preinstalled rules for my test use cases

**Acceptance Criteria**:
- [x] The following rules can be configured using helm values
  - [x] Callback Rules
  - [x] Sync Response Rules
  - [x] Validation Rules

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Populate the default rules based on the helm values file.
- [x] Deploy the helm chart and test the rules.
- [x] Deploy the mojaloop with the new TTK helm chart and run regression tests.
- [x] Make sure the PR is merged to master and a snapshot version is released.

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/500

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/2861?planning-poker) with Zenhub @kleyow @mdebarros @vijayg10

**Comment by vijayg10** [comment]
The PR is merged to master and we got development release of TTK helm chart `mojaloop/ml-testing-toolkit:15.1.0-14029.147b298`
