### ISSUE TITLE
TTK Helm - Configurable API definitions through helm values

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2862]
## **Goal**:
`As a` individual implementer

`I want to` configure new API definitions in TTK through the helm chart
  
`so that` I can deploy TTK with preinstalled API definitions for my test use cases

**Acceptance Criteria**:
- [ ] A new API definition can be added through helm values

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
This feature can be done in the same way we are doing for rules. See the changes in this PR https://github.com/mojaloop/helm/pull/500

i.e. api definitions can be specified through the config section of the TTK helm chart using the following syntax.
api_definitions**__**<foldername>__api_spec.yaml: <content / URL>
