### ISSUE TITLE
TTK: Support for markdown in additional info in testcases

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#2866]
## **Goal**:
`As a` TTK User

`I want to` have the feature of markdown support for the info field in meta section of the test_cases of TTK json
  
`so that` the rendering of lengthy lines can be converted to multi-lines which shows up as a readable format in TTK reports

**Acceptance Criteria**:
- [ ] Multiline is supported in the info field

**Complexity**: Medium. I am planning to use Gherkin syntax for the description of bulk test cases. Having this multi-line support for Given, When and Then is required for better readability.

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: Sridevi
