### ISSUE TITLE
Refactor tables affecting/affected-by positions

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#287]
**Goal**:
As a developer
I would like to _refactor the tables related to positions_
so that the position calculations can be optimally affected and persisted when relevant.

**Tasks**:
- [ ] Refactor these tables as necessary
  - [ ] participantLimit
  - [ ] transferPosition
- [ ] Refactor the Data Model / Schema of these tables as necessary
  - [ ] participantLimit
  - [ ] transferPosition

**Acceptance Criteria**:
- [ ] Positions related tables are refactored and renamed if necessary to consist of the fields necessary for position calculation and persisting.

**Dependencies**:
- [ ] None currently

**Accountability**:
- Owner
- Review

**Comment by elnyry** [comment]
duplicate of #342  (also outdated)
