### ISSUE TITLE
[ML Bulk] Switch Bulk Fulfilment to handle duplicate requests

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2873]
## **Goal**:
`As a` Hub Operator

`I want to` have Bulk Fulfilment Callback Requests handle Duplicates
  
`so that` FSPs can receive the correct Callback (i.e. Error Get) feedback for such Non-happy Use-Cases

**Acceptance Criteria**:
- [ ] Bulk Fulfilment Callback Requests handles Duplicates WHEN Fulfilment Callback is an exact duplicate
    - [ ] It will be handled as a GET request from the Payee FSPs perspective IF and ONLY IF the state of the Bulk is in a final state (i.e. COMPLETED, ABORTED)
    - [ ] It will be ignored IF and ONLY IF the Bulk is still being processed (i.e. NOT a final state)
- [ ] Bulk Fulfilment Callback Requests handles Duplicates WHEN Fulfilment Callback differs (i.e. not hash match)
    - [ ] An error Callback will be sent to the PayeeFSP.

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
