### ISSUE TITLE
[SDK-Scheme-Adapter] Add Implement Full CI\CD Pipeline to do automated releases and testing

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2874]
## **Goal**:
`As a` Developer
`I want to` rely on the CICD of the SDK Scheme Adapter Monorepo to perform automated testing and releases
`so that` I can be sure that my changes meet the mojaloop standard while saving time.

**Acceptance Criteria**:
- [x] Verify that Docker Images for each module have been created
- [x] Verify that any Module changes are identified and the CI|CD for each affected Module is run
- [ ] Verify that 'Standard' Mojaloop CI\CD Pipelines are run on each affected Module.
- [ ] Verify that Releases are Published for each affected module when released in master with associated release notes being published.

Support for the following tests and tying them into the CI\CD Pipeline:
- [x] Exiting Integration Tests
- [x] New Bulk Integration Tests
- [x] Unit Tests

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Screenshot showing PR flow:
![Screenshot 2022-08-23 at 16 08 33](https://user-images.githubusercontent.com/11392873/186180002-8a5bccd3-8733-411a-83fe-56ac3666cd6f.png)

Screenshot showing Snapshot (Similiar to standard Release) release flow:
![Screenshot 2022-08-23 at 16 08 49](https://user-images.githubusercontent.com/11392873/186180061-1119e2f8-c7ce-4f03-b049-9414b19aeb1e.png)

**Comment by mdebarros** [comment]
Note: I am unable to fully validate snapshot/release processes until all validation have passed.
