### ISSUE TITLE
Simplify liquidity cover check and fix issue with validation

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2880]
## **Goal**:

As a Hub Operator

I would like to add an additional check on top of the Net-debit-cap check to validate liquidity cover (settlementPosition balance)

so that defaulting DFSP risk can be reduced

Notes:
This is **not** the initial implementation of the issue. This enhances existing implementation by simplifying it and fixing related issues. Follow-up to implementation after DA issue: https://github.com/mojaloop/design-authority-project/issues/90. Review the DA issue for further information (approved by DA).

**Acceptance Criteria**:
- [x] Verify that transactions larger than the difference between the settlement account balance and the position account balance are prevented even when the NDC check allows the transaction.((position + transaction amount < settlement account balance) AND (position + transaction amount < NDC - )) → Transfer Allowed to Continue
- [x] Verify that the correct distinct error Code is returned for both failure scenarios
  - [x] 4001: Insufficient Liquidity - Check against the settlement account balance
  - [x] 4200: Payer limit error - Check against NDC
- [x] Verify that the transactions larger than the difference between the NDC and the position account balances are prevented.transaction amount > NDC - position → Insufficient liquidity
- [x] Verify that the existing GP TTK tests are adjusted to reflect the new liquidity checks (and any funds-in requests needed)
- ~Utilise [ML-Number](https://github.com/mojaloop/ml-number) library to handle all mathematical operations within the Settlement Gross Handler~ <-- https://github.com/mojaloop/project/issues/2927 has been created to address this issue.
  - ~`model.transferSettlement.facade.updateTransferSettlement` function~

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Simplify liquidity check by eliminating separate checks that were based on settlement models - "immediate" or "deferred"
- [x] Fix issue to use correct settlementaccountbalance for the additional check (recently added check on top of the usual NDC check)
- [x] Add TTK requests to add funds-in for setup
- [x] Add TTK tests for regression testing
- [x] Create snapshot-releases to run TTK GP test-suite against
- [x] TTK GP tests pass
- [x] Mojaloop dev release
- [ ] Patch v14 release

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- #2734 

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
PR for consideration:
- https://github.com/mojaloop/central-ledger/pull/917
- https://github.com/mojaloop/central-settlement/pull/384

**Comment by mdebarros** [comment]
Useful queries:

```sql
SELECT * from central_ledger.participantPositionChange WHERE participantPositionId IN ('64', '36') AND createdDate > '2022-08-18 17:58:00' order by createdDate desc; --  where participantCurrencyId IN ('64', '36'); --  AND createdDate > '2022-08-18 09:00:00' order by createdDate desc;
```

```sql
SELECT * from central_ledger.participantPositionChange WHERE  createdDate > '2022-08-18 17:58:00' order by createdDate desc; --  where participantCurrencyId IN ('64', '36'); --  AND createdDate > '2022-08-18 09:00:00' order by createdDate desc;
```

For transferParticipantId Insert
```sql
select TP.transferParticipantId, TP.transferId, TP.participantCurrencyId, TP.transferParticipantRoleTypeId, TP.ledgerEntryTypeId, TP.amount * -1 from transferParticipant as TP
inner join participantCurrency as PC on TP.participantCurrencyId = PC.participantCurrencyId
inner join settlementModel as M on PC.ledgerAccountTypeId = M.ledgerAccountTypeId 
inner join settlementGranularity as G on M.settlementGranularityId = G.settlementGranularityId 
where (TP.transferId = 'f9e605e8-5e53-4b99-995e-166ab38a1853' and (G.name = 'GROSS'))
union 
	select TP.transferParticipantId, TP.transferId, PC1.participantCurrencyId, TP.transferParticipantRoleTypeId, TP.ledgerEntryTypeId, TP.amount * +1 from transferParticipant as TP 
    inner join participantCurrency as PC on TP.participantCurrencyId = PC.participantCurrencyId 
    inner join settlementModel as M on PC.ledgerAccountTypeId = M.ledgerAccountTypeId 
    inner join settlementGranularity as G on M.settlementGranularityId = G.settlementGranularityId 
    inner join participantCurrency as PC1 on PC1.currencyId = PC.currencyId and PC1.participantId = PC.participantId and PC1.ledgerAccountTypeId = M.settlementAccountTypeId 
    where (TP.transferId = 'f9e605e8-5e53-4b99-995e-166ab38a1853' and (G.name = 'GROSS'));
```


For participantPositionChange Insert
```sql
select TP.transferParticipantId, TP.transferId, TP.participantCurrencyId, TP.transferParticipantRoleTypeId, TP.ledgerEntryTypeId, TP.amount * +1 from transferParticipant as TP
inner join participantCurrency as PC on TP.participantCurrencyId = PC.participantCurrencyId
inner join settlementModel as M on PC.ledgerAccountTypeId = M.ledgerAccountTypeId 
inner join settlementGranularity as G on M.settlementGranularityId = G.settlementGranularityId 
where (TP.transferId = 'f9e605e8-5e53-4b99-995e-166ab38a1853' and (G.name = 'GROSS'))
union 
	select TP.transferParticipantId, TP.transferId, PC1.participantCurrencyId, TP.transferParticipantRoleTypeId, TP.ledgerEntryTypeId, TP.amount * -1 from transferParticipant as TP 
    inner join participantCurrency as PC on TP.participantCurrencyId = PC.participantCurrencyId 
    inner join settlementModel as M on PC.ledgerAccountTypeId = M.ledgerAccountTypeId 
    inner join settlementGranularity as G on M.settlementGranularityId = G.settlementGranularityId 
    inner join participantCurrency as PC1 on PC1.currencyId = PC.currencyId and PC1.participantId = PC.participantId and PC1.ledgerAccountTypeId = M.settlementAccountTypeId 
    where (TP.transferId = 'f9e605e8-5e53-4b99-995e-166ab38a1853' and (G.name = 'GROSS'));
```

**Comment by mdebarros** [comment]
Follow-up stories: 
1. Story to review the need for `reservedValue` in the Admin API spec for `GET /participants/{name}/accounts` (and other operations)
2. Enhance existing GP Test-case to include Balance Checks (I.e. Position, Reserved-Position, Settlement, Interchange) if/where required

**Comment by mdebarros** [comment]
Executed multiple tests based on changes made on https://github.com/mojaloop/testing-toolkit-test-cases/releases/tag/v14.0.0.1

Starting at approximately 6:20pm UTC (2022/09/08), ran 22 consecutive tests without failure, and an additional test the following morning @ 9:00am UTC. All test passed successfully without failures.

**Comment by mdebarros** [comment]
## Moja1

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP Tests
Environment: moja1.test.mojaloop.live@v14.0.0
Total assertions: 2634
Passed assertions: 2634
Failed assertions: 0
Total requests: 598
Total test cases: 130
Passed percentage: 100.00%
Started time: Fri, 09 Sep 2022 14:20:47 GMT
Completed time: Fri, 09 Sep 2022 14:24:06 GMT
Runtime duration: 198710 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-09-09T14%3A24%3A06.661Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Bulk Tests
Environment: moja1.test.mojaloop.live@v14.0.0
Total assertions: 183
Passed assertions: 183
Failed assertions: 0
Total requests: 17
Total test cases: 4
Passed percentage: 100.00%
Started time: Fri, 09 Sep 2022 14:25:09 GMT
Completed time: Fri, 09 Sep 2022 14:25:33 GMT
Runtime duration: 24898 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-09-09T14%3A25%3A33.937Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Thirdparty Tests
Environment: moja1.test.mojaloop.live@v14.0.0
Total assertions: 21
Passed assertions: 21
Failed assertions: 0
Total requests: 20
Total test cases: 8
Passed percentage: 100.00%
Started time: Fri, 09 Sep 2022 14:28:23 GMT
Completed time: Fri, 09 Sep 2022 14:28:30 GMT
Runtime duration: 7504 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-09-09T14%3A28%3A30.612Z.html)

**Comment by mdebarros** [comment]
## Default install

```
--------------------FINAL REPORT--------------------
Test Suite:GP Tests
Environment:Development
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 2634                          │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 2634                          │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 0                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 598                           │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 130                           │
├───────────────────┼───────────────────────────────┤
│ Passed percentage │ 100.00%                       │
├───────────────────┼───────────────────────────────┤
│ Started time      │ Fri, 09 Sep 2022 14:37:48 GMT │
├───────────────────┼───────────────────────────────┤
│ Completed time    │ Fri, 09 Sep 2022 14:41:06 GMT │
├───────────────────┼───────────────────────────────┤
│ Runtime duration  │ 198659 ms                     │
└───────────────────┴───────────────────────────────┘
TTK-Assertion-Report-multi-2022-09-09T14:41:06.667Z.html was generated
```

**Comment by mdebarros** [comment]
```
NAME                       	CHART VERSION	APP VERSION                                                                                                                                                                                                                                                                                                                                                                                                                                                               	DESCRIPTION
mojaloop/mojaloop          	14.0.0       	ml-api-adapter: v14.0.0; central-ledger: v15.1.0; account-lookup-service: v13.0.0; quoting-service: v15.0.2; central-settlement: v14.0.0; central-event-processor: v12.0.0; bulk-api-adapter: v13.0.1; email-notifier: v12.0.0; als-oracle-pathfinder: v12.0.0; transaction-requests-service: v14.0.1; simulator: v12.0.0; mojaloop-simulator: v13.0.0; sdk-scheme-adapter: v18.0.2; thirdparty-sdk: v15.1.0; ml-testing-toolkit: v15.0.0; ml-testing-toolkit-ui: v15.0.0;	Mojaloop Helm chart for Kubernetes
mojaloop/mojaloop-bulk     	14.0.0       	bulk-api-adapter: v14.0.0; central-ledger: v15.1.0                                                                                                                                                                                                                                                                                                                                                                                                                        	Mojaloop Bulk Helm chart for Kubernetes
mojaloop/mojaloop-simulator	14.0.0       	sdk-scheme-adapter: v18.0.2; mojaloop-simulator: v13.0.0; thirdparty-sdk: v15.1.0                                                                                                                                                                                                                                                                                                                                                                                         	Helm Chart for the Mojaloop (SDK-based) Simulator
❯ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "reporting-k8s-templates" chart repository
...Successfully got an update from the "bitnami" chart repository
...Successfully got an update from the "mojaloop-charts" chart repository
...Successfully got an update from the "mojaloop" chart repository
Update Complete. ⎈Happy Helming!⎈
❯ helm search repo mojaloop/mojaloop --max-col-width 900
NAME                       	CHART VERSION	APP VERSION                                                                                                                                                                                                                                                                                                                                                                                                                                                                 	DESCRIPTION
mojaloop/mojaloop          	14.0.0       	ml-api-adapter: v14.0.0; central-ledger: v15.1.2.1; account-lookup-service: v13.0.0; quoting-service: v15.0.2; central-settlement: v15.0.0; central-event-processor: v12.0.0; bulk-api-adapter: v13.0.1; email-notifier: v12.0.0; als-oracle-pathfinder: v12.0.0; transaction-requests-service: v14.0.1; simulator: v12.0.0; mojaloop-simulator: v13.0.1; sdk-scheme-adapter: v18.0.2; thirdparty-sdk: v15.1.0; ml-testing-toolkit: v15.0.0; ml-testing-toolkit-ui: v15.0.0;	Mojaloop Helm chart for Kubernetes
mojaloop/mojaloop-bulk     	14.0.0       	bulk-api-adapter: v14.0.0; central-ledger: v15.1.2.1                                                                                                                                                                                                                                                                                                                                                                                                                        	Mojaloop Bulk Helm chart for Kubernetes
mojaloop/mojaloop-simulator	14.0.0       	sdk-scheme-adapter: v18.0.2; mojaloop-simulator: v13.0.1; thirdparty-sdk: v15.1.0                                                                                                                                                                                                                                                                                                                                                                                           	Helm Chart for the Mojaloop (SDK-based) Simulator
```

**Comment by mdebarros** [comment]
Moja1 Deployment: 

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP Tests
Environment: moja1.test.mojaloop.live@v14.0.0
Total assertions: 2634
Passed assertions: 2634
Failed assertions: 0
Total requests: 598
Total test cases: 130
Passed percentage: 100.00%
Started time: Mon, 12 Sep 2022 13:52:40 GMT
Completed time: Mon, 12 Sep 2022 13:55:47 GMT
Runtime duration: 187152 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-09-12T13%3A55%3A47.800Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Bulk Tests
Environment: moja1.test.mojaloop.live@v14.0.0
Total assertions: 183
Passed assertions: 183
Failed assertions: 0
Total requests: 17
Total test cases: 4
Passed percentage: 100.00%
Started time: Mon, 12 Sep 2022 13:56:30 GMT
Completed time: Mon, 12 Sep 2022 13:56:55 GMT
Runtime duration: 24807 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-09-12T13%3A56%3A55.512Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Thirdparty Tests
Environment: moja1.test.mojaloop.live@v14.0.0
Total assertions: 21
Passed assertions: 21
Failed assertions: 0
Total requests: 20
Total test cases: 8
Passed percentage: 100.00%
Started time: Mon, 12 Sep 2022 13:58:02 GMT
Completed time: Mon, 12 Sep 2022 13:58:09 GMT
Runtime duration: 7186 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-09-12T13%3A58%3A09.567Z.html)

**Comment by mdebarros** [comment]
# Moja3 (Default install)

## Deployment

```bash
❯ helm -n moja3 list
NAME 	NAMESPACE	REVISION	UPDATED                              	STATUS  	CHART          	APP VERSION
moja3	moja3    	1       	2022-09-12 16:01:21.614392 +0200 SAST	deployed	mojaloop-14.0.0	ml-api-adapter: v14.0.0; central-ledger: v15.1.2.1; account-lookup-service: v13.0.0; quoting-service: v15.0.2; central-settlement: v15.0.0; central-event-processor: v12.0.0; bulk-api-adapter: v13.0.1; email-notifier: v12.0.0; als-oracle-pathfinder: v12.0.0; transaction-requests-service: v14.0.1; simulator: v12.0.0; mojaloop-simulator: v13.0.1; sdk-scheme-adapter: v18.0.2; thirdparty-sdk: v15.1.0; ml-testing-toolkit: v15.0.0; ml-testing-toolkit-ui: v15.0.0;
```

## Tests

```
--------------------FINAL REPORT--------------------

Test Suite:GP Tests
Environment:Development
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 2634                          │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 2634                          │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 0                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 598                           │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 130                           │
├───────────────────┼───────────────────────────────┤
│ Passed percentage │ 100.00%                       │
├───────────────────┼───────────────────────────────┤
```
