### ISSUE TITLE
[central-ledger][testing-toolkit-cases] Update tests with failure scenario timeout bulkTransfer tests

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#2881]
## **Goal**:
`As a` fsp that wants to use bulk transfer functionality 

`I want to` be shown tests validating the time-out functionality on bulk transfers
  
`so that` I can have confidence when integrating and use the tests for validation and regression testing

**Acceptance Criteria**:
- [ ] TTK Tests for time-out tests are merged into testing toolkit cases repo

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] Add test - `POST /bulkTransfers` prepare request which has timed out. Assert both Payer and Payee receive PUT /bulkTransfers/{ID} callbacks detailing a `COMPLETED` bulkTransfer with individualTransfer errors for all transfers.
- [ ] Add test - `POST /bulkTransfers` prepare request which has timed out and the Payee sends a `PUT /bulkTransfers/{ID}` fulfilment request. Assert both Payer and Payee receive `PUT /bulkTransfers/{ID}` callbacks detailing a `COMPLETED` bulkTransfer with individualTransfer errors for all transfers. Payee FSP receeves some error on late fulfilment.

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
