### ISSUE TITLE
[documentation][central-ledger] Update bulk transfer timeout sequence diagrams with bulk api adapter callback payload examples

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#2882]
## **Goal**:
`As a` fsp that wants to use bulk transfer functionality 

`I want to` be shown tests validating the functionality
  
`so that` I can have confidence when integrating

**Acceptance Criteria**:
- [x] Documentation and sequence diagrams are updated

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Update payload to 3303 error used in implementation in diagram found at https://docs.mojaloop.io/technical/central-bulk-transfers/transfers/3.1.1-transfer-timeout-handler-consume.html
- [x] Update seq diagram with callback examples from the bulk-api-adapter in diagram found at https://docs.mojaloop.io/technical/central-bulk-transfers/transfers/3.1.0-transfer-timeout-overview-for-bulk.html

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
