### ISSUE TITLE
[ttk-tests] Update bulk tests with time-out scenarios

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2884]
## **Goal**:
`As an` adopter of bulk functionality in Mojaloop

`I want to` be able to run tests and assert that advanced bulk time-out scenarios work as expected
  
`so that` I can test for regressions and confidently adopt bulk functionality

**Acceptance Criteria**:
- [ ] TTK Tests for `POST /bulkTransfers` scenario which has timed out in the middle of a large set of individual transfers is validated and added to bulk test collection
- [ ] Assertions to validate that both Payer and Payee FSP receive `PUT /bulkTransfers/{ID}` callbacks detailing a COMPLETED bulkTransfer with individualTransfer errors for a partial set of transfers and successful fulfilments for the rest are present in the GP test for the above test scenario

**Complexity**: Medium-High

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- #2881 (this is a follow-up to previously added bulk timeout tests) and #2853

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
