### ISSUE TITLE
Mojaloop Helm: Externalize backend Dependencies

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2887]
## **Goal**:
`As a` Mojaloop Deployer

`I want to` update Helm charts to externalize backend dependencies
  
`so that` I we can have separation of concerns during a Mojaloop deployment between Mojaloop specific charts and external ones

**Acceptance Criteria**:
- [ ] separate out the major base services from the main mojaloop chart i.e. database, kafka and mongodb will now be separate helm deploys thus freeing the Mojaloop charts of maintaining the version dependencies
- [ ] Confirm that there are no other immediate deprecated APIs that can be addressed with this issue.

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [x] remove the below items from the chart dependencies
  - [x] kafka
  - [x] mongodb
  - [x] database (percona xtradb)
- [x] update all values files to reflect the above changes
- [x] test and document deployment steps 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
going to move this to blocked until we pick this up again..

**Comment by tdaly61** [comment]
Hi @elnyry-sam-k : so I am just in the process of creating a PR for this , can we (can I) move it to in process again please ?
Also  how does #3041 relate to this issue ?

**Comment by elnyry-sam-k** [comment]
Thanks Tom, that would be great!

#3041 is about reviewing this (Miguel to review) and then create follow-up tasks..
