### ISSUE TITLE
Implement the database design for the quote to realise story #214.

### ISSUE THREAD

**Issue by HenkKodde** [mojaloop/project#289]
**Goal**:
This is a dev-ops story for the below goals:
Implement the database design for the quote process as per outcome and specifications in story #214. 

**Tasks**:
- [x] Verify and confirm changes required to the current CDM Migration scripts
- [x] Create the tables as per the Quote database design
- [x] Create the database table relationships by implementing the Foreign Keys as per the Quote database design
- [x] Identify the tables required for the implementation to complement the relevant dynamic data required for the Quote process. These are referenced in the Mojaloop API definition v1.0 document. (AmountType, TransactionSubScenario, BalanceOfPayment, TransactionScenario TransactionInitiator, TransactionInitiatorType)
- [x] Write the scripts to populate the relevant tables required for the quote. (AmountType, TransactionScenario TransactionInitiator, TransactionInitiatorType)
- [x] Reviewed the implementation
- [x] Publish updated design

**Acceptance Criteria**:
- [x] Verify the new tables are create as per the Quote database design.
- [x] Verify the table relationships are as per the Quote database design.
- [x] Verify that the “SEED” tables:
  - [x] are created
  - [x] contain the correct foreign relationships.
  - [x] contain the correct enumerations as per the Mojaloop API Definition v1.0 document.

**Dependencies**:
- [New story #296 created] Design completed and signed off for #214.

**Accountability**
- Owner @HenkKodde 
- Review **Design Authority** (New story #296 created).

**Comment by elnyry** [comment]
Closing this as this Epic/Topic isn't part of the plan for Mojaloop PI-3. Please re-open if necessary.
