### ISSUE TITLE
Deploy dfsp-adapter and supporting services to facilitate end-to-end demo

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#290]
**Goal**:
As a contributor
_I would like to deploy dfsp-adpater and supporting services_
so that an end-to-end transfer can be demonstrated in a way that USSD interface can be used

**Tasks**:
- [x] Deploy dfsp-adpater service
- [x] Verify basic api calls to ensure compatibility

**Acceptance Criteria**:
- [x] dfsp-adapter service is deployed to support an end-to-end transfer
- [x] USSD interface can be used for 

**Dependencies**:
- None currently

**Accountability**
- Owner @ksatya77 
- Review
