### ISSUE TITLE
Align the coloured (dbeaver) database diagram to the latest implementation

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#291]
**Goal**:
As a contributor
I would like to update the database diagram to show the current database state. The purpose of this diagram is to be easily printed or included in a slide as it fits to single landscape oriented page.

**Tasks**:
- [ ] Run `npm run migrate` against clean (newly created) database
  - [ ] Check all tables and connections
  - [ ] Repair any issues and merge to mojaloop repo
- [ ] Create the diagram in DBeaver
  - [ ] Drag & drop all tables
  - [ ] Re-order to match latest screenshot
  - [ ] Make colouring
  - [ ] Make legend
  - [ ] Export to file 

**Acceptance Criteria**:
- [ ] The created diagram matches current state of the implementation

**Dependencies**:
- no dependencies

**Accountability**:
- Owner [ @ggrg ]
- Review [ @mdebarros, @elnyry ]
