### ISSUE TITLE
[SDK Scheme Adapter] Update API swagger definitions for bulk MVP

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2910]
## **Goal**:
`As a` member or the core delivery squad implementing the bulk MVP design
`I want to` ensure that the Open API definition of the backend API of the SDK-Scheme-Adapter (previously called Inbound api) has the latest design definition changes
`so that` use this definition to build on top of.

**Acceptance Criteria**:
- [x] Verify that the  POST \BulkTransaction provides a bulktransactionId that is required
- [x] Verify that the PUT \bulkTransaction callback recieves a bulkTransactionId (Not a bulktransferId)
- [x] Verify that the PUT \bulkTransaction outbound message to accept party provides a required bulkTransactionId (Not a bulktransferId)
- [x] Verify that the PUT \bulkTransaction outbound message to accept quotes provides a required bulkTransactionId (Not a bulktransferId)
- [x] Verify that the API snippets has been update
   - [x] API-Snippets SDKSchemeAdapter.Outbound.V2_0_0.Types.individualTransaction is incorrectly named, and should be individualTransfers. <-- MVP
   - [x] API Snippets is missing FSPIOP Export for PartyiesByTypeAndId (using any as a temporary workaround) <-- MVP
   - [x] Define the lastError scheme/type for individualTransferState entity <-- MVP
   - [x] Issue: Schema for Outbound API for homeTransactionId on Individual Transfers is not a generic string, but rather enforces UUID Regex pattern
- [x] Verify that the Doc sequence diagram is updated
   - [x] [outbound DDD sequence design](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/outbound-sequence.md)
   - [x] [API bulk plant uml design](https://github.com/mojaloop/documentation/blob/PB.SDKBulkSupport/docs/technical/sdk-scheme-adapter/assets/sequence/BulkTransactionsSequenceDiagramOverview.PlantUML) 
      - [x] Move to PlantUML to SDK Adapter repo
      - [x] add validation for manually generated SVG diagram
      - [x] update SVG reference in document repo

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/2910?planning-poker) with ZenHub @mdebarros @kirgene @vijayg10 @sri-miriyala

**Comment by PaulGregoryBaker** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/2910?planning-poker) with ZenHub @elnyry-sam-k
