### ISSUE TITLE
[SDK Scheme Adapter] Update Mojaloop Helm for MVP bulk design 

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2911]
## **Goal**:
`As a` Mojaloop Community member 
`I want to` enable the deployment of the MVP bulk functionality using helm as part of the existing Mojaloop simulators
`so that` deploy this functionality using the helm accepted standard for deployment

**Acceptance Criteria**:
- [ ] Verify that the mojaloop simulators as part of Mojaloop's helm charts have been updated to include the Bulk MVP design
- [ ] Verify that the bulk command and event handlers have health end points that verify that the end points are healthy.
- [ ] Verify that the Bulk MVP functional test are executed (when bulk tests are enabled) by helm tests and passed successfully. 
- [ ] Verify that the bulk TTK test collection includes the MVP functionality tests
- [ ] Verify that the command and event handlers are only deployed if the bulk functionality is enabled
- [ ] Verify that the development release is created when the functionality is merged into the master branch
- [ ] Verify that the development release is deployable and passes the helm test when bulk is enabled.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
This story have been broken up into smaller stories, so no-longer serves a purpose.
