### ISSUE TITLE
MVP Bulk - Add API-Server to Outbound-domain-event-handler for basic health end-point (returns status ok)

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2914]
## **Goal**:
`As a` Tech Ops supporting the deployment of the SDK scheme adapter in kubernetes
`I want to` ensure that the new bulk MVP implementation has that appropriate health endpoints
`so that` kubernetes can make use of theses endpoints to ensure up-time reliability of these micro-services. 

**Acceptance Criteria**:
- [ ] Add API-Server to Outbound-domain-event-handler for basic health end-point (returns status ok)

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

Note: This existing in the command handler, so it can be copied from there.

---

**Tasks**:
- [x] Import api server code to domain handler
- [x] Import tests

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by kleyow** [comment]
TODO: Create a story to fix unit tests stalling in CI.
