### ISSUE TITLE
[SDK Scheme Adapter] Extend Functional tests to include bulk transfer phase of the Bulk MVP

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2917]
## **Goal**:
`As a` Mojaloop Community developer
`I want to` ensure that the functionality for the bulk MVP use case is functionally tested end to end
`so that` I can test this functionality in a deployment

`As a` Tech Ops deploying the SDK Scheme Adapter to support the bulk use case
`I want to` ensure that the functionality is functional after deployment
`so that` I am confident in the services being provided

**Acceptance Criteria**:
- [ ] Verify that functional tests are provided that cover the transfer phase of the bulk design
- [ ] Verify that the functional tests test the consolidated response with the results from all three phases
- [ ] Verify that functional expiration test are included

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
This story was combined with #2803
So can be closed
