### ISSUE TITLE
[SDK Scheme Adapter] Perform Manual Tests to test for internal SDK Scheme Adapter errors

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2918]
## **Goal**:
`As a` hub operator using the bulk use case
`I want to` be confident that any internal SDK errors triggered are appropriately generated and returned
`so that` I can be confident in the live use of this functionality.

**Acceptance Criteria**:
- [ ] Verify

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
