### ISSUE TITLE
[SDK Scheme Adapter] Extend Unit test coverage on MVP bulk

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2919]
## **Goal**:
`As a` core developer team member
`I want to` ensure that the unit test converge for the new MVP bulk is inline with the Mojaloop Standards
`so that` I am able to merge the code into master and ensure that the functionality becomes available in the next Mojaloop release.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Add unit test to private-shared-lib - in order to improve the testing coverage to meet CI checks
   - [ ] output command events
   - [ ] output domain events
   - [ ] domain aggregates and entities.
   - [ ] ~~Infrastructure~~ ??? - should be integration tests
- [ ] Add unit test to domain event handler - in order to improve the testing coverage to meet CI checks
   - [ ] output events handlers (3/7)
   - [ ] 
- [ ] Add unit test to command event handler - in order to improve the testing coverage to meet CI checks
   - [ ] Not many existing unit tests; but good integration tests; need to decide where best effort should go.

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
