### ISSUE TITLE
Extend/Verify that the Mojaloop Simulator as Payer and Payee for Bulk quotes and bulk transfers and bulk transactions

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2924]
## **Goal**:
`As a` Mojaloop Community developer 
`I want to` ensure that the Mojaloop Simulator can be used for testing the bulk MVP functionality (I.e. it is extended so that the bulk transactions test functionality can be called and that the payee bulk quote and bulk transfers call can be mocked)
`so that` the bulk test collections can be used to verify this functionality.

Notes:
- Modify Mojaloop simulator to have bulk support
   - (Simulator API) As Payee verify that the bulkQuotes and bulkTransfers work
   - (Test API - Not FSPIOP) As Payer extend the simulator to include bulkTransactions
   - (Simulator API - Not FSPIOP) PUT callbacks on bulkTransactions x 3 (accept parties, accept quotes, transfer results)
   - (Test API) Test scenario endpoint must support a synchronous request that orchestrates the asynchronous process (POST /bulktransaction, PUT /bulktransaction callback for parties, PUT / bulkTransaction accept party, PUT /bulktransaction callback for quotes, PUT /bulktransaction accept quote, PUT  /bulktransaction callback with final results)

**Acceptance Criteria**:
- [ ] Verify that the the Mojaloop simulator responded when used in a bulk Quotes call as a payee DFSP
- [ ] Verify that the the Mojaloop simulator responded when used in a bulk Transactions call as a payee DFSP
- [ ] Verify that the Mojaloop Simulator facilitates a bulk transactions call as a Payer DFSP initiating a transfer, accepting a party, and accepting a quote and then returns the bulk transaction results.
- [ ] Verify that the Mojaloop simulator's unit test and integration test are extended appropriately

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Making the changes presented in the story doesn't make sense, because most of the functionality that is required to be built, already exists in the TTK.

It makes more sense to expand on the usage of the TTK tool.
(Over the medium term this probably means the the Mojaloop simulator will end up being deprecated. )

It was decided not to continue with this; so the item will be closed.
