### ISSUE TITLE
Align liquidity check comparison for both the Settlement and Transfer Processes

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2927]
## **Goal**:
`As a` Mojaloop

`I want to` make the liquidity check comparison between the position account and the settled funds account as modified by the NDC, instead of between the position account and the NDC as part of the Settlement Process
  
`so that` liquidity checks are aligned  for both the Settlement and Transfer Processes

This is a follow-up story to the following:
- DA Issue: https://github.com/mojaloop/design-authority-project/issues/90. 
- Initial PR for Transfer process: https://github.com/mojaloop/central-ledger/pull/899

**Acceptance Criteria**:
- [ ] Verify liquidity check comparison between the position account and the settled funds account as modified by the NDC, instead of between the position account and the NDC as part of the Settlement Process

**Complexity**: High

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
