### ISSUE TITLE
Improve Mojaloop Simulator logging

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2928]
## **Goal**:
`As a` Hub Operator

`I want to` improve the Mojaloop Simulator's logging
  
`so that` logs can be used for both trouble shooting and auditing purposes

**Acceptance Criteria**:
- [x] Mojaloop-Simulator supports standard log levels (debug, info, etc)
- [x] Mojaloop-Simulator logs are properly persisted to stdout (currently they are not available when downloading log from Kubernetes)
- [x] Mojaloop-Simulator log noise for health-checks when set to "INFO" is surprised, and instead only shown when log level is set to "DEBUG"

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Switch out in built logger for central-services-logger
- [x] Add conditionals for health endpoint
- [x] Update central-services-logger to format new `context` object 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-logger/pull/39
- [x] https://github.com/mojaloop/central-services-logger/pull/40
- [x] https://github.com/mojaloop/mojaloop-simulator/pull/153
- [x] https://github.com/mojaloop/mojaloop-simulator/pull/148

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
