### ISSUE TITLE
Automate the content population of a website by utilising the JSDocs from source

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#294]
**Goal**:
As a developer
_I would like to automatically create a website_ with content derived from JSDocs tasks in source code

**Tasks**:
- [x] Install the JSdoc plugin with the docdash template __[@rmothilal]__
- [x] Test installation and the creation of the Webpage  __[@rmothilal]__
- [x] Add JSdocs block tags to  -src/handlers/... __[@rmothilal]__
- [x] Add JSdocs block tags to  -/src/domain/transfer/commands/index.js __[@vgenev]__
- [x] Add JSdocs block tags to  -/src/domain/transfer/index.js __[@bothadeon]__
- [x] Add JSdocs block tags to  -ilp, transferState __[@nikolayanastasov]__
- [x] Add JSdocs block tags to  -src/domain/transfer/models/transferStateChanges.js __[@vgenev]__
- [x] Add JSdocs block tags to   -transfer-read-model.js__[@vgenev]__
- [x] Add JSdocs block tags to   -src/models/extensions.js__[@vgenev]__
- [x] Add JSdocs block tags to   -src/domain/transfer/projection.js__[@bothadeon]__

**Acceptance Criteria**:

**Dependencies**:

**Accountability**
- Owner @bothadeon 
- Review

**Comment by bothadeon** [comment]
docs/scripts/index.js -
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Home - Documentation</title>

    <script src="scripts/prettify/prettify.js"></script>
    <script src="scripts/prettify/lang-css.js"></script>
    
    <link type="text/css" rel="stylesheet" href="styles/prettify.css">
    <link type="text/css" rel="stylesheet" href="styles/jsdoc.css">
</head>
<body>

<input type="checkbox" id="nav-trigger" class="nav-trigger" />
<label for="nav-trigger" class="navicon-button x">
  <div class="navicon"></div>
</label>

<label for="nav-trigger" class="overlay"></label>

<nav>
    <h2><a href="index.html">Home</a></h2><h3>Modules</h3><ul><li><a href="module-src_domain_transfer.html">src/domain/transfer</a><ul class='methods'><li data-type='method'><a href="module-src_domain_transfer.html#~fulfil">fulfil</a></li><li data-type='method'><a href="module-src_domain_transfer.html#~getAll">getAll</a></li><li data-type='method'><a href="module-src_domain_transfer.html#~getById">getById</a></li><li data-type='method'><a href="module-src_domain_transfer.html#~getFulfillment">getFulfillment</a></li><li data-type='method'><a href="module-src_domain_transfer.html#~prepare">prepare</a></li><li data-type='method'><a href="module-src_domain_transfer.html#~reject">reject</a></li><li data-type='method'><a href="module-src_domain_transfer.html#~rejectExpired">rejectExpired</a></li><li data-type='method'><a href="module-src_domain_transfer.html#~saveExecutedTransfer">saveExecutedTransfer</a></li><li data-type='method'><a href="module-src_domain_transfer.html#~saveSettledTransfers">saveSettledTransfers</a></li><li data-type='method'><a href="module-src_domain_transfer.html#~saveTransferExecuted">saveTransferExecuted</a></li><li data-type='method'><a href="module-src_domain_transfer.html#~saveTransferPrepared">saveTransferPrepared</a></li><li data-type='method'><a href="module-src_domain_transfer.html#~saveTransferRejected">saveTransferRejected</a></li><li data-type='method'><a href="module-src_domain_transfer.html#~settle">settle</a></li><li data-type='method'><a href="module-src_domain_transfer.html#~updateTransferState">updateTransferState</a></li></ul></li><li><a href="module-src_handlers.html">src/handlers</a><ul class='methods'><li data-type='method'><a href="module-src_handlers.html#~RegisterHandlerRoutesHAPI">Register Handler Routes HAPI</a></li><li data-type='method'><a href="module-src_handlers.html#~RegisterAllHandlers">RegisterAllHandlers</a></li><li data-type='method'><a href="module-src_handlers.html#~RegisterAllHandlersRoute">RegisterAllHandlersRoute</a></li><li data-type='method'><a href="module-src_handlers.html#~RegisterAllPositionHandlersRoute">RegisterAllPositionHandlersRoute</a></li><li data-type='method'><a href="module-src_handlers.html#~RegisterAllTransferHandlersRoute">RegisterAllTransferHandlersRoute</a></li><li data-type='method'><a href="module-src_handlers.html#~RegisterFulfilHandlerRoute">RegisterFulfilHandlerRoute</a></li><li data-type='method'><a href="module-src_handlers.html#~RegisterNotificationHandlerRoute">RegisterNotificationHandlerRoute</a></li><li data-type='method'><a href="module-src_handlers.html#~RegisterPrepareHandlerRoute">RegisterPrepareHandlerRoute</a></li><li data-type='method'><a href="module-src_handlers.html#~RegisterRejectHandlerRoute">RegisterRejectHandlerRoute</a></li></ul></li><li><a href="module-src_handlers_lib.html">src/handlers/lib</a><ul class='methods'><li data-type='method'><a href="module-src_handlers_lib.html#~createGeneralTopicConfig">createGeneralTopicConfig</a></li><li data-type='method'><a href="module-src_handlers_lib.html#~createParticipantTopicConfig">createParticipantTopicConfig</a></li><li data-type='method'><a href="module-src_handlers_lib.html#~createTransferMessageProtocol">createTransferMessageProtocol</a></li><li data-type='method'><a href="module-src_handlers_lib.html#~GeneralTopicTemplate">GeneralTopicTemplate</a></li><li data-type='method'><a href="module-src_handlers_lib.html#~GetKafkaConfig">GetKafkaConfig</a></li><li data-type='method'><a href="module-src_handlers_lib.html#~ParticipantTopicTemplate">ParticipantTopicTemplate</a></li><li data-type='method'><a href="module-src_handlers_lib.html#~produceGeneralMessage">produceGeneralMessage</a></li><li data-type='method'><a href="module-src_handlers_lib.html#~produceParticipantMessage">produceParticipantMessage</a></li><li data-type='method'><a href="module-src_handlers_lib.html#~RetrieveAllParticipants">RetrieveAllParticipants</a></li><li data-type='method'><a href="module-src_handlers_lib.html#~TransformGeneralTopicName">TransformGeneralTopicName</a></li><li data-type='method'><a href="module-src_handlers_lib.html#~TransformGeneralTopicName">TransformGeneralTopicName</a></li><li data-type='method'><a href="module-src_handlers_lib.html#~updateMessageProtocolMetadata">updateMessageProtocolMetadata</a></li></ul></li><li><a href="module-src_handlers_lib_kafka.html">src/handlers/lib/kafka</a><ul class='methods'><li data-type='method'><a href="module-src_handlers_lib_kafka.html#~CreateHandler">CreateHandler</a></li><li data-type='method'><a href="module-src_handlers_lib_kafka.html#~Disconnect">Disconnect</a></li><li data-type='method'><a href="module-src_handlers_lib_kafka.html#~GetConsumer">GetConsumer</a></li><li data-type='method'><a href="module-src_handlers_lib_kafka.html#~ProduceMessage">ProduceMessage</a></li></ul></li><li><a href="module-src_handlers_notification.html">src/handlers/notification</a><ul class='methods'><li data-type='method'><a href="module-src_handlers_notification.html#~RegisterAllHandlers">RegisterAllHandlers</a></li><li data-type='method'><a href="module-src_handlers_notification.html#~RegisterNotificationHandler">RegisterNotificationHandler</a></li></ul></li><li><a href="module-src_handlers_positions.html">src/handlers/positions</a><ul class='methods'><li data-type='method'><a href="module-src_handlers_positions.html#~CreatePositionHandler">CreatePositionHandler</a></li><li data-type='method'><a href="module-src_handlers_positions.html#~RegisterAllHandlers">RegisterAllHandlers</a></li><li data-type='method'><a href="module-src_handlers_positions.html#~RegisterPositionsHandlers">RegisterPositionsHandlers</a></li></ul></li><li><a href="module-src_handlers_transfers.html">src/handlers/transfers</a><ul class='methods'><li data-type='method'><a href="module-src_handlers_transfers.html#~CreatePrepareHandler">CreatePrepareHandler</a></li><li data-type='method'><a href="module-src_handlers_transfers.html#~RegisterAllHandlers">RegisterAllHandlers</a></li><li data-type='method'><a href="module-src_handlers_transfers.html#~RegisterFulfillHandler">RegisterFulfillHandler</a></li><li data-type='method'><a href="module-src_handlers_transfers.html#~RegisterPrepareHandlers">RegisterPrepareHandlers</a></li><li data-type='method'><a href="module-src_handlers_transfers.html#~RegisterRejectHandler">RegisterRejectHandler</a></li><li data-type='method'><a href="module-src_handlers_transfers.html#~RegisterTransferHandler">RegisterTransferHandler</a></li><li data-type='method'><a href="module-src_handlers_transfers.html#~TransferPrepareHandler">TransferPrepareHandler</a></li><li data-type='method'><a href="module-src_handlers_transfers.html#~TransferTransferHandler">TransferTransferHandler</a></li><li data-type='method'><a href="module-src_handlers_transfers.html#~validateParticipantByName">validateParticipantByName</a></li></ul></li></ul>
</nav>

<div id="main">

**Comment by bothadeon** [comment]
<img width="1300" alt="screen shot 2018-06-08 at 12 51 08" src="https://user-images.githubusercontent.com/13884584/41154561-c245cc34-6b1a-11e8-9718-7dded275c42f.png">
