### ISSUE TITLE
[sdk-scheme-adapter][private-shared-lib] Update private-shared-lib to use v0.2.0 of @mojaloop/platform-shared-lib

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#2949]
## **Goal**:
`As a` stakeholder in bulk transfers

`I want to` deploy a bulk platform using the latest technologies
  
`so that` the bulk implementation conforms to vNext

**Acceptance Criteria**:
- [x] Ci pipeline passes

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [x] Update @mojaloop/platform-shared-lib-nodejs-kafka-client-lib to latest version.
- [x] Update @mojaloop/platform-shared-lib-messaging-types-lib to latest version.

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/414

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
