### ISSUE TITLE
Addition enhancements for Story #214 

### ISSUE THREAD

**Issue by HenkKodde** [mojaloop/project#295]
**Goal**:
This is a dev-ops story for the below goals:
Additional enhancements database design for the quote process as per outcome and specifications in story #214. 

**Tasks**:
- [x] Remove FK between ilp table and the quoteResponse table.
- [x] Add ilpPacket and ilpCondition Columns to the quoteResponse table.
- [x] Add originalTransactionReferenceId and refundReason to the quote table.
- [x] Remove FK transactionId on quoteExtension table.
- [x] Remove column transactionId on quoteExtension table.
- [x] Add extensionId column to quoteExtension table.
- [x] Add extensionId as FK to extensionId on extension table.
- [x] Create the migration scripts for tables (PartyIdType, PartySubIdType, PartyIdentifierType).
- [x] Create the index scripts for tables (PartyIdType, PartySubIdType, PartyIdentifierType).
- [x] Create the database relationships (Foreign Keys) on the quote table for the above new tables.
- [x] Create the 'SEED' scripts to populate (PartyIdType, PartyIdentifierType) tables required for the quote process.
- [x] Verify the Migration Scripts are creating the tables.
- [x] Verify the Migration SEEDS Scripts are populating the new tables as per the Mojaloop API document v1.0.
- [ ] Publish updated design

**Acceptance Criteria**:
- [x] Remove FK between ilp table and the quoteResponse table.
- [ ] Add ilpPacket and ilpCondition Columns to the quoteResponse table.
- [x] Add originalTransactionReferenceId and refundReason to the quote table.
- [x] Remove FK transactionId on quoteExtension table.
- [x] Remove column transactionId on quoteExtension table.
- [x] Add extensionId column to quoteExtension table.
- [x] Add extensionId as FK to extensionId on extension table.
- [x] The new tables (PartyIdType, PartySubIdType, PartyIdentifierType) are create.
- [x] Verify the table relationships (Foreign Keys) are as per the quote table and link to the new tables (PartyIdType, PartySubIdType, PartyIdentifierType).
- [x] Verify that the “SEEDS” (PartyIdType, PartyIdentifierType):
  - [x] are created
  - [x] contain the correct foreign relationships.
  - [x] contain the correct enumerations as per the Mojaloop API Definition v1.0 document.

**Dependencies**:
- [New story #296 created] Design completed and signed off for #214.

**Accountability**
- Owner @HenkKodde 
- Review **Design Authority** (New story #296 created)

**Comment by elnyry** [comment]
Closing this as this Epic/Topic isn't part of the plan for Mojaloop PI-3. Please re-open if necessary.
