### ISSUE TITLE
Design review for Story #214: To record quote requests and ensure that transfers can be associated with a quote.

### ISSUE THREAD

**Issue by HenkKodde** [mojaloop/project#296]
**Goal:**
This is a design review story for story #214:

As a HUB Operator
I want to be able to record quote requests
so that I can report to the regulator and be able to enforce scheme rules.

As a Participant
I want to ensure that transfers can be associated with a quote
so that the billing model and scheme rules can be applied.

**Tasks:**
- [ ] Verify DDL [@henk, @warren & @ggrg ]
- [ ] Verify the updated design is reviewed by the Design Authority
- [ ] Publish updated design

**Acceptance Criteria:**
- [ ] Verify that the data model includes an auditable record of the quote request as per Mojaloop API POST /quote (insert only with appropriate foreign keys).
- [ ] Verify that the data model includes an auditable record of the quote response as per Mojaloop API POST /quote (insert only with appropriate foreign keys).
- [ ] Verify that the requesting party can be identified.
- [ ] Verify that the responding party can be identified.
- [ ] Verify that the data model can reconcile requests.
- [ ] Verify that the data model can reconcile responses.
- [ ] Verify that the data model supports linking a quote to a transfer.
- [ ] The CDM/Data Model is updated/aligned to reflect the Quote requirements
- [ ] Verify the data model supports the concept of Transaction
- [ ] Verify that the CDM supports the requirements for Quotes

**Dependencies:**
None currently

**Accountability**
Owner @HenkKodde
Review Design Authority

**Comment by elnyry** [comment]
Closing this as this Epic/Topic isn't part of the plan for Mojaloop PI-3. Please re-open if necessary.
