### ISSUE TITLE
Update Mojaloop Simulator - SDK Scheme Adapter Helm Chart to deploy latest SDK API module version

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2962]
## **Goal**:
`As a` User of the Mojaloop 
`I want to` ensure that the latest release of Mojaloop runs the Mojaloop Simulator tests through the latest SDK Scheme Adapter version
`so that` I am confident that exiting functions are still functional with the new version.

Note: This does not include expanding the current test cases, nor does it include extending the Mojaloop Simulator
The SDK Scheme Adapter deployment should not include the bulk components. (I.e. command handler, and event handler)

- Make sure that configs are mounted in the correct directory
- Updating to correct images
- Update to using the correct command I.e. from npm to using Yarn.
- Make sure that only the API module is included

**Acceptance Criteria**:
- [x] Verify that the Mojaloop Simulator deploys the latest SDK Scheme Adapter 
- [x] Verify that the existing golden path tests are still passing

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Snapshot mvp/bulk-sdk branch and run functional tests on dev
- [x] Snapshot mvp/bulk-sdk branch and run functional tests on staging
- [x] PR and merge snapshot into helm mvp/bulk-sdk

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/2962?planning-poker) with Zenhub @elnyry-sam-k
