### ISSUE TITLE
Create an SDK Scheme Adapter helm chart

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2963]
## **Goal**:
`As a` Mojaloop Community developer
`I want to` deploy the SDK Scheme adapter as test FSP's for 
`so that` test the latest functionality in a deployment setting

Note: dependencies should not be included
I.e. preinstall redis and kafka

**Acceptance Criteria**:
- [x] Verify that the SDK Scheme Adapter helm exists in the Mojaloop org
- [x] Verify that the chart aligns the Mojaloop helm standards
- [x] Verify that the chart includes the support for bulk MVP I.e. it includes
   - [x] API Module
   - [x] Command Handler
   - [x] Event Handler
- [x] Verify that after deployment of the helm chart that all the services startup and are declared healthy - happy

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- ~setup helper scripts to setup backend dependencies~ (removed as documentation provides simple commands to deploy backend dependencies)
- [x] create documentation for backend dependency setup
- [x] create template chart that can be used for deployment of api-svc, event-handler, cmd-handler
- [x] ensure template chart adheres to Mojaloop standards
- [x] create parent wrapper chart to deploy a configurable instance of  [@mdebarros ] 
    - [x] api-svc
    - [x] event-handler
    - [x] cmd-handler
    - [x] Blocked by PR https://github.com/mojaloop/sdk-scheme-adapter/pull/395
    - [x] Blocked by Issue https://github.com/mojaloop/project/issues/2914
        - [x] Update default configs to correctly set health end-point port, etc in values.yaml config
- [x] test deployment and ensure that health end-points report success

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- ~https://github.com/mojaloop/helm/pull/501~
- [x] https://github.com/mojaloop/helm/pull/502

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
