### ISSUE TITLE
Add three new simulator DFSPs using SDK + TTK (that are deployed without Mojaloop)

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2964]
## **Goal**:
`As a` user of Mojaloop
`I want to` deploy two three simulator DFSPs that use TTK and the SDK Scheme Adapter
`so that` I can ensure that the latest SDK functionality is tested against the Mojaloop Version 

Note:
This needs to be part of a Mojaloop install  - which will slow down the testing of this
I.e. this is inside of Mojaloop
Use the existing Kafka
Use a different Redis

**Acceptance Criteria**:
- [x] Verify that three static deployed test DFSP are added to the Mojaloop helm that make use of
   - [x] SDK Scheme Adapter helm
   - [x] TTK helm (simulating a core connector)
 - [x] Verify that no backend dependencies are added as a helm dependency (I.e. only configuration)
 - ~Verify that an onboarding script collection is built~ ~ _Done in Follow-up story_
 - [x] Verify that the functional happy path tests are running.
 - [x] Verify that any rules to support the Happy Path are configured

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Follow-up Story/s**:

- https://github.com/mojaloop/project/issues/2976

---

**Tasks**:
- [x] Create placeholders for mojaloop-ttk-simulator-svc wrapper chart (for TTK + SDK) [@mdebarros]
- [x] Create placeholders for mojaloop-ttk-simulators parent chart (this will contain a dependency instance of the mojaloop-ttk-simulator-svc for each Simulator) [@mdebarros]
- [x] Update mojaloop-ttk-simulator-svc to include dependencies and config for TTK + SDK
- [x] Update mojaloop-ttk-simulators parent chart to include alias's and configs for each instance Simulator
- [x] Add documentation (including pre-requisites, and how to validate manually)

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/helm/pull/503

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/2964?planning-poker) with Zenhub @kirgene @kleyow @mdebarros @sri-miriyala @vijayg10
