### ISSUE TITLE
Refactor of the existing bulk MVP functional test in preparation for Helm Tests Pts 1

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2965]
## **Goal**:
`As a` Mojaloop User
`I want to` ensure that the bulk MVP test collection is readily available to be run as deployment helm tests
`so that` be sure that my deployment has all the latest bulk functionality tested.

**Acceptance Criteria**:
- [x] Verify that the bulk MVP functional test are refactored and added to the TTK test collection repo
- [x] Verify that Refactor TTK Rules for match conditions to support multiple simulators
- [x] Verify that any rules to support all the Functional Tests are configured

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Design the rules in such a way there is minimal or no complication in the set up of sims. [ @sri-miriyala ]
- [x] Update the TTK rules [ @sri-miriyala ]
- [x] Update the tests [ @sri-miriyala ]
- [x] Run the tests to make sure all rules work with sims. [ @sri-miriyala ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/2965?planning-poker) with Zenhub @kirgene @kleyow @mdebarros @sri-miriyala @vijayg10
