### ISSUE TITLE
Repurpose the bulk MVP functional tests as TTK optional helm tests (8pts left)

### ISSUE THREAD

**Issue by chris-me-law** [mojaloop/project#2966]
## **Goal**:
`As a` Mojaloop User
`I want to` ensure that the bulk MVP test collection is readily available to be run as deployment helm tests
`so that` be sure that my deployment has all the latest bulk functionality tested.

**Acceptance Criteria**
- [x] Verify that a new optional helm test is available to run on a deployment testing the bulk MVP functionality.
- [x] Verify that when the helm option for bulk SDK simulators is enabled that the helm test for on-boarding and functional tests are executed when the helm test is run
- [x] Verify that when the helm option for bulk SDK simulators is not enabled, that the newly added helm bulk test and on-boarding scripts are not run.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Environment Access
- [x] Create env file for TTK Tests
- [x] Redeploy TTK sims with updated rules file
- [x] Onboard Hub, Sims with TZS currency
- [x] Onboard few MSISDNs that are env vars for the parties error tests
- [x] Make the happy path work with the new env file
- [x] Make changes to the scripts according to the latest changes 
- [x] Fix note field issue in quotes @kleyow 
- [x] Fix note field issue in transfers @kleyow 
- [x] Fix issues withNDC case @kleyow 
- [x] Fix issue with timeout - parties @kleyow 
- [x] Make one Parties error test case to run successfully in switch env
- [x] Make rest of Parties error test cases to run successfully in switch env
- [x] Make one Quotes error test case to run successfully in switch env
- [x] Make rest of Quotes error test cases to run successfully in switch env
- [x] Make one Transfers error test case to run successfully in switch env
- [x]  Make rest of Transfers error test cases to run successfully in switch env
- [x] Run the regression on each fix [Inprogress]
- [x] Run tests with TZS currency for 100% pass
- [x] Redeploy the env with "ml-ttk-test-val-sdk-bulk.tests.enabled" and test "helm test [@vijayg10 ]
- [x] Verify that when the helm option for bulk SDK simulators is not enabled, that the newly added helm bulk test and on-boarding scripts are not run. [@vijayg10 ]
- ~Enable CICD to run bulk TTK tests~ (This is removed as it is going to be a new story)

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/93
- [x] https://github.com/mojaloop/helm/pull/524
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/94
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/95

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
Deployed the mojaloop helm chart in an environment with bulk and sdk-bulk-tests enabled.
`helm test` command produced the following output
```
--------------------FINAL REPORT--------------------

Test Suite:SDK Bulk Tests
Environment:moja4.test.mojaloop.live
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 195                           │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 194                           │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 1                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 33                            │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 18                            │
├───────────────────┼───────────────────────────────┤
│ Passed percentage │ 99.49%                        │
├───────────────────┼───────────────────────────────┤
│ Started time      │ Fri, 11 Nov 2022 18:14:38 GMT │
├───────────────────┼───────────────────────────────┤
│ Completed time    │ Fri, 11 Nov 2022 18:17:19 GMT │
├───────────────────┼───────────────────────────────┤
│ Runtime duration  │ 161214 ms                     │
└───────────────────┴───────────────────────────────┘
TTK-Assertion-Report-multi-2022-11-11T18:17:19.915Z.html was generated
Terminate with exit code 1
npm notice 
npm notice New major version of npm available! 8.5.5 -> 9.1.1

```

**Comment by mdebarros** [comment]
```
Testing Toolkit Report
Test Result: PASSED
Test Suite: SDK Bulk Tests
Environment: moja4.test.mojaloop.live
Total assertions: 195
Passed assertions: 195
Failed assertions: 0
Total requests: 33
Total test cases: 18
Passed percentage: 100.00%
Started time: Mon, 14 Nov 2022 12:57:31 GMT
Completed time: Mon, 14 Nov 2022 12:59:41 GMT
Runtime duration: 129317 ms
```

[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-11-14T12%3A59%3A41.145Z.html)
