### ISSUE TITLE
Correctly handling FSPIOP Errors

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2969]
## **Goal**:
`As a`  an implemented of the bulk MVP SDK scheme adapter functionality
`I want to` ensure that FSPIOP errors are correctly handled
`so that` the correct error message is captured against the individual transfers

**Acceptance Criteria**:
- [x] Verify that the error information is added to the Kafka classes for
   - [x] Discovery
   - [x] Quotes
   - [x] Transfers
- [x] Verify that the FSPIOP error are captured and added to the Kafka classes for
   - [x] Discovery
   - [x] Quotes
   - [x] Transfers
- [x] Verify that the command handler handles the error cases for
   - [x] Discovery
   - [x] Quotes
   - [x] Transfers
- [x] Verify that the regression tests pass

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] ensuring that the unit tests pass
- [x] ensuring that the Integration tests pass
   - [x] all tests are passing (Individually)
   - [x] tests are not running in batch locally
- [x] ensuring that the end to end tests pass

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
