### ISSUE TITLE
Create a Mojaloop release that includes the bulk MVP implementation 

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2973]
## **Goal**:
`As a` user of Mojaloop
`I want to` release a version of Mojaloop that has the bulk SDK scheme adapter /bulkTransactions functionaltiy
`so that` these new features are easy to deploy.

**Acceptance Criteria**:
- [ ] Verify that a new Mojaloop release is created
- [ ] Verify that the bulk SDK test set helm tests run after an deployment of this release.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
completed
