### ISSUE TITLE
Add three new simulator DFSPs using SDK + TTK that are deployed into Mojaloop Pts 1

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2976]
## **Goal**:
`As a` user of Mojaloop
`I want to` deploy two three simulator DFSPs that use TTK and the SDK Scheme Adapter
`so that` I can ensure that the latest SDK functionality is tested against the Mojaloop Version 

Note:
This needs to be part of a Mojaloop install  - which will slow down the testing of this
I.e. this is inside of Mojaloop
Use the existing Kafka
Use a different Redis

**Acceptance Criteria**:
- [x] Verify that three static deployed test DFSP are added to the Mojaloop helm that make use of
   - [x] SDK Scheme Adapter helm
   - [x] TTK helm (simulating a core connector)
 - [x] Verify that no backend dependencies are added as a helm dependency (I.e. only configuration)
 - [x] Verify that an onboarding script collection is built
 - [x] Verify that the DFSPs are onboarded using the onboarding script collection manually
 - [x] Verify that the functional happy path tests are running.
 - [x] Verify that any rules to support the Happy Path are configured
 - [x] Verify that a new optional helm test is available to run on a deployment testing the Happy Path bulk MVP functionality.
 - [x] Verify that when the helm option for bulk SDK simulators is enabled that the helm test for on-boarding and Happy Path functional tests are executed when the helm test is run
 - [x] Verify that when the helm option for bulk SDK simulators is not enabled, that the newly added helm bulk test and on-boarding scripts are not run.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Include the `mojaloop-ttk-simulators` chart as dependency in `mojaloop` chart with necessary configuration in the values file
- [x] Deploy the mojaloop in OSS env and make sure all the new sims are deployed properly
- [x] Prepare the provisioning collection test cases for the new sims
- [x] Execute the happy path manually
- [x] Prepare a bof values file for transfers and positions UI for moja4 env
- [x] Include the provisioning tests and happy path in the test cases repo
  - [x] Include provisioning collection for ttksim1, ttksim2 and ttksim3 with oracle entries for some MSISDNs in each sim
  - [x] Include rules file in the repo and change the reference in chart
  - [x] Include happy path bulktransaction consists of multiple transfers to ttksim2 and ttksim3
- [x] Fix the kafka topic creation issue with init containers
- [x] Add the happy path test to helm test command
- [x] Publish the PR and get it reviewed

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/507

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/2976?planning-poker) with Zenhub @kirgene @kleyow @mdebarros @sri-miriyala @vijayg10
