### ISSUE TITLE
1.3 Prepare scripts for end-to-end Perf testing for transfers

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#298]
**Goal**:
1. As a developer
I would like to _Prepare scripts for end-to-end Perf testing for transfers_
so that when a deployment is ready, performance testing and analysis can be done (happy path)
2. As an FSP
I would like to _have scripts that can test performance of **transfers**_
so that the performance of central services can be assessed

**Tasks**:
- [x] Prepare JMeter scripts for end-to-end Perf testing for transfers (happy path)
  - [x] Setup central services locally (successfully) @elnyry
  - [x] Successfully use postman to make Prepare and Fulfill requests on the deployment @elnyry
  - [x] Update the JMeter scripts with new formats to be directed at ml-api-adapter @elnyry
  - [x] Setup Mock services to help with running an end-to-end transfer using JMeter @elnyry
- [x] Make sure that the scripts that parse the logs for timestamps etc works for transfers
- [x] Mock FSP service for sending fulfilments @elnyry
- [x] Sanity test the scripts (to ensure readiness for future sprints)

**Acceptance Criteria**:
- [x] JMeter scripts for end-to-end Perf testing for transfers are available
- [x] Scripts that search logs for notification timestamps are available
- [x] Mock FSP services are available for simulating fulfils
- [x] For the first version, the testing is done on 2 FSPs (FSP1 & FSP2)

**Dependencies**:
- [x] Availability of the mock FSP payee service for (payee, fulfils)

**Accountability**:
- Owner @elnyry
- QA/Review

**Notes**:
test-scripts repo not following the typical PR process since sometimes updates are made from the AWS VMs used to perform testing.

Commit details:
1. https://github.com/mojaloop/test-scripts/commit/b527afb8285bf28489c7357bfef42b1382292a78
2. https://github.com/mojaloop/test-scripts/commit/3540fb7739856d9e4f3f6f871a75ab012d819416

**Comment by elnyry** [comment]
Added a very basic readme file - https://github.com/mojaloop/test-scripts/tree/develop/pi3-perf-jmeter, will refine this shortly.. just wanted to get in a first draft there.
