### ISSUE TITLE
SDK Bulk - When the payerfsp rejects all parties in the PUT/bulkTransaction/ID, the implementation should advance to the global COMPLETED state.

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#2982]
## **Goal**:
As a payerfsp, using the bulk transaction feature, 

`I want to' get a response, if I reject all parties in the PUT/bulkTrasaction/ID , 
  
`so that ' I can get a global state to "Completed" state and thus the transaction is complete, and build a standardized integration.

Notes: 
In diagram [ref](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/outbound-sequence.md) . At step 44, if all parties are rejected, update Global state to "COMPLETED" and generate event "SDKOutboundBulkTransfersRequestProcessed" ( like in the steps 105 & 106 from the ref seq diagram)
**Acceptance Criteria**:
- [ ] verify that the TC-BQ6 test case passes.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by sri-miriyala** [comment]
This one is covered in #3015 , hence closed.
