### ISSUE TITLE
Payee SDK - backend API bulk quotes and bulk transactions add Last Error to individualTransactionResults

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2986]
## **Goal**:
`As a` Payee DFSP receiving a bulk quotes and bulk transaction message
`I want to` be able to fail by providing an error for an individual transaction
`so that` I can align my backend system with Mojaloop when processing a bulk message

The API that the SDK Scheme Adapter uses to call the core connector is defined [here](https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/test/func/config/ml-testing-toolkit/spec_files/api_definitions/mojaloop_simulator_sim_1.4/api_spec.yaml).

The swagger need to be update to
1. POST \bulkQuotes 200 response needs to have the individualQuoteResults amended
   - [x] The QuoteId need to be required
   - [x] The Last Error should be optional in this class.
2. POST \bulkTransfers 200 response needs to have the individualTransfersResults amended
   - [x] The Last Error should be optional in this class.

**Acceptance Criteria**:
- [x] Verify that the SDK - backend API bulk quotes has the individual Transactions Results that allow a Last Error
- [x] Verify that the SDK - backend API bulk transfers has the individual Transactions Results that allow a Last Error
- [x] Verify that the SDK - backend API bulk quotes has the individual Transactions Results QuoteID as a required field

NOTE: Below are the test cases to be passed upon fixing the issue.
https://github.com/mojaloop/sdk-scheme-adapter/tree/mvp/bulk-sdk/test/func/ttk-testcases
TC-BQ4 and TC-BT4 from the above collections.
**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by sri-miriyala** [comment]
TC-BQ4
<img width="1265" alt="Screen Shot 2022-10-13 at 3 46 00 PM" src="https://user-images.githubusercontent.com/38143240/195695485-fcfcaab3-a687-4bdc-9d9d-18f1e1779c69.png">


TC-BT4
<img width="1251" alt="Screen Shot 2022-10-13 at 3 47 27 PM" src="https://user-images.githubusercontent.com/38143240/195695520-43eb1dd1-850f-48e4-8fee-c15110cf8dc9.png">
