### ISSUE TITLE
Add unit test coverage check to the SDK-Scheme-Adapter Repo

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2989]
## **Goal**:
`As a` member of the Mojaloop Community using the SDK scheme adapter
`I want to` ensure that there is sufficient unit test coverage that is enforce through a CI check
`so that` I can be sure that the repository meets the mojaloop standards

**Acceptance Criteria**:
- [ ] Verify that the unit test coverage scripts are added to the repository
- [ ] Verify that the unit test coverage meets the mojaloop threshold standards.
- [ ] Verify that the test coverage check is added to the circle CI on the respository

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
