### ISSUE TITLE
Merge SDK-Scheme-Adapter MVP\Bulk Branch into master

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#2990]
## **Goal**:
`As a` developer in the mojaloop community using the SDK-scheme-adapter
`I want to` have the latest Bulk support features merged into master
`so that` I can deploy and build on the functionality built

**Note:**
SDK-Scheme-Adapter  - Need to pull updates from master

Dependent on Sri merging the 2965 branch is merged into the bulk-sdk branch on the sdk-scheme-adapter
I.e. https://github.com/mojaloop/sdk-scheme-adapter/tree/mvp/feat/%232965-func-tests
Dependent on 2976

**Acceptance Criteria**:
- [ ] Verify that the SDK-Scheme-Adapter branch I.e. https://github.com/mojaloop/sdk-scheme-adapter/tree/mvp/bulk-sdk branch is merged into master
   - [ ] Document the known issues (This need to be included in the Mojaloop 14.1 release notes)

---

**Tasks**:
- [ ] Update mvp/bulk-sdk with master changes
- [ ] Merge mvp/bulk-sdk into master after all outstanding work is merged.

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
