### ISSUE TITLE
TTK - dynamic rules and request mutation through outbound scripts

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2997]
## **Goal**:
`As an` adopter, QA team member

`I want to` configure TTK rules to respond with dynamic mock responses and outbound request mutation through scripting
  
`so that` I can use minimum number of rules and test cases with the help of scripts

**Acceptance Criteria**:
- [x] Dynamic Rules - ex: a rule can be configured to get a mock response containing an array with number of elements derived based on the request
- [x] Outbound Request Mutation - ex: A test case request can be implemented with an array containing any number of elements derived from script

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Enable request mutation through scripting in outbound test case requests
- [x] Implement a function in inbound script which can set the event body dynamically
- [x] Add documentation for newly added functions

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/219

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
