### ISSUE TITLE
4.1 Design Event Logging Framework placeholder

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#300]
**Goal**:
As a developer
I would like to _design the Event Logging Framework placeholder_
so that events can be logged/persisted at a very basic level and which can be extended later

**Note**:
This is not about the comprehensive "Event Logging Framework" the team intended to do prior to the PI3 meetings.

**Tasks**:
- [x] Kafka **Event** topic related tasks
  - [x] Design Producer and Consumer config (Auto-commit ?)
    - [x] ~Writes the Lime messages?~
  - [x] All published messages are consumed/published

**Acceptance Criteria**:
- [x] Event Logging Framework placeholder is designed
  - [x] ~Lime messages for events are logged/published to a topic~
  - [x] The events are published to a Kafka topic (design)
- [x] Event Logging Sequence diagram is updated to reflect the placeholder version of event logging
- [x] The placeholder sequence diagram is reviewed

**Dependencies**:
- [ ] None currently

**Accountability**:
- Owner @ggrg @mdebarros 
- QA/Review DA

**Comment by elnyry** [comment]
PR: https://github.com/mojaloop/docs/pull/50

**Comment by elnyry** [comment]
The PR has been approved / agreed by 4 DA members, closing this now. If there are any issues or suggestions that come up later, I'll re-open this.
