### ISSUE TITLE
Higher capacity bulk tests

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3000]
## **Goal**:
`As a` Mojaloop Community member planning on implementing the bulk functionality
`I want to` test the bulk enhancements using Mojaloop with higher number of transactions
`so that` I can incorporate bulk in my product design with confidents

**Acceptance Criteria**:
- [ ] Verify that the bulkTransactions adheres to the 1000 transaction limit and completes all transactions without timeouts. (I.e. > 1000 transaction for a single payee DFSP)

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Note:**
The Minimal Mojaloop is not able to process the transactions. I.e. a new higher performance Mojaloop deployment is required.

---

**Tasks**:
- [x] Extend TTK rules to handle dynamic large individual transactions
- [x] Create a TTK Script that test the bulk functionality through POST and PUT /bulkTransactions that can be configured to send > 1200 transactions.
- [ ] 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
I tried a bulk transfer of 700 items between two SDKs directly with the helm of TTK functional tests. I am getting the following error. This issue is at the final response because its too big for a kafka message.

```
payer-sdk-api-svc_1                         | {"ts":"2022-11-04T06:56:26.151Z","level":"debug","msg":"SDKOutboundBulkTransfersRequestProcessedDmEvt:eacc10a4-a41f-4048-9fd4-36f3cd5ab234 - Skipping unknown domain event","ctx":{"hostname":"a037cab2a864","app":"backend-event-handler"}}
payer-sdk-outbound-domain-event-handler_1   | 2022-11-04T06:56:26.157Z (SDK-Scheme-Adapter domain-event-handler v0.0.1) (null) [] info: Sent command event PrepareSDKOutboundBulkResponseCmdEvt
payer-sdk-outbound-command-event-handler_1  | 2022-11-04T06:56:26.157Z (SDK-Scheme-Adapter command-event-handler v0.0.1) (OutboundEventHandler) [] info: OutboundHandler._messageHandler - Processing PrepareSDKOutboundBulkResponseCmdEvt
payer-sdk-outbound-command-event-handler_1  | 2022-11-04T06:56:26.157Z (SDK-Scheme-Adapter command-event-handler v0.0.1) (BulkTransactionAgg.ProcessCommandEvent) [] info: Calling handlePrepareSDKOutboundBulkResponseCmdEvt
payer-sdk-outbound-command-event-handler_1  | 2022-11-04T06:56:26.158Z (SDK-Scheme-Adapter command-event-handler v0.0.1) (BulkTransactionAgg.handlePrepareSDKOutboundBulkResponseCmdEvt) [] info: Created BulkTransactionAggregate [object Object]
payer-sdk-outbound-command-event-handler_1  | 2022-11-04T06:56:26.171Z (SDK-Scheme-Adapter command-event-handler v0.0.1) (null) [] error: Error: Broker: Message size too large meta: "MLKafkaProducer - send - Error getting aks from publisher"
payer-sdk-outbound-command-event-handler_1  | 2022-11-04T06:56:26.171Z (SDK-Scheme-Adapter command-event-handler v0.0.1) (BulkTransactionAgg.handlePrepareSDKOutboundBulkResponseCmdEvt) [] error: Failed to create BulkTransactionAggregate. Broker: Message size too large
```
