### ISSUE TITLE
[SDK-Scheme-Adapter] TransactionId is being used instead of TransferId

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3018]
In the bulk SDK API for the discovery and agreement phase implementations, the transactionId was used instead of the transferId. Although this doesn't break anything, it is confusing and inconsistent so should be corrected.

**Acceptance Criteria**:
- [x] Verify that the API Snippets are update to require the transferId instead of the transactionId
- [x] Verify that the Swagger API for the inbound PUT callback. Snippets are update to require the transferId instead of the transactionId
- [x] Verify that the API module is updated with the transferId to transactionId changes.
- [x] Verify that the command handler module is updated with the transferId to transactionId changes.
- [x] Verify that the domain event handler module is updated with the transferId to transactionId changes.
- [x] Verify that the integration test are updated with the transferId to transactionId changes.
- [x] Verify that the functional test are updated with the transferId to transactionId changes.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] API Snippets
- [x] Update the swagger for the DFSP Backend API + required fields change to TransferId
    - [x] (PUT inbound\bulkTransactions) -- present party info
    - [x] (PUT inbound\bulkTransactions) -- present quote info
- [x] Updating SDK outbound API + required fields change to TransferId
    - [x] (PUT outbound\bulkTransactions) - accept party info
    - [x] (PUT outbound\bulkTransactions) - accept quote info
- [x] Update command& domain handler interface types  to map TransferId & TranactionId correctly
   - [x] For party processing
   - [x] Update integration tests for party processing
   - [x] For quote processing
   - [x] Update integration tests for quote processing
- ~Update Unit tests~ <-- there are no unit tests that cover these use-cases
- [x] Update Integration tests
- [x] Updating functional test cases
   - [x] Update test assertions in local functional tests
   - [x] Update test cases in TTK repo

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/api-snippets/pull/148
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/422
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/96
- [x] https://github.com/mojaloop/helm/pull/525
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/424
- [x] https://github.com/mojaloop/documentation/pull/396

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
```
Testing Toolkit Report
Test Result: PASSED
Test Suite: SDK Bulk Tests
Environment: moja4.test.mojaloop.live
Total assertions: 195
Passed assertions: 195
Failed assertions: 0
Total requests: 33
Total test cases: 18
Passed percentage: 100.00%
Started time: Mon, 14 Nov 2022 12:57:31 GMT
Completed time: Mon, 14 Nov 2022 12:59:41 GMT
Runtime duration: 129317 ms
```

[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-11-14T12%3A59%3A41.145Z.html)
