### ISSUE TITLE
SDK Bulk - CICD functional tests

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3023]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` run functional tests in SDK CICD using the testcases and rules in ttk testcases repository
  
`so that` I can maintain the tests and rules in a single place

**Acceptance Criteria**:
- [x] Test cases should be maintained at a single place for both helm tests and CICD tests
- [x] CICD is setup for SDK repo

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Test the testcases from ttk repo using local functional test harness [@vijayg10 ]
- [x] Add 2 new Transfers related tests. [@sri-miriyala ]
- [x] Find out the gaps and list the tasks
  - [x] Change the MSISDNs align with new env [@vijayg10 ]
  - [x] Need to handle the special MSISDNs like 'party not found', 'party timeout'...etc in hub forward rules [@sri-miriyala] [Inprogress]
  - [x] Add hub rules for the quotes -ve test cases
  - [x] Add hub rules required for the transfers -ve test cases [Inprogress]
  - [x] Run all tests against local env [Inprogress]
  - [x] Docker-compose should fetch the ttk testcases from TTK repo [@vijayg10 ]
  - [x] Docker-compose should fetch the ttk rules from TTK repo - (Need to discuss about this with the team)
  - [x] Configure default environment file for ttksim1 to match with the one in mojaloop helm chart [@vijayg10 ]
  - [x] Migrating rules from TTK testcases repo to SDK repo. [@sri-miriyala]
  - [x] Merge the SDK PR into master 
  - [x] Remove the rules from TTK testcases repo [@sri-miriyala]
  - [x] Change the references in the helm chart [@mdebarros]
 about it so that he can change the references in the helm chart
- [x] Include the functional tests in CICD
  - [x] Update the CICD pipeline to run ttk-sdk-bulk functional tests using helm test command [@vijayg10 ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- https://github.com/mojaloop/sdk-scheme-adapter/pull/425
- https://github.com/mojaloop/testing-toolkit-test-cases/pull/101
- https://github.com/mojaloop/helm/pull/532

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3023?planning-poker) with Zenhub @mdebarros @sri-miriyala @vijayg10 @kleyow @PaulGregoryBaker
