### ISSUE TITLE
4.4 Design Timeout DAO layer and flow

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#303]
**Goal**:
As a developer
I would like to _design Timeout DAO layer and flow_
so that time-outs can be triggered on relevant transfers/transactions

**Tasks**:
- [x] Create node.js program to generate random 1,000,000 transfers with 1,000 randomly distribued to be expired [@ggrg]
- [x] Design Timeout DAO layer [@ggrg]
  - [x] Design how the pending transfers are listed (or accessed) from the DB [@ggrg]
- ~PoC for _Materialized_ views~
- [x] Investigate if MySQL partitions might be used in place of other segmentation [@ggrg]
- [x] Document the output of the story using markdown [@ggrg]

**Acceptance Criteria**:
- [x] An understanding of handling, distribution of pending transfers (Example: With a million transfers in the DB, how long does it take to identify a 1000 distributed)
- [x] ~DAO Objects and Knex layer~ SQL query(ies) that allows accessing pending transfers are available (pending timeout)

**Dependencies**:
- [x] #301 

**Accountability**:
- Owner @rmothilal 
- QA/Review DA

**Comment by ggrg** [comment]
Output document: [des-timeout-1.0.md](https://github.com/mojaloop/docs/blob/develop/CentralServices/designs/des-timeout-1.0.md)
