### ISSUE TITLE
TTK UI Export and import for Backend Rules

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3033]
## **Goal**:
`As a` Mojaloop QA Tester

`I want to` have the ability to export and import Backend Rules (similar to Test-Case Collection)
  
`so that` I can easily save Rules to a desired location and reuse later

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Add import/export file feature to ttk backend
- [ ] Add import/export file feature to ui

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
