### ISSUE TITLE
Core Infra K8s env to latest k8s version

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3035]
## **Goal**:
`As a` Mojaloop QA/Developer

`I want to` deploy Mojaloop releases to the latest Kubernetes version
  
`so that` I can test/dev against a supported K8s version

**Acceptance Criteria**:
- [ ] TBD

**Complexity**:  Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Undeploy all moja envts before the upgrade
- [x] Updated to latest k8s envt using Rancher, k8s plane
- [x] Redeploy moja4 and test
- [x] Test moja1
- [ ] Redeploy moja2 and test

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/helm/pull/533

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3035?planning-poker) with Zenhub @kleyow @mdebarros @sri-miriyala @vijayg10

**Comment by mdebarros** [comment]
```
--------------------FINAL REPORT--------------------

Test Suite:GP Tests
Environment:moja4.test.mojaloop.live@v14.1.0
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 2634                          │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 2634                          │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 0                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 598                           │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 130                           │
├───────────────────┼───────────────────────────────┤
│ Passed percentage │ 100.00%                       │
├───────────────────┼───────────────────────────────┤
│ Started time      │ Tue, 13 Dec 2022 12:15:49 GMT │
├───────────────────┼───────────────────────────────┤
│ Completed time    │ Tue, 13 Dec 2022 12:19:07 GMT │
├───────────────────┼───────────────────────────────┤
│ Runtime duration  │ 197831 ms                     │
└───────────────────┴───────────────────────────────┘
TTK-Assertion-Report-multi-2022-12-13T12:19:07.096Z.html was generated
Terminate with exit code 0
```

```
--------------------FINAL REPORT--------------------

Test Suite:Bulk Tests
Environment:moja4.test.mojaloop.live@v14.1.0
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 337                           │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 337                           │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 0                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 54                            │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 13                            │
├───────────────────┼───────────────────────────────┤
│ Passed percentage │ 100.00%                       │
├───────────────────┼───────────────────────────────┤
│ Started time      │ Tue, 13 Dec 2022 10:24:08 GMT │
├───────────────────┼───────────────────────────────┤
│ Completed time    │ Tue, 13 Dec 2022 10:26:31 GMT │
├───────────────────┼───────────────────────────────┤
│ Runtime duration  │ 143059 ms                     │
└───────────────────┴───────────────────────────────┘
TTK-Assertion-Report-multi-2022-12-13T10:26:31.981Z.html was generated
Terminate with exit code 0
```

```
--------------------FINAL REPORT--------------------

Test Suite:SDK Bulk Provisioning Collection
Environment:moja4.test.mojaloop.live@v14.1.0
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 123                           │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 123                           │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 0                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 119                           │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 13                            │
├───────────────────┼───────────────────────────────┤
│ Passed percentage │ 100.00%                       │
├───────────────────┼───────────────────────────────┤
│ Started time      │ Tue, 13 Dec 2022 10:27:42 GMT │
├───────────────────┼───────────────────────────────┤
│ Completed time    │ Tue, 13 Dec 2022 10:28:20 GMT │
├───────────────────┼───────────────────────────────┤
│ Runtime duration  │ 38207 ms                      │
└───────────────────┴───────────────────────────────┘
TTK-Assertion-Report-multi-2022-12-13T10:28:20.744Z.html was generated
Terminate with exit code 0
```

```
--------------------FINAL REPORT--------------------

Test Suite:Thirdparty Tests
Environment:moja4.test.mojaloop.live@v14.1.0
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 21                            │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 21                            │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 0                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 20                            │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 8                             │
├───────────────────┼───────────────────────────────┤
│ Passed percentage │ 100.00%                       │
├───────────────────┼───────────────────────────────┤
│ Started time      │ Tue, 13 Dec 2022 10:27:26 GMT │
├───────────────────┼───────────────────────────────┤
│ Completed time    │ Tue, 13 Dec 2022 10:27:34 GMT │
├───────────────────┼───────────────────────────────┤
│ Runtime duration  │ 8536 ms                       │
└───────────────────┴───────────────────────────────┘
TTK-Assertion-Report-multi-2022-12-13T10:27:34.914Z.html was generated
Terminate with exit code 0
```

**Comment by mdebarros** [comment]
```
```
[View Report]()

```
```
[View Report]()

```
```
[View Report]()

```
```
[View Report]()

```
```
[View Report]()

**Comment by elnyry-sam-k** [comment]
Environment upgrade is done. Kept this in blocked as there were intermittent stability issues which are not consistently reproducible.. Will raise new issues for any stability issues that occur..
