### ISSUE TITLE
Initial PR review for "Mojaloop Helm: Externalize backend Dependencies"

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#3041]
## **Goal**:
`As a` code owner on mojaloop releases repository (helm)

`I want to` review a PR that "Externalize backend Dependencies" for Mojaloop
  
`so that` this feature can be implemented and published with Mojaloop v15

**Acceptance Criteria**:
- [ ] Review the initial PR for externalizing backend dependencies and creating stories (or next steps) for follow-up (PR: https://github.com/mojaloop/helm/pull/535)

**Complexity**: Low (This story is limited to the initial review; further stories can be created based on the initial review and analysis)

**Uncertainty**: Medium

---

**Tasks**:
- [x] PR review
- [x] Create stories to address any issues/future enhancements as a result of these changes
- [ ] Validate PR - deploy and run tests (in-progress)

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/helm/pull/535

## **Follow-up**:
- N/A

**Dependencies**:
- "Mojaloop Helm: Externalize backend Dependencies" #2887

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3041?planning-poker) with Zenhub @mdebarros @vijayg10 @kleyow @PaulGregoryBaker

**Comment by mdebarros** [comment]
Refer to the following comments on the PR for the stories created: https://github.com/mojaloop/helm/pull/535#pullrequestreview-1252998550
