### ISSUE TITLE
SDK Backend API - Define callbacks in the same file

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3042]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` have information about the callbacks for asynchronous API resources like `/bulkTransaction` in the same swagger file of SDK back-end API
  
`so that` I can refer the callback information from the same swagger specification and also I can configure TTK to get the callback format for some TTK UI features

**Acceptance Criteria**:
- [ ] Callback information is provided in the same SDK Backend API file for asynchronous resources using OAS 3.0 callback feature https://swagger.io/docs/specification/callbacks/

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
