### ISSUE TITLE
TTK - Callback map using openAPI callback feature

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3043]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` specify the callback map for asynchronous APIs in the same openapi file instead of a separate callback map file
  
`so that` I can leverage the openAPI 3.0 callback specification and comply with the standard

**Acceptance Criteria**:
- [ ] TTK can understand the callback mapping specified in the openAPI 3.0 files as per the standard (https://swagger.io/docs/specification/callbacks/)

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
