### ISSUE TITLE
Characterise and validate applicability of current Rules Engine

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3047]
## **Goal**:
`As a` Hub Administrator

`I want to` be able to define and configure rules that meets requirements for Transfer Processing (i.e. within a Processing Handler)
  
`so that` I dynamically change these rules without developer input

**Acceptance Criteria**:
- [ ] ~Rules processing engine must be configurable~
- [ ] ~Rules processing engine must support live configuration management~
- [ ] ~Rules processing engine is imbeddable or integrated into existing Mojaloop Applications/Services~
- [ ] ~Rules processing engine must execute rule scripts/configuration in a secure manner (i.e. rule scripts must not be able to impact the underlying application code)~
- [ ] ~Rules processing engine must provide a mechanism to match rules, and process the matching rules~
- [x] Characterised a baseline Rules script when running in native node vs via the Rules processing engine

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Write a sample program using the rules engine we used for interchange fee calculation
- [x] Characterise the time taken to execute a script with rules engine and without rules engine
- [x] Document the findings

**Done**
- [x] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @mdebarros

**Comment by vijayg10** [comment]
## Objective
The objective is to characterize the rules engine used in `central-settlement` service.
Need to prepare a baseline Rules script when running in native node vs via the Rules processing engine.

## Test program with basic conditional logic
Prepared a sample nodeJS program which runs an express server exposing a sample route `GET /`.
When we pass the query parameter `subScenario` on this route (like `GET /?subScenario=REMITTANCE`), it responds with a text message saying that the subScenario is `REMITTANCE` or `default` based on the query parameter passed with an `if` condition.

This logic is implemented in three ways and calculated the performance overhead for all the approaches.
- Using native code - Used `if` condition directly in the route handler to check the query parameter
- Using nodeJS VM module - The `if` condition logic is passed as an external script to the nodeJS program and executed by the module `vm` in an isolated context and outputs the desired action variables
- Using `Json Rules Engine` - The condition is passed as JSON rules and the rules are executed by handler and catch the events fired and output parameters.

## Tools used
- locust - For generating http load and calculate average response time
- express-status-monitor - For monitoring resource usage like CPU, Memory, NodeJS event loop delay ...etc
- clinic - As a secondary resource monitoring tool for double checking.

## Steps followed for characterization
- Prepared three sample programs for all the three approaches mentioned above (Native code, VM & JRE) using basic express server with an exposed route.
- Run the three programs on three different ports (3000, 3001 & 3002)
- Prepared a python locust script to hit the three endpoints
- Run the locust with concurrency `10`
- Observe the average response time for all the three endpoints
- Monitor the resources using module `express-status-monitor` (i.e. on URL /status)
- To double check the resource usage, also used `clinic` tool for running the node services and get resource usage graphs

## Observations
- After running the three programs and tested with load, the following is the locust output which shows the average response time difference.

![screenshot-locust](https://user-images.githubusercontent.com/33152110/211023601-0ab6212c-9171-4717-a643-626870edd83c.png)

  And the following express server status with resource usage data. In this screen shot, the left one is for native code, middle one is with `VM` and the right one is with `JRE`.

![screenshot-express-status](https://user-images.githubusercontent.com/33152110/211023659-c30e6cbd-6ac4-4a83-b43c-2db8dea1351e.png)

  From the above screenshots, we can observe that the resource usage is considerably very high when running the script with the module `VM`(Middle image).
  The resource usage is much less when using `JRE`.

- We can also observe the following HTML reports from the tool `clinic` and get the resource usage graphs for double checking.
  - Native Code
    ![screenshot-clinic-native-code](https://user-images.githubusercontent.com/33152110/211024086-dcbcfcea-26ff-4286-896f-48cdd15941d1.png)
  - With VM
    ![screenshot-clinic-with-vm](https://user-images.githubusercontent.com/33152110/211024394-f20aaeaa-9ff5-453f-b0ef-54c9939c7a4a.png)
  - With JRE
    ![screenshot-clinic-with-jre](https://user-images.githubusercontent.com/33152110/211024509-16c2e38d-cb37-4d2a-bdf9-9e6546e051f8.png)

## Conclusion
With the above observations, maintaining rules as javascript code and executing it with `VM` modules adds unnecessary performance overhead.
Maintaining rules as JSON and running them using the module `JRE` seems more elegant solution for this problem.

## Deployment Instructions
- Install locust
  ```
  pip3 install locust
  ```
- Start the three applications using the following commands
  ```
  npm run start:clinic-with-vm
  npm run start:clinic-with-jre
  npm run start:clinic-without-vm
  ```
- Open the following pages side by side
  - http://localhost:3000/status
  - http://localhost:3001/status
  - http://localhost:3002/status
- Start the locust server using the following command
  ```
  locust -f locustfile.py --host localhost
  ```
- Generate the load using the web interface using concurrency `10`
  http://localhost:8089
- Observe the metrics in the three webpages
- Exit the three programs and you can get the clinic reports in html format
