### ISSUE TITLE
4.3 Design for handling of duplicate Fulfils

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#305]
**Goal**:
As a contributor
I would like to _design for handling of duplicate Fulfil requests_
so that the idempotent nature of the API is maintained

**Tasks**:
- [x] Ensure event is logged/published (possibly only an implementation task)
- [x] Design Handling of Duplicate transfers requests
  - [x] Update Sequence diagrams
  - [x] Ensure relevant error conditions (error codes) are catered for

**Acceptance Criteria**:
- [x] A design for handling of Duplicate Fulfil requests is available and is reviewed

**Dependencies**:
- None currently

**Accountability**:
- Owner 
- QA/Review

**Comment by elnyry** [comment]
This is covered by the story - https://github.com/mojaloop/project/issues/375
In the PR - https://github.com/mojaloop/docs/pull/38 ,seq-fulfil-2.1.1.plantuml and seq-fulfil-2.1.1.svg consist the steps for Duplicate checks on incoming Fulfil requests (PUT /transfers calls)

I reviewed this and made some suggestions. If the PR is approved, that covers the current story as well.
