### ISSUE TITLE
Define Rules logic & Rules Interface for Default and Remittance use-cases

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3050]
## **Goal**:
`As a` Hub Administrator

`I want to` be able to write Rule scripts based on a set Rules Inteface/API
  
`so that` I can write & configure rule logic to return a set accounts based on the Transfer characteristics which can then be used for liquidity checks.

**Note on rules Engine**
- This rule is to be implemented in the prepare handler and follow the design as outlined in #3061
- This should use the JSON rules engine as an outcome of the Characterisation story #3047
- Define facts to be used as input parameters to the rules engine
  - Transfer object
  - List settlement models
- Define output events for the rules engine

**Acceptance Criteria**:
- [x] Documented Rules Interface/API (Object Schema) (which includes the Transaction Object - ILP Packet) that can be used for writing Rule scripts
- [x] Defined default Rule script to return Default Accounts for as-is Position-Management use-case based on the Transfer's characteristics (or Settlement account type as decided or defined by story #3061
- [x] Defined MAS PoC Rule script to return Remittance Accounts for MAS Position-Management use-case on the Transfer's characteristics

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Observe the previous rules engine tests from quoting service [ @sri-miriyala]
- [x] checking the new rules logic
- [x] comeup with a frame work
- [x] Implement the rules engine for selecting settlement model
- [x] Prepare a default rule
- [x] Prepare a rule for MAS usecase
- [x] Unit tests for rules engine [@sri-miriyala ][Inprogress]
- [x] Add tests for Settlement-model-rules-engine [@sri-miriyala ]
- [x] Add tests for the rules-engine.js [@sri-miriyala ]
- [x] Generate HTML report to show the test coverage for tape scripts
- [x] Fix rules-engine.js tests [@sri-miriyala ]

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/934

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3050?planning-poker) with Zenhub @elnyry-sam-k @vijayg10 @sri-miriyala @kleyow
