### ISSUE TITLE
MAS - SOAK Test

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3052]
## **Goal**:
`As a` Hub Administrator

`I want to` to see that a soak test executed against the MAS PoC changes
  
`so that` I can be confident that all Transfers are correctly assigned to their associated Settlement Model over an extended period of time

Ref: https://en.wikipedia.org/wiki/Soak_testing

**Acceptance Criteria**:
- [ ] Soak Tests to validate Rules / Rules Processing Engine over a 24-hour period of time equivelant load of Transfers
- [ ] Soak Test must include a mix of successful and failed Transfers

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
