### ISSUE TITLE
Add support to SDK-Scheme-Adapter for subScenario mapping on Quote requests

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3053]
## **Goal**:
`As a` Hub Participant

`I want to` send Quotes Requests with a defined subScenario
  
`so that` a can destinguish particiular types of Transfers by this characteristic

**Acceptance Criteria**:
- [x] SDK-Scheme-Adapter Outbound API supports subScenario's for Quote Requests
- [x] SDK-Scheme-Adapter Inbound (FSPIOP) API supports subScenario mapping on handling a Quote Request
- [x] FSP Backend API (Core-Connector) supports subScenario mapping on handling a quote request
- [x] Verify that unit tests and functional tests are extended to test this feature
- [x] Verify that the sub-scenario is available in the ILP packet (This should already be working, but need to be verified)
- [x] Test updated SDK’s with Quoting Service in pass-through-mode

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Update SDK inbound/outbound/backend API
- [x] Update models and request/response mapping
- [x] check the existing test
- [x] Come up with more negative test cases
- [x] Add negative test to the TTK test collection (error code: 400) 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/430
- [x] https://github.com/mojaloop/mojaloop-simulator/pull/159
- [x] https://github.com/mojaloop/api-snippets/pull/152
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/107

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3053?planning-poker) with Zenhub @kleyow @elnyry-sam-k @vijayg10 @mdebarros @sri-miriyala
