### ISSUE TITLE
Prepare-Handler to include the decoded Transaction Object (ILP Packet) in event messages

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3054]
## **Goal**:
`As a` Hub Operator

`I want to` have the Transaction Object (ILP Packet) included in the Transfer events (Kafka message)
  
`so that` that the Transaction Object is available to the Central-Ledger's processing handlers for Rule execution as part of the MAS PoC.

**Acceptance Criteria**:
- [x] Transfer's event messages ilp packets are decoded  in Prepare handler and include the decoded Transaction Object (ILP Packet) in subsequent kafka messages
- [x] Integration Tests are updated to validate that the decoded Transaction Object (ILP Packet) is included on Transfer messages produced in the Prepare processing stage
- [x] Verify that this functionality is made optional through configuration with default being enabled.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Add config option for decoding ilp
- [x] Decode ilppacket and include in kafka messages
- [x] Update tests

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/936

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3054?planning-poker) with Zenhub @elnyry-sam-k @kleyow @mdebarros @sri-miriyala @vijayg10

**Comment by PaulGregoryBaker** [comment]
The design of this story was change to add this to the prepare handler instead of the ML API Adapter.
The ML API Adapter need to respond synchronously with the response message, so adding it there is a problem. The Prepare handlers responsibility is for security and functional validation, so this functionality is better suited there. It is important that it is added to a handler that can be horizontally scaled. The prepare handler can be horizontally scaled.

**Comment by kleyow** [comment]
After reviewing the sequence diagram the ilp packet will no longer be sent in the kafka message to the position handler. The rules engine is being imported to the prepare handler where the transaction object will be used to determine the settlement model. The PR was merged as is in an effort to unblock other stories with the assumption the tests will be refactor to reflect the latest sequence diagram.

**Comment by kleyow** [comment]
Followup validation story https://github.com/mojaloop/project/issues/3080
