### ISSUE TITLE
Supporting MAS PoC

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3055]
## **Goal**:
`As a` Mojaloop Stakeholder / Community Member

`I want to` have the MAS PoC demo'd
  
`so that` that the Reimmitence changes can be shown and proven to work as intended

**Acceptance Criteria**:
- [x] MAS PoC deploy to the TW environment
- [x] Provide upgrade notes so that TW can update another environment 
- [x] MAS PoC run TTK test collection to verify that the deployed functionality works
   - [x] Settlement and DFSP onboarding
   - [x] Sending transfer with sub-secenario info
   - [x] Showing position ledger balances changing

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Disable the test steps in circleCI config of the feature branch
- [x] Release a snapshot version for the central ledger
- [x] Download the helm values from TW dev environment with ‘helm get values moja’ command
- [x] Compare the values file with OSS env values and do the necessary changes
  - [x] Enable two TTK sims and disabled event handlers and kafka, redis configuration in those
  - [x] Enable “enabled_settlement_model_rules_engine” in centralledger-handler-transfer-prepare
  - [x] Specify rules as rules_settlement_model in centralledger-handler-transfer-prepare
  - [x] Expose following ingress endpoints
    - [x] TTK backend and TTK frontend
    - [x] SDK of ttksim1
  - [x] Execute TTK provisioning collection
  - [x] Execute onboarding collection for ttksim1 and ttksim2
  - [x] Check P2P transfer in goldenpath
  - [x] Transfer from ttksim1 with subscenario should pass and the POSITION_REMITTANCE account value should be changed
  - [x] Demo the functionality to the team

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3055?planning-poker) with Zenhub @elnyry-sam-k @kleyow @sri-miriyala @vijayg10

**Comment by PaulGregoryBaker** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3055?planning-poker) with Zenhub @mdebarros

**Comment by vijayg10** [comment]
The following is the modified helm values file to manually update the TW dev sandbox environment
[tw-dev-sandbox-moja-mas.zip](https://github.com/mojaloop/project/files/10491558/tw-dev-sandbox-moja-mas.zip)

**Comment by vijayg10** [comment]
## Executing a transfer of type remittance:

### Through TTK interface:
- Download the file `mas-poc-test.json`
[mas-poc-test.zip](https://github.com/mojaloop/project/files/10499035/mas-poc-test.zip)
- Load the file in the ttk interface at http://ttkfrontend.dev.sanbox.wynepayhubsanbox-pre.com/admin/outbound_request
- Execute a test case
- Observe the position changes in last two requests of the test case

### With CURL requests:
We can use the following curl requests to execute a transfer.
_Note: The curl requests consist of a public endpoint of the SDK scheme adaptor which is exposed already._

```
curl 'http://ttksim1-scheme-adapter-api-svc.dev.sanbox.wynepayhubsanbox-pre.com/outbound/parties/MSISDN/4561000001'
curl 'http://ttksim1-scheme-adapter-api-svc.dev.sanbox.wynepayhubsanbox-pre.com/outbound/transfers'
  -X POST
  -H 'content-type: application/json'
    --data-binary '{"from":{"displayName":"ReceiverFirst","idType":"MSISDN","idValue":"16135551212"},"to":{"idType":"MSISDN","idValue":"4561000001"},"amountType":"SEND","currency":"MMK","amount":"10","transactionType":"TRANSFER","subScenario":"REMITTANCE","initiatorType":"CONSUMER","note":"test payment","homeTransactionId":"123ABC"}'
curl 'http://ttksim1-scheme-adapter-api-svc.dev.sanbox.wynepayhubsanbox-pre.com/outbound/transfers/2736bd0a-1295-403d-917e-5581fe0d07b1'
  -X PUT
  -H 'content-type: application/json'
  --data-binary '{"acceptParty":true}'
curl 'http://ttksim1-scheme-adapter-api-svc.dev.sanbox.wynepayhubsanbox-pre.com/outbound/transfers/2736bd0a-1295-403d-917e-5581fe0d07b1'
  -X PUT
  -H 'content-type: application/json'
  --data-binary '{"acceptQuote":true}'
```
