### ISSUE TITLE
TTK helm tests - Investigate the possibilities to make the test reports accessible with a self-hosted solution

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3056]
## **Goal**:
`As a` Hub Operator (/Tech Ops)

`I want to` access the mojaloop helm test reports in html with a self-hosted solution
  
`so that` I can use them for debugging the failures

This story is about investigating the framework to achieve this goal

**Acceptance Criteria**:
- [x] Investigation done for the possibilities to make the test reports accessible with a self-hosted solution
- [x] Different possible solutions are documented based on the investigation and the followup implementation story is available with agreed solution

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Notes**:
The following are the possible implementations
- Store the report files in a shared volume and add a new nginx service to serve the report files
  - It seems there is no proper way to share a volume between different pods
  - We can do that using NFS, but to me its like a patchy solution and not straight forward.
- Add a S3 Mock service in the cluster and point TTK CLI to store the reports on that service using the existing s3 feature in TTK CLI
  - It seems this method is easiest. TTK CLI should be altered to make the AWS endpoint configurable and there should be a selfhosted s3 service which can also serve the reports using a web UI
  - And also this approach seems like a patch and not straight forward. Because we are adding a mock s3 service because just we have s3 capability in the TTK CLI
- Add functionality in TTK CLI to send the report using some network protocol like HTTP POST / FTP and add a new http server service to serve the files
  - This can be done just by modifying the TTK CLI helm chart. Adding a new parameter in values like postScript and we can supply the curl command to upload the report file to configured server. The file server can be a new custom service / an artifactory like jfrog which can store and service the report files.
  - The advantage of this approach is the mojaloop implementers can configure their own artifactory kind of service to store the reports.
- Store the reports in TTK backend itself by leveraging some code already implemented for storing the reports in a mongodb server for HOSTED mode. And implement a page in UI to list the reports.
  - The advantages of this approach is we can use the existing TTK backend service to serve the reports and we can leverage the existing code.
  - To me. this approach is straight forward even though some refactoring to be done on TTK backend to enable this.

**Tasks**:
- [x] Investigate and document different possibilities
- [x] Discuss with the team and agree on something
- [x] Create a followup story with all required details

**Done**
- [x] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3056?planning-poker) with Zenhub @vijayg10

**Comment by vijayg10** [comment]
The agreed approach and the implementation details are added to the story https://github.com/mojaloop/project/issues/3058
