### ISSUE TITLE
Helm - TTK-Test Reports should be optional made available with a self-hosting solution

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3058]
## **Goal**:
`As a` Hub Operator

`I want to` have the TTK Test Reports produced by executing the `helm test` on a Mojaloop deployment accessable with a self-hosted solution (i.e. not requiring AWS)
  
`so that` reports can be used for QA and debugging

**Acceptance Criteria**:
- [x] Helm Test reports are optionally published to a self-hosted solution that is available when Helm Tests are enabled on a Mojaloop Deployment
- [ ] ...

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Notes**:
After investigating different possiblities as part of this [story](https://github.com/mojaloop/project/issues/3056), we agreed on the following implementation approach
- Store the reports in TTK backend itself for every testcase execution. And implement a page in UI to list the reports.
  - This can be done by leveraging some code already implemented for storing the reports in a mongodb server for HOSTED mode.
  - The advantages of this approach is we can use the existing TTK backend service to serve the reports and we can leverage the existing code.
  - This approach is straight forward even though some refactoring to be done on TTK backend to enable this.
  - The reports should be stored as JSON objects in a `mongodb server` or `file system` by the TTK backend for every test run and there should be an endpoint to serve the reports. The storage adaptor selection can be chosen based on a new system config param or existing mongo db config.
  - A TTK UI page should be created to show the report history with various download options like `JSON report`, `HTML report` or `Printer friendly HTML report`.
  - The console log of TTK CLI should print the URL to the generated report. This URL can be constructed from backend endpoint supplied to TTK CLI. But if the backend URL is based on the k8s service name, we may need to add and additional argument like `REPORT_FQDN` / `REPORT_BASE_URL` to construct the URL and print it in the console log at the end of test execution.
  
**Tasks**:
- [x] Refactor the test case execution to store the JSON report in database / file system based on the system configuration. This is already being done when HOSTED_MODE is enabled, but with DFSPID wise. We need a bit of refactoring there.
- [x] Expose an API endpoint to serve the reports from database / file system based on the configuration
  - [x] To download the report
- [x] Add configuration to the mojaloop helm chart and get the reports stored in mongodb
- [x] Modify TTK CLI to output the report URL

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit-client-lib/pull/2
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/224
- [x] https://github.com/mojaloop/helm/pull/534
- [x] https://github.com/mojaloop/deploy-config/pull/45

## **Follow-up**:
- https://github.com/mojaloop/project/issues/3060

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Duplicate of https://github.com/mojaloop/project/issues/3056

**Comment by elnyry-sam-k** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3058?planning-poker) with Zenhub @vijayg10 @mdebarros @kleyow @sri-miriyala
