### ISSUE TITLE
2.7 - 1 Implement business logic for calculation of positions

### ISSUE THREAD

**Issue by nikolayanastasov** [mojaloop/project#306]
**Goal**:
As a developer
I would like to _Implement the business logic for calculation of position for prepares, rejections, timeouts messages_ 
so that Positions can be managed

**Tasks**:
- [x] Implement business logic for the calculation of positions in **PositionHandler** for
  - [x] prepares [@vgenev, @rmothilal]
  - ~[ ] rejections~ this is covered by story #308  
  - [x] timeouts [@vgenev]
  - [x] refactor the transaction into the facade [@vgenev]
- [x] merge with #308 code [@vgenev] https://github.com/vgenev/central-ledger/tree/feature/%23306-%23308-merged
- ~update unit tests~
- [x] Implement Integration test for Transfer Prepare use-case resulting in a "reject" state due to the NET-DEBIT-CAP being exceeded [@rmothilal]
- [x] Implement Integration test for Transfer Prepares to check position changes [@ggrg]

**Acceptance Criteria**:
- [x] Business logic for calculation of positions is implemented for
  - [x] prepares
  - ~[ ] rejections~ this is covered by story #308  
  - [x] timeouts
 - ~unit tests pass~
- [x] Integration test for Transfer Prepare use-case resulting in a "reject" state due to the NET-DEBIT-CAP being exceeded
- [x] Integration test for Transfer Prepare to check position changes

**Dependencies**:
- [x] Reference Sequence diagrams
- [x] #344 
- [x] @rmothilal 
- [x] Follow-up item #384 

**Accountability**:
- Owner @rmothilal
- QA/Review

**Comment by elnyry** [comment]
PR - https://github.com/mojaloop/central-ledger/pull/106

Rest of the tasks tracked in #384
