### ISSUE TITLE
TTK UI - Stored test reports should be available in TTK UI

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3060]
## **Goal**:
`As a` Hub Operator

`I want to` have the TTK Test Reports produced by executing the `helm test` on a Mojaloop deployment accessible with a self-hosted solution (i.e. not requiring AWS)
  
`so that` reports can be used for QA and debugging

**Acceptance Criteria**:
- [ ] An API endpoint to serve the reports from database / file system based on the configuration is made available
- [ ] Pagination options on the reports to include sorting based on
  - [ ] Test execution time (sorted order) with most recent result on top
  - [ ] Failed reports

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Expose an API endpoint to serve the reports from database / file system based on the configuration
  - [x] List reports including these possible details
    - [x] File name, size, date...etc
    - [x] total/passed/failed assertion count if possible
    - [x] The list should be paginated using query param / path param
  - [x] Download reports in various formats (JSON, HTML, Printer friendly HTML)
- [x] Implement a new page in TTK UI to show the report history with pagination and date selection(if possible). (There should be a page for this already implemented for HOSTED_MODE, we can use that as reference)
- [x] Pagination sorting based on Start time
- [x] Filter based on the following fields
  - [x] Start time
  - [x] Failed reports

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/226
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/155

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3060?planning-poker) with Zenhub @mdebarros @vijayg10 @kleyow @PaulGregoryBaker @sri-miriyala
