### ISSUE TITLE
Reset positions on BULK TTK GP so that they will not fail due to insufficient liquidity

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#3068]
## **Goal**:
`As a` Mojaloop QA Tester

`I want to` BULK TTK GP Test Collections to reset available liquidity after each run
  
`so that` tests do not fail with `insufficient liquidity after repeated runs

**Acceptance Criteria**:

- [x] Repeated BULK TTK GP Tests should not fail with `Insufficient Liquidity` as the Test-Cases should pre/post load `Funds-In` as required to ensure that Liquidity is always available when executing TTK GP Tests.
- [x] OSS Moja1 environment does not fail due to `Insufficient Liquidity` after repeated runs from the daily testing cronjob.

Note: As the settlements process reset the positions of the DFSPs in the settlement window that allows to transnfer successfully, Settlements are run before and after the tests. 

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Observe the current tests [ @sri-miriyala ]
- [x] come up with a solution on NDC or settlement
- [x] Test settlement on bulk transfer window
- [x] Add settlement model manually
- [x] Add scripts as needed
- [x] Call settlements before Bulk tests [updating master.json]
- [x] Call settlements after bulk tests [updating master.json]
- [x] Call settlements before TTK tests start 
- [x] Call settlements after TTK tests end 
- [x] work on the failures
~- [ ] add validate positions [Refactoring is needed and hence not in scope of this story]~
- [x] Run the tests

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Note**:
- Add to Deferred settlements test (similar to CGS)

**Comment by elnyry-sam-k** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3068?planning-poker) with Zenhub @sri-miriyala @mdebarros @vijayg10 @kleyow @PaulGregoryBaker
