### ISSUE TITLE
Extend the reporting events process to include /bulkTransfer and /bulkquotes messages

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3070]
## **Goal**:
`As a` hub operator 
`I want to` be able to trace a bulk quotes and bulk transactions message through the reporting API
`so that` I can investigate unexpected problems associated with Mojaloop bulk messaging calls without needing to look at each microservices log files.

**Note:** the association of a kafka audit message to a transfer or quotes type can be configured by updating the quote-constants.js and the transfer-constants.js files in the src/constants folder.

**Acceptance Criteria**:
- [ ] Verify that the event processor identifies /bulkTransfer audit kafka messages as a transfer message 
- [ ] Verify that the event processor identifies /bulkQuotes audit kafka messages as a quotes message 
- [ ] Verify that the event processor correctly associates each bulk message with the multiple composed transferId enabling the transfer queries to identify the messages
- [ ] Verify that the MongoDB queries for quotes for a particular transfer show the bulkQuotes messages
- [ ] Verify that the MongoDB queries for transfers for a particular transfer show the bulkTransfer messages
- [ ] Verify that the trace a transaction UI shows the associated bulk messaging calls

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
