### ISSUE TITLE
ML-API-Adapter characterisation of the rules processing

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3072]
## **Goal**:
`As a` Hub Operator
`I want to` have the Transaction Object (ILP Packet) included in the Transfer events (Kafka message)
`so that` that the Transaction Object is available to the Central-Ledger's processing handlers for Rule execution as part of the MAS PoC.

**Acceptance Criteria**:
- [ ] Characterise the ML-API-Adapter before and after in isolation (only with POST /Transfers, and with messages being persisted to Kafka) to determine the impact to performance and/or scalability.

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
