### ISSUE TITLE
Helm CI Release process re-factored to be independent of code

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3073]
## **Goal**:
`As a` Mojaloop Maintainer

`I want to` seperate out the Helm repo branch from the code-base
  
`so that` I can publish any version of a Helm release

NOTE: Current limitation is that one can only release the current latest version or a newer version. One can manually publish older versions if required, but the CI process does not support it since it includes the code-base (and merges changes into that code-base).

**Acceptance Criteria**:
- [x] Helm CI Release should ONLY commit/publish the release artefacts generated by a build

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Clean up gh-pages branch
- [ ] Remove non repo files and folders from being commited into gh-pages 

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3073?planning-poker) with Zenhub @PaulGregoryBaker @kleyow @vijayg10 @mdebarros @sri-miriyala
