### ISSUE TITLE
[ml-testing-toolkit] Add sdk-standard-component ilp functions to TTK scripting engine.

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#3079]
## **Goal**:
`As a` test developer

`I want to` have access to useful javascript fuctions in the scripting engine of the TTK. Such as ilp packet decoding from sdk-standard-components
  
`so that` improve test coverage 

**Acceptance Criteria**:
- [ ] Add `ilp.getTransactionObject` function to scripting engine
- [ ] Add `ilp.validateIlpAgainstTransferRequest` function to scripting engine

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
