### ISSUE TITLE
2.8 Implement business logic for calculation of positions for Fulfils

### ISSUE THREAD

**Issue by nikolayanastasov** [mojaloop/project#308]
**Goal**:
As a Switch
I would like to _Implement business logic for calculation of positions for Fulfils_
so that the capacity of FSPs to make transactions is maximized while not exceeding the Net Debit Cap and minimizing cost to the Switch by reducing the number of bank transactions

**Tasks**:
- [ ] Implement business logic for calculation of positions for Fulfils in **PositionHandler** [@ggrg]
  - [x] fulfil success [@ggrg]
  - [x] testProducer - reject [@ggrg]
  - [x] TransferHandler - reject [@ggrg]
  - [x] PositionHandler - reject [@ggrg]
  - ~src/domain/transfer/projection.js to transaction~ #376
- ~Unit Tests~ #376

**Acceptance Criteria**:
- ~Business logic for calculation of positions for Fulfils is implemented~ #376

**Dependencies**:
- [x] #344 

**Note**:
List of Use Cases
- successful Fulfils (Payee position is reduced)
- rejected Fulfils (Payer Position is reduced)

**Accountability**:
- Owner @rmothilal
- QA/Review
