### ISSUE TITLE
[Helm] search-replace values with $release prefix with a TPL rendering helper function

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3081]
## **Goal**:
`As a` Helm Maintainer

`I want to` replace the existing search-replace values starting with `$release_` (e.g. `$release_name-<service_name>`) prefix with a TPL rendering helper function
  
`so that` the Helm charts align to best practices providing the most flexibility when configuring the hosts

**Acceptance Criteria**:
- [ ] Existing search-replace values starting with `$release_` prefix to be replaced with TPL Helper functions
- [ ] ...

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
