### ISSUE TITLE
[Helm] Utilise externalised secrets for password management

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3082]
## **Goal**:
`As a` Hub Maintainer

`I want to` utilise externalised secrets for password management
  
`so that` the Mojaloop's Helm charts follow best practices with regard to security

**Acceptance Criteria**:
- [x] Existing charts to use externalised secrets for passwords after the refactor
- [x] Means to automatically create the externalised secrets is provided
- [x] Documentation on how to configure externalised secrets is provided
- [x] Externalised secrets configuration must provide support for configuring the key-names to provide flexibility when utilising secrets generated automatically be backend dependencies
- [x] Ensure init-containers do not have any sensitive data (plain text secrets, etc)
- [x] Support for both external secrets (preferred) with setting passwords as optional
- [x] External secrets to always override any passwords set in helm values

**Notes**
- Externalised User management has been identified as unecessary at this time, and has been differed until the requirement arises, and a new story will be created as such.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Decision required on how best to provide example secrets config either through the example-backend or a seperate helm deployment.
- [x] Develop "template" changes that will be rolled-out/copy-pasted through-out most of the Helm charts
- [x] Validate approach with DA (https://github.com/mojaloop/design-authority-project/issues/98)
- [x] Roll-out changes
     - [x] account-lookup-service ~(x2)~
     - [x] als-oracle-pathfinder
     - [x] bulk-api-adapter ~(x2)~ [dependant on https://github.com/mojaloop/project/issues/3131]
     - [x] bulk-centralledger ~(x4)~ [dependant on https://github.com/mojaloop/project/issues/3129]
     - ~centraleventprocessor~ [**Partially** done - dependant on https://github.com/mojaloop/project/issues/3134 - removed out of scope]
     - [x] centralledger ~(x7)~ [dependant on https://github.com/mojaloop/project/issues/3129]
     - [x] centralsettlements ~(x4)~
     - ~emailnotifier~ [Partially done - dependant on https://github.com/mojaloop/project/issues/3135 - removed out of scope]
     - [x] eventstreamprocessor
     - [x] example-mojaloop-backend
     - [x] ml-api-adapter ~(x2)~
     - [x] ml-ttesting-toolkit [dependant on https://github.com/mojaloop/project/issues/3130]
     - [x] ml-ttesting-toolkit-ui [dependant on https://github.com/mojaloop/project/issues/3130]
     - [x] mojaloop
     - [x] mojaloop-bulk [dependant on https://github.com/mojaloop/project/issues/3131, https://github.com/mojaloop/project/issues/3129]
     - [x] mojaloop-simulator
     - [x] moualoop-ttk-simulators ~(x3)~  [dependant on https://github.com/mojaloop/project/issues/3130]
     - [x] quoting-service
     - ~sdk-scheme-adapter~ [Nothing was needed to be done here]
     - [x] simulator
     - [x] thirdparty ~(x3)~
         - [x] auth-svc [dependant on https://github.com/mojaloop/project/issues/3139]
         - [x] als-consent-svc
         - [x] thirdparty-sdk-adapter
     - [x] transaction-request-service
- [x] Utilise example-backend sescret deployment to test default Mojaloop Install

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/helm/pull/538

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Need to brainstorm/discuss the reconciliation between the Mojaloop helm repo and charts repo - to address gaps and have a single repo..

**Comment by elnyry-sam-k** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3082?planning-poker) with Zenhub @mdebarros @dfry @kleyow @PaulGregoryBaker

**Comment by mdebarros** [comment]
Added bocking dependency [#2887](https://github.com/mojaloop/project/issues/2887)
