### ISSUE TITLE
[Helm] Provide External Dependency support for Thirdparty Helm Charts

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3083]
## **Goal**:
`As a` Hub Maintainer

`I want to` have external dependencies added to the example backend for Thirdparty Helm Charts
  
`so that` Thirdparty Helm Chart dependencies are maintained/handled consistently and as part of a single example backend deployment that is utilised by the main Mojaloop Helm Chart

**Acceptance Criteria**:
- [ ] Thirdparty Helm Chart external dependencies are added to the Example Backend Dependency Helm charts for MySQL and Redis
- [ ] Thirdparty Helm Charts are re-worked for consistency (as per other charts) to configure their respective external backend dependendencies
- [ ] Update existing documentation to reflect these changes

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3083?planning-poker) with Zenhub @mdebarros @kleyow @vijayg10 @PaulGregoryBaker
