### ISSUE TITLE
Add-extend test cases to include testing transfers with liquidity check only (I.e. without a NDC limit check)

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3084]
## **Goal**:
`As a` DFSP using Mojaloop
`I want to` send and receive transfers without having a NDC limit defined on my position account
`so that` NDC's limits are only added when they are needed against my accounts

**Note:**
This story can either create a new DFSP to test with without an NDC, or update existing test cases to ensure that this scenario is covered in the testing.

**Acceptance Criteria**:
- [ ] Verify that a DFSP existing as part of the GP TTK test collection that does not have an NDC limits for the position account
- [ ] Verify that the POST /participants/{name}/initialPositionAndLimits endpoint is
   - [ ] TTK onboarding and test collections are not calling this endpoint, and test assertions accomodate this change (i.e. initialPosition = 0).
   - [ ] API spec updated to deprecate/remove the API function
   - [ ] Documentation API spec is updated to updated to deprecate/remove the API function   
- [ ] Verify that a test in the GP TTK test collection is added using this DFSP as a Payer (Funds In will need to be called.)
- [ ] Verify that a test in the GP TTK test collection is added using this DFSP as a Payee

**Note:**
Although this story is labelled as mas, it is not a requirement for the MAS POC, but should be completed in order to merge in the mas POC changes.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
