### ISSUE TITLE
Update API Specification to include the LedgerAccountTypes endpoint

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3088]
## **Goal**:
`As a` Mojaloop Community member
`I want to` use the API specification when adding Ledger account types
`so that` understand, and design with the Mojaloop API

**Note:**
The Admin API sepecification does not currently include this API defined in the code [here:](https://github.com/mojaloop/central-ledger/tree/master/src/api/ledgerAccountTypes)

**Acceptance Criteria**:
- [ ] Verify that the Ledger account type is added to the specifications repo
- [ ] Verify that the Ledger account type is added Mojaloop specifications documentation

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
