### ISSUE TITLE
Update Payment Manager helm to use the mojaloop SDK Scheme Adapter helm chart

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3089]
## **Goal**:
`As a` Participant connecting to Mojaloop using Payment Manager
`I want to` deploy the latest SDK-Scheme-Adapter features
`so that` I can use the latest functionality

**Note:** 
Bulk mode does not need to be support in this story.

**Acceptance Criteria**:
- [ ] Verify that the Payment Manager Helm is using the Mojaloop Sdk-Scheme-Adapter helm I.e. [here](https://github.com/mojaloop/helm/tree/master/sdk-scheme-adapter).
- [ ] Verify that the Payment Manager deployment tests pass after deployment of this helm.
- [ ] Verify that the latest SDK-Scheme-Adapter is deployed
- [ ] Verify that the IaC has been updated to use this helm chart so that this functionality can be tested

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:

- [x] Refactor the pm4ml helm chart by using new sdk chart from mojaloop repository
- [x] Refactor the IaC to reflect the changes in pm4ml values file
- [x] Try to upgarde pm4ml helm chart in an IaC based envinronment
- [x] Make sure the end-2-end transfer passes with two pm4mls (Platform Tests) in IaC before and after upgrade
- [x] Release new major versions for pm4ml helm chart and IaC
- [x] Test the deployment again with new versions
- [ ] Update the release notes as a breaking change in pm4ml  IaC and helm chart
- [x] Access new sandbox env
- [x] Run pm4ml GP collection before making the changes to the pm4ml helm in the sandbox env
- [x] Run pm4ml GP tests after the update to pm4ml helm in the sandbox env

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/pm4ml/mojaloop-payment-manager-helm/pull/129
- [x] https://github.com/pm4ml/pm4ml-k3s-iac/pull/32

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3089?planning-poker) with Zenhub @mdebarros
