### ISSUE TITLE
4.13 Implement Duplicates Handling Prepare

### ISSUE THREAD

**Issue by shashi165** [mojaloop/project#309]
**Goal**:
1. As a Switch
I would like to make sure _Duplicates Handling for Prepare requests is implemented_
so that I respond properly to duplicate requests.
2. As a DFSP
I would like to see the _Switch implement duplicate handling for Prepare requests_
so that my duplicate request calls are idempotent.

**Tasks**:
- [x] Implement Duplicates Handling Prepares (POST /transfers) - [@shashi165]
- [x] Update design (plantuml, sequence diagrams) as needed [@shashi165 @elnyry]
  - [x] Raise PR with updated design [@elnyry]
  - [x] Design to be reviewed DA
  - [x] If approved, new transferState to be added [here](https://github.com/mojaloop/central-
ledger/blob/develop/seeds/transferState.js ) (added INVALID [@ggrg])
  - [x] PR is reviewed and merged after changes are made based on reviews [@elnyry]
- [x] Add transferError table migration scripts and update docs [@ggrg]
- [x] Unit DB scripts to make change for transferId FK in transferDuplicateCheck table [@shashi165]
- [x] Unit tests - [@shashi165]
- [x] coverage tests - [@shashi165]
- [x] Integration tests - [@shashi165]
- [x] JSDocs - [@shashi165]

**Acceptance Criteria**:
- [x] Duplicate Handling of Prepare requests are handled so that for a
  - [x] valid duplicate request (with hash matching), ~a callback is sent~ for a transfer that is finalized (Committed, Aborted) (Right now only a message is put on the Notification topic, and the notification handlers makes the callbacks; story - #323 )
  - [x] valid duplicate request (with hash matching), for a transfer that is NOT finalized (RECEIVED, RESERVED), processing continues without any callback
  - [x] for invalid duplicate requests (hash doesn't match) for the same transferId, an error message is ~sent~ (3106) (Right now only a message is put on the Notification topic, and the notification handlers makes the callbacks; story - #323 )

**PRs**:
- [x] https://github.com/mojaloop/docs/pull/56
- [x] https://github.com/mojaloop/docs/pull/57\
- [x] https://github.com/mojaloop/central-ledger/pull/124

**Dependencies**:
- [x] #285 

**Accountability**:
- Owner 
- QA/Review @ggrg

**Comment by elnyry** [comment]
Changes in design as issues identified, increasing estimate and updating design

**Comment by elnyry** [comment]
PR raised - https://github.com/mojaloop/docs/pull/56

**Comment by elnyry** [comment]
Shashi's PR: https://github.com/mojaloop/central-ledger/pull/124
