### ISSUE TITLE
Update Quoting Service to support dynamic subScenarios in persistent mode 

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3090]
## **Goal**:
`As a` hub operation building new test cases that require sub-scenarios
`I want to` enable dynamic creation of sub-scenarios in the quoting service when in persistence mode
`so that` can trial and deploy into production new use cases that require sub-scenario allocation

**Note:**
There is an inconsistency in the implementation of the sub-scenario in the quotes API. The API definition has the transaction Type sub Scenario in the POST quotes call defined as an UndefinedEnum. The persistent mode implementation of this requires the Sub scenario to be pre-loaded into the database. (There are no-APIs that support this pre-loading.)
--> Suggested solution is to change the implementation and database table structure to be a free form text.

**Acceptance Criteria**:
- [ ] Verify that dynamic sub-scenarios will get send and received in the POST quotes when the quoting service is running in persistence on mode.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
