### ISSUE TITLE
[Helm] Externalise backend dependencies for TTK Helm Charts

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3091]
## **Goal**:
`As a` Helm Maintainer

`I want to` externalise all backend dependench charts for the TTK
  
`so that` all 3rd party depenendencies are managed seperately from the TTK followin Helm/Mojaloop best practices

**Acceptance Criteria**:
- [x] ~Externalise~ Remove MySQL dependency and remove/update Values config to reflect this change.
- [x] ~Externalise~ Remove KeyCloak dependency and remove/update Values config to reflect this change.
- [x] Externalise MongoDB dependency and remove/update Values config to reflect this change.
- [x] ~Externalise~ Remove Connection-Manager dependency and remove/update Values config to reflect this change.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/helm/pull/538

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3091?planning-poker) with Zenhub @vijayg10 @PaulGregoryBaker @mdebarros @kleyow @sri-miriyala

**Comment by elnyry-sam-k** [comment]
Changing the estimate to 3 because of the work done for and in [v14.1.1](https://github.com/mojaloop/helm/releases/tag/v14.1.1)
