### ISSUE TITLE
Publish ARM based docker images of all mojaloop services

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3095]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` have ARM based docker images of all mojaloop services
  
`so that` I can run mojaloop in ARM based machines like Macbook with apple silicon chips

**Acceptance Criteria**:
- [ ] CircleCI is refactored to build ARM based docker images and push it to docker hub
- [ ] ARM based docker images are available for all mojaloop services in docker hub
- [ ] Test the ARM based image in an apple silicon

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Try ARM machine executor in provided by circleCI to build ARM based docker images
- [ ] Refactor circleCI to push multiple images to docker hub

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
