### ISSUE TITLE
Update core services to Node LTS 18 with updated dependencies

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#3097]
## **Goal**:
`As an` adopter of Mojaloop core services

`I want to` be able to use core libraries that are upgraded to latest node LTS (v18 LTS)
  
`so that` I can ensure support for the version used

**Acceptance Criteria**:
**TODO: Prune repositories that don't apply, ask if PM4ML repositories are in scope.**

- New versions of core services upgraded to latest node LTS 18 with dependecies, audit and ci update.
  - [ ] account-lookup-bc
  - [ ] account-lookup-service
  - [ ] accounts-and-balances-bc
  - [ ] als-consent-oracle
  - [ ] als-oracle-pathfinder
  - [ ] als-oracle-template
  - [ ] api-notifier
  - [ ] api-snippets
  - [ ] apm-agent-nodejs
  - [ ] apm-agent-nodejs-opentracing
  - [ ] auditing-bc
  - [ ] auth-lib
  - [ ] auth-service
  - [ ] bulk-api-adapter
  - [ ] bulk-api-adapter-1
  - [ ] business-operations-framework-docs
  - [ ] central-event-processor
  - [ ] central-kms
  - [ ] central-ledger
  - [ ] central-services-error-handling
  - [ ] central-services-health
  - [ ] central-services-logger
  - [ ] central-services-metrics
  - [ ] central-services-shared
  - [ ] central-services-stream
  - [ ] central-settlement
  - [ ] charts
  - [ ] ci-config
  - [ ] community-tools
  - [ ] contrib-cross-network-demo
  - [ ] contrib-dev-portal
  - [ ] contrib-fido-test-ui
  - [ ] contrib-fido2-flutter-lib
  - [ ] contrib-mojawallet-demo
  - [ ] contrib-pisp-demo-svc
  - [ ] contrib-pisp-demo-ui
  - [ ] contrib-pos-demo
  - [ ] contrib-rancher-scaler-tool
  - [ ] database-lib
  - [ ] design-authority-project
  - [ ] dfsp-account
  - [ ] dfsp-admin
  - [ ] dfsp-identity
  - [ ] documentation
  - [ ] documentation-artifacts
  - [ ] email-notifier
  - [ ] event-sdk
  - [ ] event-sidecar
  - [ ] event-stream-processor
  - [ ] finance-portal-backend-service
  - [ ] finance-portal-lib
  - [ ] finance-portal-ui
  - [ ] finance-portal-v2-ui
  - [ ] forensic-logging-client
  - [ ] forensic-logging-sidecar
  - [ ] fraud_risk_management
  - [ ] gsp-connector
  - [ ] hackathon-docs
  - [ ] haproxy-helm-charts
  - [ ] helm
  - [ ] iac-aws-backend
  - [ ] iac-aws-bootstrap
  - [ ] iac-aws-platform
  - [ ] iac-shared-modules
  - [ ] iac_post_deploy
  - [ ] image-watcher-svc
  - [ ] interop-apis-bc
  - [ ] interop-switch-js
  - [ ] license-scanner-tool
  - [ ] logging-bc
  - [ ] microfrontend-boilerplate
  - [ ] microfrontend-shell-boilerplate
  - [ ] ml-api-adapter
  - [ ] ml-core-test-harness
  - [ ] ml-iso-hackathon
  - [ ] ml-number
  - [ ] ml-operator
  - [ ] ml-oss-sandbox
  - [ ] ml-pisp-bootcamp
  - [ ] ml-schema-validator
  - [ ] ml-testing-toolkit
  - [ ] ml-testing-toolkit-client-lib
  - [ ] ml-testing-toolkit-shared-lib
  - [ ] ml-testing-toolkit-ui
  - [ ] mojaloop
  - [ ] mojaloop-adapter
  - [ ] mojaloop-business-docs
  - [ ] mojaloop-simulator
  - [ ] mojaloop-specification
  - [ ] mojaloop.github.io
  - [ ] node-version-checker
  - [ ] ntpd
  - [ ] object-store-lib
  - [ ] operator-settlement
  - [ ] oracle-shared-library
  - [ ] participants-bc
  - [ ] pi8-perf-testing
  - [ ] pisp-project
  - [ ] platform-configuration-bc
  - [ ] platform-shared-lib
  - [ ] platform-shared-tools
  - [ ] poc-architecture
  - [ ] postman
  - [ ] project
  - [ ] quoting-bc
  - [ ] quoting-service
  - [ ] reference-architecture-doc
  - [ ] reporting
  - [ ] reporting-bc
  - [ ] reporting-events-processor-svc
  - [ ] reporting-hub-bop-api-svc
  - [ ] reporting-hub-bop-experience-api-svc
  - [ ] reporting-hub-bop-positions-ui
  - [ ] reporting-hub-bop-role-ui
  - [ ] reporting-hub-bop-settlements-ui
  - [ ] reporting-hub-bop-shell
  - [ ] reporting-hub-bop-trx-ui
  - [ ] reporting-k8s-templates
  - [ ] role-assignment-service
  - [ ] scheduling-bc
  - [ ] sdk-mock-dfsp-backend
  - [ ] sdk-scheme-adapter
  - [ ] sdk-standard-components
  - [ ] security-bc
  - [ ] security-kratos-oidc-provider-ui
  - [ ] security-rbac-tests
  - [ ] security-role-perm-operator-svc
  - [ ] settlement-management
  - [ ] settlements-bc
  - [ ] simulator
  - [ ] simulator-kafka
  - [ ] test-coda-integration
  - [ ] test-scripts
  - [ ] testing-toolkit-test-cases
  - [ ] testpages
  - [ ] thirdparty-api-svc
  - [ ] thirdparty-sdk
  - [ ] transaction-requests-service
  - [ ] transfers-bc
  - [ ] typescript-bc-template
  - [ ] typescript-svc-template
  - [ ] vuepress-plugin-versioning
  - [ ] wso2-mysql
  - [ ] wso2apim
  - [ ] wso2is-populate
  - [ ] wso2iskm

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
**COPY acceptance criteria repositories after being pruned**
- [ ] Upgrade Node to LTS 18, upgrade dependencies, address audit issuess and update CI machines to LTS 18

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ]

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
completed / obsolete
