### ISSUE TITLE
Upgrade Core OSS Dev-Test Env to meet Mojaloop Testing Standards

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3098]
## **Goal**:
`As a` Mojaloop Maintainer

`I want to` upgrade the Core OSS Dev-Test environment 
  
`so that` that it meets the Mojaloop Testing Standards as defined by the Mojaloop DA

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Confirm versions to upgrade to (Rancher , k8s support etc)
- [ ] Upgrade Rancher to the latest version (2.7.1? - to be confirmed)
- [ ] Upgrade node template config (to ensure they use LTS OS version) - based on Rancher requirements
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3098?planning-poker) with Zenhub @vijayg10 @mdebarros @kleyow @sri-miriyala

**Comment by mdebarros** [comment]
According to the [Rancher v2.6.8 Support Matrix](https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-6-8/), we are running the recommended versions of the following:

1. OS: Ubuntu v20.04 LTS 
2. K8s: v1.24

According to the [Rancher v2.6.10 Support Matrix](https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-6-10/), if we 
If we upgrade to Rancher v2.6.10], we would need to upgrade our OS from v20.04 LTS to v22.04 LTS. 

Upgrading our environment would result in us running the following recommended versions:

1. OS: Ubuntu v22.04 LTS  <-- the only major change
2. K8s: v1.24

**Comment by elnyry-sam-k** [comment]
Sounds good, Miguel. Thank you for the details of the versions.

Lets use this story when we're ready to adopt v2.7.1 of Rancher and can prioritize upgrading Ubuntu version.
