### ISSUE TITLE
[01] 4.8 Handle Rejections (from Payee)

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#310]
**Goal**:
As a Switch
I would like the _Rejections (from Payee) to be handled_
so that the rejected transfers by FSPs can be catered for as expected.

**Tasks**:
- [x] Implementation for Handling Rejections (from Payee) in
  - [x] Rejections based on Kafka events are implemented [@ggrg]
  - [x] ML-API-adapter to produce rejection events [@ggrg]
  - [x] ML-API-adapter to cater for fulfill rejections via API calls [@ggrg]
  - [x] ~Fulfill handler consumes rejection and produces position event~
  - [x] ~Position event handler to consume rejection: decrement position and produce notification, produce transfer~
  - [x] ~Transfer handler to consume rejection and update transfer state to reject~
- [x] Unit Tests [@ggrg]
- [ ] ~Integration Tests~
- [x] Code coverage [@ggrg]
- [x] Test Rejections end-to-end [@ggrg]

**Acceptance Criteria**:
- [x] Rejections based on Kafka events are implemented
- [x] ML-API-adapter to produce rejection events 
- [x] ML-API-adapter to cater for fulfill rejections via API calls
- [x] ~Fulfill handler consumes rejection and produces position event~
- [x] ~Position event handler to consume rejection: decrement position and produce notification, produce transfer~
- [x] ~Transfer handler to consume rejection and update transfer state to reject~
- [x] Rejection functionality is tested end-to-end

**Dependencies**:
- None currently

**Accountability**:
- Owner @mdebarros 
- QA/Review

**Pull Requests**:
- [ ] https://github.com/mojaloop/ml-api-adapter/pull/45

**Comment by elnyry** [comment]
Moving this over to next Sprint as this Sprint is overloaded (at 150%) and doesn't look like we'll get to this and had additional work in deploying 3.3 codebase and fixing bugs related to that (Items #403 , #392
