### ISSUE TITLE
add facility to monitor kafka to the mojaloop example backend chart

### ISSUE THREAD

**Issue by tdaly61** [mojaloop/project#3103]
## **Goal**:
`As a` Mojaloop core contributor 

`I want to` add a kafka console to the mojaloop-example-backend (probably redpanda)
  
`so that` we have good visibility into the kafka  messages

Question: is the redpanda the only or best choice here given that redpanda and apache kafka seem to be in competition ? 

**Acceptance Criteria**:
- [ ] kafka monitoring tool deploys and runs and allows easy access to monitor kafka

**Complexity**: <medium/low> > some have already tested the redpanda chart
**Uncertainty**: <Low> > as above some folks already have deployed and run a solution 

---

**Tasks**:
- [ ] add helm chart for monitoring tool to mojaloop-example-backend chart 
- [ ] deploy and test 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @tdaly61 
- QA/Review: @mdebarros
