### ISSUE TITLE
[Helm] Consolidate MongoDBs in example-backend chart

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3104]
## **Goal**:
`As a` Hub Deployer/Maintainer

`I want to` consolidate MongoDBs in example-backend chart
  
`so that` the MongoDB configuration is consistent with MySQL configs, and also reduce the deployment footprint.

**Acceptance Criteria**:
- [ ] Example Backend Helm chart only deploys a single MongoDB
- [ ] Example Backend Helm chart on MongoDB deployment creates the necessary DBs to isolate the data for each service dependency
- [ ] Services that have a dependency on MongoDB reference the same example backend service but include the "DB" configuration to isolate their data, etc.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
