### ISSUE TITLE
Upgrade IaC to support internal bulk sdk functionality (published with ml v14.1.0)

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3107]
## **Goal**:
`As a` Hub operator
`I want to` test and make use of the bulk SDK enhancements
`so that` evaluate and use these enhancements

`As a` Hub operator
`I want to` test and make use of the the latest enhancements
`so that` evaluate and use these enhancements

**Acceptance Criteria**:
- [x]  IaC deploys the latest Mojaloop version 14.1.0
- [x] Tests for changes in Mojaloop 14.1.0 have been run and pass
- [x] Confirm configuration to enable internal SDK simulators and helm sdk tests are configurable through the IaC config.
- [x] Confirm bulk tests are executed and pass on the existing IaC job 
- [x] Confirm SDK bulk tests are executed and pass on a new IaC job
- [x] Confirm that the IaC workstream team are happy with the proposed IaC job and job naming

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Previous Story**:
- https://github.com/mojaloop/project/issues/2814

**Tasks**:
- [x] Bulk tests are executed and pass on the existing IaC job [@sri-miriyala ]
- [x] SDK bulk tests are executed and pass on a new IaC job [@sri-miriyala ]
- [x] Find out the gaps to enable ttksims for sdk bulk tests
- [x] Add redis terraform helm resource as dependency for ttksims
- [x] Add ttksims_enabled parameter
- [x] Add ttksims configuration to the values file of mojaloop in IaC
- [x] Test the deployment in IaC

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/iac-aws-platform/pull/81

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3107?planning-poker) with Zenhub @elnyry-sam-k @kleyow @sri-miriyala @vijayg10
