### ISSUE TITLE
Update Payment Manager IaC to support SDKs /bulktransactions

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3108]
## **Goal**:
`As a` DFSP Participant hosting a Payment Manager, or as an organisation providing Payment Manager hosting services 
`I want to` ensure that the latest bulk enhancements are available to use
`so that` these enhancements can be validated and used

**Acceptance Criteria**:
- [ ] Confirm that the SDK-scheme-adapter is updating the jws certificates of new FSP onboarded
- [ ] Confirm that the bulk API calls needs hub to sign jws certificates outbound
- [ ] Confirm that this logged bug is no-longer an issue. #2891
- [ ] Verify that the PM4ML helm chart is update to support bulk functionality
- [ ] Verify that the IaC Payment Manager deploys Payment manager with bulk support option enabled.
- [ ] Verify that the bulktransactions endpoints are correctly tested with an end to end functional test.
- [ ] Verify that bulktransaction test are added to the IaC pipeline

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Add kafka service to pm4ml iac [@vijayg10]
- [x] Add bulk support in pm4ml helm chart if there is any configuration missing [@vijayg10]
- [x] Parameterise the sdk support per each pm4ml config [@vijayg10]
- [x] Deploy the solution and test in IaC [@vijayg10]
- [x] Create a basic happy path testcase and include that in the IaC pipeline [@vijayg10]
- [x] Release new versions for IaC, helm chart, tests...etc [@vijayg10]
- [x] Add tests for bulktransactions endpoints [@sri-miriyala ]
- [x] Write end-end test and check it is working [@sri-miriyala]
- [x] Add these new tests to the pipeline

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/iac-aws-platform/pull/84
- [x] https://github.com/pm4ml/pm4ml-k3s-iac/pull/35
- [x] https://github.com/pm4ml/pm4ml-test-scripts/pull/9

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3108?planning-poker) with Zenhub @vijayg10 @mdebarros @sri-miriyala @kleyow
