### ISSUE TITLE
[025] 4.14 Fulfil Handler Failures

### ISSUE THREAD

**Issue by shashi165** [mojaloop/project#311]
**Goal**:
As a Switch
I would like to _handle failures in the FulfilHander_
so that Notifications can be sent out to the relevant FSPs.

**Tasks**:
- [ ] Implement FulfilHandler to cater for Failures (expand list below, adding a sample case)
  - [ ] Validation failure (fulfilment/expiry-time checks.. steps 25, 26 currently)
  - [ ] Validation failures to send error message (change implementation that currently sends back same message)
  - [ ] ~Internal error occurs on one of the downline processes~
  - [ ] Throw error for duplicate (same transferID & finalized state - committed/aborted) - errorCode = 3100 , errorDescription = 'Generic validation error - Duplicate Fulfil request'
- [ ] Unit tests
- [ ] Integration tests

**Acceptance Criteria**:
- [ ] The failures that occur in FulfilHandler are catered for so that notifications can be sent appropriately to the FSPs

**Dependencies**:
- [ ] 

**Accountability**:
- Owner 
- QA/Review

**Comment by elnyry** [comment]
These are taken-care of now
