### ISSUE TITLE
[Settlement] Workshops with MJL DA Workstream to capture all Settlements v3 requirements

### ISSUE THREAD

**Issue by koekiebox** [mojaloop/project#3110]
## **Goal**:
`As a` DA Team

`I want to` Agree 
  
`so that` Settlement is implemented as intended and agree to by the Mojaloop design authority.

**Acceptance Criteria**:
# Please see:
https://github.com/mojaloop/mojaloop-specification/issues/117

## **Uncertainty**: Medium

---

**Tasks**:
- [x] TBD [ @? ]

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [x] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @koekiebox / @MichaelJBRichards / Paul Makin
- QA/Review: TBC

**Comment by koekiebox** [comment]
# Document WIP:
https://docs.google.com/document/d/1Nm6B_tSR1mOM0LEzxZ9uQnGwXkruBeYB2slgYK1Kflo/edit#heading=h.6w64vxvw6er4

# Initial Presentation as motivation:
https://docs.google.com/presentation/d/19uy6pO_igmQ9uZRnKyZkXD8a8uyMKQcn/edit?usp=sharing&ouid=114849726292590490580&rtpof=true&sd=true

# Settlement Implementation
https://github.com/mojaloop/settlements-bc/tree/main/docs/flows

![Image](https://user-images.githubusercontent.com/1992108/208678305-34062039-988b-45f7-a21c-e47268065593.png)

![Image](https://user-images.githubusercontent.com/1992108/208678373-88d6afb3-f34f-4bc1-b1ec-2496b1219a96.png)

![Image](https://user-images.githubusercontent.com/1992108/208678446-8fc6c312-a552-4e62-b264-1950175c5e15.png)

**Comment by koekiebox** [comment]
Refer to stories:
- https://github.com/mojaloop/project/issues/3375
- https://github.com/mojaloop/project/issues/3366
- https://github.com/mojaloop/project/issues/3372
- https://github.com/mojaloop/project/issues/3373
- https://github.com/mojaloop/project/issues/3376
- https://github.com/mojaloop/project/issues/3370
- https://github.com/mojaloop/project/issues/3365
- https://github.com/mojaloop/project/issues/3371
- https://github.com/mojaloop/project/issues/3374
- https://github.com/mojaloop/project/issues/3290
