### ISSUE TITLE
[Settlement] Initial Base for Settlement-BC Domain Lib (domain-lib)

### ISSUE THREAD

**Issue by koekiebox** [mojaloop/project#3111]
## **Goal**:
`As a` Mojaloop Developer.

`I want to` Develop initial codebase required for Settlements vNext.
  
`so that` Architecture follows Mojaloop principles.

**Acceptance Criteria**:
- [ ] Domain layer completed and integrating with other components of the architecture
- [ ] Process a transfer
- [ ] Create a settlement matrix

**Complexity**: `High` > Majority of business logic resides in the domain layer.
**Uncertainty**: `Low` > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] `aggregate` making use of mock repositories (batch, model, participant, acc etc)
- [ ] Complete all the necessary domain classes, which include;
- [ ] `SettlementBatch`
- [ ] `SettlementBatchAccount`
- [ ] `SettlementConfig`
- [ ] `SettlementTransfer`
- [ ] `ICurrency`
- [ ] `Errors`
- [ ] Complete `infrastructure` interfaces and mock implementation for repos
- [ ] Create all necessary privileges required for `security-bc`

# Codebase:
https://github.com/mojaloop/settlements-bc/tree/main/packages/domain-lib

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @koekiebox 
- QA/Review: TBC
