### ISSUE TITLE
[Settlement] Initial Base for Infrastructure (infrastructure-lib)

### ISSUE THREAD

**Issue by koekiebox** [mojaloop/project#3114]
## **Goal**:
`As a` Developer

`I want to` Implement the `domain-lib`
  
`so that` <reason> 

**Acceptance Criteria**:
- [ ] Infrastructure tasks completed.

**Complexity**: Medium > A short comment to remind the reason for the rating

**Uncertainty**: Low > A short comment to remind the reason for the rating

---

**Tasks**:
The initial `infrastructure-lib` needs to be completed for `settlements-bc`:

The functionality should include:
## Complete all the necessary MongoDB repo's for;
- [ ] `SettlementBatch`
- [ ] `SettlementBatchAccount`
- [ ] `SettlementConfig`

# Codebase:
https://github.com/mojaloop/settlements-bc/tree/main/packages/infrastructure-lib

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @koekiebox 
- QA/Review: TBC
