### ISSUE TITLE
[Settlement] Initial Base for REST API (http-svc)

### ISSUE THREAD

**Issue by koekiebox** [mojaloop/project#3115]
## **Goal**:
`As a` Developer

`I want to` Implement the http REST service for Settlement
  
`so that` API endpoints are exposed for consumption.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
The initial `http-svc` needs to be completed for `settlements-bc`:

The functionality should include:
## Complete all the necessary endpoints for;
- [ ] `createTransfer` - POST `/settlement/transfer`
- [ ] `settlementMatrixFor(from: Date, to: Date, settlementModel? SettlementModel)` - POST `/settlement/matrix`

# Codebase:
https://github.com/mojaloop/settlements-bc/tree/main/packages/http-svc

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @koekiebox 
- QA/Review: TBC
