### ISSUE TITLE
Remove unused charts from Mojaloop helm

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#3116]
## **Goal**:
`As a` member of DevOps / Deployment team of Mojaloop

`I want to` have only charts that are active and maintained as part of a Mojaloop charts repo
  
`so that` unmaintained and unused charts are not present to make maintenance and configuration easier

**Acceptance Criteria**:
- [ ] Unused Mojaloop charts are removed from Mojaloop helm
  - [ ] NTDP
  - [ ] forensicloggingsidecar
  - [ ] centralenduserregistry
  - [ ]  finance-portal*

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
completed
