### ISSUE TITLE
[Settlement] Initial Base for Public API Types (public-types-lib)

### ISSUE THREAD

**Issue by koekiebox** [mojaloop/project#3117]
## **Goal**:
`As a` Developer

`I want to` Have a public types lib for external services.
  
`so that` Other Mojaloop services can more easily integrate with the settlement data types.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Medium > Data models only.

**Uncertainty**: Medium > Model may change.

---

**Tasks**:
- [x] Create and define public type for `ISettlementConfigDto`
- [x] Create and define public type for `ISettlementBatchDto`
- [x] Create and define public type for `ISettlementBatchAccountDto`
- [x] Create and define public type for `IParticipantAccountDto`
- [ ] Create and define public type for `ISettlementTransferDto`
- [ ] Create and define public type for `ISettlementMatrixSettlementBatchAccountDto`
- [ ] Create and define public type for `ISettlementMatrixBatchDto`
- [ ] Create and define public type for `ISettlementMatrixDto`
- [ ] Create and define public type for `SettlementBatchStatus`

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @koekiebox 
- QA/Review: TBC
