### ISSUE TITLE
[Settlement] Create initial Solution Design document to reflect Settlement solution

### ISSUE THREAD

**Issue by koekiebox** [mojaloop/project#3118]
## **Goal**:
`As a` Technical Lead

`I want to` Capture, track and Design Settlement requirements
  
`so that` The understanding and requirements for Settlement is clear.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High> > A short comment to remind the reason for the rating

**Uncertainty**: <Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Complete Settlement Solution Design document based on current Settlement requirements
- [ ] Capture the future stories for agreed changes to Settlement design

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @koekiebox
- QA/Review: TBC
