### ISSUE TITLE
[020] 4.15 Prepare Handler Failures

### ISSUE THREAD

**Issue by shashi165** [mojaloop/project#312]
**Goal**:
As a Switch
I would like the _handle failures in the PrepareHandler_
so that Notifications can be sent out to the relevant FSPs.

**Tasks**:
- [ ] Implement PrepareHandler to cater for Failures (expand list below, adding a sample case)
  - [ ] Validation failures
    - [ ] validation success, but existing entry
    - [ ] validation failed, new entry
    - [ ] validation failed, existing entry
  - [ ] Internal error occurs on one of the downline processes
- [ ] Error message should be included in the payload itself (for NotificationHandler)

**Acceptance Criteria**:
- [ ] The failures that occur in PrepareHandler are catered for, Notifications can be sent appropriately

**Dependencies**:
- [ ] [#309](https://github.com/mojaloop/project/issues/309)

**Accountability**:
- Owner @mdebarros 
- QA/Review

**Comment by elnyry** [comment]
Moving this out of 3.4 as a good chunk of this is covered in #309 and this would be blocked until 309 is completed and merged. Will need to pick this up in the packaging Sprint

**Comment by elnyry** [comment]
These are taken-care of now
