### ISSUE TITLE
Mojaloop Helm release v15.0.0

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#3122]
## **Goal**:
`As a` ML OSS adopter

`I want to` have a Mojaloop release v15.0.0 that is successfully validated by the Golden path tests
  
`so that` I can adopt and use a version of Mojaloop Switch services bundle that is tested and contains the latest features enhancements and bug fixes added in PI-29 / PI-20

**Acceptance Criteria**:
- [x] Docs on how to deploy & configure external backend-dependencies
    - [x] helm
    - ~documentation~ *--> This has been split out into a new story due to the effort/size required: https://github.com/mojaloop/project/issues/3177*
- [x] Update "APP VERSION" for each chart.yaml
- [x] Helm RC v15.0.0 is validated on Moja2 to achieve 100% result with TTK GoldenPath 
- [x] Helm RC v15.0.0 is validated with PISP provisioning and test collection (TTK) with 100%
- [x] Helm RC v15.0.0 is validated with Bulk test collection (TTK) with 100%
- [x] QA (Golden path) on deployments done on AWS Moja2 environment is done
- [x] Bugs are logged based on observations, failures
- [x] Bugs logged are fixed if critical to make subsequent releases in individual services (or Helm)
- [x] All the changes needed for supporting v15.0.0 of Helm are done
- [x] Helm v15.0.0 is released
- [x] Release notes for v15.0.0 published
- [x] Test cases v15.0.0 is published (TTK)
- [x] TTK tests run successfully as Post-Hook jobs and Tests

**Notes**:
- RC: https://github.com/mojaloop/helm/tree/release/v15.0.0-rc-1

**Complexity**: Medium - Involves all core and supporting services

**Uncertainty**: Medium

---

**Tasks**:
- [x] Initial PR with changes for v15.0.0
  - [x] Initial PR review
  - [x] Deploy, validate, fix issues, redeploy
  - [x] With stable deployment test Golden path
  - [x] removed out of scopped services
    - central-event-processor
    - email-notifier
  - [x] Summarize the above information into the v15 Release Notes as part of the v15
- [x] Validate PISP test provisioning and test collections (TTK) 
- [x] Identify issues with QA Scripts if any - fix them and retest
- [x] QA for bugs, regressions, log them
- [x] Fix bugs logged if critical
- [x] Deploy, validate on AWS Moja2
- [x] Validate with TTK GP collection
- [x] TTK test-cases repo v15.0.0 is published
- [x] Release notes for helm v15.0.0 drafted
  - [x] Guidance for migration from v14.1.0 (may have to be a separate story if sufficiently big / complex)
- [x] Update release notes with Upgrade Strategy Guide link
- [x] Helm v15.0.0 released *--> This has been split out into a new story due to the effort/size required: https://github.com/mojaloop/project/issues/3177*
- ~Review deployment guide documentation to ensure its up-to-date [@kleyow]~
	- ~Migrate deployment guide from legacy to main docs folder, update any links from docs/* folder to match the migrated deployment guide~
	- ~Update deployment guide to reflect externalised DB (ref: https://github.com/mojaloop/helm#deploying-backends-best-practice)~
- [x] Deployment of released Helm v15.0.0 on **Moja2**
  - [x] Helm v15.0.0 is deployed on **Moja2** successfully
  - [x] Regression testing on Moja2 using TTK collections
    - [x] GP collection
    - [x] Core Bulk collection
    - [x] Third-party collection
    - [x] SDK Bulk collection
  - [x] Validation using CGS Golden path regression tests etc on Moja2
- [x] Deployment of released Helm v15.0.0 on **Moja1**
  - [x] Helm v15.0.0 is deployed on **Moja1** successfully
  - [x] Validation using Golden path regression tests etc on Moja1
    - [x] GP collection
    - [x] Core Bulk collection
    - [x] Third-party collection
    - [x] SDK Bulk collection
  - [x] Validation using CGS Golden path regression tests etc on Moja1

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] TTK Tests pass
- [x] Code Style & Coverage meets standards
- [x] Release notes are verified

## **Pull Requests**:
- https://github.com/mojaloop/testing-toolkit-test-cases/pull/116
- https://github.com/mojaloop/helm/pull/551
- https://github.com/mojaloop/helm/pull/553
- https://github.com/mojaloop/helm/pull/554
- https://github.com/mojaloop/helm/pull/555
- https://github.com/mojaloop/helm/pull/556
- https://github.com/mojaloop/helm/pull/557
- https://github.com/mojaloop/helm/pull/558
- https://github.com/mojaloop/helm/pull/559
- https://github.com/mojaloop/helm/pull/560
- ~https://github.com/mojaloop/documentation/pull/409~ *--> This has been split out into a new story due to the effort/size required: https://github.com/mojaloop/project/issues/3177*

## **Issues**:
- https://github.com/mojaloop/project/issues/3178

## **Follow-up**:
- https://github.com/mojaloop/project/issues/3177

**Dependencies**:
- N/A

## **Accountability**:
- Owner: 
- QA/Review: @mdebarros @elnyry-sam-k @vijayg10

**Comment by elnyry-sam-k** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3122?planning-poker) with Zenhub @kleyow @mdebarros @sri-miriyala @PaulGregoryBaker

**Comment by elnyry-sam-k** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3122?planning-poker) with Zenhub @vijayg10

**Comment by mdebarros** [comment]
# Upgrade Test

Dev Release: `15.0.0-15705.5785e61`

```bash
❯ helm search repo mojaloop/mojaloop --devel --max-col-width 600
NAME                            	CHART VERSION       	APP VERSION                                                                                                                                                                                                                                                                                                                                                                                                                   	DESCRIPTION
mojaloop/mojaloop               	15.0.0-15705.5785e61	ml-api-adapter: v14.0.0; central-ledger: v17.0.1; account-lookup-service: v13.0.0; quoting-service: v15.0.2; central-settlement: v15.0.0; bulk-api-adapter: v15.0.0; transaction-requests-service: v14.0.1; simulator: v12.0.0; mojaloop-simulator: v14.0.1; sdk-scheme-adapter: v22.0.1; auth-service: v14.0.0; consent-oracle: v0.2.0; thirdparty-sdk: v13.0.2; ml-testing-toolkit: v16.0.0; ml-testing-toolkit-ui: v15.1.3;	Mojaloop Helm chart for Kubernetes
```

## Configurations

- https://github.com/mojaloop/deploy-config/blob/deploy/PI21.0/mojaloop/test.mojaloop.live/values-moja2-test-mojaloop-backend-v15.0.0.yaml
- https://github.com/mojaloop/deploy-config/blob/deploy/PI21.0/mojaloop/test.mojaloop.live/values-moja2-test-mojaloop-harness-v15.0.0.yaml

## Deployment

```bash
helm -n moja2 upgrade backend mojaloop/example-mojaloop-backend --install --version 15.0.0-15705.5785e61 -f ./mojaloop/test.mojaloop.live/values-moja2-test-mojaloop-backend-v15.0.0.yaml --devel
```

```bash
helm -n moja2 upgrade moja2 mojaloop/mojaloop --install --version 15.0.0-15705.5785e61 -f ./mojaloop/test.mojaloop.live/values-moja2-test-mojaloop-harness-v15.0.0.yaml --devel
```

## Environment

```bash

```

## History

Upgrade from Mojaloop from v14.1.1 to v15 Release:

```bash

```

## Test Reults

**Comment by mdebarros** [comment]
```
❯ helm search repo mojaloop/mojaloop --devel --max-col-width 900
NAME                            	CHART VERSION       	APP VERSION                                                                                                                                                                                                                                                                                                                                                                                                                   	DESCRIPTION
mojaloop/mojaloop               	15.0.0-15803.2d81622	ml-api-adapter: v14.0.0; central-ledger: v17.0.1; account-lookup-service: v13.0.0; quoting-service: v15.0.2; central-settlement: v15.0.0; bulk-api-adapter: v15.0.0; transaction-requests-service: v14.0.1; simulator: v12.0.0; mojaloop-simulator: v14.0.1; sdk-scheme-adapter: v22.0.1; auth-service: v14.0.0; consent-oracle: v0.2.0; thirdparty-sdk: v13.0.2; ml-testing-toolkit: v16.0.0; ml-testing-toolkit-ui: v15.2.1;	Mojaloop Helm chart for Kubernetes
```

```
❯ helm -n moja2 list
NAME       	NAMESPACE	REVISION	UPDATED                                  	STATUS  	CHART                                        	APP VERSION
backend    	moja2    	1       	2023-03-23 11:56:49.177248 +0200 SAST    	deployed	example-mojaloop-backend-15.0.0-15803.2d81622	nginx: 4.4.2 ; mysql: 9.4.1; kafka: 19.0.2; mongodb: 13.3.1; redis:17.3.7
bof        	moja2    	1       	2023-03-20 08:16:57.525016084 -0500 -0500	deployed	bof-2.4.5                                    	2.4.5
bof-backend	moja2    	1       	2023-03-20 08:16:02.868115567 -0500 -0500	deployed	backend-0.1.0                                	1.16.0
moja2      	moja2    	1       	2023-03-23 12:15:04.994613 +0200 SAST    	deployed	mojaloop-15.0.0-15803.2d81622                	ml-api-adapter: v14.0.0; central-ledger: v17.0.1; account-lookup-service: v13.0.0; quoting-service: v15.0.2; central-settlement: v15.0.0; bulk-api-adapter: v15.0.0; transaction-requests-service: v14.0.1; simulator: v12.0.0; mojaloop-simulator: v14.0.1; sdk-scheme-adapter: v22.0.1; auth-service: v14.0.0; consent-oracle: v0.2.0; thirdparty-sdk: v13.0.2; ml-testing-toolkit: v16.0.0; ml-testing-toolkit-ui: v15.2.1;
```

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Standard Provisioning Collection
Environment: moja2.test.mojaloop.live@v15.0.0
Total assertions: 326
Passed assertions: 326
Failed assertions: 0
Total requests: 324
Total test cases: 37
Passed percentage: 100.00%
Started time: Thu, 23 Mar 2023 10:28:13 GMT
Completed time: 2023-03-23T10:29:47.124Z
Runtime duration: 93439 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-standard_provisioning_collection-2023-03-23T10%3A29%3A47.124Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP Tests
Environment: moja2.test.mojaloop.live@v15.0.0
Total assertions: 2668
Passed assertions: 2668
Failed assertions: 0
Total requests: 603
Total test cases: 131
Passed percentage: 100.00%
Started time: Thu, 23 Mar 2023 10:29:58 GMT
Completed time: 2023-03-23T10:33:25.633Z
Runtime duration: 207241 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-gp_tests-2023-03-23T10%3A33%3A25.633Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Bulk Tests
Environment: moja2.test.mojaloop.live@v15.0.0
Total assertions: 337
Passed assertions: 337
Failed assertions: 0
Total requests: 63
Total test cases: 16
Passed percentage: 100.00%
Started time: Thu, 23 Mar 2023 10:33:38 GMT
Completed time: 2023-03-23T10:35:46.699Z
Runtime duration: 128111 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-bulk_tests-2023-03-23T10%3A35%3A46.699Z.html)


```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Thirdparty Provisioning Collection
Environment: moja2.test.mojaloop.live@v15.0.0
Total assertions: 137
Passed assertions: 137
Failed assertions: 0
Total requests: 135
Total test cases: 15
Passed percentage: 100.00%
Started time: Thu, 23 Mar 2023 10:35:57 GMT
Completed time: 2023-03-23T10:36:35.285Z
Runtime duration: 38024 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-thirdparty_provisioning_collection-2023-03-23T10%3A36%3A35.285Z.html)


```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Thirdparty Tests
Environment: moja2.test.mojaloop.live@v15.0.0
Total assertions: 21
Passed assertions: 21
Failed assertions: 0
Total requests: 20
Total test cases: 8
Passed percentage: 100.00%
Started time: Thu, 23 Mar 2023 10:36:45 GMT
Completed time: 2023-03-23T10:36:53.066Z
Runtime duration: 7255 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-thirdparty_tests-2023-03-23T10%3A36%3A53.066Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: SDK Bulk Provisioning Collection
Environment: moja2.test.mojaloop.live@v15.0.0
Total assertions: 123
Passed assertions: 123
Failed assertions: 0
Total requests: 119
Total test cases: 13
Passed percentage: 100.00%
Started time: Thu, 23 Mar 2023 10:37:04 GMT
Completed time: 2023-03-23T10:37:42.843Z
Runtime duration: 38401 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-sdk_bulk_provisioning_collection-2023-03-23T10%3A37%3A42.843Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: SDK Bulk Tests
Environment: moja2.test.mojaloop.live@v15.0.0
Total assertions: 217
Passed assertions: 217
Failed assertions: 0
Total requests: 45
Total test cases: 22
Passed percentage: 100.00%
Started time: Thu, 23 Mar 2023 10:38:02 GMT
Completed time: 2023-03-23T10:40:43.768Z
Runtime duration: 161275 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-sdk_bulk_tests-2023-03-23T10%3A40%3A43.768Z.html)

**Comment by mdebarros** [comment]
# Upgrade Test

Dev Release: `15.0.0-5803.2d81622`

```
❯ helm search repo mojaloop/mojaloop --devel --max-col-width 900
NAME                            	CHART VERSION       	APP VERSION                                                                                                                                                                                                                                                                                                                                                                                                                   	DESCRIPTION
mojaloop/mojaloop               	15.0.0-15803.2d81622	ml-api-adapter: v14.0.0; central-ledger: v17.0.1; account-lookup-service: v13.0.0; quoting-service: v15.0.2; central-settlement: v15.0.0; bulk-api-adapter: v15.0.0; transaction-requests-service: v14.0.1; simulator: v12.0.0; mojaloop-simulator: v14.0.1; sdk-scheme-adapter: v22.0.1; auth-service: v14.0.0; consent-oracle: v0.2.0; thirdparty-sdk: v13.0.2; ml-testing-toolkit: v16.0.0; ml-testing-toolkit-ui: v15.2.1;	Mojaloop Helm chart for Kubernetes
```

## Configurations

- https://github.com/mojaloop/deploy-config/blob/deploy/PI21.0/mojaloop/test.mojaloop.live/values-moja1-test-mojaloop-backend-v15.0.0.yaml
- https://github.com/mojaloop/deploy-config/blob/deploy/PI21.0/mojaloop/test.mojaloop.live/values-moja1-test-mojaloop-harness-v14.1.1-with-v15.0.0-backend.yaml
- https://github.com/mojaloop/deploy-config/blob/deploy/PI21.0/mojaloop/test.mojaloop.live/values-moja1-test-mojaloop-harness-v15.0.0.yaml

## Deployment

```bash
helm -n moja1 upgrade backend mojaloop/example-mojaloop-backend --install --version 15.0.0-5803.2d81622-f ./mojaloop/test.mojaloop.live/values-moja1-test-mojaloop-backend-v15.0.0.yaml --devel
```

```bash
helm -n moja1 install moja1 mojaloop/mojaloop --version 14.1.1 -f ./mojaloop/test.mojaloop.live/values-moja1-test-mojaloop-harness-v14.1.1-with-v15.0.0-backend.yaml
```

```bash
export SERVICE_NS="moja1";

export SERVICE_NAME="tp-api-svc"; \
echo "Re-creating the $SERVICE_NS/$SERVICE_NAME"; \
export K8_DESCRIPTOR=$(kubectl -n $SERVICE_NS get svc/$SERVICE_NAME -o json | jq 'del(.spec.clusterIP) | del(.spec.clusterIPs)') && \
kubectl -n $SERVICE_NS delete svc/$SERVICE_NAME && \
echo $K8_DESCRIPTOR | kubectl create --save-config -f -;

export SERVICE_NAME="auth-svc"; \
echo "Re-creating the $SERVICE_NS/$SERVICE_NAME"; \
export K8_DESCRIPTOR=$(kubectl -n $SERVICE_NS get svc/$SERVICE_NAME -o json | jq 'del(.spec.clusterIP) | del(.spec.clusterIPs)') && \
kubectl -n $SERVICE_NS delete svc/$SERVICE_NAME && \
echo $K8_DESCRIPTOR | kubectl create --save-config -f -;

export SERVICE_NAME="consent-oracle"; \
echo "Re-creating the $SERVICE_NS/$SERVICE_NAME"; \
export K8_DESCRIPTOR=$(kubectl -n $SERVICE_NS get svc/$SERVICE_NAME -o json | jq 'del(.spec.clusterIP) | del(.spec.clusterIPs)') && \
kubectl -n $SERVICE_NS delete svc/$SERVICE_NAME && \
echo $K8_DESCRIPTOR | kubectl create --save-config -f -;
```

```bash
helm -n moja1 upgrade moja1 mojaloop/mojaloop --install --version 15.0.0-5803.2d81622 -f ./mojaloop/test.mojaloop.live/values-moja1-test-mojaloop-harness-v15.0.0.yaml --devel
```

## Environment

```bash
❯ helm list

```

## History

Upgrade from Mojaloop from v14.1.1 to v15 Release:

```bash
❯ helm history moja1

```

## Test Reults

**Comment by mdebarros** [comment]
```
❯ helm search repo mojaloop/mojaloop  --max-col-width 900
NAME                                    CHART VERSION   APP VERSION                                                                                                                                                                                                                                                                                                                                                                                                                           DESCRIPTION                                      
mojaloop/mojaloop                       15.0.0          ml-api-adapter: v14.0.0; central-ledger: v17.0.1; account-lookup-service: v13.0.0; quoting-service: v15.0.2; central-settlement: v15.0.0; bulk-api-adapter: v15.0.0; transaction-requests-service: v14.0.1; simulator: v12.0.0; mojaloop-simulator: v14.0.1; sdk-scheme-adapter: v22.0.1; auth-service: v14.0.0; consent-oracle: v0.2.0; thirdparty-sdk: v13.0.2; ml-testing-toolkit: v16.0.0; ml-testing-toolkit-ui: v15.2.1;        Mojaloop Helm chart for Kubernetes               
mojaloop/mojaloop-bulk                  15.0.0          bulk-api-ad
```

**Comment by mdebarros** [comment]
## Cronjob Test result

https://mojaloop.slack.com/archives/CG3MAJZ5J/p1679645004770279

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP CronJob
Environment: moja1.test.mojaloop.live@v15.0.0
Total assertions: 2668
Passed assertions: 2668
Failed assertions: 0
Total requests: 603
Total test cases: 131
Passed percentage: 100.00%
Started time: Fri, 24 Mar 2023 08:00:03 GMT
Completed time: 2023-03-24T08:03:21.006Z
Runtime duration: 197579 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-tmp_test_cases_testing-toolkit-test-cases-15.0.0_collections_hub_golden_path-2023-03-24T08%3A03%3A21.006Z.html)

**Comment by mdebarros** [comment]
## Updated v15 Release with rev 1 fix applied

https://github.com/mojaloop/helm/releases/tag/v15.0.0

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP Tests
Environment: moja1.test.mojaloop.live@v15.0.0
Total assertions: 2668
Passed assertions: 2668
Failed assertions: 0
Total requests: 603
Total test cases: 131
Passed percentage: 100.00%
Started time: Fri, 24 Mar 2023 18:41:26 GMT
Completed time: 2023-03-24T18:44:43.195Z
Runtime duration: 196456 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-gp_tests-2023-03-24T18%3A44%3A43.195Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Post Cleanup
Environment: moja1.test.mojaloop.live@v15.0.0
Total assertions: 49
Passed assertions: 49
Failed assertions: 0
Total requests: 15
Total test cases: 4
Passed percentage: 100.00%
Started time: Fri, 24 Mar 2023 18:44:56 GMT
Completed time: 2023-03-24T18:45:06.749Z
Runtime duration: 10488 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-post_cleanup-2023-03-24T18%3A45%3A06.749Z.html)
