### ISSUE TITLE
Baseline transfer phase characterisation for Mojaloop v14.1

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3123]
## **Goal**:
`As a` Hub Operator
`I want to` understand the current Mojaloop releases performance characterisation
`so that` design & optimise my deployment configuration, and understand comparative performance impact of designs changes.

Note: This initial characterisation work will be limited to the transfer phase and will exclude the impact of the IaC WS02 gateway

**Acceptance Criteria**:
- [ ] Verify that the test script tests the transfer phase 
   - using PM4ML as the participant connection tool
   - bypass any impact that the API gateway has
- [ ] Verify that test process and results are documented and published to the community.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
WSO2 no longer applicable
