### ISSUE TITLE
Deploy IaC environment for characterisation test

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3124]
## **Goal**:
`As a` Development team performing a transfers characterisation on the current Mojaloop version
`I want to` build and environment that will support the test execution
`so that` it can be configured to support the characterisation outcomes required

**Acceptance Criteria**:
- [ ] Verify that a Standard IaC Switch is deployed 
- [ ] Verify that the golden path test collection is run and passes
- [ ] Verify that the Existing Dashboards are deployed and working
- [ ] Verify that the WS02 gateway is not being used when communicating with PM4MLs
- [ ] 

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
