### ISSUE TITLE
Fix exiting Mojaloop Grafana dashboards

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3125]
## **Goal**:
`As a` Mojaloop Community
`I want to` make use of the Grafana dashboards
`so that` I can use these to analyse the performance of a Mojaloop deployment

**Acceptance Criteria**:
- Validate Existing Dashboards are working:
   - [ ] Central Services 
   - [ ] Central Services Characterisation
   - [ ] ML API Adapter
   - [ ] Kafka
   - [ ] Kubernetes Cluster
   - [ ] MySQL
   - [ ] NodeJS Application

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
This work has been completed as part of the characterisation effort on each complonent.
