### ISSUE TITLE
Define the Test Scenarios for baseline transfer characterisation

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3126]
## **Goal**:
`As a` Hub operator
`I want to` have a representative /  performance result set 
`so that` I can use these to base my deployment and use case product decisions on.

`As a` tech ops performing the characterisation test
`I want to` have a clear process for running and compiling the results
`so that` I can run this characterisation on all releases.

Note:
Initial work limits to transfer phase and excludes affect of API gateway

Meeting Notes:
Set JMeter to Run at a predefined rate
Measure concurrency of X
Duration of Run
Ramp up characteristics
 - unique Payer and Payee PM4MLs new for purpose of these test
 - 5 Payers starting at 20TPS each 

**Acceptance Criteria**:
- [ ] Verify that Test Scenarios for Standard Mojaloop P2P Use Case are documented
- [ ] Verify that the Test Characteristics are defined including
   - [ ] Actors involved (PM4ML Tenants involved)
   - [ ] Target Throughpupt
   - [ ] Concurrency
   - [ ] Duration
   - [ ] Ramp-Up
- [ ] Identify and Define changes to TTK Simulators for Mock Responses
- [ ] Define configurations for Mocked Oracles to support Test Scenarios
- [ ] Define the infra hardware for the Test PM4ML and Switch

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
