### ISSUE TITLE
Support bulk enhancements to be deployable with IaC

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3128]
## **Goal**:
`As a` Hub Operator using Mojaloop on a live system
`I want to` be able to deploy the bulk enhancements
`so that` make use of these features.

**Acceptance Criteria**:
- [x] Verify that the the IaC supports the Mojaloop versions > 14.0
- [x] Verify that Payment Manager helm deploys the latest release of SDK-Scheme Adapter
- [x] Verify that IaC deploy the latest Payment Manager helm
- [ ] Verify that IaC deploy and support bulk enabled on the latest Payment Manager helm

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
