### ISSUE TITLE
[Central-Ledger] modify mongoDB configuration to use explicit configs instead of uri 

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3129]
## **Goal**:
`As a` Hub deployers

`I want to` have each mongoDB client config seperately configurable
  
`so that` I can utilise externalised secrets

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] MongoDB configuration is configrable by seperate configs for host, port, user, database, password
- [x] Each of the MongoDB configuration that is configrable by seperate configs for host, port, user, database, password can be set via environmental variables, and will override any file configs
- [x] Integration Tests are updated and passed
- ~Upgrade ML-Core-Test Harness updated~ (to be a seperate story)

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
