### ISSUE TITLE
4.9 Implement Duplicates Handling Fulfil

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#313]
**Goal**:
1. As a Switch
I would like to make sure Duplicates Handling for Fulfil requests is implemented
so that I respond properly to duplicate Fulfil requests.
2. As a DFSP
I would like to see the Switch implement duplicate handling for Fulfil requests
so that my duplicate request calls are idempotent.

**Tasks**:
- [x] Implement Duplicates Handling Fulfil [@ggrg]
- [x] Implement non case-sensitive fspiop-source check [@ggrg]
- [x] Refactor transfer prepare duplicate check [@ggrg]
- [x] Alter database foreign keys to support transferFulfilmentDuplicateCheck [@ggrg]
- [x] Alter database to add and support transferErrorDuplicateCheck [@ggrg]
- [x] Implement transferErrorDuplicateCheck [@ggrg]
- [x] Repair integration tests [@ggrg]
- [x] Refactor PrepareHandler (Util.breadcrumb & Util.proceed) [@ggrg]
- [x] Explored all branches and documented output with analysis (see comments) [@ggrg]
- [x] Validate and refactor all notifications from Prepare Handler [@ggrg, @mdebarros]
- [x] Implement decisions made for which stories are not created [@ggrg]
- [x] Repair unit tests [@ggrg]
- [x] Add unit tests for full coverage [@ggrg]
- [x] Update docs repo (database model, sequence diagrams connectivity) [@ggrg]

**Acceptance Criteria**:
- [x] This is for receiving duplicate on the fulfilment for commits or rejected
  - [x] Duplicate Handling of Fulfil requests are handled so that for a
    - [x] valid duplicate request (with hash matching), a callback is sent for a transfer that is finalized (Committed, Aborted)
    - [x] valid duplicate request (with hash matching), for a transfer that is NOT finalized (RESERVED), processing continues without any callback
    - [x] for invalid duplicate requests (hash doesn't match) for the same transferId, an error message is sent (3106) and the transferFulfillment along with hash are stored as well
  - [x] The duplicate request related events are logged/published
- [x] This is for receiving duplicate on the error endpoint
  - [x] Apply same logic for requests on Transfer Error endpoint
  - [x] A new table transferErrorDuplicateCheck exists for storing message hashes (**?**)

**Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/263
- [x] https://github.com/mojaloop/ml-api-adapter/pull/98
- [x] https://github.com/mojaloop/docs/pull/144

**Related**:
- https://github.com/mojaloop/project/issues/697
- https://github.com/mojaloop/project/issues/698
- https://github.com/mojaloop/project/issues/699
- Discussed in DA, agreed to use the 'createdDate' timestamp from the 'transferStateChange' table for validation

**Accountability**:
- Owner @ggrg 
- QA/Review DA

**Notes**:
- Sequence diagram links:
  - [seq-fulfil-2.1.1](https://github.com/mojaloop/docs/blob/master/Diagrams/SequenceDiagrams/seq-fulfil-2.1.1.svg)
  - [seq-reject-2.2.1](https://github.com/mojaloop/docs/blob/master/Diagrams/SequenceDiagrams/seq-reject-2.2.1.svg)

**Comment by elnyry** [comment]
Eventually would like to have this implemented (already designed), but not part of the API Specification  yet, so not mandatory for PI-3

**Comment by ggrg** [comment]
```
P. prepare
  - 7. (callbackErrorInternal2) call with non-existing fsp or currency: {"from":"switch" ... {"errorCode":2001,"errorDescription":"Internal server error","extensionList": ...
  - 1. (callbackErrorNotFound1) second call with non-existing fsp:  {"from":"switch" ... {"errorCode":2001,"errorDescription":"Internal server error: transfer/state not found","extensionList": ...
  - 6. (positionTopic1) successful prepare: {"from":"dfsp1","to":"dfsp2" ... {"status":"success","code":0 ...
  - 3. (inProgress1) duplicating previous: consumerCommit, histTimerEnd
  - 4. (callbackErrorModified1) modified previous: {"from":"switch","to":"dfsp1" ... {"errorCode":3106,"errorDescription":"Modified request","extensionList": ...
  - 8. (callbackErrorGeneric) validation failed: {"from":"switch","to":"dfsp2" !!! payload.payerFsp !!! {"errorCode":3100,"errorDescription":"Generic validation error: FSPIOP-Source header should match Payer","extensionList": ...
  - 2. (callbackFinilized1) repeated previous: {"from":"switch","to":"dfsp2" !!! "payload":{ "transferState":"ABORTED" !!! "state":{"status":"success","code":0 !!!
  - 2. (callbackFinilized1) duplicate prepare for committed: {"from":"switch","to":"dfsp1" ... "payload":{"fulfilment": ...
  - 5. (callbackErrorInternal1) -- could not trigger this scenario
```

**Comment by ggrg** [comment]
```
C. commit
  - 12. (positionTopic2) successful commit: {"from":"dfsp2","to":"dfsp1" ... "payload":{"fulfilment": ...
  - 2. (callbackFinilized2) repeated previous: {"from":"switch","to":"dfsp2" ... "payload":{"fulfilment": ... {"status":"success","code":0 ...
  - 5+9. (inProgress3+callbackErrorModifiedRequest) modified previous: {"from":"switch","to":"dfsp2" ... {"errorCode":3106,"errorDescription":"Modified request","extensionList": ...
  - 3. (callbackErrorModified2) repeated modified: {"from":"switch","to":"dfsp2" ... "errorCode":3106,"errorDescription":"Modified request","extensionList": ... "errorCode":3106,"errorDescription":"Modified request","extensionList": ...
  - 5+8. (inProgress3+callbackErrorInvalidFulfilment) modified previous with invalid fulfilment: {"from":"switch","to":"dfsp2" ... {"errorCode":3100,"errorDescription":"Generic validation error: invalid fulfilment","extensionList" ...
  - 3. (callbackErrorModified2) repeated modified with invalid fulfilment: {"from":"switch","to":"dfsp2" ... "errorCode":3106,"errorDescription":"Modified request","extensionList": ...
  
  > PREPARED NEW TRANSFER <
  - 4+8. (inProgress2+callbackErrorInvalidFulfilment) tried invalid fulfilment on a prepared transfer: {"from":"switch","to":"dfsp2" ... {"errorCode":3100,"errorDescription":"Generic validation error: invalid fulfilment","extensionList" ...
  - 4+8. (inProgress2+callbackErrorInvalidFulfilment) re-tried previous multiple times: same as above !!! do we ever need to continue repeated invalid request?
  - 5+12. (inProgress3+positionTopic2) valid fulfilment for previous: {"from":"dfsp2","to":"dfsp1" ... "payload":{"fulfilment": ...
  - 2. (callbackFinilized2) changed fspiop-source to payer for previous: {"from":"switch","to":"dfsp1" ... "payload":{"fulfilment" ... Payer sending valid fulfilment, but header not validated !!!
  
  > PREPARED NEW TRANSFER <
  - 7. (callbackErrorSourceDoesntMatchPayee) changed fspiop-source to payer for newly prepared: {"from":"switch","to":"dfsp1" ... {"errorCode":3100,"errorDescription":"Generic validation error: fspiop-source does not match payee fsp","extensionList": ...
  - 4+7. (inProgress2+callbackErrorSourceDoesntMatchPayee) repeated previous: {"from":"switch","to":"dfsp1" ... {"errorCode":3100,"errorDescription":"Generic validation error: fspiop-source does not match payee fsp","extensionList": ... same question as 4+8 !!! do we ever need to continue repeated invalid request?
  
  > PREPARED NEW TRANSFER 10000<
  - 10. (callbackErrorNonReservedState) tried to fulfil existing automatically aborted transfer: {"from":"switch","to":"dfsp2" ... {"errorCode":3100,"errorDescription":"Generic validation error: transfer state not reserved"
  - 3. (callbackErrorModified2) repeated previous: {"from":"switch","to":"dfsp2" ... {"errorCode":3106,"errorDescription":"Modified request" !!! Getting different error because "isValid" is false !!! matchedHash is acquired by join on transferFulfilment from previous request, but since for automatically aborted there's no such record we get it !!!
  - 6. (callbackErrorNotFound) tried to fulfil a transfer that does not exist: {"from":"switch","to":"dfsp2" ... {"errorCode":3100,"errorDescription":"Generic validation error: transfer not found"
  - 1. (callbackErrorNotFound2) re-tried previous: {"from":"switch","to":"dfsp2" ... {"errorCode":2001,"errorDescription":"Internal server error: transfer/state not found" !!! now getting internal error, but probably OK
  > PREPARED NEW TO EXPIRE <
  - 10. (callbackErrorNonReservedState) couldn't trigger 11 while TimeoutHandler is running !!!
  - 3. (callbackErrorModified2) getting modified for the same request, same as above !!!
  > DISABLED TimeoutHandler PREPARED EXPIRED <
  - 11. (callbackErrorTransferExpired) tried to fulfil expired transfer, not timed out {"from":"switch","to":"dfsp2" ... {"errorInformation":{"errorCode":3300,"errorDescription":"Transfer expired" ...
  - 4+11. (inProgress2+callbackErrorTransferExpired) repeated previous request: {"from":"switch","to":"dfsp2" ... "errorInformation":{"errorCode":3300,"errorDescription":"Transfer expired" !!! should it validate when duplicate (not detected by select because no transferFulfilment was saved during previous request and not expired by TimeoutHandler yet!)
  > ENABLED TimeoutHandler TO EXPIRE ALL <
  {"from":"dfsp1","to":"dfsp2" ... "errorCode":3300,"errorDescription":"Transfer expired" ...
  - 3. (callbackErrorModified2) retried previous matching hash: {"from":"switch","to":"dfsp2" ... "errorCode":3106,"errorDescription":"Modified request" !!! interrupted before validation because hash exists, but could not detect it as no transferFulfilment was ever saved
```

**Comment by ggrg** [comment]
```
R. reject
  - 12. (positionTopic3) rejected with valid fulfilment: {"from":"dfsp2","to":"dfsp1" ... "payload":{"fulfilment": ...
  - 2. (callbackFinilized2) repeated previous: {"from":"switch","to":"dfsp2" ... "payload":{"transferState":"ABORTED" ... fulfilment is not returned with the callback !!! but everything else looks right
  - 5+10. (inProgress3+callbackErrorNonReservedState) tried same transferId, but without fulfilment: {"from":"switch","to":"dfsp2" ... {"errorCode":3100,"errorDescription":"Generic validation error: transfer state not reserved" ...
  - 3. (callbackErrorModified2) repeated previous: {"from":"switch","to":"dfsp2" ... {"errorCode":3106,"errorDescription":"Modified request" ... !!!
  -5+8. (inProgress3+callbackErrorInvalidFulfilment) tried same transferId, with invalid fulfilment: {"from":"switch","to":"dfsp2" ... {"errorCode":3100,"errorDescription":"Generic validation error: invalid fulfilment" ...
  - 3. (callbackErrorModified2) repeated previous: {"from":"switch","to":"dfsp2" ... {"errorCode":3106,"errorDescription":"Modified request" ... !!!
  - 6. (callbackErrorNotFound) call with unknown transferId: {"from":"switch","to":"dfsp2" ... {"errorCode":3100,"errorDescription":"Generic validation error: transfer not found" ...
  - 1. (callbackErrorNotFound2) repeated previous: {"from":"switch","to":"dfsp2" ... {"errorCode":2001,"errorDescription":"Internal server error: transfer/state not found" !!! different from previous
```

**Comment by ggrg** [comment]
```
A. abort
  - 12. (positionTopic4) successful abort: {"from":"dfsp2","to":"dfsp1" ... {"errorCode":"5101","errorDescription":"Payee transaction limit reached2"} ...
  - 2. (break) repeated previous: no callback as per design !!!
  - 5. (breakModified2) modified previous: no callback as per design !!!
  - 3. (breakModified1) repeated previous: no callback as per design !!!

  > TRIED ABORT FOR NON-EXISTING TRANSFERID <
  Resulted in unhandled rejection because insert in transferErrorDuplicateCheck fails because of FK to transfer.transferId !!!
```

**Comment by ggrg** [comment]
```
G. getTransfer
  4. (callbackMessage) successful get from payer/payee
  1. (breakParticipantDoesntExist) no callback for non-existing fsp
  2. (callbackErrorNotTransferParticipant) get from 3rd party: {"errorCode":3208,"errorDescription":"Provided Transfer ID was not found on the server."} !!! inappropriate error message
  3. (callbackErrorTransferNotFound) could not be triggered because 2 happens first !!!
```

**Comment by ggrg** [comment]
Could not trigger `callbackErrorInvalidEventAction` from `fulfil` method.
Need to discuss scenarios marked with `!!!`

**Comment by ggrg** [comment]
```
=============================== Coverage summary ===============================
Statements   : 94.61% ( 2968/3137 )
Branches     : 89.99% ( 692/769 )
Functions    : 97.92% ( 423/432 )
Lines        : 94.63% ( 2943/3110 )
================================================================================

1..1128
# tests 1128
# pass  1128

# ok
```
