### ISSUE TITLE
[TTK] modify mongoDB configuration to use explicit configs instead of uri

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3130]
## **Goal**:
`As a` Hub deployers

`I want to` have each mongoDB client config seperately configurable
  
`so that` I can utilise externalised secrets

**Acceptance Criteria**:
- [x] Mongo DB URI is split into individual config options
- [x] Password can be set with env variable

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] MongoDB configuration is configrable by seperate configs for ~~host, port, user, database,~~ password
- [x] Each of the MongoDB configuration that is configrable by seperate configs for ~~host, port, user, database,~~ password can be set via environmental variables, and will override any file configs

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/237

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3130?planning-poker) with Zenhub @kleyow @vijayg10 @mdebarros @PaulGregoryBaker @sri-miriyala
