### ISSUE TITLE
[Bulk-API-Adapter] modify mongoDB configuration to use explicit configs instead of uri 

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3131]
## **Goal**:
`As a` Hub deployers

`I want to` have each mongoDB client config seperately configurable
  
`so that` I can utilise externalised secrets

**Acceptance Criteria**:
- [x] MongoDB configuration is configrable by seperate configs for host, port, user, database, password
- [x] Each of the MongoDB configuration that is configrable by seperate configs for host, port, user, database, password can be set via environmental variables, and will override any file configs

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Split URI config into explicit parts.

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
