### ISSUE TITLE
TTK - ability to specify the test collection name when selecting multiple files to execute

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3133]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` pass a proper name of the test case template
  
`so that` I can have proper name in the reports

**Acceptance Criteria**:
~~- [ ] Test collection name can be provided in master.json~~
- [x] TTK UI should pass the name in test case template when concatenating the test cases
- [x] TTK CLI should pass the name in test case template when concatenating the test cases

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Update TTK UI to pass customized name
- [x] Update TTK client to pass customized name

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit-client-lib/pull/6
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/171

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
