### ISSUE TITLE
[Central-Event-Processor] modify CEP to support env vars injection overides

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3134]
## **Goal**:
`As a` Hub Deployer

`I want to` have the CEP to support env vars injection overides
  
`so that` that we can inject secrets on Kubernetes/Docker deployments for passwords

**Acceptance Criteria**:
- [ ] CEP configs can be overriden by env vars

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
After consultation with Director, Mojaloop Product Strategy  (Paul Makin) and current implementer(s), this has been deprioritized for v15 because of lack of automated tests (to be run during releases, maintenance); The service itself can be included in Mojaloop releases once automated tests are provided and any tech-debt (at the time of inclusion) addressed..
