### ISSUE TITLE
Update the Payment Manager on-premise deployment to use latest releases of SDK

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3136]
## **Goal**:
`As a` System Integration 
`I want to` deploy a local version of Payment Manager and TTK
`so that` develop a core-connector against this environment

Note: 
The update of Payment Manager UI is not a requirement for this work, as there may be Kubernetes dependencies; in which case they cannot be run in the docker compose setup. 

**Acceptance Criteria**:
Verify the the OnPremise docker compose supports the latest versions of
   - [x] TTK
   - [x] SDK Scheme Adapter
- [x] Verify that the readme documentation is updated/ still current with the new components.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Test the branch `release/v2.0.0` which has an open PR. Merge it to master after fixing if there are any issues.
- [x] Update SDK to latest version
- [x] Try updating the remaining services to latest versions
- [x] Update the README file and include some documentation regarding core connector development and testing.

**Done**
- [x] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/pm4ml/on-premise-deploy/pull/11
- [x] https://github.com/pm4ml/on-premise-deploy/pull/12

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
