### ISSUE TITLE
[thirdparty-auth-svc] modify database configuration to support env var overrides

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3139]
## **Goal**:
`As a` Hub Deployer

`I want to` have the Thirdparty Auth Svc to support env vars injection overides
  
`so that` that we can inject secrets on Kubernetes/Docker deployments for passwords

**Acceptance Criteria**:
- [x] Thirdparty Auth Svc Database configs can be overriden by env vars
- [x] MySQL configuration is configrable by seperate configs for host, port, user, database, password

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

Notes:
- Option to replace the existing library(config) with the library (new standard) we use in other places (convict)

---

**Tasks**:
- [x] Audit and dependency updating and resolving
- [x] Add env configuration to convict config

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [ x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/auth-service/pull/132

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
