### ISSUE TITLE
Deploy FX converter (core connector) in IaC and test the p2p transfer with different currencies

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3140]
## **Goal**:
`As a` Mojaloop Community member interested in a Rafiki cross-board cross-currency system
`I want to` have a demonstrate and perform a proof of concept on this use case
`so that` I can validate the technology for this use-case design

**Acceptance Criteria**:
- [x] Verify that FX core connector is deployed to an IaC payment manager deployed environment.
- [x] Verify that a happy path p2p transfer is tested with different currencies

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Prepare Helm Chart
- [x] Deploy it manually in IaC PM4ML
- [x] Configure endpoints in PM4ML services properly to use FX converter
- [x] Test a transfer and observe the logs in BOF, PM4ML portals ...etc

**Done**
- [x] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/fx-converter-template

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
https://user-images.githubusercontent.com/33152110/224052892-7acc03b3-465a-485b-99bd-c6a12f69f4d8.mp4
