### ISSUE TITLE
Initial Rafiki cross-board cross-currency system demonstration

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3142]
## **Goal**:
`As a` Mojaloop Community member interested in a Rafiki cross-board cross-currency system
`I want to` have a demonstrate and perform a proof of concept on this use case
`so that` I can validate the technology for this use-case design

Rafiki cross-board cross-currency system design:
![image.png](https://images.zenhubusercontent.com/5e183e2ce04060bca2d941ba/ee9093df-7d80-46fa-babe-0dbde3db8639)

Demonstration design:
![image.png](https://images.zenhubusercontent.com/5e183e2ce04060bca2d941ba/51633a2a-4cf2-4dcf-b0e0-f571cd551309)

Notes: 
The demonstration configuration will make use of 3 TTKs and 2 Payment Managers.
1. TTK to simulate the Rafiki backend.
2. Cross-network provider will be composed of Payment Manager and a custom built core connector that additionally performs the FX conversions.
3. TTK to simulate Mojaloop in hub mode
4. Payment manager simulating the disbursement bank. The design include a core connector that adapts to the IsisPlus APIs. This adapter will not be included in the initial demonstrations but designs so this can be included in the next phase.

The demonstration will use docker-compose to stand up the components necessary. The Docker-compose will support three profiles that are necessary for subsequent demonstration phases.
   1. Full end to end TTK simulation [CNP TTK - CNP PM4ML - Mojaloop TTK - Payee PM4ML - ISISPlus TTK]
   2. CNP and Mojaloop Simulation [CNP TTK - CNP PM4ML - Mojaloop TTK - ]
   3. CNP Simulation [CNP TTK - CNP PM4ML - ]

The demonstration will use a modified mobile simulator to illustrate the:
1. Payer Initiating the transfer
2. FX performed
2. Payee receiving of the funds 

**Acceptance Criteria**:
- [ ] Verify that the demonstration implements the outlined demonstration design
- [ ] Verify that a Docker-Compose file is produced that runs 3 TTK's and 2 PM4MLs. The cross currency PM4ML needs to deploy the Rafiki Cross currency and cross boarder core connector demonstrator.
- [ ] Verify that the three docker-compose profiles are supported
- [ ] Verify that the CNP's TTK mobile demonstration is modified to illustrate the FX conversion and the acknowledgement/ agreement messages
 

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
