### ISSUE TITLE
Build an FX converter (core connector)

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3143]
## **Goal**:
`As a` Mojaloop Community member interested in a Rafiki cross-board cross-currency system
`I want to` have a demonstrate and perform a proof of concept on this use case
`so that I` can validate the technology for this use-case design

Note:
This FX connector support the backend SDK APIs as both inbound and outbound APIs. This effectively makes this component optional as it can be left out of a deployment.
If an incoming transaction request is in a currency that is configured for FX conversion, then all output amounts will be converted into the destination currency. If incoming transaction request are not configured for FX conversion, then these amounts will be passed through the FX core connector as is. All amounts being returned through the FX core connector will be converted in reverse of the incoming amount conversions.

**Acceptance Criteria**:
- [x] Verify that the FX core connector supports FX currency conversions based off a configured hardcoded fixed FX rate
- [x] Verify that the Hub fees are supported and visible in the APIs
- [x] Verify that the receive bank fees are supported and visible in the APIs

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Build FX converter with two http server interfaces
- [x] Add currency conversion logic (hardcoded function with downloaded FX rates)
- [x] Test with TTK
- [x] Test with SDK and TTK
- [x] Prepare dockerfile and setup CICD to publish docker image
- [x] Test a transfer

**Done**
- [x] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/fx-converter-template/releases/tag/v0.1.1

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
