### ISSUE TITLE
Customise Mobile simulator for the Cross Network Provider demonstration UI

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3144]
## **Goal**:
`As a` Mojaloop Community member interested in a Rafiki cross-board cross-currency system
`I want to` have a demonstrate and perform a proof of concept on this use case
`so that I` can validate the technology for this use-case design

Customise TTK mobile simulator page according to the use-case for the demo

**Acceptance Criteria**:
- [ ] Verify that the TTK Mobile simulator page has been customised to support the Cross network Provider (Rafiki - Cross boarder- Cross currency)
- [ ] Verify that FX conversions are visible
- [ ] Verify that FX fees are visible
- [ ] Verify that Rafiki fees are visible

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
It was decided not to do this demo customisation
