### ISSUE TITLE
Final Configures to support end-to-end demonstration

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3145]
## **Goal**:
`As a` Mojaloop Community member interested in a Rafiki cross-board cross-currency system
`I want to` have a demonstrate and perform a proof of concept on this use case
`so that I` can validate the technology for this use-case design

Note:
Configure a receiver side mobile app simulator to show the inbound transfer notifications and prepare an end to end transfer demo

**Acceptance Criteria**:
- [ ] Verify that the receiver side mobile app simulator shows the inbound transfer notification 
- [ ] Verify that the end-to-end demonstration is correctly configured.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
