### ISSUE TITLE
IaC version to support Mojaloop v15.0.0

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#3147]
## **Goal**:
`As a` Hub operator
`I want to` deploy the latest version of Mojaloop (Mojaloop v15.0.0) using IaC
`so that` I can take advantage of the new features, enhancements and bug fixes in the latest release

**Notes:** 
Secret management will be done as follow:
(To keep random generated passwords from terraform as these get stored in state file; Instead use custom resources to generate passwords)
 - install operators in Vault to generate random passwords and secrets (Red hat operator is the chosen one.)
1. Add support for vault operator (https://github.com/redhat-cop/vault-config-operator) to allow for creation and storing of random secrets in vault as well as CR-generated K8S secrets from these same vault secrets. 
   - Custom Resource (CR) based method to auto generate credentials for the creation of stateful resources (mysql/etc)
   - CR-based creation of K8S secrets in multiple namespaces that can then be referenced in different helm charts.  
   - The auto generation of the vault secrets also means that the secret will not be stored anywhere but in vault as opposed to the current situation where the random passwords are generated in terraform first which results in the pw being stored in terraform state file.
1. Update stateful services to make use of 1 above, includes creation of CRs.
1. Update mojaloop helm install to reference secrets generated from 2 above.

**Acceptance Criteria**:
- [ ] An IaC version that deploys the latest Mojaloop version 15.0.0 is published
- [ ] Golden path and (core) bulk tests are passing on a deployment done by the newly published IaC version
- [ ] Tests for changes in Mojaloop 15.0.0 have been run and pass
- [ ] Third-party tests are run and have 100% pass rate (or known issues documented)
- [ ] SDK bulk tests tests are run and have 100% pass rate (or known issues documented)

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Prepare a values files for v15 by comparing with the values file in helm chart
  - [x] Mojaloop values file
  - [x] Moja Simulator values file
  - [x] TTK values file
- [x] Add a new stateful service for TTK mongoDB
- [x] Align the k8s secrets created by external dependencies to be used in values files instead of secrets
  - [x] Refactor the values files to take password from k8s secrets instead of plain text
- [x] Check if the service name / port changes don't break anything in other parts of IaC
- [x] Check if there are any ingress related changes to be propagated
- [x] Test the deployment in IaC sandbox with a snapshot version
- [x] Confirm tests needed to be run for the new deployment
- [x] Golden path tests run with IaC for v15.0.0
- [x] Fix the issues if any
  - [x] Increase TTK REQUEST TIMEOUT in pm4mlttksim1
  - [x] Fix issue with pm4mlsenderfsp and pm4mlreceiverfsp
- [x] Use IaC to deploy Mojaloop v15.0.0
  - [x] GP tests and Core bulk tests to be run
  - [x] ~Third-party tests (internal) - to be run~ needs to be another story
  - [x] Bulk (sdk) tests - to be run
  - [x] Run Finance portal tests (BOF portal) and document results
  - [x] Run PM4ML UI tests and document results
- [x] Using `helm test` for running tests
- [x] If there are issues debug and create tasks or bugs/stories as needed 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/iac-aws-platform/pull/85

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
