### ISSUE TITLE
Setup a new instance of Mojaloop for fintechs

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#3148]
## **Goal**:
`As a` System Integrator (or potential adopter of Mojaloop)
`I want to` have access to a Mojaloop deployment
`so that` I can explore Mojaloop and potentially deploy my extensions to validate my use-cases and demonstrate that

`As a` Mojaloop community member
`I want to` have access to notes on (blog or docs or recording) deploying Mojaloop using IaC
`so that` I can understand how Mojaloop can be deployed using IaC 

**Acceptance Criteria**:
- [x] A Mojaloop deployment using IaC with the latest stable release of Mojaloop (Mojaloop v14.1.0) is deployed
- [x] The Mojaloop deployment is validated with pass-rate same as the v14.1.0 release
- [ ] Access is provided to System Integrators teams that are approved by the Mojaloop Foundation staff
- [x] Record the setup process to be shared on a blog/post or docs
- [x] Ensure access is restricted to low level secrets to ensure security (document observations to streamline the process later)

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [x] Setup the sandbox
  - [ ] ~Narrow down pm4ml instances needed for P2P (to leave pm4ml instances for SIs)~ (going with default)
  - [ ] ~Identify tests needed based on pm4ml instances deployed~ (going with default)
- [x] Tests / validation needed to ensure functionality works as expected
- [ ] Provide access to
  - [ ] k3s cluster
  - [ ] TTK UIs
  - [ ] Finance portal
  - [ ] pm4ml UIs
  - [ ] GitLab? (view files access)

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3148?planning-poker) with Zenhub @dfry @mdebarros @vijayg10 @sri-miriyala @PaulGregoryBaker
