### ISSUE TITLE
[Central-Ledger] Glob v9.x dependency introduces a license dependency on blue-oak

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3153]
## **Goal**:
`As a` Mojaloop Maintainer

`I want to` investigate if the blue-oak license is compatible with apache-2.0
  
`so that` I can upgrade the Glob dependency on the Central-Ledger service

**Acceptance Criteria**:
- [ ] investigate if the blue-oak license is compatible with apache-2.0
- [ ] validate that the blue-oak license can included in the Mojaloop License Policy with the DA
- [ ] Glob dependency on the Central-Ledger service has been upgraded and audit-license checks pass

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
