### ISSUE TITLE
Build a Rafiki CC (Outbound) against a TTK & PM4ML

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3154]
## **Goal**:
`As a` Mojaloop Community Member Interested in connecting Mojaloop to an Interledger Network
`I want to` have a demonstration Rafiki core-connector
`so that` illustrate how cross-network transactions between Inteledger and Mojaloop would work.

This sequence diagram outlines the integration design, against which the CC will be built.

![Revised Transfer via CNP (4)](https://user-images.githubusercontent.com/33152110/223190140-74f59408-e192-4866-9608-676cbfd9af7a.svg)

**Assumptions**
- the integration will be a rest API that is synchronous 

**Acceptance Criteria**:
- [ ] Verify that the Open API definition that is prepared and represent the agreed interactions is approved by the Interledger foundation.
- [ ] Verify that tests are create and agreed to by the product owner. (happy path)
- [x] Demonstrate that the system can be deployed onto a machine using a docker-compose harness

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Define the openAPI spec based on examples from sequence diagram [@kleyow ]
- [x] Refine the openAPI spec based on the open payments and Rafiki structures [@vijayg10 ]
- [x] Create a repository for the core connector and create scaffolding for handlers [@vijayg10 ]
- [x] Check with Michael about how DfspId will be propagated in quotes request from party response [@vijayg10 ]
- [x] Implement open-payments `incoming-payments` handler, API mappings and conversion [@kleyow ]
- [x] Implement redis cache to maintain the state in CC to store some needed data [@kleyow ]
- [x] Implement rafiki `webhook` inbound handler to execute the final transfer
- [x] Implement the callback to the previously stored URL from `externalRef` field in first API call
- [x] Dockerize the service
- [x] Test it against SDK and TTK or on-premise-deploy stack
- [x] Add happy path TTK functional tests

**Done**
- [x] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-core-connector-rafiki-api-svc

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
Followup story is created after this PoC. Hence closed the story.
https://github.com/mojaloop/project/issues/3167
