### ISSUE TITLE
Rafiki Cross Network Provider POC Deployment

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3157]
## **Goal**:
`As a` Rafiki Developer
`I want to` be able to interact with a client in a Mojaloop Scheme using the Rafiki Mojaloop Interface
`so that` I can demonstrate the ability to transfer funds from a Rafiki system to a Mojaloop Participant

**Acceptance Criteria**:
- [ ] Verify that the Rafiki Core connector is deployed in a Mojaloop Sandbox, and that the functional end to end test passes.
- [ ] Verify that Rafiki tests are built and approved by the product owner to test this use case 
- [ ] Verify that a Rafiki transfer agreed tests pass 

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
