### ISSUE TITLE
Publish a blog that describes Orion's System Journey as a system integrator building a core-connector

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3161]
## **Goal**:
`As a` System Integrator building connections for DFSP Participants into Mojaloop
`I want to` be able to read a blog that describes how other have tackled this
`so that` I take advantages of lessons they learned and can build on their experience

**Note:**
It would good if this read like a case study. I.e. It should describe the problem, and then describe the solution and how the solution addresses the problem.
This blog must become a resource, so it must link to detail descriptions and how to videos to achieve this.

**Acceptance Criteria**:
 - [ ] Verify that a blog is published that describes Orion's Systems journey as system integrators
 - [ ] Verify that on premise development is described
 - [ ] Verify that a testing approach or strategy is described

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Paul continuing discussions with Vijay and Sri - to continue March 24th
