### ISSUE TITLE
Build a new Helm BOF Financial Portal release to include the #3141 bug fix

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3166]
## **Goal**:
`As a` Hub Operator
`I want to` update my financial portal to include a patch
`so that` I can deploy a version with bug #3141

**Acceptance Criteria**:
- [x] Verify the the reporting graphQL has a new release and image
- [x] Verify the the BOF chart's example template has the latest release in it.
- [x] Verify that release notes have been completed
- [ ] Verify that TW are able to release this patch

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

https://github.com/mojaloop/project/issues/3141

**Tasks**:
- [x] Create release for reporting-hub-bop-api-svc
- [x] Update bof and reporting-hub-bop-api-svc charts
- [x] Deploy and validate fix against either oss or sandbox enviorment
- [ ] Support TW in deploying fix

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/charts/pull/82

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by kleyow** [comment]
![image](https://user-images.githubusercontent.com/5932442/226371037-03b16f28-0fb1-4f71-af33-d887a3a14ad6.png)

Tested on OSS enviorment with Mojaloop v15 to validate this tranfser view fix.

```
helm --namespace moja4 install moja4 ./mojaloop -f /home/kleyow/mojaloop/deploy-config/mojaloop/test.mojaloop.live/values-moja4-test-mojaloop-harness-v15.0.0.yaml \
  --set ml-ttk-test-setup.tests.enabled=true \
  --set ml-ttk-test-val-gp.tests.enabled=true \
  --set ml-ttk-test-val-bulk.tests.enabled=true \
  --set ml-ttk-test-setup-tp.tests.enabled=true \
  --set ml-ttk-test-val-tp.tests.enabled=true \
  --set account-lookup-service.account-lookup-service.config.featureEnableExtendedPartyIdType=true \
  --set account-lookup-service.account-lookup-service-admin.config.featureEnableExtendedPartyIdType=true \
  --set thirdparty.enabled=true \
  --set mojaloop-bulk.enabled=true \
  --set ml-ttk-test-val-bulk.tests.enabled=true

helm -n moja4 upgrade backend ./example-mojaloop-backend --install -f /home/kleyow/mojaloop/deploy-config/mojaloop/test.mojaloop.live/values-moja4-test-mojaloop-backend-v15.0.0.yaml
helm -n moja4 install bof-backend mojaloop-charts/backend -f /home/kleyow/mojaloop/deploy-config/mojaloop/test.mojaloop.live/values-moja4-bof-backend.yaml --skip-crds
helm -n moja4 install bof /home/kleyow/mojaloop/charts/mojaloop/bof -f /home/kleyow/mojaloop/deploy-config/mojaloop/test.mojaloop.live/values-moja4-bof.yaml  --skip-crds

```

**Comment by PaulGregoryBaker** [comment]
Aung Thaw Aye from Thisawork acknowledged receiving this release.
Will leave the story open for the remainder of this week to see if any issues arise.
