### ISSUE TITLE
CNP transfer flow refactoring - open-payments based

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3167]
## **Goal**:
`As a` Mojaloop Community Member Interested in connecting Mojaloop to an Interledger Network

`I want to` have a PoC version of CNP
  
`so that` illustrate how cross-network transactions between Inteledger and Mojaloop would work.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Refactor the transfer flow and sequence diagram with new API calls (open-payments only) and payloads [@vijayg10 ]
- [x] Propagate the changes to CNP core connector with new API endpoints and handlers [@vijayg10 ]
- [x] Create a docker-compose stack for local deployment and demos [@vijayg10 ]
- [x] Record a demo [@vijayg10 ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-core-connector-openpayments-api-svc

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
