### ISSUE TITLE
Add secret vault operator to IaC to support Mojaloop v15

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3169]
## **Goal**:
`As a` Mojaloop Community using IaC
`I want to` the IaC to create secrets
`so that` secrets created during the deploy that utilise the Mojaloop release v15

**Acceptance Criteria**:
- [x] Verify that the IaC deploys Mojaloop v15 with secrets that are created during the deployment
- [x] Verify that the secrets are generated inside Kubernetes without any appearing in the deployment logs or terraform state file
- [ ] 

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
1. Add support for vault operator (https://github.com/redhat-cop/vault-config-operator) to allow for creation and storing of random secrets in vault as well as CR-generated K8S secrets from these same vault secrets.
   - Custom Resource (CR) based method to auto generate credentials for the creation of stateful resources (mysql/etc)
   - CR-based creation of K8S secrets in multiple namespaces that can then be referenced in different helm charts.
   - The auto generation of the vault secrets also means that the secret will not be stored anywhere but in vault as opposed to the current situation where the random passwords are generated in terraform first which results in the pw being stored in terraform state file.
1. Update stateful services to make use of 1 above, includes creation of CRs.
1. Update mojaloop helm install to reference secrets generated from 2 above.

- [x] TBD [ @? ]

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [x] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
