### ISSUE TITLE
2.01-1 Design position management - [8]

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#317]
**Goal**:
1. As a contributor
I would like to _design the positions management flow for successful and failed scenarios_ 
so that FSP positions can be managed by the Switch.
2. As a Hub Operator
I want to make sure that _no FSP exceeds their net Debit CAP_
I want to make sure that _the Positions Management facilitates Settlement process that follows_
3. As a DFSP
_I'm not allowed to transact more than the funds I'm allocated to the Mojaloop Switch_

**Tasks**:
- [x] PoC to validate Design approach [@vgenev @bothadeon @shashi165] 
- [x] Create Positions PlantUML Diagram for
  - [x] Position Prepare [@ggrg]
  - [x] Position Fulfil [@rmothilal]
  - [x] Position Abort [@rmothilal]
- [x] Create overall Position PlantUML Diagram
- [x] Create svg files for
  - [x] Position Prepare [@ggrg]
  - [x] Position Fulfil [@rmothilal, @ggrg]
  - [x] Position Abort [@rmothilal]
- [x] Create svg files for the overall Positions Diagram

**Acceptance Criteria**:
- [x] Deterministically recreate position changes against timelines
- [x] Position process captures all the state changes
- [x] This design needs to include the time-outs
- [x] All designs to be reviewed by DA (Review to covered in #341 as they are duplicates right now)
  - [x] Update Position Prepare PlantUML Diagram
  - [x] Update Position Fulfil PlantUML Diagram
  - [x] Update Position Abort PlantUML Diagram

**Dependencies**:
- [ ] Clarity from PO about Settlements/Fulfils updating positions @wdcmb 
- [x] DA

**Accountability**:
- Owner @rmothilal  
- QA/Review Design Authority

**Comment by vgenev** [comment]
1. Single Consumer + Multiple Topics
    a.) Consume in Batches, sort in-to buckets, and prioratise bucket processing.
    b.) Consume in Flow, there is no prioratization here, but because of multiple topics we have a round-robin processing approach. <-- Possible performance issue if batch processing is faster (to be determined). Flow seems to be the most performant.
2. Single Consumer + Single Topic <-- possible delay in prioratization due to a single topic
    a.) Consume in Batches, sort in-to buckets, and prioratise bucket processing. <-- still need to lock the table-rows, but minimal contention on the database
    b.) Consume in flows, there is no prioratization here <-- since we use a single topic, that means that fulfil's could be heavily delayed. Possible performance issue if batch processing is faster (to be determined). Flow seems to be the most performant.
3. Multiple Consumer + Single Topic for each consumer <-- lock tables to ensure data-integrity, with possible database contention
    a.) Consume in Batches, sort in-to buckets, and prioratise bucket processing.
    b.) Consume in flow, there is no prioratization here...but because of multiple topics we have a round-robin processing approach. Possible performance issue if batch processing is faster (to be determined). Flow seems to be the most performant.
Recommendation option in preference: 1. -> 3. -> 2.
Recommendation on Batch vs Flow: Batch (assuming the performance issues can be addressed)
Next steps:
1. Present findings to DA/Team for a decision on the approach
2. Document the final decision
3. Update the design based on the final decision
