### ISSUE TITLE
Design, SDs for patch notifications on failures

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#3172]
## **Goal**:
`As a` Payee FSP

`I want to` know if a 'fulfil request' I sent (a `PUT /transfers/{ID}`) to the switch has failed
  
`so that` I can update my systems with that information and initiate any follow-up actions needed

This story covers the design for this solution (already approved by FSPIOP SIG in [issue#103](https://github.com/mojaloop/mojaloop-specification/issues/103))

Example: https://docs.mojaloop.io/technical/central-ledger/transfers/2.1.0-fulfil-transfer-request.html

**Notes**:
Following the first bullet point here: https://github.com/mojaloop/mojaloop-specification/issues/103#issuecomment-970407712

**Acceptance Criteria**:
- [ ] A sequence diagram showing a PATCH notification to a Payee FSP upon failure of a 'fulfil request' to commit on the Switch
- [ ] Any follow-up notes for implementation are documented

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3172?planning-poker) with Zenhub @vijayg10 @mdebarros @PaulGregoryBaker
