### ISSUE TITLE
[Docs] Update Deployment Guide for Mojaloop Helm v15 Release

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3177]
## **Goal**:
`As a` Mojaloop Deployer

`I want to` have the Deployment Guide updated for v15 Release
  
`so that` I have a Deployment Guide that is "current"

**Acceptance Criteria**:
- [x] Deployment Guide is ported over the VuePress [@kleyow]
- [ ] Deployment Guide is updated for v15 Release [@kleyow / @mdebarros ]
- [ ] v15 Release Notes references the "current" Deployment Guide [@mdebarros]
- [ ] What about testing/verifying the Deployment Guides (i.e. on Linux etc)? [@mdebarros]
- [ ] Local deployment guides deprecated and pre-requisites updated to provide pointers to k8s setup/ installation (external) guides  / instructions [@mdebarros]
- [ ] Update FAQ [@mdebarros]
	- [ ] ARM based Mac support

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Review deployment guide documentation to ensure its up-to-date [@kleyow]
	- [ ] Migrate deployment guide from legacy to main docs folder, update any links from docs/* folder to match the migrated deployment guide
	- [ ] Update deployment guide to reflect externalised DB (ref: https://github.com/mojaloop/helm#deploying-backends-best-practice)
- [ ] Update links in v15 Release Notes to point to current Deployment Guide 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/documentation/pull/409

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3177?planning-poker) with Zenhub @kleyow @PaulGregoryBaker @mdebarros @vijayg10 @sri-miriyala
