### ISSUE TITLE
Show the env name next to the version in the Admin UI

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#3238]
## **Goal**:
`As an` Hub Operator

`I want to` see the environment visible next to the UI version
  
`so that` I know which environment I'm working on

Initial environment names are:
- Production
- Development

**Acceptance Criteria**:
- [ ] See the environment name in the bottom left corner, next to the version

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by aungmonko-tw** [comment]
- Done adding env name next to the version
- Done dev testing

screenshots:
![Prod.png](https://images.zenhubusercontent.com/6426b45ed1502f6341095528/f3c28ef7-d6e2-47ee-81bf-b1fdbb63d8bf)
![Dev.png](https://images.zenhubusercontent.com/6426b45ed1502f6341095528/2396abd5-1b97-4a96-884c-62c41ef49ad4)

@pedrosousabarreto Hi Pedro, I have created a pull request and assigned you as a reviewer. Could you please review it and let me know if any else, thanks.
