### ISSUE TITLE
IaC - Refactor the test pipelines to use helm tests instead of TTK CLI directly

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3239]
## **Goal**:
`As a` TechOps team member deploying Mojaloop

`I want to` use helm tests in IaC test pipeline instead of TTK CLI directly
 
`so that` I don't need to maintain the test pipelines in sync with mojaloop release

**Acceptance Criteria**:
- [x] Test pipelines in IaC related to switch tests are refactored to use helm test
- [x] Test job executions save reports as artifacts in gitlab (download report from helm test and upload to artifacts)
- [x] Test jobs should report proper status based on the exit code
- [x] There should be proper CLI output for test execution result in the console log of the job
- [x] Test collections to include
  - [x] Mojaloop GP provisioning tests
  - [x] Mojaloop GP tests
  - [x] Mojaloop Bulk provisioning
  - [x] Mojaloop Bulk tests
  - [x] Mojaloop third-party provisioning
  - [x] Mojaloop third-party tests
  - [x] Mojaloop bulk-sdk provisioning
  - [x] Mojaloop bulk-sdk tests

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Refactor the tests in IaC pipeline to use helm test
  - [x] Test the helm test is working properly with exit codes and report generation
  - [x] Enable the tests in mojaloop values file in IaC with proper report base URL param
  - [x] Fix the issue with TTK-CLI helm chart for proper container exit code
  - [x] Add the remaining test pipelines for tests mentioned in the above acceptance criteria

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/562
- [x] https://github.com/mojaloop/iac-aws-platform/pull/85

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
