### ISSUE TITLE
2.12 Unit and Integration Testing positions

### ISSUE THREAD

**Issue by nikolayanastasov** [mojaloop/project#324]
**Goal**:
As a developer I would like to _create Unit and Integration tests for positions_ 

**Tasks**:
- [ ] Prepare **Unit tests** for positions
- [ ] Prepare **Integration tests** for positions

**Acceptance Criteria**:
- [ ] Prepare **Unit tests** for positions
- [ ] Prepare **Integration tests** for positions

**Dependencies**:
- None currently

**Accountability**:
- Owner 
- QA/Review

**Comment by elnyry** [comment]
Unit & Integration tests done as part of each separate implementation story and not as an independent story
