### ISSUE TITLE
[Helm] Automated CI Testing on PR Checks

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3241]
## **Goal**:
`As a` Mojaloop Helm Maintainer

`I want to` have automated Helm CI tests excuted on Pull-Requests
  
`so that` Helm changes can be validated against the "latest" available Kubernetes version based on the selected Kubernetes distribution that is certified by the [Cloud Native Computing Foundation (CNCF)](https://www.cncf.io/certification/software-conformance)

**Acceptance Criteria**:
- [ ] On PRs, automated CI checks are executed against a light-weight Kubernetes CNCF certified distribution
    - [ ] Example Mojaloop Backends are deployed
    - [ ] Current branch Mojaloop Helm chart is built and deployed
    - [ ] Helm Tests are executed against the deployment (TBC: WHICH TESTS?)

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
