### ISSUE TITLE
Account Lookup BC - Change the oracle finder only use party type to find oracles

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#3251]
## **Goal**:
`As a` developer

`I want to` remove the usage of party sub type in the Account Lookup internal oracle system; 
  
`so that` the internal oracle system no longer uses party sub type to associate participants

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Setup the NPM publish scripts [ @mdebarros  ]

**Done**
- [x] Acceptance Criteria pass
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
