### ISSUE TITLE
[Security] Support Secure Authentication mechanisms for Redis

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3257]
## **Goal**:
`As a` Mojaloop Deployer

`I want to` have Mojaloop Services with Redis an external Backend support secure authentication mechanism
  
`so that` we ensure secure based access to the external Redis Backends

**Acceptance Criteria**:
- The following services support Redis Authentication
    - [ ] SDK-Scheme-Adapter
    - [ ] Auth-Service

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
