### ISSUE TITLE
[Security] Support Secure Authentication mechanisms for Kafka

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3258]
## **Goal**:
`As a` Mojaloop Deployer

`I want to` have Mojaloop Services with Kafka an external Backend support secure authentication mechanism
  
`so that` we ensure secure based access to the external Kafka Backends

**Acceptance Criteria**:
- The following services support Redis Authentication
     - [ ] central-ledger
     - [ ] ml-api-adapter
     - [ ] sdk-scheme-adapter
     - [ ] bulk-api-adapter
     - [ ] central-event-processor
     - [ ] email-notifier
     - [ ] event-stream-processor
     - [ ] SDK-Scheme-Adapter

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
