### ISSUE TITLE
Introduce DISPUTED state for Batches

### ISSUE THREAD

**Issue by koekiebox** [mojaloop/project#3261]
## **Goal**:
`As a` hub operator

`I want to` dispute a batch, or set of batches for Settlement
  
`so that` a `DISPUTED` batch will be excluded from all settlement matrixes

**Acceptance Criteria**:
- [x] Ability to mark a batch or set of batches as `DISPUTED`
- [x] Domain unit tests are passing and test cases to extensively test disputed functionality
- [x] A new type of settlement matrix that would target specific batches to be disputed
- [x] `SETTLED` batches may not be disputed

**Complexity**: `<Medium>` 

**Uncertainty**: `<Low>` N/A.

---

**Tasks**:
The statuses for a batch is currently:
- `OPEN` : Batch may still receive transfers
- `CLOSED`  : A batch has been closed and settled
A new status needs to be introduced to mark a batch as `DISPUTED`.
When a batch is in dispute, it may not be considered as part of the settle-able balance for a settlement matrix.

A type of matrix request needs to be generated in order to dispute batches.
`SETTLED` batches are not allowed to be disputed.

## Background:
Please see: https://github.com/mojaloop/mojaloop-specification/issues/117

**Done**
- [x] Tests coverage is adequate

## **Pull Requests**:
https://github.com/mojaloop/settlements-bc/pull/5

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @koekiebox 
- QA/Review: @pedrosousabarreto
