### ISSUE TITLE
Updated Settlement Domain Unit test logic

### ISSUE THREAD

**Issue by koekiebox** [mojaloop/project#3262]
## **Goal**:
`As a` developer

`I want to` update domain unit tests
  
`so that` settlement logic is tested extensively

**Acceptance Criteria**:
- [x] Tests coverage is adequate
- [x] Domain unit tests are passing

**Complexity**: <Medium> > Re-testing for updated `aggregate.ts`

**Uncertainty**: <Low> > No comment.

---

**Tasks**:
- [x] create settlement transfer and ensure meta-data is present
- [x] create settlement transfer and ensure batch allocation is correct based on settlement model
- [x] test exceptions/errors responses for create transfer (validations)
- [x] request and execute a settlement matrix
- [x] ensure executed matrix cannot be executed again
- [x] ensure batch seq increments for batches within the same period
- [x] batch accounts unique per batch and participant-id
- [x] matrix re-calculate logic

**Done**
- [x] Tests coverage is adequate
- [x] Domain unit tests are passing

## **Pull Requests**:
https://github.com/mojaloop/settlements-bc/pull/4/files

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @koekiebox 
- QA/Review: @pedrosousabarreto
