### ISSUE TITLE
Split the closing of a Settlement Matrix in order to close a matrix without settling at the same time

### ISSUE THREAD

**Issue by koekiebox** [mojaloop/project#3265]
## **Goal**:
`As a` hub operator

`I want to` be able to `CLOSE` a batch 
  
`so that` a batch may be closed without actioning the settling action, which will allow a hub operator to alternatively dispute a `CLOSED` batch

**Acceptance Criteria**:
- [ ] Refactor `closeSettlementMatrix` to only mark batches as `CLOSED` and not perform the settlement action
- [ ] Introduce `executeSettlementMatrix` which will mark batches for a matrix as `CLOSED` and `SETTLED` (perform the settlement action)
- [ ] Add domain unit tests to cover the above scenarios
- [ ] Introduce negative test cases

**Complexity**: `<Medium>` 

**Uncertainty**: `<Low>` N/A.

---

**Tasks**:
Currently when `closeSettlementMatrix(secCtx: CallSecurityContext, id: string): Promise<void> {` function is invoked, the settlement batches will be closed as well as the settling process kicked off.
Instead, the `closeSettlementMatrix(secCtx: CallSecurityContext, id: string): Promise<void> {` should only `CLOSE` the batches for a matrix.

A new function called `executeSettlementMatrix(secCtx: CallSecurityContext, id: string): Promise<void> {` should be introduced, which should:
* Close any of the `OPEN` batches for the matrix
* Process the settling for the batches

## Background:
Please see: https://github.com/mojaloop/mojaloop-specification/issues/117

**Done**
- [ ] Tests coverage is adequate

## **Pull Requests**:
https://github.com/mojaloop/settlements-bc/pull/6

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @koekiebox 
- QA/Review: TBD
