### ISSUE TITLE
[rep-events-processor-svc] MONGO_DB_URI env conf does not support special characters

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3268]
**Summary**:

Bof `reporting-events-processor-svc` service does not support special characters when configuring the username & password for CENTRAL_LEDGER_DB_URL env conf.

**Severity**:
High

**Priority**:
Critical

**Expected Behavior**

The `reporting-events-processor-svc` service should support special character on both the username and password when setting the CENTRAL_LEDGER_DB_URL env variable

**Steps to Reproduce**
n/a

**Specifications**
  - Component (if known): reporting-events-processor-svc
  - Version: v1.1.0
  - Platform:
  - Subsystem:
  - Type of testing: n/a
  - Bug found/raised by: @dfry 

**Pull Requests**:
- [x] https://github.com/mojaloop/reporting-events-processor-svc/pull/11
- [x] https://github.com/mojaloop/charts/pull/85
- [ ] https://github.com/mojaloop/reporting-events-processor-svc/pull/12

---

**Tasks**
- [x] Migrate config to convict
- [x] Add support for Central-Ledger DB configuration for separate params, with env var overrides:
    - host
    - port
    - user
    - password
- [x] Update unit, integ, etc to support the above configurations
- [x] Update function tests, docker-compose, etc to support the above configurations
- [x] Publish Docker release
- [x] Update Helm charts configuration to support the above changes
- [x] Publish Helm chart release

**Comment by mdebarros** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3268?planning-poker) with Zenhub @PaulGregoryBaker @vijayg10
