### ISSUE TITLE
3.02 Design Settlement Window Closure API

### ISSUE THREAD

**Issue by nikolayanastasov** [mojaloop/project#327]
**Goal**:
1. As a developer
I would like to _Design Settlement Window Closure API_ 
2. As a Hub Operator
I want an API to call
so that I can _close the current Settlement window (by incrementing the window number)_

**NOTES**:
- Update the Settlement window number incrementally
- If a Design First approach is used, as part of acceptance criteria there needs to be an updated/new Swagger definition

**Tasks**:
- [x] Design Settlement Window Closure API  [@vgenev @bothadeon]
- [x] PoC for the Open API hapi? [@vgenev @bothadeon]
  - [x] make central-ledger/admin swagger JSON work without errors [@vgenev @bothadeon]
  - [x] create code framework with the swaggerize command-line tool from the above file [@vgenev @bothadeon]
  - [x] connect the current central-ledger database to the framework created from the above task  [@vgenev]
  - [x] update the data access model and handler for one endpoint into the framework built by the tested tool [@vgenev]
  - [x] investigate how the authorization works in the tested framework [@vgenev]
  - [x] investigate the pre-built by the tested tool test framework [@vgenev  @bothadeon]
  - [x] document the process from the above [@vgenev]
- [x] create stories for building a service for the Settlement Window API, using the design first approach and Hapi-OpenAPI plugin - _done during the grooming session with the team_[@vgenev @bothadeon]

**Acceptance Criteria**:
- [x] A design for Settlement Window Closure API is available
- [x] The Data Model to record the windows will be available and has below details:
  - [x] Window number
  - [x] Timestamp
  - [x] Authorization
- [x] Stories for implementation of above design are available

**Dependencies**:
- [ ] #333

**Accountability**:
- Owner  @vgenev
- QA/Review

**Comment by vgenev** [comment]
the POC code is available here: https://github.com/vgenev/openapi-poc
and the documentation, still WIP, is available here: https://github.com/vgenev/openapi-poc/blob/master/how-to-use-hapi-openapi.md
