### ISSUE TITLE
Daily cron job is failing

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#3274]
**Summary**:
Daily cron job (3rd Apr 2023) that runs Mojaloop GP tests (on v15) has two failures and the test result (attached) shows 500 socket hangup on a test [POST /scenarios testfsp1 -> testfsp2 b2b SEND [89.00 TZS]

Test result [here](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-tmp_test_cases_testing-toolkit-test-cases-15.0.0_collections_hub_golden_path-2023-04-03T08%3A03%3A28.944Z.html#pills-requests)

**Severity**:
Low

**Priority**:
Low

**Expected Behavior**
The daily cron job that runs GP tests passes 100%

**Steps to Reproduce**
  1. Daily cron job runs on a Mojaloop deployment and produces result
  2. Verify the results to view the failures
  3. Result showing `500 - socket hang up` on the test `[POST /scenarios testfsp1 -> testfsp2 b2b SEND [89.00 TZS]`, but the reproducibility of the issue remains to be seen, this may be intermittent

**Specifications**
  - Component (if known): Cron job running ML GP tests against an ML core deployment (non-iac deployment)
  - Version: v15.0.0
  - Platform: AWS
  - Subsystem: GP tests (and TTK)
  - Type of testing: daily cron job, automated
  - Bug found/raised by: @elnyry-sam-k 

**Notes**:

- Severity when opened: Low
- Priority when opened: Low

---

**Tasks**:
- [x] Investigate env
- [x] Document findings
- [x] Create any follow-up stories/issues as required 
- [x] Investigate `DiskPressure` issue
    - [x] Document recommendations
    - [x] Re-configure Moja1 to enable persistent storage
    - [x] Deploy Moja1 with persistent storage enabled <-- this is failing, see comments below
    - [x] Investigate k8s cluster log rotations
    - [x] Provide recommendations for k8s Cluster log rotation
    - [x] Set k8s Cluster log rotation configurations
    - [x] Investigate AWS EBS persistentVolumeClaim not provisioning issue
    - [x] Document findings and provide recommendations for AWS EBS persistentVolumeClaim not provisioning issue
        - [x] Install AWS EBS CSI Log driver
        - [x] Re-deploy Moja1 backend's with persistent storage enabled
- [x] Re-run tests to verify issue resolution and see if socket hang-up can be re-produced

**Comment by PaulGregoryBaker** [comment]
Particularly hard to debug. 
Need more investigation before this can be sized.

**Comment by mdebarros** [comment]
Unable to reproduce the 500 socket hangup on a test.

Daily Cron-jobs are currently failing due to disk space, with a screenshot showing the issue on one of our cluster nodes:

![image](https://github.com/mojaloop/project/assets/11392873/cadf2822-caa4-4566-a593-d944bd55f2c0)

![image](https://github.com/mojaloop/project/assets/11392873/8b6669c3-c4de-4387-9d3d-83e28bcd6262)

Undeploying the Mojaloop Backend components, reduced disk usage by nearly 50%.

There are two likely causes for this issue:

1. Logs are NOT being rotated <-- After some investigation, I determined that the logging driver being used is the [json-file driver](https://docs.docker.com/config/containers/logging/json-file/#options):


![Screenshot 2023-05-18 at 19 23 22](https://github.com/mojaloop/project/assets/11392873/72ae430e-1999-4d36-af5b-9a66f1e7a42c)

This by default does not have a "max-size". We need to either ensure that the "max-size" is set to something that is more manageable going forward.

2. Deploy Mojaloop backend dependencies using persistence storage for long-standing deployments, i.e. moja1 environment that is deployed to run a daily cron-job for an extended period of time. This will ensure that any Datastores (i.e. Kafka, MySQL, Redis, MongoDB, etc) will have dedicated and ample storage without impacting the ephemeral local storage on our Kubernetes nodes.

After attempting to provision EBS volumes on Rancher, I discovered that it was no longer working due to upgrading more recent Rancher versions. After some research, I have determined that Rancher no longer supports AWS EBS storage out-of-box, as we now need to configure/install the [aws-ebs-csi-driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/install.md).

**Comment by mdebarros** [comment]
> 2. Deploy Mojaloop backend dependencies using persistence storage for long-standing deployments, i.e. moja1 environment that is deployed to run a daily cron-job for an extended period of time. This will ensure that any Datastores (i.e. Kafka, MySQL, Redis, MongoDB, etc) will have dedicated and ample storage without impacting the ephemeral local storage on our Kubernetes nodes.
> 
> After attempting to provision EBS volumes on Rancher, I discovered that it was no longer working due to upgrading more recent Rancher versions. After some research, I have determined that Rancher no longer supports AWS EBS storage out-of-box, as we now need to configure/install the [aws-ebs-csi-driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/install.md).
> 
> ![Screenshot 2023-05-18 at 19 32 24](https://user-images.githubusercontent.com/11392873/239330396-b2e765d2-069f-4a5c-8d8a-c1261141411c.png)

The issue was resolved by executing the following Helm installation for the [aws-ebs-csi driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/install.md#helm):

```bash
helm repo add aws-ebs-csi-driver https://kubernetes-sigs.github.io/aws-ebs-csi-driver
helm repo update
helm upgrade --install aws-ebs-csi-driver \
    --namespace kube-system \
    aws-ebs-csi-driver/aws-ebs-csi-driver
```

![Screenshot 2023-05-19 at 14 07 42](https://github.com/mojaloop/project/assets/11392873/fd6effbe-8178-4cf1-9bad-bf74602c6e3d)

**Comment by mdebarros** [comment]
So far the following failures have occurred:

1. Insufficient Liquidity (issue to address this going forward -> https://github.com/mojaloop/project/issues/3357)
- https://mojaloop.slack.com/archives/CG3MAJZ5J/p1684829029591579
- https://mojaloop.slack.com/archives/CG3MAJZ5J/p1684829760272269

2. GP Tests failing on first run when upgrading from v14.1.1 to v15 due to WS issues between TTK and SDKs  (known issue --> https://github.com/mojaloop/project/issues/3357)
- https://mojaloop.slack.com/archives/CG3MAJZ5J/p1684839469352009
