### ISSUE TITLE
3.03 Design the Settlements API

### ISSUE THREAD

**Issue by nikolayanastasov** [mojaloop/project#328]
**Goal**:
As a Hub Operator
I would like to acknowledge that a participant FSP has successfully settled their account
so that we can I can allow them to continue transacting; so that I know that we are not liable.

**Tasks**:
- [x] Design an API for Settlements (POST) [@bothadeon @vgenev]
- [x] Design acknowledgement from settlement bank (? PUT:: /settlements/{settlementId}/participants [@bothadeon @vgenev] )
- [x] Design for Position update trigger (GET) [@bothadeon @vgenev]
- [x] Swagger API defined [@bothadeon @vgenev]
  - [x] Add filtering based on DFSP
- [x] Generate placeholders using hapi [@bothadeon @vgenev]
  - [x] Unit tests [@bothadeon @vgenev]
- [x] Minimum code coverage 90%  [@bothadeon @vgenev]

 

**Acceptance Criteria**:
- [x] A Swagger specification for Settlements API is defined that
  - [x] Fetch a Settlement by an ID
  - [x] Create a Settlement using multiple Settlement windows
  - [x] Query Settlements
    - [x] Filtering based on a DFSP
    - [x] Based on Settlement window ID
    - [x] Time period
   - [x] position update to be triggered, based on a Settlement confirmation is available
- [x] Along with the Swagger API, placeholder code using hapi is generated
- [x] Swagger API includes resource to receive confirmation of Settlement

**Dependencies**:
- [x] #327 

**Accountability**:
- Owner [@bothadeon]
- QA/Review

**Comment by mdebarros** [comment]
@vgenev @bothadeon where is the PR for this story?
