### ISSUE TITLE
InteropBC - Consume and handle error events from account-lookup, quoting and transfers BCs

### ISSUE THREAD

**Issue by ruirochawork** [mojaloop/project#3282]
## **Goal**:
`As a` huboperator

`I want to` handle all error events in the interop
  
`so that` the feedback gets sent to the correct receiver

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
