### ISSUE TITLE
3.04 Design acknowledgement from Settlement bank, plus position update trigger

### ISSUE THREAD

**Issue by nikolayanastasov** [mojaloop/project#329]
**Goal**:
As a Hub Operator
I would like to _acknowledge that a participant FSP has successfully settled their account_
so that we can we can allow them to continue transacting so that we know that we are not liable.

**Tasks**:
- [ ] Design acknowledgement from settlement bank (? PUT:: /settlements/{settlementId}/participants )
- [ ] Design for Position update trigger
- [ ] Define Swagger API
- [ ] Generate placeholder code
- [ ] Unit tests

**Acceptance Criteria**:
- [ ] Swagger API to receive confirmation of Settlement is designed with placeholder code
- [ ] Design for a position update to be triggered, based on a Settlement confirmation

**Dependencies**:
- None currently

**Accountability**:
- Owner 
- QA/Review

**Comment by elnyry** [comment]
Included in #328 now
