### ISSUE TITLE
Define Data Analytics and Reporting technology requirements

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#33]
**Goal**:
As a developer I would like to define the Data Analytics and Reporting technology requirements so that I can decide on a solution that satisfies HA, scalability and performance

**Tasks**:
- [ ] 

**Acceptance Criteria**:
- [ ] Define and Document the requirements for HA
- [ ] Define and Document the requirements for HS
- [ ] Define and Document the requirements for Performance
- [ ] Define and Document event processing requirements
- [ ] Define and Document the requirements for Reporting
- [ ] Define and Document the requirements for Data Ingestion

**Dependencies**:
- None currently

**Comment by HenkKodde** [comment]
Take note of #80  - needs to complement and enable business requirements.
