### ISSUE TITLE
2.06 Design an API to manage NET DEBIT CAP

### ISSUE THREAD

**Issue by nikolayanastasov** [mojaloop/project#330]
**Goal**:
1. As a developer
I would like to _Design the Position API to manage NET DEBIT CAP_
so that FSPs net debit cap can be managed (/updated)
2. As a Hub Operator
I need to _reflect on the fact that an FSP has provided more/less collateral so that they can continue to transact_

**Tasks**:
- [x] Design the Position API to manage NET DEBIT CAP for updates [@bothadeon @vgenev @NicoDuvenage]
  - [x] inserts ? [ @NicoDuvenage ]
- [x] Table for participant limit lock (discuss) [ @NicoDuvenage ]
- [x] Update Position Handler design to cater for position validations needing to wait for any updates of the net debit CAP to be updated first. [ @NicoDuvenage ]
- [x] Design the message (DM) that would be part of this [@bothadeon @vgenev @NicoDuvenage]
- [x] Swagger 2.0 YAML API Design [@bothadeon @vgenev @NicoDuvenage]

**Acceptance Criteria**:
- [x] Design for an API to manage NET DEBIT CAP is available to allow for net debit CAP to be updated for a specific FSP
- [x] Existing Position Handler updated to ensure that position validations need to wait for any updates of the net debit CAP to be updated first

**Dependencies**:
- None currently

**Accountability**:
- Owner @NicoDuvenage
- QA/Review

**Comment by elnyry** [comment]
Moved 28 points (#340 , #353 , #355, #356 ) into 3.1 so moving this to 3.2 to accommodate for that
