### ISSUE TITLE
Complete mode to run Central-Ledger TigerBeetle mode ON without any duplicated data

### ISSUE THREAD

**Issue by koekiebox** [mojaloop/project#3301]
Complete mode to run Central-Ledger TigerBeetle mode ON without any duplicated data (analyse impact on Central-Ledger Transfer tables)

![central-ledger-schema-bigtick.png](https://images.zenhubusercontent.com/6156fc32c26db0e5777fab42/3b4bc133-d3d2-4e7c-9116-636df21143b1)

# Tasks to complete:
- [x] Replace internal TB in central-image with `docker-compose` setup and execute
- [x] Add health checks for `docker-compose` in order for `wait-4-docker` to check TB health status
- [x] Add TB init and shutdown hooks for all integration test cases
- [x] Simplify TB integration account creation (make use of `participant=account.user_data` and `participantCurrency=account.id`) instead of account id derivation
- [x] Add function to perform DNS lookups (TB does not currently support DNS lookups for the NodeJS client)
- [x] Add TB mode only tables for storing ILP packet, condition and fulfilment
- [x] Add TB mode only tables for storing transfer extensions
- [x] Add `tb#lookupTransferMapped` in order to convert TB transfer to MJL format
- [x] Add `tb#lookupAccountMapped` in order to convert TB `participantCurrency` to MJL format (and for DC/CR position balance)
- [ ] Implement timeout status check for transfer (requires lookup of Transfer via `transfer.pending_id`) _temporary workaround to be supplied here (until TB release in July2023)_. Function should look at flags to determine if the transfer was a void or a post (return status), options include: voided/posted/none (no action yet)
- [x] Port `facade#getById` enable TB mode only and respective test cases
- [x] Port `transferDuplicateCheck` enable TB mode only and respective test cases
- [x] Port `transferFulfilmentDuplicateCheck` enable TB mode only and respective test cases
- [x] Port `facade#getByIdLight` enable TB mode only and respective test cases
- [x] Port `facade#getAll` enable TB mode only _(low priority)_ `NOT GOING TO IMPLEMENT` - Limitation.
- [x] Port `facade#getTransferInfoToChangePosition` enable TB mode only _(disable due to TB auto position)_
- [x] Port `facade#savePayeeTransferResponse` enable TB mode only
- [x] Port `facade#saveTransferPrepared` enable TB mode only
- [x]  Port `facade#getTransferStateByTransferId` enable TB mode only (Only `pending/posted/voided`), no need for a state machine
- [ ]  Port `facade#timeoutExpireReserved` enable TB mode only. Require listing of expired transfers. 
- [x]  Port `facade#transferStateAndPositionUpdate` enable TB mode only
- [x]  Port `facade#reconciliationTransferPrepare` enable TB mode only - part of funds in
- [x]  Port `facade#reconciliationTransferReserve` enable TB mode only - part of funds in
- [x]  Port `facade#reconciliationTransferCommit` enable TB mode only - part of funds in
- [x]  Port `facade#reconciliationTransferAbort` enable TB mode only - part of funds in
- [x]  Port `facade#recordFundsIn` enable TB mode only - part of funds in
- [x]  Port `facade#getTransferParticipant` enable TB mode only
- [x] Update caller clients to be compatible with TB mode only (☝️)
- [x] Update integration tests to pass with TB+DB mode on

## Relates to:
https://github.com/mojaloop/project/issues/3300

## PR:
https://github.com/mojaloop/central-ledger/pull/956
