### ISSUE TITLE
Update the internal PM4MLs IaC default values to use test currencies

### ISSUE THREAD

**Issue by chris-me-law** [mojaloop/project#3303]
## **Goal**:
`As a` 
`I want to`
`so that`

**Acceptance Criteria**:
- [ ] Verify that the PM4ML onboarding script are updated to support this

**Notes**:
XTS - test currency to test connectivity
Mojalop should be configured to perform CGS on this currency  
To avoid needing to perform cash in
A liquidity test can still be performed if the transfer amount exceeds NDC or multiple parallel transfers exceed liquidity configured.
XXX - test currency to test differed net settlement"

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Test current model against test currency XTS
- [ ] Configure onboarding script to create the CSG from XTS and currencies
- [ ] Remove hardcoded currencies in onboarding scripts

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
