### ISSUE TITLE
2.11 Design an API to query DFSP positions

### ISSUE THREAD

**Issue by nikolayanastasov** [mojaloop/project#331]
**Goal**:
1. As a developer
I would like to _design the API to manage DFSP positions (DFSP position query API)_ 
2. As an FSP
I would like to _query an API on the Switch to get my current position_ 

**Tasks**:
- [x] Swagger 2.0 YAML version of the Admin API
- [x] Design an API to query FSP Positions (current position)
  - [x] Discuss whether to leverage the existing admin API or create this separately
- [x] Design Data Model and query for Position (GET)
  - [x] For a specific FSP
  - [x] For all FSPs (probably for the Hub Operator)
- [ ] ~~Update migration scripts (as part of design)~~

**Acceptance Criteria**:
- [ ] The design for an API to query the current position of an FSP is available (Leverage the existing admin API)
- [ ] Swagger definition provided for the updated resources /positions and definitions used are specified
- [ ] Add stories for implementation of above design

**Dependencies**:
- [x] #317 
- [x] #341 

**Accountability**:
- Owner 
- QA/Review

**Comment by elnyry** [comment]
Here are some details for quick reference:
PR: https://github.com/mojaloop/docs/pull/36
The PR includes - Sequence diagram for querying position for a specific DFSP, Sequence diagram for querying positions for all FSP positions (Hub Operator), Swagger YAML with the Data Model for responses

Below are the updated sections (resources) in the YAML:

- GET /positions:
- GET /positions/{name}:

Under Definitions, added below items:

- Amount
- DateTime
- FspId
- Money
- IndividualPosition
- PositionsNameGetResponse
- PositionsGetResponseForHub

Notes:

- For the Data Model, please look at the examples provided for the field "x-examples:"
- I took the Spec from the JSON that Valentin generated and updated sections as mentioned in $5 above.
- No changes made to the migration scripts as the DM uses the tables based on the updated design (with no changes necessary)
