### ISSUE TITLE
Merchant Registration

### ISSUE THREAD

**Issue by karimjindani** [mojaloop/project#3314]
## **Goal**:
`As a` merchant,

`I want to` be added in the Merchant Registry
  
`so that` I can receive payments from my DFSP

**Acceptance Criteria**:
- [ ]  

**Complexity**: High > The requirement is similar to creating a central registry 

**Uncertainty**: Low > Essential feature to support USSD & QR code based payments

---

**Tasks**:
- [ ] Create a Central Merchant Directory
- [ ] Create a Self registration portal in which Merchant can self-register and DFSP can approve registration

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
