### ISSUE TITLE
3.05 DB Design for Settlement Processing - [8]

### ISSUE THREAD

**Issue by nikolayanastasov** [mojaloop/project#332]
**Goal**:
As a Switch
I would like the _database schema designed for Settlement Processing_ 
so that it can support the implementation of Settlements

**Tasks**:
- [x] Design the DB for Settlement Processing [@ggrg]
- [x] Update Migration scripts (as part of design) [@ggrg]
- [x] Add seeds for settlement state tables [@ggrg]
- [x] Clean seeds for transfer states [@ggrg]
- [x] Clean unused tables from migration scripts [@ggrg]
- [x] Make sure migrations match 100% the design - added **segment** and **transferTimeout** [@ggrg]
- [x] Update code base to remove unused transfer states - PENDING_SETTLEMENT, SETTLED [@ggrg]
- [x] Update docs to remove unused transfer states [@ggrg]
- [x] Update docs to include current DB Model diagram [@ggrg]
- [x] Update docs to include current DB DDL script [@ggrg]

**Acceptance Criteria**:
- [x] A DDL is available for Settlement Processing is made
- [ ] Above DDL is reviewed and signed-off

**Dependencies**:
- [ ] #333 

**Accountability**:
- Owner 
- QA/Review

**Comment by elnyry** [comment]
Couldn't get to this in 3.3, moving to 3.4.. ( Beyond Sprint capacity, >110 points for this Sprint, excluding this one)

**Comment by ggrg** [comment]
Please review and approve/comment on the following pull requests:
[central-ledger PR](https://github.com/mojaloop/central-ledger/pull/115)
[docs PR](https://github.com/mojaloop/docs/pull/52)

**Comment by elnyry** [comment]
Blocked due the dependency to #333
