### ISSUE TITLE
[SDK-Scheme-Adapter] Add support for missing PUT /transactionRequests/{transactionId}/error callback handling

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3322]
## **Goal**:
`As a` DFSP

`I want to` be able to process transactionRequests error callbacks
  
`so that` I can complete the transactionRequests processing flow as per the FSPIOP specification

**Acceptance Criteria**:
- [x] `PUT /transactionRequests/{transactionId}/error` callback is handled by the SDK-Scheme-Adapter

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Implement the missing error handler in inbound API server
- [x] Add unit tests

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/448

## **Follow-up**:
- N/A

**Dependencies**:
- The story will be implemented as part of https://github.com/mojaloop/project/issues/3322

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by chris-me-law** [comment]
Reason for Block: The sequence of Feature Stories required to fix this defect:
#3345
#3247
