### ISSUE TITLE
[SDK-Scheme-Adapter] Implement Request-to-pay functionality tests as Helm Tests

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3323]
## **Goal**:
`As a` DFSP

`I want to` have the SDK's R2P functionality tests automated
  
`so that` I can ensure the R2P functionality is working as expected

**Acceptance Criteria**:
- [ ] TTK Test Collection for R2P processing flow can be used to validate the SDK's R2P functionality
- [ ] SDK's Functional Test cases executed the R2P validations as part of the CI-checks
- [ ] Helm test on a Mojaloop Release will be able to test the SDK's R2P functionality

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Duplicate #3380
