### ISSUE TITLE
Hub Operator for Merchant Record Maintenance

### ISSUE THREAD

**Issue by ZorainTooba** [mojaloop/project#3325]
## **Goal**:
`As a` hub operator who will be handling merchant registry system,

`I want to` add bulk records for the merchant registry
  
`so that` I don't have to manually add each record to the system

**Acceptance Criteria**:
- [ ] 

**Complexity**: High > The requirement is similar to creating a central registry 

**Uncertainty**: Low > Essential feature to support USSD & QR code based payments

---

**Tasks**:
- [ ] Create a Merchant record system which will be handled by a specific hub operator
- [ ] Create an interface for bulk data entry
- [ ] Create CSV/Excel file import feature
- [ ] Create a status feature for success and failure for each import
- [ ] Create a recover feature to utilize if the import process get failed

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
