### ISSUE TITLE
3.01 Settlement Batch processing design - [8] - Part:1

### ISSUE THREAD

**Issue by nikolayanastasov** [mojaloop/project#333]
**Goal**:
As a developer
I would like to _create Settlement Batch processing design to review with DA_
- Option 1: prepare handler storing the settlement ID & putting it into the LIME Meta data;
- Option 2: Update the transfers as a DB write up on settlement)

**Tasks**:
- [ ] Decide on the approach for Settlement Batch processing
- [ ] Alter DB schema model to cater for Settlement Batch processing [@ggrg]
- [ ] Design Settlement Batch processing
  - [ ] Sequence diagrams
    - [x] GET:: getSettlementWindowById (6.1.1.) [@HenkKodde]
    - [x] POST:: closeSettlementWindow (6.1.2.) [@HenkKodde]
    - [x] GET:: getSettlementWindowByParams (6.1.3.) [@HenkKodde]
    - [ ] ~GET:: getSettlementsByParams (6.2.0.)~ <-- Final Sprint
    - [x] POST:: settlementEventTrigger (6.2.1.)[@HenkKodde, @ggrg]
    - [ ] ~GET:: getSettlementsBySettlementParticipantAccounts (6.2.2.)~ <-- Final Sprint
    - ~PUT:: updateSettlementBySettlementParticipantsAccounts (6.2.3)~
    - [ ] ~GET:: getSettsettlementsById (6.2.4.) [@HenkKodde]~ <-- Final Sprint
    - [ ] ~PUT:: updateSettlementById (6.2.5.) [@HenkKodde, @ggrg]~ <-- Final Sprint
    - ~PUT:: updateSettlementBySettlementIdParticipantId (6.2.6)~

**Follow-up item**:
- [ ] #411

**Acceptance Criteria**:
- [ ] DA to Review the design of Settlement Batch processing
  - [ ] Sequence diagrams for settlement operations

**Dependencies**:
- None currently

**Accountability**:
- Owner @wdcmb 
- QA/Review **DA**

**Comment by elnyry** [comment]
Moved over to 3.4 as all the tasks were not completed, could get to this near the end of Sprint3.3, but couldn't close out tasks

**Comment by HenkKodde** [comment]
Pull request raised for 3 seq diagrams.
https://github.com/mojaloop/docs/pull/55.

**Comment by ggrg** [comment]
Actually the sequence diagrams in the PR are currently 4.

**Comment by elnyry** [comment]
Follow-up item: #411

This was a massive item where each task could've been a story - but handling this now in the follow-up item
