### ISSUE TITLE
Support for AWAITING_SETTLEMENT state for Batches

### ISSUE THREAD

**Issue by koekiebox** [mojaloop/project#3333]
## **Goal**:
`As a` Hub operator

`I want to` Please a batch in a state of `AWAITING_SETTLEMENT`
  
`so that` The batch is allocated to a single settlement matrix, which is the only matrix allowed to settle (or cancel) that batch/s. 
Please consult the following document for more information:
https://github.com/mojaloop/mojaloop-specification/issues/117#:~:text=Settlement%20administrator%20stories.docx

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <Medium> > Addition of the following required;
- New command for handling `AWAITING_SETTLEMENT` event
- New test cases to cater for state scenarios
- Ability to update the batch, in order to place that batch into a closed state

**Uncertainty**: <Low> > Requirement is clearly defined in mentioned document.

---

**Tasks**:
- [ ] Implement the  feature as explained in https://github.com/mojaloop/mojaloop-specification/issues/117#:~:text=Settlement%20administrator%20stories.docx

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Accountability**:
- Owner: @koekiebox @MichaelJBRichards 
- QA/Review: @MichaelJBRichards
