### ISSUE TITLE
[rep-hub-bop-api-svc] Helm chart release to support special characters

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3338]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` have a new release of helm chart for rep-hub-bop-api-svc
  
`so that` I can use special charaters in CENTRAL LEDGER DB configuration parameters

**Acceptance Criteria**:
- [ ] A Helm chart is release with the new version of rep-hub-bop-api-svc (https://github.com/mojaloop/reporting-hub-bop-api-svc/releases/tag/v2.0.0)
- [ ] Helm chart supports configuration for MySQL for each of the following parameters:
    - [ ] Host
    - [ ] Port
    - [ ] User
    - [ ] Password
- [ ] Helm chart supports configuration for MongoDB for each of the following parameters:
    - [ ] Host
    - [ ] Port
    - [ ] User
    - [ ] Password

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Refactor `reporting-hub-bop-api-svc` chart in `charts` repository to use latest changes in configuration
- [x] Fix `/health` endpoint in reporting-hub-bop-api-svc
- [x] Test the deployment with special characters in DB passwords
- [ ] Make a release of `charts` helm repo

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/charts/pull/85

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3338?planning-poker) with Zenhub @PaulGregoryBaker @vijayg10
