### ISSUE TITLE
IaC release with support for special characters in finance portal (BOF) service configurations

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3339]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` test IaC with new finance portal (BOF) chart version
  
`so that` I can make sure that special characters can be used in DB_URL configuration parameters

**Acceptance Criteria**:
- [x] Mojaloop IaC by default generates passwords using special characters for deploying
   - [x] Mojaloop v15 release
   - [x] Latest BoF Helm release
- [x] Mojaloop IaC tests against deployments using default passwords generated with special characters pass successfully
   - [x] Mojaloop v15 release
   - [x] Latest BoF Helm release

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Re-configure IaC Password Policy to generate default passwords using special characters
- [x] Update BoF Helm configurations to use default passwords using special characters generated by IaC
- [x] Re-deploy Bof and Mojaloop deployments using default passwords using special characters generated by IaC
- [x] Verify IaC tests pass for Bof and Mojaloop
- [ ] ...

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/iac-aws-platform/pull/87

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3339?planning-poker) with Zenhub @PaulGregoryBaker @vijayg10
