### ISSUE TITLE
3.06 Json file validation to against ISO Spec (make necessary changes where applicable); Review/Refactor existing Settlement Engine and Json file field changes. 

### ISSUE THREAD

**Issue by nikolayanastasov** [mojaloop/project#334]
**Goal**:
As a developer I would like to _create JSON file validation to against ISO Spec (make necessary changes where applicable); Review/Refactor existing Settlement Engine and Json file field changes _

**Tasks**:
- [ ] Prepare JSON file validation to against ISO Spec (make necessary changes where applicable);
- [ ] Review/Refactor existing Settlement Engine and JSON file field changes.

**Acceptance Criteria**:
- [ ] Prepare JSON file validation to against ISO Spec (make necessary changes where applicable);
- [ ] Review/Refactor existing Settlement Engine and JSON file field changes.

**Dependencies**:
- None currently

**Accountability**:
- Owner 
- QA/Review
