### ISSUE TITLE
[SDK-Scheme-Adpator] Complete request to pay - SDK design

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3340]
## **Goal**:
`As a` DFSP using SDK scheme adapter to connect to Mojaloop
`I want to` user the request to pay payee initiated transaction flow
`so that` integration this used case into my solution

**Acceptance Criteria**:
- [ ] Verify that a sequence diagram exists to explain the data flows for SDK request to pay as both payee and payer DFSP
   - [ ] Verify that examples messages are included
   - [ ] Verify that both auto accept party and auto accept quote options are included
   - [ ] Verify that error case flows are included
- [ ] Add sequence diagram to the std documentation in a PR (PR should only be merged after code PRs are completed and merged.)

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
https://github.com/mojaloop/documentation/pull/413
