### ISSUE TITLE
TTK - Add header validation for FSPIOP headers when using TTK as simulator for mojaloop

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3343]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` get my FSPIOP headers validated properly by TTK with default configuration
  
`so that` I can use TTK to simulate mojaloop switch

**Acceptance Criteria**:
- [ ] Content-Type and Accept Headers can be validated in default TTK configuration

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
