### ISSUE TITLE
Enhance SDK Scheme Adaptor to support the request to Pay use case

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3344]
## **Goal**:
`As a` DFSP using SDK scheme adaptor to connect to Mojaloop
`I want to` have the SDK supporting request to pay  
`so that` use the request to pay use case

**Acceptance Criteria**:
- [ ] Verify that we have an sequence diagram defined that specifies the SDK calls and Mojaloop calls that support the request to pay use case
- [ ] Fully support the FSPIOP request to pay use case
   - [ ] Verify that OTP authentication is supported
   - [ ] Verify that direct Payer acceptance is supported 
   - [ ] Verify that the on rejection use case is supported.
- [ ] Verify that there is support for homeRTPTransactionId on both the Payer DFSP and the Payee DFSP
- [ ] Verify that the transactionRequestId is standardised through the SDK adapter in the RTP flows.
- [ ] Verify that the SDK documentation is update to describe this use case (both local repo and official docs).
- [ ] Verify that the Payer's detail can be validated by the Payee (I.e. AUTOACCEPTPARTY = false)
- [ ] Verify that the SDK functional tests tests the above use case

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
![requestToPaySDK drawio](https://github.com/mojaloop/project/assets/11392873/9a9138e9-3123-4e4c-a015-5bf28d2a1d13)

☝️ the above diagram has drawio information imbedded.

**Comment by mdebarros** [comment]
Working Branches:
- SDK-Scheme-Adapter: https://github.com/mojaloop/sdk-scheme-adapter/tree/feat/%233344-EPIC-Enhance-SDK-Scheme-Adaptor-to-support-the-request-to-Pay-use-case
- Testing Toolkit Test Cases: https://github.com/mojaloop/testing-toolkit-test-cases/tree/feat/%233344-EPIC-Enhance-SDK-Scheme-Adaptor-to-support-the-request-to-Pay-use-case
- API-Snippets; https://github.com/mojaloop/api-snippets/tree/feat/%233344-EPIC-Enhance-SDK-Scheme-Adaptor-to-support-the-request-to-Pay-use-case
