### ISSUE TITLE
[SDK Scheme Adaptor] Extend Payee requestToPay API process to support the validation of the payer details (3pts)

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3345]
## **Goal**:
`As a` DFSP Using SDK and RTP use case
`I want to` SDK to support RTP
`so that` continue to use the SDK to connect to Mojaloop for this use case.

**Acceptance Criteria**:
Payee Outbound modifcations
- [x] Verify that a separate AUTO_ACCEPT_R2P_PARTY configuration is used for request to pay
- [x] Verify that  a PUT \RequestToPay API end point is available to proceed after that Party information is returned when the AUTO_ACCEPT_R2P_PARTY option is false.
- [x] Verify that the Authentication type is supplied in the POST \requestToPay
- [x] Verify that the homeTransactionId is renamed to homeRTPtransactionId

Payer Inbound modification

- [x] Verify that the POST \transactionRequest is update to 
    - [x] include that authentication type 
    - [x] Add the homeTransferRequestId to the sync response
    - [x] Rename the TransferAmount to TransactionRequestState 
- [x] ~~Verify that the AuthenticationType is included on the POST /requestToPayTransfers~~
- [x] Verify that homeRTPtransactionId is added as an optional parameter to the POST \transactionRequest sync response
- [x] Verify that this end-to-end request to pay flow is functionally tested  function

Tests
- [x] Functional Tests need to be added to test this use case.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] API Snippets
  - [x] SDK Outbound
    - [x] Add PUT /requestToPay endpoint in SDK Outbound API in api-snippets
    - [x] Rename homeTransactionId to homeR2PTransactionId in POST /requestToPay
    - [x] Add Authentication type to POST \requestToPay to SDK Outbound
    - [x] Rename `requestToPayState` to `currentState` in requestToPayResponse
    - [x] Add `getPartiesResponse` in requestToPayResponse
    - [x] Add `transactionRequestResponse` in requestToPayResponse
    - [x] Remove `authenticationType` in requestToPayResponse
  - [x] SDK Backend
    - [x] Add authentication type  to POST \transactionRequest
    - [x] Rename the TransferAmount to TransactionRequestState
    - [x] Add `homeR2PTransactionId` to POST \transactionRequest sync response
- [x] Payee Outbound
  - [x] Implement PUT /requestToPay handler in SDK
  - [x] Add config param AUTO_ACCEPT_R2P_PARTY to SDK and use it in requestToPay handlers
  - [x] Add homeR2PTransactionId to corresponding handlers
  - [x] Add Authentication type to POST /transactionRequests calls in requestToPay handlers
- [x] Payer Inbound
  - [x] Add authentication type to FSPIOP inbound /transactionRequests to pass to the core backend
  - [x] Rename the TransferAmount to TransactionRequestState
  - [x] ?? `Verify that the AuthenticationType is included on the POST /requestToPayTransfers`
  - [x] Add `homeR2PTransactionId` as an optional parameter to the POST \transactionRequest sync response

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/api-snippets/pull/162
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/445
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/121

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3345?planning-poker) with Zenhub @PaulGregoryBaker @vijayg10
