### ISSUE TITLE
[SDK] Enhance the Payer requestToPayTransfer API process for OTP authentication

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3346]
## **Goal**:
`As a` DFSP using SDK to connect to Mojaloop
`I want to` enable the OTP RTP flow
`so that` make use of this use case

**Acceptance Criteria**:
Payer DFSP outbound OTP SDK changes
- [ ] Verify that the if OTP authentication is configured, then a retry mechanism is in-place for triggering Get /authorisations via PUT /requestToPayTransfer 
- [ ] Verify that the PUT /requestToPayTransfer response has the authResponse added
Payee DFSP Inbound Changes
Verify that the GET /OTP api has
   - [ ] RequestToPayId renamed to transactionRequestId
   - [ ] homeRTPTransactionId added as an optional parameter
**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3346?planning-poker) with Zenhub @PaulGregoryBaker @vijayg10

**Comment by mdebarros** [comment]
This story is a 13-story pointer if done by itself, but if https://github.com/mojaloop/project/issues/3347 is done prior to this story, it would then be reduced 5-story pointer.
