### ISSUE TITLE
[SDK Scheme Adapter] Enhance the requestToPayTransfer API process for Payer Acceptance flow

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3347]
## **Goal**:
**As a** DFSP using SDK to connect to Mojaloop
**I want to** enable the RTP flow
**so that** I can make use of this use case

**Limitations**
This does not support the OTP Authentication flow; I.e. when the Authentication Type is not provided in the /transactionRequest Inbound API.

**Acceptance Criteria**:
Payer DFSP SDK changes
- [ ] Verify that the POST /transferRequest inbound API has the authentication Type added and returns the homeRTPTransactionId
- [ ] Verify that the POST /requestToPayTransfer outbound API has the
   - [ ] homeRTPTransactionId (option) added
   - [ ] has the RequestToPayId renamed to transactionRequestId (To align with the standard naming)
- [ ]  Verify that the PUT /RequestToPay is triggered if the Payer rejects the request and a PUT \transactionRequest FSPIOP is received from Mojaloop

Payee DFSP Inbound Changes
- [ ] Verify that the homeFTPTransactionId is supplied optionally to the POST /quoterequest
- [ ] Verify that a functional test is added to the SDK repo for this.
- [ ]  Verify that the PUT /requestToPayTransfer response with an rejected result in a PUT \transactionRequest FSPIOP call to Mojaloop

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Updated to API-Snippets to accommodate the following [@vijayg10]
    - [x] Update Payer POST /requestToPayTransfer sync request
    - ~Update Payer PUT /requestToPayTransfer sync request & response~ _(I don't think we need to do anything here, but lets keep it in-case something changes)_
    - [x] Update Payee POST /quotesrequest
    - ~Update Payee GET /otp~ _(handled by OTP story)_
    - [x] Update Payee POST /transfers
    - [x] Add Payee PUT /RequestToPay
- [x] Updates to SDK-Scheme-Adapter [@vijayg10 ]
    - [x] Update Payer POST /requestToPayTransfer
    - [x] Update Payer PUT /requestToPayTransfer for accept quote/auth
    - [x] Update Payer PUT /requestToPayTransfer for reject auth
    - [x] Update Payee POST /quotesRequest
    - [x] Update Payee POST /transfers
    - [x] Add Payee PUT /requestToPay
 - [x] Add functional end to end tests for requestToPay and requestToPayTransfer
 - [x] Add unit tests
 - [x] Test coverage
 - [ ] PR reviews

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/api-snippets/pull/163
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/447
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/123

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3347?planning-poker) with Zenhub @PaulGregoryBaker @vijayg10
