### ISSUE TITLE
3.07.01 Implement the DAO layer for Settlements - 1

### ISSUE THREAD

**Issue by nikolayanastasov** [mojaloop/project#335]
**Goal**:
As a Switch 
I would like the _DAO layer for Settlements be Implemented_
so that Settlements functionality can be supported by the Database

**Tasks**:
- [ ] ~Implement DAO layer for Settlements (only implement the methods specified in the design)~
   - [ ] ~Implement DAO - GET: getSettlementsByParams. [@bothadeon]~
   - [x] Implement DAO - POST: postSettlementEventTrigger. [@vgenev]
- [ ] ~Tests~
  - [ ] ~Unit tests~
  - [ ] ~Integration tests~
  - [ ] ~Code coverage~

**Acceptance Criteria**:
- [ ] The DAO layer necessary for Settlements functionality is implemented
- [ ] The implementation aligns with the design and support the API calls
  - [ ] GET Settlements

**Dependencies**:
- [x] #327 
- [x] #328 
- [x] #332
- [ ] #333 

**Follow-up item**:
- [ ] #414

**Accountability**:
- Owner 
- QA/Review @wdcmb

**Comment by elnyry** [comment]
Follow-up item #414
