### ISSUE TITLE
[ML-TTK] Refactor Trigger Template functionality to be rule-based

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3350]
## **Goal**:
`As a` Mojaloop User

`I want to` have Trigger Template functionality via rules
  
`so that` I can trigger Template functionality as a response to receiving a sync/async request.

**Acceptance Criteria**:
- [ ] Verify that the `Rule Builder` now provides a new section to configure Trigger Template functionality
- [ ] Verify that `Sync Response Rules` support a `Rule Builder` to configure the Trigger Template functionality
- [ ] Verify that `Callback Rules` support a `Rule Builder` to configure the Trigger Template functionality
- [ ] Verify that TTK User-Guide documentation is updated to include the updated `Rule Builder` changes for the Trigger Template functionality

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3350?planning-poker) with Zenhub @PaulGregoryBaker @vijayg10
