### ISSUE TITLE
[TTK] upgrade AWS SDK dependency from v2 to v3 due to deprecation

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3352]
## **Goal**:
`As a` Mojaloop Stakeholder

`I want to` upgrade the AWS SDK dependency from v2 v3 in the ML Testing Toolkit CLI
  
`so that` we can ensure the AWS SDK dependency is supported

```log
NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
Please migrate your code to use AWS SDK for JavaScript (v3).
```

The above log appears in the ML Testing Toolkit CLI for uploading reports to the AWS S3 bucket.

**Acceptance Criteria**:
- [ ] Update AWS SDK dependency on the TTK, and ensure warning message is no longer visible
- [ ] Update TTK Helm charts with latest release

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
