### ISSUE TITLE
[Epic] Current K8s Environment for Dev and Testing

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3353]
## **Goal**:
`As a` Mojaloop Maintainer

`I want to` have a current k8s environment
  
`so that` I can validate Mojaloop Releases on the latest supported Kubernetes version

**Acceptance Criteria**: (draft - to be groomed and broken down into stories)
- [ ] Utilise Managed K8s to
  - [ ] Off-load maintenance on the K8s Management plane
  - [ ] Upgrades are automatically managed for me
  - [ ] Reduce costs by removing the Rancher Management plane (i.e. cluster)
- [ ] Utilise GitOps to deploy K8s cluster
  - [ ]  CI job to deploy K8s cluster
      - [ ]  Includes deployment of Nxinx Ingress Controller
      - [ ]  Ingress DNS configuration on Route 53
      - [ ]  Access configurations for Maintenance Team
  - [ ]  CI job to upgrade K8s cluster
  - [ ]  CI job to destroy k8s cluster
- [ ]  Automated Testing for Helm PRs/Releases
    - [ ]  CI Job to verify deployments on last k8s version <-- do we want to test multiple versions to just the "latest" version?

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
