### ISSUE TITLE
[DevOps] Switch away from Rancher to Managed EKS K8s cluster for ML Core Testing & Dev

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3354]
## **Goal**:
`As a` Mojaloop Maintainer

`I want to` switch away from Rancher to a Managed EKS K8s cluster
  
`so that` time can be spent more effectively focused on fixing Mojaloop issues instead of maintaining the underlying K8s infrastructure

**Acceptance Criteria**:
- [x] EKS Cluster Config persisted to Private Git Repo, with the latest K8s version (currently v1.26)
- [x] Simple CI process's to manage EKS cluster from Github Action
    - [x] Create Cluster
    - [x] Update Cluster
    - [x] Delete Cluster
    - [x] setup Route53 config
    - [x] deploy/upgrade Nginx Ingress Controller
    - [x] un-deploy Nginx Ingress Controller
    - [x] deployed/upgrade Certificate Manager
    - [x] un-deploy Certificate Manager
    - [x] deployed/upgrade Moja1 backend dependencies
    - [x] un-deploy Moja1 backend dependencies
    - [x] deployed/upgrade Moja1
    - [x] un-deploy Moja1
    - [x] Update IAM Mappings
- [x] Verify Moja1 environment
    - [x] deployed successfully
    - [x] helm tests pass, with reports published in the Mojaloop Slack #announcements channel
    - [x] daily cron-jobs run, with daily report published in the Mojaloop Slack #announcements 
- [x] Documentation
    - [x] Info on CI Jobs, dependencies, etc
    - [x] Info on how to connect to k8s cluster
    - [x] Announcements Blog
- [x] Decomission Rancher Env
- [x] Verify IaM and User provisioning/access for @elnyry-sam-k 

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Create repo to store CI configs
- [x] Create access token, policies, etc
    - [x] create EKS cluster
    - [x] configure DNS
- [x] Define EKS descriptor
- [x] Create CI Jobs to manage cluster
    - [x] Create
    - [x] Update
    - [x] Destroy
- [x] Create CI Job to configure DNS
- [x] Create CI Job to manage Nginx Ingress Controller
    - [x] Create
    - [x] Update
    - [x] Destroy
    - [x] Configure Internal load balancer to support Internal-only LB network traffic in the VPC (for security)
    - [x] Provide Configuration for the DNS Configuration
- [x] Create CI Job to manage Certificate Manager
    - [x] Create
    - [x] Update
    - [x] Destroy
- [x] Create CI Job to deploy Moja1
    - [x] Create
    - [x] Update
    - [x] Destroy
    - [x] Test
- [x] Test fresh env provisioning
    - [x] Deploy EKS, Infr, Moja1
    - [x] Test Moja1
    - [x] Scale Rancher test.mojaloop.live env to bare minimum
    - [x] Verify daily cron executes
- [x] Support for Updating IAM Mappings
    - [x] Add Job to update IAM Mappings
- [x] Documentation
    - [x] Info on CI Jobs, dependencies, etc
    - [x] Info on how to connect to k8s cluster
    - [x] Announcement Blog
- [x] Decomission Rancher Env
    - [x] Cleanup test.mojaloop.live cluster
    - [x] Cleanup rancher management plane
    - [x] Cleanup dangling resources (ELB, EBS, DNS, etc)
- [x] Verify IaM and User provisioning/access for @elnyry-sam-k 

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
## Environment

```bash
❯ helm -n moja1 list
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION                                                                                                                                                                                                                                                                                                                                                                                                                   
backend moja1           1               2023-06-02 09:28:37.42305295 +0000 UTC  deployed        example-mojaloop-backend-15.0.0 nginx: 4.4.2 ; mysql: 9.4.1; kafka: 19.0.2; mongodb: 13.3.1; redis:17.3.7                                                                                                                                                                                                                                                                                                                                                     
moja1   moja1           1               2023-06-02 09:31:40.378363648 +0000 UTC deployed        mojaloop-15.0.0                 ml-api-adapter: v14.0.0; central-ledger: v17.0.3; account-lookup-service: v13.0.0; quoting-service: v15.0.2; central-settlement: v15.0.0; bulk-api-adapter: v15.0.3; transaction-requests-service: v14.0.1; simulator: v12.0.0; mojaloop-simulator: v14.0.1; sdk-scheme-adapter: v22.0.1; auth-service: v14.0.0; consent-oracle: v0.2.0; thirdparty-sdk: v13.0.2; ml-testing-toolkit: v16.0.1; ml-testing-toolkit-ui: v15.2.1;
```

```bash
❯ helm -n moja1 status moja1
NAME: moja1
LAST DEPLOYED: Fri Jun  2 09:31:40 2023
NAMESPACE: moja1
STATUS: deployed
REVISION: 1
TEST SUITE:     moja1-ml-ttk-test-cleanup
Last Started:   Fri Jun  2 09:57:51 2023
Last Completed: Fri Jun  2 09:58:10 2023
Phase:          Succeeded
TEST SUITE:     moja1-ml-ttk-test-setup-sdk-bulk
Last Started:   Fri Jun  2 09:54:36 2023
Last Completed: Fri Jun  2 09:55:09 2023
Phase:          Succeeded
TEST SUITE:     moja1-ml-ttk-test-setup-tp
Last Started:   Fri Jun  2 09:53:50 2023
Last Completed: Fri Jun  2 09:54:24 2023
Phase:          Succeeded
TEST SUITE:     moja1-ml-ttk-test-setup
Last Started:   Fri Jun  2 09:47:07 2023
Last Completed: Fri Jun  2 09:48:22 2023
Phase:          Succeeded
TEST SUITE:     moja1-ml-ttk-test-val-bulk
Last Started:   Fri Jun  2 09:51:38 2023
Last Completed: Fri Jun  2 09:53:50 2023
Phase:          Succeeded
TEST SUITE:     moja1-ml-ttk-test-val-gp
Last Started:   Fri Jun  2 09:48:22 2023
Last Completed: Fri Jun  2 09:51:38 2023
Phase:          Succeeded
TEST SUITE:     moja1-ml-ttk-test-val-sdk-bulk
Last Started:   Fri Jun  2 09:55:10 2023
Last Completed: Fri Jun  2 09:57:50 2023
Phase:          Succeeded
TEST SUITE:     moja1-ml-ttk-test-val-tp
Last Started:   Fri Jun  2 09:54:24 2023
Last Completed: Fri Jun  2 09:54:36 2023
Phase:          Succeeded
NOTES:
Thank you for installing mojaloop.
```

## Test Results

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Standard Provisioning Collection
Environment: moja1.test.mojaloop.live@v15.0.0
Total assertions: 326
Passed assertions: 326
Failed assertions: 0
Total requests: 324
Total test cases: 37
Passed percentage: 100.00%
Started time: Fri, 02 Jun 2023 09:47:15 GMT
Completed time: 2023-06-02T09:48:18.050Z
Runtime duration: 62115 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-standard_provisioning_collection-2023-06-02T09%3A48%3A18.050Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP Tests
Environment: moja1.test.mojaloop.live@v15.0.0
Total assertions: 2668
Passed assertions: 2668
Failed assertions: 0
Total requests: 603
Total test cases: 131
Passed percentage: 100.00%
Started time: Fri, 02 Jun 2023 09:48:26 GMT
Completed time: 2023-06-02T09:51:31.205Z
Runtime duration: 184632 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-gp_tests-2023-06-02T09%3A51%3A31.205Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Bulk Tests
Environment: moja1.test.mojaloop.live@v15.0.0
Total assertions: 337
Passed assertions: 337
Failed assertions: 0
Total requests: 63
Total test cases: 16
Passed percentage: 100.00%
Started time: Fri, 02 Jun 2023 09:51:42 GMT
Completed time: 2023-06-02T09:53:46.175Z
Runtime duration: 123852 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-bulk_tests-2023-06-02T09%3A53%3A46.175Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Thirdparty Provisioning Collection
Environment: moja1.test.mojaloop.live@v15.0.0
Total assertions: 137
Passed assertions: 137
Failed assertions: 0
Total requests: 135
Total test cases: 15
Passed percentage: 100.00%
Started time: Fri, 02 Jun 2023 09:53:54 GMT
Completed time: 2023-06-02T09:54:19.493Z
Runtime duration: 24706 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-thirdparty_provisioning_collection-2023-06-02T09%3A54%3A19.493Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Thirdparty Tests
Environment: moja1.test.mojaloop.live@v15.0.0
Total assertions: 21
Passed assertions: 21
Failed assertions: 0
Total requests: 20
Total test cases: 8
Passed percentage: 100.00%
Started time: Fri, 02 Jun 2023 09:54:28 GMT
Completed time: 2023-06-02T09:54:33.328Z
Runtime duration: 5078 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-thirdparty_tests-2023-06-02T09%3A54%3A33.328Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: SDK Bulk Provisioning Collection
Environment: moja1.test.mojaloop.live@v15.0.0
Total assertions: 123
Passed assertions: 123
Failed assertions: 0
Total requests: 119
Total test cases: 13
Passed percentage: 100.00%
Started time: Fri, 02 Jun 2023 09:54:40 GMT
Completed time: 2023-06-02T09:55:05.531Z
Runtime duration: 25191 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-sdk_bulk_provisioning_collection-2023-06-02T09%3A55%3A05.531Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: SDK Bulk Tests
Environment: moja1.test.mojaloop.live@v15.0.0
Total assertions: 217
Passed assertions: 217
Failed assertions: 0
Total requests: 45
Total test cases: 22
Passed percentage: 100.00%
Started time: Fri, 02 Jun 2023 09:55:13 GMT
Completed time: 2023-06-02T09:57:46.817Z
Runtime duration: 153125 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-sdk_bulk_tests-2023-06-02T09%3A57%3A46.817Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Post Cleanup
Environment: moja1.test.mojaloop.live@v15.0.0
Total assertions: 49
Passed assertions: 49
Failed assertions: 0
Total requests: 15
Total test cases: 4
Passed percentage: 100.00%
Started time: Fri, 02 Jun 2023 09:57:55 GMT
Completed time: 2023-06-02T09:58:05.561Z
Runtime duration: 10512 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-post_cleanup-2023-06-02T09%3A58%3A05.561Z.html)

**Comment by mdebarros** [comment]
## TTK Report Dashboard

![Screenshot 2023-06-02 at 16 05 54](https://github.com/mojaloop/project/assets/11392873/707b141c-a287-4017-a59e-820dbd168613)
