### ISSUE TITLE
[DevOps] Enhance EKS K8s cluster CI process to deploy monitoring tools

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3355]
## **Goal**:
`As a` Mojaloop Maintainer

`I want to` have monitoring tools deployed to a Managed EKS K8s cluster
  
`so that` I can monitor underlying k8s infrastructure, and deployed applications (i.e. Mojaloop Backend Dependencies, and Mojaloop Services)

**Acceptance Criteria**:
- [ ] Simple CI process's to manage EKS cluster from Github Action
    - [ ] deployed/upgrade Prometheus/Grafana stack
    - [ ] un-deploy Prometheus/Grafana stack
- [ ] Verify dashboards are available for underlying K8s instructure
- [ ] Verify dashboards are available for Mojaloop deployment of Moja1

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
