### ISSUE TITLE
[DevOps] Enhance EKS K8s cluster CI process to deploy centralised log monitoring tools

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3356]
## **Goal**:
`As a` Mojaloop Maintainer

`I want to` have centralised logging tools deployed to a Managed EKS K8s cluster
  
`so that` the underlying k8s infrastructure, and deployed applications (i.e. Mojaloop Backend Dependencies, and Mojaloop Services) logs are captured centrally

**Acceptance Criteria**:
- [ ] Simple CI process's to manage EKS cluster from Github Action
    - [ ] deployed/upgrade log monitoring stack
    - [ ] un-deploy log monitoring stack
- [ ] Verify dashboards are available for accessing, filtering and searching through centralised captured logs

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
