### ISSUE TITLE
[Helm] Include Cleanup Helm Test Job as optionally Cron-Job

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3357]
## **Goal**:
`As a` Mojaloop User

`I want to` have the Cleanup Helm Test Job as an optionally Cron-job
  
`so that` I can execute the Cleanup script to reset all test DFSPs liquidity 

**Acceptance Criteria**:
- [ ] Cleanup Helm Test Job is configurable as optionally Cron-job
- [ ] When Cleanup Helm Test Cron-job is enabled with the Daily GP Cron-job, test DFSPs liquidity is reset after running the GP tests

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Duplicate #3361
