### ISSUE TITLE
[Helm] Helm tests to support option to configure the return code on failure to allow for subsequent tests to execute if desired

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3358]
## **Goal**:
`As a` Mojaloop user

`I want to` have the option to configure Helm tests to return a non-fatal error code
  
`so that` subsequent Helm tests can execute regardless of the prior tests' outcome

**Acceptance Criteria**:
- [ ] Helm test configuration support configuring the return code to be fatal on failure
- [ ] When Helm test config is set to not return a fatal response code on failure, subsequent Helm tests should execute
- [ ] When Helm test config is set to return a fatal response code (which is default) on failure, subsequent Helm tests should execute

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
