### ISSUE TITLE
5.02.6 Add InitContainer to Central Ledger to resolve startup MIGRATION_LOCK issue

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#336]
**Goal**:
As a developer
I would like to _Add InitContainer to Central Ledger to resolve startup MIGRATION_LOCK issue_
so that DB setup can be automated

**Tasks**:
- [ ] Add InitContainer to Central Ledger helm charts to resolve startup MIGRATION_LOCK issue
  - [ ] Check if tables already existing
  - [ ] Run migration scripts ?
  - [ ] ~Update migration lock table with primary key~

**Acceptance Criteria**:
- [ ] An InitContainer to Central Ledger to
  - [ ] automate DB setup is available
  - [ ] ensure overwriting doesn't happen on an existing Database

**Dependencies**:
- None currently

**Accountability**:
- Owner 
- QA/Review

**Comment by elnyry** [comment]
Moving out of backlog as Murthy is OOO for the coming 3 days

**Comment by elnyry** [comment]
Stories #346 and #364 were prioritized given the constraints and were pulled in to this sprint (unplanned), so moving this one out.

**Comment by elnyry** [comment]
@rmothilal - Is this still applicable?

**Comment by elnyry** [comment]
This is done.. (a while ago)
