### ISSUE TITLE
[Epic][NodeJS] Maintenance Upgrades

### ISSUE THREAD

**Issue by chris-me-law** [mojaloop/project#3363]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` <action>
  
`so that` <reason> 

Components:
- [x] core libraries
  - [x] ml-number
  - [x] api-snippets
  - [x] central-services-db (database-lib)
  - [x] central-services-stream
  - [x] central-services-logger
  - [x] central-services-metrics
  - [x] central-services-health
  - [x] central-services-shared
  - [x] central-services-error-handling
  - [x] sdk-standard-components
  - [x] event-sdk
  - [x] object-store-lib
- [x] central-ledger
- [x] ml-api-adapter
- [x] quoting-service
- [x] central-setttlement
- [x] account-lookup-service
- [x] bulk-api-adapter
- [x] event-sidecar
- [x] transactions-requests-service
- [x] Third-party (3PPI)
  - [x] ALS consent oracle
  - [x] Thirdparty-API-Svc
  - [x] Thirdparty-SDK
  - [x] auth-service
- [x] TTK
  - [x] ttk toolkit
  - [ ] ttk toolkit ui
  - [x] ttk shared lib
  - [x] ttk client lib
- [x] mojaloop-simulator
- [x] simulator (legacy, ALS oracle)
- [x] ALS oracle pathfinder
- [x] Oracle shared library 
- [ ] ~ALS oracle template~
- [x] central-event-processor
- [x] event-stream-processor
- [x] email-notifier
- [x] sdk-scheme-adapter ([sdk-scheme-adapter/pull/452](https://github.com/mojaloop/sdk-scheme-adapter/pull/452))

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/sdk-scheme-adapter/pull/452

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
- [ ] Update all dependencies
- [ ] Verify that ignored dependency upgrades are still applicable `.ncurc.yaml`
- [ ] Verify that ignored audit issues are still applicable `audit-ci.jsonc`
- [ ] Update project to the latest LTS Nodejs version run CI tests
- [ ] Update CI workflow
    - [ ] based on the latest fixes made to the SDK-Scheme-Adapter CI workflow for NVM, etc, 
    - [ ] disable dep-check on merge to master and releases/snapshots
- [ ] Resolve compatibility issue with central services stream library
- [ ] Add .versionrc
- [ ] Update the master branch to main 
   - [ ] update main readme
   - [ ] update ci config

**Comment by elnyry-sam-k** [comment]
Closing as completed!
