### ISSUE TITLE
Settlement v3 - View Settlement Models

### ISSUE THREAD

**Issue by tselit** [mojaloop/project#3365]
## **Goal**:
`As a` hub administrator

`I want to` be able to see the settlement models that are currently defined for my Scheme
  
`so that` I can specify settlement reports using the characteristics of each settlement model.

**Acceptance Criteria**:
- [x] The ability to query settlement data based on the different settlement models (as one of the filter criteria on the front-end).

**Complexity**: Low > This introduces an additional criteria for filtering settlement batch. The settlement BC gets informed what the settlement model is (by the Central Ledger or Transfers BC or ), rather than determining it.

**Uncertainty**: Low > Requirements clearly defined.

---

**Dependencies**:
- N/A

**Tasks**:
- [x] TBD [ @? ]

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] TBD

## **Follow-up**:
- N/A

## **Accountability**:
- Owner: @koekiebox 
- QA/Review: TBC

**Comment by tselit** [comment]
This user story is linked to, and directly comes from the user story document that was prepared by the Product Owners for Settlement v3, in March 2023.

Refer to [link to Change Request with user stories document](https://github.com/mojaloop/mojaloop-specification/issues/117#issuecomment-1480797650)

**Comment by koekiebox** [comment]
Example of Settlement model view.
All required criteria met. Settlement model is defined as part of settlement transfer creation:
```typescript
	const reqTransferDto_1: ITransferDto = {
			id: null,
			transferId: randomUUID(),
			payerFspId: payer,
			payeeFspId: payee,
			currencyCode: 'EUR',
			amount: '10000', //100 EURO
			timestamp: Date.now(),
			settlementModel: 'MULTI_MATRIX'// Model created based on defined model.
		};
```

## View settlement models:
<img width="1727" alt="image" src="https://github.com/mojaloop/project/assets/1992108/19bd7d37-7cf0-4c4d-9e80-3b92f04553f7">

## Filter criteria based on model:
<img width="1728" alt="image" src="https://github.com/mojaloop/project/assets/1992108/9630593e-8e10-4caa-98e4-f61f6ae470ca">

# Test cases:
https://github.com/mojaloop/settlements-bc/blob/7c55c3cc4bc483e9145a5052afe85d2661709fb2/packages/domain-lib/test/unit/index.test.ts#L1015
