### ISSUE TITLE
Settlement v3 - View a settlement report

### ISSUE THREAD

**Issue by tselit** [mojaloop/project#3366]
## **Goal**:
`As a` hub administrator

`I want to` see the current content of a previously created settlement report
  
`so that` I can understand the obligations of the participants in my scheme.

**Acceptance Criteria**:
The output is a settlement report that contains:
- [x] a. The unique identifier of the settlement report, if there is one.
- [x] b. The criteria which were used to specify the inclusion of settlement batches in the settlement report.
- [x] c. A record for each settlement batch, containing:
- [x]   (i) The name of the batch
- [x]   (ii) The current status of the batch
- [x]   (iii) For each participant in the scheme:
- [x]      - Their net position in the batch.
- [x] d. For each batch status, except AWAITING_SETTLEMENT, for each participant in the scheme:
- [x]   (i) The total position for all batches in the report which have that status.
- [x] e. Batches with the AWAITING_SETTLEMENT status should be divided into multiple rows, one for each settlement execution request to which they belong. The first row should show the batches awaiting settlement because they belong to the settlement execution request for this report. Subsequent rows should show batches awaiting settlement as a consequence of other settlement execution requests.
- [x] f. For each participant in the scheme:
- [x]   (i) The total settleable position for the report. The settleable position is the sum of all batches whose status is one of:
             - OPEN
             - CLOSED
             - AWAITING_SETTLEMENT, where this status was acquired by the settlement execution request whose identifier is associated with this settlement report.

**Complexity**: High > Delivery of this user story entails implementing multiple requirements to produce the settlement report output, and there is dependency on a related user story <link to related user story>.

 **Uncertainty**: Medium > The workstream is currently defining the structure of the resultant report.

---

**Dependencies**:
- Completion of this user story is dependent on the following ticket [Settlement v3 - Create a settlement report](https://github.com/mojaloop/project/issues/3367)

**Tasks**:
- [x] TBD [ @? ]

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [x] TBD

## **Follow-up**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by koekiebox** [comment]
Batches with the AWAITING_SETTLEMENT status should be divided into multiple rows, one for each settlement execution request to which they belong. The first row should show the batches awaiting settlement because they belong to the settlement execution request for this report. Subsequent rows should show batches awaiting settlement as a consequence of other settlement execution requests.

```json
id: "1234-1234-1234-1234",
name: "20230427001100.DEFAULT.USD.001",
batches: [{
	id: "", name: "", status: "", batchAccounts: [] …
}, …]
awaitingSettlementBatches: [
	{batchId: "", matrixId: "matrix-1"…},
	…,
]
```

**Comment by koekiebox** [comment]
Example of Settlement matrix view.

All required criteria met.

## Criteria for Matrix:
<img width="1727" alt="image" src="https://github.com/mojaloop/project/assets/1992108/de215713-9fe4-442b-ae8a-6a23301de080">

## Matrix view:
<img width="1720" alt="image" src="https://github.com/mojaloop/project/assets/1992108/aa75e370-cd90-4be4-a736-e36ce9f1f5e1">

## Participants for the matrix:
<img width="1428" alt="image" src="https://github.com/mojaloop/project/assets/1992108/6c8942d1-28b2-4223-a111-d7c465675bc6">

## Balances based on batch status:
<img width="1420" alt="image" src="https://github.com/mojaloop/project/assets/1992108/b2476e36-989e-4473-9656-716c16b12932">


# Test cases:
https://github.com/mojaloop/settlements-bc/blob/7c55c3cc4bc483e9145a5052afe85d2661709fb2/packages/domain-lib/test/unit/index.test.ts#L1015
