### ISSUE TITLE
Settlement v3 - Request settlement execution

### ISSUE THREAD

**Issue by tselit** [mojaloop/project#3370]
## **Goal**:
`As a` hub administrator

`I want to` be able to request settlement that is based on either one of the following:
(1) a previously defined settlement report OR 
(2) specifying criteria for settlement to be executed. The criteria has been defined in a related ticket [Settlement v3 - Create a settlement report](https://github.com/mojaloop/project/issues/3367)
  
`so that` the settlement gets executed, and produces results that meet the acceptance criteria defined below.

**Acceptance Criteria**:
- [x] Requesting the execution of settlement based on a previously defined settlement report.
- [x] Requesting the execution of settlement based on specifying a set of criteria. This related ticket [Settlement v3 - Create a settlement report](https://github.com/mojaloop/project/issues/3367) defines the selection criteria.
- [x] All settlement batches that are covered by the criteria AND have a status of **OPEN** or **CLOSED** should have their status changed to **AWAITING_SETTLEMENT**.
- [x] Results in assigning a unique identifier for the proposed settlement.
- [x] Results in producing a settlement report that shows the amounts to be settled. The requirements of the settlement report are defined in a related ticket [Settlement v3 - View a settlement report](https://github.com/mojaloop/project/issues/3366)

**Complexity**: Medium > Due to the number of interactions, which includes event publishing, matrix status updates and matrix batch updates
**Uncertainty**: Low > Requirements clearly defined

---

**Dependencies**:
- Related to this ticket: [Settlement v3 - View a settlement report](https://github.com/mojaloop/project/issues/3366)
- Related to this ticket: [Settlement v3 - Create a settlement report](https://github.com/mojaloop/project/issues/3367)

**Tasks**:
- [x] TBD [ @? ]

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [x] TBD

## **Follow-up**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by koekiebox** [comment]
Please refer to:
- https://github.com/mojaloop/project/issues/3375
- https://github.com/mojaloop/project/issues/3366
- https://github.com/mojaloop/project/issues/3372
- https://github.com/mojaloop/project/issues/3373
- https://github.com/mojaloop/project/issues/3376
- https://github.com/mojaloop/project/issues/3370
