### ISSUE TITLE
Settlement v3 - Change the status of a settlement batch

### ISSUE THREAD

**Issue by tselit** [mojaloop/project#3371]
## **Goal**:
`As a` hub administrator

`I want to` be able to change the status of one or more settlement batches
  
`so that` I can manage a set of transfers.

**Acceptance Criteria**:
The following settlement batch status changes are allowed:
- [x] Change from OPEN to CLOSED
- [x] Change from OPEN to IN_DISPUTE
- [x] Change from CLOSED to IN_DISPUTE
- [x] Change from IN_DISPUTE to CLOSED

Supporting the following ways to identify the settlement batches whose status is to be changed:
- [x] The name of the settlement batch.
- [x] All settlement batches in a pre-defined report to which the proposed change can be applied, specified by the identifier of the report.
- [x] All settlement batches in a pre-defined settlement request to which the proposed change can be applied, specified by the identifier of the settlement request.

**Complexity**: Medium > Need to implement a state machine to manage the state transitions. There is complexity to ensuring which process/identifier can be an entry point or ability to transition from one status to the next. _Note_: This requires extensive testing to ensure that the transitions are handled correctly.

**Uncertainty**: Low > The state transition requirements are clearly defined.

---

**Dependencies**:
- N/A

**Tasks**:
- [x] TBD [ @? ]

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [x] TBD

## **Follow-up**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by koekiebox** [comment]
Example of Settlement batch status transition.
All required criteria met.

## OPEN to CLOSED:
<img width="1450" alt="image" src="https://github.com/mojaloop/project/assets/1992108/ff648d81-fbf1-4be3-aec5-79992229dc55">
to new status CLOSED after Close action:
<img width="1436" alt="image" src="https://github.com/mojaloop/project/assets/1992108/80ed58d7-b75d-4d67-b3df-492d3888f5aa">

## TO DISPUTE:
<img width="1443" alt="image" src="https://github.com/mojaloop/project/assets/1992108/29947184-582a-4e93-97a5-c9050d9c5d3a">
The disputed batch will not be allowed to settle.

## FROM BEING DISPUTED TO CLOSED:
<img width="1440" alt="image" src="https://github.com/mojaloop/project/assets/1992108/327b7b14-1432-4035-96dc-440bc3bd9ae4">

## Settlement batches, with the ability to see individual settlement transfers for a batch:
<img width="1438" alt="image" src="https://github.com/mojaloop/project/assets/1992108/0cd428b4-35a8-4bc0-93dd-a9b937a55549">


# Test cases:
https://github.com/mojaloop/settlements-bc/blob/7c55c3cc4bc483e9145a5052afe85d2661709fb2/packages/domain-lib/test/unit/index.test.ts#L1015
