### ISSUE TITLE
Settlement v3 - Cancel execution of a settlement

### ISSUE THREAD

**Issue by tselit** [mojaloop/project#3372]
## **Goal**:
`As a` hub administrator

`I want to` be able to cancel a previously requested settlement
  
`so that` all the batches whose status was marked as **AWAITING_SETTLEMENT** by the settlement request should have that status changed to **CLOSED**.

**Acceptance Criteria**:
- [x] The settlement to be cancelled should be identified by its unique identifier. The unique identifier for settlement is one of the results from executing a settlement request,  defined in this related ticket [Settlement v3 - Request settlement execution](https://github.com/mojaloop/project/issues/3370).
- [x] The consequence of this settlement cancellation request is that all the batches whose status was marked as AWAITING_SETTLEMENT by the settlement request should have that status changed to CLOSED.

**Complexity**: Medium > Check the original settlement request ID.
**Uncertainty**: Low > Requirements are clear and well documented.

---

**Dependencies**:
- The requirements for a settlement request identifier are detailed in this related ticket [Settlement v3 - Request settlement execution](https://github.com/mojaloop/project/issues/3370)

**Tasks**:
- [x] TBD [ @? ]

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [x] TBD

## **Follow-up**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by koekiebox** [comment]
Example of Settlement matrix from `AWAITING_SETTLEMENT` to `CLOSED` status.

All required criteria met.

## IDLE to LOCKED:
<img width="1716" alt="image" src="https://github.com/mojaloop/project/assets/1992108/5e3fc768-2e59-4e50-abff-8d5b83dc23ae">

## LOCKED matrix and batch in AWAITING_SETTLEMENT:
<img width="1719" alt="image" src="https://github.com/mojaloop/project/assets/1992108/994eb6a2-196e-4771-89ad-3c9e33a1c45e">

## LOCKED matrix with batches in AWAITING_SETTLEMENT cancelled:
<img width="1728" alt="image" src="https://github.com/mojaloop/project/assets/1992108/854fb363-fabd-4d91-a483-2483adf4a575">


# Test cases:
https://github.com/mojaloop/settlements-bc/blob/7c55c3cc4bc483e9145a5052afe85d2661709fb2/packages/domain-lib/test/unit/index.test.ts#L1015
