### ISSUE TITLE
Settlement v3 - Confirm the execution of a settlement

### ISSUE THREAD

**Issue by tselit** [mojaloop/project#3373]
## **Goal**:
`As a` hub administrator

`I want to` be able to confirm a settlement which has previously been requested, as described in [Settlement v3 - Request settlement execution](https://github.com/mojaloop/project/issues/3370),
  
`so that` I can implement maker/checker functionality on settlement execution if required, OR 
so that I can review the contents of the settlement, and confirm the action.

**Acceptance Criteria**:
- [x] The batch may be settled, but only via confirmation of the original settlement request which had set the status of the settlement batch to AWAITING_SETTLEMENT. 
- [x] The consequence of this request should be that all the batches whose status was marked as **AWAITING_SETTLEMENT** by the settlement request should have that status changed to **SETTLED**.

**Complexity**: Low > This uses a settlement identifier (which should already exist, by this point), so the implementation is simpler.
**Uncertainty**: Low > Requirement is clear.

---

**Dependencies**:
- This ticket is related to [Settlement v3 - Request settlement execution (https://github.com/mojaloop/project/issues/3370)

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by koekiebox** [comment]
Example of Settlement matrix lock and then settled.
All required criteria met.

## Matrix with closed batches:
<img width="1712" alt="image" src="https://github.com/mojaloop/project/assets/1992108/97955bd7-76aa-4500-8b43-7b6c1cb1c651">

## Locked in order to put batches in AWAITING_SETTLEMENT status:
<img width="1728" alt="image" src="https://github.com/mojaloop/project/assets/1992108/adde84cb-3f53-421a-ba8f-341e6078f07c">

## Participant POSITION account effected when clearing occured:
<img width="1426" alt="image" src="https://github.com/mojaloop/project/assets/1992108/38e870c4-d48d-463f-8994-f4d7924a882d">


## Settle the LOCKED matrix with AWAITING_SETTLEMENT batches:
<img width="1721" alt="image" src="https://github.com/mojaloop/project/assets/1992108/c9b3187c-a994-4efc-a4c4-0ca880e9799f">
Matrix is now FINALIZED and batches settled.

## Funds have moved from the POSITION participant account to the LIQUIDITY account:
<img width="1435" alt="image" src="https://github.com/mojaloop/project/assets/1992108/99598e49-6f06-45e4-85cb-b361b862ecd0">



# Test cases:
https://github.com/mojaloop/settlements-bc/blob/7c55c3cc4bc483e9145a5052afe85d2661709fb2/packages/domain-lib/test/unit/index.test.ts#L1015
