### ISSUE TITLE
Settlement v3 - Identify the settlement batch to which a transfer belongs

### ISSUE THREAD

**Issue by tselit** [mojaloop/project#3374]
## **Goal**:
`As a` hub administrator

`I want to` be able to identify the settlement batch to which a transfer belongs, specified by its transfer ID,
  
`so that` I can take action on the settlement batch (e.g. in case of dispute). 

**Acceptance Criteria**:
- [x] The ability to identify the settlement batch to which a transfer belongs.

**Complexity**: Low > This is a fairly straight-forward look-up, based on an identifier. 
**Uncertainty**: Low > Clear requirements.

---

**Dependencies**:
- N/A

**Tasks**:
- [x] TBD [ @? ]

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [x] TBD

## **Follow-up**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by koekiebox** [comment]
Example of Settlement batch for a transfer.
All required criteria met.

## View of a transfer with the ability to lookup in Settlement:
<img width="1432" alt="image" src="https://github.com/mojaloop/project/assets/1992108/818f4419-f315-4d39-b0e1-14c0a180f06c">

## The batch that the transfer was allocated to:
<img width="1433" alt="image" src="https://github.com/mojaloop/project/assets/1992108/61304047-c3b1-4a62-af94-aad7820586fd">




# Test cases:
https://github.com/mojaloop/settlements-bc/blob/7c55c3cc4bc483e9145a5052afe85d2661709fb2/packages/domain-lib/test/unit/index.test.ts#L1015
## and integration tests:
https://github.com/mojaloop/settlements-bc/blob/7c55c3cc4bc483e9145a5052afe85d2661709fb2/packages/api-svc/test/unit/settlement_api_svc_route.test.ts
