### ISSUE TITLE
Settlement v3 - Unreported batches

### ISSUE THREAD

**Issue by tselit** [mojaloop/project#3375]
## **Goal**:
`As a` hub administrator

`I want to` be able to see any settlement batches which have not been included in at least one settlement report
  
`so that` I can ensure that there are no settlement batches which have escaped the settlement process. 

**Acceptance Criteria**:
- [x] Optional: The ability to select a date range for the report.
- [x] The ability to select one or more batch status values to determine which settlement batches get included in the report.
- [x] Output: For each entry, display the settlement batch name and its current status.

**Complexity**: Low > Retrieving batches that are unreported can be achieved with a fairly simple query/lookup.
**Uncertainty**: Low > The requirement is clear, and well understood.

---

**Dependencies**:
- N/A

**Tasks**:
- [x] TBD [ @? ]

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [x] TBD

## **Follow-up**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by koekiebox** [comment]
Example of Settlement batch lookup.

All required criteria met:
- Date range lookup
- filter by status
- batch name and status shown in search result

<img width="1726" alt="image" src="https://github.com/mojaloop/project/assets/1992108/c4606bd3-15a3-41cb-9c97-23b39988af78">

Batch status filtering (one or more in the backend):
<img width="1083" alt="image" src="https://github.com/mojaloop/project/assets/1992108/cba51932-e30c-4a17-97a2-81f9fb4e13fe">

# Test case:
https://github.com/mojaloop/settlements-bc/blob/7c55c3cc4bc483e9145a5052afe85d2661709fb2/packages/domain-lib/test/unit/index.test.ts#L1015
