### ISSUE TITLE
Settlement v3 - Unsettled settlement reports

### ISSUE THREAD

**Issue by tselit** [mojaloop/project#3376]
## **Goal**:
`As a` hub administrator

`I want to` be able to identify any settlement reports which have either not been settled, or have only been partially settled
  
`so that` I can take action, where appropriate, to ensure that all transfers are settled. 

**Acceptance Criteria**:
- [x] The ability to specify a time period/range for the report.
- [x] The result shows all settlement reports whose settlement batches have timestamps that fall within the time range selected.
- [x] The result shows all settlement reports that have either not been settled, or have only been partially settled.

**Complexity**: Low > Retrieving unsettled settled reports can be achieved with a fairly simple query/lookup.
**Uncertainty**: Low > The requirement is clear, and well understood.

---

**Dependencies**:
- N/A

**Tasks**:
- [x] TBD [ @? ]

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [x] TBD

## **Follow-up**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by koekiebox** [comment]
Example of Settlement matrix view.
All required criteria met.

## Date range supported batch lookup:
<img width="1720" alt="image" src="https://github.com/mojaloop/project/assets/1992108/37292b82-314c-4bbc-a6f5-be723e8c32c4">
- All batches included that fall under the selected date range.
- The result shows the batch statues that are included.

# Test cases:
https://github.com/mojaloop/settlements-bc/blob/7c55c3cc4bc483e9145a5052afe85d2661709fb2/packages/domain-lib/test/unit/index.test.ts#L1015
