### ISSUE TITLE
Mojaloop Helm release v15.1.0

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#3379]
## **Goal**:
`As a` ML OSS adopter

`I want to` have a Mojaloop release v15.1.0 that is successfully validated by the Golden path tests
  
`so that` I can adopt and use a version of Mojaloop Switch services bundle that is tested and contains the latest features enhancements and bug fixes added in PI-21 / PI-20

**Acceptance Criteria**:
- [x] Update "APP VERSION" for each chart.yaml
- [x] Helm RC Release is validated on Moja2 to achieve 100% result with TTK GoldenPath 
- [x] Helm RC Release is validated with PISP provisioning and test collection (TTK) with 100%
- [x] Helm RC Release is validated with Bulk test collection (TTK) with 100%
- [x] QA (Golden path) on deployments done on AWS Moja2 environment is done
- [x] Bugs are logged based on observations, failures
- [x] Bugs logged are fixed if critical to make subsequent releases in individual services (or Helm)
- [x] All the changes needed for supporting the Helm Release are done
- [x] Helm chart is published
- [x] Release notes are published
- [x] Test cases are published (TTK)
- [x] TTK tests run successfully as Post-Hook jobs and Tests

**Notes**:
- Request to pay enhancements / fixes to be included along with support for special characters in passwords (for services that didn't support this earlier in v15.0.0)

**Complexity**: Medium - Involves all core and supporting services
**Uncertainty**: Medium

---

**Tasks**:
- [x] Initial PR with changes for RC
  - [x] Initial PR review
  - [x] Deploy, validate, fix issues, redeploy
  - [x] With stable deployment test Golden path
- [x] Validate PISP test provisioning and test collections (TTK) 
- [x] Identify issues with QA Scripts if any - fix them and retest
- [x] QA for bugs, regressions, log them
- [x] Fix bugs logged if critical
- [x] Deploy, validate on AWS Moja2
- [x] Validate with TTK GP collection
- [x] TTK test-cases repo Release is published
- [x] Release notes for helm RC is drafted
  - [x] Guidance for migration from Release (may have to be a separate story if sufficiently big / complex)
- [x] Update release notes with Upgrade Strategy Guide link
- [x] Helm Release is published
- [x] Deployment of released Helm on **Moja2**
  - [x] Helm release is deployed on **Moja2** successfully
  - [x] Regression testing on Moja2 using TTK collections
    - [x] GP collection
    - [x] Core Bulk collection
    - [x] Third-party collection
    - [x] SDK Bulk collection
    - [x] SDK R2P collection
  - [x] Validation using CGS Golden path regression tests etc on Moja2
  - [x] Test upgradability from previous release
- [x] Deployment of released Helm on **Moja1**
  - [x] Helm release is deployed on **Moja1** successfully
  - [x] Validation using Golden path regression tests etc on Moja1
    - [x] GP collection
    - [x] Core Bulk collection
    - [x] Third-party collection
    - [x] SDK Bulk collection
  - [x] Validation using CGS Golden path regression tests etc on Moja1
  - [x] Validate daily cronJobs on Moja1 for GP and Cleanup scripts

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] TTK Tests pass
- [x] Code Style & Coverage meets standards
- [x] Release notes are verified

## **Pull Requests**:
- https://github.com/mojaloop/helm/pull/565
- https://github.com/mojaloop/helm/pull/569
- https://github.com/mojaloop/helm/pull/570
- https://github.com/mojaloop/helm/pull/571
- https://github.com/mojaloop/helm/pull/572
- https://github.com/mojaloop/helm/pull/573
- https://github.com/mojaloop/helm/compare/81a5189e065ba34ca2a287b4e42d0e5621a924a4...18a7b43d33f9f927d6dea2c5bbdc7f301679ea7f
- https://github.com/mojaloop/testing-toolkit-test-cases/pull/121
- https://github.com/mojaloop/testing-toolkit-test-cases/pull/122
- https://github.com/mojaloop/testing-toolkit-test-cases/pull/123
- https://github.com/mojaloop/testing-toolkit-test-cases/pull/124
- https://github.com/mojaloop/testing-toolkit-test-cases/pull/125

## **Follow-up**:

**Dependencies**:
- N/A

## **Accountability**:
- Owner: 
- QA/Review: @mdebarros @elnyry-sam-k @vijayg10

**Comment by mdebarros** [comment]
## Test Results

![Screenshot 2023-06-21 at 14 17 01](https://github.com/mojaloop/project/assets/11392873/504380e3-d1f6-46f0-944e-25978cb4f7c1)

## Test Reports

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Standard Provisioning Collection
Environment: moja2.test.mojaloop.live@15.1.0-16084.99faae8
Total assertions: 346
Passed assertions: 346
Failed assertions: 0
Total requests: 343
Total test cases: 37
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 11:17:18 GMT
Completed time: 2023-06-21T11:18:27.217Z
Runtime duration: 68591 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-standard_provisioning_collection-2023-06-21T11%3A18%3A27.217Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP Tests
Environment: moja2.test.mojaloop.live@15.1.0-16084.99faae8
Total assertions: 2556
Passed assertions: 2556
Failed assertions: 0
Total requests: 610
Total test cases: 131
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 11:18:35 GMT
Completed time: 2023-06-21T11:21:38.373Z
Runtime duration: 182404 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-gp_tests-2023-06-21T11%3A21%3A38.373Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Bulk Tests
Environment: moja2.test.mojaloop.live@15.1.0-16084.99faae8
Total assertions: 337
Passed assertions: 337
Failed assertions: 0
Total requests: 63
Total test cases: 16
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 11:21:49 GMT
Completed time: 2023-06-21T11:24:01.181Z
Runtime duration: 131899 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-bulk_tests-2023-06-21T11%3A24%3A01.181Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Thirdparty Provisioning Collection
Environment: moja2.test.mojaloop.live@15.1.0-16084.99faae8
Total assertions: 137
Passed assertions: 137
Failed assertions: 0
Total requests: 135
Total test cases: 15
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 11:24:09 GMT
Completed time: 2023-06-21T11:24:34.699Z
Runtime duration: 24941 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-thirdparty_provisioning_collection-2023-06-21T11%3A24%3A34.699Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Thirdparty Tests
Environment: moja2.test.mojaloop.live@15.1.0-16084.99faae8
Total assertions: 28
Passed assertions: 28
Failed assertions: 0
Total requests: 20
Total test cases: 8
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 11:24:43 GMT
Completed time: 2023-06-21T11:24:48.385Z
Runtime duration: 5153 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-thirdparty_tests-2023-06-21T11%3A24%3A48.385Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: SDK Bulk Provisioning Collection
Environment: moja2.test.mojaloop.live@15.1.0-16084.99faae8
Total assertions: 123
Passed assertions: 123
Failed assertions: 0
Total requests: 119
Total test cases: 13
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 11:24:55 GMT
Completed time: 2023-06-21T11:25:21.515Z
Runtime duration: 25522 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-sdk_bulk_provisioning_collection-2023-06-21T11%3A25%3A21.515Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: SDK Bulk Tests
Environment: moja2.test.mojaloop.live@15.1.0-16084.99faae8
Total assertions: 217
Passed assertions: 217
Failed assertions: 0
Total requests: 45
Total test cases: 22
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 11:25:30 GMT
Completed time: 2023-06-21T11:28:03.081Z
Runtime duration: 152973 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-sdk_bulk_tests-2023-06-21T11%3A28%3A03.081Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: SDK Request To Pay Tests
Environment: moja2.test.mojaloop.live@15.1.0-16084.99faae8
Total assertions: 27
Passed assertions: 27
Failed assertions: 0
Total requests: 2
Total test cases: 1
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 11:28:12 GMT
Completed time: 2023-06-21T11:28:13.198Z
Runtime duration: 1106 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-sdk_r2p_tests-2023-06-21T11%3A28%3A13.198Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Post Cleanup
Environment: moja2.test.mojaloop.live@15.1.0-16084.99faae8
Total assertions: 49
Passed assertions: 49
Failed assertions: 0
Total requests: 15
Total test cases: 4
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 11:28:20 GMT
Completed time: 2023-06-21T11:28:31.243Z
Runtime duration: 10611 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-post_cleanup-2023-06-21T11%3A28%3A31.243Z.html)

**Comment by mdebarros** [comment]
## Test Results

![Screenshot 2023-06-21 at 15 23 30](https://github.com/mojaloop/project/assets/11392873/b0225c55-cf72-42e6-a353-b27d28fc919d)

Tested on Moja2 upgraded from v15.0.0 to v15.1.0:

```bash
❯ helm -n moja2 history moja2
REVISION        UPDATED                         STATUS          CHART                           APP VERSION                                                                                                                                                                                                                                                                                                                                                                                                                     DESCRIPTION     
1               Wed Jun 21 12:39:56 2023        superseded      mojaloop-15.0.0                 ml-api-adapter: v14.0.0; central-ledger: v17.0.3; account-lookup-service: v13.0.0; quoting-service: v15.0.2; central-settlement: v15.0.0; bulk-api-adapter: v15.0.3; transaction-requests-service: v14.0.1; simulator: v12.0.0; mojaloop-simulator: v14.0.1; sdk-scheme-adapter: v22.0.1; auth-service: v14.0.0; consent-oracle: v0.2.0; thirdparty-sdk: v13.0.2; ml-testing-toolkit: v16.0.1; ml-testing-toolkit-ui: v15.2.1;  Install complete
2               Wed Jun 21 13:00:05 2023        deployed        mojaloop-15.1.0-16084.99faae8   ml-api-adapter: v14.0.0; central-ledger: v17.0.3; account-lookup-service: v13.0.0; quoting-service: v15.0.2; central-settlement: v15.0.0; bulk-api-adapter: v15.0.3; transaction-requests-service: v14.0.1; simulator: v12.0.0; mojaloop-simulator: v14.0.1; sdk-scheme-adapter: v23.0.1; auth-service: v14.0.0; consent-oracle: v0.2.0; thirdparty-sdk: v13.0.2; ml-testing-toolkit: v16.0.1; ml-testing-toolkit-ui: v15.2.1;  Upgrade complete
```


## Test Reports

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Standard Provisioning Collection
Environment: moja2.test.mojaloop.live@15.1.0-16084.99faae8
Total assertions: 346
Passed assertions: 346
Failed assertions: 0
Total requests: 343
Total test cases: 37
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 13:06:11 GMT
Completed time: 2023-06-21T13:07:22.358Z
Runtime duration: 70898 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-standard_provisioning_collection-2023-06-21T13%3A07%3A22.358Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP Tests
Environment: moja2.test.mojaloop.live@15.1.0-16084.99faae8
Total assertions: 2556
Passed assertions: 2556
Failed assertions: 0
Total requests: 610
Total test cases: 131
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 13:07:31 GMT
Completed time: 2023-06-21T13:10:40.889Z
Runtime duration: 189604 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-gp_tests-2023-06-21T13%3A10%3A40.889Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Bulk Tests
Environment: moja2.test.mojaloop.live@15.1.0-16084.99faae8
Total assertions: 337
Passed assertions: 337
Failed assertions: 0
Total requests: 63
Total test cases: 16
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 13:10:51 GMT
Completed time: 2023-06-21T13:13:01.263Z
Runtime duration: 129859 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-bulk_tests-2023-06-21T13%3A13%3A01.263Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Thirdparty Provisioning Collection
Environment: moja2.test.mojaloop.live@15.1.0-16084.99faae8
Total assertions: 137
Passed assertions: 137
Failed assertions: 0
Total requests: 135
Total test cases: 15
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 13:13:10 GMT
Completed time: 2023-06-21T13:13:36.148Z
Runtime duration: 25443 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-thirdparty_provisioning_collection-2023-06-21T13%3A13%3A36.148Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Thirdparty Tests
Environment: moja2.test.mojaloop.live@15.1.0-16084.99faae8
Total assertions: 28
Passed assertions: 28
Failed assertions: 0
Total requests: 20
Total test cases: 8
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 13:13:44 GMT
Completed time: 2023-06-21T13:13:50.386Z
Runtime duration: 5959 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-thirdparty_tests-2023-06-21T13%3A13%3A50.386Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: SDK Bulk Provisioning Collection
Environment: moja2.test.mojaloop.live@15.1.0-16084.99faae8
Total assertions: 123
Passed assertions: 123
Failed assertions: 0
Total requests: 119
Total test cases: 13
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 13:13:58 GMT
Completed time: 2023-06-21T13:14:26.198Z
Runtime duration: 27411 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-sdk_bulk_provisioning_collection-2023-06-21T13%3A14%3A26.198Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: SDK Bulk Tests
Environment: moja2.test.mojaloop.live@15.1.0-16084.99faae8
Total assertions: 217
Passed assertions: 217
Failed assertions: 0
Total requests: 45
Total test cases: 22
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 13:14:33 GMT
Completed time: 2023-06-21T13:17:06.660Z
Runtime duration: 152795 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-sdk_bulk_tests-2023-06-21T13%3A17%3A06.660Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: SDK Request To Pay Tests
Environment: moja2.test.mojaloop.live@15.1.0-16084.99faae8
Total assertions: 27
Passed assertions: 27
Failed assertions: 0
Total requests: 2
Total test cases: 1
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 13:17:15 GMT
Completed time: 2023-06-21T13:17:16.397Z
Runtime duration: 1198 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-sdk_r2p_tests-2023-06-21T13%3A17%3A16.397Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Post Cleanup
Environment: moja2.test.mojaloop.live@15.1.0-16084.99faae8
Total assertions: 49
Passed assertions: 49
Failed assertions: 0
Total requests: 15
Total test cases: 4
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 13:17:22 GMT
Completed time: 2023-06-21T13:17:33.536Z
Runtime duration: 10604 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-post_cleanup-2023-06-21T13%3A17%3A33.536Z.html)

**Comment by mdebarros** [comment]
## CronJob Reports

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP CronJob
Environment: moja2.test.mojaloop.live@15.1.0-16084.99faae8
Total assertions: 2556
Passed assertions: 2556
Failed assertions: 0
Total requests: 610
Total test cases: 131
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 08:00:02 GMT
Completed time: 2023-06-21T08:03:05.334Z
Runtime duration: 182420 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-cronjob_tests-2023-06-21T08%3A03%3A05.334Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP Cleanup
Environment: moja2.test.mojaloop.live@15.1.0-16084.99faae8
Total assertions: 49
Passed assertions: 49
Failed assertions: 0
Total requests: 15
Total test cases: 4
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 08:15:02 GMT
Completed time: 2023-06-21T08:15:13.096Z
Runtime duration: 10344 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-cronjob_cleanup-2023-06-21T08%3A15%3A13.096Z.html)

**Comment by mdebarros** [comment]
## Test Results

![Screenshot 2023-06-21 at 19 11 31](https://github.com/mojaloop/project/assets/11392873/e4f66a21-ccf2-424c-9391-44e3df648882)

```
❯ helm -n moja2 list
NAME   	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                          	APP VERSION
backend	moja2    	1       	2023-06-21 16:23:31.248050594 +0000 UTC	deployed	example-mojaloop-backend-15.0.0	nginx: 4.4.2 ; mysql: 9.4.1; kafka: 19.0.2; mongodb: 13.3.1; redis:17.3.7
moja2  	moja2    	2       	2023-06-21 16:47:49.74004456 +0000 UTC 	deployed	mojaloop-15.1.0                	ml-api-adapter: v14.0.0; central-ledger: v17.0.3; account-lookup-service: v14.1.0; quoting-service: v15.0.2; central-settlement: v15.0.0; bulk-api-adapter: v15.0.3; transaction-requests-service: v14.1.0; simulator: v12.0.0; mojaloop-simulator: v14.0.1; sdk-scheme-adapter: v23.0.1; auth-service: v14.0.0; consent-oracle: v0.2.0; thirdparty-sdk: v13.0.2; ml-testing-toolkit: v16.1.1; ml-testing-toolkit-ui: v15.4.0;
```

## Test Reports

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Standard Provisioning Collection
Environment: moja2.test.mojaloop.live@15.1.0
Total assertions: 346
Passed assertions: 346
Failed assertions: 0
Total requests: 343
Total test cases: 37
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 16:52:35 GMT
Completed time: 2023-06-21T16:53:43.683Z
Runtime duration: 68371 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-standard_provisioning_collection-2023-06-21T16%3A53%3A43.683Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP Tests
Environment: moja2.test.mojaloop.live@15.1.0
Total assertions: 2556
Passed assertions: 2556
Failed assertions: 0
Total requests: 610
Total test cases: 131
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 16:53:51 GMT
Completed time: 2023-06-21T16:56:55.063Z
Runtime duration: 183626 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-gp_tests-2023-06-21T16%3A56%3A55.063Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Bulk Tests
Environment: moja2.test.mojaloop.live@15.1.0
Total assertions: 337
Passed assertions: 337
Failed assertions: 0
Total requests: 63
Total test cases: 16
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 16:57:05 GMT
Completed time: 2023-06-21T16:59:31.257Z
Runtime duration: 145936 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-bulk_tests-2023-06-21T16%3A59%3A31.257Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Thirdparty Provisioning Collection
Environment: moja2.test.mojaloop.live@15.1.0
Total assertions: 137
Passed assertions: 137
Failed assertions: 0
Total requests: 135
Total test cases: 15
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 16:59:39 GMT
Completed time: 2023-06-21T17:00:04.786Z
Runtime duration: 25049 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-thirdparty_provisioning_collection-2023-06-21T17%3A00%3A04.786Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Thirdparty Tests
Environment: moja2.test.mojaloop.live@15.1.0
Total assertions: 28
Passed assertions: 28
Failed assertions: 0
Total requests: 20
Total test cases: 8
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 17:00:12 GMT
Completed time: 2023-06-21T17:00:18.215Z
Runtime duration: 5537 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-thirdparty_tests-2023-06-21T17%3A00%3A18.215Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: SDK Bulk Provisioning Collection
Environment: moja2.test.mojaloop.live@15.1.0
Total assertions: 123
Passed assertions: 123
Failed assertions: 0
Total requests: 119
Total test cases: 13
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 17:00:25 GMT
Completed time: 2023-06-21T17:00:51.515Z
Runtime duration: 26068 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-sdk_bulk_provisioning_collection-2023-06-21T17%3A00%3A51.515Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: SDK Bulk Tests
Environment: moja2.test.mojaloop.live@15.1.0
Total assertions: 217
Passed assertions: 217
Failed assertions: 0
Total requests: 45
Total test cases: 22
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 17:00:59 GMT
Completed time: 2023-06-21T17:03:35.596Z
Runtime duration: 155785 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-sdk_bulk_tests-2023-06-21T17%3A03%3A35.596Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: SDK Request To Pay Tests
Environment: moja2.test.mojaloop.live@15.1.0
Total assertions: 27
Passed assertions: 27
Failed assertions: 0
Total requests: 2
Total test cases: 1
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 17:03:43 GMT
Completed time: 2023-06-21T17:03:44.680Z
Runtime duration: 1002 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-sdk_r2p_tests-2023-06-21T17%3A03%3A44.680Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Post Cleanup
Environment: moja2.test.mojaloop.live@15.1.0
Total assertions: 49
Passed assertions: 49
Failed assertions: 0
Total requests: 15
Total test cases: 4
Passed percentage: 100.00%
Started time: Wed, 21 Jun 2023 17:03:51 GMT
Completed time: 2023-06-21T17:04:01.713Z
Runtime duration: 10603 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-post_cleanup-2023-06-21T17%3A04%3A01.713Z.html)

**Comment by mdebarros** [comment]
## Test Results

```bash
❯ helm -n moja1 list
NAME   	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                          	APP VERSION
backend	moja1    	1       	2023-06-22 13:43:10.971953587 +0000 UTC	deployed	example-mojaloop-backend-15.0.0	nginx: 4.4.2 ; mysql: 9.4.1; kafka: 19.0.2; mongodb: 13.3.1; redis:17.3.7
moja1  	moja1    	1       	2023-06-22 13:45:46.650808402 +0000 UTC	deployed	mojaloop-15.1.0                	ml-api-adapter: v14.0.0; central-ledger: v17.0.3; account-lookup-service: v14.1.0; quoting-service: v15.0.2; central-settlement: v15.0.0; bulk-api-adapter: v15.0.3; transaction-requests-service: v14.1.0; simulator: v12.0.0; mojaloop-simulator: v14.0.1; sdk-scheme-adapter: v23.0.1; auth-service: v14.0.0; consent-oracle: v0.2.0; thirdparty-sdk: v13.0.2; ml-testing-toolkit: v16.1.1; ml-testing-toolkit-ui: v15.4.0;
```

## Test Reports

```
```

**Comment by mdebarros** [comment]
## CronJob Test Reports

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP CronJob
Environment: moja1.test.mojaloop.live@15.1.0
Total assertions: 2556
Passed assertions: 2556
Failed assertions: 0
Total requests: 610
Total test cases: 131
Passed percentage: 100.00%
Started time: Fri, 23 Jun 2023 08:00:02 GMT
Completed time: 2023-06-23T08:03:04.913Z
Runtime duration: 182193 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-cronjob_tests-2023-06-23T08%3A03%3A04.913Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP Cleanup
Environment: moja1.test.mojaloop.live@15.1.0
Total assertions: 49
Passed assertions: 49
Failed assertions: 0
Total requests: 15
Total test cases: 4
Passed percentage: 100.00%
Started time: Fri, 23 Jun 2023 08:15:02 GMT
Completed time: 2023-06-23T08:15:12.891Z
Runtime duration: 10288 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-cronjob_cleanup-2023-06-23T08%3A15%3A12.891Z.html)

**Comment by mdebarros** [comment]
<img width="449" alt="Screenshot 2023-06-23 at 12 16 27" src="https://github.com/mojaloop/project/assets/11392873/57f6e51c-9f88-4877-9db8-98195052a675">

[View](https://app.circleci.com/jobs/github/mojaloop/helm/16172)
