### ISSUE TITLE
5.1.2.1 Test Kafka for Reliable Messaging

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#338]
**Goal**:
As a developer
I would like to _test Kafka for Reliable Messaging_
so that Reliability issues in messaging are addressed

**Note**:
Approach to testing could include testing with the Switch deployment or the Kafkapoc project; Eventually it could be a combination of both.

**Tasks**:
- [ ] Test, Investigate Kafka stability issues with the kafka consumers over long periods of time (consumers seem to crash).
- [ ] Consider https://github.com/yahoo/kafka-manager as an optional deployment to our helm charts so we can properly monitor kafka going forward.
- [ ] Test Message replay for non-committed messages
- [ ] Try to reproduce issues locally

**Acceptance Criteria**:
- [ ] Observations, Recommendations are documented regarding reliability issues with Kafka
- [ ] Create stories to address the issues that've been found

**Dependencies**:
- [ ] Kafka Monitoring

**Accountability**:
- Owner 
- QA/Review

**Comment by mdebarros** [comment]
Hey guys, note that we may have stability issues with the kafka consumers over long periods of time.

We have seen two cases where the consumers seem to "die" even though the pods are up and running for either the central-ledger and the ml-api-adapter
central-ledger occurrence happened just before the PI-2 demo, and @Murthy just picked up that the ml-api-adapter consumer died when testing on k8s-phoenix over the last two days.
The first occurrence pre-PI-2 demo we resolved by just restarting the pod.
we did this because there was not enough time to investigate the issue due to the impending PI-2 demo :smile:
@Murthy has re-produce this solution now with the ml-api-adapter.
We need to spend some time an investigate this stability issue once it re-occurs.
Please keep you eyes open for it, and report if you see the issue occurring on any of our environments (and even your own local setups)
This should be part of the stories to "test kafka" to determine its reliable (either a separate story or part of the proposed stories for PI3) (edited)
In addition, I also propose that we add a task/acceptance criteria to this story (possibly another story) to the Kafka reliability theme to add https://github.com/yahoo/kafka-manager as an optional deployment to our helm charts so we can properly monitor kafka going forward.
GitHub
yahoo/kafka-manager
kafka-manager - A tool for managing Apache Kafka.
If we had elk, I would perhaps consider avoiding that. But right now, I think we need something quick that can easily be used for monitoring kafka. Especially to assist with debugging any issues.

**Comment by elnyry** [comment]
As part of investigations into Performance issues and implementing findings and recommendations from the investigations, Miguel made some changes to configuration and setup that alleviate the reliability issues to some extent (though this needs to be tested); so de-prioritizing this for PI-3
