### ISSUE TITLE
[SDK] NodeJS Maintenance Upgrade for SDK-Scheme-Adapter

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3386]
## **Goal**:
`As a` Mojaloop Maintainer

`I want to` have the SDK-Scheme-Adapter using the latest NodeJS LTS version
  
`so that` the NodeJS runtime is fully supported

**Acceptance Criteria**:
- [x] SDK-Scheme-Adapter will use latest Node v18.x
- [x] CI Image Scan should pass after Nodejs upgrade to Node v18.x
- [x] CI Image Scan should select the Nodejs version from the project's nvmrc file
- [x] Upgrade dependencies to the latest version

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [x] Upgrade Nodejs version
- [x] Upgrade dependencies to latest version
- [x] Resolve CI Image Scan pipeline failure
- [x] Change CI Image Scan to use Nodejs version from nvmrc file
- [x] Cleanup of Audit CI manifest

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- https://github.com/mojaloop/sdk-scheme-adapter/pull/453
- https://github.com/mojaloop/sdk-scheme-adapter/pull/455
- https://github.com/mojaloop/sdk-scheme-adapter/pull/456

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
<img width="669" alt="Screenshot 2023-07-10 at 14 06 43" src="https://github.com/mojaloop/project/assets/11392873/ba680ad8-77ab-46ed-8ce7-593b13521bd8">

- https://mojaloop.slack.com/archives/CG3MAJZ5J/p1688989406542539
- https://mojaloop.slack.com/archives/CG3MAJZ5J/p1688990780392669
