### ISSUE TITLE
IaC V15.0.1 fix the report test pipeline

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3387]
## **Goal**:
`As a` using of the IaC deploying V15.0.1
`I want to` ensure that the legacy reports are functioning
`so that` use this release

**Acceptance Criteria**:
- [ ] Verify the IaC test reporting pipeline can be run and passes the tests.
- [ ] 

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Identify the issue
- [x] Fix the issue with security-rbac-tests
- [x] Try upgrade node in security-rbac-tests
- [x] Streamline dockerfile and CICD of security-rbac-tests

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/security-rbac-tests/pull/18
- [x] https://github.com/mojaloop/iac-aws-platform/pull/88
- [x] https://github.com/mojaloop/charts/pull/86

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
