### ISSUE TITLE
Fix the IaC v15.0.0 Third party pipeline tests

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3388]
## **Goal**:
`As a` using of the IaC deploying V15.0.0
`I want to` ensure that the legacy reports are functioning
`so that` use this release

**Acceptance Criteria**:
- [ ] Verify the IaC test PISP pipeline can be run and passes the tests.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/124

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
Tested the mojaloop deployment v15.0.0 with new patched version of test cases. All tests are passed. Here are the results.
