### ISSUE TITLE
[25] 5.2.11-02 Create Snapshot/Releases for 3.5.0

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#339]
**Goal**:
As a developer
I would like to _Create Snapshot/Releases for 3.5.0_
so that artefacts are published and deployments can be done.

**Tasks**:
- [x] Create new helm-deploy branch for PI3.5 [ ]
- [x] Configure new helm-deploy branch for PI3.5 [ ]
- [x] Create/Publish Snapshot/Releases for 3.5.0 for ML API [ ]
- [x] Create/Publish Snapshot/Releases for 3.5.0 for Central Ledger [ ]
- [x] Configure PI3.5 Callback URIs for ML API [ ] 
- [x] Deploy PI3.5 release to AWS K8s cluster [ ]
- [x] Test helm-deploy branch for PI3.5 [ ]

**Acceptance Criteria**:
- [x] Snapshots/Releases for 3.5.0 created on GitHub for ML API
- [x] Snapshots/Releases for 3.5.0 created on GitHub for Central Ledger
- [x] Snapshots/Releases for 3.5.0 created on DockerHub for ML API
- [x] Snapshots/Releases for 3.5.0 created on DockerHub for Central Ledger
- [x] Snapshots/Releases for 3.5.0 deployed to `mojatest` namespaces on AWS K8s phoenix environment

**Dependencies**:
- [x] Relevant PRs are merged to develop so that codebase can be deployed

**Accountability**:
- Owner @mdebarros 
- QA/Review
