### ISSUE TITLE
Performance Maintenance characterisation for ALS - Add instrumentation

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3396]
## **Goal**:
`As a` Mojaloop Hub adopter
`I want to` know the isolated performance characterisation of the ALS  
`so that` I can design an environment that depends on it's output.

**Acceptance Criteria**:
- [x] Verify that the ALS has metrics endpoints using existing metric endpoint methods added for 
   - [x] **GET** \parties & \parties\{SubId}
   - [x] **PUT** \parties & \parties\{SubId}
   - [x] **POST** \participants & \participants\{SubId}
   - [x] **PUT** \participants & \participants\{SubId}
   - [x] **GET** \participants & \participants\{SubId}
   - [x] **DELETE** \participants & \participants\{SubId}
   - [x] **POST** \oracles
   - [x] **PUT** \oracles
   - [x] **GET** \oracles
   - [x] **DELETE** \oracles
   
**Note**
Get participants has metrics, but get parties hasn't.
Need to add the metrics endpoint in the same way that it has been previously done.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Find the gaps in instrumentation
- [x] Add missing /metrics endpoint
- [x] Add metrics to all the missing operations
- [x] Create a release

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/account-lookup-service/pull/457

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Regarding this @PaulGregoryBaker 

The following will need to be mocked :

Central ledger
Oracle
Get endpoints
Payee DFSP (need to decide how to do this)

I think mocking the Payee FSP is fine but I think to get a good understanding, we need the central-ledger running to cater for the Get calls from ALS, otherwise it'll be incomplete more so because this is not an external function (such as the call to the DFSP) .. (And the oracle we use thats legacy-sim based should already be light-weight so we should consider continuing with that)..

**Comment by vijayg10** [comment]
https://github.com/mojaloop/account-lookup-service/releases/tag/v14.2.0
