### ISSUE TITLE
Performance Maintenance characterisation for ALS - Grafana Dashboards

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3399]
## **Goal**:
`As a` Mojaloop Hub adopter
`I want to` know the isolated performance characterisation of the ALS  
`so that` I can design an environment that depends on it's output.

**Acceptance Criteria**:
- [x] Verify that the ALS has a Grafana metrics dashboard.
   - [x] Verify that egress metrics are added
   - [x] Verify that ingress metrics are added
   - [x] Domain logic
 - [x] Total count of success and failures
 - [x] Total count of requests
 - [x] Node specific information
 - [x] Kubernetes specific information

**Note**
Depending on how this story plays out, there may be an opportunity to scale out to larger deploy and run more comprehensive tests.

The following will need to be **mocked** :
1. Central ledger
2. Oracle
3. Get endpoints
4. Payee DFSP (need to decide how to do this)

Considering using the **TTK** for these Mocks; if we do then will need to characterise the TTK.

**SDK**
Consider using the SDK for this, as the SDK would be a more realistic test.
If this is used, then the SDK will too need to be characterised.
SDK will need to be scaled for this to work.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x]  Update dashboard

**Done**
- [x] Acceptance Criteria pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/576

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
