### ISSUE TITLE
Benchmarking performance for ALS

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3400]
## **Goal**:
`As a` Mojaloop Hub adopter
`I want to` know the isolated performance characterisation of the ALS  
`so that` I can design an environment that depends on it's output.

**Acceptance Criteria**:
- [x] Verify that the transactions per second and the parallelisation is specified / identified for this test.
- [x] Verify that we run the test on two different machine size
- [x] Verify that any issues are identified and logged as stories.
- [x] Verify that the result are captured and documented

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Do it

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- https://github.com/mojaloop/ml-perf-characterization/pull/1
- https://github.com/mojaloop/account-lookup-service/pull/460
- https://github.com/mojaloop/account-lookup-service/pull/461
- https://github.com/mojaloop/central-services-shared/pull/342

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3400?planning-poker) with Zenhub @kleyow @mdebarros @vijayg10
