### ISSUE TITLE
Sandbox setup for PCH

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#3406]
## **Goal**:
`As a` fintech community member and prospective adopter / SI of Mojaloop

`I want to` have access to a Mojaloop (MLF) approved sandbox 
  
`so that` I can try out and demonstrate Mojaloop supported use-cases and develop extensions

**Acceptance Criteria**:
- [x] A fintech-sandbox is made available as requested by MLF, for PCH is setup and access provided

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [x] Deploy a IaC based sandbox environment for PCH
- [x] Handover the environment to mojaloop foundation

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
