### ISSUE TITLE
[SDK] Extend the Test collection's unhappy path tests to assert the error call-back message details

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3407]
## **Goal**:
`As a` DFSP using SDK to manage their Mojaloop Connection
`I want to` ensure that the error messages that I receive are correct and related to the error that was triggered
`so that` I can use the error message to understand the cause of the error

**Acceptance Criteria**:
- [ ] Verify that all the TTK SDK tests for Mojaloop that trigger error callbacks have asserts that check that the correct error code and message are thrown.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3407?planning-poker) with Zenhub @kleyow @mdebarros @vijayg10
