### ISSUE TITLE
2.02 Design database schema changes for Position Management - [5]

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#341]
#**Goal**:
As a contributor
I would like to _design the layout of all tables related to positions_
so that Positions Management can be addressed

**Tasks**:
- [x] Design participantPosition table [@ggrg]
- [x] Design participantLimit table [@ggrg]
- [x] Design transferState table [@ggrg]
- [x] Update sequence diagrams
  - [x] Position prepare [@ggrg]
  - [x] Position fulfil @rmothilal 
  - [x] Position abort @rmothilal

**Acceptance Criteria**:
- [x] All table designs must be approved by DA
  - [x] participantPosition
  - [x] participantLimit
  - [x] transferState
- [x] Updated ERD to reflect latest changes to the tables/fields, etc is available
- [x] Review Sequence diagrams
  - [x] Position prepare
  - [x] Position fulfil
  - [x] Position abort
  - [x] Overall sequence diagrams for Positions

**Dependencies**:
- [ ] Design Authority

**Accountability**:
- Owner 
- QA/Review @rmothilal
