### ISSUE TITLE
Spike: Investigate bug fix to enable ALS TraceStates to be propagated 

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3411]
## **Goal**:
`As a` Developer using ALS
`I want to` be able to use the tracestates to build metrics on end to end transactions
`so that` characterise the ALS

**Note**
This story is limited to investigate the cause of this issue, and devise a plan to fix.

**Acceptance Criteria**:
- [ ] Investigate and document finding as to the cause as to why the trace states are not being propagated through the ALS.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3411?planning-poker) with Zenhub @mdebarros @vijayg10 @kleyow

**Comment by vijayg10** [comment]
This is a configuration issue and can be resolved by enabling the environment variable **"EVENT_SDK_TRACEID_PER_VENDOR=false"**
