### ISSUE TITLE
Build transactions test harness

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3415]
## **Goal**:
`As a` Mojaloop Community Member considering adopting Mojaloop
So that I can understand scaling limits and associated costs in order to build my business model
`I want to` understand the performance of the core transaction processing of the current Mojaloop version  
`so that` I can understand scaling limits and associated costs in order to build my business model

**Acceptance Criteria**:
- [ ] Verify that the transactions per second performance of the transaction clearing is understood.
- [ ] Verify that the associated infrastructure costs for the chosen test environment
- [ ] Verify that the cost per transaction is calculated for the test

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Story cleaup; Feature completed and changes part of release 17.
