### ISSUE TITLE
Fix the Grafana transfer dashboards

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3416]
## **Goal**:
**As a** Mojaloop Community Member running performance testing
**I would like to** use the performance dashboards to have visibility into the inner workings of mojaloop
**So that I** can understand better which parts of the system need optimising, and then validate the optimisation

**Note:**
This story is to take the existing dashboards that was build as part of the performance stream.
[Here](https://github.com/mojaloop/helm/tree/master/monitoring/dashboards)
These dashboards need to be updated.
https://github.com/mojaloop/helm/tree/master/monitoring/dashboards/mojaloop
Backend dependency dashboards are not part of this story.

**Acceptance Criteria**:
- [ ] Check to see what Node JS dashboards are available (Maybe there is an existing board that has been maintained.)
- [ ] Verify that existing performance dashboard are functioning with updated dependencies
   - [ ] Central services - Dashboard
   - [ ] Central services Characterisation - Dashboard
   - [ ] Node JS application - Dashboard 
   - [ ] ML API adapter - Dashboard
  

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
   - [x] Central services - Dashboard
   - [x] Central services Characterisation - Dashboard
   - [x] Node JS application - Dashboard 
   - [x] ML API adapter - Dashboard

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/ml-core-test-harness/pull/14
- [ ] https://github.com/mojaloop/helm/pull/577

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3416?planning-poker) with Zenhub @kleyow @mdebarros @vijayg10 @sri-miriyala
