### ISSUE TITLE
Build transfer characterisation tests

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3417]
## **Goal**:
**As a** Mojaloop Community Member running performance testing
**I would like to** use K6 as my test runner
**So that I** can execute the performance tests

**Acceptance Criteria**:
- [ ] K6 load tests for P2P transfer
   - [ ] configure the k6 load test to specify pool of dfsps to use.
- [ ] simulated call-back handlers (web socket) for mocking the DFSPs (2 , 4 and 8 DFSP use cases will be a good start to perform the characterisation)
   - [ ] pre-generated: ILP, fulfilment, condition and amount are static
   - [ ] Docker compose define separate service for each DFSP with profiles matching the number of DFSPs (I.e. 2,4, 8)
- [ ] onboarding scripts to configure the 2, 4 & 8 DFSPs 
- [ ] Test cases
   - [ ] test case 1 : 2 DFSPs with strict payer and payee
   - [ ] test case 2 : 2 DFSPs with random payer and payee
   - [ ] test case 3 : 4 DFSPs with random payer and payee
   - [ ] test case 4 : 8 DFSPs with random payer and payee
- [ ] Update call-back handler service Grafana dashboards to display metrics by DFSP

**Note:**
1. Admin API should be characterised independently to test if the Admin API scales. 
Test this because if it is slow it will need to be mocked.
2. Need a method to isolate each handler. Maybe use a kafka proxy to do this e.g. [kafka-proxy-ws](https://github.com/microsoft/kafka-proxy-ws)

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Add profiles 2dfsp 4dfsp 8dfsp to perf docker compose [@kleyow ]
- [x] Test payer and payee pools by using our get parties test [@kleyow ]
- [x] Add 6 more dfsps and updated ttk onboarding to provision them like our initial 2 dfsps [@kleyow ]
- [x] Update the dashboard to display instance and layout for better screenshot-ability [@kleyow ]
- [x] Update handlers to handle dfsp pools [@kleyow ]
- [x] Factor out specific cbh env files from perf.env into separate env files [@kleyow ]
- [x] Add necessary handlers to callback handler service [@vijayg10 ]
- [x] Add ML services to perf docker stack [@vijayg10 ]
- [x] Prepare a K6 test case for POST /transfers [@vijayg10 ]
- [x] Make sure that a successful transfer can be done with k6 test including websocket notification [@vijayg10 ]
- [x] Split central ledger service into multiple handlers and make sure that the transfers are succussful [@kleyow ]
- [x] Observe the metrics are being populated correctly in the dashboards [@kleyow ]
- [x] Investigate if there is an existing kafka prometheus exporter and dashboard (Ex: Message lag) [@kleyow ]
- [x] Fix issue with e2e duration in callback handler dashboard [@vijayg10 ]
- [x] Deploy test stack in performance AWS machine and run tests and observe the metrics [@vijayg10 ]
- [x] Discuss the work done with team and address comments / suggestions
  - [x] Add an exporter for central-ledger mysql [@kleyow ]
  - [x] Rename the service `central-ledger` [@kleyow ]
  - [x] Disable mongodb service because there is no bulk support needed [@kleyow ]
  - [x] Change the service name of `mysql` to `mysql-cl` [@kleyow ]
  - [x] Split `ml-api-adapter` into two services `ml-api-adapter-api-svc` and `ml-api-adapter-notification-handler` [@kleyow ]
  - [x] Rename the following DFSP sims not specific to payer and payee. i.e. sim-perfsp1, sim-perfsp2...etc [@kleyow ]
  - [x] Combine both DFSP pools into one. [@kleyow ]
  - [x] Add documentation about configuring 2/4/8 DFSPs (profiles and POOLS...etc)
  - [x] Parameterise amount and currency [@vijayg10 ]
  - [x] Parameterise ilpPacket and condition [@vijayg10 ]
  - [x] Parameterise configuration of k6 tests for running specific test scenarios [@vijayg10 ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/ml-core-test-harness/pull/18

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3417?planning-poker) with Zenhub @kleyow @mdebarros @sri-miriyala
