### ISSUE TITLE
Build tests for transaction performance test harness

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3418]
## **Goal**:
**As a** Mojaloop Community Member running performance testing
**I would like to** a script that when executed will provide the environment where I can determine the TPS of transfers
**So that I** can reliably and repeatable iterate on optimising performance

**Acceptance Criteria**:
- [ ] Verify that the test case run provides the environment where TPS can be determined

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
No longer needed.
