### ISSUE TITLE
Performing the benchmark: Run the tests

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3419]
## **Goal**:
**As a** Mojaloop Community Member 
**I would like to** know the the TPS of transfers
**So that I** can reliably and repeatable iterate on optimising performance

Run the tests for 15 min with a 2 min ramp up and ramp down.

**Acceptance Criteria**:
- [x] Determine the TPS of Mojaloop transactions on the provided environment
- [x] Scenarios
   - [x] Scenarios 1: 2 DFSP - baseline (payer and payee static) without timeouts with Sims-only
   - [x] Scenarios 2: 2 DFSP - baseline (payer and payee static) without timeouts
   - [x] Scenarios 3: 2 DFSP - baseline (random payer - payee) without timeouts
   - [x] Scenarios 4: 4 DFSP - (random payer - payee) without timeouts
   - [x] Scenarios 5: 4 - 8 DFSP (random payer - payee) - without timeouts (only if the above 2 tests showed an difference)
   - [x] Scenarios 5: 2 DFSP - baseline with timeouts
- [x] Other Scenarios 
   - ~Keep alive~ (Did not do)
   - [x] Try scale (1 - 2 - 4) to check linear performance growth
   - [x] ... others that present themselves during the benchmark exercise.
- [x] Validate Scenario 2 with MySQL Query to confirm successs transfers match K6 observations
- [x] Document findings
   - [x] Create stories
   - [x] Apply Quick fixes can be applied e.g. **keep alive** 
   - [x] Export Grafana dashboards snapshots and dashboards renders (ones that are relative to the test being run.)
   - [x] Export K6 logs
- [x] Ensure that the transfers are profiled for obvious issues
   - [x] ML API Adapter service
   - [x] ML API Adapter Notification Handler
   - [x] CL Prepare Handler
   - [x] CL Position Handler
   - [x] CL Fulfil Handler
   - ~CL timeout Handler~ (Did not do)
   - [x] CL Admin service

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the ratin
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Profile the following services for obvious issues
   - [x] ML API Adapter service [@vijayg10 @kleyow ]
   - [x] ML API Adapter Notification Handler [@vijayg10  @kleyow]
   - [x] CL Prepare Handler [@vijayg10  @kleyow]
   - [x] CL Position Handler [@vijayg10 @kleyow]
   - [x] CL Fulfil Handler [@vijayg10 @kleyow]
   - [x] CL timeout Handler [@vijayg10 @kleyow]
   - [x] CL Admin service [@vijayg10 @kleyow]
 - [x] List out all the possible test scenarios
 - [x] Upgrade hardware [@mdebarros ]
 - [x] Run test scenarios and capture the results
   - [x] Test Scenarios 1
   - [x] Test Scenarios 2
   - [x] Test Scenarios 3
   - [x] Test Scenarios 4
   - [x] Test Scenarios 5
   - [x] Test Scenarios 6
   - [x] Test Scenarios 7
   - [x] Test Scenarios 8
   - [x] Test Scenarios 9
   - [x] Test Scenarios 10
   - [x] Test Scenarios 11
   - [x] Test Scenarios 12
   - [x] Test Scenarios 13
   - [x] Test Scenarios 14
   - [x] Test Scenarios 15
   - [x] Test Scenarios 16
   - [x] Test Scenarios 17
   - [x] Test Scenarios 18
   - [x] Test Scenarios 19
   - [x] Test Scenarios 20
- [x] Verify that normal Docker-Compose Functional Test-suite is still functioning
- [x] Verify that both FSPIOP-Discovery, and FSPIOP-Transfers Test-Cases are still functioning.

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- https://github.com/mojaloop/ml-perf-characterization/pull/3
- https://github.com/mojaloop/ml-core-test-harness/pull/21
- https://github.com/mojaloop/ml-api-adapter/pull/510
- https://github.com/mojaloop/central-ledger/pull/961 (to be finalised by a follow-up story)

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
