### ISSUE TITLE
2.03-1 Implement database schema changes for Position Management

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#342]
**Goal**:
As a developer
I would like to _Implement database schema changes for positions_
so that the Data Model is aligned to the design.

**Tasks**:
- [x] Implement design of participantPosition table [@ggrg]
- [x] Implement design of participantLimit table [@ggrg]
- [x] Implement design of transferState seeds [@ggrg]
- [x] Create DAO for participantPosition, participantLimit [@rmothilal]
- [x] Implement Position Management model for the initial insert of position limit & record creation of the Participant position
- [ ] ~Unit tests~
- [ ] ~Integration tests~
- [ ] ~JSDocs~
- [ ] ~Code coverage~

**Acceptance Criteria**:
- [x] All tables must be aligned to the design approved by the DA
- [x] Migration scripts generate the participantLimit and participantPosition as per design
- [x] Migration scripts insert transferState seeds as per design
- [x] Data access objects for participantPosition, participantLimit to allow for CRUD operations
- [ ] ~Position Management model to orchestrate the initial creation of participantLimit and participantPosition~

**Dependencies**:
- [x] #341 
- [ ] #317 

**Accountability**:
- Owner @rmothilal  
- QA/Review

Notes:
The remaining tasks are covered in item #378

**Comment by elnyry** [comment]
Moved 28 points (#340 , #353 , #355, #356 ) into 3.1 so moving this to 3.2 to accommodate for that
