### ISSUE TITLE
Tweeking Kafka lib for performance

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3420]
## **Goal**:
**As a** Mojaloop Community Member 
**I would like to** have the Kafka lib optmised as per recommendations from the performance stream output
**So that I** can get the best performance from Kafka

**Acceptance Criteria**:
- [ ] Verify that there is a way of testing kafka lib's performance
- [ ] Verify that the Kafka lib is adjusted for performance as recommended by the performance stream report
- [ ] Verify that any performance gains are characterised

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3420?planning-poker) with Zenhub @vijayg10
