### ISSUE TITLE
Build performance test environment

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3421]
## **Goal**:
`As a` Development test supporting the performance testing of Mojaloop
`I want to` have an environment that is configured to enable performance testing of Mojaloop
`so that` run the performance tests to determine the TPS and running costs to build a capacity model

**Acceptance Criteria**:
- [ ] Verify that the test environment is based off the IaC modules environment
- [ ] Verify that the test environment uses managed components
- [ ] Verify that the test environment deploy the K6 test harness with the associated monitoring support tools.  
   - [ ] K6 & associated tools 
   - [ ] Grafana, 
   - [ ] Prometheus, 
   - [ ] dashboards 
   - [ ] Solution to collect results

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
No longer needed.
