### ISSUE TITLE
Enhance Kafka lib to include performance workstream recommendations

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3422]
## **Goal**:
**As a** Mojaloop Community Member 
**I would like to** have the Kafka lib optimised as per recommendations from the performance stream output
**So that I** can get the best performance from Kafka

**Notes:**
There is a document that details the changed needed. Miguel will provide it.
- Using the vNext Kafka lib for this work.
1. enable.partition.eof (Rdkafak config parameter)
Here is a PR with these changes. [PR](https://github.com/mojaloop/platform-shared-lib/pull/6/files)
The PR will need to be redone.
Here is the vNext [shared lib](https://github.com/mojaloop/platform-shared-lib/blob/b4732ffc4f1b820b4b8207bc6d943d98769706dd/packages/nodejs-kafka-client-lib/src/raw/rdkafka_raw_consumer.ts)
2. Configure how many messages can be processed in parallel

**Acceptance Criteria**:
- [ ] Verify that these Kafka configurations are enabled and accessable
   - [ ] enable.partition.eof 
   - [ ] Configure how many messages can be processed in parallel

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3422?planning-poker) with Zenhub @vijayg10
