### ISSUE TITLE
Analyse ALS Perf results - document findings and recommendations to realise perf gains

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3424]
## **Goal**:
`As a` Majoaloop Maintainer

`I want to` document the ALS Perf Characterization
  
`so that` they can be preserved for for future comparisons

**Acceptance Criteria**:
- [x] Captured analysis for Scenarios 1-16

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Added analysis to Scenarios 1-16
- [x] Captured Follow-up stories
- Addressed review comments
    - [x] re-factored structure into domains (i.e. fspiop-discovery, etc)
    - [x] added status/summary to the top of domain readmes

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- https://github.com/mojaloop/ml-perf-characterization/pull/1

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Story completed
