### ISSUE TITLE
Update Node JS version for the ML API Adapter

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3425]
## **Goal**:
`As a`  Mojaloop Maintainer

`I want to`  upgrade ML-API-Adapter to use the latest NodeJS LTS version
  
`so that` the NodeJS runtime is fully supported 

**Acceptance Criteria**:
- [x] ML-API-Adapter will use latest Node v18.x
- [x] CI Image Scan should pass after Nodejs upgrade to Node v18.x
- [x] CI Image Scan should select the Nodejs version from the project's nvmrc file
- [x] Upgrade dependencies to the latest version
- [x] Update the master branch to main 
   - [x] update main readme
   - [x] update ci config

**Complexity**: Medium

**Uncertainty**: Medium

[---](https://github.com/mojaloop/project/issues/3386)

**Tasks**:
- [x] Upgrade NodeJS version for the following dependencies
     - [x] central-services-health
     - [x] central-services-metrics
     - [x] central-services-shared
     - [x] central-services-stream
     - [x] event-sdk
- [x] Update all dependencies
- [x] Validate all existing Audit issues to see if they are still applicable (ref: audit-ci.jsonc)
- [x] Update project to the latest LTS Nodejs version run CI tests
- [x] Update CI workflow based on the latest fixes made to the SDK-Scheme-Adapter CI workflow for NVM, etc. [@mdebarros]
- [x] Alignment to latest SDK repo updates ([ref](https://github.com/mojaloop/sdk-scheme-adapter/pull/453))
    - [x] Add build-local after setup to optimise the build pipeline

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- https://github.com/mojaloop/ml-api-adapter/pull/513

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by JaneS321** [comment]
Refer to story 3386

**Comment by mdebarros** [comment]
Reference PR for SDK-Scheme-Adapter as done as part of https://github.com/mojaloop/project/issues/3386 --> https://github.com/mojaloop/sdk-scheme-adapter/pull/453
