### ISSUE TITLE
[Maintenance][ALS] Enhance HTTP Egresses on ALS using HTTP Keep-alive

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3428]
## **Goal**:
`As a` Hub Operator

`I want to` enhance HTTP Egresses on ALS using HTTP Keep-alive on the Account-Lookup-Service (ALS)
  
`so that` I can improve the performance and scalability of the ALS

Ref: https://github.com/mojaloop/ml-perf-characterization/tree/feat/performance-maintenance-characterisation-als#follow-up-stories

**Acceptance Criteria**:
- [x] HTTP Agent is configurable as part of ALS config (i.e. default.json).

Notes:
- N/A

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by kleyow** [comment]
The ALS uses the central shared library which has http alive enabled.
The option isn't configurable but from previous characterization it was found to be a benefit to all services that talk to each other continuously.

If in the future http keep alive somehow affects the service negatively we can do a story to make it configurable on a per service basis.
