### ISSUE TITLE
[Maintenance][ALS] Profile NodeJS Process on ALS

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3429]
## **Goal**:
`As a` Hub Operator

`I want to` profile the NodeJs process on the Account-Lookup-Service (ALS)
  
`so that` I can improve the performance and scalability of the ALS

Ref: https://github.com/mojaloop/ml-perf-characterization/tree/feat/performance-maintenance-characterisation-als#follow-up-stories

**Acceptance Criteria**:
- [ ] ALS NodeJS process has been profiled
- [ ] Identified issues have been documented
- [ ] Stories created to resolve identified issues

Notes:
- The following mechanisms can be used to optimize the Validation calls
    -  Caching.
    -  Merge Validations and Endpoint calls.
    -  ~Adding a new API operation on the Central-Ledger Admin API that is more optimized (i.e. a single API call to validate both PayerFSP & PayeeFSP)~ (unnecessary if the Validations (i.e. GET /participants/{id}) can be used for both the validations and to attain the Endpoints (i.e. GET /participants/{id}/endpoints)

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
