### ISSUE TITLE
2.04.1 Create initial positions for participant flow - [8]

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#343]
**Goal**:
1. As a contributor
I would like to _create initial positions for participant flow_ 
so that FSPs have an initial position and a position limit
2. As a Hub Operator
I want to be able to _register a Participant for Transfer Services_
so that I can _set their FSP ID, Net Debit Cap (if not already created set position to zero)_

**Tasks**:
- [x] Design solution for:
  - [x] participantLimit [@ggrg]
  - [x] participantPosition [@ggrg]
- [x] Implement design solution (migration scripts) for:
  - [x] participantLimit [@ggrg]
  - [x] participantPosition [@ggrg]
- [x] Delete the Party table and related tables [@ggrg]
  - [x] Update migration scripts [@ggrg]
- [x] Design API for participant limit and initial position
  - [x] Create sequence diagram [@shashi165]
- [x] Enhance the existing Participant admin API to
  - [x] add participant limits - [@shashi165]
  - [x] add default positions (to zero) - [@shashi165]
- [x] Unit tests
   - [x] unit test for add limits - [@shashi165]
   - [x] unit test for add initial position - [@shashi165]
- [x] Integration tests
- [x] Code Coverage tests
- [x] Add JSDocs

**Acceptance Criteria**:
- [x] Leverage the existing admin API to allow for
  - [x] Inserting the participant limits or create participant limits
  - [x] Create initial participant entry in the participantPositions table for the specified limit type
  - [x] If values are not provided during Participant on-boarding, default to zero (Net Debit Cap & Position)

**Dependencies**:
- [ ] #341 
- [x] #317 
- [ ] #342

Note:
Follow-up story - #351

**Accountability**:
- Owner @rmothilal  
- QA/Review

**Comment by shashi165** [comment]
merged the code
