### ISSUE TITLE
[Maintenance][ALS] Add end-to-end metrics instrumentation to ALS

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3431]
## **Goal**:
`As a` Hub Operator

`I want to` enhance ALS instrumentation to include End-to-end metrics
  
`so that` I can monitor End-to-end performance when running ALS normally

Ref: https://github.com/mojaloop/ml-perf-characterization/tree/feat/performance-maintenance-characterisation-als#follow-up-stories

**Acceptance Criteria**:
- [ ] End-to-end metrics have been instrumented on the ALS for 
    - [ ] tx_getParties for end-to-end, request, and response
    - [ ] tx_getParticipants for end-to-end, request, and response

Notes:
- Implement similar approach implemented in the Transfer processing flow to capture the End-to-end metrics as part of ALS instrumentation. (ref: [1](https://github.com/mojaloop/ml-api-adapter/blob/master/src/api/transfers/handler.js#L61), [2](https://github.com/mojaloop/ml-api-adapter/blob/982f164da0e91ea19277a47444456aecb1102d24/src/api/transfers/handler.js#L103), [3](https://github.com/mojaloop/ml-api-adapter/blob/982f164da0e91ea19277a47444456aecb1102d24/src/handlers/notification/index.js#L48), [4](https://github.com/mojaloop/ml-api-adapter/blob/982f164da0e91ea19277a47444456aecb1102d24/src/handlers/notification/index.js#L179)) 

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
