### ISSUE TITLE
Script the capturing of the perf results

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3432]
## **Goal**:
`As a` Mojaloop contributor using the test harness to run performance tests
`I want to` script the running and capturing of the test results
`so that` the running of a test and capturing the results is less manual and more efficient

**Acceptance Criteria**:
- [x] Verify that the script is added to the [repo](https://github.com/mojaloop/ml-core-test-harness)
- [x] Verify that the script
   - Captures the test start time
   - Executes the test
   - Captures the test end time
   - Generates images of all the performance dashboards using the start and end times 
   - Stores the result images in that format as defined in the [ml-perf-characterization](https://github.com/mojaloop/ml-perf-characterization/tree/feat/performance-maintenance-characterisation-als)

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Understand the current k6, docker-compose setup
- [x] Script the logic for the transfers 1st scenario, get the dashboard results and store the reports locally by manually running the script [inprogress]
- [x] Extend the logic in the script for more scenarios to make sure the results are getting captured and stored locally in separate folders

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
