### ISSUE TITLE
Update Node JS version for the central-ledger

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3433]
---

**Tasks**:
- [ ] Update all dependencies
- [ ] Validate all existing Audit issues to see if they are still applicable
- [ ] Update project to the latest LTS Nodejs version run CI tests
- [ ] Update CI workflow based on the latest fixes made to the SDK-Scheme-Adapter CI workflow for NVM, etc.

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
