### ISSUE TITLE
2.5 Rework Positions Handler to cater for all messages and scenarios

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#344]
**Goal**:
As a developer
I would like to _rework positions handler to cater for all messages and scenarios_
so that all position related scenarios are handled

**Tasks**:
- [x] Implement Position Prepare flow [@ggrg]
- [x] Implement Position Fulfil flow [@ggrg]
- [x] Implement Position Abort flow [@ggrg]
- [x] Update existing Unit tests [@ggrg]
- [x] Update existing Integration tests [@ggrg]
- [x] Ensure Code coverage [@ggrg]
- [x] JSDocs [@ggrg]

**Acceptance Criteria**:
- [x] Position Handler caters for prepare position messages
- [x] Position Handler caters for fulfill position messages
- [x] Position Handler caters for abort position messages (rejects, time-outs)

**Dependencies**:
- [x] #341 
- [x] #317 
- [x] #342

**Accountability**:
- Owner @rmothilal
- QA/Review @rmothilal
