### ISSUE TITLE
Update Node JS version for the central-event-processor

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3441]
**Tasks**:
- [ ] Update all dependencies
- [ ] Verify that ignored dependency upgrades are still applicable `.ncurc.yaml`
- [ ] Verify that ignored audit issues are still applicable `audit-ci.jsonc`
- [ ] Update project to the latest LTS Nodejs version run CI tests
- [ ] Update CI workflow based on the latest fixes made to the SDK-Scheme-Adapter CI workflow for NVM, etc.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
