### ISSUE TITLE
Update Node JS version for the core libraries - central-services-shared

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3452]
**Tasks**:
- [x] Update all dependencies
- [x] Verify that ignored dependency upgrades are still applicable `.ncurc.yaml`
- [x] Verify that ignored audit issues are still applicable `audit-ci.jsonc`
- [x] Update project to the latest LTS Nodejs version run CI tests
- [x] Update CI workflow based on the latest fixes made to the SDK-Scheme-Adapter CI workflow for NVM, etc.

## **Pull Requests**:
- [ ] https://github.com/mojaloop/central-services-shared/pull/347

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
