### ISSUE TITLE
Update Node JS version for the core libraries - event-sdk

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3455]
**Tasks**:
- [x] Update all dependencies
- [x] Verify that ignored dependency upgrades are still applicable `.ncurc.yaml`
- [x] Verify that ignored audit issues are still applicable `audit-ci.jsonc`
- [x] Update project to the latest LTS Nodejs version run CI tests
- [x] Update CI workflow based on the latest fixes made to the SDK-Scheme-Adapter CI workflow for NVM, etc.
- [x] Migrate from deprecated [gRPC](https://www.npmjs.com/package/grpc) -> [gRPC-js](https://www.npmjs.com/package/@grpc/grpc-js) ([Migration guide](https://github.com/grpc/grpc-node/blob/089a8a881e0963efa44996f1a6a49a3a51eb3abd/packages/grpc-js/README.md?plain=1#L32))

## **Pull Requests**:
- [ ] https://github.com/mojaloop/event-sdk/pull/73

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
