### ISSUE TITLE
Update Node JS version for the ttk toolkit

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3458]
**Tasks**:
- [x] Update all dependencies
- [x] Verify that ignored dependency upgrades are still applicable `.ncurc.yaml`
- [x] Verify that ignored audit issues are still applicable `audit-ci.jsonc`
- [x] Update project to the latest LTS Nodejs version run CI tests
- [x] Update CI workflow based on the latest fixes made to the SDK-Scheme-Adapter CI workflow for NVM, etc.

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/thirdparty-sdk/pull/167

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
