### ISSUE TITLE
Update Node JS version for the ttk toolkit ui 

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3459]
**Tasks**:
- [x] Update all dependencies
- [x] Verify that ignored dependency upgrades are still applicable `.ncurc.yaml`
- [x] Verify that ignored audit issues are still applicable `audit-ci.jsonc`
- [x] Update project to the latest LTS Nodejs version run CI tests
- [x] Update CI workflow based on the latest fixes made to the SDK-Scheme-Adapter CI workflow for NVM, etc.
- [x] Resolve image scan issues and port whitelisting

## **Pull Requests**:
- [ ] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/178

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by oderayi** [comment]
Returning this to the PI backlog as there is no adequate test coverage in this repo. Upgrading it will be too risky.

**Comment by kleyow** [comment]
react-scripts>eslint-config-react-app>eslint-plugin-jsx-a11y>axe-core

Package "axe-core@4.8.3" is licensed under "MPL-2.0" which is not permitted by the --onlyAllow flag. Exiting.
MPL 2.0 is copy-left license, means incompatible with Apache 2.0 Mojaloop licensing.

This should affect all react based services.

On the recommendation of @elnyry-sam-k I am moving this to blocked "because its not part of the Mojaloop core platform - strictly speaking and is not our core offering.. Its only the tool we use for testing"

**Comment by kleyow** [comment]
https://github.com/mojaloop/project/issues/3710
