### ISSUE TITLE
2.16 Implement DFSP position management API (DFSP position query and update)

### ISSUE THREAD

**Issue by nikolayanastasov** [mojaloop/project#346]
**Goal**:
As a Switch
I would like to _Implement FSP position management API (FSP position query and update)_ 
so that the Position an FSP can be managed following the Rules provided by the API and the Scheme.

**Tasks**:
- [ ] Implement DFSP position management API
  - [ ] ~Position query~ [Done]
  - [ ] Position Update
- [ ] Unit tests
- [ ] Integration tests
- [ ] JSDocs
- [ ] Code coverage

**Acceptance Criteria**:
- [ ] Migration scripts generate the xxx table(s) as per design (**what is xxx table?**)
- [ ] Position Management model to orchestrate the Positions of an FSP are implemented (**??**)

**Dependencies**:
- [ ] #331 

**Accountability**:
- Owner 
- QA/Review @rmothilal

**Comment by elnyry** [comment]
This is not currently critical for either Positions or Settlements, there is a work-around being discussed which could accomplish this with the existing design. In case it doesn't cater for the needs, this should be revived, otherwise can be handled post PI-3

**Comment by elnyry** [comment]
Covered as part of #461
