### ISSUE TITLE
Update Node JS version for the ttk shared lib

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3460]
**Tasks**:
- [ ] Update all dependencies
- [ ] Validate all existing Audit issues to see if they are still applicable
- [ ] Update project to the latest LTS Nodejs version run CI tests
- [ ] Update CI workflow based on the latest fixes made to the SDK-Scheme-Adapter CI workflow for NVM, etc.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
