### ISSUE TITLE
Drop Settlement Matrix statuses: DISPUTED | CLOSED | AWAITING_SETTLEMENT

### ISSUE THREAD

**Issue by koekiebox** [mojaloop/project#3464]
## **Goal**:
`As a` stakeholder

`I want to` Remove settlement matrix statuses `DISPUTED | CLOSED | AWAITING_SETTLEMENT` and introduce `FINALIZED`
  
`so that` the matrix status does not reflect the last settlement batch status.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Drop matrix statuses `DISPUTED | CLOSED | AWAITING_SETTLEMENT`
- [x] Make currency optional for a settlement matrix
- [x] allow for a matrix to have batches with different currencies
- [x] fire event to mark a matrix `outOfSync` if batch status has been updated

@koekiebox 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
