### ISSUE TITLE
[DevOps] PoC Wireguard VPN replacement for OpenVPN 

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3467]
## **Goal**:
`As a` Mojaloop Developer

`I want to` test Wiregaurd for VPN connectivity to OSS Dev/QA Environment
  
`so that` we can replace OpenVPN with a free OSS alternative

**Acceptance Criteria**:
- [x] WireGuard has been deployed and configured to provide connectivity to the OSS Dev/QA Environment VPC
- [x] Test Profiles have been created for the OSS Dev/QA team

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
