### ISSUE TITLE
3.08 Implement the settlement window API - 1

### ISSUE THREAD

**Issue by nikolayanastasov** [mojaloop/project#347]
**Goal**:
As a Switch
I would like to have the _settlement window closure API implemented_
so that the Settlement window closure API is implemented as designed

**Tasks**:
- [x] create HAPI plugin for the Central-Services Logger to be used within server.log or request.server.log methods [@vgenev, @bothadeon]
- [x] Implement the settlement window closure API
  - [x] GET settlementWindow by Id [@vgenev, @bothadeon]
  - [x] GET settlementWindow by filters [@vgenev, @bothadeon]
  - [x] POST settlementWindow to close it [@vgenev]
- [x] Add settlement data to seed script  [@bothadeon]
- [ ] ~Error Handling~
- [ ] ~Unit Tests~
- [ ] ~Integration Tests~
- [ ] ~Code coverage~
- [ ] ~Identify if any changes are needed to the design and make necessary changes~

**Acceptance Criteria**:
- [ ] The settlement window closure API is implemented
- [ ] The implementation aligns with the design and any issues identified are brought up so that the design is updated.

**Dependencies**:
- [x] #327
- [x] Follow-up item #415

**Accountability**:
- Owner @bothadeon 
- QA/Review @bothadeon @wdcmb

**Comment by elnyry** [comment]
Follow-up item #415
