### ISSUE TITLE
Profile ML-API-Adapter Notification Handler in isolation

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3470]
## **Goal**:
`As a` team working on optimising the performance
`I want to` profile the ML API notifications handler
`so that` identify what performance problems in the code.

**Note:**
In the transfers performance characterisation work, an issue was identified in the ML-API-Adapter Notification Handler that deserves closer scrutiny. I.e. its one of the components showing the usage of resources (i.e CPU).
Running this in a profiler in an isolated environment will help show up the problem. This story is to do that. 

**Acceptance Criteria**:
- [x] Verify that the ML-API-Adapter Notification Handler implementation matches the design [@sri-miriyala] 
    - [x] Document any gaps or issues, and create follow-up stories as needed
- [ ] Verify that the ML-API-Adapter Notification Handler is tested in isolation 
- [ ] Verify that the ML-API-Adapter Notification Handler is profiled 
- [ ] Verify that noteworthy findings/observations are documented
- [ ] Verify that the problems identified are either fixed if small, or that stories to perform the fix are created.
   - [ ] Verify if http keep alive is configured and tested

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Compare ML API Notification Handler design against the code (Sri)
- [x] Review ML documentation on notification handler
- [x] kafka cat example notification messages for load
- [x] Profile notification handler with mock cl admin and dumped kafkacat messages
- [x] Create stories for identified issues
- [x] Apply fixes to central-services-shared
- [x] Run isolated performance tests and capture graphana dashbaords 
- [x] Document findings in performance repo
 
**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by JaneS321** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3470?planning-poker) with Zenhub @aaronreynoza @sri-miriyala @mdebarros @kleyow @oderayi
