### ISSUE TITLE
Profile the Central-Ledger Position Handler in isolation

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3471]
## **Goal**:
`As a` team working on optimising the performance
`I want to` profile the Central-Ledger Position Handler
`so that` identify what performance problems in the code.

**Note:**
In the transfers performance characterisation work, an issue was identified in the Central-Ledger Position Handler that deserves closer scrutiny. I.e. its one of the components showing the usage of resources (i.e CPU).
Running this in a profiler in an isolated environment will help show up the problem. This story is to do that. 

**Acceptance Criteria**:
- [x] Verify that the Central-Ledger Notification Handler implementation matches the design [@sri-miriyala ]
    - [x] Position prepare handler
        - [x] Prepare consume 
        - [x] Prepare position handler
    - [x] Position Fulfil handler
    - [x] Document any gaps or issues, and create follow-up stories as needed
- [x] Verify that the Central-Ledger Position Handler is tested in isolation 
- [x] Verify that the Central-Ledger Position Handler is profiled 
- [x] Verify that noteworthy findings/observations are documented
- [x] Verify that the problems identifies are either fixed if small, or that stories to perform the fix are created.
- [x] Double-check Table Indexes for SQL queries

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Deploy docker perf stack in local machine and take out the position handler out of it and run it as a node service. Make sure the test cases are working.
- [x] Profile position handler using chrome profiler and observe the functions taking long time and document observations
- [x] Profile using clinic.js bubbleprof and document observations
- [x] List out mysql queries those are being executed for a transfer
- [x] Analyse the mysql queries and document the observations
- [x] Create a repeatable process to test position handler in isolation without running other handlers (Like a script to recreate necessary records in database, and dump kafka messages in position topic and calculate the time taken for processing those messages)
- [x] Fix the quick issues and observe the difference in performance
- [x] Capture Mysql query execution count with a fixed number of transfers
- [x] Go though position handler code and try to find out if there is any scope for optimization
- [x] Document the observations with captured dashboard images
- [x] Try PRISMA approach as a PoC

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-perf-characterization/pull/4
- [x] https://github.com/mojaloop/ml-core-test-harness/pull/23

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by JaneS321** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3471?planning-poker) with Zenhub @aaronreynoza @kleyow @sri-miriyala @mdebarros

**Comment by JaneS321** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3471?planning-poker) with Zenhub @oderayi
