### ISSUE TITLE
Enhance Kafka lib (vNow) to include performance stream recommendations

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3472]
## **Goal**:
`As a` developer team working on the performance of the transfer flow
`I want to` validate the impact of the kafka lib config settings
`so that` I an quantify the performance impact of these settings

**Note:**
This story is to apply the performance config changes to the vNow kafka lib and then evaluate the affect it has on performance using the transfer testing harness.

**Acceptance Criteria**:
- [x] Verify that the vNow Kafka lib has been updated with to include two new consume modes with the following
   - [x] quick consume mode (Kafka messages are consumed asap)
   - [x] Backpressure mode
      - [x] Configure how many messages can be processed in parallel
   - [x]  the recommended Kafka settings
- [x]  Verify that the following are configurable
   - [x]  enable.partition.eof
   - [x]  Expose the compression configuration
   - [x] Make the serialisation functions configurable ( to support the running of a protobuf POC)
- [x] verify that the current mode, and the two new modes, and additional configurations I.e. EOF and compressions) are performance characterised to quantify the impact these changes have on performance
    - [x] Run a protobuf POC and characterise the performance
- [x] re-run best best-performing transfers configuration scenario, and document the findings, of both the quick consume **(follow-up: investigate `stutters`)**

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Create perf benchmark tests
- [x] add enhancements
    - [x] eof.partition event
    - [x] metrics event
    - [x] add the ability to change sync concurrency
    - [x] add the ability to change how the sync queuing strategy, i.e. batch vs single messages 
- [x] Create test scenarios
- [x] Capture test results

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- https://github.com/mojaloop/central-services-stream/pull/129

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Ref: https://github.com/mojaloop/platform-shared-lib/pull/6

**Comment by JaneS321** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3472?planning-poker) with Zenhub @aaronreynoza @oderayi @sri-miriyala @kleyow @mdebarros
