### ISSUE TITLE
3.09 Implement the settlement API - 1

### ISSUE THREAD

**Issue by nikolayanastasov** [mojaloop/project#348]
**Goal**:
As a Switch
I would like to have the _settlement API implemented_
so that the Settlement window query API is implemented as designed

**Tasks**:
- [x] Implement settlements API - GET: getSettlementsByParams. [@bothadeon @vgenev]
- [ ] ~Implement settlements API - GET: /settlements/{id} [@bothadeon @vgenev]~
- [x] Implement settlements API - POST: /settlements - post settlement event trigger [@vgenev]
- [ ] ~Unit Tests~
- [ ] ~Integration Tests~
- [ ] ~Code coverage~
- [ ] ~Identify if any changes are needed to the design and make necessary changes~

**Acceptance Criteria**:
- [ ] The settlement window query API is implemented
- [ ] The implementation aligns with the design and any issues identified are brought up so that the design is updated.

**Dependencies**:
- [x] #327
- [x] Follow-up item #416

**Accountability**:
- Owner [@vgenev]
- QA/Review

**Comment by elnyry** [comment]
Follow-up item #416
