### ISSUE TITLE
[All hapi based services] @hapi/joi and @hapi/good are deprecated since 2020

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#3481]
## **Goal**:
`As a` stakeholder

`I want to` ensure core libraries are maintained and up to date
  
`so that`  I have peace of mind

**Acceptance Criteria**:
- [ ] @hapi/joi is switched to joi
- [ ] @hapi/good alternative is installed and integrated

**Complexity**:  Low

**Uncertainty**:  Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
with v17, this is taken care of for all services part of the Mojaloop release (core); please reopen if there's any issue with this (anything missed)
