### ISSUE TITLE
Build the Open API definition for the FX API flows

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3483]
## **Goal**:
`As a` Development Team building the FX API flows
`I want to` use an Open API
`so that` ensure that the development of the FX follows and makes use of this API definitions

**Note: **
The FXP API is specified in the issue [issue 89](https://github.com/mojaloop/mojaloop-specification/issues/89)

**Acceptance Criteria**:
- [ ] Verify that the specification fspiop open API is updated to reflect issues 89
- [ ] Verify that the API Snippets repo is updated to reflect the changes proposed in issue 89

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3483?planning-poker) with Zenhub @kleyow @vijayg10 @sri-miriyala @aaronreynoza @oderayi

**Comment by JaneS321** [comment]
Jira Board IPROD 197

**Comment by vijayg10** [comment]
https://github.com/mojaloop/mojaloop-specification/issues/103
