### ISSUE TITLE
Implement the transfer batching design for the position handler

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3489]
## **Goal**:
`As a` development team working on mojaloop transfer performance enhancement
`I want to` Implement the transfer batching design for the position handler
`so that` I get the performance benefit of batching

**Acceptance Criteria**:
- [ ] Verify that the batch is designed and completed as defined in story #3488
- [ ] 

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
