### ISSUE TITLE
Update ML API Notification Handler sequence diagrams

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#3492]
## **Goal**:
`As a` developer working on Mojaloop implementation
`I want to` update ML API notifications handler sequence diagrams
`so that` the sequence diagram matches the current code for better understanding of the usecases.
**Note:**
In the transfers performance characterisation work, an issue was identified in the ML-API-Adapter Notification Handler sequence diagrams, that needs an update. I.e. the current version of code covering lot of scenarios while the sequence diagrams are only showing a high level flow of the msgs and not covering error cases.
Enhancing the sequence diagrams further to include all error cases (according to the current code) would be more beneficial for those who is trying to learn/contribute/adopt ML.

**Acceptance Criteria**:
- [] Update the notification handler sequence diagram that cover error cases.
- [ ] Verify that the Notification handler sequence diagram is covering all error codes according to the current implementation
- [ ] Verify that noteworthy findings/observations are documented
**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
