### ISSUE TITLE
Source Code updates in Position Handler based on Sequence Diagram

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#3496]
## **Goal**:
`As a` Mojaloop maintainer

`I want to` update Position Handler source code 
  
`so that` the code is aligned with the logic in the corresponding sequence diagrams

**Acceptance Criteria**:
- [ ] Code updated in places where it is missing/deviating from the logic in the sequence diagram.
- [ ] There are also areas where the sequence diagrams need to be updated. 

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Hi @sri-miriyala , thanks for the issue..

Can you please share here any areas of deviation that you've already identified? If thats still yet to be done, then thats fine..
