### ISSUE TITLE
Re-baseline upgraded core services including kafka lib and updated NodeJS components

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3499]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` <action>
  
`so that` <reason> 

**Acceptance Criteria**:
- [ ] Implement latest Kafka lib and Configure optimised Producer/Consumer configs for each component (i.e. ML-API-Adapter API, ML Notification Handler, CL Prepare, Position, Fulfil, etc)
- [ ] Implement latest event-sdk lib for each component (i.e. ML-API-Adapter API, ML Notification Handler, CL Prepare, Position, Fulfil, etc)

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
