### ISSUE TITLE
Fix broken batch processing logic in central position handler

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3500]
**Summary**:
Batch processing implementation is broken in central position handler.
The prepare facade function seems working fine but there are issues in handler and other facade functions.
Having a quick look at the code, the following are the places the issue needs to be fixed. Not sure if there are any other issues.

https://github.com/mojaloop/central-ledger/blob/44391177fc188841989380321da80cada854407c/src/handlers/positions/handler.js#L109
https://github.com/mojaloop/central-ledger/blob/44391177fc188841989380321da80cada854407c/src/handlers/positions/handler.js#L119

https://github.com/mojaloop/central-ledger/blob/44391177fc188841989380321da80cada854407c/src/handlers/positions/handler.js#L188

https://github.com/mojaloop/central-ledger/blob/44391177fc188841989380321da80cada854407c/src/handlers/positions/handler.js#L199

https://github.com/mojaloop/central-ledger/blob/44391177fc188841989380321da80cada854407c/src/handlers/positions/handler.js#L222

**Acceptance Criteria**:
- [ ] The current batch processing is fixed and working if we maintain the kafka partition assignment configuration properly (Caveat: A position handler service should get messages for a single participant account)
- [ ] Integration tests are added to test position changes incase of batch processing
- [ ] Integration tests are added to check if the NDC and liquidity checks are done properly

**Tasks**:
- [ ] TBD

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**
- When batch processing is enabled, the positions should be changed properly
- When batch processing is enabled, the ndc and liquidity checks should be done properly

**Steps to Reproduce**
  1. Increase batch size in central position handler
  2. Make sure the service is consuming only one partition and all the messages in that partition should be with same participant currency
  3. Send few transfers through the mojaloop switch
  4. You can observe errors in the position handler logs

**Specifications**
  - Component: central-ledger (position handler)
  - Version: v17.0.3
  - Type of testing: Functional test
  - Bug found/raised by: @vijayg10 

## **Pull Requests**:
- [ ] TBD

**Comment by PaulGregoryBaker** [comment]
#3488 #3489 #3524

Functionality was fixed through the desing and implementation of a new batching strategy
