### ISSUE TITLE
2.04.2 Add callback details for participants

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#351]
**Goal**:
1. As a contributor
I would like to _add callback details for participants_ 
so that callbacks can be done.
2. As a Hub Operator
I want to be able to _register the callback details of an FSP_
so that I can _retrieve them later and use for callbacks_

**Note**:
This story came out of breaking down #343 

**Tasks**:
- [x] Design solution for ~participantContact~ participantEndpoint(for callbacks)
    - [x] Create sequence diagram  for getting the callback details
    - [x] Create sequence diagram  for adding the callback details
- [x] Implement solution for ~participantContact~ participantEndpoint (for callbacks) -- [@shashi165]
    - [x] Implement solution for getting the callback details -- [@shashi165]
    - [x] Implement solution for adding the callback details -- [@shashi165]
- [ ] ~Enhance the existing Participant admin API to add callback URLs~(~participantContact, participantContactType~)
- [x] Unit tests
    - [x] Unit tests for getting callback details -[@shashi165]
    - [x] Unit tests for adding callback details -[@shashi165]
    - [x] Unit tests for participant routes & handlers -[@shashi165]
- [x] Integration tests -[@shashi165]
- [x] Code Coverage tests -[@shashi165]
- [x] Add JSDocs -[@shashi165]

**Acceptance Criteria**:
- [x] Design has to be approved by DA
- [x] Leverage the existing admin API to allow for on-boarding of a Participant
  - [x] to record the callback details

**Dependencies**:
- [x] #341 
- [ ] #317 
- [ ] #342
- [x] DA

**Accountability**:
- Owner @rmothilal  
- QA/Review
