### ISSUE TITLE
[Perf Maintenance] Investigate 

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3516]
## **Goal**:
`As a` Hub Operator

`I want to` implement best practices for indexed TransferIds (i.e. UUID, or CUID, etc) as a table key on MySQL
  
`so that` Mojaloop's Database scheme definition is performance & aligned to best practices

References:

```text
With UUID v4 it’s not possible to generate any sequential ouput and this is why those random UUID should never be used as Primary Key with InnoDB.
```
- https://blogs.oracle.com/mysql/post/mysql-uuids

**Acceptance Criteria**:
- [ ] Mojaloop Database Scheme does NOT use the TransferID as a `PRIMARY` key on tables
- [ ] Existing tables that use TransferID as a `PRIMARY` should instead use as a `SECONDARY` key, with an auto-inc for the `PRIMARY`
- [ ] Store UUID as binary using `UUID_TO_BIN` and `BIN_TO_UUID` to translate the UUID accordingly
- [ ] Provide documentation and scripts to assist with any data migration

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
