### ISSUE TITLE
Implement support for a Kafka Event Type-Action topic map configuration for the events of type position

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3519]
## **Goal**:
I want to add support for EVENT_TYPE_ACTION_TOPIC_MAP configuration for Prepare handlers
so that the application can produce events with type=POSITION as specified in the configuration.
`so that` I gain access to the new performant batch position handler while still using the old handler for other messages

**Acceptance Criteria:**
- [x] Implement support for EVENT_TYPE_ACTION_TOPIC_MAP for the Prepare handlers.
- [x] Ensure that when the Prepare action is triggered, it produces an event with type=POSITION and publishes it to the topic set in the EVENT_TYPE_ACTION_TOPIC_MAP overriding the exsitng topic template render functionallity.
- [x] Ensure that the existing topic template render functionality works as implmented if no override was found in the EVENT_TYPE_ACTION_TOPIC_MAP.

**Tasks:**
- [x] Modify the code to read and use the EVENT_TYPE_ACTION_TOPIC_MAP configuration.
- [x] Implement logic to produce events with the specified types for Prepare actions.
- [x] Update the unit tests to ensure that the events are produced correctly.
- [x] Update the documentation to include information about the new configuration and its usage.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/969

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
