### ISSUE TITLE
Implement API to provide details of a Participant

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#352]
**Goal**:
1. As a contributor
I would like to _implement an API to provide callback, position details of Participants_ 
so that callbacks can be done (to be used by ml-api-adapter) and positions, limits can be queried.

**Tasks**:
- [ ] Design solution for an API to
  - [ ] ~provide callback details (that are already stored #351) - GET~
  - [ ] ~provide Position - GET~
  - [ ] provide Position Limit / Net Debit Cap **and** Update it - POST, GET, PUT
- [ ] Implement solution for
  - [ ] ~retrieving callback details~
  - [ ] ~retrieving Position details~
  - [ ] retrieving Position Limit / Net Debit Cap **and** update it
- [ ] Unit tests
- [ ] Integration tests
- [ ] Code Coverage tests
- [ ] Add JSDocs

**Acceptance Criteria**:
- [ ] An API to provide the below details of a Participant is designed
  - [ ] callback details (for callbacks)
  - [ ] Position
  - [ ] Position Limits / Net Debit Cap (also to update the Net Debit Cap)

**Dependencies**:
- [ ] #351
- [ ] #343 

**Accountability**:
- Owner 
- QA/Review

**Comment by elnyry** [comment]
Covered in other stories
