### ISSUE TITLE
Provision an IaC envt 

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#3523]
## **Goal**:
`As a` team member supporting Mojaloop testing 

`I want to` make available a sandbox
  
`so that` the team has resources needed to conduct the testing.

**Acceptance Criteria**:
- [ ] A sandbox with latest Mojaloop stable release is provisioned with all tests passing as expected
- [ ] Access to team members requested is provided

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
