### ISSUE TITLE
Implement batch functionality in the position handler for fulfil actions

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3524]
## **Goal**:
`As a` development team working on mojaloop transfer performance enhancement
`I want to` Implement the transfer batching design in the position handler for the fulfil action
`so that` I get the performance benefit of batching 

**Acceptance Criteria**:
- [ ] Verify that the batch is designed for the position handler as defined in story #3488 for the following actions
   - [ ] fulfil
- [ ] Verify that the position handler characterisation is performed with the batch functionality implemented
- [ ] Verify that the happy path functional tests pass
- [ ] Verify that unit test are in place
- [ ] Build integration test for negative scenarios for the following actions
   - [ ] fulfil

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Add fulfil domain logic
- [x] Add unit tests
- [x] Add integration tests
- [x] Smoke test in test harness
- [x]  Characterize new batch functionality
- [x] Add reserve logic and tests

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3524?planning-poker) with Zenhub @aaronreynoza @kleyow @oderayi @sri-miriyala @vijayg10
