### ISSUE TITLE
5.4.2 Setup SonarQube and ensure code quality metrics for ml-api-adapter [5.4.1] [8]

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#353]
**Goal**:
As a contributor
I would like to _Setup ml-api-adapter so that it is included in SonarQube_
so that Quality metrics can be assessed/presented for this repo

**Tasks**:
- [x] Setup SonarQube for ml-api-adapter
- [x] Ensure code coverage data (lcov.info) etc is available and sonar scanner works for the repo

**Acceptance Criteria**:
- [x] SonarQube is setup to show Quality metrics for the ml-api-adapter

**Dependencies**:
- None currently

**Accountability**:
- Owner @elnyry
- QA/Review
