### ISSUE TITLE
Migrate thirdparty-sdk dependency on sdk-scheme-adapter to api-snippets

### ISSUE THREAD

**Issue by aaronreynoza** [mojaloop/project#3530]
## **Goal**:
`As a` development team working on mojaloop transfer performance enhancement
`I want to`  upgrade the thirdparty-sdk service to use types from the api-snippets library
`so that` we can  use the correct maintained library for types

**Acceptance Criteria**:
- [ ] Verify that the sdk scheme adapter is removed from thirdparty-sdk
- [ ] Build on top of the already existing types in api-snippets if needed
- [ ] Verify that unit tests are in place

**Complexity**: Low> Should migrate the types and add if missing

**Uncertainty**: Low> 

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
