### ISSUE TITLE
Build the quotes characterisation test-harness

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3532]
## **Goal**:
**As a** Mojaloop Community Member running performance testing
**I would like to** use K6 as my test runner
**So that I** can execute the performance tests on quotes

**Acceptance Criteria**:
- [ ] K6 load tests for quotes
- [ ] simulated call-back handlers (web socket) for mocking the DFSPs 
   - [ ] Docker compose define separate service for each DFSP
- [ ] Test cases
   - [ ] test case 1 : 2 DFSPs with strict payer and payee
- [ ] Update call-back handler service Grafana dashboards to display metrics by DFSP

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3532?planning-poker) with Zenhub @aaronreynoza @kleyow @oderayi @sri-miriyala @vijayg10
