### ISSUE TITLE
RC candidate for the next Mojaloop release (post v15.1.0)

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#3533]
## **Goal**:
`As a` ML OSS adopter

`I want to` have an Release Candidate for a post ML v15.1.0 that is successfully validated by the Golden path tests and ready for a release
  
`so that` I can start the validation processes prior to adopting the release based on this RC

**Acceptance Criteria**:
- [x] Confirm the version number of the next Mojaloop release based on the changes included
- [x] Helm RC Release is validated on Moja2 to achieve 100% result with TTK GoldenPath 
- [x] Helm RC Release is validated with PISP provisioning and test collection (TTK) with 100%
- [x] Helm RC Release is validated with Bulk test collection (TTK) with 100%
- [x] QA (Golden path) on deployments done on AWS Moja2 environment is done
- [x] Bugs are logged based on observations, failures
- [x] Bugs logged are fixed if critical / blockers to make subsequent releases in individual services (or Helm)
- [x] Release notes are drafted (to be published with the helm release)
- [x] Test cases on a RC branch are created and validated
- [x] TTK tests run successfully as Post-Hook jobs and Tests

**Notes**:
- This story is for creating a stable Release Candidate based on which the release will be made

**Complexity**: Medium - Involves all core and supporting services
**Uncertainty**: Medium

---

**Tasks**:
- [x] Initial PR with changes for RC @oderayi 
  - [x] Initial PR review @mdebarros @aaronreynoza 
  - [x] Deploy, validate, fix issues, redeploy @aaronreynoza @oderayi
  - [x] With stable deployment test Golden path @aaronreynoza @oderayi @sri-miriyala 
- [x] Validate PISP test provisioning and test collections (TTK)  @aaronreynoza @oderayi 
- [x] Identify issues with QA Scripts if any - fix them and retest @aaronreynoza @oderayi @mdebarros 
- [x] QA for bugs, regressions, log them @aaronreynoza @oderayi @mdebarros @sri-miriyala 
- [x] Fix bugs logged if critical @aaronreynoza @oderayi @mdebarros 
- [x] Deploy, validate on AWS Moja2 @aaronreynoza @oderayi 
- [x] Validate with TTK GP collection @aaronreynoza @oderayi @sri-miriyala 
- [x] TTK test-cases on a RC branch is created and validated @oderayi 
- [x] Release notes for helm RC is drafted @aaronreynoza @sri-miriyala 
  - [x] Guidance for migration from Release (may have to be a separate story if sufficiently big / complex) @aaronreynoza @sri-miriyala
- [x] Update release notes with Upgrade Strategy Guide link @aaronreynoza @sri-miriyala
- [x] Deployment of RC on **Moja2** (or one of the moja environments) @oderayi @aaronreynoza 
  - [x] RC is deployed on **Moja2** successfully
  - [x] Regression testing on Moja2 using TTK collections @aaronreynoza @oderayi 
    - [x] GP collection
    - [x] Core Bulk collection
    - [x] Third-party collection
    - [x] SDK Bulk collection
    - [x] SDK R2P collection
  - [x] Validation using CGS Golden path regression tests etc on Moja2
  - [x] Test upgradability from previous release @oderayi 

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] TTK Tests pass
- [x] Code Style & Coverage meets standards
- [x] Release notes are verified

## **Pull Requests**:
- [ ] https://github.com/mojaloop/helm/pull/581
- [ ] https://github.com/mojaloop/testing-toolkit-test-cases/pull/127
- [ ] https://github.com/mojaloop/thirdparty-api-svc/pull/92
- [ ] https://github.com/mojaloop/event-sidecar/pull/55
- [ ] https://github.com/mojaloop/central-settlement/pull/396
- [ ] https://github.com/mojaloop/central-ledger/pull/982
- [ ] https://github.com/mojaloop/bulk-api-adapter/pull/102
- [ ] https://github.com/mojaloop/central-settlement/pull/398
- [ ] https://github.com/mojaloop/testing-toolkit-test-cases/pull/128
- [ ] https://github.com/mojaloop/testing-toolkit-test-cases/pull/129
- [ ] https://github.com/mojaloop/quoting-service/pull/320

## **Follow-up**:

**Dependencies**:
- N/A

## **Accountability**:
- Owner: 
- QA/Review: @mdebarros @elnyry-sam-k @vijayg10

**Comment by oderayi** [comment]
Application versions for the next release:
-----------------
ml-api-adapter: v14.0.4
central-ledger: v17.2.1
account-lookup-service: v14.2.5
quoting-service: v15.1.0
central-settlement: v15.0.2 - POTENTIAL BREAKING CHANGE
bulk-api-adapter: v16.0.0
central-event-processor: v12.0.0 - no new release
email-notifier: v12.0.0 - no new release
als-oracle-pathfinder: v12.0.0 - no new release
transaction-requests-service: v14.1.1
finance-portal-ui: v10.4.3 (DEPRECATED) - not upgraded in the last release
finance-portal-backend-service: v15.0.2 (DEPRECATED) - not upgraded in the last release
settlement-management: v11.0.0 (DEPRECATED) - no new release
operator-settlement: v11.0.0 (DEPRECATED) - no new release
event-sidecar: v13.0.0
event-stream-processor: v12.0.0-snapshot.7 - no new release
simulator:  v12.0.0 - no new release
mojaloop-simulator: v14.0.2
sdk-scheme-adapter: v23.1.1
ml-testing-toolkit: v17.0.0
ml-testing-toolkit-ui: v15.4.0 - no new release
ml-testing-toolkit-client-lib: v.1.2.0 - no new release
auth-service: v14.0.1
als-consent-oracle: v0.2.1
thirdparty-api-svc: v13.0.3
thirdparty-sdk: v15.1.0 - no new release

**Comment by elnyry-sam-k** [comment]
Thanks for this @oderayi , third-party sdk should have a new release.

this story is closed: https://github.com/mojaloop/project/issues/3522 and the PR is merged as well, so I'm not sure why the release didn't happen; does the CI config need to be updated?

**Comment by oderayi** [comment]
Thanks for pointing out @elnyry-sam-k. 
Looks like the release didn't go through after the merge. I will look into this.

**Comment by elnyry-sam-k** [comment]
thanks @oderayi , appreciate it.

**Comment by mdebarros** [comment]
test.mojaloop.live has been upgraded from K8s v1.27 to v1.28:

```
❯ kubectl version
Server Version: version.Info{Major:"1", Minor:"28+", GitVersion:"v1.28.1-eks-43840fb", GitCommit:"5024547cf72fa45c3617e0c3fe3ae9e6b6e8f7e1", GitTreeState:"clean", BuildDate:"2023-09-06T20:55:59Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
```
