### ISSUE TITLE
Mojaloop Helm release v15.2.0

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#3534]
## **Goal**:
`As a` ML OSS adopter

`I want to` have a Mojaloop release v15.2.0 (version confirmed from issue #3533) that is successfully validated by the Golden path tests
  
`so that` I can adopt and use a version of Mojaloop Switch services bundle that is tested and contains the latest features enhancements and bug fixes added in PI-21 / PI-22

**Acceptance Criteria**:
- [x] Update "APP VERSION" for each chart.yaml
- [x] Helm RC Release is validated on Moja2 to achieve 100% result with TTK GoldenPath 
- [x] Helm RC Release is validated with PISP provisioning and test collection (TTK) with 100%
- [x] Helm RC Release is validated with Bulk test collection (TTK) with 100%
- [x] QA (Golden path) on deployments done on AWS Moja2 environment is done
- [x] Bugs are logged based on observations, failures
- [x] Bugs logged are fixed if critical to make subsequent releases in individual services (or Helm)
- [x] All the changes needed for supporting the Helm Release are done
- [x] Helm chart is published
- [x] Release notes are published
- [x] Test cases are published (TTK)
- [x] TTK tests run successfully as Post-Hook jobs and Tests

**Notes**:
- Follow-up to story #3533 

**Complexity**: Medium - Involves all core and supporting services
**Uncertainty**: Medium

---

**Tasks**:
- [x] Deploy, validate RC on AWS Moja2 @oderayi 
- [x] Identify issues with QA Scripts if any - fix them and retest @oderayi @aaronreynoza 
- [x] QA for bugs, regressions, log them @oderayi
- [x] Fix bugs logged if critical @oderayi
- [x] Validate with TTK GP collection @oderayi
- [x] TTK test-cases repo Release is published @oderayi
- [x] Release notes for helm RC is drafted @aaronreynoza 
  - [x] Guidance for migration from Release (may have to be a separate story if sufficiently big / complex)
- [x] Update release notes with Upgrade Strategy Guide link @aaronreynoza 
- [x] Helm Release is published @oderayi
- [x] Deployment of released Helm on **Moja2** @oderayi
  - [x] Helm release is deployed on **Moja2** successfully
  - [x] Regression testing on Moja2 using TTK collections @oderayi @aaronreynoza 
    - [x] GP collection
    - [x] Core Bulk collection
    - [x] Third-party collection
    - [x] SDK Bulk collection
    - [x] SDK R2P collection
  - [x] Validation using CGS Golden path regression tests etc on Moja2 @oderayi
  - [x] Test upgradability from previous release
- [x] Deployment of released Helm on **Moja1** @oderayi
  - [x] Helm release is deployed on **Moja1** successfully
  - [x] Validation using Golden path regression tests etc on Moja1 @oderayi
    - [x] GP collection
    - [x] Core Bulk collection
    - [x] Third-party collection
    - [x] SDK Bulk collection
  - [x] Validation using CGS Golden path regression tests etc on Moja1 @oderayi
  - [x] Validate daily cronJobs on Moja1 for GP and Cleanup scripts @oderayi

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] TTK Tests pass
- [x] Code Style & Coverage meets standards
- [x] Release notes are verified

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/586

## **Issues**:
- https://github.com/mojaloop/project/issues/3604
- https://github.com/mojaloop/project/issues/3615

## **Follow-up**:

**Dependencies**:
- N/A

## **Accountability**:
- Owner: 
- QA/Review: @mdebarros @elnyry-sam-k @vijayg10

**Comment by oderayi** [comment]
Cron job report:
[Uploading TTK-Assertion-Report-cronjob_tests_2023-11-08T08_02_58.078Z.json…]()
