### ISSUE TITLE
Performance Characterise Quotes

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3537]
## **Goal**:
`As a` Mojaloop Community Member considering adopting Mojaloop
`I want to` understand the performance of the core quotes system of the current Mojaloop version
`So that I` can understand scaling limits and associated costs in order to build my business model

This story is to build on #3532 and use the test harness to perform performance characterisation of the quotes functionality.

**Acceptance Criteria**:
- [x] Verify that the [perf documenation](https://github.com/mojaloop/ml-perf-characterization) is updated
   - [x] New quotes section added describing approach and method to reproduce
   - [x] Result dashboards
- [x] Verify that the quotes service is profiled when under test.
- [x] Perform obvious / easy to fix performance problems found. 
- [x] Write up stories or document more extensive performance extensions identified.
- [x] Verify that the quotes per second performance is understood
- [x] Verify the amount of data stored per quote is understood

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Profile the quoting service
- [x] Document profiling findings in characterization repo 
- [x] Update database dashboard to query quote data sizes 
- [x] Fix logger issues in quoting-service
- [x] Document performance findings in characterization repo 
- [x] Analyse mysql queries for a quote execution and document. [@vijayg10 ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
