### ISSUE TITLE
Settlement Initiation Report (downloaded)

### ISSUE THREAD

**Issue by TW-Ei-Nghon-Phoo** [mojaloop/project#3539]
## **Goal**:
`As a` hub operator

`I want to` be able to view and export settlement initiation report. This report is used as reference report for settlement bank to transfer funds from one DSFP to another. After downloading the report, hub operator will send it to settlement bank.

**Acceptance Criteria**:
- records should be filtered with currency,ie, records transferred in MMK currency or all currency available.
- Please see detail specification in following excel file. 
- [Settlement Initiation Report Detail Specification](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbURlIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9a11dbaccc826947029b921b6da28d6d1b772d62/Spec-%20Settlement%20Initiation%20Report-2023June12.xlsx)
- [Figma Prototype Design File](https://www.figma.com/proto/80cD3AKOglNk3UhCUxbILi/vNext-Portal?page-id=9%3A10&type=design&node-id=6047-2325&viewport=364%2C759%2C0.2&t=0AjOFyQToqGaF8uf-1&scaling=scale-down&starting-point-node-id=6043%3A714&show-proto-sidebar=1&mode=design)

**Tasks**:
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by myo-min-htet** [comment]
Done for the settlementIntitation data export API in the reporting-bc.

**Comment by einghon-phoo** [comment]
[heart]         Ei Nghon Phoo reacted to your message:
________________________________
