### ISSUE TITLE
5.1.2.0 Setup Kafka monitoring

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#354]
**Goal**:
1. As a developer
I would like to _setup monitoring for Kafka_
so that it can be used for testing reliability and other issues
2. As a Hub Operator as part of technical operations
I would like to _setup monitoring for Kafka_
so that it can be used for testing reliability and other issues with Kafka

**Tasks**:
- [ ] Analyze monitoring options ([Kafka Manager](https://github.com/yahoo/kafka-manager) , ELK or a combination)
- [ ] Present options for current & potential end-state to DA
- [ ] If the implementation is too big, create additional stories
- [ ] Setup monitoring
- [ ] Add helm charts for deployment

**Acceptance Criteria**:
- [ ] Monitoring option for Kafka is decided on for the development phase (not for production)
- [ ] If Kafka Manager is adequate for the current need, no further investigation is necessary (for PI3)
- [ ] The above option is implemented (If this is a big enough item, create a separate story)

**Dependencies**:
- None currently

**Accountability**:
- Owner 
- QA/Review
