### ISSUE TITLE
DFSP Settlement Report

### ISSUE THREAD

**Issue by TW-Ei-Nghon-Phoo** [mojaloop/project#3540]
## **Goal**:
`As a` DFSP  which joined the Scheme

`I want to`  know the total number of transactions and net transaction amount between DFSPs include in the settlement after each settlement.

**Acceptance Criteria**:

- Please see detail specification for the report in following excel file
- [DFSP Settlement Report Detail Specification](https://github.com/mojaloop/project/files/12789660/Spec-.DFSP.Settlement.Report.-.2023June09-3.xlsx)

- [Figma Prototype Design File](https://www.figma.com/proto/80cD3AKOglNk3UhCUxbILi/vNext-Portal?page-id=9%3A10&type=design&node-id=6047-2325&viewport=364%2C759%2C0.2&t=0AjOFyQToqGaF8uf-1&scaling=scale-down&starting-point-node-id=6043%3A714&show-proto-sidebar=1&mode=design)
---
### updated acceptance criteria
- Aggregate Net Position Values:

  - The settlement report should include aggregate net position values for all currencies included in the report.
  - If transactions involve multiple currencies displayed in the report, the aggregated net position should be displayed in separate rows, with one row for each currency.

- Definition of Aggregated Net Position:
  - Aggregated net position refers to the sum of net positions included in the report.

- User Interface Alignment:
  - In the preview on the user interface, the report headers and data values should be properly aligned for clarity and readability.

**Tasks**:
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by myo-min-htet** [comment]
Required backend API done in the reporting-bc.

**Comment by zinzinnyohlaing-tw** [comment]
Feature/3540 dfsp settlement report by kyaw-soe-tw · Pull Request #20 · mojaloop/reporting-bc (github.com) <-- pull request
