### ISSUE TITLE
DFSP Settlement Detail Report

### ISSUE THREAD

**Issue by TW-Ei-Nghon-Phoo** [mojaloop/project#3541]
## **Goal**:
`As a` DFSP which joined the scheme,

`I want to` know how many transactions include in the settlement and transaction detail information 

**Acceptance Criteria**:
- records should be filtered with currency,ie, records transferred in MMK currency or all currency available.
- Please see the following excel for detail specification.
- [DFSP Settlement Detail Report Detail Specification](https://github.com/mojaloop/project/files/12736764/DFSP.Settlement.Detail.Report.Detail.Specification.xlsx)
- [Figma Prototype Design File](https://www.figma.com/proto/80cD3AKOglNk3UhCUxbILi/vNext-Portal?page-id=9%3A10&type=design&node-id=6047-2325&viewport=364%2C759%2C0.2&t=0AjOFyQToqGaF8uf-1&scaling=scale-down&starting-point-node-id=6043%3A714&show-proto-sidebar=1&mode=design)
---

**Tasks**:
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by myo-min-htet** [comment]
@einghon-phoo, @nainglinnkhant 
I have added required APIs for this report in the reporting-bc.
Please continue for view in the Admin portal.

**Comment by zinzinnyohlaing-tw** [comment]
https://github.com/mojaloop/reporting-bc/pull/21 <-- pull request

**Comment by zinzinnyohlaing-tw** [comment]
added admin ui download data from the api
https://github.com/mojaloop/platform-shared-tools/pull/51 <-- pull request
