### ISSUE TITLE
Change http request library for ml-testing-toolking-client

### ISSUE THREAD

**Issue by aaronreynoza** [mojaloop/project#3545]
**Tasks**:
- [ ] Update all dependencies
- [ ] Verify that ignored dependency upgrades are still applicable `.ncurc.yaml`
- [ ] Verify that ignored audit issues are still applicable `audit-ci.jsonc`
- [ ] Change library to Axios (or other used library in the ecosystem)

## **Pull Requests**:
- [ ]

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Associated PR: https://github.com/mojaloop/ml-testing-toolkit-client-lib/pull/8 for this issue has been merged and closed so closing this issue
