### ISSUE TITLE
Implement database schema changes to the current codebase - [13]

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#355]
**Goal**:
As a developer
I would like to _Implement overall database schema changes_
so that the codebase is aligned to the design.

**Tasks**:
- [x] Update migration scripts according to the approved data model [@ggrg @bothadeon ]
  - [x] Successfully start the project APIs  [@ggrg @bothadeon]
  - [x] Confirm the migration created structures match the data model  [@ggrg @bothadeon ]
  - Working spreadsheet [link](https://docs.google.com/spreadsheets/d/1XCr35F2wnM4MCMRgJNfQ2DPK_FZFrSX4498iDssRE-0/edit#gid=0)
- [x] Update API scripts [@ggrg]
  - [x] Update /participants [@ggrg]
  - [x] Update /transfers [@ggrg]
  - [x] Update other resources [@ggrg]
- [x] Update DAO [@ggrg]
- [x] Update seeds [@ggrg]
- [x] Update transfers "golden path" scenario [@ggrg]
  - [x] Transfer Prepare [@ggrg]
  - [x] Transfer Fulfil Commit [@ggrg]
    - [x] Added expirationDate check - **todo** add to seq [@ggrg]
- [x] Code refactoring [@ggrg]
  - [x] Removal of unused code [@ggrg]
  - [x] Global /models folder tree structure [@ggrg]
  - [x] Rename models to follow table names (no more hyphenation) [@ggrg]
  - [x] Clean up unused processes and routes [@ggrg]
  - [x] Create global ENUM [@ggrg]
  - [x] Clean up tests [@ggrg]
  - Clean up unused dependencies and upgrade ones in use
  - [x] Create standard for facade layers for queries on multiple tables [@ggrg]
- [x] Unit tests - *previous unit tests report*: [@ggrg, @shashi165]
  *- tests 318*
  *- pass 318*
- [x] Integration tests [@ggrg, @vgenev]
- [x] Code coverage - *previous coverage report*: [@ggrg]
  *- Statements: 45.93% ( 1105/2406 )*
  *- Branches: 30.89% ( 139/450 )*
  *- Functions: 27.12% ( 144/531 )*
  *- Lines: 46.87% ( 1100/2347 )*

**Acceptance Criteria**:
- [x] All tables must be aligned to the design approved by the DA
- [x] Migration scripts generate tables as per design
- [x] Migration scripts insert seeds as per design (TODO: drop **contactType**)
- [x] Data access objects updated to allow for CRUD operations

**Dependencies**:
- None currently

**Accountability**:
- Owner @ggrg 
- QA/Review
