### ISSUE TITLE
5.2.2 Create Snapshot/Releases for end of PI2.4 for central repos

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#356]
**Goal**:
As a developer
I would like to _Create Snapshot/Releases for end of PI2.4 for central services repos_
so that updated code is reflected in master and old code is archived (saved)

**Tasks**:
- [x] Create Snapshot/Releases for 2.5.0 (end of PI2.4) for central services repos
- [x] Central-ledger snapshot and release
- [x] Central-services-shared snapshot and release
- [x] Central-services-database snapshot and release
- [x] Central-services-auth snapshot and release
- [x] Central-kms snapshot and release
- [x] Central-directory snapshot and release
- [x] Central-services-error-handling snapshot and release
- [x] Forensic-logging-sidecar snapshot and release
- [x] Pathfinder-provisioning-client snapshot and release
- [x] Pathfinder-query-client snapshot and release
- [x] ML-api-adapter snapshot and release

**Note**:
The releases for Central-end-user-registry, central-fraud-sharing and central-hub have not been done as those repos are not developed for release

ml-api-adapter
**Acceptance Criteria**:
- [x] Snapshot/Releases for end of PI2.4 for central services repos are done (and tagged)

**Dependencies**:
- [x] Issues with merges, conflicts

**Accountability**:
- Owner 
- QA/Review

**Comment by rmothilal** [comment]
Need to confirm with @elnyry about the versions that need to be released
