### ISSUE TITLE
[quoting-service] Re-enable caching on getParticipant and getParticipantEndpoint

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#3565]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` <action>
  
`so that` <reason> 

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Add configuration to configure cache TTL
- [ ] Re-enable getParticipant and getParticipantEndpoint code in cachedDatabase.js
- [ ] Fix any tests that are failing by adjusting the caching or write a story if necessary to address any problems 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by kleyow** [comment]
[TTK-Assertion-Report-gp_tests_2023-10-18T20_47_02.132Z.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2RPQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e3938d7a06002126451705adf92e876b6a0378c2/TTK-Assertion-Report-gp_tests_2023-10-18T20_47_02.132Z.zip)
