### ISSUE TITLE
Review ml-api-adapter repo for quality

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#357]
**Goal**:
As a QA
I would like to _see the ml-api-adapter repo updated for quality with regards to commented code, unused, updated dependencies_
so that it meets the quality standards of the mojaloop project

**Tasks**:
- [x] Identify and cleanup un-used dependencies - [@shashi165]
- [x] Identify and cleanup un-used configurations - [@shashi165]
- [x] Clean-up commented out, unused code - [@shashi165]
- [x] Add appropriate logging - [@shashi165]
- [x] update the documentation - [@shashi165]
- [ ] ~change unit tests of route to avoid spinning up of the server~(as of now this is the correct way to test routes of hapijs)
- [x] remove caret and tilde from package.json - [@shashi165]

**PRs**
- [x] https://github.com/mojaloop/ml-api-adapter/pull/57

**Acceptance Criteria**:
- [x] The ml-api-adapter project is refined to remove any unused code and dependencies

**Dependencies**:
- None currently

**Accountability**:
- Owner 
- QA/Review
