### ISSUE TITLE
FX Transfers Prepare & Fulfil POV (proof of value) for switch (2pt left)

### ISSUE THREAD

**Issue by JaneS321** [mojaloop/project#3574]
**Background:**
As the FX API’s have not been completely ratified by the community, it seems logical for the first FX delivery to be a POV to illustrate the end to end functioning is a basic way. This way if there are API changes that are made, they can be accomodated in subsequence hardening of the POV stories.

As Community member interested in the FX workflow

I would like to prove that the FX use case meets the product requirements

So that I can validate and confirm the FX design

 

**Acceptance Criteria**

- [x] Build basic functionality for the fxTransfer Prepare & Fulfil at the switch only without unit tests/integration tests
- [x] Build basic functionality for the FX related changes to transfers Prepare & Fulfil at the switch only without unit tests/integration tests
- [x] Verify that a basic end-to-end test exists

**Tasks**
- [x] Testing stack for Docker Compose #3593 [@geka-evk ]
- [x] Research 5 use cases of FXP [@geka-evk ]
- [x] Design database tables extenstions and interfaces for FX [@vijayg10 ]
   - [x] Design new tables
   - [x] Update existing tables
   - [x] Create migration scripts
   - [x] Cyril - Interface definition
- [x] Update ML API Adapter [@geka-evk ]
    - [x] Add FX transfers Request (POST)
    - [x] Add FX transfers callback (PUT + /error)
- [x] Update ML Notification Handler [@geka-evk ]
    - [x] Add FX transfers Request (POST)
    - [x] Add FX transfers callback (PUT)
- [x] Update central handlers to support FX
  - [x] `Prepare handler` for handling FX transfers [@geka-evk ]
  - [x] `Position-prepare handler` for handelling FX transfers [@vijayg10 ]
  - [x] `Position-commit handler` for handelling FX transfers [@vijayg10 ]
  - [x] `Fulfil handler` for handelling FX transfers [@vijayg10 ]

**Feature Branches**
- https://github.com/mojaloop/central-services-shared/tree/feat/fx-impl
- https://github.com/mojaloop/central-ledger/tree/feat/fx-impl

**Pull Requests**
- [x] https://github.com/mojaloop/central-ledger/pull/986
- [x] https://github.com/mojaloop/central-ledger/pull/988
- [x] https://github.com/mojaloop/ml-api-adapter/pull/517
- [ ] TBD
