### ISSUE TITLE
Investigate Kafka Config changes wrt performance

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3575]
## **Goal**:
`As a` Mojaloop Community member
`I want to` optimise my Kafa configuration for performance
`so that` I can get better use of my hardware so that I can optimise my hardware and running costs to match my performance requirements 

**Note: **The latest Kafka config optimisations in an end-to-end test translated in a drop in performance. This needs to be understood and rectified.

**Acceptance Criteria**:
- [ ] Itentify the kafka configuration that has caused the performance degradation
- [ ] Provide a new config recomendation that addresses the issues identified
- [ ] Update the performance baseline to reflect the new configuration's performance
- [ ] Any work identified that is too large to be included in this story, should be written up as a new story.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
