### ISSUE TITLE
[HELM] Update Helm to enable deployment of batching

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3577]
## **Goal**:
`As a` Mojaloop Community member
`I want to` be able to deploy the latest batch improvements to the position handler
`so that` I can benefit from the performance gains and cost reductions

The latest batch position handler work allows the redirection of kafka messages to the new batch position handler through configuration. I.e. this functionality can be turned on or off through config.

**Acceptance Criteria**:
- [ ] Verify that a helm value exists to configure the position handler events kafka topics
- [ ] Verify that the batching position handler can be enabled through setting helm values
- [ ] Verify that the batching position handler can be disabled through setting helm values

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Add new service to helm
- [x] Add configuration for new kafka topics
- [x] Add to documentation which configs need to be changed to cofigure batching
- [x] Deploy the helm chart
- [x] test the GP

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/helm/pull/582

## **Follow-up**:
- https://github.com/mojaloop/project/issues/3582
- https://github.com/mojaloop/project/issues/3581

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Thanks @vijayg10 , great work..

**Comment by vijayg10** [comment]
Closing this story as the PR to be merged after resolving issues with batch impl.
