### ISSUE TITLE
Investigate Kafka 

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3578]
## **Goal**:
`As a` Performance Engineer

`I want to` understand why "recommended" Kafka configuration from the [ml-perf-characterization](https://github.com/mojaloop/ml-perf-characterization/tree/main/lib-central-services-stream#follow-up-stories) findings result in worse performance than default Kafka configurations
  
`so that` we can find the optimised Kafka configuration to ensure that Mojaloop is able to performance as optimally as possible

References:
- https://github.com/mojaloop/ml-perf-characterization/tree/main/lib-central-services-stream#follow-up-stories

**Acceptance Criteria**:
- [ ] Investigate impact of "recommended" Kafka configuration to baseline configurations on Performance Workstream
- [ ] Document findings, observations and recommendations
- [ ] Validate any improvements via a re-baseline, with documented results

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
