### ISSUE TITLE
Document that the system only supports transfers in the "Same currency"

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#358]
**Goal**:
As a maintainer of the Mojaloop GitHub repositories
I would like to _document that the system only supports transfers in the "Same currency" (Supports multi-currency but not cross-currency)_
so that the system capabilities are accurately portrayed and to avoid ambiguity.

**Tasks**:
- [x] Identify a location to make note about the multi-currencies (cross-currency) capability(@HenkKodde )
- [x] Document that the system only supports transfers in the "Same currency" (Supports multi-currency but not cross-currency)

**Acceptance Criteria**:
- [x] The documentation for Mojaloop explicitly states the capability of supporting multi-currency but not cross-currency transfers.

**PR Create**
- [x] https://github.com/mojaloop/docs/pull/84

**Dependencies**
- None currently

**Accountability**:
- Owner 
- QA/Review
