### ISSUE TITLE
Characterise the full end-to-end financial transaction

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3590]
## **Goal**:
`As a` Mojaloop Community member
`I want to` understand the performance characterisation of the full end-to-end financial transaction 
`so that` use this to plan and cost an appropriate deployment of mojaloop that meets my availability and performance requirements.

`As a` Mojaloop Community development team adding and extending functionality
`I want to` understand the performance characterisation of the full end-to-end financial transaction 
`so that` i can ensure that the performance impact of my changes are understood.

**Acceptance Criteria**:
- [ ] Verify that the transactions per second performance of the transaction clearing is understood
- [ ] Verify the amount of data stored per transfer is understood

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Old Epic; Closing.
