### ISSUE TITLE
Build the full end-to-end financial transaction test-harness

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3591]
## **Goal**:
**As a** Mojaloop Community Member running performance testing
**I would like to** use K6 as my test runner
**So that I** can execute the performance tests on the full end-to-end transactions (including discovery and quotes)

Add to the new test-core harness as a new profile.

**Acceptance Criteria**:
- [ ] K6 load tests for end-to-end transactions
- [ ] simulated call-back handlers (web socket) for mocking the DFSPs 
- [ ] Test cases
   - [ ] test case 1 : 2 DFSPs with strict payer and payee
- [ ] Update call-back handler service Grafana dashboards to display metrics by DFSP
- [ ] Verify that all API resorces have metrics and appropriate dashboards. If any gaps are identrified then add, or if too large write up the stories to cover these gaps.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] K6s scenario/script for end-to-end testing
- [x] Docker profile for end-to-end harness
- [x] Update documentation on how to run test

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
