### ISSUE TITLE
Performance Characterise of the full financial end-to-end transaction

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3592]
## **Goal**:
`As a` Mojaloop Community Member considering adopting Mojaloop
`I want to` understand the performance of the core end-to-end system of the current Mojaloop version
`So that I` can understand scaling limits and associated costs in order to build my business model

This story is to build on #3591 and use the test harness to perform performance characterisation of the end-to-end functionality.

**Acceptance Criteria**:
- [ ] Verify that the [perf documenation](https://github.com/mojaloop/ml-perf-characterization) is updated
   - [ ] New end-to-end section added describing approach and method to reproduce
   - [ ] Result dashboards
- [ ] Perform obvious / easy to fix performance problems found. 
- [ ] Write up stories or document more extensive performance extensions identified.
- [ ] Verify that the end-to-end per second performance is understood
- [ ] Verify the amount of data stored per end-to-end transfer is understood

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
