### ISSUE TITLE
Incorporate FX into TTK

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3593]
## **Goal**:
`As a` mojaloop community member
`I want to` utilise the TTK ui and test cases infrastructure
`so that` I can later build on this to utilise TTK for FX development testing, integration testing and for technical demonstartions

**Acceptance Criteria**:
- [ ] Verify that the FSPIOP FX API extensions are available in TTK
- [ ] Verify that the SDK backend and core connector FX API extenstions are available in TTK
- [ ] Verify that a basic happy path end-to-end FX test for Payer DFSP FX conversion supporting a SEND transfer type can run

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
