### ISSUE TITLE
Add support for custom annotation to helm chart deployments 

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3599]
## **Goal**:
`As a` Hub deployer
`I want to` add support for custom annotations  
`so that` we can set annotations on deployment to support capability like Istio

**Acceptance Criteria**:
- [ ] Verify that each helm chart included in a mojaloop release supports custom annotations
   - [ ] Services (all ready done - please verify)
   - [ ] Ingress (all ready done - please verify)
   - [x] deployments
   - [x] stateful sets

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
