### ISSUE TITLE
Ensure the zero sum of money on the Switch

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#360]
**Goal**:
As an FSP
I would like to _ensure the zero sum of money on the Switch_
to confirm that all the incoming and outgoing money including fees are accounted for.
As an Regulator
I would like to _ensure the zero sum of money on the Switch_
to confirm that all the incoming and outgoing money including fees are accounted for.

**Tasks**:
- [ ] Identify how to prove the system's zero sum (all incoming money matches outgoing money, accounting for fees)
- [ ] Document outcomes, possibly visually

**Acceptance Criteria**:
- [ ] Documentation is available that shows that the Switch ensures its zero sum capability (incoming and outgoing money, accounting for fees, matches)

**Dependencies**:
- None currently

**Accountability**:
- Owner 
- QA/Review
