### ISSUE TITLE
5.5.0 Update central services database to support batch inserts and transactions

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#361]
**Goal**:
As a Switch
I would like to _Update central services database to support batch inserts and transactions_
so that batching could be implemented for efficiency and optimization.

**Tasks**:
- [x] Investigate what is needed to be done in central services database to support batch inserts and transactions
- [x] Update central services database to support batch inserts and transactions

**Acceptance Criteria**:
- [x] Central services are updated to enable the database to support batch inserts and transactions

**Dependencies**:
- None currently

**Accountability**:
- Owner 
- QA/Review
