### ISSUE TITLE
Reject action implementation for maker-checker flows

### ISSUE THREAD

**Issue by TW-Ei-Nghon-Phoo** [mojaloop/project#3614]
### Hub
- [ ] Accounts >> Account Change Requests

###  Participant

- [x]  Accounts >> Account Change Requests
- [x] Funds Movements >> Funds Movement of this Participant
- [x]  NDC >> Net Debit Caps of this Participants
- [x] Contacts >> Contact Information Change Requests

**Acceptance Criteria**:

- [x] Basic Functionality
  - [x] Checker users should be able to reject pending approval requests
- [x] No Effect on Data before checker approves or reject an action
  - [x] Before approved or rejected by checker, the pending requests should not have any effects on existing data. 
- [x] Flagging Rejected Actions
  - [x] After rejection, the system should flags the "action status" as "rejected" in the approval audit log table.
  - [x] Approval audit log includes:
    - [x] Detail action information (such as amount, activity name)
    - [x] Action status: "rejected"
    - [x] Maker and checker names
    - [x] Checked date
    - [x] Requested date
- [x] Removal from Pending List
  - [x] Rejected approval requests are removed instantly from the pending list.
- [x] Appearance in Audit Log Record Table
  - [x] Rejected requests appear in the approval audit log record table.
- [x] Audit Log Accuracy
  - [x] Audit log accurately reflects rejection details.
- [x] User Permissions
  - [x] Only checker users can reject pending approval requests.
- [x] Error Handling
  - [x] Clear and informative error messages for rejection process errors such as "Checker and Maker cannot be the same for an action".
- [x] Logging Timestamps
  - [x] Accurate timestamps for checked date and requested date in the rejection process.

### Tasks
- [x] Acceptance Criteria pass
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Code Review
- [x] QA Passed

**Comment by pedrosousabarreto** [comment]
Thanks @einghon-phoo 
We definitely needs this. Ideally, rejecting the requests simply deactivates the request.

Ideally all approval flows use the same structure, and we should replace the current approved: boolean, with a more elaborate state like:
export enum ApprovalRequestState{
    CREATED = "CREATED",
    APPROVED = "APPROVED",
    REJECTED = "REJECTED" 
}
Also, these fields should be renamed like this:
- approvedBy: string | null; -> lastActionBy: string; - here we record who did the last action (create, approve or reject)
- approvedDate: number | null; -> lastActionAt: number; - here we record the timestamp of that last action

We will still keep the history in the change log array, so we don't have to capture history in the multiple arrays, only last state.

**Comment by einghon-phoo** [comment]
Ko @SithuKyaw-Thitsaworks

**Comment by einghon-phoo** [comment]
https://github.com/mojaloop/platform-shared-tools/pull/45 <== pull request

**Comment by elnyry-sam-k** [comment]
Thank you @SithuKyaw-Thitsaworks for the discussion.

During the review checking the acceptance criteria, we had an issue with this item from the acceptance criteria - "After rejection, the system should flags the "action status" as "rejected" in the approval audit log table.". Once this is resolved, we can resume going through the list for review.

Apart from that, we'll need detailed sequence diagrams for the functionality for this item

**Comment by TW-Ei-Nghon-Phoo** [comment]
<img width="1593" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2JSQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8cf9ab68fee0b1c7b67f401afee38a7471443dfd/image.png" alt="image.png" />

> During the review checking the acceptance criteria, we had an issue with this item from the acceptance criteria - "After rejection, the system should flags the "action status" as "rejected" in the approval audit log table.". Once this is resolved, we can resume going through the list for review.

@elnyry-sam-k

**Comment by elnyry-sam-k** [comment]
Thanks @SithuKyaw-Thitsaworks for helping confirm the acceptance criteria. One follow-up item came up during this discussion about audits having issues when an elastic search pod /service wasn't running. The actions done during this time were missed, need an issue to address this issue.
