### ISSUE TITLE
Investigate and resolve issues with dependencies upgrades in ML repos

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#3616]
## **Goal**:
`As a` Maintainer

`I want to` investigate and fix issues relating to upgrades to npm dependencies in some ML repos
  
`so that` those repos can have up to date versions of the respective dependencies

**Acceptance Criteria**:
- [ ] Dependencies are updated
- [ ] Unit tests pass
- [ ] CI process validates the update successfully

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
Affected repos and packages:
- [ ]  central-ledger
  - [ ]  sinon
  - [ ]  get-port
- [ ]  ml-api-adapter
  - [ ]  central-services-stream
  - [ ]  get-port

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by kalinkrustev** [comment]
This is being addressed in this branch https://github.com/mojaloop/ml-api-adapter/tree/feat/event-kafka
