### ISSUE TITLE
Extend the FX POC/v to include the FXP Mojaloop Connector SDK 

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3618]
## **Goal**:
Background:
As the FX API’s have not been completely ratified by the community, it seems logical for the first FX delivery to be a POV to illustrate the end to end functioning is a basic way. This way if there are API changes that are made, they can be accomodated in subsequence hardening of the POC stories. This story is to extend the current POV to include the Mojaloop Connector (SDK) for the FXP

As Community member interested in the FX workflow
I would like to prove that the Mojaloop Connector supports the FXP in the FX flow
requirements
So that I can validate and confirm the FX design

**Acceptance Criteria**
 - [x] Build basic functionality in the Mojaloop Connector (SDK) POST/PUT fxQuote to support the FXP
 - [x] Build basic functionality in the Mojaloop Connector (SDK) POST/PUT fxTransfers to support the FXP
 - [x] Add the Mojaloop Connector (SDK) to the core test harness to simulate FXP

 
**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x]  Add support for inbound POST /fxQuotes and POST /fxTransfers requests to SDK
- [x]  Add the Mojaloop Connector (SDK) to the core test harness to simulate FXP

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- https://github.com/mojaloop/sdk-scheme-adapter/pull/458
- https://github.com/mojaloop/sdk-standard-components/pull/190
- https://github.com/mojaloop/ml-core-test-harness/pull/43/files

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3618?planning-poker) with Zenhub @aaronreynoza @kleyow @oderayi @sri-miriyala @geka-evk
