### ISSUE TITLE
NodeJS Performance Recommendations and Optimizations

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3619]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` optimize node services with recommended changes and libraries
  
`so that` improve overall performance of the mojaloop switch

**Stories**:
- [ ] Avoid returning resolved promises (Refactor the return statements to return unresolved promises instead of await them)
- [ ] Investigate / Characterise the difference in performance with logging library winston vs pino
- [ ] Replace inefficient JSONStringify calls with a faster alternative like fastStringify.
