### ISSUE TITLE
Investigate / Characterize the Difference in Performance with Logging Libraries Winston vs Pino

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3621]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` compare the performance of logging libraries Winston and Pino
  
`so that` we can make an informed decision on the most efficient and lightweight logging solution for our services, optimizing resource usage and improving overall performance

**Acceptance Criteria**:
- [ ] Investigate the difference in performance of logging libraries Winston and Pino
- [ ] Document the findings and provide a detailed report outlining the characteristics and nuances of each logging library's performance

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
