### ISSUE TITLE
ALS node optimization: Replace Inefficient JSONStringify Calls with fastStringify

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3622]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` replace slow JSONStringify calls with fastStringify
  
`so that` our JSON serialization becomes swift and efficient, reducing processing time and improving overall application performance

**Acceptance Criteria**:
- [ ] Identify and locate instances where JSONStringify calls are causing performance bottlenecks
- [ ] Integrate the fastStringify library into the codebase as a replacement for slow JSONStringify calls
- [ ] Ensure that the replacement does not alter the expected behavior of the application and maintains data integrity
- [ ] Conduct performance tests to validate the improvement in JSON serialization speed

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
