### ISSUE TITLE
Performance Characterise of the full financial end-to-end transaction on distributed environment

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#3623]
## **Goal**:
`As a` Mojaloop Community Member considering adopting Mojaloop
`I want to` understand the performance of the core end-to-end system of the current Mojaloop version
`So that I` can understand scaling limits and associated costs in order to build my business model
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMysxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3dbe2622af82d606961ec93e0c858ee7cb48e773/Performance%20Multi%20Node%20Setup.drawio.png)

This need to be run on the on premise docker compose environment in a distributed setup.
**Acceptance Criteria**:

- [ ] Reach understanding of what it takes to reach 1000 e2e tps
- [ ] Verify the amount of data stored per end-to-end transfer is understood

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Address or create stories for improvements blocking 1000 tps
- [ ]  Document disk space usages for transfers

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by kleyow** [comment]
Priority has been switched from working on a docker based envioronment to a kubenetes one.

We found that these env variables were close to achieving 1000 ops/s individually.
```
QS_REPLICAS=12
ALS_REPLICAS=12
CENTRAL_LEDGER_GENERAL_REPLICAS=6
CENTRAL_LEDGER_PREPARE_REPLICAS=12
CENTRAL_LEDGER_FULFIL_REPLICAS=12
CENTRAL_LEDGER_POSITION_REPLICAS=25
CENTRAL_LEDGER_POSITION_BATCH_REPLICAS=8
ML_API_ADAPTER_REPLICAS=4
ML_NOTIFICATION_REPLICAS=8

KAFKA_GENERAL_PARTITIONS_NUM=4
KAFKA_POSITION_PARTITIONS_NUM=25
KAFKA_POSITION_BATCH_PARTITIONS_NUM=4
KAFKA_NOTIFICATION_PARTITIONS_NUM=4
```

Take note of the 25 replicas of the position handler, we found that any replica count n<25 has a chance of not assigning a replica of the position handler to one of the partition that handles a specific fsp due to keying of messages. 

Due to a shift in focus the task of "Document disk space usages for transfers" has been defered for the kubenetes testing.
