### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by TW-Ei-Nghon-Phoo** [mojaloop/project#3634]
- [ ] Readme page of all repos 
     - [ ]  Overview of functionality
     - [ ]   Instructions to run the service independently
     - [ ]  Instructions to run tests
     - [ ]  Configuration options (env variables, etc to be set)
     - [ ]  Known issues
     - [ ]  Links to docs for details on functionality, sequence diagrams 
- [ ] Deployment documentation of vNext (or bundle) that includes all the required services.
- [ ] release notes outlining new features, changes, and known issues.
- [ ] Code Coverage (75%)
- [ ] Vulnerability check [npm audit [github](https://github.com/mojaloop/central-ledger/blob/bdff6c73bae5c12520696695b778bd7deb727fa2/.circleci/config.yml#L382)]
- [ ] Image scan
- [ ] License checks / audit
- [ ] TTK test collection
- [ ] docker compose, miniloop,EKS documentation

**Comment by JulieG19** [comment]
Hi @TW-Ei-Nghon-Phoo, we will create a release page where we document a release check list and go through the completion of the items before go/no do decision. As a result, I am closing this for now. Please let me know if you have any issues with this. Thanks!
