### ISSUE TITLE
Batch functionality Helm release (v15.3.0) RC

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#3636]
## **Goal**:
`As a` Mojaloop maintainer

`I want to` resolve all pending issues relating to batch processing release
  
`so that` the batch feature can be available in a Mojaloop release 

This is a follow-up story on #3489 

**Tasks**:
- [x] Address [PR](https://github.com/mojaloop/central-ledger/pull/968) comments in central-ledger  
- [x] Resolve issues with Helm [PR](https://github.com/mojaloop/helm/pull/582) 
- [x] Fix batch related bugs 
  - [x] #3581
  - [x] #3582
- [x] Document, investigate and fix issues with deployment in moja2 #3660
- [x] Update Helm chart
- [ ] Create a Mojaloop release that includes the batch feature
- [x] Create matching release of ttk-test-cases release and use the released version in the helm release
- [x] Create release note for the release
- [ ] Verify release in moja2
- [ ] Verify release in moja1

**Acceptance Criteria**:
- [ ] A new Mojaloop release is done
- [ ] The release includes the batch feature
- [x] The batch feature is disabled by default
- [ ] The oss-core-dev repo is updated with a values file that has batch enabled to aid testing
- [ ] Helm release is tested and verified in moja1 dev environment
- [ ] All tests pass

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] https://github.com/mojaloop/central-ledger/pull/968
- [ ] https://github.com/mojaloop/helm/pull/582
- [ ] https://github.com/mojaloop/helm/pull/587
- [ ] https://github.com/mojaloop/oss-core-env/pull/2
- [ ] https://github.com/mojaloop/testing-toolkit-test-cases/pull/133

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by oderayi** [comment]
Application versions for this release:
-----------------
ml-api-adapter: [v14.0.0 --> v14.0.5](https://github.com/mojaloop/ml-api-adapter/compare/v14.0.0...v14.0.5)
central-ledger: [v17.0.3 --> v17.3.2](https://github.com/mojaloop/central-ledger/compare/v17.0.3...v17.3.2) 
account-lookup-service: [v14.1.0 --> v15.0.0](https://github.com/mojaloop/account-lookup-service/compare/v14.1.0...v15.0.0)
quoting-service: [v15.0.2 --> v15.5.0](https://github.com/mojaloop/quoting-service/compare/v15.0.2...v15.5.0)
central-settlement: [v15.0.0 --> v16.0.0](https://github.com/mojaloop/central-settlement/compare/v15.0.0...v16.0.0) 
bulk-api-adapter: [v15.0.3 --> v17.0.0](https://github.com/mojaloop/bulk-api-adapter/compare/v15.0.3...v17.0.0)
central-event-processor: v12.0.0 - no new release
email-notifier: [v12.0.0 --> v14.0.0](https://github.com/mojaloop/email-notifier/compare/v12.0.0...v14.0.0)
als-oracle-pathfinder: v12.0.0 - no new release
transaction-requests-service: [v14.1.0 --> v14.1.2](https://github.com/mojaloop/transaction-requests-service/compare/v14.1.0...v14.1.2)
finance-portal-ui: v10.4.3 (DEPRECATED) - not upgraded in the last release
finance-portal-backend-service: v15.0.2 (DEPRECATED) - not upgraded in the last release
settlement-management: v11.0.0 (DEPRECATED) - no new release
operator-settlement: v11.0.0 (DEPRECATED) - no new release
event-sidecar: [v12.0.0 --> v14.0.0](https://github.com/mojaloop/event-sidecar/compare/v12.0.0...v14.0.0)
event-stream-processor: v12.0.0-snapshot.7 - no new release
simulator:  v12.0.0 - no new release
mojaloop-simulator: [v14.0.1 --> v15.0.0](https://github.com/mojaloop/mojaloop-simulator/compare/v14.0.1...v15.0.0)
sdk-scheme-adapter: [v23.0.1 --> v23.1.1](https://github.com/mojaloop/sdk-scheme-adapter/compare/v23.0.1...v23.1.1)
ml-testing-toolkit: [v16.1.1 --> v17.0.0](https://github.com/mojaloop/ml-testing-toolkit/compare/v16.1.1...v17.0.0)
ml-testing-toolkit-ui: v15.4.0 - no new release
ml-testing-toolkit-client-lib: v.1.2.0
auth-service: [v14.0.0 --> v15.0.0](https://github.com/mojaloop/auth-service/compare/v14.0.0...v15.0.0)
als-consent-oracle: [v0.2.0 --> v0.2.1](https://github.com/mojaloop/als-consent-oracle/compare/v0.2.0...v0.2.1)
thirdparty-api-svc: [v13.0.2 --> v14.0.0](https://github.com/mojaloop/thirdparty-api-svc/compare/v13.0.2...v14.0.0)
thirdparty-sdk: [v15.1.0 --> v15.1.1](https://github.com/mojaloop/thirdparty-sdk/compare/v15.1.0...v15.1.1)
