### ISSUE TITLE
Extend the FX POC/v to include SDK Payee DFSP changes

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3655]
## **Goal**:
Background:
As the FX API’s have not been completely ratified by the community, it seems logical for the first FX delivery to be a POC/V to illustrate the end to end functioning is a basic way. This way if there are API changes that are made, they can be accomodated in subsequence hardening of the POC stories. This story is to extend the current POV to include the Mojaloop Connector (SDK) for the Payee DFSP

As Community member interested in the FX workflow
I would like to prove that the Mojaloop Connector supports the Payee DFSP in the FX flow implementing the Payee DFSP FX converion
requirements
So that I can validate and confirm the FX design

**Acceptance Criteria**
 - [ ] Build basic functionality in the Mojaloop Connector (SDK) **GET parties** that a Payee DFSP would require to support the payer FX conversion FX use case.
 - [ ] Build basic functionality in the Mojaloop Connector (SDK) **POST/PUT quotes** that a Payee DFSP would require to support the payer FX conversion FX use case.
 - [ ] Build basic functionality in the Mojaloop Connector (SDK) **POST/PUT transfers** that a Payee DFSP would require to support the payer FX conversion FX use case.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3655?planning-poker) with Zenhub @aaronreynoza @kleyow @oderayi @sri-miriyala @vijayg10

**Comment by PaulGregoryBaker** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3655?planning-poker) with Zenhub @geka-evk
