### ISSUE TITLE
[ML-API Adapter] Hardening this component so that it meet ML standards for FX

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3656]
## **Goal**:
`As a` Mojaloop Community member making use of FX conversion in mojaloop
`I want to` ensure that the FX implementation POC is matured 
`so that` it can be merged into master and ultimately included in a release of mojaloop and used.

**Acceptance Criteria**:
- [x] Verify that error cases are mapped and documented.
- [x] Verify that the integration test are added to test the error cases.
Need to assert on the kafka message.
- [x] Verify that unit test are added
- [x] Verify that all mojaloop core standards are met

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Add unit tests [@geka-evk]
- [x] Fix peer dependencies resolution issues [@oderayi] 
- [x] Map error cases and document [@oderayi ] 
- [x] Fix existing integration testing issues/bugs [@oderayi] 
- [x] Add integration tests to cover error cases and assert on kafka messages [@oderayi] 
    - [x] API Routes Handler (api/transfers/handler.js) [@oderayi] 
      - [x] Handler.create - unhappy paths
      - [x] Handler.fulfilTransfer - unhappy paths
      - [x] Handler.fulfilTransferError - happy and unhappy paths
      - [x] API has no fx specific get endpoint - need to confirm this
    - [x] Domain Logic (domain/transfers/index.js) [@oderayi] 
      - [x] TransferService.prepare - happy and unhappy paths
      - [x] TransferService.fulfil - happy and unhappy paths
      - [x] TransferService.transferError - happy and unhappy paths
      - [x] TransferService.getTransferById - happy and unhappy paths
    - [x] Notification handler [@oderayi] 
- [x] Notification handler unit tests [@oderayi] 
- [x] Refactor integration test mock server for FX [@oderayi]
- [x] Complete related _TODOs_ in code [@oderayi] 
    - [x] Implement logic for negative cases action types for FX in notification handler
    [ FX_PREPARE_DUPLICATE, FX_ABORT, FX_ABORT_VALIDATION, FX_RESERVED_ABORTED, FX_FULFIL_DUPLICATE, FX_ABORT_DUPLICATE, FX_TIMEOUT_RESERVED, FX_TIMEOUT_RECEIVED, FX_GET ]
    - [x] Implement remaining endpoints [ GET, ~PATCH~ ] 
    - [x] Add unit tests for new code 
    - [x] Add integration tests for new code 
- [x] Verify Mojaloop core standards are met 

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-api-adapter/pull/520
- [x] https://github.com/mojaloop/central-services-error-handling/pull/186
- [x] https://github.com/mojaloop/central-services-health/pull/257
- [x] https://github.com/mojaloop/central-services-health/pull/258
- [x] https://github.com/mojaloop/central-services-stream/pull/137
- [x] https://github.com/mojaloop/event-sdk/pull/79
- [x] https://github.com/mojaloop/central-services-shared/pull/368
- [x] https://github.com/mojaloop/ml-api-adapter/pull/522

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by geka-evk** [comment]
Added unit-tests to have proper test-coverage: https://github.com/mojaloop/ml-api-adapter/pull/520/commits/f3bbb2af7ad3ab1cfc740e643fbfe9f9cc1b380d

PR: https://github.com/mojaloop/ml-api-adapter/pull/520
