### ISSUE TITLE
Refactor Quoting Service into an event driven solution to improve performance

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3666]
## **Goal**:
`As a` Mojaloop Community member
`I want to` have a performant quoting service
`so that` I can scale the quoting servce 

**Note:** The current quote service performs this action in memory, and a better solution would be to split the servce into two microservices with Kafka events. This will decouple the participant API responses from the work being perfromed and free's up the nodeJS event loop.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXNUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8facbd002e5eea75d06e821dfd7ef88664c2363/InstantRemittanceNetwork-Quotes.png)

**Acceptance Criteria**:
- [x] Verify the Quote service is split into two microservices namely an quotes API service and and quotes handler service
- [x] Verify that a configurable kafka topic is used to pass messages between the servcies (kafka configuration should follow same pattern as central ledger)
- [x] Verify that the GP test pass
- [x] Verfy that there is a new runtime CLI option (using commander lib; same as central ledger)
- [x] Verfy that a health endpoint is added to the new servces

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Define proper Kafka config for Producers and Consumer
- [x] Update logic of API handlers to publish a payload into separate kafka queues (quotes/bulk_quotes  get/put/post)
- [x] Create a consumer to handle all new kafka topics
- [x] Add/update unit-tests
- [x] Update test-harness to use a new version of Quoting service
- [x] Update Help charts (to deploy consumers as well) 
- [x] Check GP tests
- [x] Add healthCheck functionality
- [x] Add unit-tests for all "helper" functionalities: https://github.com/mojaloop/quoting-service/pull/321#discussion_r1424874484

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/quoting-service/pull/321
- [ ] https://github.com/mojaloop/ml-core-test-harness/pull/45
- [ ] https://github.com/mojaloop/helm/pull/588

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3666?planning-poker) with Zenhub @aaronreynoza @kleyow @oderayi @sri-miriyala @vijayg10

**Comment by elnyry-sam-k** [comment]
@PaulGregoryBaker and @geka-evk , thanks for this issue. Please bring this up at the DA at the earliest; I'm not opposed to this and it makes sense but it is a significant change.
