### ISSUE TITLE
Address Performance of TTK backend running GP tests

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3667]
## **Goal**:
`As a` Mojaloop Community Member making use of the TTK to run functional end to end tests
`I want to` have the test complete in resonable time
`so that` am not delayed 

**Note:**
It was noticed that the TTK backend test running funcitons for the GP tests are relatively slow compared to how they used to perform. I.e. TTK used to perform the GP tests for a mojaloop in less that 2 minutes. Now this is not the case.
The point of this story is to identify the cause of the delay and then either fix the problem, or write up a story that defines the work that will fix the problem. 

**Acceptance Criteria**:
- [ ] Verify that the root cause of the delelay is identified.
- [ ] Verify that either a fix is make, or stories are created that address the root cause.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
