### ISSUE TITLE
Benchmark the Mojaloop Simulator

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3669]
## **Goal**:
`As a` Mojaloop Community member interested in running a hub
`I want to` understand the performance of a mojaloop
`so that` appropriately size my environment

Note: This story is about the characterisaction of the mojaloop simulator, so that it can be included in a wider performance test, and it's performance is known and understood and taken into consideration in that work.

**Acceptance Criteria**:
- [x] Verify that the **throughput** and **latency** is calculated for the mojaloop simulator on reasonable hardware for the following calls:
   - [x] get parties
   - [x] post quoteRequest
   - [x] post transfers

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Add party info to ML-SIM using testAPI for firsttime after you start the service (Using postman, curl ...etc. Doesn't need to be from K6)
- [x] Prepare a k6 test case to trigger GET /parties
- [x] Assert on http status code
- [x] Modify the k6 scenarios to find the best performance config (VUs, target http rate, etc)
- [x] Continue with quotes and transfers

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/mojaloop-simulator/pull/170

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by aaronreynoza** [comment]
Running tests on the quotes and transfers makes the simulator run out of memory with the following error:
```
simulator  | 
simulator  | <--- Last few GCs --->
simulator  | 
simulator  | [22:0x7fa8ab4eb020]    94332 ms: Mark-sweep 4050.7 (4138.2) -> 4037.9 (4141.7) MB, 1608.6 / 0.0 ms  (average mu = 0.401, current mu = 0.107) allocation failure; scavenge might not succeed
simulator  | [22:0x7fa8ab4eb020]    97425 ms: Mark-sweep 4052.4 (4141.7) -> 4040.6 (4144.5) MB, 3056.1 / 0.0 ms  (average mu = 0.177, current mu = 0.012) task; scavenge might not succeed
simulator  | 
simulator  | 
simulator  | <--- JS stacktrace --->
simulator  | 
simulator  | FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory 
```

SIM is unable to handle more than 700 requests per second as it bloats the memory. Test cases for this story are added on the PR mentioned above but they're unable to run until the memory leak on the sim is fixed.

**Comment by aaronreynoza** [comment]
Attaching monitoring results for `get /party`, `post /quote` and `post /transfer`:

![k6-getParty](https://github.com/mojaloop/project/assets/24705637/99c2af44-d670-45da-bf23-47978836e402)
![k6-postTransfer](https://github.com/mojaloop/project/assets/24705637/43e0104f-60c8-4783-a6a0-30c6cf1cb1ec)
![prometheus-postTransfer](https://github.com/mojaloop/project/assets/24705637/57ed947d-5c4d-4cfa-b48f-33d0e5343b6e)

![prometheus-getParty](https://github.com/mojaloop/project/assets/24705637/54e929cf-f1ef-4afe-87d3-755164199539)
![k6-postQuote-1000](https://github.com/mojaloop/project/assets/24705637/d26c763d-eca2-4b58-90c5-7f553866623a)
![prometheus-postQuote-1000](https://github.com/mojaloop/project/assets/24705637/fd88a012-ce6a-48a1-b709-d3c2846ee829)
