### ISSUE TITLE
Verify level of open API Scheme validation on ALS

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3671]
## **Goal**:
`As a` Mojaloop Community member implementing mojaloop
`I want to` ensure that all communication between participants in the discovery phase conforms to the Open API definition
`so that` I am confident the participants are effectively and appropriately communicating

Note: in the fx workstream it was noticed that addition fields returned from a participant get parties call, were automatically forwarded on to the requestion participant even though these field were not part of the Open API definition.

**Acceptance Criteria**:
- [ ] Verify that the level of Open API validation is in place for:
   - [ ] get parties
   - [ ] put parties
   - [ ] get participants
   - [ ] put participants

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
