### ISSUE TITLE
Test FX PoC on K8S based mojaloop deployment including mojaloop connectors

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3674]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` test FX PoC on K8S based mojaloop deployment including mojaloop connectors
  
`so that` I can run the PoC on K8s based deployment

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Deploy latest mojaloop helm chart on K8S
- [x] Upgrade snapshot versions for FX functionalit, make sure the upgrade adds the database changes and GP is running
- [x] Deploy three new SDKs for payer, payee and FXP
- [x] Test a FX transfer
- [x] Record an end2end demo
- [x] Share the documentation with team

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
