### ISSUE TITLE
[GIT-ACTIONS] Automate parts of the release process

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3686]
## **Goal**:
`As a` mojaloop maintainer
`I want to` make the process of making Mojaloop releases easier by using automation where possible
`so that` I can facilitate the access of new features as soon as the development is completed, to the adopters.

Note: This story is about automating parts of the release process so that releases are quicker to make, reducing the overhead involved and making maintenance easier.

**Acceptance Criteria**:
- [x] Verify that a github actions script for release automation is created
- [x] Verify that the application versions part of the release is automated
- [x] Verify that the script creates helm release candidate branch
- [x] Verify that the script update chart versions
- [x] Verify that the script deploys and tests the release candidate branch to Moja2
- ~Verify that package versions can be overridden in scenarios where the latest version is not to be used in a release~ Tracked in #3738 
   
**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---
**Tasks**:
- [x] research tools for the automation
- [x] develop package update manifest for all charts
- [x] create PR for prerequisite changes to the helm charts
- [x] validate pre-requisite update to helm chart in dev env
- [x] validate automatically updated chart in dev env
- [x] develop github action config and scripts to:
  - [x] create a release candidate branch from master
  - [x] detect breaking changes
  - [x] generate the release note
  - [x] determine the release version number based on changes
  - [x] create a matching snapshot release of TTK test collections
  - [x] deploy and test the branch in Moja2
- [x] Test workflow and fix all issues found

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/helm/pull/590
- [ ] https://github.com/mojaloop/helm/pull/595
- [ ] https://github.com/mojaloop/helm/pull/596
- [ ] https://github.com/mojaloop/oss-core-env/pull/2
- [ ] https://github.com/mojaloop/helm/pull/594

## **Follow-up**:
- [3738](https://github.com/mojaloop/project/issues/3738)

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
