### ISSUE TITLE
Design MOSIP Registration Portal

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3687]
## **Goal**:
`As a` Beneficiary Management System Builder / Implementer
`I want to` have an OAuth Open ID connect redirect portal that I can call from my system that authorises the user and return as payment token
`so that` I can then use that token for all future payments to that user.

`As a` development team building out the MOSIP POC
`I want to` have a design specified
`so that` I can orchestrate my work effort so that they meet the final objectives of the POC

**Description**
Develop a design for the registration portal for the MOSIP - MIFOS Proof of Concept (POC) supporting the Government to Person (G2P) use case. This design will guide the community members in building the portal to ensure that the final product meets the objectives of the POC.

**Acceptance Criteria**:
- [x] Verify that a sequence diagram is produced to illustrate the actions of the beneficiary registration portal during a beneficiary registration
- [x] Verify that a method to obtain the beneficiary accounts/selected account is decided on and documented. 
(This can either be a standard MIFOS call with the provided JWT token, or an enhanced OAuth login that returns the selected account based in the returned JWT.)
- [x] Verify that a persistant store solution is chosen and storage format designed documented to support the:
   - [x] Storage of the beneficiary tokens.
   - [x] Storage of DFSP registration detail that include UI information and technical redirect token endpoints with mechanism for retrieving user accounts.
- [x] Verify that Open API's exist for all API calls.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3687?planning-poker) with Zenhub @aaronreynoza @kleyow @oderayi @sri-miriyala @vijayg10

**Comment by PaulGregoryBaker** [comment]
Here is the PR for this story.
[https://github.com/mojaloop/ml-mosip-integration/tree/feat/329](https://github.com/mojaloop/ml-mosip-integration/tree/feat/329)

After this design story, the design changed and was updated.
