### ISSUE TITLE
Implement FX Quotes POC

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3689]
## **Goal**:
`As a` Mojaloop Community member interested in implementing FX
`I want to` build a POC to implement the FXQuote
`so that` I can prove that the FX flows work

**Assumption**: **SIMPLE ROUTING MODE is enabled for this PoC** (We don't need to create database tables and store the fxquotes)

_Reference documents:_
- [API Spec with FX](https://github.com/mojaloop/api-snippets/blob/main/docs/fspiop-rest-v2.0-openapi3-snippets.yaml)
- [Sequence diagram](https://github.com/infitx-org/uml_diagrams/tree/main/STDBank/FXAPI_POC_payer_conversion_SEND.svg)
- [Currency Conversion repo](https://github.com/mojaloop/Currency-conversion)

**Note**
- Implementation should be merged into a feature branch (`feature/fx-impl`) and not the `main` branch

**Acceptance Criteria**:
- [x] Verify that the FXquote endpoint is handled in the hub to route message to FX providers
- [x] Verify that the API resource complies with FSPIOP 2.0 definitions
- [x] Verify a happy path functional test is in place to test the new functionality

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Implement `POST /fxQuotes` endpoint
- [x] Implement `GET /fxQuotes/{ID}` endpoint
- [x] Implement `PUT /fxQuotes/{ID}` endpoint
- [x] Implement `PUT /fxQuotes/{ID}/error` endpoint
- [x] Implement `POST /fxQuotes` handler 
- [x] Implement `GET /fxQuotes/{ID}` handler
- [x] Implement `PUT /fxQuotes/{ID}` handler
- [x] Implement `PUT /fxQuotes/{ID}/error` handler
- [x] Add functional tests

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-shared/pull/359
- [x] https://github.com/mojaloop/quoting-service/pull/326
- [x] https://github.com/mojaloop/central-ledger/pull/995
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/469
- [x] https://github.com/mojaloop/quoting-service/pull/328
- [x] https://github.com/mojaloop/quoting-service/pull/329
- [ ] https://github.com/mojaloop/ml-core-test-harness/pull/52

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by JaneS321** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3689?planning-poker) with Zenhub @kleyow @mdebarros @sri-miriyala @vijayg10

**Comment by JaneS321** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3689?planning-poker) with Zenhub @aaronreynoza
