### ISSUE TITLE
Hub currencies configuration

### ISSUE THREAD

**Issue by ei-nghon-phoo** [mojaloop/project#3696]
## User Story:

**As a scheme owner,** **I want to** configure currencies from user interface **so that** we can have seamless scheme that operate in desirable currencies.

### Acceptance Criteria:

Acceptance Criteria for Currency Configuration:

1.	Global Currency Standard:
•	 The system will utilize the ISO 4217 standard for global currencies.
•	Currency configuration will include the following attributes: decimal place, numeric code, alphabetic code, and currency description.
•	   [ISO currency formats](https://www.iso.org/iso-4217-currency-codes.html#:~:text=The%20first%20two%20letters%20of,and%20the%20D%20for%20dollar.)

2.	Addition of New Currencies:
•	If a hub operator wishes to update the currency list with a currency not included in the latest system currency list, 
    or update the existing currency's attributes, they should be able to do so via the API.

3.	Currency Onboarding for Hub Operators:
•	Default currencies configured at the hub should automatically create corresponding accounts.
•	The hub operators have the option to manually create accounts for currencies beyond the default selection.
•	If hub operators choose to add accounts for currencies beyond the defaults, they can do so through manual creation.
4.	Participant DFSP Currency Creation:
•	Participant DFSPs will have the capability to create accounts with newly onboarded currencies.
5.	Currency Display in Admin Portal UI:
•	Currency-related drop-down menus and displays in the admin portal UI should reflect the updated currency list, ensuring alignment with the system's currency configuration.
6.	Adding a currency should adhere maker checker mechanism.
7.	The system should enable the hub operators to add multiple currencies within a single hub. (Background: Some hubs will facilitate cross-border payments, necessitating multi-currency payment operations.)

## approach to be considered
- enabling hub operators to configure currency from the user interface with or without maker checker mechanism
- configuring hub currencies from hub onboarding/set up stage from backend or infrastructure level. 
- 

<img width="1282" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1hXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4adca2ccd0c2b5b6757e449525a6e550b497f5af/image.png" alt="image.png" />

**Comment by TW-Ei-Nghon-Phoo** [comment]
Future plan: disabling a currency.

**Comment by TW-Ei-Nghon-Phoo** [comment]
### Action plan
- [ ]  Adding MongoConfigSetRepo and ‌adding new currency from API with the attributes (numeric code, currency code and decimal place) with ISO 4217 format.
- [ ]  Consuming config changes from other Bounded Contexts 
- [ ]  Updating Admin UI to use the platform-configurations-bc: [design file](https://www.figma.com/proto/80cD3AKOglNk3UhCUxbILi/vNext-Portal?page-id=9%3A10&type=design&node-id=7190-9368&viewport=379%2C864%2C0.35&t=D1pUhTp2upmOwThw-1&scaling=scale-down&starting-point-node-id=7190%3A9368&show-proto-sidebar=1&mode=design)

cc: @hsuyeemon-tw

**Comment by bushjames** [comment]
@PaulMakinMojaloop Please can you review this ticket and let us know your opinion on if maker checker is needed for maintaining the list of ISO4217 currencies in the hub?

**Comment by elnyry-sam-k** [comment]
@TW-Ei-Nghon-Phoo can you please post a summary of our discussion and consensus on this - that currencies will be configured part of the deployment (using ISO 4217) list and enabling or disabling essentially is done at account level.

**Comment by JulieG19** [comment]
There is a change of strategy for vNext. All the tickets are being closed.
