### ISSUE TITLE
Producers Singleton Factory instantiates a new Producer on every sendMessage

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#370]
**Issue**:
Producers Singleton Factory instantiates a new Producer on every `sendMessage`. The Singleton Factory should only instantiate the Producer if it has already not been done so. This in turn means that on every `sendMessage` a Producer will have to connect to the Kafka broker which adds an additional 500ms-1second delay on the transport of the message.

**Tasks**:
- [ ] Implement Fix
- [ ] Validate Unit Tests
- [ ] Validate Integration Tests

**Acceptance Criteria**:
- [ ] The Singleton Factory will only instantiate the Producer if it has already not been done so.

**Dependencies**:
- n/a

**Accountability**:
- Owner: @rmothilal 
- QA/Review: @mdebarros

**Comment by mdebarros** [comment]
PRs for ML-API-Adapter: 
- https://github.com/mojaloop/ml-api-adapter/pull/20
- https://github.com/mojaloop/ml-api-adapter/pull/18

PRs for Central-Ledger:
- https://github.com/mojaloop/central-ledger/pull/95
- https://github.com/mojaloop/central-ledger/pull/94

**Comment by mdebarros** [comment]
ML-API-Adapter: 
1. https://github.com/mojaloop/ml-api-adapter/pull/24
2. https://github.com/mojaloop/ml-api-adapter/pull/25 (first review #24)
