### ISSUE TITLE
Security Certificate Management

### ISSUE THREAD

**Issue by ei-nghon-phoo** [mojaloop/project#3717]
## User Story
**As a hub operator**, **I want** to upload and manage JWS certificates for each DFSP **so that** I can ensure the security of the switch and the integrity of trusted transactions among DFSP.

### Technical Design for the certificate management
<img width="981" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk5GQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dfb58e6c90a85094b58211a135010e39d1a3b9af/certificate%20mangement%20technical%20design.png" alt="certificate mangement technical design.png" />

Certificate workflow
-     DFSP will have to generate private key on its own independently outside of the hub.  
-     DFSP/hub operator user will have to upload cert signing request file. (Participant portal/hub admin portal) 
-     Hub operator user will have to approve the request. (Hub admin portal) 
-     Approved certificate will be generated and stored in the DB.  
-     Participants' certificate will be shared across participant network so that certificates can be used for request sender verification. 

### Tasks
- [x] Acceptance Criteria pass
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Code Review
- [ ] QA Passed

**Comment by zinzinnyohlaing-tw** [comment]
https://github.com/mojaloop/cert-management-bc/pull/1 <-- pull request

**Comment by tw-sithumyo** [comment]
hello Ma @TW-Ei-Nghon-Phoo , based on the recent discussion with Ko @myo-min-htet  and Ko @tw-aungthawaye , we will be uploading `.cer` file instead of `.pem` format...
and cert-managment-bc internal service will be responsible for generate `.pem` file instead.

**Comment by tw-sithumyo** [comment]
admin ui and service integration in docker-compose-cross-cutting

https://github.com/mojaloop/platform-shared-tools/pull/52

**Comment by tw-sithumyo** [comment]
According to Pedro suggestion admin-ui should not directly use certificates services (should not be exposed), instead certificates requests should go through the participant-svc.

**Comment by TW-Ei-Nghon-Phoo** [comment]
### history
### Security Management with JWS certificates
In JWS security management, Public and private keys are generated by a certificate authority for DFSP. This signature can be validated by any participant, including the hub and DFSPs involved in the transaction. Successful validation is crucial for a transaction to proceed., and the Public key certificate can be decoded to extract information such as time validity, issuer certificate authority, and the signature creation algorithm.


### Acceptance Criteria:

1. **Certificate Upload:**
   - Hub operators with the assigned privilege should be able to upload public key certificates for each DFSP.
   - Only users with the proper privileges should be able to upload and view certificates.   
   - The uploaded file format must adhere to the expected format (DFSPID-pub.pem); otherwise, an appropriate error message, such as "Invalid file format. Please use the correct format (DFSPID-pub.pem)," should be displayed.

2. **Certificate Information:**
   - The UI should display essential information related to the certificates, including Signature Algorithm, Certificate Authority (Issuer), time validity (Not Before, Not After), and a downloadable link for the certificate file.

3. **Security Management with JWS:**
   - Each participant DFSP should have only one associated public key certificate.
   - If the signature validation fails during a transaction, the transaction should not be successful.
   - If a transaction fails due to signature validation, monitoring personnel should receive a proper error code and message, indicating the reason for the failure.
   - DFSPs must securely hold their private keys, ensuring the confidentiality and integrity of their cryptographic key material.

4. **Certificate Renewal:**
   - Before the expiration of the current certificate, users should be able to upload a new certificate.
   - The UI should reflect the information according to the new certificate after a successful upload.
   - The system should notify relevant parties if the certificate is approaching expiration.
   
<img width="1009" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFBLQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ed33c3ed2aa8dd621300d84eb9eec78f731652e/image.png" alt="image.png" />

### UI Design

[Design File](https://www.figma.com/proto/80cD3AKOglNk3UhCUxbILi/vNext-Portal?page-id=9%3A10&type=design&node-id=7247-5560&viewport=-959%2C-2116%2C0.17&t=i0rjtHNOtPu59kal-1&scaling=scale-down&starting-point-node-id=7247%3A5560&show-proto-sidebar=1&mode=design)

**Comment by TW-Ei-Nghon-Phoo** [comment]
### history
### Security Management with JWS certificates
In JWS security management, Public and private keys are generated by a certificate authority for DFSP. This signature can be validated by any participant, including the hub and DFSPs involved in the transaction. Successful validation is crucial for a transaction to proceed., and the Public key certificate can be decoded to extract information such as time validity, issuer certificate authority, and the signature creation algorithm.


### Acceptance Criteria:

1. **Certificate Upload:**
   - Hub operators with the assigned privilege should be able to upload public key certificates for each DFSP.
   - Only users with the proper privileges should be able to upload and view certificates.   
   - The uploaded file format must adhere to the expected format (DFSPID-pub.pem); otherwise, an appropriate error message, such as "Invalid file format. Please use the correct format (DFSPID-pub.pem)," should be displayed.

2. **Certificate Information:**
   - The UI should display essential information related to the certificates, including Signature Algorithm, Certificate Authority (Issuer), time validity (Not Before, Not After), and a downloadable link for the certificate file.

3. **Security Management with JWS:**
   - Each participant DFSP should have only one associated public key certificate.
   - If the signature validation fails during a transaction, the transaction should not be successful.
   - If a transaction fails due to signature validation, monitoring personnel should receive a proper error code and message, indicating the reason for the failure.
   - DFSPs must securely hold their private keys, ensuring the confidentiality and integrity of their cryptographic key material.

4. **Certificate Renewal:**
   - Before the expiration of the current certificate, users should be able to upload a new certificate.
   - The UI should reflect the information according to the new certificate after a successful upload.
   - The system should notify relevant parties if the certificate is approaching expiration.
   
<img width="1009" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFBLQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ed33c3ed2aa8dd621300d84eb9eec78f731652e/image.png" alt="image.png" />

### UI Design

[Design File](https://www.figma.com/proto/80cD3AKOglNk3UhCUxbILi/vNext-Portal?page-id=9%3A10&type=design&node-id=7247-5560&viewport=-959%2C-2116%2C0.17&t=i0rjtHNOtPu59kal-1&scaling=scale-down&starting-point-node-id=7247%3A5560&show-proto-sidebar=1&mode=design)

**Comment by JulieG19** [comment]
@TW-Ei-Nghon-Phoo , is the team working on this ticket?/Can you please provide updates? Thanks!

**Comment by smthitsaworks** [comment]
@JulieG19 , yes TW team member @tw-sithumyo  is working on this ticket. We divided into five parts under this ticket.
1.1 CSR signing from Key Management SVC
1.2 SecureStorage (mongo, local directory, redis, vault)
1.3 Maker/Checker design confirmation
1.4 integration with participant-bc with key-management-svc
1.5 Admin UI changes

The focal Dev can finish the above two tasks during Sprint 1. The rest tasks will be focused in next Sprints.

**Comment by JulieG19** [comment]
@bushjames, is this the ticket you have concerned about?

**Comment by bushjames** [comment]
@JulieG19 this ticket raised my concerns. This is related to JWS key management and is worthy of a  review by the DA.
