### ISSUE TITLE
Convert the Swagger definition file comments to JSDocs

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#372]
**Goal**:
1. As a develop
I would like to convert the Swagger definition file comments to JSDocs in order for it to be utilised

**Tasks**:
- [ ] Design solution for:
  - [ ] conversion of Swagger comments to required format
- [ ] Add JSDocs

**Acceptance Criteria**:
- [ ] Successfully view JSDocs converted from Swagger

**Dependencies**:
- [ ] 

Note:

**Accountability**:
- Owner @rmothilal  
- QA/Review

**Comment by wdcmb** [comment]
Why would we want to do this - swagger is the documentation?

**Comment by NicoDuvenage** [comment]
I was asked to add this requirement as it was indicated that some automated process would take the consolidated extracted data and do some analysis or dashboard creation with it. If I can recall correctly, it was Rajiv who asked for it.

**Comment by elnyry** [comment]
I think the other argument for that was uniformity - all the current docs are in JSDocs form, so we would like to keep that consistent

**Comment by wdcmb** [comment]
mmm… The API should be defined and documented from the swagger/openAPI definition and that should be a sufficient and single source of truth. Having two places to update should not happen. 

 

That doesn’t mean that we don’t document the code, but similarly that the code documentation isn’t defining the API or even presenting the API. Maybe the latter is what he had in mind, but it is not clear from the story.

**Comment by elnyry-sam-k** [comment]
not needed anymore
