### ISSUE TITLE
3.06.1 Unit tests for database transactions in src/models/participant/facade.js

### ISSUE THREAD

**Issue by shashi165** [mojaloop/project#373]
**Goal**:
As a Developer
I would like to _write unit tests for database transactions in src/models/participant/facade.js _ 
so that the transaction is fully tested and code coverage is 100%

**Tasks**:
- [x] Unit tests
   - [x] unit test for participantEndpoint transaction - [@shashi165]
   - [x] unit test for initial position and limits transaction - [@shashi165]
- [x] Code Coverage tests

**Acceptance Criteria**:
- [x] code coverage 100%

**Dependencies**:
- [x] @rmothilal 

Note:
Follow-up story - #351

**Accountability**:
- Owner @rmothilal  
- QA/Review

**Comment by shashi165** [comment]
Merged the PR https://github.com/mojaloop/central-ledger/pull/103
