### ISSUE TITLE
Build DFSP deployed Payment ALIAS Token adapter

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3733]
## **Goal**:
`As a` Mojaloop Community member intending on using Mojaloop to falicitate G2P or beneficiary payments
`I want to` understand how the MOSIP-MIFOS payement token would redirect payments at DFSPs
`so that` extend my existing integrations to support this new functionality

**Notes:**
The design for this work is outlined [here](https://github.com/mojaloop/ml-mosip-integration/blob/main/Docs/TokenAdapterDetails.png):

This token adapter must be a new servce and new repo.
It is required to implement the Backend SDK as both incoming and outgoing which is defined [here](https://github.com/mojaloop/api-snippets/blob/main/docs/sdk-scheme-adapter-backend-v2_1_0-openapi3-snippets.yaml).
The functionality is similar to the [fx converter template](https://github.com/mojaloop/fx-converter-template) repo, which can be used as a reference, or starting point for this work.

**Acceptance Criteria**:
- [x] Verify that the token adapter repo is create in the mojaloop org as a public repo.
- [ ] Verify that the token adapter implements the Backend SDK API as both incoming and outgoing
- [x] Verify that a new Token Registration End point (**POST** users/{PSUT}/tokens) is create the enable the beneficiary registration portal to register new tokens.
- [x] Verify that all API are passed through unless they are required to be mapped.
   - [x] GET PUT parties/{type}/{ID} (SDK backend API)
      - [x] passthrough for {Type} = MSISDN, EMAIL, ACCOUNT_ID, BUSINESS, DEVICE, IBAN
      - [x] Alias mapping for {Type} = ALIAS
   - [x]  POST PUT /quotes (SDK backend API)
      - [x] passthrough for requestbody.payee.partyInfo.partyIdType = MSISDN, EMAIL, ACCOUNT_ID, BUSINESS, DEVICE, IBAN
      - [x] Alias mapping forrequestbody.payee.partyInfo.partyIdType = ALIAS
   - [x] POST PUT /transfer (SDK backend API)
      - [x] passthrough for requestbody.to.partyIdType = MSISDN, EMAIL, ACCOUNT_ID, BUSINESS, DEVICE, IBAN
      - [x] Alias mapping for requestbody.to.partyIdType = ALIAS
- [ ] Verify that TTK functional test exist that test this functionality

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x]  Create the project  repository in mojaloop organization
- [x] Create a hapi js project and configure it for typescript, linting, deployment, versioning and pre-commit checks.
- [x] Implement the Register Token Functionality ==> Token Registration End point (**POST** /tokens)
    - [x] Implement functionality
    - [x] Write TTK test - According to Vijay, No need for TTK tests. The code unit tests are sufficient. Although  I had already written TTK tests for it.
  
- [x] Implement Map Token in Discovery Functionality. Both Inbound and Outbound requests
    - [x] Implement function
    - [x] Write TTK test
- [x] Implement Map Token in Agreement Functionality Both Inbound and Outbound requests
    - [x] Implement function
    - [x] Write TTK test
- [x] Implement Map Token in Transfers Functionality. Both Inbound and Outbound requests.
    - [x] Implement function
    - [x] Write TTK test

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Repository**.
- https://github.com/mojaloop/payment-token-adapter
## **Pull Requests**:
- https://github.com/mojaloop/payment-token-adapter/pull/1 PR to create TTK tests for register token functional requirement
- https://github.com/mojaloop/payment-token-adapter/pull/2 PR to setup mojaloop circle ci
- https://github.com/mojaloop/payment-token-adapter/pull/6 Get Parties in Discovery - Merged
- https://github.com/mojaloop/payment-token-adapter/pulls - Transfers and Quotes - Awaiting Review

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
