### ISSUE TITLE
[GIT-ACTIONS] Implement package version override in Helm release workflow

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#3738]
## **Goal**:
`As a` Mojaloop maintainer

`I want to` update the Helm release automation workflow 
  
`so that` package versions used in the update process can be overridden/controlled 

**Acceptance Criteria**:
- [ ] Verify that package versions can be overridden in scenarios where the latest version is not to be used in a release
- [ ] Verify that the workflow works as expected

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Research how best the feature can be implemented within the context of the current implementation
- [ ] Implement changes to allow package version control in the git actions workflow

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by oderayi** [comment]
There is a draft PR for this issue [here](https://github.com/mojaloop/helm/pull/602)
