### ISSUE TITLE
Quote refactor to use Kafka - metrics regression

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3739]
## **Goal**:
`As a` mojaloop community member makeing use of the quoting service and interrested in performance
`I want to` understand the performance 
`so that` I can optimise my system for performance

**Acceptance Criteria**:
- [x] Verify that the quoting service include the metrics lib and it is running and configured in the quotes handler

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Fix metrics endpoint for quotes handler

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/quoting-service/pull/323

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
