### ISSUE TITLE
3.03-2 Design the Settlements API (PR and DA review)

### ISSUE THREAD

**Issue by bothadeon** [mojaloop/project#374]
**Goal**:
As a Hub Operator
I would like to acknowledge that a participant FSP has successfully settled their account
so that we can I can allow them to continue transacting; so that I know that we are not liable.

**Tasks**:
- [x] ~Design an API for Settlements (POST) [@bothadeon @vgenev]~
- [x] ~Design acknowledgement from settlement bank (? PUT:: /settlements/{settlementId}/participants [@bothadeon @vgenev] )~
- [x] ~Design for Position update trigger (GET) [@bothadeon @vgenev]~
- [x] ~Swagger API defined [@bothadeon @vgenev]~
  - [x] ~Add filtering based on DFSP~
- [x] ~Generate placeholders using hapi [@bothadeon @vgenev]~
  - [x] Unit tests [@bothadeon @vgenev done in 3.3]
- [x] Minimum code coverage 90%  [@bothadeon @vgenev done in 3.3]
- [x] DA review  [@bothadeon @vgenev @DA ]
- [x] Implement DA review changes [@bothadeon @vgenev] 
- [x] Pull request and create a development  branch for the repo [@bothadeon @vgenev] 
- [x] Add central service shared logging to new repo [@bothadeon] 
- [x] Added Happi pagination plugin to the framework [@bothadeon] 

**Acceptance Criteria**:
- [x] ~A Swagger specification for Settlements API is defined that~
  - [x] ~Fetch a Settlement by an ID~
  - [x] ~Create a Settlement using multiple Settlement windows~
  - [x] ~Query Settlements~
    - [x] ~Filtering based on a DFSP~
    - [x] ~Based on Settlement window ID~
    - [x] ~Time period~
   - [x] ~position update to be triggered, based on a Settlement confirmation is available~
- [x] ~Along with the Swagger API, placeholder code using hapi is generated~
- [x] ~Swagger API includes resource to receive confirmation of Settlement~
- [x] A PR is raised for the changes
- [x] Design/PR is reviewed
- [x] Changes based on PR comments, feedback is incorporated

**Dependencies**:
- [x] #328

**Accountability**:
- Owner: [@bothadeon]
- QA/DA Review: Design Authority

**Comment by bothadeon** [comment]
Swagger definition file for this story : 
-------------------------------------
https://github.com/mojaloop/central-settlement/blob/newApiDoc/config/swagger.json

Mind Notes /specs
------------------
[OneNote.Onlinev2.pdf](https://github.com/mojaloop/project/files/2213651/OneNote.Onlinev2.pdf)

The Swagger definition file has to be passed by the DA , preferably with Warren attending.

**Comment by bothadeon** [comment]
This stpry is an overflow from story #328 - sprint 3-2

**Comment by bothadeon** [comment]
Pull request : New central settlement #10
Latest swagger definition file (Includes DA review changes ):
[swagger.json.zip](https://github.com/mojaloop/project/files/2240646/swagger.json.zip)
Latest design notes from the DA's review 
[WarrenOneNotes.pdf](https://github.com/mojaloop/project/files/2240649/WarrenOneNotes.pdf)

**Comment by elnyry** [comment]
Updated estimate based on Deon's input - "The changes resulted in a new API design , had to lose almost everything of the previous design , quite a few more endpoints were added resulting in more unit tests to be created; Went from 55 to 94"

**Comment by bothadeon** [comment]
Added the changes as per DA review and changes as per reviewer pull request.
