### ISSUE TITLE
Update k8s monitoring dashboard to provide standard filtering and monitoring options

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#3741]
## **Goal**:
`As a` Hub Operations user

`I want to` have access to standard monitoring dashboards
  
`so that` take advantage of the filtering options provided by default on nodes and namespaces.

**Acceptance Criteria**:
- [x] namespace based filtering is provided 
- [x] fixes for pod resource utilization are done
- [x] chart for PVC utilization is published

**Complexity**: medium (need to figure out why pod related queries are not working)

**Uncertainty**:Low (fixing the query fixes the dashboard)

---

**Tasks**:
- [x] debug why pod related queries are not working
- [x] add namespace based filter
- [x] add PVC utilisation chart  

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/597

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @muzammil360 
- QA/Review: @dfry
