### ISSUE TITLE
Codeowners added for Baobab target repositories

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#3742]
## **Goal**:
`As a` community contributor

`I want to` ensure that there are codeowners associated with vnext tagged repositiroes
  
`so that` there are contributors and SMEs assigned as PR reviewers for contributions.

**Acceptance Criteria**:
- [ ] All vnext tagged repos have codeowners reviewed and updated

**Complexity**: Low

**Uncertainty**: Low

**Repo list**:

S No | Repo
-- | --
1 | [mojaloop/platform-shared-tools](https://github.com/mojaloop/platform-shared-tools)
2 | [mojaloop/settlements-bc](https://github.com/mojaloop/settlements-bc)
3 | [mojaloop/security-bc](https://github.com/mojaloop/security-bc)
4 | [mojaloop/thirdparty-api-bc](https://github.com/mojaloop/thirdparty-api-bc)
5 | [mojaloop/platform-configuration-bc](https://github.com/mojaloop/platform-configuration-bc)
6 | [mojaloop/participants-bc](https://github.com/mojaloop/participants-bc)
7 | [mojaloop/auditing-bc](https://github.com/mojaloop/auditing-bc)
8 | [mojaloop/foreign-exchange-bc](https://github.com/mojaloop/foreign-exchange-bc)
9 | [mojaloop/transfers-bc](https://github.com/mojaloop/transfers-bc)
10 | [mojaloop/platform-shared-lib](https://github.com/mojaloop/platform-shared-lib)
11 | [mojaloop/logging-bc](https://github.com/mojaloop/logging-bc)
12 | [mojaloop/interop-apis-bc](https://github.com/mojaloop/interop-apis-bc)
13 | [mojaloop/reporting-bc](https://github.com/mojaloop/reporting-bc)
14 | [mojaloop/scheduling-bc](https://github.com/mojaloop/scheduling-bc)
15 | [mojaloop/accounts-and-balances-bc](https://github.com/mojaloop/accounts-and-balances-bc)
16 | [mojaloop/typescript-bc-template](https://github.com/mojaloop/typescript-bc-template)
17 | [mojaloop/quoting-bc](https://github.com/mojaloop/quoting-bc)
18 | [mojaloop/account-lookup-bc](https://github.com/mojaloop/account-lookup-bc)

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by TW-Ei-Nghon-Phoo** [comment]
Additional Code Owners: We would like to propose the addition of the following individuals as code owners to th project due to their significant experience and in-depth knowledge of the code base:
   - tw-aungthawaye
   - myo-min-htet
   - ZweHMyat
   - SithuKyaw-Thitsaworks
 Sam's reply: Adding contributors who have expertise in the area is fine (along with adding James's ID (bushjames) and mine (elnyry-sam-k) ).
<img width="929" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXd2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e4578ef920b2b28af734ffbc73742b5385fcf37/image.png" alt="image.png" />
<img width="930" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTh2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--999064d3a6ce802a5c21521f156dc4e0608c163d/image.png" alt="image.png" />

**Comment by SithuKyaw-Thitsaworks** [comment]
Hi Sam @elnyry-sam-k, I just created a bunch of PRs for this ticket. Also committed your suggestions. Please review.

https://github.com/mojaloop/platform-shared-tools/pull/56
https://github.com/mojaloop/security-bc/pull/9
https://github.com/mojaloop/settlements-bc/pull/30
https://github.com/mojaloop/platform-configuration-bc/pull/4
https://github.com/mojaloop/participants-bc/pull/27
https://github.com/mojaloop/auditing-bc/pull/9
https://github.com/mojaloop/transfers-bc/pull/9
https://github.com/mojaloop/platform-shared-lib/pull/20
https://github.com/mojaloop/logging-bc/pull/14
https://github.com/mojaloop/interop-apis-bc/pull/18
https://github.com/mojaloop/scheduling-bc/pull/11
https://github.com/mojaloop/accounts-and-balances-bc/pull/12
https://github.com/mojaloop/quoting-bc/pull/12
https://github.com/mojaloop/account-lookup-bc/pull/17

**Comment by elnyry-sam-k** [comment]
Thanks @SithuKyaw-Thitsaworks , all PRs reviewed and approved.

**Comment by SithuKyaw-Thitsaworks** [comment]
Thanks @elnyry-sam-k.
