### ISSUE TITLE
Improve SDK K6 tests with simulators replicas

### ISSUE THREAD

**Issue by aaronreynoza** [mojaloop/project#3747]
## **Goal**:
`As a` Mojaloop Developer

`I want to` Change the infraestructure on how the SDK performs calls
  
`so that` The performance on the SDK can be isolated without the sim being a drawback

**Acceptance Criteria**:

We'll need to swap from the current architecture:
![image](https://github.com/mojaloop/project/assets/24705637/2602d6de-a53c-47ad-8be4-11956262e7a5)

to a new replica based one:
![image](https://github.com/mojaloop/project/assets/24705637/fceca30c-273f-4233-aaf5-5f1d4de837e9)

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] setup performance VM
- [x] Test Inbound Requests
- [x] Test Outbound Requests
- [x] Compile/merge latest SDK version with fixes
- [x]  Document SDK/k6-harness process

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [x] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
