### ISSUE TITLE
Mojaloop Helm release v16.0.0

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#3748]
## **Goal**:
`As a` ML OSS adopter

`I want to` have a Mojaloop release v16.0.0 (version to be confirmed as part of the story) that is successfully validated by the Golden path tests
  
`so that` I can adopt and use a version of Mojaloop Switch services bundle that is tested and contains the latest features enhancements and bug fixes added in PI-22, 23 (includes Batching and other performance enhancements)

**Acceptance Criteria**:
- [x] Update "APP VERSION" for each chart.yaml
- [x] Helm RC Release is validated on Moja2 to achieve 100% result with TTK GoldenPath 
- [x] Helm RC Release is validated with PISP provisioning and test collection (TTK) with 100%
- [x] Helm RC Release is validated with Bulk test collection (TTK) with 100%
- [x] QA (Golden path) on deployments done on AWS Moja2 environment is done
- [x] Bugs are logged based on observations, failures
- [x] Bugs logged are fixed if critical to make subsequent releases in individual services (or Helm)
- [x] All the changes needed for supporting the Helm Release are done
- [x] Helm chart is published
- [x] Release notes are published
- [x] Test cases are published (TTK)
- [x] TTK tests run successfully as Post-Hook jobs and Tests

**Notes**:
- 

**Complexity**: Medium - Involves all core and supporting services
**Uncertainty**: Medium

**Tasks**:
- [x] Deploy, validate RC on AWS Moja2 
- [x] Identify issues with QA Scripts if any - fix them and retest 
- [x] QA for bugs, regressions, log them 
- [x] Fix bugs logged if critical 
- [x] Validate with TTK GP collection 
- [x] TTK test-cases repo Release is published 
- [x] Release notes for helm RC is drafted
  - [x] Guidance for migration from Release (may have to be a separate story if sufficiently big / complex)
- [x] Update release notes with Upgrade Strategy Guide link
- [x] Helm Release is published 
- [x] Deployment of released Helm on **Moja2** 
  - [x] Helm release is deployed on **Moja2** successfully
  - [x] Regression testing on Moja2 using TTK collections 
    - [x] GP collection
    - [x] Core Bulk collection
    - [x] Third-party collection
    - [x] SDK Bulk collection
    - [x] SDK R2P collection
  - [x] Validation using CGS Golden path regression tests etc on Moja2 
  - [x] Test upgradability from previous release
- [x] Deployment of released Helm on **Moja1** 
  - [x] Helm release is deployed on **Moja1** successfully
  - [x] Validation using Golden path regression tests etc on Moja1 
    - [x] GP collection
    - [x] Core Bulk collection
    - [x] Third-party collection
    - [x] SDK Bulk collection
  - [x] Validation using CGS Golden path regression tests etc on Moja1 
  - [x] Validate daily cronJobs on Moja1 for GP and Cleanup scripts 

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] TTK Tests pass
- [x] Code Style & Coverage meets standards
- [x] Release notes are verified

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/599
- [x] https://github.com/mojaloop/oss-core-env/pull/5
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/136

## **Issues**:
- [x] https://github.com/mojaloop/project/issues/3603 @oderayi 
- [x] https://github.com/mojaloop/project/issues/3752 @oderayi 
- [x] https://github.com/mojaloop/project/issues/3759 @kleyow 

## **Follow-up**:

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @oderayi 
- QA/Review: @elnyry-sam-k @vijayg10

**Comment by elnyry-sam-k** [comment]
Thanks @oderayi , we have a successful daily run now. Feel free to close this.
