### ISSUE TITLE
Branch protection rules added to vnext repos

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#3749]
## **Goal**:
`As an` adopter of Mojaloop,

`I want to` ensure security of main branches which are used for Mojaloop's official releases
  
`so that` confident of the codebase adopted and the corresponding images, that they've been results of pull request reviews and follow adopted standards of Mojaloop

**Acceptance Criteria**:
- [x] Branch protection rules are applied to all vnext repos
  - [x] "main" branch needs PR before merging
  - [x] Needs status checks to pass
  - [x] Require review from codeowners

**Complexity**: Low

**Uncertainty**: Low

**Note**:
Refer to the details in the Epic #3743 to ensure acceptance criteria is delivered in accordance.

**Repo list**:

S No | Repo
-- | --
1 | [mojaloop/platform-shared-tools](https://github.com/mojaloop/platform-shared-tools)
2 | [mojaloop/settlements-bc](https://github.com/mojaloop/settlements-bc)
3 | [mojaloop/security-bc](https://github.com/mojaloop/security-bc)
4 | [mojaloop/thirdparty-api-bc](https://github.com/mojaloop/thirdparty-api-bc)
5 | [mojaloop/platform-configuration-bc](https://github.com/mojaloop/platform-configuration-bc)
6 | [mojaloop/participants-bc](https://github.com/mojaloop/participants-bc)
7 | [mojaloop/auditing-bc](https://github.com/mojaloop/auditing-bc)
8 | [mojaloop/foreign-exchange-bc](https://github.com/mojaloop/foreign-exchange-bc)
9 | [mojaloop/transfers-bc](https://github.com/mojaloop/transfers-bc)
10 | [mojaloop/platform-shared-lib](https://github.com/mojaloop/platform-shared-lib)
11 | [mojaloop/logging-bc](https://github.com/mojaloop/logging-bc)
12 | [mojaloop/interop-apis-bc](https://github.com/mojaloop/interop-apis-bc)
13 | [mojaloop/reporting-bc](https://github.com/mojaloop/reporting-bc)
14 | [mojaloop/scheduling-bc](https://github.com/mojaloop/scheduling-bc)
15 | [mojaloop/accounts-and-balances-bc](https://github.com/mojaloop/accounts-and-balances-bc)
16 | [mojaloop/typescript-bc-template](https://github.com/mojaloop/typescript-bc-template)
17 | [mojaloop/quoting-bc](https://github.com/mojaloop/quoting-bc)
18 | [mojaloop/account-lookup-bc](https://github.com/mojaloop/account-lookup-bc)
---

**Tasks**:
- [x] Update each repo's branch protection rules / create branch protection rules on "main" branch to only allow merges with PRs, code owners review and with status checks passing

**Done**
- [x] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3749?planning-poker) with Zenhub @bushjames @JaneS321 @SithuKyaw-Thitsaworks @myo-min-htet @zinzinnyohlaing-tw @PaulMakinMojaloop

**Comment by elnyry-sam-k** [comment]
Issue completed, details shared on slack.
