### ISSUE TITLE
2.01-2 Design position management

### ISSUE THREAD

**Issue by bothadeon** [mojaloop/project#375]
**Goal**:
1. As a contributor
I would like to _design the positions management flow for successful and failed scenarios_ 
so that FSP positions can be managed by the Switch.
2. As a Hub Operator
I want to make sure that _no FSP exceeds their net Debit CAP_
I want to make sure that _the Positions Management facilitates Settlement process that follows_
3. As a DFSP
_I'm not allowed to transact more than the funds I'm allocated to the Mojaloop Switch_

**Tasks**:
- [x] ~PoC to validate Design approach [@vgenev @bothadeon @shashi165]~
- [x] ~Create Positions PlantUML Diagram for~
  - [x] ~Position Prepare [@ggrg]~
  - [x] ~Position Fulfil [@rmothilal]~
  - [x] ~Position Abort [@rmothilal]~
- [x] ~Create overall Position PlantUML Diagram~
- [x] ~Create svg files for~
  - [x] ~Position Prepare [@ggrg]~
  - [x] ~Position Fulfil [@rmothilal, @ggrg]~
  - [x] ~Position Abort [@rmothilal]~
- [x] ~Create svg files for the overall Positions Diagram~
- [x] Record issues identified (topic for position per currency (per FSP) and others)
- [x] Update the designs to include changes/fixes @elnyry @rmothilal 

**Acceptance Criteria**:
- [x] ~Deterministically recreate position changes against timelines~
- [x] ~Position process captures all the state changes~
- [x] ~This design needs to include the time-outs~
- [x] Updated designs to be reviewed by DA @elnyry @rmothilal @wdcmb 
  - [x] Updated Position Prepare PlantUML Diagram is reviewed
  - [x] Updated Position Fulfil PlantUML Diagram is reviewed
  - [x] Updated Position Abort PlantUML Diagram is reviewed

**Dependencies**:
- [x] Clarity from PO about Settlements/Fulfils updating positions @wdcmb 
- [x] ~DA~

**Accountability**:
- Owner @rmothilal  
- QA/Review Design Authority

**Comment by bothadeon** [comment]
This story is the continuation of story #317 2.01

**Comment by elnyry** [comment]
Accounting for the time spent by DA members for review, changes recommended and changes made, increasing estimate to reflect reality :-)

**Comment by elnyry** [comment]
PR: https://github.com/mojaloop/docs/pull/38

**Comment by elnyry** [comment]
Finally closed after meeting with Georgi to make the remaining changes..
