### ISSUE TITLE
[Helm Release] v16.0.0 RC Test Failures

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#3752]
**Summary**:
TTK GP tests are failing in v16.0.0.

**Severity**: Medium
**Priority**: Medium

**Expected Behavior**
All tests in GP collection should pass.

**Steps to Reproduce**
  1. Deploy v16.0.0-snapshot version of Helm to Kubernetes
  2. Run Helm test
  3. GP tests should fail

**Tasks**

_GP failing tests (intermitent)_:
- [x] Active and inactive participant (1)
- [x] Active and inactive participant account (1)
- [ ] [new sims] transfers, positions CGS Window1 tests (OTC-649, OTC-645) (5)
- [ ] [new sims] new transfers window1 (1)
- [ ] [new sims] new transfers window2 (1)
- [ ] [new sims] new transfers window5 (1)
- [ ] Create Settlement for previously closed 5 windows (4)

_Thirdparty failing tests (11)_
- [ ] ACCOUNT LINKING - HAPPY PATH OTP
- [ ] THIRD PARTY TRANSACTION REQUEST - HAPPY PATH

**Specifications**
  - Component (if known):
  - Version: v16.0.0-snapshot
  - Platform: K8s
  - Subsystem: 
  - Type of testing: Helm test
  - Bug found/raised by: @oderayi 

**Notes**:

- Severity when opened: Medium
- Priority when opened: Medium

**Comment by oderayi** [comment]
Outstanding bug tasks have been traced to ALS v15.1.0 to v15.2.1. Downgrading to ALS v15.0.0 fixes all the outstanding issue.

The underlying ALS bug is now being tracked [here](https://github.com/mojaloop/project/issues/3759)
