### ISSUE TITLE
2.8-2 Implement business logic for calculation of positions for Fulfils

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#376]
**Goal**:
As a Switch
I would like to _Implement business logic for calculation of positions for Fulfils_
so that the capacity of FSPs to make transactions is maximized while not exceeding the Net Debit Cap and minimizing cost to the Switch by reducing the number of bank transactions

**Tasks**:
- [x] Implement business logic for calculation of positions for Fulfils in **PositionHandler** [@ggrg]
  - [x] src/domain/transfer/projection.js to transaction (fulfil & reject) [@ggrg]
- [x] Unit Tests [@ggrg]
- [x] Add Integration Tests [@ggrg]
- [x] Improving Tests Coverage
  - [x] all seeds/ [@ggrg]
  - [x] src/domain/participant/index.js [@shashi165, @ggrg]
  - [x] src/domain/position/positionCalculator.js [@ggrg]
  - [x] src/handlers/lib/utility.js [@shashi165]
  - [x] src/handlers/positions/handler.js [@shashi165]
  - [x] src/handlers/transfers/handler.js [@shashi165]
  - [x] src/lib/time.js [@ggrg]
  - [x] src/models/participant/participantPositionChange.js [@shashi165]

**Acceptance Criteria**:
- [x] Business logic for calculation of positions for Fulfils is implemented
- [x] Integration test for Transfer Fulfil use-case resulting in a "commit" state
- [x] Integration test for Transfer Fulfil use-case resulting in a "reject" state

**Dependencies**:
- #308 

**Note**:
List of Use Cases
- successful Fulfils (Payee position is reduced)
- rejected Fulfils (Payer Position is reduced)

**Accountability**:
- Owner @rmothilal
- QA/Review

**Comment by elnyry** [comment]
@ggrg please confirm if this is the PR: https://github.com/mojaloop/central-ledger/pull/96 and then close it if relevant
