### ISSUE TITLE
Mojaloop Helm Chart - Using K8S secret for JWS private keys

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3760]
## **Goal**:
`As a` Mojaloop Community member
`I want to` use K8S secret to store JWS private key in mojaloop helm chart
`so that` I can avoid exposing the key in k8s deployment manifest.

**Acceptance Criteria**:
- [x] Verify all mojaloop services in mojaloop helm chart use K8S secret to mount the JWS private key
- [x] Verify that Golden path, bulk and third party tests pass
- [ ] Verify that the changes are merged to master and a snapshot version is released

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Add K8s secret config option for JWS signing keys where applicable
  - [x] account-lookup-service chart
  - [x] bulk-api-adapter chart 
  - [x] ml-api-adapter chart 
  - [x] mojaloop-bulk chart
  - [x] quoting-service chart 
  - [x] sdk-scheme-adapter chart 
  - [x] thirdparty chart
  - [x] mojaloop-simulator chart 
  - [x] mojaloop chart -  __In progress__
- [x] Test changes in dev environment

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] https://github.com/mojaloop/helm/pull/600

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @dfry
