### ISSUE TITLE
In Memory Cache Issue

### ISSUE THREAD

**Issue by TW-Ei-Nghon-Phoo** [mojaloop/project#3761]
### Background Information
The infra team encountered a challenge when attempting to horizontally scale up the infrastructure specifications in dev environment. This difficulty arose due to issues with the in-memory cache. When multiple server instances are utilized, the data for transactions cannot be processed effectively and accurately across these servers because the data across multiple in-memory caches is not synchronized. 

### Experimenting Solution
As a solution, we are considering using a Redis database instead of the in-memory cache. This approach will initially be applied in a participant BC and the results will be tested before implementing it in other bounded contexts.
### Tasks
- [x] To experiment with Redit database. 
- [ ] To preform load testing
- [ ] To communicate results with the DA and if the results are improved, to implement in core code. 
- [ ] Acceptance Criteria pass
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Code Review
- [ ] QA Passed

**Comment by elnyry-sam-k** [comment]
Thanks for this issue @TW-Ei-Nghon-Phoo . Would you be able to propose this for discussion at the DA meeting?

**Comment by TW-Ei-Nghon-Phoo** [comment]
Hi @elnyry-sam-k, currently the issue is being investigated to get more in-depth information. It's still in the backlog stage. We will inform you and the DA after we get enough information for it.

**Comment by TW-Ei-Nghon-Phoo** [comment]
Message from Ko Si Thu Kyaw (context)

> we tried to implement horizontal scaling and auto-scaling on our Kubernetes deployment during load tests when a service instance is getting high loads. However, it seems like horizontal scaling isn't functioning properly. Upon investigating the code, we suspect that in-memory caching might be the issue hindering horizontal scaling. Therefore, I am conducting an experiment by adding an option to use a shared cache like Redis. Afterward, I will retest to determine if we achieve better performance in the load test and if auto-scaling functions correctly.

**Comment by bushjames** [comment]
Hi all watchers, I will bring this up at the DA at next available opportunity. I believe there is a solution but it requires some delicate analysis of the code. I am not 100% certain that redis consistency guarantees are sufficient for this use case.

**Comment by pedrosousabarreto** [comment]
Everyone: the build-in ledger was not designed to scale out, only to scale up. For higher loads the recommendation is always to use the TigerBeetle ledger implementation.

**Comment by bushjames** [comment]
Many thanks for your comment @pedrosousabarreto . Lets discuss possibility of refocusing efforts on completing the tigerbeetle integration to handle scale-out scenarios.

**Comment by JulieG19** [comment]
Hi Team, I am unclear on the status of this ticket.
1. What has been done?
2. What is left to be done?
3. Do we still even this ticket based on James comment?


I am moving this to block for now so that we can discuss this during sprint planning.

**Comment by SithuKyaw-Thitsaworks** [comment]
I'm closing this ticket since it was created to investigate a performance issue during load testing. We suspected that in-memory caching was the root of the problem, but it wasn't.
