### ISSUE TITLE
Build the Beneficiary Registration Portal

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3765]
## **Goal**:
`As a` Beneficiary Management system user
`I want to` be able to create and register an Alias Payment Token
`so that` this token can be used to make future beneficiary payments.

**Notes:**
This story is to implement the beneficiary management component as described in the MOSIP-Mojaloop POC [here](https://github.com/mojaloop/ml-mosip-integration/tree/main).
The Beneficiary registration portal is:
- A MOSIP registered partner
- A Mojaloop Participant

**Acceptance Criteria**:
- [ ] Verify that the beneficiary management system should define the KYC matching criteria for the token.
- [ ] Verify that the beneficiary registration portal implements the (OIDC) open id connect redirect login flow.
- [ ] Verify that the beneficiary management system can call the login redirect and is returned the payment token that was registerd for that user and the user's name.
- [ ] Verify that the beneficiary registration portal calls the MOSIP+eSignet sandbox's OIDC login redirect to validate and obtain the MOSIP PSUT (Partner specific user token.)
- [ ] Verify that the beneficiary registration portal has a UI that enables the user to select a Mojaloop Payment Token. Only a limited set of payment tokens are supported by a scheme, so this can be defined through configuration.
- [ ] Verify that the beneficiary registration portal calls the Mojaloop get Parties (discovery) to validate the chosen Mojaloop Payment Token
- [ ] Verify that the MOSIP Kyc information and the Mojaloop get Parties KYC information is compared and validated based on beneficiary management system criteria
- [ ] Verify that the beneficiary registration portal Generates a token 
- [ ] Verify that generated tokens are stored using PSUT as the key for the token.
- [ ] Verify that the beneficiary registration portal registers a generated token with both Mojaloop and the configured [Payment Token Adpaters](https://github.com/mojaloop/payment-token-adapter) for each Participant. (Each mojaloop DFSPid  should map to a URL location where the token registration endpoint is mapped.
- [ ] Verify that a docker compose exists for deploying the beneficiary registration portal

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
2 pts left
