### ISSUE TITLE
Add mojaloop-performance-troubleshooting dashboard

### ISSUE THREAD

**Issue by muzammil360** [mojaloop/project#3768]
## **Goal**:
`As a` developer

`I want to` review performance of mojaloop services 
  
`so that` I can readily understand and debug performance problems with mojaloop services. 

**Acceptance Criteria**:
- [x] cpu utilization 
- [x] ram utilization
- [x] disk utilization
- [x] node list

**Complexity**: Medium | We need to write custom PromQL queries. 

**Uncertainty**: Low | Metrics exists. We just need to update the dashboard.

---

**Tasks**:
- [x] add panels to dashboard
- [x] reference dashboard as custom grafana dashboard resource

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/601

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
