### ISSUE TITLE
Producers Singleton Factory instantiates a new Producer on every sendMessage - Part 2

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#377]
**Bug**:
Producers Singleton Factory instantiates a new Producer on every `sendMessage`. The Singleton Factory should only instantiate the Producer if it has already not been done so. 

**Impact**:
- Impacts both the Ml-API-Adapter and the Central-Ledger.
- This in turn means that on every `sendMessage` a Producer will have to connect to the Kafka broker which adds an additional 500ms-1second delay on the transport of the message.

**Tasks**:
---
- [x] Implement Fix for Central-Ledger
- [x] Validate Unit Tests for Central-Ledger
- [x] Validate Integration Tests for Central-Ledger
- [x] Implement Disconnect fix for Central-Ledger
- [x] Implement fix for Central-Ledger in PI3 code-base
- [x] Implement fix for Ml-API-Adapter in PI3 code-base
---
Central-Ledger Pull Requests:
- [x] https://github.com/mojaloop/central-ledger/pull/99
- [x] https://github.com/mojaloop/central-ledger/pull/98
- [x] https://github.com/mojaloop/central-ledger/pull/101
- [x] https://github.com/mojaloop/central-ledger/pull/100 (for merging disconnect fix)
---
ML-API-Adapter Pull Requests:
- [x] https://github.com/mojaloop/ml-api-adapter/pull/19
- [x] https://github.com/mojaloop/ml-api-adapter/pull/20
- [x] https://github.com/mojaloop/ml-api-adapter/pull/24
- [x] https://github.com/mojaloop/ml-api-adapter/pull/25
---

**Acceptance Criteria**:
- [x] The Singleton Factory will only instantiate the Producer if it has already not been done so  for Central-Ledger

**Dependencies**:
- [x] #370

**Accountability**:
- Owner: @rmothilal @mdebarros
- QA/Review: @mdebarros @rmothilal

**Comment by mdebarros** [comment]
Central-Ledger:
1. https://github.com/mojaloop/central-ledger/pull/99
2. https://github.com/mojaloop/central-ledger/pull/98 (first review #99)
3. https://github.com/mojaloop/central-ledger/pull/100 (for merging disconnect fix)
