### ISSUE TITLE
Development of a Mifos Core Connector for Mojaloop Payment Manager 

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3772]
## **Goal**:
`As an` FSP with Fineract\MIFOS Core Banking
`I want to` be able to use the "PM4ML/SDK Core Connector" 
`so that` I can transact on Mojaloop effectively

**Acceptance Criteria**:
- [ ] Verify that an API is available for the registration portal to call to register a token.
- [ ] Verify that the following integrations are built to provide access to the MIFOS savings accounts that follow this design
   - [ ] Payee Get Parties
      - verify token, client and account, and return user name
   - [ ] Payee POST quotes
      - verify token, client and account, and perform checks
   - [ ] Payee POST transfer
     - return reserved state
   Payee PATCH transfer - This is currently not supported in the scheme adapter.
     - commit the payment
- [ ] Verify that functional TTK tests validate the above functionality
- [ ] Verify that the core connector is deployable alongside PM4ML with supportive documentation 

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Create mifos core connector repository in Mojaloop Github Org
- [x] Setup project and push initial commit containing project structure, circle-ci, test folders, pre-commit config, and node project setup.
- [x] Build Payee GET Parties integration with Fineract
    - [x] Implement function 
    - [x] Write Functional Test using jest
    - [x] Implement TTK Test
 - [x] Build Payee POST quotes  integration with Fineract
    - [x] Implement function 
    - [x] Write Functional Test using jest
    - [x] Implement TTK Test 
  - [x] Build Payee POST transfers  integration with Fineract
    - [x] Implement function 
    - [x] Write Functional Test using jest
    - [x] Implement TTK Test 
   - [x] Creating a blog about Developing a Core Connector for Mifos X. 
   - [x] Code quality improvements
     - [x] Environment Variable Injection
     - [x] Logging plugin 
     - [x] Api request schema validation 
   
**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
