### ISSUE TITLE
2.03-2 Implement database schema changes for Position Management

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#378]
**Goal**:
As a developer
I would like to _Implement database schema changes for positions_
so that the Data Model is aligned to the design.

**Tasks**:
- [x] ~Implement design of participantPosition table [@ggrg]~
- [x] ~Implement design of participantLimit table [@ggrg]~
- [x] ~Implement design of transferState seeds [@ggrg]~
- [x] ~Create DAO for participantPosition, participantLimit [@rmothilal]~
- [x] ~Implement Position Management model for the initial insert of position limit & record creation of the Participant position~
- [ ] Unit tests
- [ ] Integration tests
- [ ] JSDocs
- [ ] Code coverage

**Acceptance Criteria**:
- [x] ~All tables must be aligned to the design approved by the DA~
- [x] ~Migration scripts generate the participantLimit and participantPosition as per design~
- [x] ~Migration scripts insert transferState seeds as per design~
- [x] ~Data access objects for participantPosition, participantLimit to allow for CRUD operations~
- [ ] Position Management model to orchestrate the initial creation of participantLimit and participantPosition

**Dependencies**:
- [x] #342 

**Accountability**:
- Owner @rmothilal  
- QA/Review

**Comment by elnyry** [comment]
Pending tasks tracked in story #385
