### ISSUE TITLE
Incorporate FX POC into IaC deployment

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3784]
## **Goal**:
`As a` Mojaloop Community member interested in making use of the Mojaloop FX support
`I want to` deploy the Mojaloop FX poc
`so that` I can validate the the Fx flows support my use case

**Note:**
This story excludes the JWS signing and validation for Payer/Payee/FXP Payment Manager. This functionality will be added as a seperate story to follow shortly.

**Acceptance Criteria**:
- [ ] Verify that the IaC is extended to support the FX on an IaC feature branch
    - [ ] Mojaloop Gateway configured with new FX endpoints
    - [ ] Payment Manager Gateway configured with new FX endpoints
    - [ ] New FXP Payment manager deployed
    - [ ] Update Payment TTK rule to support FX mock responses to mock FXP and Payee backend functionality
       - [ ] for Payee (supported currencies)
       - [ ] for FXP 
 - [ ] Verify that we have an automated happy path test validating the functionallity added.

Here is a link a FXP helm values deployment file.
https://github.com/infitx-org/test-mojaloop-deployment-fx/blob/main/values-mojaloop.yaml

TTK Test cases without assertions can be found in this repo.
https://github.com/infitx-org/test-mojaloop-deployment-fx/

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Pull the upstream changes of central ledger and release snapshot [@vijayg10 ]
- [x] Pull the upstream changes of sdk and release snapshot [@geka-evk ]
- [x] Test FX functionality with latest helm deployment and with latest snapshots [@vijayg10 ]
- [x] Prepare initial draft PR on IaC modules repo for FX integration [ @vijayg10  ]
- [x] Release a snapshot of IaC modules with FX support and deploy it in a new environment [ @vijayg10  ]
- [x] Test FX functionality [@vijayg10 ]
  - [x] Fix jws signing for FX quotes and transfers [@vijayg10 ]
- [x] Test P2P functionality [@vijayg10 ]
- [x] Discuss about the demo [@vijayg10 ]
- [x] Develop a mobile simulator for FX transfer [@vijayg10 ] [#3827](https://github.com/mojaloop/project/issues/3827)
- [x] Create a story for standardising the IaC modules including reference links to the feature branches

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/infitx-org/test-mojaloop-deployment-fx/pull/1
- [ ] https://github.com/mojaloop/iac-modules/pull/183 (WIP)
- [x] https://github.com/mojaloop/sdk-standard-components/pull/200

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3784?planning-poker) with Zenhub @aaronreynoza @kleyow @sri-miriyala @vijayg10 @geka-evk
