### ISSUE TITLE
Update Technical Documentation For vNext

### ISSUE THREAD

**Issue by TW-Ei-Nghon-Phoo** [mojaloop/project#3786]
As a Mojaloop adopter,

I want to update the vnext repositories with the standard readme document

so that fundamental information such as what the service does, how to run the service, tests, C/CD steps and related details can be easily found.

The readme page to include the following sections at the least:
-  [x] Basic description of the BC / repository
-  [x] Testing, coverage details, how to run
-  [x] CI/CD (Continuous Integration/Continuous Deployment) process for the BC
-  [x] Known issues if any
-  [x] Environment variables to be set / configured

**Comment by JulieG19** [comment]
Hello @bushjames and @TW-Ei-Nghon-Phoo can I understand why this has been put at the top of the backlog?

**Comment by JulieG19** [comment]
This ticket should be done already - meeting to be organised between Sam and Sue
