### ISSUE TITLE
Enable CI Pipeline for Central-Settlement services to support Automated Unit Tests

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#379]
**Goal**:
As a Developer
I would like to _Automate the Continuous Integration Pipeline in CircleCI_
so that automated Unit testing for PR & pre-CD checks.

**Tasks**:
- [x] Configure CircleCI for the Central-Settlement service [@mdebarros]
- [x] Added the CircleCI Script to Central-Settlement service for CI (to support Unit Tests at this time) [@vgenev, @elnyry]
- [x] Configure GitHub project for the Central-Settlement service for Unit Test checks [@vgenev]
- [x] Configure GitHub project for the Central-Settlement service for Peer Review checks from the Development Team [@vgenev]
- [x] Verify Unit Test Pipeline in CircleCI [@elnyry]

**Acceptance Criteria**:
- [x] Continuous Integration to be executed by CircleCI on PRs (and support for Future CDs)
- [x] Continuous Integration pipeline to execute Unit Test job

**Dependencies**:
- [x] #374

**Accountability**:
- Owner @bothadeon @vgenev 
- QA/Review @mdebarros

**Comment by elnyry** [comment]
Initial PR to develop: https://github.com/mojaloop/central-settlement/pull/2

PR to master: https://github.com/mojaloop/central-settlement/pull/3

**Comment by vgenev** [comment]
closed with this PR https://github.com/mojaloop/central-settlement/pull/9
