### ISSUE TITLE
Enable CI Pipeline for Central-Settlement services to support Automated Integration Tests

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#380]
**Goal**:
As a maintainer of the Mojaloop codebase
I would like the _running of Integration tests be automated in the CircleCI pipeline_
so that automated Integration testing for can be done for PR & pre-CD checks.

**Tasks**:
- [ ] Add the CircleCI Script to Central-Settlement service for CI (to support Integration Tests at this time)
- [ ] Configure GitHub project for the Central-Settlement service for Integration Test checks
- [ ] Verify Integration Test Pipeline in CircleCI

**Acceptance Criteria**:
- [ ] Continuous Integration to be executed by CircleCI on PRs (and support for Future CDs)
- [ ] Continuous Integration pipeline to execute Integration Test job

**Dependencies**:
- [ ] #379

**Accountability**:
- Owner  @bothadeon @vgenev
- QA/Review @mdebarros

**Comment by elnyry** [comment]
Now done in #635
