### ISSUE TITLE
Improve kubernetes dashboard labeling

### ISSUE THREAD

**Issue by muzammil360** [mojaloop/project#3806]
## **Goal**:
`As a` developer

`I want to` see container names in k8s monitoring dashboard
  
`so that` I can easily identity containers and pods

**Acceptance Criteria**:
- [ ] dashboard json updated in git

**Complexity**: Low 

**Uncertainty**: Low

---

**Tasks**:
- [x] show pod cpu and memory utilisation based on `pod/container-name`
- [x] remove container network panel 
- [x] stop auto refresh and put the chart to 5 mins 
- [x] remove all process CPU, memory and network 
- [x] apply namespace label to networking I/O pressure 
- [x] allow pvc util to be collapsed 
 

- **Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/610

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @muzammil360 
- QA/Review: TBC
