### ISSUE TITLE
Upgrade kafka dashboard

### ISSUE THREAD

**Issue by muzammil360** [mojaloop/project#3808]
## **Goal**:
`As a` developer

`I want to` I want to have better regarding how kafka topics are behaving
  
`so` So I need a dashboard which provides the following information 

**Acceptance Criteria**:
- [x] Topic wise kafka lag
- [x] Topic wise storage used
- [x] Topic wise messages per sec
- [x] Number of partitions for topics

**Complexity**: <Low> 

**Uncertainty**: <Low> > 
---

**Tasks**:
- [x] update dashboard

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/613

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
