### ISSUE TITLE
Enable CD Pipeline for Central-Settlement services to support Automated Deployments

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#381]
**Goal**:
As a maintainer of the Mojaloop codebase
I would like the _Deployment of the codebase be automated in the CircleCI Pipeline_
so that the latest code can be deployed as required.

**Tasks**:
- [x] Create Helm Chart for Central-Settlement
- [x] Test Helm Chart for Central-Settlement from local code
- [x] Build Helm Chart in `gh-pages` branch
- [x] Publish Helm Chart on `gh-pages` branch to the Mojaloop Helm Chart Repo
- [x] Test Helm Chart from the Mojaloop Published Helm Chart repo
- [x] Test new deployment by creating a snapshot release via Github (which will kick-off the CI/CD pipeline on CircleCI) --> This should then execute all tests, coverage, build and deploy job which will then push the code to Kubernetes
- [x] Test existing deployment by creating a snapshot release via Github (which will kick-off the CI/CD pipeline on CircleCI) --> This should then execute all tests, coverage, build and deploy job which will then push the code to Kubernetes

**Acceptance Criteria**:
- [x] Helm Chart for Central-Settlement is available
- [x] Helm Chart for Central-Settlement is published
- [ ] Deployment via CI/CD pipeline is tested

**Dependencies**:
- [x] #379
- [x] #380

**Accountability**:
- Owner  @bothadeon @vgenev
- QA/Review @mdebarros

**Comment by elnyry** [comment]
This is completed, been using the charts to deploy central-settlement as part of the ML Switch deployment for a while now
