### ISSUE TITLE
FX Quotes - update mojaloop helm chart

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3816]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` have a development version of mojaloop helm chart which includes FX Quotes
  
`so that` I can use it for PoC deployments

**Acceptance Criteria**:
- [ ] Configuration for quotes services is updated with FX related config
- [ ] Development version of mojaloop helm chart is published with FX Quotes
- [ ] Backend dependency example helm chart is updated with new topics required

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Update quoting service in helm chart to support FX
- [x] Publish a dev release

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
