### ISSUE TITLE
[Quoting Service] Harden the fx quotes for FX - simple routing mode = true

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3817]
## **Goal**:
`As a` Mojaloop Community member making use of FX conversion in mojaloop
`I want to` ensure that the FX implementation POC is matured 
`so that` it can be merged into master and ultimately included in a release of mojaloop and used.

**Note:** This story covers the harnening of the central services components that are associated with the  fx quotes.
- The POC only catered for simple routing mode. This story needs to include the other routing mode.

**Acceptance Criteria**:
- [ ] Verify that error cases are mapped and documented.
- [ ] Verify that the integration test are added to test the error cases.
- [ ] Verify that unit test are added
- [ ] Verify that all mojaloop core standards are met

**Note:**
The current integration test harness is not great; May need to update with the integration framework that is running in Central Ledger

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] create new tables
- [ ] implement simple routing = false
- [ ] harned simple routing mode
- [ ] add unit tests
- [ ] add integration tests 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3817?planning-poker) with Zenhub @aaronreynoza @kleyow @oderayi @sri-miriyala @vijayg10

**Comment by PaulGregoryBaker** [comment]
Feature completed; and part of Release 17
