### ISSUE TITLE
[CENTRAL_LEDGER] Harden the Central Ledger - prepare flow for FX

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3819]
## **Goal**:
`As a` Mojaloop Community member making use of FX conversion in mojaloop
`I want to` ensure that the FX implementation POC is standardized 
`so that` it can be merged into master and ultimately included in a release of mojaloop and used.

**Note:** This story covers the harnening of the central services components that are associated with the prepare leg a FX  transfer and transfer for FX. 

The followin components need to be addressed in this story.
 - [ ] prepare handler
 - [ ] postion prepare handler
(This excludes timeouts and aborts, as they are captured in another story.)

**Acceptance Criteria**:
- [ ] Verify that error cases are mapped and documented.
- [ ] Verify that the integration test are added to test the error cases.
- [ ] Verify that unit test are added
- [ ] Verify that all mojaloop core standards are met

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---
This hardening pertains to prepare payer initiatied conversion hardening - SEND type transfer.

**Tasks**:
- [x] Add unit tests domain/prepare handler [@kleyow]
- [x] Add in error cases to inform users of unsupported features as payee conversion. [@kleyow]
- [x] Add integration tests domain/prepare handler [@kleyow]
- [x] Refactor position prepare handler logic in batch mode [@vijayg10 ]
- [x] Add integration tests domain/prepare-position handler [@vijayg10 ]
- [x] Add unit tests domain/prepare-position handler [@vijayg10 ]
- [x] Add function test for FX transfer as part of CICD pipeline [@kleyow]
- [x] Evaluate error cases

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/1004
- [x] https://github.com/mojaloop/central-ledger/pull/1005'
- [x] https://github.com/mojaloop/central-ledger/pull/1009
- [x] https://github.com/mojaloop/ml-core-test-harness/pull/54

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
![Binning Design With FX drawio](https://github.com/mojaloop/project/assets/33152110/5e125844-a271-4ae1-ad50-a658b3bf0746)

**Comment by chris-me-law** [comment]
(Planning 1\2 Pt left)
