### ISSUE TITLE
1.4.2 Kafka Performance Issue Analysis & Investigation - Implement auto-commit findings and recommendations as of PI3.2 & PI3.3

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#382]
## **Goal**:
1. As a contributor
I would like to _implement the findings & recommendations from the Kafka Performance Issue Analysis & Investigation_
so that transfers can be performant
2. As a Switch
I would want _the development team to implement Kafka Performance Issue Analysis & Investigation findings & recommendations_
so that transfers can be performant

## **Tasks**:
- [ ] Kafka Performance - Implement Auto-Commit changes for Central-Ledger
- [ ] Kafka Performance - Implement additional validation logic to ensure that no replays or duplicates occur in the Position Handler within the Central-Ledger __(aka ensure that the event is applicable based on the current transfer state)__
- [ ] Verify Unit Tests for Central-Ledger
- [ ] Verify Integration Tests for Central-Ledger
- [ ] Kafka Performance - Implement Auto-Commit changes for Ml-API-Adapter
- [ ] Verify Unit Tests for Ml-API-Adapter
- [ ] Verify Integration Tests for Ml-API-Adapter

## **Acceptance Criteria**:
- [ ] Implemented [Recommendations & Findings as of PI3.2](https://mdebarros.github.io/kafkapoc-results/20180720/#recommendations--findings-as-of-pi32) changes for the enabling/disabling of Auto-commits & Manual-Commits
- [ ] Implemented [Recommendations & Findings as of PI3.2](https://mdebarros.github.io/kafkapoc-results/20180720/#recommendations--findings-as-of-pi32) validation logic to ensure that no replays or duplicates occur in the Position Handler within the Central-Ledger

## **Dependencies**:
- n/a

## **Notes**:
- Based on the following: https://mdebarros.github.io/kafkapoc-results/20180720
- This is a revised story from without the auto-commit changes: https://github.com/mojaloop/project/issues/371

## **Accountability**:
- Owner 
- QA/Review: @mdebarros

**Comment by elnyry** [comment]
Covered in items #371 and #386
