### ISSUE TITLE
[CENTRAL_LEDGER] Harden the Central Ledger-Central Ledger API for FX

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3820]
## **Goal**:
`As a` Mojaloop Community member making use of FX conversion in mojaloop
`I want to` ensure that the FX implementation POC is standardized 
`so that` it can be merged into master and ultimately included in a release of mojaloop and used.

**Note:** This story covers the harnening of the central services components that are associated with central ledger API related a FX  transfer and transfer for FX. 

The followin components need to be addressed in this story.
 - [ ] Central Ledger API

**Acceptance Criteria**:
- [ ] Verify that error cases are mapped and documented.
- [ ] Verify that the integration test are added to test the error cases.
- [ ] Verify that unit test are added
- [ ] Verify that all mojaloop core standards are met
ertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Improve coverage and test suite

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/central-ledger/pull/1000

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
