### ISSUE TITLE
[CENTRAL_LEDGER] Implement the Central Ledger batch-fufil flow for FX position handler

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3821]
## **Goal**:
`As a` Mojaloop Community member making use of FX conversion in mojaloop
`I want to` ensure that the FX implementation POC is standardized 
`so that` it can be merged into master and ultimately included in a release of mojaloop and used.

**Note:** This story was initially implemented in the non-batch as part of a POC. This functionality need to be re-implemented in the performant position batch handler, and then needs to be hardened with full testing so that it can be merged into master. 

The followin components need to be addressed in this story.
 - [ ] batch position commit handler (need to be implemented) (This is similar to the code added to the non-batch position commit handler added in the POC).
(This excludes timeouts and aborts, as they are captured in another story.)

**Acceptance Criteria**:
- [ ] Verify that error cases are mapped and documented.
- [ ] Verify that the integration test are added to test the error cases.
- [ ] Verify that unit test are added
- [ ] Verify that all mojaloop core standards are met

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Migrate position fulfil logic to batch handler [@vijayg10 ]
- [x] Add unit tests [@vijayg10 ]
- [x] Refactor existing fulfil batch handler to support FX [@vijayg10 ]
- [x] Adjust unit tests for the changes [@vijayg10 ]
- [x] Add integration tests
- [x] Make sure functional tests are working [@kleyow]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/1019
- [x] https://github.com/mojaloop/central-ledger/pull/1009
- [x] https://github.com/mojaloop/ml-core-test-harness/pull/54
- [x] https://github.com/mojaloop/central-ledger/pull/1030

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
