### ISSUE TITLE
"platform-shared-tools" repo to use standard CI/CD steps, checks

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#3822]
## **Goal**:
`As an` adopter of Mojaloop

`I want to` ensure that standard CI/CD steps adopted by Mojaloop are followed for the "platform-shared-tools" repo 
  
`so that` I can be confident of the quality of the codebase of this repo

**Acceptance Criteria**:
- [ ] CI/CD steps listed below are configured for the [mojaloop/platform-shared-tools](https://github.com/mojaloop/platform-shared-tools) repo and pass
  - [ ] Integration tests 
  - [ ] Vulnerability checks 
  - [ ] Image scans 
  - [ ] Functional tests 
  - [ ] License scans 
  - [ ] PR title check missing 
  - [ ] Missing automated releases 
  - [ ] Test coverage 90% 

**Note**: In case there are issues with any of the steps (such as failure of a license scan failure), separate issues maybe created based on the scope and nature of the issue to address it.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by JulieG19** [comment]
There is a change of strategy with vNext. I am closing this ticket accordingly to that change.
