### ISSUE TITLE
TTK - Implement Payer Mobile Simulator that works with Mojaloop connector to send a transfer

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3827]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` use TTK to simulate a payer mobile application to send a transfer through mojaloop via mojaloop connector
  
`so that` I can use TTK for various demonstrations

**Acceptance Criteria**:
- [x] Payer mobile simulator is available in TTK release
- [x] TTK can be configured to act as a core backend that speaks to SDK outbound API to send a transfer
- [x] It supports both normal transfers and FX transfers

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/252
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/183

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
