### ISSUE TITLE
Merge generic functionality implemented for PoCs from IaC feature branch to the main branch

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3828]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` standardise the customization did for PoC demos
  
`so that` I can use those features with standard IaC release

**Acceptance Criteria**:
- [ ] All the customisation is merged into main except FX related functionality

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Update TTK and SDK in Pm4ml helm chart
- [x] Merge fixes into iac main branch
  - [x] Fix paths in Istio VS for pm4mls
  - [x] Fix indent for mojaloop tolerations
- [x] Merge pm4ml customisation into iac main branch
  - [x] Add new Istio VS for payment token adapter in pm4ml
  - [x] Change default values for AUTO_ACCEPT
  - [x] `core_connector_selected` instead of `use_ttk_as_backend_simulator` for specifying custom backendpoint in SDK
  - [x] Add `pta_portal_fqdns` variable

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/pm4ml/mojaloop-payment-manager-helm/pull/147
- [x] https://github.com/mojaloop/iac-modules/pull/205

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
