### ISSUE TITLE
2.15.02 Implement participant API to manage multiple Limits (Array of limits)

### ISSUE THREAD

**Issue by shashi165** [mojaloop/project#383]
**Goal**:
As a Switch
I would like to _Implement operations on the Participant API to manage the multiple Participant Limits in a single call_ 
so that multiple Limits of an FSP can be managed following the Rules provided by the API and the Scheme.

**Tasks**:
- [ ] Implement participant API to manage multiple Limits
  - [ ] extend the existing functionality to update multiple limits for a participant
- [ ] Unit tests
- [ ] Integration tests 
- [ ] JSDocs 
- [ ] Code coverage

**Acceptance Criteria**:
- [ ] Participant Management model to orchestrate the management of multiple participantLimit is done

**Dependencies**:
- [ ] #345 

**Accountability**:
- Owner 
- QA/Review @rmothilal
