### ISSUE TITLE
Add offending processes charts to performance-troubleshooting-dashboard 

### ISSUE THREAD

**Issue by muzammil360** [mojaloop/project#3830]
## **Goal**:
`As a` developer

`I want to` observe processes consuming too much node resources
  
`so that` I can look into what is causing this

**Acceptance Criteria**:
- [x] chart showing processes consuming more than 70% of node CPU
- [x] chart showing processes consuming more than 70% of node memory

**Complexity**: <Medium > Need to build custom PromQL queries and setup recording rules

**Uncertainty**: <Low> 

---

**Tasks**:
- [x] enable the process-exporter
- [x] add service monitor for exporter
- [x]  adding `nodename` label to process metrics using relable config in service monitor
- [x] add charts in performance-monitoring-dashboard  

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/616

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
