### ISSUE TITLE
Address dependabot alerts >=moderate on central-ledger

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#3831]
## **Goal**:
`As an` adopter of Mojaloop

`I want to` ensure that all critical and high priority issues raised by dependabot (GitHub security measure) are addressed
  
`so that` I can use Mojaloop services that have no known security issues (>=moderate priority)

**Acceptance Criteria**:
- [ ] All critical and high-priority issues reported by GitHub are addressed on central-ledger repo

**Complexity**: Medium

**Uncertainty**: High

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
fixed
