### ISSUE TITLE
SPIKE - Plan for ISO20022 implementation for P2P R2P and FX in Mojaloop

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3841]
## **Goal**:
`As a` Mojaloop adapter

`I want to` run an ISO20022 implementation of Mojaloop
  
`so that` I can make use of standardised API

**Acceptance Criteria**:
- [ ] Document mapping between FSPIOP and ISO20022 APIs for the following resources
  - [ ] /parties
  - [ ] /quotes
  - [ ] /transfers
  - [ ] /transactionRequest
  - [ ] /fxQuotes
  - [ ] /fxTransfers
  - [ ] /participants
- [ ] Document API headers for ISO20022 (Ex: JWS signature, Authorisation header)
- [ ] Write up the EPIC for the implementation that includes an outline for the stories required

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
