### ISSUE TITLE
IAC - Advanced core connector deployments in payment manager

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3842]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` more flexibility to deploy a core connector as part of payment manager IaC deployment (for example to be able to specify a helm chart for core connector...etc)
  
`so that` I should be able to deploy core connector with backend dependencies

**Acceptance Criteria**:
- [ ] Agreed on level of customisation for core connector deployments and list of possible use cases to be part of this story
- [ ] New helm charts are released if any
- [ ] New IaC modules is released
- [ ] Documentation is provided to deploy core connectors and configuration

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
