### ISSUE TITLE
[CENTRAL_LEDGER] Implement the Central Ledger fufil handler for FX flow 

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3844]
## **Goal**:
`As a` Mojaloop Community member making use of FX conversion in mojaloop
`I want to` ensure that the FX implementation POC is standardized 
`so that` it can be merged into master and ultimately included in a release of mojaloop and used.

**Note:** This story was initially implemented in the POC and  needs to be hardened with full testing so that it can be merged into master. 

The followin components need to be addressed in this story.
 - [ ] fulfil handler: implement the rest of logic, and then needs to be hardened
(This excludes timeouts and aborts, and position fulfil updates, as they are captured in another story.)

**Acceptance Criteria**:
- [ ] Verify that error cases are mapped and documented.
- [ ] Verify that the integration test are added to test the error cases.
- [x] Verify that unit test are added
- [x] Verify that all mojaloop core standards are met

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Add implementation of all corner cases  _[done]_
- [x] Add unit-tests  _[done]_
- [ ] Add integration-tests  _**(in progress)**_

**Done**
- [ ] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-shared/pull/369
- [ ] https://github.com/mojaloop/central-ledger/pull/1006/
- [ ] https://github.com/mojaloop/central-ledger/pull/1011

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3844?planning-poker) with Zenhub @aaronreynoza @geka-evk @kleyow @sri-miriyala @vijayg10

**Comment by PaulGregoryBaker** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3844?planning-poker) with Zenhub @oderayi

**Comment by chris-me-law** [comment]
(Planning 2 pts remaining)
