### ISSUE TITLE
"participants-bc" repo to use standard CI/CD steps, checks

### ISSUE THREAD

**Issue by ei-nghon-phoo** [mojaloop/project#3849]
## **Goal**:
`As an` adopter of Mojaloop

`I want to` ensure that standard CI/CD steps adopted by Mojaloop are followed for [mojaloop/participants-bc](https://github.com/mojaloop/participants-bc)
  
`so that` I can be confident of the quality of the codebase of this repo

**Acceptance Criteria**:
- [ ] CI/CD steps listed below are configured for the security-bc repo and pass
  - [ ] Integration tests 
  - [ ] Vulnerability checks 
  - [ ] Image scans 
  - [ ] Functional tests 
  - [ ] License scans 
  - [ ] PR title check missing 
  - [ ] Missing automated releases 
  - [ ] Test coverage 90% 

**Note**: In case there are issues with any of the steps (such as failure of a license scan failure), separate issues maybe created based on the scope and nature of the issue to address it.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Sample current circleci run for this: https://app.circleci.com/pipelines/github/mojaloop/participants-bc/357/workflows/266b0976-7398-4f5e-a8d8-296bfa350c28 with the steps missing.

**Comment by PaulMakinMojaloop** [comment]
Needs further refinement, based on further understanding (Sam) of the CI/CD pipeline.

**Comment by JulieG19** [comment]
Discussed today with Ei, Sam and Si Thu => Tickets can be taken up this week by Sam as he is working on the next release, nor by Si Thu as he is focussed on another internal project. 

Julie asked for a re-prioritization of the tickets within ThitsaWorks'team as this ticket is a MUST HAVE to declare vNext as a the next release candidate.

**Comment by JulieG19** [comment]
There is a change of strategy with vNext. I am closing this ticket accordingly to that change.
