### ISSUE TITLE
2.03-3 Implement (tests for) database schema changes for Position Management

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#385]
**Goal**:
As a developer
I would like to _Implement (tests for) database schema changes for positions_
so that the Data Model is aligned to the design.

**Tasks**:
- [x] ~Implement design of participantPosition table [@ggrg]~
- [x] ~Implement design of participantLimit table [@ggrg]~
- [x] ~Implement design of transferState seeds [@ggrg]~
- [x] ~Create DAO for participantPosition, participantLimit [@rmothilal]~
- [x] ~Implement Position Management model for the initial insert of position limit & record creation of the Participant position~
- [x] Unit tests (pending test for transactions)
- [ ] ~Integration tests~
- [ ] ~JSDocs~ [Covered in #325 ]
- [x] Code coverage

**Acceptance Criteria**:
- [x] ~All tables must be aligned to the design approved by the DA~
- [x] ~Migration scripts generate the participantLimit and participantPosition as per design~
- [x] ~Migration scripts insert transferState seeds as per design~
- [x] ~Data access objects for participantPosition, participantLimit to allow for CRUD operations~
- [x] Position Management model to orchestrate the initial creation of participantLimit and participantPosition

**Dependencies**:
- [x] #342 
- [x] #378 

**Accountability**:
- Owner @rmothilal  
- QA/Review

**Comment by elnyry** [comment]
same PR as for #384 : mojaloop/central-ledger#116
