### ISSUE TITLE
MIFOS Core Connector - Payer Initiated integration

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3860]
## **Goal**:
`As an` FSP with Fineract\MIFOS Core Banking
`I want to` be able to use the "PM4ML/SDK Core Connector" 
`so that` I can transact on Mojaloop effectively

**Note:**
This story starts with an investigation into the best practise method for triggering payment out of fineract, and then decides how to incorporate that into the integration design.

**Acceptance Criteria**:
- [ ] Verify that the integration design sequence diaram exists, with e.g. API calls showing data mapping and error handeling 
   - [ ] Verify that a decision has been made on whether MIFOS can perform Party Validation
   - [ ] Verify that a decision has been made on whether MIFOS can perform Quote Validation
   - [ ] Verify that Quote Validation exists inside the CC
- [ ] Enhance the CC to implement the decided CC integration design
- [ ] Verify that functional TTK tests validate the above functionality
- [ ] Verify that the core connector is deployable alongside PM4ML with supportive documentation 

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Investigate how payments can be initiated out of Fineract 
- [x] Design a sequence diagram for a payer initiated integration for the Mifos Core Connector.
- [x] Review and discuss Sequence Diagram for approval and perform any necessary edits.
- [x] Update Fineract Client with cash withdraw function
- [x] Create an SDK Client to handle communication with the SDK Scheme Adapter
- [x] Implement integration for POST /transfers
    - [x] Implement functional and unit tests
- [x]  Implement integration for PUT /transfers/{transferId}
    - [x]  Implement tests functional and unit tests  
 - [x] Write functional tests for dfsp server
 - [x] Increase tests coverage for fineract client 
    
**PR review Suggestions and improvements**
- [x] Fix api schemas to be consistent with what api actually returns
- [x] Adding logs to the system
- [x] User camel case every where
- [x] Refactor to remove repetition in fineract client. Request headers
 - [x]  Implement TTK Tests 

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/mifos-core-connector/pull/12 - In Progress

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elijah0kello** [comment]
https://github.com/openMF/ph-ee-integration-test/blob/master/src/test/java/resources/mojaloop.feature

**Comment by elijah0kello** [comment]
Here is the draft sequence diagram subject to changes discussed with @PaulGregoryBaker 

https://github.com/elijah0kello/mifos-core-connector-docs?tab=readme-ov-file#integration-for-payer-flow

**Comment by PaulGregoryBaker** [comment]
1 pt left
