### ISSUE TITLE
Deploy Sprint-3.3 codebase to AWS

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#387]
**Goal**:
As a Switch
I would like to _deploy the Sprint3.3 codebase (on AWS)_
to enable Testing & QA activities on the updated code and uncover any issues.

**Tasks**:
- [ ] Deploy 3.3 codebase on AWS
- [ ] ~Sanity testing (happy path) to ensure setup works as expected~

**Acceptance Criteria**:
- [ ] A Switch deployment with the Sprint 3.3 code-base exists on AWS
- [ ] ~Sanity testing for happy path is performed on the above deployment~

**Dependencies**:
- [ ] Codebase availability (pending PRs, etc)

**Accountability**:
- Owner @mdebarros 
- QA/Review

**Comment by elnyry** [comment]
Covered in #392 now
