### ISSUE TITLE
Transfer Prepare request that exceeds the NET_DEBIT_CAP does not respond with an errorInformation message

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#388]
## **Issue**:
- https://github.com/mojaloop/central-ledger/issues/109

**Tasks**:
- [x] Identify issue [@ggrg]
- [x] Bugfix [@ggrg]
- [x] Extend the solution adding Errors module for API specs' defined errors [@ggrg]
- [x] And unit tests and cover 100% on new code [@ggrg]

**Acceptance Criteria**:
- [x] When a transfer request exceeds Net Debit Cap, an error message is sent (as described in Fix here: https://github.com/mojaloop/central-ledger/issues/109 )

## **Pull Requests**:
- [x] [PR 118](https://github.com/mojaloop/central-ledger/pull/118)

## **Follow-up**:
- N/A

## **Dependencies**:
- N/A

## **Accountability**:
- Owner: @mdebarros 
- QA/Review: Dev-Team

**Comment by elnyry** [comment]
Included in #312

**Comment by ggrg** [comment]
[PR 118](https://github.com/mojaloop/central-ledger/pull/118)
