### ISSUE TITLE
Harden the Mojaloop Connector to support FX flows as an FXP, Payer DFSP, Payee DFSP

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3909]
## **Goal**:
`As a` DFSP wanting to make and receive FX payment in mojaloop
`I want to` ensure that the FX implementation POC is matured 
`so that` I can make use of the Mojaloop connector to build my integration for the FX use case to my backend system.

`As a` directly connected Foreign Exchange Provider participating in a mojaloop
`I want to` ensure that the FX implementation POC is matured 
`so that` I can make use of the Mojaloop connector to build my integration for the FX use case to my backend system.

Note: FXPID are obtained through configuration in Payer DFSP 

**Acceptance Criteria**:
- [x] Verify that error cases are mapped and documented.
  - [x] Payer DFSP 
      - [x] Check if FX is required
      - [x] Obtain FX quote
      - [x] Check conversion acceptance with Core connector 
      - [x] Initiate FX Transfer
   - [x] Payee DFSP
      - [x] Get Parties add supported Currencies (Config)
   - [x] FXP
      - [x] POST / PUT fx Quotes
      - [x] POST / PUT fx Transfers
- [x] Verify that the functional test are added to test the error cases. 
- [x] Verify that unit test are added
- [x] Verify that all mojaloop core standards are met

Note: because API is being use this may need to be functional TTK test and not integration tests.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
   - [x] Bump central-services-shared to release version
   - [x] Update funtional test harness
   - [x] Payer DFSP 
       - [x] Fx quote expired
           - [x] Unit test
           - [x] Func test  
       - [x] Fx transfer fulfil expired
           - [x] Unit test
           - [ ] Func test
       - [x] Fx transfer invalid fulfilment
           - [x] Unit test
           - [x] Func test (Unable to test since custom fulfilment would require harness overhaul)
   - [x] No providers found (TODO added, functionality not yet implemented)
       - [x] Unit test
       - [x] Functional test
   - [x] Payee DFSP
      - [x] Get Parties add supported Currencies (Config)
          - [x]  No config supported currency env
              - [x]  Unit test
          - [x]  No payee currency supported
              - [x]  Unit test
              - [x]  Functional test (Would need a singular ill-configured sdk for this test - skipped)
           - [x]  No payee currency returned
              - [x]  Unit test
              - [x]  Functional test
   - [x] Payee DFSP 
       - [x] Unit tests
       - [x] Functional tests
           - postFxQuotes inbound
           - createPutFxQuotesHandler inbound
           - postFxTransfers inbound
           - createPutFxTransfersHandler inbound
           - createPutFxTransfersHandler inbound

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3909?planning-poker) with Zenhub @kleyow @oderayi @sri-miriyala @vijayg10

**Comment by PaulGregoryBaker** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3909?planning-poker) with Zenhub @kalinkrustev

**Comment by PaulGregoryBaker** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3909?planning-poker) with Zenhub @geka-evk
