### ISSUE TITLE
[30] Postman collection not up to date

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#391]
**Goal**:
As a switch user
I would like to _have access to well documented & published Postman Collections/Scripts_
so that I can easily sue Postman to call an existing deployment

**Tasks**:
- [x] Create ML API Collection [ @mdebarros  - 20180823 ]
- [x] Create documentation for ML API Postman Collection [ @mdebarros  - 20180823 ]
- [x] Publish ML API Collection
- [x] Create Settlements API Collection [ @mdebarros  - 20180824 ]
- [x] Create documentation for Settlements API Postman Collection [ @mdebarros - 20180824 ]
- [x] Publish Settlements API Collection
- [x] Create Central Ledger Admin API Collection [ @mdebarros ]
- [x] Create documentation for Central Ledger Admin API Postman Collection [ @mdebarros ]
- [x] Publish Central Ledger Admin API Collection
- [x] Updated docs and on boarding guide to include information about the Published API Collections (issue https://github.com/mojaloop/central-ledger/issues/102)

**Acceptance Criteria**:
- [x] Postman scripts published in a GIT repository
- [x] Postman scripts are well documented
- [x] GIT repository has documentation on how to use Postman Collections
- [x] On-boarding documentation is updated to reference the correct Postman Collection (issue https://github.com/mojaloop/central-ledger/issues/102)
- [x] Docs repo is updated to reference the correct Postman Collection

## **Pull Requests**:
- [x] https://github.com/mojaloop/postman/pull/1
- [x] https://github.com/mojaloop/central-ledger/pull/151

## **Follow-up**:
- N/A

## **Dependencies**:
- [x] #416 [ BLOCKER ]

## **Accountability**:
- Owner: @mdebarros
- QA/Review: Dev-Team

**Comment by elnyry** [comment]
Miguel, at this point - I'm leaning towards going ahead with adding a collection for the existing services an tracking Settlements separately, later on.

What do you think?

**Comment by elnyry** [comment]
Closing this now as the collection is published to mojaloop/postman repo and documentation in Onboarding.md is updated
