### ISSUE TITLE
Extend the Mojaloop Golden Path test to include the FX use case

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3910]
## **Goal**:
`As a` adopter of Mojaloop
`I want to` make use of the FX use case and be able to regularly test its functionality 
`so that` use these test to validate deployment and to ensure there is no regressions as features are added in the future.

**Note:** This story does not cover GP testing of Aborted (not timed-out) FX transfers, and fx Quotes

**Acceptance Criteria**:
- [x] Verify that the TTK golden path test cases have the FX tests added
- [x] Verify that unhappy path test cases are included for all errors. e.g. Errors originating in:
   - [x] timeout failures
   - [x] schema failures
   - [x] switch errors
   - [x] fxp errors
   - [x] Payee dfsp errors
   - [x] payer dfsp errors

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Understand the detailed FX flow diagram 
- [x] Put a diagram that shows the set up of tests [Inprogress]
- [x] Write FX happy path along with tests 
- [x] Run docker compose set up
- [x] Quotes Negative Scenarios
     - [x] Post/fxpQuotes - 400 error
     - [x] Put /fxpQuotes/ID/error
     - [x] Put/Quotes/ID/error
     - [x] POST/quotes after FX validity in put/fxQuotes expires.
- [x] Transfers Negative scenarios
     - [x]  400 error code
     - [x]     Fxp-error
        Put /fxpTransfers/ID/error
     - [x]    Put /transfers/ID/error
     - [x]    Timeout test cases(5)
     - [x]  Invalid Fulfilment from FXP in Put/fxTransfers
     - [x] payee_invalid_fulfilment
     - [x] Duplicate Handling 
         - [x]    fulfil_commit
         - [x]  fulfil_reject
    - [x]    Block transfer
    - [x] FXP - REJECTED status
    - [x] FXP - PENDING status
    - [x] FXP - COMPLETED status
    - [x] FXP transfer after quote expiry
- [x] Connectivity tests 
- [x] What about settlements [Discussed and created a place holder, https://github.com/mojaloop/project/issues/3940]

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Tests are complete; errors in running and testing the tests.

3 pts left

**Comment by sri-miriyala** [comment]
This story is limited to writing tests only. Running of tests is another story and it is here:
