### ISSUE TITLE
Create visual feedback on buttons pressed in the portals

### ISSUE THREAD

**Issue by PaulMakinMojaloop** [mojaloop/project#3915]
The impassive (no feedback) implementation we currently have results in people (me) repeatedly hitting a button when the portal is simply being slow to respond. Which causes potential operational issues.

## **Goal**:
As a Hub portal operator

I want to get visual feedback on my actions, such as clicking a button, so that I know the portal is carrying out the corresponding action
 
so that I'm not repeatedly clicking on an impassive button, and confusing the system and myself with multiple identical requests.

## Acceptance Criteria
 - [ ] **Scenario: Visual feedback on button presses**
  - Given the user interacts with a button on any portal
  - When the button is pressed by the user
  - Then the button should display visual feedback (e.g., change color or show an animation) indicating that it's processing the action
  

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
