### ISSUE TITLE
Improve Participant support by providing automated notifications of key events

### ISSUE THREAD

**Issue by PaulMakinMojaloop** [mojaloop/project#3916]
## **Goal**:
As a participating DFSP staff member responsible for the financial management of our connection to a Mojaloop Hub

I want to receive a notification (using my email and mobile phone contact details registered at the Hub) when my available liquidity drops below an agreed threshold, or approaches the NDC value

so that I can take timely corrective action by transferring additional funds to the settlement/liquidity account

**Acceptance Criteria**:
 - [ ] **Scenario: Notification sent when available liquidity drops below threshold or approaches NDC value**
  - Given a participating DFSP staff member has registered their contact details at the Hub
  - When their available liquidity drops below an agreed threshold or approaches the NDC value
  - Then the staff member should receive an automated notification via email and mobile phone contact details
  - And the staff member should take timely corrective action by transferring additional funds to the settlement/liquidity account

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
