### ISSUE TITLE
3.3.0-snapshot

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#392]
## **Pull Request**:
- https://github.com/mojaloop/central-ledger/pull/107

**Tasks**:
- ~Resolve merge conflicts~
- [ ] ~Define Functional test scenarios~ [ @sri-miriyala  ]
- [ ] ~Verify Functional test scenarios~ [ @sri-miriyala  ]
- [x] ~Merge~ Rename `develop-PI3` code into `develop` [ @mdebarros ]
- [x] Snapshot release (tags, docker image, etc) [ @mdebarros ]
- [x] Deploy to AWS [ @mdebarros ]
- [x] Fix issues with deployment, resolve blockers for QA activities [ @mdebarros ]
  - [x] Redeploy to fix issue - requests not sent to ml-api-adapter as expected [ @mdebarros ]
  - [x] Redeploy to fix issue with Notifications not being sent to mock/simulated FSP [ @mdebarros ]
  - [x] Fixed bug #403 [ @mdebarros ]
- [x] Support testing activities (setup, configuration needed) [ @mdebarros ]
- [ ] ~Verify Functional test scenarios in `develop` branch~ [ @sri-miriyala  ]

**Bug Fixes**:
_**Note:** Only issues with priority `high` must be completed as part of this story. Others may be completed in future_
- [x] https://github.com/mojaloop/ml-api-adapter/issues/29 (Priority: High)
- [x] https://github.com/mojaloop/ml-api-adapter/pull/32(Priority: High)
- [x] https://github.com/mojaloop/ml-api-adapter/pull/31 (Priority: High)
- [ ] https://github.com/mojaloop/central-ledger/issues/121 (Priority: Medium)
- [ ] https://github.com/mojaloop/central-ledger/issues/123 (Priority: Medium)

**Acceptance Criteria**:
- [x] PI3.3 Code ~has been merged into~ is available on `develop` branch
- [x] All built assets are published (docker images, packages, etc)
- [x] A Switch deployment with the Sprint 3.3 code-base exists on AWS
- [x] Fix issues with configuration or setup to enable QA activities.
- [ ] ~PI3.3 Code has been functionally tested with bugs logged as necessary~

## **Follow-up**:
- N/A

## **Dependencies**:
- [x] Casa-team [ @sri-miriyala ] for running the Functional Test Harness

## **Accountability**:
- Owner: tbd
- QA/Review: Dev-Team

**Comment by elnyry** [comment]
Added 2 new tasks to reflect work that was done by Miguel to fix configuration issues, bugs in setup to enable transfers to work; Hence, increased estimate as well

**Comment by elnyry** [comment]
Increasing estimate as Miguel had fix a few bugs and logged a few more to un-block QA activities
