### ISSUE TITLE
Quality improvements on beneficiary-registration-portal-backend

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3924]
## **Goal**:
`As a` Community member interested in the G2P usecase that leverages MOSIP to manage personal payment aliases
`I want to` quality software assets
`so that` I can make use for and confidently modify the software

**Acceptance Criteria**:
- [ ] Verify that  [beneficiary-registration-portal-backend](https://github.com/mojaloop/beneficiary-registration-portal-backend) is updated to include
   - [ ] linting can code formatting by adding esLint and prettier
   - [ ] unit tests are added
   - [ ] API has an Open API definition file
   - [ ] all unused variables, methods, packages are removed
   - [ ] Testing coverage meets standards

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Add eslint config
- [x] Add commit linting
- [x] Add dependency checks
- [x] Add pre commit hooks
- [x] Add prettier config
- [x] Review code functionality
- [x] Write unit tests
- [x] Api Request schema validation
- [x] Review api and develop open api schema
- [x] Remove unused resources with help of eslint
- [x] Increase test coverage to meet standard.

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [x] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/beneficiary-registration-portal-backend/pull/7

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
