### ISSUE TITLE
Quality improvements on beneficiary-registration-portal-frontend

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3925]
## **Goal**:
`As a` Community member interested in the G2P usecase that leverages MOSIP to manage personal payment aliases
`I want to` quality software assets
`so that` I can make use for and confidently modify the software

**Acceptance Criteria**:
- [ ] Verify that  [beneficiary-registration-portal-frontend](https://github.com/mojaloop/beneficiary-registration-portal-frontend) is updated to include
   - [ ] latest dependencies
   - [ ] all unused depencencies are removed
   - [ ] licence error is fixed (details below)
   - [ ] automated tests unit tests are added
   - [ ] API has an Open API definition file
   - [ ] all unused depencencies are removed
   - [ ] Testing coverage meets standards

**licence-scanner error:** https://app.circleci.com/pipelines/github/mojaloop/beneficiary-management-system-svc/2/workflows/fa306d87-54d4-4761-8ac0-2a3d4fcd47ba/jobs/15
```
Allowing only the following licenses: AFLv2.1;Apache License, Version 2.0;Apache*;Apache-2.0;Apache 2.0;BlueOak-1.0.0;BSD;BSD*;BSD-2-Clause;BSD-3-Clause;BSD-3-Clause-Clear;CC-BY-3.0;CC-BY-4.0;CC0-1.0;ISC;MIT;MIT*;Public Domain;Python-2.0;UNLICENSED;Unlicense;Unlicensed;WTFPL;(BSD-2-Clause OR MIT OR Apache-2.0);(MIT OR Apache-2.0);(MIT OR CC0-1.0);(Unlicense OR Apache-2.0);WTFPL OR ISC;(WTFPL OR MIT)

Package "axe-core@4.7.0" is licensed under "MPL-2.0" which is not permitted by the --onlyAllow flag. Exiting.
make: *** [Makefile:49: run] Error 1
```
What should be done to fix it:
  Identify which UI package is using axe-core@4.7.0, and try to remove/update it. I think, 
@James Simbi
 is able to do it.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Add eslint config
- [x] Add commit linting
- [x] Fix license error
- [x] Add dependency checks
- [x] Remove unused dependencies
- [x] Add pre commit hooks
- [x] Add prettier config
- [x] Review code functionality
- [x] Write unit tests
- [x] Remove unused resources with help of eslint
- [x] Increase test coverage to meet standard.

**New Issues**
- [x] Fixing Failing ci tests
- [x] Dependency conflict issue
- [x] Licence issue
- [x] eslint errors that require code refactoring
- [x] fix vulnerbility issues in audit ci

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- This is a frontend and not an api. Does it still need an open api schema?

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elijah0kello** [comment]
This is an a frontend and not an api. Does it still need an open api schema?

**Comment by elijah0kello** [comment]
Here is a link to the latest run and it passes for license checks but fails on linting and vulnerability checks.

I need some advice on how to fix these vulnerability checks.

**Comment by elijah0kello** [comment]
PR Merged
