### ISSUE TITLE
Deploy and Record G2P Demonstration

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3926]
## **Goal**:
`As a` DPG community member
`I want to` understand the value being designed and poc'ed in the G2P - Mosip POC
`so that` incorporate part of this design or assets in my G2P solution

**Acceptance Criteria**:
- [x] Verify that the beneficiary registration portal (front end and back end) are deployable on a server using Docker Compose
- [x] Verify that the beneficiary registration portal connects to a secured mojaloop payment switch through the mojaloop connector
- [x] Verify that the beneficiary registration portal has a functional connection to the MOSIP sandbox
- [x] Verify that the beneficiary registration portal can be called by the beneficiary management system
- [x] Verify that the beneficiary registration portal can connect to the payment token adapter to register tokens.
- [x] Verify that the payment token adapter is deployed between a MIFOS and mojaloop connector that is connecting to the same mojaloop.

**Demo Recording**
- [x] Verify that a script has been created and review by Paul Maikin\G2P
- [x] Verify that a full demo is recorded

Here is a diagram summarising the demonstration deployment configuration.

![FX-G2P Demo (1)](https://github.com/mojaloop/project/assets/40144680/ea845462-91d3-4d81-a428-3305a5209f29)

G2P repo: https://github.com/mojaloop/ml-mosip-integration

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Deploy BRP and BMS to vm; deploy 2 pm4mls and run g2p p2p transfer test-case using TTK
- [x] Demo: https://drive.google.com/file/d/1Y1ItvN7Qic0XX9tB-uAKjnpTyM1hgNQW/view?usp=sharing

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
