### ISSUE TITLE
Update IaC to deploy Hardened Currency conversion components

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3927]
## **Goal**:
`As a` User of a mojaloop 
`I want to` test the cross currency functionallity
 `so that` I can decide if the functallity meets my requirements

**Acceptance Criteria**:
- [x] Verify that a new Helm development version is released.
   - [ ] Verify that the existing non-fx golden path test passes
- [x] Verify that the IaC [FX branch](https://github.com/mojaloop/iac-modules/tree/feature/fx) is updated to
    - [x] New Mojaloop Dev Version with latest currency conversion snapshots
    - [x] new Kafka topics
    - [x] Mojaloop Values file changes
    - [x] Merge upstream changes to the FX IaC Modules branch

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Update central-ledger api and handlers
- [x] Update quoting-service api and handlers
- [x] Update sdks
- [x] Update ml adapter/notification
- [x] Deploy
- [x] Test run GP
- [ ] ~Investigate/Fix problems causing GP to fail~
- [x] Create story for 15.8.0-snapshot.15->15.8.0-snapshot.21 regression in GP
- [ ] `Create story for IAC Mojaloop v16 GP failures`
- [x] Create story for IAC Quoting health point test and updating helm chart with ttk fix

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3927?planning-poker) with Zenhub @aaronreynoza @kleyow @oderayi @sri-miriyala @vijayg10

**Comment by PaulGregoryBaker** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3927?planning-poker) with Zenhub @geka-evk

**Comment by PaulGregoryBaker** [comment]
1 pts left

**Comment by kleyow** [comment]
Follow up stories.
https://github.com/mojaloop/project/issues/3949

**Comment by kleyow** [comment]
As discussed in the review the acceptance criteria "Verify that the existing non-fx golden path test passes" was not able to be met due to follow up issues. Those stories are listed above. 

Story was agreed to be moved to done after those stories were created.
