### ISSUE TITLE
4.2-2 Design Timeout Handler

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#393]
**Goal**:
As a developer
I would like to _design the Timeout Handler_
so that timeouts can be issued/administered for the Switch

**Note**:
An API may be needed to query 'pending' transactions/transfers

**Tasks**:
- [x] ~Design Timeout Handler~
  - [x] ~Sequence diagrams for timeout handler (starting [here](https://github.com/ggrg/docs/blob/feature/designNegativeScenarios/CentralServices/seq_diagrams/seq-timeout-2.3.0.svg)) [@NicoDuvenage]~
  - [x] ~DA to review the Sequence diagrams~
- [x] ~Discuss the frequency of the Timeout Handler (how frequently it runs - 2 seconds? 10 seconds?)~
  - [x] ~Make the value of frequency at which the timeout handler picks up messages configurable [@NicoDuvenage]~
  - [x] ~Decide whether it needs to be run separately (thread pool etc) [@NicoDuvenage]~
- [x] Update sequence diagrams based on inputs from design for DAO layer, etc #303 

**Acceptance Criteria**:
- [x] ~Sequence diagrams for Timeout handler are available~
- [x] ~Sequence diagrams for Timeout handler are reviewed by the DA~
- [x] ~Review the approach (run separately, frequency) with DA~
- [x] The Sequence diagrams are updated to incorporate changes and feedback coming out of the DAO layer design in #303 

**Dependencies**:
- [x] #301 

**Accountability**:
- Owner [@NicoDuvenage]
- QA/Review
