### ISSUE TITLE
FX - Unnecessary participant currency validations in FX transfer

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3932]
**Summary**:
Observed that some validations are not needed for FX transfer but are happening in the central services.
For example:
- Payer doesn't need an account in target currency
- Payee doesn't need an account in source currency

**Severity**:
High

**Priority**:
Medium

**Expected Behavior**
We should be able to make an FX transfer without onboarding both source and target currencies for payer.

**Steps to Reproduce**
  1. Observe the integration tests for fxTimeout (test/integration-override/handlers/transfers/fxTimeout.test.js)
  2. In function `prepareFxTestData`, remove target currency for payer by changing the line
  ```
const payer = await ParticipantHelper.prepareData(dataObj.payer.name, dataObj.sourceAmount.currency, dataObj.targetAmount.currency)
----to----
const payer = await ParticipantHelper.prepareData(dataObj.payer.name, dataObj.sourceAmount.currency)
```
  3. Execute this integration test and it fails
  4. Observe the logs in central ledger services and we can find some error like 'Participant currency' doesn't exist

**Specifications**
  - Component (if known): Central Ledger FX branch
  - Type of testing: Integration tests
  - Bug found/raised by: @vijayg10 

**Tasks**
  - [x] Investigate the issue by going through different FX uses cases sequence diagrams
  - [x] Discuss the observations and agree on the logic for validations
  - [x] Refactor prepare handler for validations
  - [x] Unit tests
  - [x] Integration tests
  - [ ] Fix the issue with table transferParticipant related to the column `participantCurrencyId`
    - [x] Change participantCurrencyId as nullable
    - [x] Add participantId to the table transferParticipant
    - [x] Refactor the queries using participantCurrencyId from the table transferParticipant
    - [x] Fix unit tests

**Pull Requests**:
- [ ] https://github.com/mojaloop/central-ledger/pull/1041

**Comment by vijayg10** [comment]
I have gone through the sequence diagrams and discussed with @PaulGregoryBaker and came up with the following solution for this problem.

The participant account validations to be done based on the cyril result. i.e, In prepare handler, cyril should return a list of participant accounts (participantCurrencyIds) to be validated and then the prepare handler function iterates through the list and validate the accounts of existence and active status.

The following are the validations based on different FX use cases.

Payer side currency conversion
----------------------------------
- POST /fxTransfer
  - InitiatingFSP - Source Currency
  - CounterPartyFSP - Source Currency
   - CounterPartyFSP - Target Currency

- POST /transfers
  - Payee - Currency

Payee side currency conversion
---------------------------------
- POST /transfers
  - Payer - Currency
  - Payee - Currency (Optional based on config param)

- POST /fxTransfer
  - InitiatingFSP - Target Currency
   - CounterPartyFSP - Source Currency
   - CounterPartyFSP - Target Currency

**Comment by PaulGregoryBaker** [comment]
2 pts left
Integration tests still outstanding.
