### ISSUE TITLE
[FX] Adjust participant account validations in quoting service to support FX

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3933]
## **Goal**:
`As a` mojaloop community member making use of FX

`I want to` validate the correct participants accounts
  
`so that` I am confident that those accounts are active and are in place before agreeing to the quote

**Acceptance Criteria**:
- [x] Refactored POST /quotes
  - [x] If supportedCurrencies is set in the payer object, then we should validate the payer against all those currencies
  - [x] If it is not set, then we should validate only payer against the currency in the quotes request. But we can't validate payee and it will be done in PUT /quotes.
- [x] Refactored PUT /quotes
  - [x] If payeeReceiveAmount is set, validate payee against the payeeReceiveAmount currency
  - [x] If not, validate payee against the transferAmount currency
- [x] This refactoring doesn't break the exiting GP tests
- [x] Add integration tests for this use case (POST /quotes and PUT /quotes)

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Update participants accounts validation for POST /quotes requests [ **Done** ]
- [x] Update participants accounts validation for PUT /quotes requests [ **Done** ]
- [x] Write integration tests [ **Done** ]
- [x] Validate GP tests pass [**Done**]

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/quoting-service/pull/333

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
1 pt left + bug needs fixing.

**Comment by vijayg10** [comment]
I think one of the acceptance criteria is wrong in the story. I updated it correctly.If it is not set, then we should validate only payer against the currency in the quotes request. But we can't validate payee and it will be done in PUT /quotes.
[6:56](https://infitx.slack.com/archives/D04DKV5EUEL/p1719494803611359)
If there is no supportedCurrencies in the quotes request, that means that's normal quotes request or payer side conversion. In both cases we can validate if payee has an account in the currency specified in quotes request.
6:57
But we mentioned it as 'payer' in that point
