### ISSUE TITLE
[Token Portal] Enable configuration of redirect.

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3934]
## **Goal**:
`As a` as mojaloop community member interested in personal payment token alias funcitonality
`I want to` ensure that I can deploy the system on my servers
`so that` configure the MOSIP redirects effectively.

**Acceptance Criteria**:
- [ ] Verify that through configuration of the token portal backend, the portal frontend will correctly configure the MOSIP redirect when calling the MOSIP.
- [ ] 

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
