### ISSUE TITLE
Central Ledger Migration / Seeds implementation should not depend on the auto_increment config of mysql

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3939]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` seed the database tables with fixed Enum integer values instead of depending on the auto increment of mysql
  
`so that` I can deploy mysql with any auto_increment value which will be needed incase of active-active replica and cluster deployments

**Acceptance Criteria**:
- [ ] All the seeds in the following databases uses fixed integer values
  - [ ] central_ledger
  - [ ] quoting_service
  - [ ] account_lookup
- [ ] Auto increment config in the mysql should not affect the GP

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
@kalinkrustev suggested this ref https://github.com/knex/knex/issues/2130
