### ISSUE TITLE
3.07.02 Implement the DAO layer for Settlement Windows

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#394]
**Goal**:
As a Switch 
I would like the _DAO layer for Settlements be Implemented_
so that Settlements functionality can be supported by the Database

**Tasks**:
- [ ] Implement DAO layer for Settlements (only implement the methods specified in the design)
- [ ] Tests
  - [ ] Unit tests
  - [ ] Integration tests
  - [ ] Code coverage

**Acceptance Criteria**:
- [ ] The DAO layer necessary for Settlements functionality is implemented
- [ ] The implementation aligns with the design

**Dependencies**:
- [x] #327 
- [x] #328 
- [ ] #332
- [ ] #333 

**Notes**:
- Ten API calls involved
- Six tables
- Two queries

**Accountability**:
- Owner 
- QA/Review @wdcmb
