### ISSUE TITLE
Run FX golden path tests on a VM

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#3942]
## **Goal**:
`As a` adopter of Mojaloop
`I want to` make use of the FX GoldenPath tests be able to regularly run and test its functionality 
`so that` use these test to validate deployment and to ensure there is no regressions as features are added in the future.

**Note:** This story does not cover GP testing of Aborted (not timed-out) FX transfers, and fx Quotes

**Acceptance Criteria**:
- [ ] Verify that the TTK Rules are updated/added to run and have the FX GoldenPath be tested
- [ ] Verify that these tests are running on a VM:
   - [ ] timeout failures
   - [ ] schema failures
   - [ ] switch errors
   - [ ] fxp errors
   - [ ] Payee dfsp errors
   - [ ] payer dfsp errors

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Get Access to VM and run happy path
- [x]  Trouble shoot the happy path
- [ ] Add TTK rules needed for Quotes , transfers error cases
- [ ] Run Quotes Negative Scenarios and update scripts as needed
     - [ ] set 1
     - [ ] set 2
- [ ] Run Transfers Negative scenarios and update scripts as needed
     - [ ]  Set 1
     - [ ]  Set 2
     - [ ]  Set 3
     - [ ]  Set 4
     - [ ] Set 5
 - [ ] Check for PATCH notification
 - [ ] Report any issues 
    
**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
