### ISSUE TITLE
Testing approach to Oracle Management in vnext

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#3952]
## **Goal**:
`As a` Hub Operator

`I want to` test Oracles used for the Account lookup system
  
`so that` I can onboard and test Oracles needed for the scheme to support various identifiers chosen.

**Acceptance Criteria**:
- [ ] A testing approach for onboarding and using Account lookup oracles is documented

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by JulieG19** [comment]
There is a change of strategy with vNext. I am closing this ticket accordingly to that change.
