### ISSUE TITLE
Build FX bundled release GP tests using three Payment Managers with TTK as core-connectors

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#3953]
As an adopter of Mojaloop intending on offering a cross-currency service
I want to make sure that PM4ML is configured to run as FXP, PM4ML as payer, PM4ML as payee
so that I can rely on this functionality once deployed in an IaC environment.

**Note**: This story does not cover GP testing of Aborted (not timed-out) FX transfers, and fx Quotes

**Acceptance Criteria**:
 - [ ] Verify that payer, payee and FXP are configured and deployed as PM4ML in the IaC env, that will be used for testing
 - [ ] Verify that the  existing TTK Rules can be leveraged for TTK with PM4ML
 - [ ]  Verify that the below tests that are part of FXP Golden Path can be run in an IaC deployed environment
   - [ ] timeout failures
   - [ ] schema failures
   - [ ]  switch errors
   - [ ]  fxp errors
   - [ ]  Payee dfsp errors
   - [ ] payer dfsp errors

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty:** <High|Medium|Low> > A short comment to remind the reason for the rating

**Tasks:**

 - [x] Get Access to environment and run happy path [@vijayg10 ]
 - [x] ~~Pull upstream changes from main branch to fx branch and refine the FX related changes~~ [@vijayg10 ] Compared the changes in the feat/fx-impl branch against main branch and observed that the necessary changes are already merged to main. So we don't need fx branch.
 - [x] 3 new PM4MLs to be deployed using TTK as core connector, in dev env [@vijayg10 ]
 - [x] 3 new PM4MLs to be onboarded in the dev env. [@vijayg10 ]
 - [x] Add a provisioning collection for fxp and a sample env file [@vijayg10 ]
 - [x] Create helm development versions for FX [@vijayg10 ]
   - [x] Add FX support for SDK helm chart (Pushed a commit to https://github.com/mojaloop/helm/pull/632)
   - [x] Update SDK in PM4ML helm chart to support FX (https://github.com/pm4ml/mojaloop-payment-manager-helm/pull/151)
 - [x] Trouble shoot the happy path to check if there are any issues [@vijayg10 ]
   - [x] Identified an issue with quoting service validation [quoting-service/pull/340](https://github.com/mojaloop/quoting-service/pull/340)
   - [x] Batch processing should be enabled and observed some issue with the fx branch of helm chart. Handled with the following commits
     - [x] https://github.com/mojaloop/helm/commit/657d5084e9c0ae8ad173ad68a3ed88a07fb96c18
     - [x] https://github.com/mojaloop/helm/commit/0feb52b837d6f3bb4893c2c8effe9e9c45d1f3e5
     - [x] Update IaC repo for adding support to batch processing of timeout handlers [iac-modules/pull/302](https://github.com/mojaloop/iac-modules/pull/302)
   - [x] Version of the central ledger is not updated in batch position handler
   - [x] Fixed an issue with migration scripts for transferParticipant table [commit](https://github.com/mojaloop/central-ledger/commit/bc306034f475ccb17fd8574079259f3758f16ec7)
   - [x] Admin transfer is throwing an error (This is because of old version in the hlem chart, fixed it in the helm fx branch)
 - [x] Update scripts to point to PM4ML payer outbound endpoint 1 [@sri-miriyala ]
 - [x] Update scripts to point to PM4ML payer outbound endpoint2 [@sri-miriyala ]
 - [x] Verify TTK rules needed for Quotes error cases are still working with PM4ML as TTK[@sri-miriyala ]
 - [x] Verify TTK rules needed for transfers error cases are still working with PM4ML as TTK[@sri-miriyala ]
 - [x] Run Quotes Happy Path Scenario and update scripts as needed [@sri-miriyala ]
- [x]  Run Transfers Negative scenarios and update scripts as needed[@sri-miriyala ]
       - [ ] Set 1 
       - [ ] Set 2
       - [ ] Set 3
      - [ ]  Set 4
     - [x]  Set 5
 - [x] Run Payer errors
 - [x] Run payee error 
 - [x] Report any issues 

 **Acceptance Criteria pass**
- [ ]  Designs are up-to date
- [ ]  Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

**Comment by vijayg10** [comment]
https://github.com/mojaloop/helm/pull/632

**Comment by vijayg10** [comment]
**Deployment and Testing Notes:**

**Switch Deployment:**
- `custom-config/mojaloop-vars.yaml`
  ```yaml
  mojaloop_chart_version: 16.2.0-18561-510a080
  ttk_testcases_tag: 16.1.0-fx-snapshot
  onboarding_collection_tag: 16.1.0-fx-snapshot.1
  central_ledger_handler_transfer_position_batch_processing_enabled: true
  ```
- Use the following versions in `custom-config/cluster-config.yaml`
  ```yaml
  ansible_collection_tag: v5.2.6
  iac_terraform_modules_tag: v5.4.0-fx.1
  ```
- `custom-config/mojaloop-values-override.yaml`
  ```yaml
  quoting-service:
    quoting-service:
      ## This is required until the PR https://github.com/mojaloop/helm/pull/636 gets merged to fx branch
      configOverride:
        .QUOTErc: {
          "HUB_PARTICIPANT": {
            "ID": 1,
            "NAME": "Hub"
          }
        }
    quoting-service-handler:
      ## This is required until the PR https://github.com/mojaloop/helm/pull/636 gets merged to fx branch
      configOverride:
        .QUOTErc: {
          "HUB_PARTICIPANT": {
            "ID": 1,
            "NAME": "Hub"
          }
        }
  ## The following is required if we use older version of IaC. This is addressed in the recent PR https://github.com/mojaloop/iac-modules/pull/302
  centralledger:
    centralledger-handler-timeout:
      config:
        batch_processing_enabled: true
  ```

**PM4ML Deployment:**
- Use the following versions in the file `custom-config/cluster-config.yaml`
  ```yaml
  ansible_collection_tag: v5.2.6
  iac_terraform_modules_tag: v5.3.5
  ```
- `custom-config/pm4ml-vars.yaml`
  ```yaml
  pm4mls:
    - pm4ml: testpayer
      pm4ml_chart_version: 9.2.1-snapshot.1
      pm4ml_dfsp_id: testpayer
      core_connector_selected: ttk
      pm4ml_external_switch_oidc_url: <KEYCLOAK_URL_OF_SWITCH_HERE>
      pm4ml_external_switch_fqdn: <FSPIOP_FQDN_OF_SWITCH_HERE>
      pm4ml_external_mcm_public_fqdn: <MCM_FQDN_OF_SWITCH_HERE>
      supported_currencies: "EUR"
      fxp_id: "testfxp"
    - pm4ml: testpayee
      pm4ml_chart_version: 9.2.1-snapshot.1
      pm4ml_dfsp_id: testpayee
      core_connector_selected: ttk
      pm4ml_external_switch_oidc_url: <KEYCLOAK_URL_OF_SWITCH_HERE>
      pm4ml_external_switch_fqdn: <FSPIOP_FQDN_OF_SWITCH_HERE>
      pm4ml_external_mcm_public_fqdn: <MCM_FQDN_OF_SWITCH_HERE>
      supported_currencies: "CAD"
      fxp_id: "testfxp"
    - pm4ml: testfxp
      pm4ml_chart_version: 9.2.1-snapshot.1
      pm4ml_dfsp_id: testfxp
      core_connector_selected: ttk
      pm4ml_external_switch_oidc_url: <KEYCLOAK_URL_OF_SWITCH_HERE>
      pm4ml_external_switch_fqdn: <FSPIOP_FQDN_OF_SWITCH_HERE>
      pm4ml_external_mcm_public_fqdn: <MCM_FQDN_OF_SWITCH_HERE>
      supported_currencies: "EUR,CAD"
      fxp_id: "testfxp"
  ```
