### ISSUE TITLE
FX GP tests to be part of automated IaC pipeline

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#3954]
## **Goal**:
`As a Mojaloop adopter,

`I want to` run the Forex Golden Path tests in automated fashion on every deployment in any environment
  
`so that` the deployment with Forex feature will be validated automatically without manual intervention.

**Acceptance Criteria**:
- [ ] IaC pipeline to be created for Forex Golden Path tests
- [ ] Tests to use Payment manager
- [ ] Tests to use a specific version of Forex GP according to the Forex implementation version
- [ ]  IaC to use a variable to run the specific version of Forex GP tests
- [ ] Run in an IaC deployed environment
- [ ] Slack notifications to be sent out to Mojaloop "announcements" channel

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] IaC pipeline to be created for Forex Golden Path tests
- [ ] Tests to use Payment manager
- [ ] Tests to use a specific version of Forex GP according to the Forex implementation version
- [ ]  IaC to use a variable to run the specific version of Forex GP tests
- [ ] Run in an IaC deployed environment
- [ ] Slack notifications to be sent out to Mojaloop "announcements" channel

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulGregoryBaker** [comment]
Feature completed and Part of release 17 and included in to IaC
