### ISSUE TITLE
[pi-24 pqs] Address pqs issues on central-ledger for Mojaloop v16.1.0 RC

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#3955]
## **Goal**:
`As an` adopter 

`I want to` ensure that latest Mojaloop releases have known security issues addressed
  
`so that` Mojaloop platform can be deployed securely with known vulnerabilities addressed.

**Acceptance Criteria**:
- [x] Snyk alerts for Central-ledger repository are addressed
- [x] Dependabot alerts for Central-ledger repository are addressed (moderate, high and critical)
- [x] Ensure main branch is protected and collaborator list is up-to-date
- [x] Ensure open PRs are addressed, closing stale PRs
- [x] Update audit exceptions json file to remove exceptions added that are not necessary anymore
- [x] Close issues on the repository that are fixed / out-of-date

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [x] Address dependabot alerts and fix issues
- [x] Address Snyk alerts and fix
- [x] Review open PRs and close ones that are out-of-date or not applicable and remind owners to update
- [x] Review open issues and close ones that are out-of-date or not applicable and remind owners to update
- [x] Review branch protection rules
- [x] Review collaborators and access to the repository

**Done**
- [x] Acceptance Criteria pass
- [ ] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
