### ISSUE TITLE
[pi-24 pqs] ml-api-ledger pqs readiness for Mojaloop v16.1.0 RC

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#3957]
## **Goal**:
`As an` adopter of Mojaloop

`I want to` ensure that latest Mojaloop release of ml-api-adapter has known security & quality issues addressed
  
`so that` Mojaloop platform can be deployed securely with known vulnerabilities addressed.

**Acceptance Criteria**:
- [x] Snyk alerts for ml-api-adapter repository are addressed
- [x] Dependabot alerts for ml-api-adapter repository are addressed (moderate, high and critical)
- [x] Ensure main branch is protected and collaborator list is up-to-date
- [x] Ensure open PRs are addressed, closing stale PRs
- [x] Update audit exceptions json file to remove exceptions added that are not necessary anymore
- [x] Close issues on the repository that are fixed / out-of-date
- [x] Ensure codeowners file is current

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [x] Address dependabot alerts and fix issues
- [x] Address Snyk alerts and fix
- [x] Review open PRs and close ones that are out-of-date or not applicable and remind owners to update
- [x] Review open issues and close ones that are out-of-date or not applicable and remind owners to update
- [x] Review branch protection rules
- [x] Review collaborators and access to the repository
- [x] Update codeowners file to be up-to-date

**Done**
- [x] Acceptance Criteria pass
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-api-adapter/pull/528

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @elnyry-sam-k 
- QA/Review: Codeowners on repos
