### ISSUE TITLE
Enhance IaC modules to deploy test configuration for FX usecase

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3958]
## **Goal**:
`As a` hub operation intending on providing a cross currency servcie
`I want to` ensure that the cross currency functionality is working in my development
`so that` rely on that functionality

**Acceptance Criteria**:
- [ ] Verify that three PM4MLs are deployed with the Bundled release of Mojaloop
   - [ ] Payer DFSP PM4ML with TTK as core-connector
   - [ ] Payee DFSP PM4ML with TTK as core-connector (with basic rule for happy path)
   - [ ] FXP PM4ML with TTK as core-connector (with basic rule for happy path)
- [ ] Verify that all three PM4ML are security onboarded
- [ ] Verify that the FX happy path test runs

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating
**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by JaneS321** [comment]
Approach changed - no longer relevant
