### ISSUE TITLE
Implement API to query positions Part-1

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#396]
**Goal**:
As a Switch
I would like to _make an API available to query position or an FSP_ 
so that the Position of an FSP can be provided based on user profiles (to be added later)

**Tasks**:
- [ ] ~Sequence Diagram (design) for the API to GET Position of an FSP~
- [x] Implement API to GET Position of an FSP --> Sprint 3.4 [@shashi165]
- [ ] ~Tests~
  - [ ] ~Unit tests~
  - [ ] ~Integration tests~
  - [ ] ~Code coverage~

**Acceptance Criteria**:
- [x] An API to query position of an FSP is made available

**Dependencies**:
- [x] Follow-up item #404

**PR**:
- [ ] https://github.com/mojaloop/central-ledger/pull/120

**Accountability**:
- Owner @ggrg 
- QA/Review

**Comment by elnyry** [comment]
PR: https://github.com/mojaloop/central-ledger/pull/120

**Comment by shashi165** [comment]
merged the code
