### ISSUE TITLE
Implement Error Code Enum for Consistency Across BCs

### ISSUE THREAD

**Issue by ei-nghon-phoo** [mojaloop/project#3960]
### User Story
As a **developer**,
**I want to** implement a standardized error code enum for each bounded context (BC),
**So that** the service can access it as a single source of truth and avoid changing error codes multiple times for different svc.
Reference:
https://github.com/mojaloop/transfers-bc/blob/main/packages/public-types-lib/src/enums.ts
https://github.com/mojaloop/quoting-bc/blob/main/packages/public-types-lib/src/enums.ts
Https://github.com/mojaloop/account-lookup-bc/blob/main/packages/public-types-lib/src/enums.ts

### Tasks
- [ ] Participant BC
- [ ] Account and Balance BC
- [ ] Reporting BC
- [ ] Interops BC // to refer FSPIOP error codes
- [ ] settlement BC
- [ ] platform-config-bc
- [ ] security-bc
- [ ] auditing-bc
- [ ] logging bc
- [ ] scheduling-bc
- [ ] thirdparty-api-bc

**Comment by elnyry-sam-k** [comment]
hi @TW-Ei-Nghon-Phoo - whats the basis for this single source of truth for the error codes and possibly definitions. For example, like the FSPIOP error code definition: https://docs.mojaloop.io/api/fspiop/v1.1/api-definition.html#error-codes

These include several APIs - Administration, settlement and third-party APIs, so need some standard definitions.
