### ISSUE TITLE
Cleanup central-ledger codebase before PI3 releases are done

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#397]
**Goal**:
1. As a Switch
I would like to make sure _the central-ledger codebase is cleaned-up_
so that it is ready to be released after PI-3 and coverage metrics and other aspects can be improved.

**Tasks**:
- [x] Identify files/branches that are covered by unit tests and those that are not
- [x] Clean-up unused code (commented out code) - [@shashi165] [PR #161](https://github.com/mojaloop/central-ledger/pull/161)
- [ ] ~Check all TODO items~
- [x] Achieve code coverage goals  - [@shashi165] [PR #165](https://github.com/mojaloop/central-ledger/pull/165), [PR #167](https://github.com/mojaloop/central-ledger/pull/167)
- [x] Clean up package.json
  - [x] Remove carets, tilde symbols from package.json - [@shashi165] [PR #161](https://github.com/mojaloop/central-ledger/pull/161)
- [ ] ~Ensure that any Handlers do not have implementation business logic code, and that they should only mediate "transport"~

**Acceptance Criteria**:
- [x] The central-ledger code base is cleaned-up and better coverage is achieved, which would also help the CI/CD process.
- [ ] ~Ensure that stories are created for code re-factoring and resolving any technical debt issues/improvements~

**PRs**
 - [x] https://github.com/mojaloop/central-ledger/pull/161
 - [x] https://github.com/mojaloop/central-ledger/pull/163
 - [x] https://github.com/mojaloop/central-ledger/pull/164
 - [x] https://github.com/mojaloop/central-ledger/pull/165
 - [x] https://github.com/mojaloop/central-ledger/pull/167

**Dependencies**:
- [ ] None currently

**Accountability**:
- Owner 
- QA/Review

**Comment by elnyry** [comment]
Additional coverage provided in #425
