### ISSUE TITLE
Design the Profiling in IaC modules repo

### ISSUE THREAD

**Issue by PaulGregoryBaker** [mojaloop/project#3970]
## **Goal**:
`As a` technical operations team making use of mojaloop bundled release to deploy
`I want to` have a way of versioning my environment values that I am using to customise my deployment
`so that` have a structured release process through my landscape of environments

**Background:**
Would like to create a way to incorporate versioned custom config values that get combined with environment specific custom config values to define an environment deployment.
The acceptance criteria for this would be something like this:
1. Verify that the change are applied to the IaC modules repo
2. Verify that the versioned release of custom config values exist in an independent repository
3. Verify that the in the IaC modules the version (tag) of the independent config repo can be defined
4. Verify that an IaC pipeline can apply the latest tags and compile and deploy the latest environment configurations

**Acceptance Criteria**:
- [ ] Document the design
- [ ] Review the design with all stakeholders

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by kalinkrustev** [comment]
Implemented in https://github.com/mojaloop/iac-modules/pull/296
Documentation is here https://github.com/mojaloop/iac-modules/blob/main/profiles.md
