### ISSUE TITLE
Test CI/CD pipeline for central-ledger and ml-api-adapter

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#398]
**Goal**:
1. As a Switch
I would like to make sure _the CI/CD pipeline for key central services repos - central-ledger and ml-api-adapter are tested_
to ensure that builds work as expected and releases, deployments can be done as configured (and all phases pass in given circumstances).

**Tasks**:
- [ ] Test CI/CD pipeline to ensure automated tests pass for
  - [ ] central-ledger
  - [ ] ml-api-adapter
- [ ] Test CI/CD pipeline to ensure releases are made as expected for
  - [ ] central-ledger
  - [ ] ml-api-adapter
- [ ] Test CI/CD pipeline to ensure deployments can be done as expected for
  - [ ] central-ledger
  - [ ] ml-api-adapter
- [ ] Fix issues with failures in phases (coverage?)
  - [ ] central-ledger
  - [ ] ml-api-adapter

**Acceptance Criteria**:
- [ ] The central-ledger and ml-api-adapter and configured in CI/CD for
  - [ ] automated tests
  - [ ] Releases and
  - [ ] Deployments

**Dependencies**:
- [ ] None currently

**Accountability**:
- Owner @mdebarros 
- QA/Review @mdebarros

**Comment by lewisdaly** [comment]
@elnyry can we close this one in favour of: https://github.com/mojaloop/project/issues/1107 which soley addresses the deployment step? The rest of this ticket seems out of date to me.

**Comment by elnyry** [comment]
@lewisdaly I thought so as well.. and #1107 is something that we'll do in PI9 anyway..

**Comment by lewisdaly** [comment]
Thanks
