### ISSUE TITLE
Parameterize hard-coded 'switch' ID and harmonize with hub name in all ML services

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#3984]
## **Goal**:
`As an` adopter of Mojaloop building interconnected Mojaloop schemes using proxy

`I would like to` be able to configure unique names for each Mojaloop Scheme

`so that` messages can be routed correctly across the schemes and each of the participants can validate JWS error messages from either scheme

**Acceptance Criteria**:
- [x] Verify that a mojaloop can be configured to have a different identity to ‘switch' 
- [x] Verify that the configured name is used in FSPIOP-Source or FSPIOP-Destination headers where applicable
- [x] Verify that usage of the ‘switch’ name in all services through central-services-shared enums (ENUM.Headers.FSPIOP.SWITCH , ENUM.Http.HeaderResources.SWITCH)  and functions (transformHeaders, initializeCache kafka.proceed) are removed or parameterized
- [x] Verify that the configured name is used in JWS signing where applicable
- [x] Verify that the GP test pass with the hub's identifier not being the default (I.e. not 'switch') using a helm Kubernetes deployment. (OSS)
- [x] The following need to be checked:
  - [x] ALS - fx branch
  - [x] quoting Service - fx branch
  - [x] Central Ledger - FX branch
  - [x] Central Services Shared - main
  - [x] Central Services Stream - main
  - [x] ML API Adapter - fx branch
  - [x] SDK standard components - main
  - [x] SDK Scheme Adapter - main
  - [x] ML core test harness - fx branch
  - [x] Bulk API adapter - main
  - [x] Central Settlement - fx branch
  - [x] Thirdparty API svc - main
  - [x] Transaction Request Service - main
  - [x] Auth Service - main
  - [x] Simulator - main
  - [x] Helm chart - fx branch

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Implement in ALS - fx branch
- [x] Implement in Quoting Service - fx branch
- [x] Implement in Central Ledger - fx branch
- [x] Implement in Central Services Shared - main
- [x] Implement in Central Services Stream - main
- [x] Implement in ML API Adapter - fx branch
- [x] Implement in SDK standard components - main
- [x] Implement in SDK Scheme Adapter - main
- [x] Implement in ML core test harness - fx branch
- [x] Implement in Bulk API adapter - main
- [x] Implement in Central Settlement - fx branch
- [x] Implement in Third-party API svc - main
- [x] Implement in Transaction Request Service - main
- [x] Implement in Auth Service - main branch
- [x] Implement in Simulator - main
- [x] Implement in Helm chart - fx branch
- [x] Implement in ML core test harness - fx branch

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/account-lookup-service/pull/482
- [x] https://github.com/mojaloop/quoting-service/pull/339
- [x] https://github.com/mojaloop/central-services-shared/pull/385/
- [x] https://github.com/mojaloop/central-ledger/pull/1057
- [x] https://github.com/mojaloop/ml-api-adapter/pull/531
- [x] https://github.com/mojaloop/central-settlement/pull/406
- [x] https://github.com/mojaloop/central-services-shared/pull/386
- [x] https://github.com/mojaloop/bulk-api-adapter/pull/109
- [x] https://github.com/mojaloop/transaction-requests-service/pull/103
- [x] https://github.com/mojaloop/simulator/pull/260
- [x] https://github.com/mojaloop/helm/pull/636
- [x] https://github.com/mojaloop/thirdparty-api-svc/pull/94
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/149
- [x] https://github.com/mojaloop/auth-service/pull/135
- [x] https://github.com/mojaloop/oss-core-env/pull/7

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
