### ISSUE TITLE
Re-factor migration scripts into common library

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#399]
**Goal**:
1. As a Switch
I would like to have  _migration scripts in a common library_
so that they can be referenced from either the Central-Ledger or the Central-Settlements services.

**Tasks**:
- [ ] Create new project for "Common Migration Scripts"
- [ ] Move migration scripts for both the Central-Ledger and Central-Settlements 
- [ ] Add any tests if applicable
- [ ] Update Central-Ledger to use the "Common Migration Scripts" lib
- [ ] Update Central-Settlements to use the "Common Migration Scripts" lib

**Acceptance Criteria**:
- [ ] Common Migration Scripts lib that is utilised by Central-Ledger
- [ ] Common Migration Scripts lib that is utilised by Central-Settlements

**Dependencies**:
- [ ] N/A

**Accountability**:
- Owner 
- QA/Review
