### ISSUE TITLE
Enhance Quoting Service to support cross-network proxy routing

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#3991]
## **Goal**:
`As an` adopter of Mojaloop building an inter-scheme scheme

`I want to` enhance quoting service to handle routing of inter-scheme requests
  
`so that` inter-scheme agreements can be made

**Acceptance Criteria**:
- [x] Verify that the standardized Proxy Mapping standard (lib) is used
- [x] Verify that the solution implements the design
- [x] Verify that an Error Code 3201 is generated if the proxy is not available in the cache
- [x] Verify that integration / functional tests are updated to test this functionality
- [x] Verify that the helm changes are made so that this can be deployed.
- [x] Verify that existing GP tests pass after this change

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Add proxy cache lib and config
- [x] Implement change in POST /quotes handler
- [x] Implement change in PUT /quotes/{ID} handler
- [x] Implement change in POST /fxQuotes handler
- [x] Implement change in PUT /fxQuotes/{ID} handler
- [x] Implement change in POST /bulkQuotes handler
- [x] Implement change in PUT /bulkQuotes/{ID} handler
- [x] Add unit tests
- [x] Add integration tests
- [x] Update Helm chart
- [x] Deploy in OSS env and test

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] https://github.com/mojaloop/quoting-service/pull/341
- [ ] https://github.com/mojaloop/helm/pull/638

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
