### ISSUE TITLE
Add kafka and resource charts to performance-troubleshooting-dashboard

### ISSUE THREAD

**Issue by muzammil360** [mojaloop/project#3994]
## **Goal**:
`As a`  developer 

`I want to` see following charts in performance-troubleshooting-dashboard

Kafka: partitions by topic
Kafka: consumers by consumer group
Kafka: Lag by topic
network util by node
disk I/O rate by node
network util by container

`so that` it is easier for me to review this information on a single dashboard

**Acceptance Criteria**:
- [x] all dashboards added

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
