### ISSUE TITLE
make prometheus-remote-write dashboard

### ISSUE THREAD

**Issue by muzammil360** [mojaloop/project#3996]
## **Goal**:
`As a` <developer>

`I want to` add prometheus-remote-write dashboard
  
`so that` operations team can get visibility into performance of remote write.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Medium
**Uncertainty**: Low

---

**Tasks**:
- [x] make the dashboard

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/helm/pull/639

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @muzammil360 
- QA/Review: TBC
