### ISSUE TITLE
Enhance position handler to support proxy obligation tracking

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#3998]
`As an` adopter of Mojaloop building an inter-scheme scheme
`I would like to` have the central ledger service replace DFSP position updates with the proxy representative position update
`So that` inter-scheme proxy ledgers reflect movement of funds through the proxy representative

**Note**: The design of the inter-scheme accounting, means that if for a transfer (either FxTransfer or Transfer) the Debtor and Creditor both are represented by the same proxy; then that transaction should not be accounted for in the ledgers. (To do so would be confusing as the same participant would require a debit and credit at the same time; and the transaction really don’t have anything to do with the scheme involved.)

This story is to ensure that the position handler processes these 0 adjustments by not making an adjustment. In the design diagram attached, this situation only arrises in Scheme A with a cross currency POST transfer message; on both the prepare and fulfill leg.

`KAFKA Message Key = 0 [AccountId]`

**Acceptance Criteria**

- [ ] Verify that in a cross currency POST \transfer where the FXP and the Payee DFSP is being represented by the same proxy, ensure that:

  - [ ] In the Prepare leg, the transfer does not reserved FXP funds in the proxy

  - [ ] In the Fulfil leg, the transfer does not commit Payee DFSP funds in the proxy

- [ ] Verify that the golden path runs and passes.

- [ ] Verify that integration tests exist to test this functionality

Here is a diagram illustrating the issue that occurs in Scheme A.

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
