### ISSUE TITLE
Automate the CI pipeline for central-ledger

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#40]
**Goal**:
As a developer I would like to automate the CI pipeline for central-ledger so that I can shorten the development cycle #40

**Tasks**:
- [x] Migrate CircleCI v1 to CircleCI v2
- [x] Create CircleCI v2 parallel job for Unit Testing
- [x] Create CircleCI v2 parallel job for Integration Testing
- [x] Create CircleCI v2 parallel job for Functional Testing
- [x] Create CircleCI v2 parallel job for Code Coverage Testing
- [x] Automate the upload of Code Coverage results to SonarQube
- [x] Publish build snapshot artefacts to Docker Hub if all tests are successful if there is a tag push to the development branch
- [x] Publish build release artefacts to Docker Hub if all tests are successful if there is a tag push to the master branch

**Acceptance Criteria**:
- [x] Automated build artifacts are published to the respective repository for master (release) and develop (snapshot) pushed tags 
- [x] Automated unit tests for PR validations with results made available
- [x] Automated integration tests for PR validations with results made available
- [x] Automated functional tests for PR validations with results made available
- [x] Automated code coverage tests for PR validations with results made available to sonarQube only on a commit to the master branch

**Dependencies**:
- None currently

**Comment by elnyry** [comment]
LGTM

**Comment by mdebarros** [comment]
PR open for review: https://github.com/mojaloop/central-ledger/pull/42

**Comment by mdebarros** [comment]
Thanks @elnyry

**Comment by mdebarros** [comment]
PR merged into develop branch

**Comment by mdebarros** [comment]
Demo: https://drive.google.com/file/d/1T-i2NAK6uBqbAP1EM6j_Gonsh_kaot2f/view?usp=sharing
