### ISSUE TITLE
Validate the data model of responses, callbacks from the Switch confirm to the specification

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#400]
**Goal**:
As a Switch
I would like to validate _the responses and callbacks from the Switch_
so that they conform to the API Specification.

**Tasks**:
- [ ] Responses for the below calls conform to the API specification
  - [ ] GET /transfers/{ID}
  - [ ] POST /transfers
  - [ ] PUT /transfers/{ID}
  - [ ] PUT /transfers/{ID}/error
- [ ] Callbacks for the below calls conform to the API specification
  - [ ] GET /transfers/{ID}
  - [ ] POST /transfers
  - [ ] PUT /transfers/{ID}
  - [ ] PUT /transfers/{ID}/error

**Acceptance Criteria**:
- [ ] The responses to the calls specified in the API Specification conform to the spec
- [ ] The callbacks to the requests specified in the API Specification conform to the spec

**Dependencies**:
- [ ] Deployment of the ML Switch
- [ ] Availability

**Note**:
The API specification version in this context is v1.0

**Accountability**:
- Owner 
- QA/Review
