### ISSUE TITLE
Re-work errors throughout code-base to be aligned to the pattern lib/error

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#401]
**Goal**:
As a Switch
I would like to validate _re-work errors throughout code-base to be aligned to the pattern lib/error_
for uniformity and so that this helps with error-handling and future enhancements.

**Tasks**:
- [ ] Re-work errors throughout code-base to be aligned to the pattern lib/error
  - [ ] ml-api-adapter
  - [ ] central-ledger
  - [ ] central-settlement

**Acceptance Criteria**:
- [ ] The errors throughout ML codebase are aligned to be under lib/error
- [ ] Add a story to move lib/error to a common library so that it can be re-used by multiple services.

**Dependencies**:
- [ ] Availability

**Accountability**:
- Owner 
- QA/Review

**Comment by elnyry** [comment]
Closing this now as it should be covered by the Event & Error Framework #765 .. @rmothilal @mdebarros , please re-open if this is not addressed in #765
