### ISSUE TITLE
Update license in Mojaloop repos to fix outdated entries referencing BMGF

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#4013]
## **Goal**:
`As a` maintainer of the Mojaloop repositories

`I want to` ensure the license information is up-to-date and references Mojaloop Foundation(Copyright © 2020–2024 )
  
`so that` outdated entries referencing BMGF are updated.

**Acceptance Criteria**:
- [ ] Mojaloop repositories license files reference Mojaloop Foundation instead of BMGF (Copyright © 2020–2024 )

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] update license template to use Mojaloop Foundation(Copyright © 2020–2024) and create pull requests for repositories with outdated license information
- [ ] Ensure PRs are merged. 

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Confirmed for all repos included in Mojaloop releases.

**Comment by elnyry-sam-k** [comment]
completed
