### ISSUE TITLE
Standardize Oracle API and publish

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#4016]
## **Goal**:
`As a` stakeholder

`I want to` standardize th oracle API
  
`so that` implementers can use for their oracle implementations and integrations

**Acceptance Criteria**:
- [ ] Oracle API is standardized
- [ ] Followup stories created if there are any changes required in the existing services (ALS, als-msisdn-oracle-svc...etc)
- [ ] New API is added to api-snippets
- [ ] References are added to mojaloop documentation

**Background**:
As there is no real oracle implementation for MSISDN party type, we recently developed the new service [mojaloop/als-msisdn-oracle-svc](https://github.com/mojaloop/als-msisdn-oracle-svc).
In process of developing and testing the GP using that, found the following gaps.

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
