### ISSUE TITLE
Add useful logging to finance portal backend

### ISSUE THREAD

**Issue by shashi165** [mojaloop/project#4017]
## **Goal**:
`As a` <stakeholder|persona>

`I want to` add useful logging to finance portal backend
  
`so that` I can see which service is being called by actions on finance portal, along with incoming and outgoing payloads, endpoints, headers etc. This information is useful while debugging the finance portal issues

**Acceptance Criteria**:
- [ ] When enabled the logs should have following information, service being called, endpoint, headers, incoming and outgoing payloads

**Complexity**: Low > Should be straight forward to add basic logging

**Uncertainty**: Low > Should be straight forward to add basic logging

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
