### ISSUE TITLE
Ability to select settlement model while settling via finance portal

### ISSUE THREAD

**Issue by shashi165** [mojaloop/project#4019]
## **Goal**:
`As a` stakeholder

`I want to` select settlement model while settling via finance portal
  
`so that` different settlement models can be used as per requirement

**Acceptance Criteria**:
- [ ] provide a list in dropdown on finance portal with available settlement models
- [ ] select appropriate settlement model while creating settlement
- [ ] provide a default settlement model if none is selected

**Complexity**: Medium > Need to add new component to the UI and additional backend calls

**Uncertainty**: Low > Should be straight forward to use a selected settlement model

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
