### ISSUE TITLE
Trx req service: Identify and address deprecations

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#4022]
## **Goal**:
`As a` maintainer of the Mojaloop OSS codebase

`I want to` ensure the [transaction-requests-service](https://github.com/mojaloop/transaction-requests-service) is up-to-date
  
`so that` any underlying (nested) deprecations are identified and addressed

**Acceptance Criteria**:
- [x] Transaction requests service has no known deprecations even in the underlying dependencies or issues are documented in case alternatives cannot be found

**Complexity**: Medium

**Uncertainty**: High

---

**Tasks**:
- [x] Run script for deprecation check (from sdk standard components as reference)
- [x] Identify any deprecations (nested)
- [ ] Identify fixes and implement

**Done**
- [x] Acceptance Criteria pass
- [x] Designs are up-to date
- [x] Unit Tests pass
- [ ] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
