### ISSUE TITLE
quoting-service: json-rules-engine upgrade to address deprecation

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#4023]
## **Goal**:
`As a` maintainer of the Mojaloop OSS codebase

`I want to` ensure the [quoting-service](https://github.com/mojaloop/quoting-service) is up-to-date
  
`so that` any underlying (nested) deprecations are identified and addressed; this story is specific to **json-rules-engine** dependency

**Acceptance Criteria**:
- [X] json-rules-engine dependency is upgraded and all tests passing

**Complexity**: Medium

**Uncertainty**: High

---

**Tasks**:
- [X] Identify fixes and implement
- [X] troulbeshoot and root cause unit tests for
- [X] Add 2 new custom operators to json-rules-engine arrayEqual and arrayNotEqual for backward compatibility as after updates jsonpath-plus in combination to almanac.js setting of wrap:false returns an array instead of a scalar when there is only 1 element in the result.

**Done**
- [X] Acceptance Criteria pass
- [X] Designs are up-to date
- [X] Unit Tests pass
- [X] Integration Tests pass
- [X] Code Style & Coverage meets standards
- [X] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [X] https://github.com/mojaloop/quoting-service/pull/377

## **Follow-up**:
- The PR-377 is open against the minor/iso branch, to make it to main it needs to be merged into minor/iso and then to main.

**Dependencies**:
- N/A

## **Accountability**:
- Owner: Juan Correa
- QA/Review: TBC
