### ISSUE TITLE
ML PI-26: Setup VPN access for oss core dev environments

### ISSUE THREAD

**Issue by shashi165** [mojaloop/project#4024]
## **Goal**:
`As a` DevOps Engineer, contributor

`I want to` have the capability to access Mojaloop core dev/qa environments on AWS using wireguard VPN
  
`so that` I can access mojaloop services deployed and continue with dev/ qa activities

**Acceptance Criteria**:

- [x] install wireguard vpn server on EC2 instance
- [x] access mojaloop services via wireguard vpn client
- [x] create users to team members and ensure access

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @shashi165 
- QA/Review: TBC
