### ISSUE TITLE
Deploy finance portal using "charts" helm charts on default Mojaloop helm deployment

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#4025]
## **Goal**:
`As an` adopter of Mojaloop

`I want to` be able to deploy Mojaloop Finance Portal on top of a Mojaloop helm deployment
  
`so that` I can use the finance portal for Hub management in a demo/dev/qa environment

**Acceptance Criteria**:
- [ ] Mojaloop "charts" to deploy finance portal can be deployed on a default Mojaloop helm deployment
- [ ] For the initial iteration the transfers UI should be available with ability to query for tranfers based on the filters provided

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- [ ] Create a follow item (Epic possibly) to standardize and move charts to Mojaloop "helm"

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
