### ISSUE TITLE
ML PQS: Review FLOSS / Open SSF criteria and create checklist for Mojaloop

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#4027]
## **Goal**:
`As an` adopter

`I want to` have a checklist view of platform quality & security aspects of Mojaloop compared with Open SSF/ FLOSS criteria (here: https://www.bestpractices.dev/en/criteria) 
  
`so that` I can verify the standards Mojaloop has adopted and follows

**Acceptance Criteria**:
- [ ] A checklist with OpenSSF criteria and current state of Mojaloop is captured as a starting point

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
