### ISSUE TITLE
ML PI-26 PQS: Mojaloop libraries deprecation check

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#4028]
## **Goal**:
`As a` maintainer of the Mojaloop OSS codebase

`I want to` ensure that the Mojaloop libraries used in the Mojaloop release are checked for deprecations (and fixed as needed)
  
`so that` any underlying (nested) deprecations are identified and addressed; this story is specific to the libraries listed in the acceptance criteria

**Acceptance Criteria**:
- [x] Core libraries are checked for deprecations and
- [ ] Deprecations found are documented
  - [x]  ml-number
  - [x]  api-snippets
  - [x] database-lib
  - [x] central-services-stream
  - [x] central-services-logger
  - [x] central-services-metrics
  - [x] central-services-health
  - [x] central-services-shared
  - [x]  central-services-error-handling
  - [x]  sdk-standard-components
  - [x]  event-sdk
  - [x]  object-store-lib

**Complexity**: Medium

**Uncertainty**: High

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
