### ISSUE TITLE
[030] Implement API to query positions Part-2 

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#404]
**Goal**:
As a Switch
I would like to _make an API available to query position or an FSP_ 
so that the Position of an FSP can be provided based on user profiles (to be added later)

**Tasks**:
- [x] Sequence Diagram (design) for the API to GET Position of an FSP - [@shashi165]
- [x] ~Implement API to GET Position of an FSP --> Sprint 3.4 [@shashi165]~
- [x] Add the participant validation to the implementation - [@shashi165]
- [x] Tests 
  - [x] Unit tests - [@shashi165]
  - [x] Integration tests - [@shashi165]
  - [x] Code coverage - [@shashi165]
- [x] ~JS Docs - [@shashi165]~

**PRs**:
- [x] https://github.com/mojaloop/central-ledger/pull/134 - [@shashi165]
- [x] https://github.com/mojaloop/docs/pull/77 - [@shashi165]

**Acceptance Criteria**:
- [x] ~An API to query position of an FSP is made available~
- [x] Sequence diagrams are provided to depict the design for the Participant Position API
- [x] Tests that enable automated testing of the API to query position of an FSP are available

**Dependencies**:
- [x] #396

**Accountability**:
- Owner @shashi165 
- QA/Review
