### ISSUE TITLE
Validate the Schema validation rules for /transfers end-point to ensure that they conform to the specification

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#405]
**Goal**:
As a QA engineer
I would like to validate _Schema validation rules_
to ensure that they conform to the specification and don't impose additional constraints or compromise on specified constraints.

**Tasks**:
- [ ] Incoming calls to /transfers for the below calls conform to the API specification
  - [ ] GET /transfers/{ID}
  - [ ] POST /transfers
  - [ ] PUT /transfers/{ID}
  - [ ] PUT /transfers/{ID}/error

**Acceptance Criteria**:
- [ ] The Schema validation rules applied on the Switch are in harmony with those specified in the API Spec

**Dependencies**:
- [ ] Deployment of the ML Switch
- [ ] Availability

**Note**:
The API specification version in this context is v1.0

**Accountability**:
- Owner 
- QA/Review
