### ISSUE TITLE
Streamline DB (postgres) being used by interop-switch for callback URLs, registration process

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#406]
**Goal**:
1. As a Switch
I would like to review _DB use of the interop-switch (for callback URLs, registration)_
so that DB usage can be streamlined (streamlining the deployment process as well)

**Tasks**:
- [ ] Review DB (postgres) being used by interop-switch for callback URLs, registration process
- [ ] Identify solution for streamlining this process (registration, callback URL access)
- [ ] Add stories for implementation of the solution.

**Acceptance Criteria**:
- [ ] A solution to streamline DB usage by interop-switch (to move away from associated postgres DB) is provided.
- [ ] Follow-up stories to complete implementation are added

**Dependencies**:
- [ ] Availability

**Accountability**:
- Owner 
- QA/Review @mdebarros

**Comment by elnyry** [comment]
Callback urls are now registered as part of the on-boarding process of FSPs and are used for callbacks, etc
