### ISSUE TITLE
Demo Prep - Presentation Deck of Phase-2 wrap-up (End-of-PI3)

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#407]
**Goal**:
1. As a contributor
I would like to _draft a presentation slide deck_
to use for the Phase-2 Wrap-up meetings to show demos and drive discussions.

**Tasks**:
- [ ] Confirm on the template to use for Phase-2 wrap-up (end-of-pi3) meetings
- [ ] Identify sections based on the items to be discussed/demonstrated at the event
- [ ] Identify owner for each section
- [ ] Consolidate sections from the owner of each sub-section
- [ ] Review the presentation for uniformity
- [ ] Get the reviews done by stakeholders

**Acceptance Criteria**:
- [ ] A presentation slide deck is drafted that contains all the topics planned to be addressed at the Phase-2 wrap-up onsite meeting
- [ ] This presentation is 
  - [ ] reviewed by the stakeholders
  - [ ] aligns with the Agenda
  - [ ] and is uniform

**Dependencies**:
- [ ] Presentation Template
- [ ] Reviews
- [ ] Each section owner's submission

**Accountability**:
- Owner @elnyry
- QA/Review
