### ISSUE TITLE
[55] Deploy FSP & supporting services needed for end-to-end demo for Phase-2 wrap-up meetings

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#408]
**Goal**:
1. As a contributor
I would like to _deploy FSP services needed for end-to-end demo for Phase-2 wrap-up meetings_
so that transfers can be demonstrated end-to-end using USSD simulators

**Tasks**:
- [x] Initial discussion to identify current status of FSP services [@elnyry]
- [x] Identify whether a deployment for FSP services is needed or verify if a deployment that works 
- [x] Login to the AWS VMs that have the FSP services deployed, reboot services and test USSD end-point [@elnyry]
- [ ] Debug issues with "Send Money" option using USSD [@elnyry]
  - [x] Issue with "User Not Found" now fixed (URL issue, needs https for fsps)
  - [x] Getting HTTP Error on "Send Money" option [In Progress - Murthy confirms this is a known issue, needs a config change, will look at this Friday Eastern Time]
  - [ ] ~HTTP Error got resolved after the new deployment, having issue with date validation~
- [ ] ~Get a P2P transfer working using USSD - Happy Path~

**Acceptance Criteria**:
- [x] A deployment with FSP services that work as expected is available to support the Switch services
- [x] Supporting interop services for this end-to-end setup are deployed working as expected
- [ ] Sanity testing is done for happy path to be demonstrated (others to be demo-ed using postman)

**Dependencies**:
- [ ] Availability of SMEs
- [ ] Time constraints - if major issues to be fixed with FSP services (Reference Implementation)

**Accountability**:
- Owner @ggrg @elnyry
- QA/Review

**Comment by elnyry** [comment]
Reducing estimate as the scope for this changed (just to get the Send Money - P2P, working)

**Comment by elnyry** [comment]
Moving ahead with Postman for this Demo
