### ISSUE TITLE
Add Story, Bug templates to docs

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#409]
**Goal**:
As a contributor
I would like to _add templates for Stories and bugs to the docs_
so that issues can be created to include sections, that may otherwise be missed.

**Tasks**:
- [x] Identify a relevant folder in docs repo to publish templates - Using the [Standards] (https://github.com/mojaloop/docs/tree/master/Standards) folder  [ @elnyry ]
- [x] Add Story template to docs repo [ @mdearros ]
- [x] Add Bug template to docs repo [ @elnyry ]

**Acceptance Criteria**:
- [x] Templates for creating Stories and bugs are confirmed and added to docs in the ML GitHub repo, that help with creating issues.

## **Pull Requests**:
- [x] https://github.com/mojaloop/docs/pull/58
- [x] https://github.com/mojaloop/docs/pull/59

**Dependencies**:
- None currently

**Accountability**:
- Owner @mdebarros  
- QA/Review

**Comment by elnyry** [comment]
PRs merged and closed. Templates added here - https://github.com/mojaloop/docs/tree/develop/Standards
