### ISSUE TITLE
3.01 Settlement Batch processing design - [8] - Part:2

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#411]
**Goal**:
As a Switch
I would like to _design Settlement Batch processing_
so that implementation for Settlements with batching can be done
- Option 1: prepare handler storing the settlement ID & putting it into the LIME Meta data;
- Option 2: Update the transfers as a DB write up on settlement)

**Tasks**:
- [x] ~Decide on the approach for Settlement Batch processing~
- [x] Alter DB schema model to cater for Settlement Batch processing [@ggrg]
- [x] Make corrections to swagger definition file [@ggrg]
- [x] Design Settlement Batch processing
  - [x] Sequence diagrams
    - [x] ~First draft of GET:: getSettlementWindowById (6.1.1.) [@HenkKodde]~
      - [x] Update GET:: getSettlementWindowById (6.1.1) [@ggrg] [**link**](https://github.com/mojaloop/docs/tree/develop/CentralServices/seq_diagrams/seq-setwindow-6.1.1.svg)
      - [x] Review for GET:: getSettlementWindowById (6.1.1.) is done
    - [x] ~First draft of POST:: closeSettlementWindow (6.1.2.) [@HenkKodde]~
      - [x] Update POST:: closeSettlementWindow (6.1.2.) [@ggrg] [**link**](https://github.com/mojaloop/docs/tree/develop/CentralServices/seq_diagrams/seq-setwindow-6.1.2.svg)
      - [x] Review for POST:: closeSettlementWindow (6.1.2.) is done
    - [x] ~GET:: getSettlementWindowByParams (6.1.3.) [@HenkKodde]~
      - [x] Update GET:: getSettlementWindowsByParams (6.1.3.) [@ggrg] [**link**](https://github.com/mojaloop/docs/tree/develop/CentralServices/seq_diagrams/seq-setwindow-6.1.3.svg)
      - [x] Review for GET:: getSettlementWindowsByParams (6.1.3.) is done
    - [x] ~First draft of POST:: settlementEventTrigger (6.2.1.)[@HenkKodde, @ggrg]~
      - [x] Update POST:: createSettlement (6.2.1) [@ggrg] [**link**](https://github.com/mojaloop/docs/tree/develop/CentralServices/seq_diagrams/seq-settlement-6.2.1.svg)
      - [x] Review for POST:: createSettlement (6.2.1.) is done
    - [x] GET:: getSettlementsByParams (6.2.2.) [@ggrg] [**link**](https://github.com/mojaloop/docs/tree/develop/CentralServices/seq_diagrams/seq-settlement-6.2.2.svg)
      - [x] Review for GET:: getSettlementsByParams (6.2.2) is done
    - [x] GET:: getSettlementBySettlementParticipantAccount (6.2.3.) [@ggrg] [**link**](https://github.com/mojaloop/docs/tree/develop/CentralServices/seq_diagrams/seq-settlement-6.2.3.svg)
      - [x] Review for GET:: getSettlementBySettlementParticipantAccount (6.2.3) is done
    - [x] GET:: getSettlementById (6.2.4.) [@ggrg] [**link**](https://github.com/mojaloop/docs/tree/develop/CentralServices/seq_diagrams/seq-settlement-6.2.4.svg)
      - [x] Review for GET:: getSettlementById (6.2.4) is done
    - [x] PUT:: updateSettlementById (6.2.5.) [@ggrg] [**link**](https://github.com/mojaloop/docs/tree/develop/CentralServices/seq_diagrams/seq-settlement-6.2.5.svg)
      - [x] Review for PUT:: updateSettlementById (6.2.5.) is done

**Acceptance Criteria**:
- [x] Sequence diagrams for the below resource+methods are designed and reviewed
  - [x] GET:: getSettlementWindowById (6.1.1.)
  - [x] POST:: closeSettlementWindow (6.1.2.)
  - [x] GET:: getSettlementWindowsByParams (6.1.3.)
  - [x] POST:: createSettlement (6.2.1.)
  - [x] GET:: getSettlementsByParams (6.2.2.)
  - [x] GET:: getSettlementBySettlementParticipantAccount (6.2.3.)
  - [x] GET:: getSettlementById (6.2.4.)
  - [x] PUT:: updateSettlementById (6.2.5.)

**PRs**:
- [x] https://github.com/mojaloop/central-ledger/pull/125
- [x] https://github.com/mojaloop/docs/pull/64
- [x] https://github.com/mojaloop/central-settlement/pull/13
- [x] https://github.com/mojaloop/docs/pull/65

**Dependencies**:
- [x] Preceding item #333 

**Accountability**:
- Owner @wdcmb 
- QA/Review **DA**

**Comment by elnyry** [comment]
Each of the sequence diagrams coming to about '5' points with the first draft, then internal review, then DA review --> so bumped up the estimate (actually coming to 30)
