### ISSUE TITLE
Removing Transfer Handler from central-ledger - Part:1

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#412]
**Goal**:
As a Switch
I would to _make sure any redundant services are removed_
so that the processing in the Switch is more efficient and any unnecessary hops and handlers are removed.

**Tasks**:
- [ ] Identify changes needed to remove transfer handler from central-ledger
  - [ ] List design changes needed
  - [ ] List documentation changes needed
  - [ ] Assess implementation changes needed
- [ ] Update overview architecture diagram to reflect changes
- [ ] Update sequence diagrams in [docs](https://github.com/mojaloop/docs/tree/develop/CentralServices/seq_diagrams) repo to ensure these changes are reflected (removing transfer handler)
- [ ] DA to review changes (and approve)
- [ ] Create follow-up stories to complete this process

**Acceptance Criteria**:
- [ ] The overview architecture without Transfer Handler is proposed with
  - [ ] Sequence diagram changes and is
  - [ ] approved by the DA
- [ ] Follow-up stories are created based on the changes needed and are listed.

**Dependencies**:
- [ ] None currently

**Accountability**:
- Owner @rmothilal 
- QA/Review

**Comment by elnyry** [comment]
Covered in #478
