### ISSUE TITLE
[015] 3.07.02 Implement the DAO layer for Settlement Windows - 2

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#413]
**Goal**:
As a Switch 
I would like the _DAO layer for Settlement Windows be Implemented_
so that Settlement Windows functionality can be supported by the Database

**Tasks**:
- [x] ~Implement DAO layer for Settlement Windows (only implement the methods specified in the design)~
  - [x] ~Create DAO directory and files structure [@vgenev, @bothadeon]~
  - [x] ~Connect database to the server.js [@vgenev, @bothadeon]~
  - [x] ~Add  enumerations from the DB to the server.app.enums object [@vgenev, @bothadeon]~
  - [x] ~Add DAO methods for GET:: getSettlementWindow (6.1.1.)  [@vgenev, @bothadeon]~
    - [x] Align the DAO to the to the latest diagram (6.1.1.)   [@vgenev, @bothadeon, @HenkKodde]
    - [x] ReAlign the DAO to the to the latest diagram (6.1.1.) [@vgenev]
  - [x] ~Add DAO methods for GET:: getSettlementWindowByParams (6.1.3.)  [@vgenev, @bothadeon]~
    - [x] Align the DAO to the to the latest diagram (6.1.3.)   [@vgenev, @bothadeon, @HenkKodde]
    - [x] ReAlign the DAO to the to the latest diagram (6.1.3.) [@vgenev]
  - [x] ~Add  enumerations from the DB server cache [@vgenev]~
  - [x] ~Add DAO methods for POST:: closeSettlementWindow (6.1.2.) [@vgenev]~
    - [x] Align the DAO to the to the latest diagram (6.1.2.)   [@vgenev, @bothadeon, @HenkKodde]
    - [x] ReAlign the DAO to the to the latest diagram (6.1.2.) [@vgenev]
- [ ] Error Handling
- [ ] Tests
  - [ ] Unit tests
  - [ ] Integration tests
  - [ ] Code coverage

**Acceptance Criteria**:
- [x] The DAO layer necessary for Settlement Windows functionality is implemented
- [x] The implementation aligns with the design

**PR**s:
- [ ] https://github.com/mojaloop/central-settlement/pull/14

**Dependencies**:
- [x] #327 
- [x] #328 
- [x] #332
- [x] #333 

**Notes**:
- [x] Preceding item #394 

**Accountability**:
- Owner  [@bothadeon]
- QA/Review @wdcmb

**Comment by HenkKodde** [comment]
PR raised - https://github.com/mojaloop/central-settlement/pull/14

**Comment by elnyry** [comment]
Follow-up story #431
