### ISSUE TITLE
3.07.01 Implement the DAO layer for Settlements - 2

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#414]
**Goal**:
As a Switch 
I would like the _DAO layer for Settlements be Implemented_
so that Settlements functionality can be supported by the Database

**Tasks**:
- [x] Implement DAO layer for Settlements (only implement the methods specified in the design)
   - [x] Implement DAO(6.2.1) - GET: getSettlementsByParams. [@bothadeon, @HenkKodde]
   - [x] ~Implement DAO - POST: postSettlementEventTrigger. [@vgenev]~
       - [x] re-align DAO to Swagger and design(6.2.1) - POST: postSettlementEventTrigger. [@vgenev, @HenkKodde]
   - [x] Implement DAO - Investigate Knex raw in query builder to speed up dev [@bothadeon]
   - [x] Implement DAO(6.2.2) - GET: getSettlementsByParams. [@ggrg] ~ Not priority
   - [x] Implement DAO(6.2.3) - GET: getSettlementBySettlementParticipantAccount. [@HenkKodde @vgenev ] ~ Not priority
   - [x] Implement DAO(6.2.4) - GET: getSettlementsById. [@bothadeon @HenkKodde @vgenev]
       - [x] re-align DAO to Swagger and design - GET: getSettlementsById. [@HenkKodde @vgenev]
   - [x] Implement DAO(6.2.5) - PUT: updateSettlementById. [@ggrg]
- [ ] ~Unit tests~
- [ ] ~Integration tests~
- [ ] ~Code coverage~

**Acceptance Criteria**:
- [x] The DAO layer necessary for Settlements functionality is implemented
- [x] The implementation aligns with the design and support the API calls
  - [x] GET Settlements

**Dependencies**:
- [x] #327 
- [x] #328 
- [x] #332
- [x] #333 
- [x] Preceded by #335 
- [x] Follow-up story #445

**Accountability**:
- Owner 
- QA/Review @wdcmb
