### ISSUE TITLE
[010] 3.08 Implement the settlement window API - 2

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#415]
**Goal**:
As a Switch
I would like to have the _settlement window closure API implemented_
so that the Settlement window closure API is implemented as designed

**Tasks**:
- [x] ~create HAPI plugin for the Central-Services Logger to be used within server.log or request.server.log methods [@vgenev, @bothadeon]~
- [x] ~Implement the settlement window closure API~
  - [x] ~GET settlementWindow by Id [@vgenev, @bothadeon]~
    - [x] Align the response to the latest diagram  [@vgenev, @bothadeon, @HenkKodde]
    - [x] Re-Align the response to the latest diagram [@vgenev]
  - [x] ~GET settlementWindow by filters [@vgenev, @bothadeon]~
    - [x] Align the response to the latest diagram  [@vgenev, @bothadeon, @HenkKodde]
    - [x] Re-Align the response to the latest diagram  [@vgenev]
  - [x] ~POST settlementWindow to close it [@vgenev]~
    - [x] Align the response to the latest diagram  [@vgenev, @bothadeon, @HenkKodde]
    - [x] Re-Align the response to the latest diagram  [@vgenev]
- [x] ~Add settlement data to seed script  [@bothadeon]~
- [ ] ~Error Handling~
- [ ] ~Unit Tests~
- [ ] ~Integration Tests~
- [ ] ~Code coverage~
- [x] Identify if any changes are needed to the design and make necessary changes

**PR**s:
- [ ] https://github.com/mojaloop/central-settlement/pull/14

**Acceptance Criteria**:
- [ ] The settlement window closure API is implemented
- [ ] The implementation aligns with the design and any issues identified are brought up so that the design is updated.

**Dependencies**:
- [x] #327
- [x] Preceding item #347 

**Accountability**:
- Owner @bothadeon 
- QA/Review @bothadeon @wdcmb

**Comment by elnyry** [comment]
PR: https://github.com/mojaloop/central-settlement/pull/14

**Comment by elnyry** [comment]
Follow-up story #431
