### ISSUE TITLE
3.09 Implement the settlement API - 2

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#416]
**Goal**:
As a Switch
I would like to have the _settlement API implemented_
so that the Settlement window query API is implemented as designed

**Tasks**:
- [x] ~Implement settlements API - POST: /settlements - post settlement event trigger(6.2.1) [@vgenev]~
  - [x] Re-Align the response to the latest diagram [@vgenev @HenkKodde @rmothilal ]
- [x] ~Implement settlements API - GET: getSettlementsByParams(6.2.2). [@bothadeon @vgenev]~
  - [x] Re-Align the response to the latest diagram [@ggrg]
- [x] Implement settlements API - GET: getSettlementBySettlementParticipantAccount(6.2.3). [@HenkKodde @vgenev]
- [x] ~Implement settlements API - GET: /settlements/{id}(6.2.4) [@bothadeon @vgenev @HenkKodde]~
  - [x] Re-Align the response to the latest diagram [@vgenev @HenkKodde]
- [x] Implement settlements API - PUT: /settlements/{id} (6.2.5)[@bothadeon @vgenev @rmothilal @ggrg]
- [ ] ~Unit tests~
- [ ] ~Integration tests~
- [ ] ~Code coverage~

**Dependencies**:
- [x] #327
- [x] Preceded by #348 
- [x] Follow-up story #445

**Accountability**:
- Owner [@vgenev]
- QA/Review
