### ISSUE TITLE
[00] 5.2.11-01 Create Snapshot/Releases for 3.4.0

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#417]
**Goal**:
As a developer
I would like to _Create Snapshot/Releases for 3.4.0_
so that artefacts are published and deployments can be done.

**Tasks**:
- [x] Create new helm-deploy branch for PI3.4 [ @mdebarros ]
- [x] Configure new helm-deploy branch for PI3.4 [ @mdebarros ]
- [x] Create/Publish Snapshot/Releases for 3.4.0 for ML API
- [x] Create/Publish Snapshot/Releases for 3.4.0 for Central Ledger [ @mdebarros ]
- [x] Configure PI3.4 Callback URIs for ML API [ @mdebarros ] 
- [x] Deploy PI3.4 release to AWS K8s cluster [ @mdebarros ]
- [x] Test helm-deploy branch for PI3.4

**Acceptance Criteria**:
- [x] Snapshots/Releases for 3.4.0 created on GitHub for ML API
- [x] Snapshots/Releases for 3.4.0 created on GitHub for Central Ledger
- ~Snapshots/Releases for 3.4.0 created on DockerHub for ML API~
- [x] Snapshots/Releases for 3.4.0 created on DockerHub for Central Ledger
- [x] Snapshots/Releases for 3.4.0 deployed to `mojatest` namespaces on AWS K8s phoenix environment
- [x] Helm-deploy config and documentation created for PI3.4

**Dependencies**:
- [x] Relevant PRs are merged to develop so that codebase can be deployed.
- [x] Mojaloop Test Harness Environment Setup

**Notes**:
- No 3.4.0 Snapshot/Release for ML API required since no changes have been made since 3.3.2-snapshot
- A release/3.4.0-snapshot branch created for ML API to accommodate any bug fixes
- Deployment config/commands documented: https://github.com/mojaloop/deploy-config/tree/deploy/PI3.4/mojaloop

**Accountability**:
- Owner @mdebarros 
- QA/Review @sri-miriyala

**Comment by mdebarros** [comment]
1. Created release for Central Ledger: https://github.com/mojaloop/central-ledger/releases/tag/v3.4.0-snapshot

**Comment by mdebarros** [comment]
Waiting on @sri-miriyala to complete the Mojaloop Test Harness environment setup.

**Comment by mdebarros** [comment]
Deployments documented in the following repo/branch: https://github.com/mojaloop/helm-deploy-config/tree/deploy/PI3.4/mojaloop

**Comment by mdebarros** [comment]
Verified Golden path with @sri-miriyala 20180821 @ approximately 17h00 BS:
- Transfer Prepare Request Successful
- Transfer Fulfil Request Successful

**Comment by sri-miriyala** [comment]
@mdebarros, Yes... this can be closed.
