### ISSUE TITLE
Setup helm chart for central-settlement

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#418]
**Goal**:
As a Switch
I would like to _setup helm charts for the central-settlement component_
so that the central-settlement service can be deployed (automatically) using helm.

**Tasks**:
- [x] Create Dockerfile in the central-settlement repo [ @mdebarros ]
- [x] Create Central-Settlement v3.4.0-snapshot release [ @mdebarros ]
- [x] Setup helm chart for central-settlement [ @mdebarros ]
- [x] Test Helm chart deployment [ @mdebarros ]
----
- [ ] Create Central-Settlement v3.5.0-snapshot release [ @mdebarros - 20180722 - waiting on blockers ]
- [ ] Configure Central-Settlements helm values for Central-Settlements
- [ ] Configure Central helm values for Central-Settlements
- [ ] Re-align helm charts for Central-Settlements configs
- [ ] Test Helm chart deployment

**Acceptance Criteria**:
- [ ] A helm chat for central-settlement component is created that facilitates the deployment of central-settlement service.

**Dependencies**:
- [ ] #411 [ BLOCKER ]
- [ ] #414 [ BLOCKER ]
- [ ] #416 [ BLOCKER ]

**Accountability**:
- Owner @mdebarros 
- QA/Review Dev-Team
