### ISSUE TITLE
Setup helm chart for timeout handler

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#419]
**Goal**:
As a Switch
I would like to _setup helm chart for the timeout handler component_
so that the timeout handler service can be deployed (automatically) using helm.

**Tasks**:
- [ ] Create Dockerfile in the timeout handler repo
- [ ] Update new Helm values for Timeout Handler config [@mdebarros - BLOCKED]
- [ ] Create new Helm Chart release for 3.5.0 to include Timeout Handler [@mdebarros]
- [ ] Setup helm chart for timeout handler
- [ ] Configure timeout handler helm values for timeout handler
- [ ] Configure Central helm values for timeout handler
- [ ] Re-align helm charts for timeout handler configs
- [ ] Test Helm chart deployment

**Pull Requests**:
- [ ] https://github.com/mojaloop/helm/pull/81 [ Blocked: Pending Build of 3.5.0 Central Ledger to test Timeout Handler ]

**Acceptance Criteria**:
- [ ] A helm chart for timeout handler component is created that facilitates the deployment of central-timeout service.

**Dependencies**:
- [ ] #314 

**Accountability**:
- Owner @mdebarros 
- QA/Review Dev-Team
