### ISSUE TITLE
Fixing bugs in ml-api-adapter for end-to-end transfers to work (on 3.4 deployment)

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#421]
**Goal**:
As a Switch
I would like to _fix critical bugs in ml-api-adapter (and central-ledger)_
that were uncovered as part of QA activities
so that end-to-end transfers can work as expected without issues

**Tasks**:
- [x] Fix bug (content-length header issue) https://github.com/mojaloop/ml-api-adapter/issues/34 [ @mdebarros - 20180823 ]
- [x] Fix bug (Error callback URL issue) https://github.com/mojaloop/ml-api-adapter/issues/33 [ @mdebarros - 20180823 ]
- [x] Confirmation on the fixes  https://github.com/mojaloop/ml-api-adapter/issues/33 &  https://github.com/mojaloop/ml-api-adapter/issues/34
- [x] Fix bug (Instructions on setting up interop-switch, ml-api-adapter) https://github.com/mojaloop/helm/issues/80 [ Blocked by #418 ]
- [x] Redeploy 3.4 code-base with fixes (hotfixes) [ @mdebarros - 20180824 ]

**Acceptance Criteria**:
- [x] Critical bugs uncovered during QA using the 3.4 deployment are fixed so that end-to-end transfers can function as expected
- [x] Confirmation/verification that the issues have been fixed.

**Dependencies**:
- [x] Triaging done to assign severity/priority
- [x] #418 

**Accountability**:
- Owner @mdebarros 
- QA/Review

**Comment by elnyry** [comment]
Blocked on #418
