### ISSUE TITLE
Fix issue with /documentation end-point for Admin API on K8s (central-ledger #114)

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#423]
**Goal**:
As a Switch
I would like to _fix the issue with /documentation resource on central admin services_
so that the correct Swagger spec that reflects admin/operational functionality of the Switch can be rendered and provide documentation

**Tasks**:
- [x] Fix issue with /documentation end-point for Admin API on K8s
- [x] Deploy fix
- [x] Confirm issue is fixed

**Acceptance Criteria**:
- ~The /documentation resource for admin functionality shows the correct Swagger spec and serves as documentation for admin/operational functionality.~
- [x] /documentation resource for API functionality shows the correct Swagger spec and serves as documentation for admin/operational functionality.

**Dependencies**:
- [x] Link to the bug - https://github.com/mojaloop/central-ledger/issues/114
- [x] https://github.com/mojaloop/project/issues/600

**PR**:
- [x] https://github.com/mojaloop/helm/pull/138

**Accountability**:
- Owner @mdebarros 
- QA/Review Dev-Team

**Comment by mdebarros** [comment]
@sri-miriyala please test this on release 5.1.0.

**Comment by elnyry** [comment]
works fine now

**Comment by sri-miriyala** [comment]
This is working as per v5.1.1 with the below endpoint.
http://test-central-ledger.mojaloop.live/documentation

<img width="1423" alt="screen shot 2019-02-07 at 2 19 07 pm" src="https://user-images.githubusercontent.com/38143240/52436955-a1ae2c80-2ae3-11e9-852a-2d2b7d213126.png">

Hence closing.
