### ISSUE TITLE
Hard-coded values are looked up using a common enum

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#427]
## **Goal**:
As a `Code Owner` I want to `ensure that all hard-coded values are looked up using a common enum` so that `changes to the hard-coded values are maintainability and improve overall QA`

**Tasks**:
- [ ] TBD [ @? ]

**Acceptance Criteria**:
- [ ] All hard-coded values are located in a Central Common Shared Lib Enum
- [ ] Central-Ledger utilises the Central Common Shared Lib Enum
- [ ] Central-Settlements utilises the Central Common Shared Lib Enum
- [ ] ML-API-Adapater utilises the Central Common Shared Lib Enum

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @mdebarros
