### ISSUE TITLE
Fix for bug - "seq-prepare-1.1.1.a update required for spelling and publishing event detail #69"

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#429]
**Goal**:
As a Switch
I would like to _fix errors in designs (currently issue: [69](https://github.com/mojaloop/docs/issues/69) in docs)_
so that the sequence diagrams are up-to-date with implementation and have known issues resolved.

**Tasks**:
- [x] Fix issue: [69](https://github.com/mojaloop/docs/issues/69) from docs and raise PR
- [x] Review PR and merge.

**Acceptance Criteria**:
- [x] The fix for the bug: 69 (under docs) is fixed (reviewed and changes merged)

**PRs**:
- [x] https://github.com/mojaloop/docs/pull/71

**Dependencies**:
- [ ] None currently

**Accountability**:
- Owner @elnyry 
- QA/Review

**Comment by elnyry** [comment]
Raised PR with the fix - https://github.com/mojaloop/docs/pull/71
