### ISSUE TITLE
Align the Sequence Diagram names with the title and description

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#430]
## **Goal**:
As a Developer I want to make an association between the sequence diagram and the file descriptor so that I can easily find what I am looking for in terms of a design document

**Tasks**:
- [x] Fix the 3 listed mismatches in the raised Bug

**Acceptance Criteria**:
- [ ] Designs are up-to date in therms of the file name and sequence diagram name

## **Pull Requests**:
- [ ] https://github.com/mojaloop/docs/pull/74

## **Follow-up**:
- N/A

**Dependencies**:
- mojaloop/docs#70

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
PR - https://github.com/mojaloop/docs/pull/74
