### ISSUE TITLE
[010, 015] 3.08 Add tests settlement window API, DAO layer - Part3

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#431]
**Goal**:
As a Switch
I would like to have the tests for _settlement window closure API and DAO layer for Settlements windows, implemented_
so that the Settlement window closure API has automated tests against the implementation

**Tasks**:
- [ ] Error Handling
  - [ ] settlement window API
  - [ ] DAO Layer for Settlement windows
- [ ] Unit Tests
  - [ ] settlement window API
  - [ ] DAO Layer for Settlement windows
- [ ] Integration Tests
  - [ ] settlement window API
  - [ ] DAO Layer for Settlement windows
- [ ] Code coverage
  - [ ] settlement window API
  - [ ] DAO Layer for Settlement windows

**PR**s:
- [ ] 

**Acceptance Criteria**:
- [ ] The Unit, Integration tests for settlement window closure API is implemented
- [ ] PRs for the tests with CC data are reviewed, approved and merged to develop

**Dependencies**:
- [x] #415 
- [x] #413

**Accountability**:
- Owner @vgenev @HenkKodde 
- QA/Review @wdcmb
