### ISSUE TITLE
Fulfil Handler to cater for Error Handling Scenarios

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#432]
## **Goal**:
As a <stakeholder> I want to <action> so that <reason>

**Tasks**:
- [ ] TBD [ @? ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @mdebarros

**Comment by elnyry** [comment]
We have this one - https://github.com/mojaloop/project/issues/311 for fulfils failures and #312 for prepares failures.. 

Still should be ok, if they're duplicates we can close one
