### ISSUE TITLE
[30] Sequence diagram (Design) for handling of notifications for duplicate Prepare requests

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#433]
**Goal**:
As a Switch 
I would like to _make sure designs are present/updated for notifications of duplicate prepare requests_
so that implementation and design are aligned

**Tasks**:
- [x] Document design for notifications/callbacks for duplicate prepare requests - Sequence diagram
- [x] Design to be reviewed and merged to docs

**Acceptance Criteria**:
- [x] The Design for notifications of duplicate prepare requests is added to the sequence diagrams set

**Dependencies**:
- [x] Check to see if this can be used - https://github.com/mojaloop/docs/blob/develop/CentralServices/seq_diagrams/seq-prepare-1.1.4.a.svg

**PRs**:
- [x] https://github.com/mojaloop/docs/pull/101

**Accountability**:
- Owner 
- QA/Review
