### ISSUE TITLE
Create Snapshot/Releases for 3.5.1

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#434]
**Goal**:
As a developer
I would like to _Create Snapshot/Releases for 3.5.1_
so that artefacts are published and deployments can be done.

**Tasks**:
- [x] Create new helm-deploy branch for release PI3.5.1 [ ]
- [x] Configure new helm-deploy branch for release PI3.5.1 [ ]
- [x] Create/Publish Snapshot/Releases for release v3.5.1 Central Ledger (include SettlementWindow asign in Fulfil Handler) [ ]
- [x] Create/Publish Snapshot/Releases for release v3.5.0 Central Settlement [ ]
- [x] Deploy PI3.5.1 release to AWS K8s cluster [ ]
- [x] Test helm-deploy branch for v3.5.1 [ ]

**Acceptance Criteria**:
- [ ] Snapshots/Releases for v3.5.1 created on DockerHub for Central Ledger
- [ ] Snapshots/Releases for v3.5.0 created on DockerHub for Central Settlement
- [ ] Snapshots/Releases for v3.5.1 deployed to `mojatest` namespaces on AWS K8s phoenix environment

**Dependencies**:
- [ ] Relevant PRs are merged to develop so that codebase can be deployed

**Accountability**:
- Owner @mdebarros 
- QA/Review
