### ISSUE TITLE
Fulfil handler to assign the settlement window

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#435]
**Goal**:
As a Switch
I would like to assign _settlement windows for transfers_
so that they cater for processing of Settlements

**Tasks**:
- [x] Fulfil Handler to assign Settlement windows to transfers [@rmothilal, @ggrg]
- [x] Test Settlements functionality to ensure this functionality helps Settlements processing [@rmothilal]
- [x] Unit tests [@rmothilal]
- [ ] ~Integration tests~

**Acceptance Criteria**:
- [x] Fulfil Handler of the central services is able to assign Settlement windows to transfers which enables Settlements functionality to be provided

**Dependencies**:
- [x] None currently

**Accountability**:
- Owner @rmothilal 
- QA/Review @mdebarros
