### ISSUE TITLE
Need to create a new settlement window at initialization of the system

### ISSUE THREAD

**Issue by HenkKodde** [mojaloop/project#437]
**Goal**:
As a Switch 
I need to ensure that _a settlement window exists in an 'OPEN' STATE during the initialization process of central ledger_
so that transfers can be assigned a window.
(If the settlement window is not available, one needs to be created with an STATE of 'OPEN'.)

**Tasks**:
- [x] Update the SEEDS in Central Services;
   - [x] Verify if a settlement window exists
   - [x] If a settlement window exists - ensure the STATE is 'OPEN
   - [x] If a settlement window does not exists, or the STATE is not 'OPEN', create a new settlement window with an 'OPEN' STATE.
- [x] Tests
  - [x] Unit tests
  - ~[ ] Integration tests~
  - ~[ ] Code coverage~

**Acceptance Criteria**:
- [x] On the Switch, at any given point of time
  - [x] a new Settlement window is created with an OPEN State 
  - [x] If a Settlement window in an OPEN state exists, another new window cannot be created
**Dependencies**:
- None currently

**PR**
 - [x] https://github.com/mojaloop/central-ledger/pull/133

**Accountability**:
- Owner 
- QA/Review @wdcmb

**Comment by millerabel** [comment]
Consider closing “stale settlement windows” discovered upon startup...

A stale window is one that is Open;
It has been open for longer than the permitted intraday duration;
It has at least one committed transaction.

The stale window should be closed, submitted for settlement, and a new window opened.

There may be corner cases here, such as a stale settlement window with no transactions, or reserved transfers assigned to the stale window but that have not committed and have not expired. These require careful thought, though not necessarily special handling. 

— Miller

On Sep 3, 2018, at 11:49 AM, HenkKodde <notifications@github.com> wrote:

As part of the initialisation of the system, the process need to insure a settlement window exist in an 'OPEN' state. If the settlement window is not available, one needs to be created.
