### ISSUE TITLE
Fix updateSettlementById issues (MdB 12, central-settlement PR 20)

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#439]
**Goal**:
As a Switch 
I would like to _make updateSettlementById process efficient_
so that implementation and design are aligned

**Tasks**:
- [x] Validation of payload Accounts against Participants [@ggrg]
- [x] Resolve technical debt (marked as TODO) [@ggrg]
  - [x] use of lodash.deepClone() instead of JSON.parse(JSON.stringify ...)) => [PoC](http://jsben.ch/13YKQ) [@ggrg]
  - [x] clean object properties on initialisation (remove deletes) [@ggrg]
  - [x] settlementStateChange insert and settlement update should use object [@ggrg]
- [x] Use transaction for the entire process [@ggrg]
- [x] Test endpoint for negative scenarios and fix found issues [@ggrg]
- [ ] ~Unit tests~
- [x] Update design [6.2.5.](https://github.com/mojaloop/docs/blob/develop/CentralServices/seq_diagrams/seq-settlement-6.2.5.svg) to match implementation [@ggrg]

**Acceptance Criteria**:
- [ ] updateSettlementById working for all scenarios and matching design

**Dependencies**:
- None currently

**Accountability**:
- Owner @ggrg
- QA/Review

**Pull requests**:
- [x] https://github.com/mojaloop/central-settlement/pull/21
- [ ] https://github.com/mojaloop/docs/pull/75
