### ISSUE TITLE
Testing API to query positions Part-2

### ISSUE THREAD

**Issue by shashi165** [mojaloop/project#444]
**Goal**:
As a Switch
I would like to _make an API available to query position or an FSP_ 
so that the Position of an FSP can be provided based on user profiles (to be added later)

**Tasks**:
- [ ] ~Sequence Diagram (design) for the API to GET Position of an FSP~
- [x] Implement API to GET Position of an FSP --> Sprint 3.4 [@shashi165]
- [ ] ~Tests~
  - [ ] ~Unit tests~
  - [ ] ~Integration tests~
  - [ ] ~Code coverage~
- [x] JS Docs

**Acceptance Criteria**:
- [x] An API to query position of an FSP is made available

**Dependencies**:
- [x] Follow-up item #404

**PR**:
- [x] https://github.com/mojaloop/central-ledger/pull/120

**Accountability**:
- Owner @ggrg 
- QA/Review

**Comment by shashi165** [comment]
This was a duplicate of #404
