### ISSUE TITLE
Unit tests for central-settlement - I

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#445]
**Goal**:
As a contributor 
I would like the write unit tests against the implementation of central-settlement
so that unit tests can be automated and run as part of the CI/CD pipeline

**Tasks**:
- [x] Initialize .test.js files tree structure to facilitate collaboration [@ggrg] [PR 23](https://github.com/mojaloop/central-settlement/pull/23)
- [x] Write unit tests for implemented functionality
  - [x] test/unit/domain/settlement/index.test.js [@ggrg]
    - [x] 83.61% Statements, 80.39% Branches, 91.67% Functions, 83.19% Lines [@ggrg]
    - [x] 100% Statements, 100% Branches, 100% Functions, 100% Lines [@ggrg]
  - [x] test/unit/domain/settlementWindow/index.test.js [@ggrg]
  - [x] test/unit/handlers/settlements/.../participants/.../accounts/{accountId}.test.js [@vgenev]
  - [x] test/unit/handlers/settlements/{settlementId}/participants/{participantId}.test.js [@vgenev]
  - [x] test/unit/handlers/settlements/{id}.test.js [@vgenev]
  - [x] test/unit/handlers/settlementWindows/{id}.test.js [@vgenev]
  - [x] test/unit/handlers/settlements.test.js [@vgenev]
  - [x] test/unit/handlers/settlementWindows.test.js [@vgenev]
  - [x] test/unit/models/lib/enums.test.js [@ggrg]
  - [x] test/unit/models/settlement/facade.test.js [@ggrg]
    - [x] putById covered to 100% and 33 asserts added [@ggrg]
    - [x] getById covered to 100% and 5 asserts added [@ggrg]
    - [x] getByParams covered to 100% and 4 asserts added [@ggrg]
    - [x] knexTriggerEvent covered to 100% and 3 asserts added [@ggrg]
    - [x] spc.getByListOfIds covered to 100% and 5 asserts added [@ggrg]
    - [x] spc.getAccountsInSettlementByIds covered to 100% and 5 asserts added [@ggrg]
    - [x] spc.getParticipantCurrencyBySettlementId - 100% and 5 asserts [@ggrg]
    - [x] spc.getAccountById covered to 100% and 5 asserts added [@ggrg]
    - [x] spc.getAccountsByListOfIds covered to 100% and 5 asserts added [@ggrg]
    - [x] ssw.getWindowsBySettlementIdAndAccountId - 100% and 9 asserts [@ggrg]
    - [x] ssw.getWindowsBySettlementIdAndParticipantId - 100% and 9 asserts [@ggrg]
    - [x] src/models/settlement/facade.js covered to 100% by 238/238 statements, 67/67 branches, 35/35 functions, 227/227 lines and 88 tests [@ggrg]
  - [x] test/unit/models/settlement/index.test.js [@ggrg]

**Acceptance Criteria**:
- [x] Unit tests are written so that tests coverage is 100%

**Dependencies**:
- None currently

**Accountability**:
- Owner @ggrg
- QA/Review

**Pull Requests**:
- [x] https://github.com/mojaloop/central-settlement/pull/23 [@ggrg]
- [x] https://github.com/mojaloop/central-settlement/pull/30 [@ggrg]
- [ ] https://github.com/mojaloop/central-settlement/pull/32 [@vgenev]

**Comment by ggrg** [comment]
**Estimate change note**: test files list contains 22 items. My personal average estimate for each item is rather 2 than 1 and this is why I vote for 40.

**Comment by elnyry** [comment]
Thanks Georgi, but as you can see, this is huge.. If we have to break it down, what would you suggest would be a good differentiating point would be?
