### ISSUE TITLE
Unit tests for central-settlement - II

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#449]
**Goal**:
As a contributor 
I would like the write unit tests against the implementation of central-settlement
so that unit tests can be automated and run as part of the CI/CD pipeline

**Tasks**:
- [ ] Write unit tests for implemented functionality
  - [x] test/unit/models/settlement/participantCurrency.test.js [@ggrg]
  - [x] test/unit/models/settlement/settlement.test.js [@ggrg]
  - [x] test/unit/models/settlement/settlementParticipantCurrency.test.js [@ggrg]
  - [x] test/unit/models/settlement/settlementTransferParticipant.test.js [@ggrg]
  - [x] test/unit/models/settlementWindow/facade.test.js [@ggrg]
  - [x] test/unit/models/settlementWindow/index.test.js [@ggrg]
  - [x] test/unit/models/settlementWindow/settlementWindowStateChange.test.js [@ggrg]
  - [x] test/unit/models/index.test.js [@ggrg]
  - [x] test/unit/utils/cloneDeep.test.js [@ggrg]
  - [x] test/unit/utils/logger-plugin.test.js [@ggrg]
  - [x] **extract** src/setup.js out from src/server.js [@ggrg]
  - [x] test/unit/setup.test.js [@ggrg]
  - [x] test/unit/server.test.js [@ggrg]

**Acceptance Criteria**:
- [x] Unit tests are written so that tests coverage is 100%

**Dependencies**:
- None currently

**Accountability**:
- Owner @ggrg
- QA/Review

**Pull Requests**:
- [ ] https://github.com/mojaloop/central-settlement/pull/31
