### ISSUE TITLE
Define the requirements for a transactional DB to be HA, HS and Performance

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#45]
**Goal**:
As a developer I want to define the requirements for a transactional database to be highly available (HA) and highly scalable (HS) in order for the solution to be robust and scale based on demand

**Tasks**:
- [ ] 

**Acceptance Criteria**:
- [ ] Define and Document the requirements for HA
- [ ] Define and Document the requirements for HS
- [ ] Define and Document the requirements for Performance
- [ ] Define and Document the requirements for Transactionality

**Dependencies**:
- None currently

**Comment by NicoDuvenage** [comment]
The requirements have been defined in a document shared on google docs:
https://docs.google.com/spreadsheets/d/1x47ZL2hNoTd7_4tU3dunxXOLHNkysSRj-YW-nDw9VzA/edit#gid=0
