### ISSUE TITLE
Validate currency amounts for Transfer requests

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#450]
**Goal**:
As a Switch
I would like to _validate all incoming amounts that relate to a currency are positive_ 
to ensure integrity is maintained and avoid calculation issues... 

**Tasks**:
- [x] Optimized handlers.test.js for faster execution (212s->89s) [@ggrg]
- [x] validate the amount to be positive in central-ledger [@vgenev]
~- [x] validate the amount to be at least 0.001 in central-settlement [@vgenev]~
- [x] check ml-api-adapter to be positive [@vgenev]
- [ ] Create follow-up stories based on the outcome

**PRs**:
- [x] https://github.com/mojaloop/central-ledger/pull/137
- [x] https://github.com/mojaloop/central-ledger/pull/136
~- [ ] https://github.com/mojaloop/central-settlement/pull/29~ not applicable 

**Acceptance Criteria**:
- [x] Incoming amounts for transfer requests are valid ( >0 )

**Dependencies**:
- None currently

N.B. This should be looked at in transfers, positions, limits etc.

**Accountability**:
- Owner @rmothilal  
- QA/Review
