### ISSUE TITLE
[45] Handling GET on /transfers/{ID} (phase2 version)

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#452]
**Goal**:
As a Switch
I would like to _provide a feature for an FSP to query a transfer based on the transferId_
so that they can find out information about that specific transfer (according to the Switch)

**Tasks**:
- [x] ~Design GET /transfers based on the specification (Send out callback if the transferState is one of COMMITTED, ABORTED or RECEIVED; if it is in RESERVED state, do not respond as part of this GET call, as a callback will be sent soon one way or the other. This approach is fine for now as we don't deal with long standing transactions but in the future where cross-implementation is supported, we may want to just respond to a GET /transfers/{ID} with whatever the current state of the transfer is) [@bothadeon @HenkKodde ]~
- [x] Design a simpler GET /transfers for Phase2 - where a callback is sent for a GET request with whatever the current state of a given transferID is (async, of course) @elnyry
- [x] PR for Sequence design: https://github.com/mojaloop/docs/pull/88 @elnyry 

- ML-API-ADAPTER :
Implementation for GET /transfers/{ID}
 - [x] Add code to the routes [@bothadeon]
 - [x] Add code to the handler [@bothadeon]
 - [x] Add methods to the transfer service [@bothadeon]
 - [x] Add method to src/domain/transfer/index.js [@bothadeon]
 - [x] Update Postman collection [@bothadeon]
 - [x] Update Js Docs [@bothadeon]
 - [x] Unit tests and code coverage [@vgenev ]

   
- CENTRAL_LEDGER :
Implementation for GET /transfers/{ID}
 - [x] Add code to src/handlers/api/admin/routes.js [@bothadeon @rmothilal ]
 - [x] Add code to src/handlers/register.js [@bothadeon @rmothilal ]
 - [x] Add code to src/handlers/transfers/handlers.js [@bothadeon @rmothilal ]
 - [x] Add code to src/handlers/transfers/validator.js [@bothadeon @rmothilal ]
 - [x] Add code to src/lib/enum.js [@bothadeon @rmothilal ]
 - [x] Add code to src/shared/setup.js [@bothadeon @rmothilal ]
 - [x] Update Js Docs [@bothadeon]

 - [x] Unit tests and code coverage [@bothadeon]

**Acceptance Criteria**:
- [ ] A GET call on /transfers/{ID} is made available, using which an FSP can query the status of a particular transfer

**Dependencies**:
- None currently

**Accountability**:
- Owner @bothadeon 
- QA/Review DA

**Comment by elnyry** [comment]
Sure Miller, will review the design with you

**Comment by bothadeon** [comment]
Pull request for the initial design : https://github.com/mojaloop/docs/pull/79

**Comment by bothadeon** [comment]
Sam commented :
I created the sequence diagrams for these.. This is a temporary solution we are doing for Phase2
Here is the PR - https://github.com/mojaloop/docs/pull/88
GitHub
Feature/#452 get transfers temporary solution phase2 by elnyry · Pull Request #88 · mojaloop/docs
