### ISSUE TITLE
Moving tests from testPI2 folder to the test folder for central services repos

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#453]
**Goal**:
As part of packaging
I would like _to move/merge the tests from testPI2 folder to the test folder_
so that all the tests reside in a single folder

**Tasks**:
- [x] Move the tests from testPI2 folder to test folder for the central services repos [@vgenev]
- [x] Ensure tests pass locally and in CircleCI [@vgenev]

**Acceptance Criteria**:
- [x] The tests from testPI2 folder are merged/moved to the test folder and have pass/fail results same as before [@vgenev]

**Dependencies**:
- [x] https://github.com/mojaloop/project/issues/397

**Accountability**:
- Owner @rmothilal  
- QA/Review

**Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/158
