### ISSUE TITLE
Investigate Settlements API failure  

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#454]
Priority: High
Investigate why the central-settlements API crashed on Kubernetes.
you search should relook at getWindowsBySettlementIdAndParticipantId function in src/models/settlement/facade.js

**Tasks**:
- [x] Run local instance of the environment to be able to test based on @mdebarros 's video https://drive.google.com/file/d/1HHuszQ3bjSTbXKujf6h0JkmYBW2K0HKD/view [@vgenev]
- [x] Fix logging of errors [@vgenev]
- [x] Put logging throughout the settlements API [@vgenev]
- [x] Investigate the suggested method behavior [@vgenev]
- [x] Fix any unwanted behavior [@vgenev]
- [x] Fix unit tests of the the above fixes [@vgenev]
- [x] Make coverage 100% again [@vgenev]
- [x] Run postman tests for few hours without restarting [@vgenev]
 - transfer.prepare 
 - transfer.fulfil
 - close settlementWindow
 - trigger settlement event
 - settle the accounts
 - all available for the Settlement API GETs
  - with delay slightly bigger than the enum cache
  - repeat

**Acceptance criteria**:
- [x] log requests [@vgenev]
- [x] log responses [@vgenev]
- [x] catch all the errors [@vgenev]
- [x] log all the errors [@vgenev]
- [x] tests running without errors [@vgenev]
- [x] coverage is 100% [@vgenev]

**PRs**:
- [x] https://github.com/mojaloop/central-settlement/pull/33

**Accountability**:
- Owner [@vgenev] 
- QA/Review [@rmothilal]
