### ISSUE TITLE
Documentation: Stale documents

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#456]
**Goal**:
As a community member,
I would like to _know which repos are actively used and which ones deprecated or stale_
so that I can filter out information and focus on relevant repos.

**Tasks**:
- [x] Identify repos not being deployed or used (@HenkKodde)
  - [x] Identify documentation in repos (@HenkKodde @NicoDuvenage)
  - [x] Create worksheet of existing documentation in repos (@HenkKodde)
  - [x] Identify documentation requirements in repos (@HenkKodde @NicoDuvenage)
  - [x] Update worksheet with required documentation in repos (@HenkKodde)
  - [x] Identify resources accountable to create / update documentation in repos (@HenkKodde @NicoDuvenage @elnyry)
  - [x] Comment if they are deprecated or no longer in use or stale (@HenkKodde @NicoDuvenage)
  - [x] Provide historic description to give context regarding the repo (Where, how it was used earlier) (@HenkKodde @NicoDuvenage)

**Acceptance Criteria**:
- [x] Stale documents are identified and marked as such, with historic information provided for context.

**Dependencies**:
- [ ] Availability of SMEs

**Accountability**:
- Owner @NicoDuvenage @HenkKodde  
- QA/Review
