### ISSUE TITLE
Documentation: Onboarding

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#457]
**Goal**:
As a developer to be onboarded
I would like to _get the resources needed for on-boarding (overview, deployment)_
so that I can quickly get started on using the resources for education, deployment and possibly extension, contribution.

**Tasks**:
- [x] Work on the landing page( @kjw000 . @HenkKodde, @NicoDuvenage  )
- [x] Ensure proper flow of information for on-boarding to a Mac (@NicoDuvenage, @mdebarros  )
- [x] Links to FAQs, Contacts, descriptions of components, etc (eg: Here is the deployment architecture, transfers architecture, end-to-end architecture, settlements architecture, etc) (@HenkKodde )
  - [x] Need descriptions on the diagrams (architecture diagrams [here](https://github.com/mojaloop/docs/tree/develop/CentralServices))
- [x] Links to specification documents and what to look for, where(@HenkKodde @NicoDuvenage )
- [x] A brief description of all repos (all components)(@HenkKodde @NicoDuvenage )
- [x] Include latest deployment and setup document. (@HenkKodde @NicoDuvenage )

**Acceptance Criteria**:
- [x] All the resources needed for developer on-boarding (on Mac) is provided with a consistent flow, with a good landing page.

**Dependencies**:
- [x] Availability of SMEs
- [x] #456 - Document list under tasks are actioned

**Accountability**:
- Owner @NicoDuvenage @HenkKodde  
- QA/Review

**Comment by elnyry** [comment]
PR for a minor change - https://github.com/mojaloop/docs/pull/91
