### ISSUE TITLE
Documentation: Deployment

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#458]
**Goal**:
As a community member,
I would like to _know the steps involved in deploying a Mojaloop system or Switch locally or on a cloud platform_
so that I can test the system and find out the characteristics.

**Tasks**:
- [ ] Identify steps, instructions needed to deploy a Switch
  - [ ] Provide specific details and step-by-step instructions to setup locally (with platform details)
  - [ ] Provide specific details and step-by-step instructions to setup on a cloud platform
- [ ] Identify steps, instructions needed to deploy an end-to-end system
  - [ ] This may need inputs in deploying the DFSP services

**Acceptance Criteria**:
- [ ] Documents that provide instructions on how to deploy a Mojaloop Switch are available (end-to-end deployment - needs investigation and fixing of issues; may need separate issue)

**Dependencies**:
- [ ] Availability of SMEs

**Accountability**:
- Owner @NicoDuvenage @HenkKodde  
- QA/Review

**Comment by elnyry** [comment]
This good enough for the time being ? - https://github.com/mojaloop/docs/blob/develop/WorkShops/Presentations/Mojaloop_Phase2_Wrap-up_Deployment-Day3_V2.0-published.pdf

**Comment by elnyry** [comment]
Now provided by stories #606, #633
