### ISSUE TITLE
Address licensing issue

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#459]
**Goal**:
As a Mojaloop platform maintainer,
I would like to _ensure all the software, packages that are used are **Apache 2.0** compatible_
so that they conform to the LevelOne principles.

**Tasks**:
- [ ] Identify licenses of all packages used (Explore tools for this - fossa?)
- [ ] List out issues that use GNU licenses and find resolutions
- [ ] Create follow-up issues to address to each of the groups (buckets) that use GPL, LGPL or similar issues.

**Acceptance Criteria**:
- [ ] A list that includes the packages used in the system along with their license information is provided and if possible a list of violations is produced so that it can be used for resolution.

**Dependencies**:
- [ ] Availability of SME, experts in licensing issues

**Accountability**:
- Owner 
- QA/Review

**Comment by lewisdaly** [comment]
@elnyry is this now outdated?

**Comment by elnyry** [comment]
@lewisdaly, Yes thanks.. Closing it
