### ISSUE TITLE
Set up an NPM repository

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#46]
**Goal**:
As a developer I need to set up an NPM repository so that I can use it to maintain the versioning of dependent libraries across components

**Tasks**:
- [x] Setup Mojaloop NPM repo on npmjs.com
- [x] Publish NPM repos to Mojaloop NPM repo on npmjs.com
- [x] Configure Github Mojaloop Node repos to use npmjs.com

**Acceptance Criteria**:
- [x] Secure NPM repository for publishing dependencies
- [x] Publicly available to the OSS community for retrieval of dependencies

**Dependencies**:
- None currently

**Comment by mdebarros** [comment]
Note that this was done during the pre-Jan18 phase. Using npmjs.com as the OSS repo may change at a later stage as required.

**Comment by elnyry** [comment]
LGTM

**Comment by mdebarros** [comment]
Demo: https://drive.google.com/file/d/1T-i2NAK6uBqbAP1EM6j_Gonsh_kaot2f/view?usp=sharing
