### ISSUE TITLE
As a hub operator I can't see the NetDebitCap per currency of all DFSPs

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#464]
**PRIORITY : MEDIUM**

Tool : Postman
API : limits
Operation : GET

**Summary:**
As a hub operator, I want to see the NDC per currency of all the DFSPs. But there is no option to search for this via the API. 
for example, if I want to see all DFSPs that has the NDC in "AFN", I can not send request for this as the current API doesn't support this functionality.

**Expected Behavior:** 
limits API should facilitate this search so that I can see all DFSP's NDC that has the same currency at one place in one request.

**Note:** Currently, limits API provides POST and GET limits functionality for a specific DFSP in only "USD". No filtering option available and not allowing to create limits in other currency. Also can't see NDC of multiple DFSP's in one window.

**Tasks**
  - [x] Design the api to get limits for all the participants - Sequence diagram -- @shashi165 
  - [x] Implement the design -- @shashi165 
  - [x] Test cases -- @shashi165 

**PRs**
 - [x] https://github.com/mojaloop/central-ledger/pull/225

![get limits](https://user-images.githubusercontent.com/33355509/50903508-a1871800-13e3-11e9-9c6d-762762e036be.png)

**Comment by elnyry** [comment]
This is a feature request, not a bug.

We already have the bug for the currency related issue [here](https://github.com/mojaloop/project/issues/463), so that should be taken care-of.

**Comment by shashi165** [comment]
You can filter the NET_DEBIT_CAP by currency for a single DFSP
URL: /participants/{{dfsp}}/limits?currency={{currencyId}}
e.g : /participants/dfsp1/limits?currency=AFN
