### ISSUE TITLE
Fix deployment script bug for incorrect fsp names

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#466]
**Goal**:
As DevOps
I would like to _deploy the performance test environment with the correct participants_
so that I can easily run the performance test scenarios

**Tasks**:
- [x] update env.sh with correct fsp names
- [x] drop the current deployment and redeploy

**Acceptance Criteria**:
- [x] We are able to test the golden path successfully

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/97

## **Follow-up**:
- N/A

## **Accountability**:
- Owner: @mdebarros
- QA/Review: Dev-Team
