### ISSUE TITLE
Central-Settlements Cache layer to be de-coupled from the Hapi Server

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#468]
## **Goal**:
As a `DevTeam` I want to `separate the cache from the Hapi Server` so that `the caching implementation does not require the Hapi Server for execution or access. (I.e. we want to be transport agnostic as much as possible, and must not closely couple any core functionality with the transport layer)`

**Tasks**:
- [ ] Instantiate the Cache as part of the Initialise method
- [ ] Ensure that the Cache object is accessed via the Model Layer: Facade and DAO 
- [ ] Update unit tests to comply with this change
- [ ] Update integration tests to comply with this change

**Acceptance Criteria**:
- [ ] Central-Settlements starts up the Cache independant of the Hapi server
- [ ] Central-Settlements acquires any cached values via the Model (Facade/DAO) Layer
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: DevTeam
