### ISSUE TITLE
Set up a Docker repository

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#47]
**Goal**:
As a developer I need to set up a Docker repository so that I can use it to maintain the versioning of dependent libraries across components

**Tasks**:
Performance activities:
- [x] Create Mojaloop org on Docker Hub
- [x] Create developer roles for manual developer publishing

**Acceptance Criteria**:
- [x] Secure Docker repository for publishing dependencies
- [x] Publicly available to the OSS community for retrieval of dependencies

**Dependencies**:
- None currently

**Comment by mdebarros** [comment]
Note that this was done during the pre-Jan18 phase. Using npmjs.com as the OSS repo may change at a later stage as required.

Access the Mojaloop Docker Hub org via the following URI: https://hub.docker.com/u/mojaloop/

**Comment by elnyry** [comment]
Looks good.

**Comment by mdebarros** [comment]
Demo: https://drive.google.com/file/d/1T-i2NAK6uBqbAP1EM6j_Gonsh_kaot2f/view?usp=sharing
