### ISSUE TITLE
Data consistency issue with Percona MySQL Cluster setup

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#470]
## **Goal**:
As a `DevTeam member`
I want to `configure Percona MYSQL Cluster to ensure consistency during all operations (inserts, selects, updates, deletes, replace, etc)`
so that `the Golden Path for Transfers is fully operational` with required configuration (master-master-master)

**Tasks**:
- [x] Investigate cause of issue [@ggrg, @rmothilal] (could not reproduce locally and on mojadev2)
  - [x] Investigate replication settings [@ggrg, @mdebarros, @rmothilal]

_@ggrg: The issue could not be reproduced with percona/percona-xtradb-cluster: 5.7.19. The recommended setting for [PXC Strict Mode](https://www.percona.com/doc/percona-xtradb-cluster/LATEST/features/pxc-strict-mode.html) is the default one - ENFORCING. The recommended setting for InnoDB Transaction Isolation Level remains also the default - REPEATABLE READ. How the pessimistic InnoDB locking works within the cluster is best described [here](https://www.percona.com/blog/2012/08/17/percona-xtradb-cluster-multi-node-writing-and-unexpected-deadlocks/) and regardless the fact it is an old article from 2012, it was confirmed to function exactly as described. The fact that `the cluster will use an optimistic locking model` is described [here](https://www.percona.com/doc/percona-xtradb-cluster/LATEST/features/multimaster-replication.html) and it differs from the default InnoDB pessimistic locking that can be observed when transacting in different sessions, opened against the same pod._

_@ggrg: Another observation for **minikube** that came up while on this story - it was impossible to run official stable/percona-xtradb-cluster chart with Kubernetes v1.15.6 or v1.16.2. Though, it was possible with Kubernetes v1.14.6, where I noted pxc pods being initiated one by one. After 5 minutes pods fail and need restarting. Pods were running stable with Docker Kubernetes in place of minikube. Please, find more info about versions of used components, setup commands (w/ minikube) and example SQL statements as comments to the story._
- [x] Propose fix: ensure percona/percona-xtradb-cluster: 5.7.19 or later is used [@ggrg]
- [x] Team to review fix [@ggrg]
  - [ ] ~Confirm behaviour on 5.7.27~ <-- couldn't get it properly deployed. These two articles might be useful for future story: [link1](https://www.percona.com/doc/kubernetes-operator-for-pxc/kubernetes.html), [link2](https://github.com/paulczar/helm-percona-xtradb-cluster-operator) [@ggrg]
  - [x] Confirm on dev2 using 5.7.19 [@ggrg]
- [ ] ~Implement fix~
- [ ] ~Investigate if a specific test can be done to check consistency / replication~ [Check to see if this needs a separate story] <-- I don't think we can trigger this via api requests [@ggrg]
- [x] Configure Helm Values file for MYSQL Percona Cluster to be configured correctly for consistency

**Notes**:
Currently, when increasing the number of replicas for the database to an odd number doesn't result in multi-master node implementation. <-- could not be reproduced [@ggrg]

**Acceptance Criteria**:
- [x] Transfers Golden Path Functional Tests pass with Percona mysql configured as required (in multi-master setup)

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: 
- QA/Review: ML OSS Core Team

**Comment by rmothilal** [comment]
@mdebarros please loot at this and let me know if we could use the configFiles: section in our values files to get the config we require for replication. https://github.com/helm/charts/blob/master/stable/percona-xtradb-cluster/values.yaml

**Comment by ggrg** [comment]
Will resume later, after resolving other higher priority item(s).

**Comment by ggrg** [comment]
## Used components:
- minikube v1.5.2 on Darwin 10.15.1
- Kubernetes v1.14.6 on Docker '18.09.9'
- kubectl v1.14.6
- helm v2.16.1

## Commands for local setup:
```
minikube start --kubernetes-version='v1.14.6'
curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.14.6/bin/darwin/amd64/kubectl
chmod +x ./kubectl
sudo mv ./kubectl /usr/local/bin/kubectl
helm install --debug --name pxc --namespace pxcluster stable/percona-xtradb-cluster -f ./values.yaml
kubectl expose pod pxc-pxc-0 --port=3306 --type=NodePort --namespace=pxcluster
kubectl expose pod pxc-pxc-1 --port=3306 --type=NodePort --namespace=pxcluster
kubectl expose pod pxc-pxc-2 --port=3306 --type=NodePort --namespace=pxcluster
minikube ip
```
## values.yaml
The following needs to stored into values.yaml file and passed to the `helm install` command above - 
```
# Default values for Percona XtraDB Cluster

## percona image and version
## ref: https://hub.docker.com/r/percona/percona-xtradb-cluster/tags/
image:
  repository: "percona/percona-xtradb-cluster"
  tag: "5.7.19"
  pullPolicy: IfNotPresent

# Desired number of members of xtradb cluster
replicas: 3

## Specify password for root user
##
mysqlRootPassword: password

## Specify password for xtradb backup user
##
# xtraBackupPassword: replicate-my-data

## Uncomment to create a database user
##
mysqlUser: central_ledger
mysqlPassword: password

## Allow unauthenticated access, uncomment to enable
##
mysqlAllowEmptyPassword: true

## Uncomment to Create a database
##
mysqlDatabase: central_ledger

## Configure pxc_strict_mode
## ref: https://www.percona.com/doc/percona-xtradb-cluster/LATEST/features/pxc-strict-mode.html
## pxc_strict_mode: ENFORCING
# pxc_strict_mode: DISABLED

## hosts to allow root user access from
# set to "127.0.0.1" to deny remote root.
allowRootFrom: "%"

## Persist data to a persistent volume
persistence:
  enabled: false
  ## percona data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 8Gi

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## Pod annotations
## Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}

## Tolerations labels for pod assignment
## Allow the scheduling on tainted nodes (requires Kubernetes >= 1.6)
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
# resources:
#  requests:
#    memory: 256Mi
#    cpu: 100m

configFiles:
  node.cnf: |+
    [mysqld]
    datadir=/var/lib/mysql
    default_storage_engine=InnoDB
    binlog_format=ROW
    innodb_flush_log_at_trx_commit  = 0
    innodb_flush_method             = O_DIRECT
    innodb_file_per_table           = 1
    innodb_autoinc_lock_mode=2
    bind_address = 0.0.0.0
    wsrep_slave_threads=2
    wsrep_cluster_address=gcomm://
    wsrep_provider=/usr/lib/galera3/libgalera_smm.so
    wsrep_cluster_name=galera
    wsrep_sst_method=xtrabackup-v2

## When set to true will create sidecar for `prom/mysqld-exporter`
## metrics exporting
metricsExporter:
  enabled: false
  commandOverrides: []
  argsOverrides: []

prometheus:
  ## Are you using [Prometheus Operator](https://coreos.com/operators/prometheus/docs/latest/user-guides/getting-started.html)?
  operator:
    ## Setting to true will create Prometheus-Operator specific resources like ServiceMonitors
    enabled: false

    ## Configures alerts for Prometheus to pick up
    prometheusRule:
      enabled: true

      ## Labels to add to alerts
      labels: {}

      ## Namespace which Prometheus is installed in
      # namespace: monitoring

      ## Label Selector for Prometheus to find alert rules
      # selector:
      #   prometheus: kube-prometheus

    ## Configures targets for Prometheus to pick up
    serviceMonitor:
      ## Interval at which Prometheus will scrape metrics exporter
      interval: 10s

      ## Namespace which Prometheus is installed in
      # namespace: monitoring

      ## Label Selector for Prometheus to find ServiceMonitors
      # selector:
      #   prometheus: kube-prometheus

## When set to true will create sidecar to tail mysql log
logTail: true

ssl:
  enabled: false
  secret: mysql-ssl-certs
  certificates:
#  - name: mysql-ssl-certs
#    ca: |-
#      -----BEGIN CERTIFICATE-----
#      ...
#      -----END CERTIFICATE-----
#    cert: |-
#      -----BEGIN CERTIFICATE-----
#      ...
#      -----END CERTIFICATE-----
#    key: |-
#      -----BEGIN RSA PRIVATE KEY-----
#      ...
#      -----END RSA PRIVATE KEY-----

## Configure PodDisruptionBudget
## ref: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
#
podDisruptionBudget:
  enabled: false
  # minAvailable: 1
  maxUnavailable: 1

## Set the percona kubernetes service headless (no load-balancing)
## ref: https://kubernetes.io/docs/concepts/services-networking/service/#headless-services
service:
  percona:
    headless: false

ingress:
  enabled: true
  type: http
  externalPath:
    api: /
  # Used to create an Ingress record.
  hosts:
    - percona-xtradb-cluster.local
    # api: percona.local
  annotations: {}
    # nginx.ingress.kubernetes.io/rewrite-target: '/'
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
```
## Sample SQL:
The following commands may be executed in separate sessions against different pods -
```
-- SELECT @@VERSION;
-- SET autocommit = 0;
-- SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
-- SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
-- SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
-- SET SESSION MAX_EXECUTION_TIME=2000;
START TRANSACTION;
SELECT * FROM test WHERE id = 1;
SELECT * FROM test WHERE id = 1 FOR UPDATE;
UPDATE test SET description = 'pxc-0' WHERE id = 1;
COMMIT;
```
