### ISSUE TITLE
Fulfil message on COMMIT not being put on payee FSP topic

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#472]
**Summary**:
When a Fulfil message is received, if it is to be COMMITTED, it is expected to be put on the Payee FSPs topic so that the Payee FSPs position can be updated; Instead it is being put on the Payer FSP topic. 

**Severity**:
High

**Priority**:
Critical

**Expected Behavior**
The Fulfil message is put on the Payee FSP's topic (so that its position can be updated); The Payer FSP's position is already updated during Prepare

**Tasks**:
- [x] Reproduce issue
- [x] Root-cause analysis, etc
- [x] Fix (config changes, etc)

**Pull Request**:
- [x] https://github.com/mojaloop/central-ledger/pull/143

**Specifications**
  - Component: Prepare/Position Handler (central-services in general)
  - Version: 3.6.0
  - Type of testing: Manual, Perf
  - Bug found/raised by: @mdebarros

**Notes**:
Earlier it worked since all the consumers are running in the same process. This was identified as part of perf setup where we have split up each of the handlers into their own processes (for performance).
