### ISSUE TITLE
Kafka Consumers Groups to be named consistently

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#473]
## **Goal**:
As a `DevTeam` I want to `the Kafka Consumers Groups to be named consistently` so that `we have a standardised naming convention`

**Tasks**:
- [ ] Updated ml-api-adapter configs with consistent consumer group name
- [ ] Updated central-ledger configs with consistent consumer group name
- [ ] Updated configs in all helm charts (parent, children, etc) with consistent consumer group name

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: DevTeam
