### ISSUE TITLE
Removal of all caret and tilde from package.json files for all API's

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#476]
**Summary**:
Exact versions of the dependencies we use in our API's are needed for deployment to AWS 

**Severity**:
High

**Priority**:
Critical

**Expected Behavior**
Dependency versions should be as represented in package.json and should not be automatically updated

**Tasks**:
- [x] ~Central-ledger package.json~ covered in #423 
- [x] Central-settlements package.json [@shashi165] [PR #44](https://github.com/mojaloop/central-settlement/pull/44)
- [x] ~ml-api-adapter package.json~ covered now in #357 
- [ ] ~remaining central-services libraries package.json~

**Pull Request**:
- [x] [PR #44](https://github.com/mojaloop/central-settlement/pull/44)

**Specifications**
  - Component: central-ledger, central-settlement, mlapi-adapter and remaining central-services libraries
  - Version: 3.6.0
  - Type of testing: Manual, Perf
  - Bug found/raised by: @mdebarros

**Notes**:
Noticed while sanity testing Dev demo environment logs

**Comment by millerabel** [comment]
This should make it easy… It enables development branch to use dynamic, semantic versioning, but enables locking down for release:

https://nodejs.org/en/blog/npm/managing-node-js-dependencies-with-shrinkwrap/ <https://nodejs.org/en/blog/npm/managing-node-js-dependencies-with-shrinkwrap/>

The article discusses use of “npm outdated” to test for updates without installing them and the ability to up level individual modules during a development cycle. Binary releases are still handled the old-fashioned way… as fully tested and packaged binaries.

— Miller

On Sep 25, 2018, at 9:47 AM, Rajiv Mothilal <notifications@github.com> wrote:

Summary:
Exact versions of the dependencies we use in our API's are needed for deployment to AWS

Severity:
High

Priority:
Critical

Expected Behavior
Dependency versions should be as represented in package.json and should not be automatically updated

Tasks:

 Central-ledger package.json
 Central-settlements package.json
 ml-api-adapter package.json
 remaining central-services libraries package.json
Pull Request:

[ ]
Specifications

Component: central-ledger, central-settlement, mlapi-adapter and remaining central-services libraries
Version: 3.6.0
Type of testing: Manual, Perf
Bug found/raised by: @mdebarros <https://github.com/mdebarros>
Notes:
Noticed while sanity testing Dev demo environment logs
