### ISSUE TITLE
Removing transfer handler from central-ledger services

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#478]
**Goal**:
As a Switch
I would like to _eliminate any handlers that do not add value to transfer critical path processing_
so that the critical path efficiency and performance can be improved.

**Tasks**:
- [x] Remove transfer handler from central-services
- [x] Use a separate branch for this to start with and update any tests that fail
- [x] Deploy on perf environment for testing
- [x] Update designs
  - [x] Update sequence diagrams
  - [x] Update architecture diagrams [@elnyry]
- [x] Snapshot versions released with this change [@elnyry]
- [x] Versions with the change deployed on dev envt. for QA for validation [@elnyry]
- [x] If no issues found or when stable, merge with dev

**Acceptance Criteria**:
- [x] Transfer Handler which is currently not serving any significant purpose as part of transfers process is removed/disabled from central-services to improve performance and efficiency

**PRs**:
- [x] https://github.com/mojaloop/central-ledger/pull/155
- [x] https://github.com/mojaloop/central-ledger/pull/169

**Dependencies**:
- None currently

**Accountability**:
- Owner @rmothilal 
- QA/Review @elnyry
