### ISSUE TITLE
Set up Circle-CI for the mojaloop org

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#48]
**Goal**:
As a developer I would like to set up Circle-CI for the mojaloop org so that I can integrate the development and deployment effort end-to-end

**Tasks**:
- [x] Create Mojaloop Org on Circle-CI
- [x] Configure connectivity to Github Mojaloop Org

**Acceptance Criteria**:
- [x] Mojaloop org setup on Circle-CI with access to mojaloop github org
- [x] Upgrade the $0 plan to a paid plan to increase parallel workflows and provide support (optional if required)

**Dependencies**:
- None currently

**Comment by mdebarros** [comment]
Note that this was completed in the pre-Jan18 phase

**Comment by mdebarros** [comment]
Hi @bhcrosslake,

Sam indicated that you guys currently have a paid plan for CircleCI for the L1P project. Could we move this to the Mojaloop CircleCI org for the following reasons:
1. We can only get support through a paid plan
2. We will increase the number of parallel flows that will improve CI/CD pipeline times. This will be required if not now, then later...certainly by sprint 2 I would think.

Let me know.

Thanks.

**Comment by mdebarros** [comment]
Reposted from Mojaloop Slack:

So far all the basic flows for Central-Ledger are working. However there is still one pending issue that is impacting the delivery of the central-ledger CI story (and all other CI stories tbh).
Currently Circle CI v2.0 supports kicking off a Workflow when a Tag has been pushed to Git. This functionality was added late last year, and does not seem to be working correctly.
I have come accross several people complaining about the issue, with little or no support from Circle CI team. I am also unable to log any support tickets to Circle CI team as we do not have a paid Circle CI solution.

Currently we have two options going forward:
1. We wait till the CircleCI team official acknowledge the issue and fix it <– I do not believe we can afford to wait for this option
2. Arrange for a paid subscription so that we can attain some support from the Circle CI Team, and open a support ticket to resolve the issue ASAP <– prefered approach
3. I can use a hack to work around this issue. That being that whenever there is a commit to the develop/master branches.....I can then check the specific branch for the latest tag....and then use that. <- This means that we will have to conform to a strict workflow when publishing new releases: that being that we must FIRST create a tag and push that to Github, then merge the PR or commit the changes as required. This will then allow for CircleCI to kick-off the workflow and subsequantly grab the tag from the previous pushed tag. I am personally not a fan of this approach, but dont see much of an option at the moment unless we go with option 1 or 2

Let me know if you have any comments, and or suggestions on the above.

**Comment by bhcrosslake** [comment]
We dropped the paid plan for 2 parallel builds for CircleCI a while ago. On mojaloop, the open source plan we are using has 4 parallel builds, which is even better. Let me know if this is sufficient.

thanks,
- Bill

**Comment by mdebarros** [comment]
Demo: https://drive.google.com/file/d/1T-i2NAK6uBqbAP1EM6j_Gonsh_kaot2f/view?usp=sharing
