### ISSUE TITLE
Timezones apart from UTC being used in central services

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#486]
**Summary**:
As part of implementing signed amounts during transfer and running integration tests locally using `npm run test:int`, it was noticed that there were instances where local time/timezones were being used instead of UTC.

**Severity**:
High

**Priority**:
Critical

**Expected Behavior**
UTC needs to be used consistently across all central services where timestamps, times, timezones are used.

**Tasks**:
- [x] Locate issues where local timezones are used
- [x] Fix issues

**Pull Request**:
- [ ] https://github.com/mojaloop/central-ledger/pull/157

**Specifications**
  - Component: central-services in general
  - Version: 3.6.0
  - Type of testing: Manual
  - Bug found/raised by: @ggrg 

**Notes**:
Local timestamps were found in the following tables after run @ 2018-10-02 06:44:55 GMT:
- [x] ~migration~ (this is a node_module)
<img width="446" alt="migration" src="https://user-images.githubusercontent.com/20338055/46333541-66798980-c629-11e8-915c-b7eaa83106d9.png">

- [x] participantPosition 
<img width="530" alt="participantposition" src="https://user-images.githubusercontent.com/20338055/46333733-1e0e9b80-c62a-11e8-872d-70e4a0fc73af.png">

- [x] participantPositionChange
<img width="690" alt="participantpositionchange" src="https://user-images.githubusercontent.com/20338055/46333597-9163dd80-c629-11e8-80ec-b9a61b7b29ea.png">

At the above screenshot another issue is observed - the last record with id 5 is a transfer with amount of 1100 which is over the limit for the participant. Due to that the transfer is ABORTED, but latest reservedValue is 1100. Also it does not match the value of reservedValue from participantPosition screenshot for participantPositionId=6, which is correctly 0. @elnyry, please consider logging it as a different bug.

- [x] transferExtension
<img width="827" alt="transferextension" src="https://user-images.githubusercontent.com/20338055/46333601-96c12800-c629-11e8-94f6-f34e9414234d.png">

- [x] transferFulfilment
<img width="790" alt="transferfulfilment" src="https://user-images.githubusercontent.com/20338055/46333614-a04a9000-c629-11e8-91d7-673ebda3650d.png">

At the above screenshot it should be also noticed completedDate and createdDate for record 3 and 4 do not match - not sure if it's ok or not?

- [x] transferStateChange
<img width="805" alt="transferstatechange" src="https://user-images.githubusercontent.com/20338055/46333619-a50f4400-c629-11e8-881a-f9d99032bbc3.png">

- [x] transfer.expirationDate -> same issues, now fixed

**Comment by elnyry** [comment]
Thanks Georgi
