### ISSUE TITLE
Set up Ansible provisioning for k8s

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#49]
**Goal**:
As a developer I would like to set up an Ansible provisioning of the environment so that I can consistently and automatically deploy and provision a new environment

**Tasks**:
- [x] Clone the Kubespray Git Repo into the Mojaloop Github Org
- [x] Modify Kubespray Ansible scripts and configuration for the AWS K8s deployment
- [x] Deploy working K8s cluster on AWS for testing/development purposes

**Acceptance Criteria**:
- [x] Deliver a configurable ansible script that automagically deploys a k8s cluster to a provisioned AWS infrastructure

**Dependencies**:
- None currently

**Comment by mdebarros** [comment]
Mojaloop Kubespray script and configurations are available via the following Github Private repo: https://github.com/mojaloop/kubespray

Note that the AWS K8s deployment for develop/testing environment is found under the branch "release/aws-mojaloop-dev".

**Comment by mdebarros** [comment]
Demo: https://drive.google.com/open?id=1BDjsVK4WpGhAg69lJulq8o2XSPcJ8sRc
