### ISSUE TITLE
Plug in monitoring dashboards for health reporting with persistent storage

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#497]
**Goal**:
As Ops I would like to see a dashboard displaying the health status of the different deployed components and containers with the data persisted to ensure High-Availability.

**Tasks**:
- [ ] Configure persistent storage for all health reporting data

**Acceptance Criteria**:
- [ ] Storage persisting health reporting data
- [ ] Kill monitoring technology/containers with the K8s deployment. Once they are re-deployed by K8 via self-healing the history health reporting data should be available in all dashboards.

**Dependencies**:
- [ ] K8 environment
- [ ] Deployment Monitoring technology

Old issue - https://github.com/mojaloop/mojaloop/issues/109

**Comment by elnyry-sam-k** [comment]
should be part of the bus ops workstream
