### ISSUE TITLE
Interfaces for RecordFundsIn & RecordFundsOut to support the Settlement process

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#499]
**Goal**:
As a Hub Operator
I would like to provide _APIs to reflect Deposits and Withdrawals_
so that those operations are updated in the Switch.

**Tasks**:
- [x] Study of business requirements and processes [@ggrg]
- [x] Provide central-ledger/admin **RecordFundsIn** API [@ggrg]
  - [x] Refer to item#1 in notes below [@ggrg]
  - [x] Confirm Data Model for the RecordFundsIn, RecordFundsOut requests [@ggrg, @vgenev]
  - [x] Data Validation of the requests (for example, currency match against a/c, settlement Type, etc) [@vgenev]
- [x] Provide central-ledger/admin **RecordFundsOut** API [@ggrg]
  - [x] Data validations similar to above [@vgenev]
  - [x] Aborting a prepared Transfer [@ggrg]
  - [x] Committing a prepared Transfer [@ggrg]
    - [x] If enough funds are available for the fundsOut commit operation [@ggrg]
- [x] Recorded demo session [@ggrg]
- [x] Add unit tests
  - [x] seeds/participant.js [@vgenev]
  - [x] src/admin/participants/handler.js [@vgenev]
  - [x] src/domain/participant/index.js [@vgenev]
  - [x] src/models/participant/facade.js [@vgenev]
  - [x] src/handlers/admin/handler.js [@vgenev]
  - [x] src/handlers/admin/validator.js [@vgenev]
  - [x] src/models/transfer/facade.js [@ggrg]
  - [x] src/shared/setup.js [@ggrg]
- [x] Provide 100% code coverage for newly introduced code [@vgenev, @ggrg]
- [x] Release this feature as a snapshot [@elnyry]
- [x] Deploy this Release this feature as a snapshot (dev environment) [@elnyry]

**Acceptance Criteria**:
- [x] A Deposits API is available to reflect inbound funds movement
- [x] A Withdrawals API is available to reflect outbound funds movement
- [x] If the account being provided is not a Settlement account, validation should fail (along with other checks specified).

**PRs**
 - [x] https://github.com/mojaloop/central-ledger/pull/188

**Dependencies**:
- [ ] None currently

**Accountability**:
- Owner @ggrg 
- QA/Review @wdcmb @RobReeve 

**Notes**:
1. Video fo the demo: https://www.dropbox.com/s/nrmw7gb06a1qcov/SettlementTransfersDemoScripts-Georgi.mp4?dl=0
2. To record FundsIn/Out against an FSP ```POST /participants/{name}/accounts/{id}```
on valid on accounts '_type_' = settlement (actions: **recordFundsIn**, **recordFundsOutPrepare**, **recordFundsOutCommit** and **recordFundsOutAbort**)
 ```
{
  "transferId": "a87fc534-ee48-7775-b6a9-ead2955b6413",
  "externalReference": "string",
  "action": "recordFundsIn",
  "amount": {
    "amount"="0.0000", # no negative values
    "currency"="USD"
  },
  "reason": "Reason for in/out flow of funds",
  "extensionList": {
    "extension": [
      {
        "key": "string",
        "value": "string"
      }
    ]
  }
}
```

**PUT /participants/{name}/accounts/{id}/transfers/{transferId}**
_Record funds out commit & abort should happen using this end-point - uses the same payload, without the transferId as it is already present as the URI param_

3. To be implemented to be in 'async' mode - no callback since no service will be running for the Hub Operator. The thinking is that the Hub Operator has access to the status through another API which may be leveraged by **UI** at a later time.

4. FundsIn - is just a notification
FundsOut - Request to send money (reserve, commit, etc), need to support roll-back

**Comment by elnyry** [comment]
Implementing this story - https://github.com/mojaloop/project/issues/509 instead of 499 in the current Sprint

**Comment by elnyry** [comment]
Deployed on the dev environment, tested a transfer and see that the DB records look fine and also the notification handler logs seem okay.

Versions:
1. central-ledger **v3.8.3**
2. central-settlement **v3.8.0**
3. ml-api-adapter **v3.8.0**
(4. helm **3.8.3**)
