### ISSUE TITLE
API for adding and querying hub accounts

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#505]
**Goal**:
As a Hub Operator
I would like to provide _APIs for adding and querying hub participant and hub reconciliation currency accounts_
so that participating FSPs can add corresponding accounts and query them.

**Tasks**:

Create:
- [x] Create new endpoint (/participants/{name}/accounts) in central-ledger to capture POST requests for creation  [@bothadeon]
- [x] Add postman script to collection for new endpoint (/participants/{name}/accounts) in central-ledger to capture POST requests for creation  [@bothadeon]
- [x] Add corresponding record into Participant position table with a value & Reserved value  of zero   [@bothadeon]
- [x] Functional tests with postman script  [@bothadeon]
- [x] Add unit tests and check code coverage  [@bothadeon]
- [x] Update jsdocs for new code  [@bothadeon]

Get:
- [x] Create new endpoint (/participants/{name}/accounts) in central-ledger to capture GET requests for querying [@bothadeon]
- [x] Add postman script to collection for new endpoint (/participants/{name}/accounts) in central-ledger to capture GET requests for creation  [@bothadeon]
- [x] Functional tests with postman script  [@bothadeon]
- [x] Add unit tests and check code coverage  [@bothadeon]
- [x] Update jsdocs for new code  [@bothadeon]

General tasks:
- [x] Refactor 'HUB_LIABILITY' to '**HUB_RECONCILIATION**'
  - [x] Update seeds
  - [x] Update references
- [x] Create handler for combined creation of hub participant and hub reconciliation accounts for specified currency, functioning similarly to the participant account creation
  - [x] Add Hub Participant via seeds (participant ID of #1)
- [x] Handler should enable addition of the current HUB_RECONCILIATION account type, as well the future **HUB_FEE** account type.
- [x] Create GET endpoint for querying existing hub accounts (see https://github.com/mojaloop/project/issues/509)
- [x] Update demo scripts (test/util/scripts/reconciliationTransfer) to use the newly created POST endpoint 

**Acceptance Criteria**:
- [x] An API for adding/querying hub reconciliation accounts is provided by the Switch
- [x] An existing Hub participant account cannot be over-written

**PRs**
 - [x] mojaloop/central-ledger#189

**Dependencies**:
- [ ] None currently

**Accountability**:
- Owner @ggrg 
- QA/Review @wdcmb

**Comment by bothadeon** [comment]
created pull request : https://github.com/mojaloop/central-ledger/pull/189
