### ISSUE TITLE
Change participant account creation/query handlers

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#506]
**Goal**:
As a Hub Operator
I would like to change the _process for adding and querying participant accounts_
so that they support the Settlement process and updating of Positions/limits.

**Tasks**:
- [x] Account for a currency should be allowed only if _hub reconciliation_ for that currency exists [@ggrg]
- [x] Result of account creation shows all created accounts and their respective type (enumeration name instead of id) [@ggrg]
- [x] Result of account query should output all participant accounts and their respective type (enumeration name instead of id) [@ggrg]
- [x] Add HUB_MULTILATERAL_SETTLEMENT account type and functionality for its creation [@ggrg]
- [x] Bugfix: /participants/{name}/accounts endpoint should not allow creation of POSITION and SETTLEMENT account for Hub operator with error message "The requested hub operator account type is not allowed." [@ggrg]
- [x] Bugfix: /participants/{name}/accounts endpoint should not work for any other participant and fail with error message "Endpoint is reserved for creation of Hub account types only." [@ggrg]
- [x] Add admin API swagger definition file to the repo @ src/admin/interface/swagger.json [@ggrg]
- [x] Fix failing unit tests [@ggrg]
- [x] Add unit tests [@ggrg]
  - [x] src/admin/participants/handler.js
  - [x] src/domain/participant/index.js
  - [x] src/models/participant/participantCurrency.js
  - [ ] ~seeds/settlementWindow2Open.js~
  - [ ] ~src/errors/ParticipantAccountCreate.js~
  - [ ] ~src/errors/ParticipantAccountExist.js~
  - [ ] ~src/errors/record-exists-error.js~
  - [ ] ~src/handlers/index.js~
  - [ ] ~src/handlers/lib/utility.js~
  - [ ] ~src/handlers/lib/kafka/consumer.js~
  - [ ] ~src/handlers/transfers/handler.js~
  - [ ] ~src/handlers/transfers/validator.js~
  - [ ] ~src/models/participant/facade.js~
  - [ ] ~src/models/participant/participantLimit.js~
  - [ ] ~src/models/participant/participantPosition.js~
  - [ ] ~src/models/position/facade.js~
  - [ ] ~src/models/transfer/transferStateChange.js~

- [x] Provide 100% code coverage for newly introduced code

**Acceptance Criteria**:
- [ ] API for adding/querying participant accounts is updated

**PRs**
 - [ ] https://github.com/mojaloop/central-ledger/pull/196

**Dependencies**:
- [ ] None currently

**Accountability**:
- Owner @ggrg 
- QA/Review @wdcmb 

**Notes**:
- Currently (v3.8.0) an FSP account can be created irrespective of whether or not a Hub account for that currency exists
- Currently (v3.8.0), not all accounts are listed and also 'ledgerAccountTypeId' is present in the response message
- Desired response (after changes) **POST http://{{ADMIN_API_3001}}/participants**
```
{
    "name": "dfsp1",
    "id": "http://localhost:3001/participants/dfsp1",
    "created": "2018-10-18T06:29:16.000Z",
    "isActive": 1,
    "links": {
        "self": "http://localhost:3001/participants/dfsp1"
    },
    "accounts": [
        {
            "id": 4,
            "ledgerAccountType": "POSITION",
            "currency": "EUR",
            "isActive": 1,
            "createdDate": "2018-10-18T06:29:16.000Z",
            "createdBy": "unknown"
        },
        {
            "id": 5,
            "ledgerAccountType": "SETTLEMENT",
            "currency": "EUR",
            "isActive": 1
            "createdDate": "2018-10-18T06:29:16.000Z",
            "createdBy": "unknown"
        }
    ]
}
```
- Desired response (after changes) **GET http://{{ADMIN_API_3001}}/participants/dfsp1/accounts**
```
{
    "name": "dfsp1",
    "id": "http://localhost:3001/participants/dfsp1",
    "created": "2018-10-18T06:29:16.000Z",
    "isActive": 1,
    "links": {
        "self": "http://localhost:3001/participants/dfsp1"
    },
    "accounts": [
        {
            "id": 2,
            "ledgerAccountType": "POSITION",
            "currency": "USD",
            "isActive": 1,
            "createdDate": "2018-10-18T06:29:16.000Z",
            "createdBy": "unknown"
        },
        {
            "id": 3,
            "ledgerAccountType": "SETTLEMENT",
            "currency": "USD",
            "isActive": 1
            "createdDate": "2018-10-18T06:29:16.000Z",
            "createdBy": "unknown"
        },
        {
            "id": 4,
            "ledgerAccountType": "POSITION",
            "currency": "EUR",
            "isActive": 1,
            "createdDate": "2018-10-18T06:29:16.000Z",
            "createdBy": "unknown"
        },
        {
            "id": 5,
            "ledgerAccountType": "SETTLEMENT",
            "currency": "EUR",
            "isActive": 1
            "createdDate": "2018-10-18T06:29:16.000Z",
            "createdBy": "unknown"
        }
    ]
}
```

**Comment by elnyry** [comment]
I think we need an item to detail the step-by-step process of on-boarding an FSP and formalize the process - what accounts need to be created first, and then addition of end-points, initialization of limits, etc.

**Comment by RobReeve** [comment]
@elnyry I will start the documentation, when do you need it for

**Comment by elnyry** [comment]
Thanks Rob. I don't have a timeline in mind but, the earlier the better.. Would be nice to have it done with our MVP release, if you have the time...

**Comment by ggrg** [comment]
Current test code coverage:
```
=============================== Coverage summary ===============================
Statements   : 97.34% ( 2819/2896 )
Branches     : 94.3% ( 662/702 )
Functions    : 96.07% ( 391/407 )
Lines        : 97.38% ( 2791/2866 )
================================================================================

1..990
# tests 990
# pass  990

# ok
```
