### ISSUE TITLE
Integration tests for central-settlement

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#507]
**Goal**:
As a Contributor
I would like to _add integration tests for central-settlement_
so that the settlement features testing can be automated

**Tasks**:
- [x] Use central-settlement/test/util/scripts/settlementTransfer scripts as a starting point for creation of integration tests [@ggrg]
- [x] Add integration tests following *test/util/scripts/settlementTransfer* demo scripts [@ggrg]
  - [x] Populate initial admin data through central-ledger micro service and assert [@ggrg]
  - [x] Populate transfer through ml-api-adapter, central-ledger, simulator and assert [@ggrg]
  - [x] Close settlement window and assert valid [@ggrg]
  - [x] Create settlement and assert [@ggrg]
  - [x] PS_TRANSFERS_RECORDED for PAYER and assert [@ggrg]
  - [x] PS_TRANSFERS_RECORDED for PAYEE and assert [@ggrg]
  - [x] Settlement to PS_TRANSFERS_RESERVED and assert [@ggrg]
    - [x] Resolve issue with open kafka producer handle [@ggrg]
  - [x] Settlement to PS_TRANSFERS_COMMITTED and assert [@ggrg]
  - [ ] ~SETTLED for PAYER and assert~
  - [ ] ~SETTLED for PAYER - additional note and assert~
  - [ ] ~SETTLED for PAYEE / Settlement SETTLED and assert~
- [ ] ~Enable running integration tests for central-settlement in circleCI (enable the path)~
- [ ] ~Make sure integration tests pass/fail as expected in circleCI~

**Acceptance Criteria**:
- [x] _Progress is made on_ Integration tests ~are provided~ for central-settlement ~and~ _to_ work in circleCI

**PRs**
 - None ([compare changes](https://github.com/mojaloop/central-settlement/compare/master...ggrg:feature/507IntegrationTests)) 

**Dependencies**:
- None currently

**Accountability**:
- Owner @ggrg 
- QA/Review @RobReeve @wdcmb

**Comment by elnyry** [comment]
Link for changes is provided in the **PRs** section. Its not merged yet, but closing this item, as it will be taken up in #635 .
