### ISSUE TITLE
Provide central-ledger admin api /participants/{name}/accounts endpoint for querying accounts balance

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#509]
**Goal**:
As a Hub Operator
I would like to provide _an admin endpoint for querying accounts' balance of an FSP_
so that accounts' balance can be queried.

**Tasks**:
- [x] Alter /initialPositionAndLimits endpoint to create initial position of 0 for SETTLEMENT account [@ggrg]
- [x] Amend settlementTransferCommit to write position change for SETTLEMENT account [@ggrg]
- [x] Add /participants/{name}/accounts endpoint to return to following sample response: [@ggrg]
```
[
    {
        "id": 1,
        "currency": "USD",
        "ledgerAccountType": "POSITION",
        "value": 0,
        "reservedValue": 0,
        "changedDate": "2018-10-10T07:17:01.000Z"
    },
    {
        "id": 2,
        "currency": "USD",
        "ledgerAccountType": "SETTLEMENT",
        "value": 0,
        "reservedValue": 0,
        "changedDate": "2018-10-10T07:17:01.000Z"
    }
]
```
- [x] Add unit tests
  - [x] central-ledger [@ggrg]
  - [x] central-settlement [@ggrg]
- [x] Provide 100% code coverage for newly introduced code
  - [x] central-ledger [@ggrg]
  - [x] central-settlement [@ggrg]

**Acceptance Criteria**:
- [x] It is possible to query current balance of all participant accounts

**PRs**
- [ ] https://github.com/mojaloop/central-ledger/pull/170
- [ ] https://github.com/mojaloop/central-settlement/pull/45

**Dependencies**:
- None currently

**Accountability**:
- Owner @ggrg 
- QA/Review @wdcmb
