### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#512]
**Goal**:
As a Community member
I would like to have access to _documentation that is up-to-date_  &  reflects actual implemented state
so that I can interpret, consume and use it without ambiguity.

**Tasks**:
**Below tasks to be actioned by technical development team members.**
1. **Core Component - Required documents to be created**
    - **central-settlement**(@vgenev @ggrg @wdcmb )
        - [x] README.md [@vgenev]
        - [ ] Onboarding.md ==> (document to be renamed - Deployment.md / Installation.md) ~(@ggrg: file does not exist)~(@HenkKodde: Document required to be created)
        - [x] API Definition.md [@vgenev]
        - [ ] SettlementGuide.md ~(@ggrg: file does not exist)~(@HenkKodde: Document required to be created)

2. **Core Component - Documents to be verified as currently relevant. Insure they are up to date**
    - **central-ledger**(@rmothilal @ggrg @elnyry )
        - [ ] API.md (@ggrg: this document is completely out of date and needs to be sync with the latest Postman collection we have. My estimate would be it needs at least 4 hrs of editing.)
        - [ ] README.md (@ggrg: looks good. Onboarding link to be altered to Deployment. Environment variables list needs updating - some variables might not be used any more. CLEDG_PORT 3000 is now used by ml_api_adapter. In the Tests section there is a command I've never used. By my opinion it needs to be replaced with `npm run test:unit`, `npm run test:coverage` and probably `npm run test:int`, the last one being for running integration tests locally.)
        - [ ] KUBERNETES.md
        - [ ] LICENSE.md
        - [ ] Onboarding.md  ==> (document to be renamed - Deployment.md / Installation.md) (@ggrg: content seems to be correct and current. I would leave it as is, besides filename change and have the next person to join the team use it and alter it where necessary)
        - [ ] TransferGuide.md (@ggrg: document out of date. Accounts payload and response are different. Also it worths mentioning that admin API is used. Transfer prepares and commits are now done via ml-api-adapter endpoints)
    - **central-services-shared**(@rmothilal @elnyry @ksatya77 @shashi165 )
        - [ ] README.md
        - [ ] LICENSE.md
        - [ ] src/kafka/readme.md
        - [ ] src/kafka/examples/consumer.md
        - [ ] src/kafka/examples/producer.md
        - [ ] src/kafka/protocol/readme.md
    - **ml-api-adapter**(@elnyry @rmothilal @shashi165 )
        - [ ] API.md
        - [ ] LICENSE.md
        - [ ] Onboarding.md  ==> (document to be renamed - Deployment.md / Installation.md)
        - [ ] README.md
    - **mock-pathfinder**(@elnyry )
        - [ ] API.md
        - [ ] KUBERNETES.md
        - [ ] LICENSE.md
        - [ ] README.md
    - **central-services-database**(@rmothilal )
        - [ ] LICENSE.md
        - [ ] README.md
    - **central-directory**(@elnyry @rmothilal )
        - [ ] API.md
        - [ ] KUBERNETES.md
        - [ ] LICENSE.md
        - [ ] Onboarding.md  ==> (document to be renamed - Deployment.md / Installation.md)
        - [ ] README.md
        - [ ] UserRetrievalGuide.md
    - **central-services-error-handling**(@rmothilal @bothadeon )
        - [ ] LICENSE.md
        - [ ] README.md
    - **central-services-auth**(@rmothilal )
        - [ ] LICENSE.md
        - [ ] README.md
    - **central-kms**(@rmothilal )
        - [ ] API.md
        - [ ] KUBERNETES.md
        - [ ] LICENSE.md
        - [ ] README.md
        - [ ] Socket.md
    - **forensic-logging-sidecar**(@rmothilal )
        - [ ] FLS-review-for-THREAT-modeling.md
        - [ ] KUBERNETES.md
        - [ ] LICENSE.md
        - [ ] README.md
    - **ntpd**(@fbotha-stratuscloud @elnyry )
        - [ ] README.md
    - **central-end-user-registry**(@elnyry )
        - [ ] API.md
        - [ ] KUBERNETES.md
        - [ ] LICENSE.md
        - [ ] Onboarding.md  ==> (document to be renamed - Deployment.md / Installation.md)
        - [ ] README.md
    - **interop-switch**(@ksatya77 @elnyry )
        - [x] LICENSE ==> LICENSE.md [@elnyry]
        - [ ] ~Onboarding.md  ==> (document to be renamed - Deployment.md / Installation.md)~ Readme file has a section regarding deployment, so it is covered there.
        - [x] README.md [@elnyry]

3. **Core Related**
    - **test-scripts**(@sri-miriyala @elnyry )
        - [x] LICENSE.md [@elnyry]
        - [x] contract-tests/README.md (empty document) - added a basic readme file [@elnyry]
        - [x] functional-tests/README.md [@elnyry]
    - **postman**(@elnyry @mdebarros )
        - [x] README.md [@elnyry]
        - [x] Add license file [@elnyry]
    - **docs**(@ggrg @shashi165 @rmothilal @elnyry @mdebarros )
        - [ ] Discovery.md
        - [ ] L1P Architecture and Payment Flow.pdf
        - [ ] LICENSE.md
        - [ ] Mojaloop_comprehensive_Documentation.pdf
        - [ ] Mojaloop_Developer_Onboarding.pdf
        - [ ] PKI Guide.md
        - [ ] PerformanceAndLatencyMetricsAndScenarios.md
        - [ ] central-services-overview.md
        - [ ] decisions.md (@ggrg: looks perfect to me)
        - [ ] scenarios.md (@ggrg: document looks good and represents near future state of mojaloop)
        - [ ] terminology.md (@ggrg: probably worth adding the enumerations we use throughout the lookup tables. Document looks to be detailed and current)
        - [ ] README.md
            - **CentralDirectory** (sub directory)
            - [ ] README.md
            - [ ] central_directory_endpoints.md
            - [ ] .svg and .png - diagrams
            - **CentralLedger** (sub directory)
            - [ ] README.md
            - [ ] central_ledger_endpoints.md
            - [ ] .svg and .png - diagrams
            - **CentralRules** (sub directory)
            - [ ] README.md
            - [ ] central_rules_endpoints.md
            - [ ] .svg and .png - diagrams
            - **CentralServices** (sub directory)
            - [ ] README.md (document required)
            - **design** (sub directory)
            - [ ] des-timeout-1.0.md
            - **DFSP** (sub directory)
            - [ ] README.md
            - [ ] account.md
            - [ ] developement.md
            - [ ] directory.md
            - [ ] identity.md
            - [ ] notification.md
            - [ ] rule.md
            - [ ] subscription.md
            - [ ] transfer.md
            - **BulkPayment** (sub directory)
            - [ ] README.md
            - **E2E integration test proposal** (sub directory)
            - [ ] README.md
            - **GSMA MM & L1P DFSP API** (sub directory)
            - [ ] ReadMe.md
            - **Invoice API** (sub directory)
            - [ ] README.md
            - **ManageAccountHolders** (sub directory)
            - [ ] ReadMe.md
            - **Pending Transactions Api** (sub directory)
            - [ ] README.md
            - **PendingTransactions** (sub directory)
            - [ ] README.md
            - **USSD** (sub directory)
            - [ ] README.md
            - **DevOps** (sub directory)
            - [ ] README.md (document required)
            - [ ] CI_and_CD_requirements.md
            - [ ] CircleCI.md
            - **ELK** (sub directory)
            - [ ] README.md (document required)
            - [ ] ELKSetup.md
            - [ ] kibana-user-guide.md
            - **ExportDocs** (sub directory)
            - [ ] README.md
            - **ILP** (sub directory)
            - [ ] README.md
            - **Interop Services and Mule** (sub directory)
            - [ ] README.md
            - [ ] Configuring HAProxy.md
            - [ ] docker.md
            - [ ] logging-guidelines.md
            - [ ] studio-and-mule-runtime-setup.md
            - **Standards** (sub directory)
            - [ ] README.md (document required)
            - [ ] Bug_Template.md
            - [ ] Creating_new_Feature.md
            - [ ] Standard_Headers.md
            - [ ] Template_Bug.md
            - [ ] Template_Story.md
            - **Wiki** (sub directory)
            - [ ] README.md (document required)
            - [ ] .svg and .png  - diagrams
            - **Workshop/Presentations** (sub directory)
            - [ ] README.md (document required)
            - **metrics-images** (sub directory)
            - [ ] README.md (document required)
            - [ ] .jpg - diagrams
            - **test** (sub directory)
           - [ ] README.md (document required)
            - [ ] RMA.md
            - [ ] account management tests.md
            - [ ] bulk payments.md
            - [ ] customer management tests.md
            - [ ] dfsp test.md
            - [ ] fees tests.md
            - [ ] forensic logging tests.md
            - [ ] pending transaction tests.md
            - [ ] send money test.md
    - **helm**(@mdebarros @elnyry @rmothilal )
        - [ ] README.md
    - **mojaloop-specifications**(@elnyry )
        - [x] API Definition v1.0.pdf
        - [x] Generic Transaction Patterns.pdf
        - [x] JSON Binding Rules.pdf
        - [x] LICENSE.md
        - [x] Logical Data Module.pdf
        - [x] PKI Best Practices.pdf
        - [x] README.md
        - [x] Scheme Rules.pdf
        - [x] UseCases.pdf
    - **mojaloop**(@kjw000 )
        - [x] FAQ.md
        - [x] README.md
        - [x] LICENSE.md
        - [x] contribute.md
        - [x] requirements.md
            - **contribute** (sub directory)
            - [x] Architecture-Documentation-Guidelines.md
            - [x] Branching-Strategy.md
            - [x] Building-and-Publish-NodeJS.md
            - [x] Code-Quality-Metrics.md
            - [x] Code-Style.md
            - [x] Decision-Items.md
            - [x] Documentation-Style-Guide.md
            - [x] Documentation-and-Template-Standards.md
            - [x] GitHub-Lables.md
            - [x] License.md
            - [x] Local-K8s-Developement-Guide.md
            - [x] Moving-issues-from-docs-to-another-repo.md
            - [x] Onboarding-Developers.md
            - [x] Pipeline.md
            - [x] Pragmatic-REST-Guidelines.md
            - [x] README-Template.md
            - [x] Readme.md
            - [x] Reporting-Bugs.md
            - [x] Repos-and-versioning.md
            - [x] Roadmap.md
            - [x] Scenarios-and-Epics.md
            - [x] Structure-of-the-Documentation.md
            - [x] Terminology.md
            - [x] Testing-strategy.md
            - [x] Tools-technology-and-process-choices.md
            - [x] Writing-Code.md
    - **interop-devops** (@jeffplesko @elnyry )
        - [x] LICENSE.md [@elnyry]
        - [x] README.md [@elnyry]
        - [x] README_EC2.md [@elnyry]
        - [x] README_VAGRANT.md [@elnyry]
        - [x] Swagger.md -> Renamed to Endpoint_details.md (It is not a Swagger, wrongly named) [@elnyry]
        - [ ] ~README.md~ Duplicate
    - **interop-common** (@elnyry @kjw000 )
        - [x] LICENSE.md [@elnyry]
        - [x] README.md [@elnyry]
    - **interop-parent**(@elnyry @kjw000 )
        - [x] LICENSE.md [@elnyry]
        - [x] README.md [@elnyry]
    - **project**
        - [ ] README.md
    - **interop-domain**
        - [x] LICENSE.md [@elnyry]
        - [x] README.md [@elnyry]
    - **mojaloop.github.io**(@kjw000 )
        - [ ] LICENSE.md
        - [ ] README.md (document required)

**Acceptance Criteria**:
- [ ] All documents in all repositories are updated and promoted to the "master" branch for each repository listed as "CORE" or "RELATED" to mojaloop.

**PRs**
 - [x] https://github.com/mojaloop/docs/pull/92

**Dependencies**:
- [ ] None currently

**Accountability**:
- Owner 
- QA/Review

**Comment by kjw000** [comment]
updated my sections and they are in master.
