### ISSUE TITLE
Settle Window and Adjust Positions - Risk managed after Settlement

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#528]
**Goal**:
As a Hub Operator
I want to _manage Settlements while updating positions independent of the Settlement bank_
so that _even while the Settlement process is in progress, the FSPs can operate against their settled Positions_; this relies on the Scheme Rules to provide consistency

**Tasks**:
- [x] Update seeds [@ggrg]
- [x] Update diagram 6.2.1. Trigger Settlement Event (createSettlement) -- NOT_SETTLED [@ggrg]
- [x] Update diagram 6.3.1. Settlement Transfer Prepare (Received_Prepare) [@ggrg]
- [x] Add new diagram 6.3.2. Settlement Transfer Reserve (using current 6.3.1.) [@ggrg]
- [x] Add new diagram 6.3.3. Settlement Transfer Commit (using current 6.3.2.) [@ggrg]
- [x] Update diagram 6.2.5. Acknowledgement of Settlement Transfer (updateSettlementById) with ref. to 6.3.1., 6.3.2., 6.3.3. [@ggrg]
- [ ] ~Add diagram 6.3.4. Settlement Transfer Abort (using new 6.3.3.)~
- [ ] ~Create new diagram 6.2.6. Abort Settlement (abortSettlementById) with ref. to 6.3.4.~
- [x] Implement required HUB_MULTILATERAL_SETTLEMENT account when creating Dfsp POSITION account [@ggrg]
- [x] Implement changes in **createSettlement** (6.2.1.) [@ggrg]
- [x] Implement Record Settlement Transfer Received_Prepare method (6.3.1.) [@ggrg]
- [x] Implement Reserve Settlement Transfer Reserve method (6.3.2.) [@ggrg]
- [x] Implement Commit Settlement Transfer Commit method (6.3.3.) [@ggrg]
- [x] Implement changes in **updateSettlementById** - Record, Reserve, Commit & Settle a Settlement, utilising the previous 3 methods (6.2.5.)
- [ ] ~Implement Abort Settlement Transfer Abort method, reverting positions when needed (6.3.4.)~
- [ ] ~Create new endpoint `PUT /settlements/{ID}/abort` and implement **abortSettlementById** (6.2.6.)~
- [x] Update demo scripts to cover all operations [@ggrg]
- [x] Update sequence diagrams according to the implementation [@ggrg]
- [x] Fix Inspect Code errors and warnings for src/models/settlement/facade.js & test/unit/models/settlement/facade.test.js [@ggrg] ([commit](https://github.com/ggrg/central-settlement/commit/2a122861acdc9ffe51c8b4a39192a29303541a15))
- [x] Preparation for the Sprint Demo [@ggrg] ([commit](https://github.com/ggrg/central-settlement/commit/0a77b653614347f75be7d75b5c439f6b25c3e5de))
- [x] Unit tests
  - [x] Fix broken unit tests [@ggrg] ([commit](https://github.com/ggrg/central-settlement/commit/3cc21b21141c565252cc33d848d353e52716cac0))
  - [x] Provide > 90% code coverage [@ggrg] ([commit](https://github.com/ggrg/central-settlement/commit/cfabb7697c30e5073760ecf79d2279efdd062e49)) achieved 98%+

**Pull Requests**:
- [x] https://github.com/mojaloop/central-settlement/pull/50
- [x] https://github.com/mojaloop/central-ledger/pull/210
- [x] https://github.com/mojaloop/docs/pull/95

**Acceptance Criteria**:
When submitted via a Secure Postman request, verify that for…
- [x] Create: `POST /settlements`
  - [x] Settlement windows in state NOT_SETTLED may be added to new settlement together with settlement windows in CLOSED state
- [x] Prepare: `PUT /settlements/{ID}`
  - [x] Settlement set to PS_TRANSFERS_RECORDED
  - [x] All Transfers from Position account to HUB_MULTILATERAL_SETTLEMENT (MLNS) account are created and are set to RECEIVED_PREPARE state.
  - [x] No positions are changed
- [x] Reserve: `PUT /settlements/{ID}`
  - [x] Settlement set to PS_TRANSFERS_RESERVED
  - [ ] All Transfers from POSITION account to MLNS account are set to RESERVED state.
  - [x] Positions in POSITION and MLNS are affected for DR
- [x] Commit: `PUT /settlements/{ID}`
  - [x] Settlement set to PS_TRANSFERS_COMMITTED
  - [x] All Transfers from POSITION account to MLNS account are set to RESERVED state.
  - [x] Positions in POSITION and MLNS are affected for CR
- [x] Settle: `PUT /settlements/{ID}`
  - [x]  Settlement set to SETTLED
  - [x] Transfers & positions not affected (already COMMITTED)
- [ ] ~Abort: `PUT /settlements/{ID}/abort`~
  - [ ] ~Settlement set to NOT_SETTLED~
  - [ ] ~All Transfers from POSITION account to MLNS account are set to ABORTED state.~
  - [ ] ~If aborted from PS_TRANSFERS_RESERVED, DR Positions for POSITION and MLNS are reverted back~

**Implementation notes**:
- Create a follow-up story for Reconciliation
- In new approach, the risk of unavailable funds is managed after settlement whereas in the earlier approach (not preserved), the risk is managed during the Settlement process
- Settlement existing states - PENDING_SETTLEMENT, SETTLED, ABORTED (new needed - PS_TRANSFERS_RECORDED, PS_TRANSFERS_RESERVED, PS_TRANSFERS_COMMITTED, SETTLING)
- POST /settlements - (CLOSED and NOT_SETTLED windows) to PENDING_SETTLEMENT
- PUT /settlements/{ID} - PS_TRANSFERS_RECORDED, PS_TRANSFERS_RESERVED, PS_TRANSFERS_COMMITTED, (SETTLING as result of previous), SETTLED
- PUT /settlements/{ID}/abort - (NOT_SETTLED as result of the request, when allowed)

**Dependencies**:
- none

**Accountability**:
- Owner @ggrg @wdcmb 
- QA/Review @RobReeve
