### ISSUE TITLE
Update DB Host name in Central Ledger Helm Chart

### ISSUE THREAD

**Issue by ksatya77** [mojaloop/project#532]
**Goal**:
As a Contributor
I want to _update the helm charts to use a generic database hostname_
so that _these charts can be used in instances where a managed DB is used outside of Kubernetes cluster_.

**Tasks**:
- [ ] Update dbHost variable in the secret for Central Ledger related Helm charts

**Pull Requests**:
- [ ] 

**Acceptance Criteria**:
- [ ] Should work with DB hosts that are both part of the cluster and outside of the cluster
- [ ] Central Ledger components should deploy successfully
  

**Implementation notes**:

**Dependencies**:
- none

**Accountability**:
- Owner @ksatya77 
- QA/Review @mdebarros @elnyry
