### ISSUE TITLE
Settle Window and Adjust Positions - Transfer Abort

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#535]
**Goal**:
As a Hub Operator
I want to _manage Settlements while updating positions independent of the Settlement bank_
so that _even while the Settlement process is in progress, the FSPs can operate against their settled Positions_; this relies on the Scheme Rules to provide consistency

**Tasks**:
- [x] Create new diagram 6.2.6. Abort Settlement (abortSettlementById) with ref. to 6.3.4. [@ggrg]
- [x] Add diagram 6.3.4. Settlement Transfer Abort [@ggrg]
- [x] Present for DA review and apply DA recommendations [@ggrg]
- [x] Add RECEIVED_FULFIL transferState entry prior to COMMITTED [@ggrg]
- [x] Create new endpoint `PUT /settlements/{ID}` and implement abortSettlementById (6.2.6.) [@ggrg]
- [x] Implement Abort Settlement Transfer Abort method, reverting positions when needed (6.3.4.) [@ggrg]
- [x] Added reason and changedDate to settlement.getById [@ggrg]
- [x] Fixed bug when creating new settlement with ABORTED windows [@ggrg]
- [x] Add REJECTED transferStateChange entry prior to ABORTED [@ggrg]
- [x] Test settlements may be created with windows in ABORTED state [@ggrg]
- [x] **Improved**: settlement getById now also returns settlement level information as reason, createdDate, changedDate [@ggrg]
- [x] **Improved**: settlementEventTrigger error placeholders were updated with descriptive errorInformation and also return settlement level info for reason, createdDate and changedDate [@ggrg]
- [x] **Technical Debt**: as Swagger 2.0 does not support anyOf, all accepted payload attributes are optional and further validated programatically. For more information see the comment below (definitions.SettlementUpdatebySettlementIdPayload). [@ggrg]
- [x] Update sequence diagrams to match implementation [@ggrg]
- [x] Fix broken unit tests [@ggrg]
- [x] Update demo scripts to cover abort operation [@ggrg]
- [x] Write new unit tests and provide full coverage, if possible [@ggrg]

**Pull Requests**:
- [x] https://github.com/mojaloop/docs/pull/96
- [x] https://github.com/mojaloop/central-settlement/pull/51
- [x] https://github.com/mojaloop/central-ledger/pull/213
- [x] https://github.com/mojaloop/central-settlement/pull/55
- [x] https://github.com/mojaloop/docs/pull/103

**Acceptance Criteria**:
- [x] Abort: `PUT /settlements/{ID}`
  - [x] Settlement set to ABORTED
  - [x] All Transfers from POSITION account to MLNS account are set to ABORTED state.
  - [x] If aborted from PS_TRANSFERS_RESERVED, DR Positions for POSITION and MLNS are reverted back

**Implementation notes**:
- Create a follow-up story for Reconciliation
- In new approach, the risk of unavailable funds is managed after settlement whereas in the earlier approach (not preserved), the risk is managed during the Settlement process
- PUT /settlements/{ID} - (ABORTED as result of the request, when allowed)

**Dependencies**:
- none

**Accountability**:
- Owner @ggrg @wdcmb 
- QA/Review @RobReeve

**Comment by ggrg** [comment]
```
"definitions": {
    "SettlementUpdatebySettlementIdPayload": {
        "type": "object",
        "properties": {
            "state": {
                "type": "string",
                "enum": [
                    "ABORTED"
                ]
            },
            "reason": {
                "type": "string"
            },
            "externalReference": {
                "type": "string"
            },
            "participants": {
                "type": "array",
                "items": {
                    "$ref": "#/definitions/SettlementUpdateBySettlementIDOuterPayload"
                }
            }
        }
    },
```
