### ISSUE TITLE
Sequence diagrams for FundsIn/FundsOut flows

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#536]
**Goal**:
As a Switch
I want to _provide sequence diagrams for FundsIn/FundsOut flows_
so that _the design for the FundsIn and FundsOut flow_ are provided with clarity and details.

**Tasks**:
- [x] Sequence diagram for FundsIn flows [@ggrg]
    - [x] Change of positions to be incorporated into the **reserve**, **commit** steps [@ggrg]
- [x] Sequence diagram for FundsOutPrepareReserve [@ggrg]
    - [x] Change of positions to be incorporated into the **reserve**, **commit** steps [@ggrg]
- [x] Sequence diagram for FundsOutCommit [@ggrg]
    - [x] Change of positions to be incorporated into the **reserve**, **commit** steps [@ggrg]
- [x] Sequence diagram for FundsOutAbort [@ggrg]
    - [x] Change of positions to be incorporated into the **reserve**, **commit** steps [@ggrg]
- [x] Reviews to be done [@ggrg]
- [x] Amendments according to the DA review

**Pull Requests**:
- [ ] https://github.com/mojaloop/docs/pull/98
- [ ] https://github.com/mojaloop/docs/pull/99

**Acceptance Criteria**:
- [x] Sequence diagrams for FundsIn and FundsOut flows with updated flows regarding position changes are provided and reviewed

**Dependencies**:
- none

**Notes**:
- Link to a recording discussing the changes: https://modusbox.zoom.us/recording/play/T3FgMHNmjcpXHVi5n-cRuDvKgEkjqFXLsALrbfMnOW37K12SOf7-d3EY5pjTuBn7?continueMode=true

**Accountability**:
- Owner @ggrg
- QA/Review @RobReeve
