### ISSUE TITLE
Update accounts to be active only after initial positions, limits are set

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#537]
**Goal**:
As a Hub Operator
I want to _set an account that was newly created to be active only after the complete on-boarding process is complete by setting initial positions and limits_
so that _the all the pre-requisites are followed_ during the account creation process (and onboarding) and consistency of the transfers process is ensured..

**Tasks**:
- [x] Create accounts by default initially to be inactive -- [@shashi165]
- [x] Only set the accounts to be active after the final step of on-boarding process - possibly during the step where initial limits and positions are set -- [@shashi165]
- [x] Automated tests -- [@shashi165]

**Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/217

**Acceptance Criteria**:
- [x] The on-boarding process for FSPs and accounts provides consistency so that accounts can be used to transact only after the initial limits and positions are set.

**Dependencies**:
- none

**Accountability**:
- Owner @shashi165 
- QA/Review @RobReeve @elnyry

**Comment by elnyry** [comment]
Merged to develop, closing this (will be released in the version after 4.1.0, most likely 4.1.1)
