### ISSUE TITLE
Follow-up changes in implementation to FundsIn, FundsOut flows following the design changes in #536

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#538]
**Goal**:
As a Switch
I want to _update the implementation to follow the updated design for FundsIn/FundsOut flows_
so that _the FundsIn and FundsOut flows cater to the updated designs_

**Tasks**:
- [ ] Implementation changes for FundsIn flows
    - [ ] Change of positions to be incorporated into the **reserve**, **commit** steps
- [ ] Implementation changes for FundsOutPrepareReserve
    - [ ] Change of positions to be incorporated into the **reserve**, **commit** steps
- [ ] Implementation changes for FundsOutCommit [@ggrg]
    - [ ] Change of positions to be incorporated into the **reserve**, **commit** steps
- [ ] Implementation changes  for FundsOutAbort
    - [ ] Change of positions to be incorporated into the **reserve**, **commit** steps
- [ ] Automated tests

**Pull Requests**:
- [ ] 

**Acceptance Criteria**:
- [x] Implementation for the FundsIn, FundsOut flows follow/adhere to the Sequence diagrams for FundsIn and FundsOut flows (#536 )

**Dependencies**:
- none

**Notes**:
- Link to a recording discussing the changes: https://modusbox.zoom.us/recording/play/T3FgMHNmjcpXHVi5n-cRuDvKgEkjqFXLsALrbfMnOW37K12SOf7-d3EY5pjTuBn7?continueMode=true

**Accountability**:
- Owner @ggrg
- QA/Review @RobReeve
