### ISSUE TITLE
Making Hub participant ID configurable instead of setting it to '1'

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#547]
**Goal**:
As a Switch
I want to _make the Hub's participant ID configurable_
so as to avoid _using numbers that create data inconsistency while upgrading and such others_

**Tasks**:
- [x] Create config values HUB_NAME and HUB_ID [@ggrg]
- [x] Use those (above) everywhere in central-ledger and central-settlement [@ggrg]
- [x] Fix broken unit tests [@ggrg]
- [x] Write new unit tests and provide full coverage, if possible [@ggrg]

**Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/220
- [x] https://github.com/mojaloop/central-settlement/pull/54

**Acceptance Criteria**:
- [x] Hub Participant IDs are configurable using config values HUB_NAME and HUB_ID

**Implementation notes**:
- The initial values for the above would be ‘Hub’ and 1 respectively, but may be changed when needed

**Dependencies**:
- none

**Accountability**:
- Owner @ggrg 
- QA/Review @wdcmb
