### ISSUE TITLE
Optimize helm to have manageable values yaml files

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#553]
**Goal**:
As a DevOps team member
I would like to _optimize helm repo to optimize values yaml files used by extracting knex, default.json values out of values files_
so that _helm updates and releases can be more manageable_

**Tasks**:
- [x] Optimize helm repo by extracting knex and default configs [ @shashi165 , @mdebarros ]
- [x] start mysql init container [ @shashi165 , @mdebarros ]
- [x] Validate, test and publish [ @shashi165 , @mdebarros ]

**Acceptance Criteria**:
- [x] Optimize helm config by extracting out knex and other common config 

**PRs**
 - [x] https://github.com/mojaloop/helm/pull/126
 - [x] https://github.com/mojaloop/helm/pull/128

**Dependencies**:
- [ ] None currently

**Accountability**:
- Owner @shashi165 
- QA/Review @mdebarros 

**Notes**:
- One side-effect is that the granularity for control is lost a bit, so if there is a need for a specific config item, a request needs to be raised and then it can be exposed to be available (so that it can be configured as needed)
