### ISSUE TITLE
Automated testing - unit, etc tests for central-event-processor component

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#558]
**Goal**:
As a QA
I would like to _have (automated) unit tests for the CEP component_
to ensure quality and avoid regressions.

**Tasks**:
- [ ] Unit tests/src
   - [x] Kafka : Consumer
   - [x] Kafka : Producer
   - [ ] Kafka : Index
   - [x] Lib: Config
   - [x] Lib: Database
   - [x] Lib: Enum
   - [ ] Lib: Utility
   - [x] Models: Action
   - [x] Models: Events
   - [x] Models: Limits
   - [x] Models: Current Position
   - [x] Models: Notification Endpoint
   - [ ] Observables: Setup
   - [ ] Observables: index
   - [ ] Observables: actions
   - [ ] Observables: CentralLedgerAPI
   - [ ] Rules: Index
   - [ ] Rules: ndcAdjustment
   - [ ] Rules: ndcBreach
       
- [ ] Enable unit tests phase in the CI/CD
- [ ] Ensure unit tests run as part of the CI/CD process

**Acceptance Criteria**:
- [ ] Unit test framework is available for CEP component that runs with every build and PR on GitHub to ensure quality

**PRs**
 - [ ] 

**Dependencies**:
- [ ] 

**Accountability**:
- Owner 
- QA/Review
