### ISSUE TITLE
Automated testing - unit, etc tests for email-notifier component

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#559]
**Goal**:
As a QA
I would like to _have (automated) unit tests for the email-notifier component_
to ensure quality and avoid regressions.

**Tasks**:
- [x] Unit tests
- [x] Enable unit tests phase in the CI/CD
- [x] Ensure unit tests run as part of the CI/CD process

**Acceptance Criteria**:
- [x] Unit test framework is available for email-notifier component that runs with every build and PR on GitHub to ensure quality

**PRs**
 - [x] https://github.com/mojaloop/email-notifier/pull/22

**Dependencies**:
- [ ] 

**Accountability**:
- Owner 
- QA/Review
