### ISSUE TITLE
Investigate/Design error handling mechanism (avoid hard coding) to send out errorCodes, messages as per Spec

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#561]
**Goal**:
As a Switch
I would like to _send appropriate error codes & messages based on the Specification_
to ensure conformation

**Tasks**:
- [ ] Investigate/design mechanism (or package) that serves the purpose and enables mapping error codes/messages based on error conditions without hardcoding
- [ ] PoC
- [ ] Create follow-up story for implementation or use #520 / #521 / #522 

**Acceptance Criteria**:
- [ ] A recommendation is made for the design/strategy to be used for error handling, mapping to the codes in the specification and returning error codes

**PRs**
 - [ ] 

**Dependencies**:
- [ ] 

**Accountability**:
- Owner 
- QA/Review 

**Notes**:
Refer to comments on the issue mojaloop/central-ledger/issues/282

**Comment by elnyry** [comment]
Duplicate of #830
