### ISSUE TITLE
GET /transfers/{ID} functionality for Settlements transfers

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#564]
**Goal**:
As a Switch
I would like to _ensure that Settlements transfers respond to GET /transfers/{ID} similar to P2P transfers_
so as to have uniformity and conform to the Spec

**Tasks**:
- [x] Investigate, record current functionality on how data is currently returned for GET /transfers on Settlement transfers [@ggrg]
- [x] Documented findings in Slack. DA decision is required. [@ggrg]
- [x] Implement changes necessary to make the PUT callback have the same Schema and data as that of normal P2P transfers (PUT responses) [@ggrg]
- [x] Automated tests, 100% coverage [@ggrg]

**Acceptance Criteria**:
- [x] A GET /transfers/{ID} call on a Settlement transfer has the same schema as that of a GET call on a P2P transfers call (both follow the same Spec and have the same Schema)

**PRs**
 - [x] https://github.com/mojaloop/central-ledger/pull/228

**Dependencies**:
- none

**Accountability**:
- Owner 
- QA/Review
