### ISSUE TITLE
Check FSPIOP-Source for GET /transfers and respond only when the transfer is associated with that FSP

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#565]
**Goal**:
As a Switch
I would like to _verify that a response for a GET /transfers request is sent only if the calling FSP is part of that transfer_
for security, confidentiality purposes.

**Tasks**:
- [x] Implement verification/validation to respond to a GET /transfers request only if the FSP in the FSPIOP-Source header is part of the transfer (a Payer or Payee) -- [@shashi165]
- [x] Tests  -- [@shashi165]

**Acceptance Criteria**:
- [x] A response for a GET /transfers request is sent only if the calling FSP is part of that transfer (otherwise error is sent)

**PRs**
 - [x]  https://github.com/mojaloop/central-ledger/pull/227

**Dependencies**:
- [ ] 

**Accountability**:
- Owner 
- QA/Review
