### ISSUE TITLE
Notification for NetDebitCap changes - publish to notifications and send email based on the change

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#566]
**Goal**:
As a Switch
I would like to _send email alerts for changes to NetDebitCap or Position adjustments (only adjustments based on Position resets, not changes)_
so that participating FSPs and the Hub Operator can be notified of such changes

**Tasks**:
- [x] Publish a message to the notifications topic for changes in NetDebitCap from central-ledger api [@vgenev]
- [x] Publish a message to the notifications topic for initialization of the NetDebitCap from central-ledger api [@vgenev]
- [x] Update CEP to get message from notifications topic for changes in NetDebitCap limit based on the message published by before task [@vgenev]
- [x] Make only threshold breach event to work with "spam control oscilation" [@vgenev]
- [x] Update CEP to get data for Threshould breach adjustment to relay on the limit data from the message instead of making another API call [@vgenev]
- [x] Update kafka lib code in CEP
- [x] Update kafka lib code in Email Notifier  
- [x] Update the messages in CEP, Email Notifier and Central Ledger to match the standard message format used in the central-settlement task [@vgenev @bothadeon]
  - [x] Add limit-adjustment action to the Central Ledger topic map [@vgenev]
  - [x] Add Enums for Hub operator as it was done in the Settlements service [@vgenev]
     - ~[ ] central ledger~
     - [x] CEP [@vgenev]
     - [x] email-notifier [@vgenev]
  - [x] Change the code of CEP to react on limit-adjustment event action [@vgenev]
  - [x] Change the code of CEP to produce message with event action dedicated to email notifier [@vgenev]
  - [x] Change the code of the email notifier to react on dedicated messages [@vgenev]
- [x] Update central-settlements to be able to publish a message to the notifications topic [@ggrg]
- [x] Define and use standard message format [@ggrg]
- [x] Publish a message for Position Adjustments based on Settlements [@ggrg]
- [x] Test functionality and add unit tests for full coverage of settlement [@ggrg]
- [x] Update current functionality to send email alerts for changes in NetDebitCap based on settlement transfers (but only based on the update notifications published now) [@bothadeon]
- [x] Format percentage of position left in the email notification to have two decimal places [@vgenev]
- [ ] ~Edit email text for clarity~
- [ ] ~Tests~
- [x] Update flow diagrams to UML [@bothadeon @HenkKodde @vgenev ]

**Acceptance Criteria**:
- [x] An email alert (or notification) is sent to an FSP when a change is made to the Net Debit Cap
- [x] An email alert (or notification) is sent to an FSP when a Position adjustment (based on Position resets) is done

**PRs**
 - [x] https://github.com/mojaloop/central-settlement/pull/57
 - [x] https://github.com/mojaloop/central-ledger/pull/236
 - [x] https://github.com/mojaloop/central-ledger/pull/238
 - [x] https://github.com/mojaloop/central-settlement/pull/58
 - [x] https://github.com/mojaloop/central-event-processor/pull/20
 - [x] https://github.com/mojaloop/email-notifier/pull/15
 - [x] https://github.com/mojaloop/central-event-processor/pull/14

**Dependencies**:
- [ ] 

**Accountability**:
- Owner @bothadeon , @vgenev 
- QA/Review @RobReeve

**Comment by vgenev** [comment]
Publish a message to the notifications topic for Position Adjustments based on Settlements - at the moment, to solve that task we need either to connect settlements to Kafka topics or expose endpoint to the central-ledger admin services that will receive notification from the settlement and forward by publishing to the notification topic. @elnyry @RobReeve @ggrg @bothadeon we need to discuss which will be the approach for that

**Comment by ggrg** [comment]
@vgenev, @bothadeon, please notice the message that gets posted to notification topic:
```
{
  "id": "86ce97cf-2302-4d64-8b0e-df5ae9355dd0",
  "from": "central-switch",
  "to": "dfsp2",
  "content": {
    "headers": {
      "Content-Type": "application/json",
      "Date": "2019-01-17T14:46:48.918Z",
      "FSPIOP-Source": "central-switch",
      "FSPIOP-Destination": "dfsp2"
    },
    "payload": {
      "currency": "USD",
      "value": 0,
      "changedDate": "2019-01-17T14:46:48.918Z"
    }
  },
  "type": "application/json",
  "metadata": {
    "event": {
      "id": "5c7ff308-35be-46b0-b187-0bf4bee72cf8",
      "type": "notification",
      "action": "settlement-transfer-position-change",
      "state": {
        "status": "success",
        "code": 0,
        "description": "action successful"
      }
    },
    "protocol.createdAt": 1547736408918
  }
}
```

**Comment by HenkKodde** [comment]
Pull request for notification diagrams.
https://github.com/mojaloop/central-event-processor/pull/14
