### ISSUE TITLE
Changing log level of health checks to 'debug' from 'info'

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#567]
**Goal**:
As a DevOps team member
I would like the _log level of health checks of central services to 'debug' from 'info' _
for better visibility of functionality related logs in normal cases (with the option to turn on 'debug' when needed) and for easier debugging.

**Tasks**:
- [x] Change log level of health checks of central services from 'into' to 'debug'
- [x] Validate

**Acceptance Criteria**:
- [x] Health check logs are configured to be 'debug' level (and not 'info')

**PRs**
 - [x]  https://github.com/mojaloop/central-ledger/pull/229

**Dependencies**:
- [ ] 

**Accountability**:
- Owner @shashi165 
- QA/Review
