### ISSUE TITLE
Settlements demonstrations, presentation for Phase-3 kick-off

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#568]
**Goal**:
As a contributor
I would like the _prepare the demos and presentations for the Settlements topic_
so that they can be presented at the ML Phase-3 kickoff event.

**Tasks**:
- [x] Finalize scope and functionality to demo for the Settlements topic [@ggrg]
- [x] Finalize demo [@ggrg] _**Q**: ledgerEntryType: SETTLEMENT_NET_ZERO_
- [x] Prepare slides for the Settlements topic [@ggrg]
- [x] Record scripts/postman demo video [@ggrg]
- [x] Complete the review of slides [@ggrg]

**Acceptance Criteria**:
- [x] The Settlements demos for the ML Phase-3 kickoff event are finalized
- [x] The slides for the Settlements topic for the ML Phase-3 kickoff event are finalized

**Dependencies**:
- none

**Accountability**:
- Owner @ggrg 
- QA/Review @elnyry @wdcmb
