### ISSUE TITLE
QA Regression testing framework demonstration, presentation for Phase-3 kick-off

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#569]
**Goal**:
As a contributor
I would like the _prepare the demos and presentations for the QA Regression testing framework topic_
so that they can be presented at the ML Phase-3 kickoff event.

**Tasks**:
- [x] Finalize scope and functionality to demo for the QA Regression testing framework [@NicoDuvenage]
- [x] Finalize demo
- [x] Prepare slides
- [x] Complete the review of slides
- [x] Finalise Documentation on the repository for creating, installing and running a Test Server

**Acceptance Criteria**:
- [x] The QA Regression testing framework demo for the ML Phase-3 kickoff event is finalized
- [x] The slides for the Settlements topic for the ML Phase-3 kickoff event are finalized

**Dependencies**:
- [ ] 

**Accountability**:
- Owner @NicoDuvenage  
- QA/Review @elnyry @wdcmb
