### ISSUE TITLE
Prioritizing items and backlog preparation for Phase-3 kick-off

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#570]
**Goal**:
As a contributor
I would like the _prepare the backlog with prioritized items for Mojaloop Phase-3_
so that it can be used as basis for discussions at the phase-3 kick-off event and upon approval used as basis for the Program Increments moving forward.

**Tasks**:
- [x] Understand, propose scope of the seven NFRs and five FRs
- [x] Update Epics, high-level topics
- [x] Update acceptance criteria for the Epics (and rename for relevance)
- [x] Update stories
- [x] Complete the review of the board
- [x] Update release details and add dates

**Acceptance Criteria**:
- [x] A managed backlog for agreed upon NFRs and FRs is available for review at Phase-3 kickoff event

**Dependencies**:
- [ ] 

**Accountability**:
- Owner @elnyry 
- QA/Review @wdcmb
