### ISSUE TITLE
Instrumentation for metrics into central services

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#572]
**Goal**:
As a Hub Tech Operator or Hub DevOps
I would like the _add instrumentation to the Switch central services_
to enable operational monitoring and identify status/metrics and issues if any.

**Tasks**:
- [ ] Create a library that enables instrumentation
- [ ] central-services-metrics
  - [ ] Create
  - [ ] Add CI/CD 
  - [ ] Release for use
- [ ] Add this to central services to enable instrumentation
- [ ] Validate

**Acceptance Criteria**:
- [ ] A library that supports instrumentation for metrics to be used with central services is provided and released.
- [ ] Instrumentation is provided for the central services

**Dependencies**:
- [ ] 

**Accountability**:
- Owner @shashi165  
- QA/Review @rmothilal @mdebarros
