### ISSUE TITLE
Updating documentation based on features delivered this Sprint

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#573]
**Goal**:
As a Hub Tech Operator or Hub DevOps
I would like the _update documentation (or review them) for features being delivered in the current Sprint_
so that the docs are kept up-to-date with the feature work being done.

**Tasks**:
- [ ] Add details of repo and features being delivered
- [ ] Update docs as relevant with links
- [ ] Get reviews done and merge with master

**Acceptance Criteria**:
- [ ] For the above mentioned (in the tasks) features that are delivered in the current Sprint, docs are updated to stay up-to-date

**Dependencies**:
- [ ] 

**Accountability**:
- Owner @HenkKodde   
- QA/Review @elnyry

**Comment by elnyry** [comment]
Henk covered these tasks as part of individual items
