### ISSUE TITLE
Refactor logger library to write to log files asynchronously

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#574]
**Goal**:
As a developer
I would like to _refactor logger library to write to log files asynchronously (instead of writing to the console synchronously)_
to improve performance.

**Tasks**:
- [x] Update Code to work with Winston V3
- [x] Publish to NPM
- [x] add dependency to required central repositories
- [x] Update helm and kubernetes config to read logs from new log file
- [x] Test on performance environment

**Acceptance Criteria**:
- [x] Logger library is refactored to write logs asynchronously to files (instead of synchronously logging to console)

**Dependencies**:
- N/A

**Accountability**:
- Owner @rmothilal    
- QA/Review @mdebarros

**Comment by rmothilal** [comment]
@elnyry this story needs DA approval
