### ISSUE TITLE
Performance Enhancement - Combine Transfer Prepare Topics

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#575]
## **Goal**:
As a hub-operator
I want to combine the Transfer Prepare Topics
so that the Transfer Prepare process is more performant and less CPU intensive

**Tasks**:

#### ml-api-adapter
- [x] Update Transfer Prepare Producer to send messages using a new template that matches the following - [@shashi165]
``` JSON
      "GENERAL_TOPIC_TEMPLATE": {
        "TEMPLATE": "topic-{{functionality}}-{{action}}",
        "REGEX": "topic-(.*)-(.*)"
      }
```
Instead of the DFSP specific topic:
``` JSON
      "PARTICIPANT_TOPIC_TEMPLATE": {
        "TEMPLATE": "topic-{{participantName}}-{{functionality}}-{{action}}",
        "REGEX": "topic-(.*)-(.*)-(.*)"
      },
```
- [x] Ensure that the Message Key for the message produced by the Transfer Prepare Producer uses the Transfer ID (UUID) ~ (e.g. createGeneralTopicConf should map an opaqueKey to the key within the `topicCon`) - [@shashi165]
- [x] Sequence Diagrams to be updated - [@shashi165]
- [x] Architecture Diagrams to be updated - [@mdebarros]
- [x] Update Unit Tests - [@shashi165]
- [x] Update Integration Tests - [@shashi165]

#### central-ledger
- [x] Update Prepare Handler to consume from the `topic-transfer-prepare` topic - [@shashi165]
- [x] Remove the Kafka cron-job to register DFSP Specific Prepare Handlers - [@shashi165]
- [x] Update Unit Tests - [@shashi165]
- [x] Update Integration Tests - [@shashi165]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Sequence Diagrams are updated
- [ ] Architecture Diagrams are updated
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-api-adapter/pull/83
- [x] https://github.com/mojaloop/central-ledger/pull/234
- [x] https://github.com/mojaloop/docs/pull/107
- [ ] https://github.com/mojaloop/docs/pull/108

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
