### ISSUE TITLE
Performance Enhancement - Combine Transfer Position Topics

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#576]
## **Goal**:
As a Hub-operator
I want to combine the Transfer Position Topics
so that the Transfer Position process is more performant and less CPU intensive

**Tasks**:

#### central-ledger
- [x] Update Transfer Prepare Producer to send position messages using a new template that produces messages to - [@shashi165]
``` JSON
      "GENERAL_TOPIC_TEMPLATE": {
        "TEMPLATE": "topic-{{functionality}}-{{action}}",
        "REGEX": "topic-(.*)-(.*)"
      }
```
Instead of the DFSP specific topic:
``` JSON
      "PARTICIPANT_TOPIC_TEMPLATE": {
        "TEMPLATE": "topic-{{participantName}}-{{functionality}}",
        "REGEX": "topic-(.*)-(.*)-(.*)"
      }
```
- [x] Update ~Prepare~ position Handler to consume from the `topic-transfer-position` topic - [@shashi165]
- [x] Remove the Kafka cron-job to register DFSP Specific Position Handlers - [@shashi165]
- [x] Ensure that the Message Key for the message produced by the Transfer Prepare Handler uses the DFSP ID instead of a UUID ~ (e.g. createGeneralTopicConf should map an opaqueKey to the key within the topicCon) - [@shashi165]
- [x] Ensure that the Message Key for the message produced by the Transfer Fulfil Handler uses the DFSP ID instead of a UUID ~ (e.g. createGeneralTopicConf should map an opaqueKey to the key within the topicCon) - [@shashi165]
- [x] Sequence Diagrams to be updated - [@shashi165]
- [ ] Architecture Diagrams to be updated - [@mdebarros]
- [x] Update Unit Tests - [@shashi165]
- [x] Update Integration Tests - [@shashi165]

- [x] Fix the kafka message Key and opequeKey(these 2 are different) - [@shashi165]

**Acceptance Criteria**:
- [x] The transfers flow, end-to-end designs are up-to date
- [x] Sequence Diagrams for changes in transfers are updated
- [x] Architecture Diagrams are updated
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/237
- [x] https://github.com/mojaloop/ml-api-adapter/pull/84
- [x] https://github.com/mojaloop/docs/pull/110

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
