### ISSUE TITLE
Performance Enhancement- align Kafka Configs

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#577]
## **Goal**:
As a hub-operator I want to combine the Kafka Configs to be optimised so that the Transfer process is more performant and less CPU intensive

**Tasks**:

#### ml-api-adapter
- [x] Update the Notification Consumer config to match the Performance Branch - [@shashi165]
- [x] Update the Transfer Prepare Producers config to match the Performance Branch - [@shashi165]
- [x] Update the Transfer Fulfil Producers config to match the Performance Branch - [@shashi165]
- [ ] ~Sequence Diagrams to be updated~
- [ ] ~Architecture Diagrams to be updated~
- [x] Update Unit Tests - [@shashi165]
- [x] Update Integration Tests - [@shashi165]

#### central-ledger
- [x] Update the Transfer Prepare Consumer config to match the Performance Branch - [@shashi165]
- [x] Update the Transfer Position Consumer config to match the Performance Branch - [@shashi165]
- [x] Update the Transfer Fulfil Consumer config to match the Performance Branch - [@shashi165]
- [x] Update the Transfer Reject Consumer config to match the Performance Branch - [@shashi165]
- [x] Update the Transfer ADMIN Consumer config to match the Performance Branch - [@shashi165]
- [x] Update the Transfer GET Consumer config to match the Performance Branch - [@shashi165]
- [ ] ~Update the Transfer Timeout Consumer config to match the Performance Branch~
- [x] Update the Transfer Prepare Producers config to match the Performance Branch - [@shashi165]
- [x] Update the Transfer Position Producers config to match the Performance Branch - [@shashi165]
- [x] Update the Transfer Fulfil Producers config to match the Performance Branch - [@shashi165]
- [x] Update the Transfer Reject Producers config to match the Performance Branch - [@shashi165]
- [x] Update the Transfer ADMIN Producers config to match the Performance Branch - [@shashi165]
- [x] Update the Transfer Notification Producers config to match the Performance Branch - [@shashi165]
- [ ] ~Sequence Diagrams to be updated~
- [ ] ~Architecture Diagrams to be updated~
- [x] Update Unit Tests - [@shashi165]
- [x] Update Integration Tests - [@shashi165]

#### helm
- [x] Update the charts for central-ledger
- [x] Update the charts for ml-api-adapter
- [x] Update the charts for central
- [x] Update the charts for mojaloop
- [x] Publish new version of helm charts

#### deployments
- [x] Update the deployment release value file with latest kafka changes [ @elnyry ]

**Acceptance Criteria**:
- [x] New helm version deployed with updated kafka configs
- [x] Deployment release updated to support these changes  [ @elnyry ]

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/239
- [x] https://github.com/mojaloop/ml-api-adapter/pull/86
- [x] https://github.com/mojaloop/helm/pull/135

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Consumer configs:
```JSON
             "config": {
               "options": {
                 "mode": 2,
                 "batchSize": 1,
                 "pollFrequency": 10,
                 "recursiveTimeout": 100,
                 "messageCharset": "utf8",
                 "messageAsJSON": true,
                 "sync": true,
                 "consumeTimeout": 1000
               },
               "rdkafkaConf": {
                 "client.id": "cl-con-transfer-prepare", <-- dont change this
                 "group.id": "central-ledger-kafka", <-- dont change this
                 "metadata.broker.list": "$kafka_host:$kafka_port", <-- dont change this (unless your pointing to an external hosted kafka instance)
                 "socket.keepalive.enable": true <-- everything here gets replaced by this single line :D
               },
               "topicConf": {
                 "auto.offset.reset": "earliest"
               }
             }
```

**Comment by mdebarros** [comment]
Producer configs:
```JSON
ample producer 
       "config": {
        "options": {
         "messageCharset": "utf8"
        },
        "rdkafkaConf": {
         "metadata.broker.list": "$kafka_host:$kafka_port", <-- only change if your pointing to external kafka
         "client.id": "cl-prod-notification-event", <-- dont change this
         "event_cb": true, <-- keep this
         "socket.keepalive.enable": true <-- add this
        },
        "topicConf": {
         "request.required.acks": "all"
        }
       }
      }
```

**Comment by mdebarros** [comment]
Producer IDs:
- ml-prod-transfer-prepare
- ml-prod-transfer-fulfil
- cl-prod-transfer-prepare
- cl-prod-transfer-position
- cl-prod-notification-event

Consumer IDs:
- cl-con-transfer-prepare
- cl-con-transfer-position
- cl-con-transfer-fulfil
- ml-con-notification-event
