### ISSUE TITLE
Performance Enhancement - PRISM Fulfil Transfer

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#578]
## **Goal**:
As a hub-operator I want to implement PRISM optimisations so that the Transfer fulfil process is more performant and less CPU intensive

**Tasks**:

#### central-ledger
- ~Include additional Data Queries for PRISM message enrichment~ (Not necessary)
- ~Update Transfer Fulfil to query additional data points for PRISM message enrichment~ (Not necessary)
- [x] Update Transfer Fulfil-Position leg to use a shared PRISM object through Kafka and eliminate extra DB query on position side
- [ ] Sequence Diagrams to be updated
- [ ] Architecture Diagrams to be updated
- [ ] Update Unit Tests
- [ ] Update Integration Tests

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Sequence Diagrams are updated
- [ ] Architecture Diagrams are updated
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] https://github.com/mojaloop/central-ledger/pull/569

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
Shelved because of using 'combined handlers'
