### ISSUE TITLE
Performance Enhancement - PRISM Prepare Transfer

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#579]
## **Goal**:
As a hub-operator I want to implement PRISM optimisations so that the Transfer prepare process is more performant and less CPU intensive

**Tasks**:

#### central-ledger
- [ ] Include additional Data Queries for PRISM message enrichment
- [ ] Update Transfer Prepare to query additional data points for PRISM message enrichment
- [ ] Sequence Diagrams to be updated
- [ ] Architecture Diagrams to be updated
- [ ] Update Unit Tests
- [ ] Update Integration Tests

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Sequence Diagrams are updated
- [ ] Architecture Diagrams are updated
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
Other performance improvement solutions (merging handlers to two on central ledger) may render this obsolete.. Can be reopened if thats not the case.
