### ISSUE TITLE
Performance Enhancement - Async Loggers (may need to be split)

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#580]
## **Goal**:
As a hub-operator I want to implement async loggers so that the central-switch components are more performant with reduced io

**Tasks**:

#### central-services-shared
- [ ] Migrate code changes from performance branch into master branch for file logger
- [ ] Update Unit Tests
- [ ] Update Integration Tests
- [ ] Publish new release

#### ml-api-adapter
- [ ] Update central-services-shared dependency to new release
- [ ] Update Dockerfile to link the log file to stdout

#### central-ledger
- [ ] Update central-services-shared dependency to new release
- [ ] Update Dockerfile to link the log file to stdout

#### central-event-processor
- [ ] Update central-services-shared dependency to new release
- [ ] Update Dockerfile to link the log file to stdout

#### central-settlements
- [ ] Update central-services-shared dependency to new release
- [ ] Update Dockerfile to link the log file to stdout

#### email-notifier
- [ ] Update central-services-shared dependency to new release
- [ ] Update Dockerfile to link the log file to stdout

#### central-directory
- [ ] Update central-services-shared dependency to new release
- [ ] Update Dockerfile to link the log file to stdout

#### forensic-logging-sidecar
- [ ] Update central-services-shared dependency to new release
- [ ] Update Dockerfile to link the log file to stdout

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Sequence Diagrams are updated
- [ ] Architecture Diagrams are updated
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@mdebarros I think this covered elsewhere

**Comment by elnyry** [comment]
@mdebarros agrees..
