### ISSUE TITLE
Instrumentation for metrics into Helm Charts

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#584]
## **Goal**:
As a Hub Operator I want to configure metric instrumentation as part of the helm charts so that Prometheus is able to collect metrics

**Tasks**:
- [x] Update Helm Charts for Instrumentation configs in default.json for central-ledger
- [x] Update Helm Charts for Instrumentation configs in default.json for ml-api-adapter
- [x] Update Helm Charts for Instrumentation configs in default.json for simulators
- [x] Update Helm Charts for Prometheus Scrapping for central-ledger
- [x] Update Helm Charts for Prometheus Scrapping for ml-api-adapter
- [x] Update Helm Charts for Prometheus Scrapping for simulators
- [x] Test Central-Ledger Helm Charts
- [x] Test ML-API-Adapter Helm Charts
- [x] Test Mojaloop Helm Charts
- [x] Published Helm Charts
- [x] Deploy to dev/test environment
- [ ] ~Test Dev Deployment~ - #673 

**Acceptance Criteria**:
_local_
- [x] Central-Ledger Helm Charts that support metrics end-points
- [x] Central-Ledger Helm Charts that supports enabling/disabling Prometheus scrapping/collection of metric data
- [x] ML-API-Adapter Helm Charts that support metrics end-points
- [x] ML-API-Adapter Helm Charts that supports enabling/disabling Prometheus scrapping/collection of metric data
- [x] Simulators Helm Charts that support metrics end-points
- [x] Simulators Helm Charts that supports enabling/disabling Prometheus scrapping/collection of metric data

_dev/qa environment_
- [ ] ~Central-Ledger metrics end-points tested on Dev/QA environment~ - #673 
- [ ] ~ML-API-Adapter metrics end-points tested on Dev/QA environment~ - #673 
- [ ] ~Simulators Helm metrics end-points tested on Dev/QA environment~ - #673 

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/134
- [x] https://github.com/mojaloop/helm/pull/135
- [x] https://github.com/mojaloop/helm/pull/136

## **Follow-up**:
- #673 

**Dependencies**:
- [x] Blocked due to the following issue on the Central-Ledger v4.4.0 release:
- [ ] ~Blocked due to pending new dev1 environment setup~

`src/handlers/index.js` code currently contains this code:
```JAVASCRIPT
    module.exports = Setup.initialize({
      service: 'handler',
      port: Config.PORT,
      modules: [Plugin],
      runMigrations: false,
      handlers: handlerList,
      runHandlers: true
    })
```

This will be solved by the following feature: https://github.com/mojaloop/project/issues/576

This is missing the `metric` plugin import under the module setup section. This means only the Central-Ledger API services will have the /metrics end-point enabled.

## **Accountability**:
- Owner: @mdebarros
- QA/Review: TBC

**Comment by mdebarros** [comment]
See dependency section above to see reason for blockage.

**Comment by mdebarros** [comment]
@NicoDuvenage please verify/update your tests based on the following document https://github.com/mojaloop/helm/blob/master/monitoring/METRICS.md
