### ISSUE TITLE
CEP, email-notifier demonstrations, presentation for Phase-3 kick-off

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#586]
**Goal**:
As a contributor
I would like the _prepare the demos and presentations for the cep, email-notifier topics_
so that they can be presented at the ML Phase-3 kickoff event.

**Tasks**:
- [x] Configure and run cep and email-notifier locally [@ggrg]
- [x] Examine currently delivered code and provide feedback [@ggrg]
- [x] Review documentation for the utilised technologies (rxjs, mongo) [@ggrg]
- [x] Watch, review and use recorded demos on CEP, email-notifier  [@ggrg]
- [x] Examine architecture diagrams and provide feedback [@ggrg]
- [x] Examine sequence diagrams and provide feedback [@ggrg]
- [x] Finalise scope and functionality to demo for the cep, email-notifier topics [@ggrg]
  - [x] CEP used technologies and Architecture Overview [@ggrg]
  - [x] CEP Process Overview Sequence Diagram [@ggrg]
- [x] Prepare slides for the cep, email-notifier topics [@ggrg]
- [x] Complete the review of slides [@ggrg]
- [x] Record scripts/postman demo ~video~ [_optional_] [@ggrg]
- [x] Finalise demo

**Acceptance Criteria**:
- [x] The cep, email-notifier demos for the ML Phase-3 kickoff event are finalised
- [x] The slides for the cep, email-notifier topics for the ML Phase-3 kickoff event are finalised

**Dependencies**:
- none

**Accountability**:
- Owner @ggrg 
- QA/Review @elnyry @vgenev @bothadeon
