### ISSUE TITLE
Instrumentation Metrics into Simulators

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#587]
**Goal**:
As a Hub Tech Operator or Hub DevOps
I would like the _add instrumentation to the Switch Simulator_
to enable operational monitoring and identify status/metrics and issues if any.

**Tasks**:
- [x] import mojaloop/metrics lib -- [@mdebarros]
- [x] Simulators -- [@mdebarros]
  - [x] Create -- [@mdebarros]
  - [x] Add CI/CD  -- [@mdebarros]
  - [x] Release for use -- [@mdebarros]
- [x] Validate -- [@mdebarros]
- [x] Add QA Verification Tests to the QA Framework -- [@NicoDuvenage]

**Acceptance Criteria**:
- [x] A library that supports instrumentation for metrics to be used with Simulators is provided and released.
- [x] Instrumentation is provided for the Simulators

**PRs**:
- [x] https://github.com/mojaloop/simulators/pull/2

**Dependencies**:
- [ ] 

**Accountability**:
- Owner @mdebarros  
- QA/Review @rmothilal @mdebarros
