### ISSUE TITLE
Enable CI for Simulators

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#588]
## **Goal**:
As a Hub Operator I want to CI for Simulators so that PRs/deployments can be validated

**Tasks**:
- [x] Add .circleci config
- [x] Test CI
- [x] Test PRs

**Acceptance Criteria**:
- [ ] Simulator passes unit tests in CI process
- [x] Simulator docker images are built on releases

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
This is now in place - https://circleci.com/workflow-run/7d64138d-c9b9-47c4-861c-1c3da327478b
