### ISSUE TITLE
Enable CD for Simulators

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#589]
## **Goal**:
As a Hub Operator, I want to CD for Simulators so that deployments can be validated/automated

**Tasks**:
- [x] Add .circleci config
- [x] Test CD
- [x] Test Releases

**Acceptance Criteria**:
- [x] Simulator CD process kicks off on a  new release tag
- [ ] Simulator passes unit tests in CI process
- [x] Simulator docker images are built on releases
- [x] Simulator release is deployed

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
This is now in place, example: https://circleci.com/gh/mojaloop/simulator/202
