### ISSUE TITLE
Break out the Kafka(Consumer/Producer) code into a shared repo

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#590]
## **Goal**:
As a contributor
I want to _break out the Kafka(Consumer/Producer) code in central-ledger into a shared repo_
so that it can be used as a library instead of having copies of the same code

**Tasks**:
- [ ] Separate out the kafka code (consumer/producer) code as a library [ @? ]
- [ ] Create/Release for use by other services [ @? ]
- [ ] Update code-base for central-ledger
  - [ ] Tests
- [ ] Update code-base for central-settlement
  - [ ] Tests
- [ ] Update code-base for ml-api-adapter
  - [ ] Tests
- [ ] Automated tests for the library[ @? ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Kafka consumer and producer code is available as a library for use by various services as needed.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
We now have the central-service-stream which accomplishes this
