### ISSUE TITLE
Instrumentation Metrics - Documentation for Metrics Library

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#591]
## **Goal**:
As a Hub Contributor, I want to Metrics Library documentation so that I can understand how to utilise it for all Mojaloop contributions

**Tasks**:
- [ ] Update README.md to include an overview of the Metrics Library
- [ ] Update README.md to include the functionality of the Metrics Library
- [ ] Update README.md to include development guidelines (usage, best practices, standards, etc) of the Metrics Library

**Acceptance Criteria**:
- [ ] Hub Contributors are able to understand the Metrics library functionality
- [ ] Hub Contributors are able to understand how to use the Metrics library functionality in contributions
- [ ] Hub Contributors are able to understand the standards, best practices on the use of the Metrics library

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Basic documentation present on the readme
