### ISSUE TITLE
Review and refactor default.json on all repositories

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#592]
## **Goal**:
As a contributor to the Switch Open Source codebase
I want to only have config specific to the API to which a specific repository belongs or is associated with

**Tasks**:
- [ ] Clean central-ledger
- [ ] Clean ml-api-adapter
- [ ] Clean central-settlement
- [ ] Clean central-event-processor
- [ ] account-lookup-service
- [ ] quoting-service
- [ ] transaction-requests-service
- [ ] Clean helm scripts

**Acceptance Criteria**:
- [ ] All unnecessary config is removed from the default.json across all API/scripts 
- [ ] All API/deployments still work as expected after removal of config
- [ ] All test config to be refactored to align with new default.json's
- [ ] All tests pass

## **Pull Requests**:
- [ ] ~TBD~

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rmothilal 
- QA/Review: @mdebarros

**Comment by elnyry** [comment]
duplicate of #1060
