### ISSUE TITLE
Create EMUN for metric labels in all applicable repos

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#593]
## **Goal**:
As a developer I want to create an EMUN for metric labels for Prometheus so that the labels are consistent and not hardcoded

**Tasks**:
- [ ] ENUM created in central-ledger
- [ ] ENUM created in ML-API-Adapter

**Acceptance Criteria**:
- [ ] Metrics still produced with the correct labels as hardcoded values

## **Pull Requests**:
- [ ] ~TBD~

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rmothilal 
- QA/Review: @mdebarros

**Comment by elnyry** [comment]
Moving this to next Sprint as this wasn't prioritized and a few other stories were added mid-way
