### ISSUE TITLE
Align consumer/client IDs for Kafka Consumers/Producers

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#595]
## **Goal**:
As a Hub Operator I want to `Align consumer/client IDs for Kafka Consumers/Producers` so that there is consistency in naming conventions for easier maintenance

**Tasks**:
- [x] Update Client-id for Email-Notifier - [@shashi165]
- [x] Update Group-id for Email-Notifier - [@shashi165]
- [x] Update Client-id for Central-event-processor - [@shashi165]
- [x] Update Group-id for Central-event-processor - [@shashi165]
- [x] Update Group-id for Email-Notifier Helm Charts - [@shashi165]
- [x] Update Client-id for Central-event-processor Helm Charts - [@shashi165]

**Acceptance Criteria**:
- [x] Email-notifier client-id matches: enotifier-prod, enotifier-con
- [x] Email-notifier group-id matches: enotifier-group
- [x] Central-event-processor client-id matches: cep-prod, cep-con
- [x] Central-event-processor group-id matches: cep-group

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-event-processor/pull/22
- [x] https://github.com/mojaloop/email-notifier/pull/17
- [x] https://github.com/mojaloop/helm/pull/139

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @mdebarros
