### ISSUE TITLE
Performance Characterization - Verify Scaling of Individual Handlers

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#596]
## **Goal**:
As a Hub Operator
I want to _understand the performance of each of the handlers subject to scaling_
so that _I can make informed decisions of scaling levels, ratio needed_ and identify bottle-necks

**Tasks**:
- [x] Setup needed to understand perf characteristics of each individual handler (prepare, position, fulfil, notification)
- [x] Record numbers subject to variables (scaling, infrastructure) involved
- [x] Record observations
- Test Scenarios:
    - [ ] Notification Handler -> Simulator -> ML-API-Adapter (with produce to fulfil topic commented out)
    - Test impact of FSPs
        - [x] 4 FSPs
        - [x] 8 FSPs
        - [ ] 2 FSPs
    - [x] ML-API-Adapter -> Test JMeter threads from 1-4 against
        - [ ] Scale: 1
        - [ ] Scale: 2
        - [ ] Scale: 4
- Metrics:
    - [x] Add labels to Position metrics for Prepare & Fulfil flows
- Dashboards:
    - [x] Add memory metrics to dashboards

**Acceptance Criteria**:
- [x] Each handler is run with sufficient load of messages to understand its perf characteristics when run in conjunction with the other handlers (necessary for transfers)
- [x] Metrics / Perf numbers are recorded for reference
- [x] Observations recorded and recommendations made

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: 
- QA/Review: @mdebarros @elnyry

**Comment by elnyry** [comment]
The scaling level of 4 handlers was done in 9.1. Moving the tests for scaling level 8 to Sprint 9.2

**Comment by elnyry** [comment]
This has been used to capture various iterations of tests after each and every change made. So increasing estimate and removed milestone

**Comment by elnyry** [comment]
Issue for Closing report and demo: https://github.com/mojaloop/project/issues/1260
