### ISSUE TITLE
Add metrics endpoint to the Central-Ledger Admin API server

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#599]
## **Goal**:
As a Hub Operator
I want to be able to retrieve performance and system metics on the Admin API server
so that it can be viewed on the Grafana dashboards

**Tasks**:
- [x] Add metrics lib to the central-ledger admin routes
- [x] Add /metrics endpoint to hapi server routes
- [x] Test that correct metrics are returned

**Acceptance Criteria**:
- [x] Metrics of the admin API service are accessible/available
- [x] Grafana dashboard displays metrics for central-ledger admin

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/241

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rmothilal 
- QA/Review: @mdebarros

**Comment by elnyry** [comment]
Moving over to the next Sprint for only one task left -  Grafana dashboard displays metrics for central-ledger admin

**Comment by mdebarros** [comment]
This has been fixed with #601 .

Please verify.
