### ISSUE TITLE
Merge Central-Ledger normal & admin APIs

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#600]
## **Goal**:
As a Hub Operator
I want to _deprecate the Central-Ledger API_
so that only the Central-Ledger Admin API is usable as the normal API is no longer in-use

**Tasks**:

_Central-Ledger_
- [x] Merge existing normal API & Admin code-base [ @rmothilal ]
- [x] Ensure existing API/Admin tests pass and updated accordingly [ @rmothilal ]

_Helm_
- [x] Update Helm Charts to deploy the consolidated API [ @mdebarros ]
- [x] Publish a new version of the Helm Charts [ @mdebarros ]

_QA_
- [x] Update the Postman Regression tests to remove the URI `/admin` path [ @NicoDuvenage @sri-miriyala ]
- [x] Validate the Postman Regression tests [ @NicoDuvenage @sri-miriyala ]
- [x] Update test scripts in central-ledger (to reflect the removal of /admin basepath)

_Deployment_
- [x] Update the deployment values.yaml [ @elnyry ]

**Acceptance Criteria**:
- [x] Central-Ledger only exposes a single API end-point with Admin functionality
- [x] Helm Chart now deploys the Centra-Ledger API Service with a single Container within the K8s Pod
- [x] Ensure that /health end-points are still functioning
- [x] Ensure that /metric end-points are still functioning
- [ ] ~Designs are up-to date~
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Regression Tests Pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/241
- [x] https://github.com/mojaloop/helm/pull/138
- [x] https://github.com/mojaloop/postman/pull/6

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rmothilal 
- QA/Review: @mdebarros

**Comment by mdebarros** [comment]
@sri-miriyala @NicoDuvenage can we close this?
