### ISSUE TITLE
Refactor enum cache on central-settlements to use catbox-memory instead of the Hapi server

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#603]
## **Goal**:
As a developer I want to use catbox-memory to cache the enums on central-settlements so that the caching mechanism can be separated from the the transport layer ie: Hapi server

**Tasks**:
- [ ] Remove current caching implementation on central-settlements hapi server
- [ ] Implement code changes to use catbox-memory 
- [ ] Update tests

**Acceptance Criteria**:
- [ ] All tests pass
- [ ] Cache can be accessed durning the session

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- [ ] #695 

## **Accountability**:
- Owner: @rmothilal 
- QA/Review: @mdebarros

**Comment by lewisdaly** [comment]
Is this still relevant? I had a quick chat with @mdebarros about this at the last convening, and we both thought it might be out of scope now.

**Comment by elnyry** [comment]
Ok, will move out to backlog then

**Comment by elnyry-sam-k** [comment]
should be taken care of as part of the ref architecture refactoring / implementation
