### ISSUE TITLE
Creating a Mojaloop end to end deployment document - OSX

### ISSUE THREAD

**Issue by HenkKodde** [mojaloop/project#606]
## **Goal**:
As a Community member
I want a step-by-step deployment document to follow
so that deploying the Mojaloop environment will be a pleasant experience.

**Tasks**:
- [x] Create a mark down document for the current Mojaloop system. [ @HenkKodde  ]

**Acceptance Criteria**:
- [x] Provides information on resource capacity required
- [x] Caters for current 3rd party applications
  - [x] List the 3rd party software to be used
  - [x] List the 3rd party software versions verified as compatible
  - [x] Provide links to 3rd party software
  - [x] Briefly explanation the use of 3rd party software within the context of the project
- [x] Provides installation for MacOS
- [ ] ~Provides installation for Linux (ubuntu)~
- [x] Guidelines how to verify the installation 
- [x] Links to the current Postman scripts
- [x] Note on possible issues and possible solutions

## **Pull Requests**:
- [x] https://github.com/mojaloop/docs/pull/121

## **Follow-up**:
- [x] #633

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @HenkKodde 
- QA/Review: TBC

**Comment by HenkKodde** [comment]
PR create for initial review - https://github.com/mojaloop/docs/pull/121.
