### ISSUE TITLE
Provide the on-boarding guide for the Mojaloop Central Event Processor

### ISSUE THREAD

**Issue by HenkKodde** [mojaloop/project#607]
## **Goal**:
As a community member
I want to have an on-boarding guide for the central-event-processor (CEP) component
so that it helps me setup the service locally or on a target environment.

**Tasks**:
- [ ] Create an on-boarding document [ @HenkKodde  ]
  - [x] Provide the required Software List
  - [x] Detail Setup for MacOS
  - [x] Detail Setup for Linux (ubuntu)
  - [x] Provide insight on possible errors on setup and suggested solutions

**Acceptance Criteria**:
- [x] Easy to follow on-boarding document is available for the CEP component
- [x] Setup is verified on MacOS 
- [x] Setup is verified on Linux (ubuntu)

## **Pull Requests**:
- [ ] https://github.com/mojaloop/central-event-processor/pull/26

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by HenkKodde** [comment]
PR generated. https://github.com/mojaloop/central-event-processor/pull/26
