### ISSUE TITLE
Add config to default.json to manage the connection pool for knex and MySQL

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#608]
## **Goal**:
As a developer
I want to make the connection pool for knex and MySQL configurable
so that we can change the connection pool on deployment in kubernetes if we require more or less connections

**Tasks**:
- [x] Add "MAX_DB_CONNECTION_POOL": 30, "MIN_DB_CONNECTION_POOL": 10 to the default.json and config.js 
- [x] Add changes to knexfile.js pool: { min: Config.MIN_DB_CONNECTION_POOL, max: Config.MAX_DB_CONNECTION_POOL }
- [x] Update helm scripts

**Acceptance Criteria**:
- [x] We are able to deploy central-ledger with configurable values for the connection pool size
- [x] Central-ledger can be deployed as per usual

## **Pull Requests**:
- [x] PR for Central-Ledger => https://github.com/mojaloop/central-ledger/pull/268
- [x] PR for Helm => https://github.com/mojaloop/helm/pull/166

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rmothilal 
- QA/Review: @mdebarros

**Comment by HenkKodde** [comment]
Will continue with story after the current sprint.
