### ISSUE TITLE
Remove unused/unnecessary configuration from all scripts and config files - 1

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#609]
## **Goal**:
As a developer
I want to remove all unused/unnecessary configuration from helm scrips and config files
so that we do have cleaned up repositories with only config that is applicable to the API

**Tasks**:
- [ ] ~Remove unused config from central-ledger~
- [x] Remove unused kafka cronjob code & tests from central-ledger [ @shashi165 ]
- [x] Remove unused kafka cronjob config from central-ledger [ @shashi165 ]
- [x] Remove unused config from ml-api-adapter
- [ ] ~Remove unused config from central-settlements~
- [ ] ~Remove unused config from central-event-processor~
- [ ] ~Remove unused config from central-services-shared~
- [ ] ~Remove unused config from central-services-stream~
- [ ] ~Remove unused config from helm scripts for central-ledger~
- [ ] ~Remove unused kafka cronjob config from from helm scripts for central-ledger~
- [ ] ~Remove unused config from helm scripts for central-settlement~
- [x] Remove unused config from helm scripts for ml-api-adapter - [@shashi165]
- [ ] ~Remove unused config from helm scripts for central-event-processor~

**Acceptance Criteria**:
- [ ] Regression testing (manual/automated) passes without issues
- [ ] All deployments still occur as per usual

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @mdebarros 
- QA/Review: @rmothilal

**Comment by elnyry** [comment]
To be resumed in #636
