### ISSUE TITLE
Automate the CD pipeline for central-hub

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#61]
**Goal**:
As a developer I would like to automate the CD pipeline for central-hub so that I can shorten the delivery cycle

**Tasks**:
- [x] Collect CD requirements from discussion with Dev and QA Teams
- [x] Document CD requirements from discussion with Dev and QA Teams
- [x] Automate the deployment of snapshot artefacts if a tag push has been made to the develop branch via a helm chart upgrade/install iff the CI flows completed successfully
- [x] Automate the deployment of release artefacts if a tag push has been made to the master branch via a helm chart upgrade/install iff the CI flows completed successfully

**Acceptance Criteria**:
- [x] Define and document the deployment process and requirements
- [x] Automate the deployment through k8s for master and develop push tags

**Dependencies**:
- None currently

**Comment by mdebarros** [comment]
PR: https://github.com/mojaloop/central-hub/pull/9


Note that there are no Functional or Integration tests implemented for this repository. We will need stories to implement them as required. Once that has been done I can re-configure the CI to execute them.

**Comment by mdebarros** [comment]
Demo: https://drive.google.com/file/d/1T-i2NAK6uBqbAP1EM6j_Gonsh_kaot2f/view?usp=sharing
