### ISSUE TITLE
Announcement Notifications are published on Slack Channels for new Releases

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#610]
## **Goal**:
As a `Mojaloop Open Source maintainer`
I want to `enable auto-announcements through via the CI/CD pipeline for new releases`
so that `all stakeholders are aware of new releases & features`

**Tasks**:
- [x] central-ledger release announcements (@mdebarros )
- [x] ml-api-adapter release announcements (@HenkKodde )
- [x] central-settlement release announcements (@HenkKodde )
- [x] central-event-processor release announcements (@HenkKodde )
- [x] email-notifier release announcements (@HenkKodde )

**Acceptance Criteria**:
- [x] CI/CD Pipeline sends an announcements to the Mojaloop general Slack channel for new releases that are published for the below repos
  - [x] central-ledger
  - [x] ml-api-adapter
  - [x] central-settlement
  - [x] central-event-processor
    - [x] Resolve vulnerabilities
  - [x] email-notifier

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-event-processor/pull/27
- [x] https://github.com/mojaloop/email-notifier/pull/19
- [x] https://github.com/mojaloop/central-settlement/pull/65
- [x] https://github.com/mojaloop/ml-api-adapter/pull/91

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @mdebarros

**Comment by HenkKodde** [comment]
https://github.com/mojaloop/central-event-processor/pull/27

**Comment by HenkKodde** [comment]
https://github.com/mojaloop/email-notifier/pull/19

**Comment by elnyry** [comment]
Now received announcements for central-ledger, ml-api-adapter and central-settlement so closing this out
