### ISSUE TITLE
Regression test results are published to the Mojaloop slack channels

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#611]
## **Goal**:
As a `Hub Operator`, I want to `automated scheduled regression tests reports to be published to the mojaloop slack org` so that `all stakeholders are aware of regression test results`

**Tasks**:
- [x] Refactor scripts to cater for multiple delivery channels [ @NicoDuvenage  ]
- [x] Provision an S3 bucket as "repository" for all completed tests" [ @mdebarros  ]
- [x] Test Slack and email delivery is working correctly [ @NicoDuvenage  ]
- [x] "Generalise" the Environment Settings for uploading to the repository [ @NicoDuvenage  ]

**Acceptance Criteria**:
- [x] Regression tests to sends announcements to the Mojaloop "announcements" Slack channel with a link to Regression test results

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-qa-regression-testing/pull/1

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @mdebarros
