### ISSUE TITLE
Migrate deployment doc from PDF to Markdown

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#612]
## **Goal**:
As a maintainer of the Mojaloop Open Source
I want to `move the deployment documentation to mark-down format`
so that `it is maintainable and easier for the community to help keep upto-date`

**Tasks**:
- [x] Move the https://github.com/mojaloop/docs/blob/master/WorkShops/Presentations/Mojaloop_Phase2_Wrap-up_Deployment-Day3_V2.0-published.pdf document into Markdown within the docs repository
- [x] Update the documentation with the latest changes required for the Kubernetes Dashboard as a token is now required for access (see #ml-documentation Slack channel for details)

**Acceptance Criteria**:
- [x] Deployment Documentation is in Markdown
- [x] Deployment Documentation is in Github Docs repository
- [x] Deployment Documentation has been updated to reflect the latest Kubernetes Dashboard security changes (i.e. a token is required for access)

## **Pull Requests**:
- [x] [mojaloop/docs#121](https://github.com/mojaloop/docs/pull/121)

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @HenkKodde 
- QA/Review: @mdebarros

**Comment by mdebarros** [comment]
@HenkKodde please use this story to track your task with this.

**Comment by HenkKodde** [comment]
Changes are included in the PR * mojaloop/docs#121
