### ISSUE TITLE
Review the Settlements API for standardizing

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#614]
## **Goal**:
As a maintainer of the Settlements API
I want to review the Settlements API on the whole to standardize it
so that a Settlements API for Open Source can be drafted and released as a white-paper

**Tasks**:
- [x] Review the existing Settlements API [ @ggrg ]
- [x] Draft a Whitepaper summarising the output of the review [ @ggrg ]
- [ ] Complete a review and submit the Whitepaper to GitHub mojaloop repo (link) [@ggrg]

**Acceptance Criteria**:
- [x] Known issues with the Settlements API are recorded
- [x] Items that need further documentation are recorded

## **Pull Requests**:
- [ ] https://github.com/mojaloop/docs/pull/120

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
