### ISSUE TITLE
Adopting central-directory that was contributed to OSS

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#619]
## **Goal**:
As a maintainer of the ML OSS codebase
I want to take necessary actions to adopt the central-directory contributed by Mowali to OSS
so that it is ready for integration with the rest of the OSS services and Open source consumption.

**Tasks**:
- [x] Get the code migrated to GitHub as a private repo
- [x] Review code, document issues or concerns (Sub-team from the DA)
- [x] Run the service, test integration with existing services
- [ ] ~Check Licensing of the dependencies, etc.~ To be done after design 
- [ ] ~Configuration for 'modes of operation'~ To be done after design
- [x] Document tasks/stories needed to be done before this can be made public
- [x] Identify next steps and action items 

**Acceptance Criteria**:
- [x] A document is made available that lists the issues, concerns with the central-directory service migrated
- [x] Actions to be taken before the service can be made public are documented
- [ ] ~Dependencies are validated for licensing issues (Apache 2.0 compatible)~ To be done after design
- [x] A list of action items and next steps are documented with owners as appropriate
- [ ] ~Repo is made public after the blockers to that are removed/addressed~

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- #644
- #645 

**Dependencies**:
- This is dependent on the availability of the donated code-base for central-directory

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
Blocked because of availability
