### ISSUE TITLE
CI/CD Pipeline for Helm

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#621]
## **Goal**:
As an `Oss Contributor`
I want to `have helm published on releases`
so that `we reduce the possibility of human error during the current manual publishing steps`

**Tasks**:
- [x] Add CI/CD pipeline to Helm to auto-publish charts on releases

**Acceptance Criteria**:
- [x] Helm charts are automatically published to the Mojaloop Helm repo on a release:
    - [x] Master is merged into the `gh-pages` branch
    - [x] Published charts are then generated in the `gh-pages` branch which is generated via the "publish.sh" script 
    - [x] The generated packaged charts are then added to git, and committed with the corresponding release tag and message in the following format "Publishing release <tag>"
- [x] The git user for the commit must be the following Github user `mojaloopci`
- [ ] Use the existing Github user `mojaloopci` credentials that is stored on CircleCI env vars: `GIT_CI_USER` / `GIT_CI_PASSWORD`

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @mdebarros

**Comment by elnyry** [comment]
Thanks @mdebarros , closing this out now as its delivered.. In addition, slack integration (to announcements channel) is added as well.
