### ISSUE TITLE
Transfer notifications messages are not sent on message replays

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#622]
## **Goal**:
As a `Hub Operator`
I want to `have the handler components ignore duplicate messages during a message replay`
so that `I don't receive an unnecessary notification message`

**Tasks**:
- [ ] TBD [ @? ]

**Acceptance Criteria**:
- [ ] Kafka Index to be stored as part of the Transfer meta-data within the DB
- [ ] Handlers then must validate if the existing record matches the Kafka index to determine if the message is a replay and if so it should be ignored.
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

**Notes**:
- This change is required due to the auto-commits being enabled. The actual processing of the messages will not occur, but currently, this will result in the central handlers seeing the message as a duplicate and will subsequently send a notification message to the FSP.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
This is now catered for in the "Reliable notifications design" as part of the Reference Architecture; once this is implemented; this issue should be taken care of.
