### ISSUE TITLE
One-click (or one-step) regression testing capability

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#624]
## **Goal**:
As a stakeholder
I want _the capability to run the regression testing framework for the existing functional tests using a simple one-step (or few steps) process_
so that running the QA framework on a given deployment is easy and straight-forward

**Tasks**:
- [x] Setup the regression testing framework
  - [x] Feature tests using postman
- [x] Refactor the current solution
  - [x] Modularise the current solution - Split functionally
  - [x] Parameterize as many  variables as required to make the solution generic
  - [x] Introduce more reporting delivery channels - email and slack identified
- [x] Extend the current solution
  - [x] Enable a "Clickable" execution evironment or a command-line execution
- [x] Update repository documentation to align with the refactored solution
- [x] Test runs

**Acceptance Criteria**:
- [x] A process to run the QA Regression testing framework is available that is simple and straight-forward so that any team member can run it easily

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-qa-regression-testing/pull/1
## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
