### ISSUE TITLE
Update NodeJs runtime from 8.4.x to 10.15.x LTS - 2

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#628]
## **Goal**:
As a ML OSS maintainer
I want to `upgrade NodeJs runtime from 8.4.x to 10.15.x LTS`
to ensure that `we are running on the latest LTS version of NodeJS to reduce security threats and benefit from performance enhancements.`

**Tasks**:
_Components_
- [x] ~Upgrade Central-Ledger to 10.15.x~
  - [x] Upgrade hapi and other dependencies [@ggrg]
  - [x] Code quality corrections [@ggrg]
- [x] Upgrade Central-Settlement to 10.15.x [@ggrg]
- [x] ~Upgrade Forensic-Logging-Sidecar to 10.15.x~
- [x] Upgrade Central-End-User-Registry to 10.15.x [@ggrg]
  - [x] Upgrade all dependencies [@ggrg]
  - [x] Switch to mysql database [@ggrg]
  - [x] Adjusted integration tests and integration runner [@ggrg]
  - [x] Adjusted functional tests and functional runner [@ggrg]
  - [x] Applied standard js corrections [@ggrg]
- [x] ~Upgrade Central-Directory to 10.15.x~
- [x] ~Upgrade CEP to 10.15.x~
- [x] ~Upgrade Email-Notifier to 10.15.x~
- [x] ~Upgrade ML-API-Adapter to 10.15.x~
  - [x] Upgrade hapi and other dependencies [@ggrg]
  - [x] Code quality corrections [@ggrg]
- [x] Upgrade Mock-pathfinder to 10.15.x [@ggrg]
  - [x] Upgrade all dependencies [@ggrg]
  - [x] Switch to mysql database [@ggrg]
  - [x] Adjusted integration tests and integration runner [@ggrg]
  - [x] Applied standard js corrections [@ggrg]
- [x] Upgrade Simulator to 10.15.x [@ggrg]
- [x] ~Upgrade central-services-error-handling to 10.15.x~

_Dependencies_
- [x] Upgrade Central-Ledger dependencies to latest versions
- [x] Upgrade Central-Settlement dependencies to latest versions 
- [x] Upgrade Forensic-Logging-Sidecar dependencies to latest versions
- [x] Upgrade Central-End-User-Registry dependencies to latest versions
- [x] ~Upgrade Central-Directory dependencies to latest versions (pathfinder-*)~
- [x] ~Upgrade CEP dependencies to latest versions~
- [x] Upgrade ML-API-Adapter dependencies to latest versions
- [x] Upgrade Mock-pathfinder dependencies to latest versions
- [x] ~Upgrade Email-Notifier dependencies to latest versions~
- [x] Upgrade Simulator dependencies to latest versions
- [x] Upgrade Central-services-stream dependencies to latest versions
- [x] Upgrade Central-services-error-handling dependencies to latest versions
- [x] Upgrade Central-services-database dependencies to latest versions

**Acceptance Criteria**:
- [x] Ensure all Docker images are built against NodeJs 10.15.x
- [x] Ensure that all NodeJs dependencies are updated to the latest version
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/252
- [x] https://github.com/mojaloop/ml-api-adapter/pull/92
- [x] https://github.com/mojaloop/simulator/pull/12
- [x] https://github.com/mojaloop/central-settlement/pull/66
- [x] https://github.com/mojaloop/mock-pathfinder/pull/10
- [x] https://github.com/mojaloop/central-end-user-registry/pull/9

## **Follow-up**:
- #629 

**Dependencies**:
- [x] #604 
- [x] #648

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
