### ISSUE TITLE
Update NodeJs runtime from 8.4.x to 10.15.x LTS - 3 [QA on the upgrade]

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#629]
## **Goal**:
As a ML OSS maintainer
I want to `verify the upgraded services (of NodeJs runtime from 8.4.x to 10.15.x LTS)`
to ensure that there have been no regressions to functionality and all the features work as expected.

**Tasks**:
_QA_
- [x] Verify test Central-Ledger against 10.15.x
- [x] Verify test Central-Settlement against 10.15.x
- [x] Verify test Forensic-Logging-Sidecar against 10.15.x
- [x] Verify test Central-End-User-Registry against 10.15.x
- [ ] Verify test Central-Directory against 10.15.x
- [ ] Verify test CEP against 10.15.x
- [x] Verify test ML-API-Adapter against 10.15.x
- [x] Verify test Mock-pathfinder against 10.15.x
- [ ] Verify test Email-Notifier against 10.15.x
- [x] Verify test Simulators against 10.15.x

**Acceptance Criteria**:
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Functional tests pass and if not bugs are logged against failures

## **Pull Requests**:
- N/A

## **Follow-up**:
- N/A

**Dependencies**:
- [x] #628 
- [x] #604 

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by cllty** [comment]
**Central-End-User-Registry** tested against 10.15.3
https://github.com/mojaloop/central-end-user-registry/pull/10

**Comment by elnyry** [comment]
This is happening as part of the normal QA on the deployed AWS versions not separately
