### ISSUE TITLE
Configurable Metric names in ML, CL & Simulator

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#630]
## **Goal**:
As a `Hub Operator` I want to `externalise all metric names (as they are currently hard-coded)` so that `the metrics names are consistent & maintainable`

**Tasks**:
- [ ] ML-API-Adapter: Change all static metrics to be configurable
- [ ] Central-Ledger: Change all static metrics to be configurable
- [ ] Simulator: Change all static metrics to be configurable
- [ ] ML-API-Adapter: Update documentation
- [ ] Central-Ledger: Update documentation
- [ ] Simulator: Update documentation
- [ ] ML-API-Adapter: Verify config changes work
- [ ] Central-Ledger: Verify config changes work
- [ ] Simulator: Verify config changes work
- [ ] ML-API-Adapter: Update Helm charts
- [ ] Central-Ledger: Update Helm charts
- [ ] Simulator: Update Helm charts
- [ ] ML-API-Adapter: Verify Helm changes work
- [ ] Central-Ledger: Verify Helm changes work
- [ ] Simulator: Verify Helm changes work

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Metric names are configurable in ML-API-Adapter
- [ ] Metric names are configurable in Central-Ledger
- [ ] Metric names are configurable in Simulator
- [ ] Metric names are configurable in Helm Chart deployments
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @mdebarros

**Comment by elnyry-sam-k** [comment]
closing as outdated for now
