### ISSUE TITLE
Setup new secure K8s environment with HA

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#631]
## **Goal**:
As a `OSS Team member`
I want to `have a secure HA K8s environment within the VPN`
so that `the k8s cluster is resilient and secure`

**Tasks**:
- [x] Setup HA Rancher running on RKE
- [x] Setup Dev1 environment
- [x] Deploy K8s Dashboard
- [x] Deploy Helm
- [x] Deploy Ingress
- [x] Deploy Setup DNSs for new environment
- [x] Deploy Monitoring
- [x] Deploy Logging
- [x] Deploy Mojaloop
- [ ] ~QA Framework to test environment~ - #673

**Acceptance Criteria**:
- [x] Dev1 environment is avaliable
- [ ] ~Dev1 environment has been verified using QA Framework~ - #673

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- #673

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @mdebarros

**Comment by elnyry** [comment]
Rolling this over to 5.2 (This has been taken up towards the end of 5.1 and because of a few unforeseen issues, got extended).

However, this did not affect our capability to host the 'dev' envt, which is currently intact and will be de-commissioned once the new envt (setup based on the current story) is ready.
