### ISSUE TITLE
Address lodash vulnerability in central-services-database by upgrading version

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#632]
**Summary**:
Address the security vulnerability in mojaloop / central-services-database reported by GitHub about `lodash` (Upgrade **lodash** to version 4.17.11 or later. For example:)

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
N/A

**Steps to Reproduce**
- Check the version and vulnerability report

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Notes**:
CVE-2018-16487 More information
low severity
Vulnerable versions: < 4.17.11
Patched version: 4.17.11
A prototype pollution vulnerability was found in lodash <4.17.11 where the functions merge, mergeWith, and defaultsDeep can be tricked into adding or modifying properties of Object.prototype.

- Severity when opened: Medium
- Priority when opened: Medium

**Tasks**
- [x] Identify all vulnerabilities
  - [x] Update lodash to lodash@4.17.11
  - [x] Update knex to knex@0.16.3
  - [x] Update tap-xunit to tap-xunit@2.3.0
- [x] Add badges to README.md

**Pull Requests**:
- [x] https://github.com/mojaloop/central-services-database/pull/23

**Comment by HenkKodde** [comment]
Upgraded to the following to resolve all vulnerabilities;
lodash@4.17.11
knex@0.16.3
tap-xunit@2.3.0

**Comment by HenkKodde** [comment]
Tested by executing "npm run test". 
Results - last 3 lines;
# tests 107
# pass  107
✓ ok
