### ISSUE TITLE
Creating a Mojaloop end to end deployment document - Linux (Ubuntu)

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#633]
## **Goal**:
As a Community member
I want a _step-by-step deployment document to follow for Linux (Ubuntu)_
so that _deploying the Mojaloop environment will be easy to do_.

**Tasks**:
- [x] Create a mark down document for the current Mojaloop system

**Acceptance Criteria**:
- [x] Provides information on resource capacity required
- [x] Caters for current 3rd party applications
  - [x] List the 3rd party software to be used
  - [x] List the 3rd party software versions verified as compatible
  - [x] Provide links to 3rd party software
  - [x] Briefly explanation the use of 3rd party software within the context of the project
- [x] Provides installation for Linux (ubuntu)
- [x] Guidelines how to verify the installation 
- [x] Links to the current Postman scripts
- [x] Note on possible issues and possible solutions

## **Pull Requests**:
- [x] https://github.com/mojaloop/docs/pull/130

## **Follow-up**:
- N/A

**Dependencies**:
- [x] Preceded by #606 

## **Accountability**:
- Owner: @HenkKodde 
- QA/Review: ML OSS team
