### ISSUE TITLE
Integration tests for central-settlement - 2

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#635]
**Goal**:
As a Contributor
I would like to _add integration tests for central-settlement_
so that the settlement features testing can be automated

**Tasks**:
- [x] ~Use central-settlement/test/util/scripts/settlementTransfer scripts as a starting point for creation of integration tests [@ggrg]~
- [x] Add integration tests following *test/util/scripts/settlementTransfer* demo scripts [@ggrg]
  - [x] ~Populate initial admin data through central-ledger micro service and assert [@ggrg]~
  - [x] ~Populate transfer through ml-api-adapter, central-ledger, simulator and assert [@ggrg]~
  - [x] ~Close settlement window and assert valid [@ggrg]~
  - [x] ~Create settlement and assert [@ggrg]~
  - [x] ~PS_TRANSFERS_RECORDED for PAYER and assert [@ggrg]~
  - [x] ~PS_TRANSFERS_RECORDED for PAYEE and assert [@ggrg]~
  - [x] ~Settlement to PS_TRANSFERS_RESERVED and assert [@ggrg]~
    - [x] ~Resolve issue with open kafka producer handle [@ggrg]~
  - [x] ~Settlement to PS_TRANSFERS_COMMITTED and assert [@ggrg]~
  - [x] SETTLED for PAYER and assert [@ggrg]
  - [x] SETTLED for PAYER - additional note and assert [@ggrg]
  - [x] SETTLED for PAYEE / Settlement SETTLED and assert [@ggrg]
- [x] Add unit tests and provide full coverage for newly added code in /src directory [@ggrg]
- [x] Prepare integration-runner.sh script for central-settlement [@ggrg, @mdebarros, @rmothilal]
- [x] Enable running integration tests for central-settlement in circleCI (enable the path) [@ggrg, @mdebarros, @rmothilal]
- [x] Make sure integration tests pass/fail as expected in circleCI [@ggrg, @mdebarros, @rmothilal]

**Acceptance Criteria**:
- [x] Integration tests are provided for central-settlement and work in circleCI

**PRs**
 - [x] https://github.com/mojaloop/central-settlement/pull/64

**Dependencies**:
- [x] #507

**Accountability**:
- Owner @ggrg 
- QA/Review @RobReeve @wdcmb
