### ISSUE TITLE
Remove unused/unnecessary configuration from all scripts and config files - 2

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#636]
## **Goal**:
As a developer
I want to remove all unused/unnecessary configuration from helm scrips and config files
so that we do have cleaned up repositories with only config that is applicable to the API

**Tasks**:
- [x] Remove unused config from central-ledger
- [x] ~Remove unused kafka cronjob code & tests from central-ledger~
- [x] ~Remove unused kafka cronjob config from central-ledger~
- [x] ~Remove unused config from ml-api-adapter~
- [x] Remove unused config from central-settlements
- [x] Remove unused config from central-event-processor
- [x] Remove unused config from central-services-shared
- [x] Remove unused config from central-services-stream
  - [x] Use locally in ml-api-adapter and central-ledger and run test transfers
- [x] ~Remove unused config from helm scripts for ml-api-adapter~
- [x] Remove unused config from email-notifier
- [x] Remove unused config from event-stream-processor
- [x] Remove unused config from transaction-request-service

**Acceptance Criteria**:
- [x] Regression testing (manual/automated) passes without issues
- [ ] All deployments still occur as per usual

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/504
- [x] https://github.com/mojaloop/central-event-processor/pull/108
- [x] https://github.com/mojaloop/central-services-shared/pull/144
- [x] https://github.com/mojaloop/central-services-stream/pull/56
- [x] https://github.com/mojaloop/email-notifier/pull/90
- [x] https://github.com/mojaloop/event-stream-processor/pull/14
- [x]  https://github.com/mojaloop/central-ledger/pull/512
- [x] https://github.com/mojaloop/transaction-requests-service/pull/14

## **Follow-up**:
- N/A

**Dependencies**:
- #609 

## **Accountability**:
- Owner: @mdebarros 
- QA/Review: @rmothilal

**Comment by elnyry** [comment]
Closing now as all PRs are merged.. will log a bug / reopen if any regressions arise because of this
