### ISSUE TITLE
Design for implementing error end-points on transfers

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#637]
## **Goal**:
As a DFSP
I want to _be able to use the /error end-point on a Switch_
so that _I can send error callbacks or notifications corresponding to the relevant cases as specified in the API Definition._ [This story deals with the design of this requirement]

**Tasks**:
- [x] Moved Settlements flows into Settlements folder
- [x] Moved Operations flows into Operations folder
- [x] Moved sequence diagrams for transfer-handler flows into archive as they're not relevant now and not part of transfers flows (seq-reject-2.2.3, seq-fulfil-2.1.3, seq-prepare-1.1.3.a, seq-timeout-2.3.3, seq-prepare-1.1.3.b)
- [x] Updated the word "Prepare" to "Fulfil" in the line "Consume Prepare event message for Payer" for Fulfil flows
- [x] Updated below sequence diagrams and svgs to remove Transfer topic/Transfer handler/TRANS_DAO:
  - [x] seq-fulfil-2.1.0
  - [x] seq-reject-2.2.0
  - [x] seq-reject-2.2.1
  - [x] seq-reject-2.2.2
  - [x] seq-timeout-2.3.0
  - [x] seq-timeout-2.3.1
  - [x] seq-position-1.3.0
  - [x] seq-position-1.3.2-fulfil
  - [x] seq-position-1.3.3-abort
  - [x] seq-prepare-1.1.0
  - [x] seq-prepare-1.1.1.a
  - [x] seq-prepare-1.1.1.b
  - [x] seq-prepare-1.1.2.a
- [x] Get the Position diagrams in the PR reviewed
----------------
- [x] Design a draft proposal for implementing the /error end-points for transfers
- [x] Provide sequence diagrams for the design
- [x] Provide PR for changes
- [x] Have the design reviewed by the DA
- [x] Feedback from reviews incorporated and designs (Sequence diagrams or markdown files)
- [x] Create follow-up stories based on this for implementation
  - [x] Raised bug #654 for transferStateChange on expired transfers
  - [x] For the seq-position-1.3.3-abort SD, currently under step-22, 'status' under 'state' object is changed from `rejected` to `aborted`; If this is accepted, need to make the change if needed
  - [x] New seed values for transferState proposed [in #281 ]:
     - **ABORTED_REJECTED** [_Final state for PUT /transfers/{ID} with 'aborted' in transferState. from RECEIVED_ABORT -> ABORTED_ERROR - maps to ABORTED_]
     - **ABORTED_ERROR** [_Final state for PUT /transfers/{ID}/error from RECEIVED_ABORT -> ABORTED_ERROR - maps to ABORTED_]
     - **RECEIVED_ERROR** [_On receiving PUT /transfers/{ID}/error from RESERVED -> RECEIVED_ERROR - maps to RESERVED_]
     - **RECEIVED_REJECT** [_To replace current 'REJECTED' - maps to RESERVED_]

**Acceptance Criteria**:
- [x] Sequence diagrams are provided for handling (incoming) requests on /error end-points for transfers
- [ ] ~Where sequence diagrams are not relevant (or not applicable) documentation is provided addressing the designs for error end-points on transfers~
- [x] Follow-up stories for implementing the /error end-points on transfers are provided

## **Pull Requests**:
- [x] https://github.com/mojaloop/docs/pull/134
- [x] https://github.com/mojaloop/docs/pull/135

## **Follow-up**:
- [x] #281 

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @elnyry 
- QA/Review: DA

**Notes**:
- Proposing to use a new sub-state(s)  RECEIVED_ABORT for Rejections / errors (and RECEIVED_REJECT for REJECTED).. and for final state ABORTED_REJECTED, ABORTED_ERROR
- Change EXPIRED_RESERVED in seq-position-1.3.3.abort to ABORTED --> This is a bug #654
