### ISSUE TITLE
CEP: Implement standard naming conventions in the local storage (Mongo DB Collections)

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#638]
## **Goal**:
As a maintainer of the OSS code-base
I want the CEP, notifiers to refactor naming conventions on the local storage
so that they can be standardized

**Tasks**:
- [ ] Refactor naming conventions in the local storage (Mongo DB Collections)
- [ ] Update tests
- [ ] Update designs/documentation

**Acceptance Criteria**:
- [ ] Unit Tests pass
- [ ] The naming used for local storage in the CEP and notifiers are standardized.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
