### ISSUE TITLE
CEP, notifiers: Research and implement an interface into the CEP to enable the plugin of any database

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#639]
## **Goal**:
As a maintainer of the OSS code-base
I want to _implement an interface into the CEP to enable the plugin of any database_
so that _“tight coupling” to a DB (as it is currently implemented) can be reduced_

**Tasks**:
- [ ] Research/Design capability to provide an interface into the CEP (to work with any DB)
- [ ] Implement changes
- [ ] Update tests
- [ ] Validate

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: DA
