### ISSUE TITLE
Persist CEP's rules into a data store

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#642]
## **Goal**:
As a maintainer of the OSS codebase
I want to ensure the Rules of the CEP are persisted into a data-store
so that they are standardized and can be configured by business rules/reasons.

**Tasks**:
- [ ] Refactor codebase to persist rules of CEP into data-store
- [ ] Validate DB design
- [ ] Implementation of changes
- [ ] Automated tests

**Acceptance Criteria**:
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
