### ISSUE TITLE
CI/CD pipeline for ALS

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#644]
## **Goal**:
As a maintainer of the ML OSS codebase
I want to take necessary actions to enable CI/CD pipeline for ALS
to ensure the same quality standards as the rest of the ML OSS repos

**Tasks**:
- [x] Enable/Setup CI/CD pipeline
- [x] Fix issues based on initial runs
- [ ] ~Create stories if there are significant issues/failures to fix~

**Acceptance Criteria**:
- [x] A CI/CD pipeline is put in place and is functional for the ALS repo

## **Pull Requests**:
- [ ] 

## **Follow-up**:
- N/A

**Dependencies**:
- #619 

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
@rmothilal closing this. Thanks, I see the CI pipelines in CircleCI
