### ISSUE TITLE
Assess Performance impact of the newly added Account Lookup Service (ALS)

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#645]
## **Goal**:
As a maintainer of the ML OSS codebase
I want to assess the performance impact of adopting the ALS
so that it is ready for integration with the rest of the OSS services and Open source consumption.

**Tasks**:
- [ ] Assess high-level performance impact and document
- [ ] Review if there are any concerns to be addressed and create follow-up stories.

**Acceptance Criteria**:
- [ ] High-level performance impact of adopting the ALS is documented
- [ ] Follow-up stories are created to address any significant issues, concerns

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Please re-open if/as needed
