### ISSUE TITLE
Upgrade Percona & Kafka Chart dependencies on Mojaloop Helm Chart

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#646]
## **Goal**:
As a `Maintainer of the OSS codebase`
I want to `upgrade Kafka/Percona dependency charts`
so that `Mojaloop deployments are stable`

**Tasks**:
- [ ] Upgrade Kafka dependency in requirements
- [ ] Merge new changes with the latest Kafka Values 
- [ ] Upgrade Percona dependency in requirements
- [ ] Merge new changes with the latest Percona Values 
- [ ] Add Prometheus scrape annotation to Percona Values config
- [ ] Test Helm Chart
- [ ] Test Deployment

**Acceptance Criteria**:
- [ ] Helm deployments now deploy with the latest Percona/Kafka Helm charts
- [ ] Percona mysql exporter is now scraped automatically by Prometheus
- [ ] Regression Tests Pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @mdebarros

**Comment by elnyry-sam-k** [comment]
@mdebarros please confirm if this was done as part of RC for v11.0.0?
