### ISSUE TITLE
Remove central-ledger dependency from central-settlements

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#647]
## **Goal**:
As a Maintainer of the ML OSS codebase
I want to Remove central-ledger dependency from central-settlements
so that the settlements service is independent and uses API calls instead of having the dependency on central-ledger.

**Tasks**:
- [ ] Design for changes needed [@vgenev]
- [x] Discussion of the options in the comment - option 3 has been selected
- [ ] Add tasks for implementation of Option 3 to this story
- [ ] Remove central-ledger dependency from central-settlements and call api's on central-ledger to adjust the limits
- [ ] Update / fix tests

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] central-settlement does not use central-ledger as a dependency (but now uses API calls to make necessary changes)

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
