### ISSUE TITLE
Update NodeJs runtime from 8.4.x to 10.15.x LTS - 4

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#648]
## **Goal**:
As a ML OSS maintainer
I want to `upgrade NodeJs runtime from 8.4.x to 10.15.x LTS`
to ensure that `we are running on the latest LTS version of NodeJS to reduce security threats and benefit from performance enhancements.`

**Tasks**:
- [x] Upgrade **central-services-shared** to latest version and release [@ggrg]
  - [x] Backup branches, remove develop and set up master with latest code [@ggrg, @rmothilal]
  - [x] Pull request and release [@ggrg, @rmothilal]
- [x] Upgrade **central-services-stream** to latest version and release [@ggrg]
  - [x] Backup branches, remove develop and set up master with latest code [@ggrg, @rmothilal]
  - [x] Resolve issue with recursive unit tests [@rmothilal]
  - [x] Upgrade dependencies [@ggrg]
  - [x] Fix standard code style issues [@ggrg]
  - [x] Fix issues identified by IntelliJ > Analyze > Inspect Code [@ggrg]
  - [x] Plugin updated dependency locally into central-ledger and confirm successful run [@ggrg]
  - [x] Pull request and release [@ggrg]
- [x] Upgrade **central-services-error-handling** to latest version and release [@ggrg]
  - [x] Backup branches, remove develop and set up master with latest code [@rmothilal]
  - [x] Upgraded dependencies, gitignore, intelliJ inspect code
  - [x] Pull request and release [@ggrg]
- [x] Upgrade **central-services-database** to latest version and release [@ggrg]
  - [x] Backup branches, remove develop and set up master with latest code [@ggrg, @rmothilal]
  - [x] Merge changes from backup/master-2019-02-22 [@ggrg]
  - [x] Upgrade dependencies [@ggrg]
  - [x] Fix standard code style issues [@ggrg]
  - [x] Fix issues identified by IntelliJ > Analyze > Inspect Code [@ggrg]
  - [x] Plugin updated dependency locally into central-ledger and confirm successful run [@ggrg]
  - [x] Pull request and release [@ggrg]
- [x] Upgrade **central-services-metrics** to latest version and release [@ggrg]
  - [x] Backup branches, remove develop and set up master with latest code [@rmothilal]
  - [x] Upgraded dependencies, circleci, gitignore, intellij inspect code
  - [x] Pull request and release [@ggrg]
- [x] Upgrade **central-services-auth** to latest version and release [@ggrg]
  - [x] Backup branches, remove develop and set up master with latest code [@rmothilal]
  - [x] Upgrade dependencies, circleci runtime, gitignore, standard, intelliJ
  - [x] Pull request and release [@ggrg]
- [x] Upgrade **forensic-logging-client** to latest version and release
  - [x] Backup branches, remove develop and set up master with latest code [@rmothilal]
  - [x] Upgrade dependencies, circleci, standard, intellij inspect code, gitignore [@ggrg]
  - [x] Pull request and release [@ggrg]

**Acceptance Criteria**:
- [x] Ensure all images/packages are built against NodeJs 10.15.x
- [x] Ensure that all NodeJs dependencies are updated to the latest version
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Packages/Images are built and released/published

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-shared/pull/32
- [x] https://github.com/mojaloop/central-services-shared/pull/33
- [x] https://github.com/mojaloop/central-services-shared/pull/34
- [x] https://github.com/mojaloop/central-services-stream/pull/2
- [x] https://github.com/mojaloop/central-services-database/pull/24
- [x] https://github.com/mojaloop/central-services-auth/pull/18
- [x] https://github.com/mojaloop/central-services-error-handling/pull/16
- [x] https://github.com/mojaloop/forensic-logging-client/pull/10
- [x] https://github.com/mojaloop/central-services-metrics/pull/6

## **Notes**:
- [x] Bug has been created for the unit tests which also impacts the coverage: [#652](https://github.com/mojaloop/project/issues/652)
## **Follow-up**:
- [ ] #628
- [ ] #629

**Dependencies**:
- [x] #604 

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
