### ISSUE TITLE
Update NodeJs runtime from 8.4.x to 10.15.x LTS - 5

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#649]
## **Goal**:
As a ML OSS maintainer
I want to `upgrade NodeJs runtime from 8.4.x to 10.15.x LTS`
to ensure that `we are running on the latest LTS version of NodeJS to reduce security threats and benefit from performance enhancements.`

**Tasks**:
- [x] Upgrade Email-Notifier to 10.15.x
- [x] Upgrade CEP to 10.15.x
- [ ] ~Upgrade forensic-logging-sidecar to 10.15.x~
- [x] Upgrade pathfinder-query-client to 10.15.x
- [x] Upgrade pathfinder-provisioning-client to 10.15.x
- [x] Upgrade mock-pathfinder to 10.15.x

**Acceptance Criteria**:
- [x] Ensure all images/packages are built against NodeJs 10.15.x
- [x] Ensure that all NodeJs dependencies are updated to the latest version
- [x] Unit Tests pass (Email-Notifier)
- [ ] ~Unit Tests pass - CEP~ test are pending #558 
- [x] Integration Tests pass - Email-Notifier
- [ ] ~Integration Tests pass - CEP~ tests are pending #558 
- [x] Packages/Images are built and released/published

## **Pull Requests**:
- [x] https://github.com/mojaloop/email-notifier/pull/25
- [x] https://github.com/mojaloop/central-event-processor/pull/30
- [x] mojaloop/mock-pathfinder/pull/12
- [x] mojaloop/pathfinder-query-client/pull/12
- [x] mojaloop/pathfinder-provisioning-client/pull/11

## **Follow-up**:
- [x] #629 

**Dependencies**:
- [x] #604 
- [x] #559 

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Pr for `pathfinder-query-client`: https://github.com/mojaloop/pathfinder-query-client/pull/12

**Comment by lewisdaly** [comment]
Pr for `pathfinder-provisioning-client`: https://github.com/mojaloop/pathfinder-provisioning-client/pull/11

**Comment by lewisdaly** [comment]
Pr for `mock-pathfinder`: https://github.com/mojaloop/mock-pathfinder/pull/12

**Comment by elnyry** [comment]
Thanks @lewisdaly , the PRs were approved by @rmothilal and @ggrg and @vgenev , so I merged them. Closing this story now
