### ISSUE TITLE
Automate the CD pipeline for central-end-user-registry

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#65]
**Goal**:
As a developer I would like to automate the CD pipeline for central-end-user-registry so that I can shorten the delivery cycle

**Tasks**:
- [x] tasks for CD pipeline are put in place, will be triggered when either merged with master or tagged, etc.

**Acceptance Criteria**:
- [ ] Define and document the deployment process and requirements
- [ ] Automate the deployment through k8s for master and develop push tags

**Dependencies**:
- None currently

**Comment by elnyry** [comment]
PR: https://github.com/mojaloop/central-end-user-registry/pull/6
