### ISSUE TITLE
Extending and standardizing the QA Framework - Part 1

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#650]
## **Goal**:
As an Open Source Community member of the Mojaloop codebase
I want to use the Regression testing framework
so that I can assess the quality/state of a Mojaloop Switch deployment

**Tasks**:
- [x] Ensure tests pass 100% if there are no failures [or should have bugs logged] [@sri-miriyala, @NicoDuvenage ]
- [x] Clean-up the Postman collection @sri-miriyala 
- [x] Provide examples in documentation on how to run various sets of tests
- [x] Provide an initial test that verifies the setup of the Framework itself, even before running the tests on a given deployment @sri-miriyala 

**Acceptance Criteria**:
- [x] The Regression testing framework has 100% pass rate on a deployment that has no bugs/issues
- [x] Documentation contains example commands on how to use the framework on any ML deployment
- [x] A test step is made available that helps verify the setup of the framework is correct

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-qa-regression-testing/pull/5

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
Moving this to next Sprint; attributed to availability

**Comment by sri-miriyala** [comment]
Most of the features has been cleaned-up.  Separate collection is available to point the automated tests.only 1 test failing in transfers-timeout scenario and bug is already opened on it.
