### ISSUE TITLE
Extending and standardizing the QA Framework · Part 2

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#651]
## **Goal**:
As an Open Source Community member of the Mojaloop codebase
I want to use the Regression testing framework
so that I can assess the quality/state of a Mojaloop Switch deployment

**Tasks**:
- [x] All QA tests to run against the collections hosted directly from GitHub (already done on qa.mojaloop.live box) ~ Github is the one true source for OSS tests
- [x] The QA Test reports should clearly show the request/responses for each step (currently some only show the Simulator results)
- [x] The simulator results do not seem to be available after a test has been completed (investigate)
- [x] The announcements in the slack channel should also indicate the type of report/test-result (i.e. Feature vs API etc). At the moment all tests are announced as "QA Test Results <Timestamp>" with no difference.
- [x] Changes to the QA framework follow the OSS feature/branch PR strategy.
- [x] Extend the documentation to include the process required to link notification to Slack

**Acceptance Criteria**:
- [x] The Regression testing framework covers 100% of deployed functionality
- [x] Contract testing is available via the QA framework
- [x] Results to show request/response for each test/assertion clearly
- [x] Announcements and results to have clear naming to indicate the features tested
- [x] QA framework to be configurable using required/optional parameters
- [x] Updates to QA Framework follow the adopted OSS branching [strategy](https://github.com/mojaloop/documentation/blob/master/contributors-guide/standards.md)

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @NicoDuvenage 
- QA/Review: TBC
