### ISSUE TITLE
Announcement Notifications are published on Slack Channels for new library Releases

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#653]
## **Goal**:
As a `Mojaloop Open Source maintainer`
I want to `enable auto-announcements through via the CI/CD pipeline for new releases`
so that `all stakeholders are aware of new releases & features`

**Tasks**:
### Announcements
- [x] central-services-stream has slack announcements(@mdebarros )
- [x] central-services-shared has slack announcements(@HenkKodde )
- [x] central-services-db has slack announcements(@HenkKodde )
- [x] central-services-error has slack announcements(@HenkKodde )
- [x] central-services-metrics has slack announcements(@HenkKodde )

### Badges
- [x] central-services-stream has badges on readme.me(@mdebarros )
- [x] central-services-shared has badges on readme.me(@HenkKodde )
- [x] central-services-db has slack badges on readme.me( Already updated)
- [x] central-services-error has slack badges on readme.me(@HenkKodde )
- [x] central-services-metrics has slack badges on readme.me (Already updated)

**Acceptance Criteria**:
- [x] CI/CD Pipeline sends announcements to the Mojaloop general Slack channel for new releases that are published for the below repos:
  - [x] central-services-stream
  - [x] central-services-shared
  - [x] central-services-db
  - [x] central-services-error
  - [x] central-services-metrics
- [x] Readme.md have appropriate badges:
  - [x] central-services-stream
  - [x] central-services-shared
  - [x] central-services-db
  - [x] central-services-error
  - [x] central-services-metrics

## **Pull Requests**:
- [x] central-services-stream: https://github.com/mojaloop/central-services-stream/pull/4
- [x] central-services-shared: https://github.com/mojaloop/central-services-shared/pull/35
- [x] central-services-db: https://github.com/mojaloop/central-services-database/pull/25
- [x] central-services-error: https://github.com/mojaloop/central-services-error-handling/pull/17
- [x] central-services-metrics: https://github.com/mojaloop/central-services-metrics/pull/7

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
