### ISSUE TITLE
ML OSS Account Lookup Service (ALS) Design - 1 

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#655]
## **Goal**:
As a DFSP
I would like to have a design to _request a Participant detail based on a Party ID as per the Specification_
so that _a Party Identifier [currently MSISDN] can be used for looking up Participant details_

As a DFSP
I would like to have a design to _request a Party's details, as per the Specification_
so that _a Party Identifier [currently MSISDN] can be used for looking up Party details_

As a Hub Operator
I would like to have a design to _support looking up a Participant detail based on a Party ID as per the Specification_
so that _a Party Identifier [currently MSISDN] can be used for looking up Participant details_

As a Hub Operator
I would like to have a design to _support looking up a Party's details, as per the Specification_
so that _a Party Identifier [currently MSISDN] can be used for looking up Party details_

**Tasks**:
- [x] Refactor architecture diagrams for generic use and extensibility with the proposed design
- [x] Refactor sequence diagrams for generic use and extensibility with the proposed design
    - [x] GET /participant
    - [x] GET /parties
    - [x] POST /participant 
- [x] Refactor/Create DB schema with the proposed design
- [x] Define and document a standard interface for oracles/directories so that they can be plugged-in/integrated into the ALS - #677 
- [x] A narrative document on the ALS, motivations behind design decisions, etc. (Block diagrams and such)
- [x] Document DB design
- [x] Review by the DA
- [x] Updates from DA Review
 - General:
   - [x] Improve some of the descriptions such as the validation sections by adding which FSP is validated
 - GET /participant
   - [x] When filter for currency is provided, but no results are provided an error will be thrown
   - [x] Typo fix for the ENUM on the Callback URL
   - [x] Add reference to re-usable participant flow logic
 - POST /participant
   - [x] When currency is provided (as its optional), but no results are provided an error will be thrown
 - GET /parties
   - [x] Add which FSP is being validated
   - [x] Reference the /participant flow
 - Database
   - [ ] ~ALS - Add table for central switch lookups~
 - Oracle API:
   - [x] Include note in the specifications to the differences between ML Spec and Oracle

**Acceptance Criteria**:
- [x] The re-alignment of all the discussed designs are targeted towards the current use case
- [x] The existing contributed ALS component is re-aligned to the OSS requirements, standards, etc determined by the ML DA
  - [x] The current sequence diagrams are refactored for generic use and extensibility
  - [x] The architecture diagrams are refactored for generic use and extensibility
  - [x] The DB Schema is refactored for generic use and extensibility
  - [x] A Swagger / Open API specification is made available to depict the interactions
  - [x] The sequence diagrams, architecture diagrams, DB schema are approved by the DA
- [x] Designs adhere to the following principles:
  - [x] The design should allow for multiple oracles/directories to be plugged into the ALS solution
  - [x] A standard interface is defined for oracles/directories so that they can be plugged-in/integrated into the ALS
  - [x] As new Oracles/directories are introduced, they should be pluggable with configuration changes and should not require code-changes to the ALS
  - [x] The ALS should not access the central-ledger DB directly, but use APIs as relevant
  - [x] The ALS should have its own independent DB 
- [x] Follow-up stories for implementation are created

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- 

**Dependencies**:
- [ ] #619 
- [ ] #657 
- [ ] #658
- [ ] #660 

## **Accountability**:
- Owner: TBC
- QA/Review: DA
