### ISSUE TITLE
ML OSS Account Lookup Service (ALS) Implementation -Testing

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#656]
## **Goal**:
As a DFSP
I would like to have an implementation that is fully tested that meets the minimum requirements for code coverage. I would also want integration tests to fully test the ALS integration with Oracles and central-ledger. 

**Tasks**:
- [ ] Refactor the ALS code-base according to the design
  - [x] Unit tests
    - [x] Oracle
    - [x] Parties
    - [x] participant
  - [x] Code Coverage
  - [ ] Integration tests
- [x] Update all dependencies
- [x] Fix knex pooling issue (@rmothilal  may have more info on this)
~- [ ] Update the helm charts for updated `default.json` config:~
  ~- [ ] `DISPLAY_ROUTES`~
  ~- [ ] `DB_CONNECTION_POOL_MIN` and `DB_CONNECTION_POOL_MAX`~
Helm config will be covered as a part of #1008 helm changes

**Acceptance Criteria**:
- [ ] Unit tests [Now using JEST testing framework]
- [ ] Code coverage [Coverage is by the built in coverage tool in JEST i.e. nyc]
- [ ] Integration tests

**Notes**:
Please check code in quoting service to validate how to configure JEST in the package.json 

**Pull Requests**:
- [x] https://github.com/mojaloop/account-lookup-service/pull/81 - Updating dependencies and fixing tests
- [x] https://github.com/mojaloop/account-lookup-service/pull/93 - Major refactor of tests and coverage
- [x] https://github.com/mojaloop/account-lookup-service/pull/100 - Integration tests
- [ ] TBD

**Follow-up**:
- TBD

**Dependencies**:

**Accountability**:
- Owner: @rmothilal 
- QA/Review: @rmothilal @mdebarros

**Comment by lewisdaly** [comment]
I'm currently waiting for review on the major unit test PR before adding the integration test config.
