### ISSUE TITLE
Design for an adapter for pathfinder using UDP so that it can be used as a template

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#657]
## **Goal**:
As an ML OSS codebase maintainer
I want to Create an adapter for pathfinder using UDP to use the existing components
so that it can be used as a template and to assist with testing ALS

**Tasks**:
- [ ] Design an adapter for pathfinder using UDP leveraging existing features/codebase
- [ ] Design for Integration with ALS
- [ ] Review designs

**Acceptance Criteria**:
- [ ] A design for an adapter for Pathfinder (over UDP) that can be integrated with ALS is documented and reviewed.

**Notes**:
- Note that this is for the design based on the existing mock-pathfinder setup

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- [ ] #655 

## **Accountability**:
- Owner: TBC
- QA/Review: DA
