### ISSUE TITLE
Design for an adapter for pathfinder using TCP so that it can be used as a template

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#658]
## **Goal**:
As an ML OSS codebase maintainer
I want to Create an adapter for Pathfinder using TCP to use the existing components
so that it can be used as a template and to assist with testing ALS (using the existing ALS component donated by Mowali as reference)

**Tasks**:
- [ ] Design an adapter for Pathfinder using TCP leveraging existing features/codebase (donated by Mowali)
- [ ] Design for Integration with ALS
- [ ] Review designs

**Acceptance Criteria**:
- [ ] A design for an adapter for Pathfinder (over TCP) that can be integrated with ALS is documented and reviewed.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- [ ] #655 

## **Accountability**:
- Owner: TBC
- QA/Review: DA
