### ISSUE TITLE
Investigate a way to test the PathFinder over TCP (over TLS) possibly contacting GSMA Pathfinder

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#660]
## **Goal**:
As an ML OSS codebase maintainer
I want to _Investigate a way to test the PathFinder over TCP (over TLS) possibly contacting Pathfinder_ so that _adapters for Pathfinder (for ALS that use TCP) can be tested

**Tasks**:
- [ ] Explore ways to test the Pathfinder adapter that uses TCP
- [ ] Contact PathFinder to explore options for using a test PathFinder service etc
- [ ] Setup integration for testing, etc

**Acceptance Criteria**:
- [ ] A setup/configuration is available with a test PathFinder instance to enable testing of a PathFinder adapter

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
