### ISSUE TITLE
ALS: Upgrade Node[10.15.x LTS] and dependency versions for the adopted, existing ALS service

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#661]
## **Goal**:
As a Mojaloop OSS codebase maintainer
I want to _Upgrade Node[10.15.x LTS] and dependency versions of the adopted, existing ALS service_
so that _it is brought up to the same version as the rest of the Switch services_

**Tasks**:
- [x] Upgrade Node version of the existing/adopted ALS

**Acceptance Criteria**:
- [x] Node version of the adopted ALS service is upgraded
- [x] Versions of all included dependencies are upgraded as relevant.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by rmothilal** [comment]
Completed
