### ISSUE TITLE
ML ALS: PathFinder pluggable component/adapter

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#664]
## **Goal**:
As a Hub Operator
I would like to have an implementation _for an adapter for Pathfinder which can be plugged into the existing ALS_
so that _PathFinder can be supported using the ALS and a standard interface_

**Tasks**:
- [ ] Create a GitHub repo for the PathFinder pluggable component/adapter
- [ ] Create a pluggable component/adapter for PathFinder
  - [ ] Unit tests
  - [ ] Code Coverage
  - [ ] Integration tests
  - [ ] Enable CI/CD

**Acceptance Criteria**:
- [ ] The implemented pluggable component/adapter for PathFinder aligns to the design
- [ ] PathFinder specific code has been moved into the separate pluggable component/adapter
  - [ ] Implements/Adheres to the standard Directory/Oracle interface (If it is Swagger, the implementation to be generated using API first approach)
  - [ ] This should be a separate repo
  - [ ] CI/CD pipeline is enabled
  - [ ] Unit tests [Reports provided by `faucet`]
  - [ ] Code coverage [Reports provided by `Istanbul`]
  - [ ] Integration tests

**Pull Requests**:
- [ ] TBD

**Follow-up**:
- N/A

**Dependencies**:
- [x] Upgrade Node[10.15.x LTS] and dependency versions - #661 
- [x] #655 

**Accountability**:
- Owner: TBC
- QA/Review: DA

**Comment by msk-** [comment]
See:
https://github.com/mojaloop/als-oracle-pathfinder

This is essentially a port of the Mowali Pathfinder-based central directory service to an oracle.

It doesn't meet all the criteria above. Specifically:
* Pathfinder is a pluggable component, but is not in a separate repo
* No coverage for tests
* No integration tests
* No CI/CD

I have no idea whether it 'aligns to the design'. Probably not, given that I'm ignorant to said requirement.

I don't think I was made aware of this GH issue previously. Hence non-compliance. Sorry to anyone reading this who thinks "yes he was". Maybe I was...

Anyway, some questions to move forward:
* When referring to integration tests, does the above mean pathfinder<->oracle integration, or oracle<->ALS integration, or something else?
* Is CircleCI acceptable? That'll be easy to implement.
