### ISSUE TITLE
Integration tests for 'aborted' transfers

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#665]
## **Goal**:
As a maintainer of the OSS codebase
I want to have _integration tests for the 'aborted' transfers_
so that _the implementation covering these scenarios is tested with integration tests and to thereby improve quality_

**Tasks**:
- [x] Re-assess existing strategy used by the integration tests for transfers [@ggrg]
- [x] Propose a new strategy, if possible [@ggrg]
- [x] Add integration tests for aborted transfers (reject/abort)

**Acceptance Criteria**:
- [x] Integration Tests pass
- [x] Integration Tests provide coverage for the transfers and have no issues running locally & on CircleCI
- [x] Features covered by integration tests are documented

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/256

## **Follow-up**:
- N/A

**Dependencies**:
- [x] #281 

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
