### ISSUE TITLE
Design for implementing bulk Transfers -1

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#666]
## **Goal**:
As a Hub Operator
I want to _have a design for the bulk transfers Use Case (the /bulkTransfers end-point)_
so that _I can use it to support the bulk Transfers use-case with an implementation that uses this as reference (based on the API Definition)._ 

**Tasks**:
- [x] Study/Investigate bulkTransfers functionality in the API Definition [@elnyry, @ggrg ]
- [x] Initial Architecture diagram for bulkTransfers proposal [@elnyry, @ggrg ]
- [x] Design a draft proposal for implementing the /bulkTransfers end-point [@elnyry, @ggrg ]
- [x] Discuss proposal with interested core team members and brainstorm [@elnyry, @ggrg ]
- [x] Incorporate feedback and present to team for review
- [x] Provide sequence diagrams for the design (provided for bulk prepare handler, overview)
- [x] Provide PR for changes
- [ ] ~Have the design ready for review by the DA~

**Acceptance Criteria**:
- [x] Draft Architecture diagrams are provided for supporting /bulkTransfers end-point as specified in the API Definition to the DA
- [x] Draft Sequence diagrams are provided for supporting /bulkTransfers to the DA (provided for bulk prepare handler, overview)
- [ ] ~Update existing sequence diagrams for~
  - [ ] ~prepare handler~
  - [ ] ~position handler~
  - [ ] ~fulfil handler~
  - [ ] ~timeout handler~
- [ ] ~Where sequence diagrams are not relevant (or not applicable) documentation is provided addressing the designs for /bulkTransfers end-point~
- [x] Follow-up stories for reviews and further design are provided

**Pull Requests**:
- [ ]

**Follow-up**:
- [ ] #693

**Dependencies**:
- N/A

**Accountability**:
- Owner: @elnyry 
- QA/Review: DA

**Notes**:
- BulkTransfers are intended to be sent only to a single Payee FSP by the Payer FSP
- BulkQuotes however, depending on the FSP implementation may be sent to a single Payee or multiple Payees. The Mojaloop Specification supports both of these, but currently there is no quotes service implemented by the Open Source Switch, hence only a forwarding service should be considered as available (if/when a Gateway is provided). In this case, only bulkQuotes to a single FSP will be supported.

**Comment by elnyry** [comment]
Follow-up work done in #693
