### ISSUE TITLE
All relevant documentation updated/moved to the documentation repo

### ISSUE THREAD

**Issue by kjw000** [mojaloop/project#669]
## **Goal**:
As a Mojaloop contributor
I want to easily understand the documentation
so that I can contribute and get answers to common problems.

**Tasks**:
- [ ]  Review relevant components by area
- [ ]  Update documentation to comply to new standards that include the business overview
- [ ]  Move the .md file to the specific sub-directory in /documentation
- [ ]  Move all diagrams to /documentation/.gitbooks/assets
- [ ]  Update links
- [ ] Incorporate new .md file in Gitbooks/mojaloop
- [ ] Archive old diagrams

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Links are working
- [ ] Gitbook is updated

**Comment by elnyry** [comment]
hi Kim, don't think we can get to this in this Sprint.. This is beyond capacity at this time. Lets take this up next sprint.

**Comment by kjw000** [comment]
Actually - lets go ahead and close this and then open up specific stories for individual repos.  IT would be easier to track and monitor.
