### ISSUE TITLE
Latest release and component information is easily obtained

### ISSUE THREAD

**Issue by kjw000** [mojaloop/project#670]
## **Goal**:
As a contributor I want to know the latest release/components so that I can deploy the latest version.

**Tasks**:
- [x] Roll-up all releases and components
- [x] Have an easy publish site (Github, Slack)
- [x] Ensure this can be linked to from mojaloop.io and Gitbooks

**Acceptance Criteria**:
- [ ] Docs are up-to date
- [ ] Links are easy to find 

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
@kjw000 currently we have announcements for releases published to slack on the #announcements channel and also recently published an update to the documentation repo (in a PR I recently raised).

What else did you intend to cover as part of this?

**Comment by elnyry** [comment]
Please re-open if there's anything else..
