### ISSUE TITLE
Update deployment docs for all core components and move to Documentation

### ISSUE THREAD

**Issue by kjw000** [mojaloop/project#671]
## **Goal**:
As a contributor I want to be able to have updated documentation to install the individual mojaloop components.

**Tasks**:
- [ ] For all CORE services update the documentation
- [ ] Move the updated deployment for all core documentation to the documenation repo
- [ ] Move the updated diagrams for all core documentation to the documenation/.gitbooks/assets repo
- [ ] Update Gitbooks

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by kjw000** [comment]
I am closing out this story and will open up individual stories for the different services to enable better tracking.
