### ISSUE TITLE
Create short md file to describe automated testing process

### ISSUE THREAD

**Issue by kjw000** [mojaloop/project#672]
## **Goal**:
As a contributor, I want to understand our automated testing process.

**Tasks**:
### Admin API Tasks:
- [x] Create a short description of the automated test process
- [x] Explain framework and regression testing
- [x] Update md file here: https://github.com/mojaloop/documentation/blob/master/contributors-guide/tools-and-technologies/automated%20testing

**Acceptance Criteria**:
 - [x] After reading this short guide anyone will understand how Mojaloop Core has implemented QA and regression testing

**Pull Requests**:
- [x] https://github.com/mojaloop/documentation/pull/57

**Follow-up**:
- N/A

**Dependencies**:
- N/A

**Accountability**:
- Owner: @NicoDuvenage  
- QA/Review:
