### ISSUE TITLE
QA - Validate Metrics, Dashboards and dev1 environment

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#673]
## **Goal**:
As a Mojaloop OSS codebase maintainer
I want to _perform QA to validate metrics, dashboards updates on dev1 environment_
so that _I can validate functionality against the specification and record observations_

**Tasks**:
- [ ] Instrumentation for metrics into Helm Charts #584 -  Test Dev Deployment @NicoDuvenage
- [ ] Bug - Grafana dashboards are not displaying any metrics #601 - @NicoDuvenage please verify/update your tests based on the following document https://github.com/mojaloop/helm/blob/master/monitoring/METRICS.md
- [ ] Setup new secure K8s environment with HA #631
- [ ] Test behavior of Switch for a `GET /transfers/{ID}` call to ensure an error callback is made when an FSP that is not involved in a transfer is the source of the GET call. (However, for an FSP that is involved in a transfer, a valid PUT callback is made)

**Acceptance Criteria**:
- [ ] Dev1 environment has been verified using QA Framework
- [ ] Central-Ledger metrics end-points tested on Dev environment
- [ ] ML-API-Adapter metrics end-points tested on Dev environment
- [ ] Simulators Helm metrics end-points tested on Dev environment
- [ ] GET /transfers/{ID} behavior on the Switch is validated

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
