### ISSUE TITLE
Address issues in packages reported by GitHub

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#674]
## **Goal**:
As a Mojaloop OSS codebase maintainer
I want to _address issues in packages reported by GitHub
so that those vulnerabilities can be fixed.

**Tasks**:
- [x] lodash in FLS [@henkkodde] 
- [x] mock-pathfinder [@ggrg]
  - [x] cryptiles (Upgrade cryptiles to version 4.1.2 or later) [@ggrg]
  - [x] hoek (Upgrade hoek to version 4.2.1 or later) [@ggrg]
    - [x] Upgrade dev dependency @mojaloop/pathfinder-provisioning-client to Node v10 & release [@ggrg]
    - [x] Upgrade dev dependency @mojaloop/pathfinder-query-client to Node v10 & release [@ggrg]
- [ ] ~dfsp-ledger~ (@ggrg: this repo is deprecated, do we really need to maintain it? Currently `npm audit` shows: `found 601 vulnerabilities (258 low, 322 moderate, 21 high)`)
  - [ ] ~lodash~ (Patched version: 4.17.11)

- [ ] ~central-hub~ [@ggrg]
  - [ ] ~react-dom~ (Patched version: 16.2.1)

- [ ] documentation repo [@ggrg]
  - [ ] ~cryptiles (Patched version: 4.1.2)~
  - [ ] ~lodash (Patched version: 4.17.11)~
  - [ ] ~hoek (Patched version: 4.2.1)~
  - [ ] ~jquery (Patched version: 3.0.0)~
  - [ ] ~handlebars (Patched version: 4.0.0)~

@ggrg: I don't see Github reporting the above packages. `npm audit` output 107 vulnerabilities (14 low, 74 moderate, 19 high) even though the dependencies are already updated to the latest releases. So, there's not much we can do before new releases of those packages are released addressing those vulnerabilities.

**Acceptance Criteria**:
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Versions of packages reported as vulnerable by GitHub alerts are addressed and fixed/upgraded
- [ ] ~Regression testing is done and is either passes or bugs are logged for failures~

## **Pull Requests**:
- [x] https://github.com/mojaloop/pathfinder-provisioning-client/pull/10
- [x] https://github.com/mojaloop/pathfinder-query-client/pull/11
- [x] https://github.com/mojaloop/mock-pathfinder/pull/11

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by ggrg** [comment]
Not sure about the current estimate of the story, as it looks to me as an estimate for 1 or 2 repos. The edit history shows more repos were added without reflecting the estimate.
