### ISSUE TITLE
Update Mojaloop deployment guide to reference environment setup in separate documents.

### ISSUE THREAD

**Issue by HenkKodde** [mojaloop/project#675]
## **Goal**:
As a community member, it would be preferable to reference the specific operation system setup requirements in separate documents. This would decrease the complex-ability of the current document and having to skip over sections. 

**Tasks**:
- [x] Split the environment setup instructions from the current on-boarding document [ @HenkKodde  ]
  - [x] Mac environment setup guidelines [ @HenkKodde  ]
  - [x] Ubuntu environment setup guidelines [ @HenkKodde  ]
- [x] Update current on-boarding document to reference the appropriate environment setup guide[ @HenkKodde  ]

**Acceptance Criteria**:
- [x] Environment, resources and OS versions are clearly declared
- [x] Documents are easy to follow
- [x] Appropriate references to 3rd party utilities for implementers to familiarise them self. Links to "training sites" should also be provided if appropriate.
- [x] Clarify a level of competency and the audience the document is intended for 

## **Pull Requests**:
- [x] https://github.com/mojaloop/documentation/pull/6

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @HenkKodde 
- QA/Review: TBC
