### ISSUE TITLE
Design an Interface between an Account Lookup Service (ALS) and adapters for Directory services (oracles)

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#677]
## **Goal**:
As a Hub Operator
I want to _create a standard interface between an Account Lookup Service (ALS) and adapters for Directory services (oracles)_
so that _it can be used by adapter developers to support various Directories such as Merchants, Bank Accounts and others_ while keeping the basic ALS pretty much the same.

**Tasks**:
- [x] Design a standard interface for interactions between an Account Lookup Service (ALS) and adapters for Directory services (oracles)
- [x] Review designs
- [x] Incorporate feedback from designs and publish

**Acceptance Criteria**:
- [x] A Swagger specification that captures the interface for interactions between an Account Lookup Service (ALS) and adapters for Directory services (oracles) is available 
- [x] The above Swagger is reviewed and published

**Notes**:
- 

## **Pull Requests**:
- [ ]

## **Follow-up**:
- N/A

**Dependencies**:
- [ ] #655 

## **Accountability**:
- Owner: TBC
- QA/Review: DA
