### ISSUE TITLE
ML OSS: Adopting central-directory as account-lookup-service -2

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#679]
## **Goal**:
As a maintainer of the ML OSS codebase
I want to take necessary actions to adopt the central-directory contributed by Mowali to OSS
so that it is ready for integration with the rest of the OSS services and Open source consumption.

**Tasks**:
- [x] Implement changes as recommended and documented
  - [x] Folder structure
  - [x] Updating Packages
- [x] Remove PathFinder applicable code
- [x] Refactor the use of central-ledger to API calls (remove DB access to central-ledger DBs from ALS)
- [ ] Run the service, tests, etc
- [ ] Refactor the services to work with updated design
- [ ] Rewrite tests for updated code base
- [ ] Deprecate the current central-directory
- [ ] Deprecate the current central-end-user-registry
- [ ] Update helm charts to deploy the new ALS (in place of the earlier central-directory)
  - [ ] Remove central-directory from the helm charts

**Acceptance Criteria**:
- [ ] The end-points supported by the ALS are made available on the ML Switch deployment (though functionality may not be available)
- [ ] ALS does not access central-ledger DB but uses APIs to gather required information
- [ ] The new ALS repo conforms to the conventions used on other ML OSS repos
- [ ] Testing for base code is available
  - [ ] Unit tests are available
  - [ ] Coverage tests are available
  - [ ] Integration tests are available

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- 

**Dependencies**:
- 

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
