### ISSUE TITLE
Upgrade helm to v5.4.0

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#680]
## **Goal**:
As a deployer of ML OSS Switch
I want to _have an upgraded version (v5.4.0) of helm on Mojaloop GitHub_
so that _I can deploy the latest versions of central (and supporting) services_

**Tasks**:
- [x] Update helm scripts corresponding to the changes below
  - [x] https://github.com/mojaloop/central-ledger/pull/252
  - [x] https://github.com/mojaloop/central-ledger/pull/255
  - [x] https://github.com/mojaloop/email-notifier/commit/6aa2d4d4780e7304e3b2bc29bb6a8cfa49e1351e
  - [x] https://github.com/mojaloop/central-event-processor/commit/557de8327d7b45c067ea710f5a92afd26bf8a06d
  - [x] https://github.com/mojaloop/ml-api-adapter/pull/96
- [x] Update for new releases:
  - [x] Central-Ledger v5.4.0
  - [x] ML-API-Adapter v5.4.0
  - [x] Central-Settlements v5.3.0
  - [x] Central-Event-Processor v5.3.0
  - [x] Email-Notifier v5.3.0
- [x] Update configuration on values files
- ~Refactor charts for mysql~ for later
  - ~central-end-user-registry~
  - ~FLS~
  - ~mock-pathfinder~
- [x] Update version numbers to include up-to-date versions of core central services

**Acceptance Criteria**:
- [x] A new version of helm is released and published that includes the up-to-date versions of core central services

**Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/154
- [x] https://github.com/mojaloop/helm/pull/155

**Follow-up**:
- N/A

**Dependencies**:
- N/A

**Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
Thanks Miguel, this is now deployed on AWS DEV0
