### ISSUE TITLE
Propose Enhancements for ML_Adapter Code

### ISSUE THREAD

**Issue by kjw000** [mojaloop/project#683]
## **Goal**:
As a developer I want the ML_Adapter code to be optimized for performance (improved over current implementation) and I want the code to be well-structured and easy to ready for new contributors.

**Tasks**:
- [ ] POC to rewrite for ML_Adapter code
- [x] Validate performance exceeds current
- [ ] Ensure new code has unit tests and less lines and written to code standards

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
Hi Kim @kjw000 ,

I added a 'needs clarity' label as the Acceptance Criteria need to be updated.. Right now, it has the default ones that come with the template.

Also, can you please re-phrase the Goal by adding a phrase that expresses business value?

**Comment by elnyry** [comment]
@kjw000 @pedrosousabarreto should we move this over to 5.4?

**Comment by kjw000** [comment]
moving to 5.4 when @pedrosousabarreto has time to address.

**Comment by pedrosousabarreto** [comment]
PoC code here: https://github.com/pedrosousabarreto/ml-api-adapter

Performance of this new implementation is around 800 requests per second for the prepare transfer call with Joi validations for a single instance running on a development grade env (mackbook pro).
This is expected to increase in a production grade, multi instance, environment.

**Comment by mdebarros** [comment]
I have no doubt that Expressjs will beat Hapijs with regard to performance, however, I do believe to "validate" performance one needs to compare apples to apples. 

I would suggest doing a stand-alone comparison between the two to attain figures for the purpose of this validation.

Let me know what you think.

**Comment by elnyry** [comment]
Removing the milestone on this for the time being..

**Comment by elnyry-sam-k** [comment]
@pedrosousabarreto @kjw000 is this still relevant? If not can we close this?
