### ISSUE TITLE
ML OSS: Adopting central-directory as account-lookup-service -3

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#689]
## **Goal**:
As a maintainer of the ML OSS codebase
I want to take necessary actions to adopt the central-directory contributed by Mowali to OSS
so that it is ready for integration with the rest of the OSS services and Open source consumption.

**Tasks**:
- [x] ~Implement changes as recommended and documented~
  - [x] ~Folder structure~
  - [x] ~Updating Packages~
- [x] ~Remove PathFinder applicable code~
- [x] ~Refactor the use of central-ledger to API calls (remove DB access to central-ledger DBs from ALS)~
- [x] Run the service, tests, etc
- [x] Create Helm charts
- [x] Implement CI/CD pipeline
- [ ] ~Refactor the services to work with updated design~
- [ ] ~Rewrite tests for updated code base~
- [x] Deploy ALS without Oracle or oracle adapter as part of Mojaloop
- [x] Update simulator to simulate an Oracle to support end-to-end testing
- [ ] Deprecate the current central-directory #760 
- [ ] Deprecate the current central-end-user-registry #760 

**Acceptance Criteria**:
- [x] The GET participants ML-API end-points supported by the ALS
- [x] ALS does not access central-ledger DB but uses APIs to gather required information
- [x] The new ALS repo conforms to the conventions used on other ML OSS repos
- [x] Helm charts created and published
- [x] CI/CD Pipeline in place
- [ ] ~Testing for base code is available~
  - [ ] ~Integration tests are available~
  - [ ] ~Functional tests are available~
  - [ ] ~Unit tests are available~
  - [ ] ~Coverage tests are available~

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- 

**Dependencies**:
- #696 #705

## **Accountability**:
- Owner: @rmothilal @mdebarros 
- QA/Review: @mdebarros @elnyry 

## **Notes**:
- Continuation from Story: #679 
- Ongoing story as design changes constantly occur
