### ISSUE TITLE
Review MIFOS lab onboarding documentation for hack-a-thon

### ISSUE THREAD

**Issue by kjw000** [mojaloop/project#690]
## **Goal**:
As a hack-a-thon participant
I want to be able to successfully be able to utilize the MIFOS lab to leverage Mojaloop

**Tasks**:
- [x] Validate the environment - QA
- [ ] ~validate documentation~
- [x] add links to Mojaloop documentation

Hackathon - environment details:
https://docs.google.com/spreadsheets/d/1d9J904y0uweoTw7ukvrpXk7KYHZiDZdVZUcnNYBZMjE/edit?usp=sharing

Fineract-Mojaloop - Mifos - DPC - Hackathon - technical
https://docs.google.com/document/d/1-OFKJg1fXtwKlm7BwDQEW0TJnTTOT22KY1PjZpvAbbM/edit?usp=sharing

**Acceptance Criteria**:
- [ ] Docs are up to date
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by kjw000** [comment]
Can we get this done in 5.4?

**Comment by elnyry** [comment]
Thanks Miguel for helping with this
