### ISSUE TITLE
Finalize gitbook publishing model and ensure security

### ISSUE THREAD

**Issue by kjw000** [mojaloop/project#691]
## **Goal**:
As a  Mojaloop consumer I want to be able to easily read Github documentation and take advantage of the Gitbook plugins

**Tasks**:
- [x] Publish Gitbooks to Kubernetes cluster [@mdebarros]
- [x] Ensure site is secure (Reach out to Trey) [@kjw000]
- ~Verify we need DNS entry for the foundation to create~ <-- not required as we are using mojaloop.io/documentation provided by Github hosting via gh-pages
- [x] Script to publish Gitbook via gh-pages on Github [@mdebarros]
- [x] Test Gitbook publishing via gh-pages on Github [@mdebarros]
- [x] Update Documentation link on mojaloop.io to mojaloop.io/documentation instead of docs.mojaloop.io [@kjw000]
- [x] Implement as part of CI/CD process

**Acceptance Criteria**:
- [x] Documentation is hosted on a secure platform
- [x] Docs link on mojaloop.io points to the hosted Documentation environment
- [x] CI/CD pipeline builds and publishes the Documentation on new releases (tags) to the hosted Documentation environment

## **Pull Requests**:
- [x] https://github.com/mojaloop/documentation/pull/23
- [x] https://github.com/mojaloop/documentation/pull/21
- [x] https://github.com/mojaloop/documentation/pull/18
- [x] https://github.com/mojaloop/documentation/pull/15
- [x] https://github.com/mojaloop/documentation/pull/3

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by kjw000** [comment]
Can we get this done in 5.4?

**Comment by pedrosousabarreto** [comment]
I did a bit of a security review for the publishing of this gitbooks documentation and didn’t find anything particularly insecure, however using “gitbook serve”, or any equivalent embedded web servers, is never a good idea. Gitbooks can generate static content that can be served by proper web servers, like S3 or github pages.
 
My advise would be to deploy this to S3 and let S3 do the static serving. We should never server static files/sites from the same servers/clusters that do processing as a rule of thumb.

This will be both safer and faster while keeping out clusters out of the loop.

For this we probably need a change in the deployment scripts and some DNS changes (already in the task list).

**Comment by mdebarros** [comment]
Hey @pedrosousabarreto, 

Thanks for your feedback. It very much mirror's my conclusions.

There have been several updates:

1. the Docker container now uses ExpressJs to serve the documentation. That change was merged into the master branch and has been sitting in a feature branch for over a week. However, this has proven to be unnecessary as per the 2nd point below.

2. We have found an alternative hosting solution: Specifically using gh-pages to host Gitbooks. I have added a script to publish the "current active branch" to the gh-pages branch. This also means that we can now access the documentation on the following url: http://mojaloop.io/documentation

I believe point 2 above alleviates any security concerns. Let me know if you agree.

The only thing that is remaining at this time is to update the CI/CD pipeline to utilise the publish script.

**Comment by mdebarros** [comment]
@kjw000 <-- note that I have updated the task list. Would you be able to update the docs link on mojaloop.io site to point to mojaloop.io/documentation instead of docs.mojaloop.live please?

In the interim I have setup a redirect from docs.mojaloop.live to mojaloop.io/documentation.

**Comment by elnyry** [comment]
Thanks Miguel for this.

Glad to see the passing of burden of hosting it to GitHub itself

**Comment by kjw000** [comment]
I have updated mojaloop.io to point to http://mojaloop.io/documentation

**Comment by mdebarros** [comment]
Proof of CI/CD working as intended:

Link to the release:
- https://github.com/mojaloop/documentation/releases/tag/v5.5.2

Link to the CircleCI workflow:
- https://circleci.com/workflow-run/df7f77d7-7e08-4bb6-888c-c60d7b12b21c

**Comment by mdebarros** [comment]
Closing story as it has been delivered.
