### ISSUE TITLE
ML OSS Account Lookup Service (ALS) Design - 2

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#692]
## **Goal**:
As a DFSP
I would like to have a design to _request a Participant detail based on a Party ID as per the Specification_
so that _a Party Identifier [currently MSISDN] can be used for looking up Participant details_

As a DFSP
I would like to have a design to _request a Party's details, as per the Specification_
so that _a Party Identifier [currently MSISDN] can be used for looking up Party details_

As a Hub Operator
I would like to have a design to _support looking up a Participant detail based on a Party ID as per the Specification_
so that _a Party Identifier [currently MSISDN] can be used for looking up Participant details_

As a Hub Operator
I would like to have a design to _support looking up a Party's details, as per the Specification_
so that _a Party Identifier [currently MSISDN] can be used for looking up Party details_

**Tasks**:
- [x] Refactor sequence diagrams for generic use and extensibility with the proposed design
    - [x] DELETE /participant/{Type}/{ID}
- [x] Updates from DA Review (to the ALS designs)
- [x] Re-factored design to accommodate only a single switch for initial implementation
    - [x] Updated DB Design & Assets
    - [x] Updated Sequence Diagrams
    - [x] Updated Arch Diagrams
- [x] Aligned swagger to Mojaloop specification 

**Acceptance Criteria**:
- [x] The existing contributed ALS component is re-aligned to the OSS requirements, standards, etc determined by the ML DA
- [x] The ALS design caters for GET, POST and DEL Participants
- [x] The ALS design caters for GET Parties

**Pull Requests**:
- [ ] https://github.com/mojaloop/documentation/pull/15

**Follow-up**:
- N/A

**Dependencies**:
- [x] #655 

**Accountability**:
- Owner: TBC
- QA/Review: DA

**Comment by mdebarros** [comment]
Moved tasks/acceptance criteria for Multiple Switch support to a new story -> https://github.com/mojaloop/project/issues/704
