### ISSUE TITLE
Design for implementing bulk Transfers - 2

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#693]
## **Goal**:
As a Hub Operator
I want to _have a design for the bulk transfers Use Case (the /bulkTransfers end-point)_
so that _I can use it to support the bulk Transfers use-case with an implementation that uses this as reference (based on the API Definition)._ 

**Tasks**:
- [ ] Provide PR for
  - [ ] ~changes to prepare handler, position handler, timeout handler~
  - [ ] ~new sequence diagrams for bulk fulfil handler and bulk processing handler~
  - [x] changes to the DB schema to cater for the bulk transfers [@ggrg]
- [x] Have the design reviewed by the DA
- [x] Update architecture diagram for bulkTransfers proposal
- [ ] Update/Provide sequence diagrams for the design
  - [x] Bulk prepare handler
  - [ ] ~prepare handler~
  - [ ] ~position handler~
  - [ ] ~fulfil handler~
  - [ ] ~timeout handler~
  - [ ] ~Bulk processing handler~
  - [ ] ~Bulk Fulfil handler~
- [x] Provide PR for changes
- [x] Feedback from reviews incorporated and designs (Sequence diagrams or markdown files)
- [x] Create follow-up stories based on this for implementation

**Acceptance Criteria**:
- [x] Architecture diagrams are provided for supporting /bulkTransfers end-point (as per theAPI Definition)
- [ ] ~Sequence diagrams are provided for supporting /bulkTransfers~
- [x] DB schema design is updated to cater for bulk transfers
- [ ] ~Existing sequence diagrams for the below are updated~
  - [ ] ~prepare handler~
  - [ ] ~position handler~
  - [ ] ~fulfil handler~
  - [ ] ~timeout handler~
- [x] Where sequence diagrams are not relevant (or not applicable) documentation is provided addressing the designs for /bulkTransfers end-point
- [x] Follow-up stories for implementing the /bulkTransfers end-points are provided (and other requirements such as bulkQuotes)

**Pull Requests**:
- [ ] https://github.com/mojaloop/docs/pull/143
- [ ] https://github.com/mojaloop/central-ledger/pull/267
- [x] https://github.com/elnyry/docs/pull/1

**Follow-up**:
- TBD

**Dependencies**:
- [x] #666 

**Follow-up**:
- #738 
- #739 
- #740 

**Accountability**:
- Owner: @elnyry @ggrg 
- QA/Review: DA

**Notes**:
- BulkTransfers are intended to be sent only to a single Payee FSP by the Payer FSP
- BulkQuotes however, depending on the FSP implementation may be sent to a single Payee or multiple Payees. The Mojaloop Specification supports both of these, but currently there is no quotes service implemented by the Open Source Switch, hence only a forwarding service should be considered as available (if/when a Gateway is provided). In this case, only bulkQuotes to a single FSP will be supported.

**Comment by elnyry** [comment]
The design was presented & discussed at the Mojaloop PI6 convening and alignment achieved. Created follow-up stories for design #738 , #739 , #740
