### ISSUE TITLE
Extending and standardizing the QA Framework · Part 3

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#694]
## **Goal**:
As an Open Source Community member of the Mojaloop codebase
I want to use the Regression testing framework
so that I can assess the quality/state of a Mojaloop Switch deployment

**Tasks**:
- [ ] Validation of incoming/outgoing messages from an API contract perspective should be added to the tests.
- [ ] QA framework needs to introduce a proper parameter parser to handle required/optional parameters 
- [ ] QA framework to be enhanced to include a "folder" selector for the collection that is being tested that is optional
- [ ] QA framework to have an easily configurable environment selector
- [ ] QA framework should also prepare/create/destroy any test data that is required.

**Acceptance Criteria**:
- [ ] The Regression testing framework covers 100% of deployed functionality
- [ ] Contract testing is available via the QA framework
- [ ] Results to show request/response for each test/assertion clearly
- [ ] QA framework to be configurable using required/optional parameters
- [ ] QA Framework to leave a deployment as close to the prior state as possible

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
