### ISSUE TITLE
Design for a configuration API to retrieve configurations

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#695]
## **Goal**:
As a Switch implementer
I want to design a configuration API 
so that there is an API that central services can use to retrieve configurations

**Tasks**:
- [ ] Design the configuration API
- [ ] Initially add this to the central-ledger API (To confirm while working on the story)
- [ ] Create stories to update the central-services based on this design

**Acceptance Criteria**:
- [ ] A Configuration API is available that can be used by other central services to retrieve configurations
- [ ] The API is to return Enums based on the request
  - [ ] To be configurable to return all Enums or specific ones as requested
- [ ] Follow-up stories to update central-services based on this design are created

**Pull Requests**:
- [ ] TBD

**Follow-up**:
- N/A

**Dependencies**:
- N/A

**Accountability**:
- Owner: 
- QA/Review: @mdebarros 

**Notes**:
- Separate micro-service (?) that provides an API which can be used to fetch the information?
- The configuration API possibly can be used for CRUD operations on various configurations but the Enums should be immutable (through the API)
- **Possible extension**: Can be used for looking-up error-codes, descriptions, etc

**Comment by elnyry-sam-k** [comment]
Will be taken up as the Reference Architecture workstream (platform configuration) and doesn't make sense here anymore
