### ISSUE TITLE
ALS Implementation to support GET, POST on participants and GET on parties

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#696]
## **Goal**:
As an implementer of the Switch
I want to support basic, critical functionality on the account-lookup-service
so that some functionality is available to start with and it can be incrementally improved

**Tasks**:
### ALS API Tasks:
Referencing the designs from #692 and #655 
- [x] Implementation for GET /participants - 100%
- [x] Implementation for GET /parties - 100%
- [x] Implementation for POST /participants - 100%
- [x] Implementation of the health endpoint GET /health - 0%

- ~[ ] Unit tests for GET /participants - 20%~
- ~[ ] Unit tests for GET /parties - 20%~
- ~[ ] Unit tests for POST /participants - 20%~
- [x] Unit tests for health endpoint GET /health - 100%

**Acceptance Criteria**:
- [x] Support for the below endpoints for ALS is provided based on designs in #655 and #692
  - [x] GET /participants
  - [x] GET /parties
  - [x] POST /participants
  - [x] GET /health
- [x] Designs are up-to date
- [x] Unit Tests pass
- [ ] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

**Pull Requests**:
- [ ] TBD

**Follow-up**:
- N/A

**Dependencies**:
- N/A

**Accountability**:
- Owner: @rmothilal @mdebarros 
- QA/Review: @elnyry @mdebarros
