### ISSUE TITLE
Sending notification to the Payee regarding finalization of a transfer based on config

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#700]
## **Goal**:
As a Switch implementer
I want to have the feature to send a notification to the Payee regarding finalization of a transfer based on configuration
so that it can be used to change the behavior of Switch regarding sending notifications to the Payee after finalizing a transfer

**Tasks**:
- [x] Update designs to reflect changes to support both the modes
- [x] Implement changes necessary to support this (sending notification or not)
- [x] Update unit tests
- ~Update integration tests~  (_Note: It is not possible to add an integration test for this at this time as we either need to modify the integration-runner script to restart ml-api-container with a new config, or alternatively provide a mechanism for ml-api-container to support dynamic configuration on the fly._)
- [x] Update Helm charts for changes to `default.json`
- [x] Update Transfer Sequence Diagrams to reflect config options
- [x] Broadcast changes to default.json to the team
- [x] Ensure Switch can be configured to or not to send notification to Payee by running writing and running appropriate tests

**Acceptance Criteria**:
- [x] Designs are updated to reflect changes
- [x] Sequence diagrams (transfers) are updated to reflect changes
- [x] Unit tests are updated and pass
- ~Integration Tests are updated~
- [x] Integration Tests pass
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment configs.
- [x] Based on configuration the Switch can be configured to either send out a notification to the Payee on a completed transfer or not send out that notification (as per v1.0 of the Spec)

**Pull Requests**:
- [ ] https://github.com/mojaloop/ml-api-adapter/pull/183
- [ ] https://github.com/mojaloop/helm/pull/209
- [ ] https://github.com/mdebarros/helm/pull/3

**Follow-up**:
- N/A

**Dependencies**:
- N/A

**Accountability**:
- Owner: TBC
- QA/Review: @elnyry 

**Notes*:
- The idea is to support this mode so that it may be changed to behave this way based on the incoming message, based a flag or specific field (probably in a future version of the Spec)
