### ISSUE TITLE
Hackathon Lab preparation

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#702]
## **Goal**:
As a mentor/participant at the Hackathon event (April week of 8th, Dar-e-Salaam, TZ)
I want to ensure a stable lab setup
so that the attendees at the hackathon can use it

**Tasks**:
- [x] Assist in identifying issues with setup, fixing them 
- [x] Identify environmental issue causing requests to fail to all Mojaloop API services [@mdebarros]
- [x] Deploy 0.21.x version of Ingress Controller to fix the cause of the above issue [@mdebarros]
- [x] Apply fix to Ingress's for custom friendly DNS records [@mdebarros]
- [x] Review current setup by Mifos/Fineract - scheduled 2019/03/29 [@mdebarros]
- [ ] Settlement Issue:
   - [ ] Investigate issue
   - [ ] Resolve issue
- [x] Ensure functionality needed for the Hackathon
- [ ] Create release branches for:
   - [ ] Central-Ledger
   - [ ] ML-API-Adapter
   - [ ] Central-Settlements
- [ ] Prepare presentation for Hackathon

**Acceptance Criteria**:
- [ ] A lab that can be used by the attendees at the Hackathon event is available with Collaboration from Mifos/Fineract
- [ ] Presentation is in place for Mojaloop introduction, components, APIs and deployment capabilities

**Pull Requests**:
- N/A

**Follow-up**:
- N/A

**Dependencies**:
- N/A

**Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Hackathon lab is fully functional from the Transfer Golden Path use-cases. However, Settlements is having some issues which I will need to investigate. 

- GET /settlementWindows <- returns an error
- PUT /settlements/{id} <- always returns errors indicating that the state cannot be changed

**Comment by elnyry** [comment]
Closing this out as Hackathon is going to start tomorrow
