### ISSUE TITLE
Finalizing a transfer on receiving an incorrect Fulfilment value

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#703]
## **Goal**:
As a Switch implementer
I want to finalize a transfer (to ABORTED state) on receiving a valid PUT /transfers/{ID} call with an incorrect Fulfilment value
so that the Payee FSP will not have multiple chances to get it right (to now allow brute force, etc).

**Tasks**:
- [x] Resolve the following questions: [link](https://github.com/mojaloop/central-ledger/blob/master/src/handlers/transfers/handler.js#L295) [@ggrg]
- [x] **Bugfix**: Resolve issue when transfer is `aborted` with an out of range errorCode (e.g. 9500) [@ggrg] [b431c17](https://github.com/ggrg/central-ledger/commit/b431c17)
- [x] **Bugfix**: Stop assigning transferFulifilment.settlementWindowId to `rejected` transfers and set transferFulifilment.isValid based on the fulfilment validation[@ggrg]
- [x] Added new method - `savePayeeTransferResponse` to simplify and replace duplicated code at `saveTransferFulfilled` and `saveTransferAborted`, and also cater for the current use case [@ggrg] [008130f](https://github.com/ggrg/central-ledger/commit/008130f)
- [x] Update implementation to make the change to change a transfer State to ABORTED for a PUT /transfers/{ID}, that is valid for everything else except for having an incorrect fulfilment value [@ggrg]
  - [x] Implement savePayeeTransferResponse for TransferService.fulfil [@ggrg]
  - [x] Implement savePayeeTransferResponse for TransferService.reject [@ggrg]
  - [x] Implement savePayeeTransferResponse for TransferService.abort [@ggrg]
  - [x] Implement savePayeeTransferResponse for TransferService.abort on validation errors [@ggrg]
  - [x] Code cleanup for deprecated methods above [@ggrg] [2b4af27](https://github.com/ggrg/central-ledger/commit/2b4af27)
- [x] **Bugfix**: logTransferError when NDC exceeded during TransferPrepare [@ggrg]
- [x] Verify resend request and get on the aborted transferId (transfer extension `cause`) [@ggrg]
- [x] Fix issues with integration tests, if any [@ggrg]
- [ ] Fix and introduce new unit tests to ensure full tests coverage [@ggrg]
- [ ] Update documentation (sequence diagrams) to match current implementation

**Acceptance Criteria**:
- [x] Transfers are ABORTED on receiving an incorrect Fulfilment value
  - [x] Update: The story also covers for bad fulfilment received for `reject with fulfilment`
- [ ] Designs are up-to date to reflect finalizing a transfer on receiving an incorrect Fulfilment value on an otherwise valid fulfilment request from the Payee FSP
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

**Pull Requests**:
- [ ] https://github.com/mojaloop/central-ledger/pull/378

**Follow-up**:
- N/A

**Dependencies**:
- [x] Error Framework - Adopt and Integrate Mojaloop SDK Error Handling Component - Central-Ledger #838
- [x] Review design for duplicate check on 'prepare transfers' & refactor if necessary #780
- [x] Review design for duplicate check on 'fulfil transfer' requests & refactor if necessary #781
- [x] Refactoring for duplicate checking on 'prepare transfers' & 'fulfil transfer' - part2  #904

## **Accountability**:
- Owner: TBC
- QA/Review: DA

**Notes**:
- Reference: Section 6.7.1.8 Interledger Payment Request, point 4 in the API Definition
- The intention is not to allow multiple chances to the Payee FSP to send a correct fulfilment value and abort the transfer on receiving the first valid PUT /transfers/{ID} call with incorrect fulfilment itself. Currently an error callback is sent to the Payee but the transfer is otherwise unchanged.

**Comment by ggrg** [comment]
I can see a dependency on stories #780 and #781, because as part of this story we need to update the design and the implementation of the Fulfil Handler. It would be best if DA decisions for #780 and #781 are taken and then all is addressed at once.

**Comment by elnyry** [comment]
@kjw000 it is though temporarily.. The blocker #904 is now closed, we're validating it currently and once that is done, this will be unblocked..
