### ISSUE TITLE
ALS Design to support Multiple Switches

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#704]
## **Goal**:
As a DFSP
I would like to have an ALS design to support multiple switches
so that an ALS can be deployed as a central Account Lookup Service

As a Hub Operator
I would like to have an ALS design to support multiple switches
so that an ALS can be deployed as a central Account Lookup Service

**Tasks**:
- [ ] Setup meeting with @adrianhopebailie to discuss switch resolution based on cross border/network design
- [ ] Document findings from meeting with @adrianhopebailie on switch resolution based on cross border/network design

**Acceptance Criteria**:
- [ ] Documented approach for ALS to support multiple switches
- [ ] ALS design updated to support multiple switches

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
Not in scope right now; can be revived if this topic is taken up in future
