### ISSUE TITLE
ALS Implementation for Admin API

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#705]
## **Goal**:
As an implementer of the Switch
I want to support basic, critical functionality on the account-lookup-service
so that basic functionality is available to start with and it can be incrementally improved.
[_Cater for optional currency and type fields for GET /admin/oracles/endpoints_]

**Tasks**:
### Admin API Tasks:
- [x] Implementation for Admin API for
  - [x] POST Oracle - 20%
  - [x] PUT Oracle - 20%
  - [x] GET Oracle - 20%
  - [x] DELETE Oracle - 20%
  - [x] GET health - 0%
- [ ] ~Unit tests for Admin API POST Oracle~
  - [ ] ~POST Oracle~
  - [ ] ~PUT Oracle~
  - [ ] ~GET Oracle~
  - [ ] ~DELETE Oracle~
  - [ ] ~GET health~

**Acceptance Criteria**:
 - [x] GET /admin/oracles/endpoints?type={type}&currency={currency}
 - [ ] GET /admin/oracles/endpoints/{ID} - may be required
 - [x] PUT /admin/oracles/endpoints/{ID}
 - [x] POST /admin/oracles/endpoints
 - [x] DELETE /admin/oracles/endpoints/{ID}
 - [x] GET health
- [ ] Designs are up-to date
- [ ] ~Unit Tests pass~
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

**Pull Requests**:
- [ ] TBD

**Follow-up**:
- N/A

**Dependencies**:
- N/A

**Accountability**:
- Owner: @rmothilal @mdebarros 
- QA/Review: @mdebarros @elnyry
