### ISSUE TITLE
ML OSS Account Lookup Service (ALS) Design - 3

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#707]
## **Goal**:
As a DFSP
I would like to have a design which enables Participants to _request registration/enrollment of a Participant-Party association as per the Specification_
so that _a Party Identifier can be used create a mapping with a Participant_

As a Hub Operator
I would like to have a design which enables Participants to _request registration/enrollment of a Participant-Party association as per the Specification_
so that _a Party Identifier can be used create a mapping with a Participant_

**Tasks**:
- [ ] Refactor sequence diagrams for generic use and extensibility with the proposed design
    - [ ] POST /participant/{Type}/{ID} [Implementation is done, just refactor design]
- [ ] Updates from DA Review (to the ALS designs)
- [ ] Design to accommodate only a single switch for initial implementation
    - [ ] Updated DB Design & Assets
    - [ ] Updated Sequence Diagrams
    - [ ] Updated Arch Diagrams
- [ ] Aligned swagger to Mojaloop specification 

**Acceptance Criteria**:
- [ ] The ALS design caters for POST /participant/{Type}/{ID}

**Pull Requests**:
- N/A

**Follow-up**:
- N/A

**Dependencies**:
- [x] #655 , #692 

**Accountability**:
- Owner: TBC
- QA/Review: DA

**Notes**:
- The current design only caters for the Mojaloop Specification part of the API and doesn't include checks/validations needed to be done as part of a Scheme to ensure validity of the Participant-Party associations

**Comment by elnyry-sam-k** [comment]
should already be supported
