### ISSUE TITLE
Setup helm chart for ALS

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#708]
**Goal**:
As a Switch Implementer
I would like to _setup helm charts for the ALS component_
so that the ALS can be deployed (automatically) using helm.

**Tasks**:
- [x] Create Dockerfile for the ALS repo [ @rmothilal ]
- [x] Setup helm chart for ALS [ @mdebarros ]
- [x] Configure ALS helm values [ @mdebarros ]
- [x] Re-align helm charts for ALS configs [ @mdebarros ]
- [ ] ~Test Helm chart deployment~ [ @mdebarros ]

**Acceptance Criteria**:
- [ ] A helm chat for ALS component is created that facilitates the deployment of ALS service is made available

**Dependencies**:
- [ ] A release for ALS to test

**Accountability**:
- Owner @mdebarros 
- QA/Review Core team
