### ISSUE TITLE
Integration tests for ALS admin end-points

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#709]
**Goal**:
As a ML Switch implementer
I would like to _add integration tests for ALS admin end-points_
so that the ALS admin/operational features' testing can be automated

**Tasks**:
- [ ] Add integration tests for admin end-points
- [ ] Enable running integration tests forALS in circleCI (enable the path)
- [ ] Make sure integration tests pass/fail as expected in circleCI

**Acceptance Criteria**:
- [ ] Integration tests are provided for ALS admin end-points and work in circleCI

**PRs**
 - [ ] 

**Dependencies**:
- N/A

**Accountability**:
- Owner 
- QA/Review ML Core team
