### ISSUE TITLE
Need to automate the identification of licenses of node.js modules

### ISSUE THREAD

**Issue by kjw000** [mojaloop/project#712]
## **Goal**:
As a contributor I want to understand any license violations in an automated fashion

**Tasks**:
- [ ] Use NLF command line tool on critical repos to establish baseline
- [ ] Clean up unknown licenses of restrictive licenses
- [ ] Automate the tool to run during checkin and produce report of non-permissive licenses

**Acceptance Criteria**:
- [ ] Licenses of packages are verified as part of each PR/merge and reported
- [ ] For new violations, merging is shown as blocked.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
Covered in #801
