### ISSUE TITLE
Settlements COMMITTED state not working 

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#714]
**Summary**:
When I run the settlements process, PS_TRANSFERS_RECORDED, PS_TRANSFERS_RESERVED are working as expected and all my tests are passing on these two states. But when I do PS_TRANSFERS_COMMITTED, tests are failing and the participants state still showing "PS_TRANSFERS_RESERVED" state.
**Severity**:
High

**Priority**:
Critical
**Expected Behavior**
1. When I do PS_TRANSFERS_COMMITTED on a participant during the phases of the settlements process, I should be getting a 200 - response code and when I check the state of the participant account, it must be in PS_TRANSFERS_COMMITTED
2. The settlement ID state must also be "PS_TRANFERS_COMMITTED"

**Steps to Reproduce**
  1. Open a new settlement window (i.e close the existing open window)
  2. Run few transfers between testfsp1, testfsp2, testfsp3, testfsp4
  3. Close the current open window
  4. Create settlement on the closed window
  5. Run settlements - Prepared  (PS_TRASNFERS_RECORDED)
  6. Check the status of settlement ID and participant account are PS_TRANSFERS_RECORDED
  7. Run settlemetns - Reserved (PS_TRASNFERS_RESERVED)
  8. Check the status of settlement ID and participant account are PS_TRANSFERS_RESERVED
  9. Run Settlements - Committed (PS_TRANSFERS_COMMITTED)
  10. Check the status of settlement ID and participant account are 
          PS_TRANSFERS_COMMITTED
  8. the states are not updated to PS_TRANSFERS_COMMITTED in the above step.

Curl script Request:
curl -X PUT \
  http://test-central-settlement.mojaloop.live/v1/settlements/2 \
  -H 'Authorization: Bearer {{BEARER_TOKEN}}' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 626e849b-6ed6-405f-80a2-6ed9ac74db53' \
  -H 'cache-control: no-cache' \
  -d '{
  "participants": [
    {
      "id": 5,
      "accounts": [
        {
          "id": 7,
          "reason": "test",
          "state": "PS_TRANSFERS_COMMITTED"
        }
      ]
    }
  ]
}'

Response:
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": {
        "errorInformation": {
            "errorDescription": "insert into `transferFulfilment` (`completedDate`, `createdDate`, `ilpFulfilment`, `isValid`, `settlementWindowId`, `transferFulfilmentId`, `transferId`) values ('2019-04-02 12:25:09.564', '2019-04-02 12:25:09.564', 0, 1, NULL, '0a5acf2e-8f27-4438-8baa-0a6c52e90871', 'bce8216f-8a31-40ce-afe5-1bc9e5b10e5a') - ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`central_ledger`.`transferFulfilment`, CONSTRAINT `transferfulfilment_transferfulfilmentid_foreign` FOREIGN KEY (`transferFulfilmentId`) REFERENCES `transferFulfilmentDuplicateCheck` (`transfe)"
        }
    }
}

**Specifications**
  - Component (if known): Central settlements
  - Version: 5.3.0
  - Platform: MAC OS
  - Subsystem: Mojaloop
  - Type of testing: Functional
  - Bug found/raised by: Sri

**Tasks**:
- [x] Implement Fix and raise PR [@ggrg]
- [x] Review fix, incorporate feedback, merge [@ggrg, @rmothilal , @mdebarros ]
- [x] Release, Update helm and Deploy [@ggrg, @elnyry ]

**Notes**:

- Severity when opened: High
- Priority when opened: Critical

**Comment by ggrg** [comment]
**Pull requests**:
- [ ] https://github.com/mojaloop/central-settlement/pull/68
- [ ] https://github.com/mojaloop/central-ledger/pull/265

**Comment by sri-miriyala** [comment]
I see this issue is fixed with v5.5.1. Settlements is successful as part of golden path.

**Comment by elnyry** [comment]
This needs validation on v6.1.1 release (for central-settlement) as v6.1.0 seemed to have a repro (regression)

**Comment by elnyry** [comment]
Closing this now as the fixes are made and deployed on AWS (v.6.1.1)..

Please re-open if the issue is not fixed.
