### ISSUE TITLE
Presentation for Mojaloop PI6 event

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#715]
## **Goal**:
As a member of the presenting team at the Mojaloop PI6 event
I want to _prepare presentations and other material necessary for the PI6 event_
so that _it can be used for discussions, demonstrations at the event and later for documenting, circulating_

**Tasks**:
- [x] Decide on the template, share the Initial draft v0.1 with just topics
- [x] Discussion with team about topics involved, demonstrations to be done
- [x] Identify topics and owners for each section based on attendance, etc
- [ ] Documentation upgrades [Changes done in 5.5 listed below but changes to be documented are for whole PI]
  - [x] Format community questions into .md document. (@HenkKodde )
  - [ ] document the Windows environment setup process. (@HenkKodde )
  - [x] ~Update deployment guide to include helm install.~ (incorporated by gitbook update )
- [x] Draft with all topics and placeholders for every discussion are added
- [x] Individual owners to submit initial draft of slides
  - [x] Continue Intro, Summary [@elnyry]
  - [x] Documentation updates, Adoption update [@kjw000]
  - [x] Documentation updates [Adolfo Rios]
  - [x] ALS [@mdebarros]
  - [x] Code Enhancements [@mdebarros]
  - [x] Fraud & AML [@RobReeve]
  - [x] Settlements [Michael Richards]
  - [x] QA [@nicoduvenage]
  - [x] Release Mechanism [@elnyry]
  - [x] Error end-points [@elnyry, @rmothilal ]
  - [x] BugFixes, Community Support [@elnyry]
  - [x] DA proposal [@nicoduvenage]
  - [x] Bulk Transfers [@elnyry]
  - [x] RoadMap [@elnyry]
- [x] Review a complete slide deck with the team
- [x] Second iteration of presentation deck with updated slides from each owner
- [x] Complete review of the slide deck and make changes.
- [x] A v0.9 of the slide deck is ready

**Acceptance Criteria**:
- [x] A slide-deck that is to be used for the Mojaloop PI6 event is drafted and feedback incorporated
- [x] Individual owners for each topic/section are identified responsible for that topic regarding both slides and discussions at the event.
- [x] Updated Designs are used

**Pull Requests**:
- [ ] https://github.com/mojaloop/documentation/pull/44

**Follow-up**:
- N/A

**Dependencies**:
- N/A

**Accountability**:
- Owner: @elnyry 
- QA/Review: ML Core team
