### ISSUE TITLE
Architecture or other diagrams for placemats for PI6

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#716]
## **Goal**:
As a partner of the BMGF
I want to _select and update architecture or other relevant diagrams for the Mojaloop PI6 event_
so that _they can be printed on the Placements for the event_.

**Tasks**:
- [x] Select/narrow down diagrams to be used based on space available on the placemats
- [x] Update diagrams as needed
- [x] Review and finalize the diagrams
- [x] Review and finalize placemat prototype

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Placemat template for the Mojaloop PI6 event is drafted and ready to be printed

**Pull Requests**:
- [ ] TBD

**Follow-up**:
- N/A

**Dependencies**:
- N/A

**Accountability**:
- Owner: @elnyry @kjw000 @nicoduvenage
- QA/Review: TBC

**Comment by elnyry** [comment]
Placemats finalized and ready to go.. Thanks
