### ISSUE TITLE
Email Notification failure - NDC threshold breach, Position reset - ML DEV v5.5.1

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#720]
Description:
1. Email notification is not being sent to payerfsp even though its position breached it's threshold limit.
2. Position reset email notification has not been sent to payeefsp even though its position updated during Settlements - PS_TRANSFERS_RESERVED state. this is happenning with only few fsps.

Expected Behavior:
1. Email notification has to be sent to both HUB operator and payerfsp when payerfsp breaches its threshold limit %
2. Position reset email notification has to be sent to both HUB operator and payeefsp after the settlements - Reserved state. Payerfsp has to receive this email after settlements - committed state. 

Actual behavior:
1. No notifications emails received at the provided email address in contacts regarding threshold breach
2. Few notification emails received at the provided email address in contacts reg position resets but not for all FSPs.

**Tasks**
- [x] simulate the issue for settlements
- [x] change switchMap to flatMap and investigate behavior
- [x] research about Observables error handling
- [x] solve Complete-on-Error Observables behavior 

**Specifications**
  - Component (if known): central services
  - Version: v5.5.1
  - Platform: AWS DEV0
  - Subsystem: email-notifier, CEP
  - Type of testing: Functional
  - Bug found/raised by: @sri-miriyala 

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by sri-miriyala** [comment]
NDC threshold beach email is working fine now... only issue with position reset email notifications.

No specific behavior for this position reset email notifications. Few fsps receiving emails while few fsps are not receiving these emails. Worked with Valentine on this. He is following up on the email server service.
Changed the title of the bug so that reflects only the current issue

**Comment by vgenev** [comment]
The NDC Breach might have been performing like that, because of the same issue as the settlements or because of an issue we found yesterday that stops the NDC threshold flow if there is an error. Currently I am working on error handling with Observables, since its little bit different than normal error handling, unfortunately.

**Comment by elnyry** [comment]
Sri confirmed that this is now fixed.
