### ISSUE TITLE
ML-API-Adapter to support a custom CA for callbacks

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#723]
## **Goal**:
As a `Hub Operator` I want to `ML-API-Adapter to support a custom CA/Trusted-Cert` so that `Callback operations will function against end-points that are configured with a self-signed certificate`

**Tasks**:
- [ ] Update ML-API-Adapter to support a custom CA, or Trusted-Cert
- [ ] Update ML-API-Adapter the configuration of the CA/Trusted-Cert
- [ ] Updated Helm charts to support this configuration

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] ML-API-Adapter can be configured to use a custom CA/Trusted-Cert for Callbacks done by the Notifications Handler
- [ ] Helm chart supports the configuration of the ML-API-Adapter to support setting a custom CA/Trusted-Cert for Callbacks

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
