### ISSUE TITLE
More detailed expected result verification in Golden_Path.postman_collection.json

### ISSUE THREAD

**Issue by regicorbin** [mojaloop/project#726]
## **Goal**:
As a tester I want to verify the actual result values returned by each service call match the expected result so that the quality of the software is better validated

**Tasks**:
- [ ] Determine the correct environment for testing
- [ ] Obtain direct access to the database for verification
- [ ] Better understand business rules around each service call
- [ ] Establish the approach to perform the verification in Postman
- [ ] Add verification test steps to each of the tests in Golden_Path.postman_collection.json as needed

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] Actual results from each service call match the expected results

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
