### ISSUE TITLE
Dynamic test data in Golden_Path.postman_collection.json

### ISSUE THREAD

**Issue by regicorbin** [mojaloop/project#727]
## **Goal**:
As a tester I want to use dynamic test data, as needed so that test cases are more reusable, reliable and maintainable

**Tasks**:
- [ ] Establish dynamic test data approach
- [ ] Update test cases, as needed to use dynamic test data instead of hard coded values

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] Tests us dynamic test data

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
