### ISSUE TITLE
Update 'documentation' repo with settlements artifacts from 'docs' repo

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#729]
## **Goal**:
As a ML OSS codebase maintainer
I want to _move sequence diagrams for Settlements from 'docs' repo to documentation repo and add information briefly as relevant_
so that the process of moving over up-to-date documents from 'docs' to documentation can be progressed further.

**Tasks**:
- [x] Move Sequence diagrams from docs repo to documentation repo [@ggrg]
- [x] Update links in the diagrams as relevant [@ggrg]
- [ ] Add additional information [@ggrg]
  - [x] Add API Specification section [@ggrg]
  - [x] Link Central Settlements swagger.json file [@ggrg]
  - [x] Create and link central-setttlement DB schema diagram [@ggrg]
  - [x] Add description to DB schema diagram [@ggrg]
  - [x] Settlement Windows By Params [@ggrg]
    - [x] Describe purpose [@ggrg]
  - [x] Settlement Windows By Params [@ggrg]
    - [x] Describe purpose [@ggrg]
  - [x] Close Settlement Window [@ggrg]
    - [x] Describe purpose [@ggrg]
  - [x] Create Settlement [@ggrg]
    - [x] Describe purpose [@ggrg]
  - [x] Request Settlement [@ggrg]
    - [x] Describe purpose [@ggrg]
  - [x] Settlement Transfer Acknowledgment [@ggrg]
    - [x] Describe purpose & state transition [@ggrg]
  - [x] Settlement Abort [@ggrg]
    - [x] Describe purpose & limitations [@ggrg]
  - [x] Request Settlement By SPA [@ggrg]
    - [x] Describe purpose [@ggrg]
  - [x] Request Settlements By Params [@ggrg]
    - [x] Describe purpose [@ggrg]
- [x] Add a section for Record Funds In/Out [@ggrg]
- [x] Update mojaloop/central-settlement repository accordingly [@ggrg]
- [x] Update mojaloop/docs repository accordingly [@ggrg]

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Links are up-to-date
- [x] Sequence diagrams related to settlements and additional information is moved to documentation repo from docs repo

## **Pull Requests**:
- [x] https://github.com/mojaloop/documentation/pull/32
- [x] https://github.com/mojaloop/docs/pull/145
- [x] https://github.com/mojaloop/central-settlement/pull/69

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
