### ISSUE TITLE
Update 'documentation' repo with central-ledger artifacts from 'docs' repo

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#731]
## **Goal**:
As a ML OSS codebase maintainer
I want to _move sequence diagrams for central-ledger from 'docs' repo to documentation repo and add information briefly as relevant_
so that the process of moving over up-to-date documents from 'docs' to documentation can be progressed further.

**Tasks**:
- [x] Move Sequence diagrams from docs repo to documentation repo
- [x] Update links in the diagrams as relevant
- [x] Add additional information
  - [x] Add API Specification section
  - [x] Link Central ~Settlements~ Ledger swagger.json file
  - [x] Create and link central-~settlement~ledger DB schema diagram
  - [x] Add description to DB schema diagram.
  - [x] Add description to sequence diagrams
    - [x] List of diagrams
- [x] Incorporate feedback from PR review comments

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Links are up-to-date
- [x] Sequence diagrams related to central-ledger and additional information is moved to documentation repo from docs repo

**Pull Requests**:
- [x] https://github.com/mojaloop/documentation/pull/45 (approved and merged into master)
- [x] https://github.com/mojaloop/documentation/pull/46

**Follow-up**:
- N/A

**Dependencies**:
- N/A

**Accountability**:
- Owner: TBC
- QA/Review: TBC
