### ISSUE TITLE
Rework MockPathfinder to align with Oracle Template

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#734]
## **Goal**:
As a developer i want to be able to show end to end functionality of the ALS for demonstration and testing purposes by refactoring the MockPathfinder to align with the ALS Oracle Template swagger

**Tasks**:
- [ ] Update MockPathfinder Rest endpoints 
  - [ ] GET /participants/{Type}/{ID}
  - [ ] PUT /participants/{Type}/{ID}
  - [ ] POST /participants/{Type}/{ID}
  - [ ] DELETE /participants/{Type}/{ID}
  - [ ] POST /participants
- [ ] Design Mock database for storage to Mock Participant/Parties information
- [ ] Create Helm scripts for deployment
- [ ] Register in ALS database
- [ ] Test end to end functionality
- [ ] Create postman scripts

**Acceptance Criteria**:
- [ ] All REST endpoints are accessible
- [ ] End to end testing passes 
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rmothilal @mdebarros 
- QA/Review: @elnyry
