### ISSUE TITLE
Move current sendRequests on ALS to a Model approach

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#735]
## **Goal**:
As a developer i want to refactor the ALS code for sending requests to a Model approach so that standards are followed across the Central APIs

**Tasks**:
- [x] Refactor "sendRequest" to appropriate path
- [x] Fix Unit tests

**Acceptance Criteria**:
- [x] Functionality still works as previously did
- [x] Unit Tests pass
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rmothilal 
- QA/Review: @mdebarros @elnyry

**Comment by rmothilal** [comment]
Moved to the backlog as I have not achieved the desired framework and this will have to be redone when we are doing the SubId story for ALS https://github.com/mojaloop/project/issues/736

**Comment by elnyry** [comment]
ok Rajiv, thanks
