### ISSUE TITLE
Add SubId functionality to the ALS - Part1

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#736]
## **Goal**:
As a DFSP
I would like to query the account lookup service for a party's details using a SubId
so that I can find the party's host FSP and other details that are supported by the ML API

**Tasks**:
- [x] Refactor `oracleRequest` to support `currency`, `Type`, and `SubId` 

## Update following Simulator endpoints to support `currency` and `SubId` ##
  - [x] GET /oracle/participants/{Type}/{ID}
  - [x] PUT /oracle/participants/{Type}/{ID} 
  - [x] DELETE /oracle/participants/{Type}/{ID}
  - [x] Add endpoint: PUT /oracle/participants/{Type}/{ID}/{SubId}
  - [x] Add endpoint: GET /oracle/parties/{Type}/{ID}/{SubId}
  - [x] Add endpoint: PUT /oracle/parties/{Type}/{ID}/{SubId} 

## Updates for Central Ledger, SDK-Standard-Component, and Postman Scripts ##
- [x] Update seeds for `endpointTypes` in `central-ledger`
- [x] Update `New Deployment FSP Setup` postman scripts to cover new endpoint types
- [x] Update sdk-standard-component error codes

## Implement Participants Endpoints in ALS: ##
  - [x] GET /participants/{Type}/{ID}/{SubId} 
  - [x] PUT /participants/{Type}/{ID}/{SubId}
  - [x] PUT /participants/{Type}/{ID}/{SubId}/error
  - [x] POST /participants/{Type}/{ID}/{SubId}
  - [x] DELETE /participants/{Type}/{ID}/{SubId}

## Implement Parties Endpoints in ALS:
  - [x] GET /parties/{Type}/{ID}/{SubId}
  - [x] PUT /parties/{Type}/{ID}/{SubId}

### Participants domain ###
   - [x] getParticipantByTypeAndID
   - [x] putParticipantsByTypeAndID
   - [x] putParticipantsErrorByTypeAndID
   - [x] postParticipants
   - [x] deleteParticipants
 ### Participants handler ###
   - [x] GET /participants/{Type}/{ID}/{SubId} 
   - [x] PUT /participants/{Type}/{ID}/{SubId}
   - [x] PUT /participants/{Type}/{ID}/{SubId}/error
   - [x] POST /participants/{Type}/{ID}/{SubId}
   - [x] DELETE /participants/{Type}/{ID}/{SubId}
  ### Parties domain ###
   - [ ] ~getPartiesByTypeAndID~
   - [ ] ~putPartiesByTypeAndID~
   - [ ] ~putPartiesErrorByTypeAndID~
  ### Parties handler ###
   - [ ] ~GET /parties/{Type}/{ID}/{SubId}~
   - [ ] ~PUT /parties/{Type}/{ID}/{SubId}~

**Acceptance Criteria**:
- [x] Requests hit the relevant Oracle endpoints
- [x] Designs are up-to date
- [ ] ~Unit Tests pass~
- [x] Code Style & Coverage meets standards

## **Pull Requests**: ##
- [ ] https://github.com/mojaloop/central-services-shared/pull/129
- [ ] https://github.com/mojaloop/simulator/pull/102
- [ ] https://github.com/mojaloop/account-lookup-service/pull/145
- [ ] https://github.com/mojaloop/sdk-standard-components/pull/28

## **Follow-up**:
- #1078 

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rmothilal 
- QA/Review: @mdebarros @rmothilal @elnyry
