### ISSUE TITLE
Review FSPIOP-Signature (JWS) header handling in the Switch implementation

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#737]
## **Goal**:
1. As a Mojaloop Switch Implementer
I would like to relay FSPIOP-Signature headers for HTTP calls unchanged for pass-through requests
so that Signature validation isn't affected by the Switch

2. As a Mojaloop Switch Implementer
I would like to ensure that the header FSPIOP-Signature is not present for requests that originate from the Switch
so that a Signature from the Switch can be added at a Gateway level or another external service specifically incorporated for that.

**Tasks**:
- [x] Identify various scenarios involved with the FSPIOP-Signature header [@ggrg]
  - [x] prepare - OK [@ggrg]
  - [x] duplicate prepare (for RESERVED transfer) - OK (no callback) [@ggrg]
  - [x] duplicate prepare (for COMMITTED) - FIXED [@ggrg]
  - [x] get - from switch - should not be sent - FIXED [@ggrg]
  - [x] committed - FIXED [@ggrg]
  - [x] duplicate committed - FIXED [@ggrg]
  - [x] modified request - FIXED [@ggrg]
  - [x] reject - FIXED [@ggrg]
  - [x] duplicate reject - FIXED [@ggrg]
  - [x] abort - FIXED [@ggrg]
  - [x] abort duplicate - FIXED [@ggrg]
- [x] Review ml-api-adapter implementation to ensure accurate handling of FSPIOP-Signature for 
requests originating at the Switch [@ggrg]
- [x] Review ml-api-adapter implementation to ensure accurate handling of FSPIOP-Signature for pass-through requests [@ggrg]
- [x] Ensure postman requests provide coverage for the various scenarios identified in #1 [@sri-miriyala]
- [ ] ~Validate postman requests and Switch behaviour [@sri-miriyala]~
----
- [x] Monitoring options for FSPIOP-Header failures/error scenarios on the Switch are explored and provided [@ggrg]

**Acceptance Criteria**:
- [x] Central-ledger and ml-api-adapter repos are reviewed for handling of FSPIOP-Signature header
- [x] Various scenarios involving FSPIOP-Signature are identified for validation/verification/testing.
- [ ] Postman scripts are reviewed to provide coverage for tests involving various scenarios for FSPIOP-Signature

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-api-adapter/pull/101
- [x] https://github.com/mojaloop/ml-api-adapter/pull/105

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @ggrg  
- QA/Review: @elnyry

**Comment by sri-miriyala** [comment]
@ggrg @elnyry  In addition to FSPIOP-Signature, also please make sure that FSPIOP-HTTP-Method and FSPIOP-URI are also stripped off for the messages that originate from the Switch.

**Comment by elnyry** [comment]
@sri-miriyala, for FSPIOP-HTTP-Method , the current  behavior is that for messages originating from the Switch, it is set to the current Method value. This seems correct to me. Is there a reason why it should be stripped off?

For FSPIOP-URI, it is stripped off if a message originates at the Switch..

**Comment by elnyry** [comment]
Closing this now as the fixes are made and deployed on AWS (v.6.1.1)..

Please re-open if the issue is not fixed.
