### ISSUE TITLE
Bulk Transfers: Refactoring Sequence diagrams for existing handlers

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#738]
## **Goal**:
As a Hub Operator
I want to _have a design for the bulk transfers Use Case (the /bulkTransfers end-point)_
so that _I can use it to support the bulk Transfers use-case with an implementation that uses this as reference (based on the API Definition)._ 

This specific story is for refactoring sequence diagrams of existing handlers - Prepare, position and Fulfil

**Tasks**:
- [x] Update sequence diagrams for the design
  - [x] prepare handler
  - [x] position handler
  - [x] fulfil handler
- [x] Provide PR for changes
- [x] Feedback from reviews incorporated and designs (Sequence diagrams or markdown files)

**Acceptance Criteria**:
- [ ] Existing sequence diagrams for the below are updated
  - [x] prepare handler
  - [x] position handler
  - [x] fulfil handler

**Pull Requests**:
- [ ] https://github.com/mojaloop/documentation/pull/53

**Follow-up**:
- TBD

**Dependencies**:
- [x] #693 

**Accountability**:
- Owner: @elnyry @ggrg 
- QA/Review: DA

**Comment by elnyry** [comment]
Initial PR is submitted, along with DA reviews, peer-reviews to be covered in #757
