### ISSUE TITLE
Bulk Transfers: Refactoring Sequence diagrams for timeout handler

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#739]
## **Goal**:
As a Hub Operator
I want to _have a design for the bulk transfers Use Case (the /bulkTransfers end-point)_
so that _I can use it to support the bulk Transfers use-case with an implementation that uses this as reference (based on the API Definition)._ 

This specific story is for refactoring sequence diagrams of timeout handlers

**Tasks**:
- [x] Update sequence diagrams for the design of time-out handler [@ggrg]
- [x] Provide PR for changes. **TODO**: Raise a PR against mojaloop/docs [@ggrg] 
- [x] Feedback from reviews incorporated and designs (Sequence diagrams or markdown files)

**Acceptance Criteria**:
- [ ] Existing sequence diagrams for the time-out handler is updated and ready for review by the DA [@ggrg]

**Pull Requests**:
- [ ] https://github.com/mojaloop/documentation/pull/56

**Follow-up**:
- TBD

**Dependencies**:
- [x] #693 

**Accountability**:
- Owner: @elnyry @ggrg 
- QA/Review: DA
