### ISSUE TITLE
Upgrade the version of Node for central-ledger

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#74]
**Goal**:
As a developer I would like to upgrade the version of Node of central-ledger so that we can make use of new features and upgrade the dependencies for performance and stability

**Tasks**:
- [x] update dependencies
- [x] check unit tests work
- [x] add missing dependencies
- [x] ensure that api works when used as a dependency
- [x] update circleci config for new node version
- [x] fix code broken by version upgrade
- [x] update Onboarding.md document to show new version of node

**Acceptance Criteria**:
- [x] Upgraded node from 6.5.0 to 8.9.4 LTS
- [x] Ensure NPM dependencies are upgraded and compiles
- [x] Ensure all included tests pass
- [x] Updated on-boarding documentation for NPM/Node version

**Dependencies**:
- None currently

**Comment by rmothilal** [comment]
This story was estimated incorrectly, as such I would not be able to complete it in this sprint. 
There were 3 stories that were blocking it and another 2 dependencies that it relied on.
I completed the dependencies by bringing in the stories from the groomed backlog. 
This story will be carried over into milestone 1.2 where we will aim to complete outstanding tasks.
The estimate on the story currently says 8 but I believe that this is much larger than 8
