### ISSUE TITLE
Bulk Transfers: Sequence diagrams for bulk fulfil, processing handlers

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#740]
## **Goal**:
As a Hub Operator
I want to _have a design for the bulk transfers Use Case (the /bulkTransfers end-point)_
so that _I can use it to support the bulk Transfers use-case with an implementation that uses this as reference (based on the API Definition)._ 

This specific story is for designing sequence diagrams for the newly proposed handlers: bulk-prepare, bulk-processing and bulk-fulfil

**Tasks**:
- [x] Create sequence diagrams for the design of
  - [ ] ~bulk-prepare handler~ [completed]
  - [x] bulk-processing handler [@ggrg] (drafted)
  - [x] bulk-fulfil handler [@ggrg] (drafted)
- [x] Implement changes to DB Schema design as applicable [@ggrg]
- [x] Provide PR for changes
- [x] Feedback from reviews incorporated and designs (Sequence diagrams or markdown files) [@ggrg]

**Acceptance Criteria**:
- [x] Sequence diagrams created for the below:
  - [ ] ~bulk-prepare handler~
  - [x] bulk-processing handler
  - [x] bulk-fulfil handler

**Pull Requests**:
- [ ] https://github.com/mojaloop/documentation/pull/56

**Follow-up**:
- TBD: alter existing handlers' sequence diagrams to cater for bulk

**Dependencies**:
- [x] #693 

**Accountability**:
- Owner: @elnyry @ggrg 
- QA/Review: DA

**Comment by elnyry** [comment]
Initial PR is submitted, along with DA reviews, peer-reviews to be covered in #757
