### ISSUE TITLE
Update Mojaloop deployment guide to include reference for setting up a local windows environment.

### ISSUE THREAD

**Issue by HenkKodde** [mojaloop/project#743]
## **Goal**:
As a community member, I would like specific windows local operation system setup. This would assist and allow flexibility to choose a prefered local environment.. 

**Tasks**:
- [x] Update environment setup instructions from the current on-boarding document [ @HenkKodde  ]
  - [x] Windows environment setup guidelines [ @HenkKodde  ]
- [x] Update current on-boarding document to reference the appropriate environment setup guide [@HenkKodde  ]

**Acceptance Criteria**:
- [x] Environment, resources and OS versions are clearly declared.
- [x] Documentation is inlign with the current local environment setup guides.
- [x] Appropriate references to 3rd party utilities for implementers to familiarise them self. Links to "training sites" should also be provided if appropriate.

## **Pull Requests**:
- [x] https://github.com/mojaloop/documentation/pull/45

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @HenkKodde 
- QA/Review: TBC
