### ISSUE TITLE
Bulk Transfers: Review initial DB design, Draft values for actions, types in messages for bulk

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#744]
## **Goal**:
As a Hub Operator
I want to _have a design for the bulk transfers Use Case (the /bulkTransfers end-point)_
so that _I can use it to support the bulk Transfers use-case with an implementation that uses this as reference (based on the API Definition)._ 

This specific story is for the DB design and coming up with (or finalizing) values for types, actions used in the messages for bulk

**Tasks**:
- [x] Review the initial DB design and make changes as necessary
- [x] Proposal for types, actions to be used in the bulk transfers related messages
  - [x] Initial proposal
  - [x] Review with team
  - [x] Update SDs to incorporate changes, gaps identified [@ggrg, @elnyry ]
  - [x] Finalize and submit

**Acceptance Criteria**:
- [x] DB Design for Bulk transfers is reviewed (to be used as starting point for implementation)
- [x] Types and actions for bulk messages are proposed

**Pull Requests**:
- TBD

**Follow-up**:
- TBD

**Dependencies**:
- [x] #693 

**Accountability**:
- Owner: @elnyry @ggrg 
- QA/Review: DA
