### ISSUE TITLE
Bulk Transfers: Implement bulk-prepare handler

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#745]
## **Goal**:
As a Hub Operator
I want to _implement the /bulkTransfers end-point_
so that _I can support the bulk Transfers use-case (based on the API Definition)._ 

This specific story is for implementing the newly proposed bulk-prepare handler

**Tasks**:
- [x] Implement bulk-prepare handler [@ggrg]
  - [x] add feature branches to central-ledger and ml-api-adapter (to be later used for snapshot releases) [@ggrg]
  - [x] sync up with latest design [here](https://github.com/elnyry/documentation/tree/feature/738-bulk-transfers-poc-design-phase2), SVGs made temporary available [here](https://github.com/ggrg/documentation/tree/feature/738bulkTransfersPocDesignPhase2/mojaloop-technical-overview/central-bulk-transfers/assets/diagrams/sequence) [@ggrg]
  - [x] init db schema structures, remove outdated branches/PRs [@ggrg]
  - [x] init BulkPrepareHandler using hardcoded Bulk Transfer (to be replaced by #800 later) [@ggrg]
  - [x] Create bulkTransfer Postman POST request, configure environment variables and pre-request script [@ggrg]
  - [x] Update Enums [@ggrg]
  - [x] Duplicate analysis [@ggrg]
    - [ ] ~Handle Resend (GET callback / ignore)~
    - [ ] ~Handle Modified Request (callback notification to payerFsp)~
    - [x] Allow new UUIDs
  - [x] Bulk transfer validations [@ggrg]
    - [x] validateFspiopSourceMatchesPayer
    - [x] validateExpiration
    - [x] validateDifferentFsp
    - [x] validatePayerFsp
    - [x] validatePayeeFsp
  - [ ] ~Handle validation errors~
    - [ ] ~Store invalid bulk transfer request to database~
    - [ ] ~Produce callback notification to payerFsp~
  - [x] Store RECEIVED bulk to database [@ggrg]
  - [ ] ~Transform and produce individual transfers to topic-transfer~ (provided by #800)
- [ ] ~Configure topic-bulk-transfer consumer~ (provided by #800)
- [x] Adapt BulkPrepareHandler code to work with kafka messages and Object Store stream [@ggrg]
- [x] Utilize the bulkTransfer message hash, generated and passed by ml-api-adapter [@ggrg]
- [x] Verify golden path for BulkPrepareHandler and all db writes [@ggrg]
- [x] Sequence diagrams and markdown files updated if issues identified during implementation [@ggrg]
  - [x] bulkTransferAssociation needs to be removed from seq-bulk-1.1.1-bulk-prepare-handler.plantuml, at steps 42 & 45, as it is accessed at step 51 and is to be implemented this way [@ggrg]
  - [ ] ~seq-bulk-1.1.1-bulk-prepare-handler.plantuml also needs to be updated in connection to DA decision for duplicate checking and also regarding accessing the provided hash, generated by ml-api-adapter~ (follow-up #780)
- [x] Unit tests corrections [@ggrg]
- [ ] ~JSDoc notes~

**Acceptance Criteria**:
- [x] bulk-prepare handler is implemented and tested with postman for happy path

**Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/286
- [ ] https://github.com/mojaloop/ml-api-adapter/pull/113
- [x] https://github.com/mojaloop/documentation/pull/77

**Follow-up**:
- #780

**Dependencies**:
- [x] #744
- [x] #800
- [x] Resolution regarding whether bulk related code needs a new repo or if existing central-ledger repo is to be used
- [x] Resolution regarding release strategy (use snapshots, separate branch till implementation on all handlers related to bulk is complete)

**Accountability**:
- Owner: 
- QA/Review: DA
