### ISSUE TITLE
Bulk Transfers: Refactoring prepare, position, fulfil handlers to support bulk transfers messages

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#748]
## **Goal**:
As a Hub Operator
I want to _implement the /bulkTransfers end-point_
so that _I can support the bulk Transfers use-case (based on the API Definition)._ 

This specific story is for refactoring existing handlers - prepare, position and fulfil to support bulk transfers related messages and handle them as relevant (following Sequence diagrams, designs)

**Tasks**:
- [x] Update implementation for
  - [x] prepare handler (golden path) [@ggrg]
  - [x] position handler (golden path) [@ggrg]
  - [x] fulfil handler
- [ ] ~Automated Tests~
- [x] Sequence diagrams or markdown files updated if issues identified during implementation [@ggrg]

**Acceptance Criteria**:
- [x] prepare handler is refactored to support bulk transfers (golden path)
- [x] position handler is refactored to support bulk transfers (golden path)
- [x] fulfil handler is refactored to support bulk transfers (golden path)

**Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/289
- [x] https://github.com/mojaloop/ml-api-adapter/pull/116
- [x] https://github.com/mojaloop/central-ledger/pull/290

**Follow-up**:
- TBD

**Dependencies**:
- [x] #744
- [x] #745 
- [x] #746 

**Accountability**:
- Owner: 
- QA/Review: DA
