### ISSUE TITLE
Bulk Transfers: Refactoring time-out handler to support bulk transfers

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#749]
## **Goal**:
As a Hub Operator
I want to _implement the /bulkTransfers end-point_
so that _I can support the bulk Transfers use-case (based on the API Definition)._ 

This specific story is for refactoring the existing timeout handler to support bulk transfers related messages and handle them as relevant (following Sequence diagrams, designs)

**Tasks**:
- [x] Fixing issues with current codebase (bulk transfers not working) [@ggrg]
- [x] Implement changes to timeout handler to support bulk transfers [@ggrg]
  - [x] Update TimeoutHandler to support bulk transfers [@ggrg]
  - [x] Update PositionHandler to support individual transfers timeout [@ggrg]
  - [x] Update central-services-shared enums [@ggrg]
  - [x] Add central-services-logger to central-ledger [@ggrg]
  - [x] Resolve merge conflicts [@ggrg, @rmothilal]
  - [x] Capturing interdependency issue with central-services-shared and central-services-stream [@ggrg, @rmothilal]
  - [x] Update BulkProcessingHandler to support timeouts [@ggrg]
  - [x] Update bulk-api-adapter to support bulk-abort notifications [@ggrg]
  - [x] Add new bulkTransferStates: EXPIRING (PROCESSING), EXPIRED (COMPLETED) [@ggrg]
- [x] Sequence diagrams or markdown files updated if issues identified during implementation [@ggrg]
  - [x] seq-bulk-1.2.1-prepare-handler.plantuml [@ggrg]
  - [x] seq-bulk-1.3.1-position-prepare.plantuml [@ggrg]
  - [x] seq-bulk-1.4.1-bulk-processing-handler.plantuml [@ggrg]
  - [x] seq-bulk-3.1.1-timeout-handler.plantuml [@ggrg]
- [ ] ~Automated Tests~
- [x] Resolve issue with multiple bulkTransferStateChanges being recorded for each individual transfer (PENDING_FULFIL) [@ggrg]
- [x] Resolve issue with missing bulkTransferStateChange during prepare (PENDING_PREPARE once) [@ggrg]
- [x] Resolve issue with GMT timestamp (expirationDate), **retrieved from DB/knex as local timestamp** and wrongly compared to completedTimestamp during fulfil [@ggrg] [b26266](https://github.com/ggrg/central-ledger/commit/b26266f5bf67f920d934f62dd348d87742a2947c#diff-dca77af49353b2e16faa88d9bd2489c3R359)
- [x] Resolve issue not to send notification for partial fulfil of a bulk [@ggrg]
- [x] Alter EXPIRED to COMPLETED and send call PUT callback to the normal endpoint (not at **/error) [@ggrg]
- [x] Send COMPLETED bulk callback to payer and payee as per swagger definition (fulfilment or errorInformation at individualTransfer level) [@ggrg]
- [x] Refactor bulk-api-adapter to use central-services-shared [@ggrg]
- [x] Incorporate latest changes in central-services-shared and central-services-stream [@ggrg, @mdebarros, @rmothilal]
- [x] Review and update supporting documentation [@ggrg, @elnyry]

**Acceptance Criteria**:
- [x] Timeouts are supported for bulk transfers

**Pull Requests**:
- [x] https://github.com/mojaloop/documentation/pull/113
- [x] https://github.com/mojaloop/central-services-shared/pull/108
- [x] https://github.com/mojaloop/bulk-api-adapter/pull/6
- [x] https://github.com/mojaloop/central-ledger/pull/408
- [x] https://github.com/mojaloop/documentation/pull/115

**Follow-up**:
- TBD

**Dependencies**:
- [x] #744
- [x] #745 
- [x] #746
- [x] #747
- [x] Error Framework - Adopt and Integrate Mojaloop SDK Error Handling Component - Central-Ledger #838

**Accountability**:
- Owner: 
- QA/Review: DA

**Comment by mdebarros** [comment]
@elnyry, is this story still valid?

**Comment by elnyry** [comment]
@mdebarros unfortunately this is still valid. but shouldn't be a dependency for #750 to start with, so let me update that..
