### ISSUE TITLE
Implement a POC for MySQL against the DB requirements

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#75]
**Goal**:
Implement a POC for MySQL against the DB requirements

**Tasks**:
- [x] Investigate current implementation of database connectivity
- [x] Explore Connection String changes for mySQL
- [x] Investigate configuration changes required for PostgreSQL to MySQL changes
- [x] Change current implementation of database connectivity to MySQL
- [x] Implement Connection String changes for mySQL
- [x] Implement configuration changes required for PostgreSQL to MySQL changes
- [x] Implement changes required in "migration"
- [x] Test creation of tables on Kubernetes after central-ledger start-up
- [x] Determine any other changes required for successful migration
- [x] Test interaction to AWS Kubernetes cluster on MySQL Cluster with MySQL Client
- [x] Test interaction to AWS Kubernetes cluster on MySQL Cluster with Postman

**Acceptance Criteria**:
- [x] Implement POCs on MySQL against the requirements
- [x] Document POC methodology and findings

**Dependencies**:
- [x] #117

**Comment by kjw000** [comment]
Where is this documented? I would like to review.  thanks

**Comment by kjw000** [comment]
@NicoDuvenage - can you please point me to the POC documentation for this?
