### ISSUE TITLE
Support QA, testing on Mojaloop pre-releases / releases on Dev envt for PI7 (ended with v7.4.0 Helm release)

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#750]
## **Goal**:
As a ML OSS Code base maintainer
I want to _validate and make a release in PI7 that is successfully validated by the available Golden path tests_
so that _down stream entities can take and use a version of Mojaloop Switch services bundle thats tested and contains latest features and enhancements (added in PI7)_ 

This specific story is for making necessary changes for supporting QA on bulk transfers and performing end-to-end testing for bulk transfers

**Tasks**:
- [x] Update simulator to support Bulk transfers [@rmothilal]
- [x] Update simulator to support transactionRequests [@rmothilal]
- [x] Update Helm charts (for versions)
- [x] QA on Dev2 envt. with latest releases from Error, Event Framework changes
- [x] QA after fixing issue with Golden Path transfers
- [x] QA after fixing issue with Extension List elements length
- [x] QA to update scripts for Error Framework changes
- [x] Fix issues in quotes #933 
- [x] QA to fix issues in quotes tests
- [x] Release of v7.4.0 Helm - https://github.com/mojaloop/helm/releases/tag/v7.4.0

**Acceptance Criteria**:
- [x] QA on deployments done on AWS dev envts is done
- [x] Bugs are logged [Identified fixed several bugs, not limited to #933 , #810 , #868, #869, etc]
- [x] Bugs logged are fixed to make a v.7.x.x release [Follow-up: V7.4.0 made with Golden path tests all passing]
- [x] All the changes needed for supporting bulk transfers deployment are done

**Pull Requests**:
- [x] https://github.com/mojaloop/simulator/pull/34

**Follow-up**:
- TBD

**Dependencies**:
- [x] #745 
- [x] #746
- [x] #747  
- [x] #748 

**Blockers**:
- [x] https://github.com/mojaloop/project/issues/868
- [x] https://github.com/mojaloop/project/issues/869

**Accountability**:
- Owner: 
- QA/Review: DA

**Comment by mdebarros** [comment]
Release blocked due to the following issues:
- https://github.com/mojaloop/project/issues/868
- https://github.com/mojaloop/project/issues/869
