### ISSUE TITLE
Upgrade Streaming lib to utilise latest published rdkafka version

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#751]
## **Goal**:
As a `hub operator` I want to `upgrade streaming lib to use the latest rdkafka version` so that `bugs & performance improvements can be utilised in the streaming framework`

**Tasks**:
- [ ] Upgrade streaming lib to use rdkafka v1.x release https://github.com/edenhill/librdkafka/releases/
- [ ] Ensure that tests all pass for streaming lib
- [ ] Upgrade ML-API-Adapter to use upgraded streaming lib
- [ ] Ensure that tests all pass for ML-API-Adapter
- [ ] Upgrade Central-Ledger to use upgraded streaming lib
- [ ] Ensure that tests all pass for Central-Ledger
- [ ] Upgrade Email-Notifier to use upgraded streaming lib
- [ ] Ensure that tests all pass for Email-Notifier
- [ ] Upgrade CEP to use upgraded streaming lib
- [ ] Ensure that tests all pass for CEP

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] Streaming lib upgrade to use latest published rkafka v1.x
- [ ] ML-API-Adapter upgraded with latest version of streaming lib with tests passing
- [ ] Central-Ledger upgraded with latest version of streaming lib with tests passing
- [ ] Email-Notifier upgraded with latest version of streaming lib with tests passing
- [ ] CEP upgraded with latest version of streaming lib with tests passing

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
-  Current outstanding issue - “https://github.com/Blizzard/node-rdkafka/issues/607“. node-rdkafka latest version is 2.6.1. This is still running on an old version of librdkafka V0.11.5. Should be v0.11.6 as mentioned in the above Outstanding issue.

Extract from installation verifying the above issue:
  **MKL_APP_NAME             librdkafka**
  MKL_APP_DESC_ONELINE     The Apache Kafka C/C++ library
  RDKAFKA_VERSION_STR      0.11.5
  **MKL_APP_VERSION          0.11.5**

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
This was done some time ago
