### ISSUE TITLE
Quality metrics: Assess current status of SonarQube for OSS core repos

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#752]
## **Goal**:
As a maintainer of the Mojaloop OSS repos
I want to revisit and assess the current status of SonarQube for OSS repos
so that follow-up items can be created to have complete analysis of all core OSS repos

**Tasks**:
- [x] Assess current status and identify missing items
- [x] Remove un-used or outdated repos
- [x] Add new repos: account-lookup-service, email-notifier, central-event-processor, central-services-metrics, central-services-stream, quoting-service, central-settlement
- [x] Update scripts to use new configurations and repos
- [x] Review with team to confirm
- [x] Create follow-up items based on gaps identified

**Acceptance Criteria**:
- [x] Current status of SonarQube analysis for ML OSS Core repos is identified and recorded
- [x] Outdated repos are removed and new repos that are current, are added (on dashboards)
- [x] Follow-up stories are created to fill-in gaps and provide coverage for all relevant repos

## **Pull Requests**:
- N/A

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @elnyry 
- QA/Review: TBC

**Comment by elnyry** [comment]
SonarQube dashboard live here now: http://sonar.mojaloop.live/dashboard, though this is mostly for internal use.
