### ISSUE TITLE
Support for Customer initiated Merchant payments

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#753]
## **Goal**:
As a Merchant
I want to accept a payment from a customer on another FSP

As an FSP of a Merchant
I want to support generating a Payment ID that can be used for a Merchant Payment
	- A proposal for Merchant lookup when IDs in the Scheme are not unique
	- Implement the proposal

As a Customer
I want to pay a Merchant on another FSP

**Tasks**:
- [ ] TBD [ @? ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Follow-up stories are created to implement support for PaymentIDs in ALS or QA if its already present
- [ ] QA is performed for Customer initiated Merchant Payments

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- [ ] Pre-requisites such as 'Payment ID' Proposals are published/accepted

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
outdated
