### ISSUE TITLE
Adopt Quoting service donated and include it as part of a ML OSS Switch deployment

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#754]
## **Goal**:
As a ML OSS Codebase maintainer
I want to adopt the quoting service donated and make changes necessary
so that the quoting service is included as part of ML OSS Switch deployments

**Tasks**:
- [x] Review provided codebase for quoting service [@ggrg @HenkKodde]
- [x] Identify changes needed to get running “as-is” [@HenkKodde @ggrg]
- [x] Generalise the naming (Replace Casa/Mowali with Mojaloop/OSS relevant) [ @HenkKodde ]
- [x] Identify & address content in Docker files that’s Mowali specific [ @HenkKodde ]
- [x] Run the service - Get it running [@ggrg]
- [x] Add knex table migrations, views and seeds [@ggrg] [PR#275](https://github.com/mojaloop/central-ledger/pull/275)
- [x] Get it working with ML OSS Helm [ @mdebarros ]
- [x] Run locally, include as part of the Switch deployment [@ggrg]
- [x] Provide setup to run end-to-end Testing on deployments to check for any issues, log bugs
- [x] Record tasks to be taken-up to refactor Quoting service to follow ML OSS standards [@ggrg]
- [x] Setup Github repo for public release
- [x] Setup initial CI/CD: [ @mdebarros ]
   - [x] Add .circleci dir + configs [ @mdebarros ]
   - [x] Add dockerfiles [ @mdebarros ]
   - [x] Create quoting-services on s3 bucket for sonar reports [ @mdebarros ]

**Acceptance Criteria**:
- [ ] ~Unit Tests pass (none exist)~
- [ ] ~Integration Tests pass (none exist)~
- [x] Helm charts are updated or created to support the quoting service
- [x] Implementation deployed on AWS for QA/Testing
- [x] Stories are created as follow-up to refactor and fill-in the gaps identified in Quoting service to follow ML OSS standards

## **Pull Requests**:
- [ ] ~https://github.com/mojaloop/quoting-service/pull/1~
- [x] https://github.com/mojaloop/central-ledger/pull/275

## **Follow-up**:
- N/A

**Dependencies**:
- [x] The Quoting service donated by Mowali is made available to the OSS Core team

## **Accountability**:
- Owner: @ggrg @HenkKodde 
- QA/Review: Core team

## **Notes**:

**Repos**:
1. https://github.com/mojaloop/quoting-service
2. https://github.com/mojaloop/mowali-container-init-base
3. https://github.com/mojaloop/quoting-service-init

**Next steps**
    1. Identify changes needed to get running “as-is”
    2. Generalize the naming (Replace Casa/Mowali with Mojaloop/OSS relevant)
    3. Stuff in Docker files that’s Mowali specific needs to be identified & addressed
    4. Run the service - Get it running
    5. Get it working with ML OSS Helm

**Questions (To be revisited in Sprint 6.2)**
- Refactor the services to follow OSS Standards ?
- Init script - does it run or create a new DB or update the central-ledger DB or something like that?
- CI/CD pipeline for the init-containers ?

**Comment by kjw000** [comment]
COOL!!
