### ISSUE TITLE
Updating the simulator to support (QA, etc) for ALS

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#756]
## **Goal**:
As a maintainer of the ML OSS Switch software
I want _the Simulators used for QA, testing purposes to simulate an Oracle Registry_
so that end-to-end testing, QA can be performed on a deployable ML Switch with ALS

As a community member
I want to be able to deploy the ML OSS Switch with an ALS and supporting components
so that I can perform end-to-end QA, Testing and analysis

**Tasks**:
- [x] Refactor/Update Simulator implementation to simulate an Oracle Registry service to support the account-lookup-service (ALS) [ @rmothilal ]
- [x] Sanity testing against ALS [ @rmothilal ]
- [x] Helm changes needed to make simulators part of the Mojaloop deployment [ @mdebarros ]
- [x] Deprecate (remove) central-directory and dependencies from the Mojaloop deployment [ @mdebarros ]
- [x] Sanity testing of Helm Charts [ @mdebarros ]

**Acceptance Criteria**:
- [x] The OSS Simulator is updated to simulate an Oracle/Directory to support the QA, testing & deployment of the ML Switch
- [x] Simulators are made part of the Mojaloop deployment

## **Pull Requests**:
- [x] https://github.com/mojaloop/simulator/pull/17 [ @rmothilal ]
- [x] https://github.com/mojaloop/helm/pull/181 [ @mdebarros ]

## **Follow-up**:
- [x] #787 

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rmothilal 
- QA/Review: TBC
