### ISSUE TITLE
DA Review for Bulk transfers design (sequence diagrams), supporting tasks

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#757]
## **Goal**:
As an implementer of Bulk transfers for a ML Switch
I want the designs (sequence diagrams) proposed to be reviewed by the DA so that
they can be refined and feedback, review comments, questions can be addressed.

**Tasks**:
- [x] Decide transport/persistence mechanism for Bulk Transfers as Kafka isn't the recommended option (DB directly, Object store?)
- [x] Confirm codebase management - use central-ledger or a separate repo/repos for bulk prepare, fulfil and processing handlers [If a separate repo for bulk is chosen, follow the similar structure to central-ledger] --> For this proceeding with using a **separate repo** (probably **central-bulk-processing** or something like that) for the codebase handling bulk transfers
- [x] Prepare the sequence diagrams, etc for DA Review [@ggrg, @elnyry ]
  - [x] bulk-fulfil handler overview SD
  - [x] Extend bulk-processing handler SD to break it down
- [x] Propose each of the below to the DA for review
  - [x] bulk-prepare handler
  - [x] prepare handler
  - [x] position handler
  - [x] bulk-processing handler
  - [x] bulk-fulfil handler
  - [x] fulfil handler
  - [x] Architecture diagram for bulkTransfers
- [ ] Address review comments for each by making necessary changes
  - [ ] bulk-prepare handler [@reviewers-placeholder]
  - [x] prepare handler [@reviewers-placeholder]
  - [x] position handler [@reviewers-placeholder]
  - [ ] bulk-processing handler [@reviewers-placeholder]
  - [ ] bulk-fulfil handler [@reviewers-placeholder]
  - [x] fulfil handler [@reviewers-placeholder]
  - [x] Architecture diagram for bulkTransfers

**Acceptance Criteria**:
- [ ] The below sequence diagrams (or designs) are reviewed by the DA and the feedback is incorporated
  - [ ] bulk-prepare handler
  - [x] prepare handler
  - [x] position handler
  - [ ] bulk-processing handler
  - [ ] bulk-fulfil handler
  - [x] fulfil handler
  - [x] Architecture diagram for bulkTransfers

## **Pull Requests**:
- [ ] https://github.com/mojaloop/documentation/pull/60

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
