### ISSUE TITLE
Capture learnings for adopting a donated service/codebase and generalize steps to use as template in future

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#759]
## **Goal**:
As a community member
I want to have a process specified for adopting a feature/service donated to the Mojaloop Open Source
so that I can use it as reference/template for future adoptions.

As a contributor to the ML OSS Switch implementation,
I want to have a process specified for adopting a feature/service donated to the Mojaloop Open Source
so that I can use it as reference while making contributions

**In this instance, we'd like to use the adoption of the 'Quotes service' donated by Mowali as a pilot on following the process or formulate one and then propose the actual process that can be used in future.**

**Tasks**:
- [ ] Review the service donated
- [ ] Review design, conformation to the Mojaloop Specification, standards
- [ ] Identify the minimum list of items needed to be done for the quickest way to run/adopt the service
- [ ] Create stories for refactoring, implementation and for future refactoring to standardize it

**Acceptance Criteria**:
- [ ] Designs are reviewed
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] Helm changes are made and incorporated into Mojaloop Helm

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
Added to standards now - https://docs.mojaloop.io/documentation/contributors-guide/standards/#adopting-open-source-contributions-into-mojaloop
