### ISSUE TITLE
Implement a POC for stream processing pattern

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#76]
**Goal**:
Implement a POC for stream processing pattern

**Tasks**:
- [x] Setup Baseline code (create baseline feature branch)
- [x] Deploy Baseline code **(Miguel)**
- [ ] ~~Deploy Test stubs **(Dep on Murthy)**~~ (Not applicable)
- [ ] ~~Create Baseline tests **(Dep on Murthy)**~~ (Not applicable)
- [ ] Execute performance Baseline test and capture metrics/results **(Dep on Murthy)**
- [x] Setup Stream Processing code base (create impl/feature branch)
- [x] Create Kafka Topics for Prepare Process **(Miguel)**
- [x] Implement Prepare Process using Kafka in NodeJs - Producer Prepare Tx Topic for DFSP1 **(Laz)**
- [x] Implement Prepare Process using Kafka in NodeJs - Consumer of Prepare Tx Topic for DFSP1
- [x] Implement Prepare Process using Kafka in NodeJs - Producer Notifications Topic for DFSP1
- [x] Implement Prepare Process using Kafka in NodeJs - Consumer of Notification Topic for DFSP1
- [x] Implement Prepare Process using Kafka in NodeJs - Producer Notifications Topic for DFSP2
- [x] Implement Prepare Process using Kafka in NodeJs - Consumer of Notification Topic for DFSP2
- [ ] Update Unit Tests to include Kafka Process <-- stub using https://github.com/chbatey/kafka-unit?
- [ ] Update Integration Tests to include Kafka Process <-- stub using https://github.com/chbatey/kafka-unit?
- [ ] Update Functional Tests to include Kafka Process <-- stub using https://github.com/chbatey/kafka-unit?
- [x] Test Functionality of Prepare Process from DFSP1 to DFSP2

**Acceptance Criteria**:
- [x] Prove design (does it work functionally?) (Priority: Highest)
- [x] Prove transactionality (Priority: Highest)

**Dependencies**:
- [ ] #118

**Comment by elnyry** [comment]
A huge work item, there may be a part-2 of this item with a few (if any) related tasks that are yet to be done.
