### ISSUE TITLE
ALS: Setup for QA/Testing of newly added ALS with simulator

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#760]
## **Goal**:
As a QA
I want to have a deployment and configuration setup with ALS
so that I can perform QA, testing of P2P use case end-to-end

**Tasks**:
- [x] Setup postman scripts, environment variables [ @NicoDuvenage, @sri-miriyala  ]
- [x] Update helm to deprecate central-directory and supporting services [ @mdebarros ]
- [x] Update helm to add simulator and related config [ @mdebarros ]
- [x] Update helm to deprecate interop-switch [ @mdebarros ]
- [ ] ~Test deployments to achieve a stable version~ continued in #787 

**Acceptance Criteria**:
- [x] Capability to deploy a Mojaloop Switch with ALS configured that can be tested end-to-end
- [ ] Postman scripts that cover testing of ALS are available

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/181

## **Follow-up**:
- N/A

**Dependencies**:
- [ ] A deployment is available on AWS Dev0 to perform QA/testing on ALS

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
