### ISSUE TITLE
Configure LOG_LEVEL via Helm Charts

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#761]
## **Goal**:
As a `Hub Operator`
I want to `to configure LOG_LEVEL on each container via Helm Charts`
so that `log level can be used for troubleshooting issues`

**Tasks**:
- [ ] Update Central-Ledger Helm Charts to set LOG_LEVEL='info' as standard
   - [ ] Central-Ledger - API
   - [ ] Central-Ledger - Prepare Handler
   - [ ] Central-Ledger - Position Handler
   - [ ] Central-Ledger - Fulfil Handler
   - [ ] Central-Ledger - Timeout Handler
   - [ ] Central-Ledger - Admin Handler
   - [ ] Central-Ledger - Get Handler
- [ ] Update ML-API-Adapter Helm Charts to set LOG_LEVEL='info' as standard:
   - [ ] ML-API-Adapter - API
   - [ ] ML-API-Adapter - Notification Handler
- [ ] Update Central-Settlements Helm Charts to set LOG_LEVEL='info' as standard:
   - [ ] Central-Settlements - API
- [ ] Update Central-Event-Processor Helm Charts to set LOG_LEVEL='info' as standard:
   - [ ] Central-Event-Processor
- [ ] Update Email-Notifier Helm Charts to set LOG_LEVEL='info' as standard:
   - [ ] Email-Notifier
- [ ] Update Account-Lookup-Service Helm Charts to set LOG_LEVEL='info' as standard:
   - [ ] Account-Lookup-Service - API
   - [ ] Account-Lookup-Service - Admin

**Acceptance Criteria**:
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Changes made to config (values.yaml) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] Helm charts by default set the LOG_LEVEL to 'info'
- [ ] Values.yaml provide an easy mechanism to configure LOG_LEVEL as required for installation/upgrades

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
