### ISSUE TITLE
Optimize Dockerfiles to better use docker layer caching

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#762]
## **Goal**:
As a **developer** I want to optimize the docker files to improve the build time both locally and on circleCI.

I've noticed that a lot of Dockerfiles have been written in a way that doesn't take advantage of caching build layers. For example, copying in files from the local dir and then installing packages with `apk add` means that Docker won't be able to use the image cache and need to re-install new packages every time. By simply changing the order of operations in a Dockerfile, we can greatly improve the docker build time for docker images all over the project, and speed up both local dev and CI environments.

**Example:**

For example, with the `test.Dockerfile` in `mojaloop/ml-api-adapter`
Before:
```
FROM mhart/alpine-node:10.15.1
USER root

WORKDIR /opt/ml-api-adapter
COPY src /opt/ml-api-adapter/src
COPY test /opt/ml-api-adapter/test
COPY config /opt/ml-api-adapter/config
COPY package.json /opt/ml-api-adapter/

RUN apk --no-cache add git
RUN apk add --no-cache -t build-dependencies make gcc g++ python libtool autoconf automake && \
    cd $(npm root -g)/npm \
    && npm config set unsafe-perm true \
    && npm install -g node-gyp

RUN npm install -g tape tap-xunit
RUN npm install

RUN apk del build-dependencies

EXPOSE 3000
CMD ["node /opt/ml-api-adapter/src/api/index.js"]
```

After:
```
FROM mhart/alpine-node:10.15.1
USER root

WORKDIR /opt/ml-api-adapter

RUN apk --no-cache add git
RUN apk add --no-cache -t build-dependencies make gcc g++ python libtool autoconf automake && \
    cd $(npm root -g)/npm \
    && npm config set unsafe-perm true \
    && npm install -g node-gyp tape tap-xunit

COPY package.json /opt/ml-api-adapter/
COPY package-lock.json /opt/ml-api-adapter/
RUN npm install

RUN apk del build-dependencies

COPY src /opt/ml-api-adapter/src
COPY test /opt/ml-api-adapter/test
COPY config /opt/ml-api-adapter/config

EXPOSE 3000
CMD ["node /opt/ml-api-adapter/src/api/index.js"]
```
In the optimized Dockerfile, all of the `apk add` steps will be cached, and the `npm install` won't change unless a dependency changes.

## **Tasks**:

For each of the repositories below, go through each dockerfile (including the main `Dockerfile` and any `test.Dockerfile`s etc.) and optimize:

1. The order of operations for the docker build steps to take best of docker layer caching
2. change the root Docker image to the official `node:10.15-alpine` image
3. Collapse or remove redundant steps
4. Update any local scripts that call `docker build` to take advantage of caching
5. Verify builds on CircleCI are taking advantage of docker layer caching (this can sometimes be a little fiddly)

- [x] ml-api-adapter @lewisdaly
- [x] central-ledger @lewisdaly 
- ~~[ ] central-services-stream~~  _note: no dockerfile in this project_
- [x] account-lookup-service @lewisdaly
- [x] central-event-processor @lewisdaly 
- [x] email-notifier @lewisdaly 
- [x] central-settlement @lewisdaly 

_note: please feel free to add or remove from this list - there's likely something I'm missing_

**Acceptance Criteria**:
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-api-adapter/pull/107
- [x] https://github.com/mojaloop/central-ledger/pull/277
- [x] https://github.com/mojaloop/account-lookup-service/pull/8
- [x] https://github.com/mojaloop/central-event-processor/pull/31
- [x] https://github.com/mojaloop/email-notifier/pull/26
- [x] https://github.com/mojaloop/central-settlement/pull/74

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly
- QA/Review: TBC

**Comment by mdebarros** [comment]
Sounds great to me. 

One additional change I would make to the dockerfiles, switch out `mhart/alpine-node` to the official alpine node images for 10.15.x -->`node:10.15-alpine`

Otherwise, I think this is a great idea!

**Comment by ksatya77** [comment]
This is a great suggestion. I also noticed ml-api-adapter taking unusually long time to build locally...

**Comment by lewisdaly** [comment]
Great. Thanks for the feedback. I'll make a list of the projects that can be updated, and make a note about using the official alpine node image.

**Comment by lewisdaly** [comment]
It looks like the CircleCI docker caching is non-trivial and requires an extra fee: https://circleci.com/docs/2.0/docker-layer-caching/

That said, there is still a way to manually cache a docker image and build from that cache in CircleCI without needing to activate their automatic Docker layer caching. In my experience, the time it generally takes to download that cache can tend to make the benefits of docker caching rather small. 

So regarding increasing the build times, I'll just focus on the slowest of the docker builds, and perhaps we can worry about docker caching in CircleCI later on.

**Comment by lewisdaly** [comment]
All PRs are merged. I'll close this one now
