### ISSUE TITLE
Setup helm chart for Quoting service

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#764]
**Goal**:
As a Switch Implementer
I would like to _setup helm charts for the Quoting service component_
so that the quoting-service can be deployed (automatically) using helm.

**Tasks**:
- [x] Create Dockerfile or ensure it is present for the quoting service  (done as part of https://github.com/mojaloop/project/issues/754 / PR https://github.com/mojaloop/quoting-service/pull/1)
- [x] Setup helm chart for quoting service
- [x] Configure quoting service helm values
- [x] Test Helm chart deployment

**Acceptance Criteria**:
- [x] A helm chart for quoting service component is created that facilitates the deployment of quoting service is made available

**Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/179

**Dependencies**:
- [x] A release for quoting service to test

**Accountability**:
- Owner @mdebarros 
- QA/Review Core team
