### ISSUE TITLE
Define a standard event model/structure

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#766]
## **Goal**:
As a `Hub Operator` I want to `define a standard event model/structure` so that `events are generic enough to handle all types of events (e.g. errors, audits, etc)`

**Tasks**:
- [ ] Identity event mode/structure standards that are a good fit for purpose
- [ ] Define event model/structure based on standards/design
- [ ] Document event model/structure

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
Part of #767 now
