### ISSUE TITLE
Design Event, Auditing and Error Framework Proposal

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#767]
## **Goal**:
As a `Hub Operator`, I want to `design an Event, Auditing & Error Framework` so that `events, errors and logs can be persisted, auditable (where applicable) and provide end-to-end tracing`

**Tasks**:
- [x] define high-level architecture & blue-print [ @mdebarros ]
- [x] define standard model/structure for events/errors [ @mdebarros ]
- [x] define event types to cater for events/errors [ @mdebarros ]
- [x] define event actions to cater for events/errors [ @mdebarros ]
- ~~identify dashboard/reports~~ (_moved to new story_)
- ~~define/design auditing aspects (including crypto-interlocks/hashing)~~ (_moved to new story_)
- [x] document interaction diagram
- [x] document process flows (sequence diagrams)  [ @mdebarros ]
- [x] document design specification in documentation repo  [ @mdebarros ]

**Acceptance Criteria**:
- [x] Logging mechanism that provides flexible options for 
    - [x] persistence (e.g. log file, kafka topic) - _detailed_
    - ~~auditing (including crypto inter-locks/hashing supporting existing capabilities of the existing forensic-logging-sidecar solution at a high-level) - _high-level for future detailed consideration_~~
- ~~Tracing of events/errors for end-to-end monitoring - _detailed_~~ (_moved to new story_)
    - e.g. zipkin/opentracing
- [x] Event/Error model/structure: 
    - types - _detailed_
    - actions - _detailed_
    - error - _detailed_
- ~~Error handling~~ (_moved to new story_)
    - ~~standard error mapping/lookups (from db or api, etc) - _detailed_~~ (_moved to new story_)
    - ~~API/Persistence store designs (if required) - _detailed_~~ (_moved to new story_)
- [x] The design must cater for generic to support for existing (and future) mojaloop components
	- als
	- quotes
	- settlements
	- etc
- [x] Document future requirements
- [x] Proposal submitted to DA for review

## **Pull Requests**:
- [x] https://github.com/mojaloop/documentation/pull/85

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @mdebarros 
- QA/Review: Design Authority

**Comment by elnyry** [comment]
Added a tentative estimate as it doesn't have any right now. @mdebarros @vgenev @rmothilal , please update when you get in a meeting..

**Comment by elnyry** [comment]
Planned it to be till 6.4 even initially, as the scope is large

**Comment by mdebarros** [comment]
Closing story for PI4. Will create follow up stories for scratched out items for PI7 continuation and feedback from Mojacon 2019 June Feedback.
