### ISSUE TITLE
Investigate & PoC end-to-end Tracing solution

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#768]
## **Goal**:
As a `Hub Operator`, I want to `prove an end-to-end tracing solution` so that `messages being processed by the switch can be visually traced through a dashboard`

**Tasks**:
- [x] Investigate technologies that can be used for tracing of events throughout the system (e.g. open-tracing, zipkin)
 - [x] Investigate zipkin [@vgenev]
   - [x] build some basic POC to see if it fits the needs [@vgenev]
 - [x] Investigate jaeger [@rmothilal] 
   - [x] build some basic POC to see if it fits the needs [@rmothilal]
- [x] Determine viability of using the technologies with the Mojaloop solution (API, Kafka, Kubernetes, nodejs client libraries, etc) [@vgenev, @rmothilal, @mdebarros]

- [x] Document findings, recommendations and learnings as part of the Event & Error Handling Design documentation

**Acceptance Criteria**:
- [x] Demo a full trace of the Transfer process through the API Adapter & Handlers (prepare, position, notifications):
   - [x] Show a dashboard showing a visual representation of the transactional message flow
   - [x] Show transactional message info (meta-data, payload, headers, etc) through each of the process steps for each of the associated Adapter/Handler components during the flow
- [x] Documentation:
   - [x] Changes made to the existing message structures to cater to the tracing
   - [x] Changes made to the architecture
   - [x] Findings & Learnings from the PoC
   - [x] Event & Error Handling Framework Design requirements & recomendations
- [x] Execution environment:
   - [x] Demo to be executed on a local machine
   - [x] (Optional) Demo to be executed on Kubernetes

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vgenev 
- QA/Review: @mdebarros

**Comment by elnyry** [comment]
Added a tentative estimate as it doesn't have any right now. @mdebarros @vgenev @rmothilal , please update when you get in a meeting..
