### ISSUE TITLE
Quoting Service: Support for Party Identifier Types & Transaction Scenarios

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#769]
## **Goal**:
As a adopter of the ML OSS
I want the Switch to _support all/most Party Identifiers & Transaction scenarios listed in the Specification_ so that
I can adopt/implement it to support the Use Cases needed

**Tasks**:
- [x] Add support for Party Identifier Types other than MSISDN (email, personal_id, business, device, account_id, IBAN, alias)
- [x] Add support for different Transaction Scenarios beside transfer (deposit, withdrawal, payment, refund)
- [x] Add /health check endpoint
- [x] Remove sensitive output during service startup

**Acceptance Criteria**:
- [x] Changes made to the Quoting service to support Party Identifiers & Transaction scenarios apart from MSISDN and TRANSFER respectively
- [x] Health checks supported to help with deployment, reliability

## **Pull Requests**:
- [x] central_ledger - https://github.com/mojaloop/central-ledger/pull/280
- [ ] quoting-service - https://github.com/mojaloop/quoting-service/pull/3

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by HenkKodde** [comment]
Applying change required as per review.
