### ISSUE TITLE
Quoting service - Adding initial set of tests

### ISSUE THREAD

**Issue by HenkKodde** [mojaloop/project#770]
## **Goal**:
As a QA 
I would like an initial set of tests for unit tests, coverage and integration test for the "happy path", to insure quality delivered solution.

**Tasks**:
- [ ] Unit tests/src
- [ ] Coverage test > 90%
- [ ] Enable unit tests phase in CD/CI
- [ ] Add integration test(s) for happy path
- [ ] Ensure unit tests run as part of CD/CI process

**Acceptance Criteria**:
- [ ] Unit test framework is available for Quoting component that runs with every build and PR on GitHub to ensure quality.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
Covered in #1041 and #1042 (will be)
