### ISSUE TITLE
Quoting Service enhancements: quoteError, quoteExtension, transferRules etc.

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#771]
## **Goal**:
As a ML OSS contributor
I want to enhance Quoting-service implementation
so that Quote Errors and Quote Extension are recorded and Transfer Rules commented out code is removed, but follow-up items are created if necessary

**Tasks**
- [ ] Verify Quote Errors are recorded to DB for error scenarios
- [ ] Implement db storage for quote extensions sent as quote/quoteResponse payload
- [ ] Investigate on Transfer Rules and why code has been added to Quoting Service, but later commented out. Post the findings as a comment to the story.

**Acceptance Criteria**:
- [ ] Quote Errors are captured to DB
- [ ] Quote Extensions are recorded to DB
- [ ] There is clarity on Transfer Rules and commented out code is removed
- [ ] Unit tests pass, if present upon story start

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
some of these (such as error fields) are catered for, the rest will be addressed as part of reference architecture implementation
