### ISSUE TITLE
Quoting service: Adding integration testing

### ISSUE THREAD

**Issue by HenkKodde** [mojaloop/project#772]
## **Goal**:
As a QA 
I would like integration testing functionality for the Quoting system, to insure we deliver a quality solution.

**Tasks**:
- [ ] Integration test are functional
- [ ] Enable integration tests phase in CD/CI
- [ ] Ensure integration test run as part of CD/CI process

**Acceptance Criteria**:
- [ ] Integration test framework is available for Quoting component that runs with every build and PR on GitHub to ensure quality.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
