### ISSUE TITLE
Documentation for Quoting service needs to be created and made available to the community.

### ISSUE THREAD

**Issue by HenkKodde** [mojaloop/project#774]
## **Goal**:
As a community member I would like a set of documents describing the Quoting Service.  
Documentation: Onboarding doc, sequence diagrams, summary, architecture
As a <stakeholder> I want to <action> so that <reason>

**Tasks**:
- [x] README document created as per template guidelines
- [ ] onboarding document describing the onboarding process from a community perspective
- [ ] Architecture outlines and diagrams are available to the community for review
- [x] Sequence diagrams are available to the community for review

**Acceptance Criteria**:
- [x] Documentation is available in gitbooks for the community
- [x] Architecture and sequence diagrams and designs are up-to date
- [ ] README document provides a summary of the service and its relative functionality within the greater Mojaloop project
- [ ] Onboarding document guidelines are tested and easy to follow 

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
This is now addressed via other stories
