### ISSUE TITLE
Quoting Service: Add support for a simple routing mode

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#775]
## **Goal**:
As a ML OSS contributor
I want to implement simple routing mode for the Quoting-Service
so that quoting related messages (request/callbacks/errors) are being passed through without data persistence or additional processing

**Tasks**:
- [x] Confirm the approach for implementing the functionality
- [x] Implementation of simple routing mode
- [x] Implement configurability of the two modes (current mode, pass-through mode)
- [x] Update helm charts with new config from default.json

**Acceptance Criteria**:
- [x] Quoting service supports simple routing mode
- [x] Config setting is available to switch modes of operation
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Changes made to helm charts configuration to reflect changes and default mode chosen

## **Pull Requests**:
- [x] https://github.com/mojaloop/quoting-service/pull/5

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rmothilal 
- QA/Review: @rmothilal @mdebarros
