### ISSUE TITLE
Fix ALS POST Batch Participant

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#776]
**Summary**:
When the POST /participants endpoint on the Oracle is called, the results returned are not handled correctly 

**Severity**:
Medium

**Priority**:
Critical

**Expected Behaviour**
The returned response from the Oracle should contain both successful and failed results and the ALS should be able to handle both cases and respond with the appropriate callback

**Steps to Reproduce**
  1. POST /participants with payload
  2. ALS fails to handle the request
  3. Error message received for all results

**Tasks**
- [x] Align payload to Oracle Swagger https://github.com/mojaloop/documentation/blob/master/api/assets/interface-contracts/oracle-service-swagger-v1.yaml
- [x] Map response to align with API Definition
- [x] Test with simulator

**Specifications**
  - Component (if known): ALS
  - Version: 6.2.0
  - Platform:
  - Subsystem:
  - Type of testing: Manual
  - Bug found/raised by: @rmothilal 

**Notes**:

- Severity when opened: Medium
- Priority when opened: Critical

**Comment by elnyry** [comment]
Thanks @rmothilal
