### ISSUE TITLE
Issues in postman tests giving incorrect/misleading results

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#779]
**Summary**:
Issues in 'postman' test scripts leading to incorrect/misleading test reports. Some of the known issues are with tests regarding error codes (strings / numbers) and some timing issues.

**Severity**:
High

**Priority**:
Medium

**Expected Behavior**
 1. The postman collections (FSP setup, Golden path) when run on a Mojaloop deployment with no known issues, should run without any issues. If there is an issue in the deployment, the corresponding tests should fail (The Setup collection is running fine so far).

**Steps to Reproduce**
  1. On a Mojaloop deployment (newly setup or otherwise) run the Golden Path collection
  2. Review the results / report
  3. Failures involve error codes related issues, which follow the specification

**Specifications**
  - Component (if known): QA Framework - collections (and tests) in the 'postman' repo
  - Version: Since May 7th 2019
  - Platform: Dev0, AWS
  - Subsystem: 'postman' tests - error codes, invalid duplicate transfer tests, timing issues, etc
  - Type of testing: Automated (either by cron job or triggered manually)
  - Bug found/raised by: @elnyry @NicoDuvenage 

**Notes**:

- Severity when opened: High
- Priority when opened: Medium

**Tasks**
 - [x] Fix some test scripts which were failing by altering the variables tested against
 - [x] Raise bugs on the Scrum Board against non-test-script errors
 - [x] Temporarily comment out failing tests (3) attributed to bugs in the code until they can be re-introduced to be tested
 - [x] Re-instate the scheduled test run
 - [x] Ensure we get a clean run - that way unblocking new releases

**Comment by elnyry** [comment]
New tests for ALS, Quoting, Simulator changes still happening.. Moving to 6.3
