### ISSUE TITLE
Analyse sidecar implementation for central repositories

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#78]
**Goal**:
Analyse sidecar implementation for central repositories

**Tasks**:
- [x] Run forensic logging sidecar locally (or k8s/helm)
- [x] Review Central-kms service and document observations
- [x] Analyze & document forensic logging sidecar's current capabilities (anything different from [documentation](https://github.com/mojaloop/forensic-logging-sidecar) already present).
- [x] Document recommendations for forensic logging sidecar

**Acceptance Criteria**:
- [x] Document the capabilities and limitations of the current sidecar implementation
- [x] Document recommended enhancements
- [x] The findings and output will serve as an input for the Threat modeling

**Dependencies**:
- None currently

**Comment by elnyry** [comment]
Couldn't finish this because of surge of work on the PDP project (Support for Switch, fixes)

**Comment by elnyry** [comment]
PR: https://github.com/mojaloop/forensic-logging-sidecar/pull/9

**Comment by elnyry** [comment]
Review approved by Nico.
