### ISSUE TITLE
Review design for duplicate check on 'prepare transfers' & refactor if necessary

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#780]
## **Goal**:
As a Mojaloop Hub
I want to handle duplicate 'prepare requests' in a standardized way
so that the process can be definitive and re-usable and secure

**Tasks**:
- [x] Review existing design, separate out sequence diagram for duplicate prepare checks [@ggrg]
- [x] Agreement on whether validation checks are to be made first or duplicate checks first [@ggrg]
- [x] Document current state of central-ledger duplicate handling [@ggrg]
- [x] Update design according to peer reviews [@ggrg]
- [x] Keep the DA informed of the changes [@ggrg]
- **Sprint 7.2**:
- [x] Update Request Duplicate Check design according to DA decisions [@ggrg]
- [x] Remove outdated hrefs to mojaloop/docs [@ggrg]
- [x] Update existing Transfer Prepare diagrams [@ggrg]
- [x] Confirm updated designs with the team/DA [@ggrg]
- [x] Add Request Duplicate Check code to shared library [@ggrg]
- [ ] Refactor implementation to reflect the changes in design [@ggrg]
  - [x] Implement Request Duplicate Check for prepares [@ggrg]
  - [x] Reproduce all possible prepare scenarios [@ggrg]
  - [ ] ~Resolve issue with Generic Validation Error send & resend [@ggrg, @elnyry]~
  - [x] Fix failing unit tests
  - [ ] ~Add unit tests to achieve full tests coverage [@ggrg]~

**Acceptance Criteria**:
- [ ] ~Unit Tests pass~
- [x] Integration Tests pass
- [x] Duplicate handling on transfer 'prepare requests' is standardized
- [x] Aligned with [DA decision](https://github.com/mojaloop/design-authority/issues/29)
- [ ] ~central-ledger codebase aligned to the design~

## **Pull Requests**:
- [ ] ~https://github.com/mojaloop/documentation/pull/64~
- [ ] ~https://github.com/mojaloop/documentation/pull/97~
- [x] https://github.com/mojaloop/documentation/pull/98

## **Follow-up**:
- N/A

**Dependencies**:
- [x] Error Framework - Adopt and Integrate Mojaloop SDK Error Handling Component - Central-Ledger #838

## **Accountability**:
- Owner: TBC
- QA/Review: DA

**Comment by elnyry** [comment]
Taken too late in the sprint, moving to the next one

**Comment by ggrg** [comment]
The implementation of this story would have major merge issues with #838, so moving it to blocked.

**Comment by ggrg** [comment]
Also, after discussion with the team it was decided that for generic errors during transfer prepares we would not do extra handling, but DA is to be informed about it.

**Additional Information**:
Transfer Prepare with invalid (non-existing) dfsp (or account) callback:
```
	{
	  "method" : "PUT",
	  "path" : "/transfers/8c25ccf6-cd3b-4718-8a17-07c14bd69893/error",
	  "headers" : {
	    "content-type" : [ "application/vnd.interoperability.transfers+json;version=1.0" ],
	    "date" : [ "Thu, 25 Jul 2019 09:37:01 GMT" ],
	    "fspiop-source" : [ "switch" ],
	    "fspiop-destination" : [ "dfsp1" ],
	    "host" : [ "localhost:1080" ],
	    "content-length" : [ "117" ],
	    "Connection" : [ "close" ]
	  },
	  "keepAlive" : false,
	  "secure" : false,
	  "body" : "{\"errorInformation\":{\"errorCode\":\"3100\",\"errorDescription\":\"Generic validation error: Participant dfsp2A not found\"}}"
	}
```
Callback on resend:
```
	{
	  "method" : "PUT",
	  "path" : "/transfers/8c25ccf6-cd3b-4718-8a17-07c14bd69893",
	  "headers" : {
	    "content-type" : [ "application/vnd.interoperability.transfers+json;version=1.0" ],
	    "date" : [ "Thu, 25 Jul 2019 09:37:01 GMT" ],
	    "fspiop-source" : [ "switch" ],
	    "fspiop-destination" : [ "dfsp1" ],
	    "host" : [ "localhost:1080" ],
	    "content-length" : [ "141" ],
	    "Connection" : [ "close" ]
	  },
	  "keepAlive" : false,
	  "secure" : false,
	  "body" : "{\"completedTimestamp\":\"2019-07-29T06:20:20.000Z\",\"transferState\":\"ABORTED\",\"extensionList\":[{\"key\":\"prepare\",\"value\":\"Prepare description\"}]}"
	}
```

**Comment by ggrg** [comment]
DA suggestion: optionally add another extension to the GET -
 ```
{"key": "cause", "value": "Participant dfsp2A not found".} ```
