### ISSUE TITLE
Review design for duplicate check on 'fulfil transfer' requests & refactor if necessary

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#781]
## **Goal**:
As a Mojaloop Hub
I want to handle duplicate 'fulfil requests' in a standardized way
so that the process can be definitive and re-usable

**Tasks**:
- [x] Review existing design, separate out sequence diagram for duplicate fulfil check [@ggrg]
- [x] Keep the DA informed of the changes [@ggrg]
- **Sprint 7.2**:
- [x] Update Fulfil Request Duplicate Check design according to DA decisions (in notes) [@ggrg] [6db4f3a](https://github.com/ggrg/documentation/commit/6db4f3a?diff=unified)
- [x] Update existing Transfer Fulfil diagram [@ggrg]
- [x] Confirm updated designs with the team/DA [@ggrg]
- [ ] ~Refactor implementation to reflect the changes in design [@ggrg]~

**Acceptance Criteria**:
- [ ] ~Unit Tests pass~
- [ ] ~Integration Tests pass~
- [x] Duplicate handling on transfer 'fulfil requests' is standardised and definitive
- [x] Aligned with [DA decision](https://github.com/mojaloop/design-authority/issues/29)
- [ ] ~central-ledger codebase aligned to the design~

## **Pull Requests**:
- [ ] ~https://github.com/mojaloop/documentation/pull/64~
- [x] https://github.com/mojaloop/documentation/pull/98

## **Follow-up**:
- N/A

**Dependencies**:
- [x] Error Framework - Adopt and Integrate Mojaloop SDK Error Handling Component - Central-Ledger #838

## **Accountability**:
- Owner: TBC
- QA/Review: DA

**Notes**:
1. DA to vote on option 4 above - during *transfer prepares* no db transaction will be used and data will be inserted where possible
2. For *transfer fulfils* DA to consider:
 a. Aborting a prepared transfer for all cases when invalid fulfilment message is received (incl. bad fulfilment from payee, all payee errors, 3rd party attempting to commit etc.)
 b. Do not use provided header data (source/destination), but use stored data for callbacks instead <-- note that this would only be applicable when the source/destination FSPs are not valid.
It will also ensures that:
3. Fulfil requests can't be gamed by multiple invalid attempts. This will harden the security aspects of the transfers.
4. Also ensures that all involved participants will be informed that there have been some invalid request received as a result of being notified.
5. A new transfer will need to be created from the prepare stage if the transaction is to be retried.
6. It will also simplify the solution/implementation of duplicate-checks because it will be handled exactly in the same way as the prepare stage.

**Comment by ggrg** [comment]
According to the DA decision, the current DB schema "in the perfect world" would be altered for the following tables: **transferFulfilment** and **transferFulfilmentDuplicateCheck**

![image](https://user-images.githubusercontent.com/20338055/62039056-98cf2580-b1ff-11e9-8005-448046fc6ea6.png)
because we no longer need to generate and store UUID transferFulfilmentId. In this case we would make transferId the new PK for these two tables. Or at least, in order to guarantee db integrity, we would add UNIQUE constraint on **transferFulfilmentDuplicateCheck.transferId column**. But that would cause issues with current "real world" implementations.

So the DA needs to decide are we going towards PK or unique constraint solution by providing additional scripts for dealing with data stored so far, or shall we give up on db integrity and implement this story leaving the db model as is.

**Comment by NicoDuvenage** [comment]
Georgi,

Thanks - I did not check, but if you have not yet, please add any
correspondence regarding this DA Issue into the relevant place in the DA
Issue Log.

Thanks,
Nico
--


[image: Modusbox_Logos_Modusbox_Vertical_2C.png] <http://www.modusbox.com/>

Nico Duvenage, Director of Services, South Africa

[image: Solution Partner of the Year North America2017.png]
<http://www.modusbox.com/services/>

505 5th Ave S. Suite 300, Seattle, WA 98104

+27.83.741.8856 | nico@modusbox.com <nico.duvenage@modusbox.com>

**Comment by ggrg** [comment]
### DA decision:
- Change the model for this specific case
- Preserve current data in tables such as transferFulfilmentDuplicateCheckYYYYMMDD, transferFulfilmentYYYYMMDD
- Migrate current data into new tables
- For currently stored data:
  - prefer records with settlementWindowId NOT NULL
  - if all records have settlementWindowId NULL, then prefer the one created first

Ensure **Release notes** includes the impact on the database and link to the suggested script.
