### ISSUE TITLE
Bulk Transfers: PoC to use MongoDB for the incoming bulk message to address size considerations

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#783]
## **Goal**:
As a Hub Operator
I want to address the considerations about the size of bulk messages by doing a PoC using MongoDB
so that it can be used to get clarity on how it can be used to complement the existing Kafka framework and use it for implementing the Bulk Transfers PoC

**Tasks**:
- [x] PoC to use MongoDB as transport mechanism/object store to persist and retrieve bulk messages without having to put the entire message on kafka (only use a reference)
  - [x] Use MongoDB in ml-api-adapter to persist an incoming Bulk Message and pass along a message on to the Kafka topic for the bulk-prepare-handler
  - [x] Prepare bulk transfer and individual transfer schemas with reference to the bulk document
  - [x] Validate bulk and individual transfers against schema (basic validation for field)
  - [x] Investigate unique field, indexes and hashes for duplicate checks
  - [x] Investigate mongoose middleware for error handling on validations
  - [x] Retrieve the message for processing the bulk-prepare-handler (to be validated, broken down in bulk-prepare-handler after this)
- [x] Publish single transfer to transfer prepare handler

**Acceptance Criteria**:
- [x] A PoC that demonstrates using MongoDB  to store and retrieve bulk messages between the ml-api-adapter and bulk handlers is done.
- [x] Update the designs for bulk if necessary, based on this and use it as reference for the Bulk transfers PoC implementation

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vgenev 
- QA/Review: DA, Core team

**Notes**:
- Bulk Transfers design stories #744 , #745
