### ISSUE TITLE
Consolidate and update the onboarding documentation

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#784]
## **Goal**:
As a developer I want to consolidate and update the onboarding docs to improve the onboarding experience for new developers.

At the moment, most of the major sub-projects has it's own `Onboarding.md` file. Some of them are out of date, are missing information, or are a little redundant.

**Tasks**:
- [x] consolidate and update the `Onboarding.md` files to a single Onboarding file in the `mojaloop/mojaloop` project. _Someone suggest a better place if they would like_
- [ ] update local installation guides for:
  - [ ] Linux
  - [x] MacOS
  - [ ] Windows
- [ ] Update and simplify the `Onboarding.md` docs in the following repos to link to this new common Onboarding file.
   - [x] ml-api-adapter
   - [x] central-ledger
   ~- [ ] central-directory~ - not worth the time since it will soon be deprecated
   - [x] central-end-user-registry
   - [x] central-event-processor
   - [x] quoting-service

~- [ ] update other links in docs that refer to individual Onboarding docs~ _Not necessary, as we are keeping the current links and pointing back to the unified onboarding doc._
- [x] fix the link in `mojaloop/docs` to refer to this new unified onboarding doc. [Should be somewhere in mojaloop/documentation now] *pr pending*

**Acceptance Criteria**:
- [ ] Documentation style meets standards
- [ ] After reading through new onboarding doc, new contributors will have all the steps necessary to get up and running with Mojaloop locally
- [ ] All links will be up-to-date

## **Pull Requests**:
- [x] https://github.com/mojaloop/mojaloop/pull/232
- [x] https://github.com/mojaloop/ml-api-adapter/pull/109
- [x] https://github.com/mojaloop/central-ledger/pull/283
- [x] https://github.com/mojaloop/central-end-user-registry/pull/11
- [x] https://github.com/mojaloop/central-event-processor/pull/33
- [x] https://github.com/mojaloop/quoting-service/pull/6
- [x] https://github.com/mojaloop/documentation/pull/74

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Does it make sense to delete the individual onboarding docs as they could be superseded by this new one? Or is it preferable to keep the existing docs, and link to the new consolidated one?

**Comment by elnyry** [comment]
Preferably we just leverage the existing ones and use them with links instead of getting rid of them altogether, I think...

**Comment by lewisdaly** [comment]
Most of the onboarding docs refer to MySQLWorkbench, eg.
https://github.com/mojaloop/central-ledger/blob/master/Onboarding.md#installing-mysqlworkbench

Is there really any need for this MySQLWorkbench? Is is something that all the developers are using?

**Comment by lewisdaly** [comment]
MacOS prs are merged in, and I'm working on the linux instructions now. @RobReeve is going to help with the Windows instructions.

**Comment by mdebarros** [comment]
@lewisdaly let me know if you need a Windows VM to do any testing. I can set one up for you if required on our cloud host.

**Comment by lewisdaly** [comment]
@mdebarros yes please.

@elnyry This is still in progress - I've almost finished going through the installs for Linux, but I just need a windows vm to test the steps for windows on.

**Comment by lewisdaly** [comment]
We're run into a roadblock with the Windows instructions: the virtualized environment we set up on AWS to test the docker commands doesn't work as AWS doesn't support nested virtualization.

I'm going to a unassign this now, and hopefully we either resolve the issues with a virtual windows environment, or somebody who has a windows machine can pick this up.

**Comment by elnyry-sam-k** [comment]
@lewisdaly we have https://github.com/mojaloop/project/issues/844 for windows, so can this be closed?
