### ISSUE TITLE
Bulk Transfers: Sequence diagrams for GET /bulktransfers/{ID}

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#786]
## **Goal**:
As a Hub Operator
I want to _have a design for the bulk transfers Use Case (the /bulkTransfers end-point)_
so that _I can use it to support the bulk Transfers use-case with an implementation that uses this as reference (based on the API Definition)._ 

This specific story is for designing sequence diagrams for the newly proposed get-bulk-transfer-handler

**Tasks**:
- [x] Validate partial fulfill implementation [@oderayi] 
  - ~Validate ABORTED state is included in bulk processing state check~ (Not necessary)
  - [x] Validate that notification to Payee FSP includes only fulfilled transfers (for golden path - prepare & fulfill)
  - [x] Validate that notifications to Payer FSP include all original transfers sent by Payer FSP (prepare & fulfill)
- ~Update documentation (sequence diagrams) to match current implementation for duplicate checks on `POST /bulkTransfers`~  _(moved to a separate story https://github.com/mojaloop/project/issues/1459)_
- [x] Update existing sequence diagrams to match current implementation (prepare) [@oderayi]
- [x] Create sequence diagrams for get-bulk-transfer-handler [@oderayi]
- [x] Provide PR for changes, accommodate feedback [@oderayi]
- [ ] PR merged and released

**Acceptance Criteria**:
- [x] Designs are up-to-date (other sequence diagrams)
- [x] Sequence diagrams created for the below:
  - [x] get-bulk-transfer-handler

**Pull Requests**:
- [x] https://github.com/mojaloop/bulk-api-adapter/pull/34
- [x] https://github.com/mojaloop/documentation/pull/234

**Follow-up**:
- Implementation of the handler for GET /bulkTransfers/{ID}

**Dependencies**:
N/A

**Accountability**:
- Owner: @elnyry
- QA/Review: DA
