### ISSUE TITLE
Integrating ALS, Quoting, JWS changes in deployment and fixing issues & documentation

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#787]
## **Goal**:
As a community member
I want to have a stable mojaloop deployment that includes native ALS, Quoting services and JWS fixes

This story is for the core team to debug issues with arising out of integrating the substantial changes introduced by the ALS, Quoting service and JWS fixes.

**Tasks**:
- [x] Iterate over the below tasks [ @mdebarros, @NicoDuvenage, @rmothilal, @elnyry, @vgenev ]
  - [x] Deploy 6.2.x or 6.3.x services for ALS, Quoting service and other central services
  - [x] Test deployment
  - [x] Fixes, Hotfixes
  - [x] Release, Publish
  - [x] Verify impacts to CEP/Email-Notifier 
- [x] Update documentation to reflect changes [ @mdebarros ]
- [x] QA Framework to be tested against release [ @sri-miriyala, @NicoDuvenage ]

**Acceptance Criteria**:
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] A stable deployment with the features from ALS, quoting service, JWS added in Sprint 6.2 is made available (using postman testing scripts, other sanity tests)
- [x] Documentation updated to reflect changes

## **Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/192

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @mdebarros 
- QA/Review: @mdebarros

**Comment by mdebarros** [comment]
Helm published --> https://github.com/mojaloop/helm/releases/tag/v6.3.0
