### ISSUE TITLE
Identify technologies used for tracing

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#789]
## **Goal**:
As a `Hub Operator` I want to `identify technologies used for tracing` so that `events tracing can be included as part of the error & event handling framework`

**Tasks**:
- [ ] Identify possible tracing technologies and standards that can be used for the error & event handling framework
- [ ] document options, and how they can be utilised as part of the error and event handling framework

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
