### ISSUE TITLE
Analyse the current fraud management capability implemented for demonstration purposes

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#79]
**Goal**:
As a Switch 
I would like to _analyze the current fraud management capability implemented for demonstration purposes_
so that I can assess what the gaps are between the existing setup and requirements and based on with further actions can be taken.

**Tasks**:
- [ ] Analyze the current FRMS capabilities
- [ ] Based on research/experience, provide recommendations

**Acceptance Criteria**:
- [ ] Document the capabilities and limitations of the current fraud detection implementation
- [ ] Document recommended enhancements

**Dependencies**:
- [ ]

**Comment by kjw000** [comment]
should be moved to 1.2?

**Comment by elnyry** [comment]
The current FRMS uses a random number generation and then uses that number to categorize the category. This is probably on demo purpose and doesn't have limitations as such but needs a production level capability.

**Comment by elnyry** [comment]
The recommended enhancements need input from the separate stream which is working on this. (need Nico's input to start with)

**Comment by elnyry** [comment]
Has been picked up by a separate stream..
