### ISSUE TITLE
Implement event framework PoC

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#790]
## **Goal**:
As a `Hub Operator` I want to `implement Event Framework PoC` so that `so that all events (errors, general, etc) can be audited and traced appropriately`

**Tasks**:
- [ ] Event Framework
	- SDK <-- ** [ @ramiro, @rajiv ]
		- [ ] Created Github repo
		- Design Event SDK
			- interfaces (typescript) for Clients
				- methods
				- inputs
				- outputs
				- health check (if applicable)
				- design gRPC client
			- interfaces (typescript) for Server
				- methods
				- inputs
				- outputs
				- health check (if applicable)
				- design gRPC server
		- Implement Event SDK
			- [ ] Implement client
				- [ ] Implement transport using gRPC
				- [ ] Generate events as per the model specification
				- [ ] Validate events as per the model specification
			- [ ] Implement server
				- [ ] Implement transport using gRPC
				- [ ] Prase events as per the model specification
				- [ ] Validate events as per the model specification
			- [ ] identify where/how Event SDK can be plugged into existing streaming and handler code-base
			   	- [ ] identify how the Logger framework can be updated to utilise the event Event SDK for "log-events"
			- CI/CD: [ @rajiv ]
				- [ ] Implement CI/CD
				- [ ] Publish SDK with releases
	- [ ] Integrate SDK for logging <-- ** [ @rajiv ]
	    - [ ] central-services-shared
	    	- [ ] Integrate SDK into logger as optional dependency injection
		- [ ] ml-api-adapter - API
			- [ ] Configuration of logger for either winston vs event-framework
			- [ ] Traces for start/end
			- [ ] Integrate into health end-points for Event Sidecar
		- [ ] ml-api-adapter - Notifications
			- [ ] Configuration of logger for either winston vs event-framework
			- [ ] Traces for start/end
			- [ ] Integrate into health end-points for Event Sidecar
		- [ ] prepare handler
			- [ ] Configuration of logger for either winston vs event-framework
			- [ ] Traces for start/end
			- [ ] Integrate into health end-points for Event Sidecar
		- [ ] position handler
			- [ ] Configuration of logger for either winston vs event-framework
			- [ ] Traces for start/end
			- [ ] Integrate into health end-points for Event Sidecar
		- [ ] fulfil handler
			- [ ] Configuration of logger for either winston vs event-framework
			- [ ] Traces for start/end
			- [ ] Integrate into health end-points for Event Sidecar
		- [ ] get handler
			- [ ] Configuration of logger for either winston vs event-framework
			- [ ] Traces for start/end
			- [ ] Integrate into health end-points for Event Sidecar
		- [ ] admin handler
			- [ ] Configuration of logger for either winston vs event-framework
			- [ ] Traces for start/end
			- [ ] Integrate into health end-points for Event Sidecar
		- [ ] timeout handler
			- [ ] Configuration of logger for either winston vs event-framework
			- [ ] Traces for start/end
		- [ ] central-settlements
			- [ ] Configuration of logger for either winston vs event-framework
			- [ ] Traces for start/end
			- [ ] Integrate into health end-points for Event Sidecar
		- QA Framework  <-- ** [ @? ]
			- Simulator
				- [ ] Configurable to start event consumer
				- [ ] Consume events from event topic
				- [ ] Provide API to query events consumed from topic
			- Test Scripts
				- [ ] Update QA Test scripts to validate
					- EventTypes
						- [ ] Trace start/end events
						- [ ] Logging? -- TBC
						- [ ] Audits -- TBC (when this is implemented)
					- [ ] components -- TBC - for wich components should this be tested? I would imagine all of them.
- [ ] Sidecar <-- ** [ @rajiv ]
	- [ ] Created Github repo
	- [ ] Implement base skeleton
	- [ ] Implement health end-points for readiness and liveliness
	- [ ] Implement server side for Event SDK (gRPC)
	- [ ] Implement producer for events into specific partition for event-type
	- CI/CD:
		- [ ] Implement CI/CD
		- [ ] Publish Docker image with releases

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] Integrated into Mojaloop components
	- [ ] Ensure that components can not operate without Sidecar functioning correctly when enabled
	- [ ] Ensure that components will not startup without Sidecar when enabled
	- [ ] Sidecar can be disabled for local development and/or debugging purposes only
- [ ] Event SDK
	- [ ] Client Interface for Event SDK
	- [ ] Server Interface for Event SDK
	- [ ] Implemented as part of the Logger framework
	- [ ] Implemented as part of the Server sidecar to produce messages to the event-topic
	- [ ] Implemented trace events for start/end of each component flow (e.g. prepare, position, fulfil, notifications, etc)
	- [ ] Implemented audit event for each each ingress/egress component flow (e.g. prepare, fulfil, notifications, etc)
- [ ] Sidecar
	- [ ] Implement SDK for Server
	- [ ] Handles re-connections between client/server

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Current draft design --> https://github.com/mdebarros/documentation/blob/feature/%23767DesignEvent,AuditingandErrorFrameworkProposal/mojaloop-technical-overview/event-framework/README.md

**Comment by mdebarros** [comment]
Closing story as this has been broken up into the following stories:

- https://github.com/mojaloop/project/issues/803
- https://github.com/mojaloop/project/issues/804
- https://github.com/mojaloop/project/issues/805
- https://github.com/mojaloop/project/issues/806
- https://github.com/mojaloop/project/issues/807
