### ISSUE TITLE
Event Framework - Helm Charts - Update EFK to include APM

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#791]
## **Goal**:
As a `Hub Operator` I want to `include the event framework as part of mojaloop helm charts` so that `mojaloop deployments will include all necessary components to support even logging/auditing`

**Tasks**:
- [x] Update EFK Helm Charts to include APM as part of the deployment [ @mdebarros ]
- [x] Deploy an EFK + APM Server that can be accessed externally to support the development [ @mdebarros ]
- [x] Test EFK Server ingestion [ @mdebarros, @vgenev, @rmothilal ]
    - [x] Tested APM
    - [x] Tested Fluentd

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] EFK Charts have been updated:
   - [x] Include APM as part of EFK deployment
   - [x] include configuration for APM as part of deployment

## **Pull Requests**:
- [ ] https://github.com/mojaloop/helm/pull/204

## **Follow-up**:
- N/A

**Dependencies**:
- [ ] https://github.com/mojaloop/project/issues/750 - **BLOCKER**

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
