### ISSUE TITLE
Event, Auditing and Error Framework Design - Part II - Data Extensions

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#792]
## **Goal**:
As a `Hub Operator`, I want to `design an Event, Auditing & Error Framework` so that `events, errors and logs can be persisted, auditable (where applicable) and provide end-to-end tracing`

**Tasks**:
- Revise design to clarify/include the following aspects:
  - [x] Extend Trace Meta-data Object
    - [x] transaction-type
    - [x] tags
  - [x] Clarify the definition for Internal vs External Errors. E.g:
        - position validation failure (i.e. net-debit cap reached)
        - prepare validation failure (i.e. participant not valid)
        - prepare validation failure (i.e. participant not valid, duplicates
        - callback failed by notification handler due to network connectivity
        - callback failed by notification handler due fsp responding with error
        - etc
- [ ] review changes with team
- [ ] update design with Team's feedback and promote
- [ ] publish new version
- [ ] Create/updated Stories for implementation

**Acceptance Criteria**:
- [ ] design updated
- [ ] design fully reviewed and ratified by the Team (already reviewed by DA at a high level)
- [ ] Revised design published as part of the documentation repository
- [ ] Stories for implementation have been groomed/updated

## **Pull Requests**:
- [x] https://github.com/mojaloop/documentation/pull/94

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Documentation merged
