### ISSUE TITLE
Generalise Simulator by a programmable/config API

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#793]
## **Goal**:
As a `Hub Operator`, I want to `have a Simulator that supports a programmable API` so that `expectations can be set dynamically at runtime to support the QA process` 

**Tasks**:
- [ ] TBD [ @? ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Simulator provides an API to set-up an `expectation`s (e.g. HTTP Method, URL, etc with params), and include a means to configure the response (i.e. headers, payload, callback URL, etc or no response). Thereby giving the flexibility to handle all current use-cases and also support future ones going forward.
- [ ] QA Framework is updated to set the necessary `expectations` to enable the end-to-end functional tests
- [ ] QA Framework is able to run successfully against the simulator 

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
mojaloop-simulator now has 'rules' capability
