### ISSUE TITLE
Add missing documentation end-points for API services

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#795]
## **Goal**:
As a `Hub Operator`, I want to `documentation end-points for APIs` so that `I can view the implemented API capabilities of services`

**Tasks**:
- [x] Add /documentation end-point to Central-Settlements
- [ ] ~Add /documentation end-point to Quoting-Service~ No need already following central-ledger documentation

**Acceptance Criteria**:
- [x] /documentation end-point to Central-Settlements displays swagger/open-api docs
- [ ] ~/documentation end-point to Quoting-Service displays swagger/open-api docs~ No need already following central-ledger documentation
- [x] Unit Tests pass
- [x] Integration Tests pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-settlement/pull/139

## **Follow-up**:
- N/A

**Dependencies**:
- [x] @rmothilal is making changes to the settlement api dependencies [@ggrg]

## **Accountability**:
- Owner: @gibaros 
- QA/Review: @rmothilal

**Comment by gibaros** [comment]
Central settlement PR [#139](https://github.com/mojaloop/central-settlement/pull/139) has been merged
