### ISSUE TITLE
Address code quality issues reported by SonarQube

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#798]
## **Goal**:
As a ML OSS Codebase maintainer
I want to address the quality issues reported by SonarQube
so that the issues can be fixed and code quality improved for the OSS codebase

**Tasks**:
- [ ] Address high priority issues reported for:
  - [x] account-lookup-service
  - [ ] central-event-processor
  - [ ] central-services-auth
  - [ ] central-services-database
  - [ ] central-services-error-handling
  - [ ] central-services-metrics
  - [x] central-services-shared
  - [ ] central-services-stream
  - [ ] central-ledger
  - [ ] central-settlement
  - [ ] email-notifier
  - [ ] forensic-logging-sidecar
  - [x] ml-api-adapter
  - [ ] pathfinder-provisioning-client
  - [ ] pathfinder-query-client
  - [ ] quoting-service
  - [ ] simulator
- [ ] Address other issues reported for:
  - [x] account-lookup-service
  - [ ] central-event-processor
  - [ ] central-services-auth
  - [ ] central-services-database
  - [ ] central-services-error-handling
  - [ ] central-services-metrics
  - [x] central-services-shared
  - [ ] central-services-stream
  - [ ] central-ledger
  - [ ] central-settlement
  - [ ] email-notifier
  - [ ] forensic-logging-sidecar
  - [x] ml-api-adapter
  - [ ] pathfinder-provisioning-client
  - [ ] pathfinder-query-client
  - [ ] quoting-service
  - [ ] simulator

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Notes**:
- Dashboard: http://sonar.mojaloop.live/dashboard

**Comment by gibaros** [comment]
Status update:

-central-event-processor - completed, PR approved and merge

-central-ledger, pending on PR # 303

-ml-api-adapter, reviewed, reported code coverage was not showing, fixed by Sam

-central-services-shared, reviewed, reported showing old code, fixed by Sam

-pathfinder-provisioning-client, reviewed, console log statements will be replaced once new logging framework direction is set per Miguel

-pathfinder-query-client, reviewed, console log statements will be replaced once new logging framework direction is set per Miguel

**Comment by gibaros** [comment]
Reviewing Sonar "Bugs & Vulnerabilities" for all repos
