### ISSUE TITLE
Bulk Transfers: Implement object-store [ml-api-adapter -> bulk-prepare handler]

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#800]
## **Goal**:
As a Hub Operator
I want to _implement the /bulkTransfers end-point_
so that _I can support the bulk Transfers use-case (based on the API Definition)._ 

This specific story is to implement the process of persisting an incoming bulk message to the Object store, passing a bulk notification with the reference on Kafka and accessing the persisted bulk message in the bulk-prepare or bulk-fulfil handler.

**Tasks**:
- [x] Implement persisting a bulk message to the Object store, passing a bulk notification with the reference on Kafka and accessing the persisted bulk message in the bulk-prepare handler (Following-up on the Poc done - #783 ). [@vgenev]
- [x] Use a separate server to run bulk transfers API [@vgenev] 
  - [x] prepare swagger file for the api [@vgenev]
  - [x] generate service code, using the hapi-open-api builder and refactor it to be introduced to the ml-api-adapter code base [@vgenev]
  - [x] create configuration to be able to start the bulk transfer api from ml-api-adapter [@vgenev]
- [x] Fixed issues after introducing object store to ml-api-adapter and central-ledger [@ggrg]
  - [x] added failAction to Hapi config to produce verbose validation failure message [@ggrg]
  - [x] removed individualTransfer fields that do not exist in the spec from swagger definition and mongo model definition and save at ml-api-adapter [@ggrg]
  - [x] generated bulkPayloadHash at ml-api-adapter and produced it to BulkPrepareHandler [@ggrg]
  - [x] decoded individualTransfers at central-ledger and added back properties from the bulk level [@ggrg]
  - [x] fixed hanging unit tests issue and enabled sidecar [@ggrg]
- [x] PR [ @vgenev, @ggrg  ]
- [x] Sanity Testing [ @vgenev, @ggrg ]

**Acceptance Criteria**:
- [x]  Persisting a bulk message to the Object store, passing a bulk notification with the reference on Kafka and accessing the persisted bulk message in the bulk prepare handler is implemented and available for re-use

**Pull Requests**:
-  [x] https://github.com/mojaloop/ml-api-adapter/pull/112

**Follow-up**:
- TBD

**Dependencies**:
- [ ] #783 

**Accountability**:
- Oxner: 
- QA/Review:
