### ISSUE TITLE
Add license scanning and npm audit into the CI/CD pipeline

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#801]
## **Goal**:
As a *project maintainer*, I want to *add a license scanning and npm audit steps into the CI/CD pipeline* so that *new dependencies don't introduce unwanted security vulnerabilities and OSS license restrictions*.

**Tasks**:
- [x] Add `npm-license-checker` to the CI/CD pipeline, with failure conditions for unknown or [viral licenses](https://en.wikipedia.org/wiki/Viral_license).
- [x] Add a `npm run audit` step to the CI/CD pipeline that fails on critical security issues
- [x] Apply to the following projects:
  - [x] `account-lookup-service`
  - [x] `central-ledger`
  - [x] `central-event-processor`
  - [x] `email-notifier`
  - [x] `ml-api-adapter`
  - [x] `central-settlement`
  - [x] central-services-auth
  - [x] central-services-database
  - [x] central-services-error-handling
  - [x] central-services-metrics
  - [x] central-services-shared
  - [x] central-services-stream
  - [x] forensic-logging-sidecar
  - [x] pathfinder-provisioning-client
  - [x] pathfinder-query-client
  - [x] quoting-service
  - [x] simulator

**Acceptance Criteria**:
- [x] CI/CD Pipelines are updated
- [x] Branch protection rules are updated to require the new `vulnerability-check` and `audit-licenses` steps
- [x] Any necessary dependencies are updated to fix CI/CD pipeline failures

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-api-adapter/pull/111
- [x] https://github.com/mojaloop/ml-api-adapter/pull/129
- [x] https://github.com/mojaloop/central-services-auth/pull/33
- [x] https://github.com/mojaloop/central-services-database/pull/47
- [x] https://github.com/mojaloop/central-services-error-handling/pull/34
- [x] https://github.com/mojaloop/central-services-metrics/pull/8
- [x] https://github.com/mojaloop/central-services-shared/pull/55
- [x] https://github.com/mojaloop/central-services-stream/pull/10
- [x] https://github.com/mojaloop/pathfinder-provisioning-client/pull/12
- [x] https://github.com/mojaloop/pathfinder-query-client/pull/13
- [x] https://github.com/mojaloop/quoting-service/pull/8
- [x] https://github.com/mojaloop/simulator/pull/33
- [x] https://github.com/mojaloop/account-lookup-service/pull/17
- [x] https://github.com/mojaloop/central-ledger/pull/325
- [x] https://github.com/mojaloop/central-event-processor/pull/38
- [x] https://github.com/mojaloop/email-notifier/pull/30
- [x] https://github.com/mojaloop/central-settlement/pull/80
- [x] https://github.com/mojaloop/forensic-logging-sidecar/pull/16

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@elnyry we've merged in the first addition to `ml-api-adapter`, and added 2 files:
- a `.licenseignore` file, which specifies packages we have manually approved that are false positives ([example](https://github.com/mojaloop/ml-api-adapter/blob/master/.licenseignore))
- a `.licensebanned` file, which specifies license names that we aren't ok with ([example](https://github.com/mojaloop/ml-api-adapter/blob/master/.licensebanned))

I feel like maintaining these 2 files across all projects would be rather unwieldy - is there a good place to put these files that we can pull in across all projects? The other option is to integrate them as defaults in the [licence-scanner](https://github.com/vessels-tech/license-scanner) toolkit I built, and pull that into the mojaloop project. 

That would

**Comment by lewisdaly** [comment]
As discussed at the convening, we need to also run the license scanner across the final docker image's `node_modules`, as there is a chance (however slim) that the licenses could change inside the docker image from the npm install step that runs inside of circleci.

I'm extending the `license-scanner` tool to run against a docker image, which will copy the node_modules out of the docker image, and run the license scan across them.

**Comment by lewisdaly** [comment]
We have solid steps for integrating the `npm audit` and the license scanning steps into the CI workflow - now I just need to copy them across all of the projects.

**Comment by lewisdaly** [comment]
@elnyry does this need to be done for `forensic-logging-sidecar`? I thought that was being deprecated.

**Comment by elnyry** [comment]
@lewisdaly thats correct, may be we can skip it for now.

**Comment by lewisdaly** [comment]
@elnyry done!
