### ISSUE TITLE
PoC Event SDK - Client & Server Implementation

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#803]
## **Goal**:
As a `Hub Operator` I want to `implement Event Framework PoC` so that `so that all events (errors, general, etc) can be audited and traced appropriately`

**Tasks**:
- [x] Event Framework
	- SDK [ @ramirogm ]
		- [x] Created Github repo
		- [x] Design Event SDK
			- interfaces (typescript) for Clients
				- methods
				- inputs
				- outputs
				- health check (if applicable)
				- design gRPC client
			- interfaces (typescript) for Server
				- methods
				- inputs
				- outputs
				- health check (if applicable)
				- design gRPC server
		- [x] Implement Event SDK
			- [x] Implement client
				- [x] Implement transport using gRPC
				- [x] Generate events as per the model specification
				- [x] Validate events as per the model specification
			- [x] Implement server
				- [x] Implement transport using gRPC
				- [x] Prase events as per the model specification
				- [x] Validate events as per the model specification
			- [x] identify where/how Event SDK can be plugged into existing streaming and handler code-base
			   	- ~identify how the Logger framework can be updated to utilise the event Event SDK for "log-events"~ (_moved to a separate story_)
			- CI/CD: [ @rmothilal  ]
				- [x] Implement CI/CD
				- [x] Publish SDK with releases

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- ~Integration Tests pass~ (_moved to a separate story_)
- [x] Code Style & Coverage meets standards (_moved to a separate story_)
- ~Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment configs.~ (_not applicable_)
- [x] Event SDK
	- [x] Client Interface for Event SDK
	- [x] Server Interface for Event SDK
	- [x] Unit Tests
	- ~Implemented as part of the Logger framework~ (_moved to a separate story_)
	- [x] Implemented as part of the Server sidecar to produce messages to the event-topic
	- ~Implemented trace events for start/end of each component flow (e.g. prepare, position, fulfil, notifications, etc)~ (_moved to a separate story_)
	- ~Implemented audit event for each each ingress/egress component flow (e.g. prepare, fulfil, notifications, etc)~ (_moved to a separate story_)

## **Pull Requests**:
- [x] https://github.com/mojaloop/event-sdk/pull/1

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Refer to draft design - https://github.com/mdebarros/documentation/blob/feature/%23767DesignEvent,AuditingandErrorFrameworkProposal/mojaloop-technical-overview/event-framework/README.md
