### ISSUE TITLE
Event Framework - Integrate into ML-API-Adapter

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#804]
## **Goal**:
As a `Hub Operator` I want to `integrate Event Framework into Mojaloop components` so that `so that all events (errors, general, etc) can be audited and traced appropriately for Prepare and Fulfil flows`

**Tasks**:
- [x] Event Framework
  - [x] Enhance central services shared
    - [x] Create a Hapi plugin with onPreAuth and onPreResponse to create a span per api request
    - [ ] ~Add to the README and jsdoc a description of the 'sampled' route tag for span creation~
    - [x] Integrate SDK for logging  [ ? ]
      - [x] ml-api-adapter - API
        - [x] Integrate event-sdk
        - [ ] ~Configuration in default.json (e.g. sidecar enabled, logging mode etc)~ defer
        - [x] Import NPM dependency
        - [x] Make route ids more meaningful for the event i.e. ml_post_transfer, ml_put_transfer, ml_put_transfer_error
        - [x] Add 'sampled' route tags
        - [ ] ~Integrate into health end-points for Event Sidecar (if sidecar is enabled)~ defer to #834 
        - [x] Test events being Recorded into EFK
        - [ ] ~Logs (replace existing logs)~
        - [x] Add Audits for beginning of receiving request for Prepare, Fulfil, Errors, etc
        - [x] Add Errors for both Internal (e.g. technical errors) and External (e.g. callback errors)
        - [x] Traces for main span for Prepare, Fulfil, Errors, etc
        - [x] Helm [ @mdebarros ]
          - [x] Integrate event-sidecar into helm chart
          - [x] Updated configuration for default.json in helm chart
      - [x] ml-api-adapter - Notifications
        - [x] Integrate event-sdk
        - [ ] ~Configuration in default.json (e.g. sidecar enabled, logging mode etc)~ defer
        - [ ] ~Integrate into health end-points for Event Sidecar (if sidecar is enabled)~ defer to #834
        - [x] Test events being Recorded into EFK
        - [ ] ~Logs (replace existing logs)~
        - [x] Add Audits for beginning of receiving request for Notifications
        - [x] Add Errors for both Internal (e.g. technical errors - unable to get end-points from Central-Ledger, unable to send callback due to network) and External (e.g. callback resulted in an error from DFSP)
        - [x] Traces for main span for Notifications
        - [x] Helm [ @mdebarros ]
          - [x] Integrate event-sidecar into helm chart
          - [x] Updated configuration for default.json in helm chart
- [x] Integration Testing (with ML-API-Adapter via side-car)
  - [x] Test Log events (info, debug, error, etc) on EFK
  - [x] Test Audit events on EFK
  - [x] Test Trace events on APM

**Acceptance Criteria**:
- [ ] Designs are up-to-date
- [x] Unit Tests pass
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment configs.
- [x] Event Framework integrated into ML-API-Adapter for Prepare and Fulfil flows
	- [ ] Ensure that components cannot operate without Sidecar functioning correctly when enabled
	- [ ] Ensure that components will not startup without Sidecar when enabled
	- [ ] Sidecar can be disabled for local development and/or debugging purposes only
- [x] Helm Charts
	- [ ] Deployment includes sidecar as part of deployment
	- [ ] Deployment includes sidecar configuration
- Recording of Events are correctly being captured
    - [ ] Logs events into EFK
    - [x] Audit events into EFK
    - [ ] Trace events into APM (and EFK via APM)

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-shared/pull/83
- [ ] https://github.com/mojaloop/ml-api-adapter/pull/163

## **Follow-up**:
- N/A

**Dependencies**:
- [ ] https://github.com/mojaloop/project/issues/823
- [x] https://github.com/mojaloop/project/issues/791
- [ ] #874 

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Refer to draft design - https://github.com/mdebarros/documentation/blob/feature/%23767DesignEvent,AuditingandErrorFrameworkProposal/mojaloop-technical-overview/event-framework/README.md

**Comment by elnyry** [comment]
Followed-up by #960
