### ISSUE TITLE
PoC Event SDK - QA Framework

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#805]
## **Goal**:
As a `Hub Operator` I want to `implement Event Framework PoC` so that `so that all events (errors, general, etc) can be audited and traced appropriately`

**Tasks**:
- [ ] Event Framework
	- SDK 
		- QA Framework  <-- ** [ @? ]
			- Simulator
				- [ ] Configurable to start event consumer
				- [ ] Consume events from event topic
				- [ ] Provide API to query events consumed from topic
			- Test Scripts
				- [ ] Update QA Test scripts to validate
					- EventTypes
						- [ ] Trace start/end events
						- [ ] Logging? -- TBC
						- [ ] Audits -- TBC (when this is implemented)
					- [ ] components -- TBC - for wich components should this be tested? I would imagine all of them.

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment configs.
- [ ] logs and traces are tested for mojaloop components

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Refer to draft design - https://github.com/mdebarros/documentation/blob/feature/%23767DesignEvent,AuditingandErrorFrameworkProposal/mojaloop-technical-overview/event-framework/README.md

**Comment by mdebarros** [comment]
I am going to close this story as it has been replaced in scope by the other stories within the Error & Event Handling Framework.
