### ISSUE TITLE
Event Sidecar Implementation

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#806]
## **Goal**:
As a `Hub Operator` I want to `implement Event Framework PoC` so that `so that all events (errors, general, etc) can be audited and traced appropriately`

**Tasks**:
- [x] Sidecar
	- [x] Created Github repo
	- [x] Implement base skeleton
	- [x] Implement health end-points for readiness and liveliness
	- [x] Implement server side for Event SDK (gRPC)
	- [x] Implement producer for events into specific partition for event-type
	- CI/CD:
		- [x] Implement CI/CD
		- [x] Publish Docker image with releases

**Acceptance Criteria**:
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment configs.
- ~~Integrated into Mojaloop components~~ _(moved to a new story)_
	- ~~Ensure that components cannot operate without Sidecar functioning correctly when enabled~~ _(moved to a new story)_
	- ~~Ensure that components will not startup without Sidecar when enabled~~ _(moved to a new story)_
	- ~~Sidecar can be disabled for local development and/or debugging purposes only~~ _(moved to a new story)_
- [x] Event SDK
	- ~~Client Interface for Event SDK~~  _(completed in story https://github.com/mojaloop/project/issues/803)_
	- [x] Server Interface for Event SDK
	- ~~Implemented as part of the Logger framework~~ _(moved to a new story)_
	- [x] Implemented as part of the Server sidecar to produce messages to the event-topic
	- ~~Implemented trace events for start/end of each component flow (e.g. prepare, position, fulfil, notifications, etc)~~ _(moved to a new story)_
	- ~~Implemented audit event for each each ingress/egress component flow (e.g. prepare, fulfil, notifications, etc)~~ _(moved to a new story)_
- [x] Sidecar
	- [x] Implement SDK for Server
	- ~~Handles re-connections between client/server~~ _(moved to a new story)_

## **Pull Requests**:
- [x] https://github.com/mojaloop/event-sidecar/pull/2

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
