### ISSUE TITLE
PoC Event Trace Handling

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#807]
## **Goal**:
As a `Hub Operator` I want to `implement Event Framework PoC` so that `so that all events (errors, general, etc) can be audited and traced appropriately`

**Tasks**:
- [x] Event Framework
        - CI/CD: 
	- Trace Platform
		- ~~Create Helm scripts for deployment~~ _(moved to a new story)_
		- ~~Test Helm script deployment~~ _(moved to a new story)_
		- [x] Configure EFK to show/display tracing messages [@vgenev]
	- Trace Handler
		- [x] Created Github repo (still feature branch)
https://github.com/mojaloop/event-stream-processor/tree/feature/%23807-POC-Event-Trace-Handling 
		- [x] Create project - Event Stream Processor - using CEP pattern [@vgenev]
		- [x] Research on the EFK stack and start an environment [@vgenev]     
		- [x] Wire the ESP component to EFK stack  [@vgenev]
		- [x] Wire the ESP component to tracing environment  [@vgenev]
		- [x] Create transformation of event message to tracing protocol for EFK bridge [@vgenev]
		- [x] Implementation to produce EFK trace bridge protocol messages (https://www.elastic.co/guide/en/apm/agent/nodejs/current/opentracing.html) [@vgenev]
		- ~~Create transformation of event message to tracing protocol for tracing platform~~ _(moved to a new story)_
		- ~~Implementation to produce trace protocol messages ( nice to have if there is time )~~ _(moved to a new story)_

		- CI/CD:
		     - [x] configure circleci config
		     - [x] test circleci config 
		     - [x] setup project on circleci admin

**Acceptance Criteria**:
- [x] Designs are up-to date
- ~~Unit Tests pass~~ _(moved to a new story)_
- ~~Integration Tests pass~~ _(moved to a new story)_
- ~~Code Style & Coverage meets standards~~ _(moved to a new story)_
- [x] Event Stream Processor Tracing Handler
     - [x] Consumes trace messages from the topic-events stream
     - [x] Transforms event messages to tracing protocol
     - [x] Produces tracing messages to either:
          - [x] EFK
          - ~~OpenTracing~~ _(moved to a new story)_
- [x] Tracing Platform (ElasticSearch APM)
    - [x] Show a visual trace of transfers from start to end for prepare flow
         - [x] See metadata as part of each span ( transactionId, participants, etc)
         - [x] See payload (nice to have)
    - ~~Show a visual trace of transfers from start to end for fulfil flow~~ _(moved to a new story)_
         - ~~See metadata as part of each span ( transactionId, participants, etc)~~ _(moved to a new story)_
         - ~~See payload (nice to have)~~ _(moved to a new story)_

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Refer to draft design - https://github.com/mdebarros/documentation/blob/feature/%23767DesignEvent,AuditingandErrorFrameworkProposal/mojaloop-technical-overview/event-framework/README.md
