### ISSUE TITLE
Presentation for Mojaloop PI7 event

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#808]
## **Goal**:
As a member of the presenting team at the Mojaloop PI7 event
I want to _prepare presentations and other material necessary for the PI7 event_
so that _it can be used for discussions, demonstrations at the event and later for circulation and publishing_

**Tasks**:
- [x] Decide on the template, share the Initial draft v0.1 with just topics [Using the mid-pi presentation as a starting point]
- [x] Discussion with team about topics involved, demonstrations to be done
- [x] Identify topics and owners for each section based on attendance, etc
- [x] Draft with all topics and placeholders for every discussion are added
- [x] Individual owners to submit initial draft of slides
  - [x] Intro, Summary
  - [x] ALS
  - [x] Quoting Service
  - [x] Error & Event Handling Framework
  - [x] API Gateway - WSO2
  - [ ] ~Fraud & AML~ [@RobReeve - separate slide deck now]
  - [x] Settlements [Michael Richards]
  - [x] QA, SonarQube [@nicoduvenage, @elnyry ]
  - [x] Bulk Transfers
  - [x] BugFixes, Community Support [@elnyry]
  - [x] DA Update [@nicoduvenage]
  - [x] RoadMap [@elnyry]
- [x] Review a complete slide deck with the team
- [x] Second iteration of presentation deck with updated slides from each owner
- [x] Complete review of the slide deck and make changes.
- [x] A v0.9 of the slide deck is ready

**Acceptance Criteria**:
- [x] A slide-deck that is to be used for the Mojaloop PI7 event is drafted and feedback incorporated
- [x] Individual owners for each topic/section are identified responsible for that topic regarding both slides and discussions at the event.
- [x] Updated Designs are used

**Pull Requests**:
- [ ] 

**Follow-up**:
- N/A

**Dependencies**:
- N/A

**Accountability**:
- Owner: @elnyry 
- QA/Review: ML Core team
