### ISSUE TITLE
Automate the CI pipeline for central-hub

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#81]
**Goal**:
As a developer I would like to automate the CI pipeline for central-hub so that I can shorten the development cycle

**Tasks**:
- [x] Migrate CircleCI v1 to CircleCI v2
- [x] Create CircleCI v2 parallel job for Unit Testing
-  ~~Create CircleCI v2 parallel job for Integration Testing~~ *(Not applicable)*
-  ~~Create CircleCI v2 parallel job for Functional Testing~~ *(Not applicable)*
- [x] Create CircleCI v2 parallel job for Code Coverage Testing
- [x] Automate the upload of Code Coverage results to SonarQube
- [x] Publish build snapshot artefacts to Docker Hub if all tests are successful if there is a tag push to the development branch
- [x] Publish build release artefacts to Docker Hub if all tests are successful if there is a tag push to the master branch

**Acceptance Criteria**:
- [x] Automated build artifacts are published to the respective repository for master (release) and develop (snapshot) pushed tags 
- [x] Automated unit tests for PR validations with results made available
- ~~Automated integration tests for PR validations with results made available~~ *(Not applicable)*
- ~~Automated functional tests for PR validations with results made available~~ *(Not applicable)*
- [x] Automated code coverage tests for PR validations with results made available to sonar-qube

**Dependencies**:
- None currently

**Comment by mdebarros** [comment]
PR: https://github.com/mojaloop/central-hub/pull/9

**Comment by elnyry** [comment]
Thanks Miguel. Before we close this, it would be nice to add those stories and leave them in some backlog items so that we don't lose track.

**Comment by mdebarros** [comment]
@elnyry I have created place holder issues for the lack of Integration and Functional tests which has been added to the backlog.

**Comment by bhcrosslake** [comment]
@NicoDuvenage I don't verify this. I fixed the central hub repo on sonarqube (it was messed up) but there's no code coverage file in the S3 bucket for sonar/central-hub

**Comment by mdebarros** [comment]
@bhcrosslake I had to create a new branch called "master-test" to be able to verify the functionality.
- https://github.com/mojaloop/central-hub/tree/master-test

See bellow screenshots showing the locv.info file in the s3 bucket
- https://www.dropbox.com/s/qohnz0wia74mi4g/Screenshot%202018-02-15%2016.49.28.png?dl=0 <-- circleCi job with the step, and the resultant lcov.info file in the s3 bucket
- https://www.dropbox.com/s/7y35xapen524ygf/Screenshot%202018-02-15%2016.49.50.png?dl=0 <-- CircleCI Config showing the code change for the "master-test" branch check instead of the usual "master"

CircleCI Job of the build: 
- https://circleci.com/workflow-run/6d4bae98-5297-448d-b1c4-15bc2d8e4102

Please verify and let me know if I can delete the "master-test" branch.

**Comment by bhcrosslake** [comment]
Ah. because we deleted the keys in aws, sonarqube couldn't download the coverage file - I'll fix.

**Comment by bhcrosslake** [comment]
Coverage is now being updated. The coverage file is out of sync with the master branch so I had to manually update the paths in the file from "/home/circleci/project". The script expects "/home/ubuntu/" since that's what the path is in CircleCI if the coverage is generated their.

**Comment by mdebarros** [comment]
Awesome thanks @bhcrosslake. Moving this story to completed.

Let me know if there are any other issues.

**Comment by mdebarros** [comment]
Demo: https://drive.google.com/file/d/1T-i2NAK6uBqbAP1EM6j_Gonsh_kaot2f/view?usp=sharing
