### ISSUE TITLE
QA and Regression Testing Framework - Enhancements

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#811]
## **Goal**:
As a QA Tester, I want to be sure the framework uses and accesses the correct information so that the trust in the system and validity of the results are never in question

**Tasks**:
- [x] Clean up unused variables from the environment file(s) [ @NicoDuvenage  ]
- [x] Move Mojaloop Testing Framework EC2 to the London Region to enforce VPC connection to the server [@mdebarros , @elnyry , @NicoDuvenage ]
- [x] Make required changes on Server and scheduled scripts to target Dev-1 [@NicoDuvenage ]
- [x] Fix FSP Setup postman collection for running on AWS dev1[ @elnyry  ]
  - [x] Parameterize hostnames where dev0 values were used
  - [x] Fix tests as relevant
  - [x] Deploy, run FSP setup collection for clean run
  - [x] Raise PR

**Acceptance Criteria**:
- [x] All collection Tests in 'master' pass along with setup collection

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: [ @NicoDuvenage ]
- QA/Review: TBC
