### ISSUE TITLE
Upgrade EFK, Promfana Helm Charts to latest versions

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#814]
## **Goal**:
As a `Hub Operator`, I want to `upgrade Helm Prometheus Charts to the latest version` so that `the retention by size can be utilised to ensure data retention can be configured by size`

**Tasks**:
- [x] Upgrade Helm Charts for Prometheus (and related sub-charts)
- [x] Update values config for Prometheus (new/modified configs + container tags/versions)
- [x] Upgrade Helm Charts for Grafana (and related sub-charts)
- [x] Update values config for Grafana (new/modified configs + container tags/versions)
- [ ] Fix issues with Grafana Dashboards
    - [x] `Promfana Dashboards - Central-Service - # Pods for each Components` <-- `kube_deployment_spec_replicas` metric no longer exists
    - [x] `ML-API - # Nodes for each Components`  <-- `kube_deployment_spec_replicas` metric no longer exists
    - [x] `Simulators- # Nodes for each Components`  <-- `kube_deployment_spec_replicas` metric no longer exists
    - [ ] All MySQL Dashboards are no longer operational
    - [ ] Validate all other charts are operational
- [x] EFK charts updated

**Acceptance Criteria**:
- [x] Updated Helm Chart dependencies for Promfana upgrade
- [x] Updated Helm Chart configs for Promfana upgrade
- [x] Updated Helm Chart versions for Promfana upgrade
- [x] Upgraded Promfana charts are published
- [x] Updated Helm Chart dependencies for EFK upgrade
- [x] Updated Helm Chart configs for EFK upgrade
- [x] Updated Helm Chart versions for EFK upgrade
- [x] Upgraded EFK charts are published

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
@mdebarros - this seems to be covered by https://github.com/mojaloop/helm/pull/349 , can you please confirm?
