### ISSUE TITLE
API Gateway for Mojaloop Dev - Initial implementation

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#815]
## **Goal**:
As a Hub Operator
I want to implement an API Gateway (using WSO2) on a Mojaloop Switch
so that I can use it as a Gateway for validations (JWS, Schema) and Authentication.

**Tasks**:
- [x] Setup Infrastructure in ML OSS environment to setup Gateway
- [x] Setup WSO2 API Gateway
- [x] Configurations
- [x] Testing
- [x] Demo

**Acceptance Criteria**:
- [x] Design for the initial implementation is drafted
- [x] ~A single~ One Gateway for inbound and another for outbound traffic is used
- [x] Authentication (+ way for people to create and register APPs to generate auth details) is provided
- [x] Incoming Validation of requests (schema + auth) is done
- [x] Incoming SSL-one-way ( lets-encrypt )
- [x] Helm script to deploy WSO2 ( non-persistent + pre-backed config (e.g. ssl cert) )

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @markusvanaardt @orcr 
- QA/Review: ML Core team
