### ISSUE TITLE
On-boarding team members to the ML OSS Core team - Neal

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#818]
**Goal**:
As a ML OSS Core team member
I would like to make sure new team members
have a checklist of items to address for on-boarding

**Tasks**:
- [x] ModusBox emails (Nico)
- [x] Collect GitHub IDs: ndonnan
- [x] Get access to the mojaloop github organisation
- [x] Send self-invitation link to Slack mojaloop workspace: https://mojaloop-slack.herokuapp.com/
- [x] Slack invite to mojaloop-core-team channel, self-join onboarding
- [x] Introduction to Mavenlink time-tracking requirement: https://sites.google.com/modusbox.com/intranet/getting-started/time-expenses
- [x] Introduction to GitHub workflow - https://www.atlassian.com/git/tutorials/comparing-workflows
- [x] Introduction to standard coding style - add standard extension to the IDE: https://standardjs.com/
- [x] Brief overview of documentation (mojaloop/mojaloop, mojaloop.io/documentation, mojaloop.io): https://mojaloop.io/documentation/
- [x] Onboarding videos: https://drive.google.com/open?id=1kpQw5WU5djfWTPqYI1F65msbs6WNWyik
- [x] Getting the Central-Ledger up and running on local machines: 
  - [x] https://github.com/mojaloop/central-ledger/blob/master/Onboarding.md
  - [x] https://github.com/mojaloop/ml-api-adapter/blob/master/Onboarding.md
- [x] Share Local Kubernetes Development Guide
   - [x] https://mojaloop.io/documentation/deployment-guide/
- [x] Share Helm Charts Guide: https://github.com/mojaloop/helm/blob/master/README.md
- [x] Ensure ZenHub access
  - [x] Sign up for Zenhub: https://www.zenhub.com/ using your github account and connect to mojaloop organisation. Search for the 'project' workspace.
  - [x] Install the Zenhub Chrome extension: https://www.zenhub.com/extension You can now see the Zenhub board at: https://github.com/mojaloop/project#zenhub
- [x] Zoom availability
- [x] Contributors Guide: https://mojaloop.io/documentation/contributors-guide/
- [x] Dropbox access (Sam)
- [x] PI presentations - https://github.com/mojaloop/documentation-artifacts/tree/master/presentations/June%202019%20PI-7_OSS_community%20session

**Comment by ndonnan** [comment]
All tasks have been completed and the issues encountered have been raised.
This includes the central-ledger documentation referring to a postman collection that is no longer available and minor fixes for the mojaloop onboarding documentation
