### ISSUE TITLE
On-boarding team members to the ML OSS Core team - Juan

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#819]
**Goal**:
As a ML OSS Core team member
I would like to make sure new team members
have a checklist of items to address for on-boarding

**Tasks**:
- [x] ModusBox emails
- [x] Collect GitHub IDs: gibaros
- [x] Get access to the mojaloop GitHub Organisation
- [x] Sign up for Zenhub: https://www.zenhub.com/ using your github account and connect to mojaloop organisation. Search for the 'project' workspace.
- [x] Install the Zenhub Chrome extension: https://www.zenhub.com/extension You can now see the Zenhub board at: https://github.com/mojaloop/project
- [x] Send self-invitation link to Slack mojaloop workspace: https://mojaloop-slack.herokuapp.com/
- [x] Slack invite to mojaloop-core-team channel, other OSS team channels
- [x] Introduction to Mavenlink time-tracking requirement: https://sites.google.com/modusbox.com/intranet/getting-started/time-expenses
- [x] Introduction to GitHub workflow - https://www.atlassian.com/git/tutorials/comparing-workflows
- [x] Introduction to standard coding style - add standard extension to the IDE: https://standardjs.com/
- [x] Brief overview of documentation (mojaloop/mojaloop, mojaloop.io/documentation, mojaloop.io)
- [x] Onboarding videos: https://drive.google.com/open?id=1kpQw5WU5djfWTPqYI1F65msbs6WNWyik
- [x] Getting the Central-Ledger up and running on local machines: 
  - [x] https://github.com/mojaloop/central-ledger/blob/master/Onboarding.md
  - [x] https://github.com/mojaloop/ml-api-adapter/blob/master/Onboarding.md
- [x] Share Local Kubernetes Development Guide
   - [x] https://mojaloop.io/documentation/deployment-guide/
- [x] Share Helm Charts Guide: https://github.com/mojaloop/helm/blob/develop/README.md
- [x] Ensure ZenHub access
  - [x] https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd
  - [x] https://github.com/mojaloop/project#boards?repos=116650553 
- [x] Zoom availability
- [x] Contributors Guide: https://mojaloop.io/documentation/contributors-guide/
- [x] Dropbox access (Sam)
- [x] PI presentations - https://github.com/mojaloop/documentation-artifacts/tree/master/presentations/June%202019%20PI-7_OSS_community%20session

**Comment by gibaros** [comment]
Comments to update tasks:
-says GitHub Workflow, but we use Forking Workflow, so should be updated
-in addition to standard.js, there are other extensions like: ESLint, Code Runner
-Nothing at: https://drive.google.com/open?id=1Nb69-S_CkTpczSV4syrGs3bpYVo_XMjz
-Nothing at: https://github.com/mojaloop/helm/blob/develop/README.md

**Comment by gibaros** [comment]
Onboarding completed
