### ISSUE TITLE
Automate the CI pipeline for central-services-shared

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#82]
**Goal**:
As a developer I would like to automate the CI pipeline for central-services-shared so that I can shorten the development cycle

**Tasks**:
- [ ] 

**Acceptance Criteria**:
- [x] Automated build artifacts are published to the respective repository for master (release) and develop (snapshot) pushed tags 
- [x] Automated unit tests for PR validations with results made available
-  ~~Automated integration tests for PR validations with results made available~~ (not applicable)
-  ~~Automated functional tests for PR validations with results made available~~ (not applicable)
- [x] Automated code coverage tests for PR validations with results made available to sonar-qube

**Dependencies**:
- None currently

**Comment by mdebarros** [comment]
Documentation for CI/CD created via this PR:
https://github.com/mojaloop/docs/pull/9

PR: 
https://github.com/mojaloop/central-services-shared/pull/7
