### ISSUE TITLE
Bulk Transfers Initial Release - 2

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#820]
## **Goal**:
As a contributor I want to resolve the technical debt for BulkTransfersPOC so that introduced functionality can be merged to master branches for: central-ledger, ml-api-adapter, bulk-api-adapter, central-object-store

**Tasks**:
- [ ] ~Update BulkProcessingHandler to send callback notification to Payer with bulk prepare result~
- [ ] ~Update BulkFulfilHandler to ABORT payee omitted individualTransfers (not provided in individualTransferResults list)~
- [ ] ~Update sequence diagrams to match current implementation~
- [x] Improve existing unit tests for setup.js to mock MongoDB connection [@ggrg]
- [ ] ~Add unit tests and meet coverage criteria in order to merge code to master repos~
  - [x] Alter .istanbul.yml file to exclude bulk related code for newly added script files [@ggrg]
  - [x] Complement unit tests to meet coverage criteria for bulk related code to existing scripts (e.g. PrepareHandler, PositionHandler, FulfilHandler, existing src/models) [@ggrg]

**Acceptance Criteria**:
- [x] Latest version of central-object-store is used
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
  - [ ] ~Unit tests for Bulk Transfers POC code are added and full tests coverage is achieved~
  - [x] Bulk Transfers POC code is excluded from the coverage report by config (.istanbul.yml)
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config [@mdebarros]

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/307

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
Snapshot release made - https://github.com/mojaloop/bulk-api-adapter/releases/tag/v7.1.1-snapshot
