### ISSUE TITLE
Bulk Transfers Initial Release - 1

### ISSUE THREAD

**Issue by ggrg** [mojaloop/project#821]
## **Goal**:
As a contributor I want to resolve the technical debt for BulkTransfersPOC so that introduced functionality can be merged to master branches for: central-ledger, ml-api-adapter, bulk-api-adapter, central-object-store

**Tasks**:
- [x] Move bulkApi out from ml-api-adapter to new bulk-api-adapter repository
   - [x] Init repo, ability to start the service same as earlier [@ggrg, @elnyry] [6409fd6](https://github.com/mojaloop/bulk-api-adapter/commit/6409fd6)
   - [x] Add consumer config and handler for bulk messages produced to topic-event-notifications [@ggrg]
   - [x] Remove bulk related code from ml-api-adapter and drop the dependency on MongoDB [@ggrg]
   - [x] Initial release [@ggrg]
   - [x] Helm charts [@mdebarros]
       - [x] Fixed deployments issues on bulk-api-handler to support deployment
       - [x] Fixed deployments issues on bulk handlers on central-ledger to support deployment
       - [x] Updated Helm charts to deploy bulk-api [@mdebarros ]
       - [x] Updated Helm charts to deploy bulk handlers on central-ledger [@mdebarros ]
- [x] Central-object-store related tasks
  -  ~Decide on which schemas to use (3 out of 6)~
  -  ~Remove unnecessary schema definitions~
  - [x] Create Initial Release (7.1.0) [@ggrg]
  - [x] Update bulk-api-adapter [@ggrg]

**Acceptance Criteria**:
- [x] Bulk-api-adapter repo is created 
- [x] Bulk-api-adapter repo is added to deployment
- [x] Central-object-store is released and latest version is used

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-api-adapter/pull/125 (dependency #820)
- [x] https://github.com/mojaloop/bulk-api-adapter/pull/1
- [x] https://github.com/mojaloop/central-ledger/pull/313
- [x] https://github.com/mojaloop/bulk-api-adapter/pull/3
- [x] https://github.com/mojaloop/helm/pull/198

## **Follow-up**:
- N/A

**Dependencies**:
1. https://github.com/mojaloop/project/issues/820

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
All tasks except the helm charts are for 7.0
