### ISSUE TITLE
Address security vulnerabilities being reported by GitHub in core services

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#822]
## **Goal**:
As a Mojaloop OSS code base maintainer
I want to update dependencies for vulnerabilities reported by GitHub
so that security issues are fixed

**Tasks**:
- [ ] Update Version of dependencies based on PRs for below repos
  - [ ] account-lookup-service _issues with github security scan: see comment below_
  - [x] central-event-processor
  - [x] central-services-auth
  - [x] central-services-database
  - [x] central-services-error-handling
  - [x] central-services-metrics
  - [x] central-services-shared
  - [x] central-services-stream
  - [x] central-ledger
  - [x] central-settlement
  - [x] email-notifier - _PR Pending_
  - [x] forensic-logging-sidecar - _Pending #801 fixes_
  - [x] ml-api-adapter
  - [x] pathfinder-provisioning-client
  - [x] pathfinder-query-client
  - [x] quoting-service - _Pending #801 fixes_
  - [x] simulator

**Acceptance Criteria**:
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Vulnerabilities and other issues reported by GitHub are addressed by incrementing versions of dependencies (as relevant)

## **Pull Requests**:
- [x] https://github.com/mojaloop/email-notifier/pull/31

## **Follow-up**:
- There is a vulnerability in `lodash` for the current release of `central-services-database:5.2.1`. This has been updated on master, and once we release a new version of `central-services-database`, we should update the following dependent projects: [_Can leverage #866_ ]
  - [ ] account-lookup-service
  - [ ] central-ledger
  - [ ] central-settlement
  - [ ] forensic-logging-sidecar

- The account-lookup-service security alerts from github are for `package.json` and `package-lock.json` files that no longer exist in the project. 
    - I suspect this is a problem with the github security alerts tool, which is still in beta
    - We should take care of these separately.

- the forensic-logging-sidecar is still reporting a vulnerability for `braces`, which is a dependency of the `central-services-database:0.4.0` that this project is stuck on. Upgrading to a newer central-services-database is a breaking change, so this upgrade will need to be followed up separately.

**Dependencies**:
- https://github.com/mojaloop/project/issues/801

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Many of the `account-lookup-service` vulnerabilities reported by github are for `package.json` and `package-lock.json` files that are no longer in the repo.

**Comment by lewisdaly** [comment]
Many of the vulnerabilities (especially for `central-services-*`) have already been addressed in https://github.com/mojaloop/project/issues/801

**Comment by elnyry** [comment]
Thanks Lewis, we can follow-up ALS separately then.

**Comment by lewisdaly** [comment]
Cool. I think it's a bug with how the scanner works on github, it's still in beta after all.

**Comment by lewisdaly** [comment]
@elnyry I think we can consider this one done now. Please see follow-up above for some of the dependency issues I wasn't able to resolve as of now.

**Comment by elnyry** [comment]
Great, thanks!
