### ISSUE TITLE
Event Framework - Event SDK Client & Server Implementation (part II)

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#823]
## **Goal**:
As a `Hub Operator` I want to `enhance the Event Framework PoC` so that `all events (errors, general, etc) can be audited and traced appropriately`

**Tasks**:
- [x] Event Framework [ @vgenev, @mdebarros ]
  - [x] Update design for Event Framework [ @mdebarros ]
  	- [x] Update event to include tag support
  	- [ ] ~Document transaction-types~
  	- [ ] ~Document Error types (aka, Internal vs External)~
  - [x] Implement Event SDK  [ @vgenev ]
  	- [x] Enhance client usability
  		- [x] Re-factor to expose the following usable operations
    		- [x] Inject trace information into inter-service messages
    		- [x] Extract trace information from inter-service messages
    		- [x] Get trace-context from trace information (derive tags e.g. source, destination, transaction-id, transaction-type - e.g. transfer, quote, msisdn - TBC )
    		- [x] Enhance trace-context to include additional tags
    		- [x] Single unified operation to create new and child traces:
  				- [x] Auto-generate IDs (if not present)
  				- [x] Create a new trace (trace-id, span-id, etc) when no trace-context is provided <--- return the new context
  				- [x] Or create a new child trace (same traceid, new spanid, parentid = old spanid, etc) when trace-context is provided <--- return the derived context
    		- [x] Record
  				- [x] log arbiturary text or objects with the trace-context (as optional)
  				    - [x] use await's to ensure synchronuous blocking operations
  				- [x] audit arbiturary text or objects with the trace-context (as optional)
      				- [x] use await's to ensure synchronuous blocking operations
  				- [x] error arbiturary text or objects with the trace-context (as optional)
      				- [x] use await's to ensure synchronuous blocking operations
  				- [x] trace with trace-context (NOT optional - include start & end timestamps)
      				- [x] use await's to ensure synchronuous blocking operations
  		- [x] Configuration
          - [x] Logging options:
            - [x] to stdout sync (aka use existing logger) (aka disable requirement for event-sidecar)
            - [x] to stdout sync (aka use existing logger) & event-sidecar
            - [x] to stdout async (aka use existing logger) & event-sidecar
  	- [ ] ~Implement server~
  		- [ ] ~Support synchronous blocking (by default for now - this can be made to be configurable in future)~

**Acceptance Criteria**:
- [x] Unit Tests pass
- ~Integration Tests pass~ _(to be done in future)_
- [ ] ~Code Style & Coverage meets standards _(optimistic)_~
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment configs.
- [x] Event SDK
	- [x] Unit Tests
	- [x] SDK now supports logger operations and replaces the standard Mojaloop logger (which is used internally within the SDK).
	- ~Implemented trace events for start/end of each component flow (e.g. prepare, position, fulfil, notifications, etc)~ (_moved to a separate story_)
	- ~Implemented audit event for each ingress/egress component flow (e.g. prepare, fulfil, notifications, etc)~ (_moved to a separate story_)

## **Pull Requests**:
- [x] https://github.com/mojaloop/event-sdk/pull/2

## **Follow-up**:
- [ ] https://github.com/mojaloop/project/issues/803

**Dependencies**:
- [ ] https://github.com/mojaloop/project/issues/791

## **Accountability**:
- Owner: @vgenev 
- QA/Review: @mdebarros
