### ISSUE TITLE
Event Framework - Integrate into Central-Services

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#824]
## **Goal**:
As a `Hub Operator` I want to `integrate Event Framework into Mojaloop components` so that `so that all events (errors, general, etc) can be audited and traced appropriately`

**Tasks**:
- [ ] Event Framework
	- [ ] Integrate SDK for logging  [ ? ]
		- [ ] prepare handler
			- [x] Integrate event-sdk
    			- [ ] ~Configuration in default.json (e.g. sidecar enabled, logging mode etc)~ defer
    			- [x] Import NPM dependency
			- [ ] ~Integrate into health end-points for Event Sidecar (if sidecar is enabled)~ defer
			- [x] Test events being Recorded into EFK
    			- [ ] ~Logs (replace existing logs)~
    			- [x] Add Audits for beginning of receiving request for Prepare
    			- [x] Add Errors for both Internal vs External (e.g. errors - validation failure - TBD should this not be external?)
    			- [x] Traces for main span for Prepare
  			- [x] Helm 
    			- [x] Integrate event-sidecar into helm chart
    			- [x] Updated configuration for default.json in helm chart
		- [ ] position handler
			- [x] Integrate event-sdk
    			- [ ] ~Configuration in default.json (e.g. sidecar enabled, logging mode etc)~ defer
    			- [x] Import NPM dependency
			- [ ] ~Integrate into health end-points for Event Sidecar (if sidecar is enabled)~ defer
			- [x] Test events being Recorded into EFK
    			- [ ] ~Logs (replace existing logs)~
    			- [x] Add Audits for beginning of receiving request for Positions
    			- [x] Add Errors for both Internal vs External (e.g. errors - limit validation failure - TBD should this not be external?)
    			- [x] Traces for main span for Positions
  			- [x] Helm 
    			- [x] Integrate event-sidecar into helm chart
    			- [x] Updated configuration for default.json in helm chart
		- [ ] fulfil handler
			- [x] Integrate event-sdk
    			- [ ] ~Configuration in default.json (e.g. sidecar enabled, logging mode etc)~ defer
    			- [x] Import NPM dependency
			- [ ] ~Integrate into health end-points for Event Sidecar (if sidecar is enabled)~ defer
			- [x] Test events being Recorded into EFK
    			- [ ] ~Logs (replace existing logs)~
    			- [x] Add Audits for beginning of receiving request for Fulfil
    			- [x] Add Errors for both Internal vs External (e.g. errors - validation failure - TBD should this not be external?)
    			- [x] Traces for main span for Fulfil
  			- [x] Helm 
    			- [x] Integrate event-sidecar into helm chart
    			- [x] Updated configuration for default.json in helm chart
		- [ ] timeout handler
			- [x] Integrate event-sdk
    			- [ ] ~Configuration in default.json (e.g. sidecar enabled, logging mode etc)~
    			- [x] Import NPM dependency
			- [ ] ~Integrate into health end-points for Event Sidecar (if sidecar is enabled)~
			- [ ] Test events being Recorded into EFK
    			- [ ] ~Logs (replace existing logs)~
    			- [x] Add Audits for beginning of receiving request for Timeout-Events
    			- [x] Add Errors for both Internal vs External (e.g. errors - ?)
    			- [x] Traces for main span for Timeout-Events
  			- [x] Helm 
    			- [x] Integrate event-sidecar into helm chart
    			- [x] Updated configuration for default.json in helm chart
		- [ ] get handler
			- [ ] Integrate event-sdk
    			- [ ] ~Configuration in default.json (e.g. sidecar enabled, logging mode etc)~
    			- [x] Import NPM dependency
			- [ ] ~Integrate into health end-points for Event Sidecar (if sidecar is enabled)~
			- [x] Test events being Recorded into EFK
    			- [ ] ~Logs (replace existing logs)~
    			- [x] Add Audits for beginning of receiving request for Get-Transfer
    			- [x] Add Errors for both Internal vs External (e.g. errors - ?)
    			- [x] Traces for main span for Get-Transfer
  			- [x] Helm 
    			- [x] Integrate event-sidecar into helm chart
    			- [x] Updated configuration for default.json in helm chart

**Acceptance Criteria**:
- [x] Designs are up-to-date
- [x] Unit Tests pass
- [ ] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment configs.
- [x] Event Framework integrated into Central-Services
	- [ ] Ensure that components cannot operate without Sidecar functioning correctly when enabled
	- [ ] Ensure that components will not startup without Sidecar when enabled
	- [ ] Sidecar can be disabled for local development and/or debugging purposes only
- [x] Helm Charts
	- [ ] Deployment includes sidecar as part of deployment
	- [ ] Deployment includes sidecar configuration

## **Pull Requests**:
- [ ] https://github.com/mojaloop/central-ledger/pull/375

## **Follow-up**:
- N/A

**Dependencies**:
- [ ] https://github.com/mojaloop/project/issues/823
- [x] https://github.com/mojaloop/project/issues/791
- [ ] #874 

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
Followed-up by #960
