### ISSUE TITLE
Event Framework - Integrate into Central-Settlements

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#825]
## **Goal**:
As a `Hub Operator` I want to `integrate Event Framework into Mojaloop components` so that `so that all events (errors, general, etc) can be audited and traced appropriately`

**Tasks**:
- [ ] Event Framework
	- [ ] Integrate SDK for logging  [ ? ]
		- [ ] central-settlements
			- [ ] Integrate event-sdk
    			- [ ] Configuration in default.json (e.g. sidecar enabled, logging mode etc)
    			- [ ] Import NPM dependency
			- [ ] Integrate into health end-points for Event Sidecar (if sidecar is enabled)
			- [ ] Recording
    			- [ ] Logs (replace existing logs)
    			- [ ] Add Audits for beginning of receiving request for settlements, settlement-windows, etc
    			- [ ] Add Errors for both Internal vs External (e.g. errors - ?)
    			- [ ] Traces for main span for settlements, settlement-windows, etc
  			- [ ] Helm 
    			- [ ] Integrate event-sidecar into helm chart
    			- [ ] Updated configuration for default.json in helm chart

**Acceptance Criteria**:
- [ ] Designs are up-to-date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment configs.
- [ ] Event Framework integrated into Central-Settlements
	- [ ] Ensure that components cannot operate without Sidecar functioning correctly when enabled
	- [ ] Ensure that components will not startup without Sidecar when enabled
	- [ ] Sidecar can be disabled for local development and/or debugging purposes only
- [ ] Helm Charts
	- [ ] Deployment includes sidecar as part of deployment
	- [ ] Deployment includes sidecar configuration
- [ ] Helm Charts
	- [ ] Deployment includes sidecar as part of deployment
	- [ ] Deployment includes sidecar configuration

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
