### ISSUE TITLE
Event Framework - Integrate into Account-lookup-Service - Part1

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#826]
## **Goal**:
As a `Hub Operator` I want to `integrate Event Framework into Mojaloop components` so that `so that all events (errors, general, admin etc) can be audited and traced appropriately`

**Tasks**:
- [ ] Event Framework
	- [ ] Integrate SDK for logging  [ ? ]
		- [x] account-lookup-service
			- [x] Integrate event-sdk
    			- [x] Configuration in default.json (e.g. sidecar enabled, logging mode etc)
    			- [x] Import NPM dependency
			- [ ] ~Integrate into health end-points for Event Sidecar (if sidecar is enabled)~
			- [ ] ~Recording~
    			- [ ] ~Logs (replace existing logs)~
    			- [x] Add Audits for beginning of receiving request for participants, party, etc
    			- [x] Add Errors for both Internal vs External (e.g. errors - ?)
    			- [x] Traces for main span for participants, party, etc
             - [x] Implemented Endpoints for which Event Framework was integrated into:
                      - [x] GET /oracles
                         - [x] POST /oracles
                         - [x] PUT /oracles/{ID}
                         - [x] DELETE /oracles/{ID}
                         - [x] GET /participants/{TYPE}/{ID}
                         - [x] POST /participants/{TYPE}/{ID}
                         - [x] PUT /participants/{Type}/{ID}/error
                         - [x] POST /participants
                         - [x] GET /parties/{TYPE}/{ID}
                         - [x] PUT /parties/{TYPE}/{ID}
                         - [x] PUT /parties/{Type}/{ID}/error
                         - [x] DELETE /endpointcache

**Acceptance Criteria**:
- [x] Event Framework integrated into Account-Lookup-Service -- Follow-up in #1086
	- [ ] Ensure that components cannot operate without Sidecar functioning correctly when enabled
	- [ ] Ensure that components will not startup without Sidecar when enabled
	- [ ] Sidecar can be disabled for local development and/or debugging purposes only

## **Pull Requests**:
- [ ] https://github.com/mojaloop/account-lookup-service/pull/139

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
