### ISSUE TITLE
Event Framework - Integrate into Quoting-Service

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#827]
## **Goal**:
As a `Hub Operator` I want to `integrate Event Framework into Mojaloop components` so that `so that all events (errors, general, etc) can be audited and traced appropriately`

**Tasks**:
- [x] Explore the current integration of event-sdk with central-ledger and ml-api adapter [@ggrg]
  - [x] Introduction with @ndonnan [@ggrg]
  - [x] Setup vpn [@ggrg]
  - [x] Local setup for pushing to dev1-efk [@ggrg]
  - [x] Local setup of quoting-service, working with simulator to send quoteResponse [@ggrg]
  - [x] Explore event-sdk, event-sidecar, event-stream-processor [@ggrg]
  - [x] Explore related PRs (https://github.com/mojaloop/central-ledger/pull/375, https://github.com/mojaloop/ml-api-adapter/pull/190) [@ggrg]
- [ ] Event Framework
  - [ ] ~Integrate SDK for logging~
  - [x] quoting-service
    - [x] Extend hapi-openapi for use with CentralServices.Util.Hapi.HapiEventPlugin [@ggrg]
    - [x] Integrate event-sdk [@ggrg]
    - [ ] ~Configuration in default.json (e.g. sidecar enabled, logging mode etc)~
    - [x] Import NPM dependency [@ggrg]
    - [ ] ~Integrate into health end-points for Event Sidecar (if sidecar is enabled)~
    - [x] Recording
      - [ ] ~Logs (replace existing logs)~
      - [x] Add Audits for beginning of receiving request for quotes [@ggrg]
      - [x] Handle Errors (for both Internal vs External) [@ggrg]
      - [x] Traces for main span for quotes, etc [@ggrg]
  - [x] Simulator
    - [x] Ensure that simulator is able to process and respond with trace headers for Quoting operations [@ggrg]
    - [x] ~Implement trace header handling on GET Quotes operation (this has not been implemented as part of the original PR)~ [@ggrg] <-- GET /payerfspORpayeefsp/quotes/{id} is not implemented at all, so this is rather a separate simulator story ([create](https://github.com/mojaloop/project/issues/new?assignees=&labels=Story&template=feature_request.md&title=))
  - [ ] Remaining tasks
    - [x] Get PR review for event-sdk, merge & release [@ggrg, @vgenev, @mdebarros]
    - [x] Provide unit tests coverage for central-services-shared [@ggrg]
    - [x] Upgrade central-services-shared to use latest event-sdk [@ggrg]
    - [x] Get PR review for central-services-shared, merge & release [@ggrg]
    - [x] Upgrade LibUtil.getSpanTags for PUT and GET [@ggrg]
    - [x] Fix unit tests for quoting service [@ggrg]
      - [x] Add a story for addressing quoting-service setImmediate calls in unit testing ([create](https://github.com/mojaloop/project/issues/new?assignees=&labels=Story&template=feature_request.md&title=))
    - [x] Upgrade dependencies [@ggrg]
    - [x] Verify newly implemented functionality with story owner [@ggrg, @mdebarros]
    - [ ] Get PR review for quoting-service, merge & release [@ggrg]
  - [ ] ~Helm~
    - [ ] ~Integrate event-sidecar into helm chart~ #1015
    - [ ] ~Updated configuration for default.json in helm chart~ #1015

**Acceptance Criteria**:
- [x] Designs are up-to-date
- [x] Unit Tests pass
- [ ] ~Integration Tests pass~
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment configs.
- [x] Event Framework integrated into Quoting-Service
	- [x] Ensure that components cannot operate without Sidecar functioning correctly when enabled
	- [ ] ~Ensure that components will not startup without Sidecar when enabled~ #834
	- [x] Sidecar can be disabled for local development and/or debugging purposes only
- [ ] ~Helm Charts~
	- [ ] ~Deployment includes sidecar as part of deployment~ #1015
	- [ ] ~Deployment includes sidecar configuration~ #1015

## **Pull Requests**:
- [x] https://github.com/mojaloop/simulator/pull/87
- [x] https://github.com/krakenjs/hapi-openapi/pull/164 --> **Update**: [v1.2.4](https://www.npmjs.com/package/hapi-openapi) released
- [x] https://github.com/mojaloop/central-ledger/pull/445
- [x] https://github.com/mojaloop/event-sdk/pull/13
- [x] https://github.com/mojaloop/central-services-shared/pull/121
- [x] https://github.com/mojaloop/quoting-service/pull/70

## **Follow-up**:
- N/A

**Dependencies**:
- [x] https://github.com/mojaloop/project/issues/823
- [x] https://github.com/mojaloop/project/issues/791

## **Accountability**:
- Owner: @mdebarros 
- QA/Review: TBC
