### ISSUE TITLE
Event Framework - Integrate into Transaction-Service

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#828]
## **Goal**:
As a `Hub Operator` I want to `integrate Event Framework into Mojaloop components` so that `so that all events (errors, general, etc) can be audited and traced appropriately`

**Tasks**:
- [x] Event Framework
	- [x] Integrate SDK for logging  [ ? ]
		- [x] transaction-service
			- [x] Integrate event-sdk
    			- [x] Configuration in ~default.json~ .env (e.g. sidecar enabled, logging mode etc)
    			- [x] Import NPM dependency
			- ~Integrate into health end-points for Event Sidecar (if sidecar is enabled)~ _No longer applicable_
			- [x] Recording
    			- [x] Logs (replace existing logs)
    			- [x] Add Audits for beginning of receiving request for transactions
    			- ~Add Errors for both Internal vs External (e.g. errors - ?)~ _No longer applicable_
    			- [x] Traces for main span for transactions, etc
            - [x] E2E test with event-sidecar and event-stream-processor
  			- [x] Helm 
    			- [x] Integrate event-sidecar into helm chart [@oderayi] 
    			- ~Updated configuration for default.json in helm chart~ 
                - [x] Update `deployment.yml` for Transaction Request Service in helm chart with `.env` variables
              - [x] Deploy and validate in Dev 2

- [x] Documentation
  - [x] Add sequence diagram to Transaction Request Service's documentation 

**Acceptance Criteria**:
- [x] Designs are up-to-date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment configs.
- [x] Event Framework integrated into Transaction-Service
	- [x] Ensure that components cannot operate without Sidecar functioning correctly when enabled
	- [x] Ensure that components will not startup without Sidecar when enabled
	- [x] Sidecar can be disabled for local development and/or debugging purposes only
- [x] Helm Charts
	- [x] Deployment includes sidecar as part of deployment
	- [x] Deployment includes sidecar configuration

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-shared/pull/196
- [x] https://github.com/mojaloop/transaction-requests-service/pull/24
- [x] https://github.com/mojaloop/documentation/pull/193
- [x] https://github.com/mojaloop/helm/pull/288
- [x] https://github.com/mojaloop/transaction-requests-service/pull/28

## **Follow-up**:
- N/A

**Dependencies**:
- [ ] https://github.com/mojaloop/project/issues/823
- [ ] https://github.com/mojaloop/project/issues/791

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
