### ISSUE TITLE
Update the onboarding documentation of Postman initialization

### ISSUE THREAD

**Issue by HenkKodde** [mojaloop/project#829]
## **Goal**:
As a developer I want to have clear reference to understand that an initialization setup is required after an initial or new deployment of the project.

**Tasks**:
- [x] Include reference in Postman section to refer to initial Postman setup requirement[ @HenkKodde  ]

**Acceptance Criteria**:
- [x] Included paragraph to reference required setup
- [x] Verified links are working

## **Pull Requests**:
- [x] https://github.com/mojaloop/documentation/pull/89

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
