### ISSUE TITLE
Automate the CI pipeline for central-kms

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#83]
**Goal**:
As a developer I would like to automate the CI pipeline for central-kms so that I can shorten the development cycle

**Tasks**:
- [ ] 

**Acceptance Criteria**:
- [ ] Automated build artifacts are published to the respective repository for master (release) and develop (snapshot) pushed tags 
- [ ] Automated unit tests for PR validations with results made available
- [ ] Automated integration tests for PR validations with results made available
- [ ] Automated functional tests for PR validations with results made available
- [ ] Automated code coverage tests for PR validations with results made available to sonar-qube

**Dependencies**:
- None currently

**Comment by elnyry** [comment]
Outdated issue
