### ISSUE TITLE
Error Framework - Adopt and Integrate Mojaloop SDK Error Handling Component - ML-API-Adapter

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#830]
## **Goal**:
As a `Hub Operator`, I want to `implement a standard Error Handling framework` so that `errors are consistent throughout the Mojaloop stack for both the Switch and the FSPs`.

**Tasks**:
- [x] Integrate the https://github.com/modusbox/mojaloop-sdk-standard-components dependency into central-services-error-handling [ @ndonnan ]
- [x] Update the central-services-error-handling Hapi plugin to return Mojaloop API compliant error information codes. [ @ndonnan ]
- [x] Integrate the [Error Handler](https://github.com/modusbox/mojaloop-sdk-standard-components/blob/master/src/lib/errors/index.js) from the standard components lib into Mojaloop:
  - [x] ML-API-Adapter [ @ndonnan ]
- [ ] ~Create a task to remove unnecessary try / catch blocks from all components~
- [ ] ~Create a task to create a custom validator for the completedTimestamp body parameter on the fulfil request for ml-api-adapter~
- [ ] ~QA~
  - [ ] ~Ensure that all Errors from the ML API Specification are included~
  - [ ] ~Validate Mojaloop Components return correct ML API Specification Errors (https://github.com/mojaloop/mojaloop-specification/blob/master/API%20Definition%20v1.0.pdf)~
    - [ ] ~ML-API-Adapter~

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [ ] ~Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.~
- [x] Mojaloop SDK Standard Components has been integrated into the main Mojaloop components to provide a consistent error handler framework:
  - [x] ML-API-Adapter
- [ ] ~Mojaloop SDK Standard Components produce compliant ML API Specification errors:~
  - [ ] ~ML-API-Adapter~

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @ndonnan 
- QA/Review: @mdebarros
