### ISSUE TITLE
Event Framework - Integrate into Event Stream Processor

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#833]
## **Goal**:
As a `Hub Operator` I want to `integrate Event Framework into Mojaloop components` so that `so that all events (errors, general, etc) can be audited and traced appropriately`

**Tasks**:
- [ ] Event Framework
	- [ ] Integrate SDK for logging  [ ? ]
		- [ ] event-stream-processor
			- [ ] Identify duplicate functionality that can be replaced with event-sdk (i.e. extract trace-context, etc)
			- [ ] Integrate event-sdk
    			- [ ] Configuration in default.json (e.g. sidecar enabled, logging mode etc)
    			- [ ] Import NPM dependency
			- [ ] Utilise Event SDK to for duplicate functionality
			- [ ] Use enums from Event-SDK where applicable
- Integration Testing
    - [ ] Test Log events (info, debug, error, etc) on EFK
    - [ ] Test Audit events on EFK
    - [ ] Test Trace events on APM

**Acceptance Criteria**:
- [ ] Designs are up-to-date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment configs.
- [ ] Event Framework integrated into event-stream-processor
	- [ ] Ensure that Event-SDK is used to extract trace-context
        - [ ] Use enums from Event-SDK
- [ ] Helm Charts
	- [ ] Deployment includes event-stream-processor as part of deployment
	- [ ] Deployment includes event-stream-processor configuration
- Recording of Events are correctly being captured
    - [ ] Logs events into EFK
    - [ ] Aduit events into EFK
    - [ ] Trace events into APM (and EFK via APM)

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- n/a

**Dependencies**:
-  [x] #873 

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
Picked up some issues while testing.

We may need to inject the start and end times as tags because the APM event does not store that information, but instead only stores the calculated duration. :/

Other improvements that we will need to make:
- add support for HTTP Transport trace context/headers for injections and extraction

@vgenev, @elnyry FYI

1. 

1. 

1.

**Comment by elnyry** [comment]
Thanks Miguel.. Paraphrased your comment and created a new issue here: https://github.com/mojaloop/project/issues/906

**Comment by elnyry** [comment]
[Valentin] - Needs to be re-assessed as to whats needed as part of this.
