### ISSUE TITLE
Event, Auditing and Error Framework Design - Part III - Interlocks

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#834]
## **Goal**:
As a `Hub Operator`, I want to `design an Event, Auditing & Error Framework` so that `events, errors and logs can be persisted, auditable (where applicable) and provide end-to-end tracing`

**Tasks**:
- [ ] Revise design to clarify/include the following aspects:
  - [ ] Inter-lock mechanism between main service and sidecar
    - [ ] Ensure trust between sidecar and main service (aka code has not changed)
    - [ ] Ensure main service cannot operate without sidecar
- [ ] review changes with DA
- [ ] update design with DA's feedback and promote
- [ ] publish new version

**Acceptance Criteria**:
- [ ] design fully reviewed and ratified by the DA
- [ ] Revised design published as part of the documentations repository

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
