### ISSUE TITLE
Event, Auditing and Error Framework Design - Part IV - Audit

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#835]
## **Goal**:
As a `Hub Operator`, I want to `design an Event, Auditing & Error Framework` so that `events, errors and logs can be persisted, auditable (where applicable) and provide end-to-end tracing`

**Tasks**:
- Revise design to clarify/include the following aspects:
  - [ ] Clarify requirements for crypto-signatures on individual audit messages.
  - [ ] Clarify requirements for crypto-signatures on batch of audit messages.
  - [ ] Update design to include design consideration
- [ ] review changes with DA
- [ ] update design with DA's feedback and promote
- [ ] publish new version
- [ ] Create Stories for implementation

**Acceptance Criteria**:
- [ ] design fully reviewed and ratified by the DA
- [ ] Revised design published as part of the documentation repository
- [ ] Stories for implementation have been groomed

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
