### ISSUE TITLE
Updated Grafana Helm Charts to support auto-deployment of dashboards & config

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#837]
## **Goal**:
As a `Hub Operator`, I want to `auto-deploy Grafana configs` so that `manual configuration is reduced`

**Tasks**:
- [ ] Update Grafana Helm Chart to auto-deploy dashboards in correct folders
- [ ] Update Grafana Helm Chart to configure data sources for Prometheus
- [ ] Update Grafana dashboard documentation to reflect the auto-deploy changes
- [ ] Consider updating MySQL dashboard to dashboard #6239 (currently using #7362)

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] Grafana deployments now auto-deploy dashboards
- [ ] Grafana deployments now configure data sources for Prometheus

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
oudated; monitoring tools currently deployed separately; can use IaC as reference:
