### ISSUE TITLE
Error Framework - Adopt and Integrate Mojaloop SDK Error Handling Component - Central-Ledger

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#838]
## **Goal**:
As a `Hub Operator`, I want to `implement a standard Error Handling framework` so that `errors are consistent throughout the Mojaloop stack for both the Switch and the FSPs`.

**Tasks**:
- [x] Integrate the [Error Handler](https://github.com/modusbox/mojaloop-sdk-standard-components/blob/master/src/lib/errors/index.js) from the standard components lib into Mojaloop:
  - [x] Central-Ledger
- [ ] ~QA~
  - [ ] ~Ensure that all Errors from the ML API Specification are included~
  - [ ] ~Validate Mojaloop Components return correct ML API Specification Errors~
     - [ ] ~Central-Ledger~
- [x] src/handlers/lib/utility.js <-- remove createPrepareErrorStatus method and refactor any usages of it
- [x] remove src/Errors folder and its related unit tests at test/unit/errors folder and refactor any usages of it
- [x] remove src/lib/errors.js and refactor any usages of it
- [x] Refactor tests (unit and integration) that use previous Error object in favor of FSPIOPError
  - [x] identify hard coded Errors being created and replace with FSPIOErrors
  - [x] identify if errors are correct per API Specification, eg:
https://github.com/mojaloop/central-ledger/blob/8a34ae14129b8a455703af56fa793cd23fcd1ea5/test/integration/handlers/handlers.test.js#L169
- [x] Update Error Framework ( @mdebarros )
   - [x] Include FSPIOPErrrorTypes to provide regex to validate error codes and types
   - [x] Include function to find ErrorCode from an integer or string
   - [x] Add validations for valid FSPIOPError Codes
- [x] Update Unit Tests
- [x] Update Integration Tests
- [x] Create follow-up stories for validation --> https://github.com/mojaloop/project/issues/893
- [x] Create follow-up stories to modify SQL queries datetimes on the model layer to use UTC --> https://github.com/mojaloop/project/issues/892

**Acceptance Criteria**:
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] Mojaloop SDK Standard Components has been integrated into the main Mojaloop components to provide a consistent error handler framework:
  - [x] Central-Ledger
- [x] Mojaloop SDK Standard Components produce compliant ML API Specification errors:
  - [x] Central-Ledger

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-error-handling/pull/36
- [x] https://github.com/mojaloop/central-ledger/pull/332

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @gibaros 
- QA/Review: @mdebarros @ndonnan @rmothilal

**Comment by gibaros** [comment]
Pending 1 integration test passing. Working with Miguel, Rajiv and Neal on a fix.

**Comment by elnyry** [comment]
Follow-up QA item #900 .. Closing this now as PR is merged after approvals.
