### ISSUE TITLE
Error Framework - Adopt and Integrate Mojaloop SDK Error Handling Component - Account-Lookup-Service

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#839]
## **Goal**:
As a `Hub Operator`, I want to `implement a standard Error Handling framework` so that `errors are consistent throughout the Mojaloop stack for both the Switch and the FSPs`.

**Tasks**:
- [x] Integrate the [Error Handler](https://github.com/modusbox/mojaloop-sdk-standard-components/blob/master/src/lib/errors/index.js) from the standard components lib into Mojaloop:
  - [x] Account-Lookup-Service
- [x] Remove errors thrown that are not specifically handled (Catch & throw error only if there is prescribed action)
- [x] PR review comments, addressing feedback

**Acceptance Criteria**:
- [x] Unit Tests pass
- ~[ ] Integration Tests pass~
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] Mojaloop SDK Standard Components has been integrated into the main Mojaloop components to provide a consistent error handler framework:
  - [x] Account-Lookup-Service
- [x] Mojaloop SDK Standard Components produce compliant ML API Specification errors:
  - [x] Account-Lookup-Service

## **Pull Requests**:
- [x] https://github.com/mojaloop/account-lookup-service/pull/18

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
