### ISSUE TITLE
Automate the CI pipeline for central-directory

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#84]
**Goal**:
As a developer I would like to automate the CI pipeline for central-directory so that I can shorten the development cycle

**Tasks**:
- [ ] 

**Acceptance Criteria**:
- [x] Automated build artifacts are published to the respective repository for master (release) and develop (snapshot) pushed tags 
- [x] Automated unit tests for PR validations with results made available
- [x] Automated integration tests for PR validations with results made available
- [x] Automated functional tests for PR validations with results made available
- [x] Automated code coverage tests for PR validations with results made available to sonar-qube

**Dependencies**:
- None currently

**Comment by elnyry** [comment]
All tests pass, except functional. This may be dependent on the node upgrade story #97 . Will have to revisit once thats done (or during review of that one). Also, need to discuss issues with cache in CirceCI

**Comment by elnyry** [comment]
Released a v1.1 version for CI/CD and artifacts released to docker-hub here: https://hub.docker.com/r/mojaloop/central-directory/tags/ . For deployment, helm charts need to be updated for all the components which will be taken up as a separate item.
