### ISSUE TITLE
Error Framework: Adopt & Integrate ML SDK Error Handling Component - Quoting-Service - 1

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#840]
## **Goal**:
As a `Hub Operator`, I want to `implement a standard Error Handling framework` so that `errors are consistent throughout the Mojaloop stack for both the Switch and the FSPs`.

**Tasks**:
- [x] Add quote endpoints to test data script and mockserver [ @ndonnan ]
- [ ] ~Integrate the [Error Handler](https://github.com/modusbox/mojaloop-sdk-standard-components/blob/master/src/lib/errors/index.js) from the standard components lib into Mojaloop~: Covered here: https://github.com/mojaloop/project/issues/901
  - [ ] ~quoting-service~ [ @ndonnan ]
- [ ] ~Remove errors thrown that are not specifically handled (Catch & throw error only if there is prescribed action)~ https://github.com/mojaloop/project/issues/901

**Acceptance Criteria**:
Below acceptance criteria will be validated in part-2 of this, here: https://github.com/mojaloop/project/issues/901
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] Mojaloop SDK Standard Components has been integrated into the main Mojaloop components to provide a consistent error handler framework:
  - [ ] Quoting Service
- [ ] Mojaloop SDK Standard Components produce compliant ML API Specification errors:
  - [ ] Quoting Service

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- https://github.com/mojaloop/project/issues/901

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
