### ISSUE TITLE
Event Framework - Update Event Client SDK, Sidecar & existing logging for Async Audit capabilities

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#846]
## **Goal**:
As a `Hub Operator` I want to `integrate Event Framework into Mojaloop components` so that `so that all events (errors, general, etc) can be audited and traced appropriately`

**Tasks**:
- [x] Event Framework
	- [x] Event SDK for Clients  [ ? ]
		- [x] Update to enable "aysnc"-logging for when the audit events are published to the event stream.
	- [x] Event SDK for Server  [ ? ]
		- [x] Update to enable "aysnc"-logging for when the audit events are published to the event stream.
	- [x] Event Sidecar for Server  [ ? ]
		- [x] Update to enable "aysnc"-logging for when the audit events are published to the event stream.
- [x] Existing Logging
	- [x] Updated central-services-logger to use async logging via a file <-- ensure that the transport is configurable and can be changed from a file back to stdout <-- This is needed to ensure that logging is done asynchronously as logging to stdout is sync (example used in last perf work stream: https://github.com/mojaloop/central-services-shared/blob/release/v4.4.0-performance/src/logger.js)
	- [x] Reconfigure docker containers to tail log file (example used in last perf work stream: https://github.com/mojaloop/central-ledger/blob/release/4.4.0-performance/Dockerfile)
        - [x] Apply for:
           - [x] account-lookup-service  [PR]
           - [x] bulk-api-adapter [PR]
           - [x] central-event-processor
           - [x] central-ledger
           - [x] central-settlement [PR]
           - [x] email-notifier
           - [x] ml-api-adapter [PR]
           - [x] quoting-service [PR]
           ~- [ ] mojaloop-simulator~ _Not relevant as it still uses a custom logger_

**Acceptance Criteria**:
- [x] Designs are up-to-date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment configs.
- [ ] Event SDK for clients:
	- [ ] Normal logs via Winston are done so via an "aysnc"-fashion to reduce IO

## **Pull Requests**:
- [x] https://github.com/mojaloop/event-sdk/pull/14
- [x] https://github.com/mojaloop/central-services-logger/pull/7
- [x] https://github.com/mojaloop/central-services-logger/pull/8
- [x] https://github.com/mojaloop/central-services-logger/pull/9
- [x] https://github.com/mojaloop/central-services-logger/pull/10 <-- fixes default output
- [x] https://github.com/mojaloop/email-notifier/pull/84
- [x] https://github.com/mojaloop/central-event-processor/pull/103
- [x] https://github.com/mojaloop/account-lookup-service/pull/167
- [x] https://github.com/mojaloop/quoting-service/pull/100
- [x] https://github.com/mojaloop/central-ledger/pull/497
- [x] https://github.com/mojaloop/ml-api-adapter/pull/285
- [x] https://github.com/mojaloop/bulk-api-adapter/pull/17
- [x] https://github.com/mojaloop/central-settlement/pull/199
- [x] https://github.com/mojaloop/event-sdk/pull/19

- [ ] https://github.com/mojaloop/helm/pull/234 <-- Helm Changes

## **Follow-up**:
- Update the following environment variables in helm:
  - `EVENT_SDK_ASYNC_OVERRIDE_EVENTS` -> A comma-separated list of events that should return immediately instead of waiting for the promises to resolve in the `recorder.record()` function. Any combination of: `'log,audit,trace'` 
  - `CSL_LOG_TRANSPORT`: `'file'` 
  - `CSL_TRANSPORT_FILE_OPTIONS` (optional dict, refer to `central-services-logger` readme)

- Create follow up stories for:
  - Ensuring a fully synchronous flow from publishing an event with the EventSDK client, and said event being received by the EventSDK Server (running in the sidecar) and published on the kafka stream
     - Currently, this uses `Event.emit()`, which is executed asynchronously. 
     - As per discussion with @mdebarros, we essentially want a "stop the world" ability, to make sure that certain events (e.g. audit events) have guarantees that they are published to kafka.

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@mdebarros my first thought for how to implement the async vs sync event sdk is as follows:

If the `async` env variable is true, then don't wait for the `recordMessage()` function to return. For example: 

```js
/* event-sdk: src/span.ts*/
 /**
   * Logs INFO type message.
   * @param message if message is a string, the message is added to a message property of context of an event message.
   * If message is not following the event framework message format, the message is added as it is to the context of an event message.
   * If message follows the event framework message format, only the metadata is updated and if message lacks an UUID it is created. 
   * @param state optional parameter for state. Defaults to 'success'
   */
  async info(message: TypeOfMessage, state?: EventStateMetadata): Promise<any> {
    let { action, type } = new LogEventTypeAction(LogEventAction.info)

    //If ASYNC, then don't wait for this.record message to return
    if (Config.ASYNC) {
      this.recordMessage(message, type, action, state)
      return Promise.resolve(true)
    }

    await this.recordMessage(message, type, action, state)
  }
```

The only issue I can see of the top of my head is the potential for uncaught rejected promises. 

Is this implementation similar to what you were thinking?

**Comment by lewisdaly** [comment]
@mdebarros re. the 2 points above:
>  Updated central-services-logger to use async logging via a file

> Reconfigure docker containers to tail log file

Since we are going to be configuring the dockerfiles as in the example, I think we should make the file log the default option.

My only concern with this is that running these services locally for development will make viewing some of the logs more difficult to view. I guess we can obviously just set this back to using the console log for local development, but it might end up getting annoying.

Do you have any other thoughts on what should be our sensible default options?

**Comment by mdebarros** [comment]
> @mdebarros re. the 2 points above:
> 
> > Updated central-services-logger to use async logging via a file
> 
> > Reconfigure docker containers to tail log file
> 
> Since we are going to be configuring the dockerfiles as in the example, I think we should make the file log the default option.

By this, you mean default in the Docker image, or default when you run the service natively?

> My only concern with this is that running these services locally for development will make viewing some of the logs more difficult to view. I guess we can obviously just set this back to using the console log for local development, but it might end up getting annoying.

If possible, it would be good if we could output to console when running natively (i.e. for local development), and only in the docker image to a file by default.

> 
> Do you have any other thoughts on what should be our sensible default options?

I would say defaults should be based on use-case:
1. Native local (i.e. for development) --> console
2. Docker image --> log file which is redirected to stdout (as per example)

What are your thoughts?

**Comment by lewisdaly** [comment]
@mdebarros, yeah I think console for local logging, and a logfile for the dockerfile sounds like the best option, and should be do-able.

>By this, you mean default in the Docker image, or default when you run the service natively?

Yeah I mean the default for when running inside of docker

**Comment by lewisdaly** [comment]
Waiting on the release of `v8.5.1` of `central-services-logger`, which failed because of npm audit issues.

**Comment by lewisdaly** [comment]
Need to control async vs non async per log level.

**Comment by lewisdaly** [comment]
Currently working on the helm updates to enable this functionality.
