### ISSUE TITLE
Event Framework - Instrument WSO2 to produce Event Traces to event-stream

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#847]
## **Goal**:
As a `Hub Operator` I want to `integrate Event Framework into Mojaloop components` so that `so that all events (errors, general, etc) can be audited and traced appropriately`

**Tasks**:
- [ ] Event Framework
	- [ ] WSO2
		- [ ] Investigate how to instrument WSO2 to produce Event Traces to event-stream.
		- [ ] Implement WSO2 to produce Event Traces to event-stream.
		- [ ] Update Lab deployment to include Kafka in DMZ deployment
		- [ ] Update Lab deployment to include event-stream-processor in DMZ deployment to ingest events into EFK

**Acceptance Criteria**:
- [ ] Designs are up-to-date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment configs.
- [ ] WSO2:
	- [ ] WSO2 is able to produce Event Traces to event-stream that can be ingested and displayed using EFK

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Not in current scope
