### ISSUE TITLE
Move the "transformHeaders" into a shared http library -1

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#848]
## **Goal**:
As a ML OSS Codebase maintainer
I want to _move the "transformHeaders" into a shared http library_
 so that it can be reused in ml-api-adapter, bulk-api-adapter, quoting-service, ALS as relevant

**Tasks**:
- [x] Move the "transformHeaders" into a shared http library
- [x] Create tests
- [x] Create Initial Release
- [ ] ~Update ml-api-adapter~
- [ ] ~Update bulk-api-adapter~
- [ ] ~Update quoting-service~
- [ ] ~Update ALS~

**Acceptance Criteria**:
- [x]  "transformHeaders" functionality is moved into a shared http library
- [ ] ~Bulk-api-adapter, ml-api-adapter are updated to use the above library~
- [ ] ~Unit tests pass (same pass rate as before)~
- [ ] ~Integration tests pass (same pass rate as before)~

## **Pull Requests**:
- [ ] https://github.com/mojaloop/central-services-shared/pull/57 (Followed-up in #871 )

## **Follow-up**:
- [ ] #871 

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
