### ISSUE TITLE
Automate the CI pipeline for central-end-user-registry

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#85]
**Goal**:
As a developer I would like to automate the CI pipeline for central-end-user-registry so that I can shorten the development cycle

**Tasks**:
- [x] Run integration tests successfully locally and on circleci via PR
- [x] Run functional tests successfully locally and on circleci via PR
- [x] Run build complete circleCI2.0 configuration on circleci via PR, verify all steps pass

**Acceptance Criteria**:
- [ ] Automated build artifacts are published to the respective repository for master (release) and develop (snapshot) pushed tags 
- [x] Automated unit tests for PR validations with results made available
- [x] Automated integration tests for PR validations with results made available
- [x] Automated functional tests for PR validations with results made available
- [x] Automated code coverage tests for PR validations with results made available to sonar-qube

**Dependencies**:
- None currently

**Comment by elnyry** [comment]
All tests pass and config is in place for the whole CI/CD pipeline (based on templates that worked for central-ledger and FLS).
