### ISSUE TITLE
Create a Repository Template for a Typescript Project

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#850]
## **Goal**:
As a Developer
I want to create a typescript template project in Github
to enable new mojaloop sub-projects to use Typescript in an easy and consistent manner

This story is related to: https://github.com/mojaloop/design-authority/issues/2

**Tasks**:
- [x] Create a new template project for a Mojaloop Typescript repo using github's new [Repository Templates](https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/) feature. 

**Acceptance Criteria**:
- [x] Project template contains `tsconfig.json` and `package.json` outlined in the above DA issue.
- [x] Project template also contains sample config:
  - [X] CircleCI, 
  - [x] SonarCube
  - [X] Unit Tests 
~- [ ] Integration Tests~ _Outside of scope for now_
~- [ ] Dockerfile(s)~ _Outside of scope for now - not all repos have docker images attached_
  - [x] License file
- [x] Project template contains a Readme describing how to use the template, and a clear method for updating the project template
- [x] Unit Tests pass
~- [ ] Integration Tests pass~ _Outside of scope for now_
- [x] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] https://github.com/mojaloop/template-typescript-public/pull/1

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: TBC
