### ISSUE TITLE
Implement a Contributor License Agreement check to Pull requests to ensure all contributors have signed the CLA

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#851]
## **Goal**:
As a **Project Maintainer**, 
I want to enforce a **Contributor License Agreement (CLA)**
so that **we can ensure the IP of mojaloop contributions are clearly defined.**

**Tasks**:
- [x] Find/track down an appropriate CLA for Mojaloop
- [x] Investigate the best method for signing and ensuring that new contributors have signed the CLA
- [x] Update the documentation for contributing to Mojaloop to include a step for signing the CLA

**Acceptance Criteria**:
- [x] Documentation Style meets standards
- [x] CLA Agreed upon and integrated
- [x] CLA bot applied to the Mojaloop Organization

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: @kjw000

**Comment by kjw000** [comment]
thanks for driving this one.

**Comment by lewisdaly** [comment]
@kjw000 I found a simple tool that can take care of this for us: https://github.com/cla-assistant/cla-assistant

We just need to sign in with github, put the CLA in a gist, and link the cla assistant to a given repo.

Then the process of signing the agreement from a pull request is quite straightforward. Here's some screenshots that show the process.

1. Open a pull request and see that the `license/cla` check is pending:
<img width="696" alt="Screen Shot 2019-07-10 at 2 27 35 pm" src="https://user-images.githubusercontent.com/1683980/60945870-5660aa00-a31f-11e9-9c3b-ef6fc0ff8326.png">


2. Click "Details", and Sign the agreement:
<img width="1349" alt="Screen Shot 2019-07-10 at 2 27 45 pm" src="https://user-images.githubusercontent.com/1683980/60945827-35985480-a31f-11e9-898d-9e480ffb346e.png">


Do we already have an existing CLA that I can use? Or do you need me to also find a CLA that will be suitable for the project?

**Comment by kjw000** [comment]
@lewisdaly - please include Paula Hunter (not sure she is on github) but lets run this by her.  We might have one from the foundation or the entity we can leverage.

**Comment by lewisdaly** [comment]
We are currently waiting for Gates Legal on this one.

**Comment by lewisdaly** [comment]
This is blocked by waiting for the Mojaloop Entity set up.

**Comment by lewisdaly** [comment]
Here's an draft set of documentation for signing and administering the CLA: https://github.com/vessels-tech/documentation/blob/feature/cla-example/contributors-guide/signing-the-cla.md

**Comment by elnyry-sam-k** [comment]
This looks good @lewisdaly; I have a minor question.. Is it required for every PR or once someone signs it for mojaloop, then they're good? Or are there other options with granularity, company, etc..

**Comment by lewisdaly** [comment]
You can either have a _per-organization_ CLA or a _per-repo_ CLA. I think we want it to be _per-organization_, and I'm pretty sure that means that once you sign it for the Mojaloop Github Org, then you are good for any pull request to any repo within the Mojaloop org.

**Comment by elnyry-sam-k** [comment]
Cool, thanks Lewis; that works.

**Comment by kjw000** [comment]
Agree - we want it for the entire organization (not per repo) thanks.

**Comment by lewisdaly** [comment]
Done!
