### ISSUE TITLE
Extend and Integrate ALS and JWS Test Scripts for the Golden path

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#853]
## **Goal**:
As a Tester, I want to integrate all functionality released into Mojaloop into the QA and Regression Test Framework so that we can ensure subsequent new releases do not affect the current stable Mojaloop implementation

**Tasks**:
- [x] Complete and enhance un-committed test scripts residing in private repositories, into Postman Master [ @sri-miriyala ]
- [x] Ensure integration of tests are yielding an "all-green" regression run

**Acceptance Criteria**:
- [x] Postman Master repository contains ALL currently written feature and integration test scripts
- [x] RegressionTests pass

## **Pull Requests**:
- [x] https://github.com/mojaloop/postman/pull/32

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @sri-miriyala 
- QA/Review: @NicoDuvenage

**Comment by elnyry** [comment]
PR - https://github.com/mojaloop/postman/pull/32 now approved and merged, so closing this
