### ISSUE TITLE
Automate the CI pipeline for central-fraud-sharing

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#86]
**Goal**:
As a developer I would like to automate the CI pipeline for central-fraud-sharing so that I can shorten the development cycle

**Tasks**:
- [ ] 

**Acceptance Criteria**:
- [x] Automated build artifacts are published to the respective repository for master (release) and develop (snapshot) pushed tags 
- [x] Automated unit tests for PR validations with results made available
- ~~Automated integration tests for PR validations with results made available~~ (not applicable)
- ~~Automated functional tests for PR validations with results made available~~ (not applicable)
- [x] Automated code coverage tests for PR validations with results made available to sonar-qube

**Dependencies**:
- None currently

**Comment by mdebarros** [comment]
Documentation for CI/CD created via this PR:
https://github.com/mojaloop/docs/pull/9

PR: 
https://github.com/mojaloop/central-fraud-sharing/pull/1

SonarQube:
https://s3-us-west-2.amazonaws.com/elasticbeanstalk-us-west-2-886403637725/sonar/central-fraud-sharing/lcov.info

See Published NPM deployments from CircleCI: 
$ npm view @mojaloop/central-fraud-sharing

Output:
{ name: '@mojaloop/central-fraud-sharing',
  'dist-tags': { snapshot: '1.1.0-snapshot.4', latest: '**1.1.0-snapshot.4**' },
  versions: [ '**1.1.0-snapshot.4**' ],
  time:
   { created: '2018-02-20T13:34:50.204Z',
     '**1.1.0-snapshot.4': '2018-02-20T13:34:50.387Z**',
     modified: '2018-02-20T13:34:50.582Z' },
