### ISSUE TITLE
 Change Instanbul to Nyc for coverage on all projects

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#864]
## **Goal**:
As a developer I want to update all services to use nyc instead of istanbul so that we can have the most recently updated dependencies as nyc now replaces the deprecated istanbul

**Tasks**:
- [x] update `package.json` files for all services to latest nyc (where applicable) version 
- [x] add `.nycrc.yml` files in root with nyc config or make sure that jest/ava is configured similiarly

- [x] Core APIs first
  -  ~central-services-auth~ (**currently uses Istanbul**)(deprecated)
  - [x] central-services-database
  - [x] central-services-error-handling
  - [x] central-services-metrics (**uses nyc, missing .nycrc.yml**) -> https://github.com/mojaloop/central-services-metrics/pull/153
  - [x] central-services-shared
  - [x] central-services-stream
  - [x] central-services-logger
  - [x] central-services-health (**uses nyc, missing .nycrc.yml**) -> https://github.com/mojaloop/central-services-health/pull/245 https://github.com/mojaloop/central-services-health/pull/247
  - [x] central-object-store 
  - [x] ml-number

- [x] Ensure core dependencies are updated befor doing other APIs

- [x] Other APIs
  - ~forensic-logging-sidecar~ (deprecated)
  - ~forensic-logging-sidecar~ (deprecated)
  - [x] quoting-service (**uses jest with nyc exporter,  .nycrc.yml with no code-coverage 90% milestones configured, with jest.config.js with 90% coverage milestones**) -> https://github.com/mojaloop/quoting-service/pull/279
  -  ~simulator~ (no unit tests/coverage exists for this project)
  - [x] account-lookup-service
  - [x] central-event-processor (**currently uses Istanbul**) -> https://github.com/mojaloop/central-event-processor/pull/231 https://github.com/mojaloop/central-event-processor/pull/232
       - [x] __Need story to fix code-coverage__ -> https://github.com/mojaloop/project/issues/2411
  - [x] event-sidecar
  - [x] event-sdk (**uses jest with nyc exporter, missing .nycrc.yml**)
  - [x] central-ledger
  - [x] central-settlement
  - [x] email-notifier (**currently uses Istanbul**) -> https://github.com/mojaloop/email-notifier/pull/191 https://github.com/mojaloop/email-notifier/pull/192
       - [x] __Need story to fix code-coverage__ -> https://github.com/mojaloop/project/issues/2410
  - [x] ml-api-adapter
  - ~pathfinder-provisioning-client~ (deprecated)
  - ~pathfinder-query-client~ (deprecated)
  - [x] event-stream-processr (**currently uses Istanbul**) -> https://github.com/mojaloop/event-stream-processor/pull/49
       - [x] __Need story to fix missing unit tests, code-coverage and CI/CD checks__ -> https://github.com/mojaloop/project/issues/2412
  - [x] als-oracle-pathfinder (**uses ava, with istanbul**) https://github.com/mojaloop/als-oracle-pathfinder/pull/57
       - [x] __Need story to fix missing code-coverage and CI/CD checks__ -> https://github.com/mojaloop/project/issues/2413
  - [x] als-consent-oracle  (**uses jest, with jest.config.js with 90% coverage milestones**)
  - [x] oracle-shared-library
  - [x] sdk-standard-components (**uses jest, with jest.config.js with 90% coverage milestones**)
  - [x] sdk-scheme-adapter (**uses jest, with jest.config.js with 90% coverage milestones**)
  - [x]  transaction-request-service (**uses jest**) 
  -  ~finance-portal-lib~ (**no code coverage tests, being deprecated by finance-portal v2**)
  -  ~finance-portal-ui~  (**no code coverage tests, being deprecated by finance-portal v2**)
  - ~finance-portal-backend-service~ (**uses jest, being deprecated by finance-portal v2**)
  - [x] auth-service (**uses jest, with jest.config.js with 90% coverage milestones**)

**Acceptance Criteria**:
- [x] Code Style & Coverage meets standards

## **Notes**:
Example .nycrc.yml file:
```
temp-directory: "./.nyc_output"
check-coverage: true
per-file: true
lines: 90
statements: 90
functions: 90
branches: 90
all: true
include: [
  "src/**/*.js"
]
reporter: [
  "lcov",
  "text-summary"
]
exclude: [
  "**/node_modules/**"
]
```

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rmothilal 
- QA/Review: @rmothilal @mdebarros @elnyry
