### ISSUE TITLE
Update dependencies to latest stable versions

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#866]
## **Goal**:
As a developer I want to update all dependencies to the latest stable release so that all security, performance and stability updates are included in the OSS code base

**Tasks**:

- [x] Core libraries first
  - [x] central-services-auth
  - [x] central-services-database
  - [x] central-services-error-handling
  - [x] central-services-metrics
  - [x] central-services-shared
  - [x] central-services-stream

- [x] Core services then
  - [x] quoting-service
  - [x] simulator
  - [x] account-lookup-service
  - [x] central-event-processor
  - [x] central-ledger
  - [x] central-settlement
  - [x] email-notifier
  - [x] ml-api-adapter
  - [x] pathfinder-provisioning-client
  - [x] pathfinder-query-client
- [x] Helm (After the above are done)

**Acceptance Criteria**:
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Update helm charts and other deployment config.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rmothilal 
- QA/Review: @rmothilal @mdebarros

**Comment by elnyry** [comment]
A few of the services have open / active PRs so closing this as they're being followed-up now..
