### ISSUE TITLE
Move the "transformHeaders" into a shared http library - 2

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#871]
## **Goal**:
As a ML OSS Codebase maintainer
I want to _reuse the "transformHeaders" functionality from a shared http library_
 so that 'transform headers' functionality can be standardized in ml-api-adapter as relevant

**Tasks**:
- [x] Update ml-api-adapter
- [ ] ~Update bulk-api-adapter~
- [ ] ~Update quoting-service~
- [ ] ~Update central-ledger~
- [ ] ~Update ALS~
- [x] Update/Create tests to ensure coverage is complete
- [x] Continually look for additions to the shared library
- [x] Fix/Complete outstanding TODOs in shared library
- [x] Creating generic function for Kafka lime protocol messages

**Acceptance Criteria**:
- [x] ml-api-adapter is updated to use the above library
- [x] Unit tests pass (same pass rate as before)
- [x] Integration tests pass (same pass rate as before)

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-shared/pull/57
- [x] https://github.com/mojaloop/ml-api-adapter/pull/133

**Dependency**:
- [x] #848 

## **Follow-up**:
- #887 
- #888

## **Accountability**:
- Owner: @rmothilal  
- QA/Review: @rmothilal @mdebarros
