### ISSUE TITLE
Event Framework - Event SDK Client & Server Implementation (part III)

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#873]
## **Goal**:
As a `Hub Operator`, I want to `enhance the Event Framework PoC` so that `all events (errors, general, etc) can be audited and traced appropriately`
​
**Tasks**:
- [x] Refactoring Event SDK
  - [x] Create Interfaces for the following:
    - [x] Tracer Interface provides common methods between Trace and Span objects~ [@vgenev]
    - [x] Trace Interface provides Trace specific operations (to inject Event Recorder for each of the record types i.e. log, trace, audit)  [@vgenev]
    - [x] Span Interface provides Span specific operations for specific log, trace & audit  [@vgenev]
    - [x] Event Recorder interface provides methods for generic log, trace & audit  [@vgenev]
    - [x] Event Trace Context interface [@vgenev]
  - ~~[ ] Implement Interfaces for Tracer~~ After discussion regarding the interfaces, it was decided that Tracer is redundant, thus it will not be implemented.
  - [x] Implement Interfaces for Trace [@vgenev]
  - [x] Implement Interfaces for Span [@vgenev]
  - [x] Implement Interfaces for Event Recorder for gRPC [@vgenev]
  - [x] Implement Interfaces for Event Recorder for Winston Logger [@vgenev]
  - [x] Implement Interfaces for Trace Context (Possibly refactor (if necessary) the current IEventTrace and EventTraceMetadata and rename them to represent a Span and its context) [@vgenev]
  - [x] Create API that exports the currently exposed by the Tracer methods to the end-user, together with the necessary types and interfaces for necessary type checks during API useLogger in [@vgenev]
  - [x] Update Shared Services Logger with new levels [@vgenev]
  - [x] Update gRPC Server definitions (if required) [@vgenev]
  - [x] Testing
    - [x] Test Log events (info, debug, error, etc) on EFK [@vgenev]
    - [x] Test Audit events on EFK [@vgenev]
    - [x] Test Trace events on APM [@vgenev]
- [x] Create story for log levels on the SDK --> https://github.com/mojaloop/project/issues/895
  
**Acceptance Criteria**:
- [x] Classes for Event Recorder, Trace, Span, etc are not overlapping functionally and hold only methods that represent their nature
- [x] End-user API is the same as the current one and the behaviour is as similar as possible to the sample apps is the same
- [x] Designs are up-to-date
- [x] Unit Tests pass
- [ ] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment configs.
​
## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-shared/pull/58
​
## **Follow-up**:
- N/A
​
**Dependencies**:
- N/A
​
## **Accountability**:
- Owner: [@vgenev]
- QA/Review: [@mdebarros]
