### ISSUE TITLE
Event Framework - Event SDK Side-car implementation

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#874]
## **Goal**:
As a `Hub Operator`, I want to `enhance the Event Framework PoC` so that `all events (errors, general, etc) can be audited and traced appropriately`
​
**Tasks**:
- Sidecar:
  - [x] Implement the latest version of SDK (server-side implementation)
  - [x] Publish new version

**Acceptance Criteria**:
- [ ] Sidecar implements the latest Event SDK Server implementation.
- [ ] Sidecar is able to accept Event SDK connections, and API requests from the Event SDK Client implementation.
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards

## **Pull Requests**:
- [ ] TBD
​
## **Follow-up**:
- N/A
​
**Dependencies**:
- [ ] #873 
​
## **Accountability**:
- Owner: TBC
- QA/Review: TBC
