### ISSUE TITLE
Event Framework - Manual Integration & Test Transfers End-to-End

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#875]
## **Goal**:
As a `Hub Operator` I want to `integrate Event Framework into Mojaloop components` so that `so that all events (errors, general, etc) can be audited and traced appropriately`

Priority:
1. update ml and cl with latest sdk from mojaloop/feature branch ~ @ndonnan 
2. complete the fulfil audits, errors and finish ~ @ndonnan 
3. update the simulator with HTTP w3c header handling for PUT callbacks (fulfil/error) ~ valentin
3. test the http prepare & fulfil <-- end-to-end ~ @vgenev & @ndonnan 
4. implement logging on ml-api on the "business flow" ~ @ndonnan 
5. implement logging on cl on the "business flow" ~ @ndonnan 

**Tasks**:
- [x] Review to below to check if sync is working with audits, to ensure they're published]
  - [ ] event-sdk
  - [ ] event-sidecar
- [x] Manual Integration Test-cases
    - [ ] Transfer Prepare
        - [ ] Test Log events (info, debug, error, etc) on EFK
        - [ ] Test Audit events on EFK
        - [ ] Test Trace events on APM
        - [ ] Test error scenarios (states, etc) are being captured correctly events on APM
    - [ ] Transfer Fulfil
        - [ ] Test Log events (info, debug, error, etc) on EFK
        - [ ] Test Audit events on EFK
        - [ ] Test Trace events on APM
        - [ ] Test error scenarios (states, etc) are being captured correctly events on APM
    - [ ] Transfer Prepare & Fulfil (HTTP WC3 Trace Header)
        - [ ] Update simulator for PUT callbacks (fulfil, error) to handle HTTP WC3 Trace Header
        - [ ] Test Log events (info, debug, error, etc) on EFK
        - [ ] Test Audit events on EFK
        - [ ] Test Trace events on APM
        - [ ] Test error scenarios (states, etc) are being captured correctly events on APM
    - [ ] Transfer Timeout
        - [ ] Test Log events (info, debug, error, etc) on EFK
        - [ ] Test Audit events on EFK
        - [ ] Test Trace events on APM
        - [ ] Test error scenarios (states, etc) are being captured correctly events on APM

**Acceptance Criteria**:
- Recording of Events are correctly being captured
    - [ ] Logs events into EFK
    - [ ] Aduit events into EFK
    - [ ] Trace events into APM (and EFK via APM)
- Manual Integration Test-cases
    - [x] Transfer Prepare
        - [ ] Spans are correctly linked and visualised on Kibana
        - [ ] Log events are correctly captured and searchable
        - [ ] Audits events are correctly captured and searchable
        - [ ] Traces events are correctly captured and searchable
    - [x] Transfer Fulfil
        - [ ] Spans are correctly linked and visualised on Kibana
        - [ ] Log events are correctly captured and searchable
        - [ ] Audits events are correctly captured and searchable
        - [ ] Traces events are correctly captured and searchable
    - [ ] Transfer Prepare & Fulfil Successful Commit
        - [ ] Spans are correctly linked and visualised on Kibana
        - [ ] Log events are correctly captured and searchable
        - [ ] Audits events are correctly captured and searchable
        - [ ] Traces events are correctly captured and searchable
    - [ ] Transfer Prepare & Fulfil Abortted Commit
        - [ ] Spans are correctly linked and visualised on Kibana
        - [ ] Log events are correctly captured and searchable
        - [ ] Audits events are correctly captured and searchable
        - [ ] Traces events are correctly captured and searchable
    - [ ] Transfer Prepare Error - Invalid FSP
        - [ ] Spans are correctly linked and visualised on Kibana
        - [ ] Log events are correctly captured and searchable
        - [ ] Audits events are correctly captured and searchable
        - [ ] Traces events are correctly captured and searchable
    - [ ] Transfer Prepare Error - Position Limit Breach
        - [ ] Spans are correctly linked and visualised on Kibana
        - [ ] Log events are correctly captured and searchable
        - [ ] Audits events are correctly captured and searchable
        - [ ] Traces events are correctly captured and searchable
    - [ ] Transfer Prepare Error - Timeout abort
        - [ ] Spans are correctly linked and visualised on Kibana
        - [ ] Log events are correctly captured and searchable
        - [ ] Audits events are correctly captured and searchable
        - [ ] Traces events are correctly captured and searchable

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- [x] https://github.com/mojaloop/project/issues/873
- [x] https://github.com/mojaloop/project/issues/833
- [x] https://github.com/mojaloop/project/issues/834
- [x] https://github.com/mojaloop/project/issues/804
- [x] https://github.com/mojaloop/project/issues/824

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
This story was created to make the end-to-end transfer tracing at message level possible to use for the demonstration at the end-of-phase3 community event and it was done successfully..
