### ISSUE TITLE
Replace ad-hoc message creation with consistent message parsing

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#878]
## **Goal**:
As an `OSS Maintainer` I want to `replace ad-hoc message creation with a factory method` to `ensure consistent and reliable message parsing across all services`

This ticket is a follow up for https://github.com/mojaloop/project/issues/868, wherein some parameters from the notification message were missing, causing downstream errors.

Our tests failed to catch the issue as the mocked messages we were testing against were not consistent with what was in the actual code.

**Tasks**:
- [ ] Determine whether or not such a factory method exists in `central-services-shared` or `central-services-stream` _@rmothilal you might be able to help here_
- [ ] Apply the method to the following projects:
  - [ ] central-ledger
  - [ ] ml-api-adapter
  -  TODO: 

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Looks out of scope now.
