### ISSUE TITLE
Adopt ML Simulator donated - Part1

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#880]
## **Goal**:
As a ML OSS Codebase maintainer
I want to adopt the ML Simulator donated and make changes necessary
so that the Simulator is included as part of ML OSS Space

**Tasks**:
- [x] Review provided codebase for the Simulator [@ggrg]
- [x] Identify changes needed to get running “as-is” [@ggrg]
- [x] Generalize the naming (Replace Casa/Mowali with Mojaloop/OSS relevant) [@ggrg]
- [x] Identify & address content in Docker files that’s Mowali specific
- [x] Run the service - Get it running [@ggrg]
- [x] Document findings and discuss with the team [@ggrg]

**Acceptance Criteria**:
- [x] A report with tasks needed for making public as a first step is published
- [x] A report with steps needed for standardizing this to OSS is drafted
- [x] Stories are created as follow-up to refactor and fill-in the gaps identified in Simulator to follow ML OSS standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/mowali-simulator/pull/1

## **Follow-up**:
- #898 

**Dependencies**:
- [x] The Simulator donated by Mowali is made available to the OSS Core team
- [ ] ~Postman collection for the Simulator is shared with the core team~

## **Accountability**:
- Owner: 
- QA/Review: Core team

## **Notes**:

**Repos**:

**Next steps**
    1. Identify changes needed to get running “as-is”
    2. Generalize the naming (Replace Casa/Mowali with Mojaloop/OSS relevant)
    3. Stuff in Docker files that’s Mowali specific needs to be identified & addressed
    4. Run the service - Get it running
    5. Get it working with ML OSS Helm
    6. Refactor the services to follow OSS Standards ?
