### ISSUE TITLE
Use EFK for a more scalable approach to process and display performance test results

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#881]
## **Goal**:
As a Hub Operator
I want to have a scalable approach for Performance testing and viewing results
so that Performance testing can be done as and when needed and results published.

**Note**: This specific story is directed towards Event Framework related data and doesn't include API Gateway.

**Tasks**:
- [ ] TBD [ @? ]
- [ ] Confirm the feasibility of using EFK for this purpose
- [ ] Identify process to report end-to-end metrics for transfers
- [ ] Identify process to view and publish end-to-end metrics for transfers for analysis with below details
  - [ ] TPS
  - [ ] Min/Max/Avg response times
  - [ ] Median
  - [ ] Aggregated numbers
  - [ ] Transactions taking >1sec [percentile breakdown of response times]
  - [ ] Service level granularity
  - [x] Validate the visualization metrics are generated correctly they aren't
  

**Acceptance Criteria**:
- [ ] First milestone - Mechanism to calculate, report end-to-end metrics for transfers (same as earlier performance effort)
- [ ] Performance testing reports for publishing based on a time interval
  - [ ] TPS some colors 
  - [ ] Min/Max/Avg response times
  - [ ] Median
  - [ ] Aggregated numbers (dial)
  - [ ] Transactions taking >1sec [percentile breakdown of response times] (dial)
  - [ ] Service level granularity
  - [ ] Filter on dashboard by service name
  - [ ] Metalinks between the APM, the Discover and the custom dashboard (from markdown)

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- [ ] Metrics instrumented
- [ ] Event Framework is in place
  - [ ] Events eg: Trace, etc being sent to EFK and indexed (are searchable / can be queried, etc)
- [ ] Test scripts for running performance (for transfers)
- [ ] EFK / Prometheus+Grafana Dashboards as necessary

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
This was considered a feature and not story as such. This is now covered under stories such as #1000 and other stories related to that.
