### ISSUE TITLE
Repurpose the `mojaloop/docs` repo for private documentation

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#882]
## **Goal**:
As a `OSS Maintainer` I want to `make the *mojaloop/docs* repo a suitable place to store private documentation` to `aid the management of the project`.

**Tasks**:
- [ ] Update the repo description
- [ ] Remove outdated docs and docs that are already covered in the `mojaloop/documentation` repo
- [ ] Restructure the repo as needed with a new folder structure, and readme

**Acceptance Criteria**:
- [ ] Documentation conforms to style guide

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by millerabel** [comment]
I suggest *mojaloop/doceditor* repo, making it clear that editors of the documentation use the repo for that purpose.

And the repo should be public, as all other repos that are part of the project. We can use the GitHub permission system to decide who can add, edit, and remove documents within the *doceditor* repo. 

— Miller

On Jul 29, 2019, at 3:19 AM, Lewis Daly <notifications@github.com> wrote:

Goal:

As a OSS Maintainer I want to make the *mojaloop/docs* repo a suitable place to store private documentation to aid the management of the project.

Tasks:

 Update the repo description
 Remove outdated docs and docs that are already covered in the mojaloop/documentation repo
 Restructure the repo as needed with a new folder structure, and readme
Acceptance Criteria:

 Documentation conforms to style guide
Pull Requests:

 TBD
Follow-up:

N/A
Dependencies:

N/A
Accountability:

Owner: TBC
QA/Review: TBC
