### ISSUE TITLE
Include newly commissioned services in the local deployment documentation.

### ISSUE THREAD

**Issue by HenkKodde** [mojaloop/project#885]
## **Goal**:
As a community member I want to insure all deployed/released services are included in the local/hosts file so that setup and access on a local environment is a true reflection of functionality provided to the community.

**Tasks**:
- [x] Include new services in the local/hosts file. [ @HenkKodde  ]
  - [x] email-notifier [ @HenkKodde  ]
  - [x] account-lookup-service [ @HenkKodde  ]
  - [x] quoting-service [ @HenkKodde  ]
  - [x] moja-simulator [ @HenkKodde  ]

**Acceptance Criteria**:
- [x] Verify on local environment.

## **Pull Requests**:
- [x] https://github.com/mojaloop/documentation/pull/101

## **Follow-up**:
- Depreciated services were left for community members that might be running on older versions. Clarification will be required from the OSS team at what point (release) the specified services was depreciated and noted as such in the deployment guides to provide the appropriate guidelines to the community going forward.

**Dependencies**:
- N/A

## **Accountability**:
- Owner: Henk Kodde
- QA/Review:

**Comment by HenkKodde** [comment]
having issues with CircleCI. Moved back until resolved.

**Comment by HenkKodde** [comment]
Have tested this on my local environment as per the guidelines in .gitbook.md. Everything works fine and able to view the updated content on my local browser without and issues.

info: >> generation finished with success in 148.1s !

Starting server ...
Serving book on http://localhost:8989

Will need some assistance in resolving the circleCI error.

**Comment by HenkKodde** [comment]
Ready to be reviewed.

**Comment by HenkKodde** [comment]
Not able to merge into master. Will need to be done by someone with the appropriate authorization.

Have the below that prevents me from actioning the merger for this PR:
```The base branch restricts merging to authorized users.```
```You’re not authorized to merge this pull request.```
