### ISSUE TITLE
Use "transformHeaders" from the shared http library in central-ledger - 3

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#887]
## **Goal**:
As a ML OSS Codebase maintainer
I want to _reuse the "transformHeaders" functionality from a shared http library_
 so that 'transform headers' functionality can be standardized in central-ledger services 

**Tasks**:
- [ ] ~Update central-ledger~ (Now in #939 )
- [x] Update central-services-shared library
- [x] Update/Create tests to ensure coverage is complete

**Acceptance Criteria**:
- [ ] ~central-ledger is updated to use the above library~ (Now in #939 )
- [x] New version of central-services-shared released
- [x] Unit tests pass (same pass rate as before)
- [x] Integration tests pass (same pass rate as before)

## **Pull Requests**:
- [ ] TBD

**Dependency**:
- [x]  #871

## **Follow-up**:
- N/A

## **Accountability**:
- Owner: 
- QA/Review: @rmothilal @mdebarros
