### ISSUE TITLE
Use "transformHeaders" from the shared http library in central services - 4

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#888]
## **Goal**:
As a ML OSS Codebase maintainer
I want to _reuse the "transformHeaders" functionality from a shared http library_
 so that 'transform headers' functionality can be standardized in bulk-api-adapter, quoting-service and transaction-requests-service

**Tasks**:
- [x] Update quoting-service
- [x] Update transaction-requests-service
- [x] Update/Create tests to ensure coverage is maintained

**Acceptance Criteria**:
- [x] quoting-service is updated to use the above library
  - [x] Unit tests pass (same pass rate as before)
  - [x] Integration tests pass (same pass rate as before)
- [x] transaction-requests-service is updated to use the above library
  - [x] Unit tests pass (same pass rate as before)
  - [x] Integration tests pass (same pass rate as before)

## **Pull Requests**:
- [x] https://github.com/mojaloop/transaction-requests-service/pull/3
- [x] https://github.com/mojaloop/quoting-service/pull/19

**Dependency**:
- [x] #887 

## **Follow-up**:
- New task to be created to complete work for the bulk-api-adapter

## **Accountability**:
- Owner: 
- QA/Review: @rmothilal @mdebarros

**Comment by gibaros** [comment]
PRs mojaloop/transaction-requests-service#3 and mojaloop/quoting-service#19 were merged and a new Issue for bulk-api-adapter will be created, closing this issue.
