### ISSUE TITLE
QA: Automation to validate passing of fees information through the Switch

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#889]
## **Goal**:
As a maintainer of ML OSS codebase
I want to have QA automation scripts (postman) that validate 'passing of fees information through a Mojaloop Switch'
so that _these scripts can be used for testing, validating a given Mojaloop codebase_

**Tasks**:
- [x] Postman scripts for validating 'fees usage' through the Mojaloop Switch
- [x] PR - https://github.com/mojaloop/postman/pull/32
- [x] Validate locally / on an available environment

**Acceptance Criteria**:
- [x] Postman scripts that validate the 'passing / relaying of fees information' through the Mojaloop Switch as supported by the Mojaloop FSPIOP API are tested and made available on the public 'postman' repo

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @NicoDuvenage @elnyry

**Comment by sri-miriyala** [comment]
@elnyry  could you pls link the DEV story for this?

**Comment by elnyry** [comment]
@sri-miriyala thats not applicable for this.. there no additional Dev needed on this one, based on earlier conversations..

**Comment by sri-miriyala** [comment]
@elnyry  I'm already sending fees and commission from payeefsp in the happy path itself. But Tests included in the Happy path POST /quotes itself.
<img width="1167" alt="Screen Shot 2019-08-19 at 7 41 17 PM" src="https://user-images.githubusercontent.com/38143240/63306920-85712080-c2ba-11e9-98fd-441bfec6d5f1.png">
<img width="1236" alt="Screen Shot 2019-08-19 at 7 48 42 PM" src="https://user-images.githubusercontent.com/38143240/63306926-8a35d480-c2ba-11e9-92ce-be83df26a997.png">

**Comment by elnyry** [comment]
@sri-miriyala Thanks for the update Sri. Are these included in https://github.com/mojaloop/postman/pull/26 , if not, can you please raise a new PR that would make it easier to test and merge.

Thanks!

**Comment by elnyry** [comment]
PR - https://github.com/mojaloop/postman/pull/32 now validated and merged
