### ISSUE TITLE
Automate the CI pipeline for forensic-logging-sidecar

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#89]
**Goal**:
As a developer I would like to automate the CI pipeline for forensic-logging-sidecar so that I can shorten the development cycle

**Tasks**:
- [x] Migrate CircleCI v1 to CircleCI v2
- [x] Create CircleCI v2 parallel job for Unit Testing
- [x] Create CircleCI v2 parallel job for Integration Testing
- ~~Create CircleCI v2 parallel job for Functional Testing~~ *(not applicable)*
- [x] Create CircleCI v2 parallel job for Code Coverage Testing
- [x] Automate the upload of Code Coverage results to SonarQube
- [x] Publish build snapshot artefacts to Docker Hub if all tests are successful if there is a tag push to the development branch
- [x] Publish build release artefacts to Docker Hub if all tests are successful if there is a tag push to the master branch

**Acceptance Criteria**:
- [x] Automated build artifacts are published to the respective repository for master (release) and develop (snapshot) pushed tags 
- [x] Automated unit tests for PR validations with results made available
- [x] Automated integration tests for PR validations with results made available
- ~~Automated functional tests for PR validations with results made available~~ *(not applicable)*
- [x] Automated code coverage tests for PR validations with results made available to sonar-qube

**Dependencies**:
- None currently

**Comment by mdebarros** [comment]
PR:

Working CI/CD Pipeline: https://circleci.com/workflow-run/e2c8be87-33df-4344-826d-0dfe82c98f27

Note that there are no Functional tests implemented for this repository. We will need stories to implement them as required. Once that has been done I can re-configure the CI to execute them.

**Comment by mdebarros** [comment]
@NicoDuvenage, @elnyry: I have created place holder issues for the lack of Integration and Functional tests which has been added to the backlog:
- https://github.com/mojaloop/forensic-logging-sidecar/issues/7

**Comment by mdebarros** [comment]
Demo: https://drive.google.com/file/d/1T-i2NAK6uBqbAP1EM6j_Gonsh_kaot2f/view?usp=sharing
