### ISSUE TITLE
QA: Automation to validate handling of multiple currencies in Settlements

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#890]
## **Goal**:
As a maintainer of ML OSS codebase
I want to have QA automation scripts (postman) that validate 'handling of multiple currencies in Settlements on a Mojaloop Switch'
so that _these scripts can be used for testing, validating use cases where multiple currencies are present in a Settlement_

**Tasks**:
- [x] Postman scripts for validating the Switch behavior when multiple currencies are present in a Settlement
- [x] Validate locally / on an available environment
- [x] PR

**Acceptance Criteria**:
- [x] Postman scripts that validate the 'handling of multiple currencies in Settlements on a Mojaloop Switch' as supported by the Mojaloop Settlements API are tested and made available on the public 'postman' repo

## **Pull Requests**:
- [x] https://github.com/mojaloop/postman/pull/40

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @NicoDuvenage @elnyry

**Comment by elnyry** [comment]
We now have this available (as part of OSS API test collection), so closing this
