### ISSUE TITLE
QA: Refactor QA Automation scripts that validate duplicate handling of requests 

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#891]
## **Goal**:
As a maintainer of ML OSS codebase
I want to refactor the QA automation scripts (postman) that validate 'duplicate handling of requests on a Mojaloop Switch'
so that _these scripts can be used for testing the refactored implementation that uses the newly standardized design / structure for handling duplicate requests_

**Tasks**:
- [x] Refactor postman scripts for validating the Switch's handling of duplicate requests
- [x] Validate locally / on an available environment
- [ ] PR

**Acceptance Criteria**:
- [x] Postman scripts that validate the 'Switch's handling of duplicate requests' as supported by the Mojaloop FSPIOP API are refactored to reflect the newly standardized design

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @NicoDuvenage @elnyry

**Comment by elnyry** [comment]
Not much refactoring was needed after the duplicate checking enhancements in v7.4.3
