### ISSUE TITLE
Enable MySQL driver timezone to be UTC

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#892]
## **Goal**:
As a `Hub Operator`, I want to `set MySQL timezone on the driver connection` so that `all date, timestamps, and datetimes are stored in UTC`

**Tasks**:
- [ ] Apply connection string updates to Central-Ledger (ref: https://github.com/mysqljs/mysql#connection-options) to set timezone option as UTC.
- [ ] Test connection-option for the timezone to ensure that it's being set and configured appropriately.
- [ ] Update Helm scripts to also set the connection-options for UTC
- [ ] Publish new version of Central-Ledger
- [ ] Publish new version of Helm scripts

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] All date, timestamps, and datetimes are stored in UTC in the Database as auto-configured by the MySQL driver.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
