### ISSUE TITLE
Event Framework to support config of Levels & real-time trace config

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#895]
## **Goal**:
As a `Hub Operator`, I want to `enhance Event Framework to support recorder levels` so that `the operator can select what events should be recorderd`.

**Tasks**:
- [ ] Enhance Event SDK to support configuring recorder levels on the client and server:
    - [ ] Implement recorder level config on instrumented components (i.e. Central-Ledger, ML-API) 
    - [ ] Implement recorder level support on sidecar
    - [ ] Update helm charts to support recorder level configs
- Real-time Trace Config Support:
    - [ ] API to enable/disable tracing (disable sidecar recorder, or enable local logging, etc) <-- this could be done via a rest API on the sidecar which could communicate to the host service via the gRPC api. <-- to be clarified through a design discussion <-- this would ensure that tracing can be disabled and enabled (i.e. disabled if there is a performance overhead).
    - [ ] Update helm charts to support real-time config API/mechanism

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] Event Framework (SDK, Client, Server & Sidecar) all support configuring the recorder levels as required (i.e. set to `info` level, no `debug` log entries are recorded, etc)
- [ ] Helm scripts are updated to support the new recorder level configs
- [ ] Helm scripts are updated to support real-time config for tracing
- [ ] EventSDK client updated to provide a mechanism to support real-time Trace config either (e.g. HTTP API, or via Sidecar mechanism to update client)

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
