### ISSUE TITLE
Adopt ML Simulator donated - Part2

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#898]
## **Goal**:
As a ML OSS Codebase maintainer
I want to adopt the ML Simulator donated and make changes necessary
so that the Simulator is included as part of ML OSS Space

**Tasks**:
- [x] Setup Github repo for public release
- [x] Validate the deployment with Postman scripts donated by Mowali [Dependency]
- [ ] ~Include as part of the Switch deployment [or outside if so decided]~
- [ ] Provide setup to run end-to-end Testing on deployments to check for any issues, log bugs
- [x] Record tasks to be taken-up to refactor Simulator to follow ML OSS standards
- [x] Setup initial CI [@lewisdaly to take this on]
   - [x] Add .circleci dir + configs
   - [x] Add dockerfiles
   - [x] Create Simulator on s3 bucket for sonar reports

**Acceptance Criteria**:
- [x] Unit Tests pass
- [x] Postman collection for the Simulator is shared with the core team
  - [x] Simulator deployed is validated using the postman scripts donated [dependency]
- [x] Continuous Integration is setup
- [x] Stories are created as follow-up to refactor and fill-in the gaps identified in Simulator to follow ML OSS standards

## **Pull Requests**:
- [x] https://github.com/mojaloop/mojaloop-simulator/pull/9
- [x] https://github.com/mojaloop/license-scanner/pull/8 Changes for the license scanner to support the mojaloop-simulator docker folder structure, and general improvements.
- [x] https://github.com/mojaloop/mojaloop-simulator/pull/4 - Adds CI/CD to mojaloop-simulator
- [x] https://github.com/mojaloop/mojaloop-simulator/pull/9 - Removes deploy section

## **Follow-up**:
- [ ] Functional + Integration tests: https://github.com/mojaloop/project/issues/983
- [ ] Nested package.json files: https://github.com/mojaloop/project/issues/984

**Dependencies**:
- [x] Postman scripts specific to the Mowali Simulator are donated

## **Accountability**:
- Owner: 
- QA/Review: Core team

## **Notes**:

**Repos**:

**Next steps**
    1. Stuff in Docker files that’s Mowali specific needs to be identified & addressed
    2. Run the service - Get it running
    3. CI
    4. Get it working with ML OSS Helm
    5. Refactor the services to follow OSS Standards ?

**Comment by lewisdaly** [comment]
Hi all, this is up for discussion, but I would like to make a few changes to the directory structure of this project, namely:
- move the package.json to the root of the project: This makes docker layer caching much easier, as we can install packages separately from copying the `src` directory over
- Move the `test` directory into its own place at the project root: This makes it easier to build a 'production' docker image that doesn't contain the test files

Additionally, these changes bring it more into line with the other projects, which will make working on this repo easier in general. 

Please let me know what you think!

**Comment by lewisdaly** [comment]
Another thing that would be nice to change, to ensure consistency across projects is the tab width. Currently it is 4 spaces, but I think we should change it to 2 spaces to be consistent with the other projects.

**Comment by elnyry** [comment]
@lewisdaly thanks for this. Can you please raise a PR with the 4 changes that you summarized here, in the description  of the PR and add James Bush (bushjames) and Murthy (ksatya77 ) to the PR along with the usual reviewers to get their opinion.

**Comment by lewisdaly** [comment]
For the "Create Simulator on s3 bucket for sonar reports" task, I think this should just happen automatically since the artifacts for sonar are uploaded to a "sub-folder" on the s3 bucket.

I don't however have access to sonar or the s3 bucket, so someone else will have to verify this for me once I'm done with the CI (or give me permission 😉).

**Comment by elnyry** [comment]
Hi Lewis, I created one for mojaloop-simulator, so we should be good. (I don't think the CI task has access to create a folder automatically, so we should be good now; It looks for a folder with the name of the repo and pushes the lcov.info file)

**Comment by lewisdaly** [comment]
@elnyry what's the plan for "Include as part of the Switch deployment". Last I heard, the plan is to keep separate for now.

Do we want to have working helm charts for this anyway so it can be spun up easily alongside a deployment? Or is that something outside the scope of this ticket?

**Comment by elnyry** [comment]
@lewisdaly I think we need to strike that task off, as this sill be stand alone, it was a more generic statement applicable to services that are usually part of the Switch..

Of course, we need helm charts, but lets have a separate story for that.

**Comment by lewisdaly** [comment]
CI PR is merged, but I'm now having issues with a snapshot deployment: https://circleci.com/gh/mojaloop/mojaloop-simulator/307#build-parameters/containers/0

I'll try and debug this and hopefully at least get a snapshot deployment done before the convening.

**Comment by lewisdaly** [comment]
Looks like @dfry fixed this for me - thanks! I'm going to disable the `deploy` section for now, since there is no current deployment of this on helm. We can re enable it later on.

**Comment by lewisdaly** [comment]
@elnyry added follow up items.

**Comment by elnyry** [comment]
Thanks @lewisdaly .. looking good now..
