### ISSUE TITLE
Automate the CI pipeline for forensic-logging-sidecar-client

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#90]
**Goal**:
As a developer I would like to automate the CI pipeline for forensic-logging-sidecar-client so that I can shorten the development cycle

**Tasks**:
- [ ] 

**Acceptance Criteria**:
- [x] Automated build artifacts are published to the respective repository for master (release) and develop (snapshot) pushed tags 
- [x] Automated unit tests for PR validations with results made available
- [x] Automated integration tests for PR validations with results made available
- [x] Automated functional tests for PR validations with results made available
- [x] Automated code coverage tests for PR validations with results made available to sonar-qube

**Dependencies**:
- None currently

**Comment by mdebarros** [comment]
Documentation for CI/CD created via this PR:
https://github.com/mojaloop/docs/pull/9

PR: 
https://github.com/mojaloop/forensic-logging-client/pull/9

SonarQube:
?
