### ISSUE TITLE
QA: Validate error codes from central-ledger, ml-api-adapter based on updates done in #838, #830

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#900]
## **Goal**:
As a maintainer of ML OSS codebase
I want to perform QA and refactor the QA automation scripts if necessary (postman) that validate 'error codes used by central-services on a Mojaloop Switch'
so that _these scripts can be used for testing the refactored implementation that uses the newly standardized Error Framework_ and the Error Framework itself can be validated and refined.

**Tasks**:
- [x] Use postman scripts for validating the error codes generated by the Switch services
- [x] Refactor postman scripts if necessary based on above QA
- [x] Record Observations from test results

**Acceptance Criteria**:
- [x] Updates for Error Framework done on central services (central-ledger, ml-api-adapter) are verified using QA Framework and observations noted.
- [x] Postman scripts that validate the 'error codes' as supported by the Mojaloop FSPIOP API are refactored to reflect the newly standardized design

## **Pull Requests**:
- [ ] https://github.com/mojaloop/postman/pull/28

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @NicoDuvenage @elnyry

**Comment by elnyry** [comment]
Some of this if not all is covered by #750 , will keep reviewing..
