### ISSUE TITLE
Error Framework: Adopt & Integrate ML SDK Error Handling Component - Quoting-Service - 2

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#901]
## **Goal**:
As a `Hub Operator`, I want to `Integrate the standard Error Handling framework to the quoting-service` so that `errors are consistent throughout the Mojaloop stack for both the Switch and the FSPs`.

**Tasks**:
- [x] Integrate the [Error Handler](https://github.com/modusbox/mojaloop-sdk-standard-components/blob/master/src/lib/errors/index.js) from the standard components lib into Mojaloop:
  - [x] quoting-service [ @ndonnan ]
  - [x] Release after PR is merged [ @ndonnan ]
- [x] Remove errors thrown that are not specifically handled (Catch & throw error only if there is prescribed action)

**Acceptance Criteria**:
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] Mojaloop SDK Standard Components has been integrated into the main Mojaloop components to provide a consistent error handler framework:
  - [ ] Quoting Service
- [ ] Mojaloop SDK Standard Components produce compliant ML API Specification errors:
  - [ ] Quoting Service

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
