### ISSUE TITLE
Move the "transformHeaders" into a shared http library - 3 [ALS]

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#902]
## **Goal**:
As a ML OSS Codebase maintainer
I want to _reuse the "transformHeaders" functionality from a shared http library_
 so that 'transform headers' functionality can be standardized in ALS as relevant

**Tasks**:
- [x] Update ALS
- [x] Continually look for additions to the shared library
- [x] Fix/Complete outstanding TODOs in shared library
- [x] Creating generic function for Kafka lime protocol messages

**Acceptance Criteria**:
- [x] ALS is updated to use the above library
- [x] Unit tests pass (same pass rate as before)
- [ ] Integration tests pass (same pass rate as before)

## **Pull Requests**:
- TBD

**Dependency**:
- [x] #848 

## **Follow-up**:
- N/A

## **Accountability**:
- Owner: @rmothilal  
- QA/Review: @rmothilal @mdebarros
