### ISSUE TITLE
Simulator response doesn't contain body to validate payerfsp related fields in 7.1 (not released) deployments

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#903]
**Summary**:
Simulator response doesn't contain body to validate _payerfsp_ related fields in 7.1 (not released) deployments (on AWS). This is needed as the postman scripts for P2P and Golden path use this response from the simulator to validate the Golden path tests and currently because of this, it is failing. 

The payee side call - GET http://xxxx-simulator.mojaloop.live/payeefsp/requests/a404fda9-eb4c-4a41-8fd8-29855fb86d7f is working fine, its sending a message body in response that’s used in the tests). However, the payer side call **/callbacks/** is responding with an empty body (and in the logs showing as CACHE: [undefined].

**Severity**:
High

**Priority**:
Medium (if issue in simulator, if root-cause found to be in central-services, Critical)

**Expected Behavior**:
1. GET call on the end-point /payerfsp/callbacks/<id> on the simulator responds with a message body that contains the details of the callback sent for a particular ID, which is then used in the postman scripts for validation.

**Steps to Reproduce**
  1. GET call on the end-point /payerfsp/callbacks/<id> on the simulator (v7.2.1) is responding with an empty message body, which is causing the tests to fail.
  2.
  3.

**Specifications**
  - Component (if known): Simulator version
  - Version:  v7.2.1 (simulator. Helm uses an un-released 7.1.x internal version)
  - Platform: AWS dev2 envt
  - Subsystem: Simulator
  - Type of testing: Golden Path postman scripts (Functional)
  - Bug found/raised by: @elnyry 

**Tasks**:
- [x] Reproduce issue
- [x] Root cause analysis
- [x] Identify fixes needed
- [x] Implement Fix
  - [x] PR: https://github.com/mojaloop/postman/pull/27
- [x] Validate fix

**Notes**:

- Severity when opened:
- Priority when opened:

On the simulator v7.2.1, here's the log:
```
2019-08-02T08:47:17.212Z - info: L1p-Trace-Id=undefined - Method: get Path: /payerfsp/callbacks/a404fda9-eb4c-4a41-8fd8-29855fb86d7f Query: {}

8/2/2019 2:17:17 PM 2019-08-02T08:47:17.213Z - info: L1p-Trace-Id=undefined - Headers: {"host":"xxxx-simulator.mojaloop.live","connection":"close","x-request-id":"623cc75ff87754e3eca3a049ea457f46","x-real-ip":"10.1.2.119","x-forwarded-for":"10.1.2.119","x-forwarded-host":"xxxx-simulator.mojaloop.live","x-forwarded-port":"80","x-forwarded-proto":"http","x-original-uri":"/payerfsp/callbacks/a404fda9-eb4c-4a41-8fd8-29855fb86d7f","x-scheme":"http","user-agent":"PostmanRuntime/7.15.2","accept":"*/*","cache-control":"no-cache","postman-token":"a7c311db-fd1a-49e2-8e86-e62846036c88","accept-encoding":"gzip, deflate"}

8/2/2019 2:17:17 PM 2019-08-02T08:47:17.213Z - info: IN PAYERFSP:: PUT /payerfsp/callbacks/a404fda9-eb4c-4a41-8fd8-29855fb86d7f, CACHE: [undefined]
```

**Comment by mdebarros** [comment]
The issue was being caused due to bad data being inserted as part of the `FSP Onboarding` process on the `OSS-New-Deployment-FSP-Setup` collection.

The PUT call back URIs for transfers were configured as follows:
```
[
    {
        "type": "FSPIOP_CALLBACK_URL_TRANSFER_PUT",
        "value": "http://dev2-simulator.mojaloop.live/payerfsp/transfers/6b24a393-cdf5-4be1-9057-e4a8cf49a34a"
    },
    {
        "type": "FSPIOP_CALLBACK_URL_TRANSFER_ERROR",
        "value": "http://dev2-simulator.mojaloop.live/payerfsp/transfers/6b24a393-cdf5-4be1-9057-e4a8cf49a34a/error"
    }
]
```

All PUT call-backs would be sent to the incorrect transfer-id as a result of the configuration being hardcoded to `6b24a393-cdf5-4be1-9057-e4a8cf49a34a`.

The correct configuration should look as follows:
```
[
    {
        "type": "FSPIOP_CALLBACK_URL_TRANSFER_PUT",
        "value": "http://dev2-simulator.mojaloop.live/payerfsp/transfers/{{transferId}}"
    },
    {
        "type": "FSPIOP_CALLBACK_URL_TRANSFER_ERROR",
        "value": "http://dev2-simulator.mojaloop.live/payerfsp/transfers/{{transferId}}/error"
    }
]
```

The reason for this is due to the Postman environment containing a variables called `transferId` which contains the values `6b24a393-cdf5-4be1-9057-e4a8cf49a34a`. When running the `FSP Onboarding` process, the request is not used verbatim but instead replaces the template placeholder with the value since both Postman and Mustache (Mojaloop's template parsing engine) use the same syntax.

Fixes: 
- ensure that there is no variable within your Postman environment that matches the template name of `transferId`. <-- immediate fix.
- modify postman scripts to escape the template so that it WILL not think that it should replace the template placeholder with a value of such a variable exists. <-- long-term solution to ensure that it does not happen again.

**Comment by mdebarros** [comment]
Found 3rd solution:
Add `Pre-request script` to unset the variables as follows:

```
pm.environment.unset('transferId')
```

That will ensure that there is no variable set in the environment that can impact the Postman test.

**Comment by mdebarros** [comment]
Added the following `Pre-request script` to the `FSP Onboarding` folder:

```
// Ensure that the following variables are not set in the environment
// This is a fix for the following issue: https://github.com/mojaloop/project/issues/903
// This will ensure that templates are not replaced in the endpoint configs:
pm.environment.unset('partyIdType')
pm.environment.unset('partyIdentifier')
pm.environment.unset('requestId')
pm.environment.unset('transferId')
```

See the following PR: https://github.com/mojaloop/postman/pull/27
