### ISSUE TITLE
Refactoring for duplicate checking on 'prepare transfers' & 'fulfil transfer'  - part2

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#904]
## **Goal**:
As a Mojaloop Hub
I want to handle duplicate 'Prepare' and 'Fulfil requests' in a standardized way
so that the process can be definitive and re-usable

**Tasks**:
- [x] Apply changes introduced during Sprint 7.2 (#780) on top of Error Handling Framework changes to central-ledger's master branch (current [working branch](https://github.com/ggrg/central-ledger/tree/feature/904RequestDuplicateCheck)) [@ggrg]
- [x] Provide full knex script for DDL changes and data migration [@ggrg] [d39a179](https://github.com/ggrg/central-ledger/commit/d39a179)
- [x] Change codebase to work with the introduced DB schema changes [@ggrg]
- [x] Fix Unit & Integration tests according the DB schema changes [@ggrg] [739717e](https://github.com/ggrg/central-ledger/commit/739717e)
- [x] Attempt to incorporate changes for #703 [@ggrg]
- [x] Resolve execution issues with migration scripts [@ggrg]
- [x] Separate DDL and data migration scripts [@ggrg]
- [x] Execute data migration script in a transaction and according to a config [@ggrg]
- [x] Implement Request Duplicate Check for transfer fulfils [@ggrg]
- [x] Implement Request Duplicate Check for transfer REJECTs and ERRORs during fulfil [@ggrg]
  - [x] Addition migration scripts for changes in transferError related tables [@ggrg]
- [x] Fix integration tests to work with current implementation of fulfil, abort and reject [@ggrg]
- [x] Test data migration script on sample data and provide notes on its usage [@ggrg]
- [x] Fix existing unit tests [@ggrg]
- [x] Apply PR suggested code restructuring for central-services-shared [@ggrg]
- [x] Add unit tests to achieve full code coverage [@ggrg]
  - [x] central-services-shared [@ggrg]
  - [x] central-ledger [@ggrg]
- [x] 'Prepare-Transfer' Refactor implementation to reflect the changes in design [@ggrg]
  - [x] Resolve issue with Generic Validation Error send & resend [@ggrg]
  - [x] Add unit tests to achieve full tests coverage [@ggrg]
- [x] 'Fulfil Transfer': Refactor implementation to reflect the changes in design [@ggrg]
  - [x] Resolve issue with Generic Validation Error send & resend [@ggrg]
  - [x] Add unit tests to achieve full tests coverage [@ggrg]
- [x] Upgrade all dependencies [@ggrg]
- [x] Address new issues with changed standard.JS [@ggrg]
- [ ] ~Add validations on the Message Create functions to extensionList Object to limit length of 'Value' fields to 128 and 'key' fields to 32~
- [x] Verify proper function of Reconciliation Transfers (Funds In/Funds Out) [@ggrg]
- [x] Verify proper function of Settlement Transfers [@ggrg]
  - [x] Update central-settlement transferFulfilmentDuplicate(Check) facade inserts [@ggrg]
- [x] Update documentation with the updated DB design [@ggrg]

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] Duplicate handling on transfer 'fulfil requests' is standardized and definitive
- [x] Duplicate handling on transfer 'prepare requests' is standardized and definitive
- [x] Aligned with [DA decision](https://github.com/mojaloop/design-authority/issues/29)
  - [ ] ~DA Suggestion ([link](https://github.com/mojaloop/project/issues/780#issuecomment-519433883)) to be addressed~
- [x] central-ledger codebase aligned to the design

## **Pull Requests**:
_Pull requests need to be merged in order for the following PRs on the list to execute CI successfully_
- [x] https://github.com/mojaloop/central-services-shared/pull/76
- [x] https://github.com/mojaloop/central-services-shared/pull/77
- [x] https://github.com/mojaloop/documentation/pull/105
- [x] https://github.com/mojaloop/central-ledger/pull/356
- [x] https://github.com/mojaloop/central-settlement/pull/96

## **Follow-up**:
- [ ] https://github.com/mojaloop/project/issues/703 ([more info](https://github.com/ggrg/central-ledger/blob/feature/904RequestDuplicateCheck/src/handlers/transfers/handler.js#L291))
- [ ] [DA Suggestion](https://github.com/mojaloop/project/issues/780#issuecomment-519433883)

**Dependencies**:
- [x] Implementation specific Request Duplicate Check issues - https://github.com/mojaloop/design-authority/issues/33

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by ggrg** [comment]
**Related links**:
https://github.com/mojaloop/project/issues/780#issuecomment-515924318
https://github.com/mojaloop/project/issues/781#issuecomment-515945618
https://github.com/mojaloop/design-authority/issues/33

**Comment by elnyry** [comment]
Blocked due to Georgi's availability (Away sick)

**Comment by ggrg** [comment]
Tests coverage after feature implementation and unit tests fix, before introducing new tests:
```
=============================== Coverage summary ===============================
Statements   : 98.31% ( 3136/3190 )
Branches     : 97.47% ( 770/790 )
Functions    : 98.6% ( 422/428 )
Lines        : 98.29% ( 3100/3154 )
================================================================================

1..1239
# tests 1239
# pass  1239

# ok
```

**Comment by ggrg** [comment]
```
=============================== Coverage summary ===============================
Statements   : 100% ( 3184/3184 )
Branches     : 99.75% ( 784/786 )
Functions    : 100% ( 427/427 )
Lines        : 100% ( 3148/3148 )
================================================================================

1..1253
# tests 1253
# pass  1253

# ok
```
