### ISSUE TITLE
Enhance the event-stream-processor to add additional tags for start and end times

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#906]
## **Goal**:
As a `Hub Operator` I want to `Enhance the Event Framework by adding tags for start and end times` so that `not just the duration but start and end times are recorded` (Either in the event-stream-processor or in the event-sdk)

Note: This is needed because the APM event does not store that information, but instead only stores the calculated duration.

**Tasks**:
- [ ] Event Framework design to be updated
- [ ] Need to enhance either the event-stream-processor to add the additional tags (could also consider this as part of the event-sdk's job)
- [ ] Add support for HTTP Transport trace context/headers for injections and extraction
ensure that recording of events (logs, audits, etc) are done with async-await are handled via the event-sdk and the event-sidecar. (Thereby allowing the client to confirm if the recordering should be sync or async. This has currently been done on the event-sdk, but not properly implemented on the sidecar.)

**Acceptance Criteria**:
- [ ] Designs are updated to reflect changes
- [ ] Unit Tests pass (on refactored services)
- [ ] Integration Tests pass (on refactored services)
- [ ] Code Style & Coverage meets standards (on refactored services)
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config. (on refactored services)
- [ ] Event Framework captures for providing start and end times of events and not just duration
- [ ] Support for HTTp transport is provided

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependency**:
- [ ] #833 

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vgenev** [comment]
outdated. might be covered by #1013
