### ISSUE TITLE
PI-7 Mid-PI Review Prep

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#907]
## **Goal**:
As a contributor team for the ML OSS
I want to prepare presentation and content for the Mid-PI review
so that it can be used for discussions, reviews for PI-7

**Tasks**:
- [x] Update presentation slide deck for
  - [x] Event & Error Framework [@mdebarros  ]
  - [x] Standardizing by moving common code to shared libraries [@rmothilal ]
- [x] Deployment updates
  - [x] Simulator [@rmothilal ]
  - [x] Bulk transfers integration and deployment [@mdebarros ]
- [x] Agenda, Review slides [@elnyry ]
- [x] Slide for Mowali Simulator Adoption [@ggrg ]
- [x] Review presentation and items to discuss

**Acceptance Criteria**:
- [x] A slide-deck is prepared for use during Mid-PI review meetings to inform / share progress regarding objectives and provide details as necessary. 
- [x] The slide deck covers all significant items worked on so far in PI-7 and also bring forth any significant design decisions.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @elnyry @mdebarros 
- QA/Review: OSS Core team
