### ISSUE TITLE
Error Framework: Adopt & Integrate Mojaloop SDK Error Handling to central-settlement

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#908]
## **Goal**:
As a `Hub Operator`, I want to `implement a standard Error Handling framework and apply it to the central-settlement service` so that `errors are consistent throughout the Mojaloop stack for both the Switch and the FSPs`.

**Tasks**:
- [x] Integrate the [Error Handler](https://github.com/modusbox/mojaloop-sdk-standard-components/blob/master/src/lib/errors/index.js) from the standard components lib into **central-settlement**
- [x] Refactor tests (unit and integration) that use previous Error object in favor of FSPIOPError
  - [x] Validate that hard coded Errors are being created and replaced with FSPIOErrors
  - [x] Validate that errors are correct per API Specification, eg:
https://github.com/mojaloop/central-ledger/blob/8a34ae14129b8a455703af56fa793cd23fcd1ea5/test/integration/handlers/handlers.test.js#L169
- [x] Update Unit Tests
- [ ] ~Update Integration Tests~ (not impacted by code changes)
- [x] Create follow-up stories for validation [one follow-up item #928 ]
- [ ] ~central-settlement needs custom errors, document and publish such error codes, descriptions and details clearly~

**Acceptance Criteria**:
- [x] Unit Tests pass
- [ ] ~Integration Tests pass~
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] Mojaloop SDK Standard Components for Error handling have been integrated into the central-settlement service
- [x] central-settlement component produces ML API compliant Specification errors
- [x] Custom errors for settlements are documented and published (New item created #928)

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-settlement/pull/83

## **Follow-up**:
- [ ] Create follow up story to fix Simulator as it is breaking the central-settlement Integration Tests

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @gibaros 
- QA/Review: @mdebarros @ndonnan @rmothilal
