### ISSUE TITLE
Build Artifacts for vulnerability-check don't output valid JSON

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#909]
**Summary**:
Across all projects, the newly added vulnerability-check step doesn't output valid JSON. For example:

https://3236-129916230-gh.circle-artifacts.com/0/home/circleci/project/audit/results/auditResults.json

Has console output in the file:
```json

> @mojaloop/ml-api-adapter@7.2.0 audit:check /home/circleci/project
> SHELL=sh check-audit "--json"

{"issues":[{"title":"Regular Expression Denial of Service","severity":"low","items":[{"data":{"id":1076,"path":"jsdoc>marked","dev":false,"optional":false,"bundled":false},"report":" - dependencies: jsdoc>marked"}]}],"actions":[{"isMajor":false,"action":"install","resolves":[{"id":1076,"path":"jsdoc>marked","dev":false,"optional":false,"bundled":false}],"module":"jsdoc","target":"3.6.3","humanReviewComplete":false}],"advisories":{"1076":{"findings":[{"version":"0.6.2","paths":["jsdoc>marked"]}],"id":1076,"created":"2019-07-17T20:26:14.214Z","updated":"2019-07-25T18:15:12.932Z","deleted":null,"title":"Regular Expression Denial of Service","found_by":{"link":"","name":"Bart Grantham"},"reported_by":{"link":"","name":"Bart Grantham"},"module_name":"marked","cves":[],"vulnerable_versions":">=0.4.0 <0.7.0","patched_versions":">=0.7.0","overview":"Affected versions of `marked` are vulnerable to Regular Expression Denial of Service (ReDoS). The `_label` subrule may significantly degrade parsing performance of malformed input.","recommendation":"Upgrade to version 0.7.0 or later.","references":"","access":"public","severity":"low","cwe":"CWE-400","metadata":{"module_type":"","exploitability":5,"affected_components":""},"url":"https://npmjs.com/advisories/1076"}},"metadata":{"vulnerabilities":{"info":0,"low":1,"moderate":0,"high":0,"critical":0},"dependencies":1127,"devDependencies":3492,"optionalDependencies":107,"totalDependencies":4625}}
```
## Tasks
Remove the extra console statement in the circle config for the follow projects:
- [x] [account-lookup-service](https://github.com/mojaloop/account-lookup-service)
- [x] [central-ledger](https://github.com/mojaloop/central-ledger)
- [x] [central-event-processor](https://github.com/mojaloop/central-event-processor)
- [x] [email-notifier](https://github.com/mojaloop/email-notifier)
- [x] [ml-api-adapter](https://github.com/mojaloop/ml-api-adapter)
- [x] [central-settlement](https://github.com/mojaloop/central-settlement)
- [x] [central-services-auth](https://github.com/mojaloop/central-services-auth)
- [x] [central-services-database](https://github.com/mojaloop/central-services-database)
- [x] [central-services-error-handling](https://github.com/mojaloop/central-services-error-handling)
- [x] [central-services-metrics](https://github.com/mojaloop/central-services-metrics)
- [x] [central-services-shared](https://github.com/mojaloop/central-services-shared)
- [x] [central-services-stream](https://github.com/mojaloop/central-services-stream)
- [x] [forensic-logging-sidecar](https://github.com/mojaloop/forensic-logging-sidecar)
- [x] [pathfinder-provisioning-client](https://github.com/mojaloop/pathfinder-provisioning-client)
- [x] [pathfinder-query-client](https://github.com/mojaloop/pathfinder-query-client)
- [x] [quoting-service](https://github.com/mojaloop/quoting-service)
- [x] [simulator](https://github.com/mojaloop/simulator)

## PRs
- [x] https://github.com/mojaloop/account-lookup-service/pull/19
- [x] https://github.com/mojaloop/central-ledger/pull/341
- [x] https://github.com/mojaloop/central-event-processor/pull/39
- [x] https://github.com/mojaloop/email-notifier/pull/32
- [x] https://github.com/mojaloop/ml-api-adapter/pull/136
- [x] https://github.com/mojaloop/central-settlement/pull/82
- [x] https://github.com/mojaloop/central-services-auth/pull/37
- [x] https://github.com/mojaloop/central-services-database/pull/58
- [x] https://github.com/mojaloop/central-services-error-handling/pull/48
- [x] https://github.com/mojaloop/central-services-metrics/pull/13
- [x] https://github.com/mojaloop/central-services-shared/pull/75
~- [ ] https://github.com/mojaloop/central-services-stream/pull/17~
- [x] https://github.com/mojaloop/central-services-stream/pull/25
- [x] https://github.com/mojaloop/forensic-logging-sidecar/pull/17
- [x] https://github.com/mojaloop/pathfinder-provisioning-client/pull/18
- [x] https://github.com/mojaloop/pathfinder-query-client/pull/17
- [x] https://github.com/mojaloop/quoting-service/pull/18
- [x] https://github.com/mojaloop/simulator/pull/42

**Severity**:
Low

**Priority**:
Medium

**Expected Behavior**
The `auditResults.json` should be valid json, with no console output.

**Steps to Reproduce**
  1. Run any CI process with the `vulnerability-check` step
  2. Log into CircleCI, and access the build artifacts 
  3. Observe that there is console output in the `auditResults.json` file.

**Specifications**
  - Component (if known):
  - Version: 7.2.0
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: @mdebarros 

**Notes**:

- Severity when opened: Low
- Priority when opened: Medium

**Comment by lewisdaly** [comment]
This is almost done. There's a couple issues with some of the unit tests after upgrading node packages.
