### ISSUE TITLE
Add a license-scanner step in the helm CI/CD process

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#911]
## **Goal**:
As an `OSS Maintainer` I want to `include the license-scanner in the helm release process` so that `we can attach and monitor a new license summary excel doc with every helm release`

**Tasks**:
- [ ] Integrate the [license-scanner](github.com/mojaloop/license-scanner) into the helm CircleCI `config.yml` file
- [ ] Update the license-scanner to support scans across multiple docker images (it currently only supports one docker image at a time or many github repositories at a time)

**Acceptance Criteria**:
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Any manual steps are covered 

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
It appears I made this ticket twice.

Closing in favour of #916
