### ISSUE TITLE
Submit Updates to Packages with ambiguous licenses

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#912]
## **Goal**:
As a `OSS Maintainer` I want to `update any dependencies that have ambiguous licenses` so that `we can clarify where we stand on the licensing of dependencies`.

**Tasks**:
- [ ] Submit PRs to the following repositories with clarified licenses:

| Done | Repo | Issue |
| ---- | ---  | --- |
| [ ] | https://github.com/typicaljoe/taffydb | Contains MIT license on github, but not listed in package.json |
| [ ] | https://github.com/dscape/cycle |  Listed as Public-Domain on npm, but no License file in github |
| [ ] | https://github.com/tjfontaine/node-buffercursor |  No license on github or npm |

- [ ] Once the above changes are accepted, update the package version in the `package.json` or `package-lock.json` file to pull through this license update. Apply for:
  - [ ] central-directory
  - [ ] central-ledger
  - [ ] central-settlement
  - [ ] interop-switch-js
  - [ ] ml-api-adapter
  - [ ] mock-pathfinder

- [ ] Remove any now outdated whitelisted packages from the license-scanner `config.toml`

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Re run the license-scanner across all repos and ensure there are no more warnings for the above packages

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- [ ] TBD

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Looks like taffydb has already fixed this license issue in `v2.7.3`

**Comment by lewisdaly** [comment]
Cycle is listed as Public Domain in the package.json, but the license scanner tool fails to parse the package.json file for some reason.

**Comment by lewisdaly** [comment]
This will be blocked now as we wait for pull requests to other repos out of our control to be reviewed, and npm modules to be released.

**Comment by lewisdaly** [comment]
The cycle maintainer doesn't seem to want to release a new version. (Ref: https://github.com/dscape/cycle/issues/21)

It may not be worth worrying about for now, since the only places we use this dependency are in `central-directory` (which is no longer used) and `interop-switch-js`

**Comment by TheIncorrigible1** [comment]
I've submitted a PR to address cycle if any of the maintainers are still active.

https://github.com/dscape/cycle/pull/26

**Comment by lewisdaly** [comment]
Thanks @TheIncorrigible1 . Unfortunately I think the maintainer is MIA, we might not get a release anytime soon.
