### ISSUE TITLE
On-boarding on to the ML OSS Core team - Amarnath

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#913]
**Goal**:
As a ML OSS Core team member
I would like to make sure that a new team member
has a checklist of items to address as part of on-boarding

**Tasks**:
- [x] Get access to the mojaloop github organisation
- [x] Send self-invitation link to Slack mojaloop workspace: https://mojaloop-slack.herokuapp.com/
- [x] Slack invite to mojaloop-core-team channel, self-join onboarding
- [x] Introduction to GitHub workflow - https://www.atlassian.com/git/tutorials/comparing-workflows
- [x] Introduction to standard coding style - add standard extension to the IDE: https://standardjs.com/
- [x] Brief overview of documentation (mojaloop/mojaloop, mojaloop.io/documentation, mojaloop.io): https://mojaloop.io/documentation/
- [x] Getting the Central-Ledger up and running on local machines: 
  - [x] https://github.com/mojaloop/central-ledger/blob/master/Onboarding.md
  - [x] https://github.com/mojaloop/ml-api-adapter/blob/master/Onboarding.md
- [ ] Review Local Kubernetes Development Guide
   - [ ] https://mojaloop.io/documentation/deployment-guide/
- [ ] Review Helm Charts Guide: https://github.com/mojaloop/helm/blob/master/README.md
- [x] Fork and clone [`postman`](https://github.com/mojaloop/postman) repo, clone environment files required for OSS DEV environments and run [`Golden path`](https://github.com/oderayi/postman/blob/master/Golden_Path.postman_collection.json) either on a DEV or local environment
- [x] Request and get VPN access (Miguel)
- [x] Request and get access to [Rancher](
https://k8s-tanuki-rancher.mojaloop.live/p/c-ztqzn:p-cxdfd/workloads) (Sam) 
- [x] Clone the [Mojaloop API Specification](https://github.com/mojaloop/mojaloop-specification) repo and open the v1.0 of the [implementation friendly yaml](https://github.com/mojaloop/mojaloop-specification/blob/master/Supporting%20Files/fspiop-rest-v1.0-OpenAPI-implementation.yaml) file on [editor.swagger.io](https://editor.swagger.io/)
- [x] Introduction to Scaled Agile Framework
- [x] Ensure ZenHub access
  - [x] Sign up for Zenhub: https://www.zenhub.com/ using your github account and connect to mojaloop organisation. Search for the 'project' workspace.
  - [x] Install the Zenhub Chrome extension: https://www.zenhub.com/extension You can now see the Zenhub board at: https://github.com/mojaloop/project#zenhub
- [x] Contributors Guide: https://mojaloop.io/documentation/contributors-guide/
- [x] Dropbox access (Sam)
- [x] PI presentations - https://github.com/mojaloop/documentation-artifacts/tree/master/presentations/June%202019%20PI-7_OSS_community%20session

**Comment by amarmodus** [comment]
mojaloop-core-team channel, self-join onboarding - Ask Sam - Done

**Comment by amarmodus** [comment]
error: Consumer::onError()[topics='topic-notification-event'] - Error: Local: Broker transport failure)
2019-08-14T13:37:16.329Z - error: Consumer::onError()[topics='topic-notification-event'] - Error: Local: All broker connections are down)

Solution : docker restart cl_ml-api-adapter

**Comment by amarmodus** [comment]
If you get following error :
error: uncaughtException: Could not locate the bindings file. 

Solution:
Please export following items

export CPPFLAGS=-I/usr/local/opt/openssl/include
export LDFLAGS=-L/usr/local/opt/openssl/lib

**Comment by amarmodus** [comment]
SAFe(Scalable Agile Framework) way for work, Phases, PI's, Convene can be explained

**Comment by elnyry** [comment]
@amarmodus when you get a chance, I think these need to be added to the FAQ on setup (and the SAFe on the task here on the story)
