### ISSUE TITLE
Extension Value fields in ExtensionList objects exceeding the size limit of 128

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#914]
**Summary**:
The 'value' in the key, value pairs of extension Objects of ExtensionLists are exceeding the length of 128 chars as specified in the Spec and so the transfers with errors are failing.. (As scheme validation is failing on the Simulator). Successful transfers are fine because (obviously) the extension values with trace elements do not exist in those (however, I think these may need to be addressed as well, to limit the length to 128)

**Severity**:
High

**Priority**:
Medium

**Expected Behavior**
1. Extension List elements when used the 'key', 'value' elements have strings no longer than 128 characters.
2. Error callbacks using these are sent to the FSPs and Scheme validaton passes

**Steps to Reproduce**
  1. Requests that make use of the Error callbacks with ExtensionList elements "key", "value" elements populated (with traces?)
  2. Observe results, logs
  3.

**Tasks**:
- [x] Repro issue
- [x] Implementing Fix (central-services-error-handling)
- [x] Release, update version in central-ledger, ml-api-adapter, other services
- [x] Redeploy on AWS, Verify Fix

**Specifications**
  - Component (if known): central-services error handling?
  - Version: v7.3.x
  - Platform: AWS (Any)
  - Subsystem: Error Handling
  - Type of testing: Functional testing (Regression testing using Postman before releases)
  - Bug found/raised by: @mdebarros @elnyry 

**Notes**:

- Severity when opened:
- Priority when opened:
