### ISSUE TITLE
Error Framework: Adopt Mojaloop SDK Error Handling to CEP, email-notifier & transactions-requests-service

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#915]
## **Goal**:
As a `Hub Operator`, I want to `implement a standard Error Handling framework and apply it to the central-event-processor & email-notifier services` so that `errors are consistent throughout the Mojaloop stack for both the Switch and the FSPs`.

**Tasks**:
- [x] Integrate the [Error Handler](https://github.com/modusbox/mojaloop-sdk-standard-components/blob/master/src/lib/errors/index.js) from the standard components lib into 
  - [x] central-event-processor
  - [x] email-notifier
  - [x] transaction-request-service
  - [x] central-services-shared
- [x] Refactor tests (unit and integration) that use previous Error object in favor of FSPIOPError
  - [x] Validate that hard coded Errors are being created and replaced with FSPIOErrors
  - [x] Validate that errors are correct per API Specification, eg:
https://github.com/mojaloop/central-ledger/blob/8a34ae14129b8a455703af56fa793cd23fcd1ea5/test/integration/handlers/handlers.test.js#L169
- [x] Update Unit Tests
- [ ] ~Update Integration Tests~

**Acceptance Criteria**:
- [x] Unit Tests pass
- [ ] ~Integration Tests pass~
- [ ] ~Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.~
- [x] Mojaloop SDK Standard Components for Error handling have been integrated into
  - [x] central-event-processor
  - [x] email-notifier
  - [x] transaction-request-service
  - [x] central-services-shared
- [x] central-event-processor component produces ML API compliant Specification errors
- [x] email-notifier component produces ML API compliant Specification errors
- [x] transaction-request-service component produces ML API compliant Specification errors
- [x] central-services-shared component produces ML API compliant Specification errors

## **Pull Requests**:
- [x] https://github.com/mojaloop/email-notifier/pull/33
- [x] https://github.com/mojaloop/central-event-processor/pull/40
- [x] https://github.com/mojaloop/transaction-requests-service/pull/2
- [x] https://github.com/mojaloop/central-services-shared/pull/67

## **Follow-up**:
- TBD

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @gibaros 
- QA/Review: @mdebarros @ndonnan @rmothilal

**Comment by elnyry** [comment]
Added transaction requests service to the same story (increasing from 5 to 8)
