### ISSUE TITLE
Incorporate license-scanner into Helm Release workflow

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#916]
## **Goal**:
As an `OSS Maintainer` I want to `incorporate the license-scanner into Helm Release CI/CD pipeline` so that `all releases contain an .xlsx license summary for all of the associated docker images in the helm release`

**Tasks**:
- [x] Update the license scanner to allow for scans across multiple docker images at once in standalone mode (it currently only supports multiple repos, or just one docker image)
- [x] Edit the `./.circleci/config.yml` file to include a license-scanner step which outputs the `license-summary.xlsx` file as an artifact
- [x] Establish a (manual?) process for adding the `license-summary.xlsx` file to the release notes when a new release is made

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Added `audit-licences` to master protected branch rules
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/license-scanner/pull/5
- [x] https://github.com/mojaloop/license-scanner/pull/6
- [x] https://github.com/mojaloop/helm/pull/201
- [x] https://github.com/mojaloop/license-scanner/pull/7

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: TBC

**Comment by lewisdaly** [comment]
This is semi-blocked by some major revisions to the helm charts: https://github.com/mojaloop/helm/pull/200

 I'll wait until that is merged so we're not double handling things.

**Comment by lewisdaly** [comment]
@elnyry All done! 

The next time we release helm, we will just have to pull out the license-sumary.xlsx file and attach to the release notes.

**Comment by elnyry** [comment]
Yes, was thinking the same :-)..

Thanks Lewis!
