### ISSUE TITLE
6.1.3.1 Settlements DB Design (or redesign): Change to settlement, settlementWindow tables

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#921]
## **Goal**:
As a Scheme Administrator
I want to be able to store the currency against a Settlement & Settlement Window
so that I can later request Settlements in a given currency.

**Tasks**:
- [ ] Change to settlement table
The settlement table in the central ledger database needs to be modified to add a currencyId column. This column should have the following characteristics:
  - The column should be required (NOT NULL).
  - The column’s data type should be varchar(3)
  - The column should be defined as a foreign key reference to the currencyId field of the currency table.
- [ ] Change to settlementWindow table [**To be confirmed**]
The settlementWindow table in the central ledger database needs to be modified to add a currencyId column. This column should have the following characteristics:
  - The column should be required (NOT NULL).
  - The column’s data type should be varchar(3)
  - The column should be defined as a foreign key reference to the currencyId field of the currency table
- [ ] Refactoring DB scripts

**Acceptance Criteria**:
- [ ] DB Designs for central services are up-to date
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config
- [ ] An approved and tested way of applying this to existing databases is documented
- [ ] The DB creation scripts used by CI/CD are updated and changes tested
- [ ] DB scripts that create new records in Settlements and SettlementWindows tables fail gracefully if they're run against an unsupported version of the database

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
