### ISSUE TITLE
6.2.2.13 Add openSettlementWindow functionality

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#923]
## **Goal**:
As a Hub Operator
I want to _be able to open a Settlement with specific criteria(account type, currency)_
so that _I can open such windows as needed_

The existing API needs to have functionality added to allow an administrator to set up a settlement for a given account type and currency.

Change to code supporting closeSettlementWindow resource [Story #3]
- The existing API described in Ref_2 above provides a single function (closeSettlementWindow) to manage settlement windows. This function allows its user to select a settlement window by ID number and to input a new status for the window and a reason for that status.
- The code supporting this function should create a new settlement window with the same currency as the settlement window that is being closed.

**Tasks**:
- [ ] 

**Acceptance Criteria**:
- [x] Designs are up-to date (@bothadeon)
- [x] Unit Tests pass (@bothadeon)
- [x] Integration Tests pass (@bothadeon)
- [x] Code Style & Coverage meets standards (@bothadeon)
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] Settlement windows can be aggregated for account type, currency 

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @bothadeon 
- QA/Review: @ggrg , @ndonnan
