### ISSUE TITLE
Changes to any administration portals which call this (Settlements) API

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#926]
## **Goal**:
As a <stakeholder> I want to <action> so that <reason>

getSettlementWindowsByParams [Story #5]

The parameters for the getSettlementWindowsByParams resource in the API described in Ref_2 above should be extended to allow a caller to request settlement windows by currency ID. The same constraints on the currency code as described in Section 6.1.1.2 above should be used.

**NOTE**: this change will also require changes to any administration portals which call this API – In release notes [Story #6]

**Tasks**:
- [x] Modify Swagger def
- [x] Modify DAO script 
- [x] Modify handler script
- [x] Add unit tests to cover delivered functionality
- [x] Address PR comments

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-settlement/pull/254

## **Follow-up**:
- N/A

**Dependencies**:
- #915 

## **Accountability**:
- Owner: @lazolalucas 
- QA/Review: @ggrg , @ndonnan
