### ISSUE TITLE
Upgrade the version of Mule for interop-services for Mojaloop projects

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#93]
**Goal**:
As a developer I would like to upgrade the version of Mule for interop-services so that we can make use of new features and upgrade the dependencies for stability and staying current.

**Tasks**:
- [ ] 

**Acceptance Criteria**:
- [x] Upgraded Mule run-time version (CE) from 3.8.1 (or 3.8.0) to 3.9.0
- [x] Ensure dependencies are updated and apps compile without issues
- [x] Ensure all included tests pass
- [x] Test end-to-end to ensure no regressions
- [x] Interop Account Lookup is upgraded
- [x] Interop Routing is upgraded
- [x] Interop Switch is upgraded
- [x] Interop Connector is upgraded

**Dependencies**:
- None currently

**Comment by elnyry** [comment]
Upgraded mule version to 3.9.0 CE for Mojaloop interop projects. Still needs to be done for the other 
'OSS' projects (An issue with metrics connector needs to be fixed).

**Comment by yzaki16** [comment]
I m unable to start the interop mule services. Can any 1 guide me for it.

I places the interop app in mule/app folder and start the mule... it showing mule-config.xml not found.

**Comment by elnyry** [comment]
Hi yzaki16, I created an issue for this [here](https://github.com/mojaloop/project/issues/132) - Please use it and if you have other issues, please raise a new issue, we can use it to work towards resolution. The current issue #93 is for a different purpose.
