### ISSUE TITLE
Event Framework: Bug Fixes & Enhancements - I

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#930]
## **Goal**:
As a `Hub Operator`, I want to `implement a standard Error Handling framework` so that `errors are consistent throughout the Mojaloop stack for both the Switch and the FSPs`.

**Tasks**:

- ### Enhancements:
    - #### End-to-end Flow [~3]
       - [ ] ~Design~
           - [ ] ~Define end-to-end flow-tags for master parent span that represents the end-to-end trace~
           - [ ] ~Cater for trace flow name~
           - [ ] ~Cater for start and end timestamps~
       - [ ] ~Implementation~
           - [ ] ~Automatically add start flow-tags on a parent span (aka no parentSpanId is provided, and span is not a child)~
           - [ ] ~Add flag to finish operation to add end flow-tags~
           - [ ] ~Event-Stream-Processor to log the End-to-end trace-flow once it sees a trace message with the end-to-end (start & end) flow-tags~

    - #### Tags in the event-stream-processor 
       - [x] Add tags from span to event-stream-processor [@vgenev ]

    - #### Inject Config into Tracer (SERVER_HOST, SERVER_PORT, DISABLE_SIDECAR) [~1]
       ~- [ ] Create sidecar recorders with different than the default config~ *it is possible with the current code. Check the comment https://github.com/mojaloop/project/issues/930#issuecomment-521969979 for details*

    - #### Add new actions for Audits [~0.5] [@vgenev]
        - [x] start
        - [x] default <-- this is existing (nothing to do here)    
        - [x] finish
        - [x] egress
        - [x] ingress

    - #### Add support for HTTP Transport [~3] 
        - [x] Function to inject Trace Context into HTTP Transport headers
        - [x] Function to extract Trace Context from HTTP Transport headers
        - [x] Return `undefined` context if header is not found

    - #### Async Consistency [~8]
       - [x] Investigate if messages/metadata is consistent with not using `await` [@vgenev]
               Investigation outcome: https://github.com/mojaloop/project/issues/930#issuecomment-521972530
       - [x] Determine if we need to provide an additional flag or operation for event operations 
(debug, warn, audit, etc) to support only the recorder is operating in sync vs async modes, or alternatively, consider having different recorders for sync vs async modes.

- ### Hotfixes:
    - [x] `DISABLE_SIDECAR` --> renamed to `SIDECAR_DISABLED` [~0.5] [@vgenev]
    - [x] Enable Sidecar Recorder with option to log to default logger with the proper level [@vgenev]
    - [x] Double Info Log issue [~1] [@vgenev]
        - [x] Investigate <-- Repeat line 64 `await parentSpan.info(event)` and below it add `await parentSpan.info('this is an info log')` <-- this resulted in NO messages being sent to the sidecar
        - ~[ ] Resolve issue <-- this most likely has been resolved with the following commit https://github.com/mojaloop/event-sdk/commit/b3ecf0d517640cfdc4ed43d7cd07583674418f96~ *issue has been resolved*
    - [x] Message Protocol Events that are logged using the Event-SDK are not being logged properly <-- the entire event must be logged, and not be transformed into the "Recorded Event" [~1] [@vgenev]
        - [x] Fix issue
    - [ ]  Optional Fields are being recored with empty strings <-- these nice to have [~3]
        - [ ]  parentspanId should not be included if its empty
        - [ ]  finishTimestamp should not be included if its empty
        - [ ]  sampled <-- should this be included if not set?
        - [ ]  flags <-- should this be included if not set?
        - [ ]  pp <-- not included if its not set
        - [ ]  from/to <-- not being set in the audit
    - [x]  Check why span is `successful` even if the state is `failed`
        - [x] Update SDK to be able to add `state` into finish method.
        - [x] Update Event Stream Processor to be able to set result.error and corresponding tags of the Elastic APM span context, so the span can be set as `error` if necessary.

- ### Nice to have
    - [x] `state` into `finish`
    - [x] Optional flag to enable "local client logging" on the Event-SDK client

- ### Future stories to be created/groomed
    - [ ] Consider the transaction.type for APM API calls from event-streaming-processor

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vgenev** [comment]
The recorders can be assigned at creating a Span and changed while creating a child spans. All recorders are inherited, if not set.

#### create a default recorder:
```
let anotherSideCardSpan = Tracer.createSpan('another sidecar', {}, { defaultRecorder: new DefaultSidecarRecorder(new EventLoggingServiceClient('localhost', 50051)) })

let anotherLoggerSpan = Tracer.createSpan('another logger', {}, { defaultRecorder: new DefaultLoggerRecorder() })
```
#### create new recorders for a child
```
let IIChild = parentSpan.getChild('child II service', {defaultRecorder: new DefaultoggerRecorder()})
let IIIChild = Tracer.createChildSpanFromContext('child III service', contextFromMessage, { defaultRecorder: new DefaultLoggerRecorder() })
```

**Comment by vgenev** [comment]
The finish methods generate correct timestamps no matter if they are await-ed or just called. The issue at the moment is that we need to provide synchronous recorders.

**Comment by mdebarros** [comment]
Based on discussions:
- End-to-end design has been scratched for now, and instead, use the EFK dashboards to show this information. This would avoid abusing the tags functionality providing in the
