### ISSUE TITLE
On-boarding on to the ML OSS Core team - Steven

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#937]
**Goal**:
As a ML OSS Core team member
I would like to make sure that a new team member
has a checklist of items to address as part of on-boarding

**Tasks**:
- [x] Get access to the mojaloop GitHub Organization
- [x] Send self-invitation link to Slack mojaloop workspace: https://mojaloop-slack.herokuapp.com/
- [x] Slack invite to mojaloop-core-team channel, self-join on-boarding
- [x] Introduction to GitHub workflow - https://www.atlassian.com/git/tutorials/comparing-workflows
- [x] Introduction to standard coding style - add standard extension to the IDE: https://standardjs.com/
- [x] Brief overview of documentation (mojaloop/mojaloop, mojaloop.io/documentation, mojaloop.io): https://mojaloop.io/documentation/
- [x] Getting the Central-Ledger up and running on local machines: 
  - [x] https://github.com/mojaloop/central-ledger/blob/master/Onboarding.md
  - [x] https://github.com/mojaloop/ml-api-adapter/blob/master/Onboarding.md
- [x] Review Local Kubernetes Development Guide
   - [x] https://mojaloop.io/documentation/deployment-guide/
- [x] Review Helm Charts Guide: https://github.com/mojaloop/helm/blob/master/README.md
- [x] Ensure ZenHub access
  - [x] Sign up for Zenhub: https://www.zenhub.com/ using your GitHub account and connect to mojaloop organisation. Search for the 'project' workspace.
  - [x] Install the Zenhub Chrome extension: https://www.zenhub.com/extension You can now see the Zenhub board at: https://github.com/mojaloop/project#zenhub
- [x] Contributors Guide: https://mojaloop.io/documentation/contributors-guide/
- [x] Dropbox access (Sam)
- [x] PI presentations - https://github.com/mojaloop/documentation-artifacts/tree/master/presentations/June%202019%20PI-7_OSS_community%20session
