### ISSUE TITLE
On-boarding on to the ML OSS Core team - Steven O

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#938]
**Goal**:
As a ML OSS Core team member
I would like to make sure that a new team member
has a checklist of items to address as part of on-boarding

**Tasks**:
- [ ] Get access to the mojaloop GitHub Organization
- [ ] Send self-invitation link to Slack mojaloop workspace: https://mojaloop-slack.herokuapp.com/
- [ ] Slack invite to mojaloop-core-team channel, self-join on-boarding
- [ ] Introduction to GitHub workflow - https://www.atlassian.com/git/tutorials/comparing-workflows
- [ ] Introduction to standard coding style - add standard extension to the IDE: https://standardjs.com/
- [ ] Brief overview of documentation (mojaloop/mojaloop, mojaloop.io/documentation, mojaloop.io): https://mojaloop.io/documentation/
- [ ] Getting the Central-Ledger up and running on local machines: 
  - [ ] https://github.com/mojaloop/central-ledger/blob/master/Onboarding.md
  - [ ] https://github.com/mojaloop/ml-api-adapter/blob/master/Onboarding.md
- [ ] Share Local Kubernetes Development Guide
   - [ ] https://mojaloop.io/documentation/deployment-guide/
- [ ] Share Helm Charts Guide: https://github.com/mojaloop/helm/blob/master/README.md
- [ ] Ensure ZenHub access
  - [ ] Sign up for Zenhub: https://www.zenhub.com/ using your github account and connect to mojaloop organisation. Search for the 'project' workspace.
  - [ ] Install the Zenhub Chrome extension: https://www.zenhub.com/extension You can now see the Zenhub board at: https://github.com/mojaloop/project#zenhub
- [ ] Contributors Guide: https://mojaloop.io/documentation/contributors-guide/
- [ ] Dropbox access (Sam)
- [ ] PI presentations - https://github.com/mojaloop/documentation-artifacts/tree/master/presentations/June%202019%20PI-7_OSS_community%20session

**Comment by elnyry** [comment]
Duplicate of #937
