### ISSUE TITLE
Use "transformHeaders" from the shared http library in central-ledger - 3.5

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#939]
## **Goal**:
As a ML OSS Codebase maintainer
I want to _reuse the "transformHeaders" and other shared functionality from a shared http library_
 so that 'transform headers' and other shared functionality can be standardized in central-ledger services 

**Tasks**:
- [x] Update central-ledger
- [x] Release new version of central-services-shared
- [x] Include new version of shared library in already updated API's
  - [x] ALS
  - [x] ML-API-Adapter
- [x] Update/Create tests to ensure coverage is complete

**Acceptance Criteria**:
- [x] central-ledger is updated to use the new version of library (central-services-shared)
- [x] Unit tests pass (same pass rate as before)
- [x] Integration tests pass (same pass rate as before)

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/359

**Dependency**:
- [x]  #887 

## **Follow-up**:
- N/A

## **Accountability**:
- Owner: 
- QA/Review: @rmothilal @mdebarros
