### ISSUE TITLE
Upgrade the version of Node for central-hub

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#94]
**Goal**:
As a developer I would like to upgrade the version of Node of central-hub so that we can make use of new features and upgrade the dependencies for performance and stability

**Tasks**:
- [x] Upgrade Node to 8.94 LTS
- [x] Upgrade npm
- [x] Upgrade dependencies
- [x] Upgrade devDependencies
- [x] Update manifest.js code to be compatible with the latest version of "glue"--one of the dependancies
- [x] Run the test package

**Acceptance Criteria**:
- [x] Upgraded node from 6.5.0 to 8.9.4 LTS
- [x] Ensure NPM dependencies are upgraded and compiles
- [x] Ensure all included tests pass

**Dependencies**:
- None currently
