### ISSUE TITLE
PI7 Onboarding enhancements and fixes

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#941]
## **Goal**:
As an `OSS Team`, I want to `resolve all onboarding issues` so that `new OSS team and community members can onboard successfully to be productive contributors to Mojaloop`

**Tasks**:
 1. Onboarding Issues, Fixing (Onboarding docs on ml-api-adapter, central-ledger or to a Common location) - Miguel
        a. [x] Docker Section-4 here - https://github.com/mojaloop/central-ledger/blob/master/Onboarding.md
        b. Update Docker compose for central-ledger:
            i. [x] Needs simulator added
            ii. [x] MongoDB needs to be added
            iii. [x] Include health-checks
            iV. [x] Ensure ordering on startup
        c. Update Docker compose for ml-api-adapter:
            i. [x] Needs simulator added
            iii. [x] Include health-checks , ensure ordering
            iV. [x] Ensure ordering on startup
            V. [x] Include fix for https://github.com/mojaloop/project/issues/940 [ mdebarros ]
        c. [x] Populate test data script Section - 3.4 here -  https://github.com/mojaloop/central-ledger/blob/master/Onboarding.md
        d. [x] Update QA scripts to run containers locally [ mdebarros ]
        e. Missing steps
            i. [x] Add hosts to avoid manual steps [ mdebarros ]
            ii. [x] Update instructions to test a deployment using postman [may point to existing docs and use the local envt file]

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] New OSS team and community members can onboard successfully to be productive contributors to Mojaloop via the onboarding guide and related resources

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/365
- [x] https://github.com/mojaloop/ml-api-adapter/pull/154
- [x] https://github.com/mojaloop/postman/pull/33
- [x] https://github.com/mojaloop/documentation/pull/106

## **Follow-up**:
- [ ] Review on-boarding, go through

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by oderayi** [comment]
Verification (on Ubuntu Desktop 18.04):

I am not able to launch central-ledger and ml-api-adapter with docker-compose as documented.

Central Ledger:
* The following services didn't start up:
  - Kafka
  - Mongo
  - Central Ledger
* I could not follow logs for the following services individually with `docker logs -f <conatiner-name>`  (might be useful for debugging/troubleshooting containers individually):
  - MySQL
  - Kafka
  - Mongo

ML API Adapter
* The following services didn't start up:
  - Central Ledger
  - Kafka
  - Central Ledger
* I could not follow logs for the following services individually with `docker logs -f <conatiner-name>`  (might be useful for debugging/troubleshooting containers individually):
  -  Kafka
  - MySQL

* Other updates for the docs:
  - Include command to shut down the containers (started with docker-compose) at once
  - Include command to follow logs on individual container

**Comment by oderayi** [comment]
We can have a Zoom to share detailed error logs.

**Comment by mdebarros** [comment]
> Verification (on Ubuntu Desktop 18.04):
> 
> I am not able to launch central-ledger and ml-api-adapter with docker-compose as documented.
> 
> Central Ledger:
> 
> * The following services didn't start up:
>   
>   * Kafka
>   * Mongo
>   * Central Ledger
> * I could not follow logs for the following services individually with `docker logs -f <conatiner-name>`  (might be useful for debugging/troubleshooting containers individually):
>   
>   * MySQL
>   * Kafka
>   * Mongo
> 
> ML API Adapter
> 
> * The following services didn't start up:
>   
>   * Central Ledger
>   * Kafka
>   * Central Ledger
> * I could not follow logs for the following services individually with `docker logs -f <conatiner-name>`  (might be useful for debugging/troubleshooting containers individually):
>   
>   * Kafka
>   * MySQL
> * Other updates for the docs:
>   
>   * Include command to shut down the containers (started with docker-compose) at once
>   * Include command to follow logs on individual container

The issue was not a docker-compose problem but seemed to be caused by a network connectivity/stability issue on @oderayi's side. 

@oderayi please let me know if you have any further issues or suggestions.
