### ISSUE TITLE
Error Framework: Refactor extensionList object to not include 'cause' in responses

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#943]
## **Goal**:
As a Hub Operator
I want to include clear error information and no technical details on messages that FSPs receive so that any ambiguity is avoided along with not giving away too much technical details

**Tasks**:
- [x] Update framework to not include 'cause' in responses in extensionList (key, value) (can be used / logged internally but not externally)
- [x] Concatenation for 'cause' to happen at the notification-handler (discuss)

**Acceptance Criteria**:
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] The message body on error messages to FSPs does not include 'cause' in the extensionList (as this is now truncated to a length of 128), to remove any ambiguity.

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-error-handling/pull/63
- [x] https://github.com/mojaloop/central-services-stream/pull/33
- [x] https://github.com/mojaloop/ml-api-adapter/pull/168
- [x] https://github.com/mojaloop/central-ledger/pull/384

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rmothilal 
- QA/Review: @rmothilal @mdebarros

**Comment by gibaros** [comment]
All PRs, reviewed, merged and released:

 - mojaloop/central-services-error-handling#63
 - mojaloop/central-services-stream#33
 - mojaloop/ml-api-adapter#168
 - mojaloop/central-ledger#384
