### ISSUE TITLE
EFK, Prometheus, Grapahana requirements for Performance testing

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#945]
## **Goal**:
As a Core team member
I want to build performance testing capabilities so that
Performance testing on a given Mojaloop deployment can be performed and metrics published.

This story is specific to providing requirements for EFK, Prometheus, Graphana and other tools required for the Performance Infrastructure. It includes providing requirements for JMeter scripts needed for Perf testing.

**Tasks**:
- [ ] Provide EFK requirements for Infrastructure needs
  - [ ] EFK
  - [ ] Prometheus
  - [ ] Graphana
- [ ] Provide JMeter requirements to QA
- [ ] Refactor Helm Promfana config/docs to instead use the _prometheus-operator_ chart

Provide Prometheus dashboards information, charts, etc

**Acceptance Criteria**:
- [ ] Requirements for below tools are provided / documented
  - [ ] EFK
  - [ ] Prometheus
  - [ ] Graphana
  - [ ] JMeter scripts (or test scripts in general)

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
