### ISSUE TITLE
Initial QA automation for bulk transfers

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#946]
## **Goal**:
As a Hub Operator
I want to _implement the /bulkTransfers end-point_
so that _I can support the bulk Transfers use-case (based on the API Definition)._ 

This specific story is for making necessary changes for supporting QA on bulk transfers and performing end-to-end testing for bulk transfers

**Tasks**:
- [x] Create
  - [x] Test scripts to test bulk transfers happy path (PoC)
  - [x] QA framework release as relevant
- [x] Executing tests from the QA framework

**Acceptance Criteria**:
- [x] A new collection for bulk transfers is made available in the postman repo that tests the happy path of bulk transfers (which can be extended)

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
Currently blocked with an issue in POST /bulkTransfers..

**Comment by elnyry** [comment]
#947 fixed in v8.1.0 of helm. Currently blocked by #1033

**Comment by elnyry** [comment]
Recently added by @rmothilal in 9.6. so closing this
