### ISSUE TITLE
Archive Deprecated Repos

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#948]
## **Goal**:
As an `OSS Maintainer` I want to `archive any deprecated repos` to help `keep the mojaloop project clean on github`

**Tasks**:
- [x] Validate that older releases and documentation doesn't point to these repos
- [x] Add a `deprecated` label to the repo in github
- [x] Add a boilerplate text to the readme file so folks know they are deprecated and why
- [x] Archive the repository in github (this keeps it searchable, but uneditable)
- [x] Update the repo descriptions 
- [x] Apply the above to the following repos:
  - [X] dfsp-account
  - [X] dfsp-admin
  - [X] dfsp-api
  - [X] dfsp-directory
  - [X] dfsp-identity
  - [X] dfsp-ledger
  - [X] dfsp-mock
  - [X] dfsp-rule
  - [X] dfsp-scheme-adapter
  - [X] dfsp-subscription
  - [X] dfsp-transfer
  - [x] dfsp-ussd
  - [X] central-hub 
  - [X] central-end-user-registry
  - [X] interop-ilp-conditions
- [x] Add a "repo guide" piece of documentation to help people find and understand the public repos
  - I'm not sure what this will look like just yet, perhaps we can divide the repos into sections: `core-services`, `tools`, `QA`, `libraries`, `experiments`

**Acceptance Criteria**:
- [ ] Code Style & Coverage meets standards
- [ ] Documentation changes meet documentation standards
- [ ] TBD

## **Pull Requests**:
- [x] https://github.com/mojaloop/documentation/pull/107
- [x] https://github.com/mojaloop/dfsp-ussd/pull/2
- [x] https://github.com/mojaloop/dfsp-ledger/pull/3
- [x] https://github.com/mojaloop/dfsp-account/pull/2
- [x] https://github.com/mojaloop/dfsp-api/pull/5
- [x] https://github.com/mojaloop/dfsp-admin/pull/3
- [x] https://github.com/mojaloop/dfsp-directory/pull/3
- [x] https://github.com/mojaloop/dfsp-identity/pull/2
- [x] https://github.com/mojaloop/dfsp-mock/pull/3
- [x] https://github.com/mojaloop/dfsp-rule/pull/2
- [x] https://github.com/mojaloop/dfsp-scheme-adapter/pull/1
- [x] https://github.com/mojaloop/dfsp-subscription/pull/2
- [x] https://github.com/mojaloop/dfsp-transfer/pull/2
- [x] https://github.com/mojaloop/central-hub/pull/45
- [x] https://github.com/mojaloop/central-end-user-registry/pull/46
- [x] https://github.com/mojaloop/interop-ilp-conditions/pull/1
- [x] https://github.com/mojaloop/documentation/pull/111

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: @elnyry, @kjw000

**Comment by lewisdaly** [comment]
`dfsp-ussd` is only referred to in other deprecated repos

**Comment by lewisdaly** [comment]
- There is one reference to `central-hub` in the documentation repo
- I also found plenty of references to the `central-end-user-registry` across a number of repos that will need to be removed.

**Comment by lewisdaly** [comment]
@kjw000 can you please expand on what you wanted in "updating the repo descriptions?" For now, I've prepended a 'DEPRECATED' label to the start of each. Is that sufficient?

**Comment by kjw000** [comment]
The DEPRECATED label is good.
I would also add the following (or something like this) to the main readme:
"This repo has been deprecated and no longer supported by the Mojaloop team.  No releases are no longer dependent or referencing this information or code. "

**Comment by lewisdaly** [comment]
Cool. As for the readmes I added a deprecation notice (you can see the pull requests above) as follows:


>## Deprecation Notice
>
>The <service name> service was deprecated as of January 2018. This service is no longer >maintained, and is no longer referenced by any releases of Mojaloop.
>
>For a list of active Mojaloop repos, please refer to [Repo Details](https://mojaloop.io/documentation/repositories/) section of the Mojaloop documentation.

**Comment by kjw000** [comment]
thanks - looks great.

**Comment by lewisdaly** [comment]
Ok. This is almost across the line. The only thing left to do is remove references to `central-end-user-registry` from the Helm repo if we want.

The `central-end-user-registry` is currently commented out in the charts (and hence not a part of the release) so we might be ok leaving it in for now. @elnyry let me know what you think.

**Comment by elnyry** [comment]
hi @lewisdaly yes, this is great progress and much needed. Yes, I agree about central-end-user-registry, lets leave it as it is for now and call it deprecated. We'll remove it from Helm soon.

**Comment by lewisdaly** [comment]
Great, that sounds good. 

In that case - I think we can consider this ticket done.
