### ISSUE TITLE
Update dependencies with broken tests

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#950]
## **Goal**:
As a `developer` I want to `update all dependencies and fix tests` so that `all security, performance and stability updates are included in the OSS code base`

This is a follow for:
- https://github.com/mojaloop/project/issues/866
- https://github.com/mojaloop/project/issues/909

Updating some of the dependencies was causing test failures and CircleCI build failures which need to be resolved.

**Tasks**:
- Update packages to latest versions for:
  - [x] central-services-auth
  - [x] central-services-error-handling
  - [x] central-services-stream

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [x] Unit Tests pass
- [ ] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: TBC

**Comment by elnyry** [comment]
#866 and #909 referenced here are both closed, so closing this
