### ISSUE TITLE
Create test for validating PUT/transfers calls without IDs

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#951]
## **Goal**:
As a Hub Operator
I want to validate PUT /<service> calls according to the specification
so that an appropriate error callback is made to the FSPs

**Tasks**:
- [x] Postman tests for the scenario from issue #849 
- [x] Validate on /quotes

**Acceptance Criteria**:
- [x] A test exists for the scenario #849 so that a valid error callback is made to the FSP

## **Pull Requests**:
- [x] https://github.com/mojaloop/postman/pull/35
- [x] https://github.com/mojaloop/postman/pull/37

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
