### ISSUE TITLE
Schema Validations on the quoting-service

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#953]
## **Goal**:
As a Hub Operator of a Mojaloop Switch
I want to respond with an HTTP error code for requests that do not follow the (Swagger) API Definition Data Model
so that only valid requests are accepted and processed in the Switch

**Tasks**:
- [ ] Implement Scheme validations based on missing items as per list [here](https://github.com/mojaloop/quoting-service/issues/9)

**Acceptance Criteria**:
- [ ] Unit Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Schema Validations on /quotes calls are performed according to the API Definition. 

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Notes**:
- List of known issues - https://github.com/mojaloop/quoting-service/issues/9
