### ISSUE TITLE
 Event Framework: Optional Enhancements - II follow up on #930 

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#955]
## **Goal**:
As a `Hub Operator`, I want to `implement the optional and nice to have enhancements of the Event SDK`.

**Tasks**:

- ### Enhancements:
    - [x]  Optional Fields are being recored with empty strings <-- these nice to have [~3]
        - [x]  parentspanId should not be included if its empty
        - [x]  finishTimestamp should not be included if its empty
        - [x]  sampled <-- should this be included if not set?
        - [x]  flags <-- should this be included if not set?
        - [x]  pp <-- not included if its not set
        - [x]  from/to <-- not being set in the audit
    - [x] Consider the transaction.type for APM API calls from event-streaming-processor
    - [x] Added APM metadata when logging (audits, logs, trace not just on APM index via the APM API) to ensure seamless transition between APM & Mojaloop Index's

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
- [x] https://github.com/mojaloop/event-stream-processor/pull/4
- [x] https://github.com/mojaloop/event-sdk/pull/12
- [x] https://github.com/mojaloop/event-sidecar/pull/8

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
