### ISSUE TITLE
Use "transformHeaders" from the shared http library in central services at  bulk-api-adapter - 4

### ISSUE THREAD

**Issue by gibaros** [mojaloop/project#957]
## **Goal**:
As a ML OSS Codebase maintainer
I want to _reuse the "transformHeaders" functionality from a shared http library_
 so that 'transform headers' functionality can be standardized in bulk-api-adapter

**Tasks**:
- [x] Update bulk-api-adapter
- [ ] ~Update/Create tests to ensure coverage is maintained~
- [x] Tested end to end prepare and fulfill via Postman

**Acceptance Criteria**:
- [x] bulk-api-adapter is updated to use the above library
  - [x] Unit tests pass (same pass rate as before)
  - [ ] ~Integration tests pass (same pass rate as before)~

## **Pull Requests**:
- [x] https://github.com/mojaloop/bulk-api-adapter/pull/4

**Dependency**:
- [x] #887 

## **Follow-up**:
- 

## **Accountability**:
- Owner: 
- QA/Review: @rmothilal @mdebarros

**Comment by gibaros** [comment]
Closing issue as it corresponding PR has been reviewed, merged and closed
