### ISSUE TITLE
Instrumenting, Logging for Event framework on central-ledger, ml-api-adapter - 2

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#960]
## **Goal**:
As a Hub Operator
I want to _integrate Event Framework into Mojaloop components_ so that
_all events (errors, general, etc) can be audited and traced appropriately for Prepare and Fulfil flows_

This applies to central-ledger and ml-api-adapter

**Tasks**:
- [x] Event Framework
  - [x] Enhance central services shared
    - [x] Add to the jsdocs, a description of the 'sampled' route tag for span creation
    - ~Add to the README, a description of the 'sampled' route tag for span creation~
    - [x] Integrate SDK for logging
      - [x] ml-api-adapter - API
        - ~Logs (replace existing logs)~ TBD when span log-level can be configured
        - [x] Add the following tags for Transfers (_ADDED in PI8.1_)
          - [ ] updated Event Documentation to include this information [ @mdebarros ]
          - [x] transactionId
          - [x] transactionType <-- type of the transactionId (i.e. transfer)
          - [x] transactionAction <-- action associated to the transaction (i.e. prepare, fulfil)
          - [x] source <-- transport sending fsp
          - [x] destination <-- transport receiving fsp
          - [x] payerfsp <-- sending participant
          - [x] payeefsp <-- receiving participant
        - [x] Helm 
          - [x] Integrate event-sidecar into helm chart
          - [x] Updated configuration for default.json in helm chart
      - [x] ml-api-adapter - Notifications
        - ~Logs (replace existing logs)~ TBD when span log-level can be configured
        - [x] Helm 
          - [x] Integrate event-sidecar into helm chart
          - [x] Updated configuration for default.json in helm chart
- [x] Event Framework
	- [x] Integrate SDK for logging
		- [x] prepare handler
    			- ~Logs (replace existing logs)~ TBD when span log-level can be configured
			- ~Integrate into health end-points for Event Sidecar (if sidecar is enabled)~ - TBD in future story
  			- [x] Helm 
       	         		- [x] Integrate event-sidecar into helm chart
    		        	- [x] Updated configuration for default.json in helm chart
        			- [x] Configuration in default.json (e.g. sidecar enabled, logging mode etc)
		- [x] position handler
    			- ~Logs (replace existing logs)~
			- ~Integrate into health end-points for Event Sidecar (if sidecar is enabled)~ - TBD in future story
  			- [x] Helm 
       	         		- [x] Integrate event-sidecar into helm chart
    		        	- [x] Updated configuration for default.json in helm chart
        			- [x] Configuration in default.json (e.g. sidecar enabled, logging mode etc)
		- [x] fulfil handler
    			- ~Logs (replace existing logs)~ TBD when span log-level can be configured
			- ~Integrate into health end-points for Event Sidecar (if sidecar is enabled)~ - TBD in future story
  			- [x] Helm 
       	         		- [x] Integrate event-sidecar into helm chart
    		        	- [x] Updated configuration for default.json in helm chart
        			- [x] Configuration in default.json (e.g. sidecar enabled, logging mode etc)
		- [x] timeout handler
			- ~Integrate into health end-points for Event Sidecar (if sidecar is enabled)~ - TBD in future story
			- [x] Test events being Recorded into EFK
    			- ~Logs (replace existing logs)~ TBD when span log-level can be configured
  			- [x] Helm 
       	         		- [x] Integrate event-sidecar into helm chart
    		        	- [x] Updated configuration for default.json in helm chart
        			- [x] Configuration in default.json (e.g. sidecar enabled, logging mode etc)
		- [x] get handler
			- [x] Integrate event-sdk
			- ~Integrate into health end-points for Event Sidecar (if sidecar is enabled)~ - TBD in future story
    			- ~Logs (replace existing logs)~ TBD when span log-level can be configured
  			- [x] Helm 
       	         		- [x] Integrate event-sidecar into helm chart
    		        	- [x] Updated configuration for default.json in helm chart
        			- [x] Configuration in default.json (e.g. sidecar enabled, logging mode etc)
		- [x] central services admin handler _PARTIALLY COMPLETE - Instrumentation to be moved to a new story_
			- ~Integrate event-sdk~ - TBD in future story
    			- [x] Import NPM dependency
			- ~Integrate into health end-points for Event Sidecar (if sidecar is enabled)~ - TBD in future story
			- ~Test events being Recorded into EFK~
    			- ~Logs (replace existing logs)~ TBD when span log-level can be configured
    			- ~Add Audits for beginning of receiving request for Admin-Events~
    			- ~Add Errors for both Internal vs External (e.g. errors - ?)~
    			- ~Traces for main span for Admin-Events~
  			- [x] Helm  (_Note: Added but disabled as the handler has not been instrumented_)
       	         		- [x] Integrate event-sidecar into helm chart
    		        	- [x] Updated configuration for default.json in helm chart
        			- [x] Configuration in default.json (e.g. sidecar enabled, logging mode etc) (_Note: Added but disabled as the handler has not been instrumented_)

**Acceptance Criteria**:
- [ ] Designs are up-to-date
- [x] Unit Tests pass
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment configs.
- [x] Event Framework integrated into ML-API-Adapter for Prepare and Fulfil flows
	- ~Ensure that components cannot operate without Sidecar functioning correctly when enabled~
	- ~Ensure that components will not startup without Sidecar when enabled~
	- [x] Sidecar can be disabled for local development and/or debugging purposes only
- [x] Helm Charts
	- [x] Deployment includes sidecar as part of deployment
	- [x] Deployment includes sidecar configuration
- Recording of Events are correctly being captured
    - ~Logs events into EFK~
    - [x] Audit events into EFK
    - [x] Trace events into APM (and EFK via APM)

## **Pull Requests**:
- [x] https://github.com/mojaloop/ml-api-adapter/pull/190
- [x] https://github.com/mojaloop/central-ledger/pull/403

## **Follow-up**:
- N/A

**Dependencies**:
- [x] #804 
- [x] #824 

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
