### ISSUE TITLE
Create test for validating changes for scale to conform to the spec [In #949]

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#961]
## **Goal**:
As a Hub Operator
I want to _validate a mojaloop deployment for scale changes (done in #949)_
so that _there are no regressions because of it and future changes_

**Tasks**:
- [x] Postman tests for the scenario from issue #949 
- [x] Validate on current v7.4.3 (or another v7.x.x release)

**Acceptance Criteria**:
- [x] A test exists for the scenario #949 so that there are no regressions and a scale / precision of 4 is supported on the minor currency part (4 digits after the decimal)

## **Pull Requests**:
- [x] https://github.com/mojaloop/postman/pull/xx

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
