### ISSUE TITLE
Validating error codes on incoming PUT /error requests

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#964]
## **Goal**:
As a Hub Operator
I want to _validate error codes on /error requests _
so that _only error codes defined in the Specification and Scheme are allowed_

**Tasks**:
- [X] Confirm where the validation needs to happen (ml-api-adapter? prepare-handler?)
- [ ] ~Implement validation with regex giving room for Scheme custom errors~ - will reuse existing validateFSPIOPErrorCode()
- [X] Create validateFspioperrorCodeByCategory hapi plugin at central-services-error-handling at onPreHandler during request lifecycle to validate payload. Leverage existing validateFSPIOPErrorCode() at factory.js. If validation fails call response.takeover()
- [X] Apply validateFspioperrorCodeByCategory hapi plugin at central-services-error-handling at ml-api-adapter only at the error callback route

**Acceptance Criteria**:
- [X] On /error PUT calls into the Switch, only error codes that are defined in the Specification or by a Scheme are allowed and those that are not, are rejected
- [X] Designs are up-to date
- [X] Unit Tests pass
- [X] Integration Tests pass
- [x] Code Style & Coverage meets standards
- ~[ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.~

## **Pull Requests**:
- [x] https://github.com/mojaloop/central-services-error-handling/pull/72
- [x] https://github.com/mojaloop/ml-api-adapter/pull/206

## **Follow-up**:
- N/A

**Dependencies**:
- [x] https://github.com/mojaloop/central-services-error-handling/pull/72 

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by gibaros** [comment]
@mdebarros @rmothilal Ready for early review.

**Comment by gibaros** [comment]
Closing issue after work session with Rajiv where both PRs were reviewing and merged.
