### ISSUE TITLE
Refactoring for duplicate checking on transaction-requests

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#965]
## **Goal**:
As a Mojaloop Hub
I want to _ensure duplicates are handled in a standardized way in transaction-requests service_
so that _Idempotency on these calls can be ensured_

Follows-up on and uses #904 

**Tasks**:
- [ ] Provide full knex script for DDL changes and data migration as needed
- [ ] Change codebase to work with the introduced DB schema changes
- [ ] Resolve execution issues with migration scripts
- [ ] Execute data migration script in a transaction and according to a config
- [ ] Implement Request Duplicate Check for POST calls
- [ ] Implement Request Duplicate Check for PUT calls (including PUTs on /error)
  - [ ] Addition migration scripts for changes in transferError related tables
- [ ] Test data migration script on sample data and provide notes on its usage
- [ ] Fix tests
  - [ ] Unit tests
  - [ ] Integration tests as needed
  - [ ] Ensure coverage is met
- [ ] Update documentation with the updated DB and other designs

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] Duplicate handling on POST calls is standardized and definitive
- [ ] Duplicate handling on PUT calls is standardized and definitive
- [ ] Aligned with [DA decision](https://github.com/mojaloop/design-authority/issues/29)
  - [ ] DA Suggestion ([link](https://github.com/mojaloop/project/issues/780#issuecomment-519433883)) to be addressed
- [ ] Codebase aligned to the design

**Pull Requests**:
- [ ] TBD

**Reference**:
- [x] #904 

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Not applicable, as it is a pass-through service now.
