### ISSUE TITLE
Refactoring for duplicate checking on funds-in/out service

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#966]
## **Goal**:
As a Mojaloop Hub
I want to _ensure duplicates are handled in a standardized way on Funds In/Out services_
so that _Idempotency on these calls can be ensured_

Follows-up on and uses #904 

**Tasks**:
- [x] Change codebase to work with the introduced DB schema changes [@ggrg]
- [x] Implement Request Duplicate Check for POST calls [@ggrg]
- [ ] ~Implement Request Duplicate Check for PUT calls (including PUTs on /error)~
- [x] Fix tests [@ggrg]
  - [x] Unit tests [@ggrg]
  - [x] Integration tests as needed [@ggrg]
  - [x] Ensure coverage is met [@ggrg]
- [ ] ~Update documentation with the updated DB and other designs~

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] Duplicate handling on POST calls is standardized and definitive
- [x] Duplicate handling on PUT calls is standardized and definitive
- [x] Aligned with [DA decision](https://github.com/mojaloop/design-authority/issues/29)
  - [x] DA Suggestion ([link](https://github.com/mojaloop/project/issues/780#issuecomment-519433883)) to be addressed
- [x] Codebase aligned to the design

**Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/423

**Reference**:
- [x] #904 

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
