### ISSUE TITLE
Event Framework - event-stream-processor refactoring and dependency updates

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#969]
## **Goal**:
As a `Developer` I want to refactor the code and update dependency of event-stream-processor module  so that `all latest Mojaloop libraries and good practices are up-to-date`

**Tasks**:
- [x] Change the config loader to use the same as the rest of Mojaloop stack [@vgenev]
- [x] Update all shared libraries to their latest versions [@vgenev]
  - [x] Change the kafkaconsumer logic to latest best practices [@vgenev]
- [x] Change healthcheck endpoint to use the mojaloop shared library healthcheck endpoint  [@vgenev]
  - [x] Create healthcheck server [@vgenev] 
  - [x] Create healthcheck methods to verify services (broker) [@vgenev] 

**Acceptance Criteria**:
- [x] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vgenev 
- QA/Review: @mdebarros
