### ISSUE TITLE
Upgrade the version of Node for central-directory

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#97]
**Goal**:
As a developer I would like to upgrade the version of Node of central-directory so that we can make use of new features and upgrade the dependencies for performance and stability

**Tasks**:
- [ ] 

**Acceptance Criteria**:
- [x] Upgraded node from 6.5.0 to 8.9.4 LTS
- [x] Ensure NPM dependencies are upgraded and compiles
- [x] Ensure all included tests pass

**Dependencies**:
- None currently
