### ISSUE TITLE
Error Framework: Adopt & Integrate Mojaloop SDK Error Handling to Bulk-API-Adapter

### ISSUE THREAD

**Issue by gibaros** [mojaloop/project#970]
## **Goal**:
As a `Hub Operator`, I want to `implement a standard Error Handling framework and apply it to the Bulk-API-Adapter service` so that `errors are consistent throughout the Mojaloop stack for both the Switch and the FSPs`.

**Tasks**:
- [x] Integrate the [Error Handler](https://github.com/modusbox/mojaloop-sdk-standard-components/blob/master/src/lib/errors/index.js) from the standard components lib into **Bulk-API-Adapter**
- [ ] Refactor tests (unit and integration) that use previous Error object in favor of FSPIOPError
  - [x] Validate that hard coded Errors are being created and replaced with FSPIOErrors
  - [x] Validate that errors are correct per API Specification, eg:
https://github.com/mojaloop/central-ledger/blob/8a34ae14129b8a455703af56fa793cd23fcd1ea5/test/integration/handlers/handlers.test.js#L169
- [ ] ~Update Unit Tests~
- [ ] ~Update Integration Tests~
- [x] Tested end to end prepare and fulfill via Postman

**Acceptance Criteria**:
- [ ] ~Unit Tests pass~
- [ ] ~Integration Tests pass~
- [x] Code Style meets standards
- [ ] ~Coverage meets standards~
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [x] Mojaloop SDK Standard Components for Error handling have been integrated into the Bulk-API-Adapter service
- [ ] Bulk-API-Adapter component produces ML API compliant Specification errors

## **Pull Requests**:
- [x] https://github.com/mojaloop/bulk-api-adapter/pull/5

## **Follow-up**:
- [ ]

**Dependencies**:
- https://github.com/mojaloop/project/issues/957

## **Accountability**:
- Owner: @gibaros 
- QA/Review: @mdebarros @ndonnan @rmothilal

**Comment by gibaros** [comment]
PR https://github.com/mojaloop/bulk-api-adapter/pull/5 reviewed, merged and closed...closing this issue.
