### ISSUE TITLE
QA: Postman OSS-API-Tests collection

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#971]
## **Goal**:
As a Community member
I want to have the postman test collections other than the golden path
so that they can be used to test various features for higher coverage

**Tasks**:
- [x] Create a copy of OSS-API-Tests postman collection(https://github.com/mojaloop/postman) and separate the tests to create a separate tests with the active ones 
  - [ ] Mojaloop-API
    - [x] participants
      - [x] MSISDN
      - [x] GET - Raised bug (https://github.com/mojaloop/project/issues/1243 - fixed , https://github.com/mojaloop/project/issues/1244,)
      - [x] POST - Raised bug  ( https://github.com/mojaloop/project/issues/1246 - fixed, https://github.com/mojaloop/project/issues/1249 - fixed)
    - [ ] ~parties`
    - [x] quotes
      - [x] GET - fixed bug (https://github.com/mojaloop/project/issues/1173)
      - [x] POST - (https://github.com/mojaloop/project/issues/1178 resolved)
      - [ ] ~PUT~
    - [ ] ~transfers~

**Acceptance Criteria**:
- [x] A sub-set of the OSS API tests collection is identified based on active tests and created as a separate collection to be run regularly with Helm releases along with the Golden path collection for below scenarios (or resources)
  - [x] Mojaloop-API
    - [x] participants
      - [x] MSISDN
      - [x] GET - Raised bug (https://github.com/mojaloop/project/issues/1243 - fixed , https://github.com/mojaloop/project/issues/1244,)
      - [x] POST - Raised bug  ( https://github.com/mojaloop/project/issues/1246 - fixed, https://github.com/mojaloop/project/issues/1249 - fixed)
    - [x] quotes
      - [x] GET - fixed bug (https://github.com/mojaloop/project/issues/1173)
      - [x] POST - (https://github.com/mojaloop/project/issues/1178 resolved)

## **Pull Requests**:
- [x] https://github.com/mojaloop/postman/pull/84
- [x] https://github.com/mojaloop/postman/pull/96

## **Follow-up**:
- [x] https://github.com/mojaloop/project/issues/1265

**Comment by amarmodus** [comment]
update POST /Quotes - invalid payer party identifier and  payee party identifier requests

**Comment by amarmodus** [comment]
All screenshots are attached in the https://github.com/mojaloop/postman/pull/96
