### ISSUE TITLE
Migrate from SonarCube to SonarCloud

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#972]
## **Goal**:
As an `OSS Maintainer`, I want to `migrate from SonarCube to SonarCloud` to `reduce costs`.

SonarCloud is now available as a free service that we can take advantage of in order to cut down on costs. It should replace all of our needs with SonarCube, so we just need to double check, and make the switch over.

It would also be wise to conduct a basic risk assessment - do we expect SonarCloud to stay free forever? What potential impacts might this have downstream for Mojaloop implementers?

**Tasks**:
- [ ] Evaluate whether or not SonarCloud will meet the current needs served by SonarCube
- [ ] Set up CI for SonarCloud and apply for all projects currently on SonarCube
- [ ] Shut down any SonarCube instances

**Acceptance Criteria**:
- [ ] Code Style & Coverage meets standards
- [ ] CI/CD Jobs remain successful
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: TBC

**Comment by lewisdaly** [comment]
I spoke more with @elnyry about this one, and it is probably not worthwhile. The time taken to migrate from a self-hosted SonarCube instance to the SonarCloud will likely cost far more than running the t2.medium instance ($33/month on demand), and sticking with the self-hosted version of SonarCube doesn't introduce a dependency on a 3rd party service.

@kjw000 would like to hear your thoughts before we close this one out

**Comment by lewisdaly** [comment]
Closing as out of scope ATM, will review this along with the "code security initiative"
