### ISSUE TITLE
Update Helm Chart meta-data to support better upgradability

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#974]
## **Goal**:
As a `Hub Operator`, I want to `ensure that Helm charts have the correct metadata labels` so that `upgrades are better supported`.

**Tasks**:
- [x] Update all Helm Chart template to use latest Helm best-practices for label tags introduced with Helm v2.0 (currently v1.0 tags were being used):
    - [x] ml-api-adapter
    - [x] central-ledger
    - [x] central-settlements
    - [x] central-event-processor
    - [x] bulk-api-adapter
    - [x] qouting-service
    - [x] account-lookup-service
    - [x] simulator
    - [x] email-notifier
    - [x] event-stream-processor
- [x] Update helm charts to correctly set the knex connection pools

**Acceptance Criteria**:
- [ ] QA Framework Golden Path Test pass
- [ ] Helm Charts are upgradable

## **Pull Requests**:
- [ ] https://github.com/mojaloop/helm/pull/209

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
