### ISSUE TITLE
Instrumenting, Logging for Event framework on central-ledger, ml-api-adapter - 3

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#975]
## **Goal**:
As a Hub Operator
I want to _integrate Event Framework into Mojaloop components_ so that
_all events (errors, general, etc) can be audited and traced appropriately for Prepare and Fulfil flows_

This applies to central-ledger and ml-api-adapter

**Tasks**:
- [ ] Event Framework
  - [ ] Enhance central services shared
    - [ ] Add to the README, a description of the 'sampled' route tag for span creation
    - [ ] Integrate SDK for logging
      - [ ] ml-api-adapter - API
        - [ ] Logs (replace existing logs)
      - [ ] ml-api-adapter - Notifications
        - [ ] Logs (replace existing logs)
- [ ] Event Framework
	- [ ] Integrate SDK for logging
		- [ ] prepare handler
			- [ ] Logs (replace existing logs)
			- [ ] Integrate into health end-points for Event Sidecar (if sidecar is enabled)
		- [ ] position handler
			- [ ] Logs (replace existing logs)
			- [ ] Integrate into health end-points for Event Sidecar (if sidecar is enabled)
		- [ ] fulfil handler
			- [ ] Logs (replace existing logs)
			- [ ] Integrate into health end-points for Event Sidecar (if sidecar is enabled)
		- [ ] timeout handler
			- [ ] Logs (replace existing logs)
			- [ ] Integrate into health end-points for Event Sidecar (if sidecar is enabled)
		- [ ] get handler
			- [ ] Logs (replace existing logs)
			- [ ] Integrate into health end-points for Event Sidecar (if sidecar is enabled)
  			- [ ] Helm
			    - [ ] Enable Sidecar config
		- [ ] central services admin handler 
			- [ ] Integrate event-sdk
			- [ ] Integrate into health end-points for Event Sidecar (if sidecar is enabled)
			- [ ] Test events being Recorded into EFK
    			- [ ] Logs (replace existing logs)
    			- [ ] Add Audits for beginning of receiving request for Admin-Events
    			- [ ] Add Errors for both Internal vs External (e.g. errors - ?)
    			- [ ] Traces for main span for Admin-Events
  			- [ ] Helm
			    - [ ] Enable Sidecar config

**Acceptance Criteria**:
- [ ] Designs are up-to-date
- [ ] Unit Tests pass
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment configs.
- [ ] Event Framework integrated into ML-API-Adapter for Prepare and Fulfil flows
	- [ ] Ensure that components cannot operate without Sidecar functioning correctly when enabled
	- [ ] Ensure that components will not startup without Sidecar when enabled
- [ ] Helm Charts
	- [ ] Deployment includes sidecar as part of deployment
	- [ ] Deployment includes sidecar configuration
- Recording of Events are correctly being captured
    - [ ] Logs events into EFK
    - [ ] Audit events into EFK
    - [ ] Trace events into APM (and EFK via APM)

## **Pull Requests**:
- N/A

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
Dependency on https://github.com/mojaloop/project/issues/895

**Comment by elnyry** [comment]
@mdebarros @vgenev - is there an overlap between this and #1289 (or already closed stories for that matter) ?
