### ISSUE TITLE
Event Framework - Enhance handling of incoming HTTP API requests with W3C Trace Headers

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#976]
## **Goal**:
As a `Hub Operator`, I want to `ensure that requests received from FSP with W3C Trace Headers on initial requests (e.g. Prepare, Quotes, and Parties) correctly handles the tracestate header field` so that `Hub systems can receive an out-of-switch Trace context, create its own internal trace, and respond appropriately with a follow-up tracestate continuing the original FSP trace as per W3C specification`

**Tasks**:
- [ ] Update Event-SDK Hapi Plugin to properly manage incoming W3C Trace Headers (traceparent & tracestate) as per the W3C specification
- [ ] Ensure that callbacks respond with the appropriate W3C Trace Header response (i.e. tracestate containing a reference to the original trace information send from the FSP)

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] WC3 Headers are handle as per the [W3C Trace specification](https://mojaloop.io/documentation/mojaloop-technical-overview/event-framework/#411-wc3-http-headers)

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
