### ISSUE TITLE
Event Framework - Event Framework Documentation

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#978]
## **Goal**:
As a `Hub Operator`, I want to `Event Framework Documentation/Guidelines for each stakeholder involved in the end-to-end trace` so that `each stakeholder understands their responsibilities and implementation requirements`

**Tasks**:
- [x] Ensure event framework designs and documentation is up-to-date and reflects the implementation [@vgenev]
- [ ] ~Create Hub Operator documentation/guides on how to:~
    - [ ] ~Monitoring events/transactions~
    - [ ] ~Troubleshoot issues~
    - [ ] ~Trace requests/transactions~
    - [ ] ~Information on types of Events~
- [x] Create FSP Participant documentation/guides on how to:
    - [x] Create W3C Trace Headers for initial requests (which is optional - although it may be mandatory based on shema rules)
    - [x] Handle incoming W3C Trace Headers and how they should use this information on the Callback requests (which is also optional - although it may be mandatory based on shema rules)

**Acceptance Criteria**:
- [ ] Published documentation for Hub Operators on how to use the Event Framework/Visualisation dashboards provided by EFK/APM for Operational Monitoring, Management & Troubleshooting
- [ ] Published documentation on how FSP Participants can generate W3C Trace headers on initial requests, how they should process incoming headers and send Callbacks with the appropriate response headers as per W3C Trace specification

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- https://github.com/mojaloop/project/issues/1427

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC
