### ISSUE TITLE
Dependency conflict central-services-shared and central-services-stream

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#979]
## **Goal**:
As a developer I want to ensure that there is no version conflicts between dependencies so that the testing of APIs happens quickly and effectively and mocking of services can occur. Also the central-services-shared library has become bulky and should be more lightweight.

**Tasks**:
- [x] Move all kafka util code to central-services-stream
- [x] Add encoding/decoding library to central-services-shared from central-services-stream
- [x] Update tests in central-services-shared
- [x] Update tests in central-services-stream
- [x] Update central-ledger (@ggrg)
- [x] Update ml-api-adapter
- [x] Update account-lookup-service (@oderayi)
     - [x] central-services-shared
     - [x] central-services-stream
- [x] Update quoting-service~ (@oderayi - Quoting Service is unaffected. Validated OK.)
     - [x] central-services-shared
- [x] Update central-settlement
- [x] Update bulk-api-adapter (@oderayi - Already fixed by https://github.com/mojaloop/bulk-api-adapter/pull/5)
     - [x] central-services-shared
     - [x] central-services-stream
- [x] Update simulator (@oderayi - Simulator is unaffected. Validated OK.)
     - [x] central-services-shared
- [x] Update event-sidecar (@oderayi - Event Sidecar is unaffected. Validated OK.)
     - ~central-services-shared~
     - [x] central-services-stream

**Acceptance Criteria**:
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] All APIs function as previously did

**Notes** 
- The streaming library now consists of Producer and Consumer Utilities
- encoding and decoding of payloads have been moved out of streaming library into shared library
- Please ensure that central-services-logger is used for logging instead of central-services-shared

## **Pull Requests**:
- [x] https://github.com/mojaloop/account-lookup-service/pull/99
- [x] https://github.com/mojaloop/simulator/pull/82
- [x] https://github.com/mojaloop/event-sidecar/pull/9
- [x] https://github.com/mojaloop/bulk-api-adapter/pull/9

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rmothilal 
- QA/Review: @mdebarros @rmothilal
