### ISSUE TITLE
QA: Sprint8.1 - Golden path regression collection failures and issues running locally

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#982]
**Summary**:
1. Golden path test collection is not able to run in local machine where as able to run in newman environment (in the box)
2. Golden path test collection got 36 failures in the cron job.

**Tasks**:
- [x]  Redeployed all services and rerun the regression postman collection cron job
- [x] Find all the request which are stopping local golden path testing
- [x] Raise bug issue for transfer status steps failing w.r.t simulator - https://github.com/mojaloop/project/issues/1002 

**Severity**:
(Medium)

**Priority**:
(Medium)

**Expected Behavior**
Golden path test collection - runs in local collection and in box with 100% pass.

**Steps to Reproduce**

Cron job :
1. Make sure vpn.mojaloop.live is connected.
2. connect to box
3. Cat runGolden_Path.sh
4. Run the script locally without the broadcast first - ‘0’ 
5. All test should pass

**Specifications**
  - Component (if known):
  - Version: 
  - Platform: Dev1
  - Subsystem:
  - Type of testing: postman api testing
  - Bug found/raised by: @amarmodus , @elnyry 

## Pull Requests
- [x] https://github.com/mojaloop/postman/pull/45
- [x] https://github.com/mojaloop/postman/pull/46

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by amarmodus** [comment]
2.Golden path test collection got 36 failures in the cron job. [Once redeployed, Golden path regression test passed with no further failures - 
https://s3-us-west-2.amazonaws.com/mojaloop-oss-qa-results/report-1569279601.html]

**Comment by amarmodus** [comment]
For the local failures, following test were failing with errors such as 

Get Party Receiver - happy path Quote and Happy path send Quote
JSONError | Unexpected token u in JSON at position 0

Record Funds In - prepare transfer status
JSONError | No data, empty input at 1:1

**Comment by amarmodus** [comment]
mojaloop/postman#45 - reviewed
mojaloop/postman#46 - review done and merged
