### ISSUE TITLE
Functional + Integration tests for mojaloop-simulator

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#983]
## **Goal**:
As an `OSS Maintainer` I want to `write and enable functional and integration tests for the mojaloop-simulator` to `ensure the codebase is well checked and maintained by our CI/CD pipelines.`

**Tasks**:
- [ ] Write and enable the following tests in CI
    - [ ] Integration tests
    - [ ] Functional tests

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Since the mojaloop-simulator uses in-memory sqlite for tests, many of the tests we would cover with 'integration' tests have already been written and run as unit tests.

Perhaps this ticket should be closed, as I no longer think it is relevant (or at least not at the moment)

**Comment by elnyry-sam-k** [comment]
Closing as per above comment; also checked that integration tests are present. example run: https://app.circleci.com/pipelines/github/mojaloop/mojaloop-simulator/496/workflows/57498bcd-d684-4143-a787-e0929d30fb7d
