### ISSUE TITLE
Investigate nested package.json files for dependabot, license-scanner

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#984]
## **Goal**:
As a `OSS Maintainer` I want to `ensure that our tools can handle nested package.json files` so that `we can confirm our tooling will still work correctly`.

As we are seeing some repos with nested `package.json` files, (see mojaloop-simulator), we need to ensure our tools are able to handle these repos appropriately

**Tasks**:
- [x] The mojaloop-simulator project contains nested package.json files (inside ./src/lib). We need to evaluate how this will affect, and make the necessary changes to:
  - [x] license-scanner
  - [ ] dependabot

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: TBC

**Comment by lewisdaly** [comment]
It appears that all dependencies in the nested `package.json` files get strung together in the `package-lock.json` file in `./src`, and all dependencies can be found in the `./src/node_modules` directory.

So this at least means that the license scanner will work as expected.

**Comment by lewisdaly** [comment]
This looks to be the same for the github security scans and updates, so I'll go ahead and close this ticket.
