### ISSUE TITLE
Sending notification to the Payees regarding finalization of transfers based on config in bulkTransfers

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#985]
## **Goal**:
As a Switch implementer
I want to have the feature to send a notification to the Payees regarding finalization of a bulk transfer based on configuration so that it can be used to change the behavior of Switch regarding sending notifications to the Payees after finalizing a bulk transfer.

**Tasks**:
- [ ] Update designs to reflect changes to support both the modes
- [ ] Implement changes necessary to support this (sending notification or not)
- [ ] Update unit tests
- [ ] Run integration tests
- [ ] Update Helm charts for changes to `default.json`
- [ ] Update Transfer Sequence Diagrams to reflect config options
- [ ] Broadcast changes to default.json to the team
- [ ] Ensure Switch can be configured to or not to send notification to Payee by running writing and running appropriate tests

**Acceptance Criteria**:
- [ ] Designs are updated to reflect changes
- [ ] Sequence diagrams (transfers) are updated to reflect changes
- [ ] Unit tests are updated and pass
- [ ] Integration Tests pass
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment configs.
- [ ] Based on configuration the Switch can be configured to either send out a notification to the Payee on a completed transfer or not send out that notification (as per v1.0 of the Spec)

**Pull Requests**:
- [ ] TBA

**Follow-up**:
- N/A

**Dependencies**:
- N/A

**Accountability**:
- Owner: TBC
- QA/Review: @elnyry 

**Notes*:
- The idea is to support this mode so that it may be changed to behave this way based on the incoming message, based on a flag or specific field (probably in a future version of the Spec)

**Comment by elnyry-sam-k** [comment]
This is not needed for Bulk transfers in the current scope
