### ISSUE TITLE
License-scan followup: Remove dependencies, and scan production node_modules only

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#986]
## **Goal**:
As an OSS Maintainer
I want to tidy dependencies and ensure the license-scan scans production node_modules only
so that I can remove unused dependencies, and bad licenses from the codebase.

**Tasks**:
- [ ] remove dependencies to factor out `spdx-exceptions`, `taffydb`, `buffercursor`, `cycle`, and `xmldom` dependencies
(note: refer to the last license-scan summary [here](https://github.com/mojaloop/helm/releases/download/v7.4.3/license-summary.xlsx))
- [ ] add an `npm prune --production` step before the license scanner to ensure that devDependencies are not scanned
- Apply the above for:
  - [ ] account-lookup-service
  - [ ] central-directory
  - [ ] central-end-user-directory
  - [ ] central-ledger
  - [ ] central-settlement
  - [ ] ml-api-adapter
  - [ ] mock-pathfinder
  - [ ] simulator

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] https://github.com/mojaloop/account-lookup-service/pull/80
- [ ] https://github.com/mojaloop/central-ledger/pull/412
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Ok it turns out I was a little hasty with trying to remove `npm-run-all` in order to clean up the licenses.

The `npm run migrate` scripts for the account-lookup-service, central-ledger and possibly others.

Perhaps a follow up for this would be to find an alternative to `npm-run-all` that doesn't install the `spdx-exceptions` package as a dependency.

**Comment by lewisdaly** [comment]
Waiting for latest `central-ledger` release with `npm-check-updates` as a devDependency

**Comment by lewisdaly** [comment]
Waiting for latest `central-ledger` release with `npm-check-updates` as a devDependency

**Comment by lewisdaly** [comment]
Marking this as blocked for now, since we need to remove the `central-ledger` dependency from `central-settlements`
see: https://github.com/mojaloop/project/issues/647
