### ISSUE TITLE
QA - Validate/test bugfix 733, 742, 737 and 956 

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#987]
## **Goal**:
As a maintainer of the OSS codebase, QA 
I want to make sure that new releases are checked for regressions
so that releases are validated before being accepted or released to the public

This specific story is for writing regression postman tests for bugs #733, #742 and #737
so that it confirms the bugs are fixed

**Tasks**:
- [x] Tests for https://github.com/mojaloop/project/issues/733 [ @amarmodus ]
  - [x] Validate
- [x] Tests for https://github.com/mojaloop/project/issues/742 [ @amarmodus ]
  - [x] Validate
- [ ] ~Tests for https://github.com/mojaloop/project/issues/737 [ @? ]~ - will be covered in #1011 
  - [ ] ~Validate~
- [ ] ~Tests for https://github.com/mojaloop/project/issues/956 [ @? ]~ -  - will be covered in #1011
  - [ ] ~Validate~
- [x] Tests for issue: https://github.com/mojaloop/project/issues/935 - Already covered in Golden Path
  - [x] Validate on Dev1 (or Dev2)

**Acceptance Criteria**:
- [x] Regression tests in postman are available for bugs:
  - [x] #733
  - [x] #742
  - [x] #935 
- [ ] These tests are verified on Dev1 (and Dev2 environments) before they're merged.

![image](https://user-images.githubusercontent.com/53434415/66559863-0e376a80-eb4e-11e9-9dce-40881d29a8d5.png)

## **Pull Requests**:
- [ ] https://github.com/mojaloop/postman/pull/43

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @amarmodus 
- QA/Review: @sri-miriyala @elnyry

**Comment by elnyry** [comment]
Added 2 more bugs for validation and increased estimate accordingly
