### ISSUE TITLE
Bugs 6-9, 14 from Issue#9 of Quoting-Service

### ISSUE THREAD

**Issue by gibaros** [mojaloop/project#990]
## **Goal**:
As a Hub Operator of a Mojaloop Switch
I want to respond with an HTTP error code for requests that do not follow the (Swagger) API Definition Data Model and or data validation agains DB so that only valid requests are accepted and processed in the Switch

**Tasks**:
- [x] Implement Scheme and DB validations based on missing items as per list [here](https://github.com/mojaloop/quoting-service/issues/9) bugs 6-14
- [x] Bug 6 - Validate content type header
- [x] Bug 7 - Validate missing mandatory fields: quoteid, transactionid, payer partyIdType, payee partyIdType, payer partyIdentifier, payee partyIdentifier. Follow up session will take care of quoteid, transactionid and other missing fields were non an issue.
- [x] Bug 8 -  sending duplicate quoteid request with modified data is not returning error 3106, it was tested and found a non issue as expected 3106 is being returned at error callback
- [x] Bug 9 - Validate missing destination FSP results in 3201, tested currently missing field is detected, but instead of expected 3201, 3100 is being returned
- [x] Bug 14 - Validate incorrect version, not showing response code 406
- [x] Asses bug still occur and address them
- [x] Update HeaderValidation Plugin errorInformation response as no 2001 Internal Server Error should be returned to outside client callers. For example in the case of "Unsupported Media Type" for when a non-valid content-type header is received an error code of 3100 should be used.

**Acceptance Criteria**:
- [x] Designs are up-to date
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- [x] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.

## **Pull Requests**:
PRs to fix bugs 6,7,8,9,14
- [x] https://github.com/mojaloop/quoting-service/pull/57
- [x] https://github.com/mojaloop/central-services-error-handling/pull/82
- [x] https://github.com/mojaloop/quoting-service/pull/61

## **Follow-up**:
- [x] Create issue for 7a and 7b from [here](https://github.com/mojaloop/quoting-service/issues/9), POST/Quotes Sending quote with quoteid or transactionid missing mandatory fields error not displayed correctly due to hapi regex not properly handling empty quoteid value. Potential fix at hapi regex.
- [x] Create issue for bugs 10-13

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @gibaros 
- QA/Review: @mdebarros @rmothilal

**Comment by gibaros** [comment]
For reference, bugs to review if still exist and address from [here](https://github.com/mojaloop/quoting-service/issues/9) are:

6. Send Quote Request - 06- Validate Information Type Syntax
  6.a Send a Quote request with malformed content type
  6.b POST/Quotes - Sending a quote with invalid transaction type field - No Error 5101 is shown
    - The quote response should:
       - Validate the information and return response code 406 in case the following informations is malformed: 
         - Content Type
       - Error code: 3101
       - Error displayed: "Malformed Syntax"
       - No quote should be created
7. POST/Quotes Sending quote with any missing mandatory fields: quoteid, transactionid, payer partyIdType, payee partyIdType, payer partyIdentifier, payee partyIdentifier error not displayed correctly
    - The quote response should:
      - Validate the information and return response code 404 in case the following informations is missing: 
        - quoteid
        - transactionid
        - payer partyIdType
        - payee partyIdType
        - payeePartyIdentifier
        - payerPartyIdentifier
       - Error Code: 3107
       - Error description displayed: "Missing mandatory extension parameter"
       - No quote should be created
8. POST/Quotes - sending duplicate quoteid request with modified data is not returning error 3106
    - The quote response should:
      - Validate the information and return response code 404 in case the quoteId used is the same 
      - Error Code 3106
      - Error description displayed: "The quoteId is not valid for this request"
      - No quote should be created
9. POST/Quotes Not showing Error 3201 Destination FSP cannot be found
    - The quote response should:
    - Validate the information and return response code 404 in case the FSPID is incorrect
    - Error Code 3201
    - Error description displayed: "Destination FSP cannot be found"
    - No quote should be created
10. POST/Quotes - sending quote with non-existent payeePartyIdentifier - Party Not found Error code 3204
    - The quote response should:
      - Validate the information and return response code 404 in case the payeePartyIdentifier doesn't exists.
      - Error Code 3204
      - Error description displayed: "Party Not found"
      - No quote should be created
11. PUT/Quote - sending callback without condition field
    - Sending a PUT/quotes with no condition field should give an error message notifying about the missing information
12. Send Quote Request -13 - Validate the expire time with duplicate quote ID
  12.a Sending Duplicate Quote ID after expiry time - Not showing error
  12.b Sending Duplicate Quote ID within expiry time - Not showing error
    - Sending a POST/quote with correct body and headers.
      - There should successful quote.
      - Send a new quote using the same QuoteID as in step 1
      - An error due quote ID duplication should appear.
13. Get Quotes: Validate Header
  13.a GET/Quotes - Missing Accept header - Not showing Response code 400
  13.b GET/Quotes - Missing FSPIOP-Source header - Not showing Response code 400
  13.c GET/Quotes - Missing Date header - Not showing Response code 400
    - Get /quotes request with errors in the header 
    - The request should be rejected giving 400 response code and error code and error msg in the response body.
14. POST/quotes - Sending quote with incorrect version - not showing response code 406
    - Send in Post /quotes endpoint a not supported version in Switch, that call should response:
      - Validate the version in header and return a response code 406
      - Error Code 3001
      - Error Description displayed: " Unacceptable version requested"

**Comment by gibaros** [comment]
Status update:

6: Can't find where the 2001 is been thrown
valid - application/vnd.interoperability.quotes+json;version=1.0
3101, malformed - invalid - application/json
2001, Internal Server Error, - Unsupported Media Type application/xml

7: missing: - misleading 202 or 500 with incorrect 2001 is being returned
a, quoteid - 202, simulator detected no quoteid
b, transactionid - 202, simulator detected no transactionid
c, payer partyIdType - 500, 2001, "Internal server error - child \"Party\" fails because [child \"PartyIdInfo\" fails because [child \"PartyIdTypeEnum\" fails because [\"PartyIdTypeEnum\" must be one of [MSISDN, EMAIL, PERSONAL_ID, BUSINESS, DEVICE, ACCOUNT_ID, IBAN, ALIAS]]]]"
d, payerPartyIdentifier - 500, 2001, "Internal server error - child \"Party\" fails because [child \"PartyIdInfo\" fails because [child \"PartyIdentifier\" fails because [\"PartyIdentifier\" is not allowed to be empty]]]"
e, payee partyIdType
f, payeePartyIdentifier
*NOTE: 7c-e and 7d-f - error does not distinguishes between payer and payee

8: duplicate quoteid does not return an error and 202 and no error at logs

9: Simulator and quoting-service show correct error, but does not makes it to Postman response

10: does not return an error and 202 and no error at logs

11: Need a PUT request sample

12: Where is the expiry time sent?

13: 11: Need a GET request sample
Error at simulator not found

14: Works! Fixed by application of HeaderValidation:  406

{
    "errorInformation": {
        "errorCode": "3001",
        "errorDescription": "Unacceptable version requested - Client supplied a protocol version which is not supported by the server"
    }
}

**Comment by gibaros** [comment]
PRs listed at Pull Requests session:

mojaloop/quoting-service#57
mojaloop/central-services-error-handling#82

are ready for their final review per our last work session.

**Comment by gibaros** [comment]
Bugs 9-9 and 14 were addressed with code changes and the corresponding PRs have been merged and closed.
