### ISSUE TITLE
Complete implementing enhanced health checks on core services - 2

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#991]
## **Goal**:
As a Hub Operator
I want to make use of the enhanced health checking mechanism on core services
so that more detailed health checks can be done and necessary actions taken based on those

**Tasks**:
- [x] Implement enhanced health checks on central-settlement
- [x] Implement enhanced health checks on quoting-service (pending v8.1.0 release - PR: https://github.com/mojaloop/project/issues/991)
- [x] Implement enhanced health checks on transaction-requests-service
- [x] Implement enhanced health checks on bulk-api-adapter
- ~Implement enhanced health checks on mojaloop-simulator~ `mojaloop-simulator` uses Koa and so can't be done for now as enhanced health check is implemented only for Hapi in `central-services-health`. 

**Acceptance Criteria**:
- [x] Unit Tests pass
- [x] Integration Tests pass
- [x] Code Style & Coverage meets standards
- ~Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.~ No change was required to default.json
- [x] Enhanced health checking is now available for 
  - [x] central-settlement
  - [x] quoting-service
  - [x] transaction-requests-service
  - [x] bulk-api-adapter
  - ~mojaloop-simulator~ Not feasible now as service uses Koa

## **Pull Requests**:
- [x] https://github.com/mojaloop/project/issues/991
- [x] https://github.com/mojaloop/bulk-api-adapter/pull/7

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Notes**
Current status of health checks [Thanks to Amar] 
```
http://dev1-central-settlement.mojaloop.live/health
{
"statusCode": 404,
"error": "Not Found",
"message": "Not Found"
}
http://dev1-ml-api-adapter.mojaloop.live/health
{
"status": "OK",
"uptime": 226202.55,
"startTime": "2019-09-26T08:50:15.220Z",
"versionNumber": "7.4.1",
"services": []
}
http://dev1-account-lookup.mojaloop.live
{
"status": "OK",
"uptime": 226665.792,
"startTime": "2019-09-26T08:58:44.938Z",
"versionNumber": "7.4.0",
"services": []
}
http://dev1-quoting-service.mojaloop.live/health
{
"status": "OK"
}
http://dev1-simulator.mojaloop.live/health
{
"status": "OK"
}
```
