### ISSUE TITLE
Helm Release v8.1.0: Support QA, testing, Debugging, Fixes Mojaloop pre-releases / releases in Sprint 8.1

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#992]
## **Goal**:
As a ML OSS Code base maintainer
I want to _validate and make a release in PI8 (Sprint8.1) that is successfully validated by the available Golden path tests_
so that _down stream entities can take and use a version of Mojaloop Switch services bundle thats tested and contains latest features and enhancements (added in PI7 and PI8 so far)_ 

This specific story is for making necessary changes for supporting Deployment, QA, Debugging, Fixes, Integration and performing end-to-end testing for all the changes made since v7.4.3 of Helm

**Tasks**:
- [x] Deployment of updated Helm on Dev2 envt [ @mdebarros @elnyry ]
- [x] Validation using Golden path regression tests etc on Dev2 [ @amarmodus @elnyry ]
- [x] Identify issues with QA Scripts - fix them and retest [ @amarmodus ]
- [x] Identify issues with Bugs, log them and have tea resolve them - retest once changes are made  [ @amarmodus + team]
- [x] Fix issues in quoting service [@rmothilal ]
- [x] Fix notification issue for transfer that fails because of breaching NDC test case [@ggrg ]
- [x] ExtensionList field generated by GET /transfers response (PUT call) using wrong format 
- [x] Release of v8.1.0 of Helm after iterating through issues/deployments/QA [ @elnyry ]
- [x] Fix issue with CI/CD [@elnyry  ]
- [x] Fix broken release after using new 8.1.0 [@mdebarros ]

**Acceptance Criteria**:
- [x] Helm v8.1.0 is deployed on AWS Dev2 envt without issues
- [x] QA (Golden path) on deployments done on AWS dev2 environment is done
- [x] Bugs are logged based on observations, failures
- [x] Bugs logged are fixed to make subsequent releases in individual services (or Helm)
- [x] All the changes needed for supporting v8.1.0 of Helm (List out major changes in release notes once release is ready)

**Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/209

**Follow-up**:
- https://github.com/mojaloop/helm/pull/210

**Dependencies**:
- [ ] TBD

**Accountability**:
- Owner: @mdebarros @elnyry @rmothilal @ggrg 
- QA/Review: DA, Core team
