### ISSUE TITLE
Adopt Oracle Shared Library donated - Part1

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#993]
## **Goal**:
As a ML OSS Codebase maintainer
I want to adopt the oracle-shared-library donated and make changes necessary
so that the oracle-shared-library is included as part of ML OSS Space

**Tasks**:
- [x] Review provided codebase for the oracle-shared-library
- [x] Update License files to include the Mojaloop OSS License
- [x] Identify changes needed to get running “as-is”
- [x] Generalize the naming to make sure its Open Source compatible
- [x] Identify & address content in Docker files that’s specific to the donor - None found
- [x] Document findings and discuss with the team
- [x] Remove node_modules and .vscode directories
- [x] Update .gitignore
- [x] Remove coverage directory and non functional eslint config
- [x] Add standard lint checking
- [x] Update circleci configuration
- [x] Update README to reflect module name change
- [x] Updated package.json to include correct author
- [x] Remove start from node scripts
- [x] Replace istanbul with nyc since it's no longer supported
- [x] Add pre-commit hooks for linting, latest dependency versions and tests in package.json
- [x] Update dependencies to latest versions to fix audit vulnerabilities found

**Acceptance Criteria**:
- [x] OSS standards have been applied where applicable.

## **Pull Requests**:
- [x] https://github.com/mojaloop/oracle-shared-library/pull/2

## **Follow-up**:
- [ ] TBD

**Dependencies**:
- [ ] N/A

## **Accountability**:
- Owner: 
- QA/Review: Core team

## **Notes**:

**Comment by elnyry** [comment]
@ndonnan finalized a codebase that can be made Open source, going to create a public repo as follow-up..
