### ISSUE TITLE
QA: Postman tests for error callbacks, endpoints on quoting-service

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#994]
## **Goal**:
As a maintainer of the ML OSS codebase
I want to _validate the quoting-service error end-points and callbacks_ 
so that _error callbacks and endpoints function as expected_

**Tasks**:
- [x] Postman tests for error endpoints on quoting-service are added
- [x] Postman tests for error callbacks for quoting-service are added
- [x] Tests are validating on quoting-service and observations/bugs logged as needed
  - [x] https://github.com/mojaloop/project/issues/1137 - Bug created for content length limit.
- [x] Port these Postman tests in the new GP collection

**Acceptance Criteria**:
- [x] Postman tests for quoting-service error endpoints and callbacks are available that improve quality and help identify regressions

## **Pull Requests**:
- [x] https://github.com/mojaloop/postman/pull/76 (See screenshot in comment for the test run)
- [x] https://github.com/mojaloop/postman/pull/77
- [ ] https://github.com/mojaloop/postman/pull/78

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by vijayg10** [comment]
Guys, working on some other tasks and can not open this issue. Can somebody please pick this? Thanks

**Comment by amarmodus** [comment]
GP test run after PR 76
<img width="1278" alt="Screenshot 2019-12-24 10 58 07" src="https://user-images.githubusercontent.com/53434415/71410372-f34ca080-263c-11ea-9bc1-923a4d4c695a.png">

**Comment by amarmodus** [comment]
https://github.com/mojaloop/postman/pull/78 will be merged as part of https://github.com/mojaloop/project/issues/971
