### ISSUE TITLE
Quoting service not using most recent endpoint

### ISSUE THREAD

**Issue by conradsp** [mojaloop/project#998]
**Summary**:
If a user updates the endpoints for FSPIOP_CALLBACK_URL_QUOTES, it creates multiple records in the central ledger database. It appears that the central ledger finds the correct (most recent) endpoint, but the quoting service picks up the first endpoint that was submitted.

**Tasks**
- [x] End-to-end testing and validation
- [x] Check for possibility of same bug in ALS
       - Validated OK. ALS is not affected. ALS uses the central-ledger's API endpoint to retrieve callback URLs.
-  [x] Add docker-compose artifacts and fix mysql port conflict with central-ledger's mysql container when running locally

**Severity**:
High

**Priority**:
Medium

**Expected Behavior**
The quoting service should read the most recent value for FSPIOP_CALLBACK_URL_QUOTES.

**Steps to Reproduce**
  1. Create an endpoint for FSPIOP_CALLBACK_URL_QUOTES that is invalid (this would simulate a case where the environment has changed for an FSP and they need to update their endpoints)
  2. Create a new (valid) endpoint for FSPIOP_CALLBACK_URL_QUOTES
  3. Call the quoting service. It will load the first entry for FSPIOP_CALLBACK_URL_QUOTES and call this endpoint.

**Specifications**
  - Component (if known): quoting-service
  - Version: 7.4.0
  - Platform: Any
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: @coonradsp

**Notes**:

- Severity when opened:
- Priority when opened:

## Pull Requests ##
- [x] https://github.com/mojaloop/quoting-service/pull/53
- [x] https://github.com/mojaloop/account-lookup-service/pull/97
