### ISSUE TITLE
Error Framework: Adopt Mojaloop SDK Error Handling to quoting-service - 2

### ISSUE THREAD

**Issue by gibaros** [mojaloop/project#999]
## **Goal**:
As a `Hub Operator`, I want to `implement a standard Error Handling framework and apply it to the quoting-service` so that `errors are consistent throughout the Mojaloop stack for both the Switch and the FSPs`.

**Tasks**:
- [x] Integrate the [Error Handler](https://github.com/modusbox/mojaloop-sdk-standard-components/blob/master/src/lib/errors/index.js) from the standard components lib into 
  - [x] quoting-service
- ~[ ] Refactor tests (unit and integration) that use previous Error object in favor of FSPIOPError~
  - ~[ ] Validate that hard coded Errors are being created and replaced with FSPIOErrors~
  - ~[ ] Validate that errors are correct per API Specification, eg:~
https://github.com/mojaloop/central-ledger/blob/8a34ae14129b8a455703af56fa793cd23fcd1ea5/test/integration/handlers/handlers.test.js#L169
- [ ] ~Update Unit Tests~
- [ ] ~Update Integration Tests~

**Acceptance Criteria**:
- [x] Unit Tests pass
- [ ] ~Integration Tests pass~
- [ ] ~Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.~
- [x] Mojaloop SDK Standard Components for Error handling have been integrated into
  - [x] quoting-service
- [x] quoting-service component produces ML API compliant Specification errors

## **Pull Requests**:
- [x] https://github.com/mojaloop/quoting-service/pull/51

## **Follow-up**:
- TBD

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @gibaros 
- QA/Review: @mdebarros @ndonnan @rmothilal
